### ISSUE TITLE
Hidden window? 

### ISSUE THREAD

**Issue by jzelner** [koekeishiya/yabai#100]
Is there a yabai command that can be used to hide or minimize a window and then bring it back as needed? I'd love to be able to have a floating terminal or browser window that I can use quickly and then disappear analogous to cmd-H, but with the ability to also bring it back w/the keyboard without having to cmd-tab to find it?

Thanks!

**Comment by dominiklohmann** [comment]
Some notes on the application switcher:
- When you press <kbd>cmd</kbd> + <kbd>tab</kbd> and navigate to an application with a minimised window, press and hold <kbd>alt</kbd> while releasing <kbd>cmd</kbd> to deminimise windows of the focused application.
- When you press <kbd>cmd</kbd> + <kbd>tab</kbd> and navigate to an application, press <kbd>1</kbd> without releasing <kbd>cmd</kbd> to invoke App Exposé, which shows you all non-hidden and minimised windows.

Regarding your problem: using yabai, you could always float the window and move it to the bottom right corner to effectively hide it:

```sh
# grab the target window id (in this case of the focused window)
target_window="$(yabai -m query --windows --window | jq -re '.id')"

# float the target window and move it to somewhere that's far off to the bottom right
# (regardless of which window is focused at this point)
yabai -m window "${target_window}" --toggle float
yabai -m window "${target_window}" --move abs:10000:10000

# unfloat the target window to tile it again
yabai -m window "${target_window}" --toggle float
```

You can easily create a script for this to create some kind of collection of hidden windows per space.

**Comment by tarasowski** [comment]
There is an easier way to do that. Just drag and drop the window you want to minimize to another space. That's it!

**Comment by marcelarie** [comment]
You have the default macOS command: `cmd + h`.
Then you can use `cmd + shift + tab` to show it again :)

**Comment by bergingwer07** [comment]
I found out that you can hide the current focused window without passing an application name to it:

hide:
```
osascript -e "tell application \"System Events\" to set visible of first application process whose frontmost is true to false"
```

unhide via "cmd + tab" like @marcelarie mentioned:
```
osascript -e "tell application \"System Events\" to key code 48 using {command down}"
```

For myself I´m happy with this solution cause i can map them in my skhdrc to just two shortcuts.

I hope that helps for You!

**Comment by xbladesub** [comment]
I still didn't find right solution

tried to write a tool in swift, but it doesn't seem to work correctly - sometimes I have to run this command twice some reason (I think the problem persist only if apps are on different spaces)

```swift
import AppKit
import ArgumentParser

@main
struct Cycler: ParsableCommand {
    static var configuration = CommandConfiguration(
        abstract: "Simple tool to hide/show macOS apps by name or bundleId",
        version: "1.0.0",
        subcommands: []
    )

    @Argument(help: "Name or bundleId of the app")
    var nameOrId: String

    mutating func run() throws {
        let app = NSWorkspace.shared.runningApplications.first(where: {
            $0.localizedName?.lowercased() == nameOrId.lowercased() || $0.bundleIdentifier == nameOrId
        })

        if let app = app {
            let isHidden = app.isHidden
            if isHidden {
                NSWorkspace.shared.launchApplication(nameOrId)
            } else {
                app.hide()
            }
        } else {
            print("App with name or bundleId: \(nameOrId) not found, trying to launch")
            // try to launch the app
            let launched = NSWorkspace.shared.launchApplication(nameOrId)
            if !launched {
                print("Failed to launch app with name or bundleId: \(nameOrId)")
            }
        }
    }
}
```

**Comment by xbladesub** [comment]
One 100% solution is `rcmd` macOS app which I bought and happy with that

**Comment by douo** [comment]
`skhd -k "cmd -h"` can do the job. ex:
```
# toggle kitty
hyper - return : if [ $(yabai -m query --windows  --window | jq  '.app') = '"kitty"' ]; then skhd -k "cmd - h" ; else open /Applications/kitty.app; fi
```

**Comment by vaygr** [comment]
Coming from bspwm I had this in sxhkd:

```
# hide/show a window
super + {_,shift + }v
        bspc node {-g hidden,$(bspc query -N -n .hidden | tail -n1) -g hidden=off}
```

The idea is to be able to hide a single window with possibility to hide multiple and then unhide them (the more windows created at different times, the more unpredictable unhiding order is).

It seems you can't "unhide" on macOS using yabai, so I had to play with minimize. This is what I came up with to get nearly identical behavior as on bspwm:

```
# minimize
cmd + shift - v : yabai -m window --minimize
# deminimize
cmd + ctrl - v : yabai -m window --deminimize "$(yabai -m query --windows | jq '[.[] | select(."is-minimized" == true) | .id] | last // -1')"
```
