### ISSUE TITLE
Keep floating app on top of other windows

### ISSUE THREAD

**Issue by yar00001** [koekeishiya/yabai#1007]
[probably related to https://github.com/koekeishiya/yabai/issues/527]

I am trying to keep certain applications in floating mode that works as expected. The floating windows though usually get hidden by other "tiled" windows, similar to the screenshot I have attached. I tried to add the following line to my config but that did not help. Is this a bug or is this by design?

![image](https://user-images.githubusercontent.com/2102983/133509539-d14cc8c3-066b-4198-a149-c9fae9b9e2a5.png)

```
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
```

**Comment by yar00001** [comment]
It seems this is because I haven't disabled SIP. Closing this issue.

**Comment by rublev** [comment]
> It seems this is because I haven't disabled SIP. Closing this issue.

I'm actually having the same issue. i have focus_follows_mouse to autoraise and i am unable to get floating windows to always stay above the rest @koekeishiya on latest sonoma 14.8.1 and latest yabai version. SIP also disabled
