### ISSUE TITLE
Random tile arrangement when moving window from one monitor to another

### ISSUE THREAD

**Issue by 0xhmn** [koekeishiya/yabai#1008]
Say I have the initial Window order in my two monitor setup. I want to move the window which is marked with `x` from left screen to right screen. I am using `ctrl + alt - right : yabai -m window --display east` to move windows across screens

![pre](https://user-images.githubusercontent.com/2102983/133535472-ef1c81c8-24b5-465e-ae15-07ea3357a296.png)

After moving the screen, the window moves to the end of the right screen instead of moving to the most left window on the right monitor. I have seen this behavior in different orders (sometimes it moves to the middle, sometimes to the beginning):

![Screen Shot 2021-09-15 at 6 33 20 PM](https://user-images.githubusercontent.com/2102983/133535726-389afbef-97c9-4f8a-bb79-802f1710d957.png)

The other issue is the loss of focus after the window is moved (i.e. the focus after moving the `x` window is moved to the most left window on left monitor)

**Comment by raphaelsmosaic** [comment]
having exactly the same issue

**Comment by koekeishiya** [comment]
Track this in #1096
