### ISSUE TITLE
Predefined Desktop, Apps & Windows sizes

### ISSUE THREAD

**Issue by fedeiglesias** [koekeishiya/yabai#1009]
Is there a way to predefine slot sizes or window spaces for each of the desktops? It happens to me that for example, for the desktop with aliases "communication" I always open the same apps (teams, spark & ​​slack) and the sizes differ. I would like to be able to assign the apps to a specific desktop with sizes already defined, so when I restart the computer it opens everything in its place, ready to work.

Thank you!!

**Comment by dbarria** [comment]
I love this. I need it!

**Comment by pantasio** [comment]
it sounds like only Moon can do this at a moment.

**Comment by koekeishiya** [comment]
You can do this using window rules by making the window unmanaged, and using the grid command to set position and size. Check the docs for syntax.
