### ISSUE TITLE
Focus Has No Effect

### ISSUE THREAD

**Issue by jessebett** [koekeishiya/yabai#101]
I just started trying to use yabai and am currently using the example config files listed in the readme for both yabai and skhd. I am on Mojave and have upgraded to current `brew` installs.

It appears both yabai and skhd are functioning. My windows are being managed and the keyboard shortcuts for actions like moving windows work.

However, actions involving focus, both window and display, do not work. I thought this was an issue with the keyboard shortcut, but executing the command directly has no effect:
`yabai -m window --focus east` 
(where `yabai -m window --focus west` gives `could not locate a westward managed window`)

This is also true for desktop and monitor focusing.

**Comment by dominiklohmann** [comment]
Read the instructions carefully: [&rarr;&nbsp;Wiki: Installing yabai (latest release)](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release))

Your issue is likely that you did not properly install and load the scripting addition for Dock.app. This requires System Integrity Protection to be disabled.

**Comment by jessebett** [comment]
I see that I missed the disable System Integrity Protection. These steps are much clearer in the Wiki than the README. Could I suggest that the wiki be referenced in the readme as the quickstart guide and installation section of the wiki would have been beneficial had I seen them. The requirements section of the README, being distinct from the Install section and more verbose, made this step not obvious to me. 

Thanks for the help, sorry for not reading the instructions more carefully.

**Comment by dominiklohmann** [comment]
I plan to open a PR with a README rework (and some other repo/community stuff) sometime soon. I posted about this a while back in the wiki thread (#5 — if you ever wanna request anything), but I just didn't get around to it yet.

**Comment by jessebett** [comment]
I prematurely closed this issue. I have disabled the System Integrity Protection, and confirmed it with `csrutil status`. I have also reinstalled yabai, uninstalled and reinstalled the scripting additon, and `killall Dock`'d. However, I am still unable to focus windows/desktop/displays.

**Comment by dominiklohmann** [comment]
Well, here's a sneak preview of the requirements section of the reworked README. It's likely that you missed something on that list.

Additionally, you could try to run `yabai --verbose` (requires you to stop the launch agent first using `brew services stop yabai` and to add your Terminal to the Accessibility API access list) to run yabai in debug mode. 

|Requirement|Note|
|-:|:-|
|Operating&nbsp;System|macOS&nbsp;High&nbsp;Sierra&nbsp;10.13.6, macOS&nbsp;Mojave&nbsp;10.14.4+ or macOS&nbsp;Catalina&nbsp;Dev&nbsp;Beta&nbsp;2+ are supported.|
|System&nbsp;Integrity&nbsp;Protection|System Integrity Protection needs to be disabled for **yabai** to inject a scripting addition into Dock.app for controlling windows with functions that require elevated privileges. This enabled control of the window server, which is the sole owner of all window connections.|
|Accessibility&nbsp;API|**yabai** must be given permission to utilize the Accessibility API and will request access upon launch. The aplication must be restarted after access has been granted.|
|Code&nbsp;Signing|When building from source (or installing from HEAD), it is recommended to codesign the binary so it retains its privileges when updated or rebuilt.|
|Mission&nbsp;Control|In System Preferences > Mission Control, the setting "Displays have seperate Spaces" must be enabled.|

**Comment by jessebett** [comment]
Thanks for your help. In addition to my earlier mistake I also needed to update Mojave to .4+
