### ISSUE TITLE
Can't focus relative displays/currently focused display seems fixed?

### ISSUE THREAD

**Issue by neeerp** [koekeishiya/yabai#1010]
I can't seem to get relative focus to work for displays:

I have three displays, the output from `yabai -m query --displays` is as follows (sans uuids)

```
[{
	"id":441002249,
	"index":1,
	"spaces":[1, 2, 3, 4],
	"frame":{
		"x":0.0000,
		"y":0.0000,
		"w":1920.0000,
		"h":1080.0000
	}
},{
	"id":724057871,
	"index":3,
	"spaces":[8, 9, 10],
	"frame":{
		"x":4480.0000,
		"y":0.0000,
		"w":2560.0000,
		"h":1440.0000
	}
},{
	"id":724050320,
	"index":2,
	"spaces":[5, 6, 7],
	"frame":{
		"x":1920.0000,
		"y":0.0000,
		"w":2560.0000,
		"h":1440.0000
	}
}]
```

When I have the rightmost display focused (i.e. display with index 3) and I run `yabai -m display --focus west` in a terminal, I get the response "could not locate a westward display."

My current workaround (which I'm not proud of, lol) is as follows:
```
alt - h : yabai -m window --focus west || \
    (cur=`yabai -m query --displays --display mouse | jq ".index"` && \
        yabai -m window --focus $(yabai -m query --windows --display $((cur - 1)) | jq 'map(select(.visible == 1)) | sort_by(-.frame.x, .frame.y) | first | .id')) || \
    (cur=`yabai -m query --displays --display mouse | jq ".index"` && \
        yabai -m display --focus $((cur - 1)))
```

Unfortunately, this might break if I decide to open the lid of my laptop, which is sitting under the middle monitor and arranged to match.

I've gone and built yabai locally and ran it with `lldb`, and I noticed that in the `display_manager_find_closest_display_in_direction` function when I run the aforementioned command, I've got `source_did=441002249` (i.e. my left-most monitor). Same goes if I do this with my terminal in the middle monitor. Trying to focus east will focus on one of the middle/right monitors, with the source once again being the leftmost display no matter what display was actually being focused).

**Comment by koekeishiya** [comment]
Can you reproduce this on the latest release v4.0.0?
