### ISSUE TITLE
 Active border stopped working.

### ISSUE THREAD

**Issue by ahmed-rezk-dev** [koekeishiya/yabai#1021]
Active border stopped working after making an update of yabai. Only work once when I restart Yabai. Then it disappears after switching between windows and never works back. Only shows a little corner border at the top. Please look at the picture below.

[https://ibb.co/3N36VyS](url)

**Comment by koekeishiya** [comment]
Window borders require the scripting-addition. Make sure it is loaded properly on startup: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
