### ISSUE TITLE
Stack documentation/commands?

### ISSUE THREAD

**Issue by clyra** [koekeishiya/yabai#1026]
Hi all,

I saw in issues/discussion a few messages about the stack feature, but couldn't find the documentation about it or the available commands. Where I can find more about it? thx in advance!

**Comment by anujc4** [comment]
You can find relevant information on [yabai.asciidoc#window](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#64-window).

**Comment by clyra** [comment]
Hi,

Thanks!
