### ISSUE TITLE
Switching focus from a "bsp" type display to a "stack" type display doesn't seem to work properly

### ISSUE THREAD

**Issue by akharrou** [koekeishiya/yabai#1027]
Trying to change focus from a "bsp" display to a "stack" display, for me at least, doesn't seem to work. all I get is a loss of focus then it just hangs with no actual window focused.

Example:
- I have Finder windows on display (monitor) 1, laid out as in "bsp" mode
- I have terminals on display (monitor) 2, laid out in "stack" mode

From display 2, I go "alt-h" to focus on display 1, and it works fine, i.e from "stack" layout display to "bsp" layout display it works. But then when I try to go from display 1 (which is in "bsp" mode) to display 2 (which is in "stack" mode) it just loses focus from windows in display 2, then hangs without focusing anywhere.

---

Here are my `skhd` bindings:

```plaintext
# skhdrc
alt-l : yabai -m display --focus prev
alt-h : yabai -m display --focus next
```

**Comment by akharrou** [comment]
My temporary workaround for the moment is:

```plaintext
# focus [monitor] display
alt-l : \
  space=$(for i in $(yabai -m query --displays --display prev | jq '.spaces[]'); do yabai -m query --spaces | jq -r ".[]|select(.visible==1 and .index==$i)"; done) && \
  case $(<<< $space jq -r '.type') in \
    stack) yabai -m window --focus $(<<< $space jq -r '.["first-window"]') ;; \
      bsp) yabai -m display --focus prev ;; \
  esac
alt-h :  \
  space=$(for i in $(yabai -m query --displays --display next | jq '.spaces[]'); do yabai -m query --spaces | jq -r ".[]|select(.visible==1 and .index==$i)"; done) && \
  case $(<<< $space jq -r '.type') in \
    stack) yabai -m window --focus $(<<< $space jq -r '.["first-window"]') ;; \
      bsp) yabai -m display --focus next ;; \
  esac
```

> the switch is relatively slow though

**Comment by koekeishiya** [comment]
I am unable to reproduce this issue.

I have display 1. in a bsp space with multiple Finder windows.
On display 2. I have multiple Terminal windows in a stack layout.

When I am on display 2, running (using skhd) `yabai -m display --focus prev` works fine, same with `yabai -m display --focus 1`.
When on display 1, running (using skhd) `yabai -m display --focus next` works fine, same with same with `yabai -m display --focus 2`.

**Comment by akharrou** [comment]
> I am unable to reproduce this issue.
> 
> I have display 1. in a bsp space with multiple Finder windows. On display 2. I have multiple Terminal windows in a stack layout.
> 
> When I am on display 2, running (using skhd) `yabai -m display --focus prev` works fine, same with `yabai -m display --focus 1`. When on display 1, running (using skhd) `yabai -m display --focus next` works fine, same with same with `yabai -m display --focus 2`.

Weird, I don't know what else I might be doing that's causing this. Ok thanks anyways.
