### ISSUE TITLE
Shortcut to Manage/Unmanage window

### ISSUE THREAD

**Issue by mavaras** [koekeishiya/yabai#1032]
Is there some command to make a window float/tiled?
Like doing `manage=off` in a Yabai rule but with a shortcut.
Maybe I want to move a window freely and then having it tied, does Yabai has a way to shortcut that?

**Comment by antoni-k** [comment]
Just to clarify, Yabai doesn't provide any shortcuts on its own, and that's what the [companion software skhd](https://github.com/koekeishiya/skhd) is for. The reply above is a possible way that you can implement this behavior.

> If you are using skhd you can add a binding like this:
> 
> ```cs
> alt - t : yabai -m window --toggle float
> ```
