### ISSUE TITLE
Space Index Changed Signal

### ISSUE THREAD

**Issue by FelixKratz** [koekeishiya/yabai#1034]
I am currently working on a dynamic space indicator script for [SketchyBar](https://github.com/FelixKratz/SketchyBar) and I noticed, that it is currently not possible to get a signal for space index change. Am I missing something?

The motive is that I want to subscribe to yabai events in sketchybar, rather than polling for change, and when I swap spaces
there is no event that I can subscribe to, thus the swapped spaces only appear in sketchybar once the space refresh is triggered from another event.

**Comment by xiamaz** [comment]
How did you fix your problem?

**Comment by FelixKratz** [comment]
I created some scripts to call for space actions and trigger a custom event from within those:
[yabai_actions.zip](https://github.com/koekeishiya/yabai/files/7784958/yabai_actions.zip)
