### ISSUE TITLE
Yabai broken after macOs 12.0.1 update

### ISSUE THREAD

**Issue by sabaodi** [koekeishiya/yabai#1035]
After installing the latest macOs update (12.0.1), yabai restart everytime I open a new window (e.g., chrome, finder, vlc, etc.) and rearrange the windows randomly. 
Any solution?
I've installed the latest version of yabai.

**Comment by ecriminal** [comment]
> Oh boy! Wtf I've done. Now I'm gonna suffer without a tiling manager... Maybe I should downgrade to Big Sur.

I feel the pain brother...

**Comment by enku-io** [comment]
> > > > You can use https://github.com/donaldguy/yabai instead
> > > 
> > > 
> > > Any explanation on what changed and how it's working there? Change could be applied to yabai.
> > 
> > 
> > If you tell me how to install yabai from the branch https://github.com/donaldguy/yabai I can try today and let you know.
> 
> I've tried right now. I downloaded the released version (v3.4.0+donaldguy) and run the binary on a shell (First, you have to stop the previous version of yabai running on brew services...). It work like a charm, no more crash!!!
> 
> Here's a video, MacOs Monterey 12.0.1 with yabai running flawless:
> 
>  screen.mp4

Would you mind sharing the steps you took to install the donandguy/yabai fork? Thanks.

**Comment by yiluoegit** [comment]
>我无法让'yabai-m space --focus 3（或任何其他）'工作。是因为脚本？me too

**Comment by issmirnov** [comment]
There's some chatter on https://github.com/koekeishiya/yabai/issues/1054 - it's a bit convoluted, but we are able to get it working. I'm running M1 Max on Monterety with Yabai and everything works. See that other thread for details.

**Comment by abhatthal** [comment]
Hope this helps. https://github.com/koekeishiya/yabai/issues/1131

Running Yabai on macOS Monterey 12.1 (Intel) and only thing that isn't working for me is transparency.
Neither the stable nor dev installations worked, so I needed to use a specific commit where it was working for me.

**Comment by sabaodi** [comment]
This video/tutorial seem solve the problem: https://www.youtube.com/watch?v=WJrtA6SKGXU

**Comment by koekeishiya** [comment]
The above video uses an unofficial fork; use at your own discretion.
Read my post in #1054 for instruction running off my branch.
