### ISSUE TITLE
minimize minimizes all windows of application

### ISSUE THREAD

**Issue by basbebe** [koekeishiya/yabai#1037]
I'm using kitty as a scratchpad terminal.

However, when I try to minimize the terminal window by id (queried with window title), _all_ my kitty windows will be minimized.

If I do this within a kitty window, only the window with the given id is minimized.
If I do the same with a shortcut through `skhd`, all kitty windows will be closed.

I currently circumvent this by using a dedicated kitty instance, but this brings other problems (e.g. as soon as I have several scratchpads for specific uses…).

Any idea what could cause this and if there is anything to do about it?

thanks!

```bash
#!/bin/sh

kitty_cmd="kitty \
  --config="$HOME/.config/kitty/kitty.conf" \
  --config="$HOME/.config/kitty/themes/gruvbox-$(fish -c 'echo $OS_THEME').conf"
  --override macos_hide_from_tasks=yes \
  --single-instance \
  --instance-group=scratchpad \
  --listen-on=unix:/tmp/kitty_listen_scratchpad"

kitty_launch="kitty @ --to=unix:/tmp/kitty_listen_scratchpad \
  launch \
  --env SHELL=/usr/local/bin/fish \
  --title=$SCRATCHPAD_TITLE \
  --cwd=$HOME \
  --type=os-window"

scratchpad_id=$(yabai -m query --windows | jq --arg title "$SCRATCHPAD_TITLE" -c '[.[] | select(.title==$title).id'][0])

is_focused()
{
  [[ $(yabai -m query --windows --window $1 | jq '.focused') -eq  1 ]]
}
is_minimized()
{
  [[ $(yabai -m query --windows --window $1 | jq '.minimized') -eq 1 ]]
}

if [[ "$scratchpad_id" -lt 1 ]]; then
  $kitty_launch "${@}" || \
  $kitty_cmd $kitty_launch "${@}"
else
  current_space=$(yabai -m query --spaces --space | jq '.index')
  if is_minimized $scratchpad_id ; then
    yabai -m window "$scratchpad_id" --space "$current_space"
    yabai -m window --focus "$scratchpad_id"
  else
    if is_focused $scratchpad_id ; then
      yabai -m window "$scratchpad_id" --minimize
    else
      yabai -m window --focus "$scratchpad_id"
    fi
  fi
fi

```

**Comment by koekeishiya** [comment]
Not sure why this would happen. Yabai minimises a window by calling the appropriate action on the window using macOS accessibility API. This might be better to ask in Kitty's repo, if you still experience this issue.
