### ISSUE TITLE
Would there be benfits to using non-native spaces?

### ISSUE THREAD

**Issue by jerbaroo** [koekeishiya/yabai#1039]
Currently two downsides of Apple's native spaces: 
- somewhat slow to navigate (compared to near-instant when using a window manager on Linux on the same machine)
- requires disabling SIP to create/destroy spaces

I am wondering if it would be feasible to mimic the native spaces system instead of using the native spaces system? Potential benefits could be faster application/space switching and not requiring SIP to be disabled?

The way this would work is that switching to some logical/yabai space Sn would not use apple's native spaces but instead just brings the windows within the logical space Sn into view and hides whatever other windows were on the screen.

Logical spaces, natice spaces and application windows would be related as follows:

```js
// Each monitor displays a single native space.
// Each monitor may contain multiple logical spaces, one of which is being displayed on the monitor.
Monitor1 --> NativeSpace1 --> { LogicalSpace1: [Window1, Window2], LogicalSpace2: [Window3] }
Monitor2 --> NativeSpace2 --> { LogicalSpace3: [Window4, Window5], LogicalSpace4: [] }

// Keep track of what logical space is currently being displayed on each monitor.
activeSpaces = { Monitor1 : LogicalSpace1, Monitor2 : LogicalSpace4 }
```

**Comment by hatunike** [comment]
To your first point :

`defaults write com.apple.dock workspaces-swoosh-animation-off -bool YES`

and then do :

`killall Dock`

That dramatically increases the speed of switching spaces.

It doesn't solve your 2nd point though.

**Comment by SxC97** [comment]
You can enable faster space switching with the `defaults` command above and most of the tiling features work without disabling SIP. 

The only reason I could see implementing non-native spaces would be if we could implement a "tags" system instead of spaces like dwm.

Although, this might be out of scope for this project. Maybe a fork would be better?

**Comment by joshtwo** [comment]
> To your first point :
> 
> `defaults write com.apple.dock workspaces-swoosh-animation-off -bool YES`
> 
> and then do :
> 
> `killall Dock`
> 
> That dramatically increases the speed of switching spaces.
> 
> It doesn't solve your 2nd point though.

Is this supposed to disable the animation for swiping to other spaces using the 3 finger gesture? I ran that command a while ago and it's still happening.

**Comment by SxC97** [comment]
I was running into the same issue, so I mapped a 4 finger swipe left or right to yabai’s fast focus keyboard shortcut (ctrl + arrow key for me).

**Comment by collinhundley** [comment]
@SxC97 is the `defaults` command above working for you? It seems to have no effect for me on Monterey, and some people online say it hasn't worked since OSX 10.6.

**Comment by SxC97** [comment]
Yes, it looks like this command is no longer working. I had implemented the BTT workaround mentioned above and had simply forgotten about it and assumed that I had used the `defaults` command instead in my first comment. I apologize for the confusion 😁 I have just updated my comments.

**Comment by collinhundley** [comment]
@SxC97 can you explain how the fast focus command works with SIP still enabled? I haven't had any luck with that.

**Comment by koekeishiya** [comment]
This is not really in the scope of what I want yabai to be, as of now anyway. In general it should be technically possible to make something like this, if someone is interested in giving it an attempt on their own.
