### ISSUE TITLE
Keep qlmanage on top of other windows 

### ISSUE THREAD

**Issue by MiuKaShi** [koekeishiya/yabai#1040]
Hi,

I use qlmange for quick view. I want the quick view window to be the topmost windows, but I don't know how to set the rules in yabai becuase yabai seemns to can not capture the quick view windows information and the qlmanage is a terminal command not app.

I have try

yabai -m config window_topmost on

but failed.

can anyone help me to slove this problem

thx~

**Comment by piersolenski** [comment]
@MiuKaShi did you find a solution for this in the end?

**Comment by koekeishiya** [comment]
Should work fine in v6.0.0
