### ISSUE TITLE
strange behavior when unminimizing my terminal

### ISSUE THREAD

**Issue by danielporterda** [koekeishiya/yabai#1041]
When I minimize my terminal and then unminimize it, I get a very strange configuration of windows.

![Before unminimization](https://user-images.githubusercontent.com/75383985/140378139-be89cf8b-de6f-4e87-a526-9479aab3cdad.png)
![after unminimization](https://user-images.githubusercontent.com/75383985/140378149-0224f0f1-c3a5-4d49-8969-759d9c43b916.png)

This doesn't happen all of the time, and seems to happen after I've created a new tab in my terminal by using `ctrl+t`. 

Additionally, when I hit `ctrl+t` in my terminal, that also resizes my windows in somewhat pathological way:

![after creating a new tab in my terminal with "ctrl+t"](https://user-images.githubusercontent.com/75383985/140378839-6bb35ee4-c092-4428-a726-0e428f939e9f.png)

I'm using plain jane OSX terminal running big sur. Pasting in "About This Mac": ![about this computer](https://user-images.githubusercontent.com/75383985/140379116-f8da24df-b02b-4fee-b2aa-059d23f596c1.png)

**Comment by danielporterda** [comment]
Notably I haven't disabled SIP b/c it's a work machine

**Comment by koekeishiya** [comment]
Tabs are not supported due to lack of macOS APIs. See #68

**Comment by danielporterda** [comment]
Aha, thanks. Interesting API shortcomings.
