### ISSUE TITLE
Creating new window resets zoom-fullscreen state for the current window

### ISSUE THREAD

**Issue by kvaps** [koekeishiya/yabai#1044]
If you have current window set to fullscreen:

```
yabai -m window --toggle zoom-fullscreen
```

When creating a new window, the fullscreen mode for the old window will be reseted.

**Comment by Strafos** [comment]
This has been a problem for me too. Is it possible to create a rule that always sets certain apps to zoom-fullscreen? Looks like that option only exists for native fullscreen.

**Comment by koekeishiya** [comment]
Duplicate of https://github.com/koekeishiya/yabai/issues/864
