### ISSUE TITLE
Unable to install scripting additions on MacOS Monterey 12.0.1

### ISSUE THREAD

**Issue by crackonosh** [koekeishiya/yabai#1048]
I've installed new version of OS to my MacBook Pro and after that the scripting addition stopped working. I've tried to reinstall yabai and install the scripting additions once again, but when I run `sudo yabai --install-sa` I get `2` return code from the script.

**Comment by BR00l** [comment]
Give a look at https://github.com/koekeishiya/yabai/issues/725#issuecomment-968104277

SIP has to be disabled for now.

Im also waiting for a solution for this, I think a lot more people.

**Comment by crackonosh** [comment]
> SIP has to be disabled for now.

The problem is I have SIP disabled. I've tried to enable it without debug and FS, but that didn't work nor did work disabling it completely. 
(To clarify for [#725 (comment)](https://github.com/koekeishiya/yabai/issues/725#issuecomment-968104277) I'm trying to install the normal brew version, should I try to build from source the `the-future` branch even when I have Intel?)

**Comment by BR00l** [comment]
I think we must wait a bit more for more clear instructions. Im also not too relevant with building sadly, and I cant help you a lot with those questions sadly...

**Comment by crackonosh** [comment]
Yeah I guess we'll have wait until it's fixed. So I'm closing this issue
