### ISSUE TITLE
Cannot drag window to another display while Mission Control is open

### ISSUE THREAD

**Issue by eavesjump** [koekeishiya/yabai#1051]
Reliable repro of this bug:

1. Hit the Mission Control key to see all of your Desktops
2. Drag and drop a window from one display up onto any hidden Desktop on the Mission Control bar on a different display
3. Exit Mission Control (without focusing that same hidden Desktop)

The dragged window instantly moves back to its original Desktop instead of staying on the hidden Desktop you dropped it on to.

&nbsp;

Related but fixed issue for non-hidden Desktops: https://github.com/koekeishiya/yabai/issues/103

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/issues/820

Fixed on the-future branch, which will be the upcoming release.

**Comment by eavesjump** [comment]
Ah, thanks. Sorry for the duplicate.

&nbsp;

(I did search, just didn't find it. Both [github](https://github.com/koekeishiya/yabai/search?q=can%27t+move+windows+between+external+displays+with+mouse&type=issues) and [google](https://www.google.com/search?q=can't+move+windows+between+external+displays+with+mouse+site%3Ahttps%3A%2F%2Fgithub.com%2Fkoekeishiya%2Fyabai%2F) searches miss that issue even if you search its verbatim title but just replace "Issue" with "Can't". Wonder if that's a bug.)
