### ISSUE TITLE
SLSGetWindowBounds gives stale readings

### ISSUE THREAD

**Issue by residentsummer** [koekeishiya/yabai#1055]
I was doing some improvements of how mff works for my own convenience (#808 plus some more cases) and noticed that sometimes cursor wouldn't follow the window after a swap. Turned out that early exit in `window_manager_center_mouse` when cursor is already inside window bounds sometimes triggers incorrectly due to `CGRect window_frame(struct window *)` returning stale data.

I've added some logging statements to illustrate the issue. What I did is swapping kitty window with its right neighbor and back.

```
==> /usr/local/var/log/yabai/yabai.out.log <==
EVENT_HANDLER_DAEMON_MESSAGE: window --swap east

==> /usr/local/var/log/yabai/yabai.err.log <==
=== ACTING WINDOW: vim .config/yabai/yabairc 557
=== TARGET WINDOW: tail -f /usr/local/var/log/yabai/yabai.* 610
=== BEFORE SWAP: ax_frame is (   3,   25) <-> ( 959, 1077)
=== BEFORE SWAP:    frame is (   3,   25) <-> ( 959, 1077)
===  AFTER SWAP: ax_frame is ( 961,   25) <-> (1917, 1077)
===  AFTER SWAP:    frame is ( 961,   25) <-> (1917, 1077)
=== REFOCUS WINDOW: vim .config/yabai/yabairc 557

==> /usr/local/var/log/yabai/yabai.out.log <==
EVENT_HANDLER_WINDOW_MOVED: kitty 610
EVENT_HANDLER_WINDOW_MOVED: kitty 557

-- here goes swap back --

EVENT_HANDLER_DAEMON_MESSAGE: window --swap west

==> /usr/local/var/log/yabai/yabai.err.log <==
=== ACTING WINDOW: vim .config/yabai/yabairc 557
=== TARGET WINDOW: tail -f /usr/local/var/log/yabai/yabai.* 610
=== BEFORE SWAP: ax_frame is ( 961,   25) <-> (1917, 1077)
=== BEFORE SWAP:    frame is ( 961,   25) <-> (1917, 1077)
===  AFTER SWAP: ax_frame is (   3,   25) <-> ( 959, 1077)
===  AFTER SWAP:    frame is ( 961,   25) <-> (1917, 1077)
=== REFOCUS WINDOW: vim .config/yabai/yabairc 557

==> /usr/local/var/log/yabai/yabai.out.log <==
EVENT_HANDLER_WINDOW_MOVED: kitty 610
EVENT_HANDLER_WINDOW_MOVED: kitty 557
```

As you can see, `SLSGetWindowBounds` is sometimes stuck in the past, even after AX api returned correct values.

Changing `window_manager_center_mouse` to use `window_ax_frame` fixes the issue.

So the question is what are the downsides of using Accessibility APIs vs SkyLight?

I'm on rMBP + external display; Mojave (10.14.6); SIP fully enabled, not using SA. I've used [this patch](https://gist.github.com/residentsummer/e61bdfa663a5763cceab8b104c412281) @ 8777db4 to produce the logs.

**Comment by koekeishiya** [comment]
`SLSGetWindowBounds` is no longer a thing in the new version for exactly that reason. The primary motivation before is that the SLS version was more responsive, as it does not need to take a global mutex like the accessibility API does.
The new version of yabai just caches the window frame instead.

**Comment by residentsummer** [comment]
OK, I see. Thank you for clarification.
