### ISSUE TITLE
Monterey : borders have (internal) shadow

### ISSUE THREAD

**Issue by rougier** [koekeishiya/yabai#1056]
I know borders are not supposed to work (yet) with Monterey but they are kind of working for me. One problem though is that they somehow add an internal shadow over the window as shown on the screenshot. Left is with yabai off, right is with yabai on (I manually cropped the external drop shadow to better highlight the problem). I'm not asking for a fix, but maybe this information is important to help debug borders.

![screenshot](https://user-images.githubusercontent.com/327203/142671654-f12ce925-4544-42d7-ba59-bfc1a46d1cf5.png)

**Comment by cxa** [comment]
It's a known issue. If you want some workaround, just check my [fork](https://github.com/cxa/yabai).

**Comment by rougier** [comment]
ok, thanks. Didn't noticed it before.

**Comment by rougier** [comment]
After searching, it seems the problem has been solved by this [commit](https://github.com/koekeishiya/yabai/commit/cc7bb9be85ad70dddc21b376f9f9d6bfb60c7945) but it somehow re-appears in latest HEAD (or even before) on my machine. Can anyone confirm the behavior?

**Comment by cxa** [comment]
I can confirm that this fix is not for Monterey, `kCGSDisableShadowTagBit` does not work anymore.

**Comment by koekeishiya** [comment]
update to v4.0.0.

**Comment by rougier** [comment]
Shadow has been reduced but I think it is still here. Left is border by OSX (Increase contrast), right is yabai (HEAD):

<img width="268" alt="screenshot" src="https://user-images.githubusercontent.com/327203/159174959-ea53462b-0893-413c-923b-19dee44976cb.png">

**Comment by koekeishiya** [comment]
Fixed in v4.0.1.
