### ISSUE TITLE
Yabai ignoring some config parameters like window_shadow et al.

### ISSUE THREAD

**Issue by cxor** [koekeishiya/yabai#1059]
I use macOS Monterey on a Mac Mini 2018 (so, intel), and I know yabai is still not supported for it. I still think that pointing out to the developer the current issue can be useful since I couldn't find some similar report on the github issue tracker.

My yabai version is installed via "brew install koekeishiya/formulae/yabai --HEAD".
Some config parameters are completely ignored. The ones that I have found to be broken after some pretty quick testing are window_shadow (on, off and float do not make any difference: the shadow is always present), as well as active_window_opacity and normal_window_opacity (windows are always fully opaque even then window_opacity is on and their opacity value are set to something like 0.5).

Yabai is SO great, I hope developers can restore its amazing capabilities soon. 
Keep up the incredible work.

**Comment by obsidianical** [comment]
I have the same problem on Big Sur (11.2.3), yesterday it worked, now it doesn't anymore. Thought i was doing something wrong.

**Comment by obsidianical** [comment]
Okay update: solved it.

The problem for me was, that the scripting addition wasn't loaded, so that may work for you too.

**Comment by cxor** [comment]
You are right, the scripting addition does not load automatically, even when you add the required commands in the rc file, as suggested in the documentation. I added the sudoers file to use passwordless yabai, but that seems to not work. Maybe I have to recheck all the things.

**Comment by clementaudic** [comment]
To load the scripting addition, run `sudo yabai --load-sa`.
