### ISSUE TITLE
System-wide slowdowns with high input polling rate

### ISSUE THREAD

**Issue by peppy** [koekeishiya/yabai#1061]
With a 1000hz HID mouse device, system-wide slowdowns are experienced while moving the mouse with `yabai` running. Testing on latest HEAD (5317b16)

System specs:

![20211124 111059 (System Information)](https://user-images.githubusercontent.com/191335/143158811-519d61c5-09ba-4ce2-a8b9-55334fe46c2b.png)

Pay attention to the update frame rate of the dock when `yabai` is running:

https://user-images.githubusercontent.com/191335/143159131-24c1bbbb-c93b-4233-9d61-d096257ff8fd.mp4

This kind of slowdown can also be seen in window dragging and most other UI based operations. Seems like some hook is taking far too long to process mouse events. I've tried removing all mouse-related lines from my config and it doesn't help.

Note that this is not visible with a 125hz polling mouse, but CPU usage is still higher than expected on `WindowServer` when moving the mouse (around 20-30% of a core overhead when `yabai` is running).

[Sample of WindowServer.txt](https://github.com/koekeishiya/yabai/files/7592246/Sample.of.WindowServer.txt)

**Comment by peppy** [comment]
Re-testing on 12.1 Beta (21C5039b), this no longer reproduces.

I'm not sure if a restart alone may have been enough to fix this. There's also potential that the scripting additions could be responsible in some way (on the beta they no longer work, suggesting they may not be applying as they usually would).

**Comment by koekeishiya** [comment]
No clue how to make this faster. It's not really possible to do less work than is currently happening: https://github.com/koekeishiya/yabai/blob/master/src/event_tap.c#L17

We read the event and queue it up for processing, so the callback for the WindowServer returns almost instantenously.

**Comment by peppy** [comment]
Thanks for confirmation. I'm guessing this was either something else on the system adding overhead, or it was fixed in one of the subsequent beta releases of macOS. I probably should have tested after a restart before upgrading to a newer beta, but oh well.

**Comment by peppy** [comment]
@koekeishiya I am currently able to reproduce this after switching to 12.3. Can I help potentially debug what's going on here?

https://user-images.githubusercontent.com/191335/158754769-ead02012-e3ec-4bfe-b3e2-5d38cdaa33b7.mp4

This is noticeable in not just the dock (which you can notice has its animation lagging behind the mouse when `yabai` is running) but also any other application.

**Comment by koekeishiya** [comment]
Hmm my Dock doesn't animate like that and I don't see a setting for it in System Preferences. Do you happen to know I can enable that?

As far as that stuck yabai process goes, I can't say I've experienced that, but it seems to be a zombie process -- which is also why it can't be killed directly. You can send the SIGCHLD signal to the parent process to reap the zombie.

Can you reproduce the issue when `focus_follows_mouse` is set to off?

**Comment by peppy** [comment]
> Hmm my Dock doesn't animate like that and I don't see a setting for it in System Preferences. Do you happen to know I can enable that?

It's the "magnification" setting:

![System Preferences 2022-03-17 at 11 28 04](https://user-images.githubusercontent.com/191335/158799463-bdebbb45-53a8-4d6f-9e79-7a5db5da77a8.png)

> As far as that stuck yabai process goes, I can't say I've experienced that, but it seems to be a zombie process -- which is also why it can't be killed directly. You can send the SIGCHLD signal to the parent process to reap the zombie.

Weirdly it looks like the zombie process is already gone, so we can rule that out.

> Can you reproduce the issue when `focus_follows_mouse` is set to off?

I actually didn't have this on in the first place. I was using `mouse_follows_focus`, but turning that off does not have a noticeable effect.

**Comment by koekeishiya** [comment]
I realised I don't actually have a usb-c mouse to test this with, but luckily the code that would cause this to happen is fairly isolated. There are a couple of ways to approach debugging this, so let's try a couple of things to isolate the issue. I assume you are able to build from source to follow these.

1. If you comment/remove the following line and recompile, I would expect the issue to disappear: https://github.com/koekeishiya/yabai/blob/master/src/yabai.c#L319

Assuming the issue stopped, revert that change, and continue below.

2. The event handler for mouse events can be found here: https://github.com/koekeishiya/yabai/blob/master/src/event_tap.c
Comment out all of the event_loop_post statements and recompile; I would expect the issue to be gone.

Add them back in one by one, recompile in-between to see if there is a specific one that causes the issue to appear when enabled.

3. If you are able to identify which event causes it, the actual code for these events are found in: https://github.com/koekeishiya/yabai/blob/master/src/event.c -- search for `EVENT_HANDLER_MOUSE_`

You could then try to binary-search the issue within said event, to track down the offending section.

I think that is the best I can do without actually being able to reproduce it myself.

**Comment by peppy** [comment]
Thanks for the extra info. I immediately tried step 1 and while it does improve the scenario, I have noticed that *even without* yabai running, the system event queue seems to get further and further behind the longer i am moving the mouse, suggesting it is more likely than not going to be a system level issue and yabai is only making it negligibly worse by adding one extra callback.

Last time a restart resolved this for me, and I think it may this time as well, but am hesitant to do so as I may not be able to repro again.

I'll work through this and report back if I find anything of use.

**Comment by peppy** [comment]
I'm seeing this occur again. A restart does fix it, but after some time it gets worse until I am forced to reboot.

The easiest way for me to test this is using Cmd-Shift-4 screenshot selection, when it will lag behind my mouse cursor, but this is also noticeable in things like dragging files in finder, interacting with VMs and some other windows.

https://user-images.githubusercontent.com/191335/204195760-52fb99c3-17f2-41cf-9588-3e112832c3af.mp4

Interestingly, even after killing yabai it still is non-zero latency, suggesting there's more going on here. Just thought I'd document this as I try and get to the bottom of this.
