### ISSUE TITLE
Bug: A new window of the same application will be invisible and crash the app (Monterey 12.0.1, yabai-v4.0.0)

### ISSUE THREAD

**Issue by TonyWu20** [koekeishiya/yabai#1063]
When I created another window of the current application, e.g. another ```Chrome``` window, the new window is invisible, but the space is allocated. After closing the previous visible window, the app will be out of respond and a force-quit is needed.
<img width="961" alt="image" src="https://user-images.githubusercontent.com/45414421/143378364-9eb7c1c8-0780-4025-854f-74068a3d5d79.png">

Note: this seems to be dependent on the applications. So far, I have met this with ```Chrome``` and ```Skim```. ```Safari``` seems fine with it.

**Comment by Mopip77** [comment]
I encountered it too. I was thinking it is a bug from Chrome.

And I noticed that the bug only occurs when window_border configuration is enabled.

**Comment by joshtwo** [comment]
I dealt with that a lot with Firefox. I had to make all new windows open as tabs to deal with it. Now for some reason Firefox doesn't tile anymore so it's somewhat irrelevant.

**Comment by TonyWu20** [comment]
> I encountered it too. I was thinking it is a bug from Chrome.
> 
> And I noticed that the bug only occurs when window_border configuration is enabled.

Exactly! I turned off `window_border` and then the problems are gone.

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/issues/1054#issue-1058384717

> Known issues:

> Window borders are broken; they cause random applications to freeze and also sometimes crashes the WindowServer. I have not found a pattern to this behaviour. Most likely borders will be disabled for Monterey until a solution is found. Limelight needs to be updated for Monterey; I'll look into that at some point, but no ETA.

Not sure why I bother writing anymore; people don't read anyway.

**Comment by TonyWu20** [comment]
> [#1054 (comment)](https://github.com/koekeishiya/yabai/issues/1054#issue-1058384717)
> 
> > Known issues:
> 
> > Window borders are broken; they cause random applications to freeze and also sometimes crashes the WindowServer. I have not found a pattern to this behaviour. Most likely borders will be disabled for Monterey until a solution is found. Limelight needs to be updated for Monterey; I'll look into that at some point, but no ETA.
> 
> Not sure why I bother writing anymore; people don't read anyway.

Sorry for my carelessness when reading this post! I will close this.

**Comment by koekeishiya** [comment]
@TonyWu20 

I don't mean to be rude, sorry.
 Obviously this is not the best format and I know that it's easy to miss minor details such as this.
I try to help, but it gets exhausting is all.

**Comment by typkrft** [comment]
After updating yabai to head with brew I have this issue regardless of whether borders are on or off with firefox(stable/beta/nightly) or chromium. 
Occasionally I get what appears to be a fully interactive miniature window, but usually it's invisible.

`/Applications/Firefox.app/Contents/MacOS/firefox-bin --new-window` works however.

```
Macbook Pro (16-inch, 2021)
Chip Apple M1 Max
Memory 32GB
Version 12.1 (21C52)
```
[yabairc](https://github.com/typkrft/dots/blob/main/yabai/yabairc)
