### ISSUE TITLE
Yabai 4.0. Application not allocated to assigned space on launch

### ISSUE THREAD

**Issue by beatslikeahelix** [koekeishiya/yabai#1066]
I am facing an issue wherein an application is not moved to its assigned space -- as dictated in .yabairc -- when first launched. Yabai needs to be restarted before the window is moved to the space in which it belongs. This process can be tedious as it forces a reshuffle of all windows in all spaces.

I'm using an Intel 2016 MBP on Monterey.
Anyone else facing this issue?

P.S. Much love for the Monterey support.

**Comment by koekeishiya** [comment]
Is this still an issue in the released v4.0.0?

**Comment by koekeishiya** [comment]
Aight, closing this one then. Feel free to create a new issue if you should experience this again.
