### ISSUE TITLE
Allow `window_placement` configuration per display

### ISSUE THREAD

**Issue by guildencrantz** [koekeishiya/yabai#1068]
It'd be nice if `window_placement` could be configured per display: This would allow displays on the left to be set to `window_placement first_child` while displays to the right can be left at `window_placement second_child` (so new windows are created on the "outside" no matter the display).

Alternatively: Allowing `mirror y-axis` to be a sticky configuration per display would also (probably more correctly, since it doesn't switch the top/bottom behavior) solves this issue (though that seems to be a more complicated fix?).

**Comment by koekeishiya** [comment]
I think #1096  would solve the issue you are having?

**Comment by koekeishiya** [comment]
Closing as duplicate of #1096
