### ISSUE TITLE
how to touch a space bar?

### ISSUE THREAD

**Issue by taigacute** [koekeishiya/yabai#107]
HI   thanks for your greate work!  i am new begginer of yabai ..i saw your pic has too many space bar.  i only have one . by the way i use your config .  i create these rule 
```
# window rules
yabai -m rule --add app=Google Chrome space=2
yabai -m rule --add app=Emacs space=3
yabai -m rule --add app=网易云音乐 space=3
```
and i use this keymap the skhdrc from your dotfiles.`shift+cmd -n` but nothing happend
![1](https://user-images.githubusercontent.com/41671631/60897179-333fe700-a29a-11e9-9932-07cfcd351610.png)

**Comment by koekeishiya** [comment]
The icons in the bar reflect how many macOS Spaces are available to you. You can manage spaces by activating *Mission Control* (default: four-finger swipe up on the Trackpad) or by using the *space* commands provided with *yabai*: https://github.com/koekeishiya/yabai/wiki/Commands#space-commands

If you are new to macOS Spaces, maybe give this a read: https://appleinsider.com/articles/18/10/12/how-to-use-spaces-apples-mostly-ignored-macos-mojave-productivity-feature

**Comment by taigacute** [comment]
very thanks  i got it `Mission Control`

**Comment by taigacute** [comment]
by the way  i use this config . but when i type the keymap  nothing happend . did i missed something ?
```
# create desktop, move window and follow focus
shift + cmd - n : yabai -m space --create;\
                  id=$(yabai -m query --displays --display | grep "spaces");\
                  yabai -m window --space $(echo ${id:10:${#id}-10});\
                  yabai -m space --focus $(echo ${id:10:${#id}-10})

# create desktop and follow focus
cmd + alt - n : yabai -m space --create;\
                id=$(yabai -m query --displays --display | grep "spaces");\
                yabai -m space --focus $(echo ${id:10:${#id}-10})
```

**Comment by dominiklohmann** [comment]
Make sure you have System Integrity Protection disabled and the scripting addition installed. Check the wiki for instructions on each.

**Comment by taigacute** [comment]
thanks for your reply.  type `csrutil status` i got this
![image](https://user-images.githubusercontent.com/41671631/60976139-c3942f80-a35f-11e9-8b0c-0ca47c756f28.png)

**Comment by nuynait** [comment]
Did you install `skhd`?

```
brew install koekeishiya/formulae/skhd
brew services start skhd
```

**Comment by taigacute** [comment]
i installed , i can use some kemap in .skhdrc.

**Comment by koekeishiya** [comment]
Did you install the scripting addition after disabling system integrity protection?

`sudo yabai --install-sa`

I will assume this is the problem as *skhd* works properly as per your last comment.

**Comment by glepnir** [comment]
@koekeishiya  hi there. I install yabai in my new mbp. i found these keys can't work. I can confirm disable sip and install sa.
```
ctrl + alt - n : yabai -m space --create
ctrl + alt - d : yabai -m space --destroy
```
