### ISSUE TITLE
Spaces follow main space

### ISSUE THREAD

**Issue by 24unix** [koekeishiya/yabai#1083]
Hi,

as yabai wants Displays have separate Spaces :-( I had a workaround with TotalSpaces II for grouping all displays to one desktop.
But they gave up on Monterey :(

Now I switched back to skhd for changing my main spaces like so:

`ctrl - 1 : yabai -m space --focus 1
ctrl - 2 : yabai -m space --focus 2
ctrl - 3 : yabai -m space --focus 3
ctrl - 4 : yabai -m space --focus 4
ctrl - 5 : yabai -m space --focus 5
ctrl - 6 : yabai -m space --focus 6
ctrl - 7 : yabai -m space --focus 7
ctrl - 8 : yabai -m space --focus 7
ctrl - 9 : yabai -m space --focus 9
`

Now I want yabai to react when the space on the main display changes by any means (Mission Control, cli or my Menubar-Applet) that both external displays also change spaces.

`function space_changed {

	current_space=$(yabai -m query --spaces --display 1 | jq 'map(select(."has-focus" == true))[-1].index')

	case $current_space in
	1)
		yabai -m space --focus 10
		yabai -m space --focus 19
		;;
	2)
		yabai -m space --focus 11
		yabai -m space --focus 20
		;;
	3)
		yabai -m space --focus 12
		yabai -m space --focus 21
		;;
	4)
		yabai -m space --focus 13
		yabai -m space --focus 22
		;;
	5)
		yabai -m space --focus 14
		yabai -m space --focus 23
		;;
	6)
		yabai -m space --focus 15
		yabai -m space --focus 24
		;;
	7)
		yabai -m space --focus 16
		yabai -m space --focus 25
		;;
	8)
		yabai -m space --focus 17
		yabai -m space --focus 26
		;;
	9)
		yabai -m space --focus 18
		yabai -m space --focus 27
		;;
	esac
}

yabai -m signal --add event=space_changed action="${functions[space_changed]}"

`

But it seems like there's a race condition, right displays flickers 1-2 seconds and then finally has the right space active.

Is there a better approach?

Kind regards,
  Micha

**Comment by koekeishiya** [comment]
Probably not a better way to do this no.
