### ISSUE TITLE
mac monterey upgrade "scripting-addition payload is not installed some features will not work"

### ISSUE THREAD

**Issue by sajohal** [koekeishiya/yabai#1084]
I've recently installed yabai following this [tutorial](https://www.notion.so/Yabai-8da3b829872d432fac43181b7ff628fc) without disabling SIP and hope to keep it that way. Absolutely love the tool and is why disappointed i can't get around this current issue after today upgrading to Mac OS monterey. I now get this constant notification.

I'm currently on 3.3.10. Please let me know what supplemental information I need to provide. Have attached the console crash report

[yabai-2021-12-09-111943 CRASH report.txt](https://github.com/koekeishiya/yabai/files/7685222/yabai-2021-12-09-111943.CRASH.report.txt)
.

**Comment by 24unix** [comment]
I had the same issues, went to HEAD branch, now it works.

**Comment by sajohal** [comment]
thanks, how do i upgrade to HEAD branch. Did the following:

`brew unlink yabai
brew install koekeishiya/formulae/yabai --HEAD
brew link yabai
brew services restart yabai`

....still same notification

**Comment by sajohal** [comment]
get this so trying again (after i've updated command line tools)

**Your branch is up to date with 'origin/master'.
HEAD is now at 5317b16 xcrun
==> Installing yabai from koekeishiya/formulae
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install**

**Comment by 24unix** [comment]
I had that as well, just perform all steps mentioned ending with xcode-select --install

**Comment by sajohal** [comment]
yes worked, much appreciated

**Comment by Tylerc230** [comment]
I'm still experiencing this. I'm on an Intel mac, Macos 12.2.1, yabai -v yabai-v3.3.10. I get the notification every few seconds.

**Comment by anajuliabit** [comment]
I'm having this on yabai 5.0.6 :/
