### ISSUE TITLE
Yabai ignoring Mail app

### ISSUE THREAD

**Issue by clyra** [koekeishiya/yabai#1087]
Hi there,

This seems a bit off, but yabai is completely ignoring Mail app! I have shortcuts (skhd) to resize/move windows and they work right with every other app. I use to have Mail and calendar side by side on a separate  space (float) and I can move/resize the Calendar app with my shortcuts but not Mail. 

I did a simple test running yabai from the command line and got a unexpected result. I ran the command below and clicked on the Mail window. 
```
$ sleep 5; yabai -m window  --grid 1:2:1:0:1:1 
could not locate the window to act on!
````

The same command works right with other windows... any hints? I'm on a mac mini m1 running big sur 11.6.1 and yabai-v3.3.10.

**Comment by koekeishiya** [comment]
should've been fixed in https://github.com/koekeishiya/yabai/commit/d8dcca2171aece881b86b52369b8265dbb25a16b some time ago.

**Comment by lake-effect** [comment]
Nothing that this behavior is occurring in yabai-v5.0.4, OSX 13.3.1.

Adding `yabai -m rule --add app=Mail manage=on` and restarting yabai was the workaround.
