### ISSUE TITLE
Bug: need to explicitly reset "bsp" before applying `split_ratio` a second time.

### ISSUE THREAD

**Issue by molleweide** [koekeishiya/yabai#1092]
## version
` yabai-v3.3.10`

## note

maybe this has been fixed in HEAD. I do not know.

Also, I need to verify with you guys that this isn't the appropriate behavior.

## description

It seems that if I have already set `config split_ratio` once, then resetting it again to another value does not work
for me. I have tested this with separate commands in on the command line and also tested with my function
below. I found this "bug" whilst trying to write a script function that sets up an automatic custom layout and therefore 
I needed to update the split_ratio value between each terminal instantiation.

Eg.
1. set split ratio to `0.3`
2. add new window -> opens with 0.3 ratio
3. change split ratio to `0.4`
4. add new window -> still opens with 0.3 ratio
5. reset layout bsp
6. add new window  -> opens with correct ratio 0.4

## my function

hopefully this is readable..

``` bash
# @param  number of terminals to create
# @param window_placement
# @param split_ratio
terms_add() {

   # get existing terminals info
    local aid=($(jq_w_ids_by_app_name "Alacritty"))
    local aid_ct=${#aid[@]}
    local aid_ct_new=$(($aid_ct + 1))
    local new_name="Alacritty"

    local new_num=$1
    cfg_wp $2 # call function that sets windowplacement

    wmc y bsp # NEED TO EXPLICITLY SET layout here to make split_ratio (*) take effect
    # if I don't set layout bsp above split ratio won't take effect even though
   # the layout already is set to bsp

    local ratio
    if test $2 = "1"; then # window placement before / after -> reverse split ratio...
        ratio=$3
    elif test $2 = "2"; then
        ratio=$(bc <<< "scale=2; 1-${3}")
    fi

    wmc sr "${ratio:-.5}" # (*) here I set the split_ratio.

    inst_ceiling=$(( $aid_ct + $new_num))
    term_new $aid_ct_new $inst_ceiling
}
```

**Comment by Holer90** [comment]
I am experiencing this bug too.

The first time I run `yabai -m config split_ratio X` it applies to all windows (not including the time its called in the `yabairc`). The second time I run `yabai -m config split_ratio Y` it only applies to  _nodes created after the call_, i.e. the new ratio is only applied after creating two new windows.

**Comment by molleweide** [comment]
Cool! I shall follow you instructions Åsmund and I'll close this for now.
