### ISSUE TITLE
Awesome Fonts are not showing for clock or battery

### ISSUE THREAD

**Issue by amadeusrotundo** [koekeishiya/yabai#110]
After installing font awesome from homebrew I was still unable to get the fonts to render.  I used the example config, then changed the font naming around, at a loss.

`brew cask install font-fontawesome`

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/47001298/60919913-eaba0680-a264-11e9-9e2c-5be3daf8c36a.png">

**Comment by Sweenu** [comment]
try `"FontAwesome 5 Free:Solid:12"` 
:)

**Comment by dominiklohmann** [comment]
For future reference, you can see the relevant info about your fonts in *Font Book.app*. yabai wants the format `family:style:size`.

![image](https://user-images.githubusercontent.com/4488655/60921014-dc3a1200-a299-11e9-9fa4-8a7132144fe5.png)

**Comment by amadeusrotundo** [comment]
`"Font Awesome 5 Free:Solid:12"` is what ended up working, those pesky spaces getting in the way.  Thanks @dominiklohmann
