### ISSUE TITLE
Spaces query information for has-focus and is-visible is swapped

### ISSUE THREAD

**Issue by xiamaz** [koekeishiya/yabai#1108]
On the current master the information for `has-focus` and `is-visible` is swapped for multiple monitors.

When using `yabai -m query --spaces` `is-visible` is false for the non-focused monitor, while `has-focus` is set to true. For the focused and visible monitor both are true.

**Comment by koekeishiya** [comment]
This was fixed in https://github.com/koekeishiya/yabai/commit/28c2e8e778210103c04d4574cbed446bd54bc965
