### ISSUE TITLE
[Request] Two finger swipe on title bar to move windows

### ISSUE THREAD

**Issue by amadeusrotundo** [koekeishiya/yabai#111]
Is it possible to add two finger swipe on the title bar to move the windows to the next/previous desktop?

**Comment by dominiklohmann** [comment]
yabai does not care about user input at all aside from mouse actions and [&rarr;&nbsp;skhd](https://github.com/koekeishiya/skhd) by the same author does not care about gesture inputs either, although this certainly would be a nice-to-have feature.

Your best bet here might be [&rarr;&nbsp;BetterTouchTool](https://folivora.ai), which is an application that does way too many things (some well, others not so much), and some of these things include mapping gestures to asynchronously executed external commands. 

I don't think you can reliably detect whether the element under the cursor is a title bar, as there is no single commonly used accessibility role or subrole for title bars elements in macOS. Your best bet here might be detecting an `AXTabGroup` role for the frontmost element under the cursor using Apple Script.

**Comment by amadeusrotundo** [comment]
[Hyperdock](https://bahoom.com/hyperdock) does an ok job of two finger swipe, and I've really only found it to not work on the iMessage app.  Unfortunately, it doesn't seem like it is under development and I suspect it will fail to work under Catalina.  I don't have any idea how hyperdock decides what is a title bar or not.  I will see what I can do with AppleScript and BTT in the mean time.  I'll leave this issue open in the event someone has some insight.  Feel free to close it if it's of no interest regardless.

**Comment by dominiklohmann** [comment]
You can also just accept it if it's in the top 40px of your window or something like that. That's way easier to script and does not require you to use any Apple Script at all.

```sh
# grab current mouse xy coords 
xy_coords=($(cliclick p | tr "," "\n"))

# set vertical threshold
h_threshold="40.0"

# compare with current window
# iff threshold is met move the window to the next space
yabai -m query --windows --window  | jq -re ".frame 
    | (${xy_coords[1]} >= .x) and (${xy_coords[1]} <= .x + .w) and
      (${xy_coords[2]} >= .y) and (${xy_coords[2]} <= .y + ${h_threshold})" \
   && yabai -m window --space next
```

The example script uses cliclick to grab the mouse coords and jq for json parsing (`brew install cliclick jq`).

**Comment by koekeishiya** [comment]
I started very briefly on gestures by hooking up the Apple multi-touch framework, but I shifted my interests to other fields and did not make anything of it.

If someone is interested in writing a system to recognize and turn custom gestures into actions feel free to take a look at what I started in *skhd* on the *mt* branch. I have made sure it is up to date with master, compiles properly and outputs some touch information.

I don't imagine that I'll be looking into this for quite a while, as there are far too many things I want to do.

**Comment by koekeishiya** [comment]
> I'll leave this issue open in the event someone has some insight. Feel free to close it if it's of no interest regardless.

I'll leave it open for some time so that it is noticable by other users, in case someone is interested in trying to implement this themselves. I'm not particularly interested in having it upstream in *yabai* though, but I would be open to a PR for this in *skhd*. This issue would maybe be better suited for follow-up in https://github.com/koekeishiya/skhd/issues/25
