### ISSUE TITLE
configure bsp window_placement to always be on bottom-right?

### ISSUE THREAD

**Issue by JoelLau** [koekeishiya/yabai#1112]
This could be a configuration problem, but yabai seems to split my windows into 3 columns before starting to split as I would expect (see gif below).

Is there any way I can configure yabai to always split on the bottom right in bsp mode?

![screen-split](https://user-images.githubusercontent.com/29514264/147523907-935af31d-d8de-480b-8cdf-949c6b834e56.gif)

**Comment by koekeishiya** [comment]
Should work better after #1423
