### ISSUE TITLE
Focus next and then focus previous does not always focus the same window again

### ISSUE THREAD

**Issue by kiryph** [koekeishiya/yabai#1114]
Consider following bsp layout:
```
+-----------------------+ +----------+
| w1                    | | w4       |
| id 21914              | | id 20434 |
+-----------------------+ |          |
+----------+ +----------+ |          |
| w2       | | w3       | |          |
| id 26564 | | id 26563 | |          |
+----------+ +----------+ +----------+
```

Currently w1 has focus. Invoking `$ yabai -m window --focus next` three times selects w1 -> w2 -> w3 -> w4.

Now w4 has focus.
If you now invoke `$ yabai -m window --focus prev` several times selects w4 -> w2 -> w1.

This skips w3.

skhd mappings
```
# Next
shift + ctrl - o : yabai -m window --focus next

# Previous
shift + ctrl - i : yabai -m window --focus prev
```

```
❯ yabai -m query --spaces --space
{
	"id":8,
	"label":"Space 5",
	"index":5,
	"display":1,
	"windows":[21914, 20434, 26563, 26564],
	"type":"bsp",
	"visible":1,
	"focused":1,
	"native-fullscreen":0,
	"first-window":21914,
	"last-window":20434
}
```

<details>
<summary>Output of <tt>yabai -m query --windows --space</tt>:</summary>

```
[{
	"id":26563,
	"pid":1325,
	"app":"Finder",
	"title":"Macintosh HD",
	"frame":{
		"x":856.0000,
		"y":723.0000,
		"w":845.0000,
		"h":711.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":5,
	"visible":1,
	"focused":1,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":0,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":26564,
	"pid":1325,
	"app":"Finder",
	"title":"Users",
	"frame":{
		"x":6.0000,
		"y":723.0000,
		"w":845.0000,
		"h":711.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":5,
	"visible":1,
	"focused":0,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":0,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":20434,
	"pid":64906,
	"app":"Google Chrome",
	"title":"koekeishiya/yabai: A tiling window manager for macOS based on binary space partitioning - Google Chrome",
	"frame":{
		"x":1707.0000,
		"y":6.0000,
		"w":846.0000,
		"h":1428.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":5,
	"visible":1,
	"focused":0,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":0,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":21914,
	"pid":57415,
	"app":"VimR",
	"title":"[No Name] - - NVIM",
	"frame":{
		"x":6.0000,
		"y":6.0000,
		"w":1696.0000,
		"h":711.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":5,
	"visible":1,
	"focused":0,
	"split":"horizontal",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":0,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}]
```
</details>

Is it possible that invoking `yabai -m window --focus previous` cycles through the list of windows in the same but reverse order compared to `yabai -m window --focus next`?

**Comment by koekeishiya** [comment]
Resolved on master.

**Comment by kiryph** [comment]
Thanks for the fix.

BTW I am encountering the same issue as the closed issue https://github.com/koekeishiya/yabai/issues/1110 when running `brew install --HEAD yabai` on 

OS: macOS 11.6.2
XCode: 13.2.1

**Comment by kiryph** [comment]
@koekeishiya I am curious whether the printed list of windows for 
```
❯ yabai -m query --spaces --space | jq '.windows'
[
  442,
  2189,
  2199,
  123
]
```

is a typical [tree traversal](https://en.m.wikipedia.org/wiki/Tree_traversal), i.e. post/pre/in-order?

**Comment by koekeishiya** [comment]
Windows are listed in the order given by macOS, which iirc is based on most recently used/focused. It includes both managed/tiled and floating windows.

**Comment by kola-web** [comment]
Try this
`
alt - k : yabai -m query --spaces --space \
  | jq -re ".index" \
  | xargs -I{} yabai -m query --windows --space {} \
  | jq -sre 'add | map(select(."is-minimized"==false)) | sort_by(.display, .frame.y, .frame.x, .id) | . as $array | length as $array_length | index(map(select(."has-focus"==true))) as $has_index | if $has_index > 0 then nth($has_index - 1).id else nth($array_length - 1).id end'  \
  | xargs -I{} yabai -m window --focus {}

# alt-j
alt - j : yabai -m query --spaces --space \
  | jq -re ".index" \
  | xargs -I{} yabai -m query --windows --space {} \
  | jq -sre 'add | map(select(."is-minimized"==false)) | sort_by(.display, .frame.y, .frame.x, .id) | . as $array | length as $array_length | index(map(select(."has-focus"==true))) as $has_index | if $array_length - 1 > $has_index then nth($has_index + 1).id else nth(0).id end' \
  | xargs -I{} yabai -m window --focus {}

`

**Comment by kiryph** [comment]
@kola-web Thanks for your comment. Can you explain your mappings? It looks like a custom sort of windows by y- and x-coordinate of the current space.

However, they do not work for me.

I have tried to understand the mappings:

I think following part of your code
```
$ yabai -m query --spaces --space | jq -re ".index" | xargs -I{} yabai -m query --windows --space {} > a.txt
```
is identical to 
```
$ yabai -m query --windows --space > b.txt
```
which can be verified by `diff`'ing stdout
```
diff -s a.txt b.txt
Files a.txt and b.txt are identical
```
Why do you need `xargs`? I think shell variables or shell substitution would be fine as well. Echoing shell variables helps to debug.

So I would end up with:
```
alt - k : win_id = $(yabai -m query --windows --space \
| jq -sre 'add | map(select(."is-minimized"==false)) | sort_by(.display, .frame.y, .frame.x, .id) | . as $array | length as $array_length | index(map(select(."has-focus"==true))) as $has_index | if $has_index > 0 then nth($has_index - 1).id else nth($array_length - 1).id end');\
yabai -m window --focus $win_id

alt - j : win_id = $(yabai -m query --windows --space \
| jq -sre 'add | map(select(."is-minimized"==false)) | sort_by(.display, .frame.y, .frame.x, .id) | . as $array | length as $array_length | index(map(select(."has-focus"==true))) as $has_index | if $array_length - 1 > $has_index then nth($has_index + 1).id else nth(0).id end');\
yabai -m window --focus $win_id
```
But they still do not work. `$win_id` is always `null`.

I did not go through the lengthy expression for `jq` where I suppose is the issue. Can you explain this part?

And can you correct your markdown formatting? Thank you.

**Comment by kola-web** [comment]
> 
我也出来了一点，类似于dwm

**Comment by kola-web** [comment]
> @kola-web谢谢你的评论。你能解释一下你的映射吗？从当前空间的 y 坐标和 x 坐标来看，它看起来像是一种自定义类型的窗口。
> 
> 但是，它们对我不起作用。
> 
> 我试图理解映射：
> 
> 我认为遵循您的部分代码
> 
> ```
> $ yabai -m query --spaces --space | jq -re ".index" | xargs -I{} yabai -m query --windows --space {} > a.txt
> ```
> 
> 等同于
> 
> ```
> $ yabai -m query --windows --space > b.txt
> ```
> 
> 可以通过`diff`'ing stdout来验证
> 
> ```
> $ diff -s a.txt b.txt
> Files a.txt and b.txt are identical
> ```
> 
> 为什么需要`xargs`？我认为 shell 变量或 shell 替换也可以。回显 shell 变量有助于调试。
> 
> 所以我最终会得到：
> 
> ```
> alt - k : win_id=$(yabai -m query --windows --space \
> | jq -sre 'add | map(select(."is-minimized"==false)) | sort_by(.display, .frame.y, .frame.x, .id) | . as $array | length as $array_length | index(map(select(."has-focus"==true))) as $has_index | if $has_index > 0 then nth($has_index - 1).id else nth($array_length - 1).id end');\
> yabai -m window --focus $win_id
> 
> alt - j : win_id=$(yabai -m query --windows --space \
> | jq -sre 'add | map(select(."is-minimized"==false)) | sort_by(.display, .frame.y, .frame.x, .id) | . as $array | length as $array_length | index(map(select(."has-focus"==true))) as $has_index | if $array_length - 1 > $has_index then nth($has_index + 1).id else nth(0).id end');\
> yabai -m window --focus $win_id
> ```
> 
> 但它们仍然不起作用。`$win_id`总是`null`。
> 
> 我没有通过冗长的表达来`jq`说明我认为问题所在。你能解释一下这部分吗？
> 
> 你能纠正你的降价格式吗？谢谢你。

Interaction similar to dwm

**Comment by kola-web** [comment]
There is also a swap window
```
# alt+shift-k
alt + shift - k : yabai -m query --spaces --space \
  | jq -re ".index" \
  | xargs -I{} yabai -m query --windows --space {} \
  | jq -sre 'add | map(select(."is-minimized"==false)) | sort_by(.display, .frame.y, .frame.x, .id) | . as $array | length as $array_length | index(map(select(."has-focus"==true))) as $has_index | if $has_index > 0 then nth($has_index - 1).id else nth($array_length - 1).id end'  \
  | xargs -I{} yabai -m window --swap {}

# alt+shift-j
alt + shift - j : yabai -m query --spaces --space \
  | jq -re ".index" \
  | xargs -I{} yabai -m query --windows --space {} \
  | jq -sre 'add | map(select(."is-minimized"==false)) | sort_by(.display, .frame.y, .frame.x, .id) |. as $array | length as $array_length | index(map(select(."has-focus"==true))) as $has_index | if $array_length - 1 > $has_index then nth($has_index + 1).id else nth(0).id end' \
  | xargs -I{} yabai -m window --swap {}


```
