### ISSUE TITLE
Unable to focus specific spaces

### ISSUE THREAD

**Issue by DennisFeldbusch** [koekeishiya/yabai#1116]
Hi there, I'm unable to focus several spaces even though it seems to work partially.

The problem is: when I try to focus the space I'm currently at it gives me: `cannot focus an already focused space.` so I assume it is generally working. When I try to focus another space nothing is happening: no error, no nothing... 
But if I try to focus the space on the other display it works.. 

So I have 6 spaces where space 1 - 4 is mapped to display 1 and space 5 - 6 is mapped to display 2. When I'm at space 1 I can only focus space 1 (where I'm currently at) and space 5 (the space on the other display which I can see but is at the moment not focused). I can't focus space 2-4 and 6. It seems nothing is happening there.

- I'm running the latest yabai on intel.

- I have SIP disabled: `csrutil status > System Integrity Protection status: disabled.` And I assue this is working because the transparency of unfocused windows is working

- I restarted yabai several times and rebooted my mac.

- I uninstalled, installed and then loaded the scripting addition.

- I try focusing with the following command: `yabai -m space --focus <number_of_space>`

I checked issue #697 and #471 but none of these seems to work for me

Thanks in advance

**Comment by koekeishiya** [comment]
If you are on Monterey you need to run from the master branch. See the first post in #1054 for information.
There is also information there on how to debug the scripting-addition when the command "appears to work".

**Comment by koekeishiya** [comment]
update to v4.0.0.
