### ISSUE TITLE
Restarting yabairc for limelight

### ISSUE THREAD

**Issue by sajohal** [koekeishiya/yabai#1117]
I'm currently on **yabai 3.3.10 HEAD-5317b16** and in my yabairc config file these commands to restart limelight:

`killall limelight &> /dev/null
limelight &> /dev/null &`

which I added after following this [tutorial](https://www.notion.so/Yabai-8da3b829872d432fac43181b7ff628fc)....and after a few minutes I keep losing my limelight settings so have to keep restarting this config file.

**Comment by br1ttle** [comment]
I presume you are on monterey. If you scroll down to 'known issues' on issue #1054 you'll see "Window borders are broken; they cause random applications to freeze and also sometimes crashes the WindowServer. I have not found a pattern to this behaviour. Most likely borders will be disabled for Monterey until a solution is found. Limelight needs to be updated for Monterey; I'll look into that at some point, but no ETA."

**Comment by sanjeevjohal** [comment]
Many thanks @br1ttle

**Comment by koekeishiya** [comment]
limelight will not be updated. borders in yabai v4.0.0 work with SIP enabled, use those instead.

**Comment by sajohal** [comment]
That's ashame. The company laptop prohibits this. Thanks all the same

**Comment by typkrft** [comment]
> That's ashame. The company laptop prohibits this. Thanks all the same

You do NOT need to disable sip for yabai's border system to work.
