### ISSUE TITLE
Switching spaces does not work

### ISSUE THREAD

**Issue by JackShort** [koekeishiya/yabai#1118]
Hello after the recent OS update I am unable to switch spaces. I was wondering if there is a workaround for this, for instance when I run yabai --load-sa I get the following error in console:
<img width="1065" alt="Screen Shot 2022-01-05 at 7 32 21 PM" src="https://user-images.githubusercontent.com/9094792/148309307-ce0b708f-343e-474b-84a7-3a2985f8fc8b.png">

Thanks,
Jack

**Comment by ericlovesmath** [comment]
[Check the pinned issue for instructions](https://github.com/koekeishiya/yabai/issues/1054)

**Comment by JackShort** [comment]
thank you that was correct
