### ISSUE TITLE
Yabai follow_focus_mouse not working on MacOs Monterey 12.1

### ISSUE THREAD

**Issue by Vib1240n** [koekeishiya/yabai#1121]
So I mainly use yabai for the follow focus feature. This feature was working perfectly fine before I had to clean install macos on my laptop and I didnt even need to disable SIP. Now, when I try to set the follow focus to 'on', It does nothing. I tried to restart yabai but that doesnt work either. Is there anything else I am missing since I am on apple silicon? Or this feature doesn't work at all on apple silicon. 

Thanks.

**Comment by koekeishiya** [comment]
> focus_follows_mouse [autofocus|autoraise|off]
Automatically focus the window under the mouse.

ref. https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#config

Use `autoraise` or `autofocus`. `on` has not been a thing for ages.

**Comment by Vib1240n** [comment]
I did that, it only works for just a while and it stops working, I have to and type in the command again for it to work. Do you know why thats happening?

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/issues/1054

**Comment by koekeishiya** [comment]
update to v4.0.0 and it should be fine.

**Comment by Vib1240n** [comment]
Do I still need to disable SIP?

**Comment by koekeishiya** [comment]
focus_follows_mouse does *not* need  SIP to be disabled.

**Comment by Vib1240n** [comment]
Thank you
