### ISSUE TITLE
Feature Request: Window swallower

### ISSUE THREAD

**Issue by Mathux** [koekeishiya/yabai#1123]
Hello,

I don't know if it is feasible but it would be great to have windows swallowing possible in yabai. Like in these projects: 
https://github.com/salman-abedin/devour
https://github.com/jamesofarrell/i3-swallow

I love it when I was still using i3wm and it might interest other people.

**Comment by koekeishiya** [comment]
How does something like this differ from simply having a monocle/stack layout, opening an application, and quitting / hiding / minimizing it when you are done. The previous window will once again becomes the key window. ??

**Comment by tami5** [comment]
This is useful when for example, you open a file using finder or terminal and you want the source window hidden until the opened window is closed (maybe preview, maybe edit a line). This helps keep the desktop layout consistent and feels natural for most use-cases.

**Comment by koekeishiya** [comment]
Isn't that effectively the same as opening a window on-top-of another window without changing the layout? Which is exactly how window stacking works. When the top window of the stack is closed, the window beneath is revealed.

e.g.
1. focus a window
2. activate "swallowing"  for the currently focused window (`yabai -m window --insert stack`)
3. open a new application / window. it will be placed on top of the window selected in step 1.
4. do whatever you want in the newly created window.
5. close the window
6. window selected in step 1 is visible/focused again 

step 1. and 2. above can be replaced / merged into a single `yabai -m window west --insert stack` command or w/e, if you know which window you want to make the target for the "swallow" operation.

![swallow](https://github.com/koekeishiya/yabai/assets/6175959/7927b46d-30f8-4730-870b-5de766354c5a)
