### ISSUE TITLE
Yabai doesn't float System Preferences

### ISSUE THREAD

**Issue by CommanderData1701** [koekeishiya/yabai#1125]
Yabai doesn't float System Preferences. It weirdly works with Finder. I do have the System in german and I don't know how Macos actually treats that. I am on Big Sur, and this is my configuration for the exception rules 
`yabai -m rule --add app=Finder layer=above manage=off`
`yabai -m rule --add app="^System Preferences$" layer=above manage=off`

**Comment by ujjwal3067** [comment]
I have this in my yabai config and it works fine for me on bigsur. 
`yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off`

**Comment by CommanderData1701** [comment]
> `yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off`

Still doesn't work. I am very lost at this point

**Comment by Liquidmantis** [comment]
My guess is it's a German localization issue.  Install `jq` if you don't have it and run `yabai -m query --windows | jq ".[] | { App: .app, Title: .title }"` when you have System Preferences open.  Then adjust your filter to match.

Here's how I'm excluding System Preferences:
`yabai -m rule --add app="^System Preferences$" manage=off `

**Comment by xel-x** [comment]
Same Issue here.

querying I get the following:
```
{
  "App": "Systemeinstellungen",
  "Title": "Systemeinstellungen"
}
```

Rules, which do not work:
```
yabai -m rule --add app="^Systemeinstellungen$" sticky=on layer=above manage=off
yabai -m rule --add app="Systemeinstellungen" sticky=on layer=above manage=off
yabai -m rule --add app="^Systemeinstellungen$" title=".*" sticky=on layer=above manage=off
yabai -m rule --add app="System Preferences" sticky=on layer=above manage=off

yabai -m rule --add label="sys" app="^System P" sticky=on layer=above manage=off
yabai -m rule --add label="sys" app="^Systemp" sticky=on layer=above manage=off
yabai -m rule --add label="sys" app="^Systeme" sticky=on layer=above manage=off
yabai -m rule --add label="sys" app="^System E" sticky=on layer=above manage=off
yabai -m rule --add label="sys" app="^System e" sticky=on layer=above manage=off
yabai -m rule --add app="System.einstellungen$" sticky=on layer=above manage=off
```

Rule which does work however
```
yabai -m rule --add app="System..einstellungen$" sticky=on layer=above manage=off
```

So I guess the problem are two special, non-printable characters between "System" and "einstellungen".
Just to be safe I would suggest using the following instead:
```
yabai -m rule --add app="System.*einstellungen$" sticky=on layer=above manage=off
```

**Comment by ChrisSku** [comment]
I found the character: U+00AD : SOFT HYPHEN [SHY] {discretionary hyphen}
You can get the full text with all chars also the invincible once when copying out of spotlight search.
```sh
yabai -m rule --add app="^System­einstellungen$" sticky=on layer=above manage=off
```
If you copy the string in VSCode you will see some kind of yellow box for the char.
![image](https://user-images.githubusercontent.com/43596787/186177048-80227e4a-173c-4109-bba3-84392c73b638.png)

**Comment by loeffel-io** [comment]
> My guess is it's a German localization issue. Install `jq` if you don't have it and run `yabai -m query --windows | jq ".[] | { App: .app, Title: .title }"` when you have System Preferences open. Then adjust your filter to match based on what string that gives you.
> 
> Here's how I'm excluding System Preferences, in EN-US: `yabai -m rule --add app="^System Preferences$" manage=off `
> 
> [Edit after installing German language] Try this: `yabai -m rule --add app="^System­ einstellungen$" manage=off `
> 
> And add the layer=above if you want, after testing.

For me it was `System­einstellungen`

**Comment by ilmmr** [comment]
The option "layer=above" was causing me the problem... With "manage=off", it works fine
