### ISSUE TITLE
Web page a tag title problem

### ISSUE THREAD

**Issue by ati46** [koekeishiya/yabai#1127]
I used a script to realize that the border does not appear when there is only one window in the current space, and then found this problem.
1. Use chrome in the space stack, and place the mouse on the a tag with title for a long time. When the title appears, chrome will display a border, which means that the title is recognized as a window.
2. Use chrome in space bsp, put the mouse on the a tag with title for a long time, when the title appears, it will disappear in a flash.
3. When using safari in the space stack, the mouse is placed on the a tag with title for a long time. When the title appears, a border will appear in chrome, which means that the title is recognized as a window.
4. Use safari in space bsp, put the mouse on the a tag with title for a long time, when the title appears, chrome will appear a border, that is to say, the title is recognized as a window

Is there a way to prevent the title from being recognized as a window?

**Comment by cuiko** [comment]
same problem :(

**Comment by cuiko** [comment]
> same problem :(

I try to update yabai rule and it works for me now, seem like following.
```bash
# before
yabai -m rule --add app=".+" manage=off
yabai -m rule --add app="^${apps}$" manage=on

# after
yabai -m rule --add app!="^${apps}$" manage=off
```

reference from https://github.com/koekeishiya/yabai/issues/424
