### ISSUE TITLE
[$100 bounty] Disable animations for native-fullscreen toggle

### ISSUE THREAD

**Issue by tobiasmuehl** [koekeishiya/yabai#1129]
Is there a way to speed up or disable the animation when toggling a window into our out of native fullscreen? (`yabai -m window --toggle native-fullscreen`)

**Comment by lwmacct** [comment]
> Probably technically possible, but I don't expect that this is something I will be spending time on any time soon.

This feature is greatly needed, as the switching animation has a delay and also affects the visual experience. It is indeed a very necessary function.

**Comment by koekeishiya** [comment]
I basically never use macOS native-fullscreen. Feel free to submit a PR that solves this.

**Comment by tobiasmuehl** [comment]
Actually stopped using yabai but still looking for a solution for this. Offering $100 bounty for a solution to this (ideally one that's not reliant on yabai)

**Comment by aspauldingcode** [comment]
Omg you figured it out??

**Comment by koekeishiya** [comment]
No, I am not interested on spending time on this, as mentioned in my previous comment.
Since the original poster also no longer uses yabai I didn't feel the need to keep this open.
