### ISSUE TITLE
Focus / cycle through floating windows

### ISSUE THREAD

**Issue by jack836** [koekeishiya/yabai#113]
Yabai is certainly making everyday workflow enjoyable. Thank you!
BTW, I always have the feeling that, to achieve close to 100% keyboard oriented operation, I should be able to focus  between floating and tiled windows OR cycle through all floating windows (assume a few windows are floating and the rest are tiled) using some keyboard shortcuts. 
[Related issue](https://github.com/koekeishiya/chunkwm/issues/510#issuecomment-483261157)

Would love to see this feature in Yabai. 
Let me know if this feature already exists and that I am missing some thing.

**Comment by dominiklohmann** [comment]
You will be able to do this if #112 gets added, so you can focus a window by its id.

```sh
# 1. query all windows on active space
# 2. get the ids of all floating windows, sorted by id
# 3. get the id after the currently focused windows id
# 4. focus the window with the id
yabai -m query --windows --space \
    | jq 'sort_by(.id) | .[] | select(.floating == 1) | .id' \
    | awk "/$(yabai -m query --windows --window | jq '.id')/{getline; print}" \
    | xargs -I{} yabai -m window --focus {}
```

The below example works up until step 3 right now: you can print the target window id. You can't focus it yet.

**Comment by dominiklohmann** [comment]
@jack836 on current master you can use this beautifully long oneliner to cycle through all windows on a space, sorted by their x coordinate first and then by their y coordinate. 

```sh
# cycle all windows on space backwards by coordinate
alt - tab : yabai -m window --focus "$(yabai -m query --windows --space | jq -re "[sort_by(.frame.y) | sort_by(.frame.x) | reverse | .[] | select(.role == \"AXWindow\" and .subrole == \"AXStandardWindow\") | .id] | nth(index($(yabai -m query --windows --window | jq -re ".id")) - 1)")"

# cycle all windows on space backwards by coordinate
shift + alt - tab : yabai -m window --focus "$(yabai -m query --windows --space | jq -re "[sort_by(.frame.y) | sort_by(.frame.x) | .[] | select(.role == \"AXWindow\" and .subrole == \"AXStandardWindow\") | .id] | nth(index($(yabai -m query --windows --window | jq -re ".id")) - 1)")"
```

The scripts in my above post still had some very slight issues. For example chrome spawns some unfocusable windows that have a role of AXUnknown and these needed to be filtered out.

**Comment by dominiklohmann** [comment]
Now that #112 has landed on master you can do some pretty fancy stuff:

```sh
# cycle through all windows sorted by: coordinates -> space index -> display index
yabai -m window --focus "$(yabai -m query --windows | jq "sort_by(.display, .space, .frame) | map(select(.subrole != \"AXUnknown\")) | reverse | nth(index(map(select(.focused == 1))) - 1).id")"
```

**Comment by jack836** [comment]
Pretty awesome. Thank you!! 
I am not able to test it immediately (vacations and other stuff). I will report back soon.....

**Comment by jack836** [comment]
Sorry for the delay.... Tested it today.
@dominiklohmann Thank you for putting up a readymade recipe. It worked out of the box on high Sierra. Anyway, it delivers what I wanted. 
With my level of knowledge I wouldn't have come up with such a nice solution (I still don't understand what the command does exactly). 
So far, I was restricting myself from making windows float (even though the need arises), and I don't have to do that any more. Thank you for the freedom.

**Comment by dominiklohmann** [comment]
> I still don't understand what the command does exactly

I'll try to explain the last one

```sh
# the full command
yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .frame.x, .frame.y, .id) | map(select(.visible == 1 and .subrole != \"AXUnknown\")) | reverse | nth(index(map(select(.focused == 1))) - 1).id")"

# in parts, explained:

# focus window with selector (window id in this case)
yabai -m window --focus "$(...)"

# to get the selector, we first get information about all windows
yabai -m query --windows

# and run that information through jq, which is a tool for operating on JSON data
| jq -re ".."

# we first sort our available windows by their display and by their coordinates
# and also sort by id in case two windows have the same origin
sort_by(.display, .frame.x, .frame.y, .id) 

# next we select only windows that are visible and whose subrole is not AXUnknown
# (on current master the check for subrole != AXUnknown is no longer necessary)
| map(select(.visible == 1 and .subrole != \"AXUnknown\")) 

# we then reverse the list
| reverse 

# and grab the element with the index that's one less than
| nth(... - 1)

# the index of the currently focused window
index(map(select(.focused == 1)))

# then we return only its id so we can focus the window
.id
```

Now you may wonder why we reverse the list and reduce the index by 1 instead of just raising the index by 1. That is because with `jq`, the array index [-1] indicates the last element of the array so we  get wraparound for free.

**Comment by jack836** [comment]
@dominiklohmann I truly appreciate your enthusiasm in explaining things. Its nicely explained that it helps as a good starting point and motivates  to explore further. I believe it will be the same for many other people too.
Thank you for the nice work!

**Comment by mrdylanyin** [comment]
When I build from HEAD ( 5317b16 ) seems the keywords changed. I hacked the code to the following get worked.
```shell
# cycle through all windows sorted by: coordinates -> space index -> display index
yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .space, .frame.x, .frame.y, .id) | map(select(.\"is-visible\" == true and .role != \"AXUnknown\")) | reverse | nth(index(map(select(.\"has-focus\" == true))) - 1).id")"
# cycle through all visible windows sorted by: coordinates -> display index
yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .frame.x, .frame.y, .id) | map(select(.\"is-visible\" == true and .role != \"AXUnknown\")) | reverse | nth(index(map(select(.\"has-focus\" == true))) - 1).id")"
```

**Comment by oldflag2333333** [comment]
Add some code to focus first window when losing focus from all windows.


```
alt - tab : [ $(yabai -m query --windows --space | jq -re "map(select(.\"has-focus\" == true)) | length != 0") = true ] && yabai -m window --focus "$(yabai -m query --windows --space | jq -re "[sort_by(.id, .frame) | reverse | .[] | select(.role == \"AXWindow\" and .subrole == \"AXStandardWindow\") | .id] | nth(index($(yabai -m query --windows --window | jq -re ".id")) - 1)")" ||  yabai -m window --focus "$(yabai -m query --spaces --space | jq -re ".windows[0]?")" &> /dev/null
```

**Comment by qizidog** [comment]
> ```shell
> # cycle through all windows sorted by: coordinates -> space index -> display index
> yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .space, .frame.x, .frame.y, .id) | map(select(.\"is-visible\" == true and .role != \"AXUnknown\")) | reverse | nth(index(map(select(.\"has-focus\" == true))) - 1).id")"
> # cycle through all visible windows sorted by: coordinates -> display index
> yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .frame.x, .frame.y, .id) | map(select(.\"is-visible\" == true and .role != \"AXUnknown\")) | reverse | nth(index(map(select(.\"has-focus\" == true))) - 1).id")"
> ```

In my opinion, these two commands perform no difference now, windows in other space are all invisiable.

**Comment by qizidog** [comment]
> In my opinion, these two commands perform no difference now, windows in other space are all invisiable.

sorry, I only have one display, with multiple displays they may act different.

**Comment by xtrasmal** [comment]
> Does this still work with `shkd`?
> 
> > ```shell
> > # cycle through all windows sorted by: coordinates -> space index -> display index
> > yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .space, .frame.x, .frame.y, .id) | map(select(.\"is-visible\" == true and .role != \"AXUnknown\")) | reverse | nth(index(map(select(.\"has-focus\" == true))) - 1).id")"
> > # cycle through all visible windows sorted by: coordinates -> display index
> > yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .frame.x, .frame.y, .id) | map(select(.\"is-visible\" == true and .role != \"AXUnknown\")) | reverse | nth(index(map(select(.\"has-focus\" == true))) - 1).id")"
> > ```
> 
> All keymaps stop working as soon as I add these lines to shkd.


Just tried the following, which work:

```shell
# cycle all windows on space backwards by coordinate
meh - m : yabai -m window --focus "$(yabai -m query --windows --space | jq -re "[sort_by(.id, .frame) | reverse | .[] | select(.role == \"AXWindow\" and .subrole == \"AXStandardWindow\") | .id] | nth(index($(yabai -m query --windows --window | jq -re ".id")) - 1)")"

# cycle all windows on space backwards by coordinate
meh - n : yabai -m window --focus "$(yabai -m query --windows --space | jq -re "[sort_by(.id, .frame) | .[] | select(.role == \"AXWindow\" and .subrole == \"AXStandardWindow\") | .id] | nth(index($(yabai -m query --windows --window | jq -re ".id")) - 1)")"

# cycle through all windows sorted by: coordinates -> space index -> display index
meh - v : yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .space, .frame.x, .frame.y, .id) | map(select(.\"is-visible\" == true and .role != \"AXUnknown\")) | reverse | nth(index(map(select(.\"has-focus\" == true))) - 1).id")"
# cycle through all visible windows sorted by: coordinates -> display index
meh - b : yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .frame.x, .frame.y, .id) | map(select(.\"is-visible\" == true and .role != \"AXUnknown\")) | reverse | nth(index(map(select(.\"has-focus\" == true))) - 1).id")"


```
