### ISSUE TITLE
Unable to codesign on Mac

### ISSUE THREAD

**Issue by songproducer** [koekeishiya/yabai#1132]
Hi, I'm trying to stop repeated popup dialog box of Accessibility Access. I run:

codesign -fs 'yabai-cert' $(which yabai)

error: The specified item could not be found in the keychain.

**Comment by Stanpol** [comment]
Have you created a certificate named 'yabai-cert' before signing?
Follow the instructions in the [wiki](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)).

**Comment by songproducer** [comment]
Thanks, I had not seen those instructions.
