### ISSUE TITLE
NSException on latest HEAD

### ISSUE THREAD

**Issue by basbebe** [koekeishiya/yabai#1133]
upgrading to https://github.com/koekeishiya/yabai/commit/fe86f24a21772810cd186d1b5bd2eff84b2701a9 using the procedure described in the wiki (https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) broke yabai for me:

```fish
> yabai
2022-01-23 15:54:53.241 yabai[23037:15569302] -[__NSCFNumber _daisyFrame]: unrecognized selector sentto instance 0x7ff82dc7e735
2022-01-23 15:54:53.242 yabai[23037:15569302] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber _daisyFrame]: unrecognized selector sent to instance 0x7ff82dc7e735'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff813537f0b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff813298b9d objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8135bcadb -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007ff81349edb9 ___forwarding___ + 1406
	4   CoreFoundation                      0x00007ff813562fd8 __forwarding_prep_1___ + 120
	5   AppKit                              0x00007ff8165d4e35 -[NSScreen safeAreaInsets] + 58
	6   yabai                               0x000000010ac235d0 workspace_display_has_notch + 480
	7   yabai                               0x000000010ac3005d display_bounds_constrained + 141
	8   yabai                               0x000000010ac32082 view_update + 98
	9   yabai                               0x000000010ac32eff view_create + 159
	10  yabai                               0x000000010ac3bad8 space_manager_init + 280
	11  yabai                               0x000000010ac45878 main + 1256
	12  dyld                                0x000000010fe384fe start + 462
)
libc++abi: terminating with uncaught exception of type NSException
fish: Job 1, 'yabai' terminated by signal SIGABRT (Abort)
```

using macOS 12.1, intel (2016 MacBook Pro)

downgrading to one commit earlier 91a42e747197680330a4cd9c65f932a060b56e4e using the procedure described by @abhatthal in https://github.com/koekeishiya/yabai/issues/1131#issuecomment-1017144275 fixed the problem for me

**Comment by zt1983811** [comment]
Yes I have exactly the same issue 
macOS 12.1, intel (2020 MacBook Pro)
Will try to dowgrading

**Comment by Gael101** [comment]
I also have the exact same issue. On Monterey for intel.
Tried reinstalling , building from source / brew etc , keeps having the same issue 😄

**Comment by zt1983811** [comment]
@Gael101  try this https://github.com/koekeishiya/yabai/issues/1131#issuecomment-1017144275

**Comment by Gael101** [comment]
> @Gael101 try this [#1131 (comment)](https://github.com/koekeishiya/yabai/issues/1131#issuecomment-1017144275)

This worked, thanks a lot ! :)

**Comment by mlubej** [comment]
Works for me on Monterey as well, thanks!

**Comment by koekeishiya** [comment]
ugh reverted. I give up. Brew will just remain fucked for people not running Monterey.

**Comment by zt1983811** [comment]
> ugh reverted. I give up. Brew will just remain fucked for people not running Monterey.

That's fine, they suppose to use v3.10 then 🤣
