### ISSUE TITLE
set window as "bottom-most"?

### ISSUE THREAD

**Issue by ZenithDS** [koekeishiya/yabai#1134]
Is there a way to set a window as "bottom-most" in yabai? In the sense that I want the particular window to be displayed below everything else (including the ubersicht bar) so I can essentially use the content of that window as a wallpaper?

**Comment by koekeishiya** [comment]
you can do `yabai -m window --layer bottom` or make it happen automatically using window rules, see https://github.com/koekeishiya/yabai/issues/429
