### ISSUE TITLE
window_topmost makes the floating windows appear over their menus

### ISSUE THREAD

**Issue by przemub** [koekeishiya/yabai#1135]
Hi, and thank you for a maji yabai window manager!

Version: fe86f24
macOS 12.1, M1 Pro processor

I am using [SoundSource](https://rogueamoeba.com/soundsource/) for sound device management.

Unfortunately, with yabai on, this happens:

https://user-images.githubusercontent.com/1571309/150977847-e8fd3528-9d02-477e-9c71-96a68a5d1c26.mov

Instead of this:

https://user-images.githubusercontent.com/1571309/150977870-6df20a98-49be-4b4a-bb05-432157a0e3ab.mov

I cannot exclude this window (or I don't know how, at least) with `yabai -m rule` since the window appears in neither `yabai -m query --windows | jq 'map(.pid)'` nor `yabai -m query --windows | jq 'map(.window)`.

Please let me know what debug info I could provide.

Thanks!

**Comment by peppy** [comment]
have you tried running the query command using `watch -n1` then triggering the popup? it should show in the list while it is visible.

**Comment by przemub** [comment]
> have you tried running the query command using `watch -n1` then triggering the popup? it should show in the list while it is visible.

Thanks - yes I did. In fact, the other menus from the top bar (like Wi-Fi, Battery, etc.) do not trigger any change as well.

**Comment by peppy** [comment]
System menus won't, but in general third party menus seem to. I don't have SoundSource handy to test with unfortunately (it may be using a new API or something), but can confirm things like iStat Menus create a window.

**Comment by przemub** [comment]
Ah, you're right, iStat Menus creates it on my computer as well. I even created a rule for that :)

**Comment by Liquidmantis** [comment]
I run SoundSource, too, and don't have that issue.  All you're doing is disabling Yabai to make the SoundSource child picker work normally?

**Comment by przemub** [comment]
Hi all, it struck me to disable `window_topmost` in my config, and that helped with this issue. While it's a shame, since I like that setting, yabai is back to being usable for me :)

**Comment by Signynt** [comment]
Would love for there to be a solution to this, it's quite a significant issue!

**Comment by tariqc80** [comment]
I have this issue with Firefox when `window_topmost` is `on`.  

![screenshot](https://user-images.githubusercontent.com/7843563/215146515-a6835509-8166-46b2-84a1-2751edb2baa2.png)

**Comment by koekeishiya** [comment]
Fixed in v6.0.0 #1887
