### ISSUE TITLE
Expose mode does not work in an empty space

### ISSUE THREAD

**Issue by taupiqueur** [koekeishiya/yabai#1137]
Shell command to enter in an empty space:

``` sh
yabai --message window --toggle expose
```

Native expose mode (exposed on `Control + Down` by default) works in an empty space.

**Comment by koekeishiya** [comment]
Not sure why that is; we are calling some macOS API to enter expose. I don't think this is something worth spending a lot of time trying to figure out either, as there is likely nothing we can do to fix it.
