### ISSUE TITLE
Scripting add-on broken in Monterey 12.3 Beta

### ISSUE THREAD

**Issue by addyire** [koekeishiya/yabai#1142]
![image](https://user-images.githubusercontent.com/31645301/151642584-fa954b73-48af-49a5-adfd-035fac6cb421.png)

This error is shown when running `sudo yabai --load-sa` or `sudo yabai --install-sa` on the macOS 12.3 Beta.  

Here is what is shown in `Console.app`:
![image](https://user-images.githubusercontent.com/31645301/151642755-62732797-ccff-48b7-9da6-09f77019692a.png)

**Comment by AndrzejOlender** [comment]
I confirm, it is the same for me.

**Comment by leerauljin** [comment]
I can confirm this as well.

**Comment by niij** [comment]
Same here on Mac 12.2 and Yabai 3.3.10

**Comment by niij** [comment]
I figured out how to fix it. The latest released version's scripting addition doesn't work for Monterey according to keokeishiya. If you [follow the steps to install the latest dev version](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) (HEAD) it does fix it for me at least on Mac 12.2. I can use the left/right window focus commands again.

**Comment by addyire** [comment]
This is for Monterey 12.3 not 12.2

**Comment by niij** [comment]
@addyire it was, and still is, unclear from your post whether you'd tried to use the HEAD install or not.

**Comment by Lekomia** [comment]
Same here with the version of commit 916d913.
I would appreciate it very much if this would be fixed soon.

**Comment by koekeishiya** [comment]
As mentioned many times before; I do not run beta versions of macOS, and so yabai will never support beta versions, especially at this time when the **stable release** does not really support Monterey at all. For 12.0 - 12.2 the master branch should be fairly stable though.

**Comment by theniceboy** [comment]
I'm running 12.3 beta 2. The only thing that stopped working for me is switching spaces. My current workaround is to use BetterTouchTool.

**Comment by theniceboy** [comment]
Just putting information here: script add-on is still broken on macOS 12.3 beta 3

**Comment by addyire** [comment]
> As mentioned many times before; I do not run beta versions of macOS, and so yabai will never support beta versions, especially at this time when the **stable release** does not really support Monterey at all. For 12.0 - 12.2 the master branch should be fairly stable though.

Closing bc of this

**Comment by theniceboy** [comment]
I hope this gets fixed soon. It might be Universal Control messing with things. I tried looking into the codebase but had no progress.

**Comment by gservat** [comment]
@addyire would it be possible to re-open this issue given that 12.3 is out of beta?

**Comment by theniceboy** [comment]
@addyire Seems like this has been fixed.

**Comment by addyire** [comment]
You're right, sorry I didnt check for myself. @gservat if you are still having this problem make sure you follow [these](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#updating-to-latest-head) instructions.

**Comment by gservat** [comment]
Yeah, it was fixed literally 4 hours before you re-opened it :) All it takes is a bug like this to realize just how important yabai is to my day-to-day use of my desktop. Thank you @koekeishiya <3 No other window manager on macOS comes close to yabai!
