### ISSUE TITLE
Kitty no longer tiled

### ISSUE THREAD

**Issue by Rofer11607** [koekeishiya/yabai#1144]
Hey guys,

This stopped working for me after a restart, I imagine apple made some sort of update. Really a big part of my workflow. How can I get this to a state where its working again? 

After some looking around on some other threads there was a solution where kitty window was too small to be picked up by yabai,
changed initial kitty window from 800X600 to 2400X2400, still not managed

I installed from HEAD.

My Mac-os version:
12.1

![image](https://user-images.githubusercontent.com/55964540/152022114-e1f1ef9d-911e-4242-a314-b684e9c68dc4.png)

Followed all sip instructions. I also tried to delete the tmp/yabai* but was unable to locate it.

**Comment by Liquidmantis** [comment]
No problems with Kitty here.  I just upgraded from 12.1 to 12.2 this morning and everything is still fine.

**Comment by Rofer11607** [comment]
Hey Mantis, can you elaborate on what steps you followed to get this working?

**Comment by Liquidmantis** [comment]
That's just the thing.  I wish I could be of more help but I didn't need to do anything special.  I do run Yabai from HEAD, using brew to install/update/build, but it just works.

I just poked around in your dotfiles and I don't see anything that looks off, but have you tried with empty kitty.conf and .yabairc files? 

All I do for kitty is load a color theme and set my font
https://github.com/Liquidmantis/dotfiles/blob/main/kitty/kitty.conf

My yabairc is straightforward, too
https://github.com/Liquidmantis/dotfiles/blob/main/yabai/yabairc

**Comment by kabeero** [comment]
also not tiling Kitty for me... didn't change any `yabairc` or `kitty.conf` lately. seems like a macOS update broke something

```
kitty 0.24.4 created by Kovid Goyal

yabai-v4.0.0

skhd version 0.3.5
```
----
```
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

**Comment by koekeishiya** [comment]
No idea, works fine for me on both my MacBooks.

**Comment by Meaticus22** [comment]
Having same problem too, yabai can't manage my kitty windows.
