### ISSUE TITLE
Yabai repeatedly asks for accessibility access when starting the service

### ISSUE THREAD

**Issue by lyng-dev** [koekeishiya/yabai#1146]
After installing yabai from --HEAD to using homebrew, whenever I start the service, yabai will ask for Accessibility Access. If I give it access via System Preferences, then it will just keep asking, eventhough it already has it. 

It doesn't matter if it has access or not, it will continuously ask for permission as long as the service is running.

Anyone know the cause. Unfortunately I was not able to find a duplicate

**Comment by dumbbyte** [comment]
I had this issue too and then turned to the wiki. After generating a cert to codesign the binary it started working after a service restart. 

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-%28from-HEAD%29

**Comment by peppy** [comment]
If you have rebuilt recently, it can be the case that you need to remove the `yabai` app from the whitelist and then accept one of the dialogs again.

**Comment by lyng-dev** [comment]
> I had this issue too and then turned to the wiki. After generating a cert to codesign the binary it started working after a service restart.
> 
> https://github.com/koekeishiya/yabai/wiki/Installing-yabai-%28from-HEAD%29

Thanks alot. That was the missing step for me. Works a charm now :)
