### ISSUE TITLE
Don't tile window but focus on hover mouse

### ISSUE THREAD

**Issue by regalstreak** [koekeishiya/yabai#1148]
Is there any way to not tile a window (leave it floating) but preserve the functionality of focusing it automatically when mouse is on it?

Eg: I have the following rule for Android emulator:
`yabai -m rule --add app='qemu-system-aarch64' manage=off`

Want it to not tile, but also want the mouse feature of autofocus on mouseover to work

I have these set:
```
# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
```

**Comment by Bellavene** [comment]
Add it through another way? I remember there was a setting in macos which enables it.

**Comment by typkrft** [comment]
This should work. My settings below. Have you tried turning off the service and just running yabai to see if there's any useful information. Also a query of the suspect window might be helpful. 

Relevant parts of my config below. 
```BASH
# M O U S E
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 resize
yabai -m config mouse_action2 move
yabai -m config mouse_drop_action swap
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus

# R U L E S
yabai -m rule --add app="^Bitwarden$" manage=off
```
