### ISSUE TITLE
[Request] Add event for window going full screen

### ISSUE THREAD

**Issue by amadeusrotundo** [koekeishiya/yabai#115]
Generally when I click the green dot to go full screen I prefer that windows next to my current space.  The default is to move it to the end of the spaces.  It would be nice if on a window maximize event we could specify the location 

`yabai -m signal --add event=window_fs --space=prev|next|1|2|3|4|5|6...etc`

**Comment by dominiklohmann** [comment]
### Now

Just re-enable the Mission Control setting "Automatically rearrange Spaces based on most recent use". When enabled, setting a space to fullscreen will achieve what you want.

### Maybe sometime in the future

The below script will work for toggling native-fullscreen once some bugs are fixed with native-fullscreen spaces. It's not a signal, but it's something you can use instead. 

Current issues are:
- native-fullscreen spaces cannot be moved by yabai
- native-fullscreen spaces have no unique arrangement index, and as such cannot be addressed consistently

I recommend overriding the system default keyboard shortcut for toggling fullscreen, which is <kbd>ctrl</kbd>&nbsp;<kbd>cmd</kbd>&nbsp;<kbd>f</kbd>.

```zsh
#! /usr/bin/env zsh

# We are enabling native-fullscren and are moving our space
if yabai -m query --windows --window | jq '."native-fullscreen" == 0'
then
	# grab the current space id, and the per-display space index
	old_space_id="$(yabai -m query --spaces --space | jq '.id')"
	old_space="$(yabai -m query --spaces --display | jq "map(.id) | index(${old_space_id})")"

	# move window to native fullscreen and wait half a second for the animation to complete
	yabai -m window --toggle native-fullscreen
	sleep 0.5

	# grab the new space id, and the per-display space index
	new_space_id="$(yabai -m query --spaces --space | jq '.id')"
	new_space="$(yabai -m query --spaces --display | jq "map(.id) | index(${new_space_id})")"

	# move the fullscreen space left repeatedly using zsh's built-in repeat operator
	repeat "$(( ${new_space} - ${old_space} - 1 ))" \
		yabai -m space --move prev

# We are disabling native-fullscreen, no need to move any spaces
else
	yabai -m window --toggle native-fullscreen
fi
```

**Comment by dominiklohmann** [comment]
@amadeusrotundo Now that #117 is on master you can do the following:

Add this to your skhd config:
```sh
ctrl + cmd - f : path/to/toggle-native-fullscreen.zsh
```

Now you can switch a space to fullscreen and move it at the same time.

```zsh
#! /usr/bin/env zsh

# toggle-native-fullscreen.zsh
# remember to chmod +x this file

# We are enabling native-fullscreen and are moving our space
if yabai -m query --windows --window \
	| jq -e '."native-fullscreen" == 0' > /dev/null
then

	# grab the old space index
	old_space="$(yabai -m query --windows --window | jq '.space')"

	# move window to native fullscreen
	yabai -m window --toggle native-fullscreen

	# grab the new space index
	new_space="$(yabai -m query --windows --window | jq '.space')"

	# repeat this until it's neither 0 (invalid) nor the old space id
	until [ $new_space -ne 0 ] && [ $new_space -ne $old_space ]
	do
		sleep 0.01
		new_space="$(yabai -m query --windows --window | jq '.space')"
	done

	# move the fullscreen space left using zsh's built-in repeat operator
	repeat "$(( ${new_space} - ${old_space} - 1 ))" \
		yabai -m space --move prev

# We are disabling native-fullscreen, no need to move any spaces
else
	yabai -m window --toggle native-fullscreen
fi
```

**Comment by drkostas** [comment]
Is there any update on this? I want a rule that when a window goes fullscreen, it gets moved next to the current space instead of the end. I tried the method mentioned above, but it doesn't work.
