### ISSUE TITLE
Notification Center

### ISSUE THREAD

**Issue by windowsrefund** [koekeishiya/yabai#1151]
Hello,

I'm running v3.3.10 on Big Sur and am trying to understand how to get notifications to pop up. At this time, the only way I can see them is to drag my mouse over to the upper right hand corner of my display. After taking this action, I see all the notifications along the right side of my display. Sorry if this is not a yabai issue but I've checked all my notification settings, etc, and am coming up empty. Curious to hear thoughts and provide additional information as needed. Thanks in advance.

**Comment by windowsrefund** [comment]
got it working after clicking a bunch of things... wtf knows... had nothing to do with yabai. Macs just suck.

**Comment by tami5** [comment]
Oh I'm having similar issue. guess I need to click bunch of things😑 too

**Comment by weeebdev** [comment]
same issue, how did you solve this? @kkharji @windowsrefund
