### ISSUE TITLE
Unable to codesign on mac

### ISSUE THREAD

**Issue by poddarh** [koekeishiya/yabai#1152]
I used instructions from https://github.com/koekeishiya/yabai/wiki/Installing-yabai-%28from-HEAD%29 to build yabai from the HEAD, but I am unable to sign the built binary. I followed the instructions exactly as mentioned to create a certificate and then am running the codesign command, but I get errors:

```
$ codesign -fs 'yabai-cert' /Users/poddarh/homebrew/bin/yabai

/Users/poddarh/homebrew/bin/yabai: replacing existing signature
/Users/poddarh/homebrew/bin/yabai: internal error in Code Signing subsystem
```

I am unable to figure out the issue at hand. I tried to create the certificate several times, but no help. Any help would be appreciated! Thanks!

MacOS Monterey 12.2
Apple Silicon M1 Pro

**Comment by typkrft** [comment]
Is that the path to the binary? `$(which yabai)` Mine is `/opt/homebrew/bin/yabai`
