### ISSUE TITLE
Yabai segfaults quickly after starting

### ISSUE THREAD

**Issue by dkovacevic15** [koekeishiya/yabai#1157]
I'm using the latest Homebrew version

Mac: 13-inch Macbook Pro 2017 (A1708)
MacOS: Monterey 12.2

**Comment by TheBlackfurGuy** [comment]
I am having the same issue, I am on MacOS Monterey 12.2 but on a M1 Pro MBP

**Comment by TheBlackfurGuy** [comment]
fixed by doing `brew install yabai --HEAD` still weird tho

**Comment by ArtemSmaznov** [comment]
Started getting segmentation faults every few min after updating from Big Sur to Monterey 12.2.1
reistalling the dev version as suggested above seem to have helped.

**Comment by koekeishiya** [comment]
update to v4.0.0.
