### ISSUE TITLE
scripting-addition failed to inject

### ISSUE THREAD

**Issue by SichangHe** [koekeishiya/yabai#1158]
# scripting-addition failed to inject
```shell
$ yabai -m space --focus next
cannot focus space due to an error with the scripting-addition.
$ sudo yabai --load-sa 
Password:
yabai: scripting-addition failed to inject payload into Dock.app!
```

## version
yabai-v4.0.0
macOS 12.01
M1 apple silicon

SIP is disabled

### same problem from others
*this is migrated from comments on koekeishiya/yabai#787*
@alephpt and @rublev has the problem, but on macOS 12.2

**Comment by CalvoUTN** [comment]
Hey! I had this very problem and just solved it. When you add the line to the visudo yabai file, replace the path from yabai to the output of `which yabai` as it appear that they can be different. After that just restart!

**Comment by SichangHe** [comment]
> Hey! I had this very problem and just solved it. When you add the line to the visudo yabai file, replace the path from yabai to the output of `which yabai` as it appear that they can be different. After that just restart!

I am afraid that we must have different problems.

Your problem seems to be that you were calling the wrong `yabai`.
My problem is that I called the right `yabai` and failed.

**Comment by Tweoss** [comment]
@SichangHe Have you taken a look at the #1054 issue yet? I had the same issues and error messages (I'm on M1 12.2.1) but managed to solve it with some commands. Check out [this code block](https://github.com/koekeishiya/yabai/issues/1054#issuecomment-1059404384). Hopefully that can solve your issue (this command `sudo nvram boot-args=-arm64e_preview_abi` specifically might help).

**Comment by SichangHe** [comment]
> @SichangHe Have you taken a look at the #1054 issue yet? I had the same issues and error messages (I'm on M1 12.2.1) but managed to solve it with some commands. Check out [this code block](https://github.com/koekeishiya/yabai/issues/1054#issuecomment-1059404384). Hopefully that can solve your issue (this command `sudo nvram boot-args=-arm64e_preview_abi` specifically might help).

After executing the code in the code block you mentioned (copied below), **I was able to focus next window ✌️**

``` shell
sudo nvram boot-args=-arm64e_preview_abi
# reboot
sudo yabai --uninstall-sa
sudo yabai --install-sa
sudo yabai --load-sa
```

It seems that, for M1,
``` shell
sudo nvram boot-args=-arm64e_preview_abi
```
is needed for the script addition to work.

which is not mentioned in the installation part of the wiki.

#### I will suggest adding the code to the wiki

**Comment by SichangHe** [comment]
I tried [Automatically load scripting addition on startup](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#macos-big-sur-and-monterey---automatically-load-scripting-addition-on-startup) and it does not work upon reboot
``` shell
$ yabai -m space --focus next
yabai-msg: failed to connect to socket..
```
After quitting *Finder* and opening it again, which supposedly trigger the script addition to load again, it becomes
```shell
$ yabai -m space --focus next
cannot focus space due to an error with the scripting-addition.
```
It works, however, if I manually do
```shell
sudo yabai --load-sa
```

### what I did according to *Automatically load scripting addition on startup*
```shell
sudo visudo -f /private/etc/sudoers.d/yabai
```
add this line to the opened file
```
sichanghe ALL = (root) NOPASSWD: /opt/homebrew/bin/yabai --load-sa
```
add these two lines to `yabairc`
```shell
sudo /opt/homebrew/bin/yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"
```

**Comment by Tweoss** [comment]
Hi @SichangHe 

> It seems that, for M1,
> ```
> sudo nvram boot-args=-arm64e_preview_abi
> ```
> is needed for the script addition to work.
> 
> which is not mentioned in the installation part of the wiki.

It is in fact mentioned in the wiki, though a bit lower down. Check [this page](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection#how-do-i-disable-system-integrity-protection). 

> ```
>  yabai -m space --focus next
> ```
> yabai-msg: failed to connect to socket..

Are you running yabai manually or via `brew services start yabai`? If the former, then you need to make sure to start yabai in the command line before trying to focus spaces. I believe the latter is recommended (definitely more hands off). 

Your `yabairc` addition looks about right, you might have to reboot your computer for the visudo to take effect. I assume that you're using the path of yabai from `which yabai` in there (I have a different path `/usr/local/bin/yabai`)?

**Comment by SichangHe** [comment]
@Tweoss 
> It is in fact mentioned in the wiki, though a bit lower down.

I see it now. I missed it because I already disabled SIP before I started following the wiki and I skipped the SIP part.
I would say that this configuration and SIP are usually considered two different aspects. So, the way the wiki is managed is confusing.

> Are you running yabai manually or via brew services start yabai?

I use `brew` to manage both `yabai` and `skhd`

> Your yabairc addition looks about right, you might have to reboot your computer for the visudo to take effect.

I rebooted twice.

> I assume that you're using the path of yabai from which yabai in there.

You are right about this.

**Comment by Tweoss** [comment]
> I see it now. I missed it because I already disabled SIP before I started following the wiki and I skipped the SIP part.
> I would say that this configuration and SIP are usually considered two different aspects. So, the way the wiki is managed is confusing.
I agree, that little snippet is pretty hard to locate. 

> I use brew to manage both yabai and skhd

Interesting, I figured that brew ought to have started yabai, so you wouldn't need to quit Finder (or pkill Dock). Does yabai work now without manually killing Finder?

**Comment by SichangHe** [comment]
> Interesting, I figured that brew ought to have started yabai, so you wouldn't need to quit Finder (or pkill Dock). Does yabai work now without manually killing Finder?

I killed and restarted *Finder* to trigger this in the `yabairc` to see if it works
```shell
yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"
```

`yabai` is started by `brew` no problem, and `yabai` works after manually running `sudo yabai --load-sa`.
(It causes some buggy window behaviors though)

**Comment by SichangHe** [comment]
Since the topic of this issue, *scripting-addition failed to inject*, is solved by [this](https://github.com/koekeishiya/yabai/issues/1158#issuecomment-1060168503).
I am *closing this issue*.

**Comment by palteksolution** [comment]
> Since the topic of this issue, _scripting-addition failed to inject_, is solved by [this](https://github.com/koekeishiya/yabai/issues/1158#issuecomment-1060168503). I am _closing this issue_.

On Macos Ventura, I try all the ways but it still failed.

**Comment by nategadzhi** [comment]
@palteksolution, the Ventura scripting addition was just fixed in this commit, but it's not released yet: https://github.com/koekeishiya/yabai/commit/206c0d6968210f48363f206526760e5750810a61 

```bash
brew unlink yabai
brew install yabai --head
sudo yabai --load-sa
```

Don't forget to update your sudoers config with the new sha hash of yabai binary, though.
