### ISSUE TITLE
mouse pointer disappears

### ISSUE THREAD

**Issue by technovangelist** [koekeishiya/yabai#1161]
I have a problem where my mouse pointer keeps disappearing. 

I have a M1 Pro MacBookPro with Monterey 12.2.1, Yabai version 4.0.0

When I stop the Yabai service I have zero issues with the mouse pointer disappearing. But when I start the yabai service, I see the mouse disappear for 1 second then come back for roughly 7 seconds. This cycle repeats 4 or 5 times. When the mouse is gone, moving the mouse doesn’t help, but it will come back after that 1 second period. And I mentioned that it repeats 4 or 5 times. It will then stop as long as I don't touch the mouse. As soon as I do, I get another 4 or 5 repeats of the on/off cycle.

**Comment by technovangelist** [comment]
and of course, after posting this, I started Yabai again and not having the issue, but I am confident it will start again soon.....ugh. these problems are the frustrating ones.

**Comment by koekeishiya** [comment]
yabai does not touch the visibility of the cursor; this is some other software you are running. In macOS cursor visibility is a global setting.

**Comment by blackpeter11** [comment]
> 当然，在发布这个之后，我再次启动了 Yabai 并且没有遇到问题，但我相信它很快就会再次启动......呃。这些问题令人沮丧。
Dude, I have exactly the same problem you have, when I turn on the focus_follows_mouse then the same problem will appear.hat's not going to happen when it's off.Have you found a suitable solution？

**Comment by blackpeter11** [comment]
> 

Dude, I have exactly the same problem you have, when I turn on the focus_follows_mouse then the same problem will appear.hat's not going to happen when it's off.Have you found a suitable solution？

**Comment by nocksock** [comment]
I have the same issue. As soon as I stop yabai, the issue is gone. 

However I have a lead/idea: on macos the cursor disappears when typing in an input (eg this textarea) - has been this way for as long as I can remember. I could imagine that yabai is somehow triggering that behaviour.

**Comment by blackpeter11** [comment]
您好，这里是杜炳霖，您的邮件我已经收到了，我会尽早阅读后给您回复。如果事出紧急，请联系电话18944525557。

**Comment by rubas** [comment]
![IMG_3656](https://user-images.githubusercontent.com/1042243/182452793-bcc94a79-10d9-49d5-853d-01e58e7c4359.gif)

I'm facing the same issue on two machines. I'm suspecting `manage=off layer=above` rules.

**Comment by rubas** [comment]
Is it possible that you were running `Bartender` with Yabai?
https://www.macbartender.com

Stopping Bartender made the problem (supposedly) go away.

**Comment by albertsj1** [comment]
Just came here because I've been experiencing the same invisible cursor problem.  The cursor is only missing when going over certain windows and those 'certain windows' are different each time this happens.  I noticed today that restarting yabai restores the cursor visibility.
@rubas  I do have Bartender installed.  I haven't tried restarting Bartender to fix the issue, but restarting Yabai fixes the problem.

**Comment by rubas** [comment]
@albertsj1 Since I stopped using Bartender, I had no issues any more.

**Comment by albertsj1** [comment]
Thanks @rubas .  I honestly haven't noticed the problem in a couple of months now, but I have an [even worse problem](#1732) now with the new Yabai release when using `layer=above and manage=off` that causes the window to be blurred.  I just checked and using bartender doesn't seem to be causing the blur issue I'm now seeing.
