### ISSUE TITLE
Focusing another space does not work in Monterey

### ISSUE THREAD

**Issue by eyalerez-tmrw** [koekeishiya/yabai#1162]
I'm getting an error when I try to change to another space:
```
> yabai -m space --focus 2
cannot focus space due to an error with the scripting-addition.
> yabai -m space --focus 1
cannot focus an already focused space.
> yabai -m space --focus next
cannot focus space due to an error with the scripting-addition.
```

I have SIP disabled:
```
> csrutil status
System Integrity Protection status: disabled.
```

I've tried uninstalled, reinstalling, and reloading the scripting inject and they work without an error, but do not solve the problem:
```
> sudo yabai --uninstall-sa
> sudo yabai --install-sa
> sudo yabai --load-sa
```

My macOS version is: 12.2.1.  I'm not sure what to do at this point. I'm stuck.

**Comment by kevinclark** [comment]
I can confirm the same issue with 12.2.1 and yabai-v3.3.10.

**Comment by icambron** [comment]
I'll add that it's not just 12.2.1 -- seeing the issue in 12.2 as well.

**Comment by TiagoDamascena** [comment]
For macOS 12 use [Dev Version](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)), v4 isn't released yet and v3 scripting additions dont work on macOS 12

**Comment by kevinclark** [comment]
HEAD fixes it for me, thanks!

**Comment by koekeishiya** [comment]
update to v4.0.0.
