### ISSUE TITLE
Question about SIP filesystem protection

### ISSUE THREAD

**Issue by farzadmf** [koekeishiya/yabai#1163]
Hi,

I'm a long-time i3 user and a new Mac user, and I've been wanting to try `yabai` with all the good things I hear about it.

Going through the documentation, I see that disabling SIP is something "optional" (only required for "advanced" features). I'm using a company laptop, so I don't think disabling SIP is an option for me.

So I thought "OK, I'm not gonna use the advanced features". I installed `yabai` through `brew` and started the service, but I keep seeing errors saying SIP must be disabled (also `--install-sa` requires disabling SIP)
![image](https://user-images.githubusercontent.com/5768792/154700133-f14fba27-763e-4556-9abe-50a8f1aa5693.png)

For example, I thought to give `focus_follows_mouse` a shot; it was working for a few seconds, and then it stopped working (not sure if it requires SIP or not, but since it worked for a few seconds, I think it doesn't)

So I was wondering: should I just give up on using `yabai` on my work computer?

Thank you

**Comment by typkrft** [comment]
I could be mistaken but scripting additions require SIP to be disabled. I think you can leave `--install-sa` out...

Also [running with sip](https://github.com/koekeishiya/yabai/discussions/5#discussioncomment-193584) seem to be not officially supported. I used to run with SIP enabled, from what I can remember borders, opacity, creation/destruction of spaces, and a few other things did not work. I don't recall having issues with mouse options, but that was a long time ago and things could have definitely changed. For borders limelight was an option, but I think it's now being looked at for a potential rewrite. I'm not sure if there is a feature matrix for SIP. TLDR if you want to have the best experience possible just disable sip or YMMV.

**Comment by typkrft** [comment]
I think a lot of the issues stem from macOS being difficult to manipulate in some respects. Have you tried using the prebuilt 4.0 binary which is tagged in an pinned issue I believe or installing --head with brew? I assume you're on Apple Silicon?

**Comment by farzadmf** [comment]
Nope! Company laptop, so old 2019 Intel one! 🙁
