### ISSUE TITLE
Is i3fyra layout possible with yabai api?

### ISSUE THREAD

**Issue by cakir-enes** [koekeishiya/yabai#1164]
Im not familiar with the API maybe someone knows this and yabai already and can answer easily

Layout is described here https://github.com/budlabs/i3ass/wiki/i3fyra video here https://www.youtube.com/watch?v=kU8gb6WLFk8

**Comment by dmitrym0** [comment]
That's pretty neat. I'm a yabai newbie, but why wouldn't you be able to port the script to yabai?

**Comment by cakir-enes** [comment]
Because some of the required apis might not exist? Such as tabs, stack containers, which seems like they don't exist. But thought someone might found workarounds for these
