### ISSUE TITLE
Set subsequent windows of the same application to automatically tile?

### ISSUE THREAD

**Issue by leftbones** [koekeishiya/yabai#1168]
I have the following in my `.yabairc` so that all apps are unmanaged by default...
```
yabai -m rule --add app!="^()$" manage=off
```
...and I use a hotkey to tile those that I want to tile (by the way if anyone has a better way to do this, let me know, that line is just what I figured out on my own).

If possible, I'd like to have a setting so that if I open, iTerm2 (for example) then set it to managed with my hotkey, then press cmd+n to make a new iTerm2 window, that new window will _also_ be tiled, because the first one is.

Perhaps this would be possibly by querying the focused window or just all active windows, but I couldn't make anything work in my testing. Thanks.

**Comment by TiagoDamascena** [comment]
You can do this using a signal that executes a custom script on a new window is created. I found your idea interesting and did some tests here.

Add this line to your yabairc
`yabai -m signal --add event=window_created action="~/.config/yabai/scripts/tile_new_window.sh"`

And create the respective bash script
```
#!/bin/bash

PID=$(yabai -m query --windows --window $YABAI_WINDOW_ID | jq '.pid')
FLOAT=$(yabai -m query --windows | jq 'map(select(.pid == '$PID') | select(.id != '$YABAI_WINDOW_ID')) | .[0] | ."is-floating"')
if [ "$FLOAT" = false ]
then
    yabai -m window $YABAI_WINDOW_ID --toggle float
fi
```

Explaining, it will get the PID (proccess ID) of the new window, then will find other windows with the same PID (from the same proccess) and check if the first is floating or not to toggle the float of the new window.

It worked but I haven't tested for a long time, so it may have some bugs.

**Comment by evprkr** [comment]
I've added that line to my `.yabairc`, not sure if placement matters but I put it at the top. Then I made and added the script, I had to actually create the yabai folder within ~/.config because it didn't exist. However, it's not working after restarting.

I'm on Monterey, and I don't have SIP disabled, if that matters.

**Comment by evprkr** [comment]
> You can do this using a signal that executes a custom script when a new window is created. I found your idea interesting and did some tests here.
> 
> Add this line to your yabairc `yabai -m signal --add event=window_created action="~/.config/yabai/scripts/tile_new_window.sh"`
> 
> And create the respective bash script
> 
> ```
> #!/bin/bash
> 
> PID=$(yabai -m query --windows --window $YABAI_WINDOW_ID | jq '.pid')
> FLOAT=$(yabai -m query --windows | jq 'map(select(.pid == '$PID') | select(.id != '$YABAI_WINDOW_ID')) | .[0] | ."is-floating"')
> if [ "$FLOAT" = false ]
> then
>     yabai -m window $YABAI_WINDOW_ID --toggle float
> fi
> ```
> 
> Explaining, it will get the PID (proccess ID) of the new window, then will find other windows with the same PID (from the same proccess) and check if the first is floating or not to toggle the float of the new window.
> 
> It worked but I haven't tested for a long time, so it may have some bugs.

Decided to give this another go thinking maybe I did something wrong the first time but still nothing unfortunately.

**Comment by xib** [comment]
> You can do this using a signal that executes a custom script when a new window is created. I found your idea interesting and did some tests here.
> 
> Add this line to your yabairc `yabai -m signal --add event=window_created action="~/.config/yabai/scripts/tile_new_window.sh"`
> 
> And create the respective bash script
> 
> ```
> #!/bin/bash
> 
> PID=$(yabai -m query --windows --window $YABAI_WINDOW_ID | jq '.pid')
> FLOAT=$(yabai -m query --windows | jq 'map(select(.pid == '$PID') | select(.id != '$YABAI_WINDOW_ID')) | .[0] | ."is-floating"')
> if [ "$FLOAT" = false ]
> then
>     yabai -m window $YABAI_WINDOW_ID --toggle float
> fi
> ```
> 
> Explaining, it will get the PID (proccess ID) of the new window, then will find other windows with the same PID (from the same proccess) and check if the first is floating or not to toggle the float of the new window.
> 
> It worked but I haven't tested for a long time, so it may have some bugs.

This script works great! 

However, the rule to make all apps unmanaged by default would make tiled windows go un-tile when yabai restart. I'm not quite sure how to prevent it from happens.

**Comment by xib** [comment]
Ok, I found the issue: my configuration order cause it.
The fix for me was to make all app un-managed first before turn on the layout:

```sh
## .yabairc
...
yabai -m rule --add app=".*" manage=off
yabai -m signal --add event=window_created action="~/bin/yabai-tile-new-window.sh"
...
yabai -m config layout bsp
...
```

**Comment by TiagoDamascena** [comment]
I made a script to do this based on some comments here and on other issues, it floats any non resizable window and place it on center of current screen.

It's a .sh script inside my yabai config folder and to run it i used a signal on my yabairc config file

```
#!/bin/bash

WINDOW=$(yabai -m query --windows --window $YABAI_WINDOW_ID)

CAN_RESIZE=$(jq --argjson window "$WINDOW" -rn '$window."can-resize"')
FLOATING=$(jq --argjson window "$WINDOW" -rn '$window."is-floating"')

echo "works"

if [ "$CAN_RESIZE" = false ] && [ "$FLOATING" = false ]
then
    yabai -m window $YABAI_WINDOW_ID --toggle float
    yabai -m window $YABAI_WINDOW_ID --layer above

    COORDINATES=$(jq --argjson display "$(yabai -m query --displays --window $YABAI_WINDOW_ID)" --argjson window "$WINDOW" -rn '(($display.frame | .x+.w/2) - ($window.frame | .w/2) | tostring) + ":" + (($display.frame | .y+.h/2) - ($window.frame | .h/2) | tostring)')

    yabai -m window $YABAI_WINDOW_ID --move abs:$COORDINATES
fi
```

```
yabai -m signal --add event=window_created action="~/.config/yabai/scripts/float-not-resizable.sh"
```
