### ISSUE TITLE
Assign space indices to native-fullscreen spaces 

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#117]
### Discussion / Feature request

Factored out from https://github.com/koekeishiya/yabai/issues/116#issuecomment-510824950.

@koekeishiya 
>  Say there are 4 spaces, numbered 1-4 accordingly. After the named Desktop 2, there is a fullscreen space. Would it not make sense to have the fullscreen space be mission-control index 3? I know this breaks with the names given by Apple, which appear to be a simple enumeration of user-spaces - there is no internal name given to spaces (except for the uuid string), which is why I suspect this.

@dominiklohmann 
> > If people wanted the old way back, they could then still do this, assuming there'd also be a "native-fullscreen" attribute for spaces (added it to the list in the first post):
> 
> ```shell
> # this only works if the query output is guaranteed to be ordered by appearance
> old_index=4
> yabai -m space --focus \
>     "$(yabai -m query --spaces
>         | jq -re "[.[] | select(.\"native-fullscreen\" == 0)][${old_index}].index")"
> ```

**Comment by koekeishiya** [comment]
Implemented on master. The literal mission control index is now used to refer to a space - not the index in the desktop name provided by Apple.

**Comment by dominiklohmann** [comment]
Bug: Sending a window to a native-fullscreen space in any ways needs to be a no-op.

**Comment by koekeishiya** [comment]
Right makes sense - fixed on master.

**Comment by dominiklohmann** [comment]
Sorry, it's one of those days... what's inconsistent now is that there's no non-zero exit code.

**Comment by koekeishiya** [comment]
Fixed it in a different way.

**Comment by koekeishiya** [comment]
I could only test moving a fullscreen space around on the display it was created on. I fear that it will break when moved to another display and that this might require doing some more reverse engineering in the Dock.app. Could you test this when you have a moment?

**Comment by dominiklohmann** [comment]
Works fine.
