### ISSUE TITLE
New window border conflicts with quick note

### ISSUE THREAD

**Issue by ywwry66** [koekeishiya/yabai#1173]
Hi,

I have not used window border before since it requires disabling SIP. With the latest commits, disabling SIP is no longer required so I decided to give it a try. Everything works out great except for the quick note functionality added with macOS Monterey. If I move my cursor to the bottom right corner of the screen, normally a little quick note should pop up. But now it shows a ghost border with no content inside, and it is not clickable to invoke the Note.app.

By the way, I have the following in my .yabairc
```
yabai -m rule --add app="^Notes$" manage=off
```

**Comment by koekeishiya** [comment]
Pull the latest master and use this rule:

`yabai -m rule --add app="^LinkedNotesUIService$" title="^Window$" border=off manage=off`

**Comment by ywwry66** [comment]
Thanks for the quick fix. Closing this now.
