### ISSUE TITLE
Monterey12.2.1 Can‘t execution ` sudo yabai --install-sa`

### ISSUE THREAD

**Issue by marquisXuan** [koekeishiya/yabai#1175]
OS：Monterey 12.2.1
yabai: yabai-v3.3.10
/usr/local/bin/yabai: Mach-O 64-bit executable x86_64
SIP disabled
System Integrity Protection status: disabled.

---
I use brew install yabai. when I execution `sudo yabai --install-sa`, failed, the terminal write :
```shell
yabai: '--install-sa' is not a valid option!
```

![image](https://user-images.githubusercontent.com/22328979/156870409-b6e62893-0f33-453e-8069-d684b1c439d8.png)

![image](https://user-images.githubusercontent.com/22328979/156870444-b548f94f-efc1-4c25-8783-ddb126532926.png)

and the errlog has something:

```log
2022-03-05 13:52:09.810 yabai[15868:108822] -[__NSDictionaryI _applyPropertyChanges:fromDictionary:]: unrecognized selector sent to instance 0x600001ccca00
2022-03-05 13:52:09.810 yabai[15868:108822] -[__NSCFConstantString unlock]: unrecognized selector sent to instance 0x7ff841647958
2022-03-05 13:52:09.811 yabai[15868:108822] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString unlock]: unrecognized selector sent to instance 0x7ff841647958'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff801a6af0b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff8017cbb9d objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff801aefadb -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007ff8019d1db9 ___forwarding___ + 1406
	4   CoreFoundation                      0x00007ff8019d17a8 _CF_forwarding_prep_0 + 120
	5   AppKit                              0x00007ff804419cc3 -[NSRunningApplication activationPolicy] + 83
	6   yabai                               0x000000010cdfcadf EVENT_HANDLER_APPLICATION_LAUNCHED + 191
	7   yabai                               0x000000010cdda8e4 event_loop_run + 100
	8   libsystem_pthread.dylib             0x00007ff8019284f4 _pthread_start + 125
	9   libsystem_pthread.dylib             0x00007ff80192400f thread_start + 15
)
libc++abi: terminating with uncaught exception of type NSException
```

no `sa` I can't create space

**Comment by marquisXuan** [comment]
![Uploading 截屏2022-03-05 下午2.03.34.png…]()

**Comment by Tweoss** [comment]
Hi @marquisXuan, 
Have you checked out the issue for yabai on Monterey? Try `brew install yabai --head`, that may give you a version that is more up to date for Monterey.

**Comment by marquisXuan** [comment]
Thanks ~ 
I fllow this command `brew install yabai —head`, then it  works ! 
But when I exec `yabai -m space —create` that say : “command not found : Jenny_prompt_info “ , it’s means my env isn’t right? How I fix it ?
Thanks ~ Thanks ~ Thanks ~








On 03/6/2022 02:00，Francis ***@***.***> wrote：

Hi @marquisXuan,
Have you checked out the issue for yabai on Monterey? Try brew install yabai --head, that may give you a version that is more up to date for Monterey.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by marquisXuan** [comment]
Oh no, maybe it’s not yabai 
Maybe it’s java wrong
Thank you very much~~~


On 03/6/2022 ***@***.***> wrote：
Thanks ~ 
I fllow this command `brew install yabai —head`, then it  works ! 
But when I exec `yabai -m space —create` that say : “command not found : Jenny_prompt_info “ , it’s means my env isn’t right? How I fix it ?
Thanks ~ Thanks ~ Thanks ~








On 03/6/2022 02:00，Francis ***@***.***> wrote：

Hi @marquisXuan,
Have you checked out the issue for yabai on Monterey? Try brew install yabai --head, that may give you a version that is more up to date for Monterey.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mcstrassell09** [comment]
I believe the command ```sudo yabai --install-sa``` is meant for macOS prior to Big Sur. This is why you are getting the error. If you are running Big Sur or later you want to use ``` sudo yabai --load-sa``` instead. Also,  follow the instructions in the install guide to auto load the script. I am running Monterery 12.3 Beta and seems to be working.

**Comment by marquisXuan** [comment]
> Hi @marquisXuan, Have you checked out the issue for yabai on Monterey? Try `brew install yabai --head`, that may give you a version that is more up to date for Monterey.

Thanks~ it works

**Comment by marquisXuan** [comment]
> I believe the command `sudo yabai --install-sa` is meant for macOS prior to Big Sur. This is why you are getting the error. If you are running Big Sur or later you want to use ` sudo yabai --load-sa` instead. Also, follow the instructions in the install guide to auto load the script. I am running Monterery 12.3 Beta and seems to be working.

yeah~ I use ```brew install yabai --HEAD```  reinstalled. then the comman ```shell sudo yabai --install-sa``` works~ thanks everyone
