### ISSUE TITLE
Adding window borders break Zoom share screen display name

### ISSUE THREAD

**Issue by arnavsharma93** [koekeishiya/yabai#1178]
OS：Monterey 12.0
yabai: HEAD [34d31e8](https://github.com/koekeishiya/yabai/commit/34d31e8c1b6c0969dc4181f521aa2edb8757b805)
/usr/local/bin/yabai: Mach-O 64-bit executable x86_64
System Integrity Protection status: disabled.

Adding window borders break Zoom share screen display name. 

### Without window borders
![Screenshot 2022-03-07 at 8 34 52 PM](https://user-images.githubusercontent.com/1503614/157061390-722ed8b4-bfd3-4e2f-a3e5-7b73529da6a3.png)

### With window borders
![Screenshot 2022-03-07 at 8 36 46 PM](https://user-images.githubusercontent.com/1503614/157061430-9556510e-c2c2-42f6-98d7-c4d8ee6da160.png)

**Comment by koekeishiya** [comment]
Borders have been removed in the latest release (v6.0.0) (#1889) because of multiple issues present in both Ventura and Sonoma.
