### ISSUE TITLE
Detect spaces moved to another display using Mission Control

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#118]
### Bug report

This came up during the testing of #112.

Imagine the following scenario: 
- Displays A (spaces A1, A2), B (space B1)
- Focus A2 and drag A1 to B using Mission Control

yabai now no longer recognises A1. If the displays had different sizes, windows moved with the display would not get resized at all. Opening new windows on A1 moves them to and tiles them on A2.

**Comment by koekeishiya** [comment]
I have no idea how we can detect this. A bad solution would be to just invalidate spaces after exiting mission-control.

**Comment by dominiklohmann** [comment]
Keep a cache of space ids in order per display. When leaving Mission Control, check if any space id moved to another display. If any moved, act as if the space was moved by `yabai -m space <sel> --display <sel>`.

Note that only spaces that are not currently visible can be moved to another display using Mission Control.

**Comment by koekeishiya** [comment]
Might as well just mark all views invalid then, as I think that is less (or equal) work for the system, yet currently a one-liner to implement.
