### ISSUE TITLE
Request: Add role and subrole to rules config options: Open/Save file dialog for Chrome

### ISSUE THREAD

**Issue by JacobRReed** [koekeishiya/yabai#1181]
Propose adding role and subrole options to the rule command so we can target those parameters

### Discussed in https://github.com/koekeishiya/yabai/discussions/1179

<div type='discussions-op-text'>

<sup>Originally posted by **JacobRReed** March  7, 2022</sup>
I have the following rule for Chrome:
`yabai -m rule --add app=".*Chrome.*" title=".*" opacity=1.0 space=top grid=1:5:2:0:3:1 manage=off`
but when I open a open/save file dialog in Chrome it is very odd appearing. Is there any way to fix this? I did a query and found that Google Chrome opens a `role="AXSheet"` for the dialog, so I tried adding:
`yabai -m rule --add app=".*Chrome.*" title="^$" role=".*AXSheet.*" opacity=1.0 manage=off` but doesn't seem to help.
Any suggestions? I just want my open/save dialog to be normal, or float in middle of screen even idc, but right now it expand the size of chrome's window, then when I close it, it repositions my chrome browser into an odd space

When I open a dialog:
![image](https://user-images.githubusercontent.com/25580051/157067644-18f1a33d-76bd-44e8-8c68-52893479358f.png)

After I close the dialog: (It repositions the original chrome window)
![image](https://user-images.githubusercontent.com/25580051/157068112-18e97ea0-b155-41f3-884c-f801ad686602.png)

</div>

**Comment by koekeishiya** [comment]
This has been added.
