### ISSUE TITLE
Failed on M1: Automatically load scripting addition on startup

### ISSUE THREAD

**Issue by SichangHe** [koekeishiya/yabai#1183]
I tried [Automatically load scripting addition on startup](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#macos-big-sur-and-monterey---automatically-load-scripting-addition-on-startup) and it does not work upon reboot
``` shell
$ yabai -m space --focus next
yabai-msg: failed to connect to socket..
```
After quitting *Finder* and opening it again, which supposedly trigger the script addition to load again, it becomes
```shell
$ yabai -m space --focus next
cannot focus space due to an error with the scripting-addition.
```
It works, however, if I manually do
```shell
sudo yabai --load-sa
```

### what I did according to *Automatically load scripting addition on startup*
```shell
sudo visudo -f /private/etc/sudoers.d/yabai
```
add this line to the opened file
```
sichanghe ALL = (root) NOPASSWD: /opt/homebrew/bin/yabai --load-sa
```
add these two lines to `yabairc`
```shell
sudo /opt/homebrew/bin/yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"
```

_Originally posted by @SichangHe in https://github.com/koekeishiya/yabai/issues/1158#issuecomment-1060194771_

**Comment by Tweoss** [comment]
@SichangHe I just checked the M1 / Monterey issue and one of the possible ways to run the restart action was `pkill Dock`. Perhaps that could work? Running `brew services restart yabai` might also work out.

**Comment by SichangHe** [comment]
> @SichangHe I just checked the M1 / Monterey issue and one of the possible ways to run the restart action was `pkill Dock`. Perhaps that could work? Running `brew services restart yabai` might also work out.

Are you suggesting that I add one of these to `yabairc`?
I can get `yabai` working with script addition just by manually running `sudo yabai --load-sa` every time I reboot.
*The problem here* is I cannot get it to load *automatically* on startup.

**Comment by Tweoss** [comment]
> > @SichangHe I just checked the M1 / Monterey issue and one of the possible ways to run the restart action was `pkill Dock`. Perhaps that could work? Running `brew services restart yabai` might also work out.
> 
> 
> 
> Are you suggesting that I add one of these to `yabairc`?
> 
> I can get `yabai` working with script addition just by manually running `sudo yabai --load-sa` every time I reboot.
> 
> *The problem here* is I cannot get it to load *automatically* on startup.

Ah, I see so the issue occurs every reboot. I haven't actually tried rebooting since I fixed my configuration up, so I'll try in a bit and let you know if I have the same issue.

**Comment by Tweoss** [comment]
I did reboot, and my yabai config is still working as expected. I've followed the exact same steps as you have, so I'm not sure why you have to load the addition manually and if there are any ways to resolve it.

**Comment by koekeishiya** [comment]
The instructions work fine on both my Intel and Apple Silicon machine, so I am assuming user error here, as it also seems to work for other people.
