### ISSUE TITLE
Windows swapping positions on screen during work.

### ISSUE THREAD

**Issue by auraz** [koekeishiya/yabai#1185]
Example: I have Iterm2 and Sublime opened half screen both. Then they swapped places on the screen. 
When: Issue appeared immediately after upgrading to Monterey
Proof: [Screencast](https://www.loom.com/share/f93f7aa5592341b8aac2ad65fdb795ea). The issue randomly repeats for different applications.

**Comment by Jeshii** [comment]
This has gotten worse for me recently. I'm not sure what changed, but every 5-10 seconds all the windows shift around. It's visually jarring and has made it the first time I've disabled yabai in months.

**Comment by cdkini** [comment]
I'm seeing this a lot more now that I've upgraded to macOS Monterey v12.2.1

**Comment by koekeishiya** [comment]
Update to v4.0.0.

**Comment by auraz** [comment]
Thank you.
