### ISSUE TITLE
how to make child windows for applications not managed?

### ISSUE THREAD

**Issue by theTechGoose** [koekeishiya/yabai#1186]
When I am typing into the url bar on safari there used to be a window that suggested websites, upon further inspection that window is still there but under the safari window, rendering it invisible. the same thing happens on several other apps.

I am on Mac OS Monterey 12.1

**Comment by typkrft** [comment]
I don't know if there's a fix for this. I think it has to do with topmost, it needs to be set to off. There's been several issues relating to this. 

`yabai -m config window_topmost off`

**Comment by koekeishiya** [comment]
Resolved in latest version.
