### ISSUE TITLE
How to get yabai to size and move my windows automatically

### ISSUE THREAD

**Issue by Rofer11607** [koekeishiya/yabai#1187]
Every time I restart yabai I have to resize all my windows so that they are correct, Is there a way to set it so that I can do safari 20%, kitty 60% chrome dev tools 20%?

I saw a grid with the rules but I am super confused by this. Currently resize bound to keys and manually doing this
![image](https://user-images.githubusercontent.com/55964540/157737625-7be987f1-ed10-44ee-b9fe-0bd4619bd5f6.png)

I could adjust the values for every key however when I resize one window, the dimensions for the other windows change. 

Please help.

**Comment by koekeishiya** [comment]
You can use the bsp layout, and script the behaviour using signals.
