### ISSUE TITLE
Request/Idea: Toggleable "adjustment mode"

### ISSUE THREAD

**Issue by leftbones** [koekeishiya/yabai#1188]
I've been screwing around with Linux lately and found Pop!_OS has a nice tiling manager built in, but only allows you to move/resize windows in an "adjustment mode" that you enter and exit with keyboard shortcuts.

This might be a handy feature to have, it would free up a lot of keys to be used as shortcuts. Example: Normally, the H key is reserved for... The letter H. However, if I entered "adjustment mode", the H key could then be used for moving windows, and wouldn't perform its normal functions until adjustment mode was exited.

Not sure if this is really even possible, honestly.

**Comment by typkrft** [comment]
You can setup modal keybindings with SKHD. 

For instance in my setup I have what I call Window Mode, when I press Fn+Esc which allows me to manage, resize, adjust windows.
