### ISSUE TITLE
[Monterey 12.3.0 Update] yabai scripting-addition, "payload (0x0 doesn't support this macOS version!)"

### ISSUE THREAD

**Issue by ericlovesmath** [koekeishiya/yabai#1192]
Upon upgrading to MacOS 12.3.0, yabai's scripting addition stopped working properly.

Do you need me to send over any files to support the new update? Thank you!

SIP is disabled:
```>>> csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled```

**Comment by Megum1n** [comment]
The issue was already mentioned in https://github.com/koekeishiya/yabai/issues/1142
I guess we should just wait for a fix.

**Comment by theniceboy** [comment]
Though it's good to have an issue tracker for macOS 12.3. I'm guessing that Universal Control messed up things.

**Comment by ericlovesmath** [comment]
Makes sense to me; 12.3 is out of beta though, which is why I opened it again @Megum1n

**Comment by gservat** [comment]
Ugh I wish I never updated to 12.3 :( Getting the same on an M1 Mac:

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/1061151/158493745-931b3b75-1eb0-4600-a3fa-f2fb8a080ad9.png">

**Comment by gservat** [comment]
As a workaround, since `yabai -m space --focus X` is broken but `yabai -m window X --focus` is not, I've got a bunch of shortcuts set-up in Alfred to switch to the main apps I'm using so, for example, if I press CMD-W, it calls:

```
yabai -m window $(yabai -m query --windows | jq '[.[] | select(.app == "'{query}'")] | first | .id') --focus
```

... where `query` is eg. "Google Chrome".

Still miss being able to move windows around to different spaces though 😢

**Comment by theniceboy** [comment]
> fixed on master.

ありがとう！！

🎉🎉🎉
