### ISSUE TITLE
M1 Monterery 12.3 Top-padding not working when menu bar is visible

### ISSUE THREAD

**Issue by p1k0pan** [koekeishiya/yabai#1193]
My menubar is visible but still have top gaps

<img width="579" alt="Screen Shot 2022-03-16 at 10 56 44" src="https://user-images.githubusercontent.com/36180022/158507871-0cd13d08-b25b-4ba5-847c-0005a0ef9c65.png">

I have tried `yabai -m config external_bar all:24:0`  but still not working

 ----
BTW I tried `brew install yabai --HEAD`, and access message just keep poping even I have already allowed the control.

<img width="884" alt="Screen Shot 2022-03-16 at 10 53 00" src="https://user-images.githubusercontent.com/36180022/158508204-753d44a7-6c81-44a3-88df-eb80e3fdff2a.png">

**Comment by p1k0pan** [comment]
I have rebuilded the master source code, and resigned the yabai-cert. This time not keep poping message and `yabai --version` shows `yabai-v4.0.0`

But `yabai -m config external_bar all:24:0` seems still not working and top gaps still there

**Comment by koekeishiya** [comment]
`external_bar` is supposed to be used if you are *not* using the macOS menubar. You want `yabai -m config external_bar off:0:0`

**Comment by p1k0pan** [comment]
That's right! Work fine now. Thanks!!
