### ISSUE TITLE
M1 - After Monterery 12.3 upgrade space focus not working

### ISSUE THREAD

**Issue by rayjanoka** [koekeishiya/yabai#1194]
Everything was working, but now i can't change space focus after installing Monterey 12.3.

I verified I still have SIP disabled.

I see this in the logs after sending the command, but that's about it.
```
EVENT_HANDLER_DAEMON_MESSAGE: space --focus next
```

**Comment by ericlovesmath** [comment]
`yabai -m space --focus next` works fine for me with SIP disabled, you might want to also add your config here

**Comment by net** [comment]
Looks like it's fixed on master. See #1192.

**Comment by rayjanoka** [comment]
That did the trick. thanks!

```shell
brew services stop yabai
brew remove yabai
brew install koekeishiya/formulae/yabai --HEAD

codesign -fs 'yabai-cert' $(which yabai)
brew services start yabai

sudo yabai --install-sa
sudo yabai --load-sa
```
