### ISSUE TITLE
Opacity affects dropdowns in active application

### ISSUE THREAD

**Issue by jessemillar** [koekeishiya/yabai#120]
It appears that setting `normal_window_opacity` to a non-`1` value causes dropdowns (e.g. URL suggestions in Firefox and non-styled HTML dropdowns on web pages) to be transparent. I couldn't find anything obvious in the docs about how to disable or modify this.

[This is my `.yabairc` config](https://github.com/jessemillar/dotfiles/blob/71d32c4c00a82c27c602200417b9561082e60370/.yabairc) and I'm running without SIP enabled and with the scripting-addition installed. 

I'm not sure if this is somehow related to https://github.com/koekeishiya/yabai/issues/33

**Comment by dominiklohmann** [comment]
Definitely not related to the linked issue. It's likely that Firefox spawns some windows that are recognised as non-focused windows, e.g. the URL dropdown. You can list all windows recognised by yabai on the focused space by running `yabai -m query --windows --space | jq` (get jq using `brew install jq` if you don't have it already). You will likely notice multiple Firefox entries while the Firefox URL dropdown is active.

**Comment by dominiklohmann** [comment]
Installed Firefox and confirmed my suspicion. Notice how there's an additional Firefox window with a subrole of `AXUnknown`, which is the URL dropdown.

@koekeishiya Is there a specific reason not to ignore `subrole=AXUnknown` completely? Chrome has the same issue.

```json
λ yabai -m query --windows --space | jq
[
  {
    "id": 80739,
    "pid": 97250,
    "app": "Firefox",
    "title": "",
    "frame": {
      "x": 20,
      "y": 116,
      "w": 810,
      "h": 355
    },
    "level": 0,
    "role": "AXWindow",
    "subrole": "AXUnknown",
    "movable": 1,
    "resizable": 0,
    "display": 1,
    "space": 2,
    "focused": 0,
    "split": "none",
    "floating": 1,
    "sticky": 0,
    "border": 0,
    "zoom-parent": 0,
    "zoom-fullscreen": 0,
    "native-fullscreen": 0
  },
  {
    "id": 80725,
    "pid": 97250,
    "app": "Firefox",
    "title": "",
    "frame": {
      "x": 20,
      "y": 42,
      "w": 810,
      "h": 988
    },
    "level": 0,
    "role": "AXWindow",
    "subrole": "AXStandardWindow",
    "movable": 1,
    "resizable": 1,
    "display": 1,
    "space": 2,
    "focused": 1,
    "split": "vertical",
    "floating": 0,
    "sticky": 0,
    "border": 0,
    "zoom-parent": 0,
    "zoom-fullscreen": 0,
    "native-fullscreen": 0
  },
  {
    "id": 80734,
    "pid": 96090,
    "app": "iTerm2",
    "title": "",
    "frame": {
      "x": 850,
      "y": 42,
      "w": 810,
      "h": 988
    },
    "level": 0,
    "role": "AXWindow",
    "subrole": "AXStandardWindow",
    "movable": 1,
    "resizable": 1,
    "display": 1,
    "space": 2,
    "focused": 0,
    "split": "vertical",
    "floating": 0,
    "sticky": 0,
    "border": 0,
    "zoom-parent": 0,
    "zoom-fullscreen": 0,
    "native-fullscreen": 0
  }
]
```

**Comment by koekeishiya** [comment]
I think it had something to do with how all windows had to be known, in the offchance that a window is made topmost - then all its child windows must also be made topmost, and so we have to know about them.

I suppose the opacity functionality could filter away all non-standard windows, if that feels more appropriate.

**Comment by dominiklohmann** [comment]
I think this applies to both opacity and also window queries.

**Comment by koekeishiya** [comment]
The reason they are a part of window queries is so that people can find windows that really should be managed and write appropriate rules, *cough*Emacs people*cough*

**Comment by dominiklohmann** [comment]
Alright, I'll better get used to writing `map(select(.subrole != \"AXUnknown\"))` then. 🤷‍♂

**Comment by koekeishiya** [comment]
Opacity will now only apply to windows that report a role of AXStandardWindow or AXDialog.
