### ISSUE TITLE
Request for more clarity on the yabairc file

### ISSUE THREAD

**Issue by didrio** [koekeishiya/yabai#1203]
Hello, I'm on Monterey so I'm attempting to edit the yabairc file based off this: 

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

But I have no idea where the yabairc file is, even when I google for answers or search my entire hard drive in finder. I'm not great at OS level stuff and this is my first time using yabai, so just wanted to bring up that it's not obvious where this file is for me. And when I search yabairc in this nothing comes up: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc

**Comment by 24unix** [comment]
When you follow own(!) link, there is a link called configuration file.

https://github.com/koekeishiya/yabai/wiki/Configuration#configuration-file

**Comment by didrio** [comment]
@24unix thank you, my bad lol
