### ISSUE TITLE
Update MacPorts version to 4.0.0

### ISSUE THREAD

**Issue by nalzok** [koekeishiya/yabai#1204]
The current version os MacPorts is still `v3.3.10`

```
$ sudo port info yabai
yabai @3.3.10 (sysutils)
Variants:             universal

Description:          yabai is a window management utility that is designed to work as an extension to the built-in window manager of
                      macOS.
Homepage:             https://github.com/koekeishiya/yabai

Platforms:            darwin
License:              MIT
Maintainers:          Email: macports@thekev.in, GitHub: thekevjames
                      Policy: openmaintainer
```

I was planning to open a pull request, but the version number `v4.0.0` indicates there will likely be a breaking change, so I think [the job](https://github.com/macports/macports-ports/tree/master/sysutils/yabai) is best left to someone with more expertise.

**Comment by Ci7rix** [comment]
The package was updated to version 4.0.1. I have a pull request pending for version 4.0.2.
