### ISSUE TITLE
Yabai config file not found

### ISSUE THREAD

**Issue by Vib1240n** [koekeishiya/yabai#1209]
I upgraded to Yabai 4.0.0 and I keep getting this notification yabai configuration: unable to locate config file and I keep have to restarting Yabai follow focus mouse. 
Initially I started with yabai -m config focus_follow_mouse autofocus but I have keep running this command whern that notification pops up. 
Is there any reason why this keep happening?

**Comment by koekeishiya** [comment]
Check and verify that your config file is in one of the following locations, and that is marked as executable:

```
$XDG_CONFIG_HOME/yabai/yabairc
$HOME/.config/yabai/yabairc
$HOME/.yabairc
```

**Comment by Mickychen00** [comment]
Does the first two locations contain "."?  It seems that only the third config file's name contains "."

**Comment by nsirimo** [comment]
Incase someone ever runs into this again one day, yes you are not supposed to have the "." infront of the .yabairc if you are placing it inside your $HOME/.config/yabai/

**Comment by mitscodes** [comment]
> Check and verify that your config file is in one of the following locations, and that is marked as executable:
> 
> ```
> $XDG_CONFIG_HOME/yabai/yabairc
> $HOME/.config/yabai/yabairc
> $HOME/.yabairc
> ```

if no config file is present is it safe to just create one?
