### ISSUE TITLE
When dragging multiple windows between monitors via Mission Control, yabai reverts all but one

### ISSUE THREAD

**Issue by daboross** [koekeishiya/yabai#1211]
If I open Mission Control, and drag one window from Monitor 1 to Monitor 2, yabai registers it correctly and fits the window into the tiling in Monitor 2.

However, if I open Mission Control, drag one window from Monitor 1 to Monitor 2, then drag a second window from Monitor 1 to Monitor 2, then close Mission Control, yabai will only move the first window and revert the second back to Monitor 1. Or, in some cases, revert both windows to Monitor 1 - I'm not 100% sure what the difference is between these two situations.

I'm using macOS Big Sur 11.6.4 and yabai-v3.3.10.

**Comment by koekeishiya** [comment]
Sounds like https://github.com/koekeishiya/yabai/issues/820

 Upgrade to v4.0.0.
