### ISSUE TITLE
Focus a window after minimizing a floating window

### ISSUE THREAD

**Issue by hahuang65** [koekeishiya/yabai#1212]
After calling `yabai -m window $WINDOWID --minimize` on a floating window, no windows in the current space are focused.
I need to use the mouse to click on a window to focus.

I've tried `yabai -m window --focus prev` and that doesn't seem to help in this situation.

Is there a way to fix this without having to reach for my mouse?

**Comment by koekeishiya** [comment]
You could probably hook up a signal to the minimized event, and have it focus something else

**Comment by hahuang65** [comment]
I'm not sure how to do that... Is there any documentation you could point me towards?

**Comment by koekeishiya** [comment]
Documentation on this area is sparse: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#signal
Scripts written to react to signals frequently utilise the query system to do anything useful: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#query

The following signal should do the trick; add this to your yabairc file:

```
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"
```

The way this works is basically, you subscribe to an event that yabai sends when a window is minimised. The `active` key is a filter that makes sure that this particular script is only run if the window that was minimised was the one with key-focus.

The action is the actual script. In this case I have written it inline, but you can also make it execute a script/binary-file instead. This script first queries information about the minimised window, to check if it is marked as floating. If it is a floating window we first check to see if macOS set a new focused windowed automatically, and if no focus was detected, we first attempt to focus the window under the cursor, or fall back to focusing the window on the current space that was the most recently focused window.

Combining signals and queries can allow for some powerful scripting, although I do not particularly use it in any advanced ways myself.

**Comment by hahuang65** [comment]
Thank you for that snippet!
