### ISSUE TITLE
Border color overridden by default colors

### ISSUE THREAD

**Issue by ryantking** [koekeishiya/yabai#1214]
### System

**OS:** 12.3
**Version:** yabai-v4.0.0

### Relevant Config

```
yabai -m config window_border on
yabai -m config active_window_border_color 0xFF88C0D0
yabai -m config normal_window_border_color 0x002E3440
yabai -m config insert_feedback_color 0xFFA3BE8C
```

### Details

When I enable the border, upon restarting yabai, I can see the correct border colors. Once I change the active windows, the border gets overridden by a green color. I could not find any setting to change that would change either of these colors.

**Comment by FelixKratz** [comment]
Correct me if my guess is wrong, but I suspect you might be using [SketchyBar](https://github.com/FelixKratz/SketchyBar) with my [yabai.sh](https://github.com/FelixKratz/dotfiles/blob/master/.config/sketchybar/plugins/yabai.sh) script? I change the active border color in there based on the state of the window (parent-zoom, fullscreen-zoom, stack, etc.) and the green color is my preferred default border color.

**Comment by ryantking** [comment]
@FelixKratz You are 100% correct. Thanks for the help and for sketchybar, which is absolutely fantastic.
