### ISSUE TITLE
how to disable border?

### ISSUE THREAD

**Issue by ixzh** [koekeishiya/yabai#1218]
I have small screen space and the default border is too thick. Plus it is not responsive and has this side effect:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14981695/161217442-cbd1e610-590e-42a3-b041-18a77ae971b0.png">

I have set the width to 1 and window border to off, yet it still shows. Any idea? Thanks

**Comment by koekeishiya** [comment]
Are you talking about the default macOS borders? If so, these cannot be removed by third-party software.

**Comment by koekeishiya** [comment]
Right, so just add `yabai -m config window_border off` in your config to disable them.

**Comment by restfuladi** [comment]
> Right, so just add `yabai -m config window_border off` in your config to disable them.

Would it be possible to add an option where borders are only drawn on managed windows? Something like `yabai -m config window_border managed`, similar to `yabai -m config window_shadow float`? Thanks.
