### ISSUE TITLE
Can not handle pop-up window

### ISSUE THREAD

**Issue by AurevoirXavier** [koekeishiya/yabai#1219]
```
"id":189572,
"pid":2726,
"app":"Microsoft Edge Dev",
"title":"polkadot{.js}"

yabai -m rule --add app="^Microsoft Edge Dev$" title="^polkadot\{\.js\}$" manage=off
```

When I use `brew service restart yabai`. It can ignore that(*polkadot{.js}*) window.
But every time when it pop-up, yabai still controls it and split my screen into two spaces.

**Comment by koekeishiya** [comment]
Can you enable debug_output and check what's written to the log when the window pop-up is created? I assume it spawns with an empty title or something, and quickly changes title afterwards, so the rules does not detect it.

There has been some previous discussion in which rules should be re-evaluated upon title-change, but for reasons I don't remember, this did not get implemented.

**Comment by AurevoirXavier** [comment]
> Can you enable debug_output and check what's written to the log when the window pop-up is created? I assume it spawns with an empty title or something, and quickly changes title afterwards, so the rule does not detect it.
> 
> There has been some previous discussion in which rules should be re-evaluated upon title-change, but for reasons I don't remember, this did not get implemented.

Awesome! I add the `title="^$" manage=off`. Works!

**Comment by bin101** [comment]
I also had to add `yabai -m rule --add app="^coreautha$" manage=off` for the touch id dialog, but now it's working fine, thanks ;)
