### ISSUE TITLE
Load config file after startup

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#122]
### Suggestion

I was trying to make yabai register every window by running this command in my yabairc. This fails, because the query system is initialised after the configuration file is loaded.

I think the only feature that needs to be initialised after loading the config file is the status bar, as its config options cannot be set during runtime.

```sh
# visit all spaces once, then return to visible and focused spaces like before
yabai -m query --spaces \
    | jq "sort_by(.focused, .visible) | .[].index" \
    | xargs -I{} yabai -m space --focus {}
```

**Comment by koekeishiya** [comment]
There is one slight problem with doing this - window border changes don't affect already created windows. I don't remember any other reasons at the moment for why initialization happens in this order.

**Comment by dominiklohmann** [comment]
This brings back something I've thought about a while ago:

Support the XDG base directory spec: Check for the configuration file in the following places (in order):
- `${XDG_CONFIG_HOME}/yabai/config`
- `${HOME}/.config/yabai/config`
- `${HOME}/.yabairc`

This could then be extended to search for another optional file in the yabai config directory (if it is used over a `.yabairc` file) that is executed after yabai finished initialising. 

```sh
.config/yabai/
├── config        # loaded during init
└── autoload      # loaded after init
```

**Comment by koekeishiya** [comment]
> This could then be extended to search for another optional file in the yabai config directory (if it is used over a .yabairc file) that is executed after yabai finished initialising.

I think the correct solution for this issue is to make the remaining config settings able to run without having to care which init state *yabai* is currently in, and then make execution of the config file happen at the end when all other things that need to happen have finished.

Created issue https://github.com/koekeishiya/yabai/issues/125 for *XDG_CONFIG_HOME*.

**Comment by koekeishiya** [comment]
Fixed on master. The config is now ran *asynchronusly* by yabai after all initialization and whatever has finished. Because of this every single command can now be used at runtime with immediate effect.
