### ISSUE TITLE
Chromium pop-ups not working?

### ISSUE THREAD

**Issue by gmenih** [koekeishiya/yabai#1221]
I recently upgraded to macOS 12.1, and had to re-disable SIP as it got enabled again, and some of my keybindings weren't working.

Since then I've been noticing issues in Chromium based browsers, where any popup in the browser won't work properly. Meaning, I can't see any extension pop-up menus, the omnibox, permission prompts when visiting websites, etc... It seems to appear sometimes, if I toggle the float mode of the window, but still inconsistent.

I've had this issue in Brave, Brave Beta and Chrome.

I'm running `yabai-v4.0.0`

Could Yabai be causing this, or is it an unrelated issue?

**Comment by koekeishiya** [comment]
uh sounds like a problem with `window_topmost` setting. try disabling it for now.

**Comment by gmenih341** [comment]
I've disabled it, thanks. I'll report back in a few days if that was the issue.

**Comment by gmenih341** [comment]
Looks like this was the problem. It works fine since disabling this.

**Comment by pmourer-zaneray** [comment]
Thank you! was also having this issue on Monterey, resolved for me as well.

**Comment by remi-gelinas** [comment]
I'm having the issue on Monterey as well, but setting `window_topmost` to `off` doesn't fix the popups. Am I disabling the option incorrectly?

**Comment by gmenih341** [comment]
> Am I disabling the option incorrectly?

How are you disabling it? You need to add it to your `~/.yabairc`  file, and then re-load yabai `. ~/.yabairc`

**Comment by koekeishiya** [comment]
Fixed in v6.0.0
