### ISSUE TITLE
`yabai: could not access accessibility features! abort..` after rebooting computer.

### ISSUE THREAD

**Issue by SxC97** [koekeishiya/yabai#1222]
I keep getting the error `yabai: could not access accessibility features! abort..` when I run `cat /usr/local/var/log/yabai/yabai.err.log`. 

Here is a screenshot of what my accessibility settings look like. I also keep getting the popup saying yabai would like accessibility permissions. Clicking deny just spawns a new, identical window.

<img width="800" alt="Screen Shot 2022-04-04 at T21 07 53" src="https://user-images.githubusercontent.com/53032923/161665230-218d6e6a-dd38-4d43-b286-c449a45f9b0c.png">

I have already tried reinstalling yabai and installing yabai from `--HEAD` but with no progress. I am currently on MacOS 12.3 on an M1 Max MacBook Pro if that helps in debugging.

**Comment by SxC97** [comment]
fixed it by following [these](https://github.com/koekeishiya/yabai/issues/867#issuecomment-1070721122) steps

**Comment by trqminh** [comment]
Hi @SxC97,
I am having the same problem as you had. I try the reference steps but it's not working.

In specific, I uninstalled everything, the reinstalled yabai again as follows:
```
curl -L https://raw.githubusercontent.com/koekeishiya/yabai/master/scripts/install.sh | sh /dev/stdin
ls -l $(which yabai) # -rwxr-xr-x@ 1 tqminh  wheel  1683792 Jul 30 22:02 /usr/local/bin/yabai
```
then I ran `yabai --start-service` and gave the accessibility. However I still got `yabai: could not access accessibility features! abort..` in the log file. I tried the codesign command:
```
codesign -fs 'yabai-cert' /usr/local/bin/yabai
```
but got the error: `error: The specified item could not be found in the keychain.`

Would you mind helping me to take a look at this? Thank you for your consideration.

**Comment by SxC97** [comment]
Hi @trqminh, I took a look at your issue and I think the issue here is that either you didn't create a self-signed certificate, or you created it with a different name than "yabai-cert". I would double check to make sure you followed the steps laid out here correctly.

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

**Comment by trqminh** [comment]
Thank you very much @SxC97. It is working now!!
