### ISSUE TITLE
Discord not sticking to boundaries

### ISSUE THREAD

**Issue by krims0n32** [koekeishiya/yabai#1223]
Hello, first of all, thank you for an awesome tool. As an avid Linux bspwm user, yabai really is awesome to use on my Macbook.

I have a small issue with Discord, on a space I have Telegram desktop open, when I open Discord, it seems Yabai properly places and sizes it next to Telegram but almost immediately Discord grows it window making it fall off-screen. It probably is forcing some minimum width here. Is there a Yabai rule or something that I can use to make Discord behave? Can I perhaps set a split ratio for Discord only?

Thanks!

**Comment by peppy** [comment]
If you are trying to have yabai resize discord below its minimum width, that would be the issue (making this work is likely out of scope for yabai). Hard to say without a screenshot or video showing what is going on.

**Comment by koekeishiya** [comment]
A reasonable solution to the minimum-size problem was proposed a long time ago: https://github.com/koekeishiya/yabai/issues/235 , but I have not taken the time to actually try and implement it. I suppose if done well, it could improve the experience quite a lot for people that use one or more such applications frequently.

You could probably make some scriptable workaround using a combination of signals, queries and rules, but I don't think it would be as seamless as if yabai just tried to do this internally.

**Comment by tradiff** [comment]
Just leaving this here for future readers of this thread. For Discord specifically, you can remove the minimum width using these steps:

Edit `~/Library/Application Support/discord/settings.json`

settings.json should look like this:
```json
{
  "IS_MAXIMIZED": false,
  "IS_MINIMIZED": false,
  "WINDOW_BOUNDS": {
    "x": 500,
    "y": 23,
    "width": 940,
    "height": 977
  }
}
```

Change it to add MIN_WIDTH and MIN_HEIGHT like so:
```json
{
  "IS_MAXIMIZED": false,
  "IS_MINIMIZED": false,
  "MIN_WIDTH": 0,
  "MIN_HEIGHT": 0,
  "WINDOW_BOUNDS": {
    "x": 500,
    "y": 23,
    "width": 940,
    "height": 977
  }
}
```

Save the file and restart Discord. You should be able to resize the window even smaller now.

source:
https://www.reddit.com/r/discordapp/comments/acog0e/remove_minimum_size_of_discord_window_windowsmac/
