### ISSUE TITLE
[Help] Changing top_padding when a certain resolution is set for

### ISSUE THREAD

**Issue by hkgnp** [koekeishiya/yabai#1224]
Hi!

Was wondering if any one would be able to shed light on the above. I use a Macbook Pro and I either use it on laptop mode, or in clamshell mode connected to an external monitor.

In laptop mode, `0` for the top padding works but for my external monitor in clamshell mode, `34` for the top padding is needed. 

As the resolution for my laptop and my monitor are different (3456 x 2234 vs 1920 x 1080), I was wondering if it is possible to set top padding of 34 if yabai detects 1920 x 1080 and sets to 0 if yabai detects 3456 x 2234.

Thanks in advance!

**Comment by koekeishiya** [comment]
You could run a display query in your yabairc and check either the resolution or uuid of your display and set the padding accordingly. To get information about all connected displays, use: `yabai -m query --displays`. See https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#query

**Comment by hkgnp** [comment]
@koekeishiya Thanks! I took a slightly different approach.

Posting the solution here for those who need it:

`set_padding.py`
```python
import subprocess

output = subprocess.run(["yabai","-m","query","--displays"],capture_output=True,text=True)
output_text = output.stdout.strip()
output_obj = eval(output_text)
width = (output_obj[0]["frame"]["w"])

if width == 1920.0:
    subprocess.run(["yabai","-m","config","top_padding","34"])
    print("Padding set to 34")
else:
    subprocess.run(["yabai","-m","config","top_padding","0"])
    print("Padding set to 0")

```

`yabairc`
```
...

yabai -m signal --add event=display_changed action="python3 ~/.config/yabai/set_padding.py"

...
```

**Comment by mizlan** [comment]
Hi @koekeishiya Is there a way to set a different `top_padding` for each display?

**Comment by mizlan** [comment]
Got it: https://github.com/koekeishiya/yabai/issues/598

**Comment by mjamezquidilla** [comment]
Updated solution posted by @benjypng 

`set_padding.py`

```python
import subprocess
import json

# Current Yabai version returns JSON format
output = subprocess.run(
    ["yabai", "-m", "query", "--displays"], capture_output=True, text=True
)
output_obj = json.loads(output.stdout)

# The width parameter can now be obtained
width = output_obj[0]["frame"]["w"]

if width == 1920.0:
    subprocess.run(["yabai","-m","config","top_padding","34"])
    print("Padding set to 34")
else:
    subprocess.run(["yabai","-m","config","top_padding","0"])
    print("Padding set to 0")
```

no changes in the `yabairc` file.

EDIT: specified the python file that was changed `set_padding.py` for clarity.
