### ISSUE TITLE
yabai: could not acquire lock-file! abort..

### ISSUE THREAD

**Issue by eyalch** [koekeishiya/yabai#1228]
Hi, I'm getting the following error when trying to run `yabai`:

```sh
$ yabai
yabai: could not acquire lock-file! abort..
```

I'm using Apple Silicon on macOS 12.3.1.

I followed the installation instructions very carefully. I (partially) disabled SIP. Not sure what I'm doing wrong.

**Comment by 24unix** [comment]
rm /tmp/yabai*

**Comment by eyalch** [comment]
> rm /tmp/yabai*

Already tried this, and rebooted afterwards (just in case). Still the same error.

**Comment by 24unix** [comment]
macOs is not Windows. No need to reboot for nothing.

What does 
```
rm /tmp/yabai.*
ls /tmp/ya*
yabai
```
produce?

**Comment by Liquidmantis** [comment]
Sounds like you have Yabai already running.  Try `yabai -m query --windows`

**Comment by eyalch** [comment]
> macOs is not Windows. No need to reboot for nothing.
> 
> 
> 
> What does 
> 
> ```
> 
> rm /tmp/yabai.*
> 
> ls /tmp/ya*
> 
> yabai
> 
> ```
> 
> produce?

Then I'll never reboot again!

I tried exactly what you suggested, multiple times, which resulted in the same error. I tried again now and no more error!

**Comment by eyalch** [comment]
> Sounds like you have Yabai already running. Try `yabai -m query --windows`

```sh
$ yabai -m query --windows
yabai-msg: failed to connect to socket..
```

**Comment by 24unix** [comment]
Did you configure your spaces for bsp?

**Comment by eyalch** [comment]
> Did you configure your spaces for bsp?

Do you mean this:

```
yabai -m config layout bsp
```

I didn't add it to the config, as the wiki says it's the default. Should I still add it?

**Comment by aspiiire** [comment]
I also had the same issue and I solve only by adding the last comment command to the config file, and restarted only yabai, it worked perfectly!

I found that in your permissions under accesibility you have also to allow your terminal, in my case kitty

The command is this one
```
yabai -m config layout bsp
```
And to restart yabai this one if installed with brew
```
brew services restart yabai 
```

**Comment by koekeishiya** [comment]
The default is to behave as much as standard macOS as possible. If the wiki says that `bsp` is default I'll edit that.

**Comment by hackerkarlos** [comment]
I have an issue, on MacOS 15.0.1, yabai-v7.1.4, skhd-v0.3.9.- with moving windows to different spaces. Does anyone else have this? When i try the selected window just moves backwards under the other windows - is there a fix @koekeishiya ? I partially disabled SIP, and reinstalled yabai from HEAD, but it doesnt seem to help.
