### ISSUE TITLE
Sending Window to second display misplaces border of that window

### ISSUE THREAD

**Issue by F1orian** [koekeishiya/yabai#1229]
When sending a window to my second screen using `yabai -m window --display next` the window moves to the second screen, but the border gets placed at the wrong position, until I force a refresh by manually moving the window once, or modifying another window on that screen.

Example:
![grafik](https://user-images.githubusercontent.com/27896106/163012086-b143d1df-0aa9-4235-8d79-e97ce3215552.png)

This also frequently happens when opening an application from the dock.

SIP is enabled

**Comment by ndr47** [comment]
Same for me. It happens to all windows no matter what.
Probably because it is not reading the following:

```
// in .yabairc
 yabai -m config external_bar all:24:0
```
![Screenshot 2022-05-22 at 21 35 30](https://user-images.githubusercontent.com/65710731/169712833-9c61f3ed-5913-444c-ac1a-a5e5c1e9932b.png)

**Comment by andynameistaken** [comment]
I have this issue too. Last version without this problem is [v3.3.10](https://github.com/koekeishiya/yabai/releases/tag/v3.3.10)
