### ISSUE TITLE
Set opacity for status bar

### ISSUE THREAD

**Issue by qhuyduong** [koekeishiya/yabai#123]
Hi,

Is there any way to set opacity for the status bar, either by config or by code?

Thanks.

**Comment by dominiklohmann** [comment]
This piece of code should work:

```c
SLSSetWindowAlpha(g_connnection, bar->id, 0.9f);
```

https://github.com/koekeishiya/yabai/blob/714f50a0d896665ae11197f28aed2303b3517ca4/src/bar.c#L340-L346

**Comment by koekeishiya** [comment]
The first two nibbles in the hexadecimal value of  *status_bar_background_color* controls opacity.

**Comment by qhuyduong** [comment]
Awesome. Greate work guys!
