### ISSUE TITLE
Kitty open in single-instance mode ignores focused display and always opens on display where first instance is

### ISSUE THREAD

**Issue by steven-lang** [koekeishiya/yabai#1230]
I'm using yabai with two monitors and have bound Kitty to open with the `--single-instance` argument in skhd:

```
cmd - return : /Applications/kitty.app/Contents/MacOS/kitty --single-instance -d ~
```

This unfortunately leads to the new window always opening on the display where the initial (first) kitty instance currently resides (note: display, not space). 

So e.g.:
1. Display 1 (focused): empty, Display 2: empty
2. Open the first Kitty instance
3. Display 1 (focused): [Kitty], Display 2: empty
4. Switch focus to Display 2 
5. Display 1: [Kitty], Display 2 (focused): empty
6. Open Kitty with `--single-instance` argument
7. Display 1: [Kitty, **Kitty**], Display 2 (focused): empty

Is there any fix for this? Can I somehow specify to open a window at a specific (currently focused) display? I guess this should be the default behavior anyway but somehow the `--single-instance` argument leads to this being ignored.

Dotfiles for reference:
- [yabairc](https://github.com/steven-lang/dotfiles/blob/master/configs/yabai/.config/yabai/yabairc)
- [skhdrc](https://github.com/steven-lang/dotfiles/blob/master/configs/skhd/.config/skhd/skhdrc)

**Comment by koekeishiya** [comment]
I believe there is an error in your  config. 

https://github.com/steven-lang/dotfiles/blob/master/configs/yabai/.config/yabai/yabairc#L20 should be `yabai -m config window_origin_display        focused`

That should in theory solve the issue, unless Kitty itself is stealing key-focus before spawning the new window.
If that is the case, you could set `yabai -m config window_origin_display        cursor` which will make newly created windows become tiled at the display that the cursor is placed at.

**Comment by steven-lang** [comment]
Oh wow, yes, the `focus->focused` fix resolved this issue. Thank you for your fast response and for taking the time to look at my config!

Since this went unnoticed to me, maybe a good idea would be to handle invalid configurations similar to i3wm which gives a notification (on config reload) that something went wrong.

**Comment by restfuladi** [comment]
`yabai -m config window_origin_display cursor` doesn't seem to be working for me, if there is a kitty window on another display when you close the focused kitty window, the focus goes there every time. It also happens with Alacritty and WezTerm.

**Comment by koekeishiya** [comment]
Not sure I follow; that config option only takes place when creating a new window, not when windows are closed. I probably didn't understand what you meant.

**Comment by restfuladi** [comment]
> Not sure I follow; that config option only takes place when creating a new window, not when windows are closed. I probably didn't understand what you meant.

My mistake, I got mixed up. The issue I'm describing happens when closing. Opening works as intended on my setup.
