### ISSUE TITLE
Stack layout allows for only one stack

### ISSUE THREAD

**Issue by diocletiann** [koekeishiya/yabai#1232]
Would it be possible to include a setting to set the number of panes for the stack layout? It's kind of useless with every window covering the screen and you can't stack manually in `layout float`.

Two or three stacked panes with managed window placement would be ideal for me. Thanks.

**Comment by koekeishiya** [comment]
you can just use stacks in the bsp layout.

**Comment by restfuladi** [comment]
I am, but it involves manually stacking each new windows once you have 2-3 panes.

**Comment by koekeishiya** [comment]
You can use the `yabai -m window --insert stack` command to make the next window add to the stack instead of having to stack it after opening. If you like to use the mouse you can also do `yabai -m config mouse_drop_action stack` so that you can simply drop a window on top of another to create/add to a stack. I understand this is not quite what you are asking for,
but it's not trivial to make code changes to allow the automatic creation of a set amount of panes with the way the current window layouts are represented, sorry.

**Comment by koekeishiya** [comment]
I suppose you could try to use signals combined with queries to write scripts that automatically creates or append to the correct stacks.

**Comment by restfuladi** [comment]
> You can use the `yabai -m window --insert stack` command to make the next window add to the stack instead of having to stack it after opening. If you like to use the mouse you can also do `yabai -m config mouse_drop_action stack` so that you can simply drop a window on top of another to create/add to a stack. I understand this is not quite what you are asking for, but it's not trivial to make code changes to allow the automatic creation of a set amount of panes with the way the current window layouts are represented, sorry.

Totally understand, I was thinking of a hardcoded number of panes in the stack layout, just a higher number than 1. Just 2 would be a major improvement, would that be a huge lift? Thanks!

**Comment by restfuladi** [comment]
Something like `yabai -m config stack_panes 2` would do.

**Comment by restfuladi** [comment]
One last suggestion - another way it could work would be a set a "max panes" value for the bsp layout, and then stack each new window onto the existing, least recently focused window.

Now that I have the "stack across displays command working", I'm creating two stacks per monitor, stacking placeholder windows into them, and then I'm able to shuffle the top window left/right across panes and displays.

**Comment by restfuladi** [comment]
I found a decent solution:
`yabai -m signal --add event=window_created action='yabai -m window prev --stack "$YABAI_WINDOW_ID"'`

**Comment by koekeishiya** [comment]
Closing this as not planned.

**Comment by BigBrotherJu** [comment]
@koekeishiya Solution like `yabai -m signal --add event=window_created action='yabai -m window prev --stack "$YABAI_WINDOW_ID"'` is acceptable. But windows flicker like crazy. For example, suppose we have two stacks on the left and right, with the mentioned signal appied, a new window (#1) is opened and placed in bsp style first. An old existing window (#2) would become smaller to make room. Suppose the window that window #1 is stacking onto is not #2, #2 would be restored to original size and #1 would move across #2 to the other end. This whole process involves a lot of window resizing, and is not very pleasing to the eye.

Automatically stacking a newly opened window onto existing window with window resizing would be much better.
