### ISSUE TITLE
Yabai not working (permissions issue?)

### ISSUE THREAD

**Issue by ariel-frischer** [koekeishiya/yabai#1233]
My Computer Info
```
macOS Monterey
Version 12.3.1 (21E258)
```

Looking at my error logs: `tail -f /usr/local/var/log/yabai/yabai.err.log`
```
yabai: running as root is not allowed! abort..
yabai: running as root is not allowed! abort..
```
Doesn't matter if I run `yabai` with a shell or with `brew`. I have disabled SIP and ran recommended `--load-sa` options as well.

**Comment by ariel-frischer** [comment]
Ok, I think I understand my issue more now, I have SentinelOne (security software) installed which throws a popup everytime I try to startup yabai. It says `persistence_deception` suspicious activity I'm assuming its actually blocking yabai. I ran `sudo brew services start yabai` which I'm assuming caused the logs above to appear.

**Comment by ariel-frischer** [comment]
Fixed with SentinelOne Permissions.

**Comment by archae0pteryx** [comment]
For anyone else popping in. I had disabled the preference > displays have separate spaces.
