### ISSUE TITLE
lose ability to switch desktop/spaces after reboot

### ISSUE THREAD

**Issue by huwqchn** [koekeishiya/yabai#1236]
I have been using yabai for a while, it run perfect and smoothly.but it lose ability to switch desktop/spaces after I reboot today, and no error  output.( I disabledsip already)

**Comment by searene** [comment]
I've encountered the same problem, have you tried running the following command after reboot:

```sh
sudo yabai --load-sa
```

**Comment by carterchannui** [comment]
What OS version are you running? I too am experiencing issues with yabai not allowing me to switch spaces after updating to MacOS 12.3.1. Yabai is tiling my windows correctly and all of my keybinds for yabai work except for the ones pertaining to the action of switching spaces.

**Comment by carterchannui** [comment]
> What OS version are you running? I too am experiencing issues with yabai not allowing me to switch spaces after updating to MacOS 12.3.1. Yabai is tiling my windows correctly and all of my keybinds for yabai work except for the ones pertaining to the action of switching spaces.

I reinstalled Yabai and the issue seems to have been resolved.

**Comment by huwqchn** [comment]
> What OS version are you running? I too am experiencing issues with yabai not allowing me to switch spaces after updating to MacOS 12.3.1. Yabai is tiling my windows correctly and all of my keybinds for yabai work except for the ones pertaining to the action of switching spaces.

My version is 12.3.1 too, I try to reinstalled yabai

**Comment by huwqchn** [comment]
I know exactly what happened, I was install from https://github.com/donaldguy/yabai.git, and I reinstall yabai from HEAD and everything fine now.
