### ISSUE TITLE
Window/space messed up after connect/disconnect to external screens

### ISSUE THREAD

**Issue by albert-ying** [koekeishiya/yabai#1237]
Hi, I usually work with 2 extra monitors, at home and work. I noticed that when I disconnect the monitor and reconnect to it, the windows go to different spaces.

For example, say I have 9 spaces with one window in each of them. After reconnecting, I end up having a few spaces with 4 or 5 windows and other spaces empty. And I just have to manually move them back to their original space using shortcuts provided by amazing skhd.

I'm wondering if anyone else experienced this issue and if there is any solution for this?

Thank you!

**Comment by koekeishiya** [comment]
If I understand you correctly, is this the same problem as described in https://github.com/koekeishiya/yabai/discussions/238#issuecomment-530400722 ?

**Comment by albert-ying** [comment]
Yes, I think they are the same problem! However, I don't quite get the answer in that issue. Could you show me some examples of how could I resolve this (like what did you put in `.yabairc` and `.skhdrc` for this)?

Thank you so much!

**Comment by steven-lang** [comment]
+1 on this -- also happens when coming back from sleep with two monitors

**Comment by xbladesub** [comment]
Same here, tried to use 'Stay' app, but it become even worth 😆

**Comment by itsjoeoui** [comment]
+1 on this as well :))

**Comment by zakroma** [comment]
If anyone has already figured it out, please do share your solution!

**Comment by koekeishiya** [comment]
Not really much for yabai to do here. macOS quirk..
