### ISSUE TITLE
Enable "yabai -m space --focus X" without Disabled SIP like TotalSpaces3

### ISSUE THREAD

**Issue by AlecSchneider** [koekeishiya/yabai#1238]
Not sure how they do it but I can't disable SIP on my work laptop but would still love to use these features :)

link to their [post](https://discuss.binaryage.com/t/can-we-help-test-total-spaces-3-if-we-have-apple-silicon/8199)

[...] It does not require turning off SIP, or any system modifications, but you must grant a couple of permissions (screen recording and accessibility). [...]

**Comment by AlecSchneider** [comment]
I know "working around SIP" is not a / the goal but still wanted to leave this here if anyone knows how to maybe make some edits myself. At this point it won't let me install the scripting-addition at all (without disabling SIP) and if I try to run the "yabai -m space --focus X" it tells me "cannot focus space due to an error with the scripting-addition"

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/yabai/issues/205 for a workaround. Specifically this comment: https://github.com/koekeishiya/yabai/issues/205#issuecomment-1072082380 for an alternative solution.

**Comment by AlecSchneider** [comment]
Hi, thanks for pointing me there. It works but it's slow (same speed as the macOS default: 
Sys Pref > Keyboard > Shortcuts > Mission Control > Switch To Desktop X

what I specifically like about "yabai -m space --focus X" / totalSpaces3 is that it is instant

Also @koekeishiya thanks again for all the hard work 💯

**Comment by AlecSchneider** [comment]
Problem with using totalSpaces3 is that yabai takes a second to focus the window on the switched desktop. Maybe there's a way to instantly focus a window when switched to new desktop. Only working solution for me has been:

yabai -m space --focus X

**Comment by koekeishiya** [comment]
> Problem with using totalSpaces3 is that yabai takes a second to focus the window on the switched desktop.

I think this is because TotalSpaces3 does not actually instantly perform an instant space switch, they simply hide the animation.
As far as I know it is not possible to perform an instant space switch without disabling SIP, because it requires updating internal state in the Dock's process-space.

**Comment by AlecSchneider** [comment]
ah bummer. Thanks for taking a look tho.

**Comment by koekeishiya** [comment]
Doesn't really matter as far as I'm concerned, because

> It is not possible to perform an instant space switch without disabling SIP, because it requires updating internal state in the Dock's process-space.

rom what I can tell TotalSpaces3 can make the animation disappear, but it cannot get around the internal delay that comes from having to perform some system action that synchronises the Dock state, as mentioned above:

> Problem with using totalSpaces3 is that yabai takes a second to focus the window on the switched desktop.

This is not a yabai problem, it is a problem with the technique that TotalSpaces3 is using.

There is likely a reason why TotalSpaces3 has not seen any development progress in almost 2 years now.
