### ISSUE TITLE
focus_follows_mouse=autofocus working for a couple of minutes only

### ISSUE THREAD

**Issue by sbogun** [koekeishiya/yabai#1239]
Hi. I have successfully installed yabai-v4.0.0 on my Macbook Pro M1, MacOS Monterey 12.3.1. I've disabled SIP and everything seems to work like a charm.

`sudo yabai --load-sa`
and
`brew services start yabai`
work as expected. 

I have a setting
`yabai -m config focus_follows_mouse          autofocus`
in my .yabairc file and it works as expected:
Moving the mouse over to a different window causes that window to get the focus. Lovely!!!

But, unfortunately, that functionality stops working after a while (a couple of minutes). What might be the reason for that?

`brew services info yabai` shows:
```
yabai (homebrew.mxcl.yabai)
Running: ✔
Loaded: ✔
Schedulable: ✘
User: xxx
PID: yyy
```

but the focus doesn't switch anymore when I move the mouse pointer to a different window. Only if I do
`brew services restart yabai`
will this be working again.

**Comment by koekeishiya** [comment]
There is some code that tries to detect when context menus are opened/closed and will disable focus-follows-mouse temporarily while this is the case. It should be re-enabled automatically when the last context-menu closes. Maybe there is a bug/issue with this part of the implementation.

**Comment by sbogun** [comment]
Problem doesn't show up anymore. As far as I can tell issue can be closed. Thanks!
