### ISSUE TITLE
How do I redraw borders without restarting yabai?

### ISSUE THREAD

**Issue by Rofer11607** [koekeishiya/yabai#1240]
Sometimes when I resize windows the borders get stuck and look like this:
![image](https://user-images.githubusercontent.com/55964540/164014434-694432eb-9984-4b09-8e3b-dae932e95a02.png)

How can I trigger yabai to redraw them without restarting yabai? (restarting messes with the layout so I have to rearrange the layout again if I do this)

**Comment by koekeishiya** [comment]
You can run `yabai -m config window_border off` followed by  `yabai -m config window_border on`

**Comment by Rofer11607** [comment]
This is perfect, thank you!
