### ISSUE TITLE
moving window focus past screen edge to move between spaces - broken after update?

### ISSUE THREAD

**Issue by olive-ya** [koekeishiya/yabai#1242]
Hi! I'm using an M1 air on Monterey 12.1, and updated recently - I think from yabai-sa v2.0.2 to 2.0.4 - but it seems to have broken some macros:

```
yabai -m window --focus east || $(yabai -m space --focus next)
yabai -m window --focus west || $(yabai -m space --focus prev)
```
which I put together based on this issue/use case:
https://github.com/koekeishiya/yabai/issues/526

My window *swap* macro still works to switch spaces when at the right/left of the screen, which is very similar, but for some reason the above focus macro just doesn't. Any ideas/can anyone confirm this behavior or is it just me?

My (very amateur) interpretation is that "||" activates a space change for the swap because it returns "cannot swap a window with itself" at the edge of the screen, but this error(/bool?) is no longer returned when moving focus past an edge of the current space.

**Comment by koekeishiya** [comment]
Assuming you are running the master branch, that would be a regression in this commit: https://github.com/koekeishiya/yabai/commit/910fb43b57866dc6eaa000331bb1b77d91bf245b
Will look into it. Likely what is happening is that the source window itself is considered a valid target option, when it should be ignored.

**Comment by ishovkun** [comment]
I have the same issue. I checked that when in a leftmost window, ```yabai -m window --focus east``` yields exit code 0, and, therefore, the script does not proceed to the second part.

**Comment by koekeishiya** [comment]
Fixed on the latest master.

**Comment by ishovkun** [comment]
I would not say that it has been fixed entirely:
when I have two windows (one above the other) on the right screen and try to switch to the left,
```yabai -m window --focus west || (yabai -m display --focus first || yabai -m display --focus last)```
just switches between two windows on the right screen instead switching to the left screen.

**Comment by koekeishiya** [comment]
That chain of commands doesn't really make sense to me if you want it to work regardless of which display you are on.
Something like this would be more appropriate (and works as expected) on my end:

```
yabai -m window --focus west || (yabai -m display --focus west || yabai -m display --focus east)
```

**Comment by ishovkun** [comment]
This chain
```
alt - h : yabai -m window --focus east || (yabai -m display --focus east)
```
behaves the same way for me: yabai still switches between northern and southern windows on the right screen...

**Comment by koekeishiya** [comment]
Can you post a gif or something demonstrating the behaviour? and are you certain that you are on the latest commit?

**Comment by koekeishiya** [comment]
@ishovkun Should be fixed on the latest master now. Was an off-by-one error only reproducible with window gaps disabled.

**Comment by ishovkun** [comment]
Awesome! Thank you!
