### ISSUE TITLE
ffm tweaks

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#1246]
In v4.0.0 a check was made so that a target window was not focused through focus follows mouse if it would occlude some other window.

This check appears to a bit restrictive, and would feel better if the window to be occluded was required to be a floating window for this to take place.

**Comment by koekeishiya** [comment]
autofocus is meant to switch focus to the window without raising it to the front. This is often referred to as "focus without raise", "sloppy focus", and "autofocus" in the context of focus follows mouse.

autoraise switches focus *and* brings the window to the front.

These are not documented in the repo because I just assumed that these terms would be familiar to people that are used to tiling window managers, but I agree that it should probably be explained in the documentation to make it more friendly for people that may not come from Linux.

**Comment by rosenpin** [comment]
Thanks!  
I've actually been using [i3](https://i3wm.org/docs/userguide.html#_focus_follows_mouse) for several years before moving to mac and never encountered this terminology.  
Anyways, I think at this point it's very possible that yabai will be some peoples first tilling WM, and even if not, it should probably be mentioned :)

**Comment by rosenpin** [comment]
Opened a pull request adding those docs

https://github.com/koekeishiya/yabai/pull/1280
