### ISSUE TITLE
Upgrade to Monterey 12.3.1 breaks yabai

### ISSUE THREAD

**Issue by haberdashPI** [koekeishiya/yabai#1248]
Just updated MacOS, and now yabai is no longer working (12.3.1)

When this failed with 4.0.0 I installed the dev version of yabai (following the directions in the wiki). Install was a successful, but I'm getting the same behavior I observed with 4.0.0.

Running skhd -V, I see these error messages when trying to use my typical commands (e.g. move to another window, set to bsp layout, set to full screen etc...):

```
could not locate the first managed window.
could not locate the window to act on!
could not locate the window to act on!
could not locate the window to act on!
could not locate the selected window.
could not locate the first managed window.
```

**Comment by qezz** [comment]
Has it been fixed?

**Comment by haberdashPI** [comment]
Whatever was happening for me that day does not seem to be reproducible. When I restarted my machine it all worked fine. When I tested out the upgrade on my other machine, I never ran into any issue. So it isn't clear what was happening.
