### ISSUE TITLE
Alacritty 0.10.1 opens in float mode

### ISSUE THREAD

**Issue by windowsrefund** [koekeishiya/yabai#1250]
Mac Monterey 12.3.1
Yabai v4.0.0

I just upgraded Alacritty to version 0.10.1 and am surprised to see it open in the center of my screen, above all other windows.

Things I've tried:

- Restart yabai
- Remove ~/.config/alacritty/alacritty.yaml

Whatever the issue is, it was definitely introduced in Alacritty 0.10.0 as 0.9.0 runs fine.

**Comment by sebedh** [comment]
Got the same issue.

**Comment by blaadje** [comment]
same

**Comment by Combowombo** [comment]
Same, but its probably an alacritty issue rather than a Yabai one

**Comment by ctrox** [comment]
One workaround I have found that works with 0.10.1 is the following in `.skhdrc`:

```
# instead of just `alacritty` or `/opt/homebrew/bin/alacritty`
cmd - return : /Applications/Alacritty.app/Contents/MacOS/alacritty
```

**Comment by Combowombo** [comment]
actually i restarted my yabai and it seems to work now

**Comment by xbladesub** [comment]
I don't use skhd, but have this issue. Is there any way to fix that?

**Comment by koekeishiya** [comment]
This is an Alacritty issue.

**Comment by tartavull** [comment]
Any other advice on solving this issue?

**Comment by acelel** [comment]
Might not be the same issue but in my case I just had to set `decorations: full` on `alacritty.yml`

**Comment by hamidzr** [comment]
> One workaround I have found that works with 0.10.1 is the following in `.skhdrc`:
> 
> ```
> # instead of just `alacritty` or `/opt/homebrew/bin/alacritty`
> cmd - return : /Applications/Alacritty.app/Contents/MacOS/alacritty
> ```

The issue still reproduces for me even when using this path instead of the homebrew one. I'm not sure what really different between the two they have the same hash
```
hbp ➜ ~ sha512sum $(which alacritty)
d34e0a15219619c27763826ef12251ed999a9e18a19205d32a63df52a00e5259ce71820437dbb99b636c9c8c31b34a2d77fba24313ac8dd11c1ed3900bc3de8f  /opt/homebrew/bin/alacritty
hbp ➜ ~ sha512sum /Applications/Alacritty.app/Contents/MacOS/alacritty
d34e0a15219619c27763826ef12251ed999a9e18a19205d32a63df52a00e5259ce71820437dbb99b636c9c8c31b34a2d77fba24313ac8dd11c1ed3900bc3de8f  /Applications/Alacritty.app/Contents/MacOS/alacritty
```

I use this command to reproduce the issue:

```
while true; do
alacritty -t 'test yabai bsp' -e sh -c 'yabai -m query --windows --window | jq .title; sleep 0.5';
sleep 0.5
done
```
I'm gonna try and see what changed in my set up to trigger this issue now. Maybe going back to an older Alacrity build would help?

**Comment by CaptainDaVinci** [comment]
@hamidzr for me hash of `/opt/homebrew/bin/alacritty` differs from that of `/Applications/Alacritty.app/Contents/MacOS/alacritty`

**Comment by Zerohertz** [comment]
At `~/.config/yabai/yabairc`

```bash
yabai -m signal --add app='^Alacritty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Alacritty$' event=window_destroyed action='yabai -m space --layout bsp'
```
