### ISSUE TITLE
Exiting fullscreen window that is in stack, breaks the stack

### ISSUE THREAD

**Issue by nyanSpruk** [koekeishiya/yabai#1255]
Been playing with stacks, and saw that after creating a stack.
In my specific case I have 2 chrome tabs. On one I go on youtube, watch a video in fullscreen and after exiting fullscreen the stack breaks. So I have to stack my windows again.

yabai-v4.0.0
MacOS Monterey 12.3

**Comment by koekeishiya** [comment]
When a window enters fullscreen mode on macOS, it spawns as a separate window with its own identifier, and the "old" window is removed. This is not something that can be fixed.
