### ISSUE TITLE
cmd + tab or Clicking notification rearranges windows

### ISSUE THREAD

**Issue by BMonsalvatge** [koekeishiya/yabai#1257]
Hi, 

Whenever I cmd + tab or click on a notification for an app that is in a different space, It seems to move the current space I am in closest to the target space, and then open whatever I was trying to open in the target space.

for example: I have spaces 1  - 4.  If I am on space 4, and click a notification for my browser in space 1 my current (space 4) now moves to position 2 and then my focus goes to 1 in my browser.

Is there any way to keep the notification and cmd + tab functionality without causing this space rearranging behavior?

**Comment by koekeishiya** [comment]
In System Preferences, navigate to Mission Control and uncheck the option "Automatically rearrange Spaces based on most recent use".

from https://github.com/koekeishiya/yabai/wiki/Tips-and-tricks#fix-spaces-reordering-automatically

**Comment by BMonsalvatge** [comment]
Thank you!  This resolved the issue for me.
