### ISSUE TITLE
2 apps in vertical split keep swapping from time to time

### ISSUE THREAD

**Issue by fietske** [koekeishiya/yabai#1259]
Not too familiar with configuring Yabai yet but can't fix my issue which is that I'd like my 2 apps on Desktop 1 (MacOs) to stay in a fixed order: Chrome on the left and Alacritty on the right. Same with Desktop 2: BearApp on the left and MS-Teams on the right. The issue is that sometimes the 2 apps on a Desktop swap places.

have a fairly simple setup: Macbook Air M1 connected to a LG 29" display, latest OS. A screenshot of "Desktop 1" is attached.

![image](https://user-images.githubusercontent.com/877423/167118750-4fc59525-4504-43ac-824d-72d834270028.png)

**Comment by fietske** [comment]
Thanks, but that'd be a workaround. What I want is to have Chrome on the left at all times and Alacritty on the right hand side at all times

**Comment by koekeishiya** [comment]
You need to create a signal or something to automate the behaviour. I have recently thought about adding the ability to save and restore layouts, which would solve your issue, but no ETA for when this will be ready. This was mentioned in https://github.com/koekeishiya/yabai/issues/902 in which I reference other issues where this has been mentioned.

**Comment by fietske** [comment]
Thanks. What attribute defines that 'Chrome' should sit left and 'Alacritty' should sit right?

**Comment by restfuladi** [comment]
> Thanks. What attribute defines that 'Chrome' should sit left and 'Alacritty' should sit right?

I'm not sure if the `window_moved` signal is sufficient for this, but if so, you could do something like this (edit the coordinates to match your displays):

`yabai -m signal --add event=window_moved action=~/.config/yabai/arrange-chrome-alacritty.sh`

```
if (yabai -m query --windows --space | jq -e '.[] | select(.app == "Chrome") | .frame | .x == -0 and .y < 33') \
  && (yabai -m query --windows --space | jq -e '.[] | select(.app == "Alacritty") | .frame | .x > 100 and .y < 33')
then
  yabai -m space --mirror y-axis
fi

**Comment by Bellavene** [comment]
https://github.com/h-ohsaki/macpywm
