### ISSUE TITLE
Some apps' menu items not accessible with focus_follows_mouse=autofocus

### ISSUE THREAD

**Issue by sbogun** [koekeishiya/yabai#1260]
In some apps (here: zoom.us 5.10.1) it is impossible to reach menu items on some menus embedded in the app. I have illustrated this in the attached screen recording. In my yabai config I have set 
`focus_follows_mouse=autofocus`. The entire yabairc is also attached. 
I'm running yabai-v4.0.0 on Monterey on an M1.

https://user-images.githubusercontent.com/9930951/167250655-feba6ab3-0115-42cc-aaa3-ede366aaec98.mov

[yabairc.txt](https://github.com/koekeishiya/yabai/files/8644942/yabairc.txt)

**Comment by ellerychan** [comment]
Try holding down your *mouse_modifier* key, which is set to `fn` in your yabairc config file, before moving the mouse into the menu.

**Comment by blissdev** [comment]
I tried setting this to "option" and this didn't do anything for me. Is that a bad key to use? I don't have `fn` on my desktop keyboard.

**Comment by ellerychan** [comment]
I have mine set to "alt" which seems to work for the "option" key:
```
yabai -m config mouse_modifier alt
```

**Comment by ellerychan** [comment]
Note that it doesn't always work great.  Some tools use **Alt+mouse** interactions, and they won't work.  Sometimes holding down **Alt+shift** for those is a workaround.

I wish the Yabai *mouse_modifier* could be set to a key combo like **Alt+Ctl**.  I also wish MacOS would give up on putting menus way up at the top of our giant screens.  It made sense on the original Mac screen, but not now.

**Comment by koekeishiya** [comment]
Closing this. Situation has improved in later yabai versions.
