### ISSUE TITLE
Newbie question. How to disable all window shadows?

### ISSUE THREAD

**Issue by itaysharir** [koekeishiya/yabai#1262]
I have SIP disabled. i tried adding "yabai -m config window_shadow off" to my config and rebooting but nothing changed.
i'm on an M1 MBP. any suggestions?

**Comment by PaddiM8** [comment]
`yabai -m config window_shadow off` worked *quite* well for me, but it still didn't look completely flat in all programs. To get around this, I added a border around windows with the color of the titlebar. Looks much better to me.

**Comment by clementaudic** [comment]
The top shadow does not disappear (at least on macOS 26).

<img width="134" height="57" alt="Image" src="https://github.com/user-attachments/assets/14e1eeaf-ee56-431a-ba04-7ce6f2311cb8" />

Adding keywords: white borders.
