### ISSUE TITLE
Add <SPACE_SEL> to `yabai -m space --move`

### ISSUE THREAD

**Issue by Sweenu** [koekeishiya/yabai#127]
### Feature request

I'd like to be able to swap the focused space with any other space (not only previous and next space).

Maybe another, more portable solution would be to have a `--swap <SPACE_SEL> <SPACE_SEL>` option that swaps any two spaces.

Let me know what you think :)

**Comment by dominiklohmann** [comment]
I think this is a good idea, and swap should be a separate thing as well. Note though that these are different operations: 

- Move 4 to 1: `1 2 3 4` &rarr; `4 1 2 3`
- Swap 4 to 1:  `1 2 3 4` &rarr; `4 2 3 1`

Also it only needs to accept one space selector, as you can always set the optional space selector before the command.

As a workaround for move, you can use this script. Please note though that this does not work across display boundaries.

```sh
#! /usr/bin/env zsh

# invoke like this: path/to/script $to $from
# examples: 
# - move current space to end: path/to/script last
# - move 2nd space to previous: path/to/script prev 2

to_sel="$(yabai -m query --spaces --space "$1" | jq -re '.index')"
from_sel="$(yabai -m query --spaces --space "$2" | jq -re '.index')"

if [ $to_sel -lt $from_sel ]; then
	direction="prev"
	to_sel="$(( $to_sel + 1 ))"
elif [ $to_sel -gt $from_sel ]; then
	direction="next"
	to_sel="$(( $from_sel - 1 ))"
else
	return
fi

seq $from_sel $to_sel \
	| xargs -I{} yabai -m space {} --move $direction
```

**Comment by koekeishiya** [comment]
Implemented partial support for this - not sure if I want to deal with the complexity of allowing *move* across display boundaries..

```
--move <SPACE_SEL>
  Move position of the selected space to the position of the given space. 
  The selected space and given space must both belong to the same display.
```

**Comment by koekeishiya** [comment]
There is also a new command `yabai -m space --swap SPACE_SEL` which will swap the position of the selected space and the given space. Same caveat as with move - both the selected space and the given space must belong to the same display.

```
--swap <SPACE_SEL>
    Swap the selected space with the given space. 
    The selected space and given space must both belong to the same display.
```

**Comment by koekeishiya** [comment]
I experimented a bit with allowing swap across displays because it seemed like a useful feature, but there is just a whole bunch of complexity that it was hard to get it working correctly in every possible scenario. Leaving it with the constraint of spaces having to belong to the same display for now. Part of v2.3.0
