### ISSUE TITLE
What signal does the window move to another space trigger?

### ISSUE THREAD

**Issue by ati46** [koekeishiya/yabai#1272]
I use a 2k external monitor in the M1, because the external can't turn on hidpi, so I use betterdummy to implement it, but it will cause all windows to appear in the first space after the screen is off. I want to record the space where each window is, and then quickly restore the original arrangement through a script. But I didn't find the signal that fires when the window moves to another space, please help me.

**Comment by koekeishiya** [comment]
There is no event reported by macOS when a window switches space (that I know of anyway).
