### ISSUE TITLE
Red ghost overlay when moving out of BSP stack

### ISSUE THREAD

**Issue by beatslikeahelix** [koekeishiya/yabai#1275]
I've been using the code detailed in #671 to dynamically move windows in and out of, or between stacks.
However, occasionally when moving a window out of a stack, a red residual overlay is created when completing the operation, which can only be dismissed by undoing and redoing the move.

![image](https://user-images.githubusercontent.com/47506872/169212178-a8507f00-6707-4413-a03a-f66e4617e610.png)

This can be reproduced fairly reliably by moving a window from the middle of a bsp stack to a new window.

It was also discussed peripherally in #1252, where another user confirmed experiencing the same thing.

Any idea what's going on here @koekeishiya?
Cheers and best regards.

**Comment by kerryj89** [comment]
I experience the same but seem to trigger it when moving windows between displays, but I do use Stacks so maybe the root problem is there.
