### ISSUE TITLE
yabai -m space --focus command not working?

### ISSUE THREAD

**Issue by liiyung** [koekeishiya/yabai#1281]
Hi, I seem to have a problem specifically with focusing spaces, e.g. in .skhdrc
`shift + alt - 1 : yabai -m space --focus 1`

I have previously used this same call on an older OS (Mojave 10.14 I believe), which worked fine. Currently this is the only command I seem to have a problem with; otherwise I can turn off shadows, adjust opacity, move windows on current space, move windows to a different space, etc. just fine. Downloaded yabai a few days ago, and have turned off and on multiple times already – the issue still persists. 

specs are :
M1, Monterey 12.4, downloaded HEAD node (HEAD-70e9b2a), csrutil status as below 
>       Apple Internal: disabled
> 	Kext Signing: enabled
> 	Filesystem Protections: disabled
> 	Debugging Restrictions: disabled
> 	DTrace Restrictions: enabled
> 	NVRAM Protections: disabled
> 	BaseSystem Verification: enabled
> 	Boot-arg Restrictions: disabled
> 	Kernel Integrity Protections: disabled
> 	Authenticated Root Requirement: enabled

If there is a need to inspect dotfiles, here are [.skhdrc](https://github.com/liiyung/lowcontrast_dotfiles/blob/main/dotskhdrc) and [.yabairc](https://github.com/liiyung/lowcontrast_dotfiles/blob/main/dotyabairc).

Thank you in advance!

**Comment by koekeishiya** [comment]
Works fine for me on M!, Monterey 12.4. Try to reinstall the scripting addition.

**Comment by liiyung** [comment]
I've reinstalled and reloaded the scripting addition, but changing focus still does not work. It's strange! I know the scripting addition is actually loaded and doing something since it does remove window shadows, though.

**Comment by christo-ph** [comment]
Recognizing the same behavior suddenly. As far as I can tell it begins to happen after sleep.

Updated to 4.0.1 a couple of days ago.

**Comment by christo-ph** [comment]
But it seems to be skhd, as the command `yabai -m space --focus X` works on command line

**Comment by christo-ph** [comment]
It is skhd. And it is related to secure keyboard afaik.

**Comment by liiyung** [comment]
So I tried a few more things : 
1. a) `yabai -m space --focus X` does not work for me on the command line – nothing happens. 
b) `sudo yabai -m space --focus X`, I get this message : "yabai-msg: failed to connect to socket..". 

2. I removed the tmp files as suggested [here](https://github.com/koekeishiya/yabai/issues/388). 
a) `yabai -m space --focus X` now gives the error "cannot focus space due to an error with the scripting-addition."
b) `sudo yabai -m space --focus X` gives "yabai-msg: failed to connect to socket.." (fair enough).

3. Uninstalled and reinstalled the scripting addition. I can see it working again as my windows' shadows get removed. 
a) `yabai -m space --focus X` – nothing happens again
b) `sudo yabai -m space --focus X` again gives the message "yabai-msg: failed to connect to socket.."

**Comment by moinessim** [comment]
What if you lock the screen and unlock it?
This helps me from time to time.

**Comment by ZuluNovember** [comment]
> ```
> echo "$(whoami) ALL=(ALL) NOPASSWD: $(which yabai)" | sudo tee /etc/sudoers.d/yabai
> ```
---
This solved this issue for me when using with skhd shortcuts but, what's interesting is that the `sudo yabai -m space --focus 2` command still returns `yabai-msg: failed to connect to socket..`

**Comment by koekeishiya** [comment]
> sudo yabai -m space --focus 2

Don't run regular yabai commands as root.
