### ISSUE TITLE
yabai create space does not work

### ISSUE THREAD

**Issue by glepnir** [koekeishiya/yabai#1282]
hi @koekeishiya ,  Recently I install the yabai in a new machine . fount these keys not work for me . 

```
ctrl + alt - n : yabai -m space --create
# Delete focused space and focus first space on display
ctrl + alt - d : yabai -m space --destroy

# Spaces:  Alt + [NUM]
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7
alt - 8 : yabai -m space --focus 8
```
My env is `Intel  Monterey 12.4` and the `csrutil status` output, I had  try run `sudo yabai --install-sa` , restart yabai etc .not work.

```
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

**Comment by Liquidmantis** [comment]
@glepnir Unrelated, but it is awesome to see you back!  I think the Neovim community feared the worst.

I hope you're doing well.

**Comment by Liquidmantis** [comment]
Oh, back on topic.  I _just_ dealt with the same issue a few minutes ago on a new MBP.  In my case I missed step 6 here:
https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

Namely, running `sudo nvram boot-args=-arm64e_preview_abi` and rebooting.

**Comment by glepnir** [comment]
@Liquidmantis  Thanks. but this command maybe it works for arm right? I use intel so when I tried this command I got error

`Error setting variable - 'boot-args': (iokit/common) not permitted.`

**Comment by glepnir** [comment]
Okay I got yabai works.
