### ISSUE TITLE
Can no longer re-enable SIP and get full Yabai experience?

### ISSUE THREAD

**Issue by Liquidmantis** [koekeishiya/yabai#1285]
The Disabling SIP document says:

>If you are running yabai on macOS 10.13.6 (High Sierra) you can and should re–enable System Integrity Protection after the installation has completed. Repeat the steps above, but run csrutil enable instead at step 4. The same instructions apply if you ever want to re–enable System Integrity Protection after uninstalling yabai.

However, I just tried this for the first time and now the scripting additions won't load.  Is that information no longer correct?

**Comment by koekeishiya** [comment]
That only works on macOS High Sierra, which I assume you are not running. The way it used to work back then was that the scripting-addition could be placed in `/System/Library/ScriptingAdditions` which would prevent it from being blocked by SIP afterwards.

**Comment by Liquidmantis** [comment]
Okay, that makes sense.  I wrongfully assumed that meant 10.13.6 and above.  Bummer, my new work computer gets flagged when SIP is disabled, and I had to re-enable it for compliance.
