### ISSUE TITLE
Some windows do not immediately appear in `yabai -m query --windows`

### ISSUE THREAD

**Issue by peppy** [koekeishiya/yabai#1292]
In previous builds, `yabai -m query --windows` contained windows across all spaces and displays. On the latest `master` it no longer finds windows on a secondary displays or unfocused spaces.

![iTerm2 2022-06-01 at 03 19 19](https://user-images.githubusercontent.com/191335/171321098-e710c923-455c-4768-8595-977ce222b8d1.png)

Running on 95b09be72648bb23dc18f557f438d338e7dbe84e on 12.3.1

I can provide further details if this isn't immediately reproducible.

**Comment by peppy** [comment]
Last working commit 08203a4fe5bb9676806864ff76f554dbafd43c00.

**Comment by koekeishiya** [comment]
Fixed in latest commit. Just messed up with my linear allocation strategy; accidentally left padding in there.

**Comment by peppy** [comment]
Can confirm things are great again, thank you.
