### ISSUE TITLE
Incompatible with Hummingbird on macOS

### ISSUE THREAD

**Issue by macintacos** [koekeishiya/yabai#1295]
There's an app called Hummingbird that I've been using to resize windows on macOS before I learned about yabai: https://github.com/finestructure/Hummingbird. I still want to keep using it, because I cannot disable SIP (work computer, and without disabling SIP you can't resize windows with yabai) and I think that Hummingbird has a nicer way of moving/resizing windows.

Unfortunately, it doesn't seem to work with Yabai - Yabai doesn't seem to resize all of the other windows the way that it does with the default method of dragging a window around or manually resizing.

Any chance that this could be supported? I'm not sure if I put the blame here on Yabai or on Hummingbird.

Also, perhaps you can look into how Hummingbird manages to allow resizing windows without needing to disable SIP? I'd be willing to move over to Yabai for handling this if resizing was allowed without disabling SIP.

Thanks!

**Comment by macintacos** [comment]
Interestingly, I tested out a signal to see if I could do this manually via the `window_resized` event, and at least it seems that the signal can see when a window is being resized - not sure how to get it to play nice with waiting until the resize action is "over" before triggering the signal (when I hold the activation keys for Hummingbird's resize operation, the signal seems to trigger immediately and doesn't wait for me to let go of the modifier keys before calling the action I set up).

**Comment by koekeishiya** [comment]
Yabai can move and resize windows just fine without disabling SIP. See this page for features that require SIP to be disabled: https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection or go here https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc and search for `System Integrity Protection`
