### ISSUE TITLE
Float windows on native-fullscreen spaces

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#130]
### Feature request

Treat all native-fullscreen spaces as floating spaces. Additional windows (e.g. preference panes) should not be tiled on them.

**Comment by koekeishiya** [comment]
Actually can't believe I didn't do this already. Guess that shows how often I use native macOS fullscreen mode. Fixed on master.

**Comment by dominiklohmann** [comment]
> Guess that shows how often I use native macOS fullscreen mode. Fixed on master.

There's so many weird things with it that I sometimes wonder whether the people working on it at Apple are using it.

Just today I discovered that when you use the split native-fullscreen mode (two apps per space) and you move a space to a vertical monitor, it splits the space into two native-fullscreen spaces, which does not even have an animation in Mission Control.
