### ISSUE TITLE
auto_balance does not apply after mirror

### ISSUE THREAD

**Issue by bmfurtado** [koekeishiya/yabai#1301]
To repro:
- Have auto-balance on (`yabai -m config auto_balance on`)
- Make a simple 3 window layout side-by-side
- `yabai -m space --mirror y-axis`

What happens (at least on my computer): windows tree is rotated but resulting windows are not balanced. Is that working as intended?

**Comment by koekeishiya** [comment]
This is intentional, `auto_balance` only happens on window add and removal.

**Comment by bmfurtado** [comment]
Got it... I personally find that behavior slightly confusing (since I'd anticipate that with auto_balance on, doing `yabai -m window --balance` should be a noop).

If you feel that my confusion makes sense feel free to close this issue since I can always work around it by balancing right after doing the mirror in the same skhd action.
