### ISSUE TITLE
What's the status of SIP for Intel Monterey?

### ISSUE THREAD

**Issue by DanMossa** [koekeishiya/yabai#1305]
Hey!

I've been looking into installing Yabai but I'm a little confused on whether or not I can re enable SIP after the installation.

Thanks!

**Comment by typkrft** [comment]
Certain features only work with SIP disabled. I know some of those features may be changing or have changed since I last looked. Effectively if you want every feature you would leave it disabled. You could re enable it or rather leave it enabled from the beginning to see if that works for you.

**Comment by es183923** [comment]
If you don't want the SIP-only features, you don't need to disable SIP in the first place. Otherwise, SIP must be kept disabled, unless you're on macOS High Sierra 10.13.6.

**Comment by hexadecagram** [comment]
I searched the issue tracker after reading the Wiki to find an answer to the exact question @DanMossa asked (I am also running Monterey). The Wiki is a bit confusing about this issue:

> If you are running yabai on macOS 10.13.6 (High Sierra) you can and should re–enable System Integrity Protection after the installation has completed.

In the interest of clarity, I would propose that this text be changed to something similar to the following:

> If and only if you are running yabai on macOS 10.13.6 (High Sierra) you can and should re-enable System Integrity Protection after the installation has completed. Users of ANY other version of macOS will need to leave SIP disabled if the features above are desired.

This is my interpretation of what has been discussed in this ticket; please correct me if I am misunderstanding. It seems a bit strange to me that only one particular version of macOS (High Sierra) was able to re-enable SIP and (presumably) still get the features. What did High Sierra have (or not have) that made it an exception?

**Comment by koekeishiya** [comment]
High Sierra did not have as strict security restrictions as the newer versions of macOS.
