### ISSUE TITLE
Prev focused app across displays or spaces

### ISSUE THREAD

**Issue by joshuarubin** [koekeishiya/yabai#1307]
I've got a hotkey to open a certain app. It will take me to that app from whatever window, display or space I start on. I'd like to be able to quickly return to the place I was previously but am not sure how to do that.

I don't think #104 applies, since I'm not trying to follow any sort of ordering. I may need to jump back to a different display _or_ space, but I don't know which.

It's almost like I need a way to mark a window before jumping with the hotkey to open the app, then I could just return to the marked window and delete the mark. I don't think that's a thing though.

**Comment by koekeishiya** [comment]
Does the `recent` selector not apply here? It will bring you back to the previously active window, space, or display.

**Comment by joshuarubin** [comment]
hey, thanks! I don't think that the `recent` selector is well explained, at least not in the man page. but it certainly works and I guess it's described in the wiki [here](https://github.com/koekeishiya/yabai/wiki/Commands#focus-window).
