### ISSUE TITLE
How do you send multiple commands to socket?

### ISSUE THREAD

**Issue by restfuladi** [koekeishiya/yabai#1308]
Hi, I'm toying with a Go wrapper for yabai and I have to `net.Dial()` before each write to the socket or I get an error. I'm sending strings like this (maybe I need a different char somewhere?): `window\000--toggle\000float\000\000`. I'm new to coding, apologies in advance if I'm doing something silly.

**Comment by 24unix** [comment]
I have no clue about Go, but sure that \000 equals a space?

Why don't you use Objective-C or Swift when you start from scratch? More natural on macOS.
I did some yabai related things with swift, there I could be more helpful, sorry.

**Comment by restfuladi** [comment]
I work in cloud services and Go would be most useful professionally. I was going by [this](https://stackoverflow.com/questions/38007361/is-there-anyway-to-create-null-terminated-string-in-go) to mimic `\0`, not sure what the correct usage is.

**Comment by restfuladi** [comment]
Here is a small test case:
```go
func main() {
	var w window
	var s []space

	conn, err := net.Dial("unix", "/tmp/yabai_x.socket")
	if err != nil {
		log.Fatal(err)
	}

	_, err = conn.Write([]byte("query\000--windows\000--window\000\000"))
	if err != nil {
		log.Fatal(err)
	}

	err = json.NewDecoder(conn).Decode(&w)
	if err != nil {
		log.Fatal("decoding w:", err)
	}
	fmt.Println(w)

	_, err = conn.Write([]byte("query\000--spaces\000\000"))
	if err != nil {
		log.Fatal(err)
	}

	err = json.NewDecoder(conn).Decode(&s)

	if err != nil {
		log.Fatal("decoding s:", err)
	}
```
First read unmarshals correctly (`println(w)` on first line of output), then "broken pipe"...
```
{34926 1 2 {0 30 2048 1122} 0}
2022/06/18 14:50:38 write unix ->/tmp/yabai_x.socket: write: broken pipe
```

**Comment by 24unix** [comment]
> I work in cloud services and Go would be most useful professionally. I was going by [this](https://stackoverflow.com/questions/38007361/is-there-anyway-to-create-null-terminated-string-in-go) to mimic `\0`, not sure what the correct usage is.

And in your cloud services you use macOS and yabai?

**Comment by restfuladi** [comment]
Really? Your comment is not constructive at all.

**Comment by 24unix** [comment]
Like you usecase.
You don’t need to terminate the string (\000) you just need a space.
But if you are so professional, you don’t need any help, do you?

**Comment by restfuladi** [comment]
Now you're putting words in my mouth. I said learning Go would help professionally, and I implied that I don't have time learn a second language. I'm not sure what your issue is, but feel free to not help if what I'm doing bothers you. Wow.

**Comment by koekeishiya** [comment]
You can only send one message per connection, so in your case you would need to call dial again before the 2nd call to write. This is just the way I happened to design it. There is no technical barrier to doing something different, but it would require a bit of restructuring in the yabai message handler.

**Comment by restfuladi** [comment]
> You can only send one message per connection, so in your case you would need to call dial again before the 2nd call to write. This is just the way I happened to design it. There is no technical barrier to doing something different, but it would require a bit of restructuring in the yabai message handler.
Thanks! I already have it set up that way, just curious if I was missing something obvious.
