### ISSUE TITLE
Print query errors to stderr instead of stdout

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#131]
### Bug report

I was trying to implement #104 properly with the new attributes and came across an issue.

If `yabai -m query --spaces --display $sel` fails, it prints "could not locate the selected display." to stdout, which messes with my script. 

This does affect quite a few error messages all throughout yabai. They all need to print to stderr instead.

**Comment by koekeishiya** [comment]
yabai itself always outputs warnings / errors to stderr. Messages returned to the client was erroneously using stdout for error reporting. Fixed on master.
