### ISSUE TITLE
Creating a new stack doesn't update the ID of the visible window 

### ISSUE THREAD

**Issue by restfuladi** [koekeishiya/yabai#1311]
When a new stack is created, the new visible topmost window ID doesn't seem to get updated. So when the stack is focused the first time, the hidden window surfaces and you have to re-focus the correct window. You can reproduce by creating a new stack then querying in its direction, screenshots below. Thanks!

![Screen Shot 2022-06-19 at 3 51 38 PM](https://user-images.githubusercontent.com/14058796/174498104-776f4ae8-6604-458d-baa0-28ffb7fc6373.png)

![Screen Shot 2022-06-19 at 3 54 15 PM](https://user-images.githubusercontent.com/14058796/174498145-b8f535ad-8a02-4da0-9047-c99a917d33fa.png)

**Comment by restfuladi** [comment]
Bump

**Comment by koekeishiya** [comment]
This ordering issue happens when adding a non-focused window to a stack, correct? So the window that yabai says is top of the stack, is not actually the topmost window on screen?

**Comment by restfuladi** [comment]
> This ordering issue happens when adding a non-focused window to a stack, correct? So the window that yabai says is top of the stack, is not actually the topmost window on screen?

I'm stacking like this: `yabai -m window west --stack 'focused window id'`, which stacks the focused window on top of the westward window. But if you then query the ID of the window you just stacked from a third window, it's not the same.

**Comment by koekeishiya** [comment]
Should be fixed on master.

**Comment by restfuladi** [comment]
> Should be fixed on master.

Confirmed. Thank you!
