### ISSUE TITLE
How to move tiled window as a floating one?

### ISSUE THREAD

**Issue by alexeydemidovkz** [koekeishiya/yabai#1313]
I am really sorry if I am missing something obvious. So I can move floating windows like this - yabai -m window --grid 1:3:0:0:2:1 . Is there a way to do same thing for a tiled window (i3 style) - so for example focused window will take left half of the screen and all other windows will move/size accordingly? 

Thank you very much and have a wonderful day!

**Comment by AlgusDark** [comment]
There isn't a way for managed (tiled) windows. Something you could do is a script that gets the width of your display `(yabai -m query --displays).frame` and get the focused window `(yabai -m query --windows --window).frame`; subtract the `display.frame.width` of your current focused window frame.width and apply with [yabai -m query --window --resize right:dx:dy](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#642-command). Just make sure you take in count the x and y of your window frame, as that could mean that your window has gaps. You could also play with this idea and extend this to, let's say you have 3 windows in a column and you apply this to the 3rd one; I would swap it with the first one and then apply what I mentioned before, making always the focused window to expand to the half and make the other windows follow the natural resize.
