### ISSUE TITLE
Add command to set `is_visible` state of window to false

### ISSUE THREAD

**Issue by devnoname120** [koekeishiya/yabai#1314]
`yabai -m window 42 --focus` successfully changes the `is_visible` state to `true` and activates the window.

But I haven't found a similar command for hiding the window.

Alternatives I've considered:
- `osascript -e "tell application \"System Events\" to set visible of application process \"Franz\" to false"`
  - Too slow.
- `defaults write com.apple.dock "mineffect" -string "scale"` + `yabai -m window 42 --minimize`
  - Still animated but better than `genie`.
- `skhd -k "cmd - h"`
  - Doesn't so anything (even though pressing <kbd>cmd</kbd> <kbd>h</kbd> manually works).
  - **Edit**: it works now! No idea why it didn't before… Emulating a system shortcut may not be a future-proof solution though.

**Comment by devnoname120** [comment]
Alternative using Hammerspoon: https://github.com/irfn/dotfiles/blob/669ed25fc062727582b89c089fed9616e4a9046b/hammerspoon/hammerspoon/apps.lua#L1-L10

**Comment by koekeishiya** [comment]
There isn't really any API for doing this. You can hide an entire application, not a single window. You can minimize a window (with macOS animation..) or move it to an inactive space to get it out of your way.
