### ISSUE TITLE
Airdrop window goes out of sight and can't be closed

### ISSUE THREAD

**Issue by rchiarino** [koekeishiya/yabai#1315]
Hi, today I was using Airdrop and noticed that the popup window got displaced to the right that prevent me of selecting the device and closing it. I attached a screenshot and the steps to reproduce this bug and the yabai config file.

### Steps:
Open Finder
Select file to transfer with airdrop
Initiate Airdrop

### Expected behavior 
Airdrop popup to be in the middle

### Actual behavior
Airdrop popup gets pushed, as if it was a new finder window and tries to attach it to the side of the current one.

### Screnshot 
this screenshot was made with cmd  ⌘ + ⇧ + 5 to capture the entire "window" and this show how the popup gets displaced.
![Screen Shot 2022-07-01 at 18 31 27](https://user-images.githubusercontent.com/14266404/176971130-1cc042e5-5802-4538-bcef-3d09652f2fd3.png)

### .yabairc
```sh
#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15

# apps to manage
yabai -m rule --add app="^(Finder)$" manage=on

# apps to not manage (ignore)
yabai -m rule --add app="^(System Preferences|Logi Options|Alfred Preferences|zoom.us|Xcode)$" manage=off
```

**Comment by koekeishiya** [comment]
You should not use this rule: `yabai -m rule --add app="^(Finder)$" manage=on`. manage=on is only meant for applications that are not detected by default due to bad accessibility properties.

**Comment by rchiarino** [comment]
Thanks that was, it I removed the `manage=on` on the config and now Finder is still resizing  but now the airdrop popup is in the middle.

**Comment by rchiarino** [comment]
Hi, I'm having a weird problem if I don't use the `manage=on` when I start my computer I get every window tiling and attaching as expected except Finder, if I run this command on the console `brew services restart yabai` everything starts working including Finder. 
Any ideas why this is happening?

**Comment by koekeishiya** [comment]
should be resolved in latest versions.
