### ISSUE TITLE
Commands with an invalid selector should return a non-zero exit code

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#132]
### Bug report

`yabai -m window --focus 0` prints `invalid window id specified '0'`. and exits with exit code 0, indicating success. Instead, it should exit with anything but 0.

The same applies for similar commands.

**Comment by koekeishiya** [comment]
Unable to reproduce. This is what I see:

```
~ yabai -m window --focus 0                                    22:25
invalid window id specified '0'.
~ echo $?                                                      22:25
1
~                                                              22:25
```

**Comment by dominiklohmann** [comment]
Issue was on my end, was missing `setopt -o pipefail`. Sorry for this.
