### ISSUE TITLE
Automatically go to the specific space when the APP opened in it

### ISSUE THREAD

**Issue by zfhxi** [koekeishiya/yabai#1320]
Hello, I'm newer. I wish to open some APPs in the specific space, so I have added rules:
```
yabai -m rule --add app="(Code|iTerm)" space=code
yabai -m rule --add app="^(Mail|Finder|Safari|Google Chrome)$" space=2
yabai -m rule --add app="^(Zotero|PDF Expert)$" space=research
```
But when I open Zotero, my focus remains on the current space. However, I hope the focus will automatically change to the window of Zotero in space "research" (actually space 3).

How can I implement this? Could you provide some suggestions?

**Comment by peppy** [comment]
I can't find where this is mentioned in the documentation, but try using `space=^research`. I've got this in my rules and in testing it does seem to control focus-follow on app open.

**Comment by linmingwei** [comment]
> I can't find where this is mentioned in the documentation, but try using `space=^research`. I've got this in my rules and in testing it does seem to control focus-follow on app open.

It works well for me , thanks!

**Comment by koekeishiya** [comment]
Listed next to the property under rules in the documentation:

```
display=[^]<DISPLAY_SEL>
Send window to display. If ^ is present, follow focus.

space=[^]<SPACE_SEL>
Send window to space. If ^ is present, follow focus.
```

**Comment by zfhxi** [comment]
Thanks, your suggestions totally solved my problem!
