### ISSUE TITLE
Wezterm changes total size when zooming in

### ISSUE THREAD

**Issue by marcelarie** [koekeishiya/yabai#1321]
This happens only with `wezterm`.

https://user-images.githubusercontent.com/62728887/177956000-da6e35c5-9b14-43ef-a6a8-892b4c569e88.mov

**Comment by MuhammedZakir** [comment]
https://wezfurlong.org/wezterm/config/lua/config/adjust_window_size_when_changing_font_size.html

**Comment by marcelarie** [comment]
Amazing thanks!
