### ISSUE TITLE
config `active_window_opacity` in app-specific window rules

### ISSUE THREAD

**Issue by albert-ying** [koekeishiya/yabai#1325]
Is it possible to config the `active_window_opacity` and `normal_window_opacity` per application?

I tried 
```
yabai -m rule --add app="^iTerm2$" display=3 active_window_opacity=0.3 normal_window_opacity=0.1
```
in my .yabairc, but seems that it doesn't work.

**Comment by AlgusDark** [comment]
Those options don't exist in the [Rule context ](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule). What you want is to is to create a signal for application_activated and deactivated for iTerm. That way you can change the opacity.
