### ISSUE TITLE
Can we order the result query from yabai?

### ISSUE THREAD

**Issue by AlgusDark** [koekeishiya/yabai#1327]
I'm wondering if we can get what is the last focused ID of a certain app.

For example, I go from Brave to Chrome. I open a new chrome (now I have 2) and return to Brave and jump to Discord. Now I want to know what was the latest focused Chrome. Currently I can know that the last focused app was brave, but if we already lost the information of what Chrome instance was the last focused of that group.

Is there any way to get that information from Yabai?

**Comment by restfuladi** [comment]
You could signal on "window focused" and write the IDs to a file.

**Comment by AlgusDark** [comment]
I see, like having a DB. Thanks, I'll play with that.
