### ISSUE TITLE
Keeps showing Accessibility Access popup  on MacOS Monterey 12.4 Apple Silicon M1

### ISSUE THREAD

**Issue by alexandre-thauvin** [koekeishiya/yabai#1332]
Hi,

Even if I already granted access to accessibility to Yabai it keeps showing the popup every 10 seconds as long as the service runs. restart services, reinstall yabai, reboot, or revoke/regrant accessiblity doesn't solve the issue

![image](https://user-images.githubusercontent.com/27420929/180165619-7e087eeb-4a74-4f02-8d75-c24a0e8f325e.png)

MacOS Monterey 12.4
Apple Silicon M1

**Comment by typkrft** [comment]
Did you Code Sign it?

**Comment by alexandre-thauvin** [comment]
What do you mean exactly? @typkrft

**Comment by typkrft** [comment]
Not sure if this applies to you. 
From the wiki:
Code Signing | When building from source (or installing from HEAD), it  is recommended to codesign the binary  so it retains its accessibility  and automation privileges when updated or rebuilt.

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

**Comment by alexandre-thauvin** [comment]
I indeed installed it from the head and didn't sign it! Thanks for the great help @typkrft !

**Comment by alexandre-thauvin** [comment]
I indeed installed it from the head and didn't sign it! Thanks for the great help @typkrft !
