### ISSUE TITLE
I followed install instruction and Yabai doesn't work

### ISSUE THREAD

**Issue by Dayytime** [koekeishiya/yabai#1334]
I have tried installing the release version and it work for a little but after I woke my laptop up from sleep it didn't work. I then uninstalled yabai and followed the instruction for the dev version and nothing seems to be working. I did both installs after following the instruction to disable SIP. I am on a m2 device with Monterey 12.5. If anyone needs me to provide more information just ask. I am not sure what other information I should provide right now. Any help would be appreciated I cannot stand not having a wm and Yabai seems like an amazing solution so I would really like to get it working. Thanks in advance :)

**Comment by SichangHe** [comment]
Did you do every single step in [Disabling System Integrity Protection](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection)? Specifically, did you do 6. enable non-Apple-signed arm64e binaries?
Did you code sign yabai?
Curious to see if this would work on M2 though.
Also, it might be better to ask for help in the [Discussions](https://github.com/koekeishiya/yabai/discussions).

**Comment by rustysec** [comment]
make sure in your `yabairc` you have a line like `yabai -m config layout bsp` otherwise it don't do anything ootb.
