### ISSUE TITLE
Alternate between recent spaces on current monitor

### ISSUE THREAD

**Issue by akulakovsky** [koekeishiya/yabai#1336]
I can't seem to find a way to alternate between recent spaces on the monitor that is currently focused. Am I missing something? If this isn't possible, this might be a good feature to add!

**Comment by MuhammedZakir** [comment]
This?

```
yabai -m space --focus recent
```

**Comment by peppy** [comment]
Try `yabai -m space --focus recent`.

**Comment by akulakovsky** [comment]
Yeah, I meant per-monitor, should've clarified that more. If Yabai currently only stores the previous space that you were at, then I guess it's not possible to implement without it storing a larger "history" (maybe it could have a separate history for each monitor?).

Also, hi @peppy I'm a huge fan :D

**Comment by MuhammedZakir** [comment]
You maybe able hack something with `space_changed` signal. It provides both active space id and previous space id. Using those, you can query the corresponding display id, and save the space ids for display ids seperately. You can save the data in a db, or using files ( `/tmp/.yabai/alternate_space/$display_id/{active_space,previous_space}` ).

**Comment by koekeishiya** [comment]
No plans to implement this. Try to script it using signals.

**Comment by 7vq** [comment]
Anyone scripted this yet? Or have a workaround of some kind?
