### ISSUE TITLE
Small vim window in the middle of screen

### ISSUE THREAD

**Issue by kristiansordal** [koekeishiya/yabai#1338]
Hi

How can I make it so that whenever an iTerm 2 window is opened, *and*  a script which opens a tempfile in neovim is ran, this window opens as a floating small rectangle in the bottom middle part of the screen? I'm not very experienced with yabai commands and how to string them together, so any help would be appreciated.

I'm essentially trying to replicate something like [this](https://youtu.be/10wGMzYgnqM?t=11).

**Comment by kristiansordal** [comment]
Oh, and for anyone familiar with i3wm, this was achived with the following:

```for_window [class=Alacritty instance="__text_scratchpad"] floating enable move right 50px move down 600px resize set 705 260

bindsym $mod+m exec ~/text-scratchpad.sh```

**Comment by marcelarie** [comment]
That is a nice solution but I am doing something different that you might like:
```sh
# scratchpad
alt - v : /Applications/WezTerm.app/Contents/MacOS/wezterm start fish; \
          sleep 0.1 && /opt/homebrew/bin/yabai -m window --toggle float;\
          /opt/homebrew/bin/yabai -m window --grid 4:4:1:1:2:2
```

The first command is the terminal, I use the full path, but I think you could use the terminal name directly. The `start fish` is to run fish to start with `wezterm`, you could run your script there :).

This will be something similar to the first command with other terminals:
alacritty: 
```
/Applications/Alacritty.app/Contents/MacOS/alacritty -e '/etc/profiles/per-user/m.manzanares/bin/fish'
```
kitty:
```
/etc/profiles/per-user/m.manzanares/bin/kitty --single-instance '/etc/profiles/per-user/m.manzanares/bin/fish'
```

then I need to sleep before running the `yabai` commands, so the terminal is already opened.

the end result:

https://user-images.githubusercontent.com/62728887/188142606-57896fba-3e34-4e3e-a474-47ee7f8fa35e.mov
