### ISSUE TITLE
How to get .zshenv exported variables in yabairc?

### ISSUE THREAD

**Issue by AlgusDark** [koekeishiya/yabai#1339]
As the title says. I want to use them in the signal actions like

`yabai -m signal --add event=window_created action="$YABAI_SCRIPTS_DIR/script.sh"`

This works on skhd, this because of the `$SHELL -c`, but I've been trying different things and isn't working at all.

Thanks 🙏

**Comment by MuhammedZakir** [comment]
As `yabairc` is a shell script, you should be able to expand these variables when it is executed. Have you tried that?
```zsh
#!/usr/bin/zsh

<yabai commands>
```

**Comment by AlgusDark** [comment]
Huh... It never crossed my mind. I'll try that and come back when I can try it. But it makes sense 🤔

Thanks!

**Comment by AlgusDark** [comment]
So, I make it working by adding `#!/usr/bin/env zsh` instead. [Similar on how is written in the source](https://github.com/koekeishiya/yabai/blob/4848ec028b60c29f3edb869f07e9e78834f3733a/src/event_signal.c#L89).

Thanks!!!

**Comment by 24unix** [comment]
zsh is located under /bin, not /usr/bin.
