### ISSUE TITLE
Safari geolocation popup are behind the window

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/yabai#1343]
Hi,

I just discovered a weird behavior of Safari geolocation confirmation popup when using rules.

Step 1: Create a global rule for Safari:

```
yabai -m rule --add app="^Safari$" space="Web"
yabai -m rule --add app="^Safari$" title="^(Général|Onglets|Remplissage automatique|Mots de passe|Recherche|Sécurité|Confidentialité|Sites web|Extensions|Avancées|)$" manage=off layer=above
```

Step 2: Lauch Safari
Step 3: Move Safari to another display
Step4: Open a web page which ask for geolocation

Result: the popup is hidden behind the main window.

Workaround: move the safari window a little bin. The popup then shows in front.

Note that I created a custom Safari rule for that kind of window, but even if it gets targeted by the rule and show shortly, the popup remains behind the main window.

```
yabai -m rule --add app="^Safari$" title="^$" manage=off layer=above sticky=on
```

**Comment by AlgusDark** [comment]
Have you tried to put safari on below layer and then everything else on above layer?

**Comment by mickaelperrin** [comment]
Yeah, I give it a try and this is even worse sadly.

**Comment by koekeishiya** [comment]
Should be resolved in latest version.
