### ISSUE TITLE
Split screen keep opening on the left and overlapping

### ISSUE THREAD

**Issue by lethalbrains** [koekeishiya/yabai#1345]
![Yabai issue](https://media0.giphy.com/media/oVqiIzq52UyQPGCVXl/giphy.gif)

As you can see in the gif. When I open a new window, it opens to the left overlapping the existing window. This has been happening only since today morning. 

Following is the brew info for yabai

![yabai](https://i.imgur.com/rj3Dd41.png)

**Comment by carlos-gtz** [comment]
Can you check your version?

`$ yabai --version`
yabai-v4.0.1

I don't know if your formula is installing you the 4.0.0 version. Maybe that's the reason of your bug?

**Comment by lethalbrains** [comment]
> Can you check your version?
> 
> `$ yabai --version` yabai-v4.0.1
> 
> I don't know if your formula is installing you the 4.0.0 version. Maybe that's the reason of your bug?

@carlos-gtz , I uninstalled and reinstalled Yabai. My current version is 4.0.1

The issue mentioned above is not occurring but now when I do a split or go full-screen focus or come back to the split screen, it takes around 8 - 10 seconds to get access to the application. 

Lets say, I do a Ctrl + N when I am in Chrome, I immediately get a split screen but it takes close to 10 seconds for the mouse to come in focus or even the cursor point to come active. I don't see both of the chrome windows being in focus.

**Comment by koekeishiya** [comment]
Something in your system is causing the accessibility API to be slow and sluggish.
