### ISSUE TITLE
I don't really know if this is a issue but it is for me, that it doesn't have support for picom for animations and round corners

### ISSUE THREAD

**Issue by yawarakaides** [koekeishiya/yabai#1348]
Doesn't have support for picom for animations and round corners

**Comment by koekeishiya** [comment]
Pretty sure picom is an X11 compositor, so it is not relevant for macOS?

**Comment by yawarakaides** [comment]
wait you can use picom on Mac OS???

**Comment by koekeishiya** [comment]
> wait you can use picom on Mac OS???

Nop. See #148 for animations.
