### ISSUE TITLE
skhd shortcuts don't work if Neovide is instantiated via command line

### ISSUE THREAD

**Issue by benwoodward** [koekeishiya/yabai#1353]
Not sure if this is a `skhd` issue, or `yabai` issue, so I'm posting on both in the hopes that the right person sees it.

`skhd` issue: https://github.com/koekeishiya/skhd/issues/217

To reproduce:

1. Install Neovide via Homebrew (https://neovide.dev/)
2. Start app, run shortcuts, works
3. Run `brew services stop skhd` to stop background process
4. Run `skhd` in a new terminal window to view any errors encountered
5. Start Neovide GUI from terminal (`$ neovide .`)
6. Run skhd shortcuts from your config
7. You should see the following error: `could not locate the window to act on!`

From time to time, skhd shortcuts just don't work with certain apps, usually iTerm. This is one use-case that is reproducible. 

I don't think this is an issue with `yabai`, because if I run my `yabai` commands manually they work fine with the window in question. When I try to trigger the commands with `skhd` shortcuts they don't work.

Strangely, after stopping the background process, running the process manually, and restarting the background process a couple of times it is now working with the aforementioned window. _However, if I close the window, and instantiate a new one via the `$ neovide .` command then the issue reoccurs_.

If I instantiate the Neovide app using `open -a Neovide` then I don't experience this issue, however, the `open` command just triggers the same process as is triggered by double clicking an app in Finder.

Versions:
`yabai`: yabai-v4.0.1
`skhd`:  0.3.5

**Comment by deevus** [comment]
Similar issue but with Alacritty. If I start Alacritty using a skhd hotkey yabai doesn't know anything about it.

**Comment by G0V1NDS** [comment]
@deevus Yup, I faced the same with Alacritty, I had to switch to Kitty and Iterm2 as an alternative. Not sure why it works for the other terminals but not with `Alacritty`.

**Comment by remi-gelinas** [comment]
+1, exact same issue with running `emacs` from the terminal

**Comment by oHaiyang** [comment]
for me binding skhd action command to `/Applications/Neovide.app/Contents/MacOS/neovide` solved the problem.
