### ISSUE TITLE
 yabai falsely considers webpage pop up text box as windows

### ISSUE THREAD

**Issue by patricorgi** [koekeishiya/yabai#1358]
OS: macOS 12.5 (21G72)

As you can see from the demo video below, when hovering cursor on a webpage element, there was a text box popping up. `yabai` seems to consider this text box as a window and assign the left 1/2 screen to it. After that, the cursor lost focus on that element and Safari window went back to fullscreen. As a result, you see such a flickering windows behavior. 

https://user-images.githubusercontent.com/15998986/184998553-53438cf6-c803-47bb-a19c-5dc496114a96.mp4

**Comment by koekeishiya** [comment]
Remove any rules you have that target safari with `manage=on`.
