### ISSUE TITLE
[Question] Can we using display name to refer to which display instead of the index number?

### ISSUE THREAD

**Issue by nuynait** [koekeishiya/yabai#1359]
So for command like: 

```
yabai -m display --focus 3
yabai -m window --display 3; yabai -m display --focus 3
```

Can we ask it to focus on a specific monitor instead of just the third one? 

Things are when I connect the apple sidecar, (adding iPad as a forth display), the third display becomes the second, and the second display becomes the third. 

I use `option + q` for second monitor, `option + e` for third monitor. When I have apple sidecar connected, those two keys revertted, creating a terrible experience for me. 

I know that `yabai` isn't responsible / supports config display index, but I didn't find any way to assign a monitor to a specific index on the os side and I need a solution to my specific use cases. 

Thanks for everyone's time and any help is appreciated.

**Comment by koekeishiya** [comment]
You'll have to run a yabai query to get the display uuid, and use that to filter the target display for your focus command.

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/yabai/issues/1616#issuecomment-1989707395 and follow up there.
