### ISSUE TITLE
yabai seems to be breaking Alfred Workflow that uses window server info

### ISSUE THREAD

**Issue by godbout** [koekeishiya/yabai#1360]
reported by a user: https://github.com/godbout/WooshyWindowToTheForeground/issues/11

as the creator of the Workflow, is there anything i need to be aware of? something yabai is doing/changing with the window server? i'm not disabling the SIP. thanks.

**Comment by godbout** [comment]
> You don't _need_ to disable SIP either; just some features that can't be achieved on macOS without code injection will fail to work -- other tools don't offer this functionality at all.

ah, great. thanks. i'll install it and see what's going on then. thanks for the quick feedback. closing for now.

**Comment by godbout** [comment]
so after investigation, the issue i'm having with yabai is that it's the only app that doesn't return a `kCGWindowName` when `Screen Recording` permissions have been granted. every other app does have a `kCGWindowName` (which is how we know that the permission has been granted), even if it's just empty.

is there any way you could add this to yabai @koekeishiya? what do you think. thanks.

**Comment by koekeishiya** [comment]
>  (which is how we know that the permission has been granted),

You should be using `func CGPreflightScreenCaptureAccess() -> Bool` to check for access,
 and `func CGRequestScreenCaptureAccess() -> Bool` to request access if it is not granted already.

**Comment by godbout** [comment]
fair. i wanted to avoid this from within the Workflow and rather get Alfred to get the permissions, but will do. thanks for the time.
