### ISSUE TITLE
Delayed window tiling on Monterey 12.5

### ISSUE THREAD

**Issue by mphan-exs** [koekeishiya/yabai#1361]
Hi,

After updating to Monterey 12.5 I'm getting the following issue with yabai:

- works right after `brew services restart yabai`
- continues working without issues for 5-10 min
- after that, there is a ~5 second lag every time a window needs resizing. This is happening for all applications.

Things to note:
- I'm running yabai without the scripting addition as I can't disable SIP on my laptop but yabai was working fine on Big Sur until I updated the OS.
- I have an external display connected via USB-C. Problem still persists when I'm just using the internal display

Is there a way to find what is causing yabai to lose its functionality after a while? It could be some 3rd party app causing this but I doubt it - tried just having 1 space and only chrome open and it's still happening.

Cheers

**Comment by peppy** [comment]
This can generally occur if another application is blocking the main window loop. For me, it happens when pausing a debug session of a GUI app. Are you doing anything like this?

Of course, it might be something completely different in your case.

**Comment by mphan-exs** [comment]
Yeah I saw #1277 and I did check if this was being caused by having ipython/jupyter running in the background - closing those did not resolve the issue.

**Comment by mphan-exs** [comment]
I have now installed the scripting addition and that seems to have resolved the issue. Looks like Monterey somehow broke functionality without the scripting addition. Closing the issue as I do not expect support for running without the script injection. Thanks!
