### ISSUE TITLE
[Question] Move all instances of application to a different desktop

### ISSUE THREAD

**Issue by carlosmiei** [koekeishiya/yabai#1362]
Hello guys.

First of all, great job you're doing here with Yabai.

I have a simple question, let's say we have multiple instances of the same app (Chrome, VSCode, whatever), what is the easiest way to move all of them at once to another desktop?

Thanks!

**Comment by koekeishiya** [comment]
The following command should do it.  
Replace `"kitty`" with `"Google Chrome"` or whatever the name of the application is, and the `1` in `--space 1` with the desktop number.

`yabai -m query --windows | jq 'map(select(.app=="kitty") | .id) | sort | join(" ")' | tr -d '"' | xargs -n1 -I{} yabai -m window --space 1`

**Comment by carlosmiei** [comment]
@koekeishiya nice, thanks! 🙂
