### ISSUE TITLE
More Spaces Signals

### ISSUE THREAD

**Issue by ispringle** [koekeishiya/yabai#1365]
It'd be great if there were some more signals related to Spaces, ideally a signal for each action that Yabai can do to a space (ie Create, Delete, Move, etc.). There is one already:

```
space_changed
Triggered when the active space has changed.
Passes two arguments: $YABAI_SPACE_ID, $YABAI_RECENT_SPACE_ID
```

It'd be great if there were additionally:
```
space_created
Triggered when a space has beed created.
Passes two arguments: $YABAI_NEW_SPACE_ID, $YABAI_CURRENT_SPACE_ID
```
```
space_deleted
Triggered when a space has been deleted.
Passes two arguments: $YABAI_DELETED_SPACE_ID, $YABAI_NEXT_SPACE_ID
```
```
space_moved
Passes two arguments: $YABAI_SPACE_ID, $YABAI_DISPLAY_ID
```

**Comment by GOI17** [comment]
Another option is that we can customize/create new ones

**Comment by prurph** [comment]
I'd love this as well: signals for space created and destroyed would be very useful updating of status bars/widgets. Depending on how ids change when a space is created/destroyed, it could make sense to pass the uuid, or maybe to have just a generic "space count updated" signal that passes no args could do double-duty for both create and destroy. AFAICT there is no way to listen for these events currently.

Additionally, a signal for space label changed would allow for some interesting workflows as well.

**Comment by koekeishiya** [comment]
`space_created` and `space_destroyed` added on master (Ventura only for now as we depend on a system event that I'm not sure exists in earlier versions).
Unable to test/look for `space_moved` as I only have a single monitor available for now.
