### ISSUE TITLE
Yabai automatically refreshing on Mac M1 Monterey 12.5

### ISSUE THREAD

**Issue by prajinkhadka** [koekeishiya/yabai#1369]
I am facing an unusual issue. Windows keep refreshing automatically in 5 seconds or so. I do not have anything as such in config file. Also, I have disabled automatic window arrangement. 

What might be the issue here ?

**Comment by koekeishiya** [comment]
Sounds like a crash. Make sure you are using the latest released version of yabai (v4.0.1).

**Comment by prajinkhadka** [comment]
Yup !! That solved it. 

Thank you @koekeishiya
