### ISSUE TITLE
Connection refused (os error 61) from socket

### ISSUE THREAD

**Issue by restfuladi** [koekeishiya/yabai#1372]
Did something change in the latest version? Having issues talking to the socket. Thanks!

**Comment by koekeishiya** [comment]
I made some slight changes; the client is now required to send the actual number of bytes that follows, as the first 4 bytes that is transmitted: https://github.com/koekeishiya/yabai/commit/ef51c64d50d152c5b88c43b4bed73dd02da7d7cb#diff-bfe8fb0144481cc0e1f3d8a696c9037cddfb4e350209529ab213c9982141ee99R68

**Comment by restfuladi** [comment]
Thanks for the fast reply. Does this look right?

`[25, 0, 0, 0, 119, 105, 110, 100, 111, 119, 0, 45, 45, 102, 111, 99, 117, 115, 0, 115, 111, 117, 116, 104, 0, 0]`

**Comment by koekeishiya** [comment]
You are missing a terminating `0` at the end, so it should be: `[22, 0, 0, 0, 119, 105, 110, 100, 111, 119, 0, 45, 45, 102, 111, 99, 117, 115, 0, 115, 111, 117, 116, 104, 0, 0]`
