### ISSUE TITLE
Cannot focus space with SIP enabled

### ISSUE THREAD

**Issue by ZhongXiLu** [koekeishiya/yabai#1374]
I have some trouble configuring yabai, I'm planning to use yabai with **SIP enabled**, but I cannot seem to focus a space.
```
$ yabai -m space --focus 2
cannot focus space due to an error with the scripting-addition.
```
Strangely, if I focus a space through an Ubersicht widget, it does seem to work (see [code](https://github.com/Jean-Tinland/simple-bar/blob/master/lib/yabai.js#L9)). I'm not sure what the difference is or why it doesn't work via the command line...

---

System information:
macOS Monterey 12.5.1 (Intel)
yabai-v4.0.2

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/yabai/issues/205#issuecomment-1072082380
