### ISSUE TITLE
color format for window borders

### ISSUE THREAD

**Issue by 0rphee** [koekeishiya/yabai#1375]
Great tool, so far been loving yabai. However, when trying to customize it for my use, I haven't really figured out the color format I should use for the window borders. I've tried with standard HEX (ex. 58a6ff) but as I've seen in the config files of other people, the format they use seems to be different (ex. 0xE0808080).

What color format is used to configure window borders? Thank you in advance, and please excuse my ignorance if I haven't found the place where this information could be!

**Comment by PhrantiK** [comment]
Throw the hex on the end of 0xFF and you're good to go. 

With the example you mentioned it would be: ``0xFF58A6FF``

**Comment by koekeishiya** [comment]
It is mentioned in the docs. I don't really see an issue with the way it is worded, but maybe it is unclear for some people.

> active_window_border_color [0xAARRGGBB]
Color of the border of the focused window.

> normal_window_border_color [0xAARRGGBB]
Color of the border of an unfocused window.

The format is `0xAARRGGBB`, basically `AA` is the alpha channel, `RR` is the red channel, `GG` is the green channel, and `BB` is the blue channel. 8-bits to represent each channel.

I guess most tools online only translate the `RGB` channel to `#RRGGBB` e.g: `255, 87, 51` to `#FF5733`.
The equivalent for yabai (fully opaque) would be `0xFFFF5733`. I guess the `0x` part might be confusing.

**Comment by 0rphee** [comment]
Oh thank you! It's clear to me now.

**Comment by carlosvigil** [comment]
> It is mentioned in the docs. I don't really see an issue with the way it is worded, but maybe it is unclear for some people.
> 
> > active_window_border_color [0xAARRGGBB]
> > Color of the border of the focused window.
> 
> > normal_window_border_color [0xAARRGGBB]
> > Color of the border of an unfocused window.
> 
> The format is `0xAARRGGBB`, basically `AA` is the alpha channel, `RR` is the red channel, `GG` is the green channel, and `BB` is the blue channel. 8-bits to represent each channel.
> 
> I guess most tools online only translate the `RGB` channel to `#RRGGBB` e.g: `255, 87, 51` to `#FF5733`. The equivalent for yabai (fully opaque) would be `0xFFFF5733`. I guess the `0x` part might be confusing.

yes, the 0xFF part is confusing. Everywhere else I've seen color the Alpha channel is trailing. Not sure what the 0x is for. Searching for 10 digit hex color picker didn't lead anywhere either.

**Comment by 24unix** [comment]
0x indicates that a hex value follows.
Digital Colour Meter can give a hex RGB output, just add 0xXX, where XX is the opacity from 00 to 255 in hex.

**Comment by koekeishiya** [comment]
There are various representations when encoding in 32 bits. I just happened to be introduced to the ARGB color model, and so that is the natural one for me to use. You can probably google for "ARGB32 color model" if you want to read about these things.

**Comment by carlosvigil** [comment]
@koekeishiya @24unix Thanks, seems like there's ever more to learn. I'll hold off on that rabbit hole for today.
