### ISSUE TITLE
Mouse action 1 doesn't seem to work

### ISSUE THREAD

**Issue by msr8** [koekeishiya/yabai#1376]
yabai version: yabai-v4.0.2
macOS version: Monterey (12.5.1)

So basically, I cant seem to move any window with my modifier (fn) key. Resize works properly, but move does not work. Here is the output of some commands:

![Screenshot 2022-08-31 at 6 03 24 AM](https://user-images.githubusercontent.com/79649185/187567464-e2124888-3096-4a0f-ac8c-3fb75538222b.png)

![Screenshot 2022-08-31 at 6 07 06 AM](https://user-images.githubusercontent.com/79649185/187567820-38cb9a89-c8b2-4420-896b-e18be31adf02.png)

![Screenshot 2022-08-31 at 6 03 44 AM](https://user-images.githubusercontent.com/79649185/187567496-a6ae3d05-7b1e-47ab-bcbc-9c40d0d9e15d.png)

![Screenshot 2022-08-31 at 6 04 25 AM](https://user-images.githubusercontent.com/79649185/187567560-37a8c755-357f-473f-aa87-92a8ec1843c5.png)

![Screenshot 2022-08-31 at 6 06 55 AM](https://user-images.githubusercontent.com/79649185/187567794-410586d7-b643-4cea-a63e-ddf98ed1a085.png)

**Comment by 24unix** [comment]
Sorry for OT: What ist that for a config for neofetch?

Mine looks so:
![image](https://user-images.githubusercontent.com/36622631/187629985-93a07a26-d7eb-486e-be9d-14e7fcaa1c72.png)

**Comment by msr8** [comment]
Yupp, [here](https://github.com/msr8/dotfiles/blob/main/config/neofetch/config.conf) is my config file. [Here](https://github.com/Chick2D/neofetch-themes) are many other themes or neofetch

**Comment by distek** [comment]
I deferred from this:
https://github.com/koekeishiya/yabai/issues/468#issuecomment-608394874

Basically you have to change this:
```
        scripting_addition_move_window(g_mouse_state.window->id, new_point.x, new_point.y);
```
to
```
        window_manager_move_window(g_mouse_state.window->id, new_point.x, new_point.y);
```

and it works as expected.

As of right now this is in event.c:
https://github.com/koekeishiya/yabai/blob/983e0d720328b1b46b171a9b14f9b990cb034e0a/src/event.c#L1086

The line number or entire file is, of course, subject to change, but this will get you what you want. It works pretty well so I'm not sure what added benefit the scripting addition brings, but it's probably faster in it's animation?

Regardless, it works after you build it with this change and you can keep the config as-is.

**Comment by koekeishiya** [comment]
The scripting-addition is used for more performant window movement. I've added an automatic fallback to the slower AX API if the scripting-addition is not available (on master).

**Comment by koekeishiya** [comment]
Fixed in the latest release.
