### ISSUE TITLE
Yabai crashes immediately after starting

### ISSUE THREAD

**Issue by egresh** [koekeishiya/yabai#1377]
Just updated yabai to

# yabai --version
yabai-v4.0.2

It has been running stable for a long time, but now when it starts up, it immediately dies with:

fatal error: temporary_storage exceeded amount of allocated memory. requested 1919251825, but allocated size is 4194304

I'm on an M1 system:

# sw_vers
ProductName:    macOS
ProductVersion: 12.5.1
BuildVersion:   21G83

I rolled back to 4.0.1 and it runs fine.

I tried to look into the problem and see the error appears to be generated from src/misc/ts.h.  Looks like this commit "32ce2f95" changed the file on 06-03-2022, lines 83-91. Maybe something going on there? I'd dig further but that's as far as I can go for now.

Thanks for any help.

**Comment by mgazda** [comment]
I've got the same issue. I've tried code signing, removing yabai from the Accessibility list, reinstalling with or without "--HEAD" and nothing helps...

**Comment by koekeishiya** [comment]
Do you use an external tool to send messages to yabai? There was an internal change to how the message handler operates in v4.0.2.

**Comment by mgazda** [comment]
Thank you for your quick response!

The only external tool I am using is the simple bar for Ubersicht and indeed when I upgraded it the issue has gone.
