### ISSUE TITLE
[Request] Add event for layout changed

### ISSUE THREAD

**Issue by meck** [koekeishiya/yabai#138]
Hi, I used a script with chunkwm for displaying a small, menu icon (macOS default menubar) to display the current mode. However the updating is a bit unreliable.

Adding a event like `layout_changed` possibly returning `space_id` and `new_layout` would simplify this a great deal.

**Comment by koekeishiya** [comment]
I have no intentions of adding custom events that are not used internally simply to provide them through the signals mechanism at this moment. I think the correct solution here is to expand your command that changes the layout, and have that same command be responsible for updating the menubar extension.
