### ISSUE TITLE
can not control popup window from zenity

### ISSUE THREAD

**Issue by JeffChien** [koekeishiya/yabai#1382]
yabai version: v4.0.2
mac: m1 pro 12.4 monterey

I wan't to use [zenity](https://help.gnome.org/users/zenity/stable/index.html.en) to create some simple gui input for script, but I can't figure out how to use rule to locate
the window, it's not a mac app so I've tried to specify title but failed.

example rule and zenity command.
```
yabai -m rule --add label="zenity" title="zenity" manage=off
```

```
zenity --entry --title='zenity'
```

**Comment by koekeishiya** [comment]
If it is not a macOS app then yaba will not see it. Your best bet is to use `yabai -m query --windows` and see if the window is part of the output.
