### ISSUE TITLE
Yabai not working in secondary display

### ISSUE THREAD

**Issue by sumanchapai** [koekeishiya/yabai#1385]
Is anyone having the issue that yabai works as in main display not in "Extended" display.
By not working in "Extended" display, I mean new windows not tiling automatically, shortcuts to switch focus between windows not working, etc... 

I am on MacOS Monterey 12.5.1

**Comment by ElricleNecro** [comment]
I have a similar problem: I cannot switch between spaces on the external monitor. If I run `yabai -m space --focus 3` on the main Mac display, it will work, but if I launch the exact same command while using a terminal on the external monitor, it won't work.

But tiling and switching focus between windows in the same space is working, didn't try the rest.

**Comment by TuralAsgar** [comment]
I have the same problem.

**Comment by koekeishiya** [comment]
Unable to reproduce on latest version.

**Comment by sumanchapai** [comment]
Using `yabai --restart-service` fixes things when things don't work unexpectedly.
