### ISSUE TITLE
How to focus on space for an opened application?

### ISSUE THREAD

**Issue by xbladesub** [koekeishiya/yabai#1387]
How to follow app to the specific space after I opened it? For example I have this line in my config:
```
yabai -m rule --add app=Neovide 			 space=2
```
If I currently stay on space 3 and open this app with shortcut - it opens the app on space 2 but not bring me there

**Comment by koekeishiya** [comment]
Add `^` as mentioned in the docs: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule

> space=[^]<SPACE_SEL>
Send window to space. If ^ is present, follow focus.

Sample:
`yabai -m rule --add app=Neovide 			 space=^2`
