### ISSUE TITLE
retrieve current workspace via cli

### ISSUE THREAD

**Issue by danteissaias** [koekeishiya/yabai#139]
I can't find this in the documentation anywhere. I want to be able to get the current workspace index.

**Comment by meck** [comment]
i belive `yabai -m query --spaces --space` get the info for the current space.

**Comment by kkga** [comment]
`yabai -m query --spaces --space | jq .index` would give you just the index number

**Comment by dominiklohmann** [comment]
Some more things (stolen from the upcoming script cookbook from the wiki) that were not already mentioned.

Broken up into multiple lines using backslashes for readability.

```sh
# get the 1-based space index per display
yabai -m query --spaces --display \
    | jq -r 'sort_by(.index) | map(.focused) | index(1) + 1'

# get the 1-based index as shown in mission-control (excluding fullscreen spaces)
yabai -m query --spaces \
    | jq -r 'sort_by(.index) | map(select(."native-fullscreen" == 0).focused) | index(1) + 1'

# get the space index of a window
yabai -m query --windows --window \
    | jq -r '.space'
