### ISSUE TITLE
Is it possible to move the window to the left/right half of the screen with nothing next to it?

### ISSUE THREAD

**Issue by mcaay** [koekeishiya/yabai#1390]
Hello, I'm trying to move to yabai from Magnet and googling my question it seems nobody asked for it yet.
In Magnet I manually snapped everything, which was often an unnecessary hassle, but sometimes very useful.
On my smaller display (laptop) I have my messaging apps.
In all programs I have a default location for downloaded files to be my Desktop.
Since I keep my Desktop clean and empty, the downloaded files always appear in the same right corner of the Desktop.
Then I often want to send those files to someone else.
The fastest way to do it is to simply drag the file to my messaging app.
But with yabai the app always takes the full screen, so it is impossible to drag something from the Desktop.
In magnet I could quickly Cmd+Alt+Left_Arrow to snap the messaging app to left half of the screen and in this way to uncover the important part of the Desktop.
Can I somehow do it with yabai? Even if for a brief moment?

**Comment by EdsonBittencourt** [comment]
+1

**Comment by koekeishiya** [comment]
`yabai -m window --toggle float --grid 4:4:1:1:2:2`

**Comment by mcaay** [comment]
> 



> `yabai -m window --toggle float --grid 4:4:1:1:2:2`

This line doesn't seem to do anything on my machine but it helped me to google the right thing and solve the problem. Thanks sir!

The solution is found here in the wiki (search for grid): https://github.com/koekeishiya/yabai/wiki/Commands
But in short the line is: `yabai -m window --grid 1:2:0:0:1:1`.
`1:2` -> divide screen into 1 row and 2 columns; `0:0` -> place your window top left corner at coordinates X=0 and Y=0; `1:1` -> have your window have size of 1 row and 1 column.

In order to make the window go to the left two-thirds of the screen: `yabai -m window --grid 1:3:0:0:2:1`
