### ISSUE TITLE
Make the whole window movable/resizable when holding a key

### ISSUE THREAD

**Issue by itaysharir** [koekeishiya/yabai#1391]
Is it possible to do something like [THIS](https://www.youtube.com/watch?v=Wu7ArqGOYYg)? (without the animations ofc)

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc search for `mouse_`

**Comment by itaysharir** [comment]
Thanks!
