### ISSUE TITLE
Focusing on different spaces no longer works.

### ISSUE THREAD

**Issue by emilknievel** [koekeishiya/yabai#1393]
First of all: I love this project and how it has completely changed the way I'm using my mac. Thank you!

Now to the problem:
Running `yabai -m space --focus {{some_index}}` with SIP disabled no longer works. Instead of focusing on a new space the following output is received: `cannot focus space due to an error with the scripting-addition.`

I'm aware of the workaround in [#205](https://github.com/koekeishiya/yabai/issues/205#issuecomment-1072082380) but feel that it is not an actual solution to the issue itself. To make sure that the issue is not considered resolved until the bug itself is fixed, I'm creating this issue.

Keep up the awesome work!

**Comment by koekeishiya** [comment]
Works fine for me; reinstall the scripting-additon.

**Comment by emilknievel** [comment]
Aaaand that did it. I'm an idiot haha. Sorry for taking up your time. Keep it up!

**Comment by IonelLupu** [comment]
@emilknievel  I configured the scripting-addition based on this [page](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition) but I still get this error (`cannot focus space due to an error with the scripting-addition.`). Do I have to restart anything to make it work?

**Comment by emilknievel** [comment]
> @emilknievel  I configured the scripting-addition based on this [page](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition) but I still get this error (`cannot focus space due to an error with the scripting-addition.`). Do I have to restart anything to make it work?

That exact configuration is what made it work for me, just had to restart my computer afterwards. This needs to be done after each yabai update.

**Comment by IonelLupu** [comment]
@emilknievel  oh. my bad. I was configuring it in the wrong way (MacOS beginner here). I had to read the docs more carefully. 

Now I don't get the error anymore, but running the command `yabai -m space --focus 1` or `yabai -m space --focus 2` doesn't do anything. I don't get any errors and I don't see any changes on my laptop . The same applies to `yabai -m space --focus next` as well: nothing happens. Do you have any idea why is doesn't do anything?

(I am on the second space when I run this command:)
![Screenshot 2022-11-15 at 21 38 03](https://user-images.githubusercontent.com/4083652/202010158-50ea0060-e1c1-4c5a-b5df-598ba312d7fe.jpg)

**Comment by IonelLupu** [comment]
@emilknievel I made it work. I had to install yabai from [HEAD](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) because only there is the source code to make it work on Ventura. All good now. 😄
