### ISSUE TITLE
Quicktime screen recording HUD tiles

### ISSUE THREAD

**Issue by pcr910303** [koekeishiya/yabai#14]
I was trying to report an error and trying to record the screen in Quicktime: and found out the screen record HUD tiles, resulting in a strange view.

I couldn't record the screen for obvious reasons, so here's some pics:

This is the tiled HUD; see the message on the left.
<img width="1280" alt="스크린샷 2019-06-01 오후 10 57 43" src="https://user-images.githubusercontent.com/37990858/58749432-08a38700-84c1-11e9-9fc2-67a42b162448.png">

When I move my mouse from the HUD, it becomes darker (maybe it's an intended behavior in Quicktime, e.g. when the mouse moves out of the screen Quicktime is trying to record in a multi screen setup?̊̈): 
<img width="1280" alt="스크린샷 2019-06-01 오후 10 57 14" src="https://user-images.githubusercontent.com/37990858/58749442-3b4d7f80-84c1-11e9-9769-f739b706ae9c.png">

**Comment by pcr910303** [comment]
Also, it looks like the HUD?̊̈ doesn't disappear when recording. I'm pretty sure this behavior wasn't here last week. (I updated yabai today, and the last one I used was compiled last week.)

![yabai-quicktime-hud](https://user-images.githubusercontent.com/37990858/58749522-49e86680-84c2-11e9-927c-0c05a3de9665.gif)

Seems like Gifski is suffering a similar issue (Gifski didn't tile last week), but in this case, querying for windows make yabai crash. (I'm not 100% sure if it's the same problem.)

You can see yabai is crashing(the windows aren't tiling, and my pecan bar doesn't display the space number, which only happens when yabai is running).

![yabai-gifski-short](https://user-images.githubusercontent.com/37990858/58749741-acdafd00-84c4-11e9-9be3-60c648483241.gif)

**Comment by koekeishiya** [comment]
Fixed on master (for quicktime). I don't have Gifski so not sure if that application behaves differently.

**Comment by pcr910303** [comment]
@koekeishiya Can confirm that problem is solved for QuickTime. For Gifski, the problem isn't fixed :-(

**Comment by dominiklohmann** [comment]
> You can see yabai is crashing

Run this in your terminal (requires your Terminal to have accessibility permissions):

```sh
brew services stop yabai
lldb yabai -- --verbose
```

Now the lldb command line will open. To start yabai, run:

```gdb
(lldb) run
```

Now reproduce the crash, then in the lldb command line, run:

```gdb
(lldb) bt
```

This will print a backtrace, which is super helpful for finding crashes. You might want to post this backtrace here. Of course don't forget to update to the latest HEAD before all this.

If you don't have lldb installed, I believe it comes with the Xcode command line tools. You can also use gdb instead, which works mostly the same way.

**Comment by koekeishiya** [comment]
> Seems like Gifski is suffering a similar issue (Gifski didn't tile last week), but in this case, querying for windows make yabai crash. (I'm not 100% sure if it's the same problem.)

I don't actually think this is a problem with Gifski, you just got hit by multiple bugs. So when the quicktime recording window was incorrectly detected and you ran the query command. We tried to get the window title of the quicktime which hit #20 and caused yabai to crash. If you rebuild from the current master I don't think you will have this issue.

Just my guess at what happened here..

**Comment by koekeishiya** [comment]
Downloaded Gifski and followed instructions from the gif and can no longer reproduce the crash. Closing this.
