### ISSUE TITLE
Split ratio resetting when shrinking a window below it's minimal size

### ISSUE THREAD

**Issue by antoineCharpentier-19** [koekeishiya/yabai#1401]
I use fn + mouse, or --resize commands to resize windows all the time. Sometimes, I have a lot of windows, and I want the unimportant ones to be small. My issue is that attempting to resize a window below a certain size will reset the split ratio to half-and-half, as seen in the video below : 

https://user-images.githubusercontent.com/54172932/189301329-de34d173-65e7-42eb-be4f-4971e4ff6ed2.mov

Perhaps there is an integrated way to deal with this, but I've found none. Since this makes you lose your layout and have to "get a feel" for the minimum size you can reach without having it reset, it is kind of problematic for me.
I think it's reasonable to think that simply doing nothing (i.e. going back to the pre-problematic-resize state) would be better than resetting the ratio ? Maybe I am missing a reason for the current behaviour.

**Comment by antoineCharpentier-19** [comment]
Added a PR about this : https://github.com/koekeishiya/yabai/pull/1416

**Comment by antoineCharpentier-19** [comment]
PR : https://github.com/koekeishiya/yabai/pull/1416

**Comment by koekeishiya** [comment]
Fixed on master.
