### ISSUE TITLE
Libreoffice freezes when opening a modal menu

### ISSUE THREAD

**Issue by MartyLake** [koekeishiya/yabai#1402]
Dear Yabai maintainers,

Libreoffice freezes when opening a modal menu («save as», or "format > columns» for example). I would expect that modals from Libreoffice would stay floating automatically.

Is there a way to inspect such modals and write exceptions in yabairc ? As a workaround, I have completely disabled yabai for libreoffice by adding these two lines to yabairc: 

```
yabai -m rule --add app="^LibreOffice" manage=off
yabai -m rule --add app="^soffice" manage=off
```

Thanks for creating such an awesome i3-style apps that works on macOS.
Best,

**Comment by koekeishiya** [comment]
Other issues with Libreoffice mentioned in #1344

**Comment by chairfield** [comment]
Likely fix on the LibreOffice side between versions `7.4.0` and `7.4.5` (latest stable). See https://github.com/koekeishiya/yabai/issues/1344#issuecomment-1229481572.

**Comment by MartyLake** [comment]
@chairfield Can confirm upgrading to LibreOffice `7.4.5` fixed the issue. Thank you very much for following up!
