### ISSUE TITLE
Border offset adjustment

### ISSUE THREAD

**Issue by distek** [koekeishiya/yabai#1403]
Hello!

This is in regards tot he "off by 1 pixel" border issue for us not-able-to-disable-SIP folk: https://github.com/koekeishiya/yabai/issues/753

I feel like there _used_ to be a way to get this to sort of look right by subtracting 1 from the origin xy coordinates of the border, and then increasing the size of the border by 1 pixel each way, but I'm not seeing a way to do this currently.

Is there any way we could implement such a thing so as to have everything look a bit better in this circumstance?
The two benefits I could see from it is:
- SIP-enabled folk are able to have a better visual experience
- Folk who like having *heavy* borders could have some 20 pixel thick border and provide an offset so they can have their borders, and still be able to see a majority of the window contents
- Edit: Third thought: Peeps who have SIP disabled but like the shadows macos provides for whatever reason

I imagine main focus is on the SIP-disabled environment, so no worries if you'd rather not work on this.

Thanks for all the hard work on this! Makes the mac a lot more usable to me.

**Comment by koekeishiya** [comment]
This will be fixed with the changes being made for #1430
