### ISSUE TITLE
mach_loader not found

### ISSUE THREAD

**Issue by genevera** [koekeishiya/yabai#1404]
When trying to run `sudo yabai --load-sa` the following error occurs:

```bash
% sudo yabai --load-sa
sh: /Library/ScriptingAdditions/yabai.osax/Contents/MacOS/mach_loader: No such file or directory
yabai: scripting-addition failed to inject payload into Dock.app!
```

Looking in `/Library/ScriptingAdditions/yabai.osax/Contents/MacOS` I see the following files:

```bash
 % ll /Library/ScriptingAdditions/yabai.osax/Contents/MacOS
.rwxr-xr-x root wheel 33 KB Wed Mar 24 15:44:06 2021  loader
.rw-r--r-- root wheel 33 KB Wed Mar 24 15:44:06 2021  mach_bootstrap
```

Looks like either `loader` needs to be renamed or the code calling `mach_loader` needs to change.

**Comment by koekeishiya** [comment]
Reinstall the scripting-addition.

**Comment by genevera** [comment]
@koekeishiya I did and I see mach_loader has replaced mach_bootstrap but now I get an error with no other output.  I'm happy to post the system log output if that is helpful.

```bash
% brew services stop yabai
Stopping `yabai`... (might take a while)
==> Successfully stopped `yabai` (label: homebrew.mxcl.yabai)
% sudo yabai --uninstall-sa; echo $?
0
% sudo yabai --install-sa; echo $?
0
% sudo yabai --load-sa; echo $?
yabai: scripting-addition failed to inject payload into Dock.app!
1
```
I added the `echo $?` command since running `yabai --verbose ... ` gave me an error

**Comment by koekeishiya** [comment]
Make sure you are following the wiki instructions precisely.
