### ISSUE TITLE
Possible to get most recent window for a given application?

### ISSUE THREAD

**Issue by prurph** [koekeishiya/yabai#1405]
If multiple windows of a given application are open, is it possible to use yabai to determine which of them was most recently focused when none of them are the most recent window (eg the result of `yabai -m query --windows --window recent`)?

The reason I want to do this is that I'm trying to use AppleScript and skhd/hotkeys to switch between applications, but unfortunately if multiple windows of an application are open, it seems to always focus the one on the first display, instead of the most recently used one. However, if you use cmd+tab, it goes to the most recent. This is annoying because it means if you're using shortcuts to go between multiple applications things can happen like: Have Chrome windows on spaces 1 and 2 → Use Chrome on space 2 → use terminal → use another app → shortcut to activate Chrome → Chrome window on space 1 is focused even though it wasn't recently used.

As a workaround, if Chrome is the last application used, I can just `yabai -m window --focus recent` and this correctly focuses the most recently used chrome window, but if Chrome wasn't the previous application obviously this doesn't work.

It [doesn't look like yabai maintains anything more than the last window id](https://github.com/koekeishiya/yabai/blob/b004d485f9a7b3cd3cddf8b3c04fae29e6a7f921/src/event.c#L21) but I thought I'd ask. 

Do you think it would be a possible feature for yabai to maintain and expose a list of recently focused windows? This would allow quickly moving back and forward among multiple windows which seems like a useful feature, a bit like multiple undo/redo. Otherwise I can potentially use signals and scripts to maintain the last focused Chrome window id myself and do it that way. I understand the root issue here has nothing to do with yabai and rather the behavior of macOS. Thanks!

**Comment by koekeishiya** [comment]
You can filter the output of `yabai -m query --windows` on the`app` value. The order is MRU; most recently used, at the top.

**Comment by prurph** [comment]
Thanks, this works pretty well for a single app. I ended up going with:

```sh
/opt/homebrew/bin/yabai -m query --windows | jq -re --arg APP "$1" '
	map(select(.app == $APP and ."is-minimized" == false))
	| first as $recent
	| sort_by(.id)
	| length as $len
	| index(map(select(."has-focus" == true))) as $focused
	| if $focused | not then $recent.id elif $focused < $len - 1 then nth($focused + 1).id else nth(0).id end
' | xargs -I{} /opt/homebrew/bin/yabai -m window --focus {}
```

since the entire list doesn't seem to be MRU, only most recent at the head, this will focus the most recent window of an app if the app isn't focused, otherwise it will cycle through them.

I was hoping to have recently focused windows in order across apps so you could navigate forward and backward among them, but that would require quite a bit of additional state stored in yabai that might be better handled with an external program listening to signals.

**Comment by koekeishiya** [comment]
Right, it's probably just MRU within its space, so group by space or `yabai -m query --windows --space` for the current space only. No plans to integrate more sophisticated tracking in yabai.
