### ISSUE TITLE
Change insert point programmatically ?

### ISSUE THREAD

**Issue by mickaelperrin** [koekeishiya/yabai#1408]
Hi,

Not sure that the title is correct.

I was wondering if I can do this programmatically:

![CleanShot 2022-09-12 at 13 01 39](https://user-images.githubusercontent.com/5844226/189639024-d79a7696-bcd7-4beb-acdc-d5e0ffb15a51.gif)

**Comment by koekeishiya** [comment]
So there is a `yabai -m window --insert <window_sel>` command that basically allows you to predefine how the split is going to happen, which needs to be combined/followed by some warp command. In your specific example you could just do `yabai -m window --toggle split --swap next` I think.

**Comment by mickaelperrin** [comment]
Tanks, indeed that works !

Are there any documentation on insert points to understand what I am doing ?

**Comment by Bellavene** [comment]
> So there is a `yabai -m window --insert <window_sel>` command that basically allows you to predefine how the split is going to happen, which needs to be combined/followed by some warp command. In your specific example you could just do `yabai -m window --toggle split --swap next` I think.

Hm, but in the docs it's stated that `window --insert` takes only <DIR_SEL>|stack... and when I try `yabai -m window --insert 53` I get  `value '53' is not a valid option for DIR_SEL`
Would be glad if that worked.

**Comment by koekeishiya** [comment]
`yabai -m window 53 --insert south`

**Comment by Bellavene** [comment]
Thank you
