### ISSUE TITLE
Delay when Brave Browser is activated

### ISSUE THREAD

**Issue by johnallen3d** [koekeishiya/yabai#1409]
I installed the latest Brave version a little over a week ago and I've been experiencing delays (sometimes extreme) ever since when Brave windows are activated. I'm only experiencing issues with Brave (even Chrome is fine).

Brave Version:
```
Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (arm64)
```

I tried running with `--verbose` but don't see anything egregious in the logs. This is me focusing a space where Brave is active and launching a new window.

```
EVENT_HANDLER_DAEMON_MESSAGE: space --focus browser
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: Brave Browser (93606)
EVENT_HANDLER_DISPLAY_CHANGED: 1 1
space_manager_refresh_application_windows: Finder has windows that are not yet resolved
space_manager_refresh_application_windows: Rambox has windows that are not yet resolved
space_manager_refresh_application_windows: Messages has windows that are not yet resolved
space_manager_refresh_application_windows: Brave Browser has windows that are not yet resolved
space_manager_refresh_application_windows: Slack has windows that are not yet resolved
EVENT_HANDLER_MOUSE_DOWN: 0 0.00, 0.00
EVENT_HANDLER_APPLICATION_DEACTIVATED: kitty
EVENT_HANDLER_APPLICATION_ACTIVATED: Brave Browser
EVENT_HANDLER_DAEMON_MESSAGE: query --windows --window
EVENT_HANDLER_DAEMON_MESSAGE: query --windows --window
window_manager_create_and_add_window:5222 Brave Browser - New Tab - Brave
EVENT_HANDLER_WINDOW_FOCUSED: Brave Browser 5222
EVENT_HANDLER_WINDOW_RESIZED: Brave Browser 3369
EVENT_HANDLER_WINDOW_RESIZED: Brave Browser 5222
EVENT_HANDLER_WINDOW_MOVED:DEBOUNCED Brave Browser 5222
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Brave Browser 5222
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Brave Browser 5222
```

Here's a video representation of something similar to the logs above.

https://user-images.githubusercontent.com/184915/189655017-1e1e5340-3c40-4ed9-8492-2d3e5075116d.mp4

**Comment by Liquidmantis** [comment]
I've been having a similar issue with Chrome that I just now diagnosed to the OneTab extension.  I have no idea why the behavior changed, but I have been having issues for a bit over a week now.

**Comment by johnallen3d** [comment]
OMG thank you @Liquidmantis!!! I'm not sure which extension it was (I purged several I don't use) but I'm back to normal. Funny how ~1 week seems to be the threshold for how long we could suffer with this. 😂

@koekeishiya, I'll close this since I'm no longer experiencing the problem.
