### ISSUE TITLE
Bear app doesn't tile, again

### ISSUE THREAD

**Issue by mcharo** [koekeishiya/yabai#1410]
Now a couple years later, having same issue as reported (and resolved at the time) in #447. Bear.app isn't tiling or in the `yabai -m query --windows` output. 

* Yabai: yabai-v4.0.4
* csrutil status: System Integrity Protection status: enabled.
* Bear: Version 1.9.6 (9044)

**Comment by peppy** [comment]
Can confirm it doesn't work here either.

**Comment by koekeishiya** [comment]
I just downloaded Bear and it works fine for me on master.
