### ISSUE TITLE
Feature request: legacy full screen mode

### ISSUE THREAD

**Issue by diocletiann** [koekeishiya/yabai#1411]
Probably a long shot, but I was wondering if there was a way to force/trick apps into running in legacy full-screen mode, thereby automatically disabling rounder corners, borders, shadows, and title bars? I'm not sure if you're able to modify a call to the new API into the old one or something like that. Seems like a huge win if possible. Thanks.

**Comment by koekeishiya** [comment]
I've looked at this a little on and off, but I don't think it is possible to do so.
