### ISSUE TITLE
doesn't matter please close this issue

### ISSUE THREAD

**Issue by ckpcode** [koekeishiya/yabai#1415]

**Comment by ckpcode** [comment]
> Please delete this comment and show some respect for the work that has been done here.

huh? wouldn't you be annoyed if you spent a day trying to get something working? also what is that supposed to mean, this is a really weird issue cus i downloaded all of the required scripts.

**Comment by koekeishiya** [comment]
No idea what was said here, but going to assume it wasn't exactly positive. Modifying macOS is difficult; feel free to let me know when you yourself create something more impressive.

**Comment by ckpcode** [comment]
> No idea what was said here, but going to assume it wasn't exactly positive. Modifying macOS is difficult; feel free to let me know when you yourself create something more impressive.

it wasnt working and then it did work but not fully
it said that the config file could not be found
i ended up stopping using it because whenever i opened an app it would arrange it annoyingly
the app is not good for 8+ windows open, the grid looks very off
i decided to just use mosaic on setapp
i was very annoyed, i tried to get the program to work for 12+ hours only to find the thing that would make it work was a hidden file (found through cmd+full-stop)
only for it to not work as expected and just make window management more difficult

**Comment by koekeishiya** [comment]
> i ended up stopping using it because whenever i opened an app it would arrange it annoyingly

This can be customized in various ways, but I assume you didn't like the default behaviour.

> the app is not good for 8+ windows open, the grid looks very off

Tiling is usually used in combination with workspaces, the amount of windows for each workspace varies depending on your screen size of course. 

As for the rest of your issues, they can all be resolved by following the introduction in the wiki: https://github.com/koekeishiya/yabai/wiki/Configuration#configuration-file

This is a piece of software that is supposed to be highly configurable and scriptable, but also panders to a certain paradigm, which probably didn't click with how you want things to be, and that's fine. You probably had different expectations going into this.

**Comment by ckpcode** [comment]
multiple desktops on my computer, or workspaces, makes it lag and having 4+ desktops makes the cpu spike on idle to 60%. i'm using an m1 pro aswell, so this is pretty strange behaviour for a chip this powerful.
