### ISSUE TITLE
Applying rule to app with minimized windows results in layout with invisible windows

### ISSUE THREAD

**Issue by overhacked** [koekeishiya/yabai#1418]
# What's wrong?
When you apply a rule to an app that has existing windows that are minimized, yabai includes those windows in the layout but leaves them minimized. The result is a layout with holes for invisible, minimized windows. See attached video.

https://user-images.githubusercontent.com/121654/190479767-15050840-1331-4da9-8c45-d2c34bf1e420.mp4

# Reproducing
*Using any two apps that can open multiple resizable windows:*
1. Start `Terminal.app` (Alacritty, in my video) and open two or more windows
2. Start `Minimized.app` (Firefox, for me) and open at least one window, then minimize all `Minimized.app` windows
3. In one of the terminal windows, run `yabai --verbose`
4. In the other terminal window, run:
    a. `yabai -m config layout bsp`
    b. `yabai -m rule app=. manage=off`
    `Terminal.app` windows will snap into, then out of the layout.
5. Then, run, replacing _**Terminal**_ and _**Minimized**_ with the actual app names under test:
    a. `yabai -m rule 'app=^`_**Terminal**_`$' manage=on`
    b. `yabai -m rule 'app=^`_**Minimized**_`$' manage=on`

The result will be a layout with holes in it, for the minimized application's windows.

# Possible solution
PR #1417 makes the check for minimized windows more general so they are excluded by yabai's window manager.

**Comment by koekeishiya** [comment]
Same issue exists for hidden windows. Fixed on master.
