### ISSUE TITLE
Change split type for next opened window

### ISSUE THREAD

**Issue by timofurrer** [koekeishiya/yabai#1420]
I'm aware that I can change the split type using `yabai -m window --toggle split`. 
However, this will be applied immediately. I'm looking for a command to change the split type from horizontal to vertical and back *for the next opened window*.

How can I achieve that?

**Comment by koekeishiya** [comment]
I think this is a duplicate of #1423

**Comment by timofurrer** [comment]
Yes, it actually is :)
