### ISSUE TITLE
Is there a way to fix the window's insertion point to only one side?

### ISSUE THREAD

**Issue by senpiary** [koekeishiya/yabai#1423]
Is there a way to fix the window's insertion point to only one side?

"yabai" is automatically inserted vertically or horizontally, taking into account the proportions when inserting a new window by default.

But I'm used to "i3wm" and want to unconditionally insert it on the right side of the window.

Tired of specifying the "yabai -m window --insert east" command every time.

Is there a way?

**Comment by koekeishiya** [comment]
Not yet, maybe with signals. I'll add a `split_type` config option for next release; options will be `horizontal`, `vertical`, `auto`.

**Comment by timofurrer** [comment]
> Not yet, maybe with signals. I'll add a `split_type` config option for next release; options will be `horizontal`, `vertical`, `auto`.

I'm new yabai and am wondering if this new `split_type` option can be changed during runtime and therefore have a skhd binding which changes changes the type ?

In addition - would it be possible to have a `toggle` value? Switch would switch to `vertical` if it's `horizontal` and vice-versa?

**Comment by koekeishiya** [comment]
> I'm new yabai and am wondering if this new split_type option can be changed during runtime and therefore have a skhd binding which changes changes the type 

Every command can be run at both config and run-time, and should have the same effect.

> In addition - would it be possible to have a toggle value? Switch would switch to vertical if it's horizontal and vice-versa?

This can be scripted; retrieve the current value using `yabai -m config <setting>` and compare it with whatever, and then run `yabai -m config <setting> <new_value>`

**Comment by koekeishiya** [comment]
Added on master.
