### ISSUE TITLE
Move a window with manage=off & sticky=on to a spacific position on the screen

### ISSUE THREAD

**Issue by itaysharir** [koekeishiya/yabai#1428]
Is that possible? Thanks in advance!

**Comment by koekeishiya** [comment]
I use the following for mpv sometimes when I want some video playing in the corner:

`yabai -m rule --add app="^mpv$" manage=off border=off sticky=on layer=above opacity=1.0 grid=8:8:6:0:2:2`

**Comment by itaysharir** [comment]
Thanks!
