### ISSUE TITLE
make window zoom more flexible

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#1429]
Allow a parent zoomed window to go directly into fullscreen and vice versa.

**Comment by FelixKratz** [comment]
An addition to this might be:
* Allow only one child at a time to zoom to parent node (https://github.com/FelixKratz/yabai/commit/7386dd22771e24ff01fb8494d0e14f010d021c98)
* Zoomed windows occlude windows below in the next-window-in-direction calculation (https://github.com/FelixKratz/yabai/commit/81cd0e5213b86280d118e3e80ddf29b269b7a0a5)

**Comment by koekeishiya** [comment]
> Allow only one child at a time to zoom to parent node

This is how it used to work originally when I first implemented it, but for some reason I no longer remember I removed that restriction.. Will think about it for some time.

**Comment by koekeishiya** [comment]
So I use this functionality sometimes *instead of using* the window stack system, with both `b` and `c` having parent zoom active at the same time. Then I can toggle them using the normal directional commands, as they are "still in the bsp structure".

```
+---------+
|    |    |
|    |  b |
| a  |----|
|    |  c |
|    |    |
+---------+
```

Maybe that is an indicator to improve the stack system, heh.
