### ISSUE TITLE
improve window borders

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#1430]
Borders should be placed below and outside the window, corners rounded, and have a filled blur so that it acts as a backdrop for windows that have modified opacity.

Edit: Added border commands:

```
window_border_hidpi [<BOOL_SEL>]
    Draw border in high resolution mode; for High Dots Per Inch ("Retina") displays.
    HiDPI uses significantly more memory.

window_border_blur [<BOOL_SEL>]
    Blur border allowing it to act as a backdrop for transparent windows.

window_border_radius [<integer number>]
    Radius of window border.
```

**Comment by koekeishiya** [comment]
Implemented on the `animate` branch, which is scheduled for the next release.

**Comment by jonatan-branting** [comment]
Great work on the new border system.

The only part of borders which does not feel "native" to me now is when animating to mission control. This will leave the borders where they are before the windows are scaled and moved. The borders will then disappear once the animation has finished.

Is it at all possible to remove the borders at the start of the animation as opposed to the end of the animation?

**Comment by koekeishiya** [comment]
Unfortunately, the technique I used in macOS Big Sur to detect mission control activating (pre-animation) was (unintentionally?) gated by Apple in macOS Monterey, so as of know this is the only way I know of.

**Comment by koekeishiya** [comment]
Just for documentation purposes; this is the dissasembly of the function that was added in the WindowServer that I believe broke the Big Sur solution in Monterey:


<img width="833" alt="Screenshot 2022-09-22 at 23 06 18" src="https://user-images.githubusercontent.com/6175959/191851159-1c562754-8b61-40ad-9899-d964ece00f60.png">

**Comment by mil-ad** [comment]
Is there a way to get the old behaviour back? I used borders to hide the ugly rounded corners in macOS and it's not possible with the new behaviour.

**Comment by pankamyk** [comment]
@mil-ad You can just edit your SystemAppearance.bundle and change the default Mac style.

**Comment by s-h-o-t** [comment]
@pankamyk How does one go about doing that? I have a bunch of `.car` files that I cannot edit

**Comment by pankamyk** [comment]
@s-h-o-t You'll need to disable SIP, mount sys volume disc as writeable, use an app like https://github.com/jslegendre/ThemeEngine to edit your files, and then bless the livemount

**Comment by mil-ad** [comment]
> @mil-ad You can just edit your SystemAppearance.bundle and change the default Mac corner style.

I was wondering if it's possible to get the old yabai behaviour back

**Comment by isaacraja** [comment]
@mil-ad - window_border_radius = 0;   works partially though. The border is squared but the window edges are still rounded

**Comment by PaddiM8** [comment]
Would it not be possible to have an option for choosing the border style?

**Comment by M4cs** [comment]
> @mil-ad You can just edit your SystemAppearance.bundle and change the default Mac corner style.

Which `.car` file and asset do you edit for this?

**Comment by pankamyk** [comment]
If I remember correctly, the exact asset in those files that's responsible for shaped edges is `WindowFrame_WindowShapeEdges`

**Comment by tsujp** [comment]
I pre-made bundles for this specifically for borders with Yabai back in the day: https://github.com/tsujp/customise_macos

**Comment by tsujp** [comment]
On macOS 12 onwards it's harder to replace the files you need to do (although the patches provided should be fine), I link to instructions for this here: https://github.com/tsujp/customise_macos/issues/9#issuecomment-1236115875
