### ISSUE TITLE
Changing between integrated and discrete graphics with "focus_follows_mouse autofocus" causes unwanted clicks 

### ISSUE THREAD

**Issue by wfaulk** [koekeishiya/yabai#1432]
If I start `yabai` with `yabai -m config focus_follows_mouse autofocus` in my config while my MacBook's integrated graphics are active, and later the discrete graphics become active, any time a menu is open, unwanted clicks occur. It's as if the mouse button is being pressed repeatedly while the menu is open. This makes it very difficult to select anything other than the first menu item. Changing back to integrated graphics makes the problem go away.

Also, if `yabai` is started with discrete graphics active, changing to integrated graphics causes the same problem, and changing back to discrete graphics resolves it in the same way.

Additionally, normally `focus_follows_mouse autofocus` doesn't cause yabai to focus Finder.app when the mouse pointer is just hovering over the desktop, but it does when this menu click problem is occurring.

In both cases, holding down my `mouse_modifier` seems to prevent the problem from happening.

I also feel like there are certain apps that start acting oddly when the problem is active — mostly ones that don't use normal MacOS graphical widgets, like Java apps and GTK apps — but I don't have a good description of this problem.

Given the fact that it's possible for `yabai` to work correctly in either graphics mode, depending on which was active at the time, it feels like the problem isn't the graphics mode, it's the switch between the two.

This is the entirety of my `.yabairc`:

```
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_modifier fn
```

**Comment by koekeishiya** [comment]
I don't have a MacBook with discrete graphics (and I'm not getting one), so there is no way for me to debug this issue.

**Comment by wfaulk** [comment]
If you can suggest how I can help, I'm more than willing to.

**Comment by koekeishiya** [comment]
I don't really know why it would cause an issue and how to debug that. 

Yabai does not do anything differently based on which GPU is selected, as you mentioned in your post, it works for both individually, before a switch happens.  We do not detect and alter behaviour based on some switch, and there is no GPU detection involved. We send the same events to the application to perform a focus switch.

**Comment by wfaulk** [comment]
Okay, well, I'll try and look into it myself, then. I'll put anything I find in here.

The first thing I've discovered is that if I run `yabai -m config focus_follows_mouse off`, the problem goes away along with the FFM feature. But if I turn it back on with `yabai -m config focus_follows_mouse autofocus`, the problem comes back, unlike when I completely exit yabai.

The second thing is that the problem is exactly the same with `focus_follows_mouse autoraise`.

**Comment by wfaulk** [comment]
I'm an idiot. I thought I had the most recent version running, but I was wrong. I upgraded and the problem went away.
