### ISSUE TITLE
Remove 'switch space' animation

### ISSUE THREAD

**Issue by xbladesub** [koekeishiya/yabai#1433]
I want to remove default macOS animation  when I switch between apps which are one difference spaces.
Everything was working without animation as expected and couple of days ago it started to use it some reason.

**Comment by koekeishiya** [comment]
Reinstall the scripting addition.

**Comment by xbladesub** [comment]
> 

didn't help, I updated yabai, changed hash with ```sudo visudo -f /private/etc/sudoers.d/yabai``` - still have default macOS animation

**Comment by xbladesub** [comment]
Worked after reinstalling-installing yabai several times...
