### ISSUE TITLE
How to auto-focus first window of current display when a floating window is closed?

### ISSUE THREAD

**Issue by patricorgi** [koekeishiya/yabai#1434]
Dear yabai developer and enthusiasts,

The following line in the configuration file seems not working..

```
yabai -m signal -add event=window_destroyed action="yabai -m window --focus first"
```

Thank you in advance!

**Comment by koekeishiya** [comment]
`yabai -m window --focus first` will attempt to focus the asp-managed window on screen. If you simply want the most recently used window on screen, use this signal:

```
yabai -m signal --add event=window_destroyed active=yes action="yabai -m window --focus \$(yabai -m query --windows --space | jq '.[0].id')"
```

**Comment by patricorgi** [comment]
@koekeishiya Thank you! I just realized I was missing a hyphen in the `--add` option. Your suggested command is also very helpful!
