### ISSUE TITLE
Auto split regression for mac pro 16

### ISSUE THREAD

**Issue by nikita-orca** [koekeishiya/yabai#1438]
Following - https://github.com/koekeishiya/yabai/commit/f731a694e9155e6073ed70e86ca1b6b8ad54d907#r84703418

On mac pro 16, slightly changing the ratio (to golden ratio) caused regression
When adding 2nd window to the space, (in split auto) - it's split horizontally, instead of vertically as previously

Was able to monkey-fix it by 
`yabai -m config external_bar all:6:6`

**Comment by koekeishiya** [comment]
Fixed on the latest master.
