### ISSUE TITLE
Controlling window locations

### ISSUE THREAD

**Issue by heydonovan** [koekeishiya/yabai#144]
I'm new to the world of tiling window managers. However, keep running into this issue which is a bit difficult to explain. So, I've three windows open on the external display. Can drag one by the corner, and everything resizes just fine.

Now if I want to take a window, and instead of having it stretch vertically, have it stretch horizontally, I'm not sure what to do. I'll try dragging it over the other windows but it snaps back to place. Are we just supposed to stick to what BSP determines is best? And I feel apps like Spotify, Slack, and iTerm fullscreen kinda breaks it.

**Comment by dominiklohmann** [comment]
You can set a keyboard shortcut to execute this command for you, which toggles the split of the active window between bsp/float.

```sh
yabai -m window --toggle split
```

There is no way to do this with the mouse yet, but keep looking at #142 for better mouse controls.

**Comment by heydonovan** [comment]
Nice, thanks for the information! Do you experience issues with applications such as Spotify that don't quite align? It's almost as if the bottom 50px of the window (the player controls) aren't recognized as part of the main window size. Perhaps I should open a new issue.

**Comment by dominiklohmann** [comment]
> Do you experience issues with applications such as Spotify that don't quite align? It's almost as if the bottom 50px of the window (the player controls) aren't recognized as part of the main window size. Perhaps I should open a new issue.

I can't reproduce that. If you can (reliably) you should create a new issue with a screenshot attached (and maybe also the output of `yabai -m query --windows --space`).

**Comment by heydonovan** [comment]
Just saw in my terminal this. Wonder if it could be related. I'll work on a video when I'm home.

```
$ yabai
yabai: scripting-addition could not load, make sure SIP is disabled!
yabai configuration loaded..
fish: 'yabai' terminated by signal SIGSEGV (Address boundary error)
```
