### ISSUE TITLE
After upgrading from 4.0.2 -> 4.0.4 scripting addition fails to load with `connection failed!`

### ISSUE THREAD

**Issue by s-h-o-t** [koekeishiya/yabai#1442]
I've run through the wiki and reconfigured the scripting addition. Also made sure to disable system integrity protection again. I couldn't find any info on how to get more information on how it is failing, all I have is the text from the notification.

**Comment by koekeishiya** [comment]
The wiki is updated for the current master branch (and upcoming release, hopefully by the end of this weekend).

If you have followed all the SIP steps, do the following:

```
1. stop yabai
2. remove some tmp files: `sudo rm /tmp/yabai-sa_<USERNAME>.socket`
3. sudo yabai --install-sa
4. sudo yabai --load-sa
5. start yabai
```

**Comment by s-h-o-t** [comment]
That did the trick. Thank you.  Excited to try out the new update :)
