### ISSUE TITLE
Chrome windows become transparent with animations enabled

### ISSUE THREAD

**Issue by jonatan-branting** [koekeishiya/yabai#1443]
This is with the latest master ([c1ace07](https://github.com/koekeishiya/yabai/commit/c1ace079360d555c088d001385c8041e51950edb)).

New chrome windows which are opened become transparent.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/985954/191852368-cd27ea60-0241-4160-8b26-1f597a486e2d.png">

Restarting yabai solves the issue momentarily for the current window, any new chrome windows opened will still become transparent.

I haven't found any other program with this problem.

**Comment by koekeishiya** [comment]
Uh, well fuck. Not sure how this can be solved..

**Comment by koekeishiya** [comment]
It looks like Chrome windows animate themselves upon creation, messing with the animation that yabai is trying to do.

**Comment by koekeishiya** [comment]
Thanks for reporting this. Fixed on master.
