### ISSUE TITLE
Window is not brought into focus after closing an app that was opened with spotlight

### ISSUE THREAD

**Issue by s-h-o-t** [koekeishiya/yabai#1445]
See the recording below. At first I open a new window of an app thats already opened and managed by yabai, I then close it and the previous window is brought back into focus. When I open finder with spotlight and close it (command-w) however, another window is not brought into focus.
https://user-images.githubusercontent.com/43202406/192037781-78c6fdb6-14fe-455f-8663-ecdaf85a21fa.mov

**Comment by s-h-o-t** [comment]
I'm having issues uploading a video to github it seems. You can see it here: https://imgur.com/a/KqBNWeP

**Comment by koekeishiya** [comment]
This is just standard macOS behaviour due to how windows and applications are separated.
You can add this signal to override the behaviour:

```
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
```

**Comment by s-h-o-t** [comment]
Ah okay, thanks for the signal!
