### ISSUE TITLE
Disable rounded borders in yabai v5.0.0

### ISSUE THREAD

**Issue by itaysharir** [koekeishiya/yabai#1446]
Is there a way to do that? The rounded borders do not look good with windows that have no decorations.

Here is an example of emacs and alacritty:
![Screen Shot 2022-09-23 at 22 17 17](https://user-images.githubusercontent.com/87126382/192041401-6fa850a6-b275-447e-b39c-c64923ea797c.png)

**Comment by koekeishiya** [comment]
You can only disable the radius globally. Have you looked into https://github.com/alacritty/alacritty/issues/1566#issuecomment-1121832279

**Comment by itaysharir** [comment]
How can i disable the radius globally then?

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#config

> window_border_radius [<integer number>]
Radius of window border.

Likely not going to look good when disabling it. This is why I previously did not make these changes, but enough people requested it and convinced me that it was worth the odd application that didn't conform to the system standard.

You can disable borders for specific windows using the rules system.

**Comment by itaysharir** [comment]
Thanks! That worked

**Comment by andryandrew** [comment]
If the window you're referring to is `alacritty`, changing the `decorations: none` to `decorations: buttonless` looks the same on Mac but correctly rounds the window and fixes the visual issue

**Comment by xbladesub** [comment]
Neovide doesn't have ```decorations: none``` for example. So to fix Neovide - I have to disable border radius globally for all apps also
