### ISSUE TITLE
osascript error when opening new terminal windows.

### ISSUE THREAD

**Issue by s-h-o-t** [koekeishiya/yabai#1449]
When opening a terminal window the following is displayed. The scripting addition is working just fine.

```
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/yabai.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.
```

**Comment by terrenana** [comment]
I have the same error.

**Comment by RakerZh** [comment]
same issue

**Comment by koekeishiya** [comment]
I don't have this issue, so going to need some more information? Yabai is not using AppleScript for anything, so not sure why "osascript" would output an error.

**Comment by koekeishiya** [comment]
It is fixed on master. You need to run `sudo yabai --uninstall-sa`.
