### ISSUE TITLE
Fix wrong command typos in wiki

### ISSUE THREAD

**Issue by narze** [koekeishiya/yabai#145]
https://github.com/koekeishiya/yabai/wiki/Commands/bb21f0ec2e542b6397f735db33ee073f176717db

All commands with `yabai -m config ...` cannot be run.
I've removed `config` domain for those commands.

**Comment by narze** [comment]
I thought that editing wiki will make a pull request, I'm sorry that didn't tell you before the fix.

**Comment by dominiklohmann** [comment]
No worries, the wiki is free for everyone to edit currently as discussed in #5. I do have a mirror set up as well—in case someone deletes stuff.

Thanks for the fixes.
