### ISSUE TITLE
Scripting Addition fails to install after upgrade to Yabai v5.0.0

### ISSUE THREAD

**Issue by SxC97** [koekeishiya/yabai#1451]
Hello, I updated Yabai this morning to the new version 5 release and now the scripting addition fails to install.

I'm on MacOS Monterey 12.6 and `yabai -v` returns `yabai-v5.0.0`.

When I run `sudo yabai --load-sa` I get the following error:

```
sh: /Library/ScriptingAdditions/yabai.osax/Contents/MacOS/loader: cannot execute binary file
yabai: scripting-addition failed to inject payload into Dock.app!
```

When I go to `/Library/ScriptingAdditions/yabai.osax/Contents/MacOS/` and run `./loader` I get the following error:

```
zsh: exec format error: ./loader
```

I've already tried checked that SIP is disabled with `csrutil status` and I get the response `System Integrity Protection status: disabled.`

I've also tried reinstalling Yabai with `brew reinstall yabai` and the made sure that the Yabai process already has accessibility permissions in System Preferences.

If there is anything else I can do to help with debugging, please let me know!

**Comment by 0xWaleed** [comment]
See https://github.com/koekeishiya/yabai/issues/1447, he had the same issue

**Comment by SxC97** [comment]
Thank you! Running `sudo yabai --uninstall-sa; sudo yabai --load-sa; brew services restart yabai` seems to have fixed the issue.
