### ISSUE TITLE
Improve animations (when scaling windows)

### ISSUE THREAD

**Issue by jonatan-branting** [koekeishiya/yabai#1458]
Sometimes, the animations look a bit funny when scaling a smaller window up or a larger window down.

This is because the text will almost always remain the same size regardless of the window size, while showing more content.
The animation system works by basically screenshotting and scaling the entire window.

You could solve this by doing the same thing apple is doing for their animations. Which (on the surface at least) does the following:
1. When scaling up, keep the actually screenshotted window content a fixed size, while padding it with a "similar" colour.
2. When scaling down, instead crop the screenshotted window.

This would of course be a bit more complex, but I think it would increase the perceived quality of the animations.

**Comment by koekeishiya** [comment]
Apple is able to grab a screenshot of how the window is going to look *after* the change in size, and then they scale that version of the window.

**Comment by jonatan-branting** [comment]
> Apple is able to grab a screenshot of how the window is going to look _after_ the change in size, and then they scale that version of the window. It might not even be a screenshot, but they are scaling a separate window at least.
> 
> Then they scale both the old size and the new size simultaneously while performing an alpha blend.

There is still this abrupt transition at the end, though (even with Apples implementation). It seems that the "new size" scaling is very understated. If the new size scaling was skipped, would this look weird? It was not something I noticed at all at first.

With the current implementation, the text either gets very large or very small, which I think (with nothing to back it up) is more jarring.

Still a big fan of the animations though, in any case :)

**Comment by koekeishiya** [comment]
I think the best thing we can do realistically is make the end of transition less abrupt through an alpha fade transition. 
Trying to pad the image is just going to be too complicated, taking the window decorations into consideration and what not.

**Comment by koekeishiya** [comment]
I've spent quite some time trying different solutions and the conclusion is that this is just not technically feasible with the information and access that yabai is able to have.. #2137
