### ISSUE TITLE
Warping windows does not always respect specified insert direction

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#146]
### Bug report

A mix of `yabai -m window $1 --insert <dir_sel>` and `yabai -m window $2 --warp $1` does not work if window `$1` is a direct child or parent node of window `$2`. 

Instead it simply swaps the windows.

The behaviour is probably in place because for this scenario a warp is a swap, but when an insert direction is given it should always warp.

**Comment by koekeishiya** [comment]
Your assumption is correct.

**Comment by koekeishiya** [comment]
Fixed on master.
