### ISSUE TITLE
Squared border on 5.x looks bad

### ISSUE THREAD

**Issue by cxa** [koekeishiya/yabai#1460]
pre 5.x:

<img width="437" alt="Screen Shot 2022-09-26 at 09 08 00" src="https://user-images.githubusercontent.com/32127/192175589-928a53a2-ef83-4dbd-8256-e4cea1d53a91.png">

after 5.x:

<img width="426" alt="Screen Shot 2022-09-26 at 09 08 13" src="https://user-images.githubusercontent.com/32127/192175566-a49c9580-9436-4c0d-9560-e92d6e036491.png">

Just look at the corners, can we restore previous behavior?

**Comment by koekeishiya** [comment]
No, it is not possible to restore the previous behaviour. See the issues linked to #1430 for history. This is one of these cases where no matter what I do people are not satisfied.

**Comment by FelixKratz** [comment]
It would be possible to make it look a bit better by drawing the border at double width and draw one border width *outside* of the frame and one border width *inside* of the frame. This also looks better for rounded borders, since you can then set the border radius to 9, which exactly matches the systems border curvature: https://github.com/FelixKratz/yabai/commit/4a9b6ca5367b5068b55c64e01dc70e7fe36c3f6a

![Screen Shot 2022-09-26 at 10 09 04](https://user-images.githubusercontent.com/22680421/192226485-7eec8006-1982-489d-aa5e-38ed68eed100.png)

**Comment by koekeishiya** [comment]
That doesn't look particularly good when combined with window opacity, in my opinion.

**Comment by FelixKratz** [comment]
Another approach would be to just fill in the characteristic system border radius up to the supplied border radius with a mask. This would fill out only the edges of the border.

**Comment by koekeishiya** [comment]
Well, that ties in to my previous caveat with the new border system in general (mentioned in several of the linked issues); there is no way to accurately determine the corner radius/mask of a window. Sure, *most* windows use the same, but from my experience it varies between applications, so there is always going to be something that looks "off".
This is exactly why until now I have opted for the square-borders approach.

It really is a pick-your-poison situation imo.

**Comment by koekeishiya** [comment]
So it might bepossible to detect the corner radius by taking a screen capture of the window upon border creation and simply iterate through the pixels and check which pixels are basically fully transparent, and adjust the corner radius automatically based on this.

**Comment by restfuladi** [comment]
Can you force windows to render in legacy fullscreen mode? I'm not sure if you can control their size after, but it would automatically give you square corners.

**Comment by marcelarie** [comment]
I would like this to roll back to the old look too :)

**Comment by 24unix** [comment]
Transparency ist the main reason for me to use yabai.

**Comment by brorbw** [comment]
@24unix so you don't use borders or any of the other features of yabai?

**Comment by 24unix** [comment]
@brorbw No borders. Three displays. The middle with bsp, the external with float. But without transparency I wouldn't use yabai, bsp is not so important to me.

**Comment by brorbw** [comment]
Fair enough - I didn't expect anyone to use a tiling window manager and then only use it for transparency. Guess my ignorance got the better of me. That being said. Personally I don't like the rounded corners and I would like it to go back to the way it was before. I don't care about the transparency nor the animations.

**Comment by koekeishiya** [comment]
#984 #715 #801 there is a wide range of opinions regarding this topic; as I said before this is a pick-your-poison situation. For now, make a fork and adjust the border to your liking.

**Comment by brorbw** [comment]
Adding an option to disable the rounded corners mask could possibly be a solution.

**Comment by brorbw** [comment]
May I add that the round borders don't look particularly good on square windows
![Screenshot 2022-09-28 at 19 07 52](https://user-images.githubusercontent.com/5909562/192845830-4c074a4d-4de6-488e-b171-51ad6bc5de98.png)

**Comment by cxa** [comment]
For anyone who interest in my alt square border fork, check out https://github.com/cxa/yabai

**Comment by azinsharaf** [comment]
> For anyone who interest in my alt square border fork, check out https://github.com/cxa/yabai

What OS version are you using? I read that Apple has added round corner and there is not a simple way to change it to squared corner. Is it right?
