### ISSUE TITLE
Wrong border location

### ISSUE THREAD

**Issue by jheroy** [koekeishiya/yabai#1461]
<img width="1015" alt="Snipaste_2022-09-27_09-40-32" src="https://user-images.githubusercontent.com/504766/192411714-83521764-3e6f-42f5-a52f-e77c2a9de303.png">

**Comment by koekeishiya** [comment]
Can't reproduce this; but borders don't work properly in Ventura either way.

**Comment by y9c** [comment]
Similar issue when opening finder app
