### ISSUE TITLE
Override border settings for specific app

### ISSUE THREAD

**Issue by caffo** [koekeishiya/yabai#1464]
I have this tiny app I used — https://github.com/YacTeam/ohtipi — and it keeps a hidden window that has borders all the time. Is there a way to override the borders just for it (no borders)?

<img width="2559" alt="image" src="https://user-images.githubusercontent.com/456/192847755-8c8b226c-d0a9-4313-af36-f1d48da3162b.png">

**Comment by andryandrew** [comment]
you can add a rule like this:
```
yabai -m rule --add title="^ohtipi$" manage=off border=off
```
substitute `ohtipi` with whatever the title of the window is. You can look up all current windows' properties with `yabai -m query --windows`

**Comment by caffo** [comment]
thanks!

On September 28, 2022, GitHub ***@***.***> wrote:
> you can add a rule like this:
>
> yabai -m rule --add title="^ohtipi$" manage=off border=off
> substitute ohtipi with whatever the title of the window is. You can
> look up all current windows' properties with yabai -m query --windows
>

—
Reply to this email directly, view it on GitHub
<https://github.com/koekeishiya/yabai/issues/1464#issuecomment-
1261236762>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAADSDAYF2KO6TVAAFV7S3WAR6OHANCNFSM6AAAAAAQX7YOMA>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by dotzenith** [comment]
@caffo are you on 5.x? How'd you go about getting square borders?

**Comment by caffo** [comment]
I have this on my `.yabairc`

```
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xffA8A19B
yabai -m config normal_window_border_color   0xff555555
```
