### ISSUE TITLE
🕸 Homepage for Yabai 

### ISSUE THREAD

**Issue by shot-codes** [koekeishiya/yabai#1466]
Hey there. I've been using Yabai for a while and have been so happy with it. The other day I had some time and had the idea to make a homepage for yabai that would capture some of its magic. I threw this together over the last couple of evenings. @koekeishiya, If you would want to use it as an official homepage I would love to develop it a bit further. I would update the wiki to include some front matter among other things to enrich the experience, as well as trigger rebuilds whenever the wiki is updated. Maybe make dedicated pages for installation, etc. Also would love to hear peoples inputs on the design if anyone has an interest. Let me know what you think :)

https://main--friendly-dolphin-63ea91.netlify.app/

**Comment by shot-codes** [comment]
@koekeishiya just wanted to make sure this didn't get completely buried after noticing you became active in some other threads. Still looking forward to hear if you're interested and if I should pursue a homepage :)

**Comment by 24unix** [comment]
Anything not being hosted on MS Github would be a step in the right direction.

**Comment by koekeishiya** [comment]
It looks nice, but I personally don't really care much about having a homepage. I do see the appeal for users that are discovering yabai and such, but I'm not really into the business of trying to expand a userbase so I prefer the "keep everything with the source code approach". That said, I wouldn't mind linking it in the readme if you want to continue with this.

**Comment by shot-codes** [comment]
Thanks for the response. I totally understand your stance. I will pick this up at some point when I'm less busy and see what comes of it 😃

**Comment by shot-codes** [comment]
Oh I forgot to ask. The site should only exist and be linked to if it is always up to date with the docs. I.e auto rebuilds whenever the docs change. To do this I would have to add some metadata in the wiki files, if you are open to this I will keep working on it when I have the time, otherwise it's not worth it because it's not feasible to manually keep it in sync and it would be confusing for users to receive conflicting information. Totally understand if you don't want to bother with that though. Let me know :)

**Comment by koekeishiya** [comment]
I think I'll just stick with GitHub only for now. This issue can remain open and maybe things change in the future.
