### ISSUE TITLE
Drag and drop does not work with Hazeover

### ISSUE THREAD

**Issue by tophee** [koekeishiya/yabai#1467]
[Hazeover ](https://hazeover.com/) is an app that dims windows that are not in focus. It does this by putting a layer (=window) of haze between the active window and everything underneath. As a result, yabai drag and drop no longer works because yabai detects the Haze-window instead of the intended app window. 

Is there any way to tell yabai to ignore the haze window?

**Comment by PsyMaza** [comment]
I also have some problems

**Comment by koekeishiya** [comment]
Is this still an issue?

**Comment by koekeishiya** [comment]
Unable to reproduce with yabai v6.0.15 and HazeOver 1.9.3 (1120)
