### ISSUE TITLE
Disable border for single window on the screen.

### ISSUE THREAD

**Issue by xbladesub** [koekeishiya/yabai#1470]
Is it possible disable border if there is only 1 window on the screen?

**Comment by 0xWaleed** [comment]
You could execute this command and it will disable the border for current active window
`yabai -m window --toggle border`
You need to key bind this command using [skhd](https://github.com/koekeishiya/skhd)

`ctrl - b : yabai -m window --toggle border`

**Comment by zakroma** [comment]
Thanks, but it would be cool to have it automated.

**Comment by koekeishiya** [comment]
You can use window rules to disable borders for specific applications or windows.
