### ISSUE TITLE
window_border on results in blurred screen sharing in Slack

### ISSUE THREAD

**Issue by rickythefox** [koekeishiya/yabai#1471]
A bit of a weird issue here. 

When yabai is configured with `window_border on` and you share you screen during a Slack call the whole screen is blurred. Setting `window_border off` removes the blur. This used to work fine in 4.x versions.

<img width="2048" alt="image" src="https://user-images.githubusercontent.com/1675955/193236993-d3e3676c-9157-4071-b7f8-796eb328691c.png">

**Comment by cherche** [comment]
As of 5.x, window border also includes a blur *behind* each window. This is only really noticeable with non-opaque windows, so if you've left `active_window_opacity` and `normal_window_opacity` as `1.0`, you likely would not have noticed this underlay.

Try setting `yabai -m config window_border_blur off`. I'm not familiar enough with yabai to know if it's possible to auatomatically disable `window_blur` for select windows using rules.

**Comment by rickythefox** [comment]
@cherche thanks, that worked! Would be nice to be able to disable the blur for select windows, like slack screen sharing.

**Comment by cherche** [comment]
@rickythefox Just did a [quick read of the docs](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule) and there is a way to automate this with rules, as long as it's possible to target the Slack screen sharing window:

```
yabai -m rule --add app="^Slack$" title="Window Title" border=off
```

You'll need to query windows (`yabai -m query --windows`) to see what info would uniquely identify Slack's screen sharing window.

**Comment by prdanelli** [comment]
I have a similar issue to this, but for MacOS's Mission Control (Show open windows). 

Borders on: 
![image](https://user-images.githubusercontent.com/1199977/198975739-ce8f791c-4e9a-4605-b725-139306927d7b.png)

Borders off: 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1199977/198975842-b33353c8-002d-42db-9307-1393ad2a94c3.png">

I have a shortcut to toggle the borders, but for stuff like screensharing in Slack, using mission control etc it feels like it might constitute bug.

**Comment by Allaman** [comment]
This happend to me when recording my screen with CleanshotX as well! `yabai -m config window_border_blur off` or `yabai -m config window_border off` solves the issue.

**Comment by dominiklohmann** [comment]
You should be able to detect these windows and to disable borders for them using a rule[^1], e.g., 

```bash
# Disable borders for all Slack windows that are not standard windows.
yabai -m rule--add app=^Slack$ subrole!=AXStandardWindow border=off
```

If you want to investigate this a bit further, I recommend using `yabai -m query --windows` to understand the unique characteristics of windows causing you issues. The problem here really is Slack creating a fully transparent window when screen sharing; yabai cannot possibly account for all edge cases like this.

[^1]: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule

**Comment by ArtemSmaznov** [comment]
> You should be able to detect these windows and to disable borders for them using a rule[1](#user-content-fn-1-b82e709c90ddf7625b847ef0ca677415), e.g.,
> 
> ```shell
> # Disable borders for all Slack windows that are not standard windows.
> yabai -m rule--add app=^Slack$ subrole!=AXStandardWindow border=off
> ```
> 
> If you want to investigate this a bit further, I recommend using `yabai -m query --windows` to understand the unique characteristics of windows causing you issues. The problem here really is Slack creating a fully transparent window when screen sharing; yabai cannot possibly account for all edge cases like this.
> 
> ## Footnotes
> 1. https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule [↩](#user-content-fnref-1-b82e709c90ddf7625b847ef0ca677415)

Looks like the transparent window is AXStandardWindow as well - I get 2 extra slack entries in the query. Or maybe those are something else and the transparent one is not detected as the extra ones have `level` that is not 0 as opposed to the main window but `yabai -m rule --add app="Slack" level!=0 border=off` doesn't affect the screenshare. Guess will need to play around with different parameters some more

**Comment by ricardoraposo** [comment]
I also managed to solve this problem by turning off the window_topmost setting
```
yabai -m config window_topmost               off
```

**Comment by koekeishiya** [comment]
Borders have been removed in the latest release (v6.0.0) (#1889) because of multiple issues present in both Ventura and Sonoma.

`window_topmost` has also been removed, and equivalent functionality has been introduced in a robust way #1887
