### ISSUE TITLE
yabai seems to ignore neovide when run from the command line

### ISSUE THREAD

**Issue by nerdo** [koekeishiya/yabai#1473]
I ran into a weird issue with yabai.

If I run neovide from the command line, yabai seems to ignore the window. It doesn't snap into place or seem to know it exists.

I confirmed this by running `yabai -m query --windows` and the window doesn't appear in the list.

But if I run it from spotlight or from the dock - basically anywhere other than the terminal - it gets recognized and works just like any other window.

Is there a workaround to make yabai notice it?

**Comment by HATTER-LONG** [comment]
I checked this same problem before, maybe this will help you [link].(https://github.com/neovide/neovide/issues/915#issuecomment-1198819067)

**Comment by nerdo** [comment]
Thanks!

The `--nofork` flag actually does work. Super weird, but I can live with that workaround for now.
