### ISSUE TITLE
Window not raising when focused

### ISSUE THREAD

**Issue by codegangsta** [koekeishiya/yabai#1474]
I just upgraded my yabai to 5.0.1 and now my windows no longer raise when I focus them with a `yabai -m window --focus north|south|east|west`. Some applications, like `kitty`, won't even accept input unless a window is raised.

I'm able to reproduce this on both my macbook pro m1 and my m1 mac studio.

Anybody else seeing something similar? Any ideas for workarounds?

**Comment by ljcolling** [comment]
yeah, I'm seeing this too

**Comment by isaacraja** [comment]
Is there a way to force window raising on focus?

**Comment by tophee** [comment]
Does "raising a window" include bringing minimized back up? In that case I'm seeing this even without yabai. I'm still trying to understand whether this is asMacOS thing or whether some apps don't conform to how they're supposed to behave.

**Comment by mtoohey31** [comment]
I'm seeing this with yabai 5.0.1 and macos 12.6.1. `yabai -m config focus_follows_mouse autoraise` also seems to be broken.

**Comment by mtoohey31** [comment]
I ran a bisect, and it looks like the commit that introduced the issue for me is d4aa4c9781dffb741d5348f1a8dbe01ee8047252.

**Comment by koekeishiya** [comment]
This was fixed in v5.0.4 or something.
