### ISSUE TITLE
Focus to a space doesn't work

### ISSUE THREAD

**Issue by nearsyh** [koekeishiya/yabai#1479]
Everything else works well (e.g. create a space, move a window to a space). However, changing the focus to a different space doesn't work.

```
# Current in space 2
$ yabai -m space --focus 2
cannot focus an already focused space.

$ yabai -m space --focus 1
# no output
```

Environment:
Version: yabai-v5.0.1
MacBook Pro 14 inch, M1 Max.
Ventura 13.0 (Beta 10)

I've tried `sudo yabai --load-sa`and I saw no error logs.

**Comment by Elido** [comment]
This works for me. Specifically next/prev.

Make sure you have some extra spaces created.

**Comment by juandpinto** [comment]
I've rebooted and have tried with extra spaces in both directions, but to no avail. @elido, are you on Ventura?

**Comment by koekeishiya** [comment]
![image](https://user-images.githubusercontent.com/6175959/194957178-74bfb6fc-147e-4b54-aadc-37af41fb4fb2.png)

> The scripting-addition won't inject on macOS Ventura because the code requires a versioning change to use the Mach API:
https://github.com/koekeishiya/yabai/blob/master/src/sa.m#L443. The code that is injected also needs to be updated.

https://github.com/koekeishiya/yabai/issues/1297#issuecomment-1170101565

**Comment by nearsyh** [comment]
Duplicate of https://github.com/koekeishiya/yabai/issues/1297#issuecomment-1170101565
