### ISSUE TITLE
The focus_follows_mouse configuration property applies to all spaces, regardless of whether --space (number) prefixes it.

### ISSUE THREAD

**Issue by Capta1nT0ad** [koekeishiya/yabai#1480]
Hi all,

I've been having an issue with yabai lately.

I like to have four spaces, two of which are tiled with `layout bsp` and the other two two floating with `layout float`. This works with no issues, and this is how I achieve this in my `yabairc`:

```bash
yabai -m config layout bsp
yabai -m config --space 3 layout float
yabai -m config --space 4 layout float
```

However, I would like windows in space 1 and 2 to follow the mouse focus while windows in space 3 and 4 to have normal window focusing. I have tried three approaches to this, both of which did not work (they made all windows across all spaces follow the mouse focus). Here they are:

_Approach 1_
```bash
yabai -m config focus_follows_mouse autoraise

yabai -m config --space 3 focus_follows_mouse disabled
yabai -m config --space 4 focus_follows_mouse disabled
```
_Approach 2_
```bash
yabai -m config focus_follows_mouse disabled

yabai -m config --space 1 focus_follows_mouse autoraise
yabai -m config --space 2 focus_follows_mouse autoraise
```
_Approach 3_
```bash
yabai -m config --space 1 focus_follows_mouse autoraise
yabai -m config --space 2 focus_follows_mouse autoraise
yabai -m config --space 3 focus_follows_mouse disabled
yabai -m config --space 4 focus_follows_mouse disabled
```
I would like to know whether I am missing something crucial, or if this is a bug.

Thanks to all the kind people who maintain this amazing open-source project!

**Comment by Capta1nT0ad** [comment]
Just realised that the problem was that I was using `disabled` instead of `off`. Sorry for wasting your time!
This is the configuration I meant:

```bash
yabai -m config --space 1 focus_follows_mouse autoraise
yabai -m config --space 2 focus_follows_mouse autoraise
yabai -m config --space 3 focus_follows_mouse off
yabai -m config --space 4 focus_follows_mouse off
```

I'll close this now.

**Comment by Capta1nT0ad** [comment]
Reopening because I just realised it has now disabled for all spaces.

**Comment by occludedpixel** [comment]
It seems like `focus_follows_mouse` can only be set globally (see [global settings](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#612-global-settings)). Only [these](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#613-space-settings) can be configured on a per-space basis. 

When you specify multiple settings for `focus_follows_mouse`:

> ```shell
> yabai -m config --space 1 focus_follows_mouse autoraise
> yabai -m config --space 2 focus_follows_mouse autoraise
> yabai -m config --space 3 focus_follows_mouse off
> yabai -m config --space 4 focus_follows_mouse off
> ```

I believe the last one is taken causing it to be disabled for all spaces.

A possible way to achieve what you want could be using a signal to change the setting for `focus_follows_mouse` based on the current space:

```
yabai -m signal --add event=space_changed action='space_index=$(yabai -m query --spaces --space | jq .index)
if [ $space_index -eq 3 ] || [ $space_index -eq 4 ]; then setting="autoraise"; else setting="off"; fi
yabai -m config focus_follows_mouse $setting'
```

**Comment by Capta1nT0ad** [comment]
> It seems like `focus_follows_mouse` can only be set globally (see [global settings](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#612-global-settings)). Only [these](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#613-space-settings) can be configured on a per-space basis.
> 
> When you specify multiple settings for `focus_follows_mouse`:
> 
> > ```shell
> > yabai -m config --space 1 focus_follows_mouse autoraise
> > yabai -m config --space 2 focus_follows_mouse autoraise
> > yabai -m config --space 3 focus_follows_mouse off
> > yabai -m config --space 4 focus_follows_mouse off
> > ```
> 
> I believe the last one is taken causing it to be disabled for all spaces.
> 
> A possible way to achieve what you want could be using a signal to change the setting for `focus_follows_mouse` based on the current space:
> 
> ```
> yabai -m signal --add event=space_changed action='space_index=$(yabai -m query --spaces --space | jq .index)
> if [ $space_index -eq 3 ] || [ $space_index -eq 4 ]; then setting="autoraise"; else setting="off"; fi
> yabai -m config focus_follows_mouse $setting'
> ```
This doesn’t seem to do anything. Am I missing something?

**Comment by occludedpixel** [comment]
Do you have `jq` installed?

**Comment by Capta1nT0ad** [comment]
> Do you have `jq` installed?

No, I just installed it (`brew install jq`) and restarted yabai (`brew services restart yabai`) and nothing happened.

**Comment by occludedpixel** [comment]
For debugging purposes, could you use this signal instead:

```
yabai -m signal --add event=space_changed action='space_index=$(yabai -m query --spaces --space | jq .index)
if [ $space_index -eq 3 ] || [ $space_index -eq 4 ]; then setting="autoraise"; else setting="off"; fi
yabai -m config focus_follows_mouse $setting
echo focus_follows_mouse $setting'
```

It just adds a line at the end to echo out the setting change. 

After restarting yabai, switch to space 3 or 4 then check the last few lines of the `yabai.out.log`. Does `focus_follows_mouse autoraise` or `focus_follows_mouse off` appear?

**Comment by Capta1nT0ad** [comment]
> ```
> yabai -m signal --add event=space_changed action='space_index=$(yabai -m query --spaces --space | jq .index)
> if [ $space_index -eq 3 ] || [ $space_index -eq 4 ]; then setting="autoraise"; else setting="off"; fi
> yabai -m config focus_follows_mouse $setting
> echo focus_follows_mouse $setting'
> ```

This works! I don't know what I was doing wrong before (maybe I copied/pasted it wrong?) but now it works as expected (also without the `echo` statement. Thanks for your help!
