### ISSUE TITLE
Place border on top of windows

### ISSUE THREAD

**Issue by itaysharir** [koekeishiya/yabai#1485]
What downsides would that have?

Because borders are placed on top of windows, when i leave them rounded, in certain apps that have squared corners they look like this:
![Screenshot](https://user-images.githubusercontent.com/87126382/195993550-733b3bb8-8cbb-467d-8c6b-f15589f9be33.png)

**Comment by s-h-o-t** [comment]
https://github.com/koekeishiya/yabai/issues/1460#issuecomment-1260825042

**Comment by itaysharir** [comment]
Oh, didn't see that.
