### ISSUE TITLE
Ability to make "child window" the new "main" window?

### ISSUE THREAD

**Issue by v7rzlhb3xg** [koekeishiya/yabai#1488]
If I have the following window set-up:

> ```
>  ┌─────────────────┬─────────────────┐
>  │                 │                 │
>  │                 │                 │
>  │                 │        b        │
>  │                 │                 │
>  │         a       ├─────────────────┤
>  │                 │                 │
>  │                 │                 │
>  │                 │        c        │
>  │                 │                 │
>  └─────────────────┴─────────────────┘

I'd like to make window c the "main" window of the node, however with c selected and warping the window west simply splits it with a rather than making it the new primary window like so:

> ```
>  ┌─────────────────┬─────────────────┐
>  │                 │                 │
>  │                 │                 │
>  │        a        │                 │
>  │                 │                 │
>  ├─────────────────┤        b        │
>  │                 │                 │
>  │                 │                 │
>  │         c       │                 │
>  │                 │                 │
>  └─────────────────┴─────────────────┘

Instead of what I'd like the outcome to be:
> ```
>  ┌─────────────────┬─────────────────┐
>  │                 │                 │
>  │                 │                 │
>  │                 │        a        │
>  │                 │                 │
>  │         c       ├─────────────────┤
>  │                 │                 │
>  │                 │                 │
>  │                 │        b        │
>  │                 │                 │
>  └─────────────────┴─────────────────┘

Is there an easy way of achieving this?

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/wiki/Commands#window-commands

> The following illustrates how you can use the swap operation to implement window cycling.

> cycle_clockwise.sh:

```
#!/bin/bash

win=$(yabai -m query --windows --window last | jq '.id')

while : ; do
    yabai -m window $win --swap prev &> /dev/null
    if [[ $? -eq 1 ]]; then
        break
    fi
done
```

**Comment by v7rzlhb3xg** [comment]
Thanks! I was wondering if there was a more elegant way of immediately swapping any child window with the "main" window like Amethyst without having to cycle through all of them, but this works for now.

**Comment by koekeishiya** [comment]
`yabai -m window --swap largest`
