### ISSUE TITLE
App names with double quotes (") not escaped in yabai queries

### ISSUE THREAD

**Issue by wernjie** [koekeishiya/yabai#1489]
I've recently stumbled across an app with an app name containing double quotes, which caused `yabai -m query --windows --window` to output invalid json. [From the source code here](https://github.com/koekeishiya/yabai/blob/c888d80540a580c61e68ee3f6682fb0099962f0e/src/window.c#L175), it appears while app window titles are escaped, app names are not.

This has consequences like being able to inject arbitrary data into queries, though I don't think there's much harm that can be done just from that alone.

**Comment by koekeishiya** [comment]
Do you have a sample? The app name is pulled from what is shown in *Activity Monitor* and I didn't think those could contain quotes and such.

**Comment by wernjie** [comment]
![hello_world_poc](https://user-images.githubusercontent.com/26833058/196231126-f03c11cf-b2c0-4fda-9021-b92e24606634.png)

This is a fresh macOS app created in Xcode.

This can be reproduced by just setting the `CFBundleDisplayName` key in a macOS app's `Info.plist` to `"Hello World"`, or any other text that includes the double quotes.
