### ISSUE TITLE
Zoom parent with first_child window placement

### ISSUE THREAD

**Issue by uri** [koekeishiya/yabai#149]
I'm using the following option in my config: `yabai -m config window_placement first_child`

When I open 3 windows on a vertical monitor it initially looks like this:

```
3      2

    1
```

If I execute a `yabai -m window --warp south` on *2* to get the following layout:

```
3
2
1
```

Then if I zoom-parent on *2*, it ends up expanding over *1*. This is also what happens when *window_placement* is set to *second_child*. However, I would expect *2* to expand over *3* while using the *first_child* option.

If I execute `yabai -m space --mirror x-axis` the zooming works as I would expect.

**Comment by koekeishiya** [comment]
This is not a bug.  The *parent* simply means the parent node in the bsp-tree. The window marked by *1* and *2* belong to an invisible parent node. To get your behaviour you need to perform a *window --warp north*
