### ISSUE TITLE
Switching spaces to a blank space manually does not update focus.

### ISSUE THREAD

**Issue by amusingimpala75** [koekeishiya/yabai#1490]
This results in odd situations wherein in one space I have Emacs open (or Alacritty, this happens with both) and when I switch to an blank space the focus does not transfer, and so I am left with a modified cursor to represent what it should be based off the location in the Emacs window. In fact, if I move it around, I can get it to show the tooltip from the Emacs window on the blank desktop. This is with SIP enabled, so I cannot change spaces with Yabai.

**Comment by 0xWaleed** [comment]
Did you try to restart your machine? also sometimes killing Dock process will help.

**Comment by amusingimpala75** [comment]
I first killed Dock, and then restarted. It still acts oddly. Here's a GIF of the unexpected behaviour:
![yabai_focus_oddities](https://user-images.githubusercontent.com/69653100/197108719-7fd47eec-0460-4a23-9ba2-7cdca3533851.gif)

**Comment by koekeishiya** [comment]
Sounds like a macOS issue to me, nothing yabai can do here.
