### ISSUE TITLE
focus System Preferences when invoked through menu bar

### ISSUE THREAD

**Issue by arulagrawal** [koekeishiya/yabai#1491]
Apologies for the title, didn't know what else to put. Here is what I am trying to do:
I have the following rule:
`yabai -m rule --add app='System Preferences' manage=off layer=above` which works to float System Preferences.

If I then minimize System Preferences, and go to the menu bar, and say click on the wifi icon and click network preferences, System Preferences is not brought up at all. Instead I have to click on the icon in the dock to bring it up. Is there a way to have this happen?

**Comment by koekeishiya** [comment]
This sounds like a macOS quirk to me, nothing that yabai can do.
