### ISSUE TITLE
1password Show Quick Access will trigger window_destroyed signal

### ISSUE THREAD

**Issue by jheroy** [koekeishiya/yabai#1492]
I use
```
yabai -m signal --add event=window_destroyed action="~/.config/yabai/auto_focus_last.sh"
```
to foucs last used window after current window was destroyed, but when I open 1passowd Quick access, it will prompt a  touchID popup window, but also trigger a `window_destroyed` signal which will change the focus, so I can't use my touchID to unlock 1password.

my auto_focus_last.sh
```
focusId=$(yabai -m query --windows --space | jq -r '.[]|select(."has-focus" == true)'|jq '.id')
if [[ "$focusId" != "" ]];then
        exit 0
fi

id=$(yabai -m query --windows --space | jq .[0].id)
yabai -m window --focus $id
```

**Comment by koekeishiya** [comment]
Might be resolved in latest version.
