### ISSUE TITLE
Browser windows flickering on link hover

### ISSUE THREAD

**Issue by alexandersix** [koekeishiya/yabai#1498]
Hi there! I just installed Yabai this morning and so far, it's been pretty good! I'm having one issue, though, that is really making it tricky to use effectively.

When I open up my browser (Brave Browser) and hover over just about anything that is a link (popup or not), the browser window starts flickering and jumping around, making it incredibly difficult to click on anything.

Additionally, and this may or may not be related, when I hit CMD + f to open up the find UI in the browser, the dialog never appears. An icon in the URL bar appears as if the find has opened, but that's it.

I've attached a short screen capture and my Yabai configuration file below. I absolutely could just be doing something ridiculous, so if there's something unusual about my configuration, let me know! 

Some more details on my specific circumstances:
- I have SIP entirely disabled as I try to debug this
- I am running a 16" MBP with M1 Max chip
- I set up the sudoers file as defined in the installation instructions and ran the M1 specific command in the instructions

<details>
<summary>
Screen Capture
</summary>

https://user-images.githubusercontent.com/11881203/197441273-8172430f-d557-4b57-962b-5efd48ac0869.mov

</details>

<details>
<summary>
Yabai Configuration
</summary>

```
# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# logging on
yabai -m config debug_output on

# default layout
yabai -m config layout bsp

# useless gaps
yabai -m config top_padding 20
yabai -m config right_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config window_gap 20

yabai -m config external_bar all:30:0

# auto-balance windows
yabai -m config auto_balance off

# split ratios
yabai -m config split_ratio 0.5

# mouse interaction
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# floating windows always on top
yabai -m config window_topmost on

# window shadows
yabai -m config window_shadow float

# active window borders
yabai -m config window_border on
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xffa6da95
yabai -m config normal_window_border_color 0xfff4dbd6

# application rules
yabai -m rule --add app="System Preferences$" manage=off
yabai -m rule --add app="Dash$" manage=off
yabai -m rule --add app="Zoom$" manage=off
yabai -m rule --add app="Microsoft Teams$" manage=off

```

<details>

That's all the information I have at the moment, but if there's something else you need from me or some way I can help with the issue, please let me know!

**EDIT**

10/24 - Just an additional note, this happens immediately upon starting Yabai. No toggling or floating needed–I start Yabai via Homebrew and the browser immediately has this issue. Hope that helps a bit!

**Comment by mgazda** [comment]
I have the same issue - windows flickering when I hover over links (with google chrome) and "popup windows" (like the search in a browser but also others in different apps) appearing below the main window (visible only when I press Ctrl+up).

One scenario to reproduce some of this is when I toggle a window to float (with a shortcut defined as below) it starts to cover its own popups. When I move the window a little it starts working correctly. Toggling it to managed and back to float breaks it back.

`alt - t : yabai -m window --toggle float;
yabai -m window --grid 4:4:1:1:2:2`

A workaround to fix this that seems to work is to turn off windows_topmost in the config. I don't know if it fixes the flickering too as this one is more random...

**Comment by chasonyu** [comment]
I have the same issue on microsoft edge. Is there any way to solve the problem？

**Comment by UberChili** [comment]
Have this exact same problem, quick fix is to just float then tile back the browser window with a shortcut. Currently will test if @mgazda's tip on setting windows_topmost off helps.

**Comment by HATTER-LONG** [comment]
I tested this problem in both safari and edge browsers. Is there any good solution?

**Comment by UberChili** [comment]
> Have this exact same problem, quick fix is to just float then tile back the browser window with a shortcut. Currently will test if @mgazda's tip on setting windows_topmost off helps.

The problem got back after a while and it is kind of annoying to float and tile again all the time. 
Setting windows_topmost off doesn't help

**Comment by UberChili** [comment]
I updated yabai through brew and the problem got fixed. I have no idea what was causing it.

**Comment by HATTER-LONG** [comment]
I updated Yabai through brew, but still have same problem, but I found it not happen when I delete rule for safari.
e.g:
```shell
#yabai -m rule --add app="^(Microsoft Edge|Safari浏览器)$" manage=on opacity=1.00 border=on
```
