### ISSUE TITLE
Yabai autofocusing option makes Excel popups inaccessible

### ISSUE THREAD

**Issue by pcr910303** [koekeishiya/yabai#15]
Yabai's autofocusing option makes Excel popups inaccessible.
Below is a GIF that explains the problem.
It starts with the autofocusing turned on, and opens the terminal and turns off autofocusing.
![yabai-excel](https://user-images.githubusercontent.com/37990858/58750486-380cc080-84ce-11e9-9b6b-f66c5b5fd92f.gif)
The problem isn't apparent because of the low GIF frame rate due to the 10MB limit; 
When (autofocusing is turned on and) I try to move my mouse over the popup, the popup disappears, rendering the Excel ribbon menu completely unusable 😞 I turned off yabai (and turned on chunkwm for a while) to use Excel right now... and I'm sure this problem wasn't here last week.

**Comment by koekeishiya** [comment]
Fixed on master.

**Comment by pcr910303** [comment]
Can confirm that the problem is fixed.
