### ISSUE TITLE
Moving window from screen w/o to screen w/ StatusBar

### ISSUE THREAD

**Issue by marcelja** [koekeishiya/yabai#150]
The moved window is not matching the status bar.
E.g. I moved Spotify from another screen (which had a dual split), which has no status bar:

![image](https://user-images.githubusercontent.com/12141700/61618532-5b9ded00-ac6d-11e9-8b13-c458d3373d37.png)

**Comment by koekeishiya** [comment]
This is not an issue related to the statusbar, but happen regularly when moving a window to a d ifferent display. Closing in favour of #188
