### ISSUE TITLE
Yabai disables native Switch to Desktop animation

### ISSUE THREAD

**Issue by williamhCode** [koekeishiya/yabai#1501]
I have these native shortcuts enabled:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/83525937/197605239-9d4d6985-6e8b-45ec-a800-60aca6661af5.png">
If I don't enable Yabai, using these shortcuts show the native mac animation. However if I enable Yabai, the animations get disabled. This also applies to cmd + tab and you switch to an application in another window. Even after I disable Yabai, I need to restart to get the animations back. It only effects the `Switch to Desktop` shortcuts, not `Move left/right a space`.

macOS version = 12.6
yabai version = 5.0.1

**Comment by net** [comment]
I prefer this behavior and consider it a feature.

**Comment by williamhCode** [comment]
There should be a least an option to toggle it on/off thou. I use the `reduce motion` settings under Accessibility Display and I like to better than no animation at all. 

Also if you wanted to switch desktops without animation, you can use `yabai -m space --focus 1`. I get that for cmd + tab, there no alternative, but it should still be optional and not forced on all users.

Additional problem is it also doesn't deactivate when Yabai is disabled.

**Comment by net** [comment]
> Also if you wanted to switch desktops without animation, you can use yabai -m space --focus 1. I get that for cmd + tab, there no alternative, but it should still be optional and not forced on all users.

Yes, I meant the behavior modifying other space switches (like cmd+tab, although in my case I use [AltTab](https://alt-tab-macos.netlify.app) and it thankfully modifies that too). I agree a setting would be ideal though.

**Comment by koekeishiya** [comment]
I'm not particularly interested in making this customisable at this time.
