### ISSUE TITLE
sudo yabai --load-sa not work on macos 13

### ISSUE THREAD

**Issue by huwqchn** [koekeishiya/yabai#1503]

**Comment by kalamov** [comment]
Hi. I had the same problem. koekeishiya told me in a neighboring issue that when you write the command "brew install yabai", it installs the 5.0.1 release.

koekeishiya made changes to the master branch and hasn't done a release yet. So you have to install yabai with brew install yabai --HEAD to make it work correctly. But before that you need to create a certificate. Instructions: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

It didn't work right the first time but it worked. I combined the commands:

sudo yabai --load-sa
brew services restart yabai

Translated with www.DeepL.com/Translator (free version)

**Comment by usmajeed** [comment]
Getting this error on Ventura: "cannot focus space due to an error with the scripting-addition."

**Comment by huwqchn** [comment]
Get this error on mac os 13 Ventura,
![image](https://user-images.githubusercontent.com/12139734/198924952-b7ae0eb0-91f8-4a51-9e49-f5f3502bc2d3.png)

**Comment by wdylanbibb** [comment]
> I'm struggling with installing `--HEAD`. Without it, the scripting additions dont allow me to move windows to different desktops and follow them there, but with it, I'm seeing an Accessibility Access popup about every 20 seconds:
> 
> <img alt="image" width="495" src="https://user-images.githubusercontent.com/1199977/200039833-007c86d6-b1b7-4f4a-a0a5-fab24bba357e.png">
> 
> But its already enabled...
> 
> <img alt="image" width="986" src="https://user-images.githubusercontent.com/1199977/200039682-7cdd07ca-8f29-4bbe-9db1-009fe7bf3117.png">

Did you manually add the yabai executable using the '+' button after installation, as per the instructions on [installing from HEAD](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD))? That's what seemed to work for me (I say seemed as I also did not create a certificate using `Certificate Assistant` when I had your issue).

**Comment by prdanelli** [comment]
@wdylanbibb Thank you for your response. I hadn't followed those originally, but I just followed them and it resulted in the same issues, the Accessibility Access settings popping up every 8 seconds. 

I'm also installing Yabai via Homebrew, if that matters?

**Comment by z20240** [comment]
Thank @wdylanbibb , I follow your suggestion to add yabai to grant list manually then start it. It works.

**Comment by koekeishiya** [comment]
install the latest version (v5.0.2) and make sure you have followed the wiki instructions exactly as written.
If you still have issues read this comment for instructions on how to debug your setup: https://github.com/koekeishiya/yabai/issues/1515#issuecomment-1344070256

**Comment by prdanelli** [comment]
Working for me with v5.0.2. Thank you so much for the time you have invested in this project.
