### ISSUE TITLE
Cannot create or destroy spaces in MacOS 13

### ISSUE THREAD

**Issue by probaton** [koekeishiya/yabai#1506]
# Gushing
First of all thanks for all the hard work! I cried for days when my company first condemned me to work with a MacBook, and it's only because of Yabai that the experience has been bearable. Y'all are amazing. 

# Actual issue
MacOS version: 13.0
Yabai version: 5.0.1

Entirely against my will I was forced to update to MacOS 13 Ventura, and after battling my way through updating to the CommandLineTools rc, I found out that nearly everything works except for creating and destroying spaces. I can run the commands below just fine, both exit with code 0 and provide no output (errors or otherwise), but neither of them have any discernible effect on any of my spaces. 
```
yabai -m space --destroy 1
yabai -m space --create
```

Note that running either command with an invalid index will trigger the expected null-pointer.
```
could not locate space with mission-control index '12'.
```

# Disclaimer
Of course I've read your GitHub page and I understand that MacOS 13 isn't supported. I'm reporting this because I figured you should know, not necessarily because I'm expecting a speedy fix.

**Comment by kalamov** [comment]
Hi. I had the same problem. koekeishiya told me in a neighboring issue that when you write the command "brew install yabai", it installs the 5.0.1 release.

koekeishiya made changes to the master branch and hasn't done a release yet. So you have to install yabai with brew install yabai --HEAD to make it work correctly. But before that you need to create a certificate. Instructions: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

It didn't work right the first time but it worked. I combined the commands:

sudo yabai --load-sa
brew services restart yabai

Translated with www.DeepL.com/Translator (free version)

**Comment by probaton** [comment]
@kalamov That was a _lot_ more work than I'd hoped it would be, and there's one or two things that are still a little wonky, but it looks like it worked! Thanks for much for the tip!
