### ISSUE TITLE
Drop downs on android studio are impossible to use

### ISSUE THREAD

**Issue by anuragrao04** [koekeishiya/yabai#1509]
When Focus Follows Mouse is set to `autofocus`, the drop downs on android studio are impossible to use. My guess is that yabai is treating the drop-downs as a separate window, and the moment I move the mouse, the drop-down disappears and the focus is back to the main android studio window. 
Video reference: 

https://user-images.githubusercontent.com/77329899/198822409-0bc5b250-1952-4b7c-b40a-1c31933ed41c.mov

**Comment by yshym** [comment]
You can try to use [subrole](https://github.com/koekeishiya/yabai/issues/1398) ([apple docs](https://developer.apple.com/documentation/applicationservices/carbon_accessibility/subroles)) like `yabai -m rule --add app="^Android Studio$" subrole=AXStandardWindow manage=on`. Just replace the name of the app. Not sure what the correct name is

**Comment by anuragrao04** [comment]
Adding this to .yabairc did not work. I have installed the dev version of yabai (--HEAD) and have verified that the application name is 'Android Studio'.

**Comment by anuragrao04** [comment]
Something that might be of help: even when the whole of Android Studio is in managed=off, the drop downs are still impossible to use.

**Comment by yshym** [comment]
> Something that might be of help: even when the whole of Android Studio is on managed=off, the drop downs are still impossible to use.

If you really disabled management by yabai and the issue still persists then the problem is about the application itself or something related to your setup, but not yabai

**Comment by yshym** [comment]
I'd recommend to make sure that the name of the app is correct `yabai -m query --windows` and if it is try to read the docs about subroles and experiment. But make sure that yabai is the issue before doing that

**Comment by anuragrao04** [comment]
It is related to yabai because when 'focus follows mouse' is turned off, the drop-downs work as expected. I have verified the app name. This would have something to do with a rule related to focus follows mouse. I will go through the docs later today and get back here if I find a solution!

**Comment by andryandrew** [comment]
Just as an added datapoint, the same exact issue happens in Zoom too and doesn't go away even when unmanaged. A way to solve this would be to disable `focus_follows_mouse` per application, which does not seem possible at the moment (only `mouse_follows_focus` can be set)

**Comment by anuragrao04** [comment]
can you please point me at documentation or any post on how to use the `mouse_modifier`

**Comment by andryandrew** [comment]
You should have a line in yabai configuration which tells you which key is your mouse modifier, the default is `fn`:
```
yabai -m config mouse_modifier fn
```
If you move the mouse while holding down the mouse modifier key, `focus_follows_mouse` won't be triggered.

**Comment by anuragrao04** [comment]
Thanks a lot! I’ll look into it later today. Not near my machine at the moment

**Comment by insomnia-creator** [comment]
+1
