### ISSUE TITLE
bug: gap settings are ignored when a window is created from a full-screen view

### ISSUE THREAD

**Issue by mil-ad** [koekeishiya/yabai#1512]
Let's say I have 2 windows on a space and I've put one in fullscreen view (via `yabai -m window --toggle zoom-fullscreen`). If a new window is created while I'm in this full-screen view the gap settings are ignored: I'm automatically thrown out of the full screen view (which I guess is the right behaviour) but the new window is created with no gaps. Moreover, the window that used to be full-screen goes to its old non-fullscreen size/location as if the third window has not been created. If I then put any window in and out of fullscreen the whole space is refreshed correctly.

**Comment by occludedpixel** [comment]
Is what you are experiencing similar to https://github.com/koekeishiya/yabai/issues/1481#issuecomment-1279765707 ?

**Comment by mil-ad** [comment]
I think they're related. Here's a little gif showing the problem.

I start with two windows and then put the top one into full-screen. I then create a new window which takes me out of full screen but the location and gap of the top windows are wrong. I then take the new window into fullscreen and back. This has no effect. But when I take the old window into fullscreen and back the windows jiggle themselves into the right place with the correct gap

![output3](https://user-images.githubusercontent.com/686449/199585994-049146de-fb03-4b39-8a6c-8b20460230a0.gif)

**Comment by koekeishiya** [comment]
This was likely resolved in some version and should not be a problem in the latest release.
