### ISSUE TITLE
can not switch space due to a problem with scriptting addition on MacOS Ventura 

### ISSUE THREAD

**Issue by agluck91** [koekeishiya/yabai#1515]
macOS version 13.0
Yabai version: HEAD

csrutil status output is System Integrity Protection status: disabled

already tried reinstall scripting-addition sudo yabai --uninstall-sa && sudo yabai --load-sa

**Comment by cjohnston1158** [comment]
Are you using --HEAD?

https://github.com/koekeishiya/yabai/issues/1506#issuecomment-1293906065

**Comment by muhsin-arslan** [comment]
Same here with --HEAD

**Comment by imAliAzhar** [comment]
I had the same problem after upgrading to macOS 13.0. Installing with brew --HEAD fixed the issue. Thanks!

**Comment by marc-brouard** [comment]
Also having this issue, but when i use brew --HEAD i get the following error

```
xcrun clang src/manifest.m src/osax/payload_bin.c src/osax/loader_bin.c -std=c99 -Wall -DNDEBUG -O2 -fvisibility=hidden -mmacosx-version-min=11.0 -fno-objc-arc -arch x86_64 -arch arm64 -F/System/Library/PrivateFrameworks -framework Carbon -framework Cocoa -framework CoreServices -framework SkyLight -o bin/yabai
In file included from src/manifest.m:71:
src/workspace.m:109:31: error: property 'safeAreaInsets' not found on object of type 'NSScreen *'
                return screen.safeAreaInsets.top;
                              ^
1 error generated.
make: *** [bin/yabai] Error 1
```

Any suggestions where I am going wrong?

**Comment by agluck91** [comment]
I finally got this to work. So, for others that may have the same problem. 
I had to fully uninstall and reboot
Then I reinstalled using the --HEAD option. 
Then I created my cert
Then I code signed both /opt/homebrew/bin/yabai and /opt/homebrew/yabai-<hash>/bin/yabai
Then I was able to brew services start and I had to add the /opt/homebrew/yabai to accesibility directly.

That was the only combination of things that worked for me, following the step directly in the link did not work for me.

**Comment by agluck91** [comment]
Actually, wait, this did not fix it, even installing with --HEAD and getting all that set up, I am still not able to run it

![image](https://user-images.githubusercontent.com/113385018/200936364-fac511b5-5503-44ea-8496-e4dea3d40e88.png)

**Comment by azinsharaf** [comment]
I am getting the same error on Ventura 13.0 with yabai HEAD.

**Comment by azinsharaf** [comment]
i was able to fix it to after commenting out the scripting-addition line. It was giving me syntax error and i am not familiar with its syntax. @agluck91 maybe if you post your sudoers file (that you added scripting-addition) contributers here can help.

one way that can help you find the syntax error would be 
- stop yabai service
- run 'yabai' in terminal. it showed me the lines that have syntax error.

**Comment by agluck91** [comment]
Hey @azinsharaf 
There is only one line in my yabai sudoers file:
it looks like this with the proper substitutions in the brackets. `<user> ALL = (root) NOPASSWD: sha256:<hash> <yabai> --load-sa`

the top of my yabairf file looks like this: `yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa`

**Comment by agluck91** [comment]
It unfortunately does not show any errors when I run it directly in the command line. Well, I am getting failed to inject Dock.app. But that is the error that I get when I hav already ran load-sa once.

**Comment by im6h** [comment]
Hi, I have got the error and I try to remove yabai with `brew uninstall yabai` then install with --HEAD with `yabai-cert` created, load with `sudo yabai --load-sa` and finally `brew services restart yabai`. It is working now. 

Check your version:
<img width="763" alt="Screenshot 2022-11-10 at 23 20 07" src="https://user-images.githubusercontent.com/35485655/201150097-7a31e550-8d31-4cdf-8411-5781bd7bc364.png">

**Comment by agluck91** [comment]
![image](https://user-images.githubusercontent.com/113385018/201968718-dcdca116-e8be-4cee-9928-589806f0b371.png)
I am on the proper version, I even see the commit message for the fixes as well when it is pulled fresh. 

This screen shot was taken right after uninstalling and reinstalling with --HEAD it did mention that I was already on 206c0d6 though because I went through it recently. ry is an alias to brew services restart yabai, as I seem to have to do it frequently, there are often times it misses some windows and does not tile them.

**Comment by chivalryq** [comment]
Hi guys, I have the same issue: 
- Install with --HEAD, on commit 206c0d6
- Already add sudoer:

```shell
sh-3.2# cat /private/etc/sudoers.d/yabai
qiaozp ALL = (root) NOPASSWD: sha256:2e7f8f60415f405a99bf0b1a67c293b63dc13d160e194a0c2411df16cf1473c2  /opt/homebrew/bin/yabai --load-sa
```

- Can run `--load-sa` (Firstly I can't, but after I uninstall it, `-load-sa` works.
<img width="611" alt="image" src="https://user-images.githubusercontent.com/47812250/202229222-c50f9c01-e2d8-49f4-a1c6-ba31da353c49.png">

- Add permissions in `Preferences`
- But I can't run `yabai -m space --focus  1`

<img width="606" alt="image" src="https://user-images.githubusercontent.com/47812250/202229986-3cd16a87-3c73-4f4a-9444-0ded4724d331.png">

**Comment by timhradil** [comment]
Did you add the Certificate as described here: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)?

**Comment by azinsharaf** [comment]
It is working for me. Yabai `5.0.1` (HEAD) on Macbook Pro M1 Max with Ventura 13.0.1 operating system. 
It has some focusing issue but that is different. 
Any error in `yabai -V`?

**Comment by azinsharaf** [comment]
@brightpuddle It seems my SIP is disabled completely. Honselty not sure if it matters but maybe give it a try?
```
csrutil status
System Integrity Protection status: disabled.
```

**Comment by alexanderflink** [comment]
Just want to confirm I have the same issue `cannot focus space due to an error with the scripting-addition.` on an M1 Macbook pro (Ventura 13.0.1). I've installed from HEAD, currently on commit [c02de22](https://github.com/koekeishiya/yabai/commit/c02de22e0c7c653d2048fd15eb1f86677d0f43e5). Made sure the certificate is set up and applied according to the installation guide.

**Comment by alexanderflink** [comment]
@azinsharaf Could you check which commit you installed yabai from HEAD from? You can find it by doing `ls /opt/homebrew/Cellar/yabai`

**Comment by azinsharaf** [comment]
`HEAD-206c0d6`

**Comment by alexanderflink** [comment]
Tried manually installing yabai from `206c0d6`. Still getting the same error `cannot focus space due to an error with the scripting-addition`. Tried removing and re-installing the scripting addition and yabai multiple times. Also tried completely disabling SIP if that would make any difference. Very strange. 🤔 @koekeishiya Is there any way to get a debug log from the scripting addition?

**Comment by koekeishiya** [comment]
@alexanderflink 

https://github.com/koekeishiya/yabai/issues/1054#issue-1058384717

**Comment by brightpuddle** [comment]
This resolved it for me. Even though I'd done this in the past, at some point the boot-args had reverted. Regardless of whether this is the same issue others are experiencing, thanks for the comprehensive guide--the detailed troubleshooting steps were really helpful.

**Comment by alexanderflink** [comment]
Thank you! Turns out my issue was the same as above. boot-args had reverted somehow. I set it again and restarted. Fixed the issue.
