### ISSUE TITLE
Issues with window borders

### ISSUE THREAD

**Issue by dotzenith** [koekeishiya/yabai#1517]
Hi, yabai is currently installed on my system from `HEAD`.

I've noticed some weird gaps between the window border and the window itself: 
![borders](https://user-images.githubusercontent.com/77712443/200490361-8e430380-266a-44fe-91a3-aaac8bed80a3.png)

Any idea why this is showing up? and if it's a known bug, any way to fix it?

**Comment by dotzenith** [comment]
@kvndrsslr I haven't set the border radius in my config, this is the yabai default. do you know what the default value yabai sets for the window border radius so I can adjust it?

**Comment by dotzenith** [comment]
hm looks like it's set to 12 by default, changing it to 14 almost resolves the issue but produces a similar artifact on the top portion of windows

**Comment by kvndrsslr** [comment]
yes it's difficult to trace *every* window perfectly. increading the border size helps in that regard as it covers up those leftover pixels. I myself still prefer radius 0, together with the new `blur` option it's even usable without patching the OS border masks.
