### ISSUE TITLE
How to disable all features except border-drawing feature.

### ISSUE THREAD

**Issue by eisukeesaki** [koekeishiya/yabai#1523]
How could one disable all features except the border-drawing feature?

Having updated macOS to Monterey, I had to move on from [limelight](https://github.com/koekeishiya/limelight) to yabai.

For now, I just want to run yabai solely for drawing borders around windows like limelight.

How can I disable all yabai's features including the core ones like window tiling, except the border-drawing feature?

**Comment by eisukeesaki** [comment]
I think [limelight's informational issue](https://github.com/koekeishiya/limelight/issues/37) should be linked to this issue.

**Comment by timhradil** [comment]
Add `yabai -m config layout float` to .yabairc to remove the window tiling. What else, in specific, are you trying to remove?

**Comment by eisukeesaki** [comment]
> Add `yabai -m config layout float` to .yabairc to remove the window tiling. What else, in specific, are you trying to remove?

Thank you @timhradil. That was all I needed.
