### ISSUE TITLE
Telegram app (from Mac App Store) does not tile

### ISSUE THREAD

**Issue by HeySora** [koekeishiya/yabai#1524]
Using yabai 5.0.1, Telegram is the only affected app that yabai cannot see for some reason (a yabai window query straight up ignores Telegram)  
Telegram version 9.1.1.238861

**Comment by AleksandrLiadov** [comment]
Thanks, for your issue, I wanted to created the same one 👍 

Yabai don't see Telegram app with:
**`yabai -m query --windows --space`**

**Comment by kalamov** [comment]
Same problem!

**Comment by zakroma** [comment]
There's already an issue about telegram #957

**Comment by kalamov** [comment]
Temporarily installed manually the old version 9.1 (238837), link - https://install.appcenter.ms/users/keepcoder/apps/telegram-swift/distribution_groups/public

**Comment by zakroma** [comment]
Great news everyone! 

Telegram 9.1.239550 fixes the problem and is getting recognized by yabai!

**Comment by armand1m** [comment]
@zakroma that indeed did the trick, thank you!
