### ISSUE TITLE
sudoers question

### ISSUE THREAD

**Issue by azinsharaf** [koekeishiya/yabai#1526]
Can you show me how to find the value of  `<user>  <hash>  and <yabai>` so i can edit the sudoers? I think I should edit the sudoers using those values .

`<user> ALL = (root) NOPASSWD: sha256:<hash> <yabai> --load-sa`

**Comment by mpeterson** [comment]
`<user>`: `whoami`
`<hash>`: ```sha256sum `which yabai`|cut -f 1 -d' '```
`<yabai>`: `which yabai`
