### ISSUE TITLE
window edges 

### ISSUE THREAD

**Issue by mnkhprre** [koekeishiya/yabai#1528]
<img width="724" alt="4_0" src="https://user-images.githubusercontent.com/54448793/202413483-d927407a-fe89-446d-810a-ec4ab7a11c8c.png">
<img width="725" alt="5_0" src="https://user-images.githubusercontent.com/54448793/202413505-9cbed278-09bc-49fa-900d-57061e64350b.png">

how to change it window edges like in 4.0 version?

**Comment by timhradil** [comment]
It looks like when adding the window_border_radius config option the default value was set to (I think) 12 if no value was specified to match the radius set by the OS. Add `yabai -m config window_border_radius 0` to your .yabairc and you should be good.

**Comment by mnkhprre** [comment]
> It looks like when adding the window_border_radius config option the default value was set to (I think) 12 if no value was specified to match the radius set by the OS. Add `yabai -m config window_border_radius 0` to your .yabairc and you should be good.

thx for that it fix the problem a little bit.

**Comment by timhradil** [comment]
Do you have SIP disabled and scripting addition loaded? This could be the OS curving the edges. The edges are perfectly square on my windows when window_border_radius set to 0.
