### ISSUE TITLE
syntax error in sudoers file

### ISSUE THREAD

**Issue by azinsharaf** [koekeishiya/yabai#1529]
I get a syntax error at the end of the line of scripting addition when editing the `sudoers.d/yabai`file. Can't figure out why. Any advice?

![image](https://user-images.githubusercontent.com/10101468/202523612-ed591bcd-9ade-4d7f-95bb-1e94838fad75.png)

**Comment by Keep-Simple** [comment]
maybe trailing whitespace

**Comment by azinsharaf** [comment]
that is what i thought but there is no white-spacing at the end. Weird.

**Comment by ChristianBingman** [comment]
There should be a newline after it.

**Comment by azinsharaf** [comment]
@ChristianBingman thanks for your response. There is no new line. I tried both Vim and NeoVIm for editing but same issue. How did you fix it?
This is the file. ( I added txt extension to be able to upload it into github.)
[yabai.txt](https://github.com/koekeishiya/yabai/files/10085872/yabai.txt)

**Comment by azinsharaf** [comment]
yaay! I was able to fix it. I deleted the `sudoers.d` folder and `yabai` file. Then I created the folder (`mkdir`) and yabai file (`sudo visudo`) with Vim **in MacOS default terminal app** and it worked. I was using alacritty so not sure what caused the issue.
