### ISSUE TITLE
Avoid thread-unsafe spin-locks when running code on the main thread

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#153]
### Bug report

Currently, yabai executes code on the main thread by running `dispatch_after`.

Here's one of many times this is used in the code.

https://github.com/koekeishiya/yabai/blob/54a1050f96ad3eec03091217ed862aa9a03c8e88/src/osax/payload.m#L593-L599

Some notes on this approach.
 
1. `volatile` does not guarantee atomic access. A proper way to do this would be to use `atomic_flag` from C11 in the spin-lock or a condition variable to avoid the spin-lock completely. 
2. There's a function called `dispatch_async`, which does the same as `dispatch_after` called with `dispatch_time(DISPATCH_TIME_NOW, 0)`.
3. There's a function called `dispatch_sync`, which runs code immediately on the main thread, and then returns control afterwards, thus avoiding the issue from 1\. completely.

It is better to leave the return of control to Grand Central Dispatch instead of doing it manually by spin-locking. This also avoids having to deal with issue 1\. in the code sample above.

There is likely more code in yabai relying on the false assumption that `volatile` means thread-safe. This should be looked at in-depth. See also [Why the "volatile" type class should not be used](https://www.kernel.org/doc/html/latest/process/volatile-considered-harmful.html) from kernel.org and [this proposal for deprecating some uses of volatile in C++20](http://wg21.link/P1152R3).

If you want help with it I can send a PR converting all these throughout the code base.

**Comment by koekeishiya** [comment]
> There's a function called dispatch_sync, which runs code immediately on the main thread, and then returns control afterwards, thus avoiding the issue from 1. completely.

Didn't know this. Should probably switch to this for clarity.

> volatile does not guarantee atomic access. A proper way to do this would be to use atomic_flag from C11 in the spin-lock or a condition variable to avoid the spin-lock completely.

I'm aware of that. The purpose here is not thread-safety, however because the value is only written to from one place, and is also read from only one place, volatile is sufficient because it forces the compiler to ensure that the value is always read from memory and not from the cache. Because of this there is no reason to use atomics here. I do use atomics where I deem it necessary, see `src/event_loop.c` for instance.

**Comment by dominiklohmann** [comment]
> The purpose here is not thread-safety, however because the value is only written to from one place, and is also read from only one place, volatile is sufficient because it forces the compiler to ensure that the value is always read from memory and not from the cache.

This is a tough problem to solve and while I'm not 100% certain, I'm pretty sure it's undefined behaviour as the CPU may reorder instructions with no memory barrier present.

`volatile` only guarantees that the read/write actually happens, but it does not prevent reordering.

Anyways... this should be solved by using `dispatch_sync` instead.

**Comment by koekeishiya** [comment]
> I'm pretty sure it's undefined behaviour as the CPU may reorder instructions with no memory barrier present.

That is actually true in this scenario as there are no dependencies between these two statements and it is not guaranteed that the value is written at the point where I wanted it to.

I agree that the way to fix this is to simply use `dispatch_sync` here instead.

**Comment by koekeishiya** [comment]
Fixed on master.
