### ISSUE TITLE
FAQ: What does the dock scripting addition do exactly? 

### ISSUE THREAD

**Issue by anuragrao04** [koekeishiya/yabai#1531]
I've searched the internet and I could not find clear documentation on what the scripting addition does. Can you please in a few words on what it does and how it works exactly

**Comment by buraksirma** [comment]
According to this thread https://github.com/koekeishiya/yabai/issues/13#issuecomment-497950485 it says. 

> The functionality that uses the scripting addition, and thus require SIP to be (partially) disabled are as follows:
> 
> - focus/create/destroy space without animation
> - move existing space left, right, or to another display
> - remove window shadows
> - enable window transparency
> - control window layers (make windows appear topmost or on the desktop)
> - sticky windows (make windows appear on all spaces on the display that contains the window)
> - toggle picture-in-picture for any given window

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
