### ISSUE TITLE
FAQ: Do we really need to disable Filesystem Protection SIP to enable scripting addition?

### ISSUE THREAD

**Issue by XOR-op** [koekeishiya/yabai#1536]
The code of creating folder when installing sa is [here](https://github.com/koekeishiya/yabai/blob/master/src/sa.m#L79). Even though previous code (dates back to 2021) would need write access to `/System/`, latest code only write to `/Library/`, which does not need Filesystem Protection SIP enabled. I also search for the entire codebase for possible reason for this SIP but failed. It looks like yabai performs redundant check before installing sa. So can we remove this restriction?

**Comment by XOR-op** [comment]
> IIUC it's not so much about _installing_ the SA but loading it which requires injecting code into the Dock.app – this is the part that wouldn't work with SIP enabled. You can find the details [here](https://github.com/koekeishiya/yabai/issues/798#issuecomment-767084471). But I'm sure @koekeishiya can confirm or correct me

In my understanding, the SIP required for injection is only Debugging rather than Filesystem Protection. And I found this issue too. @koekeishiya answered the problem at Jan 26, 2021, when the code still required write-access to protected `/System`, so Filesystem Protection SIP was needed. However the related code changed and no longer requires such access. This is why I'm interested in this question and I doubt if only Debugging SIP is needed.

**Comment by XOR-op** [comment]
> Did anything transpire from this @XOR-op ?

I need SIP for my current work so I don't have the chance to test it now. But I really hope to get answer from @koekeishiya who should have more understanding than me. Also I'll be glad if someone seeing this issue would give it a try. Maybe when I am available I can test it myself.

**Comment by TheNoim** [comment]
Maybe a bit off-topic, but did anyone ever send feedback to apple via the Feedback app and just ask for better APIs to interact with spaces? Or maybe even write an E-Mail? This may be a bit naive, but it would not be the first time apple would actually do something to improve the situation. And it is not like, yabai is a small project with 5 or so users.

**Comment by tmjoen** [comment]
I emailed Craig Federighi a couple years ago asking for a toggle to turn off the animation between spaces. He answered almost instantly, asking for my use case and more information. I explained that I switch spaces a lot and get kinda nauseous of all the rolling animations back and forth. He was interested and sympathetic which got my hopes up, but nothing seemed to transpire of it, unfortunately. Maybe a more API-focused request would land better with him?

**Comment by TheNoim** [comment]
> I emailed Craig Federighi a couple years ago asking for a toggle to turn off the animation between spaces. He answered almost instantly, asking for my use case and more information. I explained that I switch spaces a lot and get kinda nauseous of all the rolling animations back and forth. He was interested and sympathetic which got my hopes up, but nothing seemed to transpire of it, unfortunately. Maybe a more API-focused request would land better with him?

I will try this too when I find some time. Maybe if more people would do this, we could actually achieve something :)

**Comment by Jarvvski** [comment]
So is this no longer needed then?

**Comment by openclosure** [comment]
I would also be curious about this. This restriction is the primary reason I don't use yabai.

**Comment by gshpychka** [comment]
> I don't understand why this issue is even open. The code is pretty clear,
> 
> 
> 
> ```
> 
>     if (!scripting_addition_is_sip_friendly()) {
> 
>         warn("yabai: System Integrity Protection: Filesystem Protections and Debugging Restrictions must be disabled!\n");
> 
>         notify("scripting-addition", "System Integrity Protection: Filesystem Protections and Debugging Restrictions must be disabled!");
> 
>         result = 1;
> 
>         goto out;
> 
>     }
> 
> 
> 
>     if (scripting_addition_check() != 0) {
> 
>         result = scripting_addition_install();
> 
>         goto out;
> 
>     }
> 
> ```
> 
> 
> 
> So SIP is clearly preventing the installing of the scripting addition that aren't "friendly", what's friendly?
> 
> 
> 
> ```
> 
> static bool scripting_addition_is_sip_friendly(void)
> 
> {
> 
>     uint32_t config = 0;
> 
>     csr_get_active_config(&config);
> 
> 
> 
>     if (!(config & CSR_ALLOW_UNRESTRICTED_FS)) {
> 
>         return false;
> 
>     }
> 
> 
> 
>     if (!(config & CSR_ALLOW_TASK_FOR_PID)) {
> 
>         return false;
> 
>     }
> 
> 
> 
>     return true;
> 
> }
> 
> ```
> 
> 
> 
> Which is just checking the return from `extern int csr_get_active_config(uint32_t *config);` against
> 
> 
> 
> ```
> 
> #define CSR_ALLOW_UNRESTRICTED_FS 0x02
> 
> #define CSR_ALLOW_TASK_FOR_PID    0x04
> 
> ```
> 
> 
> 
> A quick google search shows some of the other possible options
> 
> 
> 
> https://opensource.apple.com/source/xnu/xnu-7195.81.3/bsd/sys/csr.h.auto.html
> 
> 
> 
> So basically if CSR (the SIP configuration) allows for those two things above the system is "friendly". Otherwise the sa can't be injected.
> 
> 
> 
> I don't think this will work with SIP enabled, even if you disable the check. I do however think you may be able to fiddle wiith nvram to disable _just_ the two checks above keeping the other enabled. I'm not sure if this will mean the system will advertise itself as "protected" but it may. ;P 
> 
> 
> 
> ```
> 
> /* Flags set by `csrutil disable`. */
> 
> #define CSR_DISABLE_FLAGS (CSR_ALLOW_UNTRUSTED_KEXTS | \
> 
> 	                   CSR_ALLOW_UNRESTRICTED_FS | \
> 
> 	                   CSR_ALLOW_TASK_FOR_PID | \
> 
> 	                   CSR_ALLOW_KERNEL_DEBUGGER | \
> 
> 	                   CSR_ALLOW_APPLE_INTERNAL | \
> 
> 	                   CSR_ALLOW_UNRESTRICTED_DTRACE | \
> 
> 	                   CSR_ALLOW_UNRESTRICTED_NVRAM)
> 
> ```
> 
> 
> 
> `csr disable` disables more checks then we need disabled. but anyone who thinks you can run this with SIP enabled fully, simply comment out the test and try it.. Worst case, you just restart.

This just means that currently a decision is being made at runtime (by yabai) that you cannot execute some code paths if these two restrictions are not lifted.

The question was whether the code you reference has to be there.

**Comment by koekeishiya** [comment]
Yes, filesystem protections must be disabled when injecting code into Apple processes. It does more than simply restrict `/System`; go research if you are interested in details.
