### ISSUE TITLE
Yabai auto-trees(tiles?) when I move a window to a new desktop

### ISSUE THREAD

**Issue by IanQS** [koekeishiya/yabai#1547]
E.g

```
Desktop 1: firefox(fullscreen), Spotify (background)
Desktop 2: Chrome(fullscreen), Mail
```

then I move an app from Desktop 1 to Desktop 2 and now Desktop 2 goes from

Chrome(fullscreen), Mail in background to 

```
-------
Chrome | Mail
-----------------
Spotify
------
```

is there a way to just "put" Spotify in the background instead of retiling everything? Sorry, I tried looking up "reset" and "forget" but nothin turned up.

**Comment by koekeishiya** [comment]
Not really sure what you are asking for. When yabai detects a new window in a space, that window will become managed, and other windows will be repositioned to accomodate the new window. If you want to move a window without it affecting other windows, you need to make that window float.
