### ISSUE TITLE
focus issue

### ISSUE THREAD

**Issue by azinsharaf** [koekeishiya/yabai#1551]
using `yabai -m window --focus west` (all four directions) doesn't focus correctly. It will change the border's color but doesn't focus. I still need to click on the window by mouse to focus it. Any advice for troubleshooting?

(see the color of min, max & close buttons which is gray. Not focused)
![Screenshot 2022-12-04 at 4 00 02 PM](https://user-images.githubusercontent.com/10101468/205524219-17b2325f-a024-422c-a779-e9e9113fc1dc.png)

**Comment by luciorq** [comment]
Can you provide more information on your setup?
Like MacOS version, yabai version, SIP status.

And can you also test if that happens with: 

```shell
yabai -m config mouse_follows_focus on
```

**Comment by azinsharaf** [comment]
MacOS: `Ventura 13.0.1`
Hardware: `Apple M1 Max`
Yabai version `v5.0.1`
SIP status: 
`❯ csrutil status`
`System Integrity Protection status: disabled.`

`mouse_follows_focus` was `off`. I changed it to `on` and restarted the services but still has the same issue. It changes the border color and move the mouse pointer but the window still not on focus and i have to click with mouse.

**Comment by azinsharaf** [comment]
this is the result of `yabai --verbose` in case it helps:
```
EVENT_HANDLER_DAEMON_MESSAGE: window --focus east
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: Brave Browser (5842)
EVENT_HANDLER_MOUSE_DOWN: 0 0.00, 0.00
EVENT_HANDLER_APPLICATION_DEACTIVATED: Alacritty
EVENT_HANDLER_APPLICATION_ACTIVATED: Brave Browser
EVENT_HANDLER_SLS_WINDOW_IS_VISIBLE: Brave Browser 251
EVENT_HANDLER_SLS_WINDOW_ORDER_CHANGED: Brave Browser 251
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (11482) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_APPLICATION_TERMINATED: osascript (11482) (not observed)
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (11487) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_APPLICATION_TERMINATED: osascript (11487) (not observed)
EVENT_HANDLER_MOUSE_DOWN: 251 1854.04, 839.15
EVENT_HANDLER_MOUSE_UP: 1854.04, 839.15
EVENT_HANDLER_DAEMON_MESSAGE: window --focus west
```

**Comment by jorgebef** [comment]
I am facing the same issue.
If I can be of any help, please let me know whatever I can provide to ease the troubleshooting.

**Comment by azinsharaf** [comment]
@jorgebef This issue is a show stopper for me. Can't use it without the mouse. I might reinstall it from scratch again and see what happens.

**Comment by azinsharaf** [comment]
the issue is till there even after a fresh reinstall. :/

**Comment by azinsharaf** [comment]
hi @koekeishiya, Do you have any recommendation to fix this issue? Thanks.

**Comment by koekeishiya** [comment]
No idea really. Sounds like some issue with accessibility access; I've never had any issue with focusing windows.

**Comment by azinsharaf** [comment]
thanks for checking, The issue exists on `5.0.2` as well. Closing the case since you cannot reproduce.

**Comment by azinsharaf** [comment]
i noticed if I open two windows of the same application (for instance both in Safari or both in Brave) then focus works fine. But not for different apps.

**Comment by jorgebef** [comment]
I unfortunately encounter the same issue with Alacritty windows, however, not with my web browser for example, which seems strange and might actually point towards some underlying focus which is activated on clicking inside the actual application that is open?

I would like to investigate further, however, this is not something I use too much personally.

Do you have SIP disabled or do you use yabai with SIP enabled? This might actually affect it.

**Comment by koekeishiya** [comment]
Focusing windows does not really on having SIP disabled. Commands that require SIP to be disabled are documented as such. Search for "System Integrity Protection": https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc

Alternatively a list of features (not mapped to a command invocation) that requires SIP to be disabled is listed here: https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

**Comment by nrabulinski** [comment]
I can confirm that this happens on Ventura whenever there are multiple apps open in the same space. Trying to switch focus to another app will make all windows lose focus and no window can be focused after that unless mouse is used.

For example, if I have two Safari windows in the same space, I can switch focus between them and everything is fine. Same with Finder and pretty much all the apps.
The exception here is Alacritty, which starts a new instance for each terminal window so that always loses focus (just to be completely clear what I mean here - "new instance per terminal window" means that if I have 4 Alacritty windows open, I have 4 separate Alacritty icons in my dock, just like in the screenshot below).
If I have Safari and Finder in a single space, I also cannot switch focus between them.

@koekeishiya Is there anything else that could help you identify the issue and possibly reproduce it? I'm running yabai 5.0.2 on latest Ventura on an M1 Pro MacBook 14 inch.
My `yabairc`:
```sh
yabai -m config bottom_padding 10
yabai -m config layout bsp
yabai -m config left_padding 10
yabai -m config mouse_modifier cmd
yabai -m config right_padding 10
yabai -m config top_padding 10
yabai -m config window_animation_duration 0.050000
yabai -m config window_gap 10
yabai -m rule --add app="^Alacritty$" border=on
```

![Multiple Alacritty instances](https://user-images.githubusercontent.com/24574288/209406847-32766d22-2e4f-47cb-941c-f3d57a3639a8.png)

**Comment by azinsharaf** [comment]
@nrabulinski  thanks for checking this. It is not just Alacritty, right? All the apps has this issue on my system.

**Comment by nrabulinski** [comment]
> @nrabulinski thanks for checking this. It is not just Alacritty, right? All the apps has this issue on my system.

Yes, it's any time you try to switch focus to another app instance be it from Safari to Finder, from Finder to System Preferences or from Terminal to Mail. The only time when changing the focus works as intended is when you switch between two windows of the same app. For example from one Safari window to another or from one Finder window to another etc.

**Comment by nrabulinski** [comment]
I figured out what's causing this issue: setting `mouse_modifier` to `cmd`

Having that value set to `fn` or `ctrl` makes focusing behave as expected. I will try to debug this issue further.

**Comment by azinsharaf** [comment]
@nrabulinski  wow! you literally saved my life! lol Thanks.

**Comment by jorgebef** [comment]
> I figured out what's causing this issue: setting `mouse_modifier` to `cmd`
> 
> Having that value set to `fn` or `ctrl` makes focusing behave as expected. I will try to debug this issue further.

I can confirm that this is indeed what is causing the issue for me too, good work!!
