### ISSUE TITLE
Disable border blur for single app

### ISSUE THREAD

**Issue by xbladesub** [koekeishiya/yabai#1555]
Is it possible to disable 'window_border_blur' for a specific app? I got strange bug with Finder and Telegram apps. Entire window is blurred some reason and I guess it's because of border blur. Is there any way to disable it for a specific app? 
Yabai version - yabai-v5.0.1 (I use dev build as release doesn't support Ventura so far)

<img width="1494" alt="Screenshot 2022-12-08 at 1 42 25 AM" src="https://user-images.githubusercontent.com/45129790/206254185-c264b676-028b-430f-bb44-031cb6dbaceb.png">

**Comment by azinsharaf** [comment]
i get this blurry window rarely. Rebooting the machine fixed it for me. (i am not using `window_border_blur` in `yabairc` file.)

**Comment by azinsharaf** [comment]
#1471
