### ISSUE TITLE
zoom parent/fullscreen with focus follows mouse sometimes zooms the window behind others

### ISSUE THREAD

**Issue by YellowKirby** [koekeishiya/yabai#156]
Occassionally if I switch window focus with the mouse and then zoom-fullscreen (or zoom-parent) a window, that window gets zoomed behind other windows. This does not seem to be an issue when changing focus with the keyboard + `yabai -m window --focus` command.

![zoom-fullscreen-focus-follows-mouse](https://user-images.githubusercontent.com/1654019/61889271-ff7bd880-aeb9-11e9-8faf-15d34aa70ad0.gif)

In this gif, starting with the terminal in the lower right, I use the keyboard to focus Firefox and then focus back on the bottom terminal. zoom-fullscreen on the terminal works as expected. However, after unzooming, if I do the same thing with the mouse (focus Firefox; focus back to terminal; zoom-fullscreen), the terminal then zooms behind the Firefox window. Clicking on the zoomed window will raise it to the top.

It doesn't seem to be related to any specific window or app (I've had this happen with kitty, Firefox, Slack, Finder, Chrome, etc). It also doesn't happen to all windows all the time, and I haven't quite figured out what combination of windows or focus is needed to trigger the problem 🤷‍ But usually if I have a handful of windows open on a space and I try this series of focus another + focus back + zoom then at least one of those windows will end up on top of the zoomed one.

<details>
<summary>Here's the result of <code>yabai -m query --windows --space</code> when in bad state</summary>
<pre>
[{
	"id":13316,
	"pid":72835,
	"app":"Firefox Nightly",
	"title":"Commands · koekeishiya/yabai Wiki",
	"frame":{
		"x":1061.0000,
		"y":675.0000,
		"w":854.0000,
		"h":520.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":3,
	"visible":1,
	"focused":0,
	"split":"horizontal",
	"floating":0,
	"sticky":0,
	"border":1,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":13303,
	"pid":72709,
	"app":"kitty",
	"title":"yabai -m query --windows --space | pbcopy [~]",
	"frame":{
		"x":5.0000,
		"y":27.0000,
		"w":1910.0000,
		"h":1168.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":3,
	"visible":1,
	"focused":1,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"border":1,
	"zoom-parent":1,
	"zoom-fullscreen":1,
	"native-fullscreen":0
},{
	"id":13307,
	"pid":72709,
	"app":"kitty",
	"title":" [~]",
	"frame":{
		"x":1061.0000,
		"y":27.0000,
		"w":854.0000,
		"h":638.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":3,
	"visible":1,
	"focused":0,
	"split":"horizontal",
	"floating":0,
	"sticky":0,
	"border":1,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}]
</pre>
</details>

<details>
<summary>Relavant <code>.yabairc</code></summary>
<pre>
# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_shadow                float
yabai -m config window_border                on
yabai -m config window_topmost               on
yabai -m config window_border_width          5
yabai -m config active_window_border_color   0xff9b85bb
yabai -m config normal_window_border_color   0x00505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.55
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                resize
yabai -m config mouse_action2                move
</pre>
</details>

**Comment by dominiklohmann** [comment]
You're using `autofocus`, which focuses windows, but does not raise them to appear over other windows. Use `autoraise` instead if you want focus follows mouse to also raise windows.

**Comment by YellowKirby** [comment]
Ah, yep using `autoraise` does seem to fix it, thanks @dominiklohmann. Although I'm a bit surprised that zooming a window doesn't also raise it.

**Comment by dominiklohmann** [comment]
Just use this from your keybinding in skhd:

```sh
yabai -m window --focus $(yabai -m query --windows --window | jq '.id') \
    && yabai -m window --toggle zoom-fullscreen
```

Explanation: When issuing a focus command, the target window also gets raised. There is no "focused" selector, but you can get the id of the focused window and use that as a selector to focus the already focused window, which has the side effect of raising it.

**Comment by YellowKirby** [comment]
Cool, that's really clever. Thank you!
