### ISSUE TITLE
Swipe display windows 

### ISSUE THREAD

**Issue by marcelarie** [koekeishiya/yabai#1560]
Hi! I used `leftwm` for a while and I really liked the option of swapping the displays content from one to the other. And I did not find this functionality in `yabai`. 

I created this script, that for sure could be improved a lot, that does that exactly:

```bash
#!/usr/bin/env bash

# THIS SCRIPT ONLY WORKS WITH TWO SCREENS

displays_json=$(yabai -m query --displays)

display_01_id=$(echo $displays_json | jq '.[0].id')
display_02_id=$(echo $displays_json | jq '.[1].id')

spaces=$(yabai -m query --spaces | jq -c 'map( select( ."is-visible" == true ) )')
space_01=$(echo $spaces | jq -c 'map( select( ."display" == 1 ) )[0]')
space_02=$(echo $spaces | jq -c 'map( select( ."display" == 2 ) )[0]')
space_01_id=$(echo $space_01 | jq '.index')
space_02_id=$(echo $space_02 | jq '.index')

windows_space_01=$(echo $space_01 | jq -c '.windows')
windows_space_02=$(echo $space_02 | jq -c '.windows')
windows_space_01=$(jq -r '.[]' <<< "$windows_space_01")
windows_space_02=$(jq -r '.[]' <<< "$windows_space_02")

# Iterater over all windows in space 1 and move them to space 2
while read -r window; do
  echo "Moving window $window to space $space_02_id"
  echo $space_01_id
  yabai -m window "$window" --space "$space_02_id"
done <<< "$windows_space_01"

# Iterater over all windows in space 2 and move them to space 1
while read -r window; do
  echo "Moving window $window to space $space_01_id"
  yabai -m window $window --space $space_01_id
done <<< "$windows_space_02"

yabai -m display --focus $display_01_id
```

The script is really slow. Do you know any alternative to this? I would love that functionality into `yabai`. In a way, this is more of a feature request than an issue 😆

**Comment by TheMathGuyd** [comment]
I thought for a while, and I remembered that when you change which display is your "Main Display" in System Settings/Preferences, the windows follow with the swap. I think the most efficient option is a command for doing this, which can be provided by other tools and still mapped with skhd for a seamless experience. I have not tried this option myself, but it seems a project called DisplayPlacer is capable of this https://github.com/jakehilborn/displayplacer/issues/19

**Comment by marcelarie** [comment]
Thanks for the information, I will take a look.

In any way I think this could be a nice feature for `yabai` users, tiling window managers should give as much freedom to the user on how to handle each screen, space, or window.

**Comment by kronolynx** [comment]
Similar to the first script but a bit simpler
```
#!/bin/bash

DISPLAY_1=($(yabai -m query --spaces --display 1 | jq -r '.[] | select(."is-visible" == true) | .windows | @sh'))
DISPLAY_2=($(yabai -m query --spaces --display 2 | jq -r '.[] | select(."is-visible" == true) | .windows | @sh'))

for i in "${DISPLAY_1[@]}"
do
   yabai -m window "$i" --display 2
done

for i in "${DISPLAY_2[@]}"
do
   yabai -m window "$i" --display 1
done
```
