### ISSUE TITLE
focusing window under cursor

### ISSUE THREAD

**Issue by azinsharaf** [koekeishiya/yabai#1565]
Hi, Can anyone confirm that "focusing window under cursor" command work?
```
# focus window under cursor
cmd - m : yabai -m window --focus mouse
```
It doesn't do anything for me. I was hoping to use it as a temporary solution to fix #1551.

**Comment by koekeishiya** [comment]
Works just fine for me (as do all other focus commands reported in #1551):

![cursor](https://user-images.githubusercontent.com/6175959/208093780-57cb2118-59d9-4cc0-86cb-bf3c35df0e2a.gif)
