### ISSUE TITLE
question: what is this grey horizontal line

### ISSUE THREAD

**Issue by azinsharaf** [koekeishiya/yabai#1568]
When `yabai` service is running i have a grey horizontal line below menu bar. What is it? I would disappear after stopping `yabai` service. 

![image](https://user-images.githubusercontent.com/10101468/208338435-991a1783-10f5-4a79-ae7f-d05039f4f124.png)

**Comment by koekeishiya** [comment]
Sounds like https://github.com/koekeishiya/yabai/issues/74
