### ISSUE TITLE
3+ column/row bsp layout

### ISSUE THREAD

**Issue by net** [koekeishiya/yabai#157]
Is it possible to create a 3+ column or row layout like shown in this chunkwm gif?

![6863954c-2db4-11e7-8332-221cecb52ce5](https://user-images.githubusercontent.com/6983821/61901917-e5102200-aeee-11e9-9a2d-8a4d4fe808f9.gif)

I vaguely remember being able to rotate a subtree back in kwm, but that doesn't seem possible anymore.

I've been able to create stacked rows by changing split_ratio, but it hasn't been very reliable.

**Comment by dominiklohmann** [comment]
Here's what you need.

```sh
# toggle split between vertical and horizontal
yabai -m window --toggle split

# balance all windows 
yabai -m space --balance

# config: always keep windows balance
yabai -m config auto_balance on
```

You can also convert all splits to vertical splits by creating a signal: on the signal `event=window_created` execute the below file (gotta be an external file so you can grab the arguments).

From the signal you could filter also filter for a specific display or space index. There's many ways to improve on this.

```sh
#! /usr/bin/env sh

# make this file executable using:
#     chmod +x /path/to/this/script
# create a signal using: 
#     yabai -m signal --add event=window_created action="/path/to/this/script"

# get the window id of the newly created window
wid="${2}"

# if the split is horizontal, toggle it to vertical
yabai -m query --windows --window "${wid}" | jq -re '.split == "horizontal"' \
    && yabai -m window "${wid}" --toggle split
```

**Comment by net** [comment]
@dominiklohmann thank you!

**Comment by dominiklohmann** [comment]
Here's an even simpler version. Just save this in a file and execute it somewhere from your yabairc. 

Using insert directions for this has the additional advantage of avoiding the flicker effect of toggling the split whenever a new window is created.

```sh
#! /usr/bin/env zsh

if [ "${#}" -eq 0 ]; then
	# enable auto balance
	yabai -m config auto_balance on

	# register events
	for event in window_focused application_activated; do
		yabai -m signal --add label="${0}_${event}" event="${event}" \
			action="${0}"
	done

	# when loading the script, convert all existing splits to horizontal
	yabai -m query --windows \
		| jq -r '.[] | select(.split == "horizontal").id' \
		| xargs -I{} yabai -m window {} --toggle split

	exit
fi

space_index="$(yabai -m query --spaces --space | jq '.index')"
window_placement="$(yabai -m config --space "${space_index}" window_placement)"

if [ "${window_placement}" = "first_child" ]; then
	yabai -m window --insert west
else
	yabai -m window --insert east
fi
```

**Comment by pencilcheck** [comment]
Not perfect, nor 3+ column row bsp layout but this solves my issue that I can't bring the focused window to the bigger portal of the bsp tree

Create this script and put it somewhere and follow the instructions
`
#! /usr/bin/env zsh

# put this line in your .skhdrc
# shift + alt - q : /path/to/script
# remember to make it executable
# chmod a+x /path/to/script

# Force bsp layout reset
ctrl + alt - d : yabai -m space --layout float
ctrl + alt - a : yabai -m space --layout bsp

# swap currently focused to the last window (the biggest one)
yabai -m window --swap last
`

**Comment by koekeishiya** [comment]
Any reason why `yabai -m window --swap largest` does not work for that purpose?

**Comment by rheaSPK** [comment]
Hi, I was also wondering if a three column layout was possible, and the suggestions didn't really help me. The following approach might be very buggy and certainly not elegant, but it rearranges the windows to a 3 column layout, which is fine for me. Maybe it helps.
`alt - t : yabai -m space --layout bsp;\
    yabai -m space --mirror y-axis;\
    yabai -m window --focus largest;\
    yabai -m window --insert west;\
    yabai -m window --focus next;\
    yabai -m window --warp largest;\
    yabai -m window --focus next;\
    yabai -m window --resize left:-200:0; \
    yabai -m window --resize right:500:0; \
    yabai -m window --focus next; \
    yabai -m window --swap prev;
`

**Comment by owenarden** [comment]
> Here's an even simpler version. Just save this in a file and execute it somewhere from your yabairc.
> 
> Using insert directions for this has the additional advantage of avoiding the flicker effect of toggling the split whenever a new window is created.
> 
> ```shell
> #! /usr/bin/env zsh
> 
> if [ "${#}" -eq 0 ]; then
> 	# enable auto balance
> 	yabai -m config auto_balance on
> 
> 	# register events
> 	for event in window_focused application_activated; do
> 		yabai -m signal --add label="${0}_${event}" event="${event}" \
> 			action="${0}"
> 	done
> 
> 	# when loading the script, convert all existing splits to horizontal
> 	yabai -m query --windows \
> 		| jq -r '.[] | select(.split == "horizontal").id' \
> 		| xargs -I{} yabai -m window {} --toggle split
> 
> 	exit
> fi
> 
> yabai -m window --insert "$(jq -nr \
> 	--arg window_placement "$(yabai -m config window_placement)" \
> 	--argjson display "$(yabai -m query --displays --display)" \
> 	'[["west", "east"], ["north", "south"]][if $display | .frame | .w >= .h then 0 else 1 end][if $window_placement == "first_child" then 0 else 1 end]')"
> ```
> 
> Edit: @net I updated the above script to work with vertical monitors as well (using rows over cols automatically) and simplified it a bit.

This approach had been working well for me, but the 6.0 release breaks it since application_activated was removed.  I tried just naively replacing application_activated with application_front_switched, but it didn't seem to work.  I haven't done much investigation yet, but wondered if anyone has a fix already, or an idea of what the right thing to do would be.

**Comment by kelvinst** [comment]
I have one function that is working:

```shell
# Force a determined split type for the current window
force_split_type() {
    split_type=$(yabai -m query --windows --window | jq -r '."split-type"')

    if [ "$split_type" != "$1" ]; then
      yabai -m window --toggle split
    fi
}

# Build 3 column layout for current space
three_column_layout() {
  # Disable focus-follows-mouse for the duration of this function
  yabai -m config focus_follows_mouse off

  # Reset the layout, we need to start from a clean state
  yabai -m config --space $(current_space) layout bsp

  windows_count=$(yabai -m query --windows --space | jq -r 'map(select(."is-visible")) | length')
  window_id=$(yabai -m query --windows --window | jq -r '.id')

  # If there are less than 3 windows, just put the main window on the last position
  # which is the right in my case. And then we can stop
  if [ "$windows_count" -lt 3 ]; then
    yabai -m window --swap last
    return
  fi

  # Move all windows to the right column except for 3 (2 from the left + 
  # 1 that's already there)
  i=$windows_count
  while [ "$i" -gt 3 ]; do
    # Always skip the first window, it's going to become the main one
    yabai -m window --focus next

    # Send it to the end (right column)
    yabai -m window --warp last

    # Guarantee all windows in the right are split horizontally
    force_split_type horizontal

    # Go back to the first (main) window
    yabai -m window --focus first
    i=$((i - 1))
  done

  # Now this is the magic part, down here we should already have 2 windows in the left +
  # all the others in the right column. So we just ensure the 2 windows in the left are split
  # vertically...
  force_split_type vertical

  # and then we put the first window (main) in the middle column
  yabai -m window --swap next

  # Then we calculate how many windows we need to move from the right column to the
  # left one. Which would always be half of them (discarding the 2 that are not in that column)
  windows_to_move_left=0
  if [ "$windows_count" -gt 3 ]; then
    windows_to_move_left=$(((windows_count - 2) / 2))
  fi

  # We move them all to the left the same way we move them to 
  # the right to get the 3 columns in the first place...
  while [ "$windows_to_move_left" -gt 0 ]; do
    yabai -m window --focus last
    yabai -m window --warp first

    # We guarantee they are split horizontally
    force_split_type horizontal

    windows_to_move_left=$((windows_to_move_left - 1))
  done

  # And finally we balance everything and focus back the main window
  yabai -m space --balance
  yabai -m window --focus "${window_id}"

  # And after all that, we can turn focus-follows-mouse back on
  yabai -m config focus_follows_mouse autofocus
}
```

It does a lot of move around while it's running, but I can get it to consistently set a 3 column layout with a main one (full-height) in the middle and all the other windows evenly distributed on both sides.

PS.: You might need to change some things depending on how your instance is configured
