### ISSUE TITLE
GitHub sponsors

### ISSUE THREAD

**Issue by ramnes** [koekeishiya/yabai#1570]
Hey Åsmund, thanks for the very nice WM. :)

I've been thinking about sponsoring you for a while now, but I'm procrastinating because I need to create an account on Patreon and I do have quite the "platform-fatigue" (I hate having accounts on so many websites).

I know it would take me 30 seconds to setup and that it's literally nothing compared to the huge amount of work you've put into Yabai, but my point is that if my brain works like that, there might be a whole bunch of people in the same situation.

In that perspective, would you consider enabling sponsorships on GitHub as well?

**Comment by koekeishiya** [comment]
I've not been particularly active in terms of development lately (and I don't think this is going to change soon), so encouraging people to sponsor would not feel right to me. I don't plan on enabling other forms of sponsorships in the near future, sorry.

**Comment by ramnes** [comment]
As a former sponsored maintainer (of Qtile, a X11 + Wayland tiling WM, eh) that stopped taking sponsorships, I can completely understand. I'd still be happy to send you some coins though, even if only for the maintenance that you still seem to be doing. :)

**Comment by wdanilo** [comment]
> 

Oh no, does it mean that yabai is not actively developed? There is a lot of issues now (which is normal when the project starts maturing), but if the main author/contributor is no longer involved, it would probably die sooner than later. And TBH I would never want to see it happen, as this thing is amazing.

**Comment by azinsharaf** [comment]
@wdanilo  i agree, this is an awesome application which i use everyday. I would be still sponsoring it since i am using it heavily. The current version works fine for me at this time.

**Comment by koekeishiya** [comment]
It's not like I plan to abandon the project or anything, but it is just one of many hobbies that I spend time on, and when that time is no longer enjoyable for whatever reason, I switch to other things. I just happen to be in a spot where I don't enjoy debugging issues and programming, in my spare time for now.

**Comment by azinsharaf** [comment]
i was able to assist you and have it as one of my hobbies if I knew C!

**Comment by wdanilo** [comment]
@koekeishiya totally understandable! Do you think that if there would be enough of GitHub sponsors for this project you'd be able to spend a little bit of your non-free time on it on daily/weekly basis?

**Comment by koekeishiya** [comment]
I guess it would probably incentivize me to spend a bit more of my free time on it, but only to a certain extent. My own quality of life will always come first, so if I just don't feel like it, nothing will happen. 

I know this is probably not the answer people want, but it it's just how I do things. If my main motivation for workking on these tools was to earn additional money they wouldn't be OSS in the first place.

At this point I have been working on these projects within this domain since 2014, and it is just not that interesting to me anymore, from a technical pov.

**Comment by ramnes** [comment]
Happy to see that you finally opened GitHub sponsors!
