### ISSUE TITLE
Bug: normal_window_opacity, active_window_opacity, and window_shadow not working

### ISSUE THREAD

**Issue by manc1n1** [koekeishiya/yabai#1571]
After upgrading to `yabai-v5.0.2` these features have not been working.

Yabai version: `yabai-v5.0.2`
macOS version: `Monterey 12.6.1`
SIP: `Disabled`

**Comment by 0xWaleed** [comment]
It works for me fine :/

**Comment by manc1n1** [comment]
> It works for me fine :/

What yabai version/ macOS are you on?

**Comment by manc1n1** [comment]
Completely restarted installation process and is now working normally again.
