### ISSUE TITLE
App as overlay

### ISSUE THREAD

**Issue by 0xWaleed** [koekeishiya/yabai#1572]
Is there anyway that I can make a window sticky + layer=above with semi transparent as overlay.
what I mean exactly in current yabai version, there is no way to make a window or app ignored when I focus on the space.

For instance when I make the app floating then I re-enter the space, it focuses on the floating window which requires me to use mouse or CMD+Tab. This sometimes annoying when I want to have sticky note on top of everything and want to move between displays/spaces; it focus on sticky note rather than the tiled app.

**Comment by koekeishiya** [comment]
The focus is handled by macOS and yabai cannot intercept that.
