### ISSUE TITLE
Yabai not tiling windows after reboot (Ventura)

### ISSUE THREAD

**Issue by 0xCUB3** [koekeishiya/yabai#1574]
Basically the windows all open wherever they want now...

I tried restarting yabai and it doesn't throw any errors

**Comment by ripple0328** [comment]
the same issue, checked the system integrated protection keep disabled

**Comment by zxcvbn97** [comment]
Same issue. Yabai has been working inconsistently.

**Comment by CathyMacars** [comment]
Same thing.

**Comment by HeikkiLu** [comment]
Make sure you don't have "Displays have seperate Spaces" disabled in Desktop & Dock. I had accidentally disabled it and yabai stopped working as a result.

**Comment by brorbw** [comment]
Have you followed the steps in the installation guide to load the scripting addition when the system boots?
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
