### ISSUE TITLE
Focus jumps to notifications

### ISSUE THREAD

**Issue by quulah** [koekeishiya/yabai#1579]
Each time I receive a Slack message, the focus switches to the notification. This is slightly irritating when in the middle of writing something.

This might be quite simple and there might be something wrong with my config, but I do believe that it hasn't always done this so I'm a bit confused.

I've tried with various mixes of `mouse_follows_focus` and `focus_follows_mouse`, but haven't reached a working solution. Additionally, I've tried to get rid of everything funky from my config to no avail.

* yabai-v5.0.2
* macOS Monterey v12.6

**Comment by koekeishiya** [comment]
yabai does not do anything to window focus unless you move the mouse over a window with focus follows mouse enabled, or you run a `yabai -m window --focus` command using a hotkey.

**Comment by quulah** [comment]
Okay, good to know! I'll have to continue my investigations then. :)

It does have something to do with yabai, as I've tried previously running without and the same thing didn't happen. So, if you don't mind I'll keep this issue open for a while and perhaps it'll be of use to someone if I find the culprit.

It might well be some old config I have somewhere doing something, as I have been a yabai (and the previous incarnations) user for some time.

**Comment by quulah** [comment]
Went through all relevant config for yabai, skhd, and Slack. Got rid of some old cruft at the same time. Issue still persists.

I wonder if this is somehow related to the autoraise and Dock not hiding issues: #1552 & #1474 

I realized that I'm actually seeing these both so the notification thing isn't my only focus related problem.

**Comment by azinsharaf** [comment]
Does Slack has a Notification style setting like MSTeams? 

https://support.content.office.net/en-us/media/fde835c0-fdd3-42a7-a33d-299748343e25.png

Have you tried to add it as `manage=off`?

`yabai -m rule --add app="^Microsoft Teams$" title="^Microsoft Teams Notification$" manage=off`

**Comment by quulah** [comment]
@azinsharaf Thanks! I don't think it works the same way as Teams, as I can't even `yabai -m query` the notification window. There's now setting to control the style either.

Which also makes me think that it is using just the macOS default notification system. That just makes me even more confused on why the focus keeps shifting there.

I did however find the Teams notifications there, haunting each space regardless of whether the application itself is on a particular space. So your rule is probably helpful. :)

**Comment by azinsharaf** [comment]
@quulah have this issue ever resolved?

**Comment by quulah** [comment]
Sadly no, I got bored of fighting with it and disabled the notifications
instead for the moment.

Since then I did however upgrade to Ventura, so I could check if the issue
still persists.

**Comment by koekeishiya** [comment]
Unable to reproduce using `osascript -e 'display notification "test notification!"'` on latest version.
