### ISSUE TITLE
Return an error for queries with invalid, named selectors

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#158]
### Bug report

When querying with an invalid, named selector, yabai acts as if no selector was given at all and returns the focused window/space/display. When given a number instead of a string, yabai returns an error instead.

```sh
# returns an error

❯ yabai -m query --windows --window 0
could not locate the selected window.
❯ echo $?
1

# returns the focused window

❯ yabai -m query --window --window asdf
{ ... }
❯ echo $?
0
```

The behaviour should be consistent so that scripts can test whether a valid selector was provided.

```sh
# check if a valid display selector was provided by the user
if ! yabai -m query --displays --display "${1}" > /dev/null 2>&1; then
        >&2 echo "could not locate the selected display."
        exit 1
fi

**Comment by koekeishiya** [comment]
Fixed on master.
