### ISSUE TITLE
Can yabai work together with Moom?

### ISSUE THREAD

**Issue by yanshay** [koekeishiya/yabai#1581]
Hi,
When I manually resize windows, yabai automatically adjusts other windows around it and/or resize back the window when I make it an "illegal" size/location.
When I use Moom however for resizing windows yabai doesn't behave the same, and only when I later manually change a bit the window size it adjusts other windows.

Is it possible to get Moom and Yabai work together so when Moom resize/place a window Yabai will take that as a recommendation and adjust other windows accordingly to the best possible layout conforming to yabai logic?

**Comment by koekeishiya** [comment]
Unlikely. It is as far as I know not possible to distinguish between movement and resizements done by external software, the software itself, or through user interactions/cursor etc.
