### ISSUE TITLE
Space commands not working

### ISSUE THREAD

**Issue by snax08** [koekeishiya/yabai#1582]
The space function is not working with;

`--create`
`--destroy`
`--focus`

They are working correctly with;

`--balance`
`--rotate`

The following is the snippits from my skhdrc are not working;

`## create desktop, move window and follow focus - uses jq for parsing json (brew install jq)`
`#shift + ctrl - n : yabai -m space --create && \`
`#                   index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \`
`#                   yabai -m window --space "${index}" && \`
`#                   yabai -m space --focus "${index}"`

`## Create space on the active display`
`#alt + ctrl - p : yabai -m space --create`

`## Delete focused space and focus first space on display`
`#alt - p : yabai -m space --destroy`

`## cycle space`
`##     \`
`#alt - 0x2A : yabai -m space --focus recent`
`##     [`
`#alt - 0x21 : yabai -m space --focus prev`
`##     ]`
`#alt - 0x1E : yabai -m space --focus next`

Running any of the following commands;

`yabai -m space --create`
`yabai -m space --destroy`
`yabai -m space --focus recent`
`yabai -m space --focus prev`
`yabai -m space --focus next`

returns this;

`cannot create/destroy/focus space due to an error with the scripting-addition.`

I am running version 5.0.2 installed via the command;

`brew install koekeishiya/formulae/yabai --HEAD`

I'm certain I installed the cirtificate correctly as the instructions didn't seem confusing or have any weird messages.

Please correct me if I'm using any terminology incorrectly, as I'm basicly all self taught through tutorials, documentation, and trial and error.

**Comment by indigomarxist** [comment]
Same issue here. Focusing simply won't work.

**Comment by penglei** [comment]
Same problem exists for my m1pro.

macOS 12.6 (21G115)
Darwin 21.6.0

**Comment by sofomryu** [comment]
This error also happened me. I disabled SIP, set self-signed certificate, installed yabai HEAD via brew, configure scripting edition with updated hash. but still space command doesn't work

**Comment by sofomryu** [comment]
> This error also happened me. I disabled SIP, set self-signed certificate, installed yabai HEAD via brew, configure scripting edition with updated hash. but still space command doesn't work

This has been solved. There was just a little mistype for my case..
