### ISSUE TITLE
doesn't tile window when open from a python virtual environment

### ISSUE THREAD

**Issue by pfassina** [koekeishiya/yabai#1584]
I have inconsistent tiling behavior when opening applications from my terminal.
I'm opening neovide from terminal by typing the following command `neovide . `

When I type this command from any directory, it will properly open and tile the Neovide application.
However, when I do the same from within a python virtual environment, it will not manage the window properly.

I've tried adding `yabai -m rule --add app="^neovide$" manage=on` to my yabairc file, but it didn't make any difference.

I'm running yabai on a Mac OS Ventura 13.0.1

**Comment by koekeishiya** [comment]
If the latest yabai version does not see the window, there is not much more that can be done.
