### ISSUE TITLE
Tiling functionality not working - Ventura 13.1

### ISSUE THREAD

**Issue by maxjowett** [koekeishiya/yabai#1585]
Yabai seems to be running, I can still modify spaces, however tiling has stopped working. I'm not seeing any errors in the logs or anything useful to debug. Is this a known issue?

**Comment by iSolate77** [comment]
I had a similar issue. I think tiling has an issue being enabled by default, so what I did is add a shortcut to activate tiling with the command `yabai -m space --layout bsp`

**Comment by maxjowett** [comment]
@iSolate77 Thank you, this does activate tiling, still a bit frustrating to have to manually do this each time I create a new space.

**Comment by thatszer** [comment]
Thx @iSolate77, 终于成功运行了。

**Comment by koekeishiya** [comment]
This is intentional. You are supposed to do whatever setup required in the config file.
