### ISSUE TITLE
README Requirements and Caveats deprecated under Ventura 13.0+

### ISSUE THREAD

**Issue by cmaxreilly** [koekeishiya/yabai#1586]
The Mission Control preferences pane in System Preferences no longer exists in Ventura. The setting "Automatically rearrange Spaces based on most recent use" is now located in the menu "Desktop and Dock" in System Preferences.

**Comment by sam-silva** [comment]
thanks for the help, I couldn't find that setting until I read this

the automatic sorting in the spaces was driving me crazy.

**Comment by cmaxreilly** [comment]
Don't mention it! Glad I could help!
