### ISSUE TITLE
Window borders cause severe, system-wide lag

### ISSUE THREAD

**Issue by gerryhernandez** [koekeishiya/yabai#1591]
Ever since v5, I've been experiencing really bad lag, stuttering, choppiness, etc. I've tried various combinations of software and config; the only way I can reproduce this is to specifically enable Yabai's borders.

Yabai config:
```
yabai -m config layout float

yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xFFA000FF
yabai -m config normal_window_border_color 0x0000FF00
```

Version:
```
❯ yabai -v
yabai-v5.0.2
```

This is on a freshly reformatted, fresh macOS installed, 2019 MacBook Pro 16:
```
OS: macOS 13.1 22C65 x86_64
Host: MacBookPro16,1
Kernel: 22.2.0
CPU: Intel i9-9980HK (16) @ 2.40GHz
GPU: Intel UHD Graphics 630, AMD Radeon Pro 5500M
Memory: 19967MiB / 65536MiB
```

The lag is most noticeable when switching to and from desktops that contain windows. This happens with all applications, not just electron apps. There is no noticeable lag when switching between two empty spaces.

Another way to observe severe lag is to scroll within Alacritty. Scrolling in Less or any TUI like Vim will reproduce this.

The one thing I didn't try is using the scripting addition, but that's just because I can't actually get it to work for some reason. No errors, but it just doesn't seem to do anything.

Yabai v4 was perfect, but is not compatible with macOS 13. But I figured it'd be worth noting that it worked on the same hardware.

Please let me know if there is any additional info I can fetch that would help. Thanks!

**Comment by kevinmonisit** [comment]
I wonder if window_blur is on for you? When I turned window_blur off, the lag went away on my 4k monitor. Try doing that. I'm not sure if window blur is on or off on default

`yabai -m config window_border_blur off`

**Comment by mrtns** [comment]
Same issue for me. Turning `window_border` off seems to have fixed it:
```
yabai -m config window_border                off
```

**Comment by gerryhernandez** [comment]
The `yabai -m config window_border_blur off` setting seems to have fixed it. Thank you!
