### ISSUE TITLE
two instances of one setting for different displays? 

### ISSUE THREAD

**Issue by ricerabbi** [koekeishiya/yabai#1592]
Hi, 

I have my MacBook connected to 1440p monitor. The `top_padding` setting I use to leave space for my status bar works on my MacBook, but doesn't create enough necessary space for my 1440p monitor.

Instead of making the `top_padding` universally larger and wasting screen real estate on my laptop,

Is there a way to have a `top_padding` setting specifically for one display and another `top_padding` setting (of a different value) for another display? 

I'm new to GitHub so I apologize if this post has newbie mistakes. 

Thanks!

**Comment by Bellavene** [comment]
Use [BetterDisplay](https://github.com/waydabber/BetterDisplay) to create an HDPI mode that is close to your macbook screen?

**Comment by brorbw** [comment]
You could make a script that is triggered when the screen changes. https://talk.automators.fm/t/run-script-when-connecting-disconnecting-external-monitor/13878

Then query `yabai -m query --displays` if whatever condition you want is met set the new `top_height` and then maybe call `launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"` to restart yabai quickly.
