### ISSUE TITLE
Improve 'full screen' behavior

### ISSUE THREAD

**Issue by finberg** [koekeishiya/yabai#1598]
Hi! is it possible to make all windows full-screen in case one window goes full-screen? 
For instance, I open 3 applications on the same screen and then press option+f (full screen) for App1. I would like App2 and App3 to become full-screen as well. And if press option+f again for one of them then all others will exit from the full screen as well. Is it possible? I saw such behavior on Manjaro Linux + i3.
Thanks!

**Comment by koekeishiya** [comment]
You can write a script that queries the open windows, and run the command `yabai -m window --toggle native-fullscreen` for any window that matches your criteria.

**Comment by brorbw** [comment]
It's a little bit quick and dirty but put this in a script and call this script from `skhd` for the keys you want to use for this behaviour
```sh
ACTIVE_DISPLAY_ID=$(/usr/local/bin/yabai -m query --spaces | /usr/local/bin/jq '.[] | select(."has-focus" == true).display')
for WINDOW_ID in $(yabai -m query --windows | /usr/local/bin/jq ".[] | select(.display == $ACTIVE_DISPLAY_ID).id")
do
    yabai -m window --focus $WINDOW_ID
    yabai -m window --toggle zoom-fullscreen
done
```

**Comment by finberg** [comment]
Thank you for the script, it works fine! I only added a condition to toggle focus of windows only for the current workspace.
I have a question: is it possible to toggle fullscreen without focusing? Because it looks not so good

**Comment by brorbw** [comment]
Currently there is not an option to toggle fullscreen for windows that are not in focus AFAICT. Should be a pretty easy patch to apply to the command if you want it.

**Comment by finberg** [comment]
It will be cool! What I need to do?

**Comment by brorbw** [comment]
Look at the `message.c:2090` file make toggle take an optional argument and pass that window as acting window.

**Comment by koekeishiya** [comment]
There is no need to edit the source; you can just do `yabai -m window north --toggle zoom-fullscreen` or `yabai -m window north --toggle native-fullscreen`. Replace `north` with whatever *window selector* you wanted.

**Comment by brorbw** [comment]
Neat. Didn’t know

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/skhd/issues/273#issuecomment-1574851997
