### ISSUE TITLE
question: how to use Reduced Security?

### ISSUE THREAD

**Issue by azinsharaf** [koekeishiya/yabai#1600]
I use an application that needs Security Policy to Full Security or Reduced Security. When I change it to reduced security it enables SIP. Is there any way I can use Reduced Security and keep SIP disabled (even partially)?

<img width="263" alt="image" src="https://user-images.githubusercontent.com/10101468/212747704-7d86ce33-d36e-4e97-99b2-f4ff697fee66.png">

MacOS: Ventura 13.1

**Comment by Vixeliz** [comment]
Somebody else can correct me but reduced security im pretty sure is only if you use older versions of macos. Reduced security isn't available when sip is disabled. Sip disabled is considered permissive security.

**Comment by bin101** [comment]
disabling single SIP features implies permissive security as I understand the apple docs:
https://support.apple.com/guide/security/startup-disk-security-policy-control-sec7d92dc49f/web

**Comment by azinsharaf** [comment]
Closing this since i don't have time to troubleshoot it. I just removed that app. :/

**Comment by weeebdev** [comment]
I think it still needs to be resolved. @koekeishiya would you mind to look?
