### ISSUE TITLE
MS Teams meeting window switches the space

### ISSUE THREAD

**Issue by azinsharaf** [koekeishiya/yabai#1601]
a new issue is happening on MS Teams. Wondering if anyone else experiencing the same issue.
when I join a meeting (or on a call) on MS Teams and meeting window is not minimized then switching to any space jumps back to the Teams' space. 
I've already managed (`manage=off`)the Teams notification window.
If i minimize the meeting window then it won't happen. It is so annoying.

**Comment by Finkregh** [comment]
@azinsharaf you you share your config (part)?

**Comment by azinsharaf** [comment]
i am not using mac a lot these days so have removed yabai. 
that issue with Teams is for 9 months ago and yabai has had multiple releases since that time so it could have been fixed.

**Comment by rxbn** [comment]
I have the same issuer as you described with Teams... drives me crazy :/
