### ISSUE TITLE
Flickering on stack space when animations are enabled

### ISSUE THREAD

**Issue by buraksirma** [koekeishiya/yabai#1602]
Hey, I've a `stack` space and I'm running multiple instances of IntelliJ in that space but whenever I click anywhere on the app. App looses, gets focus back and it flickers. It's only happening when animations are enabled.

https://github.com/buraksirma/dotfiles/blob/main/yabairc

**Comment by maxmwang** [comment]
I am noticing this behavior as well. Heavily slows Discord and Slack for me with noticeable flickering. 

https://github.com/maxmwang/dotfiles/blob/main/.yabairc

**Comment by iskeld** [comment]
@buraksirma @maxmwang I'm having this issue too, but now at least I have a solution which is setting `window_animation_duration` to 0.0 - thank you both!

**Comment by koekeishiya** [comment]
Same as #1493
