### ISSUE TITLE
Chrome and firefox are not properly managed by yabai

### ISSUE THREAD

**Issue by oof2win2** [koekeishiya/yabai#1603]
Hi. Running MacOS Monterey (12.6) and yabai v5.0.2. The issue that I have is that Firefox and Chrome do not appear to be managed by yabai. I have attempted to debug it for a while now, but to no avail. I have tried adding these two lines to my yabairc:
```
yabai -m signal --add event=window_created app="^Firefox$" action="echo 'firefox'"
yabai -m signal --add event=window_created app="^Safari$" action="echo 'safari'"
```
The lines work, and I get a line logged both when I open a new Firefox or Safari window. Safari however is managed, whilst Firefox is not.
When I run `yabai -m query --windows | jq 'map(select(.app == "Firefox"))'`, I get this output. I believe that it is correct for a window that *should* be managed by yabai. Is there anything that I could do about this?
```
  {
    "id": 9205,
    "pid": 2581,
    "app": "Firefox",
    "title": "yabai chrome firefox sticky default - Hledat Googlem",
    "frame": {
      "x": 0,
      "y": 25,
      "w": 1440,
      "h": 875
    },
    "role": "AXWindow",
    "subrole": "AXStandardWindow",
    "display": 1,
    "space": 3,
    "level": 0,
    "opacity": 0.9,
    "split-type": "none",
    "split-child": "none",
    "stack-index": 0,
    "can-move": true,
    "can-resize": true,
    "has-focus": false,
    "has-shadow": false,
    "has-border": true,
    "has-parent-zoom": false,
    "has-fullscreen-zoom": false,
    "is-native-fullscreen": false,
    "is-visible": false,
    "is-minimized": false,
    "is-hidden": false,
    "is-floating": false,
    "is-sticky": false,
    "is-topmost": false,
    "is-grabbed": false
  }
```

**Comment by oof2win2** [comment]
Forgot to state that this occurs for Firefox, Firefox Beta (the app itself is called just "Firefox"), however not for Firefox Nightly. As Nightly has a different name, is there any configuration file which overrides mine and makes firefox not managed/floated?

**Comment by siematypie** [comment]
I have the same issue, Chrome and Slack windows are not managed at all :(

**Comment by oof2win2** [comment]
I reached out to Apple Support, will post updates if I get any.

**Comment by oof2win2** [comment]
I got it fixed by setting Chrome to a certain screen on my monitor, as I had it assigned to "All Desktops" previously for some reason.
