### ISSUE TITLE
Black screen when switching spaces after removing second monitor and opening laptop after sleep

### ISSUE THREAD

**Issue by IonelLupu** [koekeishiya/yabai#1608]
I got this issue where the screen is black when I switch spaces. I can see the desktop folders and the top bar, but everything else is black:

![image](https://user-images.githubusercontent.com/4083652/215153629-9ae8fada-74bb-4820-8835-a2076e1db46e.png)

The only way to see something is to show the windows using three fingers on the trackpad:
![image](https://user-images.githubusercontent.com/4083652/215153815-64e728d2-0d4c-4660-b1ed-3cb429680a2d.png)

One other way is to use Alt+Tab (I have the AltTab app installed).

I use yabai just to disable the space switching animation. I just run `sudo yabai --load-sa`.

If I kill the Dock `killall Dock`, everything comes to normal. Ofc, I now have the animation when I switch between Spaces. But if I try to run `sudo yabai --load-sa`, the black screen issue shows up again.

I didn't have this issue before removing my second monitor. Probably the best solution to this is to just restart the laptop.

What might be the issue

**Comment by koekeishiya** [comment]
Not sure what the issue could be; this has never happened to me. I assume a reboot of the machine fixes it so will close this.
There isnt't really much I can do to try and understand what is going on here until it happens to me personally.

**Comment by IonelLupu** [comment]
@koekeishiya  I think you are right. Might not be from yabai. Rebooting didn't help so I guess I am left with resetting to factory settings. Updating the OS didn't help either.

Do you know if resetting to factory settings will also enable "System Integrity Protection" back? I know this setting is somewhat "behind the scenes" and resetting might not change it back. My issue might be from that

**Comment by koekeishiya** [comment]
Resetting to factory should reset SIP yes. I am fairly certain that simply doing a NVRAM reset will also reset SIP settings.
