### ISSUE TITLE
payload could not resolve addreses in Dock.app!

### ISSUE THREAD

**Issue by iiskakov** [koekeishiya/yabai#161]
Hi, I have an issue here, wasn't able to find any specific solutions in the internet :(

`Yabai: payload could not resolve addreses in Dock.app!`

SIP is disabled

**Comment by dominiklohmann** [comment]
You need to reinstall the scripting addition, as yours is likely outdated.

```sh
# For very outdated versions of yabai or the scripting addition,
# try running these steps manually. Uninstall the scripting addition,
# then install the new version, then kill the Dock to reload it.
sudo yabai --uninstall-sa
sudo yabai --install-sa
pkill -x Dock
```

Then for further updates, the scripting addition will notify you if a newer version is available. Once you're running the newer version, this is enough to update:

```sh
# reinstall the scripting addition and reload it (may restart Dock.app)
sudo yabai --install-sa
```

**Comment by koekeishiya** [comment]
You are likely running on a version of macOS that is not supported. See the requirements section in the wiki.
