### ISSUE TITLE
Yabai error in brew services?

### ISSUE THREAD

**Issue by joshuacrotts** [koekeishiya/yabai#1610]
After typing `brew services list` following an installation and doing the script additions, I get the following error:

`yabai error  256 root ~/Library/LaunchAgents/homebrew.mxcl.yabai.plist`.

If I try to uninstall then reinstall yabai and start the service, I get the following error:

```
Warning: Taking root:admin ownership of some yabai paths:
  /opt/homebrew/Cellar/yabai/5.0.2/bin
  /opt/homebrew/Cellar/yabai/5.0.2/bin/yabai
  /opt/homebrew/opt/yabai
  /opt/homebrew/opt/yabai/bin
  /opt/homebrew/var/homebrew/linked/yabai
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
Warning: yabai must be run as non-root to start at user login!
/Library/LaunchDaemons/homebrew.mxcl.yabai.plist: service already bootstrapped
Bootstrap failed: 37: Operation already in progress
Error: Failure while executing; `/bin/launchctl bootstrap system /Library/LaunchDaemons/homebrew.mxcl.yabai.plist` exited with 37.
```

Not really sure what's going on.

**Comment by azinsharaf** [comment]
Did you uninstall it according to the instruction? There is an specific steps for uninstalling it.

**Comment by joshuacrotts** [comment]
> Did you uninstall it according to the instruction? There is an specific steps for uninstalling it. 

Admittedly, I did not. I'll follow those instructions and try to reinstall. Hopefully, that'll fix it.

Though, I encountered this problem after first installing it, so I'm not sure what to do if I see it from the start.

**Comment by fcarvalhopacheco** [comment]
Not sure if this is the correct thing to do but launchctl remove homebrew.mxcl.yabai fixed similar issue

**Comment by weeebdev** [comment]
Any updates?

**Comment by weeebdev** [comment]
Yep, I just followed the instructions from https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD) and it works fine since then

**Comment by joshuacrotts** [comment]
I uninstalled yabai, then reinstalled by following the instructions. Still received the same error.

**Comment by daibertdiego** [comment]
Same issue here. 
Error: Permission denied @ rb_sysopen - /Users/xxx/Library/LaunchAgents/homebrew.mxcl.yabai.plist

Using the normal installation and the HEAD installation.

**Comment by BitInByte** [comment]
Hello, I'm having a similar error. Either using release version or dev (HEAD) version it says that missing plist and doesn't allow me to start the service. Also, I get an Accessibility Access popup and either doing deny or open system settings will no remove this popup and will stay there forever.

I've tried fresh installation of the app and multiple stuff and none of them with success :(

**Comment by koekeishiya** [comment]
Homebrew services integration was removed in the latest release (v5.0.4). Follow the updated instructions in the wiki.

**Comment by BitInByte** [comment]
Hey, yeah, it's up and running now again, thanks :D

**Comment by Pingu1337** [comment]
> Homebrew services integration was removed in the latest release (v5.0.4). Follow the updated instructions in the wiki.

Thank you, this solved it for me to.

[the updated wiki](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#updating-to-the-latest-release)
