### ISSUE TITLE
question: how to make all the windows transparent?

### ISSUE THREAD

**Issue by azinsharaf** [koekeishiya/yabai#1612]
`Yabai` supports transparency for the active/inactive window. Is there any way to have the transparency for all the windows regardless of their selection status?

**Comment by 24unix** [comment]
Just set them both to the same level.

**Comment by azinsharaf** [comment]
I use one window per space. Each application (window) goes to one space.

**Comment by 24unix** [comment]
Fullscreen? Then there is no transparency.

**Comment by azinsharaf** [comment]
Oh i got what you mean. I set both active and nonactive windows to 0.8. 
Thanks!!!

**Comment by azinsharaf** [comment]
@24unix and is it possible to exclude some applications?

**Comment by 24unix** [comment]
Yes. Like so:

```
yabai -m rule --add app="Parallels Desktop" opacity=1.0
```
