### ISSUE TITLE
Bug: Yabai conflicting with MacOS on zoom? [video]

### ISSUE THREAD

**Issue by lapinvert** [koekeishiya/yabai#1614]
In Mac OS, we can double click on a window's title bar to maximize a it's size, provided `System Preferences` -> `Dock & Menu Bar` -> `Double-click a window's title bar to zoom` is checked. Pretty much similar to what `zoom-fullscreen` does, but I prefer being able to double click for this feature.

However, when using Yabai it sometimes won't work as intended. Some window will work when other won't. I can't predict when it will happen but it's pretty frequent.

Here is a video where I double click on title bar on multiple windows to show the weird behavior / bug.

https://user-images.githubusercontent.com/3294841/216088070-42f55c55-d13e-417a-8811-5dc474e600f2.mp4

Any ideas of what is wrong and how to solve it?

**Comment by brorbw** [comment]
You could use the built in full screen for yabai. `yabai -m window --toggle zoom-fullscreen`. This does exactly what you describe, just without the mouse. If you use the standard configuration for `skhd` it should be `alt - f`.

**Comment by koekeishiya** [comment]
This isn't really something that can be integrated nicely. On master yaba will force the window back to its designated region/frame/area #2117
