### ISSUE TITLE
Child windows sometimes show up under the parent windows

### ISSUE THREAD

**Issue by theTechGoose** [koekeishiya/yabai#1617]
In some programs, I will click a button and it will open a color palette or a dropdown menu and the menu seems to not open. Upon closer inspection, it seems that the window pops up below the parent window. 

Is this an issue with the configuration? This is not fixed even when you stop running yabai. The problem with this is that it makes yabai unusable with certain programs.

There is an interesting quirk here, it only happens with some child windows, with some child windows it behaves exactly as expected.

**Comment by gilitos92** [comment]
This happens to me too, but only when a window has `--layer above`, a very reproducible scenario is opening the Messages app and trying to add a GIF by clicking on the GIF Search button. Is there a way to set all children windows to `--layer above` too?

**Comment by frigaut** [comment]
yes, I experience this too, but I don't think it has to do with the config. For me, in a new yabai session, things will behave normally (e.g. calendar popups or popup menu when searching in mail.app are above). Then, after an arbitrary long time and perhaps triggered by I don't know what, this will start happening. I've checked a couple of times that login out and back in fixes the issue, but don't have a systematic behaviour to report to help debugging.

**Comment by koekeishiya** [comment]
Fixed in v6.0.0, #1887
