### ISSUE TITLE
Ignore popover windows

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#162]
### Feature request

Popover windows should generally be ignored by yabai. 

The role for popover windows is `AXPopover`, and their subrole may be unset. 

There's really no reason to show them in queries, and they should not trigger rules or signals. They shouldn't have borders either.

This is becoming more relevant with 10.15, as iPad apps ported with Catalyst tend to use popover windows a lot.

**Comment by kiryph** [comment]
Does this refer to open/save dialog windows as well?

**Comment by koekeishiya** [comment]
Implemented on master, but no idea how to test this.

**Comment by dominiklohmann** [comment]
It works. Confirmed with Reminders.app on Catalina dev beta 4.
