### ISSUE TITLE
illegal date format 

### ISSUE THREAD

**Issue by mnkhprre** [koekeishiya/yabai#1621]
i am using Ventura 13.2
and my yabai version is 4.0.4

i couldn't find a solution for it.
<img width="471" alt="Ekran Resmi 2023-02-10 19 11 08" src="https://user-images.githubusercontent.com/54448793/218142587-431c275c-3d85-4bf6-a089-bec6cb9626f1.png">

**Comment by koekeishiya** [comment]
This is not related to yabai; it is something else in your brew installation.
