### ISSUE TITLE
Disable window border when on fullscreen

### ISSUE THREAD

**Issue by aymane-eljerari** [koekeishiya/yabai#1623]
```
yabai -m window --toggle zoom-fullscreen
```
Toggles a window to fullscreen, but how can I disable the window border on any full-screened window? I'm assuming I have to use a signal, but I do not know how to set it up. Thanks

**Comment by koekeishiya** [comment]
If you in general always have window borders enabled; you can just do `yabai -m window --toggle zoom-fullscreen --toggle border
