### ISSUE TITLE
Maintain fix number of spaces with external monitors (`display_added` triggers only once?)

### ISSUE THREAD

**Issue by dakeryas** [koekeishiya/yabai#1631]
Hello,

I am trying to maintain a constant number of spaces regardless of how many monitors I have such that my finger muscle memory, e.g. Firefox is always on space 3, reliable works. Therefore, after creating 5 initial spaces, my yabairc contains the following signal actions.

```
 # Create a couple of workspaces up to $YABAI_MAX_SPACES
 YABAI_MAX_SPACES=5
 for sp in {1..$YABAI_MAX_SPACES}; do
     yabai -m query --spaces --space $sp &> /dev/null || yabai -m space --create
 done

 # Tie applications to spaces
 yabai -m rule --add app="^iTerm2$" space=^1
 yabai -m rule --add app="^Telegram$" space=^2
 yabai -m rule --add app="^DeaDBeeF$" space=^2
 yabai -m rule --add app="^FireFox$" space=^3
 yabai -m rule --add app="^Safari$" space=^3
 yabai -m rule --add app="^Mattermost$" space=^5

 # Enforce the number of spaces regardless of the number of displays
 yabai -m signal --add event=display_added action="yabai -m space --destroy \$(yabai -m query --spaces --display 1 | jq '.[-1].index')"
 yabai -m signal --add event=display_removed action="yabai -m space --create"
```

However, if I do maintain 5 spaces via the `display_removed` action, when I plug my M1 Pro laptop back to the dock via a thunderbolt port, I get 6 spaces instead of 5. My dock is connected to two LG monitors managed by te displayLink Manager drivers, and it seems that yabai only receives the signal for one of those two, I am not sure if that is expected, and wherein the bug could lie.

EDIT: could it be that `yabai -m query --spaces --display 1 | jq '.[-1].index'` gets evaluated too early when the two monitors are connected, and the two actions try to destroy the very same space? 

I am wondering about concurrency when two displays are added like this by a doc. Is there a global locking mechanism to make sure that if some action is trying to maintain N spaces by destroying X of them, a concurrent action for another display won't come up with the same X value for the number of spaces to destroy, just because things got evaluated before the first display's action started removing spaces?

**Comment by dakeryas** [comment]
It seems I can solve my problem with an external script that checks in a loop how many spaces are still left and slowly destroy them one by one, and run that script within the action to maintain a fixed number of spaces.

```
~/.config/yabai/destroy_excess_spaces.zsh
@ -0,0 +1,24 @@
#!/usr/bin/env zsh

function get_excess_spaces(){
    local target=$1
    echo $(yabai -m query --spaces | jq "length - $target")
}

function get_last_space(){
    local display=$1
    echo $(yabai -m query --spaces --display $display | jq '.[-1].index')
}

function destroy_excess_spaces(){
    local target=$1
    local display=$2
    [ -z $display ] && display=1
    excess=$(get_excess_spaces $target)
    while (( excess > 0 )); do
        yabai -m space --destroy $(get_last_space $display)
        excess=$(get_excess_spaces $target)
    done
}

destroy_excess_spaces $@
```

and now my action becomes:
```
+yabai -m signal --add event=display_added action="~/.config/yabai/destroy_excess_spaces.zsh $YABAI_MAX_SPACES"
```

**Comment by danfbfern** [comment]
@koekeishiya @dakeryas 
Sorry for the direct ping and I know I am late to this ticket but this has been very frustrating and I wonder if there is a way to do this without having to disable SIP since I can't in my company's computer.

I believe that this Mac behaviour is caused by the "Displays have separate Spaces" feature and can't turn that off without breaking yabai, but every time I connect or disconnect a display, I have to move things around because of it and its driving me nuts.

Is there a solution of at least a mitigation to the problem without touching SIP since I'm not authorised to do so?
