### ISSUE TITLE
Can't use "yabai -m space --focus next".

### ISSUE THREAD

**Issue by Iddodo** [koekeishiya/yabai#1639]
I have updated to Ventura 13.3, and currently `yabai -m space --focus next` and `yabai -m space --focus prev` commands do not work.

Everything else seems to be in order.

I would be more than happy to share additional info (if relevant).

**Comment by gur111** [comment]
This doesn't work for me either. In fact, any commend to change focused space doesn't work.
I disabled all access to accessibility in the System Settings under Security & Privacy.
I'm running a beta release of MacOS Ventura.
Attaching a log from `yabai --verbose`
[yabai_reducted.log](https://github.com/koekeishiya/yabai/files/10793827/yabai_reducted.log)

**Comment by gur111** [comment]
Looking at: https://github.com/koekeishiya/yabai/commit/206c0d6968210f48363f206526760e5750810a61
I suspect the offsets have changed again. It seems inefficient to find the offsets again with each new release of the Dock.
I will try to find a weekend of something to created an automatic script to find the offsets that can be easily to to add support for a new version.
(I base this on not seeing any `[yabai-sa]` prefixed logs in `Console.app` so I suspect it fails to inject (although the `--load-sa` didn't return any errors).

**Comment by shinyquagsire23** [comment]
it broke for me briefly, but after installing the latest update and reinstalling yabai, it seems to have resolved itself. not sure what to make of that honestly.

**Comment by shinyquagsire23** [comment]
I checked in IDA Pro and all of the offsets and search patterns are correct for 13.2.1. If I kill the dock and reload SA, it shows in Console.app
```
default	11:21:00.480734-0800	Dock	[yabai-sa] loaded payload..
default	11:21:00.480933-0800	Dock	[yabai-sa] checking for macOS 13.2.1 compatibility!
default	11:21:00.480956-0800	Dock	[yabai-sa] (0x10484c000) dock.spaces found at address 0x40CF70 (0xfffffffefbbc0f70)
default	11:21:00.480973-0800	Dock	[yabai-sa] (0x10484c000) dppm found at address 0x40CFF0 (0xfffffffefbbc0ff0)
default	11:21:00.481028-0800	Dock	[yabai-sa] (0x10484c000) addSpace found at address 0x104A396E0 (0x1ed6e0)
default	11:21:00.481044-0800	Dock	[yabai-sa] (0x10484c000) removeSpace found at address 0x104AED30C (0x2a130c)
default	11:21:00.481066-0800	Dock	[yabai-sa] (0x10484c000) moveSpace found at address 0x104ADFC8C (0x293c8c)
default	11:21:00.481081-0800	Dock	[yabai-sa] (0x10484c000) setFrontWindow found at address 0x104894DE0 (0x48de0)
default	11:21:00.481173-0800	Dock	[yabai-sa] (0x10484c000) animation_time_addr found at address 0x104A3B2E8 (0x1ef2e8)
default	11:21:00.481213-0800	Dock	[yabai-sa] now listening..
```

Actually now that I'm looking at it though, I think my particular issue is actually an skhd issue, because I have `yabai -m space --focus next` and `yabai -m space --focus prev` bound to Option + `;` and Option + `'`. If I run the commands in a terminal they're fine, but skhd doesn't pick up on those keys any more. Maybe something with 13.2.1 clamped down on Secure Keyboard Entry? If I start skhd in kitty.app it complains about Secure Keyboard Entry being enabled, even though it is not.

**Comment by gur111** [comment]
Yeah. For my version the offsets are wrong. I'm currently attempting a fix and will update with the results

**Comment by gur111** [comment]
YAY. It's actually working.
I've testing only on my machine (like a good programmer) though.
Try reinstalling yabai but instead of using the main repo, use the one with my fix:
```
brew install gur111/formulae/yabai --HEAD
```

Warning, someone else also tried my fix and it only partially worked for him. Functionality like moving spaces between displays as well as removing spaces doesn't work.
Still, switching between spaces  adding new ones (which is imo the most important functions) do work.
The code is currently for macos 13.3 (which I think is currently still in beta)

**Comment by gldtn** [comment]
Not sure if it's entirely related..

I could not get  any "space --focus" command to work until I updated my "/private/etc/sudoers.d/yabai" config file

Seems like the sha256 hash did not match and the wiki(https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#configure-scripting-addition) says:
#   this hash must be updated manually after running brew upgrade.

So if you setup "Configure scripting addition" check your hash from
`sudo visudo -f /private/etc/sudoers.d/yabai`

With:
`echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa"`

I can now use every "space --focus" command.

Hope this helps someone with the same problem!

**Comment by jrmoulton** [comment]
> YAY. It's actually working. I've testing only on my machine (like a good programmer) though. Try reinstalling yabai but instead of using the main repo, use the one with my fix:
> 
> ```
> brew install gur111/formulae/yabai --HEAD
> ```
> 
> Warning, someone else also tried my fix and it only partially worked for him. Functionality like moving spaces between displays as well as removing spaces doesn't work. Still, switching between spaces adding new ones (which is imo the most important functions) do work. The code is currently for macos 13.3 (which I think is currently still in beta)

@gur111 I just updated to 13.3 and I tested out your fork and it didn't work for me. How did you find what to update the offsets to?

**Comment by gur111** [comment]
> > YAY. It's actually working. I've testing only on my machine (like a good programmer) though. Try reinstalling yabai but instead of using the main repo, use the one with my fix:
> > ```
> > brew install gur111/formulae/yabai --HEAD
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Warning, someone else also tried my fix and it only partially worked for him. Functionality like moving spaces between displays as well as removing spaces doesn't work. Still, switching between spaces adding new ones (which is imo the most important functions) do work. The code is currently for macos 13.3 (which I think is currently still in beta)
> 
> @gur111 I just updated to 13.3 and I tested out your fork and it didn't work for me. How did you find what to update the offsets to?


I've used radare2 on the old binary to see how the function actually looks like and then searched for the same function on the newer binary to find the function.
All and all it would have taken merely 2-3 hours if I  wasn't so rusty on reversing.
I'm still planning on creating a script to automate the flow.
If you want, you can send me your exact build number and it would help me create something more generic.
Also could you send a file of your system logs so I can see which functions were found? You can open Console.app and filter for only logs with "yabai"

**Comment by alanmicah** [comment]
> Not sure if it's entirely related..
> 
> I could not get any "space --(focus/create/destroy)" command to work until I updated my "/private/etc/sudoers.d/yabai" config file
> 
> Seems like the sha256 hash did not match and the wiki(https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#configure-scripting-addition) says:
> 
> ### "this hash must be updated manually after running brew upgrade."
> So if you setup "Configure scripting addition" check your hash from `sudo visudo -f /private/etc/sudoers.d/yabai`
> 
> With: `echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa"`
> 
> I can now use every "space" command.
> 
> Hope this helps someone with the same problem!

Thank you so much, this helped me out! I was getting _cannot focus space due to an error with the scripting-addition_ but now it works!
