### ISSUE TITLE
CleanShot X feature isn't working well when yabai is on

### ISSUE THREAD

**Issue by aviadhaham** [koekeishiya/yabai#1641]
Hello Team,

I'm a new user of yabai.

I found that my screenshot application, "CleanShot X", when using options that require "Drag to select capture area", the mouse shows in all displays (and also blinking very fast), and I can't move it to perform the needed action.
So it seems like they can't work together.
That's fine by me, but the thing is, adding it to the app disabled apps didn't help that.

Do you have another idea?

Thank you!

**Comment by Liquidmantis** [comment]
I use CleanShot X as well, and haven't had any issues.  Here is my [yabairc](https://github.com/Liquidmantis/dotfiles/blob/main/yabai/yabairc) if you want to see if its behavior is any different.

**Comment by peppy** [comment]
I had a similar issue, and this seemed to resolve it:

`yabai -m rule --add app="CleanShot X" manage=off mouse_follows_focus=off`

It may also help to make sure you're on the latest cleanshot version.

**Comment by aviadhaham** [comment]
@peppy that indeed solved it! Thank you very much!!

**Comment by lianghx-319** [comment]
> 

`yabai -m rule --add app="Xnip" manage=off mouse_follows_focus=off` also works for xnip.
