### ISSUE TITLE
Border increasing when new window is created

### ISSUE THREAD

**Issue by MegunaStellar** [koekeishiya/yabai#1646]
When I start Yabai on a space with windows on it, the window border width is correct. However, when I create a new window, the window border doubles.
When started:
![Screenshot 2023-02-24 at 7 07 57 PM](https://user-images.githubusercontent.com/71800980/221151543-22352e24-4fa2-4758-87db-577f63a2b28e.jpg)
When I created a new window ( kitty terminal )
![Screenshot 2023-02-24 at 7 08 22 PM](https://user-images.githubusercontent.com/71800980/221151643-dfe2bd7e-feff-4a77-8cdd-e93f3c68498c.jpg)

**Comment by koekeishiya** [comment]
Borders have been removed in the latest release (v6.0.0) (#1889) because of multiple issues present in both Ventura and Sonoma.
