### ISSUE TITLE
Yabai stops working from sleep

### ISSUE THREAD

**Issue by zxcvbn97** [koekeishiya/yabai#1647]
After waking up my computer from sleep, yabai stops working. 

macOS Ventura latest. 

Anyone having the same issue?

**Comment by shinyquagsire23** [comment]
macOS bug apparently, and a nasty one (but the fix is easy, lock and unlock with the touch ID button): https://github.com/koekeishiya/yabai/issues/1639#issuecomment-1440686783

**Comment by koekeishiya** [comment]
Please distinguish between skhd issues and yabai issues.
