### ISSUE TITLE
Borders off centered with floating applications

### ISSUE THREAD

**Issue by Lealchimie** [koekeishiya/yabai#1651]
Hi ! 
There is a weird behavior on borders when I do this :  
I want to launch a floating kitty window. So in my .skhdrc I have set :
`hyper - f : kitty -T Float zsh -c "some command" `
which create a kitty window whose name is Float, and in my .yabairc I have the following rule set : 
`yabai -m rule --add title="Float" manage=off grid=4:4:1:1:2:2`

Expected : pressing hyper-f gives a floating centered kitty window

Actual : pressing hyper-f gives a floating centered kitty window **with messed up borders**

![Capture d’écran 2023-03-02 à 16 50 23](https://user-images.githubusercontent.com/1372163/222482417-d85343c8-06d5-4490-9373-fd95ceca4dfa.jpg)
There is a slight delay where the window pops up where the border is actually drawn and then moves to the right place, but the border doesn't follow. If I manually toggle float + float centered then the border is drawn accurately.

This problem was always there since I use yabai (at least 4.0.4), and the workaround I had was to use limelight, which didn't had the problem and managed to track correctly the window. But I upgraded to Monterey and limelight doesn't work anymore.

It is not the only time where I see a wrongly drawn border when I have a manage=off + grid setting rule, but here it is consistent. And the same behavior is there with Alacritty terminal.

Tested and reproduced with this minimal .yabairc : 
```
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m rule --add title="Float" manage=off grid=4:4:1:1:2:2

yabai -m config active_window_border_color 0x99ff720C 
yabai -m config window_border on
``` 

I know a workaround is to use #326, but the behavior there is that window is first managed then gets floated which I would rather avoid, and the solution I had was way simpler to implement.

**Comment by koekeishiya** [comment]
Borders have been removed in the latest release (v6.0.0) (#1889) because of multiple issues present in both Ventura and Sonoma.
