### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by caffeinum** [koekeishiya/yabai#1652]
Please add onboarding! I have spent 30 minutes installing and it's not easy to find most of the information, if you're new. I have gave up and just asked ChatGPT instead.

Here are the steps you can follow to quickly start using yabai effectively:

1. Familiarize yourself with the basic concepts and terminology of yabai. yabai is a tiling window manager for macOS, which means it lets you manage your windows in a more efficient way by organizing them into tiles or "spaces." Some key terms to know include:
- Space: A virtual desktop that contains one or more windows.
- Window: A graphical user interface element that displays the contents of an application.
- Frame: A rectangular area within a space that contains a window.
2. Learn the keyboard shortcuts for yabai. yabai is controlled entirely through keyboard shortcuts, so it's important to know how to use them effectively. Some common shortcuts include:
- alt + space: Toggle the layout of the currently focused space between tiling and floating.
- alt + h/j/k/l: Change the focus to the window to the left/down/up/right of the currently focused window.
- alt + shift + h/j/k/l: Move the currently focused window to the left/down/up/right of its current position.
- alt + enter: Make the currently focused window full screen.
- alt + \: Switch to the next space.
- alt + shift + \: Move the currently focused window to the next space.

But most of these are not activated yet in a `skhdrc`.

It would be amazing to have one-page guide on how to quickly get started.

**Comment by koekeishiya** [comment]
I think the wiki is a pretty decent introduction already; I don't want to go more basic than that.
