### ISSUE TITLE
keep one window (python) afloat on top of the rest

### ISSUE THREAD

**Issue by doomdoomdoomdoom** [koekeishiya/yabai#1654]
hi guys after two days of trying different configurations i gave up and trying my luck here
i have yabai and skhd installed on macos with sip disabled
all im trying to achieve is have just one dedicated window (python) to stay afloat of top of the others without the other windows being tilted. so essentially im trying to make a macos version of https://efotinis.neocities.org/deskpins/ with yubai or am i barking at the wrong tree?

**Comment by koekeishiya** [comment]
You can disable tiling by setting the layout to float. 
You can use window rules to target specific windows and make it appear on top.
Take a look at the documentation

**Comment by colormotor** [comment]
I have a similar issue as I often run python graphical apps that require a specific window size from the command line, and have not found a general/consistent way to set this up with yabai rules yet. The behavior you mention @doomdoomdoomdoom seems to be default in i3 on linux, but I'm not sure how it is handled internally rule-wise.
