### ISSUE TITLE
Problem: "yabai -m window --focus recent" not working for me

### ISSUE THREAD

**Issue by curiousier-george** [koekeishiya/yabai#1655]
Running `yabai -m window --focus recent` returns the error

`could not locate the most recently focused window.`

and I get similar errors for `yabai -m window --focus next` and `yabai -m window --focus prev`. I am new to yabai and so may be missing something obvious, and I am also running Ventura 13.1, but `yabai -m space --focus 1`, for example, does work for me. Any help would be greatly appreciated.

**Comment by mapringg** [comment]
I have the same problem with `yabai -m window --focus next` and `yabai -m window --focus prev` on 13.2.1

**Comment by azinsharaf** [comment]
just for clarification, do you need to focus on the recent Window or Space?
```
cmd - x : yabai -m space --focus recent
cmd - z : yabai -m space --focus prev
cmd - c : yabai -m space --focus next
```

**Comment by curiousier-george** [comment]
> just for clarification, do you need to focus on the recent Window or Space?

For me, on the recent Window.

**Comment by azinsharaf** [comment]
It was for both of you. The focus on window should work but i never use it, at least in my workflow. I use mod key + h/l keys to focus on windows.

**Comment by curiousier-george** [comment]
> I use mod key + h/l keys to focus on windows.

Do those keys correspond to `yabai -m window --focus west/east` or `yabai -m window --focus prev/next`?

(`yabai -m window --focus prev/next` doesn't work for me either.)

**Comment by azinsharaf** [comment]
this is the mapping in  my `skhdrc` file. 
```
# skhdrc file
cmd - h : yabai -m window --focus west
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east

cmd - x : yabai -m space --focus recent
cmd - z : yabai -m space --focus prev
cmd - c : yabai -m space --focus next
```

**Comment by vishalnagda1** [comment]
friendly bump 🍭

**Comment by koekeishiya** [comment]
What exactly is the issue here?

First of all, `window --focus` commands are not related to `space --focus` commands. They work very differently and have different requirements. Secondly, make sure that your windows are actually managed (in a bsp-space). You cannot use these  specific window selectors to focus a floating (unmanaged) window.

All the mentioned commands work fine:

![window focus](https://github.com/koekeishiya/yabai/assets/6175959/901ac116-ac4a-45ee-a4dd-e6c518424ac5)
