### ISSUE TITLE
Bug where menus are created below the active window

### ISSUE THREAD

**Issue by eomdo** [koekeishiya/yabai#1657]
When using the Chrome browser or other apps, the window that appears when you click another element, such as a menu, usually exists in front of the previously activated window. However, sometimes with yabai, the menu becomes obscured behind the active window, making the menu unclickable.

![ezgif-3-fcf37e52c9](https://user-images.githubusercontent.com/83337136/222998723-024d26fe-37cf-4f6e-a70c-e38841ab6553.gif)

Is this a problem that only happens to me? You are using the latest version of the app.

**Comment by nicklayb** [comment]
I have the same problem, in Firefox for instance, when I want to enable notifications for a web app, the confirmation pop up opens behind the window

**Comment by eomdo** [comment]
@nicklayb 
In my case, restarting yabai did not relieve the symptoms.
```bash
$ brew services restart yabai
```
Toggling between float and unfloat via the alt-t hotkey relieved the symptoms for a while.

**Comment by azinsharaf** [comment]
i am wondering if this code can fix it.
```
# floating windows are always on top (default: off)
yabai -m config window_topmost on
```

**Comment by eomdo** [comment]
@azinsharaf 
In my settings the value of "window_topmost" was "on" and after changing the value of that setting to 'off' the problem was resolved.

I tried searching for the "window_topmost" option and found a case similar to mine in the link below.
https://github.com/koekeishiya/yabai/issues/1135

Thanks for your help.

**Comment by azinsharaf** [comment]
@eomdo  glad it worked. the Issue can be closed.
