### ISSUE TITLE
Pastille

### ISSUE THREAD

**Issue by eithannak29** [koekeishiya/yabai#1658]
Can i remove this little circle gray tablet under the "ls" cmd?
<img width="626" alt="image" src="https://user-images.githubusercontent.com/75700288/222997519-c665f29f-1ac3-43e8-a4c9-f1f2a80f1e0b.png">

<img width="220" alt="image" src="https://user-images.githubusercontent.com/75700288/222997509-a0f13c43-f867-4d31-a5e6-f1cae2b570c8.png">

**Comment by azinsharaf** [comment]
Is it there because of Yabai?

**Comment by MaliciousXatt** [comment]
I got the same issue.
Yes it is because of Yabai - it appears in iterm and terminal.
It is the border from yabai. Since when disabled it doesn't show the dot.

**Comment by MaliciousXatt** [comment]
It grabs the inactive color.

**Comment by MaliciousXatt** [comment]
Note: The dot does not appear in SSH sessions.

**Comment by jonixis** [comment]
![circle](https://user-images.githubusercontent.com/22484750/226862399-68dd9047-97ad-47de-8d4c-36c1b61a3dd9.gif)

I have a similar issue, but not necessarily in iterm or terminal. Also, when switching the room, this blurred area appears where the circle is.

**Comment by azinsharaf** [comment]
Does it happen when microphone is on? You know there a orange dot when you are in a meeting and using microphone. Wondering if that is the reason but not sure frankly.

**Comment by jonixis** [comment]
> > Does it happen when microphone is on? You know there a orange dot when you are in a meeting and using microphone. Wondering if that is the reason but not sure frankly.
> 
> No. It only appears when typing - it does not seem that it has anything to do with microphone.

Also don't think it has anything to do with the microphone for me.

**Comment by azinsharaf** [comment]
see if the stdout of `yabai -m query --windows` in terminal give you a clue.

**Comment by azinsharaf** [comment]
i see this dot when using Teams and in my case it seems it is Teams notification.

 <img width="817" alt="image" src="https://user-images.githubusercontent.com/10101468/227003831-a124b5dc-36ce-46ef-bbc9-a3b33f051fa5.png">
 
 <img width="391" alt="image" src="https://user-images.githubusercontent.com/10101468/227004183-12b94085-27aa-4fed-aaba-7a94eb8fa423.png">

**Comment by jonixis** [comment]
![image](https://user-images.githubusercontent.com/22484750/227042784-7a49ccf2-9254-4355-a389-a3fe2e4be4b9.png)

**Comment by koekeishiya** [comment]
`yabai -m rule --add app="^Microsoft Teams$" title="^Microsoft Teams Notification$" border=off

**Comment by MaliciousXatt** [comment]
my output:
λ  ~  yabai -m query --windows
[{
	"id":624,
	"pid":1243,
	"app":"iTerm2",
	"title":"xatt@Hackintosh:~",
	"frame":{
		"x":12.0000,
		"y":36.0000,
		"w":1410.0000,
		"h":1147.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"display":1,
	"space":1,
	"level":0,
	"opacity":1.0000,
	"split-type":"vertical",
	"split-child":"first_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":true,
	"has-shadow":true,
	"has-border":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-topmost":false,
	"is-grabbed":false
},{
	"id":140,
	"pid":951,
	"app":"Chromium",
	"title":"Pastille · Issue #1658 · koekeishiya/yabai - Chromium",
	"frame":{
		"x":1434.0000,
		"y":36.0000,
		"w":1410.0000,
		"h":1147.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"display":1,
	"space":1,
	"level":0,
	"opacity":1.0000,
	"split-type":"vertical",
	"split-child":"second_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":true,
	"has-border":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-topmost":false,
	"is-grabbed":false
},{
	"id":525,
	"pid":1401,
	"app":"Discord PTB",
	"title":"#main-chat | Tech-Education - Discord",
	"frame":{
		"x":2867.0000,
		"y":-202.0000,
		"w":1056.0000,
		"h":930.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"display":2,
	"space":2,
	"level":0,
	"opacity":1.0000,
	"split-type":"horizontal",
	"split-child":"first_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":true,
	"has-border":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-topmost":false,
	"is-grabbed":false
},{
	"id":535,
	"pid":1431,
	"app":"UpNote",
	"title":"UpNote",
	"frame":{
		"x":2867.0000,
		"y":739.0000,
		"w":1056.0000,
		"h":930.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"display":2,
	"space":2,
	"level":0,
	"opacity":1.0000,
	"split-type":"horizontal",
	"split-child":"second_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":true,
	"has-border":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-topmost":false,
	"is-grabbed":false
}]

**Comment by MaliciousXatt** [comment]
It seems fixed ? Is there an update? or?

**Comment by MaliciousXatt** [comment]
Nvm, it's back.

**Comment by joelleclerc** [comment]
@eithannak29 
@MaliciousXatt 

If you're using Fig with autocomplete enabled, yabai will create your configured window border around the autocomplete "window" within your terminal.

Fig's autocomplete creates an extra layer (child terminal window) that hides within your main terminal window.

Adding this to yabairc fixed it for me.

`yabai -m rule --add app="^Fig$" border=off`

There is probably a more elegant solution if you still want your border to show up when you're using the Fig GUI.

Hope that helps!
