### ISSUE TITLE
Skhd example: create and focus new space

### ISSUE THREAD

**Issue by marcelja** [koekeishiya/yabai#166]
https://github.com/koekeishiya/yabai/blob/7641afd7fdf95101de6675a8e1b9bfafdc3b4c63/examples/skhdrc#L36

Creating and focusing a space using the skhd example focuses the last space on the current display.
If the last space was a native-fullscreen window, it stays the last when creating a new space (at least for me?).
Thus, the native-fullscreen window is focused instead of the new space.

Maybe the index can be selected like this:
`index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')"`

**Comment by LudwigWS** [comment]
works well, thanks.

stick command after correct (should install tool jq before). 

```sh
# create desktop, move window and follow focus
shift + cmd - n : yabai -m space --create;\
                  id="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')";\
                  yabai -m window --space $id;\
                  yabai -m space --focus $id
```

**Comment by veetcoder** [comment]
```bash
shift + cmd - n : yabai -m space --create;\
                  id="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')";\
                  yabai -m window --space $id;\
                  yabai -m space --focus $id
```
This is new the updated way.
