### ISSUE TITLE
Yabai only works when started manually

### ISSUE THREAD

**Issue by aymtec** [koekeishiya/yabai#1661]
Hi,

I’ve tried installing yabai a few times following without success and finally got it to work by starting it manually and sourcing the config file:

`yabai -c  $XDG_HOME/yabai/yabairc`

The brew services command does not display any errors, but the app only starts working once I start the yabai command manually.

I’m on the lastest macOS ventura on an M1 Pro.

Thanks for your help

**Comment by aki-k** [comment]
@aymtec For me the main reason for using yabai was to directly interact with an inactive window. Now, even if I start yabai without a .yabairc or yabairc from Terminal, that feature doesn't work any more.

**Comment by koekeishiya** [comment]
Brew services integration has been removed in the latest release (v5.0.4). Use the new service commands to integrate with launchd.
