### ISSUE TITLE
Arc Browser Holds Focus

### ISSUE THREAD

**Issue by johnallen3d** [koekeishiya/yabai#1662]
I'm experiencing an issue with focus in a very specific scenario.

- space change on same display
- foreground app prior to space change is Arc Browser
- after space change Arc Browser retains focus

Here's some (slightly clipped) output from `yabai --verbose`.

```sh
# use skhd to focus a space with Arc at front (same display)
EVENT_HANDLER_DAEMON_MESSAGE: space --focus scratch
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: Arc (29987)
EVENT_HANDLER_APPLICATION_DEACTIVATED: kitty
EVENT_HANDLER_APPLICATION_ACTIVATED: Arc
EVENT_HANDLER_SPACE_CHANGED: 10
EVENT_HANDLER_WINDOW_FOCUSED: Arc 12058
EVENT_HANDLER_DAEMON_MESSAGE: query --windows --window
EVENT_HANDLER_DAEMON_MESSAGE: query --windows --window

# use skhd to focus a space with Kitty at front (same display)
EVENT_HANDLER_DAEMON_MESSAGE: space --focus terminal
EVENT_HANDLER_SPACE_CHANGED: 1
EVENT_HANDLER_WINDOW_FOCUSED: Arc 12057
EVENT_HANDLER_DISPLAY_CHANGED: 1 1
EVENT_HANDLER_DAEMON_MESSAGE: query --windows --window
EVENT_HANDLER_DAEMON_MESSAGE: query --windows --window
```

Basically it looks like when I navigate away from the space with Arc I'm not seeing the `DEACTIVATED`/`ACTIVATED` events. 

This occurs regardless of what the front application is on the destination space. Interestingly, when moving to a space on a different display focus changes as expected (ie. Arc lets go focus).

I've reinstalled from `HEAD` and am running Ventura.

```sh
> yabai -v
yabai-v5.0.2
> sw_vers
ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68
```

\* edit to add...

I've played around with "focus follows" and "mouse follows" setting but no combination of those settings had an impact. 

Here's by general settings:

```sh
# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_shadow off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
```

**Comment by chalop** [comment]
I followed the feedback from this [issue](https://github.com/koekeishiya/yabai/issues/1622) and its working well for now. Here's my yabai config that contains what fixed my workflow with Arc https://github.com/chalop/.dotfiles/blob/main/yabai/.config/yabai/yabairc#L18

Arc retaining focus when switching spaces is a problem with the app itself. I opened an issue with them with the following feedback and they are working on it:
```
- Firstly, I made 3 screens: 1st has Arc Browser, 2nd has a program, and 3rd has another browser.
- Starting from the 2nd screen, I switch to the 1st one -- Arc gains focus as expected.
- When I switch back to the 2nd screen, Arc retains its focus when it shouldn't be (notice the app name on the top-right corner).
    -I have to click the program from the 2nd screen in order to gain its focus.
- Finally, I jump to the 3rd screen and that browser activates. Going back to the 2nd screen it makes that program automatically focus -- this is the behavior I expected from Arc.
    -One thing to mention is that when I use Mission Control and click on the second screen it makes the program automatically focus, no matter which app I'm coming from (perhaps because, technically, is coming from "Mission Control.app", though I can't say for sure).
```

**Comment by johnallen3d** [comment]
Thanks @chalop, this is very helpful! I figured the issue was with Arc but I wasn't quite sure how to hack around it. This is _mostly_ working. I have one really strange scenario that doesn't quite work now.

- two displays
- arc open on inactive display
- switch from arc focused space on active display to non-arc
- arc on inactive display steals focus

Fairly minor annoyance. I love Arc and Yabai too much to stop using either!

**Comment by gilitos92** [comment]
To be honest, there is currently no solution for this problem. The issue lies directly with Arc, which hijacks focus even on vanilla configurations whenever you try to change spaces or switch displays. In my case, where I have a dual monitor configuration, I cannot use the `yabai -m display --focus next|prev` commands to switch between displays, as Arc prevents Yabai from triggering the `space_changed` or `display_changed` events.

**Comment by hotsno** [comment]
> The issue lies directly with Arc, which hijacks focus even on vanilla configurations whenever you try to change spaces or switch displays
For me, with yabai uninstalled, Arc lets go of focus when I switch away from its space.
