### ISSUE TITLE
Weird DOT while typing in iTerm2 - Yabai Border

### ISSUE THREAD

**Issue by MaliciousXatt** [koekeishiya/yabai#1667]
Hi,
As soon as I start typing in iterm2 I get this weird dot.
When disabling Yabai its border - it is fixed.
But then I'd not have the border. Is there any way to fix this?
If so, how? 
Thank you ,

![Screenshot 2023-03-17 at 22 25 01](https://user-images.githubusercontent.com/111096156/226056402-e4250cde-af7a-4424-80a4-f6683a345592.png)

**Comment by azinsharaf** [comment]
#1658
