### ISSUE TITLE
Rules aren't working / yabai -m rule --list outputs blank

### ISSUE THREAD

**Issue by jleseane23** [koekeishiya/yabai#1668]
Running Ventura 13.2.1 on a Retina MBP Mid 2015. The device is non-supported but I got it working with OpenCore Patcher. I think I have the SIP partially disabled. In order to do it I have to use OpenCore Patcher. The following are the SIP settings.

<img width="364" alt="Screenshot 2023-03-17 at 9 20 26 PM" src="https://user-images.githubusercontent.com/55364887/226075709-060e3df5-c0d9-498f-a236-d8a134845305.png">
 
Everything seems to work except all of my manage=off rules. Here's some of them below. 

yabai -m rule --add app="^Cryptomator$" manage=off
yabai -m rule --add app="^Infuse$" manage=off
yabai -m rule --add app="^Alfred Preferences" manage=off

When I query a list of rules using yabai -m rule --list, it only shows [], which I assume means it can't find any rules to load.

I verified the apps have the same names when I query the list of open windows.

Has anyone seen this before?

**Comment by sarcastillo** [comment]
Running Ventura 13.2.1 on a 2020 M1 MacBook Air and am facing the same issue when running yabai -m rule --list, with no rules listed and manage=off not working. I have SIP enabled and as about to disable it to see if that was the issue until I found your post here. 

I've run yabai -m query --windows to check if any of my windows are "sticky" and none are. Not sure if running the latest from HEAD will solve it but I'll probably give it a try.

**Comment by koekeishiya** [comment]
No idea, works fine for me on Ventura 13.2.1 (although OS version does not matter).

**Comment by sarcastillo** [comment]
Thanks for responding. I'm running the latest from HEAD and still have the same issue. Is there anything else I could try to get the window rules working? Or do I need SIP disabled for this feature?

**Comment by koekeishiya** [comment]
Rules don't need SIP disabled. Can you post your full config?

**Comment by sarcastillo** [comment]
This is what's in my .yabairc, below:

`yabai # default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if 
horizontal split
yabai -m config window_placement second_child

# padding set to 5px
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

# -- mouse settings --

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges 
it will split it)
yabai -m mouse_drop_action swap


# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Radio Silence$" manage=off
yabai -m rule --add app="^Parallels Desktop$" title="Control Center" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^Sublime Text$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari Technology Preview" app="^Safari Technology Preview$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off


# Music & Media
yabai -m rule --add app="^(Spotify|Music)$" space=4
yabai -m rule --add app="^YouTube$" space=4
`

**Comment by sarcastillo** [comment]
Tried reinstalling the original version of yabai (non head version) after the 13.3 update and my rules still aren't seen when checking for them on the terminal. Wonder what else I can try to get my rules seen?

**Comment by sarcastillo** [comment]
Finally got the rules working. I deleted my $HOME/.yabairc and put yabairc in the $HOME/.config/yabai/yabairc and symlinked this to the .yabairc I previously deleted in the $HOME dir.
