### ISSUE TITLE
Labels aren't cleaned up when spaces are destroyed

### ISSUE THREAD

**Issue by brookskindle** [koekeishiya/yabai#1678]
Hello 👋

I'm working on a script for myself that will create a labeled space on-demand, and then destroy it again when it's no longer in use. While experimenting, I found that I believe is a bug in yabai - the internal mapping between labels and spaces are not being updated properly when a space is destroyed.

### System details:
* OS: MacOS Monterey 12.6.1
* `yabai --version`: `yabai-v5.0.2`

### Example
Starting with a clean slate: one display, one space, no label.
```bash
$ yabai -m query --spaces | jq '.[] | {index: .index, label: .label}' -c
{"index":1,"label":""}
```

If I attempt to focus a label that doesn't exist, I get an error. This is expected
```bash
$ yabai -m space --focus testLabelFocus
value 'testLabelFocus' is not a valid option for SPACE_SEL
```

Likewise, I can give a space a label and focus it using the label without issue.
```bash
$ yabai -m space --create
$ yabai -m space 2 --label testLabelFocus
$ yabai -m query --spaces | jq '.[] | {index: .index, label: .label}' -c
{"index":1,"label":""}
{"index":2,"label":"testLabelFocus"}
$ yabai -m space --focus testLabelFocus  # my screen is now focused on that space, index=2
$
```

But if I try to focus the same space after it is destroyed, nothing happens (as expected), but the command returns as successful rather than with a failure message
```bash
$ yabai -m space --destroy testLabelFocus
$ yabai -m query --spaces | jq '.[] | {index: .index, label: .label}' -c
{"index":1,"label":""}
$ yabai -m space --focus testLabelFocus  # failed, but the return value is 0 and no error isshown
$
```

and if I have a second monitor, my wallpaper blanks out for a brief second before it returns. Almost as if it's starting to switch spaces before realizing that there is no such space.

https://user-images.githubusercontent.com/2654835/227661032-63912a87-b14d-4403-8a72-19ba9f5148ab.mov

**Comment by koekeishiya** [comment]
Fixed on master (Ventura only for now as we depend on a system event that I'm not sure exists in earlier versions).
