### ISSUE TITLE
Exploring Disabling 'Display has Separate Spaces' Check

### ISSUE THREAD

**Issue by kendreaditya** [koekeishiya/yabai#1679]
Hello 👋

I just want to preface this by saying I don't know much so please bear with me. Having shared spaces is a must have for me, I was looking for other alternatives, but yabai is by far the best and least buggy. 

I know in [#193](https://github.com/koekeishiya/yabai/issues/193), it states yabai uses private functions for interacting with spaces and displays that have been reverse engineered and these functions rely on that setting being enabled. I was just curious if I disabled [this](https://github.com/koekeishiya/yabai/blob/53c426d57a0bc947a930060efff52af4959494af/src/yabai.c#:~:text=if%20(!space_manager_has_separate_spaces,%7D)) check, if the tiling would still work:

```
if (!space_manager_has_separate_spaces()) {
        error("yabai: 'display has separate spaces' is disabled! abort..\n");
    }
```

It looks like it does, but has trouble tiling on a desktop switch. If I minimize and open all the windows back it works like normal! However, the log out puts `could not locate the space to act on!`.

Is there a potential for this?

### System details:
OS: MacOS Monterey 12.6.3
yabai --version: yabai-v5.0.2

**Comment by 24unix** [comment]
> I just want to preface this by saying I don't know much so please bear with me. Having shared spaces is a must have for me, I was looking for another alternatives, but yabai is by far the best and least buggy.


For me too, and all workarounds are gone or buggy.
Before Big Sur you could use TotalSpaces III to assemble desktops that behave like shared spaces.

My current workaround is using skhd to switch all relevant spaces in sync. But that breaks if an app comes to foreground and the space switch, they get out of sync.

I cannot understand that Apple came to the strange idea that breaking desktops might be a good idea. :-(

**Comment by kendreaditya** [comment]
Upon further exploration, it seems like the windows auto snap to the main display and can't be configured to be placed on other displays with shared spaces.

**Comment by ZebTheWizard** [comment]
If anyone is looking at how to resolve this error, it is referring to "Desktop & Dock" > "Display has Separate Spaces" system setting. In my situation, everything worked until I restarted my computer. Guessing I accidently turned this setting off when it should be enabled.

![yabai](https://github.com/koekeishiya/yabai/assets/13527122/05a713c3-134c-44a2-9b45-81962e0c65d6)
