### ISSUE TITLE
Arrow-keys

### ISSUE THREAD

**Issue by alexgulbrandsen** [koekeishiya/yabai#1681]
Hello folks! 
How can I use the arrow-keys in the skhdrc file?

**Comment by azinsharaf** [comment]
Use skhd --observe command to find the keycode of any key (in your case arrow key) then use that key in skhdrc file.

**Comment by alexgulbrandsen** [comment]
lctrl + alt - 0x7B : yabai -m window --warp west
lctrl + alt - 0x7D : yabai -m window --warp south
lctrl + alt - 0x7C : yabai -m window --warp east
lctrl + alt - 0x7E : yabai -m window --warp north

How come this is not working ?

**Comment by 24unix** [comment]
lctrl + alt - 0x7"a weird sign" �E : yabai -m window --warp north



There must be a strange character inside.

**Comment by alexgulbrandsen** [comment]
My bad. should be like this:

lctrl + alt - 0x7B : yabai -m window --warp west
lctrl + alt - 0x7D : yabai -m window --warp south
lctrl + alt - 0x7C : yabai -m window --warp east
lctrl + alt - 0x7E : yabai -m window --warp north

**Comment by waj** [comment]
Why not just `up`, `down`, `left`, `right`?

**Comment by alexgulbrandsen** [comment]
I have tried using this: 
lctrl + lalt - left : yabai -m window --display west; yabai -m display --focus west
lctrl + lalt - right : yabai -m window --display east; yabai -m display --focus east;

but still no success

**Comment by koekeishiya** [comment]
Probably secure keyboard entry causing issues; if you still have problem make an issue in the skhd repo.
