### ISSUE TITLE
Preserve apps in their dekstop spaces

### ISSUE THREAD

**Issue by weeebdev** [koekeishiya/yabai#1685]
I am not sure if it is related to yabai specifically, but I wanted to keep the applications in their  own dekstop spaces where they have been opened. Thus, if I will restart Mac, e.g. Chrome that has been opened in the 4th desktop will open in the same desktop space, also keeping the split view. Is it possible or what kind of app can you suggest me to solve this problem?

**Comment by dakeryas** [comment]
I think the issue is that despite such rules, some apps still randomly appear on other desktops.

**Comment by weeebdev** [comment]
> You can label spaces as follows:
> 
> `yabai -m space 3 --label social`
> 
> and then create an app specific rule that puts the app in the space with the given label:
> 
> `yabai -m rule --add label="Ferdium" app="^Ferdium$" space=social`

Thank you but I don't want to define space for each app explicitly. What I want is that yabai or other app will remember which app is where before shutting Mac down and then reopen them in  spaces respectively.




> I think the issue is that despite such rules, some apps still randomly appear on other desktops.

Yep.

**Comment by koekeishiya** [comment]
> Does this work without the extended privileges?

yes

> are apps supposed to be moved to the spaces always or only if they are created?

when the window is created

> I am not sure if it is related to yabai specifically, but I wanted to keep the applications in their own dekstop spaces where they have been opened. Thus, if I will restart Mac, e.g. Chrome that has been opened in the 4th desktop will open in the same desktop space, also keeping the split view. Is it possible or what kind of app can you suggest me to solve this problem?

Create a script that queries open windows and stores the necessary information in a file on disk (app name, title, space), that runs on shutdown. On startup, run a script that processes this file, and moves windows to the correct place using that information.

**Comment by dakeryas** [comment]
I have noticed that restarting yabai via `yabai --restart-service` repositions all the windows correctly; I have been using it a lot lately as a hacky fix.
