### ISSUE TITLE
Serious incompatibility with Jetbrain IDE

### ISSUE THREAD

**Issue by Apolsus** [koekeishiya/yabai#1687]
If you use an IDE for development, such as the Jetbrain family of IDEs, you will often have pop-ups.

If you don't want these pop-ups to be managed.You have to add the following rules.

```
JB_Apps='^(CLion|PyCharm|IntelliJ IDEA)$'
yabai -m rule --add app="${JB_Apps}" title!=".*\[.*\].*" manage=off
```
But this leads to another problem. When you open a project from the welcome interface, it will not be managed.

Adding rules like `app="${JB_Apps}" title=".*\[.*\].*" manage=on` doesn't make up for it.

**Comment by Apolsus** [comment]
I've read the #194 issue and spent a lot of time trying each approach, and it just doesn't work at all. This issue shouldn't be closed by mistake, people have raised this issue until now, and the solution doesn't work.

Given that Jetbrain IDE is a very common development software, it is unacceptable that this software cannot be managed automatically. I hope this issue will be taken seriously.

**Comment by Apolsus** [comment]
I suspect this is due to yabai's inability to react to window title changes, as I have observed the IDE changing the window title after lunch.

**Comment by Apolsus** [comment]
This should be because the JB IDE modifies the title and starts out empty.

Yabai has no way to track the final title.

**Comment by Apolsus** [comment]
This rule works well:

```
JB_Apps='^(CLion|PyCharm|IntelliJ IDEA)$'
yabai -m rule --add app="${JB_Apps}" manage=off
yabai -m rule --add app="${JB_Apps}" title="^$"  manage=on
```

**Comment by chasonyu** [comment]
When the Jetbrains app is open, restarting 'yabai' will cause the app's window to become floating again.

**Comment by Apolsus** [comment]
> When the Jetbrains app is open, restarting 'yabai' will cause the app's window to become floating again.

Then add the additional rule in the annotate.

**Comment by iamim** [comment]
For Rider the app name should be `JetBrains Rider`. `yabai --verbose` is helpful for debugging this kind of issues.

**Comment by abey79** [comment]
Possible work-around here: https://github.com/koekeishiya/yabai/discussions/2297#discussioncomment-9568503

> Yabai has no way to track the final title.
This doesn't seem entirely correct, since yabai can signal title change.

**Comment by RustyDoggoBytes** [comment]
thanks @chasonyu for that tip! I added the `cmd + shift - tab : yabai --restart-service` to `.skdhrc`  :)
