### ISSUE TITLE
Make window float when only 1 application.

### ISSUE THREAD

**Issue by MaliciousXatt** [koekeishiya/yabai#1696]
Hi, 
is it possible that when there is only 1 window open on the specific desktop, the application goes into float mode? Instead of going fullscreen instantly?

Would be awesome if this would work.
If not, then I've got another possible question:
How to make the first window have a specific size instead of going full screen?
 
 Thank you.

**Comment by azinsharaf** [comment]
Do you want to have float window for any application?
If you know the app name you can use "manage off" for it.

**Comment by MaliciousXatt** [comment]
Not a specific app, but when 1 application is open it floats, but when another opens it goes into tiling

**Comment by koekeishiya** [comment]
You can use signals to script this.

https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#signal

**Comment by MaliciousXatt** [comment]
Can you give me an example?

**Comment by Bellavene** [comment]
#!/bin/zsh
CURRENT_DISPLAY=$(yabai -m query --windows --window | jq '.display')
WINDOWS_ARRAY=$(yabai -m query --windows --space $(yabai -m query --spaces --space | jq '.index') --display $CURRENT_DISPLAY | jq -r 'map(select(.["is-minimized"]==false and .["is-floating"]==false))')
NUMBER_OF_WINDOWS=$(echo $WINDOWS_ARRAY | jq -r 'length')

case $NUMBER_OF_WINDOWS in
	[0-1])
		yabai -m config layout float
		;;
	2)
		yabai -m config layout bsp
		;;
	*)
		yabai -m config layout bsp
		;;
esac

**Comment by MaliciousXatt** [comment]
Awesome thank you!
Should i make this a serivce?
Or do I just add  this in the Yabai config?

**Comment by MaliciousXatt** [comment]
yea this doesn't work. Just puts everything in the middle, regarding having multiple things open.

**Comment by Bellavene** [comment]
_May need some adjustments_
