### ISSUE TITLE
Things 3 not being managed by Yabai

### ISSUE THREAD

**Issue by th4lmain** [koekeishiya/yabai#1699]
As title says. Yabai completely ignores it, covering it with managed apps and not moving it, even when focused. I haven't had this happen with other apps, but I doubt this is exclusive to Things 3. Things 3 is available here https://culturedcode.com/things/. Unfortunately, this a paid app that doesn't appear to have a free trial, so it can't be easily reproduced on other machines (unless you're willing to pay a regrettable amount for todo list software).

**Comment by koekeishiya** [comment]
Works fine for me out of the box.
<img width="1800" alt="Screenshot 2023-04-12 at 15 29 01" src="https://user-images.githubusercontent.com/6175959/231472922-760eef84-4cde-4d03-83c6-f890a4e77785.png">



Output of `yabai -m query --windows`:

```
{
        "id":496,
        "pid":5097,
        "app":"Things",
        "title":"Today",
        "frame":{
                "x":905.0000,
                "y":586.0000,
                "w":885.0000,
                "h":528.0000
        },
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "display":1,
        "space":1,
        "level":0,
        "opacity":1.0000,
        "split-type":"horizontal",
        "split-child":"second_child",
        "stack-index":0,
        "can-move":true,
        "can-resize":true,
        "has-focus":false,
        "has-shadow":false,
        "has-border":false,
        "has-parent-zoom":false,
        "has-fullscreen-zoom":false,
        "is-native-fullscreen":false,
        "is-visible":true,
        "is-minimized":false,
        "is-hidden":false,
        "is-floating":false,
        "is-sticky":false,
        "is-topmost":false,
        "is-grabbed":false
},{
        "id":476,
        "pid":5097,
        "app":"Things",
        "title":"Upcoming",
        "frame":{
                "x":904.0000,
                "y":48.0000,
                "w":885.0000,
                "h":528.0000
        },
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "display":1,
        "space":1,
        "level":0,
        "opacity":1.0000,
        "split-type":"horizontal",
        "split-child":"first_child",
        "stack-index":0,
        "can-move":true,
        "can-resize":true,
        "has-focus":false,
        "has-shadow":false,
        "has-border":false,
        "has-parent-zoom":false,
        "has-fullscreen-zoom":false,
        "is-native-fullscreen":false,
        "is-visible":true,
        "is-minimized":false,
        "is-hidden":false,
        "is-floating":false,
        "is-sticky":false,
        "is-topmost":false,
        "is-grabbed":false
}]

```

**Comment by peppy** [comment]
As a heads up for anyone else running into this (as I have more than once), make sure you don't have Things.app (or any other app that may not be working with yabai) set to "assign to all desktops". This will break it. Set it to "None" instead:

![Safari 2024-08-30 at 04 48 18](https://github.com/user-attachments/assets/a32a33ea-10c7-4882-9ae4-78c8fa511f90)

**Comment by rublev** [comment]
> As a heads up for anyone else running into this (as I have more than once), make sure you don't have Things.app (or any other app that may not be working with yabai) set to "assign to all desktops". This will break it. Set it to "None" instead:
> 
> ![Safari 2024-08-30 at 04 48 18](https://github.com/user-attachments/assets/a32a33ea-10c7-4882-9ae4-78c8fa511f90)

I would love if yabai worked with "All Desktops" 😭 Would solve all my problems. Could have multiple browser windows, and then switch spaces and have your code editor be on all of them! 

@koekeishiya Huge fan, quick question, is this at all possible what I'm asking? Cheers
