### ISSUE TITLE
Status bar showing on fullscreen Firefox videos

### ISSUE THREAD

**Issue by danteissaias** [koekeishiya/yabai#170]
As you can see, I have made this video fullscreen, and the status bar still shows.

![Image](https://i.imgur.com/7nFtOVI.jpg)

I'm certain this is not intended behavior. Furthermore, when making Firefox natively fullscreen with the green button the status bar hides. This behavior occurs on master.

**Comment by danteissaias** [comment]
Upon further investigation, I have discovered that this commit seems to be the thing that broke it: [49a1494332a7c06f3f76896cf676df1f4ceb1f54](https://github.com/koekeishiya/yabai/commit/49a1494332a7c06f3f76896cf676df1f4ceb1f54)

A temporary fix can be to revert this value back to 4:

```cpp
SLSSetWindowLevel(g_connection, bar->id, CGWindowLevelForKey(4));
```

**Comment by koekeishiya** [comment]
This isn't much to do with codebase, but more with how macOS window ordering/layering work. As far as I know there is no way to fix both of these issues.

**Comment by danteissaias** [comment]
That's a real shame, I haven't had that many run-ins with #124, so I think I'll stick to having it set to 4.

**Comment by koekeishiya** [comment]
I agree that this issue is more annoying/breaking than the other, reverted to 4.

**Comment by danteissaias** [comment]
Cool

**Comment by dominiklohmann** [comment]
Here's another workaround that should work without reverting the behaviour:

When a window is resized and its frame is equal to the frame of the display its on, make the window appear topmost.

**Comment by koekeishiya** [comment]
I don't think doing that is worth it. Having the statusbar not being topmost is not a be a big deal, as windows are padded by that height anyway.
