### ISSUE TITLE
Kill window

### ISSUE THREAD

**Issue by executionByFork** [koekeishiya/yabai#1701]
It would be nice if yabai had an option to kill a window instead of just an option to close it. As far as I can tell, only --close can be used, and this does not actually quit out of the window. It reduces it to the dock, where it still runs in the background as shown by the dot below the icon.

I could just use the cmd+q key as a workaround to kill a window, however apple does not allow me to customize this keybind in any way. I would like to modify the keybind to more closely match i3, and kill windows with mod+shift+q. This is also harder to accidentally hit than cmd+q. [I am not the only one who dislikes cmd+q](https://apple.stackexchange.com/questions/78948/how-to-disable-command-q-for-quit).

Slight tangential issue, but the --close command does not work if the close button of a window has been removed. For example, removing window decorations on Kitty terminal causes --close to cease functioning because the red close button is no longer displayed. This is noted in the [documentation](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#642-command), however it would be nice to be able to close/kill/etc a window without relying on how it is drawn. Relying on the buttons is an issue for people like me, who would like to remove the useless window decorations and purely use keybinds to open, close, and navigate windows.

Is it feasible to implement window kill (cmd+q) through yabai? And implement window close (cmd+w) through yabai without relying on the title bar buttons?

**Comment by koekeishiya** [comment]
There is no API to close windows without titlebar-buttons. There is some stylemask that windows can set in which the titlebar close button exists in the API, but is not actually visible on the window. ie. the Kitty terminal supports this option.

**Comment by cagdassalur** [comment]
If you're using `skhd` already you can do this: 
```
cmd + shift - q : skhd -k "cmd - q "
```
Maybe you can also disable the cmd+q shortcut completely:
```
cmd + shift - q   : kill $(yabai -m query --windows --window | jq .pid)
cmd - q : : "
```
However i'm not sure if you want to kill the process instead of letting it gracefully quit, maybe there's a way to do that as well using the pid of the app, idk..

**Comment by henrynvn09** [comment]
here is the code in case anyone want to bind the same button for close window and kill the last instance on skhd.
skhdrc:
`alt - q : $HOME/.config/skhd/kill_last_instance.sh`

kill_last_instance.sh:
```
#!/usr/bin/env bash

window_pid=$(yabai -m query --windows --window | jq -r '.pid') 
count_pid=$(yabai -m query --windows | jq "[.[] | select(.pid == ${window_pid})] | length")
if [ "$count_pid" -gt 1 ]; then
	yabai -m window --close
else
	kill "${window_pid}"
fi
```

**Comment by wthrajat** [comment]
Working as expected, thanks @henrynvn09!
