### ISSUE TITLE
macOS 13.3.1 cannot focus space due to an error with the scripting-addition v5.0.3.

### ISSUE THREAD

**Issue by alanmicah** [koekeishiya/yabai#1703]
When running yabai via `brew services start yabai` Yabai doesn't work as expected such as shadows, changing focus for spaces etc.
When running `skhd -V` and trying to change focus space I get _cannot focus space due to an error with the scripting-addition._.

I have uninstalled and reinstalled following:
https://github.com/koekeishiya/yabai/wiki/Uninstalling-yabai
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

Currently, my only workaround is running `$(which yabai)` which runs as expected.

**Comment by alanmicah** [comment]
I'm pretty sure I kept the sha256 hash updated everytime I updated/reinstalled yabai, but I just followed this **[comment ]**(https://github.com/koekeishiya/yabai/issues/1639#issuecomment-1451211717) and it now works.

Still not sure why Yabai stopped working after updating from macOS 13.3 to 13.3.1

**Comment by alanmicah** [comment]
I just restarted my macbook today and now I am once again receiving an `error with the scripting-addition`

**Comment by gldtn** [comment]
Let me try to help.. you installed from HEAD correct?

Are you trying to keep Yabai updated automatically?

Try adding this your .zshrc file
```
# Update sha256 hash for scripting edition
function suyabai () {
    SHA256=$(shasum -a 256 $(which yabai) | awk "{print \$1;}")
    if [ -f "/private/etc/sudoers.d/yabai" ]; then
        sudo sed -i '' -e 's/sha256:[[:alnum:]]*/sha256:'${SHA256}'/' /private/etc/sudoers.d/yabai
        echo "sudoers > yabai > sha256 hash added"
    else
        echo "sudoers file does not exist yet"
    fi
}
````

Source your zsh with: `source $ZDOTDIR/.zshrc`
Add run `suyabai`

----------------------------------------------------------

You can also add to `yabairc`:
```
# Keep yabai up to date automatically
YABAI_CERT=yabai-cert sh -c ~/.config/yabai/update.sh &
```

Create a `update.sh` and place it in `~/.config/yabai/update.sh`
Also make sure it's executable with `chmod -x update.sh`

You can download update.sh from my dotfiles if you would like:
`https://github.com/gldtn/dotfiles/blob/main/.config/yabai/update.sh`

I don't remember exactly from who's dotfiles I got that exactly, but it being working flawlessly  for me, even with Ventura 13.3.1,   Yabai updates automatically every time there is a push to the HEAD 

Make sure you followed https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD) instruction on the codesigning with a self-signed certificate

**Comment by lightbluepoppy** [comment]
I have the same problem.

<details>
<summary>neofetch</summary>

```
                    'c.          admin
                 ,xNMM.          -----------------------------
               .OMMMMo           OS: macOS 13.2.1 22D68 arm64
               OMMM0,            Host: Mac14,9
     .;loddo:' loolloddol;.      Kernel: 22.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 14 hours, 5 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 43 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1352x878@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: yabai
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: WarpTerminal
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   CPU: Apple M2 Pro
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   GPU: Apple M2 Pro
    kMMMMMMMMMMMMMMMMMMMMMMd     Memory: 3660MiB / 32768MiB
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.
```
</details> 

<details>
<summary>skhdrc file</summary>

```bash
...
# switch between spaces
ctrl - right : yabai -m space --focus next
ctrl - left : yabai -m space --focus prev
```
</details>

<details>
<summary>skhd -V</summary>

```bash
hotkey :: #149 {
	mod: 'ctrl'
	key: 'right' (0x7c)
	cmd: 'yabai -m space --focus next'
}
hotkey :: #150 {
	mod: 'ctrl'
	key: 'left' (0x7b)
	cmd: 'yabai -m space --focus prev'
}
skhd: watching files for changes:
	/Users/admin/.config/skhd/skhdrc
cannot focus space due to an error with the scripting-addition.
```
</details> 

<details>
<summary>brew info yabai and yabai --version</summary>

```bash
brew info yabai
---
...
==> koekeishiya/formulae/yabai: stable 5.0.3, HEAD
...
```

```bash
yabai version
---
yabai-v5.0.3
```
</details> 

<details>
<summary>sudo yabai --load-sa</summary>

```bash
Password:
yabai: missing required nvram boot-arg '-arm64e_preview_abi'!
```
</details>

I DID execute the command below when I initially installed yabai. 
I tried it again and rebooted. 

```bash
sudo nvram boot-args=-arm64e_preview_abi
```

After the reboot, `Accessibility Access` pane started appearing over and over in less than 10 seconds, and the fans event started growling.

<details>
<summary>Accessibility Access </summary>

<img width="476" alt="Screenshot 2023-04-28 at 13 22 22" src="https://user-images.githubusercontent.com/65863981/235136144-06566d6f-ccec-4883-9258-91653c706668.png">

<img width="458" alt="Screenshot 2023-04-28 at 13 22 46" src="https://user-images.githubusercontent.com/65863981/235136482-3dfef9e5-28ea-45dd-8877-240617d2feab.png">

</details>

There were two `yabai` settings. I deleted both `yabai` settings from the Accessibility and added manually from `/admin/.config/yabai`

`yabai` is completely broken. `brew services start yabai` returns an error 256.

<details>
<summary>brew services ls</summary>

```
brew services ls
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the koekeishiya/formulae tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/koekeishiya/homebrew-formulae/skhd.rb:27

Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the koekeishiya/formulae tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/koekeishiya/homebrew-formulae/yabai.rb:42

Name  Status     User    File
skhd  none
yabai error  256 orcinus ~/Library/LaunchAgents/homebrew.mxcl.yabai.plist
```
</details>

What can I do then...

**Comment by koekeishiya** [comment]
There are 2 sections, one is for installing the latest release, and one is for installing the dev version.

You are supposed to select only *one* path. 
Both of them include a section for configuring the scripting addition, but if you look closely, they are largely the same. 

The scripting addition works fine in either version. 
There is one exception to this: a new macOS update is released which breaks the scripting addition, and a commit that solves this is only on the dev branch before a new release is made.

The reason that yabai sometimes can appear multiple times in the `Accessibility Access` pane, is that the signature of an application *changes* when it is re-compiled. The binary that I release and that is installed using the *install latest release* instructions is already codesigned by me to avoid this issue.

When you start building from source it will get a new signature, and if you do not codesign it yourself, it will appear as a new application in the Accessibility Pane. Even if you codesign it, it will be different from the version that is codesigned by me, and so it will appear again. 

Again, if you don't have a good idea of what is going on, stick with the "latest release" instructions.

If your state is confusing and/or messed up, simply uninstall yabai and remove all traces of it (using the uninstall instructions in the wiki), remove all entries from `Accessibility Access` and reboot. Follow the installation instructions as-written and everything will work fine.

As a separate note, brew services integration has been removed in the latest release (v5.0.4) and replaced by a launchd service integration embedded into yabai itself. The installation instructions has been updated to match this.
