### ISSUE TITLE
focus follows mouse conflict with Zoom; disable focus_follows_mouse for specific applications?

### ISSUE THREAD

**Issue by small-luck2367** [koekeishiya/yabai#1706]
When **focus_follows_mouse** is set to **autofocus** or **autoraise**, the menus in a Zoom (zoom.us) chat window (like "Reactions" which is commonly used) close immediately when the mouse moves.

Screen recording of the issue:
https://imgur.com/a/HDYDhfM ([backup](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTIxZWVhMWE1ZDU3MWYxZDQ5OWRhMGYwYTZmN2E4Y2UwN2MyOTg4ZiZjdD1n/yGLQCD12EPTDCyojsq/giphy.gif))

Is there any way to fix this conflict?

Can I disable focus_follows_mouse for specific applications or windows?

Thank you for Yabai's focus_follows_mouse feature. This is the only way I've found to come close to how Windows handles mouse focusing. I just converted from Windows to Mac, and I can't get over how it requires a click just to focus a window, and a second click to interact with it.

**Comment by small-luck2367** [comment]
I think this might be a workaround for the Zoom conflict.

```
# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse	autofocus

# disable focus_follows_mouse when a Zoom window is focused
yabai -m signal --add event=window_focused app=^zoom.us$ action="yabai -m config focus_follows_mouse off"

# renable focus_follows_mouse autofocus after Zoom meeting is finished
yabai -m signal --add event=application_deactivated app=^zoom.us$ action="yabai -m config focus_follows_mouse autofocus"
yabai -m signal --add event=application_terminated app=^zoom.us$ action="yabai -m config focus_follows_mouse autofocus"
yabai -m signal --add event=application_hidden app=^zoom.us$ action="yabai -m config focus_follows_mouse autofocus"
yabai -m signal --add event=window_destroyed app=^zoom.us$ action="yabai -m config focus_follows_mouse autofocus"
yabai -m signal --add event=window_minimized app=^zoom.us$ action="yabai -m config focus_follows_mouse autofocus"
```

Kudos to Bing Chat for teaching me this solution. LLMs are incredible. O_O

**Comment by ucchiee** [comment]
FYI, My config:
```
# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
# focus follow mouse is disabled when holding a modifier key
yabai -m config focus_follows_mouse autoraise
```

Holding a mouse_modifier key disables focus_follows_mouse, so it's fine for me.

**Comment by koekeishiya** [comment]
I don't think there is anything better do to here than what has been suggested and the changes already made to master since this issue was made.
