### ISSUE TITLE
yabai not working after brew update on two seperate machines, working well on both previously

### ISSUE THREAD

**Issue by michael-odonovan** [koekeishiya/yabai#1707]
Just did a monthly brew update and now can't get yabai working again.
Have tried these multiple times:
- reinstalling
- restarting 
- have enabled in Accessibility
- have removed app in Accessibility and tried adding it again.

Any help much appreciated.
Really enjoy using your app on a daily basis.

**Comment by florian42** [comment]
On my machine, running `yabai` in the terminal displayed an error (`Displays Have Separate Spaces not turned on`), which helped resolve the issue.

**Comment by koekeishiya** [comment]
Brew services has been removed, if you used that prior. Use `yabai --start-service` instead.
