### ISSUE TITLE
Resize window to fit in the bottom left quarter / third / ... + move it there

### ISSUE THREAD

**Issue by ituri** [koekeishiya/yabai#1708]
Hi,

I'm trying to make the transition from Rectangle to yabai. I've really been missing the automatic tiling to that's a big plus with yabai. To make the transition a bit easier, I'm trying to replicate a few of Rectangle's shortcuts which are very deeply engraved into my muscle memory.
Rectangle provides these shortcuts:
![Screenshot 2023-04-18 at 14 14 22](https://user-images.githubusercontent.com/871297/232778098-9f840fd1-b745-4710-9dda-0945a3bf5797.png)
For now I just want to replicate the second group of commands which divides the screen into four quarters and then let's me resize and move the window the the respective quarter of the screen. 

I've done my fair bit of google and research in yabai's documentation and have also looked at many different `skhdrc` dotfiles. The closest I've come has been the snippet betlow, but this is still nothing close to what I'm looking for:
```
lctrl + shift - h : yabai -m window --resize left:-50:0; \
                  yabai -m window --resize right:-50:0
lctrl + shift - j : yabai -m window --resize bottom:0:50; \
                  yabai -m window --resize top:0:50
lctrl + shift - k : yabai -m window --resize top:0:-50; \
                  yabai -m window --resize bottom:0:-50
lctrl + shift - l : yabai -m window --resize right:50:0; \
                  yabai -m window --resize left:50:0
```
With these commands I can resize a window step by step but as I said, I'd rather like the window resized to a quarter of my display and then moved to one of the four corners. Is that possible with yabai?

Thank you so much!
ituri

**Comment by ituri** [comment]
Thank you! I'm getting there. Left and right half are working now. The quarters are also almost working but I'm struggling with the top right one. Can you help me out here? It doesn't do what it's supposed to do (put the window in the top right quarter). I have to press the shortcut twice in order to get the window moved to the respective corner. Here's the code:
```
#  ctrl - alt - u: top left
ctrl + alt - u  : yabai -m window --toggle float --grid 2:2:0:0:1:1

#  ctrl - alt - j: bottom left
ctrl + alt - j  : yabai -m window --toggle float --grid 2:2:0:1:1:1

#  ctrl - alt - k: bottom right
ctrl + alt - k  : yabai -m window --toggle float --grid 2:2:1:1:1:1

#  ctrl - alt - i: top right
ctrl + alt - i  : yabai -m window --toggle float --grid 2:2:1:0:1:1
```

For debugging purposes, I'm running skhd manually with a verbose flag and I keep getting these messages:
` cannot apply grid layout to a managed window.`
Can you explain the problem here?

**Comment by koekeishiya** [comment]
The `--toggle float`   makes a managed window become managed, and an unmanaged window will become managed. Only unmanaged windows can be repositioned/resized with the grid command.

You can make a script that uses the query system to check the current state and only call `--toggle float` if it is currently managed. To retrieve info about the currently focused window you can use `yabai -m query --windows --window` and the property you are interested in is `is-floating`, which when true, means that the window is unmanaged.

You can use the `jq` tool to process the json output.

**Comment by ituri** [comment]
Thank you for your help!

**Comment by wc356** [comment]
> The `--toggle float` makes a managed window become unmanaged, and an unmanaged window will become managed. Only unmanaged windows can be repositioned/resized with the grid command.
> 
> You can make a script that uses the query system to check the current state and only call `--toggle float` if it is currently managed. To retrieve info about the currently focused window you can use `yabai -m query --windows --window` and the property you are interested in is `is-floating`, which when true, means that the window is unmanaged.
> 
> You can use the `jq` tool to process the json output.

QQ: Is it a valid approach to have the script conditionally call `--toggle float` to set the current window to be temporarily floating so that it can be repositioned to take right-half of the screen w/ the grid command, and then set it back to being managed by yabai afterwards? Or am I taking a wrong approach and thinking about this the wrong way?

I've created a script to do as you mentioned and while it works, I'd like to be able to set it "back" to being managed by yabai so that I can move it to another display or so later on.

This was my attempt w/ having the script turn it off to use the grid command and then turn off the `float` again but it causes the window to go back into full-screen.
```zsh
# yabairc
yabai -m config layout bsp

# script.sh
is_floating=$(yabai -m query --windows --window | jq -r '.["is-floating"]')

if [[ "$is_floating" == "false" ]]; then
  # temporarily turn off manage to use grid command
  yabai -m window --toggle float --grid 1:2:0:0:1:1
  # turn window float back to off
  yabai -m window --toggle float
fi

# skhdrc
ctrl + shift + cmd - h : ~/.config/skhd/script.sh
```

I've only used "bsp" mode so far, so I'm not too familiar with managing both floating windows & managed-windows at the same time.
