### ISSUE TITLE
Detect Touch ID fingerprint unlock dialog using Yabai rules and signals?

### ISSUE THREAD

**Issue by small-luck2367** [koekeishiya/yabai#1709]
Is there a way to detect the [Touch ID fingerprint unlock dialog](https://i.1password.com/media/opm8-touch-id-prompt.png) using Yabai rules and signals? I'm trying to automatically disable focus_follows_mouse autofocus when the TouchID dialog appears because TouchID only works when that dialog is focused.

I've tried querying for all windows but the Touch ID dialog doesn't appear as a window as far as I can tell.
`yabai -m query --windows`

**Comment by fcaraujo** [comment]
Same here, I'm interested in ignoring the touch id dialog, leaving it at the top of windows, any ideas?

**Comment by jerfly1** [comment]
Looking for the solution as well

**Comment by bin101** [comment]
> For anyone still looking for this, this worked for me: [#1219 (comment)](https://github.com/koekeishiya/yabai/issues/1219#issuecomment-1091077838)
> 
> i simply added `yabai -m rule --add title="^$" manage=off` to my yabairc.
> 
> Im not sure whether this causes problems with Yabai not managing other windows, but so far i had no issues.

Your rule just describes windows with an empty title.
Should also work this way:

`yabai -m rule --add title="" manage=off`

But yes this should cover dialogs like the one from the bitwarden browser plugin 👍

**Comment by bin101** [comment]
I also had to add yabai -m rule --add app="^coreautha$" manage=off for the touch id dialog, but now it's working fine, thanks ;)
