### ISSUE TITLE
Replicate i3 dropdown functionality without disabling SIP

### ISSUE THREAD

**Issue by varunaswal** [koekeishiya/yabai#1710]
It's possible to replicate i3 dropdown functionality by creating a virtual display to use as a scratchpad space (using the `CGVirtualDisplay` private API).  

I've played around in my local hammerspoon config and have been able to get this working by using BetterDisplay to create a dummy display and sending a window to/from it. Looking at the open source code of BetterDisplay, it seems the process of [creating a virtual display](https://github.com/waydabber/BetterDisplay/blob/0aa8394a3c04762d41268fa9c35053ef24d1ef1e/BetterDummy/Model/Dummy.swift#L92) isn't too complicated, so hopefully this functionality can be added to yabai. 

The closest possible current solution is to either:
- disable SIP and dedicate a space to acting as scratchpad
- not disable SIP and either do the same, or minimize windows (both methods will still have animations)

I think this would bring a really handy feature to macos window management. I'm happy to take this on myself but would need some guidance as I'm new to open source and macos development

**Comment by koekeishiya** [comment]
Closing as not planned.
