### ISSUE TITLE
Conflict with scoot

### ISSUE THREAD

**Issue by DoDoENT** [koekeishiya/yabai#1719]
I'm using [scoot](https://github.com/mjrusso/scoot) - a handy tool for using the keyboard to quickly navigate to clickable elements on Mac (similar to Chrome's vimium, but uses Mac's accessibility API to target any clickable element).

However, when Scoot is started, yabai thinks it has a window and tiles it, as shown in the screenshot:

![image](https://user-images.githubusercontent.com/158844/234912233-56240620-e2d5-4da6-9537-2e143925e7d6.png)

I first thought that this is an issue with Scoot, but upon trying Amethyst, the problem did not appear, so I think it's an issue with yabai.

I tried using `yabai -m query --windows --space <my_space>` to get the ID of that "hidden" window in order to add a rule to prevent yabai from managing it, but yabai does not detect that window at all. Interestingly, after Scoot boots, restarting the yabai fixes the tiling, but still tiles Scoot's overlay that displays shortcuts, however only the first time (canceling Scoot's operation and starting shortcut population again seems to fix the issue).

Sorry for the confusing description - I hope you can try reproducing the issue on your side. I'm currently using yabai v5.0.3.

**Comment by diegolhambi** [comment]
Try adding `yabai -m rule --add app="^Scoot$" manage=off border=off` to your yabai config.

**Comment by DoDoENT** [comment]
@diegolhambi , thanks. It works. May I ask how did you discover the name of Scoot's window, as the usual `query` method didn't work for me (see the original message above)?

**Comment by diegolhambi** [comment]
I used the app name instead of the title name, so all the windows created by the app named Scoot will be not managed by the yabai.

More info about the arguments: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#663-argument

I use Scoot too is a nice app. 😁
