### ISSUE TITLE
iBooks will not tile

### ISSUE THREAD

**Issue by capaldo** [koekeishiya/yabai#172]
As the title says, Books.app will not tile when opening a book. Even restarting after the book is open does not tile the window.

**Comment by dominiklohmann** [comment]
This has been an issue with chunkwm and kwm as well.

A workaround is to toggle native-fullscreen twice on the book window and then tile it. You need to do this manually currently as the window cannot be interacted with during the custom animation.

**Comment by capaldo** [comment]
> This has been an issue with chunkwm and kwm as well.
> 
> A workaround is to toggle native-fullscreen twice on the book window and then tile it. You need to do this manually currently as the window cannot be interacted with during the custom animation.

Gave this a try but unfortunately it does not work anymore.

**Comment by capaldo** [comment]
> > This has been an issue with chunkwm and kwm as well.
> > A workaround is to toggle native-fullscreen twice on the book window and then tile it. You need to do this manually currently as the window cannot be interacted with during the custom animation.
> 
> Gave this a try but unfortunately it does not work.

So something that works is putting the library screen in full screen and opening the book. It then tiles whatever book was opened.

**Comment by koekeishiya** [comment]
In the latest version everything seems to work fine, except that the book is marked as a floating window when opened. This is likely due to the fact that it responds as non-resizable/movable or something for a short moment in time. You can manually unfloat the window and it will tile properly.

**Comment by technoplato** [comment]
For those curious about how to do this, you can add these lines to your .skhdrc (assuming you have that configured properly) and press the keys when you're focused window is Books (or whatever non-behaving window is)

```
# toggle tiled mode (used to force Applications (Books, etc) into tiled mode)
alt + cmd + ctrl - f : yabai -m window --toggle float 
```

**Comment by marcushwz** [comment]
Anyone got Books to tile in Monterey 12.0.1? It seems that I can't get it to tile anymore

**Comment by koekeishiya** [comment]
Closing this. Both the main window and books work for me using yabai v4.0.2 and macOS Monterey 12.5.1
