### ISSUE TITLE
Is it possible to keep blur without showing border?

### ISSUE THREAD

**Issue by wang-tc** [koekeishiya/yabai#1726]
I would like to hide border but keep window blur, is this possible?
I found I cannot do `window_border_width 0` and I cannot disable border either as blur needs `window_border on`. Would appreciate any help :)

**Comment by koekeishiya** [comment]
Maybe making the color transparent would be a workaround. `yabai -m config active_window_border_color 0x00000000`

**Comment by koekeishiya** [comment]
Borders have been removed in the latest release (v6.0.0) (#1889) because of multiple issues present in both Ventura and Sonoma.
