### ISSUE TITLE
Updated to v5.0.4 --HEAD macOS Monterey 12.6.5 no longer working

### ISSUE THREAD

**Issue by manc1n1** [koekeishiya/yabai#1727]
`~ brew services restart yabai`

`Error: Formula 'yabai' has not implemented #plist, #service or installed a locatable service file`

**Comment by manc1n1** [comment]
New command
`yabai --start-service`

**Comment by steynh** [comment]
May I asked why you moved away from using `brew services`? I like the centralized and predictable way of managing all background services using brew. Why step away from that?

**Comment by koekeishiya** [comment]
#1619
