### ISSUE TITLE
Split the display vertically and horizontally.

### ISSUE THREAD

**Issue by mr-scrpt** [koekeishiya/yabai#1729]
Hi everyone, could you please advise me on how to create a shortcut using yabai and skhd to move the active window under the neighboring one, not next to it, but below - so that these two windows split the screen vertically, while the third open window remains in full height. I can't find anything on this topic on Google. Here is a diagram of what I mean
Before
![before](https://user-images.githubusercontent.com/48452376/235878910-715bef27-c480-4547-997a-09e568c81776.jpg)
After
![after](https://user-images.githubusercontent.com/48452376/235879028-275e2ecf-5eeb-4935-8cf4-c63c44b27f7e.jpg)

**Comment by mrrsm** [comment]
Is this what you are looking for?
```
# toggle window split type
alt - e : yabai -m window --toggle split
```

When I run that it changes between the multiple columns and the block style from your 2nd photo.  Sometimes you have to move the windows around to get them stacked in the space you want.

**Comment by koekeishiya** [comment]
You can also combine toggling splits with `yabai -m space --balance` to easily make three column layouts and revert back to the default 1 by 2 layout, with usable sizes.
