### ISSUE TITLE
Support exclusions in regular expression

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#173]
### Feature request

A common way to use regular expressions is to exclude matches. This can be done easily using regular expressions with negative-lookahead support, where `^(?!foo).*$` would match every line that does not begin with `foo`.

yabai currently does not support negative lookahead. 

An alternative to supporting a more advanced regex syntax would be to allow inverting matches, e.g. by supporting `[[!] app=<regex>]` instead of `[app=<regex>]` filters, where the optional `!` would invert the match.

**Comment by Kryan90** [comment]
I am also interested in a way to do this with yabai.

Chunkwm had a feature when defining a rule to add an "--except" flag which I used for a few rules.

Right now, I am doing this for Pycharm and it kind of works:
```
yabai -m rule --add app="PyCharm" manage=off
yabai -m rule --add app="PyCharm" title="^-PyCharm-.*" manage=on
```
Once I tile the main window, other spawned windows will float. But I have to manually tile the main window.
(I added -PyCharm- to the title of the main window using this plugin for pycharm: https://plugins.jetbrains.com/plugin/9681-custom-title/ )

**Comment by v0rn** [comment]
Either of these features would be great. For Microsoft Outlook I'm currently trying to send the main window to a particular desktop, tile the main and compose windows, and float the rest. Some experimentation suggests there isn't precedence (e.g. first/last matching rule applies) but perhaps I'm doing something wrong. An example set of rules:

```
## Float all windows by default
yabai -m rule --add label=outlook_float \
  app='Microsoft Outlook' \
  manage=off

## Send main window to Space 3
yabai -m rule --add label=outlookmain_s3 \
  app='Microsoft Outlook' \
  title='^(Inbox .+@.+$|Calendar$|People$|Tasks$|Notes$)' \
  space=3

## Tile main and email windows
yabai -m rule --add label=outlookmainemail_tile \
  app='Microsoft Outlook' \
  title='^.+@.+$' \
  manage=on
```

The results are inconsistent; restarting yabai will apply the second rule, but close and reopen the window and it'll follow the floating rule. Changing the order rules are defined in `.yabairc` doesn't make a difference. Invert/`--except` capability would allow the floating rules to be explicitly defined, e.g.:

```
yabai -m rule --except --add label=outlookother_float \
  app='Microsoft Outlook' \
  title='^(.+@.+$|Calendar$|People$|Tasks$|Notes$)' \
  manage=off
```

**Comment by koekeishiya** [comment]
Implemented on master with the following structure: `app[!]=<regex>` and `title[!]=<regex>`, where `[..]` indicates that the token is optional. If `!=` is specified instead of `=` to a non-regex parameter, the command will fail with an error indicating which key was invalid.

**Comment by koekeishiya** [comment]
@jmcvaughn 

> Some experimentation suggests there isn't precedence (e.g. first/last matching rule applies) but perhaps I'm doing something wrong.

Rules are applied in the order they were added. All rules that match will apply, not just the first one. If multiple rules specify a value for the same parameter, the latter rule will override that value, as it was applied last.
