### ISSUE TITLE
Load failed: 5: Input/output error

### ISSUE THREAD

**Issue by joshuacrotts** [koekeishiya/yabai#1731]
I continue to get this error after running `yabai --start-service` (even when installing the latest version of Yabai):

```
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
```

I'm not sure what I'm doing wrong. I've tried uninstalling and reinstalling according to the wiki several times.

**Comment by mental2008** [comment]
I'm facing the same issue. If it helps, my environment is Ventura 13.3.1, Macbook Pro with Apple M1 chip.

**Comment by joshuacrotts** [comment]
Mine is a MacBook Pro with M1 Pro, Ventura 13.3.1.

**Comment by koekeishiya** [comment]
This error is from `launchctl` and is an Apple gimmick. Run `yabai --stop-service` followed by `yabai --start-service` and it should work.

**Comment by mental2008** [comment]
> This error is from `launchctl` and is an Apple gimmick. Run `yabai --stop-service` followed by `yabai --start-service` and it should work.

Thanks for your reply! Now it works well after running these commands.

**Comment by joshuacrotts** [comment]
This fixed it, thanks!

**Comment by believerd** [comment]
> This error is from `launchctl` and is an Apple gimmick. Run `yabai --stop-service` followed by `yabai --start-service` and it should work.

```
~ ❯ yabai --stop-service                                                                                            
Unload failed: 5: Input/output error
Try running `launchctl bootout` as root for richer errors.

~ ❯ yabai --start-service                                                                                           
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
```
It's not working for me.

macOS 13.3.1 arm64

**Comment by LiamKearn** [comment]
> > This error is from `launchctl` and is an Apple gimmick. Run `yabai --stop-service` followed by `yabai --start-service` and it should work.
> 
> ```
> ~ ❯ yabai --stop-service                                                                                            
> Unload failed: 5: Input/output error
> Try running `launchctl bootout` as root for richer errors.
> 
> ~ ❯ yabai --start-service                                                                                           
> Load failed: 5: Input/output error
> Try running `launchctl bootstrap` as root for richer errors.
> ```
> 
> It's not working for me.
> 
> macOS 13.3.1 arm64

Unload all launchctl services for yabai:
```fish
set UID (id -u) && launchctl list | rg -i yabai | awk "{print \"gui/$UID/\"\$3}" | xargs launchctl print | rg '^\s+path = (.*)$' -r '$1' --color=never | xargs -n1 -I{} -p launchctl unload -w {}
```

Then start yabai again:
```fish
yabai --start-service
```

If you're not already good to go, check the error logs:
```fish
launchctl list | rg -i yabai | awk '{print "gui/501/"$3}' | xargs launchctl print | rg '^\s+stderr path = (.*)$' -r '$1' --color=never | xargs less
```

I needed to grant accessibility permissions again so I had:
```
yabai: could not access accessibility features! abort..
yabai: could not access accessibility features! abort..
yabai: could not access accessibility features! abort..
yabai: could not access accessibility features! abort..
```

Just grant and you shouldn't need to relaunch since launchctl will keep trying.
