### ISSUE TITLE
Some windows blurred and unusable with latest release

### ISSUE THREAD

**Issue by albertsj1** [koekeishiya/yabai#1732]
Hi.  I've been using Yabai for over a year and it's amazing.  Thank you for your hard work.

I installed Yabai 5.0.4 yesterday and I now every window that matches a rule I have for 'layer=above' is blurred and unusable.

See an example of a Zoom window blurred here: https://pasteboard.co/YF2p7Thl0pju.jpg

The output of `yabai -m query --windows | jq '.[] | select(.app == "zoom.us")'`: https://gist.github.com/albertsj1/c4479926fdc46bdf5f9f4a680ccd7de7

and my `.yabairc`: https://gist.github.com/albertsj1/f60496003789921f5a8c6bbc30cddc2f

OSX 13.3.1
2019 Intel 16-inch MacBook Pro

**Comment by cbackas** [comment]
I'm also encountering this on both my macbooks, it seems possibly related to having the borders turned on?

MacOS 13.3
16" M1 Pro/Max MBP

**Comment by albertsj1** [comment]
@cbackas I believe you are correct. It does seem to be caused by having borders turned on, but also while having layer=above set.

This can be tested using the following rule for the calculator app.

1. **The following rule will cause calculator to be blurred and unusable:**
```bash
yabai -m rule --add app="Calculator"  manage=off border=on sticky=on layer=above
```
2. **With the following rule, calculator will be fine:**
```bash
yabai -m rule --add app="Calculator"  manage=off border=off sticky=on layer=above
```

**Comment by cbackas** [comment]
The "layer above" thing is so true. It happens so much on modals like download boxes or "do you wish to save/close" prompts. Its driving me insane as we speak as I attempt to download some tax documents.

**Comment by albertsj1** [comment]
@cbackas Yeah. That drove me nuts as well.  I found out that popups like that do not have titles, so I fixed that with this for Firefox:

```bash
yabai -m rule --add app="^Firefox$" title="^$" manage=off
```

I assume Chrome would be similar.  I primarily use Vivaldi and downloads are in a sidebar of the main window, so it's not an issue.

**Comment by cbackas** [comment]
> Window borders don't work properly on Ventura. Disable them if they are causing trouble in your workflow.

It was working fine on yabai 5.0.3 then after updating to 5.0.4 it started being all broken. I updated to 5.0.5 last night and after turning borders back on they don't seem fine again...

**Comment by koekeishiya** [comment]
They have been broken for all of Ventura. It was never working "fine" for you; it just doesn't exhibit broken behaviour a 100% of the time.

**Comment by koekeishiya** [comment]
Borders have been removed in the latest release (v6.0.0) (#1889) because of multiple issues present in both Ventura and Sonoma.
