### ISSUE TITLE
Ventura 13.4 Beta Compatibility issue, I know beta's aren't supported, no rush

### ISSUE THREAD

**Issue by roni-estein** [koekeishiya/yabai#1733]
I meant to disable the beta track but I hadn't gotten to it. No rush I am aware beta's are not supported. If there is any information that I can put forward that would actually be helpful, please don't hesitate to let me know which commands to run and code to show.

Here is the error displayed on screen when the service attempts to start:

```
Error: Formula `yabai` has not implemented #plist, #service or installed a locatable service file
```

Cheers!

**Comment by koekeishiya** [comment]
Brew services has been replaced with a lunchd integration: #1619 
https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#504---2023-05-01

**Comment by roni-estein** [comment]
Thanks! You are on this before it was even an issue :)

In case these help anyone, I wrapped the re-install process in some bash/zsh functions so I don't have to really look it up.

```bash
yabai:hash-update() { 

	local hashString="$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d ' ' -f 1) $(which yabai) --load-sa"
	sudo rm /private/etc/sudoers.d/yabai
	echo $hashString | sudo tee -a /private/etc/sudoers.d/yabai
	sudo chmod +x /private/etc/sudoers.d/yabai
	
}
```

* regenerates the the sudoers file for you.

```bash
yabai:reinstall () {

	export YABAI_CERT=

	# unload service, causing yabai to terminate immediately f it is running, and stop launching upon login
	yabai --stop-service

	# reinstall yabai
	brew reinstall koekeishiya/formulae/yabai

	#update the hash
	yabai:hash-update

	local updated=(/opt/homebrew/Cellar/yabai/*(/om[1]))
	codesign -fs "${YABAI_CERT:-yabai-cert}" $updated/bin/yabai

	# finally, start yabai
	yabai --start-service
}
```
* this one runs the full install, including the sudoers file. Make sure you originally installed it via the HEAD branch if you want to update it the same way. Hope this saves someone a bit of time. you can paste these in your .zshrc or separate them off in a yabai.shell and then source it from your .zshrc or wherever you keep your aliases.

**Comment by roni-estein** [comment]
@koekeishiya 
you may want to mark this as solved so people read it instead of creating duplicate issues. I should have checked for a way to do that before I closed it.
