### ISSUE TITLE
Space focusing does not work (Ventura 13.3.1(a), yabai v5.0.4)

### ISSUE THREAD

**Issue by partlyjadedyouth** [koekeishiya/yabai#1734]
I upgraded my macOS version to Ventura 13.3.1(a), and yabai to v5.0.4. 

After doing so, I'm having a problem with space focusing. 

All other commands and functionalities are working as usual.

But 'yabai -m space --focus <window>' command throws an error 'cannot focus space due to an error with the scripting-addition' when I type it into the terminal.

I also found out that creating and destroying a space are unable, too.

macOS Ventura 13.3.1 (a)
yabai v5.0.4 (HEAD)
skhd v0.3.7 (HEAD)
2021 M1 Pro 16-inch MacBook Pro

**Comment by Alkindi42** [comment]
Can you try running `sudo yabai --load-sa` in your terminal? I got the error but fixed it after successfully enabling arm64e binaries not signed by Apple (don't forget to reboot your machine).

**Comment by partlyjadedyouth** [comment]
> Can you try running `sudo yabai --load-sa` in your terminal? I got the error but fixed it after successfully enabling arm64e binaries not signed by Apple (don't forget to reboot your machine).

It worked! Appreciate your help :)
