### ISSUE TITLE
`yabai --start-service` could not be installed

### ISSUE THREAD

**Issue by josephmr** [koekeishiya/yabai#1735]
# Issue

When trying to install fresh I run into the following when trying to use the new launchd service:

```
❯ yabai --start-service
yabai: service file '/Users/joseph/Library/LaunchAgents/com.koekeishiya.yabai.plist' is not installed! attempting installation..
yabai: service file '/Users/joseph/Library/LaunchAgents/com.koekeishiya.yabai.plist' could not be installed! abort..
```

# System Info

```
❯ sw_vers
ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68
```

```
❯ yabai --version      
yabai-v5.0.4
```

```
❯ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled
	Boot-arg Restrictions: disabled
	Kernel Integrity Protections: enabled
	Authenticated Root Requirement: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

**Comment by josephmr** [comment]
Resolved by manually creating the `LaunchAgents` directory

**Comment by koekeishiya** [comment]
Fixed in #1728

**Comment by createchange** [comment]
> ## ISSUE
> 
> ```
> ❯ yabai --start-service
> yabai: service file '/Users/zero/Library/LaunchAgents/com.koekeishiya.yabai.plist' is not installed! attempting installation..
> ```
> 
> But
> 
> ```
> ❯ brew services restart yabai
> 
> Error: Formula `yabai` has not implemented #plist, #service or installed a locatable service file
> ```
> 
> And my file '/Users/zero/Library/LaunchAgents/com.koekeishiya.yabai.plist' does exist, and its contents are as follows.
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
>     <key>Label</key>
>     <string>com.koekeishiya.yabai</string>
>     <key>ProgramArguments</key>
>     <array>
>         <string>/usr/local/bin/yabai</string>
>     </array>
>     <key>EnvironmentVariables</key>
>     <dict>
>         <key>PATH</key>
>         <string>/Users/zero/.nvm/versions/node/v12.22.12/bin:/Users/zero/go/bin:/usr/local/opt/libiconv/bin:/Users/zero/.jenv/shims:/Users/zero/.jenv/bin:/usr/local/Cellar/htpdate/1.3.4/sbin/:/usr/local/opt/php@7.2/sbin:/usr/local/opt/php@7.2/bin:/usr/local/opt/bison/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/opt/openssl@3/bin:/Users/zero/anaconda3/bin:/Users/zero/anaconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/go/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Fortify/Fortify_SCA_and_Apps_22.1.0/bin:/usr/local/bin</string>
>     </dict>
>     <key>RunAtLoad</key>
>     <true/>
>     <key>KeepAlive</key>
>     <dict>
>         <key>SuccessfulExit</key>
>  	     <false/>
>  	     <key>Crashed</key>
>  	     <true/>
>     </dict>
>     <key>StandardOutPath</key>
>     <string>/tmp/yabai_zero.out.log</string>
>     <key>StandardErrorPath</key>
>     <string>/tmp/yabai_zero.err.log</string>
>     <key>ProcessType</key>
>     <string>Interactive</string>
>     <key>Nice</key>
>     <integer>-20</integer>
> </dict>
> </plist>
> ```
> 
> ## System Info
> 
> ```
> ❯ sw_vers
> ProductName:            macOS
> ProductVersion:         13.4
> BuildVersion:           22F66
> ```
> 
> ```
> ❯ yabai --version
> yabai-v5.0.6
> ```

My personal laptop had no issues, but my work laptop had the same problem as you. I checked /Users/me/Library/LaunchAgents on both, and discovered my work computer had a file for that path, rather than a directory. I removed the file, created a directory, and then it worked.

**Comment by ncasdpo** [comment]
Solution for me was to `chmod 700 /Users/<username>/library/LaunchAgentscom.koekeishiya.yabai.plist`
