### ISSUE TITLE
Installing via Homebrew

### ISSUE THREAD

**Issue by Galvo87** [koekeishiya/yabai#1737]
When installing on Osx 12.5.1 I get `Error: Formula `yabai` has not implemented #plist, #service or installed a locatable service file`.

`Brew doctor` doesn't return anything suspicious.
Any hint?

**Comment by 24unix** [comment]
Brew support has been stripped.
Use yabai --start-service instead.

**Comment by Galvo87** [comment]
`yabai --start-service` results in `Load failed: 5: Input/output error`

**Comment by Galvo87** [comment]
Ok, one must do the following:

```
launchctl unload /path/to/plist
launchctl load /path/to/plist
```

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/issues/1731#issuecomment-1535305741
