### ISSUE TITLE
Error: Formula `yabai` has not implemented #plist, #service or installed a locatable service file

### ISSUE THREAD

**Issue by j-vasanth** [koekeishiya/yabai#1738]
Hello,
I am trying to install yabai following the instructions on an m2 macbook pro max but I am getting the error
`Error: Formula `yabai` has not implemented #plist, #service or installed a locatable service file`
I am able to install other software packages with homebrew. I recollect getting the same as a warning when I installed on my M1 but the installation went through. However it is failing  with this errors on my M2. Would appreciate any help here.
Thanks
Jai

**Comment by piersolenski** [comment]
Also getting this on my M1 after updating to v5.0.4

**Comment by aarishCWT** [comment]
Having same issue on M1 pro.

**Comment by DaveMcMahon** [comment]
Experiencing the same issue on v5.0.4

**Comment by ejazahm3d** [comment]
Same issue on M1 pro.

**Comment by ejazahm3d** [comment]
Alright. What worked for me was to run 
`yabai --start-service`
And then restart. 
Do the same steps with skhd.

**Comment by vebbis321** [comment]
What worked for me was checking the Accessibility in Security and Privacy. There was a new option to give yabai and skhd access. Those had to be checked to make it work, and I also unchecked the old ones.

**Comment by j-vasanth** [comment]
> What worked for me was to run `yabai --start-service` And then restart. Do the same steps with skhd.

This worked for me too, but I first had to create a  LaunchAgents directory under /Users/username/Library/

Is not 
brew services start yabai the corrct way to do this?

**Comment by koekeishiya** [comment]
Brew services has been removed: #1619 

The installation instructions in the wiki was updated to reflect this.
The changelog mentions new commands to manage service / launchd
In the caveat section printed after installing yabai through brew, the instructions have changed.

There are also countless issues here on github regarding this topic. Please do a search before creating a new issue.

**Comment by lmBored** [comment]
> > What worked for me was to run `yabai --start-service` And then restart. Do the same steps with skhd.
> 
> This worked for me too, but I first had to create a LaunchAgents directory under /Users/username/Library/
> 
> Is not brew services start yabai the corrct way to do 

Hi @j-vasanth, how do you create a LaunchAgents under /users/username/library?

**Comment by koekeishiya** [comment]
This was fixed in v5.0.5: #1728

**Comment by duhd1993** [comment]
> 



> The installation instructions in the wiki was updated to reflect this.

the wiki still says 
>Starting with `brew services start yabai` will prompt the user to allow yabai accessibility permissions.`

it needs to be updated.

**Comment by elmehdiabdi-src** [comment]
This is happen to me when i upgrade yebai using commend `brew upgrade yabai`

i fix it by delete the old version in accecibilties and select the new version.

![Screen Shot 2023-09-10 at 15 00 18](https://github.com/koekeishiya/yabai/assets/55539600/f0f24627-26c2-4db9-8637-89bc0483abd6)

**Comment by lmBored** [comment]
> This is happen to me when i upgrade yabai using command `brew upgrade yabai`
> 
> i fix it by delete the old version in accecibilties and select the new version.
> 
> ![Screen Shot 2023-09-10 at 15 00 18](https://user-images.githubusercontent.com/55539600/266840546-f0f24627-26c2-4db9-8637-89bc0483abd6.png)

How do you know the one without icon is older version of yabai? And do you know how to remove it from accessibility?

**Comment by elmehdiabdi-src** [comment]
> > This is happen to me when i upgrade yabai using command `brew upgrade yabai`
> > i fix it by delete the old version in accecibilties and select the new version.
> > ![Screen Shot 2023-09-10 at 15 00 18](https://user-images.githubusercontent.com/55539600/266840546-f0f24627-26c2-4db9-8637-89bc0483abd6.png)
> 
> How do you know the one without icon is older version of yabai? And do you know how to remove it from accessibility?

i remove the yabai without icon.   and i interacte and restart yabai using this commande `yabai --restart-service` works fine

**Comment by Alohaoh** [comment]
> Also getting this on my M1 after updating to v5.0.4

Same here, got an error

**Comment by lmBored** [comment]
I solved this by kill all `loginwindow`. You can do this by:
```
sudo killall loginwindow
```

**Comment by paolomainardi** [comment]
@lmBored funny but stupid.

**Comment by pencilcheck** [comment]
after changing my shell and everything to m1 arch, yabai --start-service is not working, and I get no prompt on accessibility permission nor anything.

**Comment by HaxagonusD** [comment]
> I solved this by kill all `loginwindow`. You can do this by:
> 
> ```
> sudo killall loginwindow
> ```

This worked for me. I didn't run the command but I logged out manually out of my mac and logged back in. Interesting. I wonder why that happens. Yabai was working fine for me but the skhd shortcuts weren't working.

**Comment by DATEx2** [comment]
> > I solved this by kill all `loginwindow`. You can do this by:
> > ```
> > sudo killall loginwindow
> > ```
> 
> This worked for me. I didn't run the command but I logged out manually out of my mac and logged back in. Interesting. I wonder why that happens. Yabai was working fine for me but the skhd shortcuts weren't working.

This is soo dumb. This kills all the UI apps and logs you out. When logging back in, same error. It does NOTHING - just dumb answer

**Comment by DATEx2** [comment]
Why did you close this issue - it pretty much throws the same error in 2024 and latest Macbook pro OS

**Comment by idogada-akamai** [comment]
I am also still encountering this issue. What's the solution here?
I tried everything in thread, and nothing worked

**Comment by userredbirbhah2** [comment]
This is still a problem.

**Comment by tomekju** [comment]
These steps worked for me:

Mission Control: System Settings → Desktop & Dock → Displays have separate Spaces = ON → Log off  → Delete Yabai from accessibility → `yabai --restart-service` → allow in accessibility again
