### ISSUE TITLE
Yabai does not respect split type setting

### ISSUE THREAD

**Issue by oransterf** [koekeishiya/yabai#1745]
Hello, 

Thanks for the great software!  

I have an issue (I am using v5.0.4) where setting the following:

```
yabai -m config split_type horizontal
```

Still ends up spawning new windows on the bottom instead of the right.
Is there a way to fix it?

Thanks!

**Comment by koekeishiya** [comment]
`horizontal` makes it split across the x-axis, which means the window either goes on the top or the bottom. You want `vertical`.

**Comment by oransterf** [comment]
Indeed, thank you

**Comment by BigBrotherJu** [comment]
@koekeishiya But with split_type set to vertical in config file, windows still sometimes have the split type of horizontal.

My yabai is 7.1.0. Window status after opening a new window:

```
$ yabai -m query --windows --space | jq '.[]."split-type"' 
"horizontal"
"horizontal"
"vertical"
"horizontal"
"vertical"
"vertical"
"vertical"
```
