### ISSUE TITLE
"yabai -m window --focus stack.first" doesn't return error when there is no stack

### ISSUE THREAD

**Issue by mil-ad** [koekeishiya/yabai#1748]
I'm trying to define a keybinding (hyper + down key) that changes focus to the north window when there are no stacks and to the next window when in stacked mode:

```
rhyper - down : yabai -m window --focus stack.next || yabai -m window --focus stack.first || yabai -m window --focus south
```

this almost works. The problem is that when there is no stacks in my space `yabai -m window --focus stack.next` correctly gives an error code causing the next command to run but `yabai -m window --focus stack.first` happily runs with no errors even though there are no stacks. Is this a big?

**Comment by koekeishiya** [comment]
Fixed on master.
