### ISSUE TITLE
[bug] Load failed: 5: Input/output error

### ISSUE THREAD

**Issue by believerd** [koekeishiya/yabai#1749]
The size of plist file is not enough which leads to incomplete text.
Same for the skhd.

**Comment by koekeishiya** [comment]
Can you post the contents of the file that gets written?

**Comment by believerd** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.koekeishiya.yabai</string>
    <key>ProgramArguments</key>
    <array>
        <string>/opt/homebrew/bin/yabai</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/opt/openjdk@17/bin:/opt/homebrew/opt/zstd/bin ...
```
It looks something like this, a long PATH string with no closing tag `</string>` .
The file size is 4kb which I believe is fixed, so when PATH hits the limit, everything else is gone.(see populate_plist in header file) I got this working by shortening the PATH and edit it manually.

**Comment by koekeishiya** [comment]
Right, that is one heck of a path then.
