### ISSUE TITLE
Query current padding values

### ISSUE THREAD

**Issue by cbackas** [koekeishiya/yabai#1754]
I've noticed that when the padding is set it causes all my windows to flash a little bit even though they're already at the size/padding they need to be at. So, is it possible to query what settings are currently set for a space? I'm doing some scripting and since I'm querying the spaces already it would be nice if current padding for the space was included so my script could decide whether or not its going to set the padding.

**Comment by koekeishiya** [comment]
> yabai -m config [--space <SPACE_SEL>] <space setting>
Get or set the value of <space setting>.


Sample: `yabai -m config --space 1 top_padding`

**Comment by cbackas** [comment]
@koekeishiya Oh cool beans that does the trick, thanks
