### ISSUE TITLE
WIndow can not be re-managed by bsp space

### ISSUE THREAD

**Issue by chivalryq** [koekeishiya/yabai#1762]
In my configuration, I use code below to switch my terminal to `float` and in the center of space. 
```
alt - u : yabai -m window --toggle float;\
          yabai -m window --grid 6:6:1:1:4:4
```

But I can not use this again to cancel the float state of this window. And if I create another window of this terminal, it is also floating. Is this a bug or is there something I missed? Should I use another command to restore it?
<img width="2434" alt="image" src="https://github.com/koekeishiya/yabai/assets/47812250/f4d0f475-425f-4776-8cd1-6ad96abdb813">

**Comment by koekeishiya** [comment]
I use the following and it works just fine: `alt - t : yabai -m window --toggle float --grid 4:4:1:1:2:2`

![toggle float](https://github.com/koekeishiya/yabai/assets/6175959/02327953-8171-439e-80d3-e4e5f4cf85a8)

**Comment by chivalryq** [comment]
I'm still encontering this problem. Here's some problem:
1. Seems only iTerm is not correctly tiled. `alt - t` works great for any other window.
2. When iTerm is not tiled, it is not `floating` when inspect this window:

<img width="2560" alt="image" src="https://github.com/koekeishiya/yabai/assets/47812250/f62385c1-db9c-4c49-b3d8-faa70275264e">

3. Yabai version:
```
yabai -v
yabai-v5.0.6
```

**Comment by koekeishiya** [comment]
The iterm window is marked as `sticky`, which makes it appear on all spaces, which also implicitly makes it behave as a floating window, because it would make sense for it to be tiled (as it is not guaranteed to be able to be tiled with the same dimensions across various spaces).

**Comment by chivalryq** [comment]
Thanks for the quick responding and yes it is caused by `sticky`. 🙇
