### ISSUE TITLE
Focus issue on multiscreen setup (and multiple windows from same app)

### ISSUE THREAD

**Issue by thomaschrstnsn** [koekeishiya/yabai#1764]
When using `yabai -m window --focus` and targeting a window on another screen, the window only gets "partial" focus. It can be resolved by clicking on the window using the pointer.

By "partial" focus, I mean that it receives keyboard events but the window is not fully focused. 
As such a "wezterm" shows the "unfocused" caret, but clicking the window gives it "full" focus.

Other examples is yabai it self, which does not respond correctly to `yabai -m window --focus west/east` etc, after focusing a window on another space, responding with `could not locate westward managed window`. This seems to be mostly the case when there are multiple windows from the same app on the target screen.

This has broken somewhere between v5.0.2 and 4.0.1 (it worked on the 4)

Using macOS 13.4 without scripting additions on M1 MacBook Air.

Apologies if this was fixed after 5.0.2 (but scouring the changelog it seems like it has not been addressed).

Thanks for an awesome piece of software!

**Comment by koekeishiya** [comment]
Nothing has changed in how yabai does window focusing since the very beginning (https://github.com/koekeishiya/yabai/issues/102 in version [1.0.6](https://github.com/koekeishiya/yabai/compare/v1.0.5...v1.0.6) - 2019-07-09); might be an internal macOS change in Ventura.

**Comment by koekeishiya** [comment]
Hm well that seems rather strange then; maybe something that I believe to be unrelated has somehow borked something.
If you can pinpoint the first release where it breaks, that would allow me to get to a fix faster, as you already seem to be able to reproduce the problem with relative ease.

For now, here is a complete diff of changes between v4.0.1 and v5.0.2: https://github.com/koekeishiya/yabai/compare/v4.0.1...v5.0.2

Most commits should also contain the respective issue that prompted the change.
Commits with no issue tag are cleanups *that in theory should not alter any functionality*

**Comment by thomaschrstnsn** [comment]
Nevermind. I did the due diligence an upgraded to 5.0.6, and it seems to be fixed!

**Comment by koekeishiya** [comment]
Right, I believe the bug was #1551 and the fix came in v5.0.3.
