### ISSUE TITLE
[QUESTION] Is there a command that makes window --space next/prev display aware?

### ISSUE THREAD

**Issue by ConstantinCezarBegu** [koekeishiya/yabai#1765]
I am setting up yabai so that I can move a application window between spaces.

I have this so far: 
shift + alt + ctrl - 3 : yabai -m window --space next; osascript -e 'tell application "System Events" to key code 124 using control down';

The important part is yabai -m window --space next. osascript is to witch to next space without disabling sip.

This works well when I only use one display but since I have multiple displays this will break.

Let's pretend I have display 1 (has space #1), 2(has space #2), 3(has space #3) each have one space. If I do --space next/prev then it will send the window to the display which has that space.

I would like that when if a window is in a display swap would not send the window to another display.

**Comment by ConstantinCezarBegu** [comment]
I could create a script to get the display info and then based on my requirement switch. 
I am still hoping that this is coming out of the box. If not I could create a PR to add it. I am just curious to see what  others say.

**Comment by koekeishiya** [comment]
Selectors work in a consistent matter across all the domains where they are used so I am not particularly interested in such a change.

Just use the following for `next space`: `if [[ $(yabai -m query --spaces --display | jq '.[-1]."has-focus"') == "false" ]]; then yabai -m window --space next && yabai -m space --focus next; fi` and this one for `prev space`: if [[ $(yabai -m query --spaces --display | jq '.[0]."has-focus"') == "false" ]]; then yabai -m window --space prev && yabai -m space --focus prev; fi

**Comment by ConstantinCezarBegu** [comment]
Thank you for the explanation.

I will create a bash file then but will use the commands provided. This saves me time thank you!

**Comment by koekeishiya** [comment]
you don't need a bash file though, that one-liner does the entire thing. Just replace the `space --focus` part with your osascript one.

**Comment by ConstantinCezarBegu** [comment]
Thank you.

**Comment by koekeishiya** [comment]
I am fairly certain that you don't even need the osascript. The following one-liner should do the trick:

`shift + alt + ctrl - 3 : if [[ $(yabai -m query --spaces --display | jq '.[-1]."has-focus"') == "false" ]]; then yabai -m window --space next --focus; fi`

**Comment by stroiman** [comment]
If I understand this correctly, there is a reasonably simple way, if you have "When switching ... switch to a Space with open windows ..." enabled in preferences

In my skhd, I have setup <key>cmd</key>+<key>shift</key>-<key>1</key> to move to space 1. After moving, the window doesn't have focus, which the `--focus recent` fixes.

```sh
shift + cmd - 1 : yabai -m window --space  1; yabai -m window --focus recent
# ... repeated for all configured spaces 
```

This doesn't switch space by itself, but that's what the system setting can do for you:

<img width="473" alt="image" src="https://github.com/user-attachments/assets/a3705bcb-68ef-4e35-b04e-7a6acb91c3c0">

And it does seem to work as desired when the same application have multiple windows open in multiple spaces. It does switch to the space where the window you moved just ended up.
