### ISSUE TITLE
VSCode modals make the VSCode window get stuck topmost

### ISSUE THREAD

**Issue by cbackas** [koekeishiya/yabai#1768]
I've been using stacks for a lil over a week now and I really like them. Being able to have all my vscode projects open at the same time in 1 space and cycle through them with keyboard shortcuts is great. For context, the space is in BSP mode but it has a stack created inside it. It's not in stack layout mode, as afaik that wouldn't allow me to still have a browser window next to my stack in 1 space.

Annoyingly though, I've noticed that occasionally (several times a day) I'll go to cycle between stacks and whatever VSCode window was at the top of the stack will stay on top (even though I can see that window focus is cycling between windows). To fix this I've been floating then unfloating the window and then putting it back in the stack. I've had to do this while im trying to show coworkers stuff too many times already in the last week so I've been trying to pay attention to what could be causing this...

Well it seems when VSCode opens one of its little "error" or "confirm" modals (they happen for a variety of things) then that window from that point on is stuck topmost in front of the rest of the stack.
<img width="381" alt="image" src="https://github.com/koekeishiya/yabai/assets/4987637/5c113bd3-8fe6-4885-9dd9-2632f2b6477b">

When do `yabai -m query --windows` there doesn't seem to be any additional windows created while this modal is visible. Here's the result for the window thats currently stuck topmost: (note, `has-focus` changes to false if i cycle through to another item in the stack, but the window just stays on top)
```json
{
        "id":101963,
        "pid":3503,
        "app":"Code",
        "title":"Jenkinsfile — multipipeline-testing",
        "frame":{
                "x":5.0000,
                "y":49.0000,
                "w":2046.0000,
                "h":1275.0000
        },
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "display":1,
        "space":3,
        "level":0,
        "opacity":1.0000,
        "split-type":"none",
        "split-child":"second_child",
        "stack-index":4,
        "can-move":true,
        "can-resize":true,
        "has-focus":true,
        "has-shadow":false,
        "has-border":false,
        "has-parent-zoom":false,
        "has-fullscreen-zoom":false,
        "is-native-fullscreen":false,
        "is-visible":true,
        "is-minimized":false,
        "is-hidden":false,
        "is-floating":false,
        "is-sticky":false,
        "is-topmost":false,
        "is-grabbed":false
}
```

Another discovery is that a code window will be seemingly permanently tainted by this until its unfloated and floated. As in, if I have an unstacked (but still tiled) vscode window and I make the modal show (and dismiss it) then when I add the window to a stack it will immediately be broken. Floating and unfloating is the only fix I see so far.

Does this seem like something I can script/settings my way out of or does this seem like a larger (and much more annoying) issue that would take digging into? Hopefully I've provided enough detail, let me know if I should share anything else.

MacOS 13.5
Yabai 5.0.5

**Comment by cbackas** [comment]
I've now realized that I can't replicate this on my personal macbook.... So now I'm trying to determine the difference between my work and personal macbooks (I set them up the same so I'm not sure).

**Comment by cbackas** [comment]
After closing a bunch of programs and whatnot trying to find the cause I eventually noticed my personal mac (which doesnt have this problem) is on the macos 13.5 beta and broken mac was on 13.4. I updated my work mac to the beta and now the stacks work fine. Hopefully this doesnt undo itself for some reason.

**Comment by koekeishiya** [comment]
Might be same issue as #1704
