### ISSUE TITLE
Space Focus jumping to displays

### ISSUE THREAD

**Issue by jin-ahn** [koekeishiya/yabai#1771]
### Discussed in https://github.com/koekeishiya/yabai/discussions/1673

<div type='discussions-op-text'>

<sup>Originally posted by **jin-ahn** March 20, 2023</sup>
I have multiple displays and mulitple spaces. I have a short to just move between spaces as shown below. What I want/expect to happen is that when I reached my last space, I would be unable to "--focus next" since there is not a next and vice versa for prev. However what I am noticing that what ends up happen when I get to my last space and use the shortcut to focus next, it will jump focus to my other display. I'm assuming this is happening because yabai sees the space on my other display as the "next" space. 

**_TLDR_**
**Is there way a to configure it where  "-m space --focus next" only concerns itself with the spaces assigned to the current display rather than spaces across all displays?**

shift + alt - u: yabai -m space --focus next 
shift + alt - y: yabai -m space --focus prev 
</div>

**Comment by koekeishiya** [comment]
Added to the wiki

https://github.com/koekeishiya/yabai/wiki/Tips-and-tricks#constrain-space-focus-to-current-display-with-optional-cycling
