### ISSUE TITLE
Yabai causes system lockup following every `brew upgrade`

### ISSUE THREAD

**Issue by naoey** [koekeishiya/yabai#1773]
Ever since yabai was updated to drop the Homebrew service in favour of the launchd service, every time yabai is updated through `brew upgrade` it causes my entire system to become non-responsive until after a hard reset. Since a new binary is registered under Security & Privacy in System Settings after the update, I get a prompt to grant accessibility permissions and that is the point the whole system just locks up. So far I haven't been able to get around this in any other way except to hard reset (hold power button) and it works as normal after rebooting.

I'm seeing identical behaviour on my work M1 MacBook Pro as well as my personal Intel MacBook Pro. The mouse cursor can still be moved but practically everything else is non-responsive. I've been seeing this consistently for at least the last 3 updates so there is probably something going wrong.

I'm not sure what I can do to provide more information about this, but if there's anything I can try and report back do let me know.

**Comment by koekeishiya** [comment]
The macOS permissions model works the way it does;  there is a reason why the upgrade instructions tell you to stop yabai before upgrading..

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#updating-to-the-latest-release

**Comment by naoey** [comment]
Ah, seems I've never paid attention to that part as prior to the launchd change upgrading worked fine without manually stopping yabai. Thanks for the pointer, sorry for the oversight.
