### ISSUE TITLE
Prevent Yabai from Starting Automatically Upon Login

### ISSUE THREAD

**Issue by EmperorEntropy** [koekeishiya/yabai#1774]
Hello,

How do I prevent yabai and skhd from starting automatically when I login to my computer? I disabled yabai by running `yabai --stop-service`, but when I shutdown and re-login to my computer, yabai is automatically enabled. I tried unchecking yabai and skhd in "Allow in the Background" in Settings, but it still doesn't work. I don't use yabai all the time, so yabai being auto enabled upon startup is quite annoying.

Thank you!

**Comment by 24unix** [comment]
Could you elaborate on your use case when you want to use yabai and when not?

First thought: Start yabai with an "empty" config, float for all spaces, and make a hotkey for skhd to activate or deactivate the features you want.

**Comment by EmperorEntropy** [comment]
I use yabai for academical reasons to boost my productivity. Otherwise, I tend to not use it as it becomes distracting. I already have a bash script that enables yabai by running `yabai --start-service` and disables it with `yabai --stop-service`. It does work, but even when I run `yabai --stop-service` beforehand, yabai is automatically enabled when I log back into my computer, which messes up my windows.

**Comment by 24unix** [comment]
Make float the default, then it won't mess your windows.

**Comment by koekeishiya** [comment]
Sounds like a bug then, anyway just uninstall the service (`yabai --uninstall-service`) if you don't want it to run automatically on startup.

**Comment by EmperorEntropy** [comment]
Thanks for the quick response! I just followed your advice; however, it automatically reinstalls the service when it couldn't detect it. Is there another way to start and stop yabai from the command line without using the service?

**Comment by koekeishiya** [comment]
Just use the regular functionality of the shell. `yabai` will run it in the current terminal session, `yabai &` to run it in the background, `yabai &> /dev/null &` to silence stdout/stderr and running it as a background job. To stop just `pkill yabai` I guess.

**Comment by EmperorEntropy** [comment]
Thank you! Using those commands, I was able to start and stop yabai whenever I wanted. I uninstalled the services, so I'm pretty sure that I won't run into the bug where yabai started on its own after login. I'll let you know if I do. For now, I have a working yabai setup that fits my needs. Thanks again!
