### ISSUE TITLE
Yabai not starting

### ISSUE THREAD

**Issue by Tengs-Penkwe** [koekeishiya/yabai#1776]
Hello, I just followed wiki, installed yabai, rebooted,  but it still doesn't respond, Nothing happens after `yabai --start-service`, could anyone give me some suggestions ?

## Service
```
> brew services start yabai
Error: Formula `yabai` has not implemented #plist, #service or installed a locatable service file
```
 `yabai --start-service` give no response

there are `com.koekeishiya.skhd.plist` and `com.koekeishiya.yabai.plist` in `~/Library/LaunchAgents`

```
> launchctl list | grep com.koekeishiya
PID	Status	Label
661	0	com.koekeishiya.skhd
-	0	com.koekeishiya.yabai
```

## System Integrity Protection
```
> csrutil status              
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled
	Boot-arg Restrictions: disabled
	Kernel Integrity Protections: enabled
	Authenticated Root Requirement: enabled
```

## OS Version
macOS Ventura 13.4
```
> uname -a              
Darwin Tengs-MacBook-Air.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103 arm64
```

## Yabai Version
```
> yabai --version
yabai-v5.0.6
```

## Log files
```
> cat /tmp/yabai_tengs.err.log
yabai: 'display has separate spaces' is disabled! abort..
```
`/tmp/yabai_tengs.out.log` is empty

**Comment by Tengs-Penkwe** [comment]
choose Apple menu  > System Settings, click Desktop & Dock in the sidebar, then scroll down on the right and make sure that “Displays have separate Spaces” is turned on

**Comment by khanhvu207** [comment]
> choose Apple menu  > System Settings, click Desktop & Dock in the sidebar, then scroll down on the right and make sure that “Displays have separate Spaces” is turned on

This actually solved my problem! Thanks
