### ISSUE TITLE
Unresponsive when program asks for permissions

### ISSUE THREAD

**Issue by ReptoxX** [koekeishiya/yabai#1778]
When yabai is running, whenever a programm asks for permissions (webcam for example) the mouse and keyboard becomes unresponsive.
It feels like i can't focus any program anymore. Sometimes it even crashes when trying alt + tab into other programs. 

I currently have a restart shortcut in skhd. When yabai is not running, i can click on those dialogs and everything works as usual.

**Comment by koekeishiya** [comment]
Should be resolved in latest version.
