### ISSUE TITLE
make child windows app floating

### ISSUE THREAD

**Issue by mmngreco** [koekeishiya/yabai#1779]
Hey, 

Thank your for this awesome project (I'm a big fan of i3 in linux and this fill the gap).

Here is my issue:
![image](https://github.com/koekeishiya/yabai/assets/6231413/662d2297-9abc-4bdb-b5f7-53cb9fcc1cc2)

I want to make popups and dialog child windows floating to avoid the above behaviour.

Any idea of how to get it done? 

Thanks in advance!

**Comment by kabeersvohra** [comment]
@koekeishiya I have found quite often that these windows have `can-resize` to be false, I think a good rule would be if the window is unable to be resized then almost certainly it is a popup that should be floated. However in terms of rules, it seems to not be possible to add a rule based upon this, only based upon the app name? Is there some way we can achieve this? Thanks

**Comment by kabeersvohra** [comment]
I take that back, I found another issue on this, and this solved the issue for me (as long as the window is not resizable)

https://github.com/koekeishiya/yabai/issues/1317#issuecomment-1669185618

**Comment by CrazyCatZhang** [comment]
> I take that back, I found another issue on this, and this solved the issue for me (as long as the window is not resizable)
> 
> [#1317 (comment)](https://github.com/koekeishiya/yabai/issues/1317#issuecomment-1669185618)

I tried it, but it didn't work.
