### ISSUE TITLE
Recognise windows that are in native-fullscreen when yabai starts

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#178]
### Bug report

Windows that are in native-fullscreen when yabai starts are currently not recognised at all.

**Comment by koekeishiya** [comment]
This used to work fine. Probably something to do with the AXUnknown change.

**Comment by koekeishiya** [comment]
Fixed again. This is working fine in 1.1.2 but was broken on master, thus, not adding this to the changelog and whatever.
