### ISSUE TITLE
Rule for if display is empty?

### ISSUE THREAD

**Issue by barth1243** [koekeishiya/yabai#1780]
Is it possible to create a rule that if display #1 of 2 is empty, that the "next" app I open will automatically open (and focus) on display #1? Maybe another option is a rule that defaults to opening all apps on display #1 no matter what? I'd need help with the syntax there as well, and I'm also unsure if this means that I can't force an application to stay on display 2 if desired (I have the auto-balance setting on). 

I have a two display setup that has a main large screen with my laptop open to the side for calendar/to-dos always running. Right now if I close everything on my main display, I end up with mac OS "focused" on the to-do list and when I open a new app, it opens on the side display.

Sorry if this is not the correct place for these kinds of questions. Happy to close and re-post in the appropriate place if directed.

**Comment by koekeishiya** [comment]
I don't have time to go into details, but you should be able to do something like this using the signal system: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#signal

Look into the `application_launched` signal if you are interested in target applications, or the `window_created` signal if you want to do this for *every window* that is created.
