### ISSUE TITLE
Disabled SIP and installed scripting addition, but still getting error

### ISSUE THREAD

**Issue by farzadmf** [koekeishiya/yabai#1782]
So, I finally decied to give SIP and scripting addition a shot (main driver: to be able to work with spaces).

I disabled SIP with this command [from the Wiki](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection)
```
csrutil disable --with kext --with dtrace --with nvram --with basesystem
```

First question: when running this, it warns me about:
```
requesting an unsupported configuration. This is likely to break in the future and leave your machine in an unknown state.
```

which is scary, and I thin it implies that there's the possibility of me updating the OS and my Mac dying and not be usable, is that the case?

---

Other than that, with SIP being disabled, I followed [instructions from the Wiki](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition) to install scripting additions:
- Added the `sudoer` file
- Updated `yabairc` with the lines

But when I run a space-focus command; e.g. `yabai -m space --focus 2`, I get:
```
cannot focus space due to an error with the scripting-addition.
```

which is the exact error I get before disabling SIP and other steps.

I tried running `sudo yabai --install-sa` and the command runs, but I don't think anything happens because I still get the same error.

It goes without saying that I have restarted yabai using `yabai --restart-service` multiple times, but nothing changed

**Comment by koekeishiya** [comment]
If you followed the wiki instructions precisely as written, it should work.

Which macOS version are you on?
Intel or Apple Silicon processor?

Output of `nvram -p | grep "boot-args"`
Output of `sudo yabai --load-sa`

**Comment by farzadmf** [comment]
Hey @koekeishiya , thank you for your reply and sorry for the late one on my side

So, not sure what happened last time, but after following the instructions "precisely" as you mentioned (😉 ), things seem to be working now.

I think the issue that I had was that I've aliased `sudo` to `sudo -E` and that was causing issues.

I have a question though; pretty sure it's discussed in issues, but wanted to have an up-to-date answer 😛, if possible, please:

By _partially_ disabling SIP, what exactly am I risking? What can happen? Is there a way for  me to be vigilant, or things are out of my control if I have it disabled?

**Comment by koekeishiya** [comment]
> By partially disabling SIP, what exactly am I risking? What can happen? Is there a way for me to be vigilant, or things are out of my control if I have it disabled?

Well let us stop for a moment and pretend that we are malicious actors. Do you spend tons of effort (time and resources) to create malware that can target a very very small percentage of users that chose to disable certain parts of SIP (likely less than 1% of total users, lets be honest here), or do you prioritize other strategies that are able to target the entire Apple/Mac userbase?

**Comment by farzadmf** [comment]
> > By partially disabling SIP, what exactly am I risking? What can happen? Is there a way for me to be vigilant, or things are out of my control if I have it disabled?
> 
> Well let us stop for a moment and pretend that we are malicious actors. Do you spend tons of effort (time and resources) to create malware that can target a very very small percentage of users that chose to disable certain parts of SIP (likely less than 1% of total users, lets be honest here), or do you prioritize other strategies that are able to target the entire Apple/Mac userbase?

Totally valid points, and I completely agree, but you know, I may be a bit too cautioius 😛

But, being able to no-delay switching to spaces is, OMG, a Godsend!

So, I wanted to know the details and compare pros/cons and compromises that is being made, and see how I can be vigilant (I _really_ want to keep the scripting additions 😆)
