### ISSUE TITLE
Apps open on incorrect display

### ISSUE THREAD

**Issue by yasasa** [koekeishiya/yabai#1783]
Not sure what the issue is exactly, but I've been noticing at least with Firefox that it keeps opening on the main display even when i have focus on the external display. If I move the app to the second display, afterwards all new windows open only in the second display even when the main display is in focus. Running on Ventura.

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc

> window_origin_display [default|focused|cursor]
>>Specify which display a newly created window should be managed in.
>>>default: The display in which the window is created (standard macOS behaviour).
>>>focused: The display that has focus when the window is created.
>>>cursor: The display that currently holds the mouse cursor.

**Comment by yasasa** [comment]
Oh wow, can't believe I missed that! My bad!
