### ISSUE TITLE
Examples in action

### ISSUE THREAD

**Issue by Enapiuz** [koekeishiya/yabai#1788]
Hello!

Shout out to anyone who is using yabai, please, make some bunch of screenshots and (most important) some videos of how it actually works and add it to Readme.
Based on the text it seems to be a great tool, but no text can describe a window manager.

Cheers

**Comment by koekeishiya** [comment]
I'm sure you can find a few videos showcasing features on Youtube.
For screenshots there should be quite a few on various subreddits associated with desktop customization.
