### ISSUE TITLE
Rule that Identifies Chrome Profile?

### ISSUE THREAD

**Issue by dylancaponi** [koekeishiya/yabai#1790]
Is there a way to identify what profile a Chrome window is using?

This seems to identify chrome windows:
`yabai -m rule --add app="^Google Chrome$" space=2`

But now I want to have different Chrome profile windows to go to different spaces.
Eg.
`yabai -m rule --add app="^Google Chrome$" <work profile window> space=2`
`yabai -m rule --add app="^Google Chrome$" <personal profile window> space=3`

**Comment by noncog** [comment]
On macOS, applications are "bundles" of all information required to run it, which you can freely modify. Additionally, you can use AppleScript to do all kinds of things and save the script as an application. Together or separate, these can be used to create two different applications with unique names that you can identify in Yabai. There are several gotchas and "wrong" ways of implementing this, but this post should provide you with enough of a starting point and multiple solutions: https://apple.stackexchange.com/questions/389529/use-apple-script-to-open-chrome-with-specific-profile

Good luck! If you get it working report back for others to use too.

**Comment by gargantuanprism** [comment]
not sure if you fixed this already but i just made this work by using "Window --> Name Window" from the Chrome menu.

**Comment by brothell** [comment]
> not sure if you fixed this already but i just made this work by using "Window --> Name Window" from the Chrome menu.

Can elaborate more how you use it? Thanks

**Comment by brothell** [comment]
> When you open chrome, there is some menu in top bar, and that includes Window --> Name Window like he said

I get that, but the name is not persistent, after you close window. Or do i miss something? :)
