### ISSUE TITLE
After upgrade to MacOS 3.14.1 "manage=off" rules stopped working

### ISSUE THREAD

**Issue by clader** [koekeishiya/yabai#1793]
I have several rules in my yabairc similar to:
```
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Apache Directory Studio$" manage=off
```
So those applications windows do not get added to the tile layout when launched

However after upgrading MacOS to 13.4.1, all of these stopped working, and these app windows when launched are getting managed/added to the tile layout.

When this started happening I was on Yabai v5.0.4, and so I upgraded to 5.0.6 hoping that would fix, but still happening.....

**Comment by koekeishiya** [comment]
Unable to reproduce issue on lastest version.
