### ISSUE TITLE
Would be nice to have command to change split_type for currently focused window

### ISSUE THREAD

**Issue by samuelbryant** [koekeishiya/yabai#1794]
In `i3`, I would often control where new windows are placed by setting the current window split type to either horizontal or vertical, then creating the new window.

I saw that #1423 added the ability to change the split type of newly created windows. But ideally I could change the split type of the current window.

I think `toggle` accomplishes this, but I'd prefer a dedicated way to set it to vertical or horizontal since I'm not always aware of the current "split_type" state.

**Comment by koekeishiya** [comment]
One-liner to set split of current window to `vertical`:
```
if [[ $(yabai -m query --windows --window | jq -r '."split-type"') == "horizontal" ]]; then yabai -m window --toggle split; fi
```

One-liner to set split of current window to `horizontal`:
```
if [[ $(yabai -m query --windows --window | jq -r '."split-type"') == "horizontal" ]]; then yabai -m window --toggle split; fi
```

For setting a specific split type before creating a window, such as in `i3`: `yabai -m config split_type vertical` or `yabai -m config split_type horizontal`.
