### ISSUE TITLE
Disabled SIP but Yabai act as if SIP is still enabled. 

### ISSUE THREAD

**Issue by edofe99** [koekeishiya/yabai#1800]
Hello. 

I'm on MacOs 12.5 with Silicon. I've run terminal in "startup option" with command:
```
csrutil disable --with kext --with dtrace --with basesystem
```
Like mentioned in the Wiki guide. I restarted and then I also run the command 
```
sudo nvram boot-args=-arm64e_preview_abi
```
and restarted again. 

I've added to yabai config file things such as window opacity and set the animation to 0.0 but nothing change. Also on skhd I've created a shortcut to focus on a certain space, all shortcut works fine but that one (which requires SIP) not. So apparently I've disabled SIP but it's not effective. 

Any guidance? Thank's. 

EDIT: Just to confirm: 

```
$ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled
	Boot-arg Restrictions: disabled
	Kernel Integrity Protections: disabled
	Authenticated Root Requirement: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

**Comment by ironhak** [comment]
Is there anyone?? I would really like to use features that requires SIP disabled.
