### ISSUE TITLE
Switching from stack to bsp layout rearranges the windows

### ISSUE THREAD

**Issue by georg3tom** [koekeishiya/yabai#1803]
When transitioning from the BSP layout to the stack layout and subsequently switching back to BSP, rearranges the windows in the space.

The window at the top of the stack is relocated to the top left corner of the screen, which is not the desired behaviour. Ideally, the layout should be preserved when switching back to the bsp layout.

Keybind used to change the layouts.
```
alt - m : yabai -m space --layout $(yabai -m query --spaces --space | jq -r 'if .type == "bsp" then "stack" else "bsp" end')
```

sys info
```
❯ yabai --version
yabai-v5.0.6

~
❯ nvram -p | grep boot-args
boot-args	-arm64e_preview_abi

~
❯ sw_vers
ProductName:		macOS
ProductVersion:		13.4.1
BuildVersion:		22F82
```

**Comment by ironhak** [comment]
This is something that happens even without changing the layout when you restart. Eg. you're on BSP, you restart yabai and windows layout will change. 

This is something that bothered me too, don't think a fix regarding this will come soon. Suggestion is to stick using either BSO or stack, when needed you can float certain windows or make them full screen and then back into the layout without having the whole thing rearranged. 

Hope that helps.

**Comment by victortrac** [comment]
The same thing happens if you full-screen and undo a youtube video.

**Comment by koekeishiya** [comment]
This is intentional. Not a particularly easy problem to solve.
