### ISSUE TITLE
Starting a program from the terminal leaves it floating

### ISSUE THREAD

**Issue by cyanic-selkie** [koekeishiya/yabai#1806]
When I run a program from the terminal (default terminal or alacritty), it starts as a floating window in the middle of the screen.

Is this expected behavior? If so, can I somehow change it?

**Comment by shiyuangu** [comment]
This works for me: 
`yabai -m rule --add app="^Emacs$" manage=on
`

**Comment by cyanic-selkie** [comment]
@shiyuangu It doesn't seem to work for me, unfortunately.

**Comment by albertolazari** [comment]
# New instance
If you just want to open a new instance of alacritty you can create a rule in `skhdrc` like this:
```
ctrl + alt - t : open -na alacritty
```

This works just fine for me

# New instance in the same working directory
This is far more challenging and requires a little bit of hacking around. You can find how I solved it in my dotfiles:
- [New instance script](https://github.com/albertolazari/.dotfiles/blob/main/alacritty/spawn-new-instance.sh)
- [Custom Alacritty keybinding](https://github.com/albertolazari/.dotfiles/blob/main/alacritty/os-specific/macos.yml)

**Comment by cyanic-selkie** [comment]
@albertolazari When I do this, I get the exact same effect, a floating window in the middle of the screen.

**Comment by cyanic-selkie** [comment]
@shiyuangu Actually, this seems to work. I must've made a mistake the first time I tried it.
