### ISSUE TITLE
Adjust positions of fullscreen applications using yabai rules

### ISSUE THREAD

**Issue by frenzibyte** [koekeishiya/yabai#1808]
I like to have some applications run in "fullscreen mode" on launch, and I've achieved that using yabai rules by setting `native-fullscreen` to `on`. But I also want the position of each application within the layout to be constant, and that doesn't seem to be possible at the moment.

**Comment by edte** [comment]
When I use full screen, the full screen program will automatically enter the newly created layout. When the original layout has only one program, it becomes empty. This also bothers me.

**Comment by koekeishiya** [comment]
No plans to support rearranging fullscreen applications in rules.
