### ISSUE TITLE
Return a non-zero exit code when a command fails because of an issue with the scripting addition

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#181]
### Feature request

Return a non-zero exit code if a command fails because the scripting addition is not installed or failed to get addresses.

This would be nice for scripts so chaining with `&&` or `set -e` fails early. Currently there's no error message printed to stderr and the exit code is 0, indicating success.

**Comment by koekeishiya** [comment]
Do you think it is useful as an end-user to be able to tell the difference between the various ways the scripting-addition fails, or is a generic catch-all "the operation could not complete due to an error with the scripting addition" good enough (with a non-zero exit code of course).

**Comment by dominiklohmann** [comment]
If I recall correctly I wanted to write this in some place:

```
yabai -m space --focus 1 || skhd --key "ctrl - 1"
```
