### ISSUE TITLE
Focus moves to other display when auto-correct activates

### ISSUE THREAD

**Issue by b4rlw** [koekeishiya/yabai#1811]
When I have 2 displays connected, and I type in a text box in Safari (such as the one I am typing in now), the focus often jumps to the other display. Interestingly, this doesn't seem to happen with Chrome.

I'm using the latest release at the time of writing - `yabai-v5.0.6`.

Has anyone experienced a similar issue?

**Comment by b4rlw** [comment]
After taking another look at this, it seems as though it is related to auto-correct in some way.

For example - if I spell a word wrong in the ChatGPT search box, the focus is switched from my external display (where Safari is running) to my MPB internal display when the auto correction is made.

I can prevent this behaviour from occurring by disabling "Correct spelling automatically" under the "Spelling" section of System Settings.

**Comment by alwyn** [comment]
In my case whenever I use cmd-N to create a new window, it would create the window on the right display, but the mouse would go to the primary display.  Wonder if it is somehow related and some internal Mac thing.

**Comment by koekeishiya** [comment]
Should be fixed on master.
