### ISSUE TITLE
first space is broken without error

### ISSUE THREAD

**Issue by makeopts** [koekeishiya/yabai#1814]
## Issue
Hello, I currently have an issue with spaces in yabai where the first space is completely unusable, but when analysing logs to check what's up, there is nothing wrong happening.
I have enabled debugging to see what's happening further, and nothing has came out of it either.
## Sys. Info
I am running on MacBookPro11,1 on macOS 11.7.9, yabai has been downloaded via GitHub Releases.
SIP Status:
```
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```
The Scripting Addon is installed as `sudo yabai --load-sa` successfully runs.

## How to replicate
With yabai on any space over 1, type in a terminal `yabai -m space --focus 1` and it should return with exit status 0, then do the same command except replace 1 with the space you were previously on.

## Intended result
Running `yabai -m space --focus 1` should move you to space 1 without it staying on the "previous" workspace

**Comment by makeopts** [comment]
[yabai.log](https://github.com/koekeishiya/yabai/files/12241651/yabai.log)
should prob send logs here, there is no text when switching to space 1 against when opening space 4 which showed `SPACE_CHANGED` along with what windows would be visible

**Comment by Bellavene** [comment]
Have you your user files still from old macos version where dashboard was still there? Dashboard was managed by the system as a space. So there is a possibility that your system is still reserving one space for dashboard, while dashboard is totally removed long time ago. And that can cause this behavior. I had that problem.
