### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by artuross** [koekeishiya/yabai#1817]
I'm currently running macOS 14 public beta

```sh
❯ sw_vers
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A5301h
```

I have Karabiner Elements bindings to focus windows within a space. When attempting to focus a window to a side, `yabai` exits with segmentation fault (I'm not actually sure whether it is `yabai`).

Note this only happens if there's another window that can be switched to. For example, if I try to focus window to the right of the rightmost window, there's not error and `yabai` does not restart. If I try to focus west (to the left), it will. I tested it in either direction.

This is how it looks like when I run it with `yabai --verbose`:

```sh
EVENT_HANDLER_DAEMON_MESSAGE: window --focus west
zsh: segmentation fault  yabai --verbose
```

If I have a window floating and try to focus from there, nothing happens (also no error). If I manually type `yabai -m --focus east` in a managed terminal, `yabai` will exit just like with Karabiner.

```sh
❯ yabai --version
yabai-v5.0.5
```

**Comment by BanjoCam** [comment]
see https://github.com/koekeishiya/yabai/issues/1772

**Comment by artuross** [comment]
Thanks @BanjoCam, seems like a common issue with Ventura.
