### ISSUE TITLE
Avoid broken state when acting on the only space in certain situations

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#182]
### Bug report

yabai / Dock.app currently end up in a broken state when
- destroying the only non-fullscreen space on any display, or
- moving the only non-fullscreen space from any display to another display.

In any of these situations yabai should return a non-zero exit code and print an appropriate message to stderr.

**Comment by koekeishiya** [comment]
Performing these checks could very possibly add noticable performance degradation to these features.

**Comment by dominiklohmann** [comment]
Checking this manually with `yabai -m query --spaces --display | jq -re "map(select(.\"native-fullscreen\" == 0)) | length > 1"` takes less than 25ms on my computer for 10+ spaces and requires spawning two processes. What exactly do you think would cause a noticeable performance degradation here?

**Comment by koekeishiya** [comment]
> Checking this manually with yabai -m query --spaces --display | jq -re "map(select(.\"native-fullscreen\" == 0)) | length > 1" takes less than 25ms on my computer for 10+ spaces and requires spawning two processes. What exactly do you think would cause a noticeable performance degradation here?

I consider an additional 25ms noticable enough to be annoying (for me personally). The work pretty much consist of querying all spaces on the display of the space we are acting on, and checking the type of each space. It's not a huge deal, but it does feel kinda wasteful to me. I don't disagree that the confidence in the stability of said feature has more value to it.

**Comment by dominiklohmann** [comment]
Well, most of those 25ms is converting the output to json and parsing the jq script. I doubt it'd be more than 5ms when checking for this internally.

I just don't think any command should ever lead to a state only `killall Dock` can help with.
