### ISSUE TITLE
Border blinking and window opacity

### ISSUE THREAD

**Issue by srgtmshnk** [koekeishiya/yabai#1821]
First of all, i'd like to thank you for the best MacOS window manager, it helped me so much using my new MacBook. I've used it for a while and found some bugs.

1. When i switch between spaces, the previous space's selected window forgets about the selection, so when i switch back to the previous space, it causes its selected window border to blink.
2. When i open several windows at one space, and then switch some window to zoom-fullscreen mode, i can see the other window through the window opacity, i dont know if this is a bug or feature, but looks annoying.

I tried to fix these issues by myself, but i'm not really fluent in C and MacOS API. Also, i can try to make some videos showing these bugs if you want.

**Comment by koekeishiya** [comment]
Borders have been removed in the latest release (v6.0.0) (#1889) because of multiple issues present in both Ventura and Sonoma.
