### ISSUE TITLE
How to set key command to yabai to start instead of automatically on startup

### ISSUE THREAD

**Issue by yoshimario** [koekeishiya/yabai#1822]
I am trying to have a command for yabai to start instead of automatically opening on startup it gets annoying.

**Comment by GNRSN** [comment]
As per the readme you can use skhd for keyboard shotcuts

> Keyboard shortcuts can be defined with [↗ skhd](https://github.com/koekeishiya/skhd) or any other suitable software you may prefer.

If you have yabai installed through homebrew, use `brew services run yabai` key being `run` instead of `start`to launch without adding to automatic run at startup.
