### ISSUE TITLE
Add CLI '--help' and /or 'help' flags

### ISSUE THREAD

**Issue by issmirnov** [koekeishiya/yabai#1825]
I recently updated my system, and `brew services start yabai` no longer works. I tried `yabai help` and `yabai --help`, but those commands do not exist.

it would be very useful to have the CLI print a list of allowed commands. If the CLi arg parser framework doesn't have that built in, a simple printf directing the user to https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc would also be helpful.

Thanks for a wonderful WM! Can't live without it.

**Comment by koekeishiya** [comment]
Brew should be installing a manual page; just run: man yabai

**Comment by darklyspaced** [comment]
i don't really see the downsides of having both. the `--help` flag is, just like a man page, basically expected on CLI tools and could act as an easy first point of reference for users; man page being reserved for the nitty gritty details. even just telling people to `man yabai` would be an improvement over throwing a generic 404.

**Comment by AlJohri** [comment]
I think having a `--help` is fairly standard in CLI software these days. I also ran into this a few times when I tried to run `yabai --help` before realizing I should be using the `man` pages which are very detailed. I agree with @darklyspaced that even just redirecting to the man page from `--help` would be great for discoverability.

**Comment by koekeishiya** [comment]
I really don't see the use in this when the man page covers everything there is, but w/e; added list of options.

**Comment by 24unix** [comment]
That's a good decision.

**Comment by issmirnov** [comment]
Thank you!
