### ISSUE TITLE
Tabs Being Treated Like Windows in Quip

### ISSUE THREAD

**Issue by AlJohri** [koekeishiya/yabai#1826]
I am running into an issue with the [Quip](https://quip.com/) where the tabs are being treated as windows. You can see in the video below that as I open new tabs, yabai is treating them like separate windows and moving the window around:

https://github.com/koekeishiya/yabai/assets/2790092/d31a2fe0-330d-4311-9e55-da55d944d3b7

When I have two tabs open, here is the output of querying for the windows in yabai:

```
❯ yabai -m query --windows | jq '.[] | select(.app == "Quip")'
{
  "id": 249724,
  "pid": 56419,
  "app": "Quip",
  "title": "Folders",
  "frame": {
    "x": 20,
    "y": 694,
    "w": 1001,
    "h": 615
  },
  "role": "AXWindow",
  "subrole": "AXStandardWindow",
  "display": 1,
  "space": 1,
  "level": 0,
  "opacity": 1,
  "split-type": "horizontal",
  "split-child": "second_child",
  "stack-index": 0,
  "can-move": true,
  "can-resize": true,
  "has-focus": false,
  "has-shadow": true,
  "has-border": false,
  "has-parent-zoom": false,
  "has-fullscreen-zoom": false,
  "is-native-fullscreen": false,
  "is-visible": true,
  "is-minimized": false,
  "is-hidden": false,
  "is-floating": false,
  "is-sticky": false,
  "is-topmost": false,
  "is-grabbed": false
}
```

Any ideas what could be going on here? Is there an option I can enable to potentially fix this?

**Comment by jonatan-branting** [comment]
This is a known issue: https://github.com/koekeishiya/yabai/issues/68

I'd personally solve it by simply making Quip always float:
```sh
yabai -m rule --add app='^Quip$' manage=off
```

**Comment by AlJohri** [comment]
Thanks! I didn't realize this was a larger issue. Going to try a few of the potential workarounds mentioned in #68:


1. As suggested here, I tried globally disabling tabs. As mentioned in the comment edit, it only worked for some applications like Finder, not Quip. https://github.com/koekeishiya/yabai/issues/68#issuecomment-656850105:

    ```
    defaults write NSGlobalDomain NSWindowTabbingEnabled -bool false
    ```

2. Tried changing the layout to float and then back to BSP. This does seem to reset the layout properly. https://github.com/koekeishiya/yabai/issues/68#issuecomment-1248622319

    ```
    yabai -m space --layout float && yabai -m space --layout bsp
   ```

3. Wanted to try this approach (https://github.com/koekeishiya/yabai/issues/68#issuecomment-1448588871) of switching spaces and back and forth to "refresh" yabai, but I was unable to test it since it requires the scripting addition.

    ```
    ❯ yabai -m space --focus next
    cannot focus space due to an error with the scripting-addition.

    ❯ yabai -m space --focus recent
    cannot focus space due to an error with the scripting-addition.
    ``` 

4. I was able to replicate the above approach using skhd to trigger pressing `ctrl - right` and then `ctrl - left`, but its very janky and not enjoyable to use.

    ```
    yabai -m signal --add event=window_created app="^Quip$" \
        action="skhd -k 'ctrl - right' && sleep 1 && skhd -k 'ctrl - left'"
    ```

5. Setting manage to false as suggested https://github.com/koekeishiya/yabai/issues/1826#issuecomment-1680314561 certainly works, but also isn't ideal.

    ```
    yabai -m rule --add app='^Quip$' manage=off
    ```

6. For me the best solution in this case was to just stop using the Quip app and switch to use Chrome to "Create Shortcut" and "Open as window" so that it looks and feels like an app:

    ![image](https://github.com/koekeishiya/yabai/assets/2790092/38a60029-a9e2-401d-ba22-a6769dd19d49)


Hopefully there will be a better solution someday in the future. Closing as a duplicate of #68 for now.

**Comment by AlJohri** [comment]
Linking this here as if you use Quip, you likely use Chime too: https://github.com/koekeishiya/yabai/discussions/2183
