### ISSUE TITLE
Brew Install not working?

### ISSUE THREAD

**Issue by gakonst** [koekeishiya/yabai#1828]
Hi - longtime Yabai user, tried to reinstall today and brew doesn't seem to resolve?

```
~ brew install yabai
Warning: No available formula with the name "yabai".
==> Searching for similarly named formulae and casks...
Error: No formulae or casks found for yabai.

➜  ~ brew install koekeishiya/formulae/yabai
Warning: No available formula or cask with the name "koekeishiya/formulae/yabai". Did you mean koekeishiya/formulae/krp or koekeishiya/formulae/skhd?
```

Apologies if basic question - thank you for building this software again.

**Comment by zilahir** [comment]
duplicate of https://github.com/koekeishiya/yabai/issues/1368

**Comment by gakonst** [comment]
Is it? My second command in the OP is the same as the recommended command, and it doesn't seem to find that either. Does that work for you?

**Comment by gakonst** [comment]
Roger - might be something with my brew then. Thanks!
