### ISSUE TITLE
Starting service freeze

### ISSUE THREAD

**Issue by ai212983** [koekeishiya/yabai#1830]
Hello guys.

I am sorry if this issue was discussed before, wasn't able to find anything.
After `yabai --start-service` there's no response, command just hangs until interrupted with Ctrl+C.

```
❯ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled
	Boot-arg Restrictions: disabled
	Kernel Integrity Protections: enabled
	Authenticated Root Requirement: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```
Accessibility is enabled, M2 Max, Ventura 13.5.1, yabai 5.0.6

**Comment by ai212983** [comment]
Works fine. The problem was old yabai plist from homebrew in Privacy & Security/Accessibility settings. It was carried over by migrating to new Mac. 

Closing this ticket.

**Comment by hld0** [comment]
Could you elaborate a bit on which plist exactly you modified/deleted @ai212983 ?

I am stuck at the same problem after migrating to a new Mac. Would be happy for any help!

**Comment by ai212983** [comment]
@hld0 Not sure if it will work for you, but here's what I did:
1. Uninstall yabai
2. Remove yabai from Privacy & Security / Accessibility settings.
3. Install yabai
4. Enable new entry of yabai in Privacy & Security / Accessibility.

Hope it will help you too!

**Comment by pencilcheck** [comment]
Reinstalling yabai and removing entries from accessibility settings doesn't fix the issue

**Comment by marcstreeter** [comment]
I had to also run a couple yabai/skhd commands (in addition to the above)

yabai --stop-service
skhd --stop-service
yabai --uninstall-service
skhd --uninstall-service

restart like a few times for good measure.

**Comment by LoveIiei** [comment]
Hi, guys, in case you have the same problem. 
`brew uninstall yabai` first
then you need to go to system settings and under Privacy & Security, there is Accessibility, click it and try to locate skhd and yabai. There is a minus (-) at the left bottom corner, selete yabai and click on that symbol, same thing for removing skhd. 
Then, you have to run
`rm -f ~/Library/LaunchAgents/com.koekeishiya.skhd.plist`
`rm -f ~/Library/LaunchAgents/com.koekeishiya.yabai.plist`
to remove the old plist, and _**now re-download them**_, and it will ask for the Accessibility permission. 

> GIVE IT AND ENJOY!
