### ISSUE TITLE
yabai crashes (?) when using window --focus

### ISSUE THREAD

**Issue by OfficialCRUGG** [koekeishiya/yabai#1831]
Hey there! I've just set up yabai along with a bunch of hotkeys using skhd (will list config files at the end of the post)
Everything seems to work fine, except by "focus window" hotkeys. When I do them, the following happens in order:

1. Either nothing happens OR the window focus gets changed correctly OR the windows get swapped for whatever reason
2. Either yabai doesn't work (all windows can float) for about 3-5 seconds until then suddenly working again (it tiles all windows again) OR it just sets by padding/gap to 0, waits a few seconds, and sets it back to 20 (as in my config)

I am very new to yabai and don't know what could cause this nor where I could find fitting log files. To me this seems like crashes with the software restarting though? If anyone of you could tell me where to find the respective log files I'd be happy to provide them.

```
# .yabairc

yabai -m config layout bsp

yabai -m config top_padding    20
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     20

yabai -m config window_shadow float

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

yabai -m rule --add app="^System Settings$" manage=off
```

```
# .skhdrc

# launch iterm
alt - return : open -a iTerm

# focus window
alt - left : yabai -m window --focus west
alt - down : yabai -m window --focus south
alt - up : yabai -m window --focus north
alt - right : yabai -m window --focus east

# swap window
shift + alt - left : yabai -m window --swap west
shift + alt - down : yabai -m window --swap south
shift + alt - up : yabai -m window --swap north
shift + alt - right : yabai -m window --swap east

# move window
shift + cmd - left : yabai -m window --warp west
shift + cmd - down : yabai -m window --warp south
shift + cmd - up : yabai -m window --warp north
shift + cmd - right : yabai -m window --warp east

# balance size of windows
shift + alt - 0 : yabai -m space --balance

# float window
shift + alt - f : yabai -m window --toggle float;
```

**Comment by OfficialCRUGG** [comment]
https://github.com/koekeishiya/yabai/assets/25248999/bd5894bd-cb4b-4075-926a-501443edae90

Here's a video showing my issue. At first, I show off the move window hotkeys - as they work just fine - and then I show the focus window hotkeys and how they don't really work...

All key inputs can be seen in the bottom left-ish corner

**Comment by koekeishiya** [comment]
#1772
