### ISSUE TITLE
Window not managed by yabai when another window from the same process is minimised

### ISSUE THREAD

**Issue by tomelliot** [koekeishiya/yabai#1833]
Hi there,

I'm seeing an issue where a window won't be seen by yabai under certain conditions. I'm guessing yabai isn't handling a window being minimised exactly right.

# What am I seeing?

- I have 6 spaces across two screens.
- I have 3 Firefox windows. One on Screen A Space 1, one on Screen A Space 3 and one minimised
- If Screen A Space 1 is active when yabai's started or config is reloaded, then the Firefox window on Screen A Space 3 is not found by yabai
- If Screen A Space 3 is active when yabai's started or config is reloaded, then the Firefox window on Screen A Space 1 is not found by yabai
- If I unminimise the 3rd Firefox window, this doesn't happen.

# Debug info

What further info can I provide to help understand this problem?

```
$ yabai --version
yabai-v5.0.6
```

**Comment by koekeishiya** [comment]
I think this is  caused by some optimization I attempted to do to avoid having to query *every single application every time a space switch occurs* (which can be really really bad for responsiveness).
