### ISSUE TITLE
Issue with autofocus with PIP 

### ISSUE THREAD

**Issue by jin-ahn** [koekeishiya/yabai#1847]
In my config I have the below config because when I swap from one space to another I want yabai to automatically focus on the window in the space, rather than have it stay focused on a window from the previous space.
`yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"`

However, this creates in issue when I have PiP feature that is sticky on each space.
Example case:
I have arc browser on one space, I play a youtube video, and then switch to another space. Doing so will create a pip. When I switch to another space the "jq . [0].id" will be the PIP so yabai will auto switch back to the original space since that is where the window is. 

How do I make it so that I still have yabai will ignore the PIP window and still focus the next top most of window of the space?

I have tried changing it to `jq .[1].id)` but then when I switching spaces without PIP it won't focus on the top most app because there's only 1

I also have tried `yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off` and that prevents the mini player from being tiled, but does not exclude it from being `jq .[0].id`

**Comment by jin-ahn** [comment]
Figured it out. You can do a // with jq. 

`yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq '.[1].id // .[0].jd' )"`

**Comment by Nauticus** [comment]
I also had this issue. My solution is as follows.
yabairc
```bash
yabai -m signal --add event=space_changed action="$HOME/.config/yabai/scripts/yabai_pip_manage.sh"
yabai -m signal --add event=mission_control_exit action="$HOME/.config/yabai/scripts/yabai_pip_manage.sh"
```
yabai_pip_manage.sh
```bash
#!/bin/bash

space_windows=$(yabai -m query --windows --space)
focused_window_is_pip=$(jq 'map(select(."has-focus" and .title == "Picture in Picture")) | length' <<< "$space_windows")

if [[ $focused_window_is_pip -eq 1 ]]; then
    winid=$(jq 'map(select(."has-focus" and .title == "Picture in Picture" | not)) | .[0].id' <<< "$space_windows")
    if [[ "$winid" != 'null' ]]; then
        yabai -m window --focus $winid
    fi
fi
```
