### ISSUE TITLE
Automatic resize/partition when moving app to space?

### ISSUE THREAD

**Issue by kerryj89** [koekeishiya/yabai#185]
I have commands to destroy all spaces, create x amount of spaces on each display, and move the apps to their correct spaces (because OSX forgets what goes where between work and home).

I noticed in yabai that while the apps are thrown into the space correctly, they do not resize/partition until I focus on the space again.  It feels a bit janky with windows dancing around upon focus and I'm wondering if there is a way to resize/partition immediately after going through the destroy/create/move process above so that when I visit spaces I don't have windows flashing at me.

It's not really an issue, but I think chunkwm handled this part cleaner for me (could be wrong).

**Comment by dominiklohmann** [comment]
Windows immediately resize when moving them to another space on the same display as the focused space, or when moving them to a visible space on another display. They do not resize immediately when moved to an invisible space on an unfocused display. 

I posted about this behaviour previously in #112, where this behaviour was deemed not really worth fixing (emphasis mine).

> @dominiklohmann When moving windows to an inactive space on an different monitor, they do not get tiled properly until the space is active (they get resized, but not moved)

> @koekeishiya If I understand you correctly, the window does automatically get the correct position/size when that space is activated, yes? I had similar issues where sometimes a window on an inactive space will update fine, and sometimes they won't - no pattern really.. I notice this mostly when adjusting the display resolution or disconnecting a display. As long as the window does get the correct dimensions upon space activation **I probably won't bother looking into this.**

As a workaround, after moving all your windows, visit all the spaces in a specific order so the previously visible/focused spaces are still the visible/focused spaces after the command. I have this command at the very end of my yabairc as well for the same reason.

```sh
# Visit all spaces once
yabai -m query --spaces \
    | jq 'sort_by(.focused, .visible) | .[].index' \
    | xargs -I{} yabai -m space --focus {}
```

**Comment by koekeishiya** [comment]
This is not something that is fixable as far as I'm concerned. The reason this is happening is because the accessibility API (at least for the majority of applications) do not allow us to move and resize windows that are not on the active space. I have no desire to dig deeper into this behaviour.
