### ISSUE TITLE
Windows randomly shifting or swapping spaces

### ISSUE THREAD

**Issue by mlorenc01** [koekeishiya/yabai#1850]
I just started using `yabai` this week and this issue is happening to me very often.

- `yabai-v5.0.7` 
- `macOS 13.5.1`.

I have configured yabai to create 10 spaces on startup so I can send apps to the same spaces and have a consistent setup, e.g. Terminal on 1, Slack on 3, VPN on 9 etc.

It happens multiple times daily that my windows are suddenly shifting or swapping spaces. I know the shift happens during native fullscreen, so I just stopped using it completely, but the issue is still happening quite often. It seems almost random, sometimes I would find an app that should be in space 7, e.g. on space 3 for no real reason.

```
$ cat ~/.yabairc
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp

# pre-create 10 spaces to make it feel more like i3wm
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create
yabai -m space --create
```

```
$ cat ~/.skhdrc
# focus window
cmd - left : yabai -m window --focus west
cmd - right : yabai -m window --focus east
cmd - up : yabai -m window --focus north
cmd - down : yabai -m window --focus south

# swap window
cmd + shift - left : yabai -m window --swap west
cmd + shift - right : yabai -m window --swap east
cmd + shift - up : yabai -m window --swap north
cmd + shift - down : yabai -m window --swap south

# focus space
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9
cmd - 0 : yabai -m space --focus 10

# move window to space
cmd + shift - 1 : yabai -m window --space 1
cmd + shift - 2 : yabai -m window --space 2
cmd + shift - 3 : yabai -m window --space 3
cmd + shift - 4 : yabai -m window --space 4
cmd + shift - 5 : yabai -m window --space 5
cmd + shift - 6 : yabai -m window --space 6
cmd + shift - 7 : yabai -m window --space 7
cmd + shift - 8 : yabai -m window --space 8
cmd + shift - 9 : yabai -m window --space 9
cmd + shift - 0 : yabai -m window --space 10

# window properties
cmd + shift - space : yabai -m window --toggle float
cmd + shift - b : yabai -m window --toggle border
cmd + shift - f : yabai -m window --toggle native-fullscreen
```

**Comment by 24unix** [comment]
Did you disbale this silly setting?
<img width="480" alt="image" src="https://github.com/koekeishiya/yabai/assets/36622631/b66fb39e-91dd-4426-aac1-4266ca958ee0">

**Comment by mlorenc01** [comment]
No, it was enabled, @24unix . Thanks for pointing that out! I am still a newbie both to macOS and yabai :)

I have disabled the setting, let's see if it fixes the issue. I come back with an update in a couple days.

**Comment by 24unix** [comment]
You're welcome. I never regretted the switch from Linux to macOS.

**Comment by mlorenc01** [comment]
It's been a couple days now and the issue did not happen again after changing the silly setting :) Thanks again @24unix! I will close the ticket.

**Comment by adicco** [comment]
Thanks, I had this setting on as well, and I couldn't figure out why my windows were randomly moved (coming from an i3 setup.)

**Comment by Try431** [comment]
Still relevant in late 2025 on MacOS 15.7.2, thanks for the help!
