### ISSUE TITLE
Yabai cannot focus active windows

### ISSUE THREAD

**Issue by tb-1212** [koekeishiya/yabai#1852]
Hi im having a problem with focusing windows in a space, it only work for some apps and not all, i tried 
yabai -m window window-id but doesnt work
or do i need to list all the window-id for it to work? can you send me a sample code?

Appreciate the feedback

**Comment by koekeishiya** [comment]
You can get window ids using `yabai -m query --windows` and pass it to `yabai -m window --focus <id>`
