### ISSUE TITLE
Automatic load of  `yabai --load-sa`

### ISSUE THREAD

**Issue by ironhak** [koekeishiya/yabai#1855]
Hello, there are features that require SIP to be disabled that will only work when I run `sudo yabai --load-sa`, so everytime I restart the machine I have to run that command otherwise those features wont work. Is there a way to have that feature always enabled? 

Thank's

**Comment by Bellavene** [comment]
Yabai does it automatically. In .yabairc there is a line to reload it after dock restart, which can give you a clue.
`yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"`
So you can add commands to .yabairc and it will be executed when yabai is loading.

**Comment by ironhak** [comment]
.yabairc does not have default commands, I had to build it myself, so this line was not present. 

I added it, seems to works. Thank's

**Comment by Bellavene** [comment]
Yes, read wiki, it is very helpful.

**Comment by ironhak** [comment]
I added `yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"` but does not work, I still have to load it manually :/

**Comment by stoffeastrom** [comment]
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
