### ISSUE TITLE
Windows appear blurred-out

### ISSUE THREAD

**Issue by rwijtvliet** [koekeishiya/yabai#1856]
I've just started using mac and yabai, so bear with me please.

Initially, with my yabai config, floating windows (such as the settings window) were appearing blurry, behind tiled windows. 

Be setting `window_topmost` to `on`, the floating window appears on top. *But it's still blurred-out*. I tried turning off transparency effects, but no luck. Clicks on the window are not registering.

![image](https://github.com/koekeishiya/yabai/assets/4106013/1c0909ca-8da0-4aeb-afde-8857fe72353a)

I have to `yabai --stop-service` to get the blur to go - so I think it is caused by yabai.

[Here](https://github.com/rwijtvliet/dotfiles/blob/main/yabai/yabairc.symlink) is my config; let me know if there is anything else I can do.

**edit:** it is not only floating windows; here a space where the left tiled window is blurred-out. The right window has the focus. Moving the focus to the left window using keyboard shortcuts works (the white bolder moves to the left window), but can't be moved back again to the right window.

![image](https://github.com/koekeishiya/yabai/assets/4106013/e7b733da-9b8d-430f-8fc4-2453c95054f8)

**Comment by Bellavene** [comment]
yabai -m config window_border_blur off

**Comment by rwijtvliet** [comment]
awesome, many thank! Out of curiosity, what's the use-case for having this option on?

**Comment by koekeishiya** [comment]
Borders have been removed in the latest release (v6.0.0) (#1889) because of multiple issues present in both Ventura and Sonoma.
