### ISSUE TITLE
Focus follows mouse activating menu bar

### ISSUE THREAD

**Issue by kabeersvohra** [koekeishiya/yabai#1857]
Hi, I have noticed an issue with focus follows mouse option, when I move my mouse across the displays, it activates the menu bar. This happens when the displays are stacked on top of each other.

I have attached a video here (screen recorder does not allow to record multiple screens)

https://github.com/koekeishiya/yabai/assets/5859986/42c7ecd9-c0b0-4cfc-b2e1-4e2a8efab3fd

**Comment by kabeersvohra** [comment]
@koekeishiya just created a PR for a fix for this issue, would appreciate if you could take a look: https://github.com/koekeishiya/yabai/pull/1860

**Comment by koekeishiya** [comment]
The correct solution would be to path in the x and y offset here. Would need to be tested for both x86-64 and arm64: https://github.com/koekeishiya/yabai/blob/master/src/display_manager.c#L185

I'll do it at some point.

**Comment by kabeersvohra** [comment]
ah makes sense, I am happy to have a go at it but I only have a silicon mac, let me know if there is some way I can help here to fix this issue?

**Comment by kabeersvohra** [comment]
Much nicer suggestion, a lot cleaner :), I have updated the PR as you mentioned and now it is only 3 lines more of code

**Comment by koekeishiya** [comment]
Your PR had a bug on x86-64 as it already correctly offsets by the display frame. I've pushed a fix to master now.

**Comment by kabeersvohra** [comment]
Perfect, thank you for sorting this! Lol forward to the release

**Comment by Jjess2** [comment]
> Your PR had a bug on x86-64 as it already correctly offsets by the display frame. I've pushed a fix to master now for arm64.
