### ISSUE TITLE
Cycle and wrap spaces on a single display

### ISSUE THREAD

**Issue by mwpardue** [koekeishiya/yabai#1859]
I'm looking for a way to cycle through spaces on a single monitor (display) and then wrap back to the first space on that display when you reach the end of the spaces on that display. I can't quite wrap my head around the best way to approach this, though. Can anybody offer any suggestions? It seems one variation of wrapping or another is asked about pretty often but I couldn't find anything on this particular use case.

[123] [456] [789]

So if the above is 3 spaces on 3 displays and I'm on the middle display I want to be able to focus from space 4 to 5, 5 to 6, then from 6 back to 4. IDK if I can count on them always being consecutively numbered so I'm unsure of the best way to track the available spaces on the display.

I'm sorry if this has been covered somewhere and I just overlooked it. I appreciate any assistance!!

Edit: BTW, the closest I've come is addressing them directly with something like `yabai -m space --focus $(yabai -m query --displays --display | jq -r '.spaces[1]')` but that only works right now if you have just 2 spaces on the display and doesn't handle wrapping.

**Comment by koekeishiya** [comment]
Probably easier to write in a script than inline:


cycle_prev.sh
```
info=$(yabai -m query --spaces --display)
first=$(echo $info | jq '.[0]."has-focus"')

if [[ $first == "false" ]]; then
    yabai -m space --focus prev
else
    yabai -m space --focus $(echo $info | jq '.[-1].index')
fi

```

cycle_next.sh
```
info=$(yabai -m query --spaces --display)
last=$(echo $info | jq '.[-1]."has-focus"')

if [[ $last == "false" ]]; then
    yabai -m space --focus next
else
    yabai -m space --focus $(echo $info | jq '.[0].index')
fi
```

**Comment by koekeishiya** [comment]
Added to the wiki as well
https://github.com/koekeishiya/yabai/wiki/Tips-and-tricks#constrain-space-focus-to-current-display-with-optional-cycling
