### ISSUE TITLE
copy grayed out

### ISSUE THREAD

**Issue by rwijtvliet** [koekeishiya/yabai#1861]
When using `yabai`, the copy option in the right-click menu is (~always?~ no, not always....this is going to complicate things I'm aware) grayed out:

![image](https://github.com/koekeishiya/yabai/assets/4106013/77ae1d2e-3742-4f83-b288-0ff4e9c99f4d) 

Command+C still works however.

After stopping the service, the copy option is available:

![image](https://github.com/koekeishiya/yabai/assets/4106013/ea1d3a0c-9479-4570-bcf6-f75930148209)

My system is an M2 macbook pro.

I assume this is a permissions issue, so I'll mention another issue I've noticed: when yabai is active, neither touch-id nor passwords work for authentication, e.g. to adjust app permissions. I have to stop the service, make the change (and authenticate), and afterwards restart the service. This is not too much of a hassle; I just mention it in case it's related.

**Comment by koekeishiya** [comment]
I have not seen any of these issues in the latest versions, so closing this.
