### ISSUE TITLE
Auto focus does not work

### ISSUE THREAD

**Issue by mairm1340** [koekeishiya/yabai#1865]
I have this configuration

When I open an app it does work in the correct workspace but It does not focus

for example if I open safari while I am on WS7,  it opens on workspace 2 but I m still on WS7. Can you help me fix this.

I expect when I open an app, it should take me to that workspace.

here is my sample configuration...

 # move some apps automatically to specific spaces
yabai -m rule --add app="^iTerm2$" space=^1
yabai -m rule --add app="^Safari$" space=^2
yabai -m rule --add app="^Firefox$" space=^2
yabai -m rule --add app="^Microsoft Outlook$" space=^3
yabai -m rule --add app="^Microsoft Teams$" space=^4
yabai -m rule --add app="^Prospect mail$" space=^5
yabai -m rule --add app="^SecureCRT$" space=^6
yabai -m rule --add app="^Microsoft Remote Desktop$" space=^7

**Comment by koekeishiya** [comment]
The feature works fine. Make sure you have disabled SIP and installed the scripting addition according to instructions in the wiki.
