### ISSUE TITLE
Yabai breaks desktop & stage manager settings in Sonoma

### ISSUE THREAD

**Issue by ChronoStriker1** [koekeishiya/yabai#1867]
Tested yabai installed from head
Right now Im assuming whatever is breaking space switching is also causing this.  When yabai is started, with or without the scripting additions enabled Stage Manager breaks, if its enabled it will say its enabled and vice versa.  You can set it to enabled or disabled from the terminal but it will not function.  It also appears to break what is being used to show icons and hide windows when clicking on the desktop.

**Comment by alwyn** [comment]
In my case Mission Control doesn't show previews and I can't switch.

**Comment by koekeishiya** [comment]
From the readme:

<!DOCTYPE html>
System Settings (macOS 14.x) | In the Desktop & Dock tab, inside the Desktop & Stage Manager pane, the setting "Show Items On Desktop" should be enabled for display and space focus commands to work reliably in multi-display configurations.
-- | --
System Settings (macOS 14.x) | In the Desktop & Dock tab, inside the Desktop & Stage Manager pane, the setting "Click wallpaper to reveal Desktop" should be set to "Only in Stage Manager" for display and space focus commands to work reliably.
