### ISSUE TITLE
cant boot macOS 14.0，after disable SIP

### ISSUE THREAD

**Issue by cehnhy** [koekeishiya/yabai#1870]
intel cpu and macOS 14.0. i disabled SIP，then system keeps rebooting. i try enable SIP， but not work.

**Comment by Bellavene** [comment]
hackintosh?

**Comment by cehnhy** [comment]
> hackintosh?

no， it's 2019 MacBook Pro 16"

**Comment by jfraeys** [comment]
I am having the same problem even after re-enabling the SIP settings.

**Comment by cehnhy** [comment]
> I am having the same problem even after re-enabling the SIP settings.

same. I use the command 'csrutil disable --with kext --with dtrace --with nvram --with base system ', and it outputs this configuration may broken system. Then I re-install the system, use the command 'csrutil disable', everything is ok.
