### ISSUE TITLE
Performance and authentication issues

### ISSUE THREAD

**Issue by rwijtvliet** [koekeishiya/yabai#1871]
I've recently switched to mac and decided to use tiling window management with yabai. However, I've noticed some issues, and was wondering if anyone else has, too, and if there is a fix.

It's several things, which may or may not be related.

*   In general, the system feels sluggish. There is one clear example I noticed and can also show: pop-up dialog windows. These "zoom into focus" - their size and opacity increase in a ~1sec animation. If yabai is running, this is a very jagged animation with maybe 3 frames (the capturing framerate is not to blame, see the mouse at the end):

    [video](https://github.com/koekeishiya/yabai/assets/4106013/600aa181-14ba-4c70-8239-b46e76d42cc3)

    When it's not, the animation is fluid:

    [video](https://github.com/koekeishiya/yabai/assets/4106013/cdff708e-cfbc-4a51-b3cd-d08333a9a998)

    Between the first and the second video, all I did was run `yabai --stop-service`.

    Freecad seems particularly affected, and even items in comboboxes are clicked without intent. Again, this subsides when stopping the yabai service.

*   When yabai is running, touch-id and my password are not working for authentication when e.g. changing settings. Only when I stop the yabai service can I confirm/authorize.

*   Sometimes the whole system locks up and I cannot change the focused application, even with the mouse. I suspect this too is caused by yabai, but it's hard to check as I cannot stop the service once it happens.

[Here](https://github.com/rwijtvliet/dotfiles/blob/main/windowmanager/yabai/yabairc) is my config. I'm on yabai 5.0.9 and sonoma. I'm happy to investigate or check logs if someone tells me how.

```bash
❯ yabai --version
yabai-v5.0.9

❯  csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled
	Boot-arg Restrictions: disabled
	Kernel Integrity Protections: enabled
	Authenticated Root Requirement: enabled
```

**Comment by rwijtvliet** [comment]
The touch-id/authentication issue I mention is probably the same as what's mentioned [here](https://github.com/koekeishiya/yabai/issues/1284#issuecomment-1527323890)

**Comment by koekeishiya** [comment]
Should be resolved in latest version.
