### ISSUE TITLE
zoom-fullscreen rearranges windows on second monitor starting with 5.0.7

### ISSUE THREAD

**Issue by sylphid8** [koekeishiya/yabai#1873]
I run a 2 monitor configuration with the secondary display left of the primary. Since 5.0.7, using `yabai -m window --toggle zoom-fullscreen` on the secondary display does not work properly reorganizing the window layout while the primary display works fine. Only windows on the left edge of the display are able to be full screened. Also, native fullscreen also reorganizes windows after exiting the full screen mode on both displays.

**Comment by windowsrefund** [comment]
Seeing similar behavior in 6.0.0. Of the 2 windows on my left monitor, I can only fullscreen the one on the right. The window on the left behaves as expected and in order to get the other to go into fullscreen mode, I have to swap its position so it ends up being on the left side beforehand.

**Comment by windowsrefund** [comment]
Seems to be working as expected in 6.0.3.
