### ISSUE TITLE
How to ensure moved window stays on top when switching spaces in Yabai?

### ISSUE THREAD

**Issue by roelvangils** [koekeishiya/yabai#1874]
With these shortcuts I can easily throw any window from one space to another, but how do I ensure that the window also always stays on top? After all, that depends on the stacking of the windows in the other space, right? The moved window may sometimes slide under another window. So, right before moving, I ought to give the window a "z-index" of 999, to put it in CSS terms). How do I do achieve this with Yabai?

```
ctrl + cmd - left : yabai -m window --space prev && yabai -m space --focus prev
ctrl + cmd - right : yabai -m window --space next && yabai -m space --focus next
```

**Comment by koekeishiya** [comment]
Uh, if the goal is to interact with this window right away you can just do: `yabai -m window --space prev --focus`

If you actually want to make the window on top without focusing it, you can do `yabai -m window --space prev --layer above` but you should be wary that using the `above` layer may cause sub-dialogs/menus/windows/dropdowns to not functioning very well.

**Comment by koekeishiya** [comment]
The layer issues should no longer be present after #2062
