### ISSUE TITLE
[Help] Seeking differing Top Padding Value per display.

### ISSUE THREAD

**Issue by 10zero11** [koekeishiya/yabai#1876]
Hi I'm seeking some advice.

I have two 4K external monitors plugged into a 14" MBP.

I was trying to use a toolbar via Ubersicht.

I want to set a 'Top Padding' that is specific to each screen. 
eg Screen 1 and 2 have a Top Padding of 22 and Screen 3 has a Top Padding of 11.

Is this possible?
It seems if I were to set a script to detect the screen and change the padding that this would only be correct for the currently focused window/screen.

Ideally a proportional 'Top Padding' value might allow for a one size fits all. (I don't think this is possible is it?)

**Comment by cbackas** [comment]
Here's how i've been handling it: https://github.com/cbackas/.dotfiles/blob/main/home/.config/yabai/scripts/set_padding.sh

To set top padding on my main display only it uses `yabai -m config external_bar main:$padding:0`.  I also iterate over each *space* and if that space is on the main display I do some various paddings depending on how many windows there are, but for top padding i like the `external_bar` setting. [I have this `set_padding.sh` script set to run a few events. ](https://github.com/cbackas/.dotfiles/blob/29568aa7064ba503b4483f5fef2fdc894eb97230/home/.config/yabai/yabairc#L26-L32)

**Comment by 10zero11** [comment]
@cbackas thank you for this. It seems like a way address my issue. I'll need to read up some more. 
Your config files are a very interesting read. 
Thanks for sharing.

**Comment by wenqihuang** [comment]
Maybe helpful:
```
## Status bar
yabai -m config --dispaly 0 external_bar all:20:0
yabai -m config --dispaly 1 external_bar all:30:0
```

**Comment by koekeishiya** [comment]
If external_bar is not sufficient, read this comment: https://github.com/koekeishiya/yabai/issues/598#issuecomment-1992675562
