### ISSUE TITLE
Window moved to a different display is not positioned properly

### ISSUE THREAD

**Issue by kiryph** [koekeishiya/yabai#188]
yabai-v1.1.2 or installation from HEAD 6c846d4:
```
❯ ll /usr/local/bin/yabai
lrwxr-xr-x  1 kiryph  admin    38B Aug  3 11:08 /usr/local/bin/yabai -> ../Cellar/yabai/HEAD-6c846d4/bin/yabai
```

Starting with following layout of four windows:
```
Display 1  Display 2
+-------+ +--------------------+
|       | |    W2   |          |
|       | |---------|    W4    |
|  W1   | |    W3   |          |
|       | +--------------------+
|       |
+-------+
```

Active window: W1 (terminal window)

```
$ yabai -m swap <id of W3>
```

gives you

```
Display 1  Display 2
+-------+ +--------------------+
|       | | W2/W1   |          |
|       | |---------|    W4    |
|  W3   | |  empty  |          |
|       | +--------------------+
|       |
+-------+
```

```
❯ yabai -m query --windows | jq '.[] | select(.space == 1)'
{
  "id": 24462,
  "pid": 49781,
  "app": "iTerm2",
  "title": "~",
  "frame": {
    "x": 0,
    "y": 2,
    "w": 956,
    "h": 517
  },
  "level": 0,
  "role": "AXWindow",
  "subrole": "AXStandardWindow",
  "movable": 1,
  "resizable": 1,
  "display": 1,
  "space": 1,
  "visible": 1,
  "focused": 1,
  "split": "horizontal",
  "floating": 0,
  "sticky": 0,
  "border": 0,
  "zoom-parent": 0,
  "zoom-fullscreen": 0,
  "native-fullscreen": 0
}
{
  "id": 26231,
  "pid": 8877,
  "app": "Google Chrome",
  "title": "Swap by window id from other display: window is placed over other window · Issue #188 · koekeishiya/yabai",
  "frame": {
    "x": 0,
    "y": 26,
    "w": 958,
    "h": 523
  },
  "level": 0,
  "role": "AXWindow",
  "subrole": "AXStandardWindow",
  "movable": 1,
  "resizable": 1,
  "display": 1,
  "space": 1,
  "visible": 1,
  "focused": 0,
  "split": "horizontal",
  "floating": 0,
  "sticky": 0,
  "border": 0,
  "zoom-parent": 0,
  "zoom-fullscreen": 0,
  "native-fullscreen": 0
}
```

As you can see the frame values are almost identical for window ids 26231 and 24462.

Possibly related issue: https://github.com/koekeishiya/yabai/issues/183

**Comment by koekeishiya** [comment]
This is not related to #183 which was a bug in yabai, but it is related to #150 (name does not reflect the issue as it has nothing to do with the statusbar), and is happening because macOS..

If you look closely you can see that we tile the window properly, but the window is then moved by an external source. You can verify this by simply toggling fullscreen or desktop gaps/padding.

**Comment by kiryph** [comment]
@koekeishiya Thanks for looking at this. Yes, I can affirm that toggling gaps places the window correctly.

What external source could be responsible for this?

A workaround could be that I append to my mapping, where this occurs, an additional toggling of the gaps.

Or is there a possibility to fix this?

**Comment by koekeishiya** [comment]
I can reproduce this reliably also so I mean it is not something on your system. I believe it is something related to the internals of how macOS places windows when we tell it to move the window to a different space (using the OS API). I will try and look into a fix at some point when I feel motivated enough.

**Comment by koekeishiya** [comment]
I can no longer reproduce after latest change to master.

**Comment by kiryph** [comment]
I have tested with the new release
```
❯ yabai --version
yabai-v2.0.0
```
and can confirm that I also cannot reproduce it anymore.
