### ISSUE TITLE
Space commands not working with MacOS Sonoma 14.0

### ISSUE THREAD

**Issue by lsliwaradioluz** [koekeishiya/yabai#1880]
Hello,

just wanted to ask if anybody noticed space commands stopped working after updating to MacOS Sonoma 14.0. Commands such as

`yabai -m space --focus 3` or `yabai -m space --create`

yield no error but have no effect either. I can see they're somewhat working because when I attempt to switch to the currently active space, yabai informs me that: `cannot focus an already focused space.`.

What I've tried so far is [uninstalling](https://github.com/koekeishiya/yabai/wiki/Uninstalling-yabai) and [installing](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)) yabai, following all of the required configuration steps. But perhaps there is something else I should do after upgrading to Sonoma?

Keep in mind other commands I am using (e.g. `yabai -m window --grid 1:2:0:0:1:1`) work as expected.

**Comment by tromars** [comment]
I have the same issue. Curiously focusing a space works, when another screen than the one the space belongs to, is in focus when issuing the command

**Comment by lsliwaradioluz** [comment]
@tromars thanks for chiming in. 

I myself am not using an additional monitor so it does not work for me at all...

**Comment by Tylopilus** [comment]
Can confirm

**Comment by mgallecom** [comment]
I have the same issue, yabai also restarts on each failed space command

**Comment by kyuwoo-choi** [comment]
Same here. no effect at all.

`yabai -m window --space next --focus` works though. 

It moves the current window to the next space and focuses on the next space. weird.

**Comment by Ridhamz-nd** [comment]
I can confirm this as well.
```
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (25808) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_APPLICATION_TERMINATED: osascript (25808) (not observed)
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (25814) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_APPLICATION_TERMINATED: osascript (25814) (not observed)
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (25820) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (25826) is not observable, subscribing to activationPolicy changes
... (same output as above with different ids)
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (25842) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_APPLICATION_TERMINATED: osascript (25842) (not observed)
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (25852) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (25847) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_APPLICATION_TERMINATED: osascript (25847) (not observed)
EVENT_HANDLER_APPLICATION_TERMINATED: osascript (25852) (not observed)
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (25858) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_APPLICATION_TERMINATED: osascript (25858) (not observed)
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (25863) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_APPLICATION_TERMINATED: osascript (25863) (not observed)
EVENT_HANDLER_APPLICATION_LAUNCHED: osascript (25864) is not observable, subscribing to activationPolicy changes
EVENT_HANDLER_APPLICATION_TERMINATED: osascript (25864) (not observed)
EVENT_HANDLER_WINDOW_TITLE_CHANGED: kitty 378
EVENT_HANDLER_WINDOW_TITLE_CHANGED: kitty 378
EVENT_HANDLER_DAEMON_MESSAGE: space --focus 3
EVENT_HANDLER_WINDOW_TITLE_CHANGED: kitty 378
event_signal_flush: transmitting window_title_changed to 1 subscriber(s)
EVENT_HANDLER_WINDOW_TITLE_CHANGED: kitty 378
EVENT_HANDLER_WINDOW_TITLE_CHANGED: kitty 378
event_signal_flush: transmitting window_title_changed to 1 subscriber(s)
EVENT_HANDLER_WINDOW_TITLE_CHANGED: kitty 378
EVENT_HANDLER_WINDOW_TITLE_CHANGED: kitty 378
EVENT_HANDLER_DAEMON_MESSAGE: query --windows --window
EVENT_HANDLER_DAEMON_MESSAGE: query --windows --window
EVENT_HANDLER_DAEMON_MESSAGE: query --windows --window
EVENT_HANDLER_DAEMON_MESSAGE: query --windows --window
```
This is the debug output when running `yabai -m space --focus 3`. 
Is the osascript log line relevant here?

**Comment by githubuser88442** [comment]
I can also confirm:

`shell
$ yabai -m space --focus 4
cannot focus space due to an error with the scripting-addition.
$ yabai --version
yabai-v5.0.9`

**Comment by Thevetat** [comment]
Likewise, issue with spaces and overal rendering.

**Comment by karsonenns** [comment]
This was initially broken for me on Sonoma 14.0, I was able to resolve this by:
- Re-Ran `sudo nvram boot-args=-arm64e_preview_abi`
- Restart
- Updated Yabai to `v5.0.9` via homebrew `brew upgrade koekeishiya/formulae/yabai`
- Individually added Yabai to privacy settings: **Screen Recording** & **Accessibility**

I don't know the exact step that resulted in the fix here, I assume it may be permissions related.

Confirming I am now able to:
- ✅ Create new spaces via`yabai -m space --create`
- ✅ Focus via `yabai -m space --focus next`

**Comment by Ridhamz-nd** [comment]
@karsonenns your steps worked for me. Thanks! :)

**Comment by Thevetat** [comment]
Can confirm, karsonenns steps + rerunning the scripting-addition setup (new hash for the upgrade) got my spaces working again. Thanks a bunch yall.

**Comment by lekifier** [comment]
Upgrade and try to config "scripting-addition" again: 
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
I got "cannot focus space due to an error with the scripting-addition" info.
Now it worked.

**Comment by githubuser88442** [comment]
@kabeersvohra's script worked for me! I also had to run `yabai --restart-service` afterwards for the changes to reflect as well! I'd like to add that this issue happened to me when I updated from macOS Ventura to Sonoma.

**Comment by ZeChArtiahSaher** [comment]
Still not working (intel mac)...

**Comment by windowsrefund** [comment]
@kabeersvohra you can use `id -un` or `whoami` to get the current username.

**Comment by CrazyCatZhang** [comment]
> Upgrade and try to config "scripting-addition" again: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition I got "cannot focus space due to an error with the scripting-addition" info. Now it worked.

I updated and reconfigured the sudoers file, and now I'm able to switch spaces without any issues.
