### ISSUE TITLE
Moving a window to a new Space no longer keeps it selected

### ISSUE THREAD

**Issue by lukasstoecklein** [koekeishiya/yabai#1881]
The old behavior was that moving a window to a new space would keep it selected. For example you move a window one space to the right, then change current Space to the right, the window you moved would still be selected, so you could move it again easily. Which was useful when you were moving a window to an unoccupied space. The behavior has been lost in yabai 5.0.9 / Sonoma.

Btw, great piece of software!

**Comment by koekeishiya** [comment]
This is a macOS change. Use `yabai -m window --space next --focus` instead of `yabai -m window --space next && yabai -m space --focus next`

**Comment by MonstrousOgre** [comment]
@koekeishiya  What if I don't want to move the window and change the space at the same time? I want to `yabai -m window --space prev` using one keybind, and later `yabai -m space --focus prev` using a different keybind. When I do this, the window isn't focused. Is there a way to do this and also have the window focused?
