### ISSUE TITLE
Moving window north and south not working

### ISSUE THREAD

**Issue by arozmarin** [koekeishiya/yabai#1882]
Moving window north and south not working anymore. East and west woking ok. My settings:

`ctrl + alt + cmd + lshift - d : window=$(yabai -m query --windows --window | jq -r '.id') && yabai -m window east --stack $window || (yabai -m window $window --toggle float && yabai -m window $window --toggle float)
ctrl + alt + cmd + lshift - w : window=$(yabai -m query --windows --window | jq -r '.id') && yabai -m window north --stack $window || (yabai -m window $window --toggle float && yabai -m window $window --toggle float)
ctrl + alt + cmd + lshift - a : window=$(yabai -m query --windows --window | jq -r '.id') && yabai -m window west --stack $window || (yabai -m window $window --toggle float && yabai -m window $window --toggle float)
ctrl + alt + cmd + lshift - s : window=$(yabai -m query --windows --window | jq -r '.id') && yabai -m window south --stack $window || (yabai -m window $window --toggle float && yabai -m window $window --toggle float)`

I also tested only with moves and I get same result and it happen same on MacOS Ventura and Sonoma (version yabai-v5.0.9 and skhd-v0.3.9).

Any Idea what could be wrong, my settings or is this bug?

Thanks

**Comment by koekeishiya** [comment]
I don't remember having thi issue bfore, and certainly not in the latest version of yabai.
