### ISSUE TITLE
stack broken when exiting fullscreen video

### ISSUE THREAD

**Issue by grozan** [koekeishiya/yabai#1883]
Hi,

there's a bug that I find very annoying.

How to reproduce:
- open chrome and whatever else application
- stack the 2 windows together
- in the chrome window, go to youtube and play a video fullscreen
- press ESC to go back to youtube in the non-fullscreen view

the stack is "broken". the chrome window is taken out of the stack. You have to stack it again by hand

expected result: the chrome window stays in the stack, where it was

hopefully it can be fixed. Very frustrating to have your windows organization messed up every time you watch something in fullscreen

**Comment by madeinchema** [comment]
I agree, this feature would be nice to have.

By looking at this related issue, it's mentioned Amethyst has this figured out:
https://github.com/koekeishiya/yabai/issues/324

**Comment by marcomayer** [comment]
Yup this would be great. Also happens on hiding windows and then switching to the app again. It should pop back up where it was before.
