### ISSUE TITLE
Issue with Yabai when upgrading from version 5.0.3 to 5.0.9

### ISSUE THREAD

**Issue by juancamilo-dev** [koekeishiya/yabai#1884]
A few days ago, I upgraded my system to Mac OS Sonoma. While Yabai had some minor glitches, it was generally working. However, after making minor adjustments to the borders and padding, I noticed that when switching from one window to another, the borders' appearance was delayed, and it felt like the program was trying to crash. In an attempt to solve this, I decided to upgrade Yabai to version 5.0.9, but this made things worse. After the upgrade, Yabai wouldn't start. I tried installing the development version with `brew install yabai --HEAD`, uninstalled, and reinstalled the program, but to no avail. When trying to start the service with `yabai --start-service` and `sudo yabai --start-service`, I encountered errors. I've looked into the documentation and other resources on GitHub related to Yabai, and I've tried several proposed solutions, but none have worked so far.

----------------------------------------------------------------
yabai --start-service
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
----------------------------------------------------------------
sudo yabai --start-service
Password:
Could not enable service: 125: Domain does not support specified action
Bootstrap failed: 125: Domain does not support specified action
----------------------------------------------------------------

Should I return the OS version?
I have to try to reinstall

**Comment by juancamilo-dev** [comment]
After updating the Homebrew formulas and continuing with the yabai installation, I've found that the service doesn't start as expected. Even after granting the necessary execution permissions, the service still doesn't run.

brew install yabai
==> Downloading https://formulae.brew.sh/api/formula.jws.json
-#O=-#       #        #
==> Downloading https://formulae.brew.sh/api/cask.jws.json
-#O=-#       #        #
==> Fetching koekeishiya/formulae/yabai
==> Downloading https://github.com/koekeishiya/yabai/releases/download/v6.0.0/yabai-v6.0.0.tar.gz
Already downloaded: /Users/perseo/Library/Caches/Homebrew/downloads/cd08557f77af8f639f2d41bdeb7de71e34772c957a52f250252aaf82b0de752c--yabai-v6.0.0.tar.gz
==> Installing yabai from koekeishiya/formulae
==> Caveats
Copy the example configuration into your home directory:
  cp /opt/homebrew/opt/yabai/share/yabai/examples/yabairc ~/.yabairc
  cp /opt/homebrew/opt/yabai/share/yabai/examples/skhdrc ~/.skhdrc

If you want yabai to be managed by launchd (start automatically upon login):
  yabai --start-service

When running as a launchd service logs will be found in:
  /tmp/yabai_<user>.[out|err].log

If you are using the scripting-addition; remember to update your sudoers file:
  sudo visudo -f /private/etc/sudoers.d/yabai

Build the configuration row by running:
  echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa"

README: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
==> Summary
🍺  /opt/homebrew/Cellar/yabai/6.0.0: 6 files, 1.7MB, built in 2 seconds
==> Running `brew cleanup yabai`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
perseo@MacBook-Air-de-juan:s000->/Users/perseo (0)
> yabai --start-service
yabai: service file '/Users/perseo/Library/LaunchAgents/com.koekeishiya.yabai.plist' is not installed! attempting installation..
perseo@MacBook-Air-de-juan:s000->/Users/perseo (0)
>
perseo@MacBook-Air-de-juan:s000->/Users/perseo (0)
> pgrep yabai
perseo@MacBook-Air-de-juan:s000->/Users/perseo (1)

**Comment by ggsp** [comment]
I was seeing a similar issue. Here's what solved it, maybe it works for you too:

1. Uninstall yabai: `brew uninstall yabai`
2. System Preferences > Security & Privacy > Accessibility (or equivalent on your version of macOS)
3. Click the lock and enter your password
4. Uncheck and remove all versions of yabai from the list
5. `cd ~/Library/LaunchAgents`
6. Use `ls` to check if there is a `com.koekeishiya.yabai.plist` file
7. If so, `rm com.koekeishiya.yabai.plist` (you can back it up first if you prefer)
8. Install yabai: `brew install koekeishiya/formulae/yabai`
9. Start yabai: `yabai --start-service`. It should attempt to install a new plist file, taking you to the Accessibility screen so you can reactivate yabai's access.

That did it for me, yabai started back up.

**Comment by Lau-r-a** [comment]
That did not resolve the issue for me updating to 6.0.0

**Comment by neuromaancer** [comment]
I did what you suggested, but I get:
```bash
yabai: service file '/Users/neuromaancer/Library/LaunchAgents/com.koekeishiya.yabai.plist' is not installed! attempting installation..
yabai: service file '/Users/neuromaancer/Library/LaunchAgents/com.koekeishiya.yabai.plist' could not be installed! abort..
```
I tried running with `sudo`:
```bash
Could not enable service: 125: Domain does not support specified action
Bootstrap failed: 125: Domain does not support specified action
```
