### ISSUE TITLE
Rework window levels and opacity

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#1887]
Making a window appear on top of other windows does not work very well for basically anything that is not a video player.

There are currently three layers in use; "below", "normal", "above". 

The window_topmost command (uses layer "above") should be removed. Instead, all managed (read: tiled) windows will appear at a level lower (layer "below") than the standard window level (layer "normal"), effectively achieving the same goal without all the issues. The user will still be able to change the window layer using the respective command or using rules to utilize any layer if they so wish.

The window fading mechanism is useful as a focus-mode kind of option, but it falls short when using multiple monitors. The opacity mechanism should not extend across spaces.

**Comment by mefengl** [comment]
@ironhak see https://github.com/koekeishiya/yabai/issues/1898

**Comment by preland** [comment]
I'm more or less okay with this change; it should be noted that this change is not reflected in the wiki; nor is it mentioned anywhere other than this PR and the changelog

**Comment by mortang2410** [comment]
Same as above. I was super confused as to how everything completely broke. There should be a big sign on the home page or wiki announcing the breakage of everything as well as how to effectively migrate.

**Comment by koekeishiya** [comment]
> There should be a big sign on the home page or wiki announcing the breakage of everything

Or you could learn what semantic versioning is, and read the changelog before deciding to upgrade.

>># Changelog

>All notable changes to this project will be documented in this file.

>This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

 -- https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md

**Comment by alber70g** [comment]
What is the migration path to keep the old behaviour? It's not listed in the changelog, nor in the referenced PR, nor in the wiki

**Comment by koekeishiya** [comment]
If you want the old behaviour simply add a blanket rule:

`yabai -m rule --add app=".*" layer=normal`

**Comment by Vanderhoof** [comment]
@koekeishiya the fix above stopped working : {
Even after I changed the `layer` to `sub-layer`. What am I missing?

https://github.com/koekeishiya/yabai/assets/12543857/02642639-434a-4253-a912-4b9b7e2f91f0

**Comment by imshenshen** [comment]
> @koekeishiya the fix above stopped working : { Even after I changed the `layer` to `sub-layer`. What am I missing?
> 
>  Screen.Recording.2024-04-24.at.08.25.25.mov

only work for new window?
