### ISSUE TITLE
possibility of resizing windows on load in float layout

### ISSUE THREAD

**Issue by bysimeon** [koekeishiya/yabai#189]
it could be convenient to force windows (finder windows for example) to be a fixed dimension on load within a float layout. this way, a new window won't open as half the screen (or whatever else) in float because that was it's state when closed in bsp.

**Comment by dominiklohmann** [comment]
Assuming you're running latest master: Filter by `app="^Finder$"` for the signal `event=window_created`. Check if the space you're on is a floating space or if the window is floating and if it is, resize the window to a fixed size. You can read the window id in the signals action using `$YABAI_WINDOW_ID`, and should use it as a window selector.

**Comment by koekeishiya** [comment]
You can do that using rules as well.  See the *--grid* option.
