### ISSUE TITLE
Possible for yabai to put any external bars in the no click zone when moving displays

### ISSUE THREAD

**Issue by kabeersvohra** [koekeishiya/yabai#1892]
As a follow up to https://github.com/koekeishiya/yabai/issues/1857 this happens on my setup because I also have a lower bar using sketchybar, and I have set the external bar like below:

```
yabai -m config external_bar all:0:25
```

Is it possible to also exclude this area from the area that the mouse clicks on when it is moving between displays for focus purposes? I have numbers for different spaces there and when i move the mouse, sometimes it will auto change the space which is not desired.

Thanks

**Comment by koekeishiya** [comment]
Sounds like it should be fairly trivial to do.
