### ISSUE TITLE
how to set layer for haze window (like Hazeover/Blurred)

### ISSUE THREAD

**Issue by jqtmviyu** [koekeishiya/yabai#1895]
OS: macos Monterey 12.7
version: 6.0.0

I use [Blurred](https://github.com/dwarvesf/Blurred) to dim the inactive window before.
After #1887, all managed (read: tiled) windows will appear at a level lower (layer "below"). But haze window keep `normal`.

I use `yabai -m query --windows` but can't find info of haze window.

Is there anyway to set the haze window layer to `below`, or set all default layer to `normal`.

**Comment by Pandoks** [comment]
Second the set all default layer to `normal`

**Comment by Pandoks** [comment]
Found a hacky way to get around it. 
```
yabai -m rule --add app!="^(Arc|Linear|Mail|iTerm2|Discord|Spotify|Notion|Figma)$" manage=off layer=below
```
Basically set all the normal windows to below.

**Comment by jqtmviyu** [comment]
> Found a hacky way to get around it.
> 
> ```
> yabai -m rule --add app!="^(Arc|Linear|Mail|iTerm2|Discord|Spotify|Notion|Figma)$" manage=off layer=below
> ```
> 
> Basically set all the normal windows to below.

With tested, `rule for appname` cat match haze window. 

For the apps which `manage=off layer=below`, using command `yabai -m window --toggle float`,  change to float mode set layer `normal`, but back to bsp mode not set layer to `below`.

All this is too confusing for me. I will keep it at 5.0.7 and wait  for a while.

**Comment by thezacharytaylor** [comment]
> Found a hacky way to get around it.
> 
> ```
> yabai -m rule --add app!="^(Arc|Linear|Mail|iTerm2|Discord|Spotify|Notion|Figma)$" manage=off layer=below
> ```
> 
> Basically set all the normal windows to below.

I find some apps/windows not taking that rule for some reason. i.e. Signal

Gonna rollback as well, too inconvenient.

**Comment by Pandoks** [comment]
> > Found a hacky way to get around it.
> > ```
> > yabai -m rule --add app!="^(Arc|Linear|Mail|iTerm2|Discord|Spotify|Notion|Figma)$" manage=off layer=below
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Basically set all the normal windows to below.
> 
> I find some apps/windows not taking that rule for some reason. i.e. Signal
> 
> Gonna rollback as well, too inconvenient.




> > Found a hacky way to get around it.
> > ```
> > yabai -m rule --add app!="^(Arc|Linear|Mail|iTerm2|Discord|Spotify|Notion|Figma)$" manage=off layer=below
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Basically set all the normal windows to below.
> 
> With tested, `rule for appname` can't match haze window.
> 
> For the apps which `manage=off layer=below`, using command `yabai -m window --toggle float`, change to float mode set layer `normal`, but back to bsp mode not set layer to `below`.
> 
> All this is too confusing for me. I will keep it at V5.0.7 and wait for a while.

How do yall rollback?

**Comment by koekeishiya** [comment]
On master and in next release you can do `yabai -m rule --add app=".*" layer=normal`.
