### ISSUE TITLE
How can I replace topmost?

### ISSUE THREAD

**Issue by kingtosh** [koekeishiya/yabai#1898]
If I want to fix the window to the topmost position, what is the alternative to topmost?
Thank you in advance.

**Comment by Jacky-Lzx** [comment]
As far as I know, you can set the `layer` option of a window to `above` to fix it to the topmost position.

As stated in #1887, tiled windows are at layer `below`, and standard windows are at layer "normal" (floating window at "normal" as well).

Check the manual for the usage of the `--layer` option.

**Comment by maobai405** [comment]
yabai -m signal --add event=window_focused action="yabai -m window --layer above"

**Comment by AndreasNasman** [comment]
Here is my migration from a topmost toggle to a layer toggle keybinding with skhd (using fish).

```diff
# skhdrc
-lalt - t: yabai --message window --toggle topmost
# Use `--raw-output` to strip double quotes from `jq` output.
+lalt - t: yabai --message window --layer (if [ (yabai --message query --windows --window | jq --raw-output .layer) = 'below' ]; echo 'normal'; else; echo 'below'; end)
```

I use this keybinding to put e.g. Calculator (configured to have `manage=off`) on top of managed windows.

**Comment by jqtmviyu** [comment]
using bash/zsh :

alt - t: layer="$(yabai --message query --windows --window | jq --raw-output .layer)" && yabai --message window --layer "$([ "$layer" = 'below' ] && echo 'normal' || echo 'below')"

**Comment by mefengl** [comment]
Or just:

```
alt - b: yabai -m window --layer below
alt - n: yabai -m window --layer normal
alt - a: yabai -m window --layer above
```

**Comment by alexlyzhov** [comment]
For reference, this now seems to be sub-layer instead of layer: `yabai -m window --sub-layer above`
