### ISSUE TITLE
Yabai keeps tiling invisible windows in Stage Manager

### ISSUE THREAD

**Issue by lethefrost** [koekeishiya/yabai#1899]
Seems like yabai is currently incompatible with stage manager. In a bsp space it will try to tile all the windows regardless they are visible/on stage or not. 

with yabai-v6.0.0, macOS Sonoma 14.0, arm64

@dominiklohmann has post #1297 [comment](https://github.com/koekeishiya/yabai/issues/1297#issuecomment-1148917641) and #1580 a year ago - is there any update or workaround? Thanks in advance!

**Comment by koekeishiya** [comment]
No update really. I don't know of any way to detect that a window is in stage manager. The workaround is to just not use stage manager and yabai at the same time. Closing in favour of #1580
