### ISSUE TITLE
Fullscreen windows break the space number when starting service with rule

### ISSUE THREAD

**Issue by lethefrost** [koekeishiya/yabai#1900]
Reproduce steps:
- I have a builtin screen and external monitor, the builtin screen is set to be the main screen, and arranged at the left
- the builtin screen holds spaces 1,2,3,4, and external screen holds 5,6,7,8
- if there's a full screen window right after space 4, on the builtin screen
- my `.yabairc` has rules
  ```sh
  yabai -m config layout                       bsp
  yabai -m config --space 1 layout             float
  yabai -m config --space 2 layout             float
  yabai -m config --space 7 layout             float
  yabai -m config --space 8 layout             float
  ```
- and run `yabai --start-service`
- what is expected behavior: space 1,2,7,8 should be float, and 3,4,5,6 should be bsp
- what is the actual behavior: space 6 becomes float, and space 8 becomes bsp

There might be some bugs counting the space numbers. For example, what first came up to me is that yabai might think the full screen window is space5, and space5->6, space6->7(which makes it float according to the rule), space7->8, and space8->9(which fall back into the default bsp). The space numbers I'm referring to are the ones determined by the OS and showing in the mission control interface under the thumbnails of the spaces.

**Comment by koekeishiya** [comment]
This space ordering is intentional, because it needs to be possible to do `yabai -m space --focus 7` to focus a native-fullscreen space.
