### ISSUE TITLE
Window borders doesn't show 

### ISSUE THREAD

**Issue by Levvonci** [koekeishiya/yabai#1902]
Hi, after the last upgrade the borders of my windows stopped working, I tried reinstalling yabai, modifying the config file and killing the process, but they still don't work, any ideas?

**Comment by hbthen3rd** [comment]
Check [Changelog](https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#removed):
Window borders (and all related options/properties) have been removed with version 6.0.0 (#1889).

**Comment by Levvonci** [comment]
sry, didn't read last changelog.
Thanks for help
