### ISSUE TITLE
Window Modification functions not working.

### ISSUE THREAD

**Issue by KuangyeChen** [koekeishiya/yabai#1905]
After upgrading system to Sonoma, window modification functions stop working.
Does anyone find similar problems? Do I need to grand some permissions?

functions from configs like:
```
# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# window border
yabai -m config window_border                on
yabai -m config window_border_blur           off
yabai -m config window_border_width          1
yabai -m config window_border_hidpi          off
yabai -m config window_border_radius         11
yabai -m config active_window_border_color   0xffe1e3e4
yabai -m config normal_window_border_color   0xff2a2f38
yabai -m config insert_feedback_color        0xff9dd274
```

**Comment by KuangyeChen** [comment]
csrutil status returns:
```
❯ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

**Comment by loveshadowfiend** [comment]
I've fixed that by restarting my mac

**Comment by KuangyeChen** [comment]
After a few hours of explorations, I've fixed my problems: 

- The sha256 is changed after upgrade, reconfigure it according to [this](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition).
- It seems that the window border config is no longer supported, comment them in config.
- Restart everything.

**Comment by cloud-wanderer** [comment]
@KuangyeChen 
I've ran into the same issue after the last update of yabai via brew just minutes ago. My border does not show up anymore. I've tried the hints listed here, including restart, restart service etc. but that did not help. I'm using yabai with SIP enabled (some hammerspoon coding can help for some things even with SIP on)

Here's the log. _window_topmost_ is removed according to the release notes, but it seems that **more than topmost was removed, as the commands are _unknown_** 

yabai: System Integrity Protection: Filesystem Protections and Debugging Restrictions must be disabled!
unknown command 'window_topmost' for domain 'config'
unknown command 'on' for domain 'config'
unknown command 'window_border' for domain 'config'
unknown command 'on' for domain 'config'
unknown command 'window_border_width' for domain 'config'
unknown command '1' for domain 'config'
unknown command 'active_window_border_color' for domain 'config'
unknown command '0xff8789c9' for domain 'config'
unknown command 'normal_window_border_color' for domain 'config'
unknown command '0xff555555' for domain 'config'
 yabai configuration loaded..

**Comment by MaximilianHeidenreich** [comment]
@cloud-wanderer Thx for the snippet, if you want rounded corners, just add `roundedRectRadii = { xRadius = 11.0, yRadius = 11.0 },` to the rectangle element config.

```lua
...
indicatorWIN = hs.canvas.new { x = max.x, y = max.y, h = max.h, w = max.w }:appendElements({
		type = "rectangle",
		action = "stroke",
		strokeWidth = 2.0,
		roundedRectRadii = { xRadius = 11.0, yRadius = 11.0 },
		strokeColor = { red = 98 / 255, green = 157 / 255, blue = 255 / 255 },
		frame = { x = f.x, y = f.y, h = f.h, w = f.w }
	}):show()
...
```
