### ISSUE TITLE
Dock animation freeze

### ISSUE THREAD

**Issue by simonemargio** [koekeishiya/yabai#1909]
During the execution of Yabai, there are moments when the animation of **appearing and scrolling** between icons in the dock completely freezes. Stopping the service resolves the issue.

The attached video provides a more precise demonstration of the problem.

Additional information:

- Yabai version: v6.0.0
- macOS Sonoma 14.0 (23A344)
- Apple Silicon-based device
- SIP (System Integrity Protection) is not disabled.
<details>
    <summary><b>Configuration file</b></summary><br/>

```
# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# autofocus windows when mouse pass over
yabai -m config focus_follows_mouse autofocus

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt

# set modifier + left-click drag to move window
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap


# disable specific apps
# English USA
yabai -m rule --add app="^System Settings$" layer=above manage=off
yabai -m rule --add app="^Music$" layer=above manage=off
...
```
  </details>

https://github.com/koekeishiya/yabai/assets/22590804/a1a66696-b556-4989-9730-906b3dc16af1

**Comment by kola-web** [comment]
@simonemargio try it
yabai -m signal --add event=application_front_switched action="yabai -m window --layer normal"

**Comment by simonemargio** [comment]
> @simonemargio try it yabai -m signal --add event=application_front_switched action="yabai -m window --layer normal"

Unfortunately, it doesn't work. 

However, I've noticed that the problem is related to:
`yabai -m config focus_follows_mouse autofocus`

If I disable it, the dock animation works perfectly, but I would have to give up autofocus.

**Comment by kola-web** [comment]
auto focus try it
```sh
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"


```

**Comment by simonemargio** [comment]
> auto focus try it @simonemargio
> 
> ```shell
> yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
> yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"
> ```

It works, thanks for the help!
