### ISSUE TITLE
limelight has been removed, is there an alternative for window boarder if disable SIP could not be an option?

### ISSUE THREAD

**Issue by minicoderwen** [koekeishiya/yabai#1911]
https://github.com/koekeishiya/limelight
now 404.

**Comment by gldtn** [comment]
Window border has been removed completely 
See: 

- https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#600---2023-10-10
- https://github.com/koekeishiya/yabai/issues/1889

**Comment by spwx** [comment]
Limelight was a separate program by the same author of this repo which could provide window borders.

If anyone finds a solutions for borders it would be useful to share here, and reference in the wiki.

**Comment by aiguofer** [comment]
Hoping for some solution as well! It's hard to know which window has focus. I used borders to distinguish for a while, but now that they're gone I keep typing into the wrong window :(

**Comment by jqtmviyu** [comment]
1. Downgrade to the old version, eg 5.0.7. Using `Blurred.app` or `Hazeover`.
2.
```
yabai -m config window_opacity                on
yabai -m config active_window_opacity         1.0
yabai -m config normal_window_opacity         0.9
yabai -m config window_opacity_duration       0.0
```

**Comment by gldtn** [comment]
I use slight bit of opacity to distinguish active windows apart as well.

**Comment by koekeishiya** [comment]
Limelight was broken on macOS Monterey and newer.

**Comment by koekeishiya** [comment]
Go nuts. 
[limelight.zip](https://github.com/koekeishiya/yabai/files/13124524/limelight.zip)

**Comment by cultlead3r** [comment]
If this hasn't been mentioned elsewhere: https://github.com/FelixKratz/JankyBorders
