### ISSUE TITLE
Everything as Normal Layer

### ISSUE THREAD

**Issue by Pandoks** [koekeishiya/yabai#1912]
I want everything to be on the default MacOS default layer. My layer config only works for the space that yabai starts in. This is my config right now:
```
# load scriping capabilities
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m config window_placement second_child

# bsp, stack, float
yabai -m config layout bsp

# padding
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0
# yabai -m config window_topmost on

# whitelist apps to be yabaied
yabai -m rule --add app!="^(Arc|Linear|Mail|iTerm2|Discord|Spotify|Notion|Figma)$" manage=off layer=normal
yabai -m rule --add app="^(Arc|Linear|Mail|iTerm2|Discord|Spotify|Notion|Figma)$" layer=normal
```
but it doesn't seem to work. This is the output of `yabai -m query --windows`:
```
[{
        "id":140,
        "pid":1087,
        "app":"iTerm2",
        ...
        "space":2,
        "level":0,
        "layer":"normal",
        "opacity":1.0000,
        "split-type":"none",
        "split-child":"second_child",
        ...
},{
        "id":97,
        "pid":1012,
        "app":"Discord",
        ...
        "space":5,
        "level":-20,
        "layer":"below",
        "opacity":1.0000,
        "split-type":"none",
        "split-child":"second_child",
        ...
},{
        "id":120,
        "pid":1062,
        "app":"Mail",
        ...
        "space":4,
        "level":-20,
        "layer":"below",
        "opacity":1.0000,
        "split-type":"none",
        "split-child":"second_child",
        ...
}]
```
And this is the output of `yabai -m rule --list`:
```
[{
        "index":0,
        "label":"",
        "app":"^(Arc|Linear|Mail|iTerm2|Discord|Spotify|Notion|Figma)$",
        "title":"",
        "role":"",
        "subrole":"",
        "display":1,
        "space":0,
        "follow_space":false,
        "opacity":0.0000,
        "manage":false,
        "sticky":null,
        "mouse_follows_focus":null,
        "layer":"normal",
        "native-fullscreen":null,
        "grid":"0:0:0:0:0:0"
},{
        "index":1,
        "label":"",
        "app":"^(Arc|Linear|Mail|iTerm2|Discord|Spotify|Notion|Figma)$",
        "title":"",
        "role":"",
        "subrole":"",
        "display":1,
        "space":0,
        "follow_space":false,
        "opacity":0.0000,
        "manage":null,
        "sticky":null,
        "mouse_follows_focus":null,
        "layer":"normal",
        "native-fullscreen":null,
        "grid":"0:0:0:0:0:0"
}]
```
Not sure if I'm doing anything wrong or if there is an option to make everything on the normal layer?

**Comment by Pandoks** [comment]
According to the documentation `yabai -m rule --add layer=normal` gives me `missing required key-value pair 'app[!]=..' or 'title[!]=..'`

**Comment by Pandoks** [comment]
https://github.com/koekeishiya/yabai/issues/1895#issuecomment-1763527152

**Comment by adorabilis** [comment]
I use a combination of layouts (bsp, stack, float) and 6.0 with its changes to window layering broke my workflow. Screen recording apps (e.g. Discord) can’t capture individual windows where `layer=below`. Notification center displays below the focused window if `layer=normal`. After experimenting, I found this to be the most reliable way to restore pre-6.0 behaviour:

```bash
# Always show notification centre above all windows
yabai -m rule --add app="^Notification Cent.*$" layer=above

# Set all windows layer to normal
yabai -m signal --add event=application_front_switched action="yabai -m window --layer normal"
```

**Comment by Pandoks** [comment]
> I use a combination of layouts (bsp, stack, float) and 6.0 with its changes to window layering broke my workflow. Screen recording apps (e.g. Discord) can’t capture individual windows where `layer=below`. Notification center displays below the focused window if `layer=normal`. After experimenting, I found this to be the most reliable way to restore pre-6.0 behaviour:
> 
> ```shell
> # Always show notification centre above all windows
> yabai -m rule --add app="^Notification Cent.*$" layer=above
> 
> # Set all windows layer to normal
> yabai -m signal --add event=application_front_switched action="yabai -m window --layer normal"
> ```

Kinda works. I have problems with my solution and your solution also doesn't fully fix some issues. Wish there was a way to just make everything normal layer :(

**Comment by juandpinto** [comment]
> ```shell
> # Always show notification centre above all windows
> yabai -m rule --add app="^Notification Cent.*$" layer=above
> 
> # Set all windows layer to normal
> yabai -m signal --add event=application_front_switched action="yabai -m window --layer normal"
> ```

This gets mostly there, but when I have multiple windows of the same app running, things get really weird. I still don't understand why this huge change was made to layers that broke so many people's workflows.

**Comment by shrugalic** [comment]
I had something similar happen with `manage=off` apps. A workaround is in https://github.com/koekeishiya/yabai/issues/1929

(Basically `yabai -m rule --add app=".*" layer=normal` and more rules for apps with special needs)

**Comment by koekeishiya** [comment]
use `yabai -m rule --add app=".*" layer=normal` in v6.0.3.

**Comment by xiantang** [comment]
https://vim0.com/en/post/yabai_window_sometime_in_the_below/ i just wrote a debugging blog for this issue.

**Comment by kola-web** [comment]
@xiantang 
![image](https://github.com/koekeishiya/yabai/assets/46446884/ce46919a-f62c-4259-94a9-bba7b6ad4a50)

**Comment by xiantang** [comment]
> https://vim0.com/en/post/yabai_window_sometime_in_the_below/ i

should be https://vim0.com/post/yabai_window_sometime_in_the_below/, last night i refactored my blog, so maybe break some feature.

**Comment by shrugalic** [comment]
What's to debug, isn't the issue solved?

To recap:
1. Add `yabai -m rule --add app=".*" layer=normal` to your rules
2. Run `yabai -m rule --apply` to apply all rules (including this one) to already open windows

Personally, I added point 2 to my `~/.config/yabai/yabairc`, because I routinely run an alias to `yabai --restart-service` after changing anything in the config.
