### ISSUE TITLE
Incorrect uninstall instructions.

### ISSUE THREAD

**Issue by seanptmaher** [koekeishiya/yabai#1915]
On the wiki it says:

The following steps will help you remove all traces of yabai from your system.
```
# stop yabai
yabai --stop-service
```
this does not work.
yabai: '--stop-service' is not a valid option!

**Comment by marovargovcik** [comment]
`--start-service` and `--stop-service` were added when `yabai` stopped using `homebrew services` and started using `launchd` for service management. I believe that was in version `5.0.4`. If you wish to uninstall `yabai` while using on an older version you can look up the change log of the wiki page to get to the version that aligns with your version of `yabai`.

**Comment by jwmann** [comment]
To add to the above, this is what you're looking for
https://github.com/koekeishiya/yabai/wiki/Uninstalling-yabai/0dbc8211a334c470448a2a31ff5d6fc0d7322fba
