### ISSUE TITLE
Focus automatically shifts to the main display

### ISSUE THREAD

**Issue by niba** [koekeishiya/yabai#1919]
Version: 6.0.0 
MacOS Ventura 13.5.2

There is a bug where the focus is being shifted to the main display.

It's easy to reproduce:
1. Open the macOS notes application on a display other than the main one.
2. Try to write something.
3. Every time the AutoCorrect feature in Notes activates, the focus shifts from the side display to the main display.

Disabling managing of Notes app with rules doesn't help.

This issue also occurred once while I was writing this text, so it is not limited to Notes. It's likely related to the AutoCorrect/AutoComplete feature on macOS.

**Comment by kimgunho** [comment]
yeah I'm having the same problem with

I am using vs code for development and when I go to arc, it is forcing me to go to the first main space.

**Comment by koekeishiya** [comment]
Should be fixed on master.
