### ISSUE TITLE
Bspwm inspired <WINDOW_SEL>: parent, brother, first or second (child)

### ISSUE THREAD

**Issue by kiryph** [koekeishiya/yabai#192]
Currently yabai provides following window selections:

```
WINDOW_SEL  := prev | next | first | last | recent | mouse | largest | smallest | DIR_SEL | window id
```

The [example configuration of bspwm](https://github.com/baskerville/bspwm/blob/master/examples/sxhkdrc) lists following mappings

```
# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}
```

IMHO they are a good fit for the layout bsp.

They also help the user to have the right picture of the underlying tree in his/her mind. Sometimes you forget which is a subnode of another which makes operations like changing the split type guess work. Consider following layout

```
+------------------+
|           |  W2  |
|           |      |
|           |------|
|     W1    |  W3  |
|           |      |
|           |------|
|           |  W4  |
|           |      |
+------------------+
```
Is `W4` a subnode of `W2` or `W3`? The picture on its own does not answer this.

Also operating on subtrees can be a powerful method to deal with several windows (e.g. closing). However, this would be a different issue.

Also a visual hint about the tree structure could be another feature request.

**UPDATE**

I think I understood the bsp concept not properly. Most importantly following two aspects were not clear to me:

- Each node in a tree either has zero or two children.
- Each leaf node holds exactly one window.

This means a window is always only a leave in the bsp tree, i.e. cannot be a parent or have children.

The possible trees for four windows are:
```
1)       a        2)     a
        / \             / \
       /   \           /   \
      b     c         W1    b
     / \   / \             / \
    W1 W2 W3 W4           W2  c
                             / \
                            W3 W4   
 ```                             
Note any permutation of `W<i>` is possible which again mean that you do not know which is the split partner.
                              
I think this feature request could be changed to two requests:

2. select window by uncle, brother, first and second nephew.
1. add the possibility to focus nodes not only windows (draw border around all contained windows)

**Comment by koekeishiya** [comment]
> add the possibility to focus nodes not only windows (draw border around all contained windows)

Focusing a node does not make sense, but I do agree that for example that closing all windows rooted at a given node could make sense. This sort of ties in to my reply in #190 where we have a separate domain to interact with nodes.

**Comment by koekeishiya** [comment]
Implemented `sibling`, `first_nephew`, `second_nephew`, `uncle`, `first_cousin`, `second_cousin`. Window queries will also include the attribute `split-child: first/second_child`(or `none` if not bsp-managed).
