### ISSUE TITLE
Is there any way to focus space without disabling system integrity protection?

### ISSUE THREAD

**Issue by Urie96** [koekeishiya/yabai#1923]
I noticed that `yabai -m window --space 1 --focus` works without disabling system integrity protection. It is also related to focus. So is it possible that `yabai -m space --focus 1` will work?

**Comment by descensiontohell** [comment]
if you just want to switch spaces without disabling SIP, there is a built-in shortcut in macOS in settings - keyboard - shortcuts - mission control

**Comment by hugodemenez** [comment]
> if you just want to switch spaces without disabling SIP, there is a built-in shortcut in macOS in settings - keyboard - shortcuts - mission control
> 
> this, however, will not disable the fade-in space switch animation

As I understand you're talking about the whole fade-in / switch animation.  You can reduce it by turning on the reduce motion setting in Accessibility > Display > Reduce motion (but there is still a bit of fade animation).

If you have any idea of how to reduce the latter, you're welcome !
