### ISSUE TITLE
`yabai` appearing multiple times in Privacy & Security → Accessibility

### ISSUE THREAD

**Issue by roelvangils** [koekeishiya/yabai#1924]
Is there a way to avoid this, and how can I find out which one is safe to remove? They keep coming back 🙂

<img width="827" alt="image" src="https://github.com/koekeishiya/yabai/assets/103744/91e67bc4-a471-4024-9a0e-958bea708309">

**Comment by koekeishiya** [comment]
This happens if you build from source (or install a fork?) and don't codesign the binary.

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

**Comment by tbezman** [comment]
For me, I found this happened every time I upgraded yabai. I just always manually remove the old one.

**Comment by ShroomKing** [comment]
> For me, I found this happened every time I upgraded yabai. I just always manually remove the old one.

Same, I build and codesign using yabai-cert but I get multiple entries anyway.

Removing the old one became part of my upgrade process lol

**Comment by koekeishiya** [comment]
> > For me, I found this happened every time I upgraded yabai. I just always manually remove the old one.
> 
> 
> 
> Same, I build and codesign using yabai-cert but I get multiple entries anyway.
> 
> 
> 
> Removing the old one became part of my upgrade process lol

Woks for me ¯\_(ツ)_/¯

**Comment by shrugalic** [comment]
> how can I find out which one is safe to remove?

The ones without icon are safe to remove. The newest one has an icon, and is usually the bottom-most.

**Comment by shrugalic** [comment]
> How to remove the old ones?

Select one and press the - button in the bottom left.

**Comment by koekeishiya** [comment]
See this comment https://github.com/koekeishiya/yabai/issues/2086#issuecomment-1939670967

> I guess this is happening because macOS stores the absolutepath when saving permissions, because yabai is a single binary application and not an app bundle. When homebrew upgrades yabai it places it in a folder specific to the version, so every brew upgrade causes the binary to be stored at a different path, effectively resetting the permissions.

>You can remove permissions directly inside the macOS settings/permissions window. Just remove stale entry when upgrading. I'm not aware of any workaround as long as you install using homebrew, due to the above situation.

>I never experience this personally because I of course build from source manually, and the target binary never changes its location -- therefore simply codesigning the new binary with the same certificate as the previous binary is enough for macOS to retain permissions.
