### ISSUE TITLE
Window opacity no longer works (for me) in v6.0.0

### ISSUE THREAD

**Issue by ghidalgo93** [koekeishiya/yabai#1925]
Since upgrading to v6.0.0 I've noticed that window opacity is no longer behaving as expected, there is no change in opacity between active & normal windows. I hadn't been using any opacity options recently as border options were the method I used to distinguish active windows, however, I saw your comments in the changelog about the [complete removal of window borders](https://github.com/koekeishiya/yabai/issues/1889), and while that's a bummer I can certainly understand and sympathize with your decision.

The removal of borders had me move over to opacity as my method of distinguishing active windows however I am unable to get opacity to work as I had back in the day when I first started using yabai (maybe v2.x...?).

Expected Behavior: When I set the `window_opacity` config option to `on` and set different opacity levels for active & normal windows I expect to see differences in opacity of these windows.

Actual Behavior: No changes to opacity

Steps to recreate:
1. add the following yabai config:
```
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.5
```
2. restart yabai with: `yabai --restart-service`
3. nothing changes, go back to docs
4. via [requirement docs](https://github.com/koekeishiya/yabai/wiki#installation-requirements) I see that:
```
yabai must be given Screen Recording permission if and only if you want to enable window animations, and will request access when necessary. The application must be restarted after access has been granted.
```
5. I was never requested for access to Screen Recording by yabai upon start/restart
6. manually add yabai to `System Settings -> Privacy & Security -> Screen Recording` permissions
7. restart yabai with: `yabai --restart-service`
8. no changes to opacity

I do see some [rework to window level & opacity](https://github.com/koekeishiya/yabai/issues/1887) in v6.0.0 however from my understanding of that PR opacity _should still_ apply_ to focus switches within the same space. Is this expected behavior at this point or should window opacity still be working?

**Comment by albertsj1** [comment]
Have you tried restarting your computer?  I had the same problem.  I restarted the computer and now opacity is working.

**Comment by tubbo** [comment]
I tried rebooting after updating the system extension (and its permissions), but I still don't have opacity working on macOS 13.4 Ventura. Are you on Sonoma @ghidalgo93? Just wondering if maybe this is a version-specific issue since I know v6 had a lot of Sonoma-specific compatibility changes.

**Comment by ademoverflow** [comment]
I'm on Sonoma v14.2.1, csrutil disabled completely, yabai configured with opacity like @ghidalgo93 did.
Gave the screen recording access to yabai, restarted the service and even completely reboot did not work.
