### ISSUE TITLE
[improvement] when moving space to another display

### ISSUE THREAD

**Issue by rwijtvliet** [koekeishiya/yabai#1926]
Currently, when moving a space from one display to another, there are 2 issues that I suggest could be improved:

* The order of the spaces is indeterminate. I.e., it is unclear, where the space will move to in the mission control index. To make this determinate, the spaces *on each display* could be sorted (e.g. by their labels) whenever a space is moved to another display.

* The focus may move to another window. Here the improvement is to keep track of the focused window before the move and refocus it afterwards.

**Comment by rwijtvliet** [comment]
For the first improvement, I have currently a (very elaborate) solution. 

1. I wrote a wrapper around `yabai` in python (because I'm terrible at bash) to be able to handle the API using objects.
   The package is here: [https://github.com/rwijtvliet/yabaipy](https://github.com/rwijtvliet/yabaipy)

2. Its command line interface is called from `skhdrc`: 
   ```
   # (space) to monitor
   alt + cmd + shift - g : \
       ~/python/yabaipy/cli.py send_to_display west
   alt + cmd + shift - l : \
       ~/python/yabaipy/cli.py send_to_display east
    ```
   [Here](https://github.com/rwijtvliet/dotfiles/blob/a407ff09090d05ddb3856c7bff937b67718f0aa3/windowmanager/macos/skhdrc#L82) is the entire file.

**Comment by windowsrefund** [comment]
Why would anyone move a space to another display? Seems to me that just adds another level of "running around after your applications". This would be the equivalent of rearranging your home every time you enter and leave a room.

**Comment by rwijtvliet** [comment]
Here is one scenario. I work on the laptop. Then, when I arrive to the office, I split the spaces over the laptop's internal display and the external monitor. When I leave, i unplug and all spaces that were on the external monitor are moved back onto the laptop's display. In some order which I'd like to be _the_ order. 

Here is another one. While working in the office, I have my email space or my teams space open on the laptop monitor while I'm coding. That way, I can keep an eye on incoming mail. Then, at some point I decide to sit down and reply to a many emails at once. To do this, I move the email space to the big external monitor, and once I'm done, I move it back to the laptop's.

**Comment by koekeishiya** [comment]
#2114
