### ISSUE TITLE
Ann odd ball but given the project.... (set Dock FPS)

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [koekeishiya/yabai#1928]
Since this project already deals with injecting itself into Dock.app I was thinking how viable is it to implement framerate control? Or is this not inside Dock and something much lower level? Using 2019 mbp it runs so much nicer and smoother when there is an external 120 hz display connected because it makes Dock run @ 120fps native (even on 60hz panel). So I was thinking maybe there is some useful work that was done that can help achieve that without having to rely on 120hz panel.

Thanks

**Comment by koekeishiya** [comment]
I don't think this is handled by the Dock itself. At least I don't know much about this.
