### ISSUE TITLE
Windows of manage=off applications always in foreground, hiding all non-float windows

### ISSUE THREAD

**Issue by shrugalic** [koekeishiya/yabai#1929]
On my main display, I generally use `layout bsp` to have windows managed, with a few exceptions. For example my IDE's single window is displayed on the main display, and it is set to `manage=off` via rule.

I'd like to open other applications' windows on the same display and space, and have them managed. This no longer works, maybe since yabai v6.0.0?

The IDE (with `manage=off`) keeps its window in front of any other windows (unless the other window is also set to `float`).

Does anyone else have this issue?

Maybe there is some adaptation I need to make in my config. I've removed all `window_border` stuff, and anything else that resulted in error messages in the log.

Here's my full config for reference:
```
# Load scripting additions
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Rules
yabai -m rule --add app="^System Settings$" sticky=on
yabai -m rule --add app="^Little Snitch$" sticky=on
yabai -m rule --add app="^Eclipse$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^LaunchBar$" manage=off

# Automatically float non-resizable windows, such as palettes, system settings etc.
yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | /Users/boli/.nix-profile/bin/jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'

# Override default layout for last space only (that's the one on the secondary screen)
yabai -m config --space 7 layout float

# Override gaps for certain spaces only: Eclipse
yabai -m config --space 3 top_padding 0 bottom_padding 0 left_padding 0 right_padding 0

# Global Settings
yabai -m config                                  \
    layout                       bsp             \
    auto_balance                 off             \
    split_ratio                  0.5             \
    top_padding                  4               \
    bottom_padding               4               \
    left_padding                 4               \
    right_padding                4               \
    window_gap                   4               \
    window_origin_display        default         \
    window_placement             second_child    \
    window_shadow                on              \
    window_animation_duration    0.0             \
    window_opacity_duration      0.0             \
    active_window_opacity        1.0             \
    normal_window_opacity        0.95            \
    window_opacity               off             \
    insert_feedback_color        0xffd75f5f      \
    mouse_modifier               ctrl            \
    mouse_action1                move            \
    mouse_action2                resize          \
    mouse_follows_focus          off;
```

**Comment by lijiachang** [comment]
i have same question， those app always in front，

**Comment by logicalbhanu** [comment]
i am also facing the same issue, anybody any solution?

**Comment by ntananh** [comment]
I'm facing this issue also

**Comment by wthueb** [comment]
You have to set `layer=below` on the unmanaged app as well. This leads to some weird focus issues if you cmd+tab from another space and stuff, but that's the best you can do for now. This was introduced in v6.0.0.

**Comment by shrugalic** [comment]
> You have to set `layer=below` on the unmanaged app as well.

This also results in the unmanaged application to always be in the back. Whenever any managed window is open on the same screen, the unmanaged app's window is partially hidden. That is just as undesired as having the unmanaged window always in the front.

**Comment by nocksock** [comment]
Unless changed by a rule, [every window starts with the layer "below"](https://github.com/koekeishiya/yabai/blob/40d1075560ea0d110a99cf017dd0831f30a02503/src/space_manager.c#L384). And when a window is turned [into a floating window, it's set to normal](https://github.com/koekeishiya/yabai/blob/40d1075560ea0d110a99cf017dd0831f30a02503/src/space_manager.c#L123).

Setting the default layer to normal using a rule will result in a (probably) more intuitive behavior

```sh
yabai -m rule --add app=".*" layer=normal
```

Adding a `layer=normal` to the rules that have `manage=off` should probably also do the trick - and won't affect windows without a rule. 

Usually when I turn a managed window into an unmanaged, the new behavior is actually the one I wanted so this made my keymap a bit simpler. But the layer-value should probably remain unchanged when untiling a window.

**Comment by shrugalic** [comment]
> Adding a `layer=normal` to the rules that have `manage=off` should probably also do the trick

It does not, by itself. But when also adding the rule you mentioned it works. Thank you! 🙏

**Comment by shrugalic** [comment]
> It does not, by itself. But when also adding the rule you mentioned it works. Thank you! 🙏

Hmm, this only worked temporarily for some reason. Now with all windows using `layer=normal` the ones with `manage=off` are still in front of all the others, and it does not change when switching applications/windows.

**Comment by albertsj1** [comment]
> This only worked temporarily for some reason. Now with _all_ windows using `layer=normal` the ones with `manage=off` are still permanently in front of all the others.
> 
> However, keeping the non-managed windows/applications at `layer=below` seems to work (for now):
> 
> ```
> yabai -m rule --add app=".*" layer=normal
> yabai -m rule --add app="^Eclipse$" manage=off layer=below
> yabai -m rule --add app="^1Password$" manage=off layer=below
> yabai -m rule --add app="^LaunchBar$" manage=off layer=above
> ```
> 
> My main issue is with _Eclipse_, which takes up my main display a lot. The only occasionally visible _LaunchBar_ should appear above all others.

I tried this and thought it worked; however, unfortunately all apps still default to having layer=below.
I've confirmed this by stopping and then starting yabai and running the following:
```bash
yabai -m query --windows  | jq '.[].layer'
"below"
"below"
"below"
"below"
```

**Comment by koekeishiya** [comment]
I'll make it so that windows which have layers changed through `window --layer` commands or rules will be exempt from the automatic layer handling that happens when making a window managed/floating.

No ETA though.

**Comment by koekeishiya** [comment]
Fixed on master. Add something like the following rule to restore pre-v6 behaviour: `yabai -m rule --add app=".*" layer=normal`

**Comment by multi** [comment]
@koekeishiya After [commit](https://github.com/koekeishiya/yabai/commit/3ee735f661c19f78173bfc1c6ecc5645caf032e1) `Notification Center` can be shown only if 1) a `Finder` window is currently focused; 2) on a empty space;

For the following rules:

```
yabai -m config layout stack
...
yabai -m rule --add app=".*" layer=normal
yabai -m rule --add app=Finder manage=off
...
```

**Comment by logicalbhanu** [comment]
i see the same issue, just one addition here, notification center can be showed if any unmanaged window is currently focused not just the finder, or on an empty space.

**Comment by multi** [comment]
@koekeishiya It's fine now, thank you!

**Comment by Liquidmantis** [comment]
@koekeishiya it seems like maybe this is somewhat broken?  

This rule isn't working now for making my Neovide window always on top.  When I query windows, they're all 'normal'.  Neovide is floating as expected, just not on top of all the normal windows.

`yabai -m rule --add title="Neovide"             manage=off layer=above`

**Comment by koekeishiya** [comment]
Can you post the query output for the neovide window

**Comment by Liquidmantis** [comment]
```
[{
	"id":78,
	"pid":1590,
	"app":"kitty",
	"title":"tmux",
	"frame":{
		"x":12.0000,
		"y":12.0000,
		"w":1262.0000,
		"h":702.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":1,
	"level":0,
	"layer":"normal",
	"opacity":1.0000,
	"split-type":"horizontal",
	"split-child":"first_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":true,
	"has-shadow":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":81,
	"pid":1595,
	"app":"Obsidian",
	"title":"pci - notes - Obsidian v1.5.3",
	"frame":{
		"x":1286.0000,
		"y":12.0000,
		"w":1262.0000,
		"h":1416.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":1,
	"level":0,
	"layer":"normal",
	"opacity":1.0000,
	"split-type":"vertical",
	"split-child":"second_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":80,
	"pid":1607,
	"app":"Spotify",
	"title":"Spotify Premium",
	"frame":{
		"x":12.0000,
		"y":726.0000,
		"w":1262.0000,
		"h":702.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":1,
	"level":0,
	"layer":"normal",
	"opacity":1.0000,
	"split-type":"horizontal",
	"split-child":"second_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":8894,
	"pid":26986,
	"app":"Neovide",
	"title":"Neovide",
	"frame":{
		"x":649.0000,
		"y":12.0000,
		"w":625.0000,
		"h":702.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":1,
	"level":0,
	"layer":"normal",
	"opacity":1.0000,
	"split-type":"none",
	"split-child":"none",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":true,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":true,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":10579,
	"pid":1606,
	"app":"Notes",
	"title":"Notes",
	"frame":{
		"x":12.0000,
		"y":726.0000,
		"w":1262.0000,
		"h":702.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":2,
	"level":0,
	"layer":"normal",
	"opacity":1.0000,
	"split-type":"horizontal",
	"split-child":"second_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":false,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":83,
	"pid":1604,
	"app":"Mimestream",
	"title":"Inbox",
	"frame":{
		"x":1286.0000,
		"y":12.0000,
		"w":1262.0000,
		"h":1416.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":2,
	"level":0,
	"layer":"normal",
	"opacity":1.0000,
	"split-type":"vertical",
	"split-child":"second_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":false,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
},{
	"id":5295,
	"pid":56895,
	"app":"Slack",
	"title":"team-cloud-infra - HashiCorp, Inc - Slack",
	"frame":{
		"x":12.0000,
		"y":12.0000,
		"w":1262.0000,
		"h":702.0000
	},
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"root-window":true,
	"display":1,
	"space":2,
	"level":0,
	"layer":"normal",
	"opacity":1.0000,
	"split-type":"horizontal",
	"split-child":"first_child",
	"stack-index":0,
	"can-move":true,
	"can-resize":true,
	"has-focus":false,
	"has-shadow":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"is-native-fullscreen":false,
	"is-visible":false,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
}]
```

**Comment by Liquidmantis** [comment]
@koekeishiya I'm sorry to waste your time.  This is my work computer which I recently had to re-enable SIP on.  I just tested my personal computer and everything seems to work as expected.  Neovide floats on top and has a layer of "above".

**Comment by koekeishiya** [comment]
Aight no problem.

**Comment by logicalbhanu** [comment]
i think this bug has resurfaced again, in the current verison of yabai "yabai-v7.0.2", i am using below settings as mentioned in the discussion

# rule to adress bug in version 6+
yabai -m rule --add app=".*" layer=normal
# previously the workaround is to use  'layer=below' string in all 
# the unmanaged application rule that is the below rules something like
# yabai -m rule --add app="^System Settings$" manage=off layer=below 
# and the above rule is not used then.

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Commander One$" manage=off
yabai -m rule --add app="^Terminal$" manage=off
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^kitty$" manage=off
yabai -m rule --add app="^chat$" manage=off
yabai -m rule --add app="^gpt4all$" manage=off
yabai -m rule --add app="^Marta$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^Clock$" manage=off
yabai -m rule --add app="^AltTab$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Notes" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Obsidian$" manage=off
yabai -m rule --add app="^FreeTube$" manage=off
yabai -m rule --add app="^YouTube Music$" manage=off
yabai -m rule --add app="^Asana$" manage=off
yabai -m rule --add app="^Kodi$" manage=off
yabai -m rule --add app="^Stocks$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Double Commander$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^G2FA$" manage=off

but my unmanaged windows are still on top even if they are not focussed, like this 
<img width="1512" alt="image" src="https://github.com/koekeishiya/yabai/assets/40262328/cf1082a2-d6e1-48d5-97c4-3f508555145a">
in the above settings is not under focussed (firefox is in focus), but still system settings is on top of firefox.

**Comment by shrugalic** [comment]
Yes, it seems this issue is back with v7.0.2. Also, when starting `yabai` manually, it complains about `unknown key 'layer'`

**Comment by koekeishiya** [comment]
Please read the changelog when the major version changes, it indicates that a breaking API change is made.

https://github.com/koekeishiya/yabai/issues/2128

**Comment by shrugalic** [comment]
Because this issue is closed, I opened https://github.com/koekeishiya/yabai/issues/2172.

**Comment by shrugalic** [comment]
> Please read the changelog when the major version changes, it indicates that a breaking API change is made.
> 
> #2128

Doh, sorry about the noise, and thanks a lot for your response! 🙏

I'll close the issue I just opened.

TL;DW for everyone, use `sub-layer` instead of `layer`:
```
yabai -m rule --add app=".*" sub-layer=normal
```
