### ISSUE TITLE
Why must displays have separate spaces

### ISSUE THREAD

**Issue by ohemelaar** [koekeishiya/yabai#193]
Hello,
Thanks for the awesome piece of software.
I'm wondering why this is required though:

> The Mission Control setting displays have separate spaces must be enabled.

As the codebase is quite recent I couldn't find something else than the initial commit that talks about it. Is it something mandatory "by design" that can not be changed without a complete rewrite, or is it just not supported yet?
Thanks.

**Comment by dominiklohmann** [comment]
When Mission Control was introduced on macOS with the release of OS X 10.7 as a replacement for Dashboard, Exposé and Spaces, much was changed about spaces compared to how they operated before, and the separate spaces setting has become the default, bringing many advantages:

- Windows can enter a native-fullscreen mode
- Spaces can be moved between displays
- Spaces always have a rectangular frame
- Applications can be assigned to specific spaces

Besides the fact that tiling windows is a hard problem to solve on spaces that are not necessarily rectangular, it really is not worth the engineering effort to handle a feature that is only available as a compatibility feature. I would not be surprised to see the option gone in future versions of macOS.

**Comment by koekeishiya** [comment]
yabai uses private functions for interacting with spaces and displays that have been reverse engineered and these functions rely on that setting being enabled. I simply cannot be bothered reverse engineering snd trying to support the legacy solution as I have never and likely will never make use of it.

yabai currently offer enougj functionality to reiplement sinultaneous space switching for multiple displays anyway.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
