### ISSUE TITLE
Have finder follow to current desktop when opened instead of getting stuck on desktop it was opened on?

### ISSUE THREAD

**Issue by cjdjpj** [koekeishiya/yabai#1932]
Is it possible to bind something to opening the finder window on whichever desktop I want? I already have finder set to `sticky=on layer=above manage=off` but opening finder only focuses the background "finder app" instead of the window.

**Comment by joshstobbs** [comment]
Not to bump a dead issue, but I'm wondering if you managed to solve this?  I am having a similar issue and am trying to hunt down a solution.

**Comment by cjdjpj** [comment]
Hey so I just sort of bypassed the issue by having a keybind open a random directory via skhd: `ctrl + shift - f : open .`

This isn't perfect since if I'm really deep into a directory and want to keep it whilst moving to a different desktop I'd still have to manually move the finder window but its good enough for me. I have access to a finder window and any directory within a few keypresses and clicks. I have to remember to close the window each time I'm done though, otherwise I'd have multiple windows over multiple desktops (which is a bit messy but fine as well)

Its much better than what I was previously doing which was searching for finder in alfred, having the finder app be focused but in the background, and having to manually go through the six desktops I have open to find the window.
