### ISSUE TITLE
MS Teams window sharing broken when window is tiled

### ISSUE THREAD

**Issue by kinglouie** [koekeishiya/yabai#1940]
OS: Sonoma 14.0
Yabai: 6.0

While Yabai is running ms teams can not see tiled windows, when I float them teams picks them up.
There must be logic in tiled windows preventing teams to see them.

**Comment by dirkfabisch** [comment]
Same issue. It seems, that it also is impacted by the Dock extension for fast switching between desktops.

**Comment by koekeishiya** [comment]
Same as #2009
