### ISSUE TITLE
daemon and scripting addition not working on MacOS14.1: Sonoma

### ISSUE THREAD

**Issue by aryamanjeendgar** [koekeishiya/yabai#1942]
So I just upgraded to MacOS14.1 and that broke `yabai` for me.

I was previously using the macports version (currently at `v5.0.8`) but I also tried using the upto-date brew installation (currently `v6.0.0` iirc) to no avail.

Right now, `yabai --start-service` does not work (the terminal just hangs, and has to be terminated explicitly) though it does work when in it's non-daemon mode by just calling `yabai`.

In addition, the scripting addition does not work which is super problematic for me because it basically kills my entire `yabairc` :(. My System Integrity Protection has been disabled (find the `csrutil status` output below). All of this was working fine with Ventura.

Thank you for your time! Please let me know if I can share some more information!

<img width="1325" alt="Screenshot 2023-10-28 at 3 27 18 PM" src="https://github.com/koekeishiya/yabai/assets/52452970/007c0285-9915-401e-ae05-2b5ff22cfca5">

**Comment by reoring** [comment]
@aryamanjeendgar dup #1936

**Comment by aryamanjeendgar** [comment]
The issue with the scripting addition is fixed as of [this commit](https://github.com/koekeishiya/yabai/commit/2c4e397e8dabc3720c17a68258677fc3e0937a61), thank you for all of the hard work!

However, the issue with `yabai --start-service` not working is still persistent --- as a workaround right now, to even run yabai, I need to have a dedicated terminal instance that _just_ runs yabai (currently have an open-and-forget `eshell` instance in emacs for doing just that) --- is this a known issue that others are facing as well?

Thanks!

**Comment by 24unix** [comment]
> The issue with the scripting addition is fixed as of [this commit](https://github.com/koekeishiya/yabai/commit/2c4e397e8dabc3720c17a68258677fc3e0937a61), thank you for all of the hard work!
> 
> However, the issue with `yabai --start-service` not working is still persistent --- as a workaround right now, to even run yabai, I need to have a dedicated terminal instance that _just_ runs yabai (currently have an open-and-forget `eshell` instance in emacs for doing just that) --- is this a known issue that others are facing as well?


Since the brew service stuff is not working any longer: Yes.
But I don't really care, when I reboot, I open a iTerm Client, 
- 1st tab yabai
- 2nd tab skhd
- 3rd tab spacebar
Then I minimize that iTerm  and are good to gor for the next weeks …

**Comment by aryamanjeendgar** [comment]
> 1st tab yabai
> 2nd tab skhd
> 3rd tab spacebar
> Then I minimize that iTerm and are good to go for the next weeks …

Yeah, this seems to be the only way to do it right now unfortunately :\ --- is this a well-documented issue? (opened up elsewhere), if so, I will go ahead and close this one.

**Comment by gldtn** [comment]
I've updated to Sonoma 14.1.1 (23B81) yesterday and yabai 6.0.1 has been working for me without a problem. Did you try reinstalling it? This is the approach I take for every update: https://github.com/koekeishiya/yabai/discussions/1904

I've seen another issue open where macports was causing problems as well, search for macports issue here as this might be related?

Hope it helps!
