### ISSUE TITLE
`yabai -m window --display x` causes crash in Sonoma 14.0 

### ISSUE THREAD

**Issue by tomelliot** [koekeishiya/yabai#1946]
Since updating to Sonoma, this command causes yabai to crash:

`yabai -m window --display [x]`

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000138d769842e0
Exception Codes:       0x0000000000000001, 0x0000138d769842e0

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
```

System
> Sonoma 14.0
> MacBook Air
> Apple M2
> 16 GB

Please let me know if there's more info I can provide, it's been easy to reproduce.

**Comment by alexus37** [comment]
I had the same issue, was resolved by upgrading to the latest version of yabai.
