### ISSUE TITLE
Proposal: Warn about the new versions of MacOS

### ISSUE THREAD

**Issue by srgtmshnk** [koekeishiya/yabai#1948]
When a new version comes up we are getting a lot of users having problems with broken yabai. I am not really into the MacOS internals, but I think this problem will never be solved any other way due to hooking Dock panel and maybe some API changes.

So it would be cool to see something like "DO NOT UPDATE YOUR MACOS VERSION UNTIL YABAI SUPPORTS IT" on top of the README.md

**Comment by Mmasson-01** [comment]
+1 for this

**Comment by yuser1337** [comment]
+1

**Comment by koekeishiya** [comment]
The majority of people don't read the docs/wiki/changelog, so in practice this is just more work for little reward.

I don't get why people prioritize to run beta versions and day1-updates of every single release either, when they obviously want to have a stable and well functioning workflow.

**Comment by srgtmshnk** [comment]
> The majority of people don't read the docs/wiki/changelog, so in practice this is just more work for little reward.
> 
> I don't get why people prioritize to run beta versions and day1-updates of every single release either, when they obviously want to have a stable and well functioning workflow.

i agree, but people who can write issues and wait for a new release on github can probably notice this warning. As for me, for example, i read the readme before the installation but anyway broke my yabai with a MacOS update, because i am new to this kind of software and just didnt expect it to break due to a minor update

**Comment by koekeishiya** [comment]
The reason it breaks with macOS updates is because the injection points change when Dock.app is modified.
Feel free to find/create a signature generator that works for both arm64 and x64 and submit a PR that improves this part of the system; https://github.com/koekeishiya/yabai/issues/1091#issuecomment-995808162
