### ISSUE TITLE
[Question] Is it really `csrutil **enable**` for Sonoma? Why not disable?

### ISSUE THREAD

**Issue by Explosion-Scratch** [koekeishiya/yabai#1949]
[This section](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection#how-do-i-disable-system-integrity-protection) of the wiki has the following:
```
#
# APPLE SILICON
#

# If you're on Apple Silicon macOS 13.x.x
# Requires Filesystem Protections, Debugging Restrictions and NVRAM Protection to be disabled
# (printed warning can be safely ignored)
csrutil enable --without fs --without debug --without nvram

# If you're on Apple Silicon macOS 12.x.x
# Requires Filesystem Protections, Debugging Restrictions and NVRAM Protection to be disabled
# (printed warning can be safely ignored)
csrutil disable --with kext --with dtrace --with basesystem

#
# INTEL
#

# If you're on Intel macOS 13.x.x, 12.x.x, or 11.x.x
# Requires Filesystem Protections and Debugging Restrictions to be disabled (workaround because --without debug does not work)
# (printed warning can be safely ignored)
csrutil disable --with kext --with dtrace --with nvram --with basesystem
```
Why is it `csrutil enable` instead of disable? Will `csrutil disable` also work here? Also will running this break macFuse?

**Comment by Explosion-Scratch** [comment]
Sorry for the question based issue, happy to close ASAP if I get an answer

**Comment by dseum** [comment]
It's probably just the way Apple configured the command on recent Silicon macOS. If you see, the `enable` and `disable` commands have distinct flags. It's like if you have a set of light switches, there are 2 ways of getting the same lights to be on: turn off everything except some set of them or turn on everything except some set.

For example, previously, it might've been okay to disable everything but the few listed, but with the recent Silicon macOS, they might've introduced some option that's specific to Apple Silicon that you don't need to disable, so it's easier (i.e., you need less flags) to just choose which ones to enable.

**Comment by Explosion-Scratch** [comment]
That makes sense. Appreciate it, so `crsutil disable` turns off all and `csrutil enable --without-[thing]` only disables `[thing]`
