### ISSUE TITLE
Some way of disabling swipe animations

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [koekeishiya/yabai#1950]
I know that technically one could use some third party software to handle swipe gestures and then trigger next and previous desktop, however I was curious if there maybe a possibility to somehow bypass those annoying switching desktop animations with yabai when using touch gestures? I know you could also like use reduced motion but it still has this atrocious fade in/fade out effect.

**Comment by koekeishiya** [comment]
Probably technically possible, but I am not interested in looking into it as I prefer animations on swipe gestures, and no animations with keyboard shortcuts. PR (with optional config to enable/disable) welcome if anyone wants to look into it themselves.
