### ISSUE TITLE
Prevent app from being focused when switching space

### ISSUE THREAD

**Issue by oddnugget** [koekeishiya/yabai#1957]
Greetings, ever since upgrading to MacOs Sonoma i have a strange issue. When i am screensharing in [tuple](https://tuple.app/) and i do a `yabai -m space --focus <space-id>`, the tuple app popup in the menu bar opens up and takes focus as the frontmost application. 

I have a rule already set up to not manage tuple: 
`yabai -m rule --add app="^Tuple$" manage=off`

And querying for windows in the space does not return a tuple window. Most probably because it is not a window but a popover or whatever they are called. 

I'm unsure if this is an issue on yabai side or on tuple itself, but i have confirmed that the issue is not present when yabai is not running (switching spaces natively with mission control).

Is there a way to prevent the app from being focused when switching spaces?

**Comment by Mmasson-01** [comment]
This look like same problem with Microsoft Teams. Refer to https://github.com/koekeishiya/yabai/issues/74

**Comment by oddnugget** [comment]
It looks yabai is ignoring windows with the AXPopover role by default, see #162. This means that window events are not reported and a signal like the one described in #74 doesn't work. Yabai just outputs `ignoring AXPopover window Tuple`.

**Comment by koekeishiya** [comment]
Popover windows are not ignored in the latest version of yabai. Closing this as duplicate of #2041
