### ISSUE TITLE
yabai -m window --space x - working only with one open app

### ISSUE THREAD

**Issue by lsnrafalc** [koekeishiya/yabai#1959]
Hello,
 
I have problem with moving windows between spaces, but only when i have more than one window open - Sonoma 14.1

Example.

desktop 1 - terminal
desktop 2 - chrome
desktop 3 - empty

When i use shortcut `alt - 1 : yabai -m window --space 2` and move terminal to desktop 2 it is working. Now i have 2 apps split  on desktop 2 terminal and chrome and this is the moment when command stop working. Can't move any app desktop nothing happen when i hit alt - 3, alt - 1.  If i manually move app to desktop 1 - empty and now use the command alt - x it is working. 

Pls help.

**Comment by alanmicah** [comment]
dup [#1936 ](https://github.com/koekeishiya/yabai/issues/1936)
