### ISSUE TITLE
Query focused window

### ISSUE THREAD

**Issue by hrvstr** [koekeishiya/yabai#196]
Hi, I am currently in the process of writing an Alfred workflow to "replace" skhd. I want to query the focused window to display some information about it.

The doc shows these arguments:
`WINDOW_SEL  := prev | next | first | last | recent | mouse | largest | smallest | DIR_SEL | window id
`

How can I select the window that is currently focused? Maybe it's possible with `jq`?

**Comment by dominiklohmann** [comment]
Just don't pass a selector, it defaults to the focused window.

**Comment by hrvstr** [comment]
Genius! Now I feel stupid...

**Comment by dominiklohmann** [comment]
For what it's worth, sometimes you wanna do only a single query and need both the focused window and the other windows as well. You can do that with `jq`.

```sh
# get the pid of the focused window, 
# then filter the query to show all windows that belong to the same process
yabai -m query --windows \
    | jq -er 'map(select(.focused == 1).pid)[0] as $pid 
            | map(select(.pid == $pid))' 
```
