### ISSUE TITLE
I want to make the window vibrate

### ISSUE THREAD

**Issue by akira-toriyama** [koekeishiya/yabai#1963]
Thank you for the wonderful app.

I want the window to vibrate when the window focus changes.

If you try to make it work too quickly, it won't work well. Do you have any tips?

```bash
yabai -m signal --add event=window_focused action="yabai -m window --move rel:20:20 && yabai -m window --move rel:-20:-20"
```

**Comment by alexander-blackwell** [comment]
If you want window border colors again you can use JankyBorders. https://github.com/FelixKratz/JankyBorders It works pretty well.

**Comment by Bellavene** [comment]
I have seen such possibility with [phoenix](https://github.com/kasper/phoenix)

**Comment by koekeishiya** [comment]
Vibrate might be a bit hard. You'd have to emulate this with a couple of sleep statements in your approach. Personally I would use the window opacity functionality of yabai to make the window flash:


The following will automatically flash the focused window when focus changes:
`yabai -m signal --add label="flash_focus" event="window_focused" action="yabai -m window \$YABAI_WINDOW_ID --opacity 0.1 && sleep $(yabai -m config window_opacity_duration) && yabai -m window \$YABAI_WINDOW_ID --opacity 0.0"`

You can run the following in your terminal window (or using a hotkey in skhd or w/e) to trigger the same effect manually:
`yabai -m window --opacity 0.1 && sleep $(yabai -m config window_opacity_duration) && yabai -m window --opacity 0.0`
