### ISSUE TITLE
`yabai -m query --windows` doesn't seem to list all windows

### ISSUE THREAD

**Issue by farzadmf** [koekeishiya/yabai#1966]
Hi,

I'm having a hard time understanding how `yabai -m query --windows` works. It doesn't seem to list "all" the windows I have open.

I tried restarting `yabai` and the returned list even got smaller. Is there a way for `yabai` to basically list "all windows in all spaces"?

**Comment by koekeishiya** [comment]
It lists the windows that yabai "knows exists". macOS APIs only return windows on the active space, so you have to visit every space once after starting yabai.

**Comment by farzadmf** [comment]
Thank you for the quick answer @koekeishiya. Is there a way to actually get all the windows? For example, `Hammerspoon` has a function called `hs.window.allWindows()` that lists all the windows. Can I achieve something similar with `yabai`?

Even if I manage to get the window ID using `Hammerspoon`, if I want to use `yabai` to play with the window, `yabai` says "could not find the window to act on"

Is there any way I can get around this? Having to go manually through all spaces seems very impractical for scripting :slightly_frowning_face:

**Comment by koekeishiya** [comment]
No idea what hammerspoon is doing. The AX api can only see windows on the active space.

You can do --spaces query in yabai and it will return the id of all windows, but you can't really do anything with it.

**Comment by farzadmf** [comment]
So, I'm mainly curious: how would we go about automating stuff (what's your personal approach)? Let's say, for some reason, I restart `yabai` or I have a hook for it to be restarted etc.

That would imply that I basically "lose control" of everything unless I manually visit all spaces?

**Comment by koekeishiya** [comment]
I'd just have a loop in my yabairc that focuses each space and return back to where I was. Mostly I just avoid restarting yabai outside of system reboots.

I don't use my mac a lot lately anyways, hence the inactivity.

**Comment by farzadmf** [comment]
> I'd just have a loop in my yabairc that focuses each space and return back to where I was

I tried doing this:
```zsh
for idx in $( yabai -m query --spaces | jq '.[] | .index' ); do
  yabai -m space --focus $idx
done

# Go back
yabai -m space --focus 1
```
But still not all my windows show up in `yabai -m query --windows`. At least in my case, it seems to have an issue with my Firefox window

> I don't use my mac a lot lately anyways, hence the inactivity.

Oh no!!! So `yabai` is going to be dead?? I just started using it more and more 🤔

**Comment by koekeishiya** [comment]
> But still not all my windows show up in yabai -m query --windows. At least in my case, it seems to have an issue with my Firefox window

Hmm not sure why that would be then. You can try to compile from source with some filters removed and see if that helps.
There are filters in place because literally everything visible on the screen on macOS is internally represented as a window, so I need to filter all of these away, and it could be that some of your windows get mixed up in this filter.

You can try to remove this filter here: https://github.com/koekeishiya/yabai/blob/master/src/space.c#L43 by simply removing the if-statement (keep the body ofc), and see if you get all the windows you expect (you will also get a ton of windows you definitely dont expect).

> Oh no!!! So yabai is going to be dead?? I

Well it has been in maintenance mode for a long time already, so in practice nothing really changes.

> And ... I'm curious: what are you using now if I may ask?

Windows and WSL mostly for work.

**Comment by farzadmf** [comment]
> I just stopped caring at this point)

I can TOTALLY relate; I was a Linux user myself and was SUUUUPER happy with it. I HATE x100 MacOS (THE most unintuitive of the 3), but I have to use it work.

But, honestly, `yabai` is the main thing allowing me to feel _a bit_ like Linux. I'm sure if MacOS didn't have these limitations, it could be much more powerful.

I personally thank you for creating `yabai` to make MacOS a tiny bit more tolerable (as I said, it's so messed up that it simply CANNOT become good, at least IMO) .... I honestly don't know why people are so much in love with this untuitive OS.

**Comment by joliss** [comment]
I'm not sure if this is a separate issue, but I'm noticing that `sleep 4; yabai -m query --windows` misses the following:

- [iStat Menus](https://bjango.com/mac/istatmenus/) dropdowns
- Chrome title text, such as the one you get when you hover the comic on [xkcd.com](https://xkcd.com/)

**Comment by koekeishiya** [comment]
Might be fixed on master.

**Comment by kerryj89** [comment]
It now shows CleanShot X's editor window in the list of windows - thanks!
