### ISSUE TITLE
Focus on Firefox failed to switch space

### ISSUE THREAD

**Issue by ixzh** [koekeishiya/yabai#1967]
I have Firefox main window in space 3 and its Downloads window in space 1.  Now close the Downloads, and switch to Firefox, it doesn't auto switch to space 3. Instead, if I manually go to space, now app switching will go to space 1 or 3 correctly. How can I make it go to space 3 main Firefox window when switching to it?

**Comment by koekeishiya** [comment]
Sounds like macOS behavior to me. Nothing to do here.
