### ISSUE TITLE
A concurrency problem with multiple processes concurrently resize and move the same window at the same time

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [koekeishiya/yabai#1971]
If two processes are running at the same time via 
```zsh
# Same time
# A process 
yabai -m window 119 --move abs:1290:956 
# B process
yabai -m window 119 --resize abs:1250:433 
```
Adjusting the size and position of the same window may cause concurrency problems, 

For example, when the window is moved to a new position, resize will return the window to its original position, 

Or if the same window is moved and resize concurrently, one or all of them will be interrupted

This is manifested as a partial shift of the window to the target position, and the size of the window is only partially adjusted to the target size

**Comment by I-Want-ToBelieve** [comment]
For example, if a request to resize a window is submitted using the old window location, but a request to modify the window position was submitted before that, because the request has not yet taken effect, the request to resize the window uses the original window position, and the request to modify the window position has been moved to the new location. Later, the window resize request also takes effect, but the window flashes back to its original position by using the position before the window is moved, i.e., the window move request is overwritten

**Comment by I-Want-ToBelieve** [comment]
I describe the problem again using typescript code

This is gpt4's explanation of the code

The difference between the two code snippets you provided is in the way they handle asynchronous operations.

In the first snippet:
```ts
 await this.yabai.move({ x, y }, this.id)
 await this.yabai.resize({ w, h }, this.id)
```
The move and resize operations are performed sequentially. The resize operation will not start until the move operation has completed.

In the second snippet:
```ts
  await Promise.all([
    this.yabai.move({ x, y }, this.id),
    this.yabai.resize({ w, h }, this.id)
  ])
```
The move and resize operations are performed concurrently using Promise.all. This means they are started at the same time, and the promise returned by Promise.all will not resolve until both operations have completed.

If the operations need to be performed in a specific order (for example, if resize depends on the completion of move), then the first snippet would work correctly while the second snippet could cause issues. On the other hand, if the operations are independent and can be performed in any order, the second snippet could be more efficient because it performs the operations concurrently. However, if there’s a bug when they are performed concurrently, it might be due to a race condition. A race condition occurs when the behavior of a program depends on the relative timing of events, such as the order in which move and resize complete.

**Comment by I-Want-ToBelieve** [comment]
This is probably not worth fixing as we can always manipulate the windows in a sequential manner, I'm reporting the issue here in the hope it helps someone else who has the same problem

If you think the question should be closed, you can.

**Comment by koekeishiya** [comment]
Caching issue. The second operation is executed *after* the first one has completed, but *before* macOS window moved/resized event is reported to yabai.
