### ISSUE TITLE
Adobe Photoshop 2024 Clone Stamp Issue

### ISSUE THREAD

**Issue by rickalex21** [koekeishiya/yabai#1972]
Hello, thanks for all the great work.

I noticed that while using photoshop the clone stamp tool will not work. I'm not
sure if it's because my meta key is option and it requires option+click for clone source to work.

Once I stop yabai service it works fine.

I get this error:

```text
Could not use the clone stamp because the area to clone has not been defined (option-click to define a source point).
```

**Comment by koekeishiya** [comment]
Same as #1801
