### ISSUE TITLE
Issue focusing empty space

### ISSUE THREAD

**Issue by hungmanhle** [koekeishiya/yabai#1974]
```
using macOS Sonoma 14.1
using yabai v6.0.1
using skhd v0.3.9
```
I've noticed that when switching to a space that is 
1) Not on the same display and
2) Does not have any windows

The space is "correctly" switched but the entire desktop is in a strange state where I'm unable to go to a different space as if I've minimized all windows.

I'm stuck here until I click anywhere on a display. This is unideal, it would be nice to be able to continue send commands to yabai through skhd.

**Comment by PhrantiK** [comment]
System Settings > Desktop & Dock > Click wallpaper to reveal desktop > Only in Stage Manager

**Comment by koekeishiya** [comment]
Added caveat to readme and wik.
