### ISSUE TITLE
Support for After Effects

### ISSUE THREAD

**Issue by hrvstr** [koekeishiya/yabai#198]
Would it be possible to add support for After Effects? Some of the Creative Cloud apps (e.g. Illustrator, Indesign) are already managed by yabai but After Effects is not.

### window information:
```
{
	"id":4960,
	"pid":41041,
	"app":"Adobe After Effects CC 2018.3 (15.1.2)",
	"title":"Adobe After Effects CC 2018 - Unbenanntes Projekt",
	"frame":{
		"x":222.0000,
		"y":186.0000,
		"w":3440.0000,
		"h":1440.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXFloatingWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":2,
	"visible":0,
	"focused":0,
	"split":"none",
	"floating":1,
	"sticky":0,
	"border":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":3056,
	"pid":14564,
	"app":"Adobe Illustrator CC 2018",
	"title":"Unbenannt-1* bei 150 % (RGB/GPU-Vorschau) ",
	"frame":{
		"x":0.0000,
		"y":0.0000,
		"w":3440.0000,
		"h":1440.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":2,
	"visible":0,
	"focused":0,
	"split":"none",
	"floating":0,
	"sticky":0,
	"border":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}
```

**Comment by koekeishiya** [comment]
Does `yabai -m rule --add app="Adobe After Effects CC 2018.3 (15.1.2)" manage=on` not work?

**Comment by hrvstr** [comment]
No, does not seem to have any effect.

**Comment by dominiklohmann** [comment]
That's because the regex is invalid, you need to escape both parantheses.

**Comment by hrvstr** [comment]
Yes, now it is working. Thanks!

`yabai -m rule --add app="Adobe After Effects CC *" manage=on`

I now added this rule to make it update proof.

**Comment by dominiklohmann** [comment]
Just `app="^Adobe After Effects CC"` should be sufficient. `^` denotes the start of the line, and yabai looks for partial matches anyways. The star you added doesn't mean "anything after this" but instead denotes "whatever single character".
