### ISSUE TITLE
brew install asks for GH credentials?

### ISSUE THREAD

**Issue by michaelaye** [koekeishiya/yabai#1980]
I tried to install with the standard brew command, but it asks for my GH credentials:

<img width="687" alt="image" src="https://github.com/koekeishiya/yabai/assets/69774/d874b152-edae-4f2e-ac40-075774a01057">

macOS: 12.7
Intel-based MacBook

**Comment by d34dh0r53** [comment]
You have a typo in the repository name, it should be `brew install koekeishiya/formulae/yabai`.  GitHub asking for credentials is a dead giveaway that you have a typo in the URL.

**Comment by michaelaye** [comment]
Ugh, very embarrassing :( but thank you so much for that tip, didn't know that about brew. Happy new year!

**Comment by d34dh0r53** [comment]
:) don’t be embarrassed, I’ve done this so many times that if I ever see GitHub asking for my credentials I immediately Ctrl-C and go hunt for the typo.  It’s actually a non-intuitive error message from the `git` command looking for a non-existing private repository.
