### ISSUE TITLE
Issue with yabai scripting addition injection into docks after running "killall dock"

### ISSUE THREAD

**Issue by szfkamil** [koekeishiya/yabai#1981]
I encountered an issue where the yabai scripting addition injection into the docks was removed after running the `killall dock` command. 

Even after rebooting and adding the command to my yabairc file, the issue persisted. When attempting to move between spaces, I received an error message stating "`cannot focus space due to an error with the scripting-addition.`" 

According to issue #1782, this error occurs when there are issues with SIP (System Integrity Protection). To resolve the problem, I had to run the commands "`rm /tmp/yabai*`" and "`sudo yabai --load-sa`," followed by "`yabai --restart.`" If restarting doesn't work, you can try using "`yabai --stop-service`" or "`yabai --start-service`." Another option is to run "`sudo yabai --install-sa`" before "`sudo yabai --load-sa`."

**Comment by szfkamil** [comment]
Please let me know if the issue is valid and my solution is too,I have solved it, but would like to log it for all future users.

**Comment by windowsrefund** [comment]
This just saved my !@#$!%!.
