### ISSUE TITLE
A better way to rotate windows between displays

### ISSUE THREAD

**Issue by amiorin** [koekeishiya/yabai#1982]
I'd like to rotate windows between displays to avoid typing for long time with my neck turned left or right. I have three monitors in front of me and I'm concerned about staring the monitors on the sides for too long.

I've started using `yabai` recently and I was wondering how to improve the following script.

```sh
# swap windows in display
alt - g : wins=($(yabai -m query --windows | jq 'map(select(."is-visible"))[].id')) \
  && yabai -m window ${wins[1]} --swap ${wins[2]}
```

Any advice on how to improve it further?

**Comment by amiorin** [comment]
After some iterations I have found a better way to swap windows between displays. I switched to stack and alway use 4 desktop no matter how many displays I have.

https://github.com/amiorin/dotfiles-v2/blob/main/yabairc
https://github.com/amiorin/happy-yabai

**Comment by koekeishiya** [comment]
On master (in v7.0.0 when released) the `space --swap` command can be used for spaces across display boundaries, and it will basically swap all windows.
