### ISSUE TITLE
[improvement suggestion] child of topmost window also topmost

### ISSUE THREAD

**Issue by rwijtvliet** [koekeishiya/yabai#1983]
In my `yabairc`, I have the rule

```
yabai -m rule --add title="(Reminder|Notification|Preferences|Settings)$" manage=off sticky=on layer=above opacity=0.9
```

However, this causes me problems in viscosity. Its preferences window is on top, as wanted. However, any children (when clicking "edit") are shown underneath it. And because I cannot grab the title bar, I cannot move them out from under the preference window. Moving the preference window itself is not working; the child moves with it.

![image](https://github.com/koekeishiya/yabai/assets/4106013/c82af132-250b-40d1-b7c1-27efe44e6691)

I'm not sure what would be the best way to improve this. Maybe automatically have floating windows spawned by top-most windows be top-most as well (would that solve it?).

**Comment by koekeishiya** [comment]
This is a hard problem to solve because macOS does not notify about creation of these UI elements. Which is why managed windows use the *below* layer, such that every other window that macOS creates will appear above managed windows without making this issue appear.

**Comment by rwijtvliet** [comment]
If I understand correctly, `layer=above` should be used very sparingly, just in case a window should *really* be on top. And in all other cases, it's better not to use it at all? I'll give it a try, thanks for clarifying.
