### ISSUE TITLE
Sonoma some app always on top

### ISSUE THREAD

**Issue by coffee-guy** [koekeishiya/yabai#1984]
i found some refs:
https://forums.macrumors.com/threads/app-windows-stay-on-top-randomly.2407390/

there is a common issue that using multi-destop app like yabai, could lead to this issue

some app just always on top, minimize and restore cannot work.I'm so regret to update to sonoma.

Apple silicon M1
Macos Sonoma 14.1.1

is there any chance to fix it? or some one could tell why it happened, its a pain in the ass.

**Comment by Pandoks** [comment]
#1912

**Comment by shrugalic** [comment]
I had this happen for apps with `manage=off` setting. A workaround is described in https://github.com/koekeishiya/yabai/issues/1929

**Comment by koekeishiya** [comment]
use `yabai -m rule --add app=".*" layer=normal` in v6.0.3.
