### ISSUE TITLE
Yabai config after update return error

### ISSUE THREAD

**Issue by ironhak** [koekeishiya/yabai#1986]
Hi everyone, I updated yabai and homebrew during the installation of new version reported something like:
"Yabai was updated, update also the flag by pasting `echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa";` inside `/private/etc/sudoers.d/yabai`. (sorry I don't remember clearly, but that's the line anyway). 

So I pasted that line inside `/private/etc/sudoers.d/yabai`, but now whenever I run sudo in my terminal I get this error:
```
/private/etc/sudoers.d/yabai:1:119: syntax error
echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa";
```

And, this is the whole content of `/private/etc/sudoers.d/yabai`:
```
echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa";
```

**Comment by dseum** [comment]
You should paste in the result string of the `echo` command into the file in `sudoers.d`.

**Comment by gldtn** [comment]
As @dseum said, paste that line into your terminal and copy the result, than paste it into your sudoers file

**Comment by ironhak** [comment]
Thank's guys. Isn't there a way to avoid doing this at every new update?

**Comment by gldtn** [comment]
Unfortunately no, scripting addition must be reconfigured after every update.. but if you installed from [HEAD](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)), you can use this script here to make it a bit more automated: [Updating yabai (from latest HEAD) - Script](https://github.com/koekeishiya/yabai/discussions/1904 )

If your running the release version, you can add this to your .zshrc:
```
# yabai scripting-addition;
# function to update sudoers file
function suyabai () {
    SHA256=$(shasum -a 256 $(which yabai) | awk "{print \$1;}")
    if [ -f "/private/etc/sudoers.d/yabai" ]; then
        sudo sed -i '' -e 's/sha256:[[:alnum:]]*/sha256:'${SHA256}'/' /private/etc/sudoers.d/yabai
        echo "sudoers > yabai > sha256 hash update complete"
    else
        echo "sudoers file does not exist yet. Please create one before running this script."
    fi
}
```

Than source or restart your shell:
```
source ~/.zhrc
```

So after you update Yabai in future releases, just run:
```
suyabai
```

This would automatically edit yabai sudoers file  for you without the need of opening with visudo

**Comment by ironhak** [comment]
> Unfortunately no, scripting addition must be reconfigured after every update.. but if you installed from [HEAD](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)), you can use this script here to make it a bit more automated: [Updating yabai (from latest HEAD) - Script](https://github.com/koekeishiya/yabai/discussions/1904)
> 
> If your running the release version, you can add this to your .zshrc:
> 
> ```shell
> # yabai scripting-addition;
> # function to update sudoers file
> function suyabai () {
>     SHA256=$(shasum -a 256 $(which yabai) | awk "{print \$1;}")
>     if [ -f "/private/etc/sudoers.d/yabai" ]; then
>         sudo sed -i '' -e 's/sha256:[[:alnum:]]*/sha256:'${SHA256}'/' /private/etc/sudoers.d/yabai
>         echo "sudoers > yabai > sha256 hash update complete"
>     else
>         echo "sudoers file does not exist yet. Please create one before running this script."
>     fi
> }
> ```
> 
> Than source or restart your shell:
> 
> ```
> source ~/.zhrc
> ```
> 
> So after you update Yabai in future releases, just run:
> 
> ```
> suyabai
> ```
> 
> This would automatically edit yabai sudoers file for you without the need of opening with visudo

Thank's really much :D

A little off-topic question: what's the purpose of inserting the SHA256 inside the sudoers file?

**Comment by koekeishiya** [comment]
Everything you need to know is in the wiki:

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

> yabai uses the macOS Mach APIs to inject code into Dock.app; this requires elevated (root) privileges. You can configure your user to execute yabai --load-sa as the root user without having to enter a password. To do this, we add a new configuration entry that is loaded by /etc/sudoers.

**Comment by ironhak** [comment]
> Everything you need to know is in the wiki:
> 
> https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
> 
> > yabai uses the macOS Mach APIs to inject code into Dock.app; this requires elevated (root) privileges. You can configure your user to execute yabai --load-sa as the root user without having to enter a password. To do this, we add a new configuration entry that is loaded by /etc/sudoers.

Yes I read that but it does not say the purpose of SHA256
