### ISSUE TITLE
display_resized passes the wrong YABAI_DISPLAY_ID

### ISSUE THREAD

**Issue by Sulfyderz** [koekeishiya/yabai#1987]
Hello,

Thank you for your great work.

Currently, I'm working with `yabai -m signal`. By checking the log, I've discovered that `$YABAI_DISPLAY_ID` doesn't give the right ID. I have an external monitor and when I changed its resolution,  `$YABAI_DISPLAY_ID` is still 1 instead of 2.

Could you help me? I do think it's a bug.

Best,
Sulfyderz.

**Comment by koekeishiya** [comment]
$YABAI_DISPLAY_ID gives the internal display id, and not the display arrangement index. You can do a query `yabai -m query --displays` and the `id` field will be equal to the `$YABAI_DISPLAY_ID` value, and the `index` field is going to be the display arrangement index that you pass to yabai commands.

Signal should probably be changed to pass both `id` and `index`.

**Comment by koekeishiya** [comment]
#2152

**Comment by koekeishiya** [comment]
Fixed in v7.0.0.
