### ISSUE TITLE
yabai: service file is not installed! abort. (com.koekeishiya.yabai.plist)

### ISSUE THREAD

**Issue by pyinto** [koekeishiya/yabai#1989]
Any service-related Yabai command gives an error. Here is an example:
```
yabai --restart-service
> yabai: service file '.../Library/LaunchAgents/com.koekeishiya.yabai.plist' is not installed! abort..
```
But window management itself works properly. What exactly should I do to fix it? I checked the `LaunchAgents` folder, and `com.koekeishiya.yabai.plist` file is missing there. Should I create it manually, what content should be there?

Is it somehow related to the logs I've seen during previous Yabai upgrades? Here is example:
`Error: Formula yabai has not implemented #plist, #service or installed a locatable service file` 
I haven't done anything at this point, I'm just updating Yabai through Brew whenever a new version is released.

## Specifications

  - `yabai-v6.0.1 `
  - `skhd-v0.3.9`
  - MacOS `14.1.1` `23B81`

Hope to resolve this thing, thanks!

**Comment by roshaans** [comment]
Same issue...

**Comment by weeebdev** [comment]
Same. Any workarounds?

**Comment by koekeishiya** [comment]
Do a full uninstall from brew, remove from accessibility settings and reboot. Reinstall from brew and follow the printed instructions.

**Comment by remoire** [comment]
i reinstalled both, then run `--start-service` not `--restart-service`

**Comment by ironhak** [comment]
I'm on mac 13.6.6 and still get this error when trying to --load-service or --start-service
