### ISSUE TITLE
Finder tabs are considered to be new windows: node is splitted unnecessarily

### ISSUE THREAD

**Issue by kiryph** [koekeishiya/yabai#199]
macOS 10.14.6
Finder version: 10.14.5

When I open a new Finder window and then press `cmd+tab` to open a second  tab, the second tab window is considered to be a new window which does not exist, but the current node is splitted anyway.

Following screenshot illustrates the occuring empty space on the screen:

![Screenshot 2019-08-07 at 17 27 25](https://user-images.githubusercontent.com/371756/62635810-a8a1e480-b938-11e9-9810-374c6952f55c.png)

**Comment by koekeishiya** [comment]
Duplicate of #68 

Short story: macOS is garbage and there is no way to implement robust support for this, at least without combining a hundred crappy "hacks". .I've given up trying to deal with a feature I never use.

**Comment by kiryph** [comment]
Thanks for pointing me to the existing issue.

**Comment by vietvudanh** [comment]
TIL know this. Always open new window for finder then. I agree that macOS is garbage.

**Comment by Raeproject99** [comment]
Any update on this?

**Comment by kushvinth** [comment]
+1
