### ISSUE TITLE
mac OS Ventura or Higher -> Install Instructions Update (Documentation)

### ISSUE THREAD

**Issue by gamedevCloudy** [koekeishiya/yabai#1990]
## Documentation 
Since the new iOS/iPadOS like UI update to Mac OS, install instructions need slight change. 

**Old**
```
Open System Preferences.app and navigate to Security & Privacy, then Privacy, then Accessibility. Click the lock icon at the bottom and enter your password to allow changes to the list. Starting with yabai --start-service will prompt the user to allow yabai accessibility permissions. Check the box next to yabai to allow accessibility permissions.
```

**New**
```markeddown
1. Click the Apple Icon. 
2. Click "System Settings"
3. Scroll down to find "Privacy & Security". 
4. Under "Privacy" section, find "Accessibility". 
5. Now, run "yabai --start-service" in terminal. 
6. This will create a new dialogue, click "Open Systems Settings". 
7. In the list, toggle "Yabai."
8. Confirm by using TouchID or use your password. 
9. Done. 
```

**Comment by therealmrcolor** [comment]
I'm on M1 Max on Sonoma and when i run "yabai --start-service" i don't get any dialog form System Setting, how can i solve?

**Comment by gamedevCloudy** [comment]
@therealmrcolor  you may have added it already. 
Please see if you can see 'yabai' in the that menu and toggle it.

**Comment by therealmrcolor** [comment]
I checked but it's not there, isn't there a way to add it manually?
I would need to know the path, thank you
![SCR-20240203-oon](https://github.com/koekeishiya/yabai/assets/21344989/f9bf4ff7-5dd0-4616-bc20-0ef33ba1f9aa)

**Comment by koekeishiya** [comment]
Updated wiki.
