### ISSUE TITLE
Last focused window in the display always looks like it is focused in multi-display setting.

### ISSUE THREAD

**Issue by albert-ying** [koekeishiya/yabai#1992]
Hi, I'm having this issue for a while since I updated to Sonoma. I thought it would be fixed soon but seems that it persists.

I have multiple displays and I set different transparency for focused and unfocused windows in yabai.

I notice that the last focused window in the display is always "considered" as focused. For example, when I move my focus from window A in display 1 to window B in display 2, the transparency of window A doesn't change (it looks like it is still focused but it is not).

Anyone has this similar problem?

**Comment by koekeishiya** [comment]
Uh this is intentional to make multi-monitor more usable with window opacity. Well I found it more usable anyway, considering that I usually want to be able to look at what is on both monitors at the same time, even though I might be typing in the other one.

**Comment by albert-ying** [comment]
Before, it was a problem for me as I usually only have one window per display, and it makes me lose track of which window I'm focusing on. But now I'm using the JankyBorder, and it is no longer a problem for me. I will close the issue.

**Comment by OfficialCRUGG** [comment]
Are there no plans to make this configurable? I want only 1 window, the focused one to have the regular opacity and no others.
