### ISSUE TITLE
yabairc does not require executable permissions. 

### ISSUE THREAD

**Issue by penglei** [koekeishiya/yabai#1993]
Currently, yabai loads yabairc by forking a new process and then executing the configuration file (i.e. .yabairc) using the shell (sh). The new process does not need to use `[sh, -c, g_config_file]` to execute, so it does not require executable permissions. Instead, it only needs to interpret the config file directly using the shell , i.e. `[sh, g_config_file]`.

Otherwise, this would cause some scenarios to be unable to load the configuration file, for example,  the configuration file generated by `nix home-manager` is read-only.

**Comment by koekeishiya** [comment]
Fixed in v7.0.0.
