### ISSUE TITLE
New window floating despite space being bsp tiled. 

### ISSUE THREAD

**Issue by InkyStoiner** [koekeishiya/yabai#2002]
Like i3, I configured alt + enter/return to be make new Alacritty terminal, using 
```alt - return : alacritty``` in skhd. However, upon the new Alacritty terminal opening, it's a small floating window in the centre of the screen, when I want it to be tiled. The space it's entering is bsp tiled, so why isn't it?

**Comment by gldtn** [comment]
This happen to me before, for some reason when you have :
```
alt - return : alacritty
```

It does not send a signal to Yabai that a new window was created.

This should fix it:
```
alt - return : open -a alacritty
```

**Comment by InkyStoiner** [comment]
> This has happened to me before, for some reason when you have :
> 
> ```
> alt - return : alacritty
> ```
> 
> It does not send a signal to Yabai that a new window was created.
> 
> This should fix it:
> 
> ```
> alt - return : open -a alacritty
> ```

This does not work for me, as when I already have an Alacritty window open, it just focuses onto it.
