### ISSUE TITLE
Window border options removed?

### ISSUE THREAD

**Issue by 9tin9tin9** [koekeishiya/yabai#2004]
I used to set window border colors with
```
yabai -m config active_window_border_color 0xA000AACC
yabai -m config normal_window_border_color 0x01000000
```
But updating yabai (and I don't know the last version I am using) seems to have removed these options. I have searched through man page but the word "border" doesn't seem to appear in the man page. Are the options removed or renamed?

**Comment by gldtn** [comment]
Yes, see: https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#600---2023-10-10

If you want borders you'll need to use:
https://github.com/FelixKratz/JankyBorders

**Comment by 9tin9tin9** [comment]
Thx! I think i can get used to not having windows borders.
