### ISSUE TITLE
Can't get rid of animation when switching spaces.

### ISSUE THREAD

**Issue by curiousier-george** [koekeishiya/yabai#2006]
I'm running yabai 6.0.1 on Sonoma 14.1.2, and I am getting the animation when switching between spaces. My understanding is that when SIP protection has been disabled and yabai doesn't have Screen Recording permission, then there should be no animation?

One more piece of information, I had originally given yabai Screen Recording permission but then explicitly added yabai to the Settings Screen Recording page and turned it off, but I get the animation either way.

Any help or advice would be greatly appreciated!

**Comment by adorabilis** [comment]
Did you load the [scripting addition](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition)?

```bash
sudo yabai --load-sa
```

**Comment by curiousier-george** [comment]
Hmm, well, I thought I had. I set up `~/.yabairc` per the instructions, and had also run
```
sudo yabai --load-sa
```
from the command line to make sure that wasn't the issue, and I was still getting the animation. But I just ran it again right now to make sure again, and - voila! - it did the trick this time. 🤔

I'm confused but also happy. Thanks for your help - I really do appreciate it!
