### ISSUE TITLE
Scripting Addition - Effecting Other Applications

### ISSUE THREAD

**Issue by NicholasMata** [koekeishiya/yabai#2009]
I understand the scripting addition is a "hack" so I am sure supporting it can be hard. Nevertheless I am hoping you can provide support for the following issue.

## Issue:
Ever since macOS 14.1.1 and version 6.0.1, scripting addition causes issues with Microsoft Teams screen sharing. Specifically attempting to screen share a specific window no longer works. If I uninstall scripting addition using `sudo yabai --uninstall-sa` and kill the dock using `killall Dock` the feature works again in Microsoft Teams.

_An interesting fact about the issue. If a window was open before you install yabai scripting additions then it is available as a shareable window._ 

## Steps to Replicate:
1. Ensure Scripting Addition is not installed and you have killed the Dock after uninstalling Scripting Addition if it was previously installed.
2. Open browser from a closed state. I tested using Microsoft Edge but should happen in all browsers.
3. Go to [https://teams.microsoft.com](https://teams.microsoft.com) and log in (you will have to create an account if you don't have one can do that by going to [https://outlook.com](https://outlook.com)).
4. Once logged in click on "Calendar" in the side menu
5. Click "Meet Now" towards the top right. Then click "Start meeting".
6. Click the "Share" button towards the top right.
7. Click "Screen, window, or tab".
8. When the dialog comes up select the Window tab. You should see all windows you have open in the specific space.
9. Install scripting addition using `sudo yabai --load-sa`.
10. Quit the browser than repeat steps 2 - 8. You will notice that on step 8 there are no windows available for selection. (This is not always true if the window was open before installing scripting additions it is available until it is close and reopened)

### With Yabai Scripting Addition
<img width="100%" alt="With Yabai SA" src="https://github.com/koekeishiya/yabai/assets/8304095/47075918-9ea0-48b8-b801-f1af0de0afa7">

### Without Yabai Scripting Addition
<img width="100%" alt="Without Yabai SA" src="https://github.com/koekeishiya/yabai/assets/8304095/becb082a-9792-4f78-a3d7-445391bec4c2">

_(I debated a bit whether to add to an existing issue or create a new one. I landed on new issue if you believe I should add it to an existing issue just let me know below.)_

**Comment by kinglouie** [comment]
see #1940 for me the issue can be worked around by floating the window

**Comment by NicholasMata** [comment]
Appreciate the work around seems like even when floating it doesn't always pick the window up. But it does work sometimes and you can un-float the window afterward which is nice.

For others in the future you can float and un-float windows using the below commands.
https://github.com/koekeishiya/yabai/wiki/Commands#toggle-window-properties

**Comment by koekeishiya** [comment]
This is probably due to the automated window layer changes. You can disable this by setting a fixed layer using a rule or window command e.g `yabai -m rule --add app="^Finder$" layer=normal` or `yabai -m window --layer normal`.

**Comment by ademoverflow** [comment]
I'm facing the same issue, so what's the solution ?

**Comment by ademoverflow** [comment]
This is not a viable solution as you need to execute this command for each new window.
When added to yabairc, it does nothing particular as you need to execute this command for a particular window.
You can run this command `yabai -m rule --add app="^" layer=normal`, that will apply to all the windows that are __already open__, but not for new ones.
Yes it does work, but it's a workaround and not a definitive solution.

Hence my question ? 

If there isn't any solution to this issue, then ok fine but it should not be considered as completed ?
