### ISSUE TITLE
Launchagent plist service for yabai contain invalid character in the PATH that render it not working

### ISSUE THREAD

**Issue by pencilcheck** [koekeishiya/yabai#2012]
Launchagent.plist for yabai sometimes contain invalid character in the "env" that render it not working

Somehow the env section contains path that seems to not play well with plist where some characters weren't escaped or something (like a dot) and then plist just refuse to run and return 78 (function not implemented)

Should fix ENV section to mimic the homebrew generated plist which is clean and has no invalid character in the PATH

**Comment by koekeishiya** [comment]
The point is that the user is supposed to be able to access any binary that is located in a place stored in their path, from their yabai config. Using a "blank" path or the way homebrew does it, is not a solution to that problem.

If you as a user somehow has managed to set your path to something that is invalid or incompatible with launchd, then either fix your environment or simply overload the PATH variable when you call install-service

`env PATH="/usr/local/bin:/usr/bin:/usr/sbin" yabai --install-service`
