### ISSUE TITLE
workspace focus change doesn't work with Sonoma 14.2

### ISSUE THREAD

**Issue by kalebris** [koekeishiya/yabai#2013]
after the upgrade yabai switch workspaces stopped working. Desipite having `sudo yabai --load-sa`, `yabai -m space --focus (prev|next|[0-9])` is not working.

I have tried to restart the service or gain insight into what's going on with running yabai in verbose mode, but no dice. I have yabai installed from brew and it's currently at yabai-v6.0.1 version.

For some reason it seems that yabai --load-sa doesn't work:
```
% sudo yabai --load-sa; echo $?
1
%
```

**Comment by alwyn** [comment]
There was the exact same issue in some 14.1.x which was only addressed by a yabai update, so may require another update?

**Comment by thiagomeireless** [comment]
Guys, please read/search the issues. After every update it's expected to have some problems: https://github.com/koekeishiya/yabai/issues/2007

**Comment by kalebris** [comment]
closing in favor of https://github.com/koekeishiya/yabai/issues/2007 and now i know what sa stands for in --load-sa. Still a bit unclear on how the connection between workspace focus and script-addition should have been made, but thanks for pointing it out @thiagomeireless
