### ISSUE TITLE
Disable managing for signals from Google Chrome

### ISSUE THREAD

**Issue by vinntik** [koekeishiya/yabai#2014]
Hello Team, 
I try to disable MetaMask Notification signals from Google Chrome, but it doesn't work, 

I have the following settings in my yabairc:

`yabai -m signal --add \
  label=keep-metamask-small \
  event=window_created \
  app='^Google Chrome$' \
  title='^MetaMask Notification$' \
  action="
    yabai -m query --windows \
    | jq -r '.[] | select(.pid | tostring == env.YABAI_PROCESS_ID).id' \
    | xargs -I{} yabai -m window {} --toggle float
  "`

or

```
yabai -m signal --add \
  label=keep-metamask-small \
  event=window_created \
  app='^Google Chrome$' \
  title='^MetaMask Notification$' \
  action='
    yabai -m query --windows --window $YABAI_WINDOW_ID \
    | jq -re ".floating == 0" \
    && yabai -m window $YABAI_WINDOW_ID --toggle float
```

or
```
yabai -m signal --add \
  label=keep-metamask-small \
  event=window_created \
  app='^Google Chrome$' \
  title='^*$' \
  action="
    yabai -m query --windows \
    | jq -r '.[] | select(.pid | tostring == env.YABAI_PROCESS_ID).id' \
    | xargs -I{} yabai -m window {} --toggle float
  "
```

Also, I tried disabling managing all signals from Chrom, but still failing

```
yabai -m signal --add app='Google Chrome' event='window_title_changed' \
  action="yabai -m rule --add label=$(uuidgen) app='Google Chrome' title='*' manage=off"'
```

What I do wrong? 

Thanks in advise!

**Comment by koekeishiya** [comment]
You probably want a rule instead:


`yabai -m rule --add app="^Google Chrome$" title="^MetaMask Notification$" mouse_follows_focus=off manage=off`

Check the output of `yabai -m query --windows` for information about the window.
