### ISSUE TITLE
Weird stuff

### ISSUE THREAD

**Issue by Kana-fi** [koekeishiya/yabai#2016]
![Screenshot 2023-12-18 at 7 11 23 PM](https://github.com/koekeishiya/yabai/assets/106124331/14e2a132-433c-4463-a702-8c142138c775)
![Screenshot 2023-12-18 at 7 10 45 PM](https://github.com/koekeishiya/yabai/assets/106124331/6f4ef317-0ed0-4091-9bc7-48f8ded5cc89)
Every time when restart mac, I got yabai install window, when I click it, put my password, and nothing happens at all. The second thing, why is there two yabai logging items, how to deal with it?

**Comment by Bellavene** [comment]
You have two yabai plist files.
Check `~/Library/LaunchAgents/`
Additionally
```
/Library/LaunchAgents/
/Library/LaunchDaemons/
/Library/PrivilegedHelperTools/
```
for other unwanted daemons.

**Comment by Kana-fi** [comment]
> You have two yabai plist files. Check `~/Library/LaunchAgents/` Additionally
> 
> ```
> /Library/LaunchAgents/
> /Library/LaunchDaemons/
> /Library/PrivilegedHelperTools/
> ```
> 
> for other unwanted daemons.
Which one can I delete?
Library/LaunchAgents/com.koekeishiya.skhd.plist
Library/LaunchAgents/com.koekeishiya.yabai.plist
Library/LaunchAgents/com.lwouis.alt-tab-macos.plist
Library/LaunchAgents/homebrew.mxcl.borders.plist
Library/LaunchAgents/homebrew.mxcl.fyabai.plist
Library/LaunchAgents/homebrew.mxcl.svim.plist

**Comment by Bellavene** [comment]
fyabai is a fork of yabai. So you have installed yabai and a fork.
`Brew uninstall fyabai`

**Comment by Kana-fi** [comment]
> fyabai is a fork of yabai. So you have installed yabai and a fork. `Brew uninstall fyabai`

Okay, I deleted it, then I completely reinstall yabai and skhd, however, now I have more problems. I reinstalled skhd/yabai, but before that, I did back-ups of my configs, and did not make any changes. After reinstalling, restarting mac a few times, the problem persists. When I open any app, no matter if it's excluded (manage=off) or NOT, they are all float windows, and when I press hyper - t (toggle float) or hyper - f (maximize a windows) it doesn't work at all, but it only works for Arc browser, and not for a single different app.
![Screenshot 2023-12-21 at 4 54 34 PM](https://github.com/koekeishiya/yabai/assets/106124331/ff7c8829-c018-435a-a171-ae0943067109)

**Comment by Bellavene** [comment]
Не думаю, что функция if подходит для yabairc.
Запускали yabai --uninstall-sa перед переустановкой?

**Comment by Kana-fi** [comment]
> Не думаю, что функция if подходит для yabairc. Лучше пропишите autorise без if.
> 
> Запускали yabai --uninstall-sa перед переустановкой?

Все работало как часы,  не включая всплывающее окно после перезагрузки мака, либо ябаи, которое даже после ввода пароля ничего не происходит. Я не особо понимаю как прописать, можно пример? Я потратил весь день на эту проблему, как это исправить? Все окна float кроме Арк если перезагрузить ябаи, и бинды работают только для арк hyper -t, hyper -f so on. Нет, не запускал, я просто написал brew uninstall yabai, brew uninstall fyabai, brew uninstall skhd, и rm -rf все файлы с приставкой yabai/fyabai/skhd. После устанавливал ябаи через yabai wiki. Что посоветуете?

**Comment by Bellavene** [comment]
Должно все работать.

Как вариант, закройте все приложения, пропишите `yabai --uninstall-sa`, затем перезапустите yabai.

**Comment by Bellavene** [comment]
hyper - f : yabai -m window --grid 1:1:0:0:1:1 || yabai -m window --toggle zoom-fullscreen
Так приложения, которые исключены, будут тоже переходить на весь экран.

**Comment by Kana-fi** [comment]
мне нужно удалить эту часть в yabairc? ### Focus the window that is hovered with the mouse ###
if [[ $autoraise_toggle == "on" ]]; then
   yabai -m config focus_follows_mouse autoraise
fi ? Я кстати попробовал просто убрать часть if fi и это помогло, все окна работают как часы, но мышь не следует за окнами, я бы хотел чтобы оно всегда работало, как мне это сделать? И кстати, после удаления if fi перестало появляться всплывающее окно, а когда я вернул назад, снова оно выскакивает.

**Comment by Kana-fi** [comment]
> `hyper - f : yabai -m window --grid 1:1:0:0:1:1 || yabai -m window --toggle zoom-fullscreen` Так приложения, которые исключены, будут тоже переходить на весь экран.

Сделал все как сказал, yabai --uninstall-sa, yabai --restart-service изменил в skhdrc на это hyper - f : yabai -m window --grid 1:1:0:0:1:1 || yabai -m window --toggle zoom-fullscreen, и даже оставил все как и было в yabairc вместе с if fi. Теперь все работает как часы, но я не перестаю получать это окно всплывающее после перезагрузки ябаи, я попробовал просто в коммент эту часть #if [[ $autoraise_toggle == "on" ]]; then
   yabai -m config focus_follows_mouse autoraise
fi
но окно все равно всплывает после перезагрузки, как быть?

**Comment by Kana-fi** [comment]
> `hyper - f : yabai -m window --grid 1:1:0:0:1:1 || yabai -m window --toggle zoom-fullscreen` Так приложения, которые исключены, будут тоже переходить на весь экран.

Я заменил сою строку в skhd где hyper -f на твою. Все равно не работает то что надоб окна не становятся на места, float/maximize работает только для ark browser, бред какой-то, что это может быть?

**Comment by Bellavene** [comment]
> мне нужно удалить эту часть в yabairc? ### Focus the window that is hovered with the mouse ### if [[ $autoraise_toggle == "on" ]]; then yabai -m config focus_follows_mouse autoraise fi ? Я кстати попробовал просто убрать часть if fi и это помогло, все окна работают как часы, но мышь не следует за окнами, я бы хотел чтобы оно всегда работало, как мне это сделать? И кстати, после удаления if fi перестало появляться всплывающее окно, а когда я вернул назад, снова оно выскакивает.

Какое всплывающее окно? Непонятно

Удаляешь 
`export autorise toggle="off"`
и все строки с if и fi

Оставляешь просто
`yabai -m config focus_follows_mouse autorise`

**Comment by Kana-fi** [comment]
> > мне нужно удалить эту часть в yabairc? ### Focus the window that is hovered with the mouse ### if [[ $autoraise_toggle == "on" ]]; then yabai -m config focus_follows_mouse autoraise fi ? Я кстати попробовал просто убрать часть if fi и это помогло, все окна работают как часы, но мышь не следует за окнами, я бы хотел чтобы оно всегда работало, как мне это сделать? И кстати, после удаления if fi перестало появляться всплывающее окно, а когда я вернул назад, снова оно выскакивает.
> 
> Какое всплывающее окно? Непонятно
> 
> Удаляете `export autorise toggle="off"` и все строки с if и fi
> 
> Оставляете просто `yabai -m config focus_follows_mouse autorise` Но эта строчка не про "мышь не следует за окнами", она про обратное, фокус следует за мышью. Так что можете удалить, если такое не нужно. Для вашего случая есть `yabai -m config mouse_follows_focus on`

Beforehand, I almost sure this line was causing the pop-up window - YABAI_CERT=yabai-cert sh -c "$(curl -sSL "https://git.io/update-yabai")" &. 
![Screenshot 2023-12-21 at 11 23 12 PM](https://github.com/koekeishiya/yabai/assets/106124331/45889a34-0faf-4c08-b5b1-f0a2fed0d27f)

**Comment by Kana-fi** [comment]
Ok, whatever, I just decided to install fork by felixkratz, it works fine by now.

**Comment by Bellavene** [comment]
А понял, не видел такого окна никогда, потому как-то не обратил внимания в первом посте.
Это чей то сторонний скрипт, считаю что лучше такое в файл запуска не добавлять, да.

**Comment by Kana-fi** [comment]
> А понял, не видел такого окна никогда, потому как-то не обратил внимание в первом посте. Это чей то сторонний скрипт, считаю что лучше такое в файл запуска не добавлять, да.

Anyway, thank you for your help, you pointed to the right place.

**Comment by Bellavene** [comment]
btw correct option is autoraise
