### ISSUE TITLE
Application window floating problem

### ISSUE THREAD

**Issue by sundongyu** [koekeishiya/yabai#2018]
Hello, I recently encountered a problem while using yabai. For example: When I was using the Safari browser, I needed to modify the settings of the Safari browser, so I opened the browser's settings window. Safari browser is in tile mode under the influence of yabai. So the browser settings window I'm about to open will also be set to tiled mode, whereas for a window like this that's opened from within an application, floating mode is reasonable. So I'm curious if it can be set up like this.

**Comment by gabsrp2002** [comment]
You could add a rule to your `.yabairc` to tell yabai that it shouldn't manage the window.

In mine I have the following:

`yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off`
