### ISSUE TITLE
Is it okay to use the same 13.x instructions to disable SIP on 14.x?

### ISSUE THREAD

**Issue by vitoravelino** [koekeishiya/yabai#2019]
Hi there!

Sorry for opening an issue to ask a question but is it okay to execute the command below on M3 with macOS 14.x? 

> \# If you're on Apple Silicon macOS 13.x.x
> \# Requires Filesystem Protections, Debugging Restrictions and NVRAM Protection to be disabled
> \# (printed warning can be safely ignored)
>
> csrutil enable --without fs --without debug --without nvram

Does anyone know if anything changed for M3 and/or macOS 14.x?

Thank you!

**Comment by aevox** [comment]
yes

**Comment by vitoravelino** [comment]
It worked! 🎉
