### ISSUE TITLE
conflict with slack helper or chrome helper: kAXErrorCannotComplete  for Slack Helper (Plugin) / Google Chrome Helper (Plugin)

### ISSUE THREAD

**Issue by lijiachang** [koekeishiya/yabai#2020]
* macos version: 13.3.1 (a)
* yabai version: v6.0.1
* Chrome: all the version(include latest)
* Slack: 4.35.131 

I often use commands：  

> yabai -m space --focus prev  

> yabai -m space --focus next  

to switch between multiple desktops, 
but sometimes I can't switch or wait a few seconds for a response

Check the log (/tmp/yabai_my_name.out.log) and see the following errors:

EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 25615
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 25615
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 25615
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 25615
EVENT_HANDLER_MOUSE_DOWN: 25615 958.76, 892.31
EVENT_HANDLER_MOUSE_UP: 958.76, 892.31
EVENT_HANDLER_APPLICATION_LAUNCHED: Google Chrome Helper (Plugin) (87070) is not finished launching, subscribing to finishedLaunching changes
-[workspace_context observeValueForKeyPath:ofObject:change:context:]: Google Chrome Helper (Plugin) (87070) finished launching
process_create: xpc service detected! ignoring..
application_observe: error 'kAXErrorCannotComplete' for application 'Google Chrome Helper (Plugin)' and notification 'kAXTitleChangedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Google Chrome Helper (Plugin)' and notification 'kAXMenuOpenedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Google Chrome Helper (Plugin)' and notification 'kAXMenuClosedNotification'
EVENT_HANDLER_APPLICATION_LAUNCHED: could not observe notifications for Google Chrome Helper (Plugin) (87070) (1)
EVENT_HANDLER_DAEMON_MESSAGE: space --focus 2
EVENT_HANDLER_DAEMON_MESSAGE: space --focus 1
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 25615
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Google Chrome 25615

**same as Slack:**
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: Lark (70078)
EVENT_HANDLER_WINDOW_DESTROYED: Lark Helper 39270
EVENT_HANDLER_APPLICATION_LAUNCHED: Slack Helper (Plugin) (49078) is not finished launching, subscribing to finishedLaunching changes
-[workspace_context observeValueForKeyPath:ofObject:change:context:]: Slack Helper (Plugin) (49078) finished launching
application_observe: error 'kAXErrorCannotComplete' for application 'Slack Helper (Plugin)' and notification 'kAXTitleChangedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Slack Helper (Plugin)' and notification 'kAXMenuOpenedNotification'
process_create: xpc service detected! ignoring..
application_observe: error 'kAXErrorCannotComplete' for application 'Slack Helper (Plugin)' and notification 'kAXMenuClosedNotification'
EVENT_HANDLER_APPLICATION_LAUNCHED: could not observe notifications for Slack Helper (Plugin) (49078) (1)
application_observe: error 'kAXErrorCannotComplete' for application 'Google Chrome Helper (Plugin)' and notification 'kAXCreatedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Google Chrome Helper (Plugin)' and notification 'kAXFocusedWindowChangedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Google Chrome Helper (Plugin)' and notification 'kAXWindowMovedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Google Chrome Helper (Plugin)' and notification 'kAXWindowResizedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Google Chrome Helper (Plugin)' and notification 'kAXTitleChangedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Google Chrome Helper (Plugin)' and notification 'kAXMenuOpenedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Google Chrome Helper (Plugin)' and notification 'kAXMenuClosedNotification'
EVENT_HANDLER_APPLICATION_LAUNCHED: could not observe notifications for Google Chrome Helper (Plugin) (49080) (1)
EVENT_HANDLER_APPLICATION_TERMINATED: AOSHeartbeat (49022)

the error log  like to conflict with **Google Chrome Helper (Plugin)**  or  **Slack Helper (Plugin)**

This has bothered me greatly in the last year, I don't know how to fix it,
 if you have an idea, please help me, great yabai！！！thanks

**Comment by lijiachang** [comment]
Hi, anyone can help me ,thanks ！ @koekeishiya @dominiklohmann

**Comment by koekeishiya** [comment]
This message is normal and just means that these applications are not exposed to the macOS accessibility API that we use.
I have made changes to master branch that ignores "Google Chrome Helper (Plugin)" and "Slack Helper (Plugin)".

**Comment by lijiachang** [comment]
thanks for your job!!!
