### ISSUE TITLE
Window animation causes flickering when in stack mode

### ISSUE THREAD

**Issue by pseudobun** [koekeishiya/yabai#2022]
My first issue here, so let me first thank you for creating and managing this amazing software, it's an insane productivity boost, really love it.

## Issue
Pretty much what the title says. When having window animations enabled and set to anything (e.g. I have 0.25) and the layout mode is set to stack, the animations cause flickering as seen in the video. Using `yabai v6.0.1`.

https://github.com/koekeishiya/yabai/assets/32909989/60ab7cfa-2596-4a30-b2ec-9946ec786952

**Comment by koekeishiya** [comment]
Same as https://github.com/koekeishiya/yabai/issues/1493
