### ISSUE TITLE
Floating windows keep staying on top

### ISSUE THREAD

**Issue by alanmicah** [koekeishiya/yabai#2025]
I have attached a video of the issue.

When I have floating windows with stacked windows, the floating window keeps staying as the top layer, even when changing focus to another window in a stack/non-floating window.

This isn't interaction isn't an issue with only floating windows. So for example, if I have two floating windows A and B and I change focus from A to B then window A will go behind window B and vice-versa. 

https://github.com/koekeishiya/yabai/assets/31675641/563bdb6b-3832-453d-b857-d397d709eff3

Here is my Yabai config:

#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

#float system preferences. Most of these just diable Yabai form resizing them
yabai -m rule --add app="^About This Mac" manage=off 
yabai -m rule --add app="^Activity Monitor" manage=off  
yabai -m rule --add app="^AlDente" manage=off 
yabai -m rule --add app="^App Store" manage=off 
yabai -m rule --add app="^BreakTimer" manage=off 
yabai -m rule --add app="^Calendar" manage=off 
yabai -m rule --add app="^Calculator" manage=off 
yabai -m rule --add app="^Clock" manage=off 
yabai -m rule --add app="^Contacts" manage=off 
yabai -m rule --add app="^Finder" manage=off 
yabai -m rule --add app="^Hidden Bar" manage=off 
yabai -m rule --add app="^Maps" manage=off 
yabai -m rule --add app="^Messages" manage=off 
yabai -m rule --add app="^Music" manage=off 
yabai -m rule --add app="^Nightfall" manage=off 
yabai -m rule --add app="^TG Pro" manage=off 
yabai -m rule --add app="^Postgres" manage=off 
yabai -m rule --add app="^QuickTime Player" manage=off 
yabai -m rule --add app="^Spotify" manage=off 
yabai -m rule --add app="^SteelSeries ExactMouse Tool" manage=off 
yabai -m rule --add app="^System Settings" manage=off 
yabai -m rule --add app="^TIDAL" manage=off 
yabai -m rule --add app="^WhatsApp" manage=off 
yabai -m rule --add app="^Weather" manage=off 
yabai -m rule --add title='Preferences$' manage=off 
yabai -m rule --add title='Settings$' manage=off 
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off

yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  0              \
    bottom_padding               0              \
    left_padding                 0              \
    right_padding                0              \
    window_gap                   0              \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

**Comment by alanmicah** [comment]
running:
macOS 14.2.1
yabai 6.0.2

However this issue was also happening on macOS 14.1 and yabai 6.0.1

**Comment by alanmicah** [comment]
clone #1929

**Comment by varshithreddyg** [comment]
add "sub-layer=below" after every manage=off

eg:
yabai -m rule --add app="^Finder" manage=off sub-layer=below

**Comment by vu1xan** [comment]
@varshithreddyg thank you very much :)
