### ISSUE TITLE
Possible solution for detecting App Exposé and Windows Exposé signals and spaces reordering

### ISSUE THREAD

**Issue by roelvangils** [koekeishiya/yabai#2026]
I'm writing a little script that listens for an event for when you enter and exit Mission Control (and then does something).

I use this:

```
yabai -m signal --add event=mission_control_enter \
    action='(do something)'

yabai -m signal --add event=mission_control_exit \
    action='(do something else)'
```

These work well, but I have two additional requests:

1. I want to distinguish between "App Exposé" mode, which displays windows from the current application only, and "Windows Exposé" mode, which provides an overview of all open windows grouped by application.

2. I am also seeking a method to detect when a space thumbnail is moved (dragged to another position) in "App Exposé" mode. Currently, there is no `spaces_reordered` event available (although it may be added in the future, @koekeishiya?). Is there an alternative approach?

**Comment by koekeishiya** [comment]
yabai already knows the difference between app expose, window expose and mission control, but does not propagate that information through the signal (I didn't think it would matter to the user, but I guess I was mistaken). It should be trivial to either add an environment variable to inform how mission control was activated, or create separate signals.

I do not know of any way to track when spaces themselves are reordered, so that problem I can't fix.

**Comment by roelvangils** [comment]
> It should be trivial to either add an environment variable to inform how mission control was activated, or create separate signals.

Ah, that is good to know! May I officially suggest it as a feature request? 🙂

**Comment by koekeishiya** [comment]
```
yabai -m signal --add event=mission_control_enter action="echo \$YABAI_MISSION_CONTROL_MODE"
yabai -m signal --add event=mission_control_exit action="echo \$YABAI_MISSION_CONTROL_MODE"
```

Possible values present when entering and exiting mission-control:
```
show-front-windows # app expose    / default swipe-down gesture
show-all-windows   # window expose / default swipe-up gesture
show-desktop       # reveal desktop
```

**Comment by roelvangils** [comment]
Thanks, that's great! 😁 Now I can fix my script that position my Spaces labels below the thumbnails when in Windows Exposé mode.
