### ISSUE TITLE
Switching to empty space on another desktop cause mission control activation

### ISSUE THREAD

**Issue by ArtemMosk** [koekeishiya/yabai#2027]
I have a multi-monitor setup and
``` yabai -m space --focus X```
as far as 
``` yabai -m space X --display Y```
activates mission control/"show desktop" or whatever it is called (same as F11 does) WHEN it involves switching to another desktop. 
I turned off f11 in settings, and turned off "duplication" of space switching (needed to turn it off when yabai one did not work).
 It might be a system behavior rather than yabai-related but I did not find anything relevant anywhere in settings and it's extremely annoying so maybe there is a way to "fix" it or some functionality could be added to manage this. 

Macos Sohoma 14.1 on M2
<img width="677" alt="image" src="https://github.com/koekeishiya/yabai/assets/111910992/41d34772-090d-4fba-abc1-0e152a723ccc">

**Comment by ArtemMosk** [comment]
It indeed looks like system behavior as it reproduces with yabai stopped (e.g., clicking on empty desktop activates that "show desktop" too). 
Tried to use clickclick and shkd -k to "close" that "mission control" thing. That kind of works but it is not good solution and additionally it will not play nice if there are existing windows on the space. 
Maybe there are any better ideas?

**Comment by ArtemMosk** [comment]
So to summarize my understanding so far. MacOS introduced a "long-awaited" feature to show the desktop when you are switching to an empty desktop on another monitor.
That messes up "yabai UX"  as you need to click or ctrl+up IF mission control is activated. 
Workarounds like 
``` sh
yabai -m space X --toggle show-desktop
skhd -k "ctrl - up"
cliclick c:20,20 
```
 does not work out of the box because you need to know if mission control is activated. That is probably achievable but might require a separate ugly script (e.g., to switch space, you need to: save the current monitor, switch, wait, compare the current monitor with the old one, if not equal then ctrl + up or click).

**Comment by ArtemMosk** [comment]
I've implemented the mentioned ugly script for focus (yabai -m space --focus) so if anyone experiencing similar problems then you could use it:
```
#!/bin/bash

# Get the current space ID
current_space=$(yabai -m query --spaces --space | jq '.display')

# Execute the focus command (replace with your specific focus command)
yabai -m space --focus $1

window_count=$(yabai -m query --windows --space $1 | jq 'length')
echo $(yabai -m query --windows --space $1 | jq -e '.[] | select(.id)' > /dev/null)
# Get the new space ID
new_space=$(yabai -m query --spaces --space | jq '.display')

# Compare the space IDs
if [ "$current_space" != "$new_space" ] && [ "$window_count" -eq 0 ]; then
    skhd -k "ctrl - up";
fi
```

That works, but I don't think this is an acceptable solution. So, if anyone knows any better approach, please share.

**Comment by koekeishiya** [comment]
From the readme (and wiki):

In the Desktop & Dock tab, inside the Desktop & Stage Manager pane, the setting "Click wallpaper to reveal Desktop" should be set to "Only in Stage Manager" for display and space focus commands to work reliably.

**Comment by ArtemMosk** [comment]
It's a shame I did not read the manual and wasted my and your time.
Only thing I could say in my defence is that this "feature" is not quite search-friendly. Once I realized that it is OS-related I tried to find where it's turned off but did not find anything relevant.
