### ISSUE TITLE
[Q] How do I focus a particular app?

### ISSUE THREAD

**Issue by NightMachinery** [koekeishiya/yabai#2028]
How do I focus a particular app? E.g., `com.google.Chrome`.

**Comment by NightMachinery** [comment]
I found a solution to this:
`yabai -m window --focus "$(yabai -m query --windows | jq 'map(select(.app == "Google Chrome")) | .[0].id')"`

Now I need a way to take focus away from an app, and give it back to the app that last had focus. Is this possible or do I need to manually store the last app that had focus myself?

**Comment by hrvstr** [comment]
This should work:

```
yabai -m window prev --focus recent
```
[Window commands](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#window)
[Window selectors](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#definitions)
