### ISSUE TITLE
Ignore opacity

### ISSUE THREAD

**Issue by 24unix** [koekeishiya/yabai#2029]
Hi, I'm building an Xeyes clone (its holiday ^^)

I can set fixed values for opacity, like:
yabai -m rule --add app="Parallels Desktop" opacity=1.0

I added 
yabai -m rule --add app=MacEyes manage=off

Is there a way that Yabai also ignores the opacity values for that specific app?
It sets the value itself, but they get overwritten when gaining/losing focus.

This approach didn't work:
yabai -m rule --add app=MacEyes opacity=off
invalid value 'off' for key 'opacity'

**Comment by koekeishiya** [comment]
Setting a fixed opacity using a rule, e.g `yabai -m rule --add app="Finder" opacity=1.0` or `yabai -m window --opacity 1.0` will make the window exempt from active/normal opacity management until the opacity is set to 0.0 (acting as a reset) using `yabai -m window --opacity 0.0`

**Comment by 24unix** [comment]
Ah, great, thx.
<img width="532" alt="image" src="https://github.com/koekeishiya/yabai/assets/36622631/2e4dbfe7-2706-4277-8c81-e7edb54ed765">
