### ISSUE TITLE
Picture-in-picture catches focus and causes space change

### ISSUE THREAD

**Issue by wojciech-kulik** [koekeishiya/yabai#2031]
I'm using Arc browser and whenever I have picture-in-picture window visible on another space than the browser itself, it causes space change when I switch focus between displays.

Steps to reproduce:
1. Open Arc browser and trigger picture-in-picture (space 1, display 1)
2. Go to space  2, display 1
3. Go to display 2
4. Go back to display 1 (space 2)

Actual result:
It looks like picture-in-picture catches focus and triggers space change to the one that contains the browser (space 1, display 1)

Expected result:
Display 1, space 2 should be focused without any space change.

Notes:
I set `manage=off` for Arc, so this app is not even managed by Yabai

**Comment by koekeishiya** [comment]
Might be fixed on the latest master, but I don't use Arc and it will not let me do anything in the application without creating an accout and signing in, so cannot verify.

**Comment by roelvangils** [comment]
I confirm that updating to yabai-v6.0.4 resolves this issue.

**Comment by ftqo** [comment]
I think this should be re-opened. Note that the video starts on space 1. When I switch to space 3, Picture-in-Picture shows as expected. However, when I switch to space 4, yabai immediately switches back to space 1.
![CleanShot 2024-06-20 at 10 17 10](https://github.com/koekeishiya/yabai/assets/55212219/07affe94-d28d-4b1e-b334-56449a7a1ce4)

**Comment by diocletiann** [comment]
I have this issue with Firefox as well. The PiP window steals focus when changing spaces and the previously focused window in the space has to be manually focused.

**Comment by karsonenns** [comment]
Confirming that this is still an issue on Yabai 7.1.5.
Browser: Arc 1.72.1 (56511)
