### ISSUE TITLE
toggle focus_follows_mouse by skhd

### ISSUE THREAD

**Issue by mr-scrpt** [koekeishiya/yabai#2032]
I want to be able to turn focus_follows_mouse on and off - because this option is sometimes very useful, and sometimes very disturbing. I made this config in skhd
```
ctrl + shift + alt - a : yabai -m config focus_follows_mouse on
ctrl + shift - a : yabai -m config focus_follows_mouse off
```
And disabling the option works as needed, but after that it is no longer enabled, you only need to restart yabai and in this case the position of all windows is reset.
Is there any way to solve this problem?

**Comment by koekeishiya** [comment]
> focus_follows_mouse [autofocus|autoraise|off]
>> Automatically focus the window under the mouse.

https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#config

**Comment by mr-scrpt** [comment]
@koekeishiya thanks, its work

**Comment by koekeishiya** [comment]
You can use this to toggle with a single bind:

```
ctrl + shift - a : [[ $(yabai -m config focus_follows_mouse) = "disabled" ]] && yabai -m config focus_follows_mouse autoraise || yabai -m config focus_follows_mouse off
```

**Comment by mr-scrpt** [comment]
> disabled

I originally wanted to make this option toggle. But your option doesn't work.

> ctrl + shift - a : [[ $(yabai -m config focus_follows_mouse) = "disabled" ]] && yabai -m config focus_follows_mouse autoraise || yabai -m config focus_follows_mouse off

I originally wanted to make this option toggle. But your option doesn't work.
