### ISSUE TITLE
Disable SIP on Sonoma

### ISSUE THREAD

**Issue by Demianeen** [koekeishiya/yabai#2034]
I recently started to use Yabai and I did partially disable SIP for Apple silicon using the steps from [Disabling System Integrity Protection guide](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection).

But the commands like focusing spaces are not working. I suspect this is because the SIP is not disabled how it should be for MacOS Sonoma.

Did I do something wrong, or the steps are different for Yabai on MacOS Sonoma?

I use Macbook M1 Pro chip with MacOS Sonoma 14.2.1 (23C71) and yabai-v6.0.2.
`csrutil status` result:
```bash
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
        Apple Internal: disabled
        Kext Signing: enabled
        Filesystem Protections: disabled
        Debugging Restrictions: disabled
        DTrace Restrictions: enabled
        NVRAM Protections: disabled
        BaseSystem Verification: enabled
        Boot-arg Restrictions: disabled
        Kernel Integrity Protections: enabled
        Authenticated Root Requirement: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

**Comment by koekeishiya** [comment]
SIP status look fine. You need to also enable support for user-space arm64e binaries as described here: https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

> # Open a terminal and run the below command, then reboot
sudo nvram boot-args=-arm64e_preview_abi

Afterwards you can open a terminal and run: `sudo yabai --load-sa` and it should work.

When you have confirmed that the above is working, you can automate that last `--load-sa` step with these instructions: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

**Comment by Demianeen** [comment]
Yep, that's works! Thanks)
