### ISSUE TITLE
Sonoma bug with switch language  

### ISSUE THREAD

**Issue by mortr3d** [koekeishiya/yabai#2035]
when I switch keyboard in terminal it works well, but in chrome it may even stop browser for 5-10 seconds, for switch language I use caps lock + space (caps switched with control) 

and when I'm uploading file in browser it's resizing browser window

Uploading Screen Recording 2024-01-03 at 6.19.39 PM.mov…

**Comment by mortr3d** [comment]
![Screen-Recording-2024-01-03-at-6 19 39 PM](https://github.com/koekeishiya/yabai/assets/155058842/cc17038e-3e89-46da-8336-6eb06a888356)

**Comment by koekeishiya** [comment]
You need to tweak your rules:

```
yabai -m rule --add app="^Google Chrome$" role=AXWindow subrole=AXStandardWindow manage=on
yabai -m rule --add app="^Alacritty$" role=AXWindow subrole=AXStandardWindow manage=on
```
