### ISSUE TITLE
move window modifier stop working

### ISSUE THREAD

**Issue by mortr3d** [koekeishiya/yabai#2038]
when I switch layout between bsp and float with skhd it can stop move window with modifier so I have to restart yabai and then moving windows available, I was trying to do debug but idk it doesn't happen when I'm tryna debug, I'm thinking its triggered when I off all windows with "cmd Q" so when I'm not close debug window it not happens 

OS Sonoma 14.2.1

.yabairc
<img width="645" alt="image" src="https://github.com/koekeishiya/yabai/assets/155058842/658fd033-0249-4b44-9932-4143d18828f2">

.skhdrc
<img width="960" alt="image" src="https://github.com/koekeishiya/yabai/assets/155058842/af069f7a-00c6-47c0-a402-a9f5544dbd40">

**Comment by mortr3d** [comment]
I got it. Doesn't matter what key setup for window dragging, you can press button and start dragging but if you press cmd Q while dragging it's stop dragging at all before you don't restart yabai

**Comment by koekeishiya** [comment]
Note to self:

    g_mouse_state.window = NULL;
    g_mouse_state.current_action = MOUSE_MODE_NONE;

never gets reset in mouse_up handler when the window is destroyed through cmd+w or cmd+q
