### ISSUE TITLE
Float sub-windows in Adobe 2024 apps

### ISSUE THREAD

**Issue by hrvstr** [koekeishiya/yabai#2039]
Since the 2024 updates, Adobe apps have stopped reporting their sub-windows.

In earlier versions, I could manage the main window and float sub-windows (new file dialogs, etc.) like this.

```
rule app="^Adobe After Effects$" title="^$" manage=on
rule app="^Adobe After Effects$" title=".*" manage=off
```

Now Adobe apps don't report their sub-windows anymore so this approach doesn't work anymore.

```
{
  "id": 1342,
  "pid": 24534,
  "app": "Adobe After Effects",
  "title": "",
  "frame": {
    "x": 8.0000,
    "y": 33.0000,
    "w": 1708.0000,
    "h": 1399.0000
  },
  "role": "AXLayoutArea",
  "subrole": "AXFloatingWindow",
  "display": 1,
  "space": 2,
  "level": 0,
  "layer": "normal",
  "opacity": 1.0000,
  "split-type": "vertical",
  "split-child": "first_child",
  "stack-index": 0,
  "can-move": true,
  "can-resize": true,
  "has-focus": false,
  "has-shadow": true,
  "has-parent-zoom": false,
  "has-fullscreen-zoom": false,
  "is-native-fullscreen": false,
  "is-visible": false,
  "is-minimized": false,
  "is-hidden": false,
  "is-floating": false,
  "is-sticky": false,
  "is-grabbed": false
}
```

![Adobe After Effects - Adobe After Effects 2024 - Unbenanntes Projekt  - 2024 01 04 17 27 51](https://github.com/koekeishiya/yabai/assets/4610008/071ea92e-10dc-49d1-af44-8053e0e7e338)

Did anybody find a workaround for this?

**Comment by koekeishiya** [comment]
Remove both rules and see how it works, they should no longer be necessary.

Alternatively add role=AXWindow subrole=AXStandardWindow to the rule that sets manage=on

**Comment by hrvstr** [comment]
When I remove the rules both windows (main and sub) float. I noticed it works fine in Photoshop but After Effects, Premiere, Media Encoder, and Audition are not managed by default.

I completely forgot about the role and subrole arguments. Your suggested values didn't work but I took the values from the output in my first comment and it worked:

```
yabai -m rule --add app="^Adobe (After Effects|Audition|Media Encoder)$" role="AXLayoutArea" subrole="AXFloatingWindow" manage=on
```

Thanks for the help and quick reply!

**Comment by mehd-io** [comment]
Thanks for the suggestion.
FYI, due to the similar root issue, for Adobe Premiere Pro 2024, to make it work :
I had to add these two rules for the intro window and main editing 
```
yabai -m rule --add app="^Adobe Premiere Pro 2024$" role="AXLayoutArea" subrole="AXFloatingWindow" manage=on
yabai -m rule --add app="^Adobe Premiere Pro 2024$" role="AXLayoutArea" subrole="AXDialog" manage=on
```
Couldn't find a way to ignore subwindows due to these existing sub-roles that need to be managed
