### ISSUE TITLE
Upgrading Yabai breaks mouse click

### ISSUE THREAD

**Issue by gmenih** [koekeishiya/yabai#2040]
A few weeks ago I ran `brew upgrade`. One of the updates was for Yabai. When the upgrade finished, my mouse stopped working. I could move it around, but I couldn't click anything. Gestures worked as well, I could swipe between spaces, open the launchpad, etc.. but I couldn't click anything, anywhere. I shrugged it off, long pressed the power button and upon restart, everything worked.

Today I upgraded brew again, and Yabai was upgraded again. The exact same problem happened, and I had to restart my system again. 

When I get back into the OS I have to re-allow Yabai, and then do another restart before Yabai starts working.

Could this be caused by Yabai? It's the only package that was upgraded both times.

**MacOS Version**: 14.2.1 (23C71) (Apple M3)
**Yabai version**: 6.0.4

**Comment by gmenih** [comment]
I had the same issue again today when upgrading to `6.0.6`. Since the keyboard still works, I was able to kill Yabai using Raycast, after which everything went back to normal, and that confirms that Yabai is causing this issue for me.

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/issues/1913#issuecomment-1780764168

Apple bug. There is no way to work around this as far as I know.
