### ISSUE TITLE
no longer can change workspaces

### ISSUE THREAD

**Issue by nagy135** [koekeishiya/yabai#2047]
Hello, after reboot (didnt update anything) i can do anything with skhd/yabai but it doesnt allow me to change workspace this way. Usually sudo yabai --load-sa was needed to make this last feature going but now it doesnt do anything. I ve been sitting on older versions (like few months) so I tried updating to brew release:

❯ yabai --version
yabai-v5.0.4
❯ skhd --version
skhd-v0.3.7

csrutil status returns: System Integrity Protection status: unknown

And also updated my mac to Sonoma 14.2.1

Any ideas what I might try? Thanks!

**Comment by nagy135** [comment]
Thanks, did it, it got new hash but it still doesnt work ...it acts very strange currently. It feels like sometimes yabai acts but a most of the time it doesnt do anything, not even manages windows. When I tried to run commands in terminal one ran got me error while another went through. What is happening? :(
```
❯ yabai -m window --space 1
yabai-msg: failed to connect to socket..
❯ yabai -m window --space 1
```

**Comment by nagy135** [comment]
Like now ...I split my browser with terminal side by side. Then closed the terminal and browser kept its half size for like 5 seconds then it caught up and made it fullscreen
When I use my skhd binds it works once then stops so I can change focus but cant go back.


Note to myself. Do NOT update apple devices until I absolutely have to :/

**Comment by rainzm** [comment]
Please check #2007, where you will find that you need to update to v6.0.2+.

**Comment by nagy135** [comment]
didnt see that one, thanks!
