### ISSUE TITLE
window_destoryed not firing after latest update

### ISSUE THREAD

**Issue by bahman777** [koekeishiya/yabai#2048]
I just updated to the latest version. All great except window_destroyed no longer fires. Any help is much appreciated. Running 14.2.1 Mac OS .

**Comment by koekeishiya** [comment]
Uh, my bad.. This check obviously doesn't work properly when a window is destroyed.. 

```
if (window_manager_is_window_eligible(window)) {
    event_signal_push(SIGNAL_WINDOW_DESTROYED, window);
}
```

**Comment by bahman777** [comment]
Thank you. Is there an update?  I can't build it - cert issues
