### ISSUE TITLE
Ability to switch spaces/desktop via yabai?

### ISSUE THREAD

**Issue by magicmark** [koekeishiya/yabai#205]
Thanks for all the hard work on this awesome project!

Apologies if I'm getting the naming mixed up here but -

Is it possible to jump to a different display via yabai? (So I can assign a keybinding to it from skhd?)

I thought `yabai -m space --move` would do this, but maybe I'm misunderstanding what this is supposed to do? 

(tl;dr can yabai do [this](http://osxdaily.com/2011/09/06/switch-between-desktops-spaces-faster-in-os-x-with-control-keys/)? although not quite equivalent since you can't jump to full screen apps this way via mission control, which hopefully you'd be able to do with yabai)

thanks!!

**Comment by dominiklohmann** [comment]
If you have the scripting addition installed, you can use the following command:

```sh
yabai -m space --focus <space selector>
```

Where *space selector* can be either a space index (starting at 1), `first` or `last` for either the first or the last space by index, `recent` for the most recently focused space or `prev` or `next` for the previous or next space by index.

Similarly, you can focus the visible space on another display by using `yabai -m display --focus <display selector>`.

**Comment by pat-s** [comment]
I have the following in my `.skhdrc`:

`cmd - 2 : yabai -m space --focus 2`

Equivalent for other desktop numbers. In addition I assign certain apps to certain desktops by clicking on the app in the dock and then "options -> assign to this desktop". Works like a charm.

**Comment by magicmark** [comment]
Ah gotcha thanks, I haven't yet disabled SIP, which is probably why it wasn't working for me :P

(Will have to continue looking for an alternative solution for switching spaces since I can't disable SIP on my work machine)

Thanks for your help!

**Comment by dominiklohmann** [comment]
> (Will have to continue looking for an alternative solution for switching spaces since I can't disable SIP on my work machine)

Your best option is to use the keyboard shortcuts you can set in System Preferences > Keyboards > Shortcuts > Mission Control, but as you noted above these cannot be used to focus native-fullscreen spaces. macOS does not expose any API for this, sadly, which is why yabai does this through the window server directly.

However, there may actually be a way around this. 

You can still focus windows on other spaces without the scripting addition, and macOS will switch the space for you. This also works with native-fullscreen spaces.

```sh
# focus the first window that yabai knows about on space 3, if there are any
yabai -m query --spaces --space 3 | jq -r '.windows[0] // empty' | xargs yabai -m window --focus
```

The downside to this approach obviously is that this cannot focus spaces that have no windows or spaces that yabai does not know about. You can visit all spaces once after starting yabai to work around the latter issue.

**Comment by dominiklohmann** [comment]
So @magicmark here's a complete workaround, which works with SIP enabled:

```sh
# focus space 3
index=3; eval "$(yabai -m query --spaces | jq --argjson index "${index}" -r '(.[] | select(.index == $index).windows[0]) as $wid | if $wid then "yabai -m window --focus \"" + ($wid | tostring) + "\"" else "skhd --key \"ctrl - " + (map(select(."native-fullscreen" == 0)) | index(map(select(.index == $index))) + 1 % 10 | tostring) + "\"" end')"
```

This works with up to 10 non-fullscreen spaces, and requires you to have `skhd` installed and running and `jq` installed. It works by either focusing a window on the space if one exists, or if no window exists by focusing the space instead using the Mission Control shortcut as set in the System Preferences. In the prefs, set the keyboard for switching to space 1 through 10 to <kbd>control</kbd><kbd>1</kbd>  through <kbd>control</kbd><kbd>0</kbd>.

**Comment by magicmark** [comment]
<3 @dominiklohmann 

Wow thank you!! This works great!

I love this project and all the contributors who work super hard on this - thanks again!

**Comment by colossatr0n** [comment]
Another option if you want to move left/right a space while using multiple displays without disabling SIP: 

1. Assign the "Move left/right a space" shortcut in `System Preferences>Keyboard>Shortcuts>Mission Control`
2. Open your `yabairc` config file and enable `mouse_follows_focus`
3. Focus on the display you're interested in with yabai.
4. Use the "move left/right a space" shortcut to switch left or right on the focused display.

The key is that the mouse needs to be placed wherever you want to switch spaces if you're using the MacOS shortcut.

**Comment by VictorTaelin** [comment]
I've installed the last version, 4.0.0, on OSX Monterey, Macbook Pro 13" (M1), and I still can't get scripting-addition to work:

```
v@v-2 ~ % yabai -m space --focus prev
cannot focus space due to an error with the scripting-addition.
```

Is this expected?

**Comment by ywwry66** [comment]
> 
> ```shell
> # focus space 3
> index=3; eval "$(yabai -m query --spaces | jq --argjson index "${index}" -r '(.[] | select(.index == $index).windows[0]) as $wid | if $wid then "yabai -m window --focus \"" + ($wid | tostring) + "\"" else "skhd --key \"ctrl - " + (map(select(."native-fullscreen" == 0)) | index(map(select(.index == $index))) + 1 % 10 | tostring) + "\"" end')"
> ```
> 
> This works with up to 10 non-fullscreen spaces, and requires you to have `skhd` installed and running and `jq` installed. It works by either focusing a window on the space if one exists, or if no window exists by focusing the space instead using the Mission Control shortcut as set in the System Preferences. In the prefs, set the keyboard for switching to space 1 through 10 to control1 through control0.

Since a5feed0 and d8926f9, `native-fullscreen` was changed to `is-native-fullscreen`, so the above code should be modified as
```
index=3; eval "$(yabai -m query --spaces | jq --argjson index "${index}" -r '(.[] | select(.index == $index).windows[0]) as $wid | if $wid then "yabai -m window --focus \"" + ($wid | tostring) + "\"" else "skhd --key \"ctrl - " + (map(select(."is-native-fullscreen" == false)) | index(map(select(.index == $index))) + 1 % 10 | tostring) + "\"" end')"
```

**Comment by ejbills** [comment]
You can do this without disabling SIP via `SLSBridgedMoveWindowsToManagedSpaceOperation` - validated working on macOS 26.4.1 (latest) @magicmark 

https://github.com/user-attachments/assets/8bc285eb-4ea8-492d-9c82-6461cc73e543

**Comment by asmvik** [comment]
Confirmed working. Implemented support for `yabai -m window --space` commands for SIP enabled configurations.
