### ISSUE TITLE
Using Screen Studio with Yabai

### ISSUE THREAD

**Issue by afadingthought** [koekeishiya/yabai#2050]
Every time I try to use Screen Studio I get a semi-transparent window that I can't get rid of. If I totally disable Yabai the small window is gone, but would like to make these two work together without issues. In my yabairc file I have a rule to not manage the app—and Yabai seems to respect that—, but still... I get that small window. 

```
yabai -m rule --add app="^Screen Studio$" manage=off
```

![2024-01-11 at 17 44 25@2x](https://github.com/koekeishiya/yabai/assets/124819289/3a33b885-5e15-488b-8dde-cb23b1d7cc4e)

**Comment by koekeishiya** [comment]
No idea what screen studio is or how it works. You can adjust your rule to make the window hidden: `yabai -m rule --add app="^Screen Studio$" manage=off opacity=0.0`

**Comment by ArtemXTech** [comment]
Hey, has anyone found the solution to this? I tried this one `yabai -m rule --add app="^Screen Studio$" manage=off opacity=0.0`, but it didn't work. I tried to specifically programmatically close this window. 

`yabai -m query --windows \
  | jq -r '.[] 
      | select(
          .app=="Screen Studio" 
          and .subrole=="AXDialog" 
          and .frame.w==100 
          and .frame.h==100
        ) 
      | .id' \
  | xargs -r yabai -m window --close
`

It worked, but it was closing everything - all of the other windows which are required for control of Screen Studio. I had to disable yabai service and restart the Screen Studio to remove this window which is not ideal

@afadingthought, what is your approach for addressing this problem? Thank you

**Comment by ognistik** [comment]
Hey @ArtemXTech , I have these two rules:

```
yabai -m rule --add app="^Screen Studio$|^Screen Studio Beta$" subrole="AXDialog" title!="Camera Preview" manage=off opacity=0.0001
yabai -m rule --add app="^Screen Studio$|^Screen Studio Beta$" subrole!="AXDialog" manage=off opacity=1.0
```

The first one hides the annoying window (skips the Camera Preview, since it's the same kind of window. The second one just unmanages Screen Studio, I don't remember why I have that one but I think it was somehow giving me trouble when managed.

**Comment by ArtemXTech** [comment]
> Hey [@ArtemXTech](https://github.com/ArtemXTech) , I have these two rules:
> 
> ```
> yabai -m rule --add app="^Screen Studio$|^Screen Studio Beta$" subrole="AXDialog" title!="Camera Preview" manage=off opacity=0.0001
> yabai -m rule --add app="^Screen Studio$|^Screen Studio Beta$" subrole!="AXDialog" manage=off opacity=1.0
> ```
> 
> The first one hides the annoying window (skips the Camera Preview, since it's the same kind of window. The second one just unmanages Screen Studio, I don't remember why I have that one but I think it was somehow giving me trouble when managed.

Thank you very much, Robert. It worked just fine. You easily saved me and others an hour(s)? of tinkering.
