### ISSUE TITLE
Issue with `TickTick` Window/Pop Focus When Using `yabai`

### ISSUE THREAD

**Issue by richban** [koekeishiya/yabai#2051]
### Description
I'm experiencing an issue with `TickTick` where some of its windows fail to focus correctly. This problem seems to be related to `yabai`, as disabling `yabai` resolves the issue.

### Environment
- Operating System: Sonoma 14.2.1
- `yabai` version: v6.0.0

### Steps to Reproduce
1. Enable `yabai`.
2. Attempt to focus on different `TickTick` windows.

### Expected Behavior
All `TickTick` windows should be focused without any issues.

### Actual Behavior
Some `TickTick` windows do not focus correctly.

### Troubleshooting Steps Taken
- Disabled `yabai`, which temporarily resolved the issue.
- Applied the following rule in my `yabai` configuration:
    ```
    yabai -m rule --add app="^TickTick$" sticky=off layer=above manage=off
    ```

### Additional Context
Here's a link to my `yabai` configuration for reference: [yabairc config](https://github.com/richban/system/blob/master/dotfiles/yabairc)

A screenshot illustrating the issue can be found here:

https://github.com/koekeishiya/yabai/assets/6967088/bb285dfd-2bb4-45a7-8dda-7ccb0464d7c5

### Request for Help
Has anyone else encountered a similar issue with `TickTick` and `yabai`? If so, how did you resolve it? Any insights or suggestions would be greatly appreciated.

**Comment by koekeishiya** [comment]
Try upgrading to v6.0.6.

**Comment by koekeishiya** [comment]
Should be working fine in v6.0.13. Closing this. Leave a comment if you have this issue in the latest version.
