### ISSUE TITLE
need config to bsp layout

### ISSUE THREAD

**Issue by imshenshen** [koekeishiya/yabai#2054]
I have a large monitor, and the layout of my first space is `bsp` . When I have only one window, I want to center this window, but not fill the entire monitor (given the large screen size). Can you add a configuration to achieve this? 
for example: 
`yabai -m config --space 2 bsp_only_window_width 60% ` or `yabai -m config left_padding_when_only_one_width 300` to override the default padding?

**Comment by ville6000** [comment]
@imshenshen if you float the window, you can define the window position to not fill the whole monitor. In example 

```
alt - t : yabai -m window --toggle float;\
          yabai -m window --grid 9:16:1:1:14:7

```

**Comment by koekeishiya** [comment]
You can automate this with padding settings and/or floating windows + grid system, and window_created signals.
