### ISSUE TITLE
Yabai manages Assistive Tech windows (kCGAssistiveTechHighWindowLevelKey)

### ISSUE THREAD

**Issue by harryaskham** [koekeishiya/yabai#2055]
Using Yabai alongside Talon Voice, which has a feature that opens a magnified view of the current mouse position as an Assistive Tech window, I find that sometimes (around half the time) this magnified window is tiled by Yabai, which stops it working (it needs to appear exactly where the mouse is).

Is there a way to configure Yabai not to manage such windows? The window has no title or presence in e.g. a list of running apps, or Yabai's detected windows, when it is visible, and so I've not been able to add a rule myself.

**Comment by harryaskham** [comment]
I took a screencast on v6.0.6 of the issue occuring, with some examples both of the overlay getting managed, not getting managed, and the ouput of `query` while doing so. In the video the overlay is correctly unmanaged maybe 90% of the time, but you can see examples of the fewer instances where it is managed and ends up being assigned to a tile in the layout.

https://www.youtube.com/watch?v=sI9viFN6-5Y

**Comment by koekeishiya** [comment]
Should be fixed on master.
