### ISSUE TITLE
Failed to connect to socket on space --create

### ISSUE THREAD

**Issue by rwxmad** [koekeishiya/yabai#2057]
Everything works as it should, but when I try to create a new space I get an error:
yabai-msg: failed to connect to socket..
Command: sudo yabai -m space --create 
OS: Sonoma 14.1.1
yabai version: yabai-v6.0.6

**Comment by koekeishiya** [comment]
Don't use `sudo` when sending messages.

**Comment by rwxmad** [comment]
> Don't use `sudo` when sending messages.

I tried without sudo, but still no result, space is not created for some reason

**Comment by imatw4r** [comment]
@rwxmad how did you resolve the issue? 
<img width="604" alt="image" src="https://github.com/koekeishiya/yabai/assets/22574645/7d27ed7c-dd09-418c-9592-8b51d92db5dd">

**Comment by rwxmad** [comment]
> @rwxmad how did you resolve the issue? <img alt="image" width="604" src="https://private-user-images.githubusercontent.com/22574645/311443988-7d27ed7c-dd09-418c-9592-8b51d92db5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTI4MDksIm5iZiI6MTcxMDE1MjUwOSwicGF0aCI6Ii8yMjU3NDY0NS8zMTE0NDM5ODgtN2QyN2VkN2MtZGQwOS00MThjLTk1OTItOGI1MWQ5MmRiNWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZjhjZWU4NzQ3Y2I5MDg1NGUzMGRkMDJkYWY3OTA2YjIzNTIxYmNmMTFmZTI3Y2ZmZmVjOWEwZTQxYTE2MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1VyHci0avF90mHsEURb8EidKbi7g6AGqEsBEiDx_JgE">

Аfter following these instructions the problem was solved:
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#configure-scripting-addition
