### ISSUE TITLE
Status bar: Workspace counter/indicator on multiple display setups

### ISSUE THREAD

**Issue by gtsop** [koekeishiya/yabai#206]
Setup:
OS: MacOS 10.14.6
Monitors: 2

Problem description:
I have 4 workspaces on monitor no. 1 and 3 workspaces on monitor no.2
The status bar **only counts the first 4 workspaces** present on the first monitor

**Comment by A13k2** [comment]
Setup:
OS: MacOS 10.14.6
Monitors: 2

I can only see the status bar on the main monitor.

**Comment by koekeishiya** [comment]
This is working as intended.

**Comment by uri** [comment]
It would be nice if the status bar would appear on multiple monitors. Sometimes I forget how many spaces and which space I'm on given a monitor.

**Comment by gtsop** [comment]
> This is working as intended.

@koekeishiya Can you please clarify that you are referring to my initial report? The "status bar exist on only one monitor" is not what I reported on this ticket. This is about a wrong counter of total open workspaces which I highly doubt is an intentional behaviour.

@A13k2 @uri please create a new ticket for your issue

**Comment by koekeishiya** [comment]
@gtsop 

My answer applies to both questions, sorry about the confusion. I would be more inclined to implementing #136 and have the spaces for that monitor draw on that specific bar, than I would enumerating all spaces to the primary bar that currently exists.

However, before considering that, I'd need to first decide which kind of information I personally would find interesting to display.

Simply showing all spaces is a trivial change if you don't mind cloning the repo and building from source. I can help you with the modifications if necessary, but I don't want it upstream as of now.

**Comment by gtsop** [comment]
@koekeishiya 
>  I would be more inclined to implementing #136

I agree with that inclination. Thinking that having only one status bar was an intentional decision led me to expect that the status bar would enumerate all workspaces

>  I can help you with the modifications if necessary, but I don't want it upstream as of now.

I respect that. Would you consider having ether #206 or #136 implemented but disabled by default (and enabled via a config setting)? I don't think it makes sense to implement such a core feature on a fork other than the original repository. Many people depend on your upstream and get updates through that.

**Comment by snaveevans** [comment]
@koekeishiya I'm looking to implement multi-monitor status bar in my forked version of your yabai.  I see the key files from #136 however I was wondering how the logic of instantiating multiple bars might go.  I have some ideas on but without going into further detail I wanted to know if this is the best place to discuss it or if you had some sort of chat/email you'd prefer to discuss this.
PS thank you so much for yabai and skhd, they are awesome!
