### ISSUE TITLE
documentation: Sonoma "smart tooltips" handling

### ISSUE THREAD

**Issue by lake-effect** [koekeishiya/yabai#2061]
<img width="448" alt="image" src="https://github.com/koekeishiya/yabai/assets/39317653/aee57cf1-10e7-4b92-8376-2115063ac661">

OSX Sonoma includes a new tooltip element in its UI to indicate text inputs and caps lock among other context hints. A common fix for tooltip-heavy apps previously was `yabai -m rule --add app="^${applications}$" manage=on layer=below` for applications that need this treatment, which leads to disorienting snapping behavior every time a tooltip appears (which Sonoma sometimes does automatically).

The fix is to use `yabai -m rule --add app="^${applications}$" layer=above`, which stops yabai from trying to manage the tooltips (as maintainers have commented as a fix for multiple recent issues), and move them up to the `above` layer so they're still visible.

I don't have wiki access but I wanted to post this since it's a common quality of life setting.

**Comment by koekeishiya** [comment]
Are these rule still necessary in the v6.0.6? Do you have some other examples where this happens besides Slack?

**Comment by lake-effect** [comment]
As far as I can tell these tooltips are inserted in every text window after upgrading to Sonoma: 
<img width="205" alt="image" src="https://github.com/koekeishiya/yabai/assets/39317653/dc883e92-e556-453f-83b9-afb21c647090">

I'm not sure if it's something that can be disabled at the OS level but another version appears when you let a text box sit active and idle for long enough (an (A) symbol instead of an (up) symbol). Those are the only two I'm aware of so far.

**Comment by koekeishiya** [comment]
These tooltips should be not managed by yabai anymore in the latest version, and they should not be modified in any way unless a user targets them specifically with rules filter on `subrole=AXDialog`. They should work just fine (and be visible) without any additional config. Is this not the case?

**Comment by lake-effect** [comment]
Looks like I'm on 6.0.4. I'll update and confirm.

**Comment by lake-effect** [comment]
Confirmed fixed in 6.0.6.

**Comment by BigBrotherJu** [comment]
@koekeishiya With yabai 7.1.0 managing two windows, the tooltip first blinks at the cursor position, then immediately moves to the upper left corner of the right window. Can this behavior be fixed? The tooltip removing around is not very comfortable for my eyes.
