### ISSUE TITLE
manage/don't manage browser extensions popups (i.e. MetaMask) properly

### ISSUE THREAD

**Issue by pseudobun** [koekeishiya/yabai#2064]
Related to Issue #1714.

The solution in the comments of the mentioned issue works for MetaMask (or any other wallet) popups, however, Chrome extensions background.html where developers can inspect console logs and such don't get managed as well. How can this be solved? I tried (along with the mentioned solution):
```
yabai -m rule --add app="^Google Chrome$" manage=off
yabai -m rule --add app="^Google Chrome$" title="Google Chrome" manage=on
yabai -m rule --add app="^Google Chrome$" title="DevTools" manage=on # this one doesn't seem to work
```

**Comment by koekeishiya** [comment]
First upgrade to the latest yabai version. If you nee rules, use `yabai -m query --windows` to get information and look for patterns that can be used to target your windows.
