### ISSUE TITLE
yabai scripting-addition payload (0x3C) doesn't support this macOS version! macOS Sonoma 14.3 (23D56)

### ISSUE THREAD

**Issue by g3mino** [koekeishiya/yabai#2065]
Seems that this is not a new issue _per sē_, but new for this version of Sonoma.

Happy fixing and many thanks for making the life of poor macOS users better ;-)

<img width="336" alt="image" src="https://github.com/koekeishiya/yabai/assets/157477913/90f62bfd-5d91-4478-bd7c-d23e0298430c">

**Comment by koekeishiya** [comment]
Intel or Apple Silicon?

**Comment by schmidtjonas** [comment]
I have the same message on Intel.

**Comment by g3mino** [comment]
Intel

**Comment by koekeishiya** [comment]
Apple Silicon is already working fine with v6.0.6. Intel support has been fixed on the latest master.

**Comment by g3mino** [comment]
> Apple Silicon is already working fine with v6.0.6. Intel support has been fixed on the latest master.

top man! Takk skal dere ha!
In the meantime, I am managing with Mission Control shortcuts.

**Comment by kabeersvohra** [comment]
@koekeishiya I was wondering if this covered `14.3.x` for apple silicon? I got the notification of `14.3.1` but haven't installed due to fear of breaking yabai scripting addition

**Comment by koekeishiya** [comment]
14.3.1 works fine on Apple Silicon yes. 14.4 will likely require an update.

**Comment by kabeersvohra** [comment]
Great thank you!
