### ISSUE TITLE
Window not snapping back into place with fast drags

### ISSUE THREAD

**Issue by rajfly** [koekeishiya/yabai#2066]
https://github.com/koekeishiya/yabai/assets/35727146/1f568eeb-bf84-41df-8b39-86ebb80855fd

Sometimes I have the habit of misclicking the tabs in a browser and end up clicking the areas beside the tabs. This causes me to drag the browser's position by a small amount. I noticed that at times, the window does not snap back into place after dragging it. I then realised after some testing that if the dragging is done fast enough, the window does not automatically snap back into place. Is there a setting I can set to prevent this accidental drags?

**Comment by alanmicah** [comment]
This also happens with me on Yabai v6.0.6 and on v6.0.4

**Comment by koekeishiya** [comment]
Same as #1199

**Comment by koekeishiya** [comment]
Fixed in v7.0.0.
