### ISSUE TITLE
Yabai acting strange

### ISSUE THREAD

**Issue by MrNeth** [koekeishiya/yabai#2067]
I installed from head and followed the instructions on codesigning the 'yabai-cert'. however when i run:

`yabai --start-service` or `yabai --restart-service`

Accessibility access will pop up even though this is turned on already

<img width="472" alt="image" src="https://github.com/koekeishiya/yabai/assets/89204085/fe651265-e644-4489-bb9f-2a9234866cf0">

<img width="481" alt="image" src="https://github.com/koekeishiya/yabai/assets/89204085/5d7d5330-2706-4ff0-b3bd-579180e18ee0">

The only way i have found to get Yabai working is running

`yabai &; disown` and I cant really understand why but i have been using this a while. Right now i have to restart my machine and run this just to reload new changes.

Im trying to fix this issue but ever since things changed from `brew services start yabai ` to `yabai --start-service`

Things seem to not be working so well for me.

**Comment by kabeersvohra** [comment]
if you delete yabai from accessibility completely and then restart yabai. When you restart, you can then enable it and it should keep working from then on

**Comment by MrNeth** [comment]
@kabeersvohra  I cannot believe it was this simple thank you mate!!

**Comment by kabeersvohra** [comment]
No worries :) it's actually a Mac bug rather than yabai
