### ISSUE TITLE
Setting rules persistently

### ISSUE THREAD

**Issue by pat-s** [koekeishiya/yabai#207]
I've read the docs about rules and signals but still can't figure out how to set rules permanently.

I've run `yabai -m rule --add app="^Todoist$" manage=off` to have Todoist pop as in floating style.

However, where do I place this rule so that it is applied globally after a reboot?
Simply putting it in `.yabairc` did not have an effect. 
Binding it to a shortcut via `skhdrc` is not a smart solution.

Am I overlooking something obvious? Happy to extend the wiki section by one sentence which makes "applying rules persistently" crystal clear 🚀

**Comment by dominiklohmann** [comment]
> However, where do I place this rule so that it is applied globally after a reboot?

You put it in your yabairc,  which is a file that gets executed whenever yabai starts.

> Simply putting it in `.yabairc` did not have an effect.

There's likely an issue with your configuration file.

There's three ways to debug it:
1. Run it manually and look out for error messages: `./path/to/yabairc`
1. Check the log files at `/usr/local/var/log/yabai/yabai.out.log` and `/usr/local/var/log/yabai/yabai.err.log` for errors
1. Run `sudo launchctl debug gui/$UID/homebrew.mxcl.yabai --stdout --stderr -- $(which yabai) --verbose` in one terminal window to configure yabai to print its logs to the current tty and run in verbose mode next time it starts, then open another terminal window and restart yabai, using e.g. `launchctl kickstart-k gui/$UID/homebrew.mxcl.yabai`

Rules are set permanently until yabai restarts, and can only be removed or overridden at runtime when given a label.

**Comment by pat-s** [comment]
Thanks for the extensive answer! I found out that when using fish instead of bash, you need to remove the `$` in the rule above to get it working.

I had set a shortcut for reloading the config but it does not report back if it had problems loading the config.
Sourcing the config manually revealed the problem.

After setting Todoist to be assigned to "all desktops" (via the dock options), I can easily pull it up in floating mode on any space - perfect!

**Comment by dominiklohmann** [comment]
The actual fix would then be to use single quotes instead of double quotes, because fish expands $ in double quotes, which broke the regular expression.
