### ISSUE TITLE
Problem with app TablePlus

### ISSUE THREAD

**Issue by honeybyhomo** [koekeishiya/yabai#2070]
When opening a new window/connection in TablePlus, yabai creates an empty space – it thinks there's a window but there isn't (so I can see my desktop).
After a  minimize + restore of TablePlus the issue is fixed.

**Comment by Hackmodford** [comment]
All the apps that use macOS native tabs suffer from this. Finder is another example.

**Comment by koekeishiya** [comment]
#68
