### ISSUE TITLE
Can't get any prompt from System Preferences 

### ISSUE THREAD

**Issue by therealmrcolor** [koekeishiya/yabai#2072]
![SCR-20240201-kig](https://github.com/koekeishiya/yabai/assets/21344989/161a9865-2eb4-4119-bb25-f7d5a6b73165)
I just installed yabai with homebrew but when i'm trying to start it with the command `yabai --start-service` nothing happen. I can't get any pop up from System Preferences. 
I have also partially disable SIP

I'm on Mac OS Sonoma 14.2.1, Macbook Pro 16 M1 Max

**Comment by kalamov** [comment]
sudo yabai --load-sa

**Comment by therealmrcolor** [comment]
unfortunately it didn't work, I ran the command and the desktop went momentarily black, I then ran the command to start yabai but it got stuck again with no pop-up. I tried running your command again and now I have this error `yabai: missing required nvram boot-arg '-arm64e_preview_abi'!`

**Comment by therealmrcolor** [comment]
Thank you but SIP is already disabled (as you can see in the video).When I try to start yabaii, it doesn't ask me for permission in accessibility, and gets stuck. Is there any way to manually add the path?
I also tried the command `yabaii --load-sa` but it gives me the error from before`yabai: missing required nvram boot-arg '-arm64e_preview_abi'!`
![ScreenRecording2024-02-04at10 48 18-ezgif com-video-to-gif-converter](https://github.com/koekeishiya/yabai/assets/21344989/7464b26e-5432-45fb-a181-b37601cf8483)

**Comment by therealmrcolor** [comment]
`nvram: Error getting variable - 'boot-args': (iokit/common) data was not found`

I'm on Sonoma 14.2.1, M1 Max

**Comment by therealmrcolor** [comment]
Yes i'm sorry i was missing the `sudo nvram boot-args=-arm64e_preview_abi` but didn't fix 
I also configured the scripting addon https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition but still the same, when i run `yabai --start-service` nothing happen. 

There's a way to manually add the path to accessibility? 

![image](https://github.com/koekeishiya/yabai/assets/21344989/7ef181f2-16f9-48cd-8977-d829313b92c0)

**Comment by therealmrcolor** [comment]
Thank you so much! It worked!

I think the key was 
`sudo yabai --uninstall-sa`
`yabai --uninstall-service`

![SCR-20240204-gh1](https://github.com/koekeishiya/yabai/assets/21344989/4ee90388-c6ad-4403-9712-3c754b19815f)
