### ISSUE TITLE
macOS Sonoma 14.4 Intel support

### ISSUE THREAD

**Issue by activated-coal** [koekeishiya/yabai#2073]
Classic "bleeding edge" OS issues:
- scripting no longer works for macOS Sonoma 14.4 Intel

`> sudo yabai --load-sa`
yields
`payload (0x0) doesn't support this macOS version!`

**Comment by CrazyCatZhang** [comment]
Does this affect the functionality of yabai?

**Comment by koekeishiya** [comment]
> The following features of yabai require System Integrity Protection to be (partially) disabled:

> focus/move/swap/create/destroy space
remove window shadows
enable window transparency
enable window animations
control window layers (make windows appear topmost or on the desktop)
sticky windows (make windows appear on all spaces on the display that contains the window)
toggle picture-in-picture for any given window

**Comment by brymon68** [comment]
> > The following features of yabai require System Integrity Protection to be (partially) disabled:
> 
> > focus/move/swap/create/destroy space
> > remove window shadows
> > enable window transparency
> > enable window animations
> > control window layers (make windows appear topmost or on the desktop)
> > sticky windows (make windows appear on all spaces on the display that contains the window)
> > toggle picture-in-picture for any given window

Curious if this changed? I remember when I first started using yabai many months ago and it suggested enabling SIP. Im on a managed work machine so that option is not available to me for obvious reasons. 

However, even with SIP enabled, I still could swap and focus. Perhaps something changed with upgrade to Sonoma?

**Comment by koekeishiya** [comment]
Spaces functionality has always required SIP to be disabled.

**Comment by koekeishiya** [comment]
Track https://github.com/koekeishiya/yabai/issues/2150
