### ISSUE TITLE
Won't tile Orion RC

### ISSUE THREAD

**Issue by k2662** [koekeishiya/yabai#2074]
yabai refuses to tile Orion RC browser.

**Comment by koekeishiya** [comment]
Works fine for me with the following version:

Orion
Version 0.99.126.4.1-beta (WebKit 618.1.2)
Build date Dec 14 2023
MacBook Pro (macOS Sonoma 14.3 build 23D56)

**Comment by k2662** [comment]
> Works fine for me with the following version:
> 
> Orion Version 0.99.126.4.1-beta (WebKit 618.1.2) Build date Dec 14 2023 MacBook Pro (macOS Sonoma 14.3 build 23D56)


I am on the rc version of orion. 
Version 0.99.126.4.1.5-rc (WebKit 619.1.1)

**Comment by koekeishiya** [comment]
What is the output of `yabai -m query --windows` when Orion RC has visible windows? Make sure you are on the latest version of yabai (v6.0.9).

**Comment by k2662** [comment]
ah! it's been fixed.

**Comment by k2662** [comment]
Orion RC now tiles properly.
