### ISSUE TITLE
Mouse pointer issue

### ISSUE THREAD

**Issue by Kana-fi** [koekeishiya/yabai#2075]
Fix mouse pointer raise issue, please.
I use macbook, and an external monitor as my main monitor.
Everything was worked fine, I didn't do any changes recently. Lately, I've noticed a bug with mouse pointer.

If there are no open windows on mac monitor, and I switch from main external to mac monitor, and again to main, mouse pointer doesn't raise on a window.
I tried to reinstall all, to reboot, etc, no luck.

**Comment by koekeishiya** [comment]
Might be fixed on master.

**Comment by Kana-fi** [comment]
Finally, it works now. Thanks!
