### ISSUE TITLE
Customize duration of opacity transition

### ISSUE THREAD

**Issue by lucaorio** [koekeishiya/yabai#208]
Is it possible to have an instant switch between spaces, and windows focus without any kind of animation? (like chunkwm)

I checked the _reduce motion_  accessibility option, but the opacity transitions are still kind of slow.

**Comment by dominiklohmann** [comment]
```sh
# focus selected space without animation
yabai -m  space --focus <space selector>

# focus selected window and iff necessary switch the space without animation
yabai -m window --focus <window selector>
```

See also: [The following features of yabai require System Integrity Protection to be disabled](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection#what-is-system-integrity-protection-and-why-does-it-need-to-be-disabled)

**Comment by lucaorio** [comment]
Thanks for getting back to me, @dominiklohmann :) SIP is disabled, and that's exactly how I'm switching between spaces/windows.

The windows focus relies on opacity:
```
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.5
```

But when I change focus to a window/space, there always is a fade in the opacity. I was wondering if it's possible to remove that transition.

I do not have this problem in simply using a border to highlight the focus.

![ScreenFlow](https://user-images.githubusercontent.com/299621/62892062-2c265180-bcfc-11e9-8be9-5de831471a05.gif)

**Comment by dominiklohmann** [comment]
The window focus change is instant, it's just the opacity transition that is not.

It's set to a fixed 0.2 seconds here:

https://github.com/koekeishiya/yabai/blob/6c846d4151e42c0c341add7e3df2799e39bb8b3f/src/window_manager.c#L426

**Comment by karbecker** [comment]
Hi @lucaorio sorry to ask this in this thread but would you mind telling me the name of the Vscode theme your using? Thanks!

**Comment by lucaorio** [comment]
Thanks for clarifying, @dominiklohmann . Would you consider making the duration of this transition overridable?

In _chunkwm_ this was possible with
```
chunkc set window_fade_duration 0
```

@karbecker I customized it a bit, but main theme is based on the Material one!

**Comment by dominiklohmann** [comment]
> Would you consider making the duration of this transition overridable?

That's something for @koekeishiya, who seems to have been semi–absent over the past week. I'm just a contributor here, and while I do know my way around the code base and have made a few changes locally, I am mostly helping here with triage and documentation. I am not a maintainer of this project.

In the meantime, you can easily fork this and change just that one value to `0.0f`.

Personally I consider this a feature worth implementing—it's a reasonable request and easily implemented.

**Comment by koekeishiya** [comment]
Implemented on master.

**Comment by lucaorio** [comment]
@koekeishiya I just installed `yabai-v2.0.0`, but in the error logs I get:
```
unknown command 'window_opacity_duration' for domain 'config'
```

**Comment by koekeishiya** [comment]
Turns out pasta is bad for you.
