### ISSUE TITLE
Feature Request: Option to Disable Transparency for Media Content

### ISSUE THREAD

**Issue by riceset** [koekeishiya/yabai#2081]
Hello,

Firstly, I would like to express my gratitude for developing such an exceptional piece of software that I use daily. It has significantly enhanced my workflow.

I understand that the transparency feature might not be intended for active windows, yet I find the addition of slight transparency to my web browser quite appealing. However, I've encountered an issue where the transparency effect also applies to images and videos within the browser, which is not always desirable.

Would it be possible to introduce an option or feature that disables transparency for media content? Specifically, I'm looking for a way to retain transparency for the overall browser window but ensure that images and videos remain opaque.

Thank you for considering my request.

**Comment by koekeishiya** [comment]
This is not possible as far as I know.

**Comment by koekeishiya** [comment]
When yabai changes opacity of windows, that opacity change applies to the fully composited state that is drawn to the screen, so it is not possible to change the opacity of specific elements.
