### ISSUE TITLE
Sonoma 14.3 M2 Pro - Yabai doesn't remove space transitions.

### ISSUE THREAD

**Issue by rublev** [koekeishiya/yabai#2083]
# goal

- only use yabai for destroying spaces when transitioning between them
- disable space transitions like i had it before

this is all i want to use yabai for which is why my config is so barren

# problem

My old version of Yabai from way back, I forgot which (used on BigSur) worked perfectly. Now the spaces still have animations. I enabled 'reduce motion' but there is still an animation present. I believe the old version I was on was 4.

My .yabairc looks like so:

```sh
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# monitor stdout: tail -f /usr/local/var/log/yabai/yabai.out.log
# monitor stderr: tail -f /usr/local/var/log/yabai/yabai.err.log

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# yabai -m config window_topmost on

# yabai -m config layout bsp
# auto destroy and create spaces
# https://github.com/koekeishiya/yabai/issues/213#issuecomment-569410906
# read -r -d '' action <<- 'EOF'
#   sidx="$(yabai -m query --spaces --display |
#     jq -er 'map(select(.windows | length < 1).index)[0]')"
#   echo $sidx
#   if [ "$sidx" != null ] ; then
#     yabai -m space "${sidx}" --destroy
#   fi
# EOF

read -r -d '' action <<- 'EOF'
  recent_space_index="$(yabai -m query --spaces | 
    jq -er 'map(select(.id | tostring == env.YABAI_RECENT_SPACE_ID))[0].index')"
  if yabai -m query --windows --space "${recent_space_index}" |
    jq -er 'length == 0'
  then
    yabai -m space "${recent_space_index}" --destroy
  fi
EOF

yabai -m signal --add event='space_changed' action="${action}"
# yabai -m signal --add event='application_terminated' action="${action}"
# yabai -m signal --add event='window_destroyed' action="${action}"

# yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          autofocus

# bsp or float (default: bsp)

# Override default layout for space 2 only
# yabai -m config --space 1 layout float

# yabai -m config top_padding    20
# yabai -m config bottom_padding 20
# yabai -m config left_padding   20
# yabai -m config right_padding  20
# yabai -m config window_gap     20

# yabai -m config window_topmost on
# yabai -m config window_shadow float
# yabai -m config window_opacity on
# yabai -m config window_opacity_duration 0.0

# yabai -m config active_window_border_topmost on
# yabai -m config window_border off
# yabai -m config window_border_width 4
# yabai -m config window_border_radius 4
# yabai -m config active_window_border_color 0xFF00FF00
# yabai -m config normal_window_border_color 0x00FFFFFF
# yabai -m config insert_window_border_color 0x00FFFFFF

```

**Comment by koekeishiya** [comment]
Yes, it works on both architectures. You need to make sure that it is installed and running natively, so that it matches the architecture of the running Dock.app.

**Comment by koekeishiya** [comment]
Yabai itself will work regardless, but if you are on an Apple Silicon, Dock.app is running as an arm64e binary. This means that for yabai to inject code (scripting-addition) you need to run yabai as an arm64 binary, and the arm64e version if the scripting-addition.

Not sure what you have changed to make it default to running through Rosetta 2.
Simply following the yabai installation instructions using the default macOS Terminal.app should make it just work.

**Comment by panayao** [comment]
@koekeishiya Bumping this as I am on Sonoma 14.3 and installed using the default method via Terminal.app and the delay is still present; any idea how to go about debugging this?

**Comment by koekeishiya** [comment]
This comment still applies for debugging purposes: https://github.com/koekeishiya/yabai/issues/1054#issue-1058384717

**Comment by koekeishiya** [comment]
This comment may be relevant to you: https://github.com/koekeishiya/yabai/issues/1766
