### ISSUE TITLE
Borders and Blur no longer working

### ISSUE THREAD

**Issue by hackrmomo** [koekeishiya/yabai#2084]
![image](https://github.com/koekeishiya/yabai/assets/5733032/42e49ac5-b181-4cfa-b734-fefb5fdd769a)

![image](https://github.com/koekeishiya/yabai/assets/5733032/693ce497-399e-4f85-a952-65e9601b40ed)

Just wondering if this is still a supported feature or not at this point. I checked the change-logs since the last release I was on and I don't see any mention?

**Comment by hackrmomo** [comment]
Oops - never mind I'm just blind - it's clearly there in version 6.0.0 release

**Comment by koekeishiya** [comment]
Just a note to future people who may end up here. Use https://github.com/FelixKratz/JankyBorders instead for window borders. It interoperated well with yabai features.
