### ISSUE TITLE
Multiple Copies of Yabai (Caused by homebrew upgrading yabai)

### ISSUE THREAD

**Issue by rkabrick** [koekeishiya/yabai#2086]
Hello, 

I have tried to find issues that mention this happening but to no avail (my apologies if I missed something). 

Every time I restart my M1 Macbook on Sonoma I get all of the notifications as if I have a fresh install `yabai`. I have to re-enable accessibility permissions and (as seen below) all the 'old' copies of yabai are still present. SIP is disabled, and like I said it only happens on system restart. 

I hope I'm just an idiot and missing something obvious... Definitely not the end of the world just super weird behavior.

![CleanShot 2024-02-08 at 15 49 25@2x](https://github.com/koekeishiya/yabai/assets/31963805/01c74870-c520-4512-8d7c-3e956ff40a3c)

**Comment by MonstrousOgre** [comment]
I'm facing a similar issue but for me it happens every time I upgrade yabai using Homebrew. It creates a new copy under Privacy & Security > Accesibility.

It doesn't happen when I restart. I looked for existing issues and couldn't find anything.

**Comment by thiagomeireless** [comment]
Yeah, same as @MonstrousOgre, I just upgraded to `6.0.10` and got another entry (I have 7 now 😅).

Does anybody knows how to remove them?

**Comment by MonstrousOgre** [comment]
I found a more simple way to remove it for now

> 
> Highlight the old yabai entries and press -
> 
> <img width="470" alt="Screenshot 2024-01-14 09 59 48" src="https://github.com/koekeishiya/yabai/assets/45719263/0072042a-735c-4c99-8791-d74b57e65e81">
> 

_Originally posted by @PhrantiK in https://github.com/koekeishiya/yabai/issues/1968#issuecomment-1890976980_

**Comment by szfkamil** [comment]
> Yeah, same as @MonstrousOgre, I just upgraded to `6.0.10` and got another entry (I have 7 now 😅).
> 
> Does anybody knows how to remove them?
> 
> Editing...
> 
> Alright I just found out a solution:
> 
> On a terminal, run this command:
> 
> ```shell
> sudo sqlite3 /Library/Application\ Support/com.apple.TCC/Tcc.db
> ```
> 
> It will open a prompt with `sqlite>`. Now run the below command to list all entries that contains `yabai`:
> 
> ```sql
> SELECT * FROM access WHERE client LIKE "%yabai%";
> ```
> 
> You should see the list with all entries you see in the Accessibility Menu. Now, run a command to delete all versions except the last one you have installed (in my case, 6.0.10):
> 
> ```sql
> DELETE FROM access WHERE client LIKE "%yabai%" AND client NOT LIKE "%6.0.10%";
> ```
> 
> After this your Accessibility Menu should only show one entry 👍🏻
> 
> Would love to have a solution in Yabai to automatically remove the old version after a new one is installed, do you think that's possible @koekeishiya ?

So when a new version of yabai is installed, the previous one is still there? I think this is why yabai broke for me all the time personally and due to its instability decided to uninstall it. Would you suggest running these commands on each update?

I have `6.0.11`and just removed the `6.0.10` version. I now have a duplicate entry for yabai `6.0.11` that's identical:
```
kTCCServiceAccessibility|/opt/homebrew/Cellar/yabai/6.0.11/bin/yabai|1|2|4|1|��
                                                                               ||0|UNUSED||0|1707731142|||UNUSED|0
kTCCServiceScreenCapture|/opt/homebrew/Cellar/yabai/6.0.11/bin/yabai|1|2|4|1|��
                                                                               ||0|UNUSED||0|1707731215|||UNUSED|0
```
Should I leave as is, or delete one of them? If so, how? I only have one entry for yabai in the UI.

**Comment by koekeishiya** [comment]
I guess this is happening because macOS stores the absolutepath when saving permissions, because yabai is a single binary application and not an app bundle. When homebrew upgrades yabai it places it in a folder specific to the version, so every brew upgrade causes the binary to be stored at a different path, resetting the permissions. 

You can remove permissions directly inside the macOS settings/permissions window. Just remove stale entry when upgrading. I'm not aware of any workaround as long as you install using homebrew, due to the above situation. 

I never experience this personally because I of course build from source manually, and the target binary never changes its location -- therefore simply codesigning the new binary with the same certificate as the previous binary is enough for macOS to retain permissions.

**Comment by thiagomeireless** [comment]
> > Yeah, same as @MonstrousOgre, I just upgraded to `6.0.10` and got another entry (I have 7 now 😅).
> > Does anybody knows how to remove them?
> > Editing...
> > Alright I just found out a solution:
> > On a terminal, run this command:
> > ```shell
> > sudo sqlite3 /Library/Application\ Support/com.apple.TCC/Tcc.db
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It will open a prompt with `sqlite>`. Now run the below command to list all entries that contains `yabai`:
> > ```sql
> > SELECT * FROM access WHERE client LIKE "%yabai%";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You should see the list with all entries you see in the Accessibility Menu. Now, run a command to delete all versions except the last one you have installed (in my case, 6.0.10):
> > ```sql
> > DELETE FROM access WHERE client LIKE "%yabai%" AND client NOT LIKE "%6.0.10%";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After this your Accessibility Menu should only show one entry 👍🏻
> > Would love to have a solution in Yabai to automatically remove the old version after a new one is installed, do you think that's possible @koekeishiya ?
> 
> So when a new version of yabai is installed, the previous one is still there? I think this is why yabai broke for me all the time personally and due to its instability decided to uninstall it. Would you suggest running these commands on each update?
> 
> I have `6.0.11`and just removed the `6.0.10` version. I now have a duplicate entry for yabai `6.0.11` that's identical:
> 
> ```
> kTCCServiceAccessibility|/opt/homebrew/Cellar/yabai/6.0.11/bin/yabai|1|2|4|1|��
>                                                                                ||0|UNUSED||0|1707731142|||UNUSED|0
> kTCCServiceScreenCapture|/opt/homebrew/Cellar/yabai/6.0.11/bin/yabai|1|2|4|1|��
>                                                                                ||0|UNUSED||0|1707731215|||UNUSED|0
> ```
> 
> Should I leave as is, or delete one of them? If so, how? I only have one entry for yabai in the UI.

Just leave it, one is for `Accessibility` the other is for `ScreenCapture`. I edited my comment as I didn't even notice we could do it directly from the UI, thanks @MonstrousOgre for showing that!

> I guess this is happening because macOS stores the absolutepath when saving permissions, because yabai is a single binary application and not an app bundle. When homebrew upgrades yabai it places it in a folder specific to the version, so every brew upgrade causes the binary to be stored at a different path, effectively resetting the permissions.
> 
> You can remove permissions directly inside the macOS settings/permissions window. Just remove stale entry when upgrading. I'm not aware of any workaround as long as you install using homebrew, due to the above situation.
> 
> I never experience this personally because I of course build from source manually, and the target binary never changes its location -- therefore simply codesigning the new binary with the same certificate as the previous binary is enough for macOS to retain permissions.

Makes sense! Thanks for explaining why it happens 👍🏻

**Comment by koekeishiya** [comment]
I've created a simple installer script that basically is doing what I am doing locally. This will allow you to always upgrade yabai  into the same filepath on disk, allowing macOS to retain the accessibility permissions by looking at the codesigning identity.

It basically downloads the same archvive that brew does, and performs some validation and copies the binary (and man page) onto your system, to directories specified by the user. Note that you will have to first uninstall the brew version of yabai before doing this. The wiki has been updated to include the following info:

--

A codesigned binary release of yabai can be installed using the yabai [installer script](https://github.com/koekeishiya/yabai/blob/master/scripts/install.sh); it will always point at the latest release version.

```sh
# install yabai binary into /usr/local/bin and man page yabai.1 into /usr/local/man/man1
curl -L https://raw.githubusercontent.com/koekeishiya/yabai/master/scripts/install.sh | sh /dev/stdin

# install yabai binary into ~/Software/bin and man page yabai.1 into ~/Software/man
curl -L https://raw.githubusercontent.com/koekeishiya/yabai/master/scripts/install.sh | sh /dev/stdin ~/Software/bin ~/Software/man
```


Obviously the path specified as the target binary directory (and man page) should be some place in your $PATH , and the user executing the script needs write permission to that directory.

**Comment by luisdavim** [comment]
cool, can homebrew be updated to use this script?

**Comment by koekeishiya** [comment]
I'm not a brew expert, but it is my understanding that the limitation mentioned with destination directory/path above is an inherent part of how brew manages packages, so making brew "use this script" doesn't really make sense.
