### ISSUE TITLE
Cannot manage the Obsidian.md app

### ISSUE THREAD

**Issue by szfkamil** [koekeishiya/yabai#2089]
For over a week, the app [Obsidian](https://obsidian.md/) cannot be tilled with yabai. I was able to change its opacity and other properties, but was unable to tile it. I also tried to explicitly add a rule to manage it, with no luck.
```
yabai -m rule --add app="^Obsidian$" sticky=off opacity=1 manage=on
# manage=tile did not work
#sticky=off neither
```

I cannot perform any actions related to tilling as well: throw focused window to space, etc.

The app is a dock application. App is on version 1.5.3

**Comment by koekeishiya** [comment]
Output of `yabai -m query --windows` ?

**Comment by koekeishiya** [comment]
Ok so based on the output, the reason why it won't tile is 1: `"is-native-fullscreen":true`.
Second observation is `"can-move":false` which means in practice that the window is not allowed to be moved through the macOS accessibility API. If you make sure that the window is not in native fullscreen (macOS fullscreen mode), the folling rule will force it to bypass the `can-move` verification check, but the API can still freely decline the request to move the window.

```
yabai -m rule --add app="^Obsidian$" manage=on
```

**Comment by szfkamil** [comment]
I don't know what happened, but I will say for future readers: There were certain apps that had this issue smometimes, but this seems to have been fixed in one of the recent updates.
