### ISSUE TITLE
Add config option to completely hide the macOS menubar

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#2091]
Title.

Adjust opacity:

`yabai -m config menubar_opacity 0.5`

completely hide the macOS menubar (making it ignore mouseclicks, effectively disabling it completely):

`yabai -m config menubar_opacity 0.0`

When entering a native-fullscreen space, the menubar will be activated again automatically by yabai, and adjust it back down afterwards.

Works regardless of what "System Settings -> Automatically hide and show the menu bar" is configured to be.

This does not allow yabai to place windows in the menubar space / behind the notch, so it is purely a cosmetic feature.

**Comment by diocletiann** [comment]
@koekeishiya is it possible to hack the background color of the menubar? I disable transparency in macOS which unfortunately makes it annoying shade of gray.

**Comment by koekeishiya** [comment]
I'm not aware of any way to modify the color

**Comment by diocletiann** [comment]
> I'm not aware of any way to modify the color

Thanks for the reply. menubar_opacity 0.5 helps in masking the notch.

**Comment by qns7** [comment]
> When entering a native-fullscreen space, the menubar will be activated again automatically by yabai, and adjusted back down afterwards.

Is it possible to deactivate this, so that the menubar keeps hidden even in fullscreen?

**Comment by Bellavene** [comment]
System Settings
<img width="486" alt=" 2025-01-13 at 19 31 41" src="https://github.com/user-attachments/assets/6724e5dd-dd73-4196-b445-1db996d4b17f" />

**Comment by qns7** [comment]
> In some way I can understand you, but in others I can't. Because the menu bar in macos is a part of the current applications UI. So turning it completely off will leave you blind in serious applications. And just for imaginable “aesthetics”? While it is doable, and even more, I would not recommend that.
> 
> https://github.com/aspauldingcode/macwmfx
> 
> Or python
> 
> ```
> import autopy.mouse as mouse
> from time import sleep
> 
> while True:
>     x, y = mouse.location()
>     if y < 5:
>         mouse.move(x, 5)
>     sleep(0.1)
> ```
> 
> Or Hammerspoon
> 
> ```
> mouseEventTap = hs.eventtap.new({hs.eventtap.event.types.mouseMoved}, function(event)
>     --todo: you could filter with hs.application.frontmostApplication() if you want to only block the menu for certain apps. I don't
>     local rel = hs.mouse.getRelativePosition()
>     if(rel.y < 5) then
>         local frame = hs.mouse.getCurrentScreen():fullFrame()
>         local abs = event:location()
>         abs.y = frame.y + 5
>         local newEvent = event:copy():location(abs)
>         newEvent:post()
>         return true
>     end
> end)
> mouseEventTap:start()
> ```

It's not something I 'need', I was just curious.
You are right basically though in needing it from time to time, but I have a clickable item in sketchybar to make it visible if needed.
And to the googling: I don't know what's your problem in asking this question in this exact pre-existing thread, where the topic is exactly matching and the creator does mention on-point what I'm interested in. (_When entering a native-fullscreen space, the menubar will be activated again automatically by yabai, and adjusted back down afterwards._)
It this upsets you I don't understand, really.

**Comment by Bellavene** [comment]
Because this question itself is old. The best way is to do it with the mentioned defaults command, I don't remember it. But i know that there are many dot files repos here on github, whose include that built in setting.

**Comment by qns7** [comment]
> Because this question itself is old. The best way is to do it with the mentioned defaults command, I don't remember it. But i know that there are many dot files repos here on github, whose include that built in setting.

Yeah... ok. My question was also months old and I didn't bother too much about getting an answer. But thanks and let's end this here. Have a good time. :-)

**Comment by Bellavene** [comment]
The question is much older than that :) You could find the answer without waiting at all

**Comment by qns7** [comment]
> The question is much older than that :) You could find the answer without waiting at all

Since it seems I didn't made that clear enough: 
You mentioned and shared kind-of-interesting workarounds.
That's not what I'm interested in and of course something that can be done easily in many different ways.
I wanted to know if it's possible within yabai itself since it's said that
_the menubar will be activated again automatically **by yabai**, and adjusted back down afterwards._
by the author.
And in this regard I couldn't find anything back then while checking for a few minutes.
But as I said it's not something I'm very nervous about.
I just wanted to ask casually and didn't thought anyone could be this offended by that (also months later): Despite my reply being half a year & slighly more later, which I was well aware of.
But thanks for reaching out (really, no irony!) despite that you didn't give me any new insights.
And I will be more aware of trying to not-annoy anyone in the future this way.

PS: The defaults command should be ´defaults write NSGlobalDomain _HIHideMenuBarDelay -float <seconds>
´ as far as my shell-history tells me.

Best regards
a WOman perhaps in need to up her search-engine-game

**Comment by Bellavene** [comment]
I also did not want to offend you. But I believe the hiding of the menubar for your special needs is out of the scope of the project itself. Especially when it can be done in many ways.

**Comment by aspauldingcode** [comment]
> > When entering a native-fullscreen space, the menubar will be activated again automatically by yabai, and adjusted back down afterwards.
> 
> Is it possible to deactivate this, so that the menubar keeps hidden even in fullscreen?

Yes.

I will try to write you a plugin for ammonia specifically to toggle on/off macOS menubar completely.

Will you want a hotkey? maybe alt+shift+m or something?

**Comment by aspauldingcode** [comment]
> https://github.com/aspauldingcode/macwmfx

macwmfx is in development. Thanks for the mention <3

**Comment by diocletiann** [comment]
> > https://github.com/aspauldingcode/macwmfx
> 
> macwmfx is in development. Thanks for the mention <3

Could macwmfx be used to remove window decorations (edges, rounder corners) or just the title bar? Thanks!

**Comment by aspauldingcode** [comment]
> Could macwmfx be used to remove window decorations (edges, rounder corners) or just the title bar? Thanks!

macwmfx is a heavy wip. 

Currently, it has ability to remove shadows, remove titlebars, traffic lights, define custom corner radius (0 for square, something like 12 for round edges, 40 is massively shaved off corners), add window opacity, move traffic lights to the right side (like in windows by Microsoft), inline window borders, rename a macOS window (the title can be arbitrary), Terminate the application if the last tab was closed, but several things need to be fixed and many apps crash in its current state. The configuration works.

I'm working on:
Inline, outline, centerline borders, currently only inline works (this is a fast borders for macOS!)
recolor traffic lights
recolor titlebars
recolor titles
recolor the entire macOS (finder, system settings, etc). 
remove menubar
add menubar items to a window under the titlebar (like in windows, or wine apps, or linux apps)

This project will take awhile. I need to research apple's .car files, window server (for outline borders).
Currently, I am working on restructuring of the repo, and several programming convenience edits..

eventually we will have some lovely things on macOS.
