### ISSUE TITLE
Window copying to certain spaces

### ISSUE THREAD

**Issue by hisbvdis** [koekeishiya/yabai#2093]
Hello.
Thanks for great application.

I just wanted to suggest idea of copying windows to spaces.
It's useful if I want to work with the same application in different contexts in single monitor.

For example, I open my IDE on the right half of display and "copy" it to the second space.
In the first space on the left half I open browser, and on the second space I open some manual.

It allows me to keep working with IDE in every space and at the same time open different applications with it.

Looking forward for your answer.

**Comment by koekeishiya** [comment]
You can make the IDE window sticky
.
Either manually using `yabai -m window --toggle sticky` or automatically using a rule `yabai -m rule --add app="NAME OF IDE" sticky=on`

**Comment by hisbvdis** [comment]
> yabai -m window --toggle sticky

Thanks so much. I will try it
