### ISSUE TITLE
Virtual Spaces

### ISSUE THREAD

**Issue by Hackmodford** [koekeishiya/yabai#2097]
Has anyone considered using what I would call a "virtual" space instead of using the built in feature?

I was impressed with the way Aerospace handled spaces by moving windows to the bottom right corner and having hotkeys redistribute the windows based on what "virtual" space you were on.

I'm curiuos why they didn't simply hide windows instead of moving them to a corner, but has Yabai considered doing something similar with spaces to avoid the SIP issue?

**Comment by koekeishiya** [comment]
People have asked for this before, and the short answer is that the goal of this project is to enhance the macOS experience, not replace it.

If I wanted to build a completely different desktop experience for macOS (disabling menubar, dock, gestures, mission control, app switcher, etc.), that can be done. 

It would be a lot of work to recreate all this/similar functionality and build a new polished experience though.

From what I know about AeroSpace, it is sort trying to create a different macOS by employing very specific workarounds, and «not playing nicely» with macOS features. I understand the motivation, but personally think it is the wrong approach.

**Comment by diocletiann** [comment]
I quickly switched back to yabai to get real spaces back fwiw. The transitions were too slow and it seems macOS can optimize away drawing content in other spaces.

**Comment by koekeishiya** [comment]
That is fine by me. I have never once tried to market yabai to users or told people that they should use this software. It was developed for my own personal use (and still is to this day).

**Comment by 24unix** [comment]
> IMO, as a twm, yabai is massively overhyped compared to AeroSpace, and I think AeroSpace will dethrone yabai in the long term, because of yabai's SIP shenanigans and the UX of built in spaces. I think you're over-estimating how much people actually care about "playing nicely with macOS features". I'd posit that the majority of users are searching for a fast-workspace-switching i3 experience on mac, not i3-if-you-disable-SIP-but-at-least-you-can-swipe-the-trackpad on mac. I get that yabai has already gone down this path though and it's not going to change, but as far as long term project prospects go, I do think that AeroSpace has made the better tradeoffs that really matter to most users.


It doesn't support transparency, the author finds that useless, so for me it's neither on option or alternative.
YMMV. Without Yabai I'd have switched back to Linux since years.
