### ISSUE TITLE
Unknown command for window_border

### ISSUE THREAD

**Issue by orientino** [koekeishiya/yabai#2098]
Hi, I am new to yabai and trying to set up the window border colors. However, the main command is not working:
```
yabai -m config window_border on
```
The error is
```
unknown command 'window_border' for domain 'config'
unknown command 'on' for domain 'config'
```
OS: Sonoma 14.3.1
Yabai: yabai-v6.0.12

**Comment by 24unix** [comment]
Borders have been removed a while ago.

**Comment by koekeishiya** [comment]
Window borders were removed almost half a year ago in v6.0.0: https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#600---2023-10-10

**Comment by koekeishiya** [comment]
Use https://github.com/FelixKratz/JankyBorders on macOS Sonoma.
