### ISSUE TITLE
Border and Switching Spaces Instantaneously Not Working on M2 Sonoma (14.3.1)

### ISSUE THREAD

**Issue by psygo** [koekeishiya/yabai#2099]
I've tried folllowing what was discussed on #1256 and #1925, disabling SIP (`csrutil`), and adding the following lines to my `yabairc` config:

```rc
#----------------------------------------------------------------------------
# Load SA (at the top)
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#----------------------------------------------------------------------------
# Border Configs
yabai -m config active_window_border_color   0xff8E83B8
yabai -m config normal_window_border_color   0xff51425C
yabai -m config insert_window_border_color   0xff8E83B8
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

yabai -m config window_shadow                float
yabai -m config window_border                on
yabai -m config window_border_width          4
#----------------------------------------------------------------------------
```

I've also used [the Load SA docs](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition) to update `/private/etc/sudoers.d/yabai` via:

```sh
echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai
```

(By the way, why is the premise for the command above "if you know what you're doing"? Isn't it much easier for anyone to simply use this command instead of editing the file directly?)

(And I think that the fact that the hash needs to be updated manually every time you `brew upgrade` is more important than a comment in the middle of that codeblock... And maybe there's a way of updating it automatically through a hook on `brew upgrade`?)

So far, neither the border nor switching spaces instantaneously are working. What am I missing here?

> For reference, [here](https://github.com/psygo/dotfiles_mac_m2_2023/blob/main/.config/yabai/yabairc) is my Yabai config.

**Comment by koekeishiya** [comment]
> So far, neither the border nor switching spaces instantaneously are working. What am I missing here?

Window borders were removed almost half a year ago in v6.0.0: https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#600---2023-10-10

If you follow the steps as written in the wiki for disabling and installing the scripting addition; it will work.


> (By the way, why is the premise for the command above "if you know what you're doing"? Isn't it much easier for anyone to simply use this command instead of editing the file directly?)

Because I want people to actually understand what modifications they are making to their system instead of copy-pasting a command.

**Comment by psygo** [comment]
> Window borders were removed almost half a year ago in v6.0.0:

Sad to hear. Colored borders are one of my favorite features of my i3 config.

> If you follow the steps as written in the wiki for disabling SIP and installing the scripting addition; it will work.

Did you manage to spot anything wrong with the steps I've taken so far?

**Comment by psygo** [comment]
Wait a minute. I think I've spotted what I did wrong.

I did everything right in the setup, but I was still switching spaces with the Mac default <kbd>Ctrl</kbd> + arrow keys. After overriding them on SKHD, everything works instantaneously as they should, on my `skhdrc`:

```rc
ctrl - right : yabai -m space --focus next
ctrl - left  : yabai -m space --focus prev
```

I thought this overriding would happen automatically or something. I don't know if others will follow my rationel, but I would suggest putting those lines in the docs somewhere (if they don't exist already, maybe I've skipped them).

I guess you can close this issue now, @koekeishiya .

**Comment by koekeishiya** [comment]
Use https://github.com/FelixKratz/JankyBorders for window borders on macOS Sonoma.
