### ISSUE TITLE
scripting-addition payload is outdated

### ISSUE THREAD

**Issue by joshmedeski** [koekeishiya/yabai#210]
I got the following error using the latest version of Yabai from Homebrew:

>scripting-addition
>payload is outdated, please reinstall!

How do I resolve this? I read through https://github.com/koekeishiya/yabai/issues/22 but didn't find a clear way to fix my issue.

**Comment by dominiklohmann** [comment]
> I read through #22

I doubt that. 

The first post clearly states that all Catalina beta issues belong in that thread. The last post as of writing this clearly states that the scripting addition has not been updated for the latest beta.

**Comment by joshmedeski** [comment]
Haha, thanks for the confidence @dominiklohmann.

I'm running macOS Mojave (v10.14.6) so the solutions in that thread didn't seem relevant to me.

**Comment by dominiklohmann** [comment]
If you're running 10.14.6, reinstall the scripting addition and kill the Dock.

From [Wiki: Installing yabai (latest release)](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release))

> ### Updating to the latest release
> 
> To update yabai to the latest version, simply upgrade it with Homebrew, reinstall the scripting addition and restart *Dock.app* again:
> 
> ```sh
> # stop, upgrade, start yabai
> brew services stop yabai
> brew upgrade yabai
> brew services start yabai
> 
> # reinstall the scripting addition
> sudo yabai --uninstall-sa
> sudo yabai --install-sa
> 
> # load the scripting addition
> killall Dock
> ```

yabai is telling you to run `sudo yabai --install-sa`—on newer versions, uninstalling first and restarting Dock is no longer necessary. Depending on which version of yabai you're on you might need to uninstall first and restart the Dock manually after.

**Comment by joshmedeski** [comment]
I think restarting the Dock fixed it, thanks!
