### ISSUE TITLE
YABAI focus_follows_mouse + macOS USB Video InstantView application = problems

### ISSUE THREAD

**Issue by aspauldingcode** [koekeishiya/yabai#2100]
Hi,

The problem is: when yabai and instantview are run together, if I hover over the macOS dock, ALL the apps open, even if they were closed they launch.

How to reproduce this:
Get an m1 macbook air 
get a m1 USB Display hub dock thing that requires macOS InstantView by Sillicon Motion
Enable focus_follows_mouse as autofocus or autoraise.
Boom. Nightmare.

**Comment by koekeishiya** [comment]
Sounds like https://github.com/koekeishiya/yabai/issues/863
