### ISSUE TITLE
mpv is not set to float when spawned from qutebrowser

### ISSUE THREAD

**Issue by ddevaal** [koekeishiya/yabai#2101]
For some reason mpv is being tiled when spawned from qutebrowser. How can I prevent this? It seems to float when I launch mpv.app directly (raycast/spotlight) but not from qutebrowser.

~/.yabairc (6.0.12):
```
yabai -m rule --add app="^mpv$" manage=off
```

```
$ yabai -m query --windows
{
        "id":8281,
        "pid":54841,
        "app":"mpv",
        "title":"The Dygma Defy: A Software Developer's Dream? - mpv",
        "frame":{
                "x":773.0000,
                "y":47.0000,
                "w":750.0000,
                "h":422.0000
        },
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "root-window":true,
        "display":1,
        "space":2,
        "level":0,
        "sub-level":-20,
        "layer":"normal",
        "sub-layer":"below",
        "opacity":1.0000,
        "split-type":"vertical",
        "split-child":"second_child",
        "stack-index":0,
        "can-move":true,
        "can-resize":true,
        "has-focus":false,
        "has-shadow":false,
        "has-parent-zoom":false,
        "has-fullscreen-zoom":false,
        "is-native-fullscreen":false,
        "is-visible":false,
        "is-minimized":false,
        "is-hidden":false,
        "is-floating":false,
        "is-sticky":false,
        "is-grabbed":false
}

```

I found this in your dotfiles @koekeishiya, does it work for you or are you using something else nowadays?

~/.qutebrowser/config.py
```
config.bind(';M', 'hint --rapid links spawn open -na /Applications/mpv.app {hint-url}')
config.bind('M', 'hint links spawn open -na /Applications/mpv.app {hint-url}')
config.bind('m', 'spawn open -na /Applications/mpv.app {url}')
```

~/.config/mpv/mpv.conf
```
no-border
cache=auto
```

**Comment by koekeishiya** [comment]
I'm not sure, I haven't used those configs in like 7 years. I would probably just copy a url in qutebrowser and use `shift + cmd - m : /Applications/mpv.app/Contents/MacOS/mpv $(pbpaste) &> /dev/null`

**Comment by ddevaal** [comment]
> I'm not sure, I haven't used those configs in like 7 years. I would probably just copy (yank?) a url in qutebrowser and use `shift + cmd - m : /Applications/mpv.app/Contents/MacOS/mpv $(pbpaste) &> /dev/null` in skhd.

That's a col idea. However it does the same thing for some reason. Briefly it is unmanaged, but after 1 sec it is tiled.

**Comment by ddevaal** [comment]
Not that I'm aware off. I think it's something on my system and not Yabai. Thanks for the help!
