### ISSUE TITLE
Set border options per space

### ISSUE THREAD

**Issue by benallan** [koekeishiya/yabai#211]
I tried setting border options for specific spaces but it seems like the settings were applied globally to all spaces. 

```
yabai -m config --space 2 window_border_width 4
yabai -m config --space 2 window_border off
```

Maybe this isn't supported?

What I'd really like to do is disable borders for spaces where I always use fullscreen windows since I think it looks better, but keep borders on spaces where I have a bsp layout with mutliple windows.

**Comment by benallan** [comment]
Thanks a lot for the suggestions. I installed from HEAD to get the `$YABAI_` env variables, and then realised that could I probably use a much simpler set up (avoiding any spaces logic), triggering on the `window_resized` signal:

- If a window is `zoom-fullscreen`, then turn the border off.
- If a window is not full screen, turn the border on.

The border toggle logic works fine, but it seems to cause a weird side effect: 

- Press zoom-fullscreen shortcut to fullscreen window: works ok.
- Press shortcut again to disable fullscreen: works ok.
- Press shortcut again to try to fullscreen window: **fails**. The window flickers and briefly changes to fullscreen size but immediately returns to normal size (not fullscreen). I inspect the window properties I see that `zoom-fullscreen` is set to 1. 
- Toggle twice more (-> normal -> fullscreen) and full screen works the next time. 

So every second attempt to fullscreen the window fails while I'm using my signal settings. I wonder what might cause this?

yabairc:
```
yabai -m signal --add event=window_resized action="$HOME/bin/yabai_borders.sh"
```

yabai_borders.sh:
```
#!/bin/bash

is_fullscreen=$(yabai -m query --windows --window "$YABAI_WINDOW_ID" | jq -re '.["zoom-fullscreen"]')
has_border=$(yabai -m query --windows --window "$YABAI_WINDOW_ID" | jq -re '.["border"]')

if [[ "$is_fullscreen" -eq "1" ]]; then
  if [[ "$has_border" -eq "1" ]]; then
    yabai -m window "$YABAI_WINDOW_ID" --toggle border
  fi
else
  if [[ "$has_border" -eq "0" ]]; then
    yabai -m window "$YABAI_WINDOW_ID" --toggle border
  fi
fi
```

**Comment by koekeishiya** [comment]
Toggling border would cancel the windows zoom. Fixed on master.

**Comment by benallan** [comment]
Works great now, thanks a lot!
