### ISSUE TITLE
Request: support bash arrays for configuration

### ISSUE THREAD

**Issue by szfkamil** [koekeishiya/yabai#2111]
Currently, the most efficient of sending yabai config messages is to use '\' like this: 

`# global settings
  yabai -m config                                \
	external_bar                main:41:0    \
     focus_follows_mouse          autoraise      \
     mouse_follows_focus	  on	         \
     window_origin_display        default        \
     window_placement             second_child   \
     window_zoom_persist          on             \
     window_shadow                on             \
     window_animation_duration    0.15           \
     window_animation_frame_rate  120            \
     window_opacity_duration      0.15           \
     active_window_opacity        1	         \
     normal_window_opacity        0.98	         \
     window_opacity               off	         \
     insert_feedback_color        0xffd75f5f     \
     split_ratio                  0.50           \
     split_type                   auto           \
     auto_balance                 off            \
     top_padding                  20             \
     bottom_padding               20             \
     left_padding                 35             \
     right_padding                35             \
     window_gap                   25             \
     layout                       bsp            \
     mouse_modifier               ctrl           \
     mouse_action1                move           \
     mouse_action2                resize         \
     mouse_drop_action            swap           \
     menubar_opacity		  0.5		 \
     config debug_output          on             
`
(Pardon the formatting on mobile. I didn't want to make it look even worse on purpose 😆)

Would be condensed to a bash array:

```
# Define the array
yabai_config=(
    external_bar=main:41:0
    focus_follows_mouse=autoraise
    mouse_follows_focus=on
    window_origin_display=default
    window_placement=second_child
    window_zoom_persist=on
    window_shadow=on
    window_animation_duration=0.15
    window_animation_frame_rate=120
    window_opacity_duration=0.15
    active_window_opacity=1
    normal_window_opacity=0.98
    window_opacity=off
    insert_feedback_color=0xffd75f5f
    split_ratio=0.50
    split_type=auto
    auto_balance=off
    top_padding=20
    bottom_padding=20
    left_padding=35
    right_padding=35
    window_gap=25
    layout=bsp
    mouse_modifier=ctrl
    mouse_action1=move
    mouse_action2=resize
    mouse_drop_action=swap
    menubar_opacity=0.5
    config_debug_output=on
)

# Apply the configuration
yabai -m config "${yabai_config[@]}"
```

Idea taken from: https://felixkratz.github.io/SketchyBar/config/tricks#using-bash-arrays-for-cleaner-configuration

**Comment by koekeishiya** [comment]
You can already do this though?

```
yabai_config=(
    "external_bar                off:40:0    "
    "menubar_opacity             0.625       "
    "mouse_follows_focus         on          "
    "focus_follows_mouse         autoraise   "
    "window_origin_display       cursor      "
    "window_placement            second_child"
    "window_zoom_persist         off         "
    "window_shadow               off         "
    "window_animation_duration   0.33        "
    "window_opacity_duration     0.33        "
    "active_window_opacity       1.00        "
    "normal_window_opacity       0.85        "
    "window_opacity              on          "
    "insert_feedback_color       0xaad75f5f  "
    "split_ratio                 0.50        "
    "split_type                  auto        "
    "auto_balance                off         "
    "top_padding                 14          "
    "left_padding                14          "
    "right_padding               14          "
    "bottom_padding              14          "
    "window_gap                  14          "
    "layout                      bsp         "
    "mouse_modifier              fn          "
    "mouse_action1               move        "
    "mouse_action2               resize      "
    "mouse_drop_action           swap        "
)

yabai -m config ${yabai_config[*]}
```

I'm not going to change the syntax to key=value pairing, because it breaks the uniformity of the command line interface/API.

**Comment by dominiklohmann** [comment]
> I'm not going to change the syntax to key=value pairing, because it breaks the uniformity of the command line interface/API.

If users want to have it they can always just use the shell a bit more creatively:

```bash
yabai -m config $(echo ${yabai_config[*]} | tr '=' ' ')
```
