### ISSUE TITLE
Request: Less features release and more stability

### ISSUE THREAD

**Issue by koalalorenzo** [koekeishiya/yabai#2112]
Hello!
I have been using yabai for a while now and I love it! That said, a non-issue that would be nice to address would be to have yabai releases less frequently, as it feels like there is not enough period for testing the new features before they are released.

The changelog has one-two changes per patch release right now. If we could have a bigger patch release planned after testing a little, chances are that we can test things a little easier.

Currently, I am having way too many upgrades in the last weeks. I noticed that after upgrading I had some bugs and after another one some things were a little better, then another upgrade that is buggy and one more stable. 

Please, this is a minor request, yabai is a mazing and nice as it is :) I can easily fix it by using a pin in brew for yabai, but I wish these changes would still be tested for a longer time before being shipped.

**Comment by koekeishiya** [comment]
I don't really have a set schedule for when I intend to spend time on development. 

The last few weeks I have made some changes, and the reason why releases have been somewhat sporadic is that I didn't think I'd end up doing more work for another couple of months. 

Obviously for whatever reason I felt like doing more things this time around, but don't get used to this level of activity.

So, when I actually make changes these days I release them fairly quickly afterwards. I do believe the only recent release that had a regression in terms of stability was 6.0.14.

**Comment by koalalorenzo** [comment]
I would suggest planning releases instead of pushing whatever feels ready.

That said, thank you for your work 🙏

**Comment by koekeishiya** [comment]
I do understand where you're going with this, but planning is actually time consuming in itself. Anyway, there will be a major release coming up, and after that there will likely be very little changes for the rest of the year as per usual.
