### ISSUE TITLE
iTerm Window does not immediately get resized after Tab Bar Appears

### ISSUE THREAD

**Issue by AlJohri** [koekeishiya/yabai#2117]
Running into a minor bug where introduction and removal of the iTerm tab bar changes the size of the screen which does not immediately get fixed by yabai until the screen is manually resized.

In this video, you can see when the tab bar gets added the screen gets larger vertically cut off from the bottom of the screen. Similarly, when the tab bar is removed, the window is smaller than the remaining screens.

https://github.com/koekeishiya/yabai/assets/2790092/19bf6db6-0455-4a7d-8f67-244c4d5458c9

**Comment by AlJohri** [comment]
I have worked around the problem for now with this iTerm2 setting to always show the tab bar:

![Screenshot 2024-02-24 at 4 08 18 PM](https://github.com/koekeishiya/yabai/assets/2790092/e7ea5c7a-f519-44f9-af6a-2b7dbc8bdb1e)

**Comment by koekeishiya** [comment]
Fixed in v7.0.0.
