### ISSUE TITLE
Why there's this red area when I move window on top of anotehr?

### ISSUE THREAD

**Issue by ironhak** [koekeishiya/yabai#2125]
Hi, why there's this area as in screenshot? It's a new thing? I didn't saw on previous versions. 
<img width="1300" alt="Screenshot 2024-02-26 at 11 54 17" src="https://github.com/koekeishiya/yabai/assets/62611612/f27cd308-0899-4c23-9daf-5840c82d0bb1">
When I drag a window on another one this area show up, similar to Windows 11 when I try to manually tile windows.

Can I change it's color/appareanace or remove it?
Thank's

**Comment by koekeishiya** [comment]
https://github.com/koekeishiya/yabai/issues/142
https://github.com/koekeishiya/yabai/issues/2109
