### ISSUE TITLE
Automatically destroy "empty" spaces

### ISSUE THREAD

**Issue by amanjitsk** [koekeishiya/yabai#213]
How can I update my yabairc to automatically destroy un-used spaces ? I am thinking of something like in i3, where I can close all windows in a given space, and jump to another space, and have the no longer used space automatically close. Currently, I have to manually destroy all my unused spaces. Any help would be appreciated!

**Comment by dominiklohmann** [comment]
```sh
# if there are at least 2 non-fullscreen spaces on the focused display,
# destroy the focused space
yabai -m query --spaces --display \
    | jq -re 'map(select(."native-fullscreen" == 0)) | length > 1' \
    && yabai -m space --destroy
```

The above code can then be used as an action from a signal, e.g. so it runs whenever a window is destroyed.

**Comment by amanjitsk** [comment]
I added the following line to my yabairc

```
yabai -m signal --add event=window_destroyed action="yabai -m query --spaces --display \
| jq -re 'map(select(."native-fullscreen" == 0)) | length > 1' \
&& yabai -m        space --destroy"
```
but it does not seem to work. Am I doing something wrong here ?

**Comment by dominiklohmann** [comment]
You need to escape the inner double quotes. Also you can put it all on a single line—the backslash at the end of the line in my above example is just for splitting the code up into multiple lines for readability.

**Comment by amanjitsk** [comment]
Yeah sorry for the naive copy-paste, but this is what I had

```
yabai -m signal --add event=window_destroyed action="yabai -m query --spaces --display | jq -re 'map(select(.\"native-fullscreen\" == 0)) | length > 1' && yabai -m space --destroy"
```
i.e. I had them inner quotes escaped as above. It still has no effect though!

**Comment by amanjitsk** [comment]
Okay I think I have a working solution. 

I have the following in my yabairc

```
yabai -m signal --add event=space_changed action="bash ~/.config/yabai/autodestroy.sh"
```
where `autodestroy.sh` is a script that contains

```
# autodestroy.sh
bash <(yabai -m query --spaces | \
     jq -re 'map(select(."windows" == [] and ."focused" == 0)) | \
     .[]| "yabai -m space \(.index|@sh) --destroy"')
```

**Comment by dominiklohmann** [comment]
> i.e. I had them inner quotes escaped as above. It still has no effect though!

Ah sorry, that was on me. You hit the max length for commands so yabai cut it off somewhere in the middle. This was discussed briefly in another issue and is supposed to be removed.

In your script, the `bash <(...)` is unnecessary.

Also your script is crashing the Dock in some situations, because yabai does not check whether you want to destroy the last non-fullscreen space on any display. Doing so crashes Dock.app.

**Comment by amanjitsk** [comment]
Right, I added the snippet you mentioned above to check if there are more than 1 non-fullscreen spaces on the display, i.e. `autodestroy.sh` looks like

```
yabai -m query --spaces --display | \
     jq -re 'map(select(."native-fullscreen" == 0)) | length > 1' \
     && bash <(yabai -m query --spaces | \
          jq -re 'map(select(."windows" == [] and ."focused" == 0)) | .[]| \
          "yabai -m space \(.index|@sh) --destroy"')
```
This hasn't caused any crashes with Dock.app as far as I can tell. Xargs would indeed be a slightly optimized solution (I just wanted to get something quick and dirty to get it to work)!

**Comment by Juzov** [comment]
I have another approach worth sharing.
Remove current space when focus is removed from it and the space is empty.

```
#$1 space to focus
# 2. delete if empty space!
windows="$(yabai -m query --spaces | \
    jq -r 'map(select(.focused == 1 )) | map(.windows[]) | length')"
if [ "$windows" -eq 0 ]
then
    yabai -m space --label deletelabel
    yabai -m space --focus "$1"
    yabai -m space deletelabel --destroy
else
    yabai -m space --focus "$1"
fi
```
this is a snippet of a longer script that also creates a space if you try to focus on a non-existing space.

**Comment by dominiklohmann** [comment]
@Juzov this is what I use nowadays:

```sh
#! /usr/bin/env sh

read -r -d '' action <<- 'EOF'
  recent_space_index="$(yabai -m query --spaces | 
    jq -er 'map(select(.id | tostring == env.YABAI_RECENT_SPACE_ID))[0].index')"
  if yabai -m query --windows --space "${recent_space_index}" |
    jq -er 'length == 0'
  then
    yabai -m space "${recent_space_index}" --destroy
  fi
EOF

yabai -m signal --add event='space_changed' action="${action}"
```

**Comment by rublev** [comment]
> @Juzov this is what I use nowadays:
> 
> ```shell
> #! /usr/bin/env sh
> 
> read -r -d '' action <<- 'EOF'
>   recent_space_index="$(yabai -m query --spaces | 
>     jq -er 'map(select(.id | tostring == env.YABAI_RECENT_SPACE_ID))[0].index')"
>   if yabai -m query --windows --space "${recent_space_index}" |
>     jq -er 'length == 0'
>   then
>     yabai -m space "${recent_space_index}" --destroy
>   fi
> EOF
> 
> yabai -m signal --add event='space_changed' action="${action}"
> ```

Is it possible to get this working while you are in that space? I.e., I've removed the last app from a space, and it automatically sends me back to the previous space.

**Comment by wgolledge** [comment]
@rublev am wondering this too... It would be nice

**Comment by koekeishiya** [comment]
Use the same kind of logic presented in the script above, but hook it up to the signal `application_terminated`. Instead of checking for number of windows on the most recent space, check the number of windows on the active space.

**Comment by srsholmes** [comment]
For anyone having issues with the above scripts I managed to get a slightly modified version working. 

```
#!/usr/bin/env bash
yabai -m query --spaces --display | \
     jq -re 'map(select(."native-fullscreen" == 0)) | length > 1' \
     && yabai -m query --spaces | \
          jq -re 'map(select(."windows" == [] and ."focused" == 0).index) | reverse | .[] ' | \
          xargs -I % sh -c 'yabai -m space % --destroy'
```

and then in yabairc

```
# Clean up empty spaces with no windows on them.
yabai -m signal --add event=space_changed action="sh ~/dotfiles/.config/yabai/scripts/cleanEmptySpaces.sh"
```
Hope that might help someone 👍

**Comment by terrancekennedy-okta** [comment]
Due to some changes to the yabai query json, I had to make a couple more tweaks to @srsholmes script:

```bash
#!/usr/bin/env bash
yabai -m query --spaces --display | \
     jq -re 'map(select(."is-native-fullscreen" == false)) | length > 1' \
     && yabai -m query --spaces | \
          jq -re 'map(select(."windows" == [] and ."has-focus" == false).index) | reverse | .[] ' | \
          xargs -I % sh -c 'yabai -m space % --destroy'
```

Unfortunately I can't fully test this because I don't have the scripting addition installed. However, I can say that it _detects_ empty spaces correctly on yabai v5.0.2 and tries (but fails) to destroy the right ones.

**Comment by emagaram** [comment]
When I exited fullscreen mode on YouTube the space gets deleted. I think this is because for a brief period of time during that transition, yabai thinks there are no windows on the screen. By simply adding a `sleep 2` onto the code of @teekennedy   , this problem went away.

**Comment by grimerssy** [comment]
A bit complicated, but I managed to handle hidden windows too (spaces with only hidden windows are deleted on space change)
Also, ignoring any space changes until there aren't any windows in native fullscreen is the cleanest solution as for my liking

```bash
yabai -m query --spaces --display | \
  jq -re 'all(."is-native-fullscreen" | not)' &> /dev/null || exit; \

hidden_windows=$(yabai -m query --windows | jq 'map(select(."is-hidden")) | map(."id")'); \

yabai -m query --spaces | \
  jq -re "map(select((.\"has-focus\" | not) and (\
    .\"windows\" | map(select(. as \$window | $hidden_windows | index(\$window) | not))\
    ) == []).index) | reverse | .[]" | \
  xargs -I % sh -c 'yabai -m space % --destroy'
```

Hope this helps the next stranger here

**Comment by grimerssy** [comment]
So, I revisited my previous solution since I wanted "garbage collector" to work even if there are native fullscreen spaces. Thought I'd share my new way of doing it, even though it
- is even more complicated
- might break in the future if order of events on entering native fullscreen changes
- doesn't allow labels to be placed on fullscreen spaces (since they are used to track the state)

```bash
yabai -m signal --add event=space_created action='
  prev_space=$(yabai -m query --spaces --space)
  new_space=$(yabai -m query --spaces --space "$YABAI_SPACE_INDEX")
  space_id=$(jq -e "select(.\"is-native-fullscreen\") | .id" <<< "$new_space") || exit
  json_space=$(jq "{ id: $space_id, homeSpace: .id } | tojson" <<< "$prev_space")
  label=$(jq -Rr "ltrimstr(\"\\\"\") | rtrimstr(\"\\\"\")" <<< "$json_space")
  yabai -m space "$YABAI_SPACE_INDEX" --label "$label"
'

yabai -m signal --add event=space_changed action='
  home_spaces=$(yabai -m query --spaces | jq "map(.label | try fromjson | .homeSpace // empty)")
  yabai -m query --spaces \
  | jq "
      map(
        select(.windows | length == 0)
        | select(.id as \$x | $home_spaces | index(\$x) | not)
      )
      | reverse
      | .[]
      | .index
  " \
  | xargs -I{} yabai -m space --destroy {}
'
```

Basically using labels to save ids of spaces, on which windows entered fullscreen, to skip them on garbage collection
