### ISSUE TITLE
Yabai manage=off window not working

### ISSUE THREAD

**Issue by MrNeth** [koekeishiya/yabai#2135]
since the update the following is not working

`yabai -m rule --add app="^System Preferences$" manage=off border=off`
`yabai -m rule --add app="^System Settings$" manage=off border=off`
`yabai -m rule --add app="^Archive Utility$" manage=off border=off`
`yabai -m rule --add app="^Activity Monitor$" manage=off border=off`
`yabai -m rule --add app="^Finder" manage=off border=off`
`yabai -m rule --add app="^Carpe$" manage=off border=off`

also this doesnt work for visual studio code specifically:

`yabai -m rule --add app="Visual Studio Code"   space=5`

**Comment by MrNeth** [comment]
update

This seems to work:

`yabai -m rule --add app!="^(Google Chrome|Visual Studio Code|Brave Browser|WhatsApp|Telegram|)$" manage=off`

still have an issue where yabai ignores VS Code

**Comment by merlinvn** [comment]
This config works for me.

```
yabai -m rule --add app=Code space=^4
```

To see the proper name for an app, you can use:

```
yabai -m query --windows --space 4
```
