### ISSUE TITLE
alt and mouse buttons to drag windows

### ISSUE THREAD

**Issue by aspauldingcode** [koekeishiya/yabai#2136]
Using the modifier for moving and resizing windows as "alt" makes problems with clicking another window.
Causes the previous window to hide. Probably a macOS default behavior. It needs to be worked around, and currently fixable by just using control or cmd instead. 

Ideally I could use alt.

**Comment by aspauldingcode** [comment]
Might need to implement some sort of macro.

**Comment by aspauldingcode** [comment]
Also, Karabiner Elements doesn't have a keybind remap for mouse and keyboard buttons together, so that one didn't work there. I also tried to do something with skhd, and I don't think I can.

**Comment by 24unix** [comment]
Since HyperDock isn't working any longer with current macOS I use Rectangle Pro for window movement, plays nicely with Yabai.

**Comment by aspauldingcode** [comment]
> use Rectangle Pro

I prefer not to. Sounds like a great solution for many. 
I just want to use alt instead of cmd to move and resize a window. They way yabai currently does this works wonderfully for me right now - almost exactly the same UX as using swayfx on my Linux Desktop.

**Comment by 24unix** [comment]
> > use Rectangle Pro
> 
> I prefer not to. Sounds like a great solution for many. I just want to use alt instead of cmd to move and resize a window. They way yabai currently does this works wonderfully for me right now - almost exactly the same UX as using swayfx on my Linux Desktop.


I like to move/resize the window without clicking a button, just hold alt to move, ctrl to resize.
I didn't find a way yet to do that with Yabai.

**Comment by koekeishiya** [comment]
Fixed in v7.0.0.
