### ISSUE TITLE
Alpha fade end transition of window animations

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#2137]
Just an experiment.. might not make it into an actual release.

**Comment by koekeishiya** [comment]
@felixkratz I know you had something like this in your fork for some time. This works a bit differently as it does not actually change anything on the real window. It just fades the proxy window itself instead of ordering it out instantly. Thoughts?

**Comment by FelixKratz** [comment]
I just tried it and it is in some cases better than the abrupt change and in others not.

It has the problem that if the window is transparent, the alpha of the proxy and the real window multiply for the duration of the fade, leading to an observable flicker on animation end, which is more distracting than the immediate scale transition in my opinion:

https://github.com/koekeishiya/yabai/assets/22680421/b6cd0c88-4ffe-4d06-b851-5f0a0821ca8e

Technically there is a way to keep the multiplied alpha constant during the fade, then it would certainly be visually pleasing and superior to the current approach.

**Comment by koekeishiya** [comment]
I think the version you had in your fork could probably work better. Doing the transition during the animation will also reduce the stretch-effect, resulting in a cleaner look.

**Comment by FelixKratz** [comment]
I actually used the fade in my fork till recently (removed it ~a week ago) for over a year and was quite pleased with it. It had some problems that I never looked deeper into, which where all connected to altering the window transform. Maybe there is a way to do this robustly, I would be all for it.

**Comment by koekeishiya** [comment]
Hm depends which problems you faced I suppose. 

There is no way to do this without modifying the transform. I tried a couple of things to grab a capture of the window after setting the frame, that would represent the finished state, but this isn't possible when the window has systemalpha 0.

The alternative was ordering the window out instead of changing sysalpha, but that breaks when an application forcefully takes focus or if the user switches focus/space.

**Comment by FelixKratz** [comment]
So the most severe problem I had was that the windows where dislocated (had a wrong tx ty transform) after wake, which I fixed hackily by restarting yabai on a wake event. I also had problems with certain windows just being too slow at their resize, e.g. a Safari window with a youtube window was so slow to resize thrugh the AX api that the transform was changed on the unresized window, resulting in comical window deformations. There where some more problems that I can not recall right now but I will add them to this comment once I remember

**Comment by koekeishiya** [comment]
Regarding the alpha, that is correct. If I understand correctly it works like this:

```
float alpha_a = 0.85; // real window
float alpha_b = 0.85; // proxy window
float observed_alpha = alpha_a + ((1.0f - alpha_a) * alpha_b); // 0.9775
```

So I'd need to adjust both the real window alpha and proxy window alpha following the curve of this equation
```
        (alpha_a + ((1.0f - alpha_) * alpha_b)) = 0.85
```

Where I'd want the real window to end up at 1.0 and the proxy window at 0.0 at the last frame.

**Comment by koekeishiya** [comment]
I think the alpha situation should be resolved in the latest commit.

**Comment by FelixKratz** [comment]
I like it. Looks really good.

The only thing that can cause some flicker still is
https://github.com/koekeishiya/yabai/blob/bd68e6d3659d8f83933d6fd16f385336b415f90f/src/window_manager.c#L573
where the real window is visible briefly before it is hidden again by the alpha fade. Maybe Including the regular alpha in the proxy swap out would be a way to counteract that?

**Comment by koekeishiya** [comment]
Should be fixed in the latest commit. It seems to work quite well from that I can tell. I guess it might not look all that good combined with automatic opacity fade, basically when a window loses or gains focus.. which I fixed with the "old" animation system before introducing this change #2116

**Comment by FelixKratz** [comment]
I noticed that canceling an animation while it performs the alpha fade leads to the original window not being hidden again. There would likely need to be another system alpha = 0 call during the intercept.

Apart from that (and #2116) I think it is superior to the previous system.

**Comment by koekeishiya** [comment]
> I noticed that canceling an animation while it performs the alpha fade leads to the original window not being hidden again. There would likely need to be another system alpha = 0 call during the intercept.

I think it must be something else going on, since the alpha fade is not really locked as part of the animation and it doesn't touch system alpha. The real window system alpha changes when the "original" animation finishes, and this also releases the window from the animation system. A new animation that is started while the fading is happening, doesn't know or care that the fade is happening, it will start as if it was a fresh animation.

If you are able to capture the issue in a video that could maybe help identify the real issue. Also does it happen if you turn `window_opacity off` completely? There are a lot of moving parts that impact eachother in this new system so the complexity kinda sky-rocketed in regards to potential combinations that cause bugs/interference.

**Comment by FelixKratz** [comment]
Ah ok then I think it is the old proxy window that still does its fade where the real window is already animating to the next point:
(slowed down)

https://github.com/koekeishiya/yabai/assets/22680421/1eb807f2-b7df-4336-9eb7-ccba8b279e8f

**Comment by koekeishiya** [comment]
That is indeed happening. Maybe it could be fixed somehow. The motivation for keeping the fade separate from the animation itself is so that the animation_duration config is the entire movement-part of the animation. The fade itself is always a fixed 0.25sec duration.

Maybe this is not the best design. I am open to input if you have some thoughts regarding this.

**Comment by FelixKratz** [comment]
Hm, its a bit complicated. As you said, from a maintainability perspective this feature introduces a lot of trouble. Yes, it looks nicer most of the time, but if I where to decide, I am not sure I would want to keep this change.

At the end the question is wether the (slight) improvement in visual fidelity is worth the extra trouble. For a solution that looks visually a *lot* more polished, the answer would probably be yes (e.g. a robust transform-fade solution would be worth it I think). Here the main problem of the visual discomfort is not really tackled -- the large stretches that are visible for the longest duration of the actual animation (given an easing function which eases out).

**Comment by koekeishiya** [comment]
It would probably be more managable if I moved the opacity animation code/loop outside of the Dock and into yabai.

**Comment by koekeishiya** [comment]
I think I'll attempt a transform solution where the transition is a part of the animation sorta like you did / the Apple animation. If I can get that working I will invest the necessary time and work to make sure that it works well with opacity changes.

**Comment by FelixKratz** [comment]
I think it is worth considering that there might be problems with the ordering of managed/unmanaged windows in the transform fade with the current implementation. All proxy windows will be on top of all user windows unless they are created as managed windows as well. This is essentially the same problem we had in JB, where I recreated the border as an unmanaged window to circumvent the problem.

**Comment by koekeishiya** [comment]
>  also had problems with certain windows just being too slow at their resize, e.g. a Safari window with a youtube window was so slow to resize through the AX api that the transform was changed on the unresized window

This seems to be the only real unsolvable problem.

**Comment by koekeishiya** [comment]
```
EVENT_HANDLER_DAEMON_MESSAGE: window --toggle zoom-parent
Total time: 522.2688ms (timer freq 24000000)
    EVENT_HANDLER_DAEMON_MESSAGE[1]: 1264 (0.01%, 100.00% w/children)
    parse_window_selector[1]: 82 (0.00%)
    handle_domain_window[1]: 144 (0.00%, 99.99% w/children)
    window_manager_animate_window_list[1]: 12528071 (99.95%)
    window_manager_focused_application[1]: 559 (0.00%)
    window_manager_focused_window[1]: 4181 (0.03%, 0.04% w/children)
    window_manager_toggle_window_parent[1]: 133 (0.00%, 99.95% w/children)
```

This is without animations enabled, so `window_manager_animate_window_list` simply calls the AX API directly to set the window position and size. This one zoom-parent command took 522ms to run, when performed on a Safari window playing a youtube video. As you can see in the breakdown, 99.95% of the 522ms was used by the AX API. That is insane, and I think this means that this is just dead in the water.

**Comment by koekeishiya** [comment]
Reverting these changes.

**Comment by koekeishiya** [comment]
@FelixKratz 

I made it so that all windows and their proxy, in the same animation, all swap in the same transaction.
Hopefully that doesn't mess too much with JankyBorders.

**Comment by FelixKratz** [comment]
I think it reintroduces the order-of-operations flickering. The notification to JB needs to be sent after the proxy is ordered in and before the proxy is ordered out, else there will be flickering. Maybe we could also bundle all notifications for an animation into a single mach_msg call, like this:
```c
diff --git a/src/window_manager.c b/src/window_manager.c
index 8c9a855..4416396 100644
--- a/src/window_manager.c
+++ b/src/window_manager.c
@@ -427,16 +427,26 @@ void window_manager_resize_window(struct window *window, float width, float heig
     CFRelease(size_ref);
 }
 
-static inline void window_manager_notify_jankyborders(uint32_t proxy_wid, uint32_t real_wid, uint32_t proxy_event, bool wait)
+static inline void window_manager_notify_jankyborders(struct window_animation* list, uint32_t count, uint32_t proxy_event, bool ignore_skip, bool wait)
 {
     mach_port_t port;
     if (g_bs_port && bootstrap_look_up(g_bs_port, "git.felix.jbevent", &port) == KERN_SUCCESS) {
-        struct {
+        if (count > 1024) return;
+        static struct {
             uint32_t event;
-            uint32_t proxy_wid;
-            uint64_t proxy_sid;
-            uint32_t real_wid;
-        } data = { proxy_event, proxy_wid, 0, real_wid };
+            uint32_t count;
+            uint32_t proxy_wid[1024];
+            uint32_t real_wid[1024];
+        } data;
+        data.event = proxy_event;
+        uint32_t counter = 0;
+        for (int i = 0; i < count; ++i) {
+            if (!ignore_skip && __atomic_load_n(&list[i].skip, __ATOMIC_RELAXED)) continue;
+            data.proxy_wid[counter] = list[i].proxy.id;
+            data.real_wid[counter] = list[i].wid;
+            counter++;
+        }
+        data.count = counter;
         mach_send(port, &data, sizeof(data));
         if (wait) usleep(20000);
     }
@@ -511,8 +521,6 @@ static void *window_manager_build_window_proxy_thread_proc(void *data)
     }
 
     window_manager_create_window_proxy(animation->cid, alpha, &animation->proxy);
-    window_manager_notify_jankyborders(animation->proxy.id, animation->wid, 1325, false);
-
     return NULL;
 }
 
@@ -558,11 +566,11 @@ static CVReturn window_manager_animate_window_list_thread_proc(CVDisplayLinkRef
 
     pthread_mutex_lock(&g_window_manager.window_animations_lock);
     SLSDisableUpdate(context->animation_connection);
+    window_manager_notify_jankyborders(context->animation_list, animation_count, 1326, false, true);
     scripting_addition_swap_window_proxy_out(context->animation_list, context->animation_count);
     for (int i = 0; i < animation_count; ++i) {
         if (__atomic_load_n(&context->animation_list[i].skip, __ATOMIC_RELAXED)) continue;
 
-        window_manager_notify_jankyborders(context->animation_list[i].proxy.id, context->animation_list[i].wid, 1326, true);
         table_remove(&g_window_manager.window_animations_table, &context->animation_list[i].wid);
         window_manager_destroy_window_proxy(context->animation_connection, &context->animation_list[i].proxy);
 
@@ -636,8 +644,8 @@ void window_manager_animate_window_list_async(struct window_capture *window_list
             float alpha = 1.0f;
             SLSGetWindowAlpha(context->animation_connection, context->animation_list[i].wid, &alpha);
             window_manager_create_window_proxy(context->animation_connection, alpha, &context->animation_list[i].proxy);
-            window_manager_notify_jankyborders(context->animation_list[i].proxy.id, context->animation_list[i].wid, 1325, false);
-            window_manager_notify_jankyborders(existing_animation->proxy.id, existing_animation->wid, 1326, false);
+            window_manager_notify_jankyborders(&context->animation_list[i], 1, 1325, false, false);
+            window_manager_notify_jankyborders(existing_animation, 1, 1326, true, false);
 
             CFTypeRef transaction = SLSTransactionCreate(context->animation_connection);
             SLSTransactionOrderWindowGroup(transaction, context->animation_list[i].proxy.id, 1, context->animation_list[i].wid);
@@ -669,6 +677,7 @@ void window_manager_animate_window_list_async(struct window_capture *window_list
     TIME_BODY(window_manager_animate_window_list_async___swap_proxy_in, {
     scripting_addition_swap_window_proxy_in(context->animation_list, context->animation_count);
     });
+    window_manager_notify_jankyborders(context->animation_list, context->animation_count, 1325, false, false);
 
     TIME_BODY(window_manager_animate_window_list_async___set_frame, {
     for (int i = 0; i < window_count; ++i) {
```

**Comment by koekeishiya** [comment]
So I already build a structure with the relevant data to send to the scripting-addition. Maybe that same data could be sent to jankyborders, to avoid doing multiple transformations.

**Comment by FelixKratz** [comment]
Sure, lets reuse the scripting addition payload data then.

**Comment by koekeishiya** [comment]
I don't know if that is a good idea either. I'll experiment a bit and see what I like most. I can probably do the required JB changes as well and submit a pr.

**Comment by FelixKratz** [comment]
Great, this is the patch I have in stash for JB to work with the above yabai patch:
```c
diff --git a/src/misc/yabai.h b/src/misc/yabai.h
index 210489c..47cf289 100644
--- a/src/misc/yabai.h
+++ b/src/misc/yabai.h
@@ -191,23 +191,29 @@ static inline void yabai_proxy_end(struct table* windows, uint32_t wid, uint32_t
 static void yabai_message(CFMachPortRef port, void* data, CFIndex size, void* context) {
   if (size == sizeof(struct mach_message)) {
     struct mach_message* message = data;
-    struct payload {
+    static struct payload {
       uint32_t event;
-      uint32_t proxy_wid;
-      uint64_t proxy_sid;
-      uint32_t real_wid;
+      uint32_t count;
+      uint32_t proxy_wid[1024];
+      uint32_t real_wid[1024];
     } payload;
 
     if (message->descriptor.size == sizeof(struct payload)) {
       payload = *(struct payload*)message->descriptor.address;
       if (payload.event == 1325) {
-        yabai_proxy_begin(context,
-                          payload.proxy_wid,
-                          payload.real_wid  );
+        for (int i = 0; i < payload.count; i++) {
+          static int counter = 0;
+          yabai_proxy_begin(context,
+                            payload.proxy_wid[i],
+                            payload.real_wid[i]  );
+        }
       } else if (payload.event == 1326) {
-        yabai_proxy_end(context,
-                        payload.proxy_wid,
-                        payload.real_wid      );
+        for (int i = 0; i < payload.count; i++) {
+          static int counter = 0;
+          yabai_proxy_end(context,
+                          payload.proxy_wid[i],
+                          payload.real_wid[i]  );
+        }
       }
     }
     mach_msg_destroy(&message->header);
```

**Comment by koekeishiya** [comment]
I went with your version, but 4096 bytes of storage:

```
        struct {
            uint32_t event;
            uint32_t count;
            uint32_t proxy_wid[512];
            uint32_t real_wid[512];
        } data
```

**Comment by FelixKratz** [comment]
Seems to work well, thanks!

**Comment by Bellavene** [comment]
When we can see the result? Can't wait : )

**Comment by koekeishiya** [comment]
This one probably won't happen sorry. My conclusion for now is unfortunately that yabai does not have access to the information necessary to be able to implement this solution cleanly.

**Comment by Bellavene** [comment]
Sad. Now even in fyabai the smooth transition is gone and terminal windows with transparency are animated sluggishly, in past it was bearable.
@FelixKratz any changes? Why the fade was removed?

**Comment by jpatrolla** [comment]
I'm not sure if this is a solution, but I managed to get around the flicker by setting set_window_frame on frame 0. Mines not using a proxy though, these are the real windows:

https://github.com/user-attachments/assets/908cccd4-2295-4022-b3fd-55fe935bcb3c

**Comment by asmvik** [comment]
Try Safari playing a youtube video while the window size grows both horizontally and vertically. Also how does window with minimum and maximum size constraints behave?

**Comment by jpatrolla** [comment]
Pretty solid for the most part I think.. just some minor jitters to account for when swapped from certain positions. 
Working through that logic now.

https://github.com/user-attachments/assets/4347b57a-825b-437d-99ba-ecf6ab3a1f9e
