### ISSUE TITLE
Auto truncate status bar titles

### ISSUE THREAD

**Issue by spencerwooo** [koekeishiya/yabai#214]
![image](https://user-images.githubusercontent.com/32114380/63146206-bf2cf780-c02c-11e9-99c3-b2f13530e63a.png)

As you can see, sometimes the status bar text is too long when displaying web pages with long titles. Take [powerline/powerline](https://github.com/powerline/powerline) for example. An option to truncate the title automatically would be nice. 👍

**Comment by awave1** [comment]
should the title truncate only if it overlaps with left or right parts of the bar?

**Comment by tsujp** [comment]
Perhaps a setting such that when `x%` of the bar's horizontal width is taken up the title is truncated with ellipses `...`. Will need some constant width set for the ellipses since they will technically add length also.

**Comment by koekeishiya** [comment]
Fixed on master, but couldn't be bothered with the additional complexity to add an ellipsis at the end.
