### ISSUE TITLE
Menu bar opacity on inactive displays

### ISSUE THREAD

**Issue by net** [koekeishiya/yabai#2140]
The native macOS menubar dims significantly on inactive displays when using multiple displays. The dimming effect is also somewhat laggy when the active display changes, as each menubar item seems to dim and un-dim on its own timing.

I wonder if there's a way yabai could force the menu bar to always have a fixed opacity/dimness, no mater which display is active. I know the dimming isn't caused by yabai, but it does seem to be within the domain of yabai :)

For some additional context, I use SketchyBar on the left side of my menubar, but on the right side I prefer to use the native macOS menubar since it has an unbeatable ecosystem of menubar apps, and so I can use native menu bar controls like WiFi and sound.

<img width="1800" alt="Screenshot 2024-03-04 at 11 18 12" src="https://github.com/koekeishiya/yabai/assets/6983821/b7bb9e62-b81d-4f73-8a6e-50fee97dd50a">
<img width="1800" alt="Screenshot 2024-03-04 at 11 18 01" src="https://github.com/koekeishiya/yabai/assets/6983821/17e221cd-e087-4a33-a7a9-ea07841a3a0f">

**Comment by koekeishiya** [comment]
I don't think there is a way to force a specific opacity for other displays, but I do think it is possible to make the menubar hidden on specific displays.

**Comment by net** [comment]
Okay, thanks for the info :)
