### ISSUE TITLE
Dragged window should be above

### ISSUE THREAD

**Issue by danilkinkin** [koekeishiya/yabai#2144]
I think dragged window should be above than all others. Tried to search how I can make it, but don't find anything similar.

On video, first dragged window have a correct behavior, but second not

https://github.com/koekeishiya/yabai/assets/10831688/606f28b1-74f7-4381-9f1b-42f42c5bfc51

### yabai config
```
# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# padding set to 12px
yabai -m config top_padding 24
yabai -m config bottom_padding 24
yabai -m config left_padding 24
yabai -m config right_padding 24
yabai -m config window_gap 24
```

**Comment by koekeishiya** [comment]
Use `autoraise` instead of `autofocus` if you want the window be above.
