### ISSUE TITLE
Change layer of window via command failed

### ISSUE THREAD

**Issue by danilkinkin** [koekeishiya/yabai#2145]
I try to toggle window from `bsp` to float centered via hotkey, and use next command for it

```
yabai -m window --toggle float;  \
yabai -m window --grid 11:16:3:2:10:7; \
yabai -m window --layer above;
```

First two command works great, but last with layer failed with next message:
```
could not change layer of window with id '45023' due to an error with the scripting-addition.
```

I want to make window above than others (make in main focus).  Video show how it's work now

https://github.com/koekeishiya/yabai/assets/10831688/5f8d55a1-add9-4c53-89bb-8a1f274ea262

I use this command incorrect, or can you recommend how I can make it?

Maybe good decision to always make focused windows above than others?

**Comment by danilkinkin** [comment]
I found command `yabai -m window --focus` and it's made what I want. But still leave question why command with layer fails?

**Comment by koekeishiya** [comment]
Make sure you follow the wiki on how to disable SIP and configure the scripting addition, if you want to change window layers.

https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

**Comment by rgsaura** [comment]
The Sticky windows work, but for some reason the layers command doesnt get recognized

❯ yabai -m window --layer below
unknown command '--layer' for domain 'window'
unknown command 'below' for domain 'window'
❯ yabai -m rule --add app="^Finder$" layer=below
unknown key 'layer'
