### ISSUE TITLE
Resizing text or creating tabs in iTerm does not trigger the tiling

### ISSUE THREAD

**Issue by tamasgal** [koekeishiya/yabai#2148]
I face the issue that whenever I resize the text (⌘+ or ⌘-) or even open new tabs in `iTerm`, the tiling is not triggered, so I need to do some action (swap tiles) to make them fit again.

There is however no workaround if there is now window. E.g. when having a single iTerm window covering the full screen, creating the tab will expand the window so that the very bottom part of the terminal is not visible.

Is there a way to tell `yabai` to retile when doing these actions?

I am using `v6.0.13` on Sonoma 14.3

**Comment by koekeishiya** [comment]
Track #2117
