### ISSUE TITLE
The document `yabai.osax` could not be opened after upgrading to Sonoma14.4

### ISSUE THREAD

**Issue by IanQS** [koekeishiya/yabai#2149]
So, as in the title, I updated to 14.4 and things stopped working. TL;DR I uninstalled and re-installed, but am running into issues with `yabai.osax` and apple's `Script Editor`. 

## Issues on Boot

The following are errors I see on log-in: [logs, here on pastebin](https://pastebin.com/7giAs3P0) and it mentions something about reopening a file(?). When I click reopen, I'm presented with this first error:

<img width="237" alt="Screenshot 2024-03-08 at 10 37 43 PM" src="https://github.com/koekeishiya/yabai/assets/6968573/46449664-a30f-4c8b-be66-40f091c8c3cd">

I'm not really sure what the dictionary is or how it's relevant here? When I then click OK, I see a new popup 

<img width="237" alt="Screenshot 2024-03-08 at 10 37 48 PM" src="https://github.com/koekeishiya/yabai/assets/6968573/333eb38e-7d1a-4583-9860-dc866bd8b586">

# Recreating

I've tried uninstalling by following [uninstall instructions](https://github.com/koekeishiya/yabai/wiki/Uninstalling-yabai) and then installing via [install instructions](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)).

Steps to recreate:

1) `brew install koekeishiya/formulae/yabai`
2) disable SIP, per the instructions. 

I've verified that SIP is disabled by running `csrutil status` and I see `System Integrity Protection status: disabled.`

3) populated the file `/private/etc/sudoers.d/yabai` with the output of `echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai`

4) Add

```
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
```

to the top of the `~/.config/yabai/yabairc` file.

5) Reboot

6) Run into the issues I mentioned at the  very start

# More information

MacOS Version: `Sonoma 14.4`
Yabai Version: `yabai-v6.0.15`
Xcode-select: `xcode-select version 2406`

**Comment by IanQS** [comment]
When I manually start yabai, via 

`yabai --start-service`, I see the same issues as above, in the screenshot. However, I'm able to run certain commands and they work fine:

```
yabai -m window --focus {north, south, east, west}
yabai -m window --space {1 - 10}
```

however, the command to focus on a different space is failing: `yabai -m space --focus 2` results in `cannot focus space due to an error with the scripting-addition.`

**Comment by IanQS** [comment]
I see https://github.com/koekeishiya/yabai/issues/2147 which describes the same issue, but with a different error message. I've also seen the fix suggested there, which points to https://github.com/koekeishiya/yabai/issues/2138, but I don't quite understand the fix and how it works, especially if it would even work in my case

**Comment by koekeishiya** [comment]
Track #2146
