### ISSUE TITLE
Line under space name doesn't scale correctly with font size

### ISSUE THREAD

**Issue by marcjoha** [koekeishiya/yabai#215]
Increasing the font size, will make it look like this for the left-most item:

![image](https://user-images.githubusercontent.com/3009167/63156558-35bdfb00-c015-11e9-8ec0-7ac93b225000.png)

**Comment by koekeishiya** [comment]
This is by design and working as intended

**Comment by koekeishiya** [comment]
Probably not something I will bother fixing.
