### ISSUE TITLE
Create/Focus Space doesn't work (no error, no effect)

### ISSUE THREAD

**Issue by imatw4r** [koekeishiya/yabai#2151]
@EDIT:
Fixed as of 10-03-2024 in commit `f16eba3` 

As @cockytrumpet mentioned:
> It now works after updating from HEAD and running:
> 
> sudo yabai --uninstall-sa
> sudo yabai --load-sa
> pkill -x Dock
> 

Hey, I have a problem with `yabai -m space --create`. The command does execute with no errors, however no space is created. I've read the instructions on [how to create a space](https://github.com/koekeishiya/yabai/wiki/Commands), I went through multiple Github issues related to spaces:

* https://github.com/koekeishiya/yabai/issues/2115
* https://github.com/koekeishiya/yabai/issues/763
* https://github.com/koekeishiya/yabai/issues/1282
* https://github.com/koekeishiya/yabai/issues/787

Someone had pointed out in one of the issue that he had similar problem when using yabai with only one (builtin) display. 
I went through uninstalling/installing scripting additions multiple times, but nothing works. Does anyone else has the same problem? I don't experience any other issue as of now (after installing yabai from HEAD), but only that one, which is critical to me.

CSR protection is disabled:
<img width="842" alt="image" src="https://github.com/koekeishiya/yabai/assets/22574645/1b1e1334-6ca6-491e-872c-b426e45d2a10">

MacOS Version: Sonoma 14.4

On screenshot below you can see I am executing the command multiple times on the right window, and then querying for spaces, but only one is created.
<img width="1711" alt="image" src="https://github.com/koekeishiya/yabai/assets/22574645/a52d5d82-6b4c-4b7d-b588-ddc566543a20">

**Comment by imatw4r** [comment]
Update:
I went and created multiple desktops manually by pressing CTRL + ARROW_UP and "+" button to the right.
<img width="1419" alt="image" src="https://github.com/koekeishiya/yabai/assets/22574645/3e2d04ce-2540-43ba-acd4-5c9843322e14">

Now I can see them as spaces, running `yabai -m query --spaces`:
<img width="854" alt="image" src="https://github.com/koekeishiya/yabai/assets/22574645/3df20b74-2ee8-40d3-b1e5-cc2d9168c56f">

However running `yabai -m space --focues <id>` bears now effect also:
<img width="633" alt="image" src="https://github.com/koekeishiya/yabai/assets/22574645/28621790-5590-4b96-a05d-fd3b23dd0ffb">

Moving windows between displays/spaces using: `yabai -m window --space 3` works just fine, but `yabai -m space --focus 3` bears no effect.

**Comment by epiliper** [comment]
I have this same problem, also after installing from HEAD!

- scripting addon configured 
- SIP is enabled 
- skhd running

**Comment by cockytrumpet** [comment]
It now works after updating from HEAD and running:

```
sudo yabai --uninstall-sa
sudo yabai --load-sa
pkill -x Dock
```

**Comment by imatw4r** [comment]
Fixed now - details in @cockytrumpet solution 🖖 🚀
