### ISSUE TITLE
Using alt as mouse modifier cause apps to disappear

### ISSUE THREAD

**Issue by ironhak** [koekeishiya/yabai#2154]
So, this is not a yabai problem but a macos "feature". Using alt as mouse modifier:
```
yabai -m config mouse_modifier alt
```
When dragging windows keeping alt pressed sometimes all other windows disappear, because it's a mac feature that if you do alt+click on desktop/app all other apps disappear. Is there a way to stop this macos "feature"?

**Comment by koekeishiya** [comment]
I don't have anything constructive to add right now, but these are related: #2136, #1809

**Comment by koekeishiya** [comment]
Related to #1877

**Comment by koekeishiya** [comment]
Fixed on master.

**Comment by koekeishiya** [comment]
Fixed in v7.0.0.

**Comment by ironhak** [comment]
Writing there in order not to open another issue, but with v7 of yabai when you do "mouse_modifier" key + right click to resize there's "lag", I mean that it does not work properly as before. 
See if you can reproduce, otherwise I'll open a new issue.

**Comment by koekeishiya** [comment]
friggin Apple.. https://github.com/koekeishiya/yabai/issues/2160

**Comment by ironhak** [comment]
You'll figure it out, you're doing amazing work and yabai is amazing!
Thank's for making it open-source.

**Comment by koekeishiya** [comment]
Should be fixed in v7.0.1.. just annoying breakage since that part of the code had no changes
