### ISSUE TITLE
Issue with installing Yabai

### ISSUE THREAD

**Issue by neuromaancer** [koekeishiya/yabai#2156]
The same issue in #1884
I follow the wiki installation process. Also tried what is mentioned in #1884, [these steps](https://github.com/koekeishiya/yabai/issues/1884#issuecomment-1771581224).
But, my yabai version is 5.0.15. but I get:
```bash
yabai: service file '/Users/neuromaancer/Library/LaunchAgents/com.koekeishiya.yabai.plist' is not installed! attempting installation..
yabai: service file '/Users/neuromaancer/Library/LaunchAgents/com.koekeishiya.yabai.plist' could not be installed! abort..
```
I tried running with `sudo`:
```bash
Could not enable service: 125: Domain does not support specified action
Bootstrap failed: 125: Domain does not support specified action
```

My system: 14.4 (23E214) m1 

result of `csrutil status`:
```bash
csrutil status                                                                                                                                                                                     (base)
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled
	Boot-arg Restrictions: disabled
	Kernel Integrity Protections: enabled
	Authenticated Root Requirement: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

**Comment by neuromaancer** [comment]
I think the problem is when I reinstall yabai, I didn't it in the Accessibility option in Mac System setting.

**Comment by koekeishiya** [comment]
This is the function that fails https://github.com/koekeishiya/yabai/blob/master/src/misc/service.h#L155

For some reason yabai cannot write the file (outlined in your error message) to disk. The most obvious reason is that either the directory does not exist and yabai cannot create it for you for whatever reason, or your user does not have write permission to that directory.

**Comment by neuromaancer** [comment]
Thank you for the information, but I can confirm that the directory is created and my user is admin, so I should have right to write the file in that directory.

**Comment by ironhak** [comment]
Here's how to fix: 
- Get info on LaunchAgents folder
- Click on the lock icon - unlock
- Set staff permission to Read&Write.

**Comment by neuromaancer** [comment]
Thanks! it works!

**Comment by neuromaancer** [comment]
I'd like to reopen this issue because I tried this on my Mac Mini M1 today, and it doesn't work. The same error persists. The only difference is that I only have `wheel` group not `staff`, so I enable `wheel` group, and it doesn't work. @ironhak

**Comment by ironhak** [comment]
Hello, maybe try creating `Staff` group and giving it read & write? Otherwise I wouldn't know, searched the web the other day because I had the same problem and there is little to no information, I just luckily discovered by myself the "fix" outlined on prev post.

**Comment by neuromaancer** [comment]
I can't create this `staff` group, because it is already there. `staff` actually is a legacy group. see [here](https://www.macstadium.com/blog/understanding-file-permissions-on-mac). Less and less this group will be used for read & write. Now it is the `wheel` group. I didn't go through the `yabai` code, I assume it goes via `staff` group? @koekeishiya 

After searching, there is a temporal solution:

1. Give the `staff` group the right of LaunchAgents folder via: `sudo chown -R :staff ~/Library/LaunchAgents/`
2. Grant the group read-write-execute permissions on the folder via: `sudo chmod -R 770 ~/Library/LaunchAgents/`
3. Run `yabai --start-service`.
4. If it doesn't work, try [this](https://github.com/koekeishiya/yabai/issues/2156#issuecomment-2041074042) again.

In this way, everything would be fine. 

@ironhak Thanks btw!

**Comment by koekeishiya** [comment]
I have no clue what is going on with your setup. Mine looks like this: 
<img width="240" alt="Screenshot 2024-04-08 at 21 42 56" src="https://github.com/koekeishiya/yabai/assets/6175959/57dfcb29-218d-4a9b-a342-81212bbdfade">

I've never had to mess with permissions.

**Comment by neuromaancer** [comment]
So strange. Anyway, I think this would be solved in this way. Thank you! @koekeishiya
