### ISSUE TITLE
window insert feedback visual not visible (below the window)

### ISSUE THREAD

**Issue by Sulfyderz** [koekeishiya/yabai#2157]
Hello,

When you drag a window over another or when calling `yabai -m window --insert ...`, the window insert feedback visual is not visible. It seems to be below the window. See the picture:
![Untitled](https://github.com/koekeishiya/yabai/assets/72023070/caa2ea56-c45a-4e38-9e57-059680b3cdd3)

Not sure if it's related to #2132, but I wanted you to know about that bug.

Best,
Sulfyderz.

**Comment by koekeishiya** [comment]
Is this in v6.01.15 or on master? 

The visual feedback should be above the window that it encapsulates, but not necessarily in front of all windows.

**Comment by Sulfyderz** [comment]
In v6.0.15.

What’s strange is that it worked not so long ago. I was able to drag a window over another one and see the visual assistance. Can’t figure out what changed.

**Comment by koekeishiya** [comment]
Closing in favor of #2132
