### ISSUE TITLE
macOS event garbage

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#2160]
Resize throttling timestep randomly changed when moving from `kCGHIDEventTap` to `kCGAnnotatedSessionEventTap` without the actual responsible code ever being touched... amazing

**Comment by koekeishiya** [comment]
The event timestep is not fixed between macOS versions.. Decouple throttling from event timestep and use a real timer instead.

**Comment by BeCracked** [comment]
> The event timestep is not fixed between macOS versions.. Decouple throttling from event timestep and use a real timer instead.

I know this is a random place for it, but Jesus. That sounds horrible to work with. Thank you so much for making this OS useable!
