### ISSUE TITLE
Can't get yabai to not ignore sketchybar

### ISSUE THREAD

**Issue by zanexGHG** [koekeishiya/yabai#2161]
So Im using sketchybar and the problem is I cant make yabai aware of it so windows stick to it when maximizing instead of ignoring it. I have googled for countless hours on how to fix this issue and the best solution I found was this: yabai -m config external_bar all:32:0

Unfortunatly this doesnt work. Why idk. Im currently sitting on an m1 mbp and macos 14.4.

pls help D:

**Comment by kinglouie** [comment]
what version are you on? For me `yabai -m config external_bar all:20:0` works like expected. Try issuing the command in a terminal and see if the windows get pushed down by 20px

**Comment by zanexGHG** [comment]
> what version are you on? For me `yabai -m config external_bar all:20:0` works like expected. Try issuing the command in a terminal and see if the windows get pushed down by 20px

Im on the newest version (7.0.2)

**Comment by albertsj1** [comment]
7.0.0 - 7.0.2 just came out yesterday and there appear to be a lot of changes.  Possibly could be a new bug; however, I know this works fine with the latest 6.x release.  6.0.15.
I'd suggest testing with 6.0.15 to see if it works with your configuration.  If it works with 6.0.15, it's likely a new bug with 7.x.

**Comment by zanexGHG** [comment]
All fixed after updating basically everything.
