### ISSUE TITLE
Querying mechanism issue

### ISSUE THREAD

**Issue by ErwinLiYH** [koekeishiya/yabai#2163]
Hi, I issued #2153 previously, Thank you very much for fixing this bug in version 7.0.2! But I find there is a problem remaining.

After minimising a window,  do not focus on any others, command `yabai -m query --windows --window` results "could not retrieve window details." while the command `yabai -m query --windows --space` shows the minimised window has property `has-focused: true`. I think these two outputs might be conflicted, because the Wiki shows the command `yabai -m query --windows --window` queries "focused/selected window", but it can't query the focused minimized window here.

**Comment by koekeishiya** [comment]
Same as https://github.com/koekeishiya/yabai/issues/1985
