### ISSUE TITLE
zathura is ignored by yabai

### ISSUE THREAD

**Issue by naba-nyan** [koekeishiya/yabai#2164]
Hi, Updating to v7.0.2, yabai does not work well for [zathura](https://github.com/zegervdv/homebrew-zathura).
The situation remains the same though I disable all rules for zathura.

`yabai -m query --windows` generates the following contents:

```
{
	"id":693,
	"pid":98344,
	"app":"zathura",
	"title":"",
	"frame":{
		"x":0.0000,
		"y":0.0000,
		"w":1200.0000,
		"h":828.0000
	},
	"role":"",
	"subrole":"",
	"root-window":true,
	"display":1,
	"space":3,
	"level":0,
	"sub-level":0,
	"layer":"normal",
	"sub-layer":"normal",
	"opacity":1.0000,
	"split-type":"none",
	"split-child":"none",
	"stack-index":0,
	"can-move":false,
	"can-resize":false,
	"has-focus":false,
	"has-shadow":true,
	"has-parent-zoom":false,
	"has-fullscreen-zoom":false,
	"has-ax-reference":false,
	"is-native-fullscreen":false,
	"is-visible":false,
	"is-minimized":false,
	"is-hidden":false,
	"is-floating":false,
	"is-sticky":false,
	"is-grabbed":false
}
```

**Comment by koekeishiya** [comment]
You need to focus space 3 for yabai to retireve an AX-reference to that window, and then it will be able to manage the window, or at least output more information like "can-move", "can-resize", "role", "subrole", and you can make a rule if necessary.

See https://github.com/koekeishiya/yabai/issues/2126 and the window section of the query documentation https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#query

**Comment by koekeishiya** [comment]
Maybe https://github.com/koekeishiya/yabai/issues/2118 but that is is just absolutely ridiculous from Zathura at that point.
