### ISSUE TITLE
How to query the last-focused windows id on a specific space

### ISSUE THREAD

**Issue by marsjane** [koekeishiya/yabai#2165]
To make the system setting more simple, I am going to use yabai without disabling SIP. Most things works fine, just one issue:
Now I use BBT to switch to another desktop, it has some problems.
If I have two monitors, like monitor A has space 1,2 and monitor B has space 3,4, it works fine when I switch between 1 and 2, with the focused windows also also switched between these two spaces, but if monitor B already shows space 3, if I use hot-key to switch from space 2 to space 3, the focused windows still on space 2. That's why I am trying to use `yabai -m query --windows --space 3 +???` command to get the last-focused windows id on space 3.
I don't know whether it can be done, if cannot I can only do  `yabai -m query --windows --space 3 | jq '.[0].id'` to get the first windows and focus to it. If possible I want to still focus to the windows I last focused on that space.
Any advice?

**Comment by koekeishiya** [comment]
The query you suggested will output the last focused window on that space; the list is ordered that way by macOS.
