### ISSUE TITLE
[Suggestion] Change the way of loading yabairc to execute yabairc file

### ISSUE THREAD

**Issue by MirageTurtle** [koekeishiya/yabai#2169]
TL;DL:
Loading yabairc by executing yabairc file can support more flexible script, at least fork the process using `bash` instead of `sh`.

Full Details:
I found some issue when I use the following configuration in my `~/.yabairc`:
```bash
#!/usr/bin/env bash
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

declare -A opacity
opacity["active"]=1.0
opacity["normal"]=0.8
yabai -m config window_opacity on
yabai -m config active_window_opacity ${opacity["active"]} 
yabai -m config normal_window_opacity ${opacity["normal"]}
```
And I get output:
```
yabai: scripting-addition failed to inject payload into Dock.app!
declare: -A: invalid option
+ yabai -m config active_window_opacity 0.8
+ yabai -m config normal_window_opacity 0.8
```

Obviously, the interpreter/the process is not `bash`, or the one specified by the Shebang. And I confirmed this by issue #1993. As #1993 clarifys, the proccess is `sh`, and I confirmed this by some code like `echo "Current Process Name: $(ps -p $$ -o comm=)"`.

I'm not sure if the failure of yabai injecting payload is caused by `sh`, but I get nothing wrong by execute them manually in a bash/zsh.

I'm not a good programmer. I tried to contribute to the source code but failed. So what I can only do is just raising an issue for suggestion.

**Comment by MirageTurtle** [comment]
If you think this suggestion is stupid, or hard to do, please let me know, especially why.

**Comment by koekeishiya** [comment]
I don't particularly care how this works either way. You can argue the case with @penglei author of #1993 and other nix users (@gldtn, @danryan).

**Comment by koekeishiya** [comment]
Note that this specific part of the code has been untouched since like v1.0.0 from 5years ago, prior to #1993.
I didn't actually know that having it interpret rather than execute would break running through particular shells.

**Comment by koekeishiya** [comment]
After spending more than 5 seconds it is obviously clear why the change suggested in #1993 would change this behavior.
I've changed it on master to execute the config as before, if the exec-bit is set, and it will interpret as suggested in #1993 if the exec-bit is unset.

If you belong to a third group that require other behavior; feel free to go buy ice cream.

**Comment by gldtn** [comment]
> I don't particularly care how this works either way. You can argue the case with @penglei author of #1993 and other nix users (@gldtn, @danryan).

I believe I was tagged by mistake, I don't use nix!

**Comment by MirageTurtle** [comment]
> After spending more than 5 seconds it is obviously clear why the change suggested in #1993 would change this behavior. I've changed it on master to execute the config as before, if the exec-bit is set, and it will interpret as suggested in #1993 if the exec-bit is unset.

Thank you very much! `sh -c` is powerful enough. Thank you again, and thank you for making yabai better.

Feel free to close this issue, or if you plan to do it after release.
