### ISSUE TITLE
Status bar bottom border

### ISSUE THREAD

**Issue by malfario** [koekeishiya/yabai#217]
First and foremost, I'd like to thank you for this awesome piece of software. I've been following your work since _Kwm_, and it has radically improved my user experience with macOS.

Now, I'd like to know if there is a way to turn off (or change the color) of the status bar's bottom border. I was expecting some kind of setting in the config file, but I've been unable to find any.

Again, thanks for your work!

**Comment by koekeishiya** [comment]
There is no setting for this, but I think I'm likely to remove the border completely anyway.

**Comment by malfario** [comment]
Not a big deal, thank you for taking your time to reply.
Cheers!
