### ISSUE TITLE
last window of space isn't removed from yabai's list when closed

### ISSUE THREAD

**Issue by dotrosedotnet** [koekeishiya/yabai#2174]
behavior I'm experiencing:

when I close the only window in a space, the window still shows up in `yabai -m query --spaces --space [the space I was in]`

this results in the icon continuing to show up in my list of spaces, on my sketchybar

behavior I'm expecting:

window is removed from yabai's json when window is closed

what other information should I provide?

Thank you so much! so glad that this software exists.

**Comment by koekeishiya** [comment]
I cannot reproduce this issue in latest version.

**Comment by dotrosedotnet** [comment]
I think it was an issue with my config. sorry for the false alarm!
