### ISSUE TITLE
Enhancement: select visible window when switching to space

### ISSUE THREAD

**Issue by rwijtvliet** [koekeishiya/yabai#2176]
When I switch the focus to a space, sometimes "Finder" becomes the active app, even if it has no windows on that space, and even if other apps *do* have windows on the space. 

This means I can now not "navigate" to the wanted tiled window, but must first command-tab into one, or (yikes) use the mouse to click on one.

Is there a way / would it be an improvement to automatically select a visible window when moving to a space?

**Comment by koekeishiya** [comment]
You can try the following signal:

`yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"`

**Comment by rwijtvliet** [comment]
Awesome, many thanks!

I guess even better would be if the last-active window on this space would
get the focus, but that info is not available, is that correct?
