### ISSUE TITLE
Add back window borders for MacOS versions before Sonoma

### ISSUE THREAD

**Issue by lokxii** [koekeishiya/yabai#2177]
Window borders were removed due to problems in sonoma, and we are recommended to use janky borders on sonoma. But how about for MacOS versions before sonoma? I am on 2017 13" mbp. Apple discontinued support for my mbp and the latest available MacOS was Monterey. Window borders worked well on older MacOS versions. I hope it can be added back.

**Comment by koekeishiya** [comment]
In every system there is a complexity budget to manage, which decides how, when, or if, things are done or even can be done. Having to maintain such features across different operating system versions, when the feature has to work differently for each version, has a very high cost attached to it. When I also no longer have access to those systems for debugging and testing purposes that cost is amplified. 

The tradeoff here is just not beneficial.

**Comment by lokxii** [comment]
Understood. Is there any recommend software for adding window borders for older OS version?

**Comment by koekeishiya** [comment]
I'm not aware of any solution that works as well as the yabai version did for older macOS versions. I don't actually know of any projects that attempt to do this other than JankyBorders, but that one is Sonoma only as you already mentioned. People have been trying to script this using Hammerspoon, but I can already tell you that will be slow.

**Comment by lokxii** [comment]
Maybe I can extract the window border handling part out of old yabai to be a separate software... after I finished my current project. But that will only be a personal use software that only solve my problem (window borders on Monterey).

Anyways, thank you for your response! Really love yabai and skhd!
