### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by txl263** [koekeishiya/yabai#2186]
Two questions: 
1. Every time yabai is updated, it needs to ask for privacy and security permissions. Can this be improved? 
2. yabai-v7.0.3, the newly added rules do not take effect on already started programs. You must restart the program or yabai.

**Comment by koekeishiya** [comment]
1. https://github.com/koekeishiya/yabai/issues/2086#issuecomment-1939670967 and https://github.com/koekeishiya/yabai/issues/2086#issuecomment-1941363232

2. https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#700---2024-03-13

>When adding new window rules, their effects will only apply to windows that open after the rule has been added. To restore old behavior, run yabai -m rule --apply after adding all rules https://github.com/koekeishiya/yabai/issues/2123

**Comment by txl263** [comment]
My bad. You've been very diligent lately.I haven’t even checked out the 7.0 update, which has so much content.
