### ISSUE TITLE
Macports option?

### ISSUE THREAD

**Issue by rye-c** [koekeishiya/yabai#219]
I already have Macports installed so I can't install this via brew.  Are there any other options for installation?

**Comment by koekeishiya** [comment]
I don't plan on making a port-file myself, but I am sure someone else is capable of doing so, and I'd be fine with them maintaining it. I'm not sure if this project passes the criteria to be submitted into the official macports repository. I'll leave that part to someone who is interested in this..

Your alternative at this moment would be to either build from source, using the instructions in the installation step of the readme / wiki section, or download the .tar.gz file from the releases page and manually move the files where they are supposed to go / where  you want it to live on your system.

You'd then need to create a launchd plist file to run it as a service.

**Comment by onodera-punpun** [comment]
A port will hopefully be merged soon! https://github.com/koekeishiya/yabai/issues/219
