### ISSUE TITLE
yabai 7 does not manage windows launched by skhd

### ISSUE THREAD

**Issue by JoanMassachs** [koekeishiya/yabai#2194]
My skhdrc (v0.3.9) includes the following line:

```
cmd - return : kitty
```

On yabai 6.0.15, kitty windows launched with `cmd - return` would be managed by yabai. I have tried yabai 7.0.2 and 7.0.3, and now they are not managed.

**Comment by koekeishiya** [comment]
Should be fixed in v7.0.4.
