### ISSUE TITLE
Apps do not automatically move to specific space after restarting yabai

### ISSUE THREAD

**Issue by sherloach** [koekeishiya/yabai#2199]
After I upgraded yabai, it seems that Apps do not automatically move to specific spaces after restarting yabai. 
Moving automatically to spaces happened before I upgraded yabai, but now it does not working.

This is my yabai config file

`
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bsp or float (default: float)
yabai -m config layout bsp

yabai -m config window_placement second_child # New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_border                off
yabai -m config window_shadow                on
yabai -m config active_window_border_color   0xff008bff
yabai -m config normal_window_border_color   0x01000000
yabai -m config window_opacity on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config split_ratio                  0.50
yabai -m config window_topmost off # Some application/windows appear to have trouble with child windows when made topmost
yabai -m config auto_balance off
yabai -m config window_animation_duration    0.0
yabai -m config mouse_follows_focus off

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    5
yabai -m config bottom_padding 5
yabai -m config left_padding   5
yabai -m config right_padding  5
yabai -m config window_gap     5

# Space 1
yabai -m rule --add app="^Arc$" space=^1

# Space 2
yabai -m rule --add app="^iTerm2$" space=^2
yabai -m rule --add app="^kitty$" space=^2
yabai -m rule --add app="Alacritty" space=^2
yabai -m rule --add app="Code" space=^2

# Space 4
yabai -m space 4 --layout stack
yabai -m rule --add app="^Spotify$" space=^4
yabai -m rule --add app="Discord" space=^4
yabai -m rule --add app="Messenger" space=^4 manage=off
yabai -m rule --add app="WhatsApp" space=^4 manage=off

# Space 3
yabai -m space 3 --layout stack
yabai -m rule --add app="Obsidian" space=^3
yabai -m rule --add app="OrbStack" space=^3
yabai -m rule --add app="Notion" space=^3
yabai -m rule --add app="Cisco Packet Tracer" space=^3

# Disable specific apps
# yabai -m rule --add app=".*" layer=normal
yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^ExpressVPN$" manage=off
yabai -m rule --add app="^Hearthstone$" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="^Mail$" manage=off
yabai -m rule --add app="^NordVPN$" manage=off

`

**Comment by shipurjan** [comment]
I had this problem too, but I noticed that there is a "new" (actually old) rule parameter, and I think that --add changed a little bit

Namely, there's --apply parameter that applies the rules to currently open windows, so I wrote a new function that adds both rules to a window:

```bash
function yabai_rule {
  yabai -m rule --add "$@"
  yabai -m rule --apply "$@"
}

yabai_rule app="^Finder$" manage=off
```

It seems that previously the --add parameter used to work like this

**Comment by sherloach** [comment]
> I had this problem too, but I noticed that there is a "new" (actually old) rule parameter, and I think that --add changed a little bit
> 
> Namely, there's --apply parameter that applies the rules to currently open windows, so I wrote a new function that adds both rules to a window:
> 
> ```shell
> function yabai_rule {
>   yabai -m rule --add "$@"
>   yabai -m rule --apply "$@"
> }
> 
> yabai_rule app="^Finder$" manage=off
> ```
> 
> It seems that previously the --add parameter used to work like this

Yeah, I found the issue. I fixed it by adding this to my restart command
`hyper - y : yabai --restart-service | yabai -m rule --apply`

**Comment by zazer0** [comment]
> > Namely, there's --apply parameter that applies the rules to currently open windows, so I wrote a new function that adds both rules to a window:
> > ```shell
> > function yabai_rule {
> >   yabai -m rule --add "$@"
> >   yabai -m rule --apply "$@"
> > }
> > 
> > yabai_rule app="^Finder$" manage=off
> > ```
> 
> Yeah, I found the issue. I fixed it by adding this to my restart command `hyper - y : yabai --restart-service | yabai -m rule --apply`

Adding that `yabai_rule` function & manually running that `--restart-service | yabai -m rule --apply` command didn't fix the automatic space movement behaviour for me.

Was there any other steps required?

**Comment by zazer0** [comment]
> > @shipurjan 
> > Namely, there's --apply parameter that applies the rules to currently open windows, so I wrote a new function that adds both rules to a window:
> > ```shell
> > function yabai_rule {
> >   yabai -m rule --add "$@"
> >   yabai -m rule --apply "$@"
> > }
> > 
> > yabai_rule app="^Finder$" manage=off
> > ```
> @sherloach 
> Yeah, I found the issue. I fixed it by adding this to my restart command `hyper - y : yabai --restart-service | yabai -m rule --apply`

Adding that `yabai_rule` function & manually running that `--restart-service | yabai -m rule --apply` command didn't fix the automatic space movement behaviour for me.

Was there any other steps required?

**Comment by sherloach** [comment]
> > > @shipurjan
> > > Namely, there's --apply parameter that applies the rules to currently open windows, so I wrote a new function that adds both rules to a window:
> > > ```shell
> > > function yabai_rule {
> > >   yabai -m rule --add "$@"
> > >   yabai -m rule --apply "$@"
> > > }
> > > 
> > > yabai_rule app="^Finder$" manage=off
> > > ```
> > 
> > 
> > @sherloach
> > Yeah, I found the issue. I fixed it by adding this to my restart command `hyper - y : yabai --restart-service | yabai -m rule --apply`
> 
> Adding that `yabai_rule` function & manually running that `--restart-service | yabai -m rule --apply` command didn't fix the automatic space movement behaviour for me.
> 
> Was there any other steps required?

Have you changed "yabai" to "yabai_rule"? ex: yabai app="^iTerm2$" space=^2 -> yabai_rule app="^iTerm2$" space=^2

**Comment by singlexyz** [comment]
Adding `yabai -m rule --apply` after all the rules will automatically assign spaces on reboot.
