### ISSUE TITLE
Feature request: border colour

### ISSUE THREAD

**Issue by globalshrug** [koekeishiya/yabai#2209]
So, at some point I floated a window and then ended up frustrated as I couldn't remember which window(s) were floated or not, then every time I tried to bring up a background app/window I had to toggle float in order to see the window. In essence because I forgot which window was floating, I had to make all of the windows float and the issue got progressively worse.

I do have `-m config window_shadow float` set, however the effect is so subtle that it's really hard to tell which windows are floating or not unless I'm paying attention and sitting at my bright 5k monitor at home versus my laptop when I'm on the go and busy.

Can we get a setting so that the border or shadow colour can be set? A red border for example makes it clear that that window is floating and the others aren't.

**Comment by koekeishiya** [comment]
There is no window border support in this version of yabai, so this is unlikely to happen. Maybe some integration with JankyBorders @FelixKratz could be a thing.

**Comment by Bellavene** [comment]
> Can we get a setting so that the border or shadow colour can be set? A red border for example makes it clear that that window is floating and the others aren't.

Check [JankyBorders](https://github.com/FelixKratz/JankyBorders)

**Comment by FelixKratz** [comment]
In the next release of JankyBorders you will be able to script this using this new feature: https://github.com/FelixKratz/JankyBorders/issues/57
