### ISSUE TITLE
Yabai Window Move and Resize

### ISSUE THREAD

**Issue by MechaKaiju366** [koekeishiya/yabai#2211]
Yabai after 7.0.0 seemed to have altered how I can trigger window move and resize, which was through BetterTouchTool's by simulating fn + left mouse click when I three-finger tapped. 

The only way I can move the window now is holding down fn (set in Yabai config) or ctrl + cmd (defaults write -g NSWindowShouldDragOnGesture -bool true) and physically clicking, if I try to trigger movement with simulated mouse clicks, the window stutters in place as I try to move it around. I'm hoping there's a direction I can be pointed towards troubleshooting.

https://github.com/koekeishiya/yabai/assets/121596067/6a4002ec-f467-4d67-9a23-612a4f9d06f2

**Comment by koekeishiya** [comment]
So the way this works is that yabai intercepts the click event. This is used to detect which window is to be operateed on.
If there are drag-events that follow, the window will be moved accordingly, until the mouse-up event is received.

Upon mouse-up received, we check if the window is a floating window, and if yes, do nothing. If it is a managed window, we either swap/warp if is it dropped on some other managed window, or move it back to its assigned region if not.

I have no idea how BTT simulates the click and how that changes the state in macOS. You can enable `yabai -m config debug_output on` and see which events are being processed when you do this.

**Comment by MechaKaiju366** [comment]
After some testing with BTT and Karabiner / reading through referenced issues #1809 #1378 and 1240042,  I thinking it's because BTT simulates clicks higher than `kCGHIDEventTap`. My understanding is that since Karabiner creates a virtual driver and sends input as if it's from hardware, Yabai will respond to Karabiner inputs but not from BTT.

For now I will simply roll back to a previous version, since I wasn't having the issues described in that update. Thank you for all your work on this!

**Comment by s-daveb** [comment]
> After some testing with BTT and Karabiner / reading through referenced issues #1809 #1378 and [1240042](https://github.com/koekeishiya/yabai/commit/1240042a1b5382d7fbfd74f140dce57880c68ed4), I thinking it's because BTT simulates clicks higher than `kCGHIDEventTap`. My understanding is that since Karabiner creates a virtual driver and sends input as if it's from hardware, Yabai will respond to Karabiner inputs but not from BTT.
> 
> For now I will simply roll back to a previous version, since I wasn't having the issues described in that update. Thank you for all your work on this!

I'm experiencing a similar problem while connecting to a mac via macOS Screen Sharing.  What version of yabai did you revert to, if I may ask?

**Comment by MechaKaiju366** [comment]
> > After some testing with BTT and Karabiner / reading through referenced issues #1809 #1378 and [1240042](https://github.com/koekeishiya/yabai/commit/1240042a1b5382d7fbfd74f140dce57880c68ed4), I thinking it's because BTT simulates clicks higher than `kCGHIDEventTap`. My understanding is that since Karabiner creates a virtual driver and sends input as if it's from hardware, Yabai will respond to Karabiner inputs but not from BTT.
> > For now I will simply roll back to a previous version, since I wasn't having the issues described in that update. Thank you for all your work on this!
> 
> I'm experiencing a similar problem while connecting to a mac via macOS Screen Sharing. What version of yabai did you revert to, if I may ask?

I rolled back to https://github.com/koekeishiya/yabai/commit/e5370a15f21066fca212e1edbe9cc669e16c1762.
