### ISSUE TITLE
Focus follows mouse seems to have stopped working in version `yabai-v7.1.0`

### ISSUE THREAD

**Issue by farzadmf** [koekeishiya/yabai#2214]
Hi, I just upgraded `yabai` to the latest version. I have the setting:
```
yabai -m config focus_follows_mouse autofocus
```

It was working perfectly before, but seems to have stopped working with the latest version. If I restart `yabai`, it works for a bit, but then stops working.

But not working, I mean: when I hover over a window, nothing happens

**Comment by farzadmf** [comment]
Well, seems to be working now; so, closing this. Will create a new one if I see it happening again

**Comment by ixacik** [comment]
Hey man, I'm having the same issue, how did you manage to fix it?

**Comment by farzadmf** [comment]
Hey, at the time, I thought it started working, but it wasn't the case.

I used the constantly running script hack mention in #2217
