### ISSUE TITLE
Remove Minimize/Deminimize Animation

### ISSUE THREAD

**Issue by ndbeals** [koekeishiya/yabai#2218]
Hello, Love the project.

I'd like to be able to remove the minimize/deminimize animations that are applied to windows. I use yabai to remove other animations, but this minimize/deminimize seems to be unaffected by the existing settings.

MacOS: 14.4.1 
SIP: disabled
Yabai 7.1.0

**Comment by Bellavene** [comment]
It's baked into Finder. Theoretically, you could make a code injection into Finder to remove it.

**Comment by ndbeals** [comment]
I see, thank you.
