### ISSUE TITLE
How to display icon in spaces in icon bar as shown in readme?

### ISSUE THREAD

**Issue by bibstha** [koekeishiya/yabai#222]
I've changed the fonts in `yabairc` as per https://github.com/koekeishiya/yabai/issues/110 which fixes the battery and clock icons on the right. But I'd like to get the brand fonts too - like safari, firefox as shown in the readme.

<img width="1440" alt="59977681-9d873500-95d4-11e9-91e7-7be05cb11d06" src="https://user-images.githubusercontent.com/51671/63721459-51987c80-c81f-11e9-8211-d069aba3b0d3.png">

Turns out these fonts are in a separate otf `Font Awesome 5 Brands-Regular-400.otf` as can be seen from https://github.com/FortAwesome/Font-Awesome/tree/ce084cb3463f15fd6b001eb70622d00a0e43c56c/otfs

So
1. How was the icons displayed in the screenshot above?
2. Given these are two different icon files, is it possible to do it with yabai at the moment?
  Does it require building a single font file?

**Comment by dominiklohmann** [comment]
> 1\. How was the icons displayed in the screenshot above?

Just using regular Font Awesome. The icons shown in the example screenshot are all included in the standard package. The author of yabai has his dotfiles published, [including the bar configuration][koekeishiya-dotfiles].

```sh
# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Fantasque Sans Mono:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xe0202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip          
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        
```

If, however, you require icons from multiple fonts...

> 2\. Does it require building a single font file?

You can easily merge the fonts using [FontForge][fontforge]. You might also want to take a look at this [SuperUser thread][superuser-thread] about merging two fonts.

[koekeishiya-dotfiles]: https://github.com/koekeishiya/dotfiles/blob/ff58b876dc2ae154f103efc301e2adc6efc659a6/yabai/yabairc#L3-L12
[fontforge]: https://fontforge.github.io/
[superuser-thread]: https://superuser.com/questions/490922/merging-two-fonts

**Comment by dominiklohmann** [comment]
I think that separation happened with FontAwesome 5, so either install FontAwesome 4 or merge the fonts manually. Apparently the brand icons were separated out to reduce the size of the commonly used package, as the amount of brand icons kept increasing.
