### ISSUE TITLE
invalid key-value pair for setting grid rule

### ISSUE THREAD

**Issue by szfkamil** [koekeishiya/yabai#2223]
When trying to set a grid rule for an app, I get the output that key-value pair is invalid. (The same command does not output an error when ran on service start through `yabairc`.)

```
yabai -m rule --add app="^Session$" manage=off space=sm grid:100:100:0:0:10:20
invalid key-value pair 'grid:100:100:0:0:10:20'
```

In the `man` page, it says:

```
--grid <rows>:<cols>:<start-x>:<start-y>:<width>:<height>
           Set the frame of the selected window based on a self-defined grid.
```

So, I don't quite understand why this is invalid?

**Comment by stoffeastrom** [comment]
Your looking in the wrong place?

```sh
yabai -m rule <COMMAND>

where <COMMAND> is the -add

--add [--one-shot] [<ARGUMENT>]
           Add a new rule. Rules apply to windows that spawn
           after said rule has been added.
           If --one-shot is present it will apply once and
           automatically remove itself.

and <ARGUMENT>

grid=<rows>:<cols>:<start-x>:<start-y>:<width>:<height>
           Set window frame based on a self-defined grid.
```

**Comment by szfkamil** [comment]
> Your looking in the wrong place?
> 
> ```shell
> yabai -m rule <COMMAND>
> 
> where <COMMAND> is the -add
> 
> --add [--one-shot] [<ARGUMENT>]
>            Add a new rule. Rules apply to windows that spawn
>            after said rule has been added.
>            If --one-shot is present it will apply once and
>            automatically remove itself.
> 
> and <ARGUMENT>
> 
> grid=<rows>:<cols>:<start-x>:<start-y>:<width>:<height>
>            Set window frame based on a self-defined grid.
> ```

It was a simple matter of using : instead of = before 'grid'…
