### ISSUE TITLE
yabai scripting addition causes crash/logout on Catalina Beta 6

### ISSUE THREAD

**Issue by Nobody912** [koekeishiya/yabai#223]
I am currently running macOS 10.15 Beta (19A536g) and have installed yabai from the head branch via brew. Accessibility API and codesign prerequisites have been met.

I currently experience crashes upon closing my laptop's lid when scripting addition is enabled. Crash report traces it to `WindowServer`: [https://pastebin.com/H05xLFs4](https://pastebin.com/H05xLFs4)

**Comment by dominiklohmann** [comment]
Please keep everything Catalina in #22.

**Comment by koekeishiya** [comment]
Regression by Apple, nothing I can do about this, but remove the feature if they don't fix it.
