### ISSUE TITLE
Focus space not working but everything else does

### ISSUE THREAD

**Issue by jacobrreed** [koekeishiya/yabai#2232]
```
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9
cmd - 0 : yabai -m space --focus 10
cmd - s : yabai -m space --focus 11
# Move window to space
cmd + shift - 1 : yabai -m window --space 1; yabai -m space --focus 1
cmd + shift - 2 : yabai -m window --space 2; yabai -m space --focus 2
cmd + shift - 3 : yabai -m window --space 3; yabai -m space --focus 3
cmd + shift - 4 : yabai -m window --space 4; yabai -m space --focus 4
cmd + shift - 5 : yabai -m window --space 5; yabai -m space --focus 5
cmd + shift - 6 : yabai -m window --space 6; yabai -m space --focus 6
cmd + shift - 7 : yabai -m window --space 7; yabai -m space --focus 7
cmd + shift - 8 : yabai -m window --space 8; yabai -m space --focus 8
cmd + shift - 9 : yabai -m window --space 9; yabai -m space --focus 9
cmd + shift - 0 : yabai -m window --space 10; yabai -m space --focus 0

```

The following cmd+shift commands work, I open mission control and I have 10 desktops on my main display and the 11th on my second display. But for some reasion the focus space commands dont work

**Comment by jacobrreed** [comment]
`sudo yabai --load-sa` seems to fix it, even though thats the second line in my yabairc
```
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
```

does it need to be at bottom?

**Comment by anujc4** [comment]
Question: Did you complete the steps listed in [the wiki](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition)? If running `sudo yabai --load-sa` requires the user password, it won't work regardless of where you put it in the yabai config file.

**Comment by jacobrreed** [comment]
> Question: Did you complete the steps listed in [the wiki](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition)? If running `sudo yabai --load-sa` requires the user password, it won't work regardless of where you put it in the yabai config file.

I did but it has been a while since I've setup yabai so it may need redoing as my Mac has been upgraded a few times? I'll give it a another round and see

**Comment by anujc4** [comment]
You would need to do this step manually as the yabai `shasum` changes after every update. I have a helper function that I run which makes it a bit easier.

```bash
function suyabai() {
  local sha256
  sha256=$(shasum -a 256 "$(which yabai)" | awk "{print \$1;}")
  if [ -f "/private/etc/sudoers.d/yabai" ]; then
    sudo sed -i '' -e 's/sha256:[[:alnum:]]*/sha256:'"${sha256}"'/' /private/etc/sudoers.d/yabai
  else
    echo "sudoers file does not exist yet. creating one now"
    echo "$(whoami) ALL=(root) NOPASSWD: sha256:${sha256} $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai
  fi
}
```

**Comment by anujc4** [comment]
It's a function I've put in my shell profile (IMO there should be a better place to put it, this was just a dirty hack). I run it every-time yabai is upgraded.

**Comment by jacobrreed** [comment]
ya this works thanks
