### ISSUE TITLE
Focus not working properly

### ISSUE THREAD

**Issue by al-jshen** [koekeishiya/yabai#224]
Hi, running `yabai -m space --focus 2` only seems to focus the display that space 2 is on, not space 2 itself. To clarify, if I've got space 1 on the same display as space 2, and I focus space 2, yabai only focuses space 1. I've tried this with a single monitor as well, and the same problem exists; the change space focus command just doesn't do anything. Any help would be appreciated. Thanks. 

Edit: `yabai -m query --spaces --space 2 | jq -r '.windows[0] // empty' | xargs yabai -m window --focus` works, but that doesn't allow for focus on empty spaces, which is rather unfortunate. It would be nice if you could switch focus to any space regardless of whether windows are open in that space.

**Comment by dominiklohmann** [comment]
The following features require the scripting addition to be installed:

- **focus**/create/destroy **space without animation**
- move space (and its windows) left, right or to another display
- remove window shadows
- enable window transparency
- control window layers (make windows appear topmost)
- sticky windows (make windows appear on all spaces)

There's a workaround that's based on having the keyboard shortcuts in system prefs set for switching spaces, which I have previously posted in #205.

> ```sh
> # focus space 3
> index=3; eval "$(yabai -m query --spaces | jq --argjson index "${index}" -r '(.[] | select(.index == $index).windows[0]) as $wid | if $wid then "yabai -m window --focus \"" + ($wid | tostring) + "\"" else "skhd --key \"ctrl - " + (map(select(."native-fullscreen" == 0)) | index(map(select(.index == $index))) + 1 % 10 | tostring) + "\"" end')"
> ```
> 
> This works with up to 10 non-fullscreen spaces, and requires you to have `skhd` installed and running and `jq` installed. It works by either focusing a window on the space if one exists, or if no window exists by focusing the space instead using the Mission Control shortcut as set in the System Preferences. In the prefs, set the keyboard for switching to space 1 through 10 to <kbd>control</kbd><kbd>1</kbd>  through <kbd>control</kbd><kbd>0</kbd>.

Note, however, that while this workaround allows you to switch to an empty space on an unfocused display, it does not allow you to focus such a space.

**Comment by al-jshen** [comment]
I do have the scripting addition installed and SIP is disabled. 

I tried the workaround, for some reason it doesn't work with spaces other than the first three for display 1, and the first one for display 2.

**Comment by al-jshen** [comment]
Oh, might be because I'm on Catalina Dev 7. Latest commit only updates the scripting addition for Dev 6. I'll try again when it gets updated.

**Comment by al-jshen** [comment]
Okay, never mind. The workaround works. I didn't have the Mission Control keyboard shortcuts set up in my System Preferences. Thanks.  

It's still rather annoying that the regular focus command doesn't seem to work. Only focuses the display.

**Comment by dominiklohmann** [comment]
> Oh, might be because I'm on Catalina Dev 7.

See #22. The scripting addition works on beta 7, no need to update it. Neither Dock.app nor SkyLight.framework changed from 6 to 7.

Also, you know, being on Catalina is like kind of important information, so maybe you should've searched for that first. We've got that mega thread #22 set up for a reason.

**Comment by koekeishiya** [comment]
Closing this in favour of #22
