### ISSUE TITLE
on Sonoma 14.5 moving window to space is not working

### ISSUE THREAD

**Issue by FabioLissi** [koekeishiya/yabai#2240]
typing yabai -m window --space 2 --focus doesn't  yield any results.
SIP is disabled.
config:

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config split_ratio                  0.50
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

echo "yabai configuration loaded.."

#disable soecific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Obsidian$" manage=off

borders active_color=0xF0BE8900 inactive_color=0xff494d64 width=3.0 style=round hidpi=on&

**Comment by mickaelperrin** [comment]
It looks like you're missing:

```
yabai -m rule --apply
```

**Comment by pupbrained** [comment]
Same issue here, tried reinstalling yabai from HEAD but no luck. Attempting to move a window to another workspace causes it to simply just un-tile until I switch away from that workspace and back.

**Comment by FabioLissi** [comment]
> yabai -m window --space 2 --focus

Where should I put this?
typing yabai -m window --space 2 --focus; yabai -m rule --apply 
doesn't yield any results.

Also did this change lately? in the past typing this: > yabai -m window --space 2 --focus, wass enough to move window to a different space and move the focuse to it.

**Comment by berrabe** [comment]
same issue here, in previous macos version (13.x.x) i can use yabai without disable the SIP partially, everything works flawlessly especially window movement between spaces. But now in 14.5 window mode always failed to work windows between spaces

**Comment by basanys** [comment]
Same issue here after upgrading to 14.5

**Comment by mattfloat** [comment]
Possible duplicate of #2261

**Comment by drapergeek** [comment]
I'm seeing the same thing after upgrading to 14.5, with no config changes. FWIW I also downloaded and tried out Amethyst and they seem to be having the same problem.

**Comment by Sang-it** [comment]
Just updated having the same issue.

**Comment by phil-swiftly** [comment]
Likewise, having the same issue after updating today

**Comment by hpfmn** [comment]
Amethyst  now also a a bug report regarding this issue https://github.com/ianyh/Amethyst/issues/1643

**Comment by koekeishiya** [comment]
duplicate https://github.com/koekeishiya/yabai/issues/2240

**Comment by koekeishiya** [comment]
Apple did Apple things and made the function protected. Will likely require SIP to be disabled from now on.

pre 14.5:
<img width="824" alt="pre14 5" src="https://github.com/koekeishiya/yabai/assets/6175959/1355b3fd-9caa-434b-93d4-eec77048cbb8">

post 14.5:
<img width="824" alt="post14 5" src="https://github.com/koekeishiya/yabai/assets/6175959/6554c91e-1bef-4e20-a3dc-7c41c0385aac">

**Comment by jordan-da** [comment]
> Apple did Apple things and made the function protected. Will likely require SIP to be disabled from now on.
> 
> pre 14.5: <img alt="pre14 5" width="824" src="https://private-user-images.githubusercontent.com/6175959/330817774-1355b3fd-9caa-434b-93d4-eec77048cbb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDA1OTMsIm5iZiI6MTcxNTgwMDI5MywicGF0aCI6Ii82MTc1OTU5LzMzMDgxNzc3NC0xMzU1YjNmZC05Y2FhLTQzNGItOTNkNC1lZWM3NzA0OGNiYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMTkxMTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2U2M2ZiZGUxMzNmNDIzMThlMjE3ZDM5YmMxNzM2MjJmNmE3NGZmNWMwZDFiZjc2NzNkOTcyYWYzNGE3OWVhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.StOiJnyzAtoSDD3tM-J2JydesmgD-kNPIRX_VCVTZ2s">
> 
> post 14.5: <img alt="post14 5" width="824" src="https://private-user-images.githubusercontent.com/6175959/330817877-6554c91e-1bef-4e20-a3dc-7c41c0385aac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDA1OTMsIm5iZiI6MTcxNTgwMDI5MywicGF0aCI6Ii82MTc1OTU5LzMzMDgxNzg3Ny02NTU0YzkxZS0xYmVmLTRlMjAtYTNkYy03YzQxYzAzODVhYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMTkxMTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjg5ZDg3NzExYTRjOTY2Nzg1OTk1ZmQ1OWNlYWEzZjE3NTI3OTM5MWQ5ZTBjOGYwMWU1MDA0NjJiYzA4OTVkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UR_DJgT111JHqAiKRIW4D2kYY0h13bd7XFDK-TeM9bE">

that would be awful, can't really turn sip of on company laptops.. i really hope this isn't true

thanks for looking into it @koekeishiya

**Comment by xbunax** [comment]
Maybe we can use `bettertouchtool` to accomplish this function
<img width="485" alt="image" src="https://github.com/koekeishiya/yabai/assets/50800571/a6c8ea57-72df-4668-802e-23c42a8236a0">

**Comment by faustozamparelli** [comment]
To make this work do we have to fully disable SIP or we can add a flag to this?
```
csrutil enable --without fs --without debug --without nvram
```
@koekeishiya

**Comment by rubyroobs** [comment]
> To make this work do we have to fully disable SIP or we can add a flag to this?
> 
> ```
> csrutil enable --without fs --without debug --without nvram
> ```
> 
> @koekeishiya

Installing from `HEAD` fixed this for me without requiring further SIP changes

**Comment by jordan-da** [comment]
> > To make this work do we have to fully disable SIP or we can add a flag to this?
> > ```
> > csrutil enable --without fs --without debug --without nvram
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @koekeishiya
> 
> Installing from `HEAD` fixed this for me without requiring further SIP changes

it works with SIP enabled?

**Comment by hpfmn** [comment]
> > > To make this work do we have to fully disable SIP or we can add a flag to this?
> > > ```
> > > csrutil enable --without fs --without debug --without nvram
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @koekeishiya
> > 
> > 
> > Installing from `HEAD` fixed this for me without requiring further SIP changes
> 
> it works with SIP enabled?

"partialy" disabled. You need to disable filesystem restrictions, debug restricitons and nvram restrictions.

(Not sure why NVRAM and FS are needed, but yeah)

**Comment by B1T3X** [comment]
> > > > To make this work do we have to fully disable SIP or we can add a flag to this?
> > > > ```
> > > > csrutil enable --without fs --without debug --without nvram
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > @koekeishiya
> > > 
> > > 
> > > Installing from `HEAD` fixed this for me without requiring further SIP changes
> > 
> > 
> > it works with SIP enabled?
> 
> "partialy" disabled. You need to disable filesystem restrictions, debug restricitons and nvram restrictions.
> 
> (Not sure why NVRAM and FS are needed, but yeah)

I have the same SIP configuration and have reinstalled from HEAD but to no avail, still facing the issue :/

**Comment by berrabe** [comment]
> Apple did Apple things and made the function protected. Will likely require SIP to be disabled from now on.
> 
> pre 14.5: <img alt="pre14 5" width="824" src="https://private-user-images.githubusercontent.com/6175959/330817774-1355b3fd-9caa-434b-93d4-eec77048cbb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzE5MTgsIm5iZiI6MTcxNTg3MTYxOCwicGF0aCI6Ii82MTc1OTU5LzMzMDgxNzc3NC0xMzU1YjNmZC05Y2FhLTQzNGItOTNkNC1lZWM3NzA0OGNiYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMTUwMDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU0YzVkM2M5YTFkZjQxYjhhZjdkNTczY2ExYmNhYmNjOTVjMWVmY2FlNDE0ZGY2NGFhYzVmNTFiZWFiMzU3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7o5v05IHUf-S-CHjgiV2GAQrd7mKVuvyklkqQSjfKv0">
> 
> post 14.5: <img alt="post14 5" width="824" src="https://private-user-images.githubusercontent.com/6175959/330817877-6554c91e-1bef-4e20-a3dc-7c41c0385aac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzE5MTgsIm5iZiI6MTcxNTg3MTYxOCwicGF0aCI6Ii82MTc1OTU5LzMzMDgxNzg3Ny02NTU0YzkxZS0xYmVmLTRlMjAtYTNkYy03YzQxYzAzODVhYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMTUwMDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzMwYTM3NzY3M2JiZTRkNjg2YmE4YTM0YjcyMDUxNGNhMzg2MGIzNDk3YTA5MWRjOTVkNThkNTQyM2FlNDc2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sz073GJaPCfUYrqLVKGtMd4_HEOduhbSt06X0dYH3Yk">

Is there any other / alternative way to do the "windows movement" between spaces without using  `XMoveWindows...` function that have been protected? or is it the only way because of "apple things"

**Comment by hpfmn** [comment]
> > > > > To make this work do we have to fully disable SIP or we can add a flag to this?
> > > > > ```
> > > > > csrutil enable --without fs --without debug --without nvram
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > @koekeishiya
> > > > 
> > > > 
> > > > Installing from `HEAD` fixed this for me without requiring further SIP changes
> > > 
> > > 
> > > it works with SIP enabled?
> > 
> > 
> > "partialy" disabled. You need to disable filesystem restrictions, debug restricitons and nvram restrictions.
> > (Not sure why NVRAM and FS are needed, but yeah)
> 
> I have the same SIP configuration and have reinstalled from HEAD but to no avail, still facing the issue :/

Did you do all the steps explained in the Wiki? And Intel or Arm?

https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

**Comment by Vib1240n** [comment]
Installing from HEAD fixed the moving windows to different spaces for as well without changing any SIP settings. 

> > > > > To make this work do we have to fully disable SIP or we can add a flag to this?
> > > > > ```
> > > > > csrutil enable --without fs --without debug --without nvram
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > @koekeishiya
> > > > 
> > > > 
> > > > Installing from `HEAD` fixed this for me without requiring further SIP changes
> > > 
> > > 
> > > it works with SIP enabled?
> > 
> > 
> > "partialy" disabled. You need to disable filesystem restrictions, debug restricitons and nvram restrictions.
> > (Not sure why NVRAM and FS are needed, but yeah)
> 
> I have the same SIP configuration and have reinstalled from HEAD but to no avail, still facing the issue :/

**Comment by Sang-it** [comment]
Same for me. Installing from HEAD fixed it without issues.

**Comment by aileks** [comment]
> Same for me. Installing from HEAD fixed it without issues.

Installing from HEAD did not fix this for me...

**Comment by mrala** [comment]
> > Same for me. Installing from HEAD fixed it without issues.
> 
> Installing from HEAD did not fix this for me...

You'll need to disable SIP using the [documented process](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection).

I think there is a bit of confusion with people saying it's working "without changing any SIP configuration." The people saying this likely already had SIP disabled. I was unable to get it working when using the default SIP enabled configuration. After following the full steps to disable SIP and [installing the `HEAD` version](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)), previous functionality of moving windows to spaces has been restored.

I'm on M2 ARM hardware. Here is my SIP status:

```
❯ uname -m
arm64

❯ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
        Apple Internal: disabled
        Kext Signing: enabled
        Filesystem Protections: disabled
        Debugging Restrictions: disabled
        DTrace Restrictions: enabled
        NVRAM Protections: disabled
        BaseSystem Verification: enabled
        Boot-arg Restrictions: disabled
        Kernel Integrity Protections: enabled
        Authenticated Root Requirement: enabled
```

**Comment by aileks** [comment]
> > > Same for me. Installing from HEAD fixed it without issues.
> > 
> > 
> > Installing from HEAD did not fix this for me...
> 
> You'll need to disable SIP using the [documented process](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection).
> 
> I think there is a bit of confusion with people saying it's working "without changing any SIP configuration." The people saying this likely already had SIP disabled. I was unable to get it working when using the **standard SIP enabled** configuration. After following the [full steps to disable SIP](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection) and [installing the `HEAD` version](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)), previous functionality of moving windows to spaces has been restored.
> 
> I'm on M2 ARM hardware. Here is my SIP status:
> 
> ```
> ❯ uname -m
> arm64
> 
> ❯ csrutil status
> System Integrity Protection status: unknown (Custom Configuration).
> 
> Configuration:
>         Apple Internal: disabled
>         Kext Signing: enabled
>         Filesystem Protections: disabled
>         Debugging Restrictions: disabled
>         DTrace Restrictions: enabled
>         NVRAM Protections: disabled
>         BaseSystem Verification: enabled
>         Boot-arg Restrictions: disabled
>         Kernel Integrity Protections: enabled
>         Authenticated Root Requirement: enabled
> ```

SIP has been disabled. It was before updating and after updating.

**Comment by mrala** [comment]
> SIP has been disabled. It was before updating and after updating. I'm on an Intel Mac for what it's worth.

Have you configured the scripting addition? Seeing anything in error logs?

**Comment by aileks** [comment]
"Payload 0x7B doesn't support this macOS version!"
![error](https://github.com/koekeishiya/yabai/assets/88669313/14c3bf71-3fed-4fd1-8734-df9d4793e8e0)

That's the only error I'm getting. I've done the entire install process from scratch following the wiki about 3 times now.

**Comment by uherman** [comment]
Installing from HEAD fixed it for me as well, SIP partially disabled.

**Comment by koekeishiya** [comment]
Friggin Apple.. Fixed on master using parts of the old legacy workspace/spaces system that for some reason is still partially maintained in some ways, but didn't get validation added to it like the new API does.

This entire situation is just ridiculous.

Works without having to disable SIP again.

**Comment by aileks** [comment]
I have SIP completely disabled and I'm still getting this "payload (0x7B) doesn't support this macOS version!" error.

**Comment by kirkegaard** [comment]
The recent fix worked for me! :) Thank you!

**Comment by KonaKust** [comment]
The recent fix worked for me too! :D

**Comment by calism2** [comment]
The recent fix worked for me as well, but floating windows disappear when trying to move a window to another space.

**Comment by scifisamurai** [comment]
Upgraded to 7.1.1 just now. I have SIP enabled and the recent fix worked for me. I can move windows between spaces again! Thank you koekeishiya!

**Comment by jordan-da** [comment]
> Upgraded to 7.1.1 just now. I have SIP enabled and the recent fix worked for me. I can move windows between spaces again! Thank you koekeishiya!

you have sip fully enabled?

**Comment by scifisamurai** [comment]
@jordan-da yes, it's a work computer.

**Comment by jan-wacker** [comment]
I had the same issue. 

But reinstalled from HEAD and now it's working fine with SIP enabled.

**Comment by moniquelive** [comment]
@jan-wacker thanks! I ended up going to [loop](https://github.com/MrKai77/Loop) way easier to install and customize, with no need to enable SIP... 😞

**Comment by konstantinschuette** [comment]
I'm on macos 15.0.1 with an M1 Pro using the latest yabai version 7.1.4. I don't know wich macos updated caused, but I cant move windows to a space for a longer time now, at least a month. Currently when I do `yabai -m window --space 2`, then the window disappears. But if I switch to this space, it's not shown. If I now go back to the original space, the window pops up again.

Is this now the time where I need to disable SIP in order to keep it working as before?

**Comment by gaviag-cerebras** [comment]
Just updates and seeing the exact same as @konstantinschuette.

**Comment by kirkegaard** [comment]
macos 15.x is sequoia, not Sonoma

**Comment by nicolaric-akenza** [comment]
doesn't work for me neither on macos 15, even with disabled SIP.

**Comment by rmelendezz** [comment]
> doesn't work for me neither on macos 15, even with disabled SIP.

Same here, I am on MacOS 15.1.1 and yabai 7.1.5. SIP is fully enabled.

**Comment by loeffel-io** [comment]
v7.1.5 does not work for me
macOS 15.1.1 (24B91)

**Comment by lyorrei** [comment]
v7.1.5 doesn't work for me too.
Mac os 15.2 (24C101)

**Comment by thegeek-sys** [comment]
v7.1.6 doesn't work for me too too
macOS 15.3 (24D60)

**Comment by asmvik** [comment]
Working again on Tahoe 26.4 with SIP enabled. https://github.com/asmvik/yabai/issues/2788
