### ISSUE TITLE
How to send window to space and follow focus?

### ISSUE THREAD

**Issue by szfkamil** [koekeishiya/yabai#2246]
### Discussed in https://github.com/koekeishiya/yabai/discussions/2227

<div type='discussions-op-text'>

<sup>Originally posted by **szfkamil** April 11, 2024</sup>
In the manual, it says:

```
space=[^]<SPACE_SEL>
           Send window to space. If ^ is present, follow focus.
```
But it's quite unclear to me what an example command would look like, and where to put ^.

You may use this as an example: 

`ctrl + alt - 0x57 : yabai -m window --space 5`</div>

**Comment by Pe8er** [comment]
I'm not sure what `^` is about either. This works though:

`yabai -m window --space 5 --focus`

**Comment by szfkamil** [comment]
I'll close the issue, this is not a feature request, but it would be nice to clarify the manual about the `^`.

**Comment by koekeishiya** [comment]
^ is specific to window rule syntax (assign window to a space and follow focus when assignment takes place). Make sure you read the correct section.
