### ISSUE TITLE
Commands related to spaces not working

### ISSUE THREAD

**Issue by zeromask1337** [koekeishiya/yabai#2249]
Macos version: 13.6.6 (22G630)
yabai-v7.1.0
skhd-v0.3.9

Configs looks like this
```
alt - j : yabai -m window --focus south 
alt - k : yabai -m window --focus north
alt - h : yabai -m window --focus west
alt - l : yabai -m window --focus east

# Change focus between external displays (left and right)
alt - s : yabai -m space --focus prev 
alt - g : yabai -m space --focus next

# Manage spaces
alt - c : yabai -m space --create
alt - d : yabai -m space --destroy

# Modifying the Layout
# rotate layout clockwise
shift + alt - r : yabai -m space --rotate 270
# flip along y-axis
shift + alt - y : yabai -m space --mirror y-axis
# flip along x-axis
shift + alt - x : yabai -m space --mirror x-axis
# toggle window float
shift + alt - t : yabai -m window --toggle float --grid 4:4:1:1:2:2


# maximize a window
shift + alt - m : yabai -m window --toggle zoom-fullscreen

# balance out tree of windows (resize to occupy same area)
shift + alt - e : yabai -m space --balance

# swap windows
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - h : yabai -m window --swap west 
shift + alt - l : yabai -m window --swap east

# move window and split
ctrl + alt - j : vabai -m window --warp south
ctrl + alt - k : yabai -m window --warp north
ctrl + alt - h : yabai -m window --warp west 
ctrl + alt - l : yabai -m window --warp east

# move window to display left and right
shift + alt - s : yabai -m window --display west; yabai -m display --focus west;
shift + alt - g : yabai -m window --display east; yabai -m display --focus east;

# move window to prev and next space 
shift + alt - p: yabai -m window --space prev; 
shift + alt - n: yabai -m window --space next;

# move window to space #
shift + alt - 1 : yabai -m window --space 1;
shift + alt - 2 : yabai -m window --space 2;
shift + alt - 3 : yabai -m window --space 3;
shift + alt - 4 : yabai -m window --space 4;
shift + alt - 5 : yabai -m window --space 5;
shift + alt - 6 : yabai -m window --space 6;
shift + alt - 7 : yabai -m window --space 7;
```

```
yabai -m config layout bsp

yabai -m config window_placement second_child

yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12 yabai -m config right_padding 12
yabai -m config window_gap 12

# mouse settings
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
# left click + drag
yabai -m config mouse_action1 move
# right click + drag
yabai -m config mouse_action2 resize
yabai -m mouse_drop_action swap

yabai -m rule --add app="Системные настройки" manage=off 
yabai -m rule --add app=" Karabiner-Elements$" manage=off
yabai -m rule --add app="Калькулятор" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Red Shield VPN" manage=off
yabai -m rule --add app="Telegram" manage=off
yabai -m rule --add app="Transmission" manage=off
```

When I press alt-c nothing happens. alt-s also. Done everything according to installation.

**Comment by moniquelive** [comment]
I have all that and it used to work on my machine, but now the windows just vanish if I move them to 'east' or 'west'. If I do the opposite motion they reappear.

**Comment by 0xAquaWolf** [comment]
I haven't experienced this issue so i would need a bit more context to help you out.

Have you tried running `yabai -V` and trying to see if you get any error messages?

**Comment by moniquelive** [comment]
How do I use `-V` ?

```shell
🍎 ❯ yabai -V -m window --display east
yabai: '-m' is not a valid option!

~ 
🍎 ❯ yabai -m window -V --display east
unknown command '-V' for domain 'window'

~ 
🍎 ❯ yabai -m window --display east -V
unknown command '-V' for domain 'window'

~ 
🍎 ❯ 

```

**Comment by moniquelive** [comment]
I think I got it... I ran `yabai -V` in one split and ran `yabai -m window --display east` on another.
These are the logs after the command: https://pastebin.com/pUcXP2xf

**Comment by 0xAquaWolf** [comment]
Just looked at the pastebin, but still unsure of the issue, have you installed the scripting additions and disabled SIP

as per these wiki instructions?

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

**Comment by zeromask1337** [comment]
> Have you installed the scripting additions? i had a similar problem and this helped me out a lot
> 
> https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
> 
> make sure to also uncomment last line from the **sudoers** file so that you can include the updates from the wiki
> 
> it should look like this `#includedir /private/etc/sudoers.d`
> 
> after that reboot your mac and you should be good to go.

I can't believe I'm saying it but after whole year of disappointment and frustration it worked. Big appreciations my man, you're legend.

**Comment by 0xAquaWolf** [comment]
That is amazing to hear that really warms my heart, and i feel good that i have been able to pay it forward and assist another developer.

I legit reformatted my entire computer and built it up from scratch live on youtube, just to find this answer.

Hope you build some awesome software and build an awesome dev workflow 😎

**Comment by moniquelive** [comment]
> > Have you installed the scripting additions? i had a similar problem and this helped me out a lot
> > https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
> > make sure to also uncomment last line from the **sudoers** file so that you can include the updates from the wiki
> > it should look like this `#includedir /private/etc/sudoers.d`
> > after that reboot your mac and you should be good to go.
> 
> I can't believe I'm saying it but after whole year of disappointment and frustration it worked. Big appreciations my man, you're legend.

I believe so:

```shell
🍎 ❯ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled
	Boot-arg Restrictions: disabled
	Kernel Integrity Protections: enabled
	Authenticated Root Requirement: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

```

**Comment by zeromask1337** [comment]
> That is amazing to hear that really warms my heart, and i feel good that i have been able to pay it forward and assist another developer.
> 
> I legit reformatted my entire computer and built it up from scratch live on youtube, just to find this answer.
> 
> Hope you build some awesome software and an awesome dev workflow 😎

You have 1 more sub now

**Comment by zeromask1337** [comment]
@0xAquaWolf  As soon as I said it worked, new bug appeared:) Now separate windows goes underneath main one. It means if I open browser tab in separate window, it goes in foreground, preventing me to click it. The only place I see it is in mission control. I can move it to different space, but if they are on same, one overlap other.

**Comment by 0xAquaWolf** [comment]
> @0xAquaWolf As soon as I said it worked, new bug appeared:) Now separate windows goes underneath main one. It means if I open browser tab in separate window, it goes in foreground, preventing me to click it. The only place I see it is in mission control. I can move it to different space, but if they are on same, one overlap other.

This sounds like the layout might be set to floating can you confirm with by stoping the yabai service and then debugging with `yabai -V` then try opening the windows and see if you can get some logs or some more context

**Comment by 0xAquaWolf** [comment]
> > > Have you installed the scripting additions? i had a similar problem and this helped me out a lot
> > > https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
> > > make sure to also uncomment last line from the **sudoers** file so that you can include the updates from the wiki
> > > it should look like this `#includedir /private/etc/sudoers.d`
> > > after that reboot your mac and you should be good to go.
> > 
> > 
> > I can't believe I'm saying it but after whole year of disappointment and frustration it worked. Big appreciations my man, you're legend.
> 
> I believe so:
> 
> ```shell
> 🍎 ❯ csrutil status
> System Integrity Protection status: unknown (Custom Configuration).
> 
> Configuration:
> 	Apple Internal: disabled
> 	Kext Signing: enabled
> 	Filesystem Protections: disabled
> 	Debugging Restrictions: disabled
> 	DTrace Restrictions: enabled
> 	NVRAM Protections: disabled
> 	BaseSystem Verification: enabled
> 	Boot-arg Restrictions: disabled
> 	Kernel Integrity Protections: enabled
> 	Authenticated Root Requirement: enabled
> 
> This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
> ```

I looked over the logs but i don't see anything that stands out, i'm not using multiple displays so i don't know how to debug or help you here, sorry 😞

**Comment by zeromask1337** [comment]
> This sounds like the layout might be set to floating can you confirm with by stoping the yabai service and then debugging with `yabai -V` then try opening the windows and see if you can get some logs or some more context
Yeah, it was floating, my bad.

**Comment by 0xAquaWolf** [comment]
Awesome glad you were able to resolve everything :)
