### ISSUE TITLE
Can't install iPad apps anymore after disabling SIP

### ISSUE THREAD

**Issue by roelvangils** [koekeishiya/yabai#2256]
After disabling System Integrity Protection (SIP), I can no longer install iPad apps.

<img width="260" alt="modified_image" src="https://github.com/koekeishiya/yabai/assets/103744/26f175cd-13a8-469f-838a-2a4a22f32e16">

Is there a workaround to this, so I can use all of Yabai's features *and* be able to install iPad apps from the MAS?

**Comment by 24unix** [comment]
No. Apple doesn't allow that. As long as Apple thinks so, we have to decide: Yabai or those iOS/iPadOS apps.

**Comment by roelvangils** [comment]
> As long as Apple thinks so, we have to decide: Yabai or those iOS/iPadOS apps.

The choice is clear: Yabai with all of its great features!
