### ISSUE TITLE
Field active on signal don't work as expected

### ISSUE THREAD

**Issue by Marc-AnthonyG** [koekeishiya/yabai#2263]
## How to reproduce 
yabai --version = yabai-v7.1.0

1. Add this to yabairc: ```yabai -m signal --add event=space_changed action="echo 'space_changed'" active="no"```
2. Trigger space_changed and see in the log space_changed appear

<img width="1625" alt="Screenshot 2024-05-04 at 9 25 54 PM" src="https://github.com/koekeishiya/yabai/assets/78452236/99dda234-6fd4-4781-baea-52e3ddeea166">

## Expect behavior
The signal should not execute since it is not active.

## Contribution
I would love to contributed, but I am not great at c. I would love to look at it tho... Do you know where I could start to find the cause of that bug?

**Comment by koekeishiya** [comment]
*active* is not a valid filter for the *space_changed* signal.
In the docs in the event list, there is information mentioning which filters are eligible for various events.

**Comment by Marc-AnthonyG** [comment]
Hum, mb, I thought the `active` field was a way to disable a signal.
