### ISSUE TITLE
Window is zoomed out from parent node when tree changes

### ISSUE THREAD

**Issue by malfario** [koekeishiya/yabai#227]
Steps to reproduce:

1. Lay out three windows like this:

```
A
-- C
B
```

2. Run `yabai -m window --toggle zoom-parent` on _A_. It takes over _B's_ space.
3. Make any change to the tree (ie. open a new window, increase/decrease _A_ size, etc).

_A_ is visually zoomed out, but the window's internal state is not updated:

```
$ yabai -m query --windows --space 1
{
        "id":9807,
        ...
        "zoom-parent":1,
        "zoom-fullscreen":0,
        "native-fullscreen":0
}
```

As a result, running `yabai -m window --toggle zoom-parent` again on _A_ does nothing (visually) as it's really setting `zoom-parent = 0`, which is already set.

**Comment by koekeishiya** [comment]
The zoom-state should now properly reset when a window is removed or added.
I could not reproduce the cases where resizing the window caused a false positive for the zoom-state.

**Comment by malfario** [comment]
It's fixed, thanks a lot!
