### ISSUE TITLE
[Bug] Scratchpad initially not visible

### ISSUE THREAD

**Issue by carlos-gtz** [koekeishiya/yabai#2270]
I have this in yabairc:
```
yabai -m rule --add app="^Slack$" scratchpad=slack grid=11:11:1:1:9:9
```

And this in skhdrc:
```
meh - s : yabai -m window --toggle slack || open -a "Slack" 
```

If it's the first time we are opening slack, the app is opened but quickly is hidden. If I click again `meh - s`, all subsequent toggles work as expected. The only problem is when using `open - a "Slack"`. This happens to any other window.

**Comment by koekeishiya** [comment]
Fixed in commit https://github.com/koekeishiya/yabai/commits/master/ but not released yet.
