### ISSUE TITLE
Moving windows to other spaces no longer works

### ISSUE THREAD

**Issue by daslastic** [koekeishiya/yabai#2273]
Moving windows to other spaces no longer works (it moves them behind) as of the MacOS Sonoma 14.5 update; it broke it.
I.e.
`yabai -m window --space 2`

**Comment by lukejcollins** [comment]
Also experiencing this issue after updating to 14.5

**Comment by KanielDasper** [comment]
Also experiencing the same issue after updating to 14.5

**Comment by koekeishiya** [comment]
duplicate https://github.com/koekeishiya/yabai/issues/2240
