### ISSUE TITLE
Moving windows to spaces no longer works after Sonoma 14.5

### ISSUE THREAD

**Issue by jordan-da** [koekeishiya/yabai#2275]
related: https://github.com/koekeishiya/skhd/issues/355

```
yabai -m window --space 1
```
Doesn't seem to move windows to spaces anymore after the Sonoma 14.5 update

yabai config: https://github.com/hypergig/workstation/blob/master/config/yabairc
skhd config: https://github.com/hypergig/workstation/blob/master/config/skhdrc

**Comment by OneComputerGuy** [comment]
Taking a closer look at this, it seems is the same issue reported a few weeks back here: https://github.com/koekeishiya/yabai/issues/2240

**Comment by mrala** [comment]
Duplicate of 
- #2240 
- #2273

**Comment by koekeishiya** [comment]
See #2240
