### ISSUE TITLE
Typo in wiki?

### ISSUE THREAD

**Issue by Emilprivate** [koekeishiya/yabai#2278]
It's supposed to say 'disable' for the csrutil command for apple silicon 13+, no?

[Typo in the wiki?](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection#:~:text=csrutil%20enable%20%2D%2Dwithout%20fs%20%2D%2Dwithout%20debug%20%2D%2Dwithout%20nvram)

**Comment by Bellavene** [comment]
NopeNope, on arm chips it partially needs to be disabled, so the command changed there to enable bla bla.

**Comment by Emilprivate** [comment]
alright makes sense
