### ISSUE TITLE
Two windows in the same node zoomed at the same time

### ISSUE THREAD

**Issue by malfario** [koekeishiya/yabai#228]
Hi!

In Yabai we may have two windows with `zoom-parent` toggled on at the same time.

I don't know if this behavior is intended, but I believe chunkwm allowed only one window to be zoomed into the parent node at the same time, zooming out any previous active one.

**Comment by koekeishiya** [comment]
This is intentional, but I am still undecided which one I prefer.

**Comment by dominiklohmann** [comment]
You can always just run this command before toggling a window to zoom-parent to remove zoom-parent from all other windows on the space:

```sh
yabai -m query --windows --space \
    | jq -r '.[] | select(."zoom-parent" == 1).id' \
    | xargs -I{} yabai -m window {} --toggle zoom-parent
```

I prefer the current way, as it offers more flexibility.

**Comment by malfario** [comment]
@dominiklohmann Wow, that's a really nice trick indeed, thank you!

@koekeishiya I'm on the same boat as you trying to decide which way is better for me, but I think @dominiklohmann's solution works great and gives the user the chance to choose.

**Comment by malfario** [comment]
@dominiklohmann There's a catch though. Now I'm not able to remove zoom-parent from the current window, as I'm toggling it off, and then on again.

I'm trying to figure out a way to exclude the focused window from your command, but my script-fu is a bit limited for this case.

**Comment by dominiklohmann** [comment]
Add the query to the call to select in jq:

```sh
yabai -m query --windows --space \
    | jq -r '.[] | select(."zoom-parent" == 1 and .focused == 0).id' \
    | xargs -I{} yabai -m window {} --toggle zoom-parent
```

**Comment by malfario** [comment]
That's it, I completely overlooked the set of window properties! You're the man, cheers!
