### ISSUE TITLE
`alt-tab : yabai -m space --focus recent` not working 

### ISSUE THREAD

**Issue by Trid-collab** [koekeishiya/yabai#2285]
`alt-tab : yabai -m space --focus recent` doesn't seem to work with macos14.5 with the latest version of yabai and skhdrc. Could someone help me here on the what am I missing here

**Comment by Trid-collab** [comment]
I am new yabai. Most of my other stuff are working like:
`alt - r : yabai -m space --rotate 90`
`alt - f : yabai -m window --toggle zoom-fullscreen`
`alt - g : yabai -m space --toggle padding; yabai -m space --toggle gap`

excepting this one `alt - tab : yabai -m space --focus recent`
I just installed yabai skdrc using brew and started the service - enabled yabai at login and accessbilty and as for the config - I tried to follow from config in the internet. 
I am on Sonoma 14.5 and the following shows on my terminal when I run 

`csrutil status
System Integrity Protection status: enabled.`
[yabai_tridib.err.log](https://github.com/koekeishiya/yabai/files/15435965/yabai_tridib.err.log)

**Comment by 0xAquaWolf** [comment]
Alright i had something similar like this happen to me before i figured it out

first you have to partially disable SIP

https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

then after that you are going to need to install the scripting additions

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

lastly make sure to uncomment the last line from the sudoers file
`sudo visudo -f /private/etc/sudoers`

it should read

`#includedir /private/etc/sudoers.d`

then reboot your mac
