### ISSUE TITLE
yabai -m window --space 1 does not work on Mac OS 14.5 Sonoma

### ISSUE THREAD

**Issue by jonathanmorris180** [koekeishiya/yabai#2287]
This command seems to be broken in the latest Mac OS. Anyone else experiencing this/have any workarounds?

**Comment by Keyruu** [comment]
Yeah I can +1 this. I hope there is a fix soon.

**Comment by chhetrisushil** [comment]
+1, it is broken on Sonoma 14.5.

**Comment by VinozzZ** [comment]
I was able to get it work with the latest 7.1.1 release

**Comment by Keyruu** [comment]
Yes can confirm. You just need to update to 7.1.1. It even states this in the changelog: https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#711---2024-05-18

Sorry for not reading this!

**Comment by jonathanmorris180** [comment]
Thanks! Can confirm this is working with the 7.1.1 patch.
