### ISSUE TITLE
Yabai not handling kitty's windows 

### ISSUE THREAD

**Issue by Meaticus22** [koekeishiya/yabai#2291]
I'm seeking assistance on regarding an issue I've encountered with shortcuts with skhd when managing kitty terminal windows. Specifically, whenever I attempt to use a shortcut configured through skhd to handle a kitty window, I experience a glitchy red effect. However, when applying the same shortcut to manage a Firefox window, everything functions smoothly without any issues. Could anyone provide guidance on how to integrate yabai with kitty's windows using the alt+shift+right command shortcut via skhd? For a clearer understanding of the problem, please refer to this video demonstration: https://streamable.com/stad8m

Dotfiles: https://github.com/Meaticus22/dotfiles/tree/main

**Comment by Fro-Q** [comment]
same here. anyone got solutions?

**Comment by Meaticus22** [comment]
@Fro-Q Turning off `Secure Keyboard Entry` worked for me.

**Comment by Meaticus22** [comment]
@Fro-Q Turning off Secure Keyboard Entry worked for me.

**Comment by Fro-Q** [comment]
Appreciate! That solved the problem :]
