### ISSUE TITLE
move window to different space starts to behvae wierd after installing scripting additions

### ISSUE THREAD

**Issue by MKrbm** [koekeishiya/yabai#2298]
After installing scripting additions, the `yabai -m window --space <SPACE_idx>` stop to work properly.

More concretely, the window properly moves to the scpecified space only when the target space_id is at the different display. 
e.g. when the space arranges is like below and try to move a window in space 1 to space 3. ( cannot from space 1 to space 2)
![Screenshot 0006-05-27 at 17 11 38](https://github.com/koekeishiya/yabai/assets/57752203/03418686-d589-422d-bb15-f9ee3327f3cd)
![Screenshot 0006-05-27 at 17 11 05](https://github.com/koekeishiya/yabai/assets/57752203/6a5b524e-4936-444b-9ff2-4d85467a8f98)

What I did before experiencing the bug

1. Disabled SIP. 
2. run `csrutil disable`
3. After restart, executed `sudo nvram boot-args=-arm64e_preview_abi`, and restart

I'm using m3 apple silicon.

**Comment by bytesizelearning** [comment]
I'm experiencing the same issue but I never enabled SIP in the first place.

The only thing that changed is my Macbook is now in clam shell mode and I updated to the latest version of macOS.

**Comment by alber70g** [comment]
I experenced something similar where unmanaged windows (I use a shortcut to make them unmanaged and bigger) wouldn't move to the other display as well.

Steps to reproduce:
1. open a window (new terminal window for example), this window is automatically managed
2. float the window (`alt - t`)
3. move window to next display (`ctrl + shift - up`)

Expected:
- window moves to the next display, focus moves with it

Actual: 
- window doesn't move, focus __does__ move


Exhibit 1: Shortcuts for `~/.skhdrc`

```shell
# .skhdrc

# float / unfloat window and center
# use different settings for < 16:9 and > 16:9
alt - t : screen_width=$(yabai -m query --displays | jq "map(select(.index == $(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].display')))[0].frame.w"); \
  screen_height=$(yabai -m query --displays | jq "map(select(.index == $(yabai -m query --windows | jq 'map(select(."has-focus" == true))[0].display')))[0].frame.h"); \
  screen_ratio=$(echo "scale=2; $screen_width / $screen_height" | bc); \
  yabai -m window --toggle float --sub-layer below; \
  echo "$screen_ratio"; \
  if [[ $(echo "$screen_ratio > 1.78" | bc) -eq 1 ]] ; then \
    echo '> 16:9';\
    yabai -m window --grid 12:12:3:2:6:10; \
  else  \
    echo '< 16:9';\
    yabai -m window --grid 12:10:2:2:6:8; \
  fi

# send window to monitor and follow focus
ctrl + shift - up 	  : yabai -m window --display next; yabai -m display --focus next
ctrl + shift - down   : yabai -m window --display prev; yabai -m display --focus prev
```

**Comment by MKrbm** [comment]
> I'm experiencing the same issue but I never enabled SIP in the first place.
> 
> The only thing that changed is my Macbook is now in clam shell mode and I updated to the latest version of macOS.

-------

This can be the case. Actually I updated my mac-os before disabling SIP.

**Comment by HodaSalim** [comment]
I am facing the same issue since the last update with both managed and unmanaged windows I have SIP disabled

**Comment by SoheilSalmani** [comment]
Same, after macOS update.

**Comment by nlamirault** [comment]
Same issue using the last update to Sonoma 14.5

**Comment by maheks** [comment]
I have the same issue since updating, although I never touched SID so it should be enabled. Is there any other way to move the windows to another space? Because as of now yabai is unusable on 14.5 (at least for me) :(

**Comment by bytesizelearning** [comment]
@saucoide Thank you that solved it.
