### ISSUE TITLE
Send window and follow focus using space label

### ISSUE THREAD

**Issue by szfkamil** [koekeishiya/yabai#2305]
yabai can follow focus for a window if ^ is present before number in a space rule, eg. `^5`

I tried adding a space label so that all windows bound to that space also follow focus:

`yabai -m space ^5 --label media`

This produced:

`unknown command '^5' for domain 'space'`

Is there a way to use labels for spaces so that you can assign labels instead of <SPACE_SEL> (which is just an alias)

So you can: `yabai -m rule --add app="^Music$" manage=off space=media`
Instead of: `yabai -m rule --add app="^Music$" manage=off space=^5`

To send window *and* follow focus?

**Comment by koekeishiya** [comment]
yabai -m space 5 --label media

yabai -m rule --add app="^Music$" manage=off space=^media
