### ISSUE TITLE
Trackpad gestures work randomly after using yabai

### ISSUE THREAD

**Issue by pcr910303** [koekeishiya/yabai#231]
Ok, I'm not entirely sure if this is `yabai`'s problem, but I became pretty confident after few months.
When using `yabai`, swiping horizontally with two fingers (gesture used to dismiss a notification or go back in Safari) doesn't work randomly.
I have wiped & reinstalled my macOS installation two times due to this issue (one High Sierra, one Mojave), and the trackpad started to behave strangely soon after I installed & enabled `yabai`.

I have no idea why this happens, but when the trackpad gestures don't work, I have found that `killall Dock` helps mitigating the issue.

I'm pretty sure this bug report won't be useful; I'd be more than glad to work for fixing this issue, so please ask me for any additional information if needed.

**Comment by dominiklohmann** [comment]
This has been a macOS issue for a few years now, and predates even kwm. 

According to [this thread on AskDifferent](https://apple.stackexchange.com/questions/151907/how-to-bring-back-multi-touch-gestures-after-it-crashes-without-reboot) about the issue, running `killall Dock` helped for some users, while newer replies report that only `sudo killall hidd` (Human Interface Device Daemon) works.

Not an issue with yabai.

**Comment by pcr910303** [comment]
@dominiklohmann Oops :-( Should have done some more research. Sorry for spamming!
