### ISSUE TITLE
Error: Formula yabai has not implemented #plist, #service or installed a locatable service file

### ISSUE THREAD

**Issue by idogada-akamai** [koekeishiya/yabai#2310]
I am unable to start yabai on my Mac.
This issue has been happening for several months.

I am running the version `7.1.1`. With Mac OS Sonoma 14.13.1

I looked at the previously open issue for this (which has been closed) https://github.com/koekeishiya/yabai/issues/1738 but non of the solutions there seemed to work for me.

In addition to that I also tried to re-install yabai, but I am still getting the message when running `brew services start/restart yabai`

**Comment by Bellavene** [comment]
brew services was replaced with `yabai --start-service` long time ago...
