### ISSUE TITLE
Fullscreen exits randomly

### ISSUE THREAD

**Issue by oaroki-git** [koekeishiya/yabai#2317]
!! i am not sure if this is a yabai issue, but this has only started happening after i had installed yabai and disabled SIP !!

when i play a youtube video and fullscreen it, after a couple minutes it exits out of fullscreen and for a while i can't fullscreen it again

the apple forums say it has something to do with NVRam, but it also says that only intel macs should try to reset it to fix the issue

help needed

**Comment by Bellavene** [comment]
I believe it is not an issue from yabai. If it was, there would be a lot of same issues opened.
I am sorry, but you need to try to debug this issue by yourself. Who knows what causes it.

**Comment by oaroki-git** [comment]
alright then
