### ISSUE TITLE
Restarting the yabai service causes yabai to manage previously unmanaged windows

### ISSUE THREAD

**Issue by gloesch** [koekeishiya/yabai#2322]
I have a `yabairc` with the following sort of rules:

```
yabai -m rule --add app="Finder" manage=off
```

If I have a Finder window open (unmanaged, can drag around without snapping) and then restart yabai with `yabai --restart-service` (usually after I do a config change), the previously open and unmanaged Finder window is now managed. 

If I close and open a new Finder window, it's not managed as expected. This happens with another application I selectively manually manage.

I just recently updated from something yabai-5.x.x to latest yabai-v7.1.1, so perhaps I missed some logic/config breaking change?

Any help would be great.

**Comment by tamasgal** [comment]
I am using this line and it works fine:

`yabai -m rule --add app="^Finder$" sub-layer=above manage=off`

**Comment by gloesch** [comment]
@tamasgal do you mind sharing your version and also full config? I tried something similar, and I still have the same behavior. 

And what macOS version are you using? I'm on Sonoma 14.5

**Comment by gloesch** [comment]
yeah, my config looks really similar. Well if you happen to upgrade and don't have the issue *or* upgrade and do have the same issue, would love to know!

**Comment by gloesch** [comment]
oh, and I'm not using the scripting addition. Is another variable.

**Comment by szfkamil** [comment]
I have a similar issue #2307.

> I just recently updated from something yabai-5.x.x to latest yabai-v7.1.1, so perhaps I missed some logic/config breaking change?

I have been regularly updating the binary manually for a long time and still have this.

> And what macOS version are you using? I'm on Sonoma 14.5

I am also on Sonoma 14.5


I am led to believe it's a software bug and will try to work around this, for example:

Before the restart command runs, switch to a space with no windows, or a space that has windows which don't have this problem (i.e. with grid), after restart, switch focus to previous space by focus (delay if needed).

**Comment by szfkamil** [comment]
I hacked this script based on the above:



```
#!/bin/zsh


# Function to capture the current space index using yabai and jq
capture_space_index() {
    local space_index  # Declaring space_index as a local variable
    space_index=$(yabai -m query --spaces --space | jq -r '.index') 

    if [ -z "$space_index" ]; then  # Checking if space_index is empty
        echo "Error: Failed to capture space ID."
        exit 1
    fi
    echo "$space_index"  # Returning space_index
}

# Capture the current space ID dynamically
space_index_before_restart=$(capture_space_index)

yabai -m space --focus misc

# Restart the yabai service
yabai --restart-service

sleep 1

# Focus back on the original space using its dynamically captured index
yabai -m space --focus "$space_index_before_restart"

```

It works, but isn't perfect. At least for me, weird stuff with windows happens on-screen (probably because of grid rules being triggered).

Let me know how it works if you use, and feel free to suggest improvements.

**Comment by snario** [comment]
The above script worked for me. I had to change `misc` to some other space (in my case 7) that is unused.

**Comment by szfkamil** [comment]
> The above script worked for me. I had to change `misc` to some other space (in my case 7) that is unused.

Yes, that was a space label in my config... glad you figured that out!

**Comment by koekeishiya** [comment]
Add `yabai -m rule --apply` to the end of your config if you want rules to run for windows that are already open when yabai is launched (which is the case when you restart the service). This is all mentioned in the documentation.
