### ISSUE TITLE
macOS Sequoia

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#2324]
Apple has introduced their own window snapping implementation. Let's see if this is backed by something more reliable than the accessibility API that is currently exposed to third-party developers.

Edit: My initial assumption is that this is part of the AppKit framework and not a separate set of APIs, meaning that we will not be able to hook into this functionality from a third-party app in any meaningful way.

**Comment by pupbrained** [comment]
Just updated - seems the only thing broken w/ yabai is sending windows to other workspaces (yet again).

**Comment by Bellavene** [comment]
> Apple has introduced their own window snapping implementation. Let's see if this is backed by something more reliable than the accessibility API that is currently exposed to third-party developers.

I doubt it will be. Fully understand your decision to switch to something else.

**Comment by khaneliman** [comment]
This is the first place I came to check after seeing that as one of the features in the next update. Was hoping that'd give a more stable experience since it's becoming a first class citizen of the OS.

**Comment by Octogonee** [comment]
> Just updated - seems the only thing broken w/ yabai is sending windows to other workspaces (yet again).

Moving to other workspaces with skhd is broken for me aswell.

**Comment by ianyh** [comment]
I figured them locking down the APIs portended them adding their own tiling thing. I might try the dev beta at some point and poke around.

**Comment by rendinjast** [comment]
👀

https://github.com/koekeishiya/yabai/assets/63567298/b38a25bf-37f6-4db6-a9bb-3e131af3347b

**Comment by RoyalFoxy** [comment]
I have 0 clue about how macos structures their apis but after testing the builtin snapping it feels great as it's smooth and responsive. I really hope they make this api open and exentsible for third party apps to use and I really hope yabai can use this api too.

A video to show how smooth this is https://imgur.com/a/seTzNUQ

**Comment by Bellavene** [comment]
> I have 0 clue about how macos structures their apis but after testing the builtin snapping it feels great as it's smooth and responsive. I really hope they make this api open and exentsible for third party apps to use and I really hope yabai can use this api too.
> 
> A video to show how smooth this is https://imgur.com/a/seTzNUQ
> 
> Edit: Also please try and look into why yabai can't inject the scripting addition anymore, I really am a turtle on it's back without yabai

Looks promising

**Comment by koekeishiya** [comment]
> Edit: Also please try and look into why yabai can't inject the scripting addition anymore, I really am a turtle on it's back without yabai

This might just be the end of the scripting addition then. I have very little interest left in trying to circumvent all of these restrictions that they keep adding. The required effort is just not worth it to me personally anymore.

I'll install Sequoia on a separate volume and look into things when I feel like banging my head against the wall, and take a brief look at the situation. If I can't make things work without having to put in substantial effort, I'll remain on Sonoma for a couple of years and so will this software.

Also edited the following into my first post, but maybe people haven't re-read it:
My initial assumption is that this is part of the AppKit framework and not a separate set of APIs, meaning that we will not be able to hook into this functionality from a third-party app in any meaningful way.

**Comment by th0jensen** [comment]
I'm not sure if focus follows mouse is dependent on the scripting addition, but at least everything in my yabai workflow is working on Sequoia. Only issues I have are with skhd.

It also seems that the yabai process is being stopped at some times, and a new prompt shows up warning about privacy when you wake from sleep.

**Comment by pupbrained** [comment]
> I'm not sure if focus follows mouse is dependent on the scripting addition, but at least everything in my yabai workflow is working on Sequoia. Only issues I have are with skhd.
> 
> It also seems that the yabai process is being stopped at some times, and a new prompt shows up warning about privacy when you wake from sleep.

It shouldn't be IIRC. Even without yabai there are apps that can achieve the same functionality without SIP disabled.

**Comment by KennethHoff** [comment]
Even if the new system doesn't work with Yabai (or anything else), presumably the existing workflow would still work, right?

**Comment by wtf403** [comment]
> A video to show how smooth this is

Wow, how you doing it with shortcuts?

**Comment by zjp** [comment]
If I start yabai, _then_ uninstall and load the scripting addition it works for me.

**Comment by cmdham** [comment]
> > A video to show how smooth this is
> 
> Wow, how you doing it with shortcuts?
<img width="321" alt="Screenshot 2024-06-14 at 11 27 16 am" src="https://github.com/koekeishiya/yabai/assets/101636692/f65281a9-ce6b-4cdd-a0d5-a68619fbffaf">


You can use 🌐+Ctrl+Arrows and  🌐+Ctrl+Shift+Arrows

**Comment by kkoscielniak** [comment]
@cmdham You probably should be able to re-map these hotkeys as you wish in the Keyboard Shortcuts. (didn't install Sequoia though, can't tell for sure)

**Comment by pannxe** [comment]
> @cmdham You probably should be able to re-map these hotkeys as you wish in the Keyboard Shortcuts. (didn't install Sequoia though, can't tell for sure)

Nope, there is no option to do so that I can find (at least in beta 1).

**Comment by KennethHoff** [comment]
@pannxe Is it at least possible to entirely disable the feature, or did we just lose 8 combinations of keybinds for other use (Assuming we do not intend on using the feature)

**Comment by pannxe** [comment]
@KennethHoff I don't think you can. The most you can do is disable edge snapping I think

<img width="479" alt="image" src="https://github.com/koekeishiya/yabai/assets/33783983/73745ebd-ea76-4d99-9098-c7da256258b9">

**Comment by KennethHoff** [comment]
🤦 
Stop repeating Windows' worst decisions...

**Comment by Miginyon** [comment]
> > Edit: Also please try and look into why yabai can't inject the scripting addition anymore, I really am a turtle on it's back without yabai
> 
> 
> 
> This might just be the end of the scripting addition then. I have very little interest left in trying to circumvent all of these restrictions that they keep adding. The required effort is just not worth it to me personally anymore -- figuring out workarounds by myself is very time consuming.
> 
> 
> 
> I'll install Sequoia on a separate volume and look into things when I feel like banging my head against the wall, and take a brief look at the situation. If I can't make things work without having to put in substantial effort, I'll remain on Sonoma for a couple of years and so will this software.
> 
> 
> 
> Also edited the following into my first post, but maybe people haven't re-read it:
> 
> My initial assumption is that this is part of the AppKit framework and not a separate set of APIs, meaning that we will not be able to hook into this functionality from a third-party app in any meaningful way.
> 
> 
> 
> 

Fair enough bro, you've been an absolute legend

**Comment by koekeishiya** [comment]
Just an update from #2331 

<img width="896" alt="Screenshot 2024-06-21 at 13 42 46" src="https://github.com/koekeishiya/yabai/assets/6175959/e403c86c-f35a-4ebe-b106-b990eade0672">

**Comment by koekeishiya** [comment]
Another update from #2331 

<img width="896" alt="Screenshot 2024-06-23 at 15 32 54" src="https://github.com/koekeishiya/yabai/assets/6175959/45595fc0-8079-4f27-b70f-2a770c479b2b">

<img width="896" alt="Screenshot 2024-06-23 at 15 33 01" src="https://github.com/koekeishiya/yabai/assets/6175959/8ea6a9de-b855-44a5-885f-819d01f88569">

**Comment by KennethHoff** [comment]
> In macOS Sequoia, SIP must be disabled to be able to move windows between spaces.

What does "must be disabled" mean? SA currently requires partially disabling SIP (doesn't it?); Does Sequoia require fully disabling it?

**Comment by pannxe** [comment]
> > In macOS Sequoia, SIP must be disabled to be able to move windows between spaces.
> 
> What does "must be disabled" mean? SA currently requires partially disabling SIP (doesn't it?); Does Sequoia require fully disabling it?

That's will do.

**Comment by koekeishiya** [comment]
Things should be working properly on the first Sequoia Beta now.

**Comment by Octogonee** [comment]
Updated to Sequoia beta 2. 
When i type yabai --start-service, nothing happens.

When i type sudo yabai --start-service, this error pops up.

yabai: service file '/var/root/Library/LaunchAgents/com.koekeishiya.yabai.plist' is not installed! attempting installation..
Could not enable service: 125: Domain does not support specified action
Bootstrap failed: 125: Domain does not support specified action

sudo yabai --load-sa also does nothing.

**Comment by th0jensen** [comment]
I just updated to Sequoia Beta 2 and can report that yabai is working, just like in Beta 1

**Comment by Octogonee** [comment]
I updated to Sequoia beta 2, only thing not working right now is spaces, but i can move apps to other spaces? This might be my own issue however

**Comment by pannxe** [comment]
Additional info: I try revert back to previous version of yabai (the one that crashed Dock.app when switching space) and nothing happened when I try to do anything (not even Dock.app crashing).

I think that dock_spaces_offset changed again in this version?

**Comment by shsw228** [comment]
To switch spaces works on latest commit build :)

**Comment by Vib1240n** [comment]
Macos Sequoia Beta 2, yabai seems to be working properly with skhd. Installed from head and updated the hash. I can confirm that I am able to switch and focus spaces, displays and have my focus follows mouse working. Haven't noticed any Dock crashes or any other crashes with yabai. Also the scripting addition loaded properly when reinstalling from HEAD.

**Comment by donaldguy** [comment]
For my part, it appears yabai is apparently not getting informed of window destroyed events (but is getting minimized, de-minimized, hidden, and at-destroy-time, application-front-switched)

so in practice as I ⌘W and ⌘-Tab around I end up gradually halving my working space

no ~shade on not working perfectly on a beta, but I just wanted to post fair warning (for others considering the upgrade) given that the consensus appears to be all good

**Comment by donaldguy** [comment]
[possibly slightly more mysteriously, I just rebooted and ended up with first window I opened drawing on right half of screen

I did have `second_child` config;

or possibly just a case of the above; by the time I checked in that first-window which was a terminal  `-m query --windows` only knew about that window, and I certainly never saw anything else paint, but maybe yabai saw something occupy that space and then didn't see it disappear (from the vantage point of event handling; if not query)]

**Comment by koekeishiya** [comment]
I don't have any of these issues on my Sequoia install. (Both beta1 and 2 worked fine). Likely just macOS accessibility flakiness.

**Comment by pannxe** [comment]
Current head version works perfectly on beta 3, yay!

**Comment by zjp** [comment]
Working fine here too

**Comment by donaldguy** [comment]
Well I wonder why it hates me personally 🙃

I made sure that sa is definitely loading (It wasn't for a bit there cause I did the sha256 tagged sudoers fromt he wiki and didn't update that)

both `/opt/homebrew/Cellar/yabai/HEAD-09a7b23/bin/yabai` and (now to double check since its the symlink path in the plist) `/opt/homebrew/bin/yabai` are in the [`tccutil`](https://github.com/jacobsalmela/tccutil)`--list` output 

and seeing same behavior (of closed windows being treated as though persisting / consuming space in the layout)

**Comment by donaldguy** [comment]
I'd be pretty surprised if this were the issue[^1] but in terms of possible self-inflicted wounds: my `/private/var/select/sh` is pointing at `/bin/zsh` and early in my `.yabairc` (after loading the sa though) I do `emulate zsh` to bring shell features back for my config 


[^1]: since `yabai` runs directly under `launchd` without a shell - and I don't think generally spawns subshells for things other than config and rule/signal actions (which I currently have none configured)

**Comment by donaldguy** [comment]
hmm it seems like maybe removing that "invalid" (didn't open anything on right-click Reveal in Finder ; had broken icon ) and apparently redundant screen recording entry may have actually re-broken layout handling of window closes ?

(but `-m query  --windows` output remains more correct than before)

**Comment by donaldguy** [comment]
Okay, I am pretty sure my issue is caused by [Arc Browser](https://arc.net/) (on Sequoia, I don't believe it was an issue before upgrade)

(this makes some sense as Arc is a program with a pretty atypical concept of windowing (New Window (⌘N)) gives you clone(s) of  windows that share state, but are expected to point at different tabs; and then for external links from another program it makes "Little Arc" windows that are AXSystemDialogue subrole (as the intended UX is that you either close it or push the button that moves it to the main window[s]). There can also be Incognito windows, and I just learned there is also a [New] Blank Window [^⌘N] that acts more like other browsers' concept of new windows ) 

what makes less sense is why/how it "infects" other programs - as I am seeing these "ghost window" misbehavior for all programs and all spaces when Arc is running even if it is hidden, or minimized, or has no open windows (according to my eyes and yabai query)

Arc does not have Accessibility or Input Recording or Screen Recording permissions 

at core it is just a Chromium process (though perhaps unlike Chrome or most electron apps [I need to check more], it does apparently keep most of its `--type=renderer` and GPU process alive when there are no windows (and so no tabs) ~visibly open. that seems likely to be relevant - but I'll have to dig in more to how.

**Comment by donaldguy** [comment]
Actually— while I was attempting to verify / differentiate whether terminating Arc immediately restored sanity or if it was only after restarting `yabai` without Arc open— I instead (got confused because)— I hit a second case of inducing the behavior:

Pressing <kbd>⌘</kbd><kbd>N</kbd> in Finder (a second+ time /  with a window open ) apparently now(?, on my machine anyway) opens new tab rather than a new window, but `yabai` is reacting like a new window was opened (which maybe on some level it was, but certainly `yabai -m query --windows` only believes there is one

so given these two examples, it seems like at core the issue may be related to programs doing something other than in the traditional sense opening a new window on Cmd-N 

(Its definitely also possible that something else I am running is injecting confusion when it sees that, but I'm not immediately sure what that would be ; I'll keep looking)

**Comment by donaldguy** [comment]
But certainly whether or not the Finder issue repros for anybody else should be easy enough to test if you are so inclined

**Comment by donaldguy** [comment]
Also lest my description wasn't clear here have a video  - the fact that each tab appears to be listed in the long-press-on-dock-icon seems possibly relevant (to suggest that there is some window-like object somewhere)

https://github.com/user-attachments/assets/5718256f-6bcf-4206-9ca3-47cc64474ee7

**Comment by koekeishiya** [comment]
Sounds like some variation of #68

**Comment by donaldguy** [comment]
> Sounds like some variation of #68

Since theres a known thing there, this probably isn't actually helpful, but

> Its definitely also possible that something else I am running is injecting confusion when it sees that, but I'm not immediately sure what that would be… because it could be several things 

I tore all the way down to 

```
$ sudo launchctl list | grep -v apple 
PID	Status	Label
540	0	fans
-	0	com.vix.cron

 
$ launchctl list | grep -v apple  
PID	Status	Label
1441	-15	com.koekeishiya.yabai
``` 

and definitely Finder continues to behave like in above video. 

(Frustratingly, it does seem like Arc's ability to infect other programs windows behavior is perhaps eliminated here at barebones runtime)

**Comment by donaldguy** [comment]
As I've been re-boostrapping stuff and trying to catch when issues start, I am now pretty sure https://contexts.co/ is the real culprit (~the actor who is getting confused by Arc and/or Finder tabs and then somehow ~generalizing behaviors to other programs; my intuition on how is something to the effect holding on to some sort of handle that is suppressing GC at the Obj-C/Swift runtime level or so)

--

Given that it is also very much in the business of observing windows, it was in fact one of my first suspects, but quitting it didn't (and doesn't, alone) seem to resolve weirdness 

However it seems like quitting it, restarting Dock.app (!!), and then restarting `yabai`-proper and (thus) reloading the SA takes things back to behaving like before Contexts was opened.

--- 

Compatibility with this specific 3rd party app is obviously not in project scope for yabai and I can definitely live without it, so 🎉 

I do wonder what it is doing that is managing to cause issues that outlive termination of its process though 🤔

**Comment by adorabilis** [comment]
Hi, can someone report on Yabai's status on the current macOS Sequoia RC (build number 24A335)? Does scripting addition work? Thanks!

**Comment by khaneliman** [comment]
Yeah, I'm on 24A335 and it works fine.

**Comment by calliduslabs** [comment]
Hey can someone please help? I just update to Sequoia and reinstalled Yabai. It seems to work fine but i can't send a window to another space. This is how i was using: alt - 1  : yabai -m window --space 1

**Comment by zjp** [comment]
Are you sure you loaded the scripting addition? 

`sudo yabai --load-sa`

**Comment by exsesx** [comment]
I just updated to Sequoia as well. Everything's working well, including moving windows to other spaces.

**Comment by calliduslabs** [comment]
> Are you sure you loaded the scripting addition?
> 
> `sudo yabai --load-sa`

Yes. It's on the top of my yabairc file

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
# Binary space partitioning, stack, or float
yabai -m config layout bsp

yabai -m config external_bar all:32:0

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Gap
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# Sketchybar support
#yabai -m config external_bar main:30:0

# Window borders
#yabai -m config window_border on
#yabai -m config window_border_width 2
#yabai -m config window_border_blur on
#yabai -m config active_window_border_color 0xfff7768e # Tokyonight red
#yabai -m config normal_window_border_color 0xff7aa2f7 # Tokyonight blue

# Split ratio
yabai -m config auto_balance off

# Mouse
yabai -m config mouse_follows_focus off
yabai -m config mouse_modifier alt
# right click + drag
yabai -m config mouse_action2 resize

and my skhdrc file is:

#change window focus within space
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - h : yabai -m window --focus west
alt - l : yabai -m window --focus east

# Rotate windows clockwise and anticlockwise
alt - r         : yabai -m space --rotate 270
shift + alt - r : yabai -m space --rotate 90

# Rotate on X and Y Axis
shift + alt - x : yabai -m space --mirror x-axis
shift + alt - y : yabai -m space --mirror y-axis

# toggle window float
alt - f : yabai -m window --toggle float --grid 4:4:1:1:2:2

# maximize a window
alt - m : yabai -m window --toggle zoom-fullscreen

# balance out tree of windows (resize to occupy same area)
alt - e : yabai -m space --balance

# Resize windows
lctrl + alt - h : yabai -m window --resize left:-50:0; \
                  yabai -m window --resize right:-50:0
lctrl + alt - j : yabai -m window --resize bottom:0:50; \
                  yabai -m window --resize top:0:50
lctrl + alt - k : yabai -m window --resize top:0:-50; \
                  yabai -m window --resize bottom:0:-50
lctrl + alt - l : yabai -m window --resize right:50:0; \
                  yabai -m window --resize left:50:0

# swap windows
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - h : yabai -m window --swap west
shift + alt - l : yabai -m window --swap east

# move window and split
ctrl + alt - j : yabai -m window --warp south
ctrl + alt - k : yabai -m window --warp north
ctrl + alt - h : yabai -m window --warp west
ctrl + alt - l : yabai -m window --warp east

# move window to display left and right
shift + alt - s : yabai -m window --display west; yabai -m display --focus west;
shift + alt - g : yabai -m window --display east; yabai -m display --focus east;

#move window to prev and next space
shift + alt - p : yabai -m window --space prev;
shift + alt - n : yabai -m window --space next;

# move window to space #
alt - 1 : yabai -m window --space 1
alt - 2 : yabai -m window --space 2
alt - 3 : yabai -m window --space 3
alt - 4 : yabai -m window --space 4
alt - 5 : yabai -m window --space 5
alt - 6 : yabai -m window --space 6
alt - 7 : yabai -m window --space 7

**Comment by calliduslabs** [comment]
Also sip is disabled. csrutil status
System Integrity Protection status: disabled.

It was working before but i just update to Sequoia and now i can't move to another space. If someone can help i appreciate

**Comment by calliduslabs** [comment]
Hmm i typed the command on my terminal and got it:

sudo yabai --load-sa
yabai: missing required nvram boot-arg '-arm64e_preview_abi'!

what does that means?

**Comment by calliduslabs** [comment]
I just found this command sudo nvram boot-args=-arm64e_preview_abi and rebooted. Everything is fine now.

**Comment by eret9616** [comment]
> As I've been re-boostrapping stuff and trying to catch when issues start, I am now pretty sure https://contexts.co/ is the real culprit (~the actor who is getting confused by Arc and/or Finder tabs and then somehow ~generalizing behaviors to other programs; my intuition on how is something to the effect holding on to some sort of handle that is suppressing GC at the Obj-C/Swift runtime level or so)
> 
> --
> 
> Given that it is also very much in the business of observing windows, it was in fact one of my first suspects, but quitting it didn't (and doesn't, alone) seem to resolve weirdness
> 
> However it seems like quitting it, restarting Dock.app (!!), and then restarting `yabai`-proper and (thus) reloading the SA takes things back to behaving like before Contexts was opened.
> 
> Compatibility with this specific 3rd party app is obviously not in project scope for yabai and I can definitely live without it, so 🎉
> 
> I do wonder what it is doing that is managing to cause issues that outlive termination of its process though 🤔
> 
> (EDIT, FYI-for-nobody: since returning to default macOS ⌘-Tab after a long time was weirdly uncomfortable and I'm not ready to break myself of the habit [in favor of more efficient bindings] at the moment, I am giving https://alt-tab-macos.netlify.app/ a shot and glad to report it does not seem to cause any similar issues to contexts)

wish there is a  workaround to fix this, im using both context and yabai

**Comment by koekeishiya** [comment]
Implemented a workaround in the latest commit that should resolve the issue.

**Comment by Liquidmantis** [comment]
Can confirm!  This seems to have resolved the issue with Contexts for me.  Thanks!

**Comment by adorabilis** [comment]
Hi, does yabai work on macOS 15.2 (build number 24C101)?

**Comment by Liquidmantis** [comment]
I updated yesterday to see if 15.2 fixed another unrelated problem and didn't even think about yabai.  Luckily it's working fine for me.  The caveat being this is my SIP-enabled work computer so I'm not using some yabai functionality due to that restriction.

**Comment by asmvik** [comment]
Working again on Tahoe 26.4 with SIP enabled. https://github.com/asmvik/yabai/issues/2788
