### ISSUE TITLE
Window is allocated a region/tile twice when created while application is hidden

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#233]
Originally by @alextes in #159 

> I found a way to reproduce my issue, but it seems unrelated, let me know if you'd like me to create a separate issue.
> 
> I have an app Kitty. Which I open using:
> 
> ```
> cmd - return : /Applications/Kitty.app/Contents/MacOS/kitty --single-instance -d ~
> ```
> 
> If I hide Kitty and trigger a new window to be created, the app unhides, and creates a new window. This results in two windows but three spaces, one of them being empty.
> `yabai -m query --windows --space`
> 
> ```json
> [{
>         "id":10655,
>         "pid":51886,
>         "app":"kitty",
>         "title":"alextes: yabai -m query --windows --space",
>         "frame":{
>                 "x":1285.0000,
>                 "y":20.0000,
>                 "w":1255.0000,
>                 "h":1400.0000
>         },
>         "level":0,
>         "role":"AXWindow",
>         "subrole":"AXStandardWindow",
>         "movable":1,
>         "resizable":1,
>         "display":1,
>         "space":1,
>         "visible":1,
>         "focused":1,
>         "split":"horizontal",
>         "floating":0,
>         "sticky":0,
>         "border":0,
>         "shadow":1,
>         "zoom-parent":0,
>         "zoom-fullscreen":0,
>         "native-fullscreen":0
> },{
>         "id":3404,
>         "pid":51886,
>         "app":"kitty",
>         "title":"sweetspot:2:api - \"api: nvim ~/.skhdrc\" 1#,3#,4#,5#",
>         "frame":{
>                 "x":20.0000,
>                 "y":725.0000,
>                 "w":1255.0000,
>                 "h":695.0000
>         },
>         "level":0,
>         "role":"AXWindow",
>         "subrole":"AXStandardWindow",
>         "movable":1,
>         "resizable":1,
>         "display":1,
>         "space":1,
>         "visible":1,
>         "focused":0,
>         "split":"horizontal",
>         "floating":0,
>         "sticky":0,
>         "border":0,
>         "shadow":1,
>         "zoom-parent":0,
>         "zoom-fullscreen":0,
>         "native-fullscreen":0
> }]
> ```
> 
> ![Screen Shot 2019-09-02 at 10 53 02](https://user-images.githubusercontent.com/2011351/64102297-f3642000-cd6f-11e9-8a4f-048868e4baaf.png)
> 
> Restarting yabai makes the empty space disappear. Same as recreating the desktop.

**Comment by alextes** [comment]
Thanks for creating the issue and this awesome window manager @koekeishiya 🙏
