### ISSUE TITLE
yabai is not working after updating macos

### ISSUE THREAD

**Issue by trqminh** [koekeishiya/yabai#2334]
I recently updated my mac to Sonoma 14.5. After updating, yabai was not working. I am trying to uninstall and install everything again but it is still not working. Do you have any suggestion? Below are my installation steps:

```
brew install koekeishiya/formulae/yabai
cp /path/to/my/yabairc ~/.yabairc
yabai --start-service
# then I gave yabai accessibility 
yabai --restart-service
```

and nothing happen with my windows

Thank you for your consideration.

**Comment by ovidb** [comment]
Have you tried this steps here for reinstalling? 

https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#updating-to-the-latest-release


and yes you also have to go to Privacy & Security > Accessibility remove yabai from there before re-installing, then go back and allow it

**Comment by trqminh** [comment]
Thank you for your response.
I tried this to reinstall the latest and I got this error even using sudo
```
sudo curl -L https://raw.githubusercontent.com/koekeishiya/yabai/master/scripts/install.sh | sh /dev/stdin

Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3000  100  3000    0     0  64079      0 --:--:-- --:--:-- --:--:-- 65217
Error: User does not have write permission for man-page target directory '/usr/local/share/man/man1'.
```
Do you have any suggestion? Thank you for your help.

**Comment by trqminh** [comment]
Hi @ovidb , @koekeishiya , sorry for bothering you guys lately. Could you please take a look at my issue? Thank you a lot for your consideration

**Comment by trqminh** [comment]
Solved here: https://github.com/koekeishiya/yabai/issues/1222#issuecomment-2259682586
