### ISSUE TITLE
Yabai manage=off is not working.

### ISSUE THREAD

**Issue by shopifykingbd** [koekeishiya/yabai#2336]
I have added few rules into my mac yabairc file to top yabai for System settings, Finder and so on but looks like it's not working. May I know the reason why it's not working?

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Friendly Streaming$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Messenger$" manage=off
yabai -m rule --add app="^Notion$" manage=off

**Comment by mcgilly17** [comment]
Not sure why, but I cannot for the life of me get 1password to be manage=off. All other apps are working for me right now.

**Comment by Bellavene** [comment]
> I have added few rules into my mac yabairc file to top yabai for System settings, Finder and so on but looks like it's not working. May I know the reason why it's not working?

Move rules up in .yabairc and add this to the end of it `yabai -m rule --apply`



> Not sure why, but I cannot for the life of me get 1password to be manage=off. All other apps are working for me right now.
Try to query info about the window, you have three seconds to open the window after executing this command `sleep 3; yabai -m query --windows --window`
Then look the at the title, role and subrole.
Here is an example for the rule:
```
yabai -m rule --add app="^Adobe.*$" \
         role="AXLayoutArea" \
         subrole="AXFloatingWindow" \
         title="my title" \
         manage=off \
         display=^1 \
         grid=1:1:0:0:1:1

```

**Comment by mcgilly17** [comment]
Thanks @Bellavene! Making it more specific has done the trick. Also having to rm the /tmp directory for anytthing yabai related semi regularly atm which also got things working again!

**Comment by capitanBOBO** [comment]
Same issue here, added yabai -m rule --apply at the end of list of rules and looks like it's helped and everything working now.

**Comment by alptugan** [comment]
Adding `yabai -m rule --apply` to the end of the config file resolve the problem for me. Thanks @Bellavene ✌🏻

**Comment by shopifykingbd** [comment]
Adding yabai -m rule --apply to the end  and working. 
Thanks @Bellavene ✌🏻
