### ISSUE TITLE
`query --windows` take a very long time

### ISSUE THREAD

**Issue by brorbw** [koekeishiya/yabai#2344]
Querying windows is taking a lot longer than expected even with few windows.
```sh
# Timing commands
yabai -m query --displays  0.00s user 0.00s system 77% cpu 0.010 total
yabai -m query --spaces  0.00s user 0.00s system 53% cpu 0.015 total
yabai -m query --windows  0.00s user 0.01s system 1% cpu 0.674 total

# Counting windows
~
➜ yabai -m query --windows | jq length
9

# Checking most recent version
~
➜ brew update && brew upgrade yabai
==> Updating Homebrew...
Already up-to-date.
Warning: yabai HEAD-40d1075 already installed
```

I'm on Sonoma

**Comment by diocletiann** [comment]
Do you need all the fields? If you restrict the query it's much faster.

**Comment by brorbw** [comment]
No. I don't I have solved the issue adding `--window` to the query. However _something_ has happened between my latest installed version which unfortunately got lost during my update so I don't know which one I upgraded from.

**Comment by koekeishiya** [comment]
Probably same issue as https://github.com/koekeishiya/yabai/issues/2377, but you can select specific properties in your queries (if you don't need them all): `yabai -m query --windows id,app --window`
