### ISSUE TITLE
Emacs (emacs-mac) on macos goes haywire

### ISSUE THREAD

**Issue by renald** [koekeishiya/yabai#2348]
Hi,

After working in Emacs for a short period of time, the dreaded rainbow ball comes up and CPU usage goes to over 95%. I'd love to help debug this issue, but would need some pointers on how to approach this.

Note that this does not occur when running in the terminal (emacs -nw)

Further info:
 - Apple M1 Max
 - 64 GB
 - macOS 14.5
 - Emacs 29.1 (``brew install emacs-mac``  ==> emacs-29.1-mac-10.0)

## Report after Force Quit

[emacs-yabai-report.txt.gz](https://github.com/user-attachments/files/16202161/emacs-yabai-report.txt.gz)

**Comment by brorbw** [comment]
Emacs is not well behaved in MacOS so I'd recommend `emacs-plus` instead https://github.com/d12frosted/homebrew-emacs-plus.

Something like
```
brew install emacs-plus --with-native-comp
```

**Comment by renald** [comment]
Hi,

```
brew tap d12frosted/emacs-plus
brew install emacs-plus@30 --with-native-comp
```

seems to resolve the issue, indeed. Thanks for the help!

Wkr,

Renald
