### ISSUE TITLE
Bell notification in status bar

### ISSUE THREAD

**Issue by aclindsa** [koekeishiya/yabai#236]
I frequently use a terminal bell to alert me of the completion of long-running jobs in my shell in other desktop environments when I use Linux. Do you know if it would be possible to make the yabai status bar turn a desktop's background a different color if it hasn't been visited since a bell was seen?

**Comment by dominiklohmann** [comment]
The terminal bell is just the special character `\a`. iTerm2 supports running arbitrary scripts when printed text matches a regular expression, which you can use to match the bell and then run whatever code you want. There are many open-source tools available for setting the current wallpaper, e.g. [macos-wallpaper](https://github.com/sindresorhus/macos-wallpaper). You can find more information about triggers [here](https://www.iterm2.com/documentation-triggers.html).

Personally I just use the excellent [*Alert on Next Mark* feature](https://martinpeck.com/blog/2018/07/04/iterm2-goodness/) for this. Just have the shell integration installed and press <kbd>alt</kbd> <kbd>cmd</kbd> <kbd>A</kbd> and you'll get a system notification when either the currently running or the next command is done.

For Terminal.app, check out the option *Continue bouncing until in foreground* under Settings > Profiles > Advanced. I don't think there's much you can do here.

**Comment by aclindsa** [comment]
Sorry, I don't think my phrasing was clear - I'm not talking about actually changing the background of the desktop here. I'm interested in being able to set some sort of per-desktop notification in the yabai status bar. I meant to be suggesting that you could change the background color behind the number representing the desktop which had a notification.

If this just isn't in scope for you, that's fine - though I find changing the color in this way to be much less annoying than the icon bouncing around (I've gotten used to the status bar doing this with dwm in Linux).

**Comment by dominiklohmann** [comment]
That's not a thing. The code for the bar is self-contained in [src/bar.c](https://github.com/koekeishiya/yabai/blob/master/src/bar.c), so it's pretty easy to fork and patch this in by yourself. The code is held very simple, and we're also always here to help.

Generally speaking I don't think this should be a yabai feature, as the bell is something that your terminal emulator should respond to.

**Comment by dominiklohmann** [comment]
Closing this as resolved. Feel free to create a new issue if you have any questions.
