### ISSUE TITLE
manage=off not working for WhatsApp

### ISSUE THREAD

**Issue by turingzhi** [koekeishiya/yabai#2362]
Here is my config
>  /opt/homebrew/bin/yabai -m rule --add app="^WhatsApp$" manage=off

after run <code>sleep 2 ; yabai -m query --windows</code>, it shows                                                                                                       
> "id":75,
	"pid":1427,
	"app":"WhatsApp",
	"title":"WhatsApp",
	"scratchpad":"",
	"frame":{
		"x":-0.0000,
		"y":25.0000,
		"w":1440.0000,
		"h":875.0000
	},
	"role":"AXWindow",

Other apps are fine.

**Comment by lake-effect** [comment]
Same for Alacritty:

```
yabai -m rule --add app="Alacritty" sticky=on sub-layer=above manage=off
```

```
~[1]►yabai -m query --windows app                                                                                                         09:21
[{
	"app":"Alacritty"
},{
```

**Comment by lake-effect** [comment]
https://github.com/koekeishiya/yabai/issues/2336#issuecomment-2241767660 resolved it for me.

**Comment by turingzhi** [comment]
nice for you. But this solution seems not good for me somehow. Other apps are fine. Just whatsapp has something wrong

**Comment by PhrantiK** [comment]
try: `yabai -m rule --add app="WhatsApp" manage=off`
