### ISSUE TITLE
How to get all events as stream?

### ISSUE THREAD

**Issue by MarcWeber** [koekeishiya/yabai#2364]
wmii read event -> you'll get all the nice events like this:

```
desk marc i%wmiir read event                                                                                                                                /home/marc nixos   
Key Mod4-w        
ClientFocus 0x4c00006
Key Mod4-w
ClientFocus 0x4c00006
Key Mod4-0
UnfocusTag web
FocusTag 0
AreaFocus 2
ClientFocus 0x100023d
Key Mod4-b
UnfocusTag 0
FocusTag web
AreaFocus 2
ClientFocus 0x4c00006
Key Mod4-m
Key Mod4-k
ClientFocus 0x100026e
Key Mod4-j
ClientFocus 0x4c00006
Key Mod4-Return
CreateClient 0x5000006
Warning processing rule group=~: bad value
ViewAttach web 0x5000006
AreaAttach web 2 0x5000006
```

Now the simple bar  https://github.com/Jean-Tinland/simple-bar even has https://github.com/Jean-Tinland/simple-bar-server
but I think it's the wrong way to go.

Ubersicht allows a function which calls a callback or such. Thus all the nice events could be sent to JS and those which are not of interest can be ignored. Should be much chaper to keep connections open, send some data than to spawn processes over and over again.

So the idea is to have a socket, a command can connect to. yabai sending all events to it...
Then ubersicht could read all events and do whatever it wants.

If you used a JSON syntax like ["window-created", {"pos": >. }] .. everything would be very easy.
If you care about speed you could even send the actions you care about to the socket line by line and be done.

I want to get the menu bar from WMII I had. It ony does 2-3 important things: Tell me what space I am on. Allow to switch or move a window to a space with tab completion. So I can create new spaces or select existing ones.

Looks like yabai --verbose | tee /tmp/ylog   comes close. The tail -f can be used to read lines from multiple processes. While not perfect good enough for testing.

**Comment by koekeishiya** [comment]
#1606 but there has beeb very low interest

**Comment by MarcWeber** [comment]
I think TCP/IP actually would fix sending signals directly to uebersicht. Looks like you've been one step ahead of me. Eventually piping --verbeose into socat should do it for now.
