### ISSUE TITLE
How can I use rectangle like keyboard shortcuts to move windows around while using yabai?

### ISSUE THREAD

**Issue by Pranav-Karra-3301** [koekeishiya/yabai#2374]
I want to be able to move windows left right top bottom, and in quarters but at the same time while using yabai. Or how can I make rectangle commands the primary?

**Comment by matt1fy** [comment]
Try something like this

`yabai -m window --toggle float --grid 5:5:0:0:2:5`
`yabai -m window --toggle float --grid 5:5:2:0:3:5`

where
`--grid <rows>:<cols>:<start-x>:<start-y>:<width>:<height>`

then just apply it to a skhd combination and you’re good.

**Comment by Pranav-Karra-3301** [comment]
I dont want the window to float though thats the thing.  Say i had 4 windows open in quarters. I want to be able to move one of those windows to occupy the entire right half of the screen, and the other 3 to just rearrage in the left half

**Comment by kanghengliu** [comment]
`yabai -m window --warp $DIR` to wrap unwanted window to one direction (in this case other half $DIR would be either east or west)

you could also use mouse with modifier to drag a window and rearrange if you can be bothered.

**Comment by maulik13** [comment]
If you have 4 windows in 4 quadrants, you need to warp the window that is blocking the required window to be taking full space. 
Let us say you have, 
```
|----|----|
| W1 | W2 |
|----|----|
| W3 | W4 |
|----|----|
```

You want to move W1 to the right side with full height. Then you first need to swap W1 with W2. So with W1 in focus, 
`yabai -m window --swap east`

Then, warp W4 to west. So with W4 selected,
`yabai -m window --warp  west`
