### ISSUE TITLE
How to float window/pop-up based on app and title?

### ISSUE THREAD

**Issue by fcaraujo** [koekeishiya/yabai#2375]
Hey,

Can someone please help me figure out how to float this Bitwarden authentication pop-up window? (preferably vertically/horizontally centralized if possible 🙂)

I'm running `yabai-v7.1.1` on macOS Sonoma 14.6 (23G80).

This is what I currently have:
![image](https://github.com/user-attachments/assets/ce670f28-3935-4df3-b489-305605fccd0c)

This is roughly my target:
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/663d304e-5726-4ca1-a344-1edb58bb47dd">

I queried it and got the following (to ensure I have a window app/title that matches my attempts):

```
{
        "id":2836,
        "pid":624,
        "app":"Google Chrome",
        "title":"Bitwarden",
        "scratchpad":"",
        "frame":{
                "x":415.0000,
                "y":387.0000,
                "w":613.0000,
                "h":271.0000
        },
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "root-window":true,
        "display":1,
        "space":1,
        "level":0,
        "sub-level":0,
        "layer":"normal",
        "sub-layer":"normal",
        "opacity":1.0000,
        "split-type":"none",
        "split-child":"none",
        "stack-index":0,
        "can-move":true,
        "can-resize":true,
        "has-focus":false,
        "has-shadow":true,
        "has-parent-zoom":false,
        "has-fullscreen-zoom":false,
        "has-ax-reference":true,
        "is-native-fullscreen":false,
        "is-visible":true,
        "is-minimized":false,
        "is-hidden":false,
        "is-floating":true,
        "is-sticky":false,
        "is-grabbed":false
}
```

And I tried a couple of rules/signals without success:

```
yabai -m rule --add app="Google Chrome" title="Bitwarden" manage=off
...
yabai -m rule --add app="Google Chrome" title="Bitwarden" manage=on grid=10:10:1:1:8:8 border=on sticky=on layer=above
...
yabai -m signal --add app='Google Chrome' event='window_title_changed' \
  action="yabai -m rule --add label=$(uuidgen) app='Google Chrome' title='Bitwarden' manage=off"'
...
yabai -m signal --add app='Google Chrome' event='window_created' \
  action="yabai -m rule --add label=$(uuidgen) app='Google Chrome' title='Bitwarden' manage=off"'
```

Thank you

**Comment by koekeishiya** [comment]
You need to use `--apply` instead of `--add` if you want to apply rules to *existing windows* from a signal.
Try the following instead: `yabai -m signal --add app='Google Chrome' event='window_title_changed' action="yabai -m rule --apply app='Google Chrome' title='Bitwarden' manage=off"'`

**Comment by fcaraujo** [comment]
@koekeishiya really appreciated it; it worked like a charm!
By the way thanks for also clarifying the bits I missed.

I just tinkered a lil bit the grid config and that's what I have 🎉:
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/a36db7c0-0a6e-478c-944c-4b06e0d58c0e">

For posterity (and to help the next folks searching for light):
```
yabai -m signal --add app='Google Chrome' event='window_title_changed' \
  action="yabai -m rule --apply app='Google Chrome' title='Bitwarden' manage=off grid=12:12:4:4:4:4"
```

Cheers!
