### ISSUE TITLE
Screen recording permission requested even when window animation disabled

### ISSUE THREAD

**Issue by cpick** [koekeishiya/yabai#2378]
Running `yabai` with the [example version of yabairc](https://github.com/koekeishiya/yabai/blob/d9dcbc2fa556f500224c9da02a87285a3c4e8581/examples/yabairc) prompts for "Screen & System Audio Recording" permission.  When that's denied it prints the warning:
> command 'window_animation_duration' for domain 'config' requires Screen Recording permissions! ignoring request..

The [README.md says](https://github.com/koekeishiya/yabai/blob/d9dcbc2fa556f500224c9da02a87285a3c4e8581/README.md?plain=1#L52):
> yabai must be given Screen Recording permission if and only if you want to enable window animations, and will request access when necessary

And the yabairc (linked above) [includes](https://github.com/koekeishiya/yabai/blob/d9dcbc2fa556f500224c9da02a87285a3c4e8581/examples/yabairc#L25-L26):
```sh
yabai -m config                                 \
...
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
```

The [man page says](https://github.com/koekeishiya/yabai/blob/d9dcbc2fa556f500224c9da02a87285a3c4e8581/doc/yabai.1#L276-L282):
> window_animation_duration [<FLOAT_SEL>]
> Duration of window frame animation.
> If 0.0, the change in dimension is not animated.

So I would have thought that window animation was disabled (by being set to 0.0) and that that would case the permission to not be requested?

**Comment by cpick** [comment]
I'm guessing that [at this point](https://github.com/koekeishiya/yabai/blob/d9dcbc2fa556f500224c9da02a87285a3c4e8581/src/message.c#L1268-L1273):
```c
        } else if (token_equals(command, COMMAND_CONFIG_ANIMATION_DURATION)) {
            struct token_value value = token_to_value(get_token(&message));
            if (value.type == TOKEN_TYPE_INVALID) {
                fprintf(rsp, "%f\n", g_window_manager.window_animation_duration);
            } else if (value.type == TOKEN_TYPE_FLOAT) {
                if (CGPreflightScreenCaptureAccess()) {
```
There should be an additional `if (value.float_value)` around the `if (CGPreflightScreenCaptureAccess()) { ... } else { ... }` so permissions are checked if and only if `value.float_value != 0.0`?

**Comment by cpick** [comment]
That seems to do the trick, opened #2379

**Comment by koekeishiya** [comment]
Fixed in https://github.com/koekeishiya/yabai/commit/4572d69932a11e157985c7c515d1e094b88707c6 https://github.com/koekeishiya/yabai/commit/14f1220c6a8ec10b0480e5b5877b59585fba8e0c
