### ISSUE TITLE
Moving Windows Across Spaces No Longer Works in MacOS 15.0

### ISSUE THREAD

**Issue by albertcai101** [koekeishiya/yabai#2380]
I recently upgraded to MacOS 15.0 and reinstalled yabai so all other commands like switching spaces and window focusing works.

However, moving windows to different spaces no longer works:

```
# send window to a space
rcmd - 1 : yabai -m window --space 1
```
When I run this, the focused window still remains in the current space. This code worked before the MacOS 15.0 upgrade.

**Comment by koekeishiya** [comment]
Works fine for me. Note that moving windows to other spaces on Sequioa requires SIP to be partially disabled and the scripting addition to be installed and loaded.

**Comment by albertcai101** [comment]
I have installed yabai from HEAD and configured the scripting addition following the wiki. 
My yabairc begins with 
```
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
```

`yabai --start-service` gives no complains but strangely `yabai --load-sa` says the scripting addition is not configured yet. Also, looking at my error logs, `yabai -m window --space 1` gives no errors but `yabai -m space --focus next` gives `sh: focus_window: command not found` once every time. I do not know if any of these are related.

**Comment by matt1fy** [comment]
I’m on MacOS 14.4.1 and this happened all of a sudden too. Most windows will move across spaces just fine, but somehow one of them would just move half way and just breaks. I can still resize them with grid thankfully but it being sticky is bothering me.

My yabai was installled through HEAD and i am ahead in commits too. I was somehow able to temporary rectify the issue by destroying all spaces. But once i introduce new ones the affected windows will go back to being unmanaged.

**Comment by albertcai101** [comment]
I tested every single command, and they _all_ work except for Moving Windows to another Space. Specifically, these ones
```
# move window to previous space
yabai -m window --space prev

# move window to display focused before the current one
yabai -m window --display recent

# move window to space 2
yabai -m window --space 2

# move window to space 2 and switch to space 2 (works with both SIP enabled and disabled)
yabai -m window --space 2 --focus
```
ALL other commands work, which is strange. Nothing in error log.

**Comment by orikremer** [comment]
Experiencing the same on Ventura 13.6.8

**Comment by Benjscho** [comment]
Experiencing the same issue after upgrading to Ventura 13.6.8, enabling screen recording didn't fix. On yabai-v7.1.1. Similarly nothing in error log. Is there a more verbose debug mode?

**Comment by koekeishiya** [comment]
Upload Ventura 13.6.8 Dock.app and post it here or in a separate issue.

**Comment by ghaarm** [comment]
Experiencing the same on Ventura 13.6.9
- When trying to move space (next or number) yabai is just toggling between two apps.
-  skhd -V works properly.
- yabai v7.1.1

Started when updating some days ago on 13.6.8. 
- Update on 13.6.9 didn't help.
- Reinstalling yabai/skhd didn't help.
- Reinstalling yabai from HEAD and configured the scripting addition following the wiki didn't help.
- Enabling screen recording didn't fix it.

**Comment by koekeishiya** [comment]
Ventura 13.6+, Sonoma 14.5+, and Sequoia 15+ now all use the scripting addition to move a window to another space, and if the scripting addition is not installed, will attempt to use the fallback method introduced in Sonoma 14.5. 

This fallback method was NOP'd by Apple in Sequoia 15+, so it does nothing there, so Sequoia *requires* the scripting addition for this functionality to work (and I have confirmed myself that it works on 15.0Beta 1,2,3,4,5 Apple Silicon).

I don't know if the fallback method works on Ventura 13.6+ as I do not have a Ventura machine, and cannot investigate without having both of the files mentioned in my comment above.

**Comment by albertcai101** [comment]
Can confirm, v7.1.2 now works on Sequoia Beta! Thank you so much :))

**Comment by ghaarm** [comment]
Thanks a lot! Moving spaces is now working again with Ventura 13.6.9.

**Comment by gkzhb** [comment]
With SIP enabled, I managed to move window to other spaces with some [Hammerspoon](https://www.hammerspoon.org/docs/index.html) coding:
https://github.com/ianyh/Amethyst/issues/1643#issuecomment-2424143589

The core idea is to mimic the user actions to switch destop space while dragging a window, which will result in moving window to other desktop spaces.

**Comment by zt1983811** [comment]
> With SIP enabled, I managed to move window to other spaces with some [Hammerspoon](https://www.hammerspoon.org/docs/index.html) coding: [ianyh/Amethyst#1643 (comment)](https://github.com/ianyh/Amethyst/issues/1643#issuecomment-2424143589)
> 
> The core idea is to mimic the user actions to switch destop space while dragging a window, which will result in moving window to other desktop spaces.

Is this function will be included in new release? I am still stack on Sequoia15+ is not able to move to other window

**Comment by asmvik** [comment]
Working again on Tahoe 26.4 with SIP enabled. https://github.com/asmvik/yabai/issues/2788
