### ISSUE TITLE
Put new window next in stack vs top

### ISSUE THREAD

**Issue by jbriales** [koekeishiya/yabai#2387]
It seems currently when focused in a stack, a new created window goes to the top of it (rather than after the current window).

E.g. if there is a stack with 4 elements, and I'm focused in the one with index 2 and create a new one, it'll have index 5.
I'd like for the new window to go right after the current (2), so it gets into position 3 and everything afterwards gets moved a position up.

E.g.
Before: a , [b] , c, d
After (current): a, b, c, d, [new]
After (desired): a, b, [new], c, d

Would it be possible to modify the stack default config to behave in this manner?

If not, is there any alternative flow to achieve a similar effect?
So far I only saw `--swap` to change the order of windows in the stack, but it doesn't seem compatible with "inserting" within the stack.

**Comment by koekeishiya** [comment]
Sounds like reasonable default behavior. I'll look into it at some point.

**Comment by jbriales** [comment]
Do you have some code pointer to the relevant logic in case I gave it a try in local-dev first?

**Comment by jbriales** [comment]
Awesome, tried in HEAD and it works!

**Comment by jbriales** [comment]
Sth I noticed though: Now some windows (e.g. Chrome browser) do not go into the stack when created.
Not sure if this might be due to some conflict with the rest of my configuration or related to this change.

**Comment by jbriales** [comment]
> Sth I noticed though: Now some windows (e.g. Chrome browser) do not go into the stack when created. Not sure if this might be due to some conflict with the rest of my configuration or related to this change.

It seems this fixed itself after reboot. Not sure if there is sth I should look at in logs if this occurs again to root-cause it.

**Comment by koekeishiya** [comment]
Not related to this change. If you find a way to reproduce the problem, feel free to create a new issue.
