### ISSUE TITLE
Feature request: Only padding option

### ISSUE THREAD

**Issue by MattOrmianek** [koekeishiya/yabai#2389]
Honestly, configuring Yabai to match my current setup exactly could take a few hours. However, Yabai offers a game-changing feature that I really want to use: the ability to set custom padding on windows (top, bottom, left, and right). I’d like to use this feature without relying on Yabai's window management capabilities. Is that possible? I’ve been struggling with the configuration file but haven’t had any success so far. It would be great if there was a way to use Yabai just for padding.

**Comment by koekeishiya** [comment]
Not possible, yabai cannot limit the display bounds available to other software on your system.
The reason it works in yabai itself, is because it puts padding in its own tiling algorithm.
