### ISSUE TITLE
yabai outside of .yabairc rule doesn't set window border

### ISSUE THREAD

**Issue by tsujp** [koekeishiya/yabai#239]
**Version: yabai-v1.1.2
OS: macOS 10.14.16
Appropriate SIP settings removed**

My goal here is to have a configuration where the current focused window has a border and all others do not.

I am testing this manually before I write a signal (which incidentally also doesn't work) with the following:

```bash
yabai -m rule --add app="^Code$" border=on
```

This does nothing, even though I can see this app if I do

```bash
yabai -m query --windows
```

```json
[{
	"id":392,
	"pid":980,
	"app":"Code",
	"title":"yabairc",
	"frame":{
		"x":10.0000,
		"y":738.0000,
		"w":1265.0000,
		"h":692.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":1,
	"focused":0,
	"split":"horizontal",
	"floating":0,
	"sticky":0,
	"border":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}]
```

**Comment by dominiklohmann** [comment]
You need to enable window borders globally first, then you can disable/enable them on an individual basis with rules.

```sh
# enable window borders
yabai -m config window_border on

# create a rule that disables them for all apps
# needs to be run before other rules affecting borders
yabai -m rule --add label=test app=".*" border=off

# now your rule works as expected
yabai -m rule --add app="^Code$" border=on
```

This behavior is unintuitive and should be considered a bug.

**Comment by kinglouie** [comment]
If I understand you correctly and your only goal is to have a border around the focused window you don't need any signals or rules just set the focused border color to you liking and make the other border color transparent like this example.

```
yabai -m config active_window_border_color   0xffffffff
yabai -m config normal_window_border_color   0x00000000
```

**Comment by tsujp** [comment]
That was it, I seemed to have been overthinking it a bit here. Thank you both, @kinglouie's solution being the simpler (and so less likely to break) is the one I went with.
