### ISSUE TITLE
Yabai does not respond to commands

### ISSUE THREAD

**Issue by Gogn** [koekeishiya/yabai#2390]
I have been using Yabai for some time now and have updated it several times according to the instructions.
After each update, a new element was added to the Accessibility settings, which seems strange to me.
<img src="https://github.com/user-attachments/assets/8cd77ce1-e5ea-4e1e-998e-e8ac33599519" width="300">

Yabai works in fact, but when I restart the service `yabai --restart-service` and also `yabai --stop-service`
I got: `Could not find service "com.koekeishiya.yabai" in domain for user gui: 501`
If I run `yabai --start-service`, these commands do not show errors, but I cannot stop the service, after `yabai --stop-service`, the windows are still managed via tiling.

What could be wrong, why does Yabai work but not respond to commands?

**Comment by haberdashPI** [comment]
I am having a similar problem. 

I have a few hints about what might be going on. Suspecting that I might have multiple installs of yabai somehow I tried to completely remove `skhd`, `spacebar` and `yabai`, and then reinstall, clear permissions for the previous binaries.

But even then I see the same issue. I can call `skhd --stop-service` and `yabai --stop-service`: sometimes this appears to work (no output) or it doesn't (same error message as above). Either way, stopping both services appears to do nothing. My keybindings in skhd still work and yabai still actively resizes windows. ????

**Comment by haberdashPI** [comment]
I'm having a very similar problem. Tried to uninstall `yabai` and related services (e.g. `skhd`) and do a fresh install and still had the same issues.

**Comment by koekeishiya** [comment]
Something is wonky with your installation and setup. Do a full uninstall and cleanup of permissions.

**Comment by haberdashPI** [comment]
> Something is wonky with your installation and setup. Do a full uninstall and cleanup of permissions.

This is exactly what I did though. Something appears to be persisting across what I thought was a full uninstall.
