### ISSUE TITLE
Sticky scratchpad windows?

### ISSUE THREAD

**Issue by jbriales** [koekeishiya/yabai#2394]
Is it possible for a scratchpad window to be also "sticky"?

I tried just doing `yabai -m window --toggle sticky`.
The window becomes sticky in that's in every space as expected, but now toggling the visibility of the scratchpad via `yabai -m window --toggle LABEL` does not work anymore.

**Comment by koekeishiya** [comment]
I'll fix it when I have access to a computer. Takes like 4min.

**Comment by jbriales** [comment]
YES! Unfortunately I still don't understand well the code magic behind it but it does work as a charm now... Thanks for the prompt solution! :) This makes my workflow excellent now :D
