### ISSUE TITLE
no opacity on macOS 14.6.1 ?

### ISSUE THREAD

**Issue by jbaylies** [koekeishiya/yabai#2400]
it seems like macOS 14.6.1 may have broken opacity for Yabai 7.1.2

I made sure yabai was still running with `yabai -m config focus_follows_mouse autoraise`, which works.

And my SIP config seems correct:
```
Apple Internal: disabled
Kext Signing: enabled
Filesystem Protections: disabled
Debugging Restrictions: disabled
DTrace Restrictions: enabled
NVRAM Protections: disabled
BaseSystem Verification: enabled
Boot-arg Restrictions: disabled
Kernel Integrity Protections: enabled
Authenticated Root Requirement: enabled
```

But my apps are no longer opaque ;_;

**Comment by koekeishiya** [comment]
Opacity is still working fine, make sure your configuration is proper; review the wiki installation pages.
