### ISSUE TITLE
monterey macOS 12.7.6 issue moving app between windows/spaces

### ISSUE THREAD

**Issue by kulubaev** [koekeishiya/yabai#2408]
please anyone help, on macOS 12.7.6 i can not make moving app to different spaces via key combination I have tried all samples that i could find.

focusing is working, however moving app is not . I have disabled integrity as was  recommended.
have installed in boths ways from HEAD and through brew manager.

please help. this also unabling me to load organize app per several windows on start.

its intel based machine early -2015 13. retina

**Comment by koekeishiya** [comment]
Implemented same workaround (on master) as mentioned in https://github.com/koekeishiya/yabai/issues/2380#issuecomment-2281677488

**Comment by kulubaev** [comment]
many thanks for prompt response, installing from HEAD its working again. will close the issue.

**Comment by kulubaev** [comment]
i realized that on startup assigning apps via adding rules are not working
aim is to have preliminary setup so on start it will launch the apps 
could you please give direction, samples i did via `apply` also not effective, perhaps because of OS

**Comment by koekeishiya** [comment]
```
yabai -m rule --add app="^(Safari|Orion)$" space=web role=AXWindow subrole=AXStandardWindow
yabai -m rule --apply
```

works for me

**Comment by kulubaev** [comment]
> ```
> yabai -m space 3 --label web
> 
> yabai -m rule --add app="^(Safari|Orion)$" space=web role=AXWindow subrole=AXStandardWindow
> yabai -m rule --apply
> ```
> 
> works for me

this looks like works if i open the app while yabai up& running, but how do launch app on startup. should these rules get executed on initial launch?
do yabai supports this scenario?
