### ISSUE TITLE
won't start up

### ISSUE THREAD

**Issue by Yamaha3001** [koekeishiya/yabai#2415]
I have a brand new system, my first time using MacOS, followed this tutorial: https://youtu.be/k94qImbFKWE?si=mPhpvX5OPSK_R6wF
just used yabai --start-service instead of brew services start yabai
I got to the point where I needed to give acces in the System settings. But after that I used yabai --start-service and restart and stop, but it just won't turn on no matter what and I'm stuck with this now
It doesn't even respond, screenshot shows the Terminal.
<img width="530" alt="Screenshot 2024-09-09 at 23 06 52" src="https://github.com/user-attachments/assets/f89d70fa-73c5-4024-9718-bfdf6f4c55c7">

**Comment by rOnInRaJ-dev** [comment]
It looks like the terminal did not give any errors when you put in `yabai --restart-service`. It looks like yabai should be running. 

Try running `yabai --start-service` on the terminal, and then try running this command `yabai -m config layout bsp`. (best to run it with multiple windows on your current space) If this command works to tile your windows, then that means that yabai is working, and you should then configure skhd to run these commands with keyboard shortcuts.

**Comment by Abdullah16M** [comment]
`brew services start yabai` has been replaced by `yabai --start-services`

**Comment by koekeishiya** [comment]
You have to run `yabai --start-service` at least once before you can use `--restart-service`. You can't restart something that isn't running. If you run `--stop-service` you also need to run `--start-service` again, not `--restart-service`.
