### ISSUE TITLE
Move floating window fully backwards when focus changes to managed window

### ISSUE THREAD

**Issue by sbobadilla8** [koekeishiya/yabai#2418]
Hello,
I'm coming back to yabai after a while, and building my config once again. A couple of things that changed now (IIRC) is that now floating windows are not sent backwards when focus changes to another window. E.g: I have an unmanaged mail window, if I open a link from a mail, it goes to safari and safari becomes the active window, but the mail window is still on top and can't see the browser unless I minimize or close the mail window. 
Is there any setting for fixing this?

**Comment by koekeishiya** [comment]
You can use a rule for this. Add the following to your config: 

`yabai -m rule --add app=".*" sub-layer=normal`
`yabai -m rule --apply`
