### ISSUE TITLE
Turning off `window_opacity` does not restore each window's opacity

### ISSUE THREAD

**Issue by tsujp** [koekeishiya/yabai#242]
1. Start with `window_opacity` off, and set `normal_window_opacity` to some non-integer value so you can see it's effect, say 0.5.
2. Turn `window_opacity` on and reload yabai for changes to take effect, notice windows not active have their opacity reduced to 0.5 as expected.
3. Turn `window_opacity` off again, reload yabai for changes to take effect, notice windows that are not active still have their opacity set to 0.5.

While this is _correct_ behaviour it is not _intuitive_ behaviour. Intuitively turning a setting off would imply reverting back to whatever it was beforehand, in this case the window's opacity should go back to 1.0 (the default value if `window_opacity` is off).

**Comment by dominiklohmann** [comment]
The feature is not designed to be toggled often, really. 

What if an application changes its alpha by itself using the same method we use? Should we reset it to be opaque again? 

I agree this is unintuitive, but it's also not very hard to reset `*_window_opacity` back to 1.0 manually before disabling transparency.

**Comment by tsujp** [comment]
I was thinking about whether or not I should do a PR for this (good practice for my rusty C). Perhaps yabai could snapshot window opacity levels upon a change from `off -> on` before it applys settings, then if `on -> off` occurs apply the changes it cached in a file somewhere.

Just a simple map of window id to opacity, O(n) lookup time however.

**Comment by dominiklohmann** [comment]
https://github.com/koekeishiya/yabai/blob/024a21f87912643ff078b281528795a16b9aa516/src/window_manager.c#L431-L446

Take a look at the variable `enable_window_opacity` from `window_manager.{c,h}`, which determines whether transparency is enabled, and the above listed function which tells the scripting addition to change the transparency of a window by id.

I don't think caching is a proper fix—just wanted to note that applications can change their own alpha level as well, so setting to 1.0 might not be a proper reset. It's rare anyways as there are better ways to do this than `CGXSetWindowListAlpha` for the apps themselves. It might be fine to set it to 1.0 as a reset, and ultimately that's up to @koekeishiya to decide.

**Comment by tsujp** [comment]
The caching is so that it resets to whatever the setting was before the toggle, or if I can find a way to capture when a window changes it's own alpha, that setting itself.

I haven't had a chance to look at this yet but I will play around at least myself and either find success or failure hehe, thank you for the snippet too!

**Comment by koekeishiya** [comment]
I don't think this is something that I will bother looking into.
