### ISSUE TITLE
Open all app in space 6 by default?

### ISSUE THREAD

**Issue by MrNeth** [koekeishiya/yabai#2421]
I want to default all apps to window 6 except if they have a window expressly stated in config.

This is what I have in config, everything else I want open in space 6.

`
yabai -m rule --add app="Google Chrome"        space=^1
yabai -m rule --add app="Brave Browser"        space=^2
yabai -m rule --add app="Code"                 space=^3
yabai -m rule --add app="iTerm2"               space=^3
`

Is this possible?

**Comment by kmiterror** [comment]
Try adding this as last rule
```
yabai -m rule --add app="^.*$" space=^6
```

**Comment by MrNeth** [comment]
I love you lol

> Try adding this as last rule
> 
> ```
> yabai -m rule --add app="^.*$" space=^6
> ```
