### ISSUE TITLE
Possible to keep unfocused floating windows above focused tiled window?

### ISSUE THREAD

**Issue by danijar** [koekeishiya/yabai#2423]
I often run into the following issue:

- I have two windows A and B open, which are managed by default and tile the screen with A left and B right.
- Then I change A to floating mode, resulting in the floating window A on top of the B below which fills up the whole screen.
- But once I click on the background window B, the floating window A disappears in the background and becomes almost impossible to reach, because it's covered by the full screen window B.

Is it possible always to keep the floating window on top, even if the managed window below has the input focus (like in i3)?

**Comment by koekeishiya** [comment]
This is the default behaviour, but it needs the scripting-addition to work.

**Comment by danijar** [comment]
Ah I see, that explains it. Thanks!
