### ISSUE TITLE
How can I do configuration make the window looks like the screenshot ?

### ISSUE THREAD

**Issue by lkebin** [koekeishiya/yabai#2435]
How can I do configuration make the window looks like the screenshot ?

<img width="1440" alt="screenshot" src="https://github.com/user-attachments/assets/942dc0e2-e423-45d9-aec1-752a6067c90e">

**Comment by Liquidmantis** [comment]
You'll need to provide a bit more detail on what it is you're trying to achieve.  If it's just the layout, which is Yabai's area of concern, that's a basic layout.  The two background terminals are split in two by the standard BSP layout, and the foremost window is floating to sit on top.
Have you looked at the example config? https://github.com/koekeishiya/yabai/blob/master/examples/yabairc

**Comment by lkebin** [comment]
Thanks!

So there are two background terminal windows without title bar ?

Yes, I did try the example config, I got all program windows display on the screen, and arrangement automatically.

**Comment by Liquidmantis** [comment]
Yep, looking at the bar on the bottom of the left terminal, that looks like [kitty](https://sw.kovidgoyal.net/kitty/), which is a highly-configurable performant terminal.  I have a [similar pared down UI](https://github.com/Liquidmantis/dotfiles/blob/main/kitty/kitty.conf#L12), but with radiused corners.

Other than that, it's just the menubar and Dock set to hide to reduce clutter and get a clean desktop
