### ISSUE TITLE
Is it possible to make all the zoom-fullscreen work for each window in current space?

### ISSUE THREAD

**Issue by luxuxl** [koekeishiya/yabai#2439]
I like using mode toggle (tall/fullscreen) in Amethyst.Now I am trying yabai,is it possible to change global layout method?

**Comment by koekeishiya** [comment]
If you want all widnows to be fullscreen always, use `layout stack` for that space. If you want `bsp` tiling but temporarily want to fullscreen all windows, write a script that queries all windows in that space, and run them through the `window --toggle zoom-fullscreen` command.
