### ISSUE TITLE
Spaces defined based on resolution

### ISSUE THREAD

**Issue by tsujp** [koekeishiya/yabai#245]
It'd be nice to have spaces additionally defined based on resolution. This would be useful because some apps have minimum sizes (like Discord) or are too cluttered when working on the laptop screen vs an external monitor.

In my case it's jarring going from a 1440p monitor to the MBP's 1680x1050 equivalent display.

Right now you can define how windows spawn and occupy spaces as follows:

```
yabai -m rule --add app="^Discord$" space=2
```

Perhaps another conditional flag to `--add` which takes in horizontal `resolution` which you can define in three ways

```
> greater than
< less than
= optionally paired with < or > to give equality-to
else implicitly strictly equal
```

```
resolution="1050"      # matches 1050 width exactly
resolution=">=1050"    # matches anything above or equal to 1050
resolution="<=1050"    # matches anything below or equal to 1050
```

This means we can do things like this now

```
yabai -m rule --add app="^Discord$" space=3 resolution=1050
yabai -m rule --add app="^Discord$" space=2
```

If resolution is `1050` then any app matching `^Discord$` is put in space 3, otherwise it's put in space 2.

I've suggested an additional `--app` flag as otherwise a new syntax or parsing algorithm is required or the configuration file which may not be backwards compatible. This is the least intrusive way to add such functionality and suits the already laid out structure of "if the rules match `X` then do `Y`". Where `X` is just another thing to match, the resolution.

This is also something I make take a look at doing a PR for when I have time but I am curious to see if others would find this useful also.

**Comment by dominiklohmann** [comment]
This sounds unnecessarily complicated, and can already be implemented using signals quite easily.

Instead, create a rule that makes Discord float so that it's not managed by default, and then create a signal that compares the size of the display its on with your required size and moves it to another display if such a thing exists and unfloats it on there. That's like 4-5 lines of code with signals, queries and `jq`.

**Comment by tsujp** [comment]
I'll give it a shot with the `jq` and `signals` approach as you suggest. I do think that common-enough tasks (if anyone else has a use case for this) do deserve their own dedicated setting though.

**Comment by dominiklohmann** [comment]
> I do think that common-enough tasks do deserve their own dedicated setting though.

You'd just end up implementing a grammar much like jq's. I don't think this is maintainable.
