### ISSUE TITLE
Is there able to make the window opacity with blur?

### ISSUE THREAD

**Issue by xbunax** [koekeishiya/yabai#2451]
The terminal background opacity with blur is great, however yabai only can set opacity without blur.

**Comment by hungvx-dev** [comment]
You can use the Kitty terminal to achieve that. 
`background_opacity` and `background_blur` in kitty.

**Comment by xbunax** [comment]
> You can use the Kitty terminal to achieve that. Using the `background_opacity` and `background_blur`.

Yes, I know that. But `yabai` is an global setting that I can set app which is unable to make opacity and blur.

**Comment by koekeishiya** [comment]
No blur currently with how opacity has to be implemented.
