### ISSUE TITLE
Sequoia 15 yabai and Dock malfunction

### ISSUE THREAD

**Issue by SArthurX** [koekeishiya/yabai#2461]
It seems like there’s some kind of conflict between Dock and Yabai, which causes the Dock to repeatedly occupy threads until it eventually freezes.

I ultimately have to run `killall Dock` to restore everything back to normal.

**Comment by koekeishiya** [comment]
Works fine for me. Upgrade to v7.1.5 and make sure you have configured your system correctly as described in the wiki.
