### ISSUE TITLE
"error with scripting-addition"

### ISSUE THREAD

**Issue by forks04** [koekeishiya/yabai#2463]
Installed program and edited the scripting addition via the instructions on the wiki. 

```
yabai -m space --create
cannot create space due to an error with the scripting-addition.
```

I followed instructions found in issue #787, but still did not fix the issue. I saw somewhere to use the --HEAD version, but I still have the issue.

## Version
yabai-v7.1.4
macOS 14.4
M2 apple silicon

SIP is disabled

**Comment by koekeishiya** [comment]
Upgrade to v7.1.5 and follow the instructions written in the wiki.

1. https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
2. https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
