### ISSUE TITLE
Unable to move window to space after updating macos sequoa 15.1

### ISSUE THREAD

**Issue by gyanaranjans** [koekeishiya/yabai#2469]
my skhd configuration
```bash
# move window to space #
shift + alt - 1 : yabai -m window --space 1;
shift + alt - 2 : yabai -m window --space 2;
shift + alt - 3 : yabai -m window --space 3;
shift + alt - 4 : yabai -m window --space 4;
shift + alt - 5 : yabai -m window --space 5;
shift + alt - 6 : yabai -m window --space 6;
shift + alt - 7 : yabai -m window --space 7;
shift + alt - 8 : yabai -m window --space 8;
shift + alt - 9 : yabai -m window --space 9;
```

**Comment by CadenMilne04** [comment]
You have to disable SIP for anything past Sequoa 15 unfortunately. 

That the reason I haven't updated my mac.

**Comment by gyanaranjans** [comment]
@CadenMilne04  I have installed latest version of yabai also I have disabled some of my SIP still it is not working
```bash
csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled
	Boot-arg Restrictions: disabled
	Kernel Integrity Protections: enabled
	Authenticated Root Requirement: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```
```bash
yabai --version
yabai-v7.1.5
```

**Comment by CadenMilne04** [comment]
@zapoutix @gyanaranjans 

Sorry, I am just regurgitating information from this issue:
https://github.com/koekeishiya/yabai/issues/2441

Maybe try doing:
```
sudo yabai --load-sa
```

I do wish someone better with Mac stuff than I am would make it work without jumping through these hoops lol.

**Comment by zapoutix** [comment]
Hello @CadenMilne04,

With the HEAD version and the command 
`sudo nvram boot-args=-arm64e_preview_abi`

reboot and

`sudo yabai --load-sa`

it is working ! :)

Thanks

**Comment by gyanaranjans** [comment]
```bash
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

```
I had to add this `sudo yabai --load-sa` in my first line of the yabairc file to work it was in the 2nd line before don't know why it didn't worked then

**Comment by rickalex21** [comment]
Is there any way to get it working without disabling SIP? I think it was working fine without disabling SIP before?

**Comment by tiagojsag** [comment]
would also love to have this work again without disabling SIP, since I can't due it due to company laptop restrictions.
