### ISSUE TITLE
Can't update to the latest HEAD

### ISSUE THREAD

**Issue by kkga** [koekeishiya/yabai#248]
Here's the error I get after trying to reinstall:

```
$ brew reinstall koekeishiya/formulae/yabai

==> Reinstalling koekeishiya/formulae/yabai 
==> Cloning https://github.com/koekeishiya/yabai.git
Updating /Users/gadzhi/Library/Caches/Homebrew/yabai--git
==> Checking out branch master
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "yabai"
Failure while executing; `git checkout -f master --` exited with 128. Here's the output:
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
```

**Comment by kkga** [comment]
I've tried running `brew install --HEAD yabai` after:
- installing git-lfs
- uninstalling git-lfs
- installing git-lfs and running `git lfs install`
- running `git lfs uninstall` and uninstalling git lfs

in all of these cases I get the same error: `git-lfs filter-process: git-lfs: command not found`... 
I can't figure out what's the problem here ¯\_(ツ)_/¯

`git-lfs` is in my $PATH, since I'm installing it via homebrew.

I've switched to stable release of yabai for now.

**Comment by capaldo** [comment]
I'm having this issue as well and its installed in my `$PATH`

**Comment by dominiklohmann** [comment]
Undid the changes. Sorry for the mess. It would've been cleaner with LFS, but the associated issues are simply not worth it.
