### ISSUE TITLE
Yabai not recognizing windows.

### ISSUE THREAD

**Issue by AlbinWarmlind** [koekeishiya/yabai#249]
I've had Yabai installed for a while and it's been flawless so far. What I've realized is that it doesn't recognize certain windows, such as Zathura or Emacs. Is there any way for me to add something into my yabairc file in order to make it recognize specific applications? I'm thinking it has to do with something like Zathura not counting as a normal app but perhaps a process. Is there a way to only allow certain programs running to be recognized as a program that should be tiled?

**Comment by pcr910303** [comment]
See #86 and the **Rules** part of the documentation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by koekeishiya** [comment]
There are at least two different reasons for this. One is at the process level, where some processes are marked as background-only (such as daemons). Sometimes applications don't have their process-type properly set up during launch (depending on how they were launched).

The other reason why yabai may ignore an application, is that if its windows do not properly respond to, and follow, the accessibility guidelines (using wrong roles for its windows, and so on).

The first issue is not solvable. The second issue can be resolved by using *rules*.

**Comment by dr1s** [comment]
I'm getting these messages in verbose mode:

> EVENT_HANDLER_DAEMON_MESSAGE: msg 'rule --add label=emacs app=Emacs manage=on'
> EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 237724
> EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 237724
> EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 237724
> EVENT_HANDLER_APPLICATION_LAUNCHED: Emacs
> EVENT_HANDLER_APPLICATION_LAUNCHED: could not observe Emacs (1)
> EVENT_HANDLER_APPLICATION_LAUNCHED: Emacs
> EVENT_HANDLER_APPLICATION_LAUNCHED: could not observe Emacs (1)
> EVENT_HANDLER_APPLICATION_LAUNCHED: Emacs
> EVENT_HANDLER_APPLICATION_LAUNCHED: could not observe Emacs (1)
> EVENT_HANDLER_APPLICATION_LAUNCHED: Emacs

After adding the rule and launching emacs, it tiles correctly at first but yabai isn't able to focus the window again.

Running yabai-v2.0.1 on 10.14.6

**Comment by koekeishiya** [comment]
Search the issues for "Emacs" and you will find some tips that you can try; these are Emacs GUI issues and there is nothing I can do in yabai to resolve those issues.
