### ISSUE TITLE
sticky=on Not effective

### ISSUE THREAD

**Issue by txl263** [koekeishiya/yabai#2496]
One of the rules that in config file did not work.
`yabai -m rule --add app="^Telegram$" sticky=on manage=off` 
Unless execute  command `yabai -m rule --apply `in terminal. And  already have `yabai -m rule --apply` in config file.
And even though excute execute  command in terminal
`manage=off` worked but `sticky=on` not effective. Is this related to SIP status?
My SIP status:
```
# csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
        Apple Internal: disabled
        Kext Signing: disabled
        Filesystem Protections: disabled
        Debugging Restrictions: enabled
        DTrace Restrictions: enabled
        NVRAM Protections: enabled
        BaseSystem Verification: enabled
```

**Comment by txl263** [comment]
Found where the problem is.
Some rules did not take effect because there were some expired settings in the configuration file that were not excluded. It is wrong now, but it does not completely affect the operation, so it is not found.

And about the `sticky=on`. It's SIP relevant.
```
#sudo yabai --load-sa
yabai: System Integrity Protection: Filesystem Protections and Debugging Restrictions must be disabled!
```
Refer to the result `csrutil status` 
`Filesystem Protections: disabled`  ✅
`Debugging Restrictions: enabled`  ❎
This SIP status is related to opencore settings. I need to find  some documents about it.

**Comment by txl263** [comment]
![image](https://github.com/user-attachments/assets/e58d2f46-fcb3-4725-814f-6416abf95d24)
0x80f perfect solution

**Comment by Bellavene** [comment]
Can you give a bit more info please?
