### ISSUE TITLE
auto float some apps/windows

### ISSUE THREAD

**Issue by theonlygusti** [koekeishiya/yabai#25]
This is possible in chunkwm:

    chunkc tiling::rule --owner Preview --state float

Now whenever I open a Preview window it floats.

What's the equivalent for yabai? I couldn't find it by quickly browsing the docs and example dot files.

**Comment by pcr910303** [comment]
@theonlygusti Please see #2, #10, and the Rules section of the docs.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by theonlygusti** [comment]
@pcr910303 ah, I see it in the markdown page. It's not in `man yabai`

**Comment by koekeishiya** [comment]
The man page in this repo is up to date, as it is autogenerated from the asciidoc page. I do a full rebuild every time I make a change. Not sure why the bre installation is unable to update it during an upgrade.

Sent from my iPhone

On 5 Jun 2019, at 01:21, George <notifications@github.com<mailto:notifications@github.com>> wrote:


@pcr910303<https://github.com/pcr910303> ah, I see it in the markdown page. It's not in man yabai

**Comment by dominiklohmann** [comment]
@theonlygusti you probably need to install from `HEAD`, rules are not in the 0.1.0 release. This is also why your man page is not updated.

**Comment by theonlygusti** [comment]
@dominiklohmann thank you
