### ISSUE TITLE
per-window border color to highlight zoomed windows?

### ISSUE THREAD

**Issue by jzelner** [koekeishiya/yabai#251]
I was wondering if it is possible to change the window border color on a per-window basis? I'm hoping to provide some kind of indication that a window is in `zoom-parent` mode, as in #89, but am hoping to change the border color for the zoomed window both when it is active and inactive to replicate some of the behavior of, e.g. a tabbed window, in i3.  

I am currently turning the zoomed window border off on zoom and back on when it is un-zoomed, like so:

`# toggle window parent zoom
alt - d : yabai -m window --toggle zoom-parent;\
          yabai -m window --toggle border`

It works fine enough but I would prefer to be able to either 

1. Just turn *on* a border rather than turning it off, i.e. have all other windows borderless and zoomed ones bordered *or*

2. Change the active and inactive colors of a zoomed window so it is clear even if the window isn't selected. 

Is this possible with any existing yabai actions/queries? If not, would it be possible to add the ability to turn borders on for individual windows and to set border colors window-by-window?

Thanks!

-Jon

**Comment by dominiklohmann** [comment]
This requires a fair bit of work on your end, but it is possible to have borders only for zoomed windows:

- enable borders globally
- create a "catch all" rule that disables borders for all windows
- toggle borders on windows whenever you toggle zoom

**Comment by jzelner** [comment]
Thanks - this seems like a great idea. Any pointers on how to make a catch-all rule? Is there a regex I can use to do that easily? It's been awhile since my Perl days...

**Comment by dominiklohmann** [comment]
```sh
yabai -m rule --add app='.*' border=off
```
