### ISSUE TITLE
[howto] Manage Microsoft Remote Desktop

### ISSUE THREAD

**Issue by webframp** [koekeishiya/yabai#252]
MS Remote Desktop seems completely ignored and does not even appear in the window list when I run `yabai -m query --windows` so it seems like yabai can't see it. Any suggestions?

Here's a screenshot from accessibility inspector hierarchy if it helps:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/774378/64930420-81271d00-d7fe-11e9-85a9-fe81306dd282.png">

**Comment by koekeishiya** [comment]
See my last comment in #249 

You can run yabai with the *--verbose* launch argument and it will log if a process is being ignored.
