### ISSUE TITLE
How to add new items to status bar?

### ISSUE THREAD

**Issue by FrankLA0203** [koekeishiya/yabai#254]
First of all, the status bar in yabai is super cool. But since I was using Ubersicht before hand with a lot of customization with pecan, the information on the status bar seems a bit too little. For example, I would definitely want a WiFi connectivity icon on there.

Has anyone found a way to edit the source code to add new items to the status bar? Or is there a way to configure it in yabai.rc?

**Comment by ThomasF34** [comment]
If i'm not wrong, you can use Ubersicht ( [See wiki here](https://github.com/koekeishiya/yabai/wiki/Configuration#status-bar) ). You'll have to disable the current status-bar in your `.yabairc` file with `yabai -m config status_bar                   off`

**Comment by koekeishiya** [comment]
You can modify the code in `src/bar.c`. More specifically the function `bar_refresh`.

**Comment by FrankLA0203** [comment]
> If i'm not wrong, you can use Ubersicht ( [See wiki here](https://github.com/koekeishiya/yabai/wiki/Configuration#status-bar) ). You'll have to disable the current status-bar in your `.yabairc` file with `yabai -m config status_bar off`

I know that but I just like how yabai has a integrated status bar in it. Plus I really like the style of it. Do you know any Ubersicht template that looks like yabai's status bar and is easily extensible?

**Comment by koekeishiya** [comment]
I made this exact bar in ûbersicht at first, but then all übersicht widgets stopped working after an update, and I couldn't be bothered trying to debug and/or wait for an update to übersicht, so instead I made a version in C integrated with yabai directly.

I no longer have the Übersicht version.

**Comment by tsujp** [comment]
@koekeishiya I take it if we wanted to add a lot more things to the bar we should do it with übersicht or would a PR here be acceptable?

**Comment by koekeishiya** [comment]
I suppose that would depend on what the changes are and how they are made. I prefer the bar to remain simple, so I probably will not accept PRs regarding the bar. It is fairly trivial to edit it in a local fork if you don't want to mess around with Übersicht.
