### ISSUE TITLE
Sticky window is forced to be always on top

### ISSUE THREAD

**Issue by HitoriSensei** [koekeishiya/yabai#255]
`yabai -m window --toggle sticky` makes window stay on all spaces **but also** forces window to be always on top of other windows.

Toggling `float` on a `sticky` window makes no difference.

Is this a bug or a feature?

Is there a way to make a window stay on all spaces and **not** always on top?

**Comment by koekeishiya** [comment]
This is intended. There is option in yabai to make this optional without editing the source code (`src/window_manager.c`).

**Comment by koekeishiya** [comment]
The fact that a sticky window will still become top-most even if `window_topmost` setting is disabled is something that I would consider a bug.

A sticky window however will be treated as floating implicitly, as it makes no sense for it not to be (can't be managed/tiled on multiple spaces simultaneously).

**Comment by HitoriSensei** [comment]
Thank you for the response.

I've briefly checked the code in `src/window_manager.c` as you suggested and if I understand correctly, command `yabai -m window --toggle sticky`
executes `void window_manager_toggle_window_sticky(struct space_manager *sm, struct window_manager *wm, struct window *window)`

Assuming the window is not sticky when called, we are evaluating the following code branch:
```
void window_manager_toggle_window_sticky(struct space_manager *sm, struct window_manager *wm, struct window *window)
{
       ...
        struct view *view = window_manager_find_managed_window(wm, window);
        if (view) {
            space_manager_untile_window(sm, view, window);
            window_manager_remove_managed_window(wm, window->id);
            window_manager_purify_window(wm, window);
        }
        window_manager_make_sticky(window->id, true);
}
```

There are no conditions here for floating and none of the `space_manager_untile_window`, `window_manager_remove_managed_window`, `window_manager_purify_window` trigger window float.

Then the `window_manager_make_sticky(window->id, true);` is called:

```
void window_manager_make_sticky(uint32_t wid, bool sticky)
{
     if (socket_connect_un(&sockfd, g_sa_socket_file)) {
        snprintf(message, sizeof(message), "window_sticky %d %d", wid, sticky);
        socket_write(sockfd, message);
        socket_wait(sockfd);
    }
    socket_close(sockfd);

    if (socket_connect_un(&sockfd, g_sa_socket_file)) {
        snprintf(message, sizeof(message), "window_level %d %d", wid, sticky ? kCGFloatingWindowLevelKey : kCGNormalWindowLevelKey);
        socket_write(sockfd, message);
        socket_wait(sockfd);
    }
}
```

Am I reasoning correctly that
```
snprintf(message, sizeof(message), "window_level %d %d", wid, sticky ? kCGFloatingWindowLevelKey : kCGNormalWindowLevelKey);
```
makes the window top-most?

If yes, then there is no way to prevent floating without code modification because window level parameter `sticky ? kCGFloatingWindowLevelKey : kCGNormalWindowLevelKey` bases only on `sticky` variable.

Is calling the `window_level` with `kCGFloatingWindowLevelKey` parameter needed for stickiness to work?

If not and if the assumptions and reasoning are correct, maybe it would be possible to add a global config option to ignore setting window level together with making it sticky?

**Comment by HitoriSensei** [comment]
I would also like to add, that I don't use any of the awesome tiling features of yabai, I use it only to switch between spaces instantly and make windows stay on all spaces.

Since yabai also supports window floating commang, I would love to use the feature (I currently use Afloat to make windows afloat)

**Comment by HitoriSensei** [comment]
And yes, I am setting the `window_topmost` to `off`:
```
yabai -m config window_topmost off
```

**Comment by koekeishiya** [comment]
Sticky windows no longer become topmost, regardless of whether or not `window_topmost` is enabled or not. Sticky windows will still remain floating, in that they are not tiled.

There is a new option `topmost` availble to the  `window --toggle` command; e.g: `yabai -m window --toggle topmost` that can toggle  topmost for any given window.

There is also a new option available to rules, `topmost=on|off`.

This should allow for greater flexibility for the user in a fairly easy-to-use way.

**Comment by dominiklohmann** [comment]
The window attribute `topmost` is still missing I think. Haven't gotten around to testing it yet, but I don't see it anywhere in the commit. It's necessary with the toggleable attributes so you can selectively turn it on/off for windows from scripts.

**Comment by koekeishiya** [comment]
Good catch, thanks. Added to window queries as well.
