### ISSUE TITLE
Issue on startup

### ISSUE THREAD

**Issue by fuckbitchesgitmoney** [koekeishiya/yabai#257]
hello noob here

how do i fix this please

`yabai: could not locate config file!`

**Comment by pcr910303** [comment]
@fuckbitchesgitmoney As indicated in the error message, you should make a config file and mark it an executable.

For a sample setup: (not tested)
```shellsession
$ mkdir -p ~/.config/yabai
$ curl https://raw.githubusercontent.com/koekeishiya/yabai/master/examples/yabairc > ~/.config/yabai/yabairc
$ chmod +x ~/.config/yabai/yabairc
```

**Comment by fuckbitchesgitmoney** [comment]
im an amateur at this terminal stuff im so sorry but i put in those arguments and the windows rearranged FINALLY i'd practically given up thank you so much. now it says 

`yabai: could not acquire lock-file!`

the README says 

> yabai stores a lock file at /tmp/yabai_$USER.lock to keep multiple instances from launching by the same user
what should i do

**Comment by pcr910303** [comment]
@fuckbitchesgitmoney That (usually) means that more than one instance of `yabai` is running.
Try doing `ps aux | grep yabai` to check if `yabai` is already running, and kill that by running `kill <PID here>`.

For example, if the output is something like this:
![image](https://user-images.githubusercontent.com/37990858/65192892-d6d81f80-dab3-11e9-8fac-aa66af6e833a.png)
you should execute `kill 55004`.
Then remove all of `yabai`'s lockfiles with `sudo rm /tmp/yabai*` and execute `yabai` again.

Actually, if you're not familiar with using shells & terminals, I really wouldn't try using `yabai`.

**Comment by fuckbitchesgitmoney** [comment]
it worked! thank u so much
