### ISSUE TITLE
Window close doesn't work?

### ISSUE THREAD

**Issue by FrankLA0203** [koekeishiya/yabai#258]
From the documentations I saw that you can do `yabi -m window --close` to close a window. But then when I bind that to a key in skhd, nothing happens. When I run the command in terminal it returns `unknown command '--closes' for domain 'window'` error.

How is this supposed to work?

**Comment by dominiklohmann** [comment]
> `unknown command '--closes' for domain 'window'`

Read the error message. You're likely running `yabai -m window --closes` instead of `yabai -m window --close`.

**Comment by FrankLA0203** [comment]
@dominiklohmann my bad, that was a typo. But in the terminal I actually typed `--close` and it gave me `unknown command '--close' for domain 'window'`error.

**Comment by koekeishiya** [comment]
Are you sure you are running version 2.0.0 or 2.0.1? Works fine for me. 
You can check your version by running `yabai --version`

**Comment by FrankLA0203** [comment]
Oh my god for some reason my yabai version is 1.1.2.
Output of command `brew info yabai`
`koekeishiya/formulae/yabai: stable 1.1.2, HEAD
A tiling window manager for macOS based on binary space partitioning.
https://github.com/koekeishiya/yabai
/usr/local/Cellar/yabai/1.1.2 (6 files, 318.1KB) *
  Built from source
From: https://github.com/koekeishiya/homebrew-formulae/blob/master/yabai.rb
==> Requirements
Required: macOS >= 10.13 ✔
==> Options
--HEAD
        Install HEAD version
==> Caveats
Copy the example configuration into your home directory:
  cp /usr/local/opt/yabai/share/yabai/examples/yabairc ~/.yabairc
  cp /usr/local/opt/yabai/share/yabai/examples/skhdrc ~/.skhdrc

Logs will be found in
  /usr/local/var/log/yabai/yabai.[out|err].log

To have launchd start koekeishiya/formulae/yabai now and restart at login:
  brew services start koekeishiya/formulae/yabai
Or, if you don't want/need a background service you can just run:
  yabai`

Where do I get version 2.0.1?

**Comment by dominiklohmann** [comment]
Just `brew update && brew upgrade yabai`, then `brew services restart yabai` (if you're running it as a service).

**Comment by FrankLA0203** [comment]
@dominiklohmann I tried that but it gives me this:
`Error: koekeishiya/formulae/yabai 1.1.2 already installed`

**Comment by FrankLA0203** [comment]
That works! I can't believe I forgot to update brew. Thank you for your help.
