### ISSUE TITLE
[howto] Prevent apps from stealing focus

### ISSUE THREAD

**Issue by dumbbyte** [koekeishiya/yabai#261]
Would it be possible to configure yabai to prevent applications from being able to steal focus?

The Webex Meetings app is particularly obnoxious about stealing focus when people share their desktops during a meeting.

A rule for Webex specifically would be fine, or a general rule that would prevent all apps from stealing focus unless they are explicitly focused by yabai or the mouse would be ideal.

Apologies if this is a duplicate, I did a cursory search and didn't find anything immediately useful.

Thanks for any information/guidance!

**Comment by koekeishiya** [comment]
I don't think this is possible to do. At the very least you'd have to hook the call to `_SLSSetFrontProcessWithOptions` implemented in the SkyLight.framework used by the WindowServer.

**Comment by dumbbyte** [comment]
That's a shame, but thank you for the response and insight :)

**Comment by dominiklohmann** [comment]
You can always hook into the `event=window_focused` signal for that app and then focus the most recently focused window again. This won't prevent it from stealing focus, but it will immediately switch the focus back to the previously focused window.

**Comment by lmartins** [comment]
Think I'm seeing a related issue, where I have a code editor and a browser open. Saving changes in the editor causes the browser to refresh and unlike before the browser always steals focus at each reload.
