### ISSUE TITLE
Yabai SA crashes Dock (possibly)

### ISSUE THREAD

**Issue by CanonyEvo** [koekeishiya/yabai#262]
It seems that `yabai`'s scripting addition crashed my Dock. It cannot be restarted, nor is it repaired through disabling `yabai`, uninstalling the SA and reinstalling the OS with internet recovery.

When running
`/System/Library/CoreServices/Dock.app/Contents/MacOS/Dock`
in terminal, the following is printed:

```
2019-09-21 23:21:57.233 Dock[1294:12918] -[__NSCFString unsignedIntValue]: unrecognized selector sent to instance 0x7fda0948da00
2019-09-21 23:21:57.233 Dock[1294:12918] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString unsignedIntValue]: unrecognized selector sent to instance 0x7fda0948da00'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff521812fd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7c851a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff521fb106 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff5212318f ___forwarding___ + 1485
	4   CoreFoundation                      0x00007fff52122b38 _CF_forwarding_prep_0 + 120
	5   Dock                                0x000000010e3e83fe Dock + 50174
	6   Dock                                0x000000010e3e7f1f Dock + 48927
	7   Dock                                0x000000010e3e79b1 Dock + 47537
	8   Dock                                0x000000010e3e536d Dock + 37741
	9   Dock                                0x000000010e3e3b9d Dock + 31645
	10  Dock                                0x000000010e56acb1 Dock + 1633457
	11  Dock                                0x000000010e56bb1e Dock + 1637150
	12  libswiftObjectiveC.dylib            0x00007fff7dd2ef4f $s10ObjectiveC15autoreleasepool8invokingxxyKXE_tKlF + 47
	13  Dock                                0x000000010e3e1736 Dock + 22326
	14  libdyld.dylib                       0x00007fff7e01f3d5 start + 1
	15  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    1294 abort      /System/Library/CoreServices/Dock.app/Contents/MacOS/Dock
```

I am running macOS 10.14.6 on a mid 2015 15" RMBP (without dock, wallpaper, or launchpad etc.) rightnow

I really hope it is not `yabai`'s fault, otherwise I made a fool of myself for not foreseeing the risk thereof (I did run `chunkwm` for a while and loved it).

Any help is greatly appreciated.

**Comment by koekeishiya** [comment]
> It cannot be restarted, nor is it repaired through disabling yabai, uninstalling the SA and reinstalling the OS with internet recovery.

yabai does nothing to modify the on-disk binary of the Dock or anything thereof. It simply injects code through the scripting-bridge framework into a running instance of the Dock. I have never seen this kind of a crash before. Nothing yabai does should persist through a restart of the Dock, re-log of the current user session, let alone a full OS reinstall.

I don't have any tip for what you can do to further debug your issue.

**Comment by CanonyEvo** [comment]
@koekeishiya does SIP protects the Dock? Could it be some malware that has tampered with it?

I apologize for getting the discussion out of the scale of `yabai`

**Comment by CanonyEvo** [comment]
It seems that the `desktoppicture` database is corrupted. Can be fixed by

```bash
rm ~/Library/Application\ Support/Dock/desktoppicture.db
```
