### ISSUE TITLE
Chrome Apps Freeze

### ISSUE THREAD

**Issue by jbharat** [koekeishiya/yabai#263]
I use google calendar and there is no mac app for google calendar. But chrome provides a way to create your own chrome apps. Open calendar in browser, go to More Tools and create shortcut. Give a name and select open as window. Now you can open the calendar app you just created. 

When yabai is running opening chrome apps hangs chrome. 
[yabai-chromeapp.log](https://github.com/koekeishiya/yabai/files/3650633/yabai-chromeapp.log)

Stopping yabai service and opening the same chrome app works perfectly.

yabai: v2.0.1 (sa installed)
OS: 64bit Mac OS X 10.14.6
Chrome: Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by dominiklohmann** [comment]
Duplicate of #204

**Comment by jbharat** [comment]
I can close this and attach the log info to #204
