### ISSUE TITLE
Transparency for specific applications

### ISSUE THREAD

**Issue by nraiha** [koekeishiya/yabai#264]
Is it possible to set specific applications, like terminal or spotify, to be transparent?

**Comment by koekeishiya** [comment]
You can set the opacity for a given window using the rules system: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule

**Comment by horumyy** [comment]
is there a way to have a specific rule for opacity on a certain window when having a global configuration for the rest?
```
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
```

this is in my `yabairc` file, but I want vscode to have transparency even if its active
