### ISSUE TITLE
Allow windows to span multiple displays

### ISSUE THREAD

**Issue by gibfahn** [koekeishiya/yabai#265]
I see from https://github.com/koekeishiya/yabai/issues/193 and the readme that you need to enable the "Displays have separate spaces" option.

Unfortunately the only way to have a single window spanning multiple monitors in vanilla macOS is to disable this setting (see e.g. [1](https://discussions.apple.com/thread/5523369), [2](https://apple.stackexchange.com/questions/114449/macosx-maverick-10-9-how-do-i-stretch-a-window-across-both-of-my-dual-screens/114450), [3](https://apple.stackexchange.com/questions/106541/mavericks-window-across-multiple-monitors)).

Is it possible to have a window spanning multiple displays in yabai? My guess would be that this is something macOS would have to add support for.

**Comment by dominiklohmann** [comment]
This is simply not feasible.
