### ISSUE TITLE
Is over git lfs data quota

### ISSUE THREAD

**Issue by pangliang** [koekeishiya/yabai#269]
$ git clone https://github.com/koekeishiya/yabai.git
正克隆到 'yabai'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 3094 (delta 18), reused 46 (delta 9), pack-reused 3025
接收对象中: 100% (3094/3094), 1.04 MiB | 579.00 KiB/s, 完成.
处理 delta 中: 100% (2324/2324), 完成.
Downloading assets/banner/banner.png (8.1 KB)
Error downloading object: assets/banner/banner.png (8eae42d): Smudge error: Error downloading assets/banner/banner.png (8eae42d7c59fd4db2bb6659eac400b1d8ccc8bfd76df7780461e4838f133201b): batch response: This repository is over its data quota. Purchase more data packs to restore access.

**Comment by dominiklohmann** [comment]
Ah god damn it, I forgot to remove it. Will be fixed within 10 mins.

**Comment by dominiklohmann** [comment]
Fixed. Closing this issue.
