### ISSUE TITLE
Window rules: space/display + fullscreen ordering

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#27]
Example rules:

```sh
yabai -m rule --add app=<app name> display=2 fullscreen=on
yabai -m rule --add app=<app name> space=3 fullscreen=on
```

These rules need to apply fullscreen after their other functionality. For display the reason should be obvious, for space it is so that when I remove the window from fullscreen it goes back to the desired space.

Additional nit: the `fullscreen` option should be labelled `native-fullscreen` like everywhere else.

**Comment by koekeishiya** [comment]
Fairly certain that is the order it is happening in now, but it is probably a case where some internal state in Dock is not updated. Will likely have to inspect the Dock some more to fix this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dominiklohmann** [comment]
Just had a look at the code. Order is definitely right, but I bet the control returns to the caller before the move actually happens.

Also if I change the rule to move to space/display and follow it works, so maybe following should just be implied for fullscreen rules?

**Comment by koekeishiya** [comment]
This is not a timing issue. Confirmed by simply running notes and terminal on the same space. Issue the command `yabai -m window --space 7`. Window gets untiled, moved etc.. wait for whatever amount of time, hit my bind in *skhd* that toggles native-fullscreen for the active window. The active window is still terminal. Notice terminal getting moved back to the active space my monitor before entering the fullscreen animation.

I tried to get focus on a window on an inactive space without using the move function of *yabai*, but was unable to do so. I think this may actually just be an unintended side of macOS. It was clearly not intended to be able to have the key-window be on an inactive space. The proper solution would fix both of these scenarios, not just the one observed through the effects of a rule.

**Comment by koekeishiya** [comment]
I decided to solve this issue using the solution you proposed. The focus issue I mentioned in my previous comment can be dealt with separately. Also renamed *fullscreen* to *native-fullscreen*.

**Comment by dominiklohmann** [comment]
Seems to work.

> Also renamed _fullscreen_ to _native-fullscreen_.

You forgot docs + manpage here.

**Comment by koekeishiya** [comment]
> You forgot docs + manpage here.

Thanks, fixed.
