### ISSUE TITLE
Rule to float all Preference Windows?

### ISSUE THREAD

**Issue by karbecker** [koekeishiya/yabai#272]
Hi, would it be possible to have a rule that matches all regular preference windows Apps spawn? The problem is that they don’t all have the same title, for example

ForkLift Preferences:

![Screenshot](https://user-images.githubusercontent.com/8436596/66381681-1068c000-e9ba-11e9-891b-c9d583cd8802.png)

Finder Preferences:

![Screenshot 1](https://user-images.githubusercontent.com/8436596/66381687-1494dd80-e9ba-11e9-8c65-dd961401b7f6.png)

Thanks!

**Comment by dominiklohmann** [comment]
This would match all windows whose title ends in `Preferences` and make them float and topmost.

```sh
yabai -m rule --add title='Preferences$' manage=off topmost=on
```

**Comment by karbecker** [comment]
Thanks, this works fine for most preference Windows (those who have it in their title 😉)

**Comment by 4volodin** [comment]
> This would match all windows whose title ends in `Preferences` and make them float and topmost.
> 
> ```shell
> yabai -m rule --add title='Preferences$' manage=off topmost=on
> ```

it is not working

**Comment by prdanelli** [comment]
I'm seeing the same thing, that the `Preferences` is not currently working. 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1199977/172055518-25fe94a8-6619-44aa-b29d-e10b68791387.png">

**Comment by williamhCode** [comment]
change topmost=on to layer=above or delete it. works for me

**Comment by prdanelli** [comment]
Thank you @williamhCode! 🎉
