### ISSUE TITLE
Question: Is it possible to navigate windows in Mission Control?

### ISSUE THREAD

**Issue by Tylerc230** [koekeishiya/yabai#273]
I'd like to be able to use the arrow keys to focus different windows in mission control (moving north, south, east, west). I know macos doesn't provide keybindings for this. Is it possible to implement with yabai?

**Comment by dominiklohmann** [comment]
The tricky part about this isn't focusing the windows, but making the keyboard shortcuts available only while Mission Control is active.

Here's a three-step solution:
- Create a signal for `event= mission_control_enter` that creates a file containing your keyboard shortcuts  to be used by `skhd` (e.g., `~/.config/yabai/mission-control.skhd`)
- Create a signal for `event=mission_control_exit` that empties that file.
- Hotload the temporary file in your `skhdrc` file using `.load ~/.config/yabai/mission-control.skhd`. 

The keyboard shortcuts going into that temporary file should be something like this.

```
up : yabai -m window --focus north
```

Note though that `north` here means northward of the currently focused window as if it was still tiled and only focuses other tiled windows. Mission Control doesn't actually change the windows position and size, but rather applies a visual transformation to all windows. This will work best with *Group windows by application* being disabled in the Mission Control preferences.

If you want to include floating windows in your focus cycle, I encourage you to use a mix of window queries and `jq` filters for doing your own logic. The below might serve as inspiration.

```
shift - tab : yabai -m query --spaces | jq -re ".[] | select(.visible == 1).index" | xargs -I{} yabai -m query --windows --space {} | jq -sre "add | sort_by(.display, .frame.x, .frame.y, .id) | nth(index(map(select(.focused == 1))) - 1).id" | xargs -I{} yabai -m window --focus {}
tab : yabai -m query --spaces | jq -re ".[] | select(.visible == 1).index" | xargs -I{} yabai -m query --windows --space {} | jq -sre "add | sort_by(.display, .frame.x, .frame.y, .id) | reverse | nth(index(map(select(.focused == 1))) - 1).id" | xargs -I{} yabai -m window --focus {}
```

**Comment by Tylerc230** [comment]
Great I didn't realize I could use --focus to navigate mission control. The blue mission control border/highlight doesn't show up on the mission control thumbnails but not a big issue. Thanks!

**Comment by dominiklohmann** [comment]
@Tylerc230 if you enable *mouse follows focus* you'll get the blue borders as well. You can enable it in the `event=mission_control_enter` signal and disable it again in the `event=mission_control_exit` signal if you don't want to use it all the time.
