### ISSUE TITLE
Migration Guide: macOS 10.15 Catalina

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#275]
### Migration Guide

macOS 10.15 Catalina is now available and there are a few things to note when using yabai on Catalina.

#### Known Bugs

- #277 **IMPORTANT:** Disable `window_opacity` for now, as the window server crashes completely on wake when window opacity was previously changed (`yabai -m config window_opacity off`). 
- ~#276 There is a totally random crash happening in `processEventTapData`. It's harmless, but yabai might restart once a week or so.~
- ~#278 Window titles can no longer be read using the private function used previously. A fix for this has been implemented on the master branch, but has not yet been released.~

#### Before Updating

- Make sure to update yabai to the latest release (≥2.0.1)
- If you're using the scripting addition, make sure to reinstall it (`sudo yabai --install-sa`). If you have not done this in a while, note that the path for the scripting addition has changed from `/System/Library/ScriptingAdditions` to `/Library/ScriptingAdditions` in preparation for Catalina a while back.

**Comment by babygau** [comment]
I thought #276 has been fixed already

**Comment by dominiklohmann** [comment]
> I thought #276 has been fixed already

There hasn't been a new release yet since that change was made.

**Comment by babygau** [comment]
@dominiklohmann oh, my bad, :sweat_smile:

**Comment by koenhendriks** [comment]
I'm having the following issue on `10.15.1`

`yabai-msg: failed to connect to socket..`

I installed using homebrew:
`brew install --HEAD yabai`

and run `sudo yabai --install-sa`

Any tips on what I'm missing? i tried `brew services restart yabai`

**Comment by koekeishiya** [comment]
> Didn't work because of a missing config file ~/.config/yabai/yabairc, leaving this for reference.

This is no longer a requirement in v2.2.3 and newer.

**Comment by OJFord** [comment]
In case it helps anyone else searching for an issue - after upgrading 10.15.3 -> 10.15.4 I found that moving a window to a different space, e.g.:
```
$ yabai -m window --space  1
```

worked, but switching space, e.g.:
```
$ yabai -m space --focus 1
```

did not.

Reinstalling the scripting additions with:
```
$ sudo yabai --install-sa
```

fixed it.

**Comment by FinnFrotscher** [comment]
thx

**Comment by nuynait** [comment]
> In case it helps anyone else searching for an issue - after upgrading 10.15.3 -> 10.15.4 I found that moving a window to a different space, e.g.:
> 
> ```
> $ yabai -m window --space  1
> ```
> 
> worked, but switching space, e.g.:
> 
> ```
> $ yabai -m space --focus 1
> ```
> 
> did not.
> 
> Reinstalling the scripting additions with:
> 
> ```
> $ sudo yabai --install-sa
> ```
> 
> fixed it.

When I reinstall it says payload doesn't support this macOS version. I guess I might need an upgrade?

**Comment by dominiklohmann** [comment]
I'm unpinning this to make room for the Big Sur thread. Nothing much has come up here for a while, so I think this can be considered done.

**Comment by rohni** [comment]
FYI: I just wanted to add that for my upgrade from 10.15.6 -> 10.15.7 (I'm avoiding Big Sur :-)) I had exactly the same problem which was solved as above with the 
```
sudo yabai --install-sa
```

**Comment by rigarcia** [comment]
How do I install Yabai on Catalina? I get this error when trying to install.

yabai: This software does not run on macOS versions older than Big Sur.
Error: yabai: An unsatisfied requirement failed this build.

**Comment by 24unix** [comment]
> yabai: This software does not run on macOS versions older than Big Sur.

What is so unclear on that sentence?

Catalina: macOS 10.15
Big Sur: macOS 11

11 is greater than 10. Just go to the control center and make an update, if your Mac is too old, try OpenCore.
