### ISSUE TITLE
Increase `EVENT_HANDLER_WINDOW_MOVED` frequency for window drawing speed/efficiency(?)

### ISSUE THREAD

**Issue by tsujp** [koekeishiya/yabai#279]
My C is a bit rusty and I have had a cursory look through event.c and border.c as well as using yabai with verbose mode on and I see that `EVENT_HANDLER_WINDOW_MOVED` comes in at a steady rate no matter how fast the window is moving, would this be some API limitation or debouncing within Yabai (as I am still looking).

I'd like to experiment with increasing this if possible so if I am moving a floating window then window borders stick more closely to them.

Here's a video of what I mean (the GIF makes the framerate look weird, here's an MP4 for smoother viewing: https://i.imgur.com/hb0ZZP4.mp4)

![video](https://i.imgur.com/4mGMXfE.gif)

**Comment by koekeishiya** [comment]
This is a limitation of the *macOS Accessibility API*. Same thing applies to tracking when a window is resized.

**Comment by dominiklohmann** [comment]
The underlying limitation is that the borders are currently drawn as a view on a separate overlay window, which is redrawn when a *window moved* event comes in. You'd have to rework the border code so it draws its view on the target window itself. This is not an easy task.

As an alternative, you might wanna look into not rendering borders for windows that are currently moving: Measure the mean time delta between window moved events, then stop drawing borders until a timer using that delta expires, and refresh the timer whenever a window moved event comes in.

**Comment by koekeishiya** [comment]
> You'd have to rework the border code so it draws its view on the target window itself. This is not an easy task.

You could likely grab the current context of any window (through the scripting-addition), but every time that window is repainted due to some internal changes, our border would disappear. By reusing the same context we would likely occlude parts of the actual window as well - it would be an internal border, rather than external as it is now.

**Comment by tsujp** [comment]
I figured it might be something external, all I was looking for in the code was some kind of hardcoded tick rate and when I didn't see that and saw `EVENT_HANDLER_WINDOW_MOVED` coming in regular intervals no matter how fast or slow I spazzed the window I felt it must've been something external.

@koekeishiya gotcha, shame it's limited so much from macOS's side.

@dominiklohmann sounds like a good enough approach to me as in all other situations apart from floating windows I almost never (99% of the time I never) see a window border lagging.

**Comment by tsujp** [comment]
> > You'd have to rework the border code so it draws its view on the target window itself. This is not an easy task.
> 
> You could likely grab the current context of any window (through the scripting-addition), but every time that window is repainted due to some internal changes, our border would disappear. By reusing the same context we would likely occlude parts of the actual window as well - it would be an internal border, rather than external as it is now.

@dominiklohmann @koekeishiya would a semi-sane alternative to an outside border rendering as-fast-as-possible be to modify the SystemAppearance.bundle with Yabai such that active windows have custom assets which render a border? I don't know if it would be possible but in the asset files I was digging around in today there are a lot of shadows etc which means there might at least be some assets that bleed over the visible-content (for lack of a better term) of the window. That is the Finder window has it's view, and then the shadow that extends past it.

Tangentially today I've spent my time modifying the asset files to make window edges square instead of rounded; most of my time was spent looking for the damn files responsible hence I saw a few shadows; here's the repo: https://github.com/tsujp/square-macos-windows

Linking it because _if_ this sounds like a semi-sane approach then the base information there might prove useful.

**Comment by dominiklohmann** [comment]
> semi-sane approach

This sounds like it's a stupid amount of work to maintain. But if you're doing this externally anyways, feel free to add borders to your custom appearance files and link them somewhere here. 

The main issue is that some applications don't respect the system appearance (FireFox, Kitty, older Electron apps etc.). 

Just do something like this:

```sh
# if you have ffm disabled
yabai -m signal --add event='mouse_down' action='yabai -m window --toggle border'
yabai -m signal --add event='mouse_up' action='yabai -m window --toggle border'

# if you have ffm set to autofocus (adapt slightly for autoraise)
yabai -m signal --add event='mouse_down' action='yabai -m config focus_follows_mouse off; yabai -m window --toggle border'
yabai -m signal --add event='mouse_up' action='yabai -m window --toggle border; yabai -m config focus_follows_mouse autofocus'
```

**Comment by tsujp** [comment]
> The main issue is that some applications don't respect the system appearance (FireFox, Kitty, older Electron apps etc.).

Coming back to this now I think you're right, that would be a right pain in the ass to maintain files for actually. An the whole insert border colour, I don't know how that'd even be done in that now ~semi~in-sane approach.

A-ha! That's why Firefox won't budge, my god what a pain in the ass that's been. Kitty is fine because it's square anyway. I wonder how I can force Firefox to behave nicely now too, the journey just keeps on going.
