### ISSUE TITLE
Some window resizes are being ignored

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#28]
Reproducible with iTerm2 and Terminal: window resizes triggered through <kbd>command</kbd><kbd>+</kbd> or <kbd>command</kbd><kbd>-</kbd> are not picked up properly.

Temporary workaround: Toggle padding/gaps twice.

**Comment by koekeishiya** [comment]
You can toggle the window border as well, if borders are enabled. 

We simply don’t respond to moved/resized events at this time. I’m not yet sure how to solve this problem, because it needs to not interfere with the mouse support.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marcelja** [comment]
For iTerm2: In preferences --> general --> window:

`Adjust window when changing font size` could be disabled.

**Comment by dominiklohmann** [comment]
I'm closing this. I feel like I only created this issue because I was expecting yabai to work too much like chunkwm in some regards. The tip given by @marcelja fixes the biggest issue for me—thanks!
