### ISSUE TITLE
`window_border_radius` config to Yabai

### ISSUE THREAD

**Issue by tsujp** [koekeishiya/yabai#281]
Issue for PR: https://github.com/koekeishiya/yabai/pull/280

Adds functionality to define a custom `window_border_radius`, including none, as well as the option to continue to use the automatic radius determination Yabai currently provides.

## List of changes:

* Adds new `config` message `window_border_radius`, e.g. `yabai -m config window_border_radius 0`
* Valid values for `window_border_radius` are as follows:
  * `-1` to use Yabai's current auto-radius functionality.
  * `0 ... 20` to set the radius accordingly (zero to twenty).

## In-action:

![window_border_radius](https://i.imgur.com/kBV1ic4.gif)

## Changelog text:

```
### Added
- *window_border_radius* config message [#281](https://github.com/koekeishiya/yabai/issues/281)
```

**Comment by WarmlindAlbin** [comment]
How would i go about updating to this? I tried brew upgrade yabai and everything worked out. But when i try to enter the command it just says unknown command 'window_border_radius' for domain 'config'

Im on latest mojave version.

**Comment by tsujp** [comment]
@WarmlindAlbin This is part of `master` but not part of a release build yet, as such you can still use homebrew as follows:

```
brew unlink yabai
brew install --HEAD yabai
```

This will install `yabai` from the last commit (HEAD) of the currently checked out branch (default is `master`).

**Comment by pcr910303** [comment]
@tsujp Just for completeness, one also has to restart the `yabai` service.

```shell
brew services stop yabai && brew unlink yabai && brew install --HEAD yabai && brew services start yabai
```
