### ISSUE TITLE
Unresponsive window resize for Kitty

### ISSUE THREAD

**Issue by tsujp** [koekeishiya/yabai#282]
I'm not sure what's causing this but Firefox seems to respond to resizing fairly quickly (lags a little bit more due to the recording) but Kitty takes a while to be resized after the mouse is released as I demonstrate by wiggling it around showing I am not still holding left-click.

At the end of the GIF it seemed to just autosnap back to equal sharing space despite me doing nothing but releasing the mouse. It's unclear in the GIF too but the `EVENT_HANDLER_WINDOW_RESIZED: kitty 358` is being spammed until the moment it changes size; in the GIF it looks like the text is only standing still.

Demonstration: https://i.imgur.com/wFih1UU.mp4 or as a GIF https://i.imgur.com/wFih1UU.gif

![gif](https://i.imgur.com/wFih1UU.gif)

**Comment by dominiklohmann** [comment]
I don't think this belongs on this issue tracker, unless you noticed that the resize is substantially slower only when yabai is running. Some applications just take their time in the window resized event handler (text reflow is usually quite slow).

**Comment by koekeishiya** [comment]
Kitty resizes almost instantaneously for me, regardless of how many windows I have open. I am running an older version though, as I didn't see much need to update.
