### ISSUE TITLE
macOS Catalina: Scripting Addition fails to load

### ISSUE THREAD

**Issue by Hum4n01d** [koekeishiya/yabai#283]
![image](https://user-images.githubusercontent.com/17228477/66868697-a7052600-ef52-11e9-9716-d88593526c3c.png)

I am on macOS Catalina 10.15 (19A583) using yabai-v1.1.2. I turned off SIP in recovery mode and restarted before re-installing the scripting addition. 

I am trying to use the scripting addition to switch spaces.

**Comment by koekeishiya** [comment]
1.1.2 was a long time ago, and I don't think Catalina was a thing back then. Use version 2.0.1 or build from the master branch instead.

**Comment by Hum4n01d** [comment]
I ran `brew install yabai` again before making the issue and it seemed like it updated but maybe I should try updating to git master

**Comment by dominiklohmann** [comment]
You need yabai ≥2.0.1 on Catalina, and current master to avoid the window title bug. Just `brew upgrade yabai`, followed by `sudo yabai --install-sa` and `brew services restart yabai`.

**Comment by Hum4n01d** [comment]
That worked! Thank you!
