### ISSUE TITLE
Status bar on both screens

### ISSUE THREAD

**Issue by matthiasbe** [koekeishiya/yabai#292]
Thanks for this project, and for adding the status bar.

I have 4 virtual spaces
* 2 on the primary screen
* 2 on the secondary screen

In my case the status bar is only displayed on the primary screen (containing only the two spaces)

Is it possible to use the status bar to know which space is active on the secondary screen ?

**Comment by Guisanpea** [comment]
Take a look to this issue https://github.com/koekeishiya/yabai/issues/136

**Comment by matthiasbe** [comment]
It seems I haven't searched thoroughly enough.
Thank you for the pointer.
