### ISSUE TITLE
Status bar installation (Confused)

### ISSUE THREAD

**Issue by Hairylon** [koekeishiya/yabai#293]
Hello all, 

I do apologies if I'm being stupid here. 

Anyway, I went to https://github.com/felixhageloh/uebersicht and installed it. but, I have a yabairc file that is this https://github.com/koekeishiya/yabai/blob/master/examples/yabairc. I went to chmod the file then run it. but, I'm getting this error

> unknown command 'window_border_placement' for domain 'config'
unknown command 'window_border_radius' for domain 'config'
unknown command 'active_window_border_topmost' for domain 'config'
yabai configuration loaded..

**Comment by dominiklohmann** [comment]
The example configuration you’re using is for current master, which is the development version. Use the file that comes with your Homebrew installation instead—`brew Info yabai` lists it under the caveats section.

**Comment by Hairylon** [comment]
I've cp the file then did a restart but, no effect has happened. Am I missing something or, is that file suppose to be there then, I grab a status bar and toss that into the widgets?

**Comment by dominiklohmann** [comment]
Well, Übersicht is just a tool that can show whatever you want on your desktop, e.g. output generated by yabai. The yabai status bar is a feature that is totally unrelated. It's baked into yabai and can be enabled from the configuration file.

**Comment by Hairylon** [comment]
I'm just installing what ever till I fully understand it and, do a re-install.

I just ran the file again but, display those 3 errors. (Kinda lost)

**Comment by Hairylon** [comment]
Ah, got it working. You have the show status bar off :/. Just changed it to on and worked. 3 errors thou

**Comment by koekeishiya** [comment]
You don't need ubersicht installed to use the built-in yabai status bar. It does the window creation and drawing all by itself.
