### ISSUE TITLE
Rule for iOS Simulator to keep floating

### ISSUE THREAD

**Issue by ubuntudroid** [koekeishiya/yabai#294]
I've added the following rule to `.yabairc` to keep the iOS Simulator windows floating:

```
yabai -m rule --add app="^Simulator" manage=off
```

However for some reason the Simulator is still tiled. I've also tried different app regexes like `^Simulator$` or `Simulator`, but to no avail.

Simulator window information:
```
{
  "id": 31707,
  "pid": 43642,
  "app": "Simulator",
  "title": "",
  "frame": {
    "x": 1282,
    "y": 2,
    "w": 472,
    "h": 936
  },
  "level": 0,
  "role": "AXWindow",
  "subrole": "AXStandardWindow",
  "movable": 1,
  "resizable": 0,
  "display": 1,
  "space": 1,
  "visible": 1,
  "focused": 0,
  "split": "vertical",
  "floating": 0,
  "sticky": 0,
  "border": 1,
  "shadow": 1,
  "zoom-parent": 0,
  "zoom-fullscreen": 0,
  "native-fullscreen": 0
}
```

**Comment by dominiklohmann** [comment]
This works for me. Are you sure you've restarted yabai (your yabairc is just a file that yabai executes on startup).

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/4488655/67619237-4fd83e80-f7f9-11e9-8d06-db106b96a368.png">

**Comment by ubuntudroid** [comment]
Ha, I actually did restart yabai multiple times, but what I didn't do was restarting the simulator. For some reason it only worked after I did that - but now it works brilliantly every time! Thanks a lot @dominiklohmann !

**Comment by ubuntudroid** [comment]
Side note: interestingly enough sometimes the simulator out of the blue becomes tiled again. Didn't find a pattern yet. Restarting the simulator helps then.

**Comment by danielakl** [comment]
@ubuntudroid One scenario where the Simulator would become tiled again is when for whatever reason yabai would crash and automatically restart.

**Comment by ubuntudroid** [comment]
@danielakl I'm pretty sure that didn't happen here. However, if it did: why would it tile again then? Shouldn't the rules be applied after a restart of yabai as well?

**Comment by dominiklohmann** [comment]
> Shouldn't the rules be applied after a restart of yabai as well?

The yabairc file is executed asynchronously, so what you're really asking for is for rules to be applied when added.

**Comment by koekeishiya** [comment]
A rule is applied to existing windows when it is added. If there is some effect of a rule that does not apply to an existing window, that should be considered a bug. If you have steps to reproduce such a scenario, please create a new issue for that.

**Comment by ubuntudroid** [comment]
Thanks everyone, will monitor this and report back once I have found a way to reproduce reliably. :)
