### ISSUE TITLE
Rule question

### ISSUE THREAD

**Issue by Cowboy-coder** [koekeishiya/yabai#296]
Is it possible to move a app to a specific space but if the space doesn't exist it first creates it and then moves it?

```
yabai -m rule --add app=Spotify space=6
```

So I want Spotify always on space 6, but if I currrently only have 3 spaces then it will create `4`, `5` and `6` before it sends Spotify to `space 6`?

**Comment by dominiklohmann** [comment]
You can quite easily do this with actions. When Spotify launches, query for all window ids belonging to the app with the same pid. Then, if there are not enough non-fullscreen spaces on the current display, create spaces until you have just enough. You can then move the window(s) to the target space by their id.
