### ISSUE TITLE
Navigate spaces on same display

### ISSUE THREAD

**Issue by lesteenman** [koekeishiya/yabai#303]
Is it possible to use `yabai -m space --focus` to go to the next space on the same display easily? Or will I have to write a query to list all spaces on that display, and find the previous or next one manually?

I'm doing something similar with querying to select the space before the one I'm closing rather than the first one on the display, and it feels rather slow. So if there's a 'native' way to approach this, that would be great.

The goal I have is to have 3 levels of navigation: one set of buttons to focus a specific display, another to navigate between spaces on that display, and a third set to navigate windows on the selected space. The current behaviour for spaces causes me to toggle between displays when going `--focus prev` and `--focus next`, however, which would force me to remember indices of the spaces on the various displays.

**Comment by dominiklohmann** [comment]
This does what you want.

```sh
yabai -m space --focus "$(yabai -m query --spaces --display \
    | jq 'reverse | nth(index(map(select(.focused == 1))) - 1).index')"
```

I use `reverse` and `-1` to get wraparound for free. If you don't want wraparound, the script is quite easy to adapt.

**Comment by qns7** [comment]
I found this awesome solution: https://medium.com/@frigaut/better-multi-display-space-switching-with-yabai-829343241b97
