### ISSUE TITLE
Caprine marked as agent sometimes

### ISSUE THREAD

**Issue by alok** [koekeishiya/yabai#304]
I use [Caprine](https://github.com/sindresorhus/caprine) and sometimes it gets marked as an agent and is ignored for tiling. I'm not why it does that, but restarting yabai fixes it until I close and reopen Caprine, though that's obviously not ideal.

**Comment by mstr3336** [comment]
seconded! I just had this problem

**Comment by koekeishiya** [comment]
So in yabai I use the following function `ProcessInformationCopyDictionary(&psn, kProcessDictionaryIncludeAllInformationMask);` to retrieve information about the process, and macOS reports it as an agent application: https://developer.apple.com/documentation/bundleresources/information_property_list/lsuielement?language=objc

**Comment by koekeishiya** [comment]
I've made some changes on the latest master (#529) that might resolve this issue with Caprine. Would you mind trying that and reporting back? Thanks.

**Comment by alok** [comment]
Fixed
