### ISSUE TITLE
Window painting over border when clicked on

### ISSUE THREAD

**Issue by chris-kahn** [koekeishiya/yabai#310]
When I hover over a window the border appears as usual. However, when I click on the window or interact with it somehow, it seems that the window repaints over the border and looks smaller.

This only started happening after I upgraded from `bf3a656` to new commit `3e99cee`.

![funnyborders](https://user-images.githubusercontent.com/16520875/68669533-af955000-0542-11ea-814e-01025d5152cd.gif)

**Comment by koekeishiya** [comment]
Add `yabai -m config window_border_topmost 1` to get back the old behaviour.

**Comment by lvadla** [comment]
Does `yabai -m config active_window_border_topmost on` require SIP to be off?

**Comment by koekeishiya** [comment]
This setting no longer exists. It was a part of the border implementtatio back in version 2.x.x.
In the latest version (3.x.x), window borders require sip to be disabled.

**Comment by braham-snyder** [comment]
I ran into a bug that was at least superficially similar, after updating to Big Sur, but seem to have fixed it.

In my case, I think I could only see the borders at the four corners of each window. I'm also not sure what was causing the broken border state, but it seemed to persist until restarting `yabai`, then inevitably come back after a little while.

I think there's some chance uncommenting the two lines at the top of `.yabairc` for Big Sur (to load the scripting addition), plus an additional `yabai` restart, is what fixed it.

**Comment by isaiahtaylor** [comment]
In case it's helpful to anyone, I'm on Big Sur and also had the issue of borders being behind windows once you click on them. The "top two lines" @braham-snyder is talking about are these:

```bash
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
```

Adding these to my yabairc fixed the issue for me!
