### ISSUE TITLE
Too many workspaces causes crash 

### ISSUE THREAD

**Issue by vanderpot-uber** [koekeishiya/yabai#313]
When the status bar is enabled, having many (tested with 30) workspaces on one display causes a crash loop.

I believe this bug was introduced in b063ce162ec1f103fdb09d6385b4df09d64a8e9b.
I noticed this after upgrading from 2.0.1 to 2.1.2.
```
$ brew upgrade yabai
==> Upgrading 1 outdated package:
koekeishiya/formulae/yabai 2.0.1 -> 2.1.2
```

**Comment by koekeishiya** [comment]
Resolved on master.
