### ISSUE TITLE
Right click menu in firefox opening on different display and behind other windows

### ISSUE THREAD

**Issue by mackeyja92** [koekeishiya/yabai#314]
When right clicking in Firefox developer edition the menu opens up behind another window on another display. It's also really small when it does come up and I am not able to move my mouse to it (ffm) which closes the window. I have use mission control to get it visible then use my arrow keys to open what I want. I don't have this issue in chrome.

<img width="236" alt="image" src="https://user-images.githubusercontent.com/10620022/68903604-e319db00-06f8-11ea-8b6d-aeef0bd26699.png">

The issue existed in 2.0.1 and is still present in 2.1.2

**Comment by koekeishiya** [comment]
This sounds like a bizarre issue caused by Firefox incorrectly using the AXStandWindow role-attributes for their menus.

**Comment by dominiklohmann** [comment]
I cannot reproduce this. Do you have any rules configured that affect FireFox?

<div align="center">
<img width="80%" alt="image" src="https://user-images.githubusercontent.com/4488655/69870518-741fb300-12b0-11ea-8c0c-cbd080d025f5.png">
</div>

**Comment by mackeyja92** [comment]
@dominiklohmann Ok, so it is now showing the right size on the latest version of firefox. But it is still showing up on the wrong display and behind other windows. I do not have any custom rules regarding FF in my yabairc file.

**Comment by mackeyja92** [comment]
Actually, on my other screen setup, it is still small on the other side. @dominiklohmann Do you have multiple displays hooked up when you're testing that?

**Comment by dominiklohmann** [comment]
Yes.

Can you test this? Run:

```sh
sleep 3 && yabai -m query --windows | jq 'map(select(.app == "Firefox Developer Edition"))'
```

And then open a context menu on your FireFox within those three seconds. Does yabai print information about the context menu, meaning that it sees the context window as a window it should handle (it shouldn't)?

**Comment by mackeyja92** [comment]
@dominiklohmann This is the output of that.

```json
[
  {
    "id": 122469,
    "pid": 4068,
    "app": "Firefox Developer Edition",
    "title": "Right click menu in firefox opening on different display and behind other windows · Issue #314 · koekeishiya/yabai",
    "frame": {
      "x": 1940,
      "y": -574,
      "w": 3800,
      "h": 2120
    },
    "level": 0,
    "role": "AXWindow",
    "subrole": "AXStandardWindow",
    "movable": 1,
    "resizable": 1,
    "display": 2,
    "space": 4,
    "visible": 1,
    "focused": 1,
    "split": "none",
    "floating": 0,
    "sticky": 0,
    "topmost": 0,
    "border": 0,
    "shadow": 1,
    "zoom-parent": 0,
    "zoom-fullscreen": 0,
    "native-fullscreen": 0
  }
]
```

**Comment by dominiklohmann** [comment]
Yeah, yabai doesn’t care about your context window as I thought and as it should be.

If you want to investigate further than queries and still think that yabai is the root cause, run yabai in verbose mode and look at its output when you open the context window.

**Comment by mackeyja92** [comment]
Not sure why I didn't think of trying this sooner, but turning off yabai completely and doing it still causes the same thing. So I don't think this is a yabai issue. Thanks for the help troubleshooting.

**Comment by jared-fraser** [comment]
To anyone else who comes here with this issue.

https://bugzilla.mozilla.org/show_bug.cgi?id=1592416

Fixed the issue with `Right click Firefox Icon > Options > Assign to ... > Select none`
