### ISSUE TITLE
Catalina MS Teams Screen Sharing

### ISSUE THREAD

**Issue by dumbbyte** [koekeishiya/yabai#315]
Since I upgraded to macOS Catalina, whenever I have Yabai running and I try to screen share in a meeting with MS Teams, I get a message from Teams asking me to add the appropriate permissions in System Preferences for Teams to Screen Record. I've added those permissions, and screen sharing works fine in Teams when Yabai is not running.

As a workaround, I've discovered that I can have Yabai running and successfully start a screen share in Teams if Teams is running in Native Fullscreen.

I'm not sure if this is an issue with MS Teams or with Yabai, but was wondering if there is a set of rules for Yabai that I can put in place for MS Teams to bypass the need for being in native full screen mode before starting a screen share?

I have no idea where to start troubleshooting so any direction is greatly appreciated :)

**Comment by dominiklohmann** [comment]
You can add a rule for Microsoft Teams that disables the tiling of all MS Teams windows. That way yabai won't interact with the application at all.

```sh
yabai -m rule --add app='^Microsoft Teams$' manage=off
```

For more on rules, see [§ 6.6 of the user guide](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#66-rule). E.g., you might want to restrict this by window title so only the screen sharing window is untiled.
