### ISSUE TITLE
'zoom-fullscreen' not working in 'float' layout

### ISSUE THREAD

**Issue by abelsalgadoromeroWD** [koekeishiya/yabai#317]
I am using skhd to manage the shortcuts and I see that going into fullscreen does only work when on bsp layout.

Here is the shortcut I use, I recall it was from the example:
`alt - f : yabai -m window --toggle zoom-fullscreen`

Is this intended?

**Comment by ychnh** [comment]
I am able to get the toggle full screen to work in bsp layout.
So it must be a bug.

**Comment by abelsalgadoromeroWD** [comment]
My mistake, I wrote it the other way. It only works when in bsp, but not in float.
For float, I resort to a grid command.

**Comment by dominiklohmann** [comment]
That's by design and not a bug.

**Comment by abelsalgadoromeroWD** [comment]
I honestly find it odd, but then at least it would be nice if it was explained in the docs which options work for each layout.

**Comment by dominiklohmann** [comment]
The difference is straight forward imo: zoom is something you toggle, which cannot work for floating windows. A grid-layout command is just a convenience command for moving and resizing a window, and moving a tiled window makes no sense.

**Comment by abelsalgadoromeroWD** [comment]
> The difference is straight forward imo: zoom is something you toggle, which cannot work for floating windows.

I am really sorry and I don't mean to be rude, but that still does not make sense to me.
We can agree that "Float" is the normal out-of-the-box behauviour for MacOs desktop, but you are saying that zoom-fullscreen "cannot work" in this mode when this is a default feature of any similar desktop. Even i3 or other tiling wm have that.

Additionally there's a simple workarround that provides the exact same result (using grid), but thhis forces users to define an additional shortcut, so if you want to switch between bsp & float you have to keep track of different shortcuts to do the same thing.

**Comment by koekeishiya** [comment]
> I am really sorry and I don't mean to be rude, but that still does not make sense to me.
We can agree that "Float" is the normal out-of-the-box behauviour for MacOs desktop, but you are saying that zoom-fullscreen "cannot work" in this mode when this is a default feature of any similar desktop. Even i3 or other tiling wm have that.

> Additionally there's a simple workarround that provides the exact same result (using grid), but thhis forces users to define an additional shortcut, so if you want to switch between bsp & float you have to keep track of different shortcuts to do the same thing.

Well, obviously there is no technical limitation here; as you mentioned there is a separate command to perform that exact transformation to the window frame.

The reason for this is first and foremost that by allowing the command `yabai -m window --toggle zoom-fullscreen` to work on windows in a floating state is that it breaks the naming convention and thus the implied assumptions that come with the name of the command. How would the related command `yabai -m window --toggle zoom-parent` be interpreted by a user in the scenario where *--zoom-fullscreen* would be enabled on a floating window. A floating window has no concept of a parent, and there is no equivalent operation for a window in floating mode.

You can argue that this is a small thing, but I personally find that it makes the interface less complex and easier to understand. Now I agree that the documentation could use some work, but at the end of the day I have limited time to spend on this specific project and I prefer spending that time on improving the code rather than writing documentation.

Also, you don't actually need to create multiple binds for this. Simply utilize the query system to check whether the window you are operating on is floating or not, and have it call the appropriate command - all in one bind.

**Comment by abelsalgadoromeroWD** [comment]
That actually make sense, 👍 . I really hope I did not come as rude, that was not my intention.

>  Now I agree that the documentation could use some work, but at the end of the day I have limited time to spend on this specific project and I prefer spending that time on improving the software rather than writing documentation.

If you are willing to invest some time with a few reviews I can test the features and update the docs. I am an avid AsciiDoc user.

> Simply utilize the query system to check whether the _window you are operating on/space you are in_ is floating or not

I'll definetly try.


PS: I've tested several apps to make my MacOs experience better (I use it for work, I am more of a Linux guy) and yabai + skhd so far are the best. Thanks a lot!!

**Comment by koekeishiya** [comment]
> That actually make more sense to me 👍 thank you both for the time. I really hope I did not come as rude, that was not my intention.

Don't worry about it. There is nothing wrong with asking questions when something does not make sense to you. The end goal is to provide a pleasent experience for the users, and it is hard to do so if noone questions the decions that have been made.

> If you are willing to invest some time with a few reviews I can test the features and update the docs. I am an avid AsciiDoc user.

I wouldn't mind this at all. The approach so far have been to have the asciidoc page be fairly simple and concise, as it is also auto-translated into a manpage. The idea was for a more elaborate guide/description/tips to be in the wiki. The readme was at some point going to be remade with links to the wiki etc.

So far I've let @dominiklohmann handle that, but he has been busy lately (probably still is), so it will probably take some time for that to happen. Last  time I checked he did have some great progress, so might want to wait and see what happens here.  If you'd like to try and contribute on this front I think it might be best to check with him first to avoid potential redundant work.

> I'll definetly try.

If  you need some help creating this feel free to ask, either in this issue or a new one.
Some user-end customizations are fairly common, and the idea was to have a section in the wiki for these kinds of things as well.

**Comment by D4NH** [comment]
I'm the following keybind to zoom in float, not toggle-able tho.

`# make floating window fill screen
cmd + alt - up : yabai -m window --grid 1:1:0:0:1:1`

**Comment by d-miketa** [comment]
> Also, you don't actually need to create multiple binds for this. Simply utilize the query system to check whether the _window you are operating on/space you are in_ is floating or not, and have it call the appropriate command - all in one bind.

Just wondering if anyone's written a version of this so that the float version is toggle-able as well?

**Comment by mendrew** [comment]
>Also, you don't actually need to create multiple binds for this. Simply utilize the query system to check whether the window you are operating on/space you are in is floating or not, and have it call the appropriate command - all in one bind.


@d-miketa I was playing around with zoom and come to this solution using yabai `query` as @koekeishiya suggested.
```shell
# toggle window zoom 
alt - f : yabai -m query --spaces --window | grep '"type":"float"' && yabai -m space --layout bsp;\
          yabai -m query --windows --window | grep '"floating":1' && yabai -m window --toggle float;\
          yabai -m window --toggle zoom-fullscreen;
``` 

Explanation: 
1. `yabai -m query --spaces --window | grep '"type":"float"' && yabai -m space --layout bsp;\`
Check a space layout of focused window and if it's `float` set to `bsp` as window's `zoom-fullscreen` won't work for `float` space layout.


2. `yabai -m query --windows --window | grep '"floating":1' && yabai -m window --toggle float;\`
Check if the window is floating and if it is then toggle it.

3. `yabai -m window --toggle zoom-fullscreen;`
Finally set fullscreen for the window

Works for me pretty well so far.

**Comment by it-is-wednesday** [comment]
For what it's worth, this can be solved using a couple of Python lines:
```python
def yabai(cmd, check=True):
    try:
        proc = run(["yabai", "-m", *cmd.split()], capture_output=True, check=check)
        return json.loads(proc.stdout.decode())
    except json.JSONDecodeError:
        return None

def zoom(window_id):
    # get dimensions of the display of the window
    dimensions = yabai(f"query --displays --window {window_id}")["frame"]
    width = str(round(dimensions["w"]))
    height = str(round(dimensions["h"]))

    yabai(f"window {window_id} --move abs:0:0")
    yabai(f"window {window_id} --resize abs:{width}:{height}")
```

Obviously the `window_id` can be omitted in order to perform this on the current window, I just use this in a larger script:)

**Comment by lo1ol** [comment]
I use this impl with caching old size
```fish
#!/usr/bin/env fish

function window_is_float
    set layout $(yabai -m query --spaces --space | jq '.type')
    [ "$layout" = "\"float\"" ] && echo true
    echo $(yabai -m query --windows --window | jq '."is-floating"')
end

function toggle_zoom
    set float $(window_is_float)

    if $float
        mkdir -p /tmp/yabai/zoom_cache
        cd /tmp/yabai/zoom_cache
        set window_id $(yabai -m query --windows --window | jq '.id')

        if [ -e $window_id ]
            cat $window_id | read x y w h
            yabai -m window --resize abs:$w:$h
            yabai -m window --move abs:$x:$y
            rm -rf $window_id
        else
            yabai -m query --windows --window | jq '.frame.x, .frame.y, .frame.w, .frame.h' | tr '\n' ' ' > $window_id
            yabai -m window --grid 1:1:0:0:1:1
        end

    else
        yabai -m window --toggle zoom-fullscreen
    end

    yabai -m window --focus $next_id
end
```

```
alt - f : $HOME/.config/yabai/tools toggle_zoom
```

**Comment by dynaevdv** [comment]
> I use this impl with caching old size
> 
> ```fish
> #!/usr/bin/env fish
> 
> function window_is_float
>     set layout $(yabai -m query --spaces --space | jq '.type')
>     [ "$layout" = "\"float\"" ] && echo true
>     echo $(yabai -m query --windows --window | jq '."is-floating"')
> end
> 
> function toggle_zoom
>     set float $(window_is_float)
> 
>     if $float
>         mkdir -p /tmp/yabai/zoom_cache
>         cd /tmp/yabai/zoom_cache
>         set window_id $(yabai -m query --windows --window | jq '.id')
> 
>         if [ -e $window_id ]
>             cat $window_id | read x y w h
>             yabai -m window --resize abs:$w:$h
>             yabai -m window --move abs:$x:$y
>             rm -rf $window_id
>         else
>             yabai -m query --windows --window | jq '.frame.x, .frame.y, .frame.w, .frame.h' | tr '\n' ' ' > $window_id
>             yabai -m window --grid 1:1:0:0:1:1
>         end
> 
>     else
>         yabai -m window --toggle zoom-fullscreen
>     end
> end
> ```
> 
> ```
> alt - f : $HOME/.config/yabai/tools toggle_zoom
> ```

For works with few monitors should return after echo true inside function window_is_float

**Comment by jeffp123** [comment]
Setting up hammerspoon for the first time. Here is how I did it in hammerspoon:
```lua
local json = require("json")

hs = hs
spoon = spoon

local yabai_frame_cache = {}

function yabai(args, completion)
    local yabai_task = hs.task.new("/opt/homebrew/bin/yabai", function(err, stdout, stderr)
        if type(completion) == "function" then
            completion(stdout, stderr)
        end
    end, args)

    yabai_task:start()
end

function yabai_space_is_float()
    local output, status, type, rc = hs.execute("/opt/homebrew/bin/yabai -m query --spaces --space")
    if pcall(function()
        parsed = json.parse(output)
    end) then
        if parsed.type == "float" then
            return true
        end
    else
        hs.alert("Could not determine if yabai spaces are in float mode")
    end

    return false
end

function get_yabai_window()
    local output, status, type, rc = hs.execute("/opt/homebrew/bin/yabai -m query --windows --window")
    if pcall(function()
        parsed = json.parse(output)
    end) then
        return parsed
    else
        hs.alert("Could not get yabai window")
    end
end
```

And then, bind shift-alt-M to zoom:
```lua
hs.hotkey.bind({"shift", "alt"}, "M", function()
    local window = get_yabai_window()
    if yabai_space_is_float() or window["is-floating"] then
        if yabai_frame_cache[window.id] then
            local cached_size = "abs:" .. yabai_frame_cache[window.id].w .. ":" .. yabai_frame_cache[window.id].h
            local cached_position = "abs:" .. yabai_frame_cache[window.id].x .. ":" .. yabai_frame_cache[window.id].y
            yabai({"-m", "window", "--resize", cached_size}, function()
                yabai({"-m", "window", "--move", cached_position}, function()
                    yabai_frame_cache[window.id] = nil
                end)
            end)
        else
            yabai_frame_cache[window.id] = window["frame"]
            yabai({"-m", "window", "--grid", "1:1:0:0:1:1"})
        end
    else
        yabai({"-m", "window", "--toggle", "zoom-fullscreen"})
    end
end
```
