### ISSUE TITLE
When disconnecting an external monitor, relative desktop 1 on both monitors condense to Desktop 1

### ISSUE THREAD

**Issue by nzchicken** [koekeishiya/yabai#323]
I work often with an external screen, but sometimes I end up taking my laptop to a meeting. When disconnecting the external screen, Desktop 1 on the external monitor has all of its windows shifted to Desktop 1 on the internal monitor. When plugging the external monitor back in again, the windows that were originally on Desktop 1 on the external monitor all shift back to their respective places. I would like yabai to help by putting the windows from the external monitor onto a new desktop, instead of merging them onto the same screen (I think it's actually Mac doing this right?).

So, in the following example:

| Monitor | Desktop | Window |
| - | - | - |
| 1 | 1 | 1, 2 |
| 1 | 2 | 3 |
| 2 | 3 | 4 |
| 2 | 4 | 5, 6 |

This is what currently happens on disconnecting the external monitor:

| Monitor | Desktop | Window |
| - | - | - |
| 1 | 1 | 1, 2, 4 |
| 1 | 2 | 3 |
| 1 | 3 | 5, 6 |

But what would be preferable is:

| Monitor | Desktop | Window |
| - | - | - |
| 1 | 1 | 1, 2 |
| 1 | 2 | 3 |
| 1 | 3 | 4 |
| 1 | 4 | 5, 6 |

And ideally it would go back to its original state when plugging in the external monitor.

Right now, my current work around to avoid merging windows onto Desktop 1, is to just leave (in the example above) Desktop 3 empty.

Also, thanks so much for your work here. This is the first, and likely the last tiling window manager I'll use, and it's great to see there's active development!

**Comment by dominiklohmann** [comment]
(Sorry for closing, misclicked on mobile)

This has been previously discussed, and is a hard to solve issue. Yabai isn’t doing anything here—you’re observing the default behavior of macOS. You would need to serialize all spaces and their windows on almost every event to try to cache their state, just to create one new space (the one that’s missing when compared to the cached spaces) and move all windows back to it after a Display was disconnected.

**Comment by johnallen3d** [comment]
I've experienced your pain as well @nzchicken! I took @koekeishiya's [advice from this issue](https://github.com/koekeishiya/yabai/issues/238#issuecomment-530400722) and stopped using the first desktop on my external display. I just leave it there empty and everything else works as expected. To be fair, I'm not in the habit of navigating to desktops using `prev/next` so I don't notice the extra desktop in the middle.

**Comment by nzchicken** [comment]
Thanks @dominiklohmann and @johnallen3d! I suspected that it was macOS just making life harder. I'll just that workaround of keeping the desktop empty, as I can imagine that the payoff for doing this stuff internally in yabai is going to be a super pain.
