### ISSUE TITLE
Float the next window going to be opened

### ISSUE THREAD

**Issue by jack836** [koekeishiya/yabai#326]
I used the following to open iTerm in floating mode (only when I wanted to) - in chunkwm
``` 
 cmd  - return      : chunkc set window_float_next 1; /Applications/iTerm.app/Contents/MacOS/iTerm2 
```
How can I implement an equivalent in yabai wm. The following didn't work (the new window remains titled)
``` 
cmd  - return      : /Applications/iTerm.app/Contents/MacOS/iTerm2 ;\
       		     yabai -m window --toggle float 
```
What am I missing? Sorry, if it has already been addressed/answered and that I didn't search properly.
Any help is highly appreciated.

**Comment by dominiklohmann** [comment]
What you're missing with your second approach is that you're toggling float on the focused window, which isn't iTerm2 if you've just opened it.

Something like this works pretty well:

```sh
yabai -m signal --add label=float_next app='^iTerm2$' event=window_created action='yabai -m signal --remove float_next; yabai -m window $YABAI_WINDOW_ID --toggle float'
```

Note that the `event=window_created` signal doesn't trigger when windows are _restored_ when an application launches, so the logic would need to be adapted for this to also works for restored windows.

**Comment by jack836** [comment]
Thank you @dominiklohmann  for quickly putting up a solution.

I tested it on my machine, adding the above line to yabairc.
When I fire-up a new iTerm2, it fails to float and gets tiled (it also appears that the window gets floated for a fraction of a second at start, but then falls back to be tiled immediately). I have no other rules/signals set for iTerm2. I killed all iTerm2 windows, restarted yabai etc, but nothing worked. It feels as if it's getting overridden by some other setting?

**Comment by dominiklohmann** [comment]
I explained that caveat above.

> Note that the `event=window_created` signal doesn't trigger when windows are _restored_ when an application launches, so the logic would need to be adapted for this to also works for restored windows.

You'll have to hook into `event=application_launched`, which carries `$YABAI_PROCESS_ID`, which can then be turned into a set of window ids on start.

Something like this (off the top of my head, this is not battle-tested):

```sh
# trigger on window_created
yabai -m signal --add label=float_next_window_created event=window_created action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m window $YABAI_WINDOW_ID --toggle float'

# trigger on application_launched
yabai -m signal --add label=float_next_application_launched event=application_launched action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m query --windows | jq -r ".[] | select(.pid == $YABAI_PROCESS_ID).id" | xargs -I{} yabai -m window {} --toggle float'
```

Yes, this workaround is ugly. And no, there is no unified window_spawned event that does this for you.

**Comment by jack836** [comment]
Thank you again.
@dominiklohmann I did update my previous comment - in case you missed it ...
[Update] It has to do something with the way I launch iTerm2. When I launch iTerm through Launchpad --> iTerm2 OR iTerm2-Menu --> Shell --> New Window; then the newly spanned iTerm2 window actually FLOATS. So, wondering what's wrong doing the same through shkd using
cmd - return : /Applications/iTerm.app/Contents/MacOS/iTerm2

**Comment by dominiklohmann** [comment]
I did read your update, and I think you're still misunderstanding the difference between _restored_ windows and _created_ windows on a semantic level.

When an application first launches, the windows opened by it are _restored_. They do not trigger an `event=window_created` signal, but rather an `event=application_launched` signal. Note that this can be multiple windows at the same time, which is why the signal carries a process id, and you need to do an additional query to get all windows that belong to that process id.

Opening additional windows _creates_ them. These do trigger `event=window_created`, but not `event=application_launched`. This is always just a single window, which is why this signal carries the window id directly.

**Comment by jack836** [comment]
Thank you for the explanation and being very helpful. I think I got the point this time. 

So, now I am trying to think if it is possible to replicate process involved in doing (clicking)`Launchpad --> iTerm2 OR iTerm2-Menu --> Shell --> New Window` using an apple-script (then trigger it from shkd). I  am not good in apple-script either and hence could not think of a possibility.

Sorry, if I again missed/mis-understood some thing. Thank you for being considerate and helpful.

**Comment by dominiklohmann** [comment]
The easiest is just to create triggers for both signals as I've shown above:

> ```shell
> # trigger on window_created
> yabai -m signal --add label=float_next_window_created event=window_created action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m window $YABAI_WINDOW_ID --toggle float'
> 
> # trigger on application_launched
> yabai -m signal --add label=float_next_application_launched event=application_launched action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m query --windows | jq -r ".[] | select(.pid == $YABAI_PROCESS_ID).id" | xargs -I{} yabai -m window {} --toggle float'
> ```

E.g., in your .skhdrc:

```sh
 cmd - return : \
    yabai -m signal --add label=float_next_window_created event=window_created action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m window $YABAI_WINDOW_ID --toggle float' ; \
    yabai -m signal --add label=float_next_application_launched event=application_launched action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m query --windows | jq -r ".[] | select(.pid == $YABAI_PROCESS_ID).id" | xargs -I{} yabai -m window {} --toggle float' ; \
    /Applications/iTerm.app/Contents/MacOS/iTerm2 
```

Obviously you could replace the way you open iTerm2 with some sophisticated AppleScript, but that's out of scope for this issue.

**Comment by jack836** [comment]
I did add the above lines to my .skhdrc for a quick test, but the spanned iTerm2 windows again failed to float.
Reading those lines I am convinced that it should float the next spawned window, but didn't. May be I am still missing/mis-understanding something.... Hope someone successfully gets it to work.

I sincerely appreciate all the efforts of @dominiklohmann

**Comment by dominiklohmann** [comment]
I've simply pasted what's below into my skhdrc and it works. Only thing I've exchanged is how I open iTerm2.

```
 cmd - return : \
    yabai -m signal --add label=float_next_window_created event=window_created action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m window $YABAI_WINDOW_ID --toggle float' ; \
    yabai -m signal --add label=float_next_application_launched event=application_launched action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m query --windows | jq -r ".[] | select(.pid == $YABAI_PROCESS_ID).id" | xargs -I{} yabai -m window {} --toggle float' ; \
    osascript -e 'tell application "iTerm2" to create window with default profile command ""' || open -b com.googlecode.iTerm2
```

As a sidenote, I am not convinced that <kbd>cmd</kbd> + <kbd>return</kbd> is a good shortcut, since that actually overrides system functionality (confirm input/form while still in a text field of that input/form). For example, I can send the issue reply I am currently writing by pressing <kbd>cmd</kbd> + <kbd>return</kbd> without leaving the text field.

**Comment by jack836** [comment]
I tried with you last script and it WORKED ! Yes, the new iTerm window did FLOAT this time.
When I went back again to `/Applications/iTerm.app/Contents/MacOS/iTerm2 ` , it didn't work.
So, Yes the way you open iTerm2 really matters here (at-least for me).

Anyway, happy to have a nice feature (that I missed for quite a while). Thanks to the command-line wizardry of @dominiklohmann
