### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by XDID** [koekeishiya/yabai#328]
How could I add some new elements to the status bar?

**Comment by charlesdurham** [comment]
Wiki suggests using ubersicht https://github.com/koekeishiya/yabai/wiki/Configuration#status-bar

**Comment by koekeishiya** [comment]
If you are comfortable writing C, simply edit `src/bar.c` and make it draw whatever, else I'd suggest using something like übersicht as mentioned in the comment above.
