### ISSUE TITLE
Default label for any given space should be its Mission Control display name

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#329]
The default label for any given space should be its Mission Control display name, e.g.:

- `Desktop <n>` for the nth non-fullscreen space across all displays, starting at 1
- `<app name>` for fullscreen spaces which have one app
- `<app name> + <app name>` for fullscreen spaces which have two apps (left + right)

Note that while most of this can be implemented using signals, what cannot be detected easily is when two split-fullscreen apps swap their positions. Doing this with signals is hard to do, while this should be easy from within yabai.

**Comment by koekeishiya** [comment]
This could be tricky to maintain if the user uses mission-control to swap places between or create/destroy spaces. It could possibly be achieved by enumerating *all* spaces when we detect that mission-control exited and basically re-map all unknown and/or changed spaces. Not sure how efficient of a solution that would be, but I can see how that would work.

**Comment by dominiklohmann** [comment]
This kind of ties in with another change that I wanted to suggest, which is adding signals to yabai that are not raised by macOS: A _combined_ window created event that includes restored windows, and a signal for spaces being moved, created, or destroyed.

With the latter set of events a user could implement this easily by themselves.

**Comment by koekeishiya** [comment]
Closing this as mentioned it should be possible when #1365 goes through.
