### ISSUE TITLE
focused vs active vs inactive

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#33]
Maybe worth having the distinction of focused vs active. There can only be one focused window at a time, but with multilpe displays there can be multiple active windows, where an active window is defined to be the window that would be the focused window for that display.

**Comment by dominiklohmann** [comment]
Is there a specific use case outside of querying? For window queries, maybe always show both focused=0/1 and active=0/1?

**Comment by koekeishiya** [comment]
When window opacity is enabled it will lower the alpha of windows on external displays as they are not the focused window. This pretty much makes that functionality obsolete in multi-display environments.
There may be other situations where having this distinction would be helpful, but I have not yet thought that far ahead.

**Comment by koekeishiya** [comment]
There is really no good way to track if a window is active or not. There are too many unpredictable ways that might screw with us. Instead of trying to track whether a window is active or not, we simply perform a bit more sophisticated checking when trying to see if the window should be "deactivated".

This will allow the active window of a display to maintain its active border color and window opacity when focus switches to a window located on a different display.

**Comment by koekeishiya** [comment]
Decided to undo these changes because it went down a path that just felt really messed up. While this is kind off annoying to me, it is more consistent behaviour than trying all kinds of tricks to work around this, and I think consistency in behaviour is more important at this time.

Might revisit in the future.
