### ISSUE TITLE
One window not working with focus follows mouse ffm in autofocus mode

### ISSUE THREAD

**Issue by mbigras** [koekeishiya/yabai#333]
I happily use focus follows mouse ffm in autofocus mode; however there is one application that is refusing to focus but not raise, it's called yEd:

```
$ ls /Applications/ | grep yE
yEd.app
```

I'm not sure why it's raising, I remember from chunkwm that sometimes this happens and there isn't anything that can be done about it besides ignore the window.

I've tried to ignore the yEd application with a [rule](https://github.com/koekeishiya/yabai/blob/master/src/rule.h) but it's isn't working  

```
#!/usr/bin/env sh
yabai -m config focus_follows_mouse autofocus
yabai -m rule --add app="^yEd$" manage=off
```

I suspect because the manage=off option is for the tilling plugin but not the ffm plugin but I'm not sure.

I've tried running yabai in verbose mode and I am not seeing any error messages even though the yEd window is raising unexpectedly

```
$ yabai --verbose
...
yabai: scripting-addition payload was already injected into Dock.app!
yabai: osax version = 1.0.7, osax attrib = 0x3F
EVENT_HANDLER_DAEMON_MESSAGE: msg 'config focus_follows_mouse autofocus'
EVENT_HANDLER_DAEMON_MESSAGE: msg 'rule --add app=^yEd$ manage=off'
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: Sublime Text
EVENT_HANDLER_APPLICATION_DEACTIVATED: iTerm2
EVENT_HANDLER_APPLICATION_ACTIVATED: Sublime Text
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: yEd
EVENT_HANDLER_APPLICATION_DEACTIVATED: Sublime Text
EVENT_HANDLER_APPLICATION_ACTIVATED: yEd
```

* Is there a way to ignore the yEd application?
* Is there a better was to fix the unexpected autoraise behavior?

This is my setup

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88
$ yabai --version
yabai-v2.1.2
```

**Comment by koekeishiya** [comment]
The autofocus functionality was implemented by reverse engineering the event-flow of the WindowServer, and so I don't actually know why it will not work for some applications.

**Comment by pixmin** [comment]
@mbigras I have a similar problem with Firefox, have you found a solution to this problem?

**Comment by koekeishiya** [comment]
Closing this in favour of #397, but I still don't think this is fixable.
