### ISSUE TITLE
Tiling mode? Changes occasionally after hours of use

### ISSUE THREAD

**Issue by slifin** [koekeishiya/yabai#334]
Every now and again I get tiling that behaves like this: 

```
|a|b|cc|
|a|b|cc|
```
Kind of horizontal tiling 

Where a b and c are different apps 

Instead of what usually happens which is:
```
|a|c|
|b|c|
```
Which is what I want, tiling vertically and horizontally my config currently looks like this:
```
#!/usr/bin/env sh

yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise
yabai -m config window_topmost on
yabai -m config layout bsp 

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
```

**Comment by slifin** [comment]
Restarting yabai with brew appears to temporarily fix this

**Comment by koekeishiya** [comment]
I don't think this is actually a bug, but rather the consequence of certain modifications made to the bsp-tree over time, as operations persist. E.g: Open window A, open window B, resize such that A fills 30% and B filles 70%. Close window B. Now open a new window C. C will fill 70% and A will fill 30%.
