### ISSUE TITLE
How can I bind special keys in .skhdrc?

### ISSUE THREAD

**Issue by yangnom** [koekeishiya/yabai#336]
I'm trying to bind 

```
shift + ctrl + alt + cmd - \ :
```

to a command, but that isn't working. I know the keycode for `\` is 49, but I'm not sure how to implement it exactly.  I apologize if this question is in the wrong place (yabai instead of skhdrc) but this project appears to be more responsive.  Thank you.

**Comment by joshtwo** [comment]
Just write the hex number (for 49, it'd be 0x31):

```
shift + ctrl + alt + cmd - 0x31 :
```

**Comment by dominiklohmann** [comment]
> I apologize if this question is in the wrong place (yabai instead of skhdrc)

You _know_ this question is in the wrong place. The answer to this is in three places: The skhd README, the skhd example configuration, and koekeishiya/skhd#1.
