### ISSUE TITLE
High CPU when using an application in full screen

### ISSUE THREAD

**Issue by peppy** [koekeishiya/yabai#339]
On one of my PCs, I can reproduce yabai using insanely high CPU while focused on a fullscreen app.

Profile sample: [yabai.txt](https://github.com/koekeishiya/yabai/files/3956215/yabai.txt)
Configuration: [yabairc.txt](https://github.com/koekeishiya/yabai/files/3956221/yabairc.txt) (may be related to my custom rule, requires further testing)

```
➜  ~ yabai --version
yabai-v2.1.3
➜  ~ uname -a
Darwin ppybook 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
```

macOS 10.15.1 (19B88)

Please let me know if more information is required.

**Comment by koekeishiya** [comment]
Are there any differences in configuration between your machines, if it only happens on one of them? Does the high CPU usage persist if you switch away from the fullscreen space?

Is this happening for all applications or only for specific applications?

Can you try to reproduce this after disabling focus_follows_mouse and/or certain rules that you think could interfere?

**Comment by peppy** [comment]
The CPU usage immediately drops on switching away from the fullscreen application. I had to take the profile sample from an ssh session to capture it due to this.

I'll see if I can narrow it down any further.

**Comment by koekeishiya** [comment]
I assume that the issue is that the following spin-lock triggers incorrectly in this case: https://github.com/koekeishiya/yabai/blob/master/src/event.c#L672 

So what is supposed to be happening here, is that this specific code-path should only trigger when an application *exits* fullscreen-mode. The spin-lock is in place because we have to wait until the animation finishes before we can interact with the window again.

**Comment by koekeishiya** [comment]
I've made some adjustment on the master branch. Can you run that version and see if you are able to reproduce the issue?

**Comment by peppy** [comment]
Thanks for the quick changes!

I've been trying to repro it before updating to master but can't seem to make it happen again. I'll continue with my daily use on master and let you know if it appears again.

**Comment by peppy** [comment]
Just an aside, the `brew install --HEAD yabai` doesn't seem to be tracking beyond the last release.

**Comment by dominiklohmann** [comment]
> Just an aside, the `brew install --HEAD yabai` package doesn't seem to be tracking beyond the last release.

That's a Homebrew thing, you'll have to uninstall before installing from HEAD.

**Comment by peppy** [comment]
Thanks, that worked.

I managed to repro again before updating, and find a relatively reliable repro case. It does look to be resolved on `head`!
