### ISSUE TITLE
Add option to run commands through login shell

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#34]
A recent commit (904de62) made it so commands are run through `$SHELL -c`. If they were run through `$SHELL -l -c` instead, variables and aliases configured in files like `.profile`, `.bashrc`, `.zprofile` or `.zshrc` would be available as well. 

For incorrectly configured setups this may increase latency a fair bit, which is why this should be an option in my opinion. 

The same applies to `skhd`, and if implemented here I suggest adding an option to skhd for this as well.

(Side note: I also commented this on the mentioned commit itself, but the fallback should always be `/usr/bin/env sh` instead of `/bin/bash` for macOS with 10.15 in mind.)

**Comment by koekeishiya** [comment]
I replied to your comment in the commit, but what I said is actually not true, so I'll refrain from reposting it here. So the kernel expects the absolutepath to the interpreter to be used for the script and invokes `#!/usr/bin/env sh`. The `env` binary then looks up the users *PATH* and that is how this works. By that definition we can bypass the $SHELL lookup  and simply do the following:

```
        char *exec[] = { "/usr/bin/env", "sh", "-c", command, NULL};
        exit(execvp(exec[0], exec));
```

I tested the above code and it works fine on my system, actually running the specified command. It takes `0.000011` seconds to execute, which is the same amount of time it takes to run
```
        char *exec[] = { g_shell, "-c", command, NULL};
        exit(execvp(exec[0], exec));
```

where *g_shell* is either *zsh* or *bash*.

I don't think there is a huge need for the *-l* personally as it is trivial for the user to source whatever file they want at the top of their config file. I'm not opposed to adding it, but I'd rather not introduce a config option here.

**Comment by dominiklohmann** [comment]
Just tried this locally—this actually fixes the core issue, which was my `.zshenv` not being picked up. Now I can use my full `$PATH` and aliases in my `.yabairc` file. Closing this in favour of the  `/usr/bin/env sh` change.

Do you want me to open a tracking issue for `skhd` as well?

**Comment by koekeishiya** [comment]
> Do you want me to open a tracking issue for skhd as well?

Sure, go ahead.
