### ISSUE TITLE
Swap window with mouse

### ISSUE THREAD

**Issue by anoother** [koekeishiya/yabai#340]
Click-dragging currently support two actions: move and resize. Would it be possible to enable a third action for 'swap'?

It would be nice if this could be exposed by a second mouse modifier key + button click, but this might be tricky in terms of config, so enabling extra mouse buttons (3, or even 4..5..n) would work also.

**Comment by dominiklohmann** [comment]
You can just drag a window (e.g., by using the move action) onto the center of another window to swap them, or onto the edge of another window to warp (re-insert) onto the window.

**Comment by anoother** [comment]
Aha! Did not realise this, thanks.

**Comment by anoother** [comment]
Just tried, it seems that the windows move, as opposed to swap, whatever I do... what is the threshold/area for 'centre'?

**Comment by dominiklohmann** [comment]
See discussion in #142.

**Comment by anoother** [comment]
Thanks. Think I have an old version.
