### ISSUE TITLE
Hide window borders when showing desktop

### ISSUE THREAD

**Issue by Arelav** [koekeishiya/yabai#342]
When I have window borders enabled and use macOS "show desktop" functionality from touchpad gesture or using "hot corners" the windows moved to outside of the desktop however the borders still in the same place.
![image](https://user-images.githubusercontent.com/1059539/70832010-02705a80-1dc2-11ea-853a-346b32d257a5.png)

I'll be happy to provide any additional information/configs if needed however it's very simple to reproduce.

**Comment by koekeishiya** [comment]
I don't think this is fixable. I don't know of any way to detect when *show desktop* activates/deactivates..
