### ISSUE TITLE
Feature request: Ability to set default initial window behavior

### ISSUE THREAD

**Issue by lauritk** [koekeishiya/yabai#345]
I was wondering if it's possible to config initial default window behavior so that new opened windows are for example floating windows (or what user prefers). It is sometimes annoying when new windows rearrange my view and this option would be helpful.

**Comment by dominiklohmann** [comment]
What you're looking for is called window rules. 

docs tl;dr

```sh
# float all Safari windows by default
yabai -m rule --add app='^Safari$' manage=off

# float all windows by default whose title ends in `' Preferences'`
yabai -m rule --add title=' Preferences$' manage=off

# Make Chrome Picture in Picture mode windows appear topmost and on all spaces
yabai -m rule --add app='^Google Chrome$' title='^Picture in Picture$' manage=off topmost=on sticky=on

**Comment by lauritk** [comment]
Thank you, this was it! :)
