### ISSUE TITLE
Output persistent display id in "yabai -m query --displays"

### ISSUE THREAD

**Issue by kerryj89** [koekeishiya/yabai#346]
When using [displayplacer](https://github.com/jakehilborn/displayplacer) I see that it exposes not just the contextual display ID (same as `yabai -m query --displays` id property), but also a persistent display ID (which I don't see outputted in `yabai -m query --displays`).

It would be nice to output this in the display query for those of us with different setups.

**Comment by dominiklohmann** [comment]
> Persistent screen ids always stay the same. Contextual screen ids change when switching GPUs or when switching ports. It's recommended to use persistent screen ids. In some rare cases, you may need to use contextual screen ids since the modes list changes when macOS switches GPUs.

This definitely deserves an investigation. I wonder if this could fix some of the issues people have been having when sleeping with an external 4k+ display.

**Comment by koekeishiya** [comment]
> I wonder if this could fix some of the issues people have been having when sleeping with an external 4k+ display.

That's how we attempted to fix it in kwm at that time. Don't think I bothered looking into it for chunkwm, as multi display never got the be a priority for me at that point.

I see no issue with exposing the uuid through the query output. As for the rest I think that is best left for someone that actually owns a 4k display to look investigate.

**Comment by dominiklohmann** [comment]
Did a quick test as a follow-up:

Built-in display, output with integrated graphics enabled:

```json
"id":2077749241,
"uuid":"2BB310FA-929B-2148-A215-982E7715F204",
```

Built-in display, output with dedicated graphics enabled:
```json
"id":69734406,
"uuid":"2BB310FA-929B-2148-A215-982E7715F204",
```

Makes me wonder if the sleep/wake issue is that the graphics card changes shortly after the external display wakes. In that case it'd just be a timing issue.

Anyhow, the UUID looks consistent to me. Wrote down a note to test with a 5K display once I'm back in the office in a week. I'll create a follow-up issue then.
