### ISSUE TITLE
Border when activating Mission Control from fullscreen window

### ISSUE THREAD

**Issue by choco** [koekeishiya/yabai#347]
When I have a fullscreen window and enable mission control, the border gets drawn and the edges of the screen.

**Comment by choco** [comment]
To add more context executing yabai in verbose the events registered are:

```
MISSION_CONTROL_ENTER
SPACE_CHANGED
WINDOW_MOVED
```

and the border refresh in the last handler trigger border rewrite.

**Comment by dominiklohmann** [comment]
As a workaround (although with a perceivable delay), you can always do this:

```sh
yabai -m signal --add event='mission_control_enter' \
    action='yabai -m config window_border off'
yabai -m signal --add event='mission_control_exit' \
    action='yabai -m config window_border on'
```

**Comment by koekeishiya** [comment]
Fixed on master. I don't get how a window in fullscreen mode can trigger a window moved event, but yeah..

**Comment by choco** [comment]
Just grateful that you find the patience to still deal with all this madness ahah
