### ISSUE TITLE
Ghost window occasioanlly appear, causing incorrect layout

### ISSUE THREAD

**Issue by peppy** [koekeishiya/yabai#348]
Occasionally, my desktop will get into a state where it seems like there is a ghost window. Sometimes restarting individual applications will fix this. Restarting yabai 100% fixes this.

I can reproduce this around once a week, so please let me know any diagnostics you'd require to track down the root cause.

affected space:
```
yabai -m query --windows --space 2
[{
        "id":183,
        "pid":673,
        "app":"GitKraken",
        "title":"GitKraken",
        "frame":{
                "x":1284.0000,
                "y":30.0000,
                "w":1268.0000,
                "h":1402.0000
        },
        "level":0,
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "movable":1,
        "resizable":1,
        "display":1,
        "space":2,
        "visible":0,
        "focused":0,
        "split":"vertical",
        "floating":0,
        "sticky":0,
        "topmost":0,
        "border":0,
        "shadow":1,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
}]
```

query across all spaces / displays: https://gist.github.com/peppy/913c82c7f958b9e055a7cf2f12111ea2

![image](https://user-images.githubusercontent.com/191335/71162335-5e3d5680-228e-11ea-933c-ed967dec2af2.png)

https://www.youtube.com/watch?v=ha8lDbiQhEU

I can rotate the windows as shown in the video, but cannot move remaining windows into the space of the ghost window. Note that opening new windows also flows the tile layout correctly around the missing one.

![image](https://user-images.githubusercontent.com/191335/71162284-45cd3c00-228e-11ea-9284-56d708e54159.png)

Seems similar to https://github.com/koekeishiya/yabai/issues/70.

**Comment by Peeja** [comment]
Looks a lot like #300.

@peppy: Is this usually happening for you while using VS Code? I think I experience the same thing (and also with Chrome).

**Comment by peppy** [comment]
I believe it is more likely Jetbrains Rider, and may be something to do with rules I had (i removed them and have had no issues since). Will try and report back with more reproducible steps soon.

**Comment by koekeishiya** [comment]
I've made some changes that will prevent the same window from being able to tile twice in case macOS report events in some weird order in some corner-cases. This should eliminate the possibility of any type of *ghost* tile.

**Comment by koekeishiya** [comment]
I'm closing this as resolved due to possible relation with ghost windows, which are now resolved. Feel free to create a new issue if you see this happen again, although that means that yabai for some reason detects a new window, and that should be returned as part of the window query.

**Comment by peppy** [comment]
Thanks!
