### ISSUE TITLE
Rules possibly don't trigger on WINDOW_TITLE_CHANGED?

### ISSUE THREAD

**Issue by askreet** [koekeishiya/yabai#350]
I'm trying to add a simple rule to not manage Firefox download dialogs. The title of the window is "Opening filename.zip", so I have run:

```
yabai -m rule --add title="^Opening" manage=false label=rule1
```

I've tried various permutations of this, such as:
* Including an app name regexp as well (ideal to avoid including the wrong windows).
* Not including a label.
* Not anchoring the regexp.

I suspect (but haven't confirmed) the reason might be the ordering of events I see when I run yabai with verbose mode:

```
EVENT_HANDLER_WINDOW_CREATED: Firefox 3154
EVENT_HANDLER_WINDOW_TITLE_CHANGED: Firefox 3154
EVENT_HANDLER_WINDOW_RESIZED: Firefox 3154
EVENT_HANDLER_WINDOW_RESIZED: Firefox 167
EVENT_HANDLER_WINDOW_MOVED: Firefox 3154
EVENT_HANDLER_WINDOW_FOCUSED: Firefox 3154
```

The logging isn't sufficient to see what those values are at each step, but IIUC Firefox is creating a window first, then updating it's title (to, presumably, match my regexp). Perhaps yabai's rules engine only triggers during window creation and the title of the window is temporarily some default, non-matching value?

Questions:
1. Is there something obviously wrong with my approach?
2. If my assumption about the rules engine is correct, would it make sense to re-scan the rules during a window title change event and attempt to re-apply their effects?

If #2 is 'yes', I might be able to dust off my C skills and attempt to contribute this change. :-)

**Comment by dominiklohmann** [comment]
Your rule is wrong.

```
yabai -m rule --add title="^Opening" manage=false label=rule1
                                            ^^^^^
```

`manage` takes a `BOOL_SEL`, which is either `on` or `off`.

**Comment by koekeishiya** [comment]
Your assumption is still correct though, rules are not reapplied when a window changes its title.
This was implemented in chunkwm: https://github.com/koekeishiya/chunkwm/blob/2b653e415a746a70a5ea3ec0ddb9e407d498a7c8/src/plugins/tiling/plugin.mm#L1312

I don't however remember why I did not do that in *yabai*. I would think I had a good reason for it, but maybe I simply just forgot about it. I think I want to tackle this myself, as I'll need to dig through some history here.

**Comment by dominiklohmann** [comment]
Honestly though, I don't think rules should be re-applied when a title changes. If a user manually toggles a window to no longer float, having its title change should not cause that rule to be applied again.

I do agree that it should clearly be communicated which events trigger a rule check, and those currently just seem to be `window_created` and `application_launched`.

Signals are way better for this purpose:

```sh
yabai -m signal --add app='^FireFox$' title='^Opening' event='window_title_changed' \
  action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq "if .floating == 1 then .id else empty end" | xargs -I{} yabai -m window {} --toggle float'
```

**Comment by koekeishiya** [comment]
> If a user manually toggles a window to no longer float, having its title change should not cause that rule to be applied again.

I think reasons like this are exactly why this is in fact not implemented in yabai.
Rules are (currently anyway,) only applied when a window is created, or when the rule itself is created.

**Comment by dominiklohmann** [comment]
For what it's worth, if a user wanted a rule to be re-applied when a title changes, this can be done:

```sh
yabai -m signal --add app=foo title=bar event=window_title_created \
  action='yabai -m rule --add label=some_unique_label app=foo title=bar manage=off'
```

The signal will trigger, and because the rule is labeled it will get overwritten, causing it to be triggered again.

**Comment by askreet** [comment]
> Your rule is wrong.

Jeez, whoops, let me try that.

**Comment by askreet** [comment]
Turns out this does work when specified correctly, so the ordering of rule processing isn't causing any issue here.
