### ISSUE TITLE
Crash/logout when changing workspace

### ISSUE THREAD

**Issue by elkiwy** [koekeishiya/yabai#351]
Hi, last night I installed and configured yabai with the default yabairc and everything was working just fine. I shutdown my computer, then restarted today and now after yabai finish to load as soon as I switch to another desktop my computer log me out and it ask for my user password and starts back with all my programs closed as if I just boot it up.

The problem is persistent and repeatable each time I switch workspace (I'm using the 4 finger gesture with the touchpad).

I don't really know how to debug this thing, so tell me if I can do something to let you investigate on this problem.

**Comment by dominiklohmann** [comment]
This lacks a fair bit of information:
- What version of macOS are you running?
- What version of yabai are you running?
- What version of the scripting addition do you have installed, if you have it installed?
- Do you have a crash report? (Console.app > Reports > Crash Reports > yabai _or_ windowserver _or_ Dock.app)
- Can you reproduce the issue with your configuration file (yabairc) removed?

**Comment by elkiwy** [comment]
Ok so, this is one of my crash logs:

[crash.txt](https://github.com/koekeishiya/yabai/files/3991483/crash.txt)


Since I saw "fadeFinished" I tried to disable window_opacity key from my config file and it seems that it removed the crashes. 

Then I re-enable window_opacity and it works just fine with fade in animations and still doesn't crash anymore.

Now I can't reproduce the problem, but I post my yabairc so you can still check if you can find something wrong with it or reproduce the crash yourself.

[yabairc.txt](https://github.com/koekeishiya/yabai/files/3991482/yabairc.txt)

I'll keep you updated if that happens again.

**Comment by dominiklohmann** [comment]
See this pinned issue: [Migration Guide: macOS 10.15 Catalina](https://github.com/koekeishiya/yabai/issues/275)

**Comment by elkiwy** [comment]
Oh sorry I missed that one. Nice to hear that you are already working on that bug because I really liked the window opacity feature!
Thanks!

**Comment by dominiklohmann** [comment]
This is not being worked on. See this comment specifically: https://github.com/koekeishiya/yabai/issues/277#issuecomment-552960833
