### ISSUE TITLE
Border for new window from fullscreen window in wrong space

### ISSUE THREAD

**Issue by choco** [koekeishiya/yabai#353]
I use Spark as my email client. I have yabai set to not manage it, and usually just keep it in native fullscreen mode.
When I want to write an email I just switch to the main window (which as I said is in fullscreen) and a new window is created. The border for this window is drawn in the wrong space (specifically the first space). So I have this phantom border in the first space when moving back there. 

Same issue seems to happen when you have multiple windows in the same space in native fullscreen mode. (border are drawn in the first space instead in the fullscreen space)

**Comment by choco** [comment]
Here's a couple of screenshots to show the issue:

New window created from fullscreen window:
<img width="1792" alt="Screen Shot 2019-12-26 at 19 19 07" src="https://user-images.githubusercontent.com/85527/71486061-b89d6080-2814-11ea-911a-49b7bece8712.png">
As you can see the border is not visible on the window.

And here's the border in the first space:
![Screen Shot 2019-12-26 at 19 19 23](https://user-images.githubusercontent.com/85527/71486094-ea162c00-2814-11ea-9881-66aa6cdd68c1.jpg)

**Comment by koekeishiya** [comment]
Fixed on master.
