### ISSUE TITLE
Mouse Cursor disappears

### ISSUE THREAD

**Issue by aeikenberry** [koekeishiya/yabai#355]
Just installed from the master branch via Homebrew, using the default config. I keep losing my mouse cursor randomly after changing screens. If I enter Mission Control even for a second, the cursor re-appears.

**Comment by dominiklohmann** [comment]
I cannot reproduce this. Are you certain this is a bug with Mission Control?

Needs more info, basically.

**Comment by aeikenberry** [comment]
Yeah, sorry I've been trying to figure out a solid way to reproduce, but I haven't been able to. It's not only when i 4-finger swipe between spaces, and not only when i use SKHD to move spaces. If I come up with a solid way to reproduce, I will re-open. I thought maybe it's a known thing or a known sign I didn't set something up correctly. Thanks for looking!

**Comment by Joellidin** [comment]
I have the same problem. I can't reproduce it consistently either...

**Comment by koekeishiya** [comment]
There is no functionality in yabai that messes with the visibility of the mouse cursor. This is likely happening because of some other application you are using. I know that kitty (terminal application) had this bug previously (not sure if it has been resolved), in case you are using that.

**Comment by rubas** [comment]
Is it possible that you were running `Bartender` with Yabai?
https://www.macbartender.com

Stopping Bartender made the problem (supposedly) go away.
