### ISSUE TITLE
Create space with arbitrary index

### ISSUE THREAD

**Issue by Juzov** [koekeishiya/yabai#356]
Hi, I am migrating from linux and sway/i3 and would like to be able to create a space with a specific index similar to i3, e.g. creating space 9 even if space 8 doesn't exist. 

The --create flag doesn't take index arguments (like --destroy does), and there is no way as far as I have understood to set the index of a space manually.

Is this possible to implement? would it cause problems with multiple displays?

**Comment by Juzov** [comment]
Should have thought of my question for a little longer, macOS spaces don't work that way. if a space is removed, spaces with a higher index will get their index decremented.

**Comment by dominiklohmann** [comment]
You _can_ work around this by labeling spaces. You just cannot change the mission control indices.
