### ISSUE TITLE
crashing on "about this mac" window

### ISSUE THREAD

**Issue by koin612** [koekeishiya/yabai#358]
im running https://github.com/koekeishiya/yabai/commit/9a70dce4bb137949fc004e29994667f670bafae0 in osx `10.15.2`.

I was checking battery usage and opened `About this Mac -> System Report` and noticed in *Activity Monitor*, that yabai CPU usage went up to 200% and wasn't responding anymore. I hope this is enough Information to recreate, otherwise let me know and I'll provide more.

Also I'd like to ask how much CPU usage should I expect from running yabai? Currently when I just watch it's at ~35% (2 cores of an i7 at 50%) all the time.

**Comment by dominiklohmann** [comment]
I cannot reproduce this at all. Mind sharing your configuration?

> Also I'd like to ask how much CPU usage should I expect from running yabai? Currently when I just watch it's at ~35% (2 cores of an i7 at 50%) all the time.

0% when idle (i.e., not triggering signals/rules or interacting with yabai in any way), and I personally get at most 1% from yabai's tiling behavior. Your mileage may vary though, depending on how much you use signals and what you use them for.

**Comment by koin612** [comment]
Hi @dominiklohmann 

Here's my *.yabairc*

```sh
# general space settings
yabai -m config layout bsp

# mouse settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_modifier fn

# bar settings
yabai -m config status_bar on
yabai -m config status_bar_text_font "Helvetica Neue:Regular:12.0"
yabai -m config status_bar_icon_font "Font Awesome 5 Free:Solid:10"
yabai -m config status_bar_space_icon_strip terminal fire III code envelope VI VII VIII IX X
yabai -m config status_bar_clock_icon clock

# global settings
yabai -m config window_placement second_child
# floating windows always on top
yabai -m config window_topmost on

# rules for apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Font Book$" manage=off

# battery icon changer
function update_battery_loop() {
	while true; do
		# Get the current battery percentage.
		battery=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)

		if [ $battery -gt 84 ]; then
			yabai -m config status_bar_power_icon_strip battery-full bolt
		elif [ $battery -gt 60 ]; then
			yabai -m config status_bar_power_icon_strip battery-three-quarters bolt
		elif [ $battery -gt 39 ]; then
			yabai -m config status_bar_power_icon_strip battery-half bolt
		elif [ $battery -gt 14 ]; then
			yabai -m config status_bar_power_icon_strip battery-quarter bolt
		else
			yabai -m config status_bar_power_icon_strip battery-empty bolt
		fi
		sleep $frequency
	done
}
update_battery_loop &
```
Here is my Plot opening and closing some terminals and leaving it idle:
![yabai-plot](https://user-images.githubusercontent.com/8482235/71580684-f1ce1d00-2b01-11ea-9f90-1d2b49b3def4.png)
And this is what it looks like, when I open the "About this Mac" window, after a while I also opened "System Report..." but it seem have crashed already.
![yabai-plot-crash](https://user-images.githubusercontent.com/8482235/71580745-378ae580-2b02-11ea-8607-eb1a089f712d.png)

**Comment by dominiklohmann** [comment]
> ```shell
> # battery icon changer
> function update_battery_loop() {
> 	while true; do
> 		# Get the current battery percentage.
> 		battery=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)
> 
> 		if [ $battery -gt 84 ]; then
> 			yabai -m config status_bar_power_icon_strip battery-full bolt
> 		elif [ $battery -gt 60 ]; then
> 			yabai -m config status_bar_power_icon_strip battery-three-quarters bolt
> 		elif [ $battery -gt 39 ]; then
> 			yabai -m config status_bar_power_icon_strip battery-half bolt
> 		elif [ $battery -gt 14 ]; then
> 			yabai -m config status_bar_power_icon_strip battery-quarter bolt
> 		else
> 			yabai -m config status_bar_power_icon_strip battery-empty bolt
> 		fi
> 		sleep $frequency
> 	done
> }
> update_battery_loop &
> ```

Take a closer look at this snippet.

You don't set `$frequency` anywhere, so you continually run this code with a 0 second sleep (basically no pause), and then continually query the battery status using `pmset`, which is a really expensive operation.

It is quite likely that `pmset` is even more expensive when another process is querying system information, e.g., the System Information panel from About This Mac.

**Comment by koin612** [comment]
You're right, I had it set in an `.sh` file, but missed it when merging it to my `.yabairc`!
Thanks for your help @dominiklohmann

**Comment by johnallen3d** [comment]
Regarding the `$frequency` variable... I was just looking over the "Tips & Tricks" page of the Wiki and notice that this function is present there but doesn't mention setting the `$frequency` variable (it just uses it). Not a big deal but it might help to include a note about that.
