### ISSUE TITLE
New spaces are delayed in status bar

### ISSUE THREAD

**Issue by frayment** [koekeishiya/yabai#359]
When creating a new space, there is a noticeable delay of up to around 2 seconds before the space appears in the yabai status bar. The actual delay is quite variable.

This issue can be seen by just typing the command:

```
yabai -m space --create
```

![Issue video](https://i.imgur.com/oaeEDtQ.gif)

If I use the example `skhd` config and focus the window as well, this issue does not persist.

**Comment by koekeishiya** [comment]
The status bar refreshes every 5 seconds. There is no event from macOS when a space is created/destroyed, which is why we cannot update the status bar immediately.
Since yabai is the one creating/destroying the space we could trigger a status bar update manually in these cases, but I don't consider this a big issue.

**Comment by rublev** [comment]
> The status bar refreshes every 5 seconds. There is no event from macOS when a space is created/destroyed, which is why we cannot update the status bar immediately.
> Since yabai is the one creating/destroying the space we could trigger a status bar update manually in these cases, but I don't consider this a big issue.

How can this be done currently?

**Comment by koin612** [comment]
> > The status bar refreshes every 5 seconds. There is no event from macOS when a space is created/destroyed, which is why we cannot update the status bar immediately.
> > Since yabai is the one creating/destroying the space we could trigger a status bar update manually in these cases, but I don't consider this a big issue.
> 
> How can this be done currently? Triggering a status bar update I mean.

I guess in `space_manager.c` there is `space_manager_add_space` and `space_manager_destroy_space` where you would trigger a `bar_refresh` on the `extern struct bar g_bar` you'll need also to add.

**Comment by koekeishiya** [comment]
I'm not going to bother changing this. The statusbar is for all purposes temporary and will be removed in some future version of yabai.
