### ISSUE TITLE
Border on fullscreen Safari video window when exiting&entering mission control

### ISSUE THREAD

**Issue by choco** [koekeishiya/yabai#360]
As per title, if you have a fullscreen video window in Safari and switch mission control on and off, when back to the window a border is drawn.

Steps:

1. Open a YouTube video in safari and make it fullscreen
2. Activate mission control
3. Deactivate mission control
4. Border is drawn on fullscreen window

**Comment by koekeishiya** [comment]
This is a bizarre problem. Not really sure how this can be fixed..
