### ISSUE TITLE
question: how to remember always float an app?

### ISSUE THREAD

**Issue by tuananh** [koekeishiya/yabai#361]
how to remember always float an app like Messages?

**Comment by koekeishiya** [comment]
You can use window rules for this, something like:

```
yabai -m rule --add app="^Messages$" manage=off
```

Full docs: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule

PS: I'm not actually sure if the app is called messages.  You can use the query system to retrieve the necessary information when the application is running:

```
yabai -m query --windows
```

**Comment by tuananh** [comment]
Awesome.! Thank you.
