### ISSUE TITLE
How to kill a window?

### ISSUE THREAD

**Issue by Geigerkind** [koekeishiya/yabai#363]
Hey, how can I actually kill a window, like in I3 (command + q)?

**Comment by kinglouie** [comment]
doesn't it make sense to kill the window with macOS default shortcut (cmd +w) ?

**Comment by dominiklohmann** [comment]
`yabai -m window [<window selector>] --close`

**Comment by Geigerkind** [comment]
> doesn't it make sense to kill the window with macOS default shortcut (cmd +w) ?

Probably, its a work laptop, so I given that this particular laptop model does not have nice linux drivers, I try to get the best out of it :D So, I dont know much about MacOS.

Thanks for answering!

**Comment by Geigerkind** [comment]
Btw. Nice name. It literally described my situation when I discovered that there are no linux drivers :D
