### ISSUE TITLE
tiling delay when dragging a Chrome tab to create new Windows to another monitor

### ISSUE THREAD

**Issue by tuananh** [koekeishiya/yabai#364]
Minor bug really.

If i create new windows manually by using Command + N, it would be tiled immediately

However when i drag a tab to another monitor, there is a delay of (3-5 seconds) for the new windows to get tiled.

OS: catalina 10.15.2
yabai: head at this commit https://github.com/koekeishiya/yabai/commit/e693b905dc9696b6021b054606a92e0ca22f8b08

**Comment by koekeishiya** [comment]
This is a Chrome / macOS issue as far as I know.
