### ISSUE TITLE
manage=off setting not being applied for title= field

### ISSUE THREAD

**Issue by snario** [koekeishiya/yabai#366]
I have the following setting in my `yabairc`:

```
yabai -m rule --add app="Google Chrome" title="MetaMask Notification" manage=off
```

However these windows with that title still get tiled.

My app-specific rules work fine, however, like this one:

```
yabai -m rule --add app="System Preferences" manage=off
```

**Comment by dominiklohmann** [comment]
Rules don't get triggered when a window title changes. Use a signal instead with `event=window_title_changed`.

**Comment by snario** [comment]
Thanks, that seemed to work!

After your comment, I tried this too, but it didn't work, do you know why?

```bash
yabai -m signal --add event=window_created \
  app="Google Chrome" \
  title="MetaMask Notification" \
  action=`yabai -m window \${YABAI_PROCESS_ID} --toggle float`
```

**Comment by dominiklohmann** [comment]
The PID is not a valid window selector.

**Comment by snario** [comment]
Doh... Makes sense.

Trying this now on 2.1.3 but also not seeming to work:

```bash
yabai -m signal --add \
  label=keep-metamask-small \
  event=window_created \
  action="
    yabai -m query --windows \
    | jq -r '.[] | select(.pid | tostring == env.YABAI_PROCESS_ID).id' \
    | xargs -I{} yabai -m window {} --toggle float
  "
```

**Comment by snario** [comment]
Makes sense, however now I am trying to get the window selector, and running into an issue (on 2.1.3).

```bash
yabai -m signal --add \
  label=keep-metamask-small \
  event=window_created \
  app="Google Chrome" \
  title="MetaMask Notification" \
  action="
    yabai -m query --windows \
    | say \
    | jq -r '.[] | select(.pid | tostring == env.YABAI_PROCESS_ID).id' \
    | xargs -I{} yabai -m window {} --toggle float
  "
```

**Comment by dominiklohmann** [comment]
Look at the docs for the signal events: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#673-event

> **window_title_changed**
> Triggered when a window changes its title. Eligible for both app= and title= filter. Passes one argument: `$YABAI_WINDOW_ID`

The signal doesn't carry the process id of the windows application, but rather the window id of the window whose title changed.

The query itself is already aa valid window selector, although you'd still have to check whether the window already is floating before toggling it.
