### ISSUE TITLE
config --space do not work correctly with external monitor

### ISSUE THREAD

**Issue by Morniak** [koekeishiya/yabai#367]
Hi, 

the `--space` option in the .yabai config file seems to ignore spaces on a second monitor and mess with space numbers.

With the following configuration, the 120 padding is applied to the screen named "Desktop 1" in mission control. I tried to change the value after the --space option but the screens on the external monitor seems to be out of reach.

 ```
yabai -m config layout                       bsp
yabai -m config top_padding                  50
yabai -m config bottom_padding               50
yabai -m config left_padding                 50
yabai -m config right_padding                50
yabai -m config window_gap                   20

yabai -m config --space 2 top_padding     120
yabai -m config --space 2 bottom_padding  120
yabai -m config --space 2 left_padding    200
yabai -m config --space 2 right_padding   200
yabai -m config --space 2 window_gap      50
```

```
External Monitor:
[Fullscreen App] - [Fullscreen App] - [Desktop 3]

Macbook screen:
[Fullscreen App] - [Desktop 1] - [Desktop 2]
```

OS: Catalina 10.15.1

⚠️ The System Integrity Protection is not disabled on my computer.

**Comment by koekeishiya** [comment]
yabai counts Fullscreen App spaces, because it is necessary/useful to interact with them for other purposes. The index is then simply increased by 1 for each space.


```
External Monitor:
[Fullscreen App] (space 4) - [Fullscreen App] (space 5) - [Desktop 3] (space 6)

Macbook screen:
[Fullscreen App] (space 1) - [Desktop 1] (space 2) - [Desktop 2] (space 3)
```

**Comment by Morniak** [comment]
Coming from chunkwm I was not expecting this behavior. 
Thanks for the answer 👍
