### ISSUE TITLE
List all rules

### ISSUE THREAD

**Issue by entropitor** [koekeishiya/yabai#370]
It would be nice if you can get a dump of yabai rules

**Comment by koekeishiya** [comment]
I am not against implementing this, but curious why this is useful? Do you change rules a lot during runtime?

**Comment by entropitor** [comment]
It's okay now. I thought I potentially had configured a rule in the past that would move my terminal to space 3, but it turned out to be set to `Dock > Assign To > ...`. I wasn't sure if there was one or not so that's why I asked here for a way to list all rules.

So feel free to close it, if you don't think this is useful.

**Comment by koekeishiya** [comment]
I think I'll close this for now.

**Comment by henrik242** [comment]
@koekeishiya So I assume there's no way of listing all the active rules?  I was just looking for this myself.  It's would be nice to have when experimenting with different rules.

**Comment by lenntil** [comment]
#511
