### ISSUE TITLE
Using display UUID and/or ID for DISPLAY_SEL

### ISSUE THREAD

**Issue by aiguofer** [koekeishiya/yabai#372]
Hey, thanks for all your work! The addition of the UUID from #346 seems awesome and I think it'll help me improve my setup significantly by allowing me to have a way to fake assigning spaces to specific displays. However, currently I will have to write a complicated bash function to search for the index of the display I want and then use that to move spaces to the display.

It'd be great if I could pass in the UUID or ID of the display as the DISPLAY_SEL similar to how I can use the LABEL for SPACE_SEL or the window ID for WINDOW_SEL.

**Comment by koekeishiya** [comment]
I think a compromise here could be by adding labels to displays as well. The default label could be the display uuid. I need to give this some thought to avoid potential future ambiguities.

**Comment by dominiklohmann** [comment]
Or a more general `key=value` selector for everything? That would make so many things easier, but I'm not quite sure how feasible this is with yabais current architecture.

**Comment by aiguofer** [comment]
Either of those proposals would definitely help for my situation!

**Comment by koekeishiya** [comment]
Closing this in favor of #550. Support for labels can be discussed/tracked in #1616
