### ISSUE TITLE
Command to move app to a different space and follow it? Currently if I send an app to a new space I have to manually move to that space

### ISSUE THREAD

**Issue by rublev** [koekeishiya/yabai#373]
I can't find a reference for the command I need to use to move an app to a new space and automatically follow focus. `yabai -m window --space X` doesn't do it. I tried also changing the `mouse_follow_focus` to `on` but it had no effect. There is nothing to show in my configs as my yabai config is just the default config and skhd I only have this one command I'm testing right now as I'm just setting things up.
  
Thanks!

**Comment by koekeishiya** [comment]
The following chain should do what you want: `yabai -m window --space  1; yabai -m space --focus 1`

**Comment by rublev** [comment]
Thanks! What syntax is that with the `;`? Wouldn't it be `&&`?

**Comment by koekeishiya** [comment]
IIRC when chaining commands with `;` the second command will run even if the previous command fails. With `&&` you get short-circuiting, so the second command won't run if the previous one failed. I suppose `&&` would be more correct in this case.
