### ISSUE TITLE
[question] how to switch from column split to horizontal split?

### ISSUE THREAD

**Issue by tuananh** [koekeishiya/yabai#374]
how to switch from column split to horizontal split?

**Comment by webframp** [comment]
I use: `yabai -m window --toggle split` and have this mapped in `.skhdrc` like:

```
alt - space : yabai -m window --toggle split
```

**Comment by disrupted** [comment]
> I use: `yabai -m window --toggle split` and have this mapped in `.skhdrc` like:
> 
> ```
> alt - space : yabai -m window --toggle split
> ```

weird, this one doesn't work but the default `alt - e` does

**Comment by tuananh** [comment]
Thanks
