### ISSUE TITLE
How do you focus on the application once you send it to new a space and focus on that space? I still have to 'select' the space.

### ISSUE THREAD

**Issue by rublev** [koekeishiya/yabai#377]
select the app*

**Comment by rublev** [comment]
I think I solved this.

`# create desktop, move window and follow focus - uses jq for parsing json (brew install jq)
# fix for above solution, to follow window and focus window
# https://github.com/koekeishiya/yabai/issues/160
shift + cmd - n : yabai -m space --create \
	&& wid="$(yabai -m query --windows --window | jq -r '.id')" \
	&& sidx="$(yabai -m query --spaces --display | jq -r 'map(select(."native-fullscreen" == 0))[-1].index')" \
	&& yabai -m window "${wid}" --space "${sidx}" \
	&& yabai -m window --focus "${wid}"

# create desktop and follow focus - uses jq for parsing json (brew install jq)
cmd + alt - n : yabai -m space --create \
	&& wid="$(yabai -m query --windows --window | jq -r '.id')" \
	&& sidx="$(yabai -m query --spaces --display | jq -r 'map(select(."native-fullscreen" == 0))[-1].index')" \
	&& yabai -m window "${wid}" --space "${sidx}"

# cycle through spaces
# https://github.com/koekeishiya/yabai/issues/303
alt - c : yabai -m space --focus "$(yabai -m query --spaces --display \
    | jq 'reverse | nth(index(map(select(.focused == 1))) - 1).index')"

# cycle backwards
alt - z : yabai -m space --focus "$(yabai -m query --spaces --display \
    | jq 'nth(index(map(select(.focused == 1))) - 1).index')"
`

**Comment by boof-fo** [comment]
doesn't work anymore because of a change in the JSON that `yabai -m query --spaces --display` returns.

updated commands:
```
# create desktop, move window and follow focus - uses jq for parsing json (brew install jq)
shift + cmd - n : yabai -m space --create \
        && wid="$(yabai -m query --windows --window | jq -r '.id')" \
        && sidx="$(yabai -m query --spaces --display | jq -r 'map(select(."is-native-fullscreen" == false))[-1].index')" \
        && yabai -m window "${wid}" --space "${sidx}" \
        && yabai -m window --focus "${wid}

# create desktop and follow focus - uses jq for parsing json (brew install jq)
cmd + alt - n : yabai -m space --create \
        && sidx="$(yabai -m query --spaces --display | jq -r 'map(select(."is-native-fullscreen" == false))[-1].index')" \
        && yabai -m space --focus "${sidx}"
```
