### ISSUE TITLE
Allow DISPLAY_SEL and SPACE_SEL in rules

### ISSUE THREAD

**Issue by aiguofer** [koekeishiya/yabai#378]
Possibly related to #372. I'd like to be able to use labels instead of indexes for setting up spaces. In order to do this, I need to be able to pass in a label to my rules.

Alternatively, I could assign a command to call at rule execution time to determine the label. For example:

```
function yabai_get_space_index() {
    echo $(yabai -m query --spaces | jq ".[] | select(.label == \"$1\") | .index")
}

yabai -m rule --add app="Google Play Music Desktop Player" space=$(yabai_get_space_index s10)
```

This all ultimately relates to #365. The main problem lies around the fact that indexes are managed by MacOS and are dynamic (for both spaces and displays), whereas I can create/manage labels the way I want.

**Comment by koekeishiya** [comment]
Implemented on master. The display and space property of a rule now take DISPLAY_SEL and SPACE_SEL respectively.

**Comment by koekeishiya** [comment]
Part of v2.3.0
