### ISSUE TITLE
Executing shell script with command not working

### ISSUE THREAD

**Issue by rublev** [koekeishiya/yabai#381]
first attempt (not working)

```bash
ubersicht="$(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut     -d. -f1)"
alt - x: osascript -e 'tell application "'"$ubersicht"'" to refresh'
```  

second attempt (not working)
refresh-ubersicht.sh (chmod +x)
```bash
#!/usr/bin/env bash

set -e

ubersicht="$(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut     -d. -f1)"
echo $ubersicht
osascript -e 'tell application "'"$ubersicht"'" to refresh'
```
command 1 (not working): `alt - x : '/Users/username/.dotfiles/yabai/refresh-ubersicht.sh'`
command 2 (not working): `alt - x : '~/.dotfiles/yabai/refresh-ubersicht.sh'`
command 3 (not working): `alt - x : /Users/username/.dotfiles/yabai/refresh-ubersicht.sh`
command 4 (not working): `alt - x : ~/.dotfiles/yabai/refresh-ubersicht.sh`
  
zsh alias (working)
```bash
# refresh ubersicht pecan style
ubersicht="$(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut -d. -f1)"
# alias ru="osascript -e 'tell application \"'$(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut -d. -f1)'\" to refresh'"
alias ru="osascript -e 'tell application \"'$ubersicht'\" to refresh'"
```

**Comment by dominiklohmann** [comment]
This really isn't an issue with yabai.

Did you consider looking at the stdout / stderr of the parent process to see why and where this fails?

Side note: If your script is named "refresh-ubersicht", then `ps ax | grep sicht` will also catch the script itself. Use something like `pgrep -x` instead (see `man 1 pgrep`).

**Comment by rublev** [comment]
> This really isn't an issue with yabai.
> 
> Did you consider looking at the stdout / stderr of the parent process to see why and where this fails?

don't know enough about system stuff to even know what stdout or stderr is, will look into it.  
  
> Side note: If your script is named "refresh-ubersicht", then `ps ax | grep sicht` will also catch the script itself. Use something like `pgrep -x` instead (see `man 1 pgrep`).  
  
how? its a shell script not an actively running app.

**Comment by rublev** [comment]
> This really isn't an issue with yabai.
> 
> Did you consider looking at the stdout / stderr of the parent process to see why and where this fails?
> 
> Side note: If your script is named "refresh-ubersicht", then `ps ax | grep sicht` will also catch the script itself. Use something like `pgrep -x` instead (see `man 1 pgrep`).

what am I doing wrong with syntactically?  
  
`yabai -m signal --add event=space_changed action="osascript -e 'tell application $(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut -d. -f1) to refresh'"`  
  
trying to get the following working: `# refresh primary display workspaces
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-primary-jsx\"'"`

**Comment by dominiklohmann** [comment]
I suggest reading up on how to refresh individual Übersicht widgets using AppleScript, and discussing further in the repository for the bar you're using.

There is no concise question in this thread about yabai, and it looks like the troubles you're having are not related to yabai either.
