### ISSUE TITLE
How to make all sub-windows of apps float? Like firefox save windows, open/close dialogs etc

### ISSUE THREAD

**Issue by rublev** [koekeishiya/yabai#384]
As title states.

**Comment by dominiklohmann** [comment]
This should happen by default, unless the application sets the wrong role/subrole for the affected window.

If you want to override this, take a look at [window rules](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule).

**Comment by rublev** [comment]
> This should happen by default, unless the application sets the wrong role/subrole for the affected window.
> 
> If you want to override this, take a look at [window rules](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule).

I did take a look at it but I'm not sure how to get the title for all sub windows or anything like that.

**Comment by rublev** [comment]
```bash  
yabai -m rule --add app="^Firefox$" title="^Opening .*$" manage=off  
```

Got it!

**Comment by sagikazarmark** [comment]
Use `^Firefox.*$` for developer edition:

```shell
yabai -m rule --add app="^Firefox.*$" title="^Opening .*$" manage=off
```
