### ISSUE TITLE
no issue, need help drawing status bar on different display

### ISSUE THREAD

**Issue by koin612** [koekeishiya/yabai#385]
Hey,
I was trying to implement [#136](https://github.com/koekeishiya/yabai/issues/136). I've just changed `bar_create_frame function` in `bar.c`

```C
static float bar_create_frame(struct bar *bar, CFTypeRef *frame_region)
{
    uint32_t display_count;
    uint32_t *display_list = display_manager_active_display_list(&display_count);
    if (!display_list) return 0.0f;

    // bar->did = display_manager_main_display_id();
    bar->did = display_list[1];
    CGRect bounds = display_bounds(bar->did);

    float y_offset = 0.0f;
    if (!display_manager_menu_bar_hidden()) {
        CGRect menu = display_manager_menu_bar_rect(bar->did);
        y_offset    = menu.size.height;
    }

    // bar->frame = (CGRect) {{0, 0},{bounds.size.width, 26}};
    bar->frame = (CGRect) {{bounds.origin.x, bounds.origin.y}, {bounds.size.width, 26}};
    CGSNewRegionWithRect(&bar->frame, frame_region);
    free(display_list);
    return y_offset;
}
```

So there are only small changes. When I use `display_manager_main_display_id()` or even set `bar->did` to `display_list[0]`, everything works fine. When I use `display_list[1]` or `display_list[2]`, the status bar looks like this:

<img width="721" alt="Screen Shot 2020-01-24 at 16 38 52" src="https://user-images.githubusercontent.com/8482235/73081895-b63c2e00-3ec8-11ea-95c6-e248b8fe76ae.png">

Here is my output of `yabai -m query --displays`
```Json
[{
	"id":861422024,
	"uuid":"55B7F150-5724-CE51-B73C-0978E11C4C01",
	"index":1,
	"spaces":[1],
	"frame":{
		"x":0.0000,
		"y":0.0000,
		"w":1920.0000,
		"h":1080.0000
	}
},{
	"id":69731910,
	"uuid":"F466F621-B5FA-04A0-0800-CFA6C258DECD",
	"index":3,
	"spaces":[3],
	"frame":{
		"x":-1440.0000,
		"y":180.0000,
		"w":1440.0000,
		"h":900.0000
	}
},{
	"id":1127272441,
	"uuid":"037F37D1-D0BD-E390-07B5-6C7DCF83C8BA",
	"index":2,
	"spaces":[2],
	"frame":{
		"x":1920.0000,
		"y":0.0000,
		"w":1920.0000,
		"h":1080.0000
	}
}]
```

appreciate your time and I hope it's ok to ask questions like this in issue-tracker.

**Comment by koekeishiya** [comment]
> // bar->frame = (CGRect) {{0, 0},{bounds.size.width, 26}};
    bar->frame = (CGRect) {{bounds.origin.x, bounds.origin.y}, {bounds.size.width, 26}};
    
This line should not be edited.
If you want to actually change the x or y position of the bar on the screen, the correct lines to modify are the calls to `SLSSetWindowShape` in `bar_refresh` and `SLSNewWindow`  in `bar_create`.
