### ISSUE TITLE
How to have windows default to tiling horizontally? 

### ISSUE THREAD

**Issue by ChrisOlsonFilms** [koekeishiya/yabai#386]
I have read through the documentation many times, and I feel like I"m missing something so incredibly simple.

Whenever a window tiles currently, it will tile into a tall layout. I would like the default option to be horizontal instead. Right now I have to constantly toggle split in order to get the layout that I want. Once toggled to the one I want, if I restart, it goes back to tiling in tall form.

I'm surely missing something incredibly obvious with this.

**Comment by johnallen3d** [comment]
Maybe you can execute a toggle at the end of your `yabairc`?

**Comment by dominiklohmann** [comment]
You can create a signal that toggles the split if it's vertical. It's not a trivial setting to change right now, since it defaults to using the golden ratio to determine the next split.

**Comment by hrvstr** [comment]
How would this signal look like? I can't see any event that has anything to do with the split options?

**Comment by dominiklohmann** [comment]
You'd need to use `event=application_launched` for restored windows and `event=window_created` for newly created windows. Then, for all windows that are restored or created, check whether their split is vertical, and if it is toggle it to horizontal.

**Comment by hrvstr** [comment]
Sadly I have no clue how to do this... It would be nice to have some more complex example rules and signals listed somewhere. I have jq installed and a basic understanding of JSON but no idea where to start learning how to write this stuff.

**Comment by hrvstr** [comment]
I almost there, but it looks like I am still doing something wrong here.

I am using this signal but it does not seem to work although there are no errors in the log. I suspect that it has something to do with the quotes but I think I tried all possible combinations of single and double quotes.

```
yabai -m signal --add \
	label=launch-split \
	event=application_launched \
	action="yabai -m query --windows --window $YABAI_WINDOW_ID \
    | jq -re '.split == "horizontal"' \
	 && yabai -m window $YABAI_WINDOW_ID --toggle split
	"
```

Running this command on a window with horizontal split is working as intended:
`yabai -m query --windows --window | jq -re '.split == "horizontal"' && yabai -m window --toggle split`

**Comment by koekeishiya** [comment]
Either the quotation is wrong when inlining the script or there is a bug in signal processing when parsing key-value pairs, because your script has == in it. Not sure which one is at fault here.
You can paste it in a shell-script and simply have your signal execute the script for now.

**Comment by hrvstr** [comment]
Thanks, got it working now!
It's probably the quotation, i have to read up on this topic...

@ChrisOlsonFilms you can use this. You just have to swap horizontal with vertical as I am doing the opposite.

### .yabairc
```
yabai -m signal --add \
	label=launch-split \
	event=application_launched \
	action='~/Documents/script/yabai/auto-split.sh'
	
yabai -m signal --add \
	label=create-split \
	event=window_created \
	action='~/Documents/script/yabai/auto-split.sh'
```

### auto-split.sh
```
#!/usr/bin/env bash
yabai -m query --windows --window $YABAI_WINDOW_ID | jq -re '.split == "horizontal"' && yabai -m window $YABAI_WINDOW_ID --toggle split
```

**Comment by dominiklohmann** [comment]
There's still a slight mistake in there: The `event=application_launched` signal does not carry `$YABAI_WINDOW_ID`, which then evaluates to an empty string in the signals action, causing it to act on the focused window.

If multiple windows are restored, this is incorrect behavior.

Instead, you should use the `$YABAI_PROCESS_ID` that the signal actually carries and query for all windows, filtering by their process id to get their window id, and then change the split on that.
