### ISSUE TITLE
yabai-msg: failed to connect to socket..

### ISSUE THREAD

**Issue by lucian303** [koekeishiya/yabai#388]
Installed yabai. Added the dock extension (SIP is off) added the accessibility permission but it still doesn't work. OSX 10.14.6. yabai 2.2.2

```
$ brew services start yabai
Service `yabai` already started, use `brew services restart yabai` to restart.

lucian303 at Lucian in ~
$ yabai -m config focus_follows_mouse autofocus
yabai-msg: failed to connect to socket..
```

**Comment by dominiklohmann** [comment]
Can you remove the socket files, then try again?

```sh
rm /tmp/yabai_${USER}.socket
rm /tmp/yabai-sa_${USER}.socket
brew services restart yabai
```

**Comment by lucian303** [comment]
This seems to be caused by a missing configuration file. 

```
touch ~/.yabairc
chmod +x ~/.yabairc
```

Those commands might be better off in the installation section...

**Comment by gunar-gessner-qatalog** [comment]
I had the same problem. It's a tiny bit confusing that you need an init file in order to be able to send commands.

**Comment by koekeishiya** [comment]
This is just an outdated requirement because config commands worked different initially. It has been fixed on master.

Sent from my iPad

On 7 Feb 2020, at 15:43, Gunar Gessner <notifications@github.com> wrote:

﻿

I had the same problem. It's a tiny bit confusing that you need an init file in order to be able to send commands.

**Comment by 4b6169736572** [comment]
I have the same problem, I tried deleting the `.socket`, I have `.yabairc` in my home directory, I'm running the latest version, and I have SIP off. I tried doing all of the steps mentioned above then restarting which also didn't work.

**Comment by goulashsoup** [comment]
Just had this error after removing the socket, running `yabai --restart-service` resolved it.

**Comment by rikhuijzer** [comment]
For me the fix was to allow screen recording. There was still a permission request open in the background.
