### ISSUE TITLE
Option to set "Desktop on Display n"

### ISSUE THREAD

**Issue by henrik242** [koekeishiya/yabai#391]
Is it possible to set the *Dock -> Option -> Desktop on Display n* option?

<img width="623" alt="Screenshot 2020-01-29 at 10 21 11" src="https://user-images.githubusercontent.com/129931/73343665-47245800-4281-11ea-8270-1f5c5d535783.png">

I know that I can move an app using `yabai -m rule --add app="^Firefox.*$" space=5`, but I'd like that Dock option to switch correctly as well.

**Comment by dominiklohmann** [comment]
That doesn't sound like a good idea to me, as these do different things. Rules don't operate on applications, but rather on windows by a set of restrictions (including the application name).

The Dock setting makes it so new windows for a given application spawn on the assigned desktop. That's not something that can currently be configured using yabai, which can only handle windows after they have finished spawning.

**Comment by koekeishiya** [comment]
There is actually partial support for this in yabai already, but it is not exposed to the user in any way.
See: https://github.com/koekeishiya/yabai/blob/master/src/space_manager.c#L755 and https://github.com/koekeishiya/yabai/blob/master/src/space_manager.c#L760

This has the same issue as with other Dock related functionality in that it will not update the state of the Dock (menu visuals and persistence through reboot IIRC). This could obviously be fixed by doing some more RE of the Dock, but I can't be bothered to do this. I think the rules system of yabai is more flexible and it is what I personally use.

**Comment by henrik242** [comment]
@koekeishiya Thanks for the explanation! The reason I ask for this is that sometimes macOS changes these settings.  I might have locked one app to Display 3, but next time I plug in my monitors, the checkmark is next to Display 2 instead.  Fairly annoying.  (That's what I use yabai for now: When macOS decides to put my apps the wrong places, I have a hotkey that moves them to the correct ones.)

**Comment by koekeishiya** [comment]
>The reason I ask for this is that sometimes macOS changes these settings. I might have locked one app to Display 3, but next time I plug in my monitors, the checkmark is next to Display 2 instead. 

This sounds to me like the display arrangement is different the second time you connect your display.
The mapping stored by macOS uses the UUID of the display, and it notices that it is no longer the 3rd display, but is now the 2nd, and so the visuals change to reflect that. I can't confirm that this is what is happening, but it would explain what you're experiencing.

**Comment by henrik242** [comment]
@koekeishiya It can happen even though I just wake my 16" macbook up from sleep, without any disconnection/connection of the two monitors.  It happened on my previous 15" macbook as well, which had different monitors attached.

When the checkmark is on the wrong display, weird things happen even though I have used yabai to move applications to the correct monitor.  Just now I right-clicked Firefox on display 3, but the menu appeared on display 2.

**Comment by koekeishiya** [comment]
Hmm that sounds weird to me, but then again I never really used that functionality.

**Comment by henrik242** [comment]
@koekeishiya Yeah, I guess this setup is not common enough for Apple to fix it. But if you use two external monitors I'm willing to bet that it'll happen to you once in a while too.
