### ISSUE TITLE
topmost hides popup modal

### ISSUE THREAD

**Issue by qaisjp** [koekeishiya/yabai#395]
Hello!

Having topmost enabled on an application also hides any popup modals it creates. Is there any way around this?

![image](https://user-images.githubusercontent.com/923242/73608586-ba4d0780-45bc-11ea-9543-3d67f7501c58.png)

(If I paste into iTerm and have iTerm set to `topmost`, this popup is obscured by the terminal window!)

**Comment by koekeishiya** [comment]
There is already functionality implemented to deal with this situation: https://github.com/koekeishiya/yabai/blob/master/src/window_manager.c#L1335

This issue seem to appear for some windows that we to my knowledge are unable to set the window layer for - or they are not reported to us as windows being created. I'm not sure if this is fixable.

**Comment by koekeishiya** [comment]
I'm unable to reproduce this in the latest version.
