### ISSUE TITLE
Controlling windows with mouse pointer

### ISSUE THREAD

**Issue by pcr910303** [koekeishiya/yabai#4]
I am currently using chunkwm, and is using the feature to [move & resize windows with mouse](https://github.com/koekeishiya/chunkwm/tree/master/src/plugins/tiling#set-binding-to-use-for-moving-windows-with-the-mouse) extensively.

By looking around the repo, it looks like there is currently no support for such feature.
I would like to ask if features related to mouse are going to be implemented.

Also, if such features will be implemented, I would appreciate if I can move windows in a more controlled fashion.
For example, if there is a window layout like:

```
+---------------+---------------+
|               |               |
|               |       B       |
|               |               |
|       A       |---------------|
|               |               |
|               |       C       |
|               |               |
+---------------+---------------+
```
and I would like to move window B to the left, the current chunkwm mouse controlling only allows this:
```
+---------------+---------------+
|               |               |
|               |       A       |
|               |               |
|       B       |---------------|
|               |               |
|               |       C       |
|               |               |
+---------------+---------------+
```
However I would really appreciate if this is possible:
```
+---------------+---------------+
|               |               |
|       A       |               |
|               |               |
|---------------|       C       |
|               |               |
|       B       |               |
|               |               |
+---------------+---------------+
```

**Comment by koekeishiya** [comment]
If you build from master there is functionality for moving and resizing windows with the mouse works pretty much the same as the chunkwm version.

```
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
```

*move*: allows you to move a window by clicking anywhere in the window.
*resize*: allows you to resize a window from its corners, or adjust the allocated region in a bsp-layout.

New in *yabai*:

If a managed window is moved on top of another window, and the mouse-button is released, they will swap places. If a managed window is resized and the mouse-button is released, it will, if in a bsp-layout, adjust the allocated region in the bsp-layout. This will happen regardless of using the mouse action *move* and *resize* mentioned above. That means that we detect changes performed through the *native macOS window interactions*, such as simply moving a window by dragging its titlebar, or using any of the native resize-handles.

**Comment by pcr910303** [comment]
@koekeishiya The new feature in yabai is **awesome**! 
I really appreciate that....
(As I don't want to open a new issue for this) Will yabai run on macOS High Sierra 10.13.6?̊̈

**Comment by koekeishiya** [comment]
Unfortunately I have no plans to support High Sierra, mainly because I don't have a version of High Sierra to reverse engineer and experiment with.

**Comment by pcr910303** [comment]
@koekeishiya Okay.... 😞
Currently our school wifi doesn't work with macOS Mojave... It looks like the adoption of yabai will be delayed.... :-(
