### ISSUE TITLE
Speeding up window changes

### ISSUE THREAD

**Issue by capaldo** [koekeishiya/yabai#40]
Is this possible? It seems to me a longer delay exists between switching windows in comparison to chunkwm

**Comment by koekeishiya** [comment]
It may be a bit slower because we are telling the Dock to focus the window for us instead of using the accessibility API. This is to avoid the focus issue when multiple displays are used.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by koekeishiya** [comment]
On master we no longer focus a window through Dock.app, so the change happens pretty much instantaneous as it did in chunkwm. I have managed to solve the focus issue with multiple displays in a different way, #102
