### ISSUE TITLE
Space automatically moves when app opens another app

### ISSUE THREAD

**Issue by thinceller** [koekeishiya/yabai#401]
Previously it wasn't, but after disabling System Integrity Protection it started to behave like a title.

For example,
1. Open Google Chrome in space 1, terminal in space 2, Slack app in space 3. (I'm in space 3 now)
2. Click URL in Slack.
3. Link appears in default browser: Chrome. (Moved to space 1)
4. If I confirm, at this point Slack has moved to space 2 and the terminal has moved to space 3.

I think that the windows in the same space move together, so the spaces are swapped.

Is this the default behavior?

I tried the following, but the behavior did not change.
- Run yabai without skhd
- Delete all yabai settings and run `brew services restart yabai`

### My environment
- macOS 10.15.3
- yabai 2.2.2

**Comment by koekeishiya** [comment]
This is a macOS thing and has nothing to do with yabai, see https://github.com/koekeishiya/yabai/wiki/Tips-and-tricks#fix-spaces-reordering-automatically for how to resolve this.

**Comment by thinceller** [comment]
@koekeishiya 
Thanks! That help resolved this.
