### ISSUE TITLE
Dragging window in vertical split toggles split type instead of swapping

### ISSUE THREAD

**Issue by Peeja** [koekeishiya/yabai#402]
This doesn't always happen, but it's happening right now, and seems to be stable and reproducible. I'm not sure when it can be reproduced and when it can't.

When I have two windows open side by side, dragging one over the other should swap them, but instead, the split type changes from vertical to horizontal.

![yabaibug](https://user-images.githubusercontent.com/2407/73851265-2f0d8500-47fb-11ea-94cf-60d223fa7c5a.gif)

I then typically use `yabai -m window --toggle split` to get back to a vertical split, and `yabai -m space --mirror y-axis` or `yabai -m window --swap east` to do what I wanted; that works fine.

Note in a horizontal split, dragging to swap works fine.

The recording above is on `2.2.2`, but I've reproduced it on `master` ([`1452ddc`](https://github.com/koekeishiya/yabai/commit/1452ddc6e917e379614950515404bf627345b79a)).

**Comment by koekeishiya** [comment]
This is intentional behaviour - the action is based on the location of the drop in the target window. See https://github.com/koekeishiya/yabai/issues/142 for history.

I agree that it might be hard to really get this without either reading the referenced issue or just simply experimenting and observing the behaviour. This should probably be either documented in the wiki or get a visual indicator, somehow.

**Comment by dominiklohmann** [comment]
Maybe the scale could be made configurable within a range of 0 to 1, where the cutoff between swap and warp is multiplied with the configured scalar.

0 then means always swap, 1 means always warp. Right now we’re at a fixed 0.5 on that scale.

**Comment by Peeja** [comment]
Oh, I see. I assumed it was a bug because I couldn't make it work from horizontal back to vertical, but I guess I wasn't trying hard enough.

Now that I know how it works, I like it! One frustrating thing, though, is that my mouse cursor is naturally at the top of the window, because that's where I can drag it from, so to swap, I have to pull it way down to the middle of the other window. Is there a tool people like that would let me drag a window by grabbing it from anywhere, and not just the title bar? That feels like a thing that exists, but I can't come up with it off the top of my head.

**Comment by dominiklohmann** [comment]
> Is there a tool people like that would let me drag a window by grabbing it from anywhere, and not just the title bar?

That's built-in. Hold <kbd>fn</kbd>, then drag the window from anywhere (does not raise the window).

It's also built into macOS as a hidden setting:

```sh
defaults write -g NSWindowShouldDragOnGesture -bool true
```

Now hold <kbd>ctrl</kbd> + <kbd>cmd</kbd> and drag the window from anywhere (always raises the window).

**Comment by Peeja** [comment]
That's fantastic, thanks!
