### ISSUE TITLE
Windows occasionally shift up and down for no apparent reason

### ISSUE THREAD

**Issue by Peeja** [koekeishiya/yabai#403]
I can't come up with a way to reproduce this, but it's been happening occasionally for a while for me. It looks like, for no reason I can see, the status bar is turned off and on again quickly, or the space set aside for the status bar is removed and added back quickly. (It's fast enough that I haven't been able to see whether the status bar itself remains visible as it happens.)

If you have any ideas to help me debug the problem or find diagnostic info, I'd love to hear it.

**Comment by koekeishiya** [comment]
So this is either yabai crashing (that would also cause your window layout etc to reset), and you will find a crash dump in Console.app in the Crash Reports pane.

The dimensions of the space that is utilized to tile windows is altered when the Dock or Menubar autohidden setting is toggled, or if the size of the Dock is changed etc. So this might also be what you are experiencing.

**Comment by Peeja** [comment]
I don't see a crash log. :/

Is there other debug output somewhere that would help?

**Comment by koekeishiya** [comment]
You can enable debug output by running `yabai -m config debug_output on` but I don't think it will give any information that is useful for trying to track down this issue - maybe it's worth a shot though.

It's hard for me to reason about what is happening and where it would help to add additional debug information as well, as there isn't really much information to work with.

**Comment by koekeishiya** [comment]
Is this still a thing in the latest version?

**Comment by Peeja** [comment]
I haven't been able to do everything I'll need to do to upgrade yet, so I'm not sure. If you'd like to close this for now to keep things tidy around here, I can come back if it's still happening after I upgrade.

**Comment by eraserhd** [comment]
I just got a new monitor, and discovered it has an option called "Pixel Orbiting," where it shifts the image by up to two pixels at random intervals to avoid burn-in.  It was enabled by default, but I just started noticing it.  I post here _just in case_ this is what is happening.

**Comment by koekeishiya** [comment]
That seems reasonable to me. There is nothing in yabai that I can think of that would cause the mentioned symptomps. Closing this.
