### ISSUE TITLE
Sticky, topmost, float windows lose focus when the space changes

### ISSUE THREAD

**Issue by micthiesen** [koekeishiya/yabai#405]
Sorry if this is the wrong place to post, or if this is how yabai is intended to work. Most of my windows are managed by bsp or float but _not_ sticky. I have a few that are sticky, and it would be really nice if they didn't lose focus when switching to a new space/desktop. I also have `topmost=on` set but it doesn't seem to help.

A workaround using signals would also be great. Thank you.

**Comment by koekeishiya** [comment]
From what I can tell this is default macOS behaviour. Upon a space switch, it will focus the window that was previously focused on that space - which does not seem to consider the now sticky window.

I would imagine you could maybe try to add subscribe to the space_changed sigal, look for sticky windows and focus the first(?) located sticky window, or whatever matches your criteria.

**Comment by aymane-eljerari** [comment]
For anyone else looking to add this signal:

`yabai -m signal --add event=space_changed action="sticky_id=\$(yabai -m query --windows --space | jq 'map(select(.[\"is-sticky\"] == true)) | .[0].id') && yabai -m window --focus \$sticky_id"`
