### ISSUE TITLE
Yabai Space Focus Stops Working After Upgraded To Catalina

### ISSUE THREAD

**Issue by nuynait** [koekeishiya/yabai#406]
Everything works before then I upgraded to Catalina, and it stops working. I tried: 
`brew uninstall yaibai` 
`brew install yaibai` 
`brew services start yaibai`

`brew uninstall skhd`
`brew install skhd`
`brew install skhd`

`yaibai -m space --focus 1` not working no matter which number I use. I binds it to option 1 to option 0, it doesn't work anymore. Everything else seems to be fine. 

I checked `csrutil status` and returns `System Integrity Protection status: disabled.`

Version for yaibai: v2.2.2

Version for skhd: 0.3.5 

Any hint would be really appreciated. Thanks a lot. :)

**Comment by koekeishiya** [comment]
See issue #275

Sent from my iPhone

On 9 Feb 2020, at 05:45, Jerry Shan <notifications@github.com> wrote:

﻿

Everything works before then I upgraded to Catalina, and it stops working. I even tried
brew uninstall yaibai
brew install yaibai
brew services start yaibai

brew uninstall skhd
brew install skhd
brew install skhd

yaibai -m space --focus 1 not working no matter which number I use. I binds it to option 1 to option 0, it doesn't work anymore. Everything else seems to be fine.

I checked csrutil status and returns System Integrity Protection status: disabled.

Version for yaibai: v2.2.2

Version for skhd: 0.3.5

**Comment by nuynait** [comment]
Sorry. Don't know why I missed this issue. Problem solved. Thanks a lot. 👍

**Comment by tuananh** [comment]
@nuynait wait, how did you fix it?

**Comment by koekeishiya** [comment]
Most likely all you have to do is reinstall the scripting-addition. `sudo yabai --install-sa`

**Comment by tuananh** [comment]
@koekeishiya ah thanks.

I was hesistated by disabling SIP. So far I get by just fine without it, until I use this feature.
