### ISSUE TITLE
Zathura window not recognized

### ISSUE THREAD

**Issue by Zeta611** [koekeishiya/yabai#408]
I am having trouble yabai to work with zathura (a PDF viewer with vi-like keybindings).
I tried `rule --add app=zathura manage=on` but it doesn't work.
(I'm aware of #249 and #86)

As mentioned [here](https://github.com/koekeishiya/yabai/issues/249#issuecomment-531289815_) by @koekeishiya 
> One is at the process level, where some processes are marked as background-only (such as daemons). Sometimes applications don't have their process-type properly set up during launch (depending on how they were launched). 
... The first issue is not solvable. ...

, zathura indeed seems to be recognized as a background only app:
```
EVENT_HANDLER_DAEMON_MESSAGE: msg 'rule --add app=zathura manage=on'
process_handler: zathura was marked as background only! ignoring..
```

I'm not quite familiar with process info, but is there a way to change `LSBackgroundOnly` key of a running process in order to make zathura recognized as a foreground app?
I tried to figure this out using `lsappinfo`, but it prompts that zathura is a foreground app:
```
❯ lsappinfo info -app zathura
"zathura" ASN:0x0-0x92092:
    bundleID=[ NULL ]
    bundle path=[ NULL ]
    executable path="/usr/local/bin/zathura"
    pid = 5717 type="Foreground" flavor=3 Version=[ NULL ]  fileType="????" creator="????" Arch=x86_64
    checkin time = 2020/02/11 15:37:01 ( 8 minutes, 45.3827 seconds ago )
```

Any help or suggestion is appreciated!

**Comment by SebastienWae** [comment]
I don't think it's possible because zathura is using XQuartz.
See the issues from chunkwm that should still apply to yabai, [chunkwm#163](https://github.com/koekeishiya/chunkwm/issues/163) and [chunkwm#285](https://github.com/koekeishiya/chunkwm/issues/285)

**Comment by dominiklohmann** [comment]
XQuartz is deprecated. Ask the zathura devs.

**Comment by Zeta611** [comment]
I didn’t know about the issues from chunkwm, thank you! I’ll close this as it seems to be an issue of Zathura.

**Comment by drselump14** [comment]
recent zathura is built with gtk.. The zathura itself needs osx integration to be detected by window manager... I've managed to enable  the detection from moom, but unfortunately yabai still won't recognize the window

**Comment by drselump14** [comment]
Oh, It seems when I launch yabai after zathura window exists, it will detect the zathura window .. but failed to detect when zathura is opened after  yabai

**Comment by xXBeekeyXx** [comment]
@drselump14 Which zathura version are you talking about? Version number + Macports or homebrew?

**Comment by xXBeekeyXx** [comment]
@drselump14 Nevermind. I just saw you in zathura's project issues. I reinstalled zathura from brew and now it is working!! Thanks for your work man, you're making our life so much easier :))
