### ISSUE TITLE
Running yabai with SIP enabled, will signals work?

### ISSUE THREAD

**Issue by ptomasroos** [koekeishiya/yabai#409]
Thanks for a great software!

I'm running yabai with SIP enabled. I'm trying to get signals to work with a bitbar plugin.

I've added the following signals and is not getting any output in the error or out log. But still its not being triggered at least to my knowledge :)

```
# yabai -m signal --add event=space_changed \
#   action="set SHELL=/bin/sh && open -g \"bitbar://refreshPlugin?name=yabai-window-info.*?.sh\""
# yabai -m signal --add event=window_resized \
#   action="set SHELL=/bin/sh && open -g \"bitbar://refreshPlugin?name=yabai-window-info.*?.sh\""
# yabai -m signal --add event=window_focused \
#   action="set SHELL=/bin/sh && open -g \"bitbar://refreshPlugin?name=yabai-window-info.*?.sh\""
# yabai -m signal --add event=application_activated \
#   action="set SHELL=/bin/sh && open -g \"bitbar://refreshPlugin?name=yabai-window-info.*?.sh\""
```

So my question was if we're suppose to add this to the list below in the WIKI if its a requirement to disable SIP in order for it to work.

```
The following features of yabai require System Integrity Protection to be disabled:

focus/create/destroy space without animation
move space (and its windows) left, right or to another display
remove window shadows
enable window transparency
control window layers (make windows appear topmost)
sticky windows (make windows appear on all spaces)
move window by clicking anywhere in its frame
```

**Comment by koekeishiya** [comment]
Signals should work fine with SIP enabled. I updated the wiki logging entry you added to add some additional explicit information.

Note the following:
To enable debug output make sure that your configuration file contains yabai -m config debug_output on or that yabai is launched with the --verbose flag.

**Comment by ptomasroos** [comment]
It works, my bad was that I had trouble invoking the URL Scheme. Thanks for your response.

And thanks for the debug_output pointer!

Have a great day!
