### ISSUE TITLE
toggle parent (like in chunkwm)?

### ISSUE THREAD

**Issue by bobbybroadcast** [koekeishiya/yabai#41]
Is there anyway to toggle parent like in chunkwm? I was hoping something simple like`yabai -m window --toggle parent` but the docs don't mention it.

**Comment by koekeishiya** [comment]
Implemented on master.

`yabai -m window --toggle zoom-parent`

renamed `yabai -m window --toggle fullscreen` to `yabai -m window --toggle zoom-fullscreen`
