### ISSUE TITLE
Scripting Additions not working

### ISSUE THREAD

**Issue by d3rZauberer** [koekeishiya/yabai#415]
I am trying to get yabai running on macOS 10.15.1 (Catalina). I installed version 2.3.0 via brew. I followed the steps from the wiki on installing the scripting additions, also when running `csrutil status` I get the output: 

> System Integrity Protection status: disabled.

Running `sudo yabai --uninstall-sa` and then reinstalling it again did not work either.

When I run `sudo yabai --load-sa` I get:

> yabai: scripting-addition either failed to load or could not inject payload into Dock.app! Error: -10004  

Also I cannot locate yabai.osax in my /System/Library/ScriptingAdditions folder.

Yabai seems to be running already as a service in the background, resizing windows, but not taking over the Dock.app. 

Thank you very much already!

**Comment by koekeishiya** [comment]
So there are a number of things to start with here..

First of all, to clarify, did you disable SIP using the command specified in the wiki?
The output of `csrutil status` should look like the following on Catalina:
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/6175959/74753839-01035880-5271-11ea-9e24-7f89993870dd.png">

If yours look the same that part is fine, and you might've encountered something like #400, although that specific issue has been resolved. Note the following from the documentation: 
>Path is /System/Library/ScriptingAdditions on macOS High Sierra, and /Library/ScriptingAdditions on Mojave and newer.

So you want to check `/Library/ScriptingAdditions` on your system.

**Comment by d3rZauberer** [comment]
The output of `csrutil status` is the exact same as in the screenshot you provided. 

And yes, the file is actually located at `/Library/ScriptingAdditions/yabai.osax` (Sorry for that) :)

However, even after looking at #400, yabai seems to not be able to inject the scripting addition. Dock is restarting normally and not letting yabai take over. I ran `umask 0000`, installed scripting addition again, but it still isn't working properly.

**Comment by d3rZauberer** [comment]
Update:

After updating macOS to 10.15.3 and reinstalling the scripting-additions, I get the notification from yabai about the payload version. The status bar does not display the items correctly and the default status bar from macOS is still running on top. 

I still could not figure out why the Dock keeps running. I tried terminating it with `killall Dock` and `pkill -x Dock`, but it restarts immediatly after. The tiling mechanism however seems to be running fine and according to the configuration file.

**Comment by koekeishiya** [comment]
The macOS statusbar visibility is a setting in System Preferences that you have to toggle.

If the yabai statusbar is displayed incorrectly that means that the font you selected is eithee not installed or does not contain the symbols you want to display.

You should not prevent the Dock from running. Without it you lose literally 90% of the macOS desktop experience.

Sent from my iPhone


On 24 Feb 2020, at 08:54, d3rZauberer <notifications@github.com> wrote:

﻿

Update:

After updating macOS to 10.15.3 and reinstalling the scripting-additions, I get the notification from yabai about the payload version. The status bar does not display the items correctly and the default status bar from macOS is still running on top.

I still could not figure out why the Dock keeps running. I tried terminating it with killall Dock and pkill -x Dock, but it restarts immediatly after. The tiling mechanism however seems to be running fine and according to the configuration file.

**Comment by d3rZauberer** [comment]
It seems like the update & restart made everything work. 
Thanks for the quick responses and feedback, now I can go and dig through the config :) Already starting to love it!
