### ISSUE TITLE
Only active desktop is rendered when switching space while switching desktop

### ISSUE THREAD

**Issue by Sayrus** [koekeishiya/yabai#417]
Hello,

When switching Desktop (Space) using three finger scroll and switching space with Yabai at the same time, only the active desktop gets rendered which can lead to a black screen.

I do think the problem is not coming from Yabai itself but I think having an issue answering the question might be useful for others.
![desktop](https://user-images.githubusercontent.com/22404472/74748970-4a4bac00-5261-11ea-862f-e3adac1a76d2.gif)

I have not found any issue already addressing this issue.

Best regards,

**Comment by koekeishiya** [comment]
Not really sure how you thought about testing this, but I suppose we should check whether a space transition is in progress before we try to perform a space operation.

**Comment by Sayrus** [comment]
My hand was on the touchpad and the screen went black.
Maybe we should check if there is the Mission control opened. If you change space while mission control is active, you can still select windows from the old space. Either we should block changing space while mission control is active or we should close it if the user decides to switch space.
![desktop](https://user-images.githubusercontent.com/22404472/74847112-81859000-5329-11ea-9930-a33383d138ed.gif)
