### ISSUE TITLE
firefox starts on next display if it space is insufficient

### ISSUE THREAD

**Issue by Sayrus** [koekeishiya/yabai#419]
Hello,

I found another bug when using apps that have problems with resizing on startup. If the space is insufficient (and therefore the window is way outside the screen), the window will spawn on the next display. In reality, it spawns on the right screen but the floating spawning position force it to be moved on the next display.

Steps to reproduce:
```
Have two displays
Split your desktop enough time to have as little space as possible (4 windows are enough on a Mac 13)
Spawn a new Firefox: It will spawn on another display
```

I'd like to show you with a GIF as in my last issue but I don't seem to be able to record two screens using Quicktime.
My tiling is as follows and I try to spawn a new Firefox (4) on 3:
```
+---------------+    +---------------+
|     Window    |    |               |
|_______________|    |       4       |
|   1   | 2 | 3 |    |               |
+---------------+    +---------------+
```

Best regards,

**Comment by dominiklohmann** [comment]
> I'd like to show you with a GIF as in my last issue but I don't seem to be able to record two screens using Quicktime.

You can do that by pressing <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>5</kbd>, then selecting `Record Selected Portion`. It just needs to be rectangular, but that shouldn't be an issue if your displays are side by side.

(Not commenting on the actual issue.)

**Comment by Sayrus** [comment]
### 

> > I'd like to show you with a GIF as in my last issue but I don't seem to be able to record two screens using Quicktime.
> 
> You can do that by pressing cmd + shift + 5, then selecting `Record Selected Portion`. It just needs to be rectangular, but that shouldn't be an issue if your displays are side by side.
> 
> (Not commenting on the actual issue.)

Unfortunately, that does not work. The selection can be across two screen but only one screen gets "highlighted" and actually recorded.

(Not commenting on the actual issue.)

**Comment by koekeishiya** [comment]
This sounds like a macOS problem to me. When a window is created, we grab the space that macOS reports the window to be on, and we simply tile it on that space: https://github.com/koekeishiya/yabai/blob/master/src/event.c#L589

**Comment by Sayrus** [comment]
Interesting, that would make sense. I will try to find a way to spawn new window with a specific position to test this.

**Comment by koekeishiya** [comment]
You can kind of see how macOS handles this independently of yabai. First, stop yabai. Open a window of any application of your choice. Resize the window to become a reasonable size, and slowly drag the window from the top-left corner and move it on to the display to the right. At some point, when a certain area of the window is passed from the original display to the next display, it will shift how the window is highlighted, meaning that macOS now consider that window to belong to the other space/display.

I assume this is the exact same thing that you are observing when you tried to capture a selected region on both displays.

**Comment by Sayrus** [comment]
Definitely coming from macOS. Firefox itself memorize which location and size it want to get to (which might also explains #109 as Firefox sometimes resize itself after Yabai resized it).

I'll close this issue and try to find a way to disable this behavior (maybe system-wide if that exists?)
