### ISSUE TITLE
Feature Request: Ability to Maintain zoom state of Existing windows when Space is Changed

### ISSUE THREAD

**Issue by laxman20** [koekeishiya/yabai#421]
If you have a window in full screen and another window is added to the space, the original window zooms back out. Can the zoom state be maintained in this scenario so that I don't have to manually full-screen it again? The new window would just be layered on top.

It also occurs when you remove a window from the space.

**Comment by koekeishiya** [comment]
Duplicate of https://github.com/koekeishiya/yabai/issues/864
