### ISSUE TITLE
[HELP] Snap windows to grid in tiling mode

### ISSUE THREAD

**Issue by n0ibe** [koekeishiya/yabai#422]
How can I create a command to make a tiling window fill some portions of the screen?

For example I'd like to tell yabai to make the focused window fill the left half of the screen or the lower right quarter of the screen, and adjust every other window accordingly.

I know there's the `--grid` flag for floating windows, but what about tiling ones?

**Comment by koekeishiya** [comment]
There isn’t really a concept of a grid layout for managed windows, but you can adjust the split percentage of the regions, or resize the region towards a given direction.

Sent from my iPhone

On 23 Feb 2020, at 02:55, n0ibe <notifications@github.com> wrote:

﻿

How can I create a command to make a tiling window fill some portions of the screen?

For example I'd like to tell yabai to make the focused window fill the left half of the screen or the lower right quarter of the screen, and adjust every other window accordingly.

I know there's the --grid flag for floating windows, but what about tiling ones?
