### ISSUE TITLE
Set vertical/horizontal screen position before opening new window

### ISSUE THREAD

**Issue by Tandolf** [koekeishiya/yabai#423]
In i3 you can basically say "open the next window as a horizontal window" before you open it. The same goes for vertical (which is the default).

The only functionality i have found is to open the window first it will then open it vertically, then toggle it to become horizontally.

Am i missing something, or is that the general workflow? I would like to be able to open windows directly to horizontal or vertically after my choosing.

**Comment by koekeishiya** [comment]
You can use the `--insert` command.

From the documentation: 
```
DIR_SEL     := north | east | south | west


--insert <DIR_SEL>
Set the splitting area of the selected window. 
If the current splitting area matches DIR_SEL, the action will be undone.
```
