### ISSUE TITLE
window --close doesn't work with kitty hide_window_decorations yes

### ISSUE THREAD

**Issue by aaronenberg** [koekeishiya/yabai#426]
When I have set ``hide_window_decorations yes``in kitty.conf, I can no longer close the focused window with ``yabai -m window --close``. However when I have the kitty setting set to one of ``[titlebar-only, no]`` then closing the window works as expected.

```
yabai-v2.3.0
Catalina 10.15.3
kitty 0.16.0
```

**Comment by dominiklohmann** [comment]
That’s working as expected. All the command does is to look for the first AXCloseButton on the target window and tell the application that it was pressed.

**Comment by aaronenberg** [comment]
That’s odd because ``hide_window_decorations titlebar-only`` hides the titlebar and AXCloseButton along with it leaving just a thin border around the window but it closes like it should. Setting it to ``yes`` hides both the title bar and the border so does that mean the window border is somehow involved too? 

I know I should look at the code but for now I’m just a user.

**Comment by dominiklohmann** [comment]
I suppose this varies based on how Kitty implements it for the various configurations. Even though the close button is not visible in some, it might still be present, which allows yabai to close the window.

Nothing you can really reason about as an end-user, though. It’s just that there is no other good way to close a window without killing it (i.e., allowing the application to close the window itself after receiving a notification that the window is to be closed). You really don’t want to blindly kill windows, that can break all sorts of application state.

**Comment by aaronenberg** [comment]
That was the conclusion I came to as well.
Thanks for the insight and my apologies for the non-issue ticket. This was just a test of your wm knowledge and you passed!

**Comment by dominiklohmann** [comment]
> my apologies for the non-issue ticket.

Don't worry about such things. There are some very much non-obvious things about yabai, and we're always happy to answer questions.
