### ISSUE TITLE
Default spaces for windows not specified in rules.

### ISSUE THREAD

**Issue by blmhemu** [koekeishiya/yabai#428]
Hey ! Thanks for the awesome tiling manager. As I am relatively new to this software, I have a couple of questions.
1. Is there are way to set windows not specified by rules to got to a default space ?
2. Also, can I set rule such that "if more windows of the type open go to a new space" (assign multiple spaces in the rule) ?

**Comment by koekeishiya** [comment]
So using the rules system you can only specify a single space for the default regardless of any other state.

You can utilize the signals (application_launched and window_created specifically) to write whatever logic you want, using the query system to retrieve information about the state, and then move the window to the desired space.

**Comment by blmhemu** [comment]
Thanks for the fast reply, I got the answer to my second question.
But for my first, let me explain it in more detail - Lets say I have written rules such that application A, B, C go to spaces 4, 5, 6. Now I want all applications, other than A, B, C to open in say, space 2 (i.e the default space for remaining apps).

**Comment by koekeishiya** [comment]
> But for my first, let me explain it in more detail - Lets say I have written rules such that application A, B, C go to spaces 4, 5, 6. Now I want all applications, other than A, B, C to open in say, space 2 (i.e the default space for remaining apps). I need help regarding making such a rule.

This is not possible in the latest released version, but you should be able to do it if you run from the master branch or wait for the next release, now that #173 has been implemented.

**Comment by koekeishiya** [comment]
In version 2.4.0, something like the following should resolve your first question:

```
yabai -m rule --add app="^Finder$" space=3
yabai -m rule --add app="^Safari$" space=4
yabai -m rule --add app!="^(Finder|Safari)$" space=2
```
