### ISSUE TITLE
Introduce more granular layer control for windows.

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#429]
The current version of yabai will allow the user to make windows appear either topmost (above) or in their normal layer. However, It may be useful for whatever reason to be able to specify windows to appear at the desktop level (below) other windows. 

This would allow you to do something like [terminal as wallpaper](https://askubuntu.com/questions/366599/use-a-terminal-as-desktop-background-instead-of-the-wallpaper) relatively easily on macOS, by using `manage=off  sticky=on layer=below grid=1:1:0:0:1:1`, among other things.

**Comment by koekeishiya** [comment]
Layers can be set through a user initiated command, or through rules.

```
LAYER := below | normal | above

# set layer with window command
yabai -m window --layer <LAYER>

# set layer through rule
yabai -m rule --add app="^Finder$" layer=<LAYER>
```

**Comment by SGarcia710** [comment]
> Layers can be set by using a user initiated command, or through rules.
> 
> ```
> LAYER := below | normal | above
> 
> # set layer with window command
> yabai -m window --layer <LAYER>
> 
> # set layer through rule
> yabai -m rule --add app="^Finder$" layer=<LAYER>
> ```

A little shortcut to toggle the active window's layer: 
```bash
hyper - c : yabai -m query --windows --window | jq -re '.["is-topmost"]' | xargs -I {} bash -c "if [[ '{}' = 'true' ]]; then yabai -m window --layer normal; elif [[ '{}' = 'false' ]]; then yabai -m window --layer above; fi" 
```
