### ISSUE TITLE
AXSheet role z-index oddities

### ISSUE THREAD

**Issue by acmcelwee** [koekeishiya/yabai#43]
I'm seeing very strange behavior with anything that has the `AXSheet` role. I'm on `HEAD`, MacOS 10.14.5, and the simplest way to reproduce this is to click a button in Chrome that opens a File Picker (file upload, etc). I also see this in IntelliJ IDEA when it opens the Open File dialog. 

Here's the relevant window from a `yabai -m query --windows` on the relevant space:
```
{
	"id":969,
	"pid":307,
	"app":"IntelliJ IDEA",
	"title":"",
	"frame":{
		"x":441.0000,
		"y":49.0000,
		"w":799.0000,
		"h":183.0000
	},
	"level":"0",
	"role":"AXSheet",
	"subrole":"",
	"movable":1,
	"resizable":1,
	"native-fullscreen":0,
	"floating":1
}
```

Interestingly, the window seems to still be there in most cases, but just not visible. In the GIF below, you can see that attempting to toggle focus to another chrome window and back doesn't bring the file dialog to the front, but clicking *where the window should be visible* somehow activates it and shows it.

Here's a gif, showing the behavior:

![ezgif-1-3bc0f08df7a6](https://user-images.githubusercontent.com/1056585/59653928-a8b40e00-9159-11e9-8882-01ecbb48fdbc.gif)

**Comment by acmcelwee** [comment]
On a related note, do you have any plans to add a `role=...` specifier to the rules system?

**Comment by koekeishiya** [comment]
I tried to reproduce this with the exact same website (and Chrome) that you were using, but it appears to work just fine.

I get the following window details with `yabai -m config window_topmost on`:

```
        "id":5498,
        "pid":48338,
        "app":"Google Chrome",
        "title":"",
        "frame":{
                "x":1033.0000,
                "y":126.0000,
                "w":799.0000,
                "h":756.0000
        },
        "level":"3",
        "role":"AXSheet",
        "subrole":"",
        "movable":1,
        "resizable":1,
        "native-fullscreen":0,
        "floating":1
```

I get the following details with `yabai -m config window_topmost off`:
```
        "id":5517,
        "pid":48338,
        "app":"Google Chrome",
        "title":"",
        "frame":{
                "x":1033.0000,
                "y":126.0000,
                "w":799.0000,
                "h":756.0000
        },
        "level":"0",
        "role":"AXSheet",
        "subrole":"",
        "movable":1,
        "resizable":1,
        "native-fullscreen":0,
        "floating":1
```

In both cases the window appear as expected, and stay visible until I close it.

**Comment by acmcelwee** [comment]
Yeah, I just rebuilt from HEAD, and it now seems like it's resolved itself in both Chrome and IntelliJ.
