### ISSUE TITLE
Apply `window_gap` to manual `grid` configuration

### ISSUE THREAD

**Issue by JeanMertz** [koekeishiya/yabai#431]
I'm trying to use rules to configure spaces with layouts for specific applications (which I always keep running).

The important part is for that set-up to automatically re-apply after a reboot and re-launch of the relevant windows.

I'm using `grid` to achieve this, but I also like the `window_gap` to apply to my grid. From my testing, it appears the window gap config is ignored for custom grids, is that correct? Is there any solution to this other than cutting up the grid in many small rows/columns to be able to manually leave some space between the windows?

**Comment by koekeishiya** [comment]
> From my testing, it appears the window gap config is ignored for custom grids, is that correct?

That is correct. When windows are arranged manually (note: not by the bsp algorithm), yabai cannot reason about which side of the windows should or should not have gaps, as gaps should only exist between windows and not screen edges (this is padding, which is inherited from the space config).

I don't think you can do this using only rules, unless you specify a grid with tons of small rows/columns.

You could combine this with signals (application_launched, window_created) to reduce the size of the window by x in the direction(s) that you want to have a gap, but this will not work correctly if the application is already running at the time when yabai is launched. To handle that  correctly you would also need to query for the windows and run them through a script that basically applies that gap.

**Comment by JeanMertz** [comment]
Thanks for the reply. The reasoning makes sense given the current functionality of Yabai.

> yabai cannot reason about which side of the windows should or should not have gaps, as gaps should only exist between windows and not screen edges (this is padding, which is inherited from the space config).

It would be nice if there was a way to disable space padding, and apply the window gap to all sides in cases like these. But I can see how that might be a niche feature that's not worth the trouble complicating Yabai's current design over.

Feel free to close the issue if there's nothing else to be done here. I might play around with a wrapper command that takes a grid, slices it up into smaller pieces, and adds some margins around all the windows, and then produces the final `yabai` command to run.

**Comment by koekeishiya** [comment]
I don't think this is something I want to be a part of yabai as this time. Maybe I'll come up with something that could handle this situation in the future.
