### ISSUE TITLE
Swap and Warp not working on 10.15 Catalina

### ISSUE THREAD

**Issue by bcr-ch** [koekeishiya/yabai#432]
I have disabled SIP, installed Yabai and Skhd and so far it’s working great. Unfortunately whenever I create a shortcut in skhd to invoke swap or warp and nothing happens.  If I manually type it into a terminal window it does.

Any idea?

shift + alt - left : yabai -m window --swap west
Or
Shift + cmd - left : yabai -m window —warp west

**Comment by dominiklohmann** [comment]
That sounds like an issue with your skhd setup rather than your yabai setup. I recommend checking the skhd log files.

**Comment by stylerw** [comment]
I'm successfully implementing the `yabai -m window --swap west` command via Alfred, so I don't think this is a Yabai issue.

**Comment by tuananh** [comment]
it's working for me

**Comment by bcr-ch** [comment]
Thanks everyone... I re-installed skhd with logging and found that I had a silly typo in the file.  By default logging wasn't enabled.

Cheers and amazing response from community. Thanks
