### ISSUE TITLE
[Need Help] How to Restore Size and Position

### ISSUE THREAD

**Issue by yanzhang0219** [koekeishiya/yabai#435]
Hi,

My current space has one tiled window (the terminal). Then I open an app say Messages.app which I set `manage=off` via `yabai rule` so that it is "float" in the middle of my screen. Then I use `yabai -m window --toggle float` to make it tiled. It goes to the right, next to the terminal window. Then I run this command again to make it floating again, but its size is till the half of the screen and it still stays at the right half of the screen. I am wondering whether there is a way when a window gets floated again from tiled, its size and position can be restored. For this Messages.app window, I want to make it go back to the center of the screen and make its size restored to the normal. 

Thank you. 

**Edit**: 
**What I can come up with so far is:**

I create a shell script to perform this floating-or-tiling toggle. In the script, I firstly use `yabai -m query --windows --window` to check its "floating" value. 
* If it is floating, I record the value of "frame". The value contains "x" and "y" which are the position of the window, and "w" and "h" which are the size of the window. Then I use `yabai -m window --toggle float` to change it to be tiling.  
**Question: where should I record these values, creating a temporary file and storing these values in it?**
* If it is not floating (i.e., tiling), I firstly use `yabai -m window --toggle float` to change is to be floating, and then right after this, I use `yabai -m window --move abs:x:y` to restore its position and `yabai -m window --resize abs:w:h` to restore its size. 

**I am not sure whether I am in the correct direction to implement my requirement. Is it a more efficient way to do this? Does yabai provide some more decent approach for this?** 

Thank you very much!

**Comment by dominiklohmann** [comment]
I've just tried implementing this, but my attempt does not work because of a slight issue with yabai. If that gets fixed, the following should work:

```sh
#! /usr/bin/env zsh

function store_window () {
  emulate -L zsh -o err_return -o no_unset
  yabai -m query --windows --window $YABAI_WINDOW_ID | jq -re '
    if .floating == 1 then
      .frame | "yabai -m window $YABAI_WINDOW_ID --move abs:\(.x):\(.y)\n"
             + "yabai -m window $YABAI_WINDOW_ID --resize abs:\(.w):\(.h)"
    else
      empty
    end' >/tmp/yabai-restore/$YABAI_WINDOW_ID.restore
  chmod +x /tmp/yabai-restore/$YABAI_WINDOW_ID.restore
}

() {
  emulate -L zsh -o err_return
  rm -rf /tmp/yabai-restore
  mkdir /tmp/yabai-restore
  # The labels below are generated using `uuidgen` to ensure these signals are
  # never running more than once.
  yabai -m signal --add label='AA1BE1CD-6665-47B5-B5C4-111FBFFF0E1D' \
    event=window_moved action="${functions[store_window]}"
  yabai -m signal --add label='91CC175D-9D33-4D48-9767-0FAF33E63209' \
    event=window_resized action="${functions[store_window]}"
}

# To restore a window, run this command:
#   yabai -m window --toggle float &&
#     /tmp/yabai-restore/$(yabai -m query --windows --window | jq -re '.id').restore
```

Here's what doesn't work: When you toggle a window to no longer float, the window is resized and moved _before_ the floating attribute of the window is set to 0. The attribute would need to be set first (cc/ @koekeishiya).

**Comment by dominiklohmann** [comment]
Here's a small recording of the script in action (this is honestly really cool, I'll start using this myself): https://gfycat.com/ifr/OddballTallAlpineroadguidetigerbeetle

**Comment by koekeishiya** [comment]
I noticed that you alternate between using `yabai -m window --toggle float` and the appended command for restore, depending on whether the window is tiled or not, but I think it should be fine to just have a single bind for float/unfloat that always does `yabai -m window --toggle float && /tmp/yabai-restore/$(yabai -m query --windows --window | jq -re '.id').restore`

**Comment by dominiklohmann** [comment]
Yeah sure, you can do this:

```sh
yabai -m window --toggle float && /tmp/yabai-restore/$(yabai -m query --windows --window | jq -re '.id').restore 2>/dev/null || true
```

**Comment by dominiklohmann** [comment]
@koekeishiya random thought: If the `event=daemon_msg` carried more information, this could be fully automated. Might be a cool concept.

**Comment by koekeishiya** [comment]
So the only reason that this signal does not contain the message is that the message is a series of bytes where each argument given to -m is a zero terminated string. I’m not sure if that is going to play well with env variables

Sent from my iPhone

.
On 7 Mar 2020, at 14:34, Dominik Lohmann <notifications@github.com> wrote:

﻿

@koekeishiya<https://github.com/koekeishiya> random thought: If the event=daemon_msg carried more information, this could be fully automated. Might be a cool concept.

**Comment by dominiklohmann** [comment]
In bash/zsh terms that'd need to be expressed as an array, which is equal to a string that's separated with spaces.

E.g., say you're calling this:

```
yabai -m signal --add label=x event=y action="123 456"
```

Then the shell variable would need to contain this:

```
YABAI_MESSAGE='"signal" "--add" "label=x" "event=y" "action=\"123 456\""'
# semantically equivalent to
YABAI_MESSAGE=('signal' '--add' 'label=x' 'event=y' 'action="123 456"')
```

`${YABAI_MESSAGE[@]}` can then be used on the calling side to get the whole command string.

I don't think that's all too user friendly. Let's scrap this idea.

**Comment by yanzhang0219** [comment]
Thank you both for your help.

Hi @dominiklohmann,
Thank you for your code. It is very helpful and advanced. By reading your code while googling some syntax I didn't know, I learned a lot on Bash/Zsh programming. Thanks. 

Next, I implemented this feature by myself using some easier syntax, and **it works perfectly so far**. **Please take a look at it and leave some suggestions for improvement**. I attached the script below (I bind it to a shortcut using skhd). The features are:
* If a window is floating, run this script to toggle it to be tiling
* If a window is tiling, run this script to toggle it to be floating and restore its previous position and size

```bash
#!/bin/bash

# Used to toggle a window between floating and tiling

read -r id floating <<< $(echo $(yabai -m query --windows --window | jq '.id, .floating'))
tmpfile=/tmp/yabai-float-toggle/$id

# If the window is floating, toggle it to be tiling and record its position and size
if [ $floating -eq 1 ]
then
  [ -e $tmpfile ] && rm $tmpfile
  echo $(yabai -m query --windows --window | jq .frame) >> $tmpfile
  yabai -m window --toggle float

# If the window is tiling, toggle it to be floating, 
# and restore its previous position and size
else
  yabai -m window --toggle float
  if [ -e $tmpfile ]
  then
    read -r x y w h <<< $(echo $(cat $tmpfile | jq '.x, .y, .w, .h'))
    yabai -m window --move abs:$x:$y
    yabai -m window --resize abs:$w:$h
    rm $tmpfile
  fi
fi
```

**There will be a potential defect here. I am not sure whether all the window ids will be unique since the last rebooting of the laptop**.  
When a window changing from floating to tiling, a temporary file will be created, and it is deleted when it is changed back. If lots of windows are changed from floating to tiling but not changed back, then lots of files will be generated whose names are their window ids. If a window id may the same with some other before, when it is changed from floating to tiling, the file of the other window will be overridden. And if it is originally tiling and I change it to be floating, it will use the file of the other window to retore.  

Thank you very much!

**Comment by dominiklohmann** [comment]
I don't think there's anything wrong with your approach. The main difference is that you store the frame only when unfloating a window, while my script stores the frame whenever a window is moved/resized, which is a bit more robust.

> There will be a potential defect here. I am not sure whether all the window ids will be unique since the last rebooting of the laptop.

You can write the output of `who -b` into a file, and when its content is not equal to the output of `who -b` when you run yabai, you delete the cached files and update the content of the file.

**Comment by yanzhang0219** [comment]
I got it. Thank you for your help. :)

**Comment by dominiklohmann** [comment]
> When I create a window, is it possible that this newly-created window has the same id with some other window that has been closed already?

Not unless you killed the window server, which usually implies rebooting.

**Comment by yanzhang0219** [comment]
Nice. Thanks. I should run the script you provided above to refresh the cache folder each time rebooting, right?

**Comment by dominiklohmann** [comment]
I just run it whenever yabai starts (i.e., in your yabairc). Just make sure to set the cache dir to the dir you store these temp files in.

**Comment by yanzhang0219** [comment]
Gotcha! Thank you! :)
