### ISSUE TITLE
Padding for iTerm2

### ISSUE THREAD

**Issue by yanzhang0219** [koekeishiya/yabai#437]
I set all the four paddings to 5, but for iTerm2 window, the bottom padding is very large, and the right padding is still larger than the top padding. Also, when I open another iTerm2 window, the padding between them is quite large as well, ao are the bottom and top ones. I believe that this is caused by iTerm2. Does anyone using iTerm2 know how to fix this? Thanks!

Figure1: the bottom and top padding are incorrect
<img width="1920" alt="Screen Shot 2020-03-08 at 6 50 50 PM" src="https://user-images.githubusercontent.com/11582667/76176409-cbfe6d80-616d-11ea-9f2c-3569b1fc57de.png">

Figure2: the bottom padding, the right padding and the padding between the two windows are incorrect
<img width="1920" alt="Screen Shot 2020-03-08 at 6 51 05 PM" src="https://user-images.githubusercontent.com/11582667/76176417-d0c32180-616d-11ea-8fcb-39e84de1f43d.png">

Dear @dominiklohmann, based on a screen record GIF you provided in my previous issue post, I saw you are using iTerm2. Any ideas about my concern? Thank you.

**Comment by dominiklohmann** [comment]
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/4488655/76194434-6f8b6480-61e6-11ea-9cb0-e41a045c0a03.png">

**Comment by yanzhang0219** [comment]
Oh my goodness!!!! Thank you very very very much!!!!!!!!!!!
(closing this)
