### ISSUE TITLE
AXObserverAddNotification retry infinitely loops

### ISSUE THREAD

**Issue by lwouis** [koekeishiya/yabai#439]
I ran into this use case with [alt-tab-macos](https://github.com/lwouis/alt-tab-macos). In my case, the `UIKitSystem` process couldn't be subscribed to. The `AXObserverAddNotification` call kept returning `kAXErrorCannotComplete`. This triggered an infinite loop that consumed around 8% CPU on my `MacBookPro15,1`.

Looking at

https://github.com/koekeishiya/yabai/blob/99f4305b850ad68b69276ebb3ad336e60d5d53db/src/application.c#L66

and

https://github.com/koekeishiya/yabai/blob/99f4305b850ad68b69276ebb3ad336e60d5d53db/src/event.c#L334

It seems like yabai will exhibit the same issue where you will infinitely loop every 10ms, heating up the machine.

I thought about different approaches:

* Stop after N attempts
  Downside: misses out on legit, temporarily stuck processes
* Stop after N minutes
  Downside: misses out on legit, temporarily stuck processes
* Exponential backoff on the retry timer
  Downside: can get aware of processes way later after they get unstuck
* Blacklist of known unsubscribable processes
  Downside: who goes in the blacklist?
* Ignore processes that respond `kAXErrorCannotComplete`
  Downside: according to the docs, this status could be temporary, thus potentially misses out on legit, temporarily stuck processes

What do you think about this issue? It's quite a puzzle

**Comment by koekeishiya** [comment]
I have a pretty exhaustive filtering at the process level that happens in a previous step to make sure that we never end up in that situation. I can't prove that there is not some edge case, but so far I have not experienced that issue.

See https://github.com/koekeishiya/yabai/blob/master/src/process_manager.c#L64

**Comment by lwouis** [comment]
Could you elaborate a bit on how this filtering was built? I checked the commit history but couldn't find more explanations. There are 4 types of processes that you ignore: `lsuielement`, `lsbackground`, `background`, `xpc`. How did you find how that these 4 types of processes are not useful to observe? Doesn't it happen that a background process or an agent does interesting things like opening and closing windows? For instance alt-tab itself is a `LSUIElement` process.

I had considered using [this approach](https://stackoverflow.com/a/26002033/2249756) for filtering processes in the past, but got too afraid to miss out on useful processes. Are you not afraid that yabai will miss out on processes useful to the user?

**Comment by koekeishiya** [comment]
The process filtering is based on various Apple documentation that are scattered through their unbrowsable developer.apple.com site.


LSBackgroundOnly:
> LSBackgroundOnly (Boolean - macOS) specifies whether this app runs only in the background. If this key exists and is set to YES, Launch Services runs the app in the background only. You can use this key to create faceless background apps. You should also use this key if your app uses higher-level frameworks that connect to the window server, but are not intended to be visible to users. Background apps must be compiled as Mach-O executables. This option is not available for CFM apps.

LSUIElement:
>LSUIElement (Boolean - macOS) specifies whether the app runs as an agent app. If this key is set to YES, Launch Services runs the app as an agent app. Agent apps do not appear in the Dock or in the Force Quit window. Although they typically run as background apps, they can come to the foreground to present a user interface if desired. A click on a window belonging to an agent app brings that app forward to handle events.

>The Dock and loginwindow are two apps that run as agent apps.

XPC Service:
>XPC services are managed by launchd, which launches them on demand, restarts them if they crash, and terminates them (by sending SIGKILL) when they are idle. This is transparent to the application using the service, except for the case of a service that crashes while processing a message that requires a response. In that case, the application can see that its XPC connection has become invalid until the service is restarted by launchd. Because an XPC service can be terminated suddenly at any time, it must be designed to hold on to minimal state—ideally, your service should be completely stateless, although this is not always possible.

>By default, XPC services are run in the most restricted environment possible—sandboxed with minimal filesystem access, network access, and so on. Elevating a service’s privileges to root is not supported. Further, an XPC service is private, and is available only to the main application that contains it.

`background` is pulled off the carbon process info, and is mostly set when `LSBackgroundOnly` is set. I don't actually if there was a situation where one is set and the other isn't. It's been a long time since I looked into this.

If an application does not respect any of these settings then I consider that a bug in that application. There is at least no good solution to this problem, as you pointed out in the original post.

**Comment by lwouis** [comment]
Thanks for sharing these insights! I will close this ticket since I thought you had the issue, but now that I see you're filtering processes this way, I understand why you haven't been affected.

Thanks again for sharing!
