### ISSUE TITLE
Can i jump to prev or last space when destroy current space

### ISSUE THREAD

**Issue by kyoz** [koekeishiya/yabai#443]
When using `yabai -m space --destroy`. It auto jump to the 1st space, which i think is sometime not very convenient. Like i have [1] [2] [3] [4]. When i destroy space 4. I want it to jump to closest space (mean 3) 🐱

**Comment by koekeishiya** [comment]
You can get the behaviour you want by writing a small script to first focus whatever space you desire, and then destroy the space you came from. See #299

**Comment by kyoz** [comment]
Thank you so much, i i'll give it a try ❤️
