### ISSUE TITLE
Mouse modifier with fn is not working

### ISSUE THREAD

**Issue by Zeta611** [koekeishiya/yabai#445]
I'm using Happy Hacking Professional 2 keyboard, and mouse modifier set as 'fn' does not seem to work. Can it be an issue with the keyboard itself? cmd, shift, and alt works.

**Comment by koekeishiya** [comment]
This is very much an issue with how the keyboard interacts with macOS. Yabai is using a fairly high-level API for looking at input events.

**Comment by Zeta611** [comment]
I see that 'fn' key is not observed using [Karabiner Elements](https://github.com/pqrs-org/Karabiner-Elements) as well.

I opened an issue over there as well: https://github.com/pqrs-org/Karabiner-Elements/issues/2194

**Comment by koekeishiya** [comment]
So I actually have the exact same problem if I use my Ducky One keyboard. I guess the FN modifier only works correctly with an Apple keyboard?

**Comment by koekeishiya** [comment]
Nothing I can do about this, closing as can't fix.
