### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by xhfhope** [koekeishiya/yabai#446]
https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

The listed commands say enable instead of disable

The --without arguments are considered invalid when you write the command with "disable"

**Comment by koekeishiya** [comment]
See my comment https://github.com/koekeishiya/yabai/issues/5#issuecomment-586899378

**Comment by xhfhope** [comment]
@koekeishiya Maybe update the wiki and clarify that you very deliberately want the command to be written with the enable keyword

Also, you may want to address the following..

When the flags are added in my case, terminal output returns the following:

csrutil: requesting an unsupported configuration. This is likely to break in the future and leave your machine in an unkknown state.
csrutil: requesting an unsupported configuration. This is likely to break in the future and leave your machine in an unkknown state.

Thanks for your support and great contributions

**Comment by dominiklohmann** [comment]
Honestly I don't think this needs to be expanded. "enable without x" is quite clear language already. 

Everything about yabai's scripting addition falls into the category "this is likely to break in the future."

**Comment by xhfhope** [comment]
I agree that it doesn't _need_ to be explained but insofar as it will inevitably be helpful and is unlikely to ever be hurtful, it's a good idea.

New users like me are going to inevitably encounter the same confusions due to a lack of verbosity.

I'm not trying to be hyper-critical here, I just don't see why you wouldn't add something like that if it's inevitably going to cause idiots like me problems.

**Comment by dominiklohmann** [comment]
I've added a short line explaining that it's safe to ignore the warning.
