### ISSUE TITLE
[Bug] Bear application does not tile

### ISSUE THREAD

**Issue by nwaywood** [koekeishiya/yabai#447]
Hello,

[Bear](https://apps.apple.com/us/app/bear/id1091189122?mt=12) is the first application I have come across where the BSP doesn't work. When I launch Bear, yabai doesn't create a split and open it in the split (as it normally would opening a window of any application), instead it seems to open in a floating mode no matter what.

Thanks in advance

**Comment by koekeishiya** [comment]
This seems to be the same kind of issue as #304
I consider this a problem with the actual application itself. There isn't really anything that yabai can do about this.

**Comment by koekeishiya** [comment]
I've made some changes on the latest master (#529) that might resolve this issue.
Would you mind trying that and reporting back? Thanks.

**Comment by nwaywood** [comment]
Hi @koekeishiya , I just looked at the [docs for how to run the master branch version](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) and I think I would prefer to stay on stable releases, sorry.

I will happily test it out and report back when it's in a release though!

**Comment by koekeishiya** [comment]
You don't really need to codesign and give it accessibility access and all that is listed in the wiki if you run it from a terminal application that you temporarily give accessibility access.

e.g: Open privacy -> accessibiliy -> give Terminal.app access

open Terminal.app
git clone the yabai repo
run: make
run: yabai
done

Make sure to stop the brew version before doing the above: brew services stop yabai
When done, simply rm -rf the cloned repo and start the brew service again.

It's fine if you'd rather wait for a release as well, but figured I'd mention an easier approach than what is stated in the wiki. If you are actually going to run the dev version from day-to-day, the wiki instructions would apply.

**Comment by koekeishiya** [comment]
Fixed in the latest release.

**Comment by technoplato** [comment]
For those curious about how to do this, you can add these lines to your .skhdrc (assuming you have that configured properly) and press the keys when you're focused window is Books (or whatever non-behaving window is)

```
# toggle tiled mode (used to force Applications (Books, etc) into tiled mode)
alt + cmd + ctrl - f : yabai -m window --toggle float 
```
