### ISSUE TITLE
Display date in the status bar

### ISSUE THREAD

**Issue by PatrikTrefil** [koekeishiya/yabai#449]
I understand the status bar is supposed to be simple. I think it is sufficient for most people including me, just the ability to display the current date is missing.

**Comment by koekeishiya** [comment]
I'm not changing my stance on this topic, sorry. What I would like is for someone to actually make a proper bar application for macOS. Adding a statusbar to yabai itself was a mistake.

**Comment by PatrikTrefil** [comment]
The easiest way I found was to create an Ubersicht date widget that matches the theme of the status bar. It is not a perfect solution, but it works for me.

For anyone interested, you can find it here:
https://github.com/PatrikTrefil/date-yabai
