### ISSUE TITLE
can't install via brew

### ISSUE THREAD

**Issue by Fedelaus** [koekeishiya/yabai#45]
I'm trying to install following the README - I have done the following:

`brew tap koekeishiya/formulae`

Upon doing

`brew install yabai`

I'm receiving the following issue:

```
▶ brew install yabai
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Installing yabai from koekeishiya/formulae
==> Downloading https://github.com/koekeishiya/yabai/releases/download/v0.1.0/yabai-v0.1.0.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "yabai"
Download failed: https://github.com/koekeishiya/yabai/releases/download/v0.1.0/yabai-v0.1.0.tar.gz
```

Visiting https://github.com/koekeishiya/yabai/releases it seems that no releases exist and searching for `yabai` at http://searchbrew.com/ it doesn't seem to exist.

How do I install this project?

**Comment by dominiklohmann** [comment]
The 0.1.0 tagged pre-release apparently got removed. It had a major bug anyways. 

You can still install from HEAD. [Here's a guide in the wiki](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)). Note that the last step about auto updating is optional. Current master is quite stable, more so than 0.1.0 was.

**Comment by koekeishiya** [comment]
I removed the 0.1.0 release and tag because it was never meant to be used by people -  it was simply a way for me to test my make command for prepping a release archive and to make sure the formulae could propely install from source and the prebuilt package.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Fedelaus** [comment]
Thanks for the quick replies - I'm up and running with yabai and enjoying it.
