### ISSUE TITLE
Disabling SIP leads to external monitor detection failure

### ISSUE THREAD

**Issue by lake-effect** [koekeishiya/yabai#450]
I want to be clear at the outset that this isn't a yabai bug, but I want to file it here so you have something to track with. If I find a solution or a useful place to file elsewhere I'll post updates here also. 

## Symptoms

External DisplayPort monitor [Sceptre E255B-1658A](https://www.sceptre.com/Monitors/LED-Monitor/E255B-1658A-25-LED-Monitor-product1094category12category16.html) connected through USB-C to DP adapter does not detect either through manual detection in System Preferences or through waking up from sleep, restarting, etc.

## Workaround/reproduction steps

1. Execute NVRAM reset (shutdown, reboot while holding Alt+Cmd+P+R)
2. Observe that monitor detects and spaces are allocated but yabai warns that SIP is enabled, tiling fails
3. Reboot into recovery mode (Cmd + R)
4. Execute `csrutil enable --without debug --without fs`
5. Reboot into regular OS
6. Observe that yabai correctly tiles but monitor does not detect

## Environment

- MacBook 2019
- OSX Catalina 10.15.3 (19D76)
- AMD Radeon Pro 5300M 4 GB
- Intel UHD Graphics 630 1536 MB

### NVRAM parameters

Output of `nvram -xp`:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>HW_BOOT_DATA</key>
	<data>
	AQAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAABHFRUgAAAAAAAAAAAAAAAAAgAAACUk
	FSAAAAAAAAAAAAAAAAADAAAASSYVIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
	AA==
	</data>
	<key>LocationServicesEnabled</key>
	<data>
	AQ==
	</data>
	<key>backlight-level</key>
	<data>
	jwE=
	</data>
	<key>bluetoothActiveControllerInfo</key>
	<data>
	lgCsBQAAAAAAAPj/wmfOdw==
	</data>
	<key>bluetoothInternalControllerInfo</key>
	<data>
	lgCsBQAAAAD4/8Jnznc=
	</data>
	<key>csr-active-config</key>
	<data>
	FgAAAA==
	</data>
	<key>fmm-computer-name</key>
	<data>
	[REDACTED]
	</data>
	<key>fmm-mobileme-token-FMM</key>
	<data>
	[REDACTED]
	</data>
	<key>fmm-mobileme-token-FMM-BridgeHasAccount</key>
	<data>
	QnJpZGdlSGFzQWNjb3VudFZhbHVl
	</data>
	<key>gpu-policy</key>
	<data>
	AQ==
	</data>
</dict>
</plist>
```

Output of `nvram -p`:

```
bluetoothInternalControllerInfo	%96%00%ac%05%00%00%00%00%f8%ff%c2g%cew
fmm-computer-name	[REDACTED]
fmm-mobileme-token-FMM	[REDACTED]
fmm-mobileme-token-FMM-BridgeHasAccount	BridgeHasAccountValue
bluetoothActiveControllerInfo	%96%00%ac%05%00%00%00%00%00%00%f8%ff%c2g%cew
backlight-level	%8f%01
LocationServicesEnabled	%01
csr-active-config	%16%00%00%00
gpu-policy	%01
HW_BOOT_DATA	%01%00%00%00%03%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%01%00%00%00G%15%15 %00%00%00%00%00%00%00%00%00%00%00%00%02%00%00%00%25$%15 %00%00%00%00%00%00%00%00%00%00%00%00%03%00%00%00I&%15 %00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00
```

**Comment by lake-effect** [comment]
Possibly related:

- http://www.madrau.com/support/support/srx_1011.html
- https://gist.github.com/ejdyksen/8302862

**Comment by koekeishiya** [comment]
Seems like it's about time to jump ship when something like this is happening.. Luckily all my external monitors work fine (using both displayport and/or hdmi).

**Comment by lake-effect** [comment]
I wish I had finer tools to diagnose or try to mitigate the issue but OSX has always been the "don't think about it, just use it for work" environment for me. The three possibilities I can think of are:

- NVRAM reset does a lot more than it should, and as such whatever it's doing along the way to re-enabling SIP includes the actual step that's needed
- This specific monitor needs something involved in that reset step, and others don't
- Catalina's recent updates may also have included something that makes this problem worse

Sadly I don't have time to follow any of these leads.

**Comment by lake-effect** [comment]
It might not be NVRAM, at least, I'm not seeing anything interesting. The same reset command resets PRAM, but I don't know how to print its contents.

**Comment by dominiklohmann** [comment]
Note that resetting P/NVRAM has always reset SIP. That’s intended behavior, and although I cannot find where right now, I know it to be documented somewhere at least.

**Comment by lake-effect** [comment]
That makes sense, if `csr-active-config` is the key where SIP policy is stored.

**Comment by dominiklohmann** [comment]
Does the same issue occur if you disable SIP completely?

**Comment by lake-effect** [comment]
Aha! I did it 😄 

`nvram -d HW_BOOT_DATA` and then restarting did not work.

`nvram -d HW_BOOT_DATA; nvram -d gpu-policy` and then restarting did. I also toggled the monitor power as the machine was booting post login, just to ensure the monitor was in active detection mode as opposed to power saving.

> Does the same issue occur if you disable SIP completely?

I haven't tried it yet, but I'll come back to it later once I'm through high-priority work items.

**Comment by brorbw** [comment]
Im running the latest version with three external monitors, two on usb-c to DP adapters and one on hdmi on a mac mini. Everything seems to work fine. SIP is disabled, I have never tried running with SIP.

**Comment by dominiklohmann** [comment]
That's to be expected @brorbw. The issue body even states that this is not an issue with yabai per se, but rather with a known bug in a specific monitors interaction with SIP. Luckily, the author found a workaround, and was kind enough to share it with us.

If this was a more widespread issue this would've shown up years back in the chwm-sa days. Ultimately, this really is a non-issue because of that.

**Comment by brorbw** [comment]
I didn't gather that it was a specific monitor that didn't work, thought you meant the combo of usb-c -> 
 DP adaptor, running without SIP, thus I wanted to add that I didn't have a problem with SIP disabled.

**Comment by lake-effect** [comment]
Yeah I think this is maybe an entry for the wiki just as a "If you run into this corner case, here's a way someone fixed it" clue.
