### ISSUE TITLE
Stop yabai from ever splitting only 2 windows horizontally

### ISSUE THREAD

**Issue by yamini-krishnamurthy** [koekeishiya/yabai#451]
If I just have two windows, I only want them to be split left-right, not top-bottom. Is there a way to make this happen? Thank you!

**Comment by dominiklohmann** [comment]
Whenever a window is focused, toggle its `split` if the split is currently `horizontal`.

Here's a one-liner that does the job.

```
yabai -m signal --add event=window_focused action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".split == \"horizontal\"" && yabai -m window --toggle split'
```
