### ISSUE TITLE
How to use Split View in rules

### ISSUE THREAD

**Issue by SebastienElet** [koekeishiya/yabai#452]
Hello,

I replaced the former `monocle` mode with rules to set some apps in native full screen like : 
```
yabai -m rule --add label="slack" app='^Slack$' native-fullscreen=on
```
Is there any way to open two app in the same native full screen with split view ?

Thanks a lot for this awesome project !

**Comment by koekeishiya** [comment]
As far as I know there is no way to programmatically interact with the native macOS split-view. I'm sure there are ways to do this either through undocumented API's or by calling existing functions inside Dock.app, but I have not looked into that (and likely will not look into that).

**Comment by SebastienElet** [comment]
@koekeishiya thanks for the answer ! I have other way to achieve the same behavior outside of the native fullscreen then it's fine 👍
