### ISSUE TITLE
Fullscreening a window doesn't bring it to the front

### ISSUE THREAD

**Issue by Peeja** [koekeishiya/yabai#453]
I have `yabai -m config focus_follows_mouse autofocus`, so when I move my mouse to a window, it gains focus, but doesn't move to the front. If I move my mouse to a particular window and then `yabai -m window --toggle zoom-fullscreen` it, it zooms to fullscreen, and still doesn't come to the front, which places it behind other windows.

![yabaifullscreen](https://user-images.githubusercontent.com/2407/77330579-edc32d00-6cf5-11ea-927f-549afd937408.gif)

(I know this GIF isn't super useful, sorry. This one's a bit hard to record…)

That makes sense as expected behavior, but I'd like to pull the window to the front when I `--toggle zoom-fullscreen`, and I can't find a command that will do that. I there a way to simply bring a window to the front (but not move it to the `above` layer)?

**Comment by dominiklohmann** [comment]
You can focus the already focused window to raise it explicitly.

```
yabai -m window --focus "$(yabai -m query --windows --window | jq -er .id)"
```

**Comment by Peeja** [comment]
Ah, brilliant! Thank you!

**Comment by Bellavene** [comment]
Strangely I have this after updating to Sonoma 15.2
