### ISSUE TITLE
Yabai won't ignore iTerm

### ISSUE THREAD

**Issue by ThatOneCalculator** [koekeishiya/yabai#456]
I keep running `yabai -m rule --add app="^iTerm$" manage=off`
but it keeps on managing iTerm

**Comment by OuyangQianba** [comment]
`yabai -m rule --add app="iTerm2" manage=off` works for me.

**Comment by dominiklohmann** [comment]
Closing this as resolved. The app name can easily be verified to be `iTerm2` instead of `iTerm`.

```
❯ yabai -m query --windows --window | jq '.app'
"iTerm2"
```
