### ISSUE TITLE
How can I move a space including its number to a display?

### ISSUE THREAD

**Issue by danijar** [koekeishiya/yabai#457]
Let's say I'm on space 1 and display 1. When I run `yabai -m space --display 2`, the windows of space 1 indeed move to display 2. However, they are now contained in a new space 2 and space 1 itself stays on display 1. Is there a way to move the space including its number to a different screen?

**Comment by dominiklohmann** [comment]
The displayed number is simply the index assigned by Mission Control, which cannot be controlled through yabai.

You can, however, assign an internal label to a space, and address the space by its label instead of its index.

**Comment by danijar** [comment]
Okay I see. When dragging screens from one display to another via mission control they also change numbers in some way that makes no sense to me.

I'm trying to emulate the behavior of i3 where there are always 9 screens that you can focus via <kbd>Super</kbd>+<kbd>1</kbd>...<kbd>9</kbd> and send windows to via <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd>...<kbd>9</kbd>. Moreover, screens can be moved to different screens, e.g. via <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>.

It seems that I could create 9 spaces and label them via `yabai -m space 1 --label space1` etc. Then I can define keybinds that focus space labels and send windows to space labels. This would also allow me to send space labels to new displays. However, it will be hard to use when the screen numbers in mission control don't match up with the invisible screen labels used by yabai. Do you have a better idea to achieve this behavior?

**Comment by dominiklohmann** [comment]
You can try and play around with [spaces-renamer](https://github.com/dado3212/spaces-renamer), and have it somehow read the labels from yabai.
