### ISSUE TITLE
wrong with emacs

### ISSUE THREAD

**Issue by taigacute** [koekeishiya/yabai#460]
I use emacs with posframe. ..when use a command with posframe .it will to a new window ..I also set the `menu-bar-mode`. my yabairc config
```
 yabai -m rule --add app="Emacs"          manage=on space=1
```
![image](https://user-images.githubusercontent.com/41671631/77638557-50385980-6f92-11ea-968f-2f0c32880973.png)

**Comment by koekeishiya** [comment]
Emacs for macOS is a pile of garbage. Please see this and referenced issues: https://github.com/koekeishiya/yabai/issues/86

**Comment by taigacute** [comment]
@koekeishiya  I had read it.but now can't work with emacs posframe. maybe this is only way to solution this `manage=off`..

**Comment by koekeishiya** [comment]
Try to install this version of Emacs: https://github.com/d12frosted/homebrew-emacs-plus 
Then delete the yabai rule, or change it to `yabai -m rule --add app="Emacs" space=1` if you wanted the workspace association.

**Comment by taigacute** [comment]
@koekeishiya   I used `emacs-plus`, the yabai will handle the posframe of emacs.. so can't work toggther

**Comment by taigacute** [comment]
remove the `manage` it works.. why set the `manage=off` can't work?

**Comment by d12frosted** [comment]
@taigacute I don't have time right now to investigate. But I will add it to my list.

**Comment by taigacute** [comment]
@d12frosted  thanks should be close in there. because a problem with emacs-plus
