### ISSUE TITLE
Understanding how yabai borders are drawn

### ISSUE THREAD

**Issue by n0ibe** [koekeishiya/yabai#461]
I was wondering about the interactions between yabai borders and other UI elements, specifically about when they are drawn over something or under something.

For example, in this screenshot the focused window is a terminal with white borders, and after clicking the Dropbox popup menu in the menubar, this is what I get

![2020:03:27@_13 26 41](https://user-images.githubusercontent.com/59321248/77756390-5a5c6580-702f-11ea-84d3-8142a663bdb1.png)

as you can see, the border is drawn over the menu (which is not desirable). Doing the same with the battery menu results in

![2020:03:27@_13 27 08](https://user-images.githubusercontent.com/59321248/77756486-8a0b6d80-702f-11ea-8591-23df1957c37e.png)

and this time the border is drawn under the menu, which is what I want. One more example is in Firefox, when I click a popup menu

![2020:03:27@_13 27 32](https://user-images.githubusercontent.com/59321248/77756540-aa3b2c80-702f-11ea-86c8-8f82cd0a059d.png)

so again the border is drawn over the menu.

Can I tell yabai when to draw its borders over and when under, or is this something controlled by the os?

**Comment by koekeishiya** [comment]
So this is a bit complicated..

If you run with `yabai -m config active_window_border_topmost off` the border will always initially be drawn above the window, however most windows will raise themselves above the border if you click inside the window, or interact with some ui-element. There is no way for yabai to detect that the border has been occluded and automatically raise itself.

If you run with `yabai -m config active_window_border_topmost on` we tell macOS that we actually want the border to belong to a different stacking layer, giving it priority to be kept above windows in a lower stacking layer. This has the sideeffect that you see where the border will be kept in front of some other windows depending on which layer they themselves have elected into.
