### ISSUE TITLE
Yet another scripting addition issue

### ISSUE THREAD

**Issue by entrez** [koekeishiya/yabai#462]
# Summary
The scripting addition has been failing to load (at first only if yabai was running as an agent, but then consistently) after updating to macOS 10.15.4.

# Issue
After my laptop updated to macOS 10.15.4 last night, the yabai scripting addition & commands relying on it seemed to stop working, so I ran [the commands mentioned on the wiki](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#updating-to-latest-head) to update yabai, including signing the `yabai` binary and running `sudo yabai --uninstall-sa && sudo yabai --install-sa`.

Once I did that, the scripting addition seemed to work, but only when I ran yabai directly, by typing `yabai` into the terminal myself -- when yabai was started as an agent (via `launchctl` or `brew services`), I got the \`could not inject payload' notification. I figured that might be some sort of permissions issue, which sounded connected to #400, but when I poked around for potential culprits everything looked fine to me.

So then, following the advice in #415, I restarted my computer.  But after the restart, the scripting addition now fails to load whether launched directly or via agent; the error message is

    yabai: scripting-addition either failed to load or could not inject payload into Dock.app! Error: -1743

`yabai --check-sa` returns an exit code of `0`. I've tried reinstalling (via `brew` as well as by compiling it manually) and restarting my computer a couple more times but have been consistently getting the above error.

System Integrity Protection is disabled and the scripting addition has been working well for the past several months.

# Details
**System:** macOS Catalina 10.15.4 (19E266)
**Version of yabai:** current HEAD (e410f1b); also reproduced in v2.4.1 (3ff3b12)

**Comment by suntzuisafterU** [comment]
I had the same issue but was luckily able to get it working again with these commands,
found here: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

```
# stop, upgrade, start yabai
brew services stop yabai
brew upgrade yabai
brew services start yabai

# reinstall the scripting addition
sudo yabai --uninstall-sa
sudo yabai --install-sa

# load the scripting addition
killall Dock

```

System: macOS Catalina 10.15.4
Version of yabai: v2.4.1

**Comment by bodhy** [comment]
I also go the message "payload doesn't support this macOS version!" after updating to macOS 10.15.4.

**Comment by dominiklohmann** [comment]
Updating the scripting addition must be a manual task as it requires additional permissions.

To update the scripting addition, just running `sudo yabai --install-sa` is enough and will take care of the rest for you (e.g., restarting the Dock).

**Comment by entrez** [comment]
> Updating the scripting addition must be a manual task as it requires additional permissions.
> 
> To update the scripting addition, just running `sudo yabai --install-sa` is enough and will take care of the rest for you (e.g., restarting the Dock).

I had been running `sudo yabai --uninstall-sa && sudo yabai --install-sa` (and following the other instructions on the [wiki](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#updating-to-latest-head)) each time I reinstalled yabai, but I was still getting the `yabai: scripting-addition either failed to load or could not inject payload into Dock.app! Error: -1743` message on startup.

But... after reading your comment, I ran `brew uninstall yabai && brew install yabai --HEAD && sudo yabai --install-sa` again, and this time it worked. So I'm not sure if something changed about my build environment in the intervening few days or whether I was just doing something wrong, but happily everything seems to be working now. Thanks for your help!

**Comment by dominiklohmann** [comment]
It's quite likely that you were running an outdated version of yabai, so you just re-installed the old version of the scripting addition.

Note that if you install yabai from Homebrew using `--HEAD`, it will not be upgraded when you run `brew upgrade <formula>`. Only `brew reinstall <formula>` will upgrade formulas installed from HEAD.

**Comment by entrez** [comment]
I think I did *something* to the scripting addition the other day, since the \`payload is outdated' notification I initially got when starting yabai was replaced with \`failed to load or inject payload' after I tried to update it, but you're probably right that it was some sort of oversight along those lines!

**Comment by koekeishiya** [comment]
Updating yabai should not be relevant here. v2.4.1 has support for 10.15.4 in it. There are currently not really any worthwhile changes between v2.4.1 and the master branch.

**Comment by dominiklohmann** [comment]
Well, if a user installed from HEAD using brew before the 10.15.4 support landed on master, and did not reinstall a newer version of yabai since, they were stuck on that old version. It's really an issue with how Homebrew handles installations from HEAD.

**Comment by koekeishiya** [comment]
Yeah, that makes sense. I don't actually use brew these days (and have limited usage in the past) so did not actually know that it handled HEAD installs that way.
