### ISSUE TITLE
Spacebar - status bar for yabai

### ISSUE THREAD

**Issue by somdoron** [koekeishiya/yabai#463]
I forked yabai and removed anything which isn't bar related (almost everything), the project is here:

https://github.com/somdoron/spacebar

The status bar supports multiple displays.

**Comment by johnallen3d** [comment]
hmmm I wonder if `spacebar` will be the catalyst to my finally upgrading to Catlina. 🤔

**Comment by somdoron** [comment]
I think it will work on previous versions of osx, I didn't test it though

**Comment by johnallen3d** [comment]
```
==> Installing spacebar from somdoron/formulae
spacebar: macOS Catalina or newer is required.
Error: An unsatisfied requirement failed this build.
```

**Comment by somdoron** [comment]
Which version are you using? I will fix it

**Comment by johnallen3d** [comment]
Thanks for checking! Still on Mojave (`10.14.6`).

**Comment by somdoron** [comment]
I think it should work now, try again

**Comment by johnallen3d** [comment]
🎉 That did it! Thanks for this @somdoron! So happy to have a bar on both monitors (w/o resorting to resource intensive Ubersicht.

**Comment by nwaywood** [comment]
That is awesome @somdoron, thank you!

Is there any chance you are open to adding some other basic features? Such as displaying the date?

**Comment by johnallen3d** [comment]
haha great minds think alike @nwaywood?! https://github.com/somdoron/spacebar/issues/1

**Comment by somdoron** [comment]
added clock format configuration

**Comment by koekeishiya** [comment]
Just a heads up if you have not seen my comment here: https://github.com/koekeishiya/yabai/pull/316#issuecomment-579279827

I would recommend to start entirely from scratch, but using snippets from whatever is in the yabai status bar is fine if you think it is appropriate.

**Comment by somdoron** [comment]
I agree, but I had to start some where. Coming from linux (and i3) I don't have much experience with OSX API. I guess the main thing that will stay from yabai is the events and event loop. I will work on a more modular bar blocks.

**Comment by HobbinHood** [comment]
@somdoron @koekeishiya 
I think you are aware of the following already, but I'd just like to ask if there's already a solution to this, that I didn't see, yet.
When using `yabai -m space --toggle gap` yabai turns off the space's outer padding and the new `spacebar` is then of course. If there's no solution, yet, shall I create the issue in yabai or spacebar project?

On a side note: @koekeishiya could it be, that the toggles for `padding` and `gap` are mixed up? because toggling `padding` removes the yabairc defined `window_gap` and vice versa.

**Comment by koekeishiya** [comment]
Toggling of padding and gap is working fine for me, they are not switched.
There is currently no way of having external bars properly cooperate with the toggle padding command, see my latest comment in #454

**Comment by somdoron** [comment]
As @koekeishiya suggested, for spacebar case simple `custom_bar_offset_top` will do.

**Comment by vivz753** [comment]
Question: Why can't see the battery or clock icons? (not working for yabai status bar or spacebar) I installed the 3 Free Desktop OTF's from Font Awesome but I still can't view the symbols. I'm not sure how else I'm supposed to get them to display.

**Comment by dominiklohmann** [comment]
> Question: Why can't see the battery or clock icons?

See discussion in #110 about Font Book.app.

**Comment by booherbg** [comment]
This is great, thank you! I even ran spacebar by itself without yabai over the weekend while I was working through some performance issues with yabai.

One note that I installed 'Font Awesome' via the github repo, so my config works with the "out of the box" config that yabai uses:

` spacebar -m config status_bar_icon_font         "FontAwesome:Regular:11.0"`

**Comment by Lokdex** [comment]
Hello, sorry to reopen the thread, but I am getting an error in the config. I get "unknown command 'text_font' for domain 'config' ". Does anybody know how to solve it?

**Comment by somdoron** [comment]
Yes, try to install directly from github. I need to release a new version.
For the current version you can also prefix all options with status_bar_.

**Comment by Lokdex** [comment]
Yes, that solves it and it works fine, now the issue seems to be that it doesn't read the .spacebarrc file. For applying config I must input line by line in the terminal. Is that somehow related to the version?

**Comment by koekeishiya** [comment]
Closing this as this issue seems to have served its purpose.

**Comment by Chandru-B** [comment]
> Yes, that solves it and it works fine, now the issue seems to be that it doesn't read the .spacebarrc file. For applying config I must input line by line in the terminal. Is that somehow related to the version?
> 
> Nvm, I messed the directory. It works perfectly. Thanks!
> Actually, the icons are not loading, any idea how to fix that?
> 3rd edit, I got the icons. the example in the GitHub page didn't work for me. Instead of Font Awesome 5 Free, I had to put just FontAwesome

For anyone looking here, try this. It worked fine for me
https://github.com/somdoron/spacebar/issues/11

**Comment by cmacrae** [comment]
📣 spacebar has now been moved to: https://github.com/cmacrae/spacebar 📣

**Comment by FelixKratz** [comment]
Very configurable rewritten bar is available here: [https://github.com/FelixKratz/SketchyBar](https://github.com/FelixKratz/SketchyBar) (It is not as easy to use as spacebar, but very powerful).

**Comment by alber70g** [comment]
Shamless plug; I vibe coded a small app to get spaces in my taskbar: https://github.com/alber70g/spacesbar

<img width="474" height="30" alt="Image" src="https://github.com/user-attachments/assets/502147b6-beaf-41a9-b770-28f0d9bfc39c" />

<img width="474" height="30" alt="Image" src="https://github.com/user-attachments/assets/7efd8aa6-3494-42ff-a60e-9675c4be50ae" />
