### ISSUE TITLE
[Question] How to launch a floating, centered application?

### ISSUE THREAD

**Issue by denisidoro** [koekeishiya/yabai#464]
Sorry if this has already been answered. I couldn't get any search result.

I'd like to create a binding in skhd which spawns a floating, centered window of iTerm.

However, all other iTerm windows should be tiled normally, so I believe that rules won't do the job.

How to proceed? Thanks!

**Comment by koekeishiya** [comment]
Pretty sure you want to do something like this: https://github.com/koekeishiya/yabai/issues/326
You need to extend it to make it become centered though.
