### ISSUE TITLE
Colorize (tint) windows

### ISSUE THREAD

**Issue by ai212983** [koekeishiya/yabai#466]
**Feature request:** add active/inactive window color tinting as alternative to opacity. 

**Explanation:** Semi-transparent windows readability heavily depends on what's on the background. If there's some utility windows (or colorful wallpaper) in background, they became unreadable.

**Comment by koekeishiya** [comment]
I don't know of any way to make this functionality possible. I suppose you could extrapolate the method currently used for having window borders, but that will come with its own set of unfixable issues.

**Comment by ai212983** [comment]
It is implemented to some degree in [Hammerspoon](https://www.hammerspoon.org/docs/hs.window.highlight.html), but it does have some issues indeed. 

Feel free to close this ticket then, thanks!
