### ISSUE TITLE
New windows don't open on focused display

### ISSUE THREAD

**Issue by BlueDrink9** [koekeishiya/yabai#467]
I think this is more of an OSX issue, but I was wondering if using Yabai allowed some sort of workaround.

Currently, if I open a terminal window on one display, then focus another display and open another terminal window, the second window opens on the first display.
I want windows to open on whatever space/display I currently have focused.
This also happens with finder and chrome (only ones I tested on), which is why I think it differs from #413.

Any thoughts?

(I've just switched from Chunkwm and I have to thank you once again for your amazing work. Configuring skhd is much tidier now too!)

**Comment by koekeishiya** [comment]
Hmm I suggested something similar in https://github.com/koekeishiya/yabai/issues/459#issuecomment-604445428

I suppose what you refer to as the focused space/display could differ from the cursor display, so maybe the proposed solution would have to be able to select one out of multiple alternatives.

**Comment by dominiklohmann** [comment]
Related thought: More generally this could also be implemented by adding a way to run signals synchronously before even rules are run (and thus before windows are tiled).

**Comment by koekeishiya** [comment]
I agree that would open the door to a bunch of new possibilities, but it would more or less require rethinking the whole event structure. For some events there would be mandatory work that has to happen before a signal could intercept it, and for other events that wouldn't be a thing.

**Comment by BlueDrink9** [comment]
Spawning on cursor space would definitely be better, because there's a higher chance that the cursor is on the correct screen than the incorrect one. Also, mouse-follows-focus would keep in consistent if working fully with the keyboard.

**Comment by koekeishiya** [comment]
Is there even really a reason why this should not be the default behaviour?

**Comment by BlueDrink9** [comment]
Sounds like a reasonable approach. Will probably reduce issues with pop-up windows opening on unfocussed spaces and being moved to the current one

**Comment by koekeishiya** [comment]
Implemented on master. I think this is reasonable default behaviour and therefor it is not a config setting to opt in/out of this. I do feel like this is the more intuitive way for things to work, and I have to admit it has been bugging me a lot lately, where I launch an application and then have to manually move it because it spawned at the wrong display.

**Comment by aiguofer** [comment]
👏  this has been bothering me for awhile... looking forward to it! thanks for all your hard work :)
