### ISSUE TITLE
Spotlight position

### ISSUE THREAD

**Issue by qhuyduong** [koekeishiya/yabai#47]
Thank you for your awesome package! I really love it.

Just one minor question: how can I make spotlight center permanently? Currently it always lies on the right side.
![image](https://user-images.githubusercontent.com/16358771/59844382-f2347100-9384-11e9-8038-d6ad3968d679.png)

**Comment by dominiklohmann** [comment]
Click and hold the spotlight icon in the menu bar for a few secs to reset its position, then just don’t move it again. Yabai currently ignores subrole=AXSystemDialog windows and rules have no support for them either (yet?).

**Comment by qhuyduong** [comment]
It worked! Thank you so much @dominiklohmann .
