### ISSUE TITLE
yabai -m space --focus xxx  not work

### ISSUE THREAD

**Issue by daDaiMa** [koekeishiya/yabai#471]
my os version is 10.15.4 
and i do not enable the SIP
the cmd is not work, but it executed without error.
thank you . hope you can help me out

**Comment by dominiklohmann** [comment]
https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

> The following features of yabai require System Integrity Protection to be (partially) disabled:
> - **focus**/create/destroy **space without animation**
> - move space (and its windows) left, right or to another display
> - remove window shadows
> - enable window transparency
> - control window layers (make windows appear topmost)
> - sticky windows (make windows appear on all spaces)
> - move window by clicking anywhere in its frame
> - toggle picture-in-picture for any given window

**Comment by koekeishiya** [comment]
Update yabai and reinstall the scripting addition.
