### ISSUE TITLE
Is there a way to disable opening animations of applications (e.g. Chrome)?

### ISSUE THREAD

**Issue by danijar** [koekeishiya/yabai#472]
I imagine this is a common issue, but I haven't found anything related in the issue tracker. When opening a new window in Chrome, there is an animation that makes it look as if a new display-filling window would open. After this animation finishes, yabai places the new window into the layout grid. Is there a way to disable this opening animation?

**Comment by dominiklohmann** [comment]
I've had these two options changed for a long time now, not sure if they're affecting all applications but it's an improvement at least:

```
# Disable animations when opening and closing windows.
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false

# Accelerated playback when adjusting the window size
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001
```

For these settings to take effect you must logout and login again.

**Comment by danijar** [comment]
This removed the animation, even without having to log out. The window still opens in floating mode first and then snaps into the tiled layout --- I guess there is currently no way to avoid that?

**Comment by dominiklohmann** [comment]
> The window still opens in floating mode first and then snaps into the tiled layout

That's unfixable. Yabai is not replacing the macOS window manager, it's merely acting on top of it.

**Comment by danijar** [comment]
Got it, was worth a try asking :)
