### ISSUE TITLE
Repositioning issue when moving managed windows through macOS native titlebar

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#473]
When a managed window is moved by simply clicking on its titlebar, and it is returned to its region because it was not dropped on another managed window or display, it would in almost all cases be positioned slightly off, because we actually delay the return of the macOS mouse up event until after our processing has finished. The reason for this is to make sure that we do not pass through a mouse up event that should be consumed, because its initial mouse down event was consumed.

**Comment by NickClark** [comment]
So much better now! Thanks!
