### ISSUE TITLE
[feature request] Add zoom-fullscreen info to query

### ISSUE THREAD

**Issue by nwaywood** [koekeishiya/yabai#474]
At the moment, the output of `yabai -m query --spaces` has the field:

`"native-fullscreen": 1`

to let you know whether a space contains a natively fullscreened app in it or not.

However there is no equivalent field to let you know whether or not there is a zoomed window, e.g. 

`"zoom-fullscreen": 1`

My use case for this is to be able to display in my ubersicht bar which spaces have a zoomed window on them. Currently I just have to press my keybinding to toggle `zoom-fullscreen` to check if a window on that space was zoomed or not.  

If you are open to adding this feature, a corresponding event for when a `zoom-fullscreen` is toggled would be amazing (otherwise the ubersicht widget would have to resort to polling)

**Comment by dominiklohmann** [comment]
This is already available as a window query.

```
yabai -m query --windows --window | jq '."zoom-fullscreen"'
```

You can also query this for a whole space by checking if any window on a given space is fullscreen:

```
yabai -m query --windows --space | jq -e 'map(select(."zoom-fullscreen" == 1)) | length > 0'
false
```

**Comment by nwaywood** [comment]
@dominiklohmann oh thats awesome thank you! I guess I didn't play around with all of the query flags enough.

I just double checked and I'm pretty sure there is no event for it though, is that correct? Unless it's included in the `bar_refresh` event?

**Comment by dominiklohmann** [comment]
There is no signal for it. The signals only reflect system events.

As this can be triggered through yabai only, you can just run code when you toggle a windows `zoom-fullscreen` property.

**Comment by nwaywood** [comment]
ah of course! Thanks for the help, I'll try and get this working when I have a sec and post the result here for others who may be trying to do the same/similar thing :)

**Comment by nwaywood** [comment]
Ok it took me a while since I've never written my own `jq` before, but I got it working. I ended up writing a script that inserts the `zoom-fullscreen` variable into the output of `yabai -m query --spaces` so that it can be easily integrated into ubersicht.

Script can be found [here](https://github.com/nwaywood/dotfiles/blob/master/ubersicht-widgets/scripts/spaces-json.sh) for anyone who wants it :)

**Comment by nwaywood** [comment]
@dominiklohmann The above script that I have is really slow because it has to `N + 1` queries, where `N` is the number of spaces. And since it's a bash script, needs to run the commands in series.

Is there a way to get this information in less yabai queries? Atm the ubersicht bar takes 2-3 seconds to update...

**Comment by dominiklohmann** [comment]
You don't need to restrict your query to a single space.

```sh
yabai -m query --windows | jq 'group_by(.space) | map({"\(.[0].space)": (map(select(."zoom-fullscreen" == 1)) | length > 0)}) | add'
```

Example output:

```
{
  "1": false,
  "2": false,
  "3": false,
  "4": false
}
```

**Comment by nwaywood** [comment]
@dominiklohmann thank for the tip about the single windows query 👍 

I ended up implementing it as a node script instead so that I can run the two commands in parallel. It is basically the same speed as just running `yabai -m query --spaces` now.

```javascript
// This script adds the field "zoom-fullscreen" to the output of each object in $(yabai -m query --spaces)
// If a window within a space is currently zoomed in, the value will be 1, otherwise 0
import * as util from "util"
import * as cp from "child_process"

const promiseExec = util.promisify(cp.exec)

const spacesCommand = promiseExec("/usr/local/bin/yabai -m query --spaces")
const windowsCommand = promiseExec("/usr/local/bin/yabai -m query --windows")

Promise.all([spacesCommand, windowsCommand])
    .then(([spacesOutput, windowsOutput]) => {
        const spaces = JSON.parse(spacesOutput.stdout)
        const windows = JSON.parse(windowsOutput.stdout)
        // Add "zoom-fullscreen" to each space object
        const defaultZoomFullscreen = spaces.map(space => ({...space, "zoom-fullscreen": 0}))
        windows.forEach(window => {
            if (window["zoom-fullscreen"] == 1) {
                defaultZoomFullscreen[window.space -1]["zoom-fullscreen"] = 1
            }
        })
        process.stdout.write(JSON.stringify(defaultZoomFullscreen))
    })
```

**Comment by dominiklohmann** [comment]
> I ended up implementing it as a node script instead so that I can run the two commands in parallel.

Note that you can also do this in shell scripts, the syntax just isn't very ergonomic.

Great to see you found a solution to your problem, and thanks for sharing it. 👍
