### ISSUE TITLE
[Request for help] Splitting out the example status bar - what's needed?

### ISSUE THREAD

**Issue by cmacrae** [koekeishiya/yabai#476]
Hey @koekeishiya, @dominiklohmann, et al 👋   

I'd really like to get started writing a stand alone bar for everyone to use along side yabai.  
As expressed in various places, several times - for reasons I completely understand and agree with - it's clear the status bar is not a point of development focus.  

I'm opening this issue in hopes that someone may be willing to help guide me on getting at least the current example status bar split out into its own codebase and building on its own.  

I'm not familiar with C at all (but have always wanted to dabble, so this is a good chance), and so far my efforts are falling short.

Once the bar is split out, I'll be looking to introduce extensibility and other features.

Many thanks in advance for any help anyone is willing to give 🙏

**Comment by johnallen3d** [comment]
https://github.com/somdoron/spacebar

**Comment by cmacrae** [comment]
Ah! Excellent! Thanks @johnallen3d - I'll close this off then

**Comment by koekeishiya** [comment]
I took a quick look at the referenced bar and it inherits a lot of structure from yabai that is unnecessary. This is simply my opinion, but I think it is better to start from scratch and use the code from yabai as a reference when needed. I also think it should be fairly sufficient to rely on the signal and query system for the information you need from yabai, at least this is what I would do.

Some rough outlines as to what this process would look like; how I'd do it anyway:

1. Get a window up and running, and clear the screen. See `src/bar.c bar_create` for reference.
2. Ability to connect, send, and receive information from yabai. See `src/yabai.c client_send_message` for reference.
3. Draw sample information retrieved from socket calls in step2. to the screen. See `src/bar.c bar_refresh` for reference.
4. Implement some way that lets other applications notify your bar (in the future, specific modules) to refresh, for integration with the yabai signal system.
5. Put it all together.
6. Start working on modules (configuration, layout management, partial updating, etc).

**Comment by yanzhang0219** [comment]
The owner of spacebar, @somdoron, replied to me about his plan for this project. And he said he currently has not enough time to develop it further (like modularizing it). Ref: https://github.com/somdoron/spacebar/issues/5#issuecomment-615206497
Hope people who are familiar with macOS API and C could make contribution to it. :P

**Comment by cmacrae** [comment]
@koekeishiya Coincidentally almost exactly a year later; I just got started on a re-write of (soon-to-be-renamed) spacebar.  

Based off your guidance above - which I appreciate and align with - I was wondering: does yabai emit events on its socket?  
Forgive me if that's a naive question, I'm only really now getting my hands dirty with some of the event stuff.

In writing this new bar, one of the improvements I wanted to make was to rely on yabai for notification of specific events, like space changes, window focus change, display focus change, etc. Such that I wouldn't have to implement these event loops in the new bar. I was hoping I might be able to "subscribe" to event messages on yabai's socket, to which the bar could react with callbacks.
