### ISSUE TITLE
Allow specifying optional window id for window commands

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#48]
### Suggested change

Allow specifying optional window id for window commands. If not specified, operate on floating window.

```diff
- yabai -m window <COMMAND>
+ yabai -m window [window-id] <COMMAND>
```

### Motivation

I've written a script that I'm running on the signals window_created and window_focused that automatically floats non-resizable windows. I only need to run it on window_focused because I cannot run `window --toggle float` on background windows.

```sh
#! /usr/bin/env zsh

[[ "$(yabai -m query --windows --window ${2}) | jq '.resizable == 0 and .floating == 0')" == "true" ]] \
       && yabai -m window --toggle float
```

**Comment by koekeishiya** [comment]
I see where you are going with this, and I also think it would be nice to be able to issue commands that interact with arbitrary windows, spaces, displays, based on the Id.

That said, I don't think the current *signal* design is a good fit for this particular job. Even if you could float an arbitrary window the way you do now, what will happen is:

 - a window is created
 - yabai reads properties and w/e, tiles window
 - signal triggers your script
 - the script causes the window to be untiled, marked as floating

Now there are in my opinion two issues, well more like annoyances, with this approach:

 1. The window was tiled upon creation, changing its position and size - which remain even if later unfloated, unless manually repositioned/resized.

 2. Unnecessary flicker when the window spawns, giving it a sloppy feel.

I haven't exactly thought this through yet, but if there was some way to override the default handler for certain types of events, you could hook into the event before it is processed. The event could then be in some sort of "pending" state while you do whatever. At the end of that script you'd then return/set some state and someone notify yabai that this event is ready to be processed. It would then be passed a long through the pipeline as usual.

**Comment by dominiklohmann** [comment]
> interact with arbitrary windows, spaces, displays, based on the Id.

Yes. That's the end goal basically, although I'm not sure how feasible this is for spaces and displays.

You're right about the example flickering and not being nice. It was just that—an example, that was supposed to show how powerful this is. Entire yabai features could be prototyped using signals, then integrated into the actual window manager later on (e.g. this float-if-non-resizable feature).

Signals are currently unfit for returning a modified state because they are executed asynchronously, which I don't think should be given up for this feature. 

There's definitely a lot to consider here.

**Comment by koekeishiya** [comment]
Implemented on master. All `window` commands will now operate on the provided window, or the focused window if none is specified.

sample:
```
yabai -m window 1866 --space 2

yabai -m window 1866 --toggle float

..
```

Closing this. I don't see myself working on a system that would allow what I mentioned above in the near future, but it is probably something that will remain in the back of my head. If I suddenly find the problem to be an interesting problem to solve I'll start working on it automatically.

**Comment by koekeishiya** [comment]
Also regarding the ability to specify an id or some form of selector for the space and display commands as well - I think the best way to go for now is to leave it as it, until  a useful feature or use-case which require said functionality can be found.
