### ISSUE TITLE
Setup, Tiling bsp issue

### ISSUE THREAD

**Issue by timlkelly** [koekeishiya/yabai#480]
Hello, I wasn't able to find anything about this issue in the wiki or past issues, if it present, please point me in that direction.

I previously used chunkwm and skhd on High Sierra. I recently upgraded to Catalina (10.15.4), I have uninstalled chunkwm and installed yabai, however, the tiling does not seem to be working as I would expect. 

Using the example yabairc and skhdrc, I am able to switch application windows via hotkey (`alt + h`, `alt + l`), so it appears that yabai is working, however, there is no tiling happening. As per the default in the example file, the layout option is set to `yabai -m config layout bsp`. 

All windows seem to just float, or act as they normally would in macOS. My expectation is that they would tile as they did when I used chunkwm. I have checked both the err and out logs, both are empty. Sip is disabled, I have made the yabairc executable. `Displays have separate Spaces` is enabled in Mission Control and I have disabled `Automatically rearrange Spaces based on most recent use` in Mission Control.

Have I missed something in the setup? Or have I not properly configured Yabai?

**Comment by dominiklohmann** [comment]
The default option for tiling is `float`. You need to run `yabai -m config layout bsp` in your yabairc if you want it to tile by default.

The reasoning behind this is that by default, yabai should change as little as possible.

**Comment by timlkelly** [comment]
Thank you, that solved this. I am confused though because that is exactly what is in my `.yabairc`. Would that not change the default from `float` to `bsp`?

I noticed the same behavior when attempting to toggle the status bar. Changing it's value to `on` and saving / restarting yabai had no effect. However, it did turn on when I ran that command directly in the terminal.

**Comment by dominiklohmann** [comment]
Yabai looks first at `.config/yabai/yabairc`, then at `.yabairc`. If the file exists and is executable, it is executed asynchronously when yabai starts. It's likely some mistake on your end.

**Comment by timlkelly** [comment]
Hah, yes, I agree. It is most likely a mistake on my end. 

I read the order in which Yabai looks for the configuration file. My thought was that because I don't have a `$XDG_CONFIG_HOME` dir, or a `yabai` dir in `$HOME/.config/`, it would then finally pick up the configuration file at `$HOME/.yabairc`.

I do have this file symlinked from another directory, however, it looks to me that it is still executable. Though maybe there's something I don't understand about symlinked files?

```
lrwxr-xr-x    1 tim   staff     8B Apr 15 22:16 .yabairc -> .yabairc
```

**Comment by dominiklohmann** [comment]
Might also be something that yabai doesn't understand about it. Maybe you can bisect the issue by just iteratively trying to adjust things until you find out what breaks it.

**Comment by timlkelly** [comment]
This turned out to be an issue with the symlink. I removed it and recreated it and it works. Thank you for the help
