### ISSUE TITLE
Would rather cursor is not visible when focusing windows

### ISSUE THREAD

**Issue by Peeja** [koekeishiya/yabai#481]
When I `yabai -m window --focus <direction>` with `mouse_follows_focus`, the mouse cursor becomes visible over the window I've focused, and there's no good way to get rid of it using only the keyboard (unless I happen to want to type text into a text field, and even then apparently not all apps hide the cursor).

Is there a recommended way to deal with this? This is sort of a feature suggestion to hide the cursor when switching `--focus`ing a window, but that may or may not be the best solution.

**Comment by koekeishiya** [comment]
Hmm so there are APIs to control cursor visibility, and IIRC they are not application specific, as it would be in the X windowing system. However, I'm not sure if I want to mess around with cursor visibility as it could maybe confuse the internal state of a given application?

> To hide or show the mouse cursor on any display, use the functions CGDisplayHideCursor and CGDisplayShowCursor. These functions take a display ID as a parameter, but the display ID is not used. Calls to these functions need to be balanced; Quartz maintains a hide cursor count that must be zero in order to show the cursor.

[Source](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/QuartzDisplayServicesConceptual/Articles/MouseCursor.html)

**Comment by Peeja** [comment]
Huh, fascinating. I had no idea that was a stack.

That could be a blessing, though. yabai *could* `CGDisplayHideCursor` on `--focus` and then `CGDisplayShowCursor` on the next mouse movement event. If the app really wanted to keep the cursor hidden, its own `CGDisplayHideCursor` would still stick.

But it does seem a little odd as a responsibility for yabai to have. Perhaps it's a silly idea.

**Comment by koekeishiya** [comment]
I think this is outside the scope of what yabai should handle. Closing this one.
You could try to make a small tool that calls the mentioned functions until the cursor becomes hidden, and hook it up through the yabai signal system, or simply run it manually at the end of your *--focus* binds.
