### ISSUE TITLE
Better separation of floating windows with different border color

### ISSUE THREAD

**Issue by lukakemperle** [koekeishiya/yabai#482]
Would be possible to support the active floating window's *shadow* with different border color in all applications? It would help to separate the floating state in dark mode.  

I tried with this signal without luck:
```
yabai -m signal --add app='^Finder$' event='window_title_changed' \
    action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq "if .floating == 1" | xargs -I{} yabai -m config active_window_border_color 0xffD9742B'
```
Thank you.

**Comment by dominiklohmann** [comment]
Try to run the code in your signal outside of a signal and look at its output, that should help you spot the issue. Your `jq` script is invalid.

**Comment by koekeishiya** [comment]
Closing this as borders are no longer a thing.
