### ISSUE TITLE
Removal of built-in statusbar

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#486]
As I've mentioned in a couple of various issues, the addition of an integrated status bar was a mistake. Creating a good quality bar application is in itself more work than I want to do, considering the other ongoing projects I have.

**Comment by Eyjafjallajokull** [comment]
What are the other options? I really like having info about the number of spaces and currently selected. I know there is https://github.com/kkga/nibar, but running this whole thing with Ubersicht seems to me like huge overkill.

**Comment by koekeishiya** [comment]
I suppose you can check https://github.com/koekeishiya/yabai/issues/463 for now.

**Comment by alin23** [comment]
> What are the other options? I really like having info about the number of spaces and currently selected. I know there is https://github.com/kkga/nibar, but running this whole thing with Ubersicht seems to me like huge overkill.

Someone extracted the statusbar code and added some nice to have features like multiple monitor support and date formatting: https://github.com/somdoron/spacebar

**Comment by SxC97** [comment]
Hi, I'm sorry for commenting after this issue closed, but I made a small plugin for Bitbar that integrates with Yabai to display information about spaces. I thought people might find it useful! https://github.com/SxC97/Yabai-Spaces
