### ISSUE TITLE
Focus stuck on iTerm

### ISSUE THREAD

**Issue by FinnFrotscher** [koekeishiya/yabai#489]
Out of nowhere, any kind of navigation from inside iTerm has stopped working.
Meaning:
```
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east
```
When focus is on any app but iterm, i can navigate without issues. But once focus is on any iterm window, my `alt-hjkl` keystrokes are interpreted as `∆∆¬¬¬¬˚˚˚˚∆∆˙˙˙˙˙`.
It was working fine in the morning. 
Any ideas?

**Comment by dominiklohmann** [comment]
Please check if Secure Keyboard Entry is disabled (skhd cannot work with it enabled by design).

<img width="331" alt="image" src="https://user-images.githubusercontent.com/4488655/80227988-c215c880-864e-11ea-969e-4e2854828734.png">

**Comment by MrZeroo00** [comment]
I had cases where the Secure Keyboard Entry was disabled but somehow got enabled again after my Mac came out of sleep. The only solution I found was rebooting (maybe logging out of the session would work too).

**Comment by dominiklohmann** [comment]
> I had cases where the Secure Keyboard Entry was disabled but somehow got enabled again after my Mac came out of sleep.

That's a known issue where Secure Keyboard Entry is not being properly disabled after the `loginwindow` process exits. It's a bug in the operating system, can't be fixed.
