### ISSUE TITLE
unable to navigate between spaces since catalina

### ISSUE THREAD

**Issue by FinnFrotscher** [koekeishiya/yabai#490]
I upgraded to catalina this morning and since the update, i can not move between spaces. Moving focus and windows inside a space works.

The issue is not with skhd or any layer of keyboard input. Even When i run the commands directlly in iterm, they dont take effect.

```
$ yabai -m space --focus 1                                                                                                                                
cannot focus an already focused space.
$ yabai -m space --focus 2                                                                                                                                

```

**Comment by FinnFrotscher** [comment]
trying https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

**Comment by koekeishiya** [comment]
See #275
