### ISSUE TITLE
Safari resizing when hovering over links

### ISSUE THREAD

**Issue by hokum-ha** [koekeishiya/yabai#491]
Hovering over a link in safari and "alt" text appears for example:

>  alt="Your Text Here"

Causes the window to quickly resize as if a new window has opened. Further from this this autocorrect textbox also has the same effect.

<img width="1389" alt="Screen Shot 2020-04-26 at 12 18 17 am" src="https://user-images.githubusercontent.com/59903628/80282201-7bf65d00-8753-11ea-8146-9bf2d8f07f33.png">

**Comment by dominiklohmann** [comment]
You likely have a rule configured that forces _all_ Safari windows to be tiled.

**Comment by hokum-ha** [comment]
I thought the same however this is my yabairc, minus the padding and border fluff

```
yabai -m config layout bsp
yabai -m rule --add app="^System Preferences$" manage=off topmost=on
yabai -m rule --add app="^Activity Monitor$" manage=off topmost=on
yabai -m rule --add app="^Music$" manage=off topmost=on
yabai -m config mouse_follows_focus on
yabai -m rule --add app="exe$" manage=off
yabai -m rule --add app="^Calculator$" manage=off topmost=on
````

**Comment by hokum-ha** [comment]
Issue can be closed, removed a line relating to qutebrowser fixed this issue, sorry for the spam.
