### ISSUE TITLE
Question: Steam config.

### ISSUE THREAD

**Issue by AlaaSaadAbdo** [koekeishiya/yabai#494]
Hi, First of all thank you very much! I'm really have to have yabai after coming to mac from linux.

When steam app is launched it doesn't get managed by yabai nor recognised. which causes some unwanted behaviour. When switching spaces, the app in the space doesn't get focused.

Is there away to make yabai recognise steam? 

Cheers!

**Comment by kkoscielniak** [comment]
Same here. I've just recognized the same behavior. 

Adding 
```
yabai -m rule --app="Steam" manage=off
```
doesn't work. Probably Steam messes with the whole Mission Control, as even without `yabai` running, the focus does not change between spaces.

**Comment by AlaaSaadAbdo** [comment]
I can also confirm that, as I have this in my config:
```
yabai -m rule --add app="^Steam$" manage=off
```

**Comment by koekeishiya** [comment]
Steam does not interact well with the accessibility API of macOS. If you dig into what they are doing, they also have an invisible window that is "visible" on ALL spaces, but has coordinates set so that it is placed off screen. I don't remember much of the details, but I would have situations (even without yabai running) where this invisible window would make Steam become the front-most application when switching to empty spaces and so forth.

The particular issue you have here

> When switching spaces, the app in the space doesn't get focused.

While I cannot say why this is happening, this is macOS behaviour and yabai does not ovveride this when it is running.

**Comment by AlaaSaadAbdo** [comment]
Thanks for getting back to me on this :)

**Comment by JonathanHuot** [comment]
Hi,

Note that those invisible apps are also took in consideration when changing focus with keyboard. I.e. `yabai -m window --focus north` will focus those invisible windows. Could it be completly ignored by Yabai ?


For the records, I have a similar problem with Microsoft Teams which has invisible "Microsoft Teams Helper" (name in process list) aka "Microsoft Teams Notification" (name in toolbar).
However, this invisible app is like a service running in background and looks different than the regular desktop application, here the "window application" is called "Teams" in process list.

**Comment by koekeishiya** [comment]
The only reason they are included in the focus change is that they report information as if they where actually real windows. There is no way for yabai to tell the difference between these.

**Comment by JonathanHuot** [comment]
Would it be interesting to have the possibility to black list the fake "real" windows ? This black list could be managed by the Yabai users similarly than the `manage=off` (`focus=off` ?) ignoring the focus as well ? Could it help ?

**Comment by butterflysky** [comment]
Interestingly, I don't even see the Steam window in the output of `yabai -m query --windows` on my system (running yabai from latest rev of master), even with Steam in the foreground. I'm curious how Steam is creating these windows and how they are managed in the first place.

**Comment by AlaaSaadAbdo** [comment]
If it's ok with everyone I'll be closing this issue since there's nothing we can do about it here and we can use it as a reference :)
