### ISSUE TITLE
Force 4 windows in a 2x2 grid layout

### ISSUE THREAD

**Issue by macalinao** [koekeishiya/yabai#497]
Hi all, how can I force windows to follow a 2x2 grid layout when there are 4 windows? Yabai keeps splitting things into a 1x4 grid and it's kind of frustrating. Thanks

**Comment by yanzhang0219** [comment]
Yabai is based on binary space partitioning, so 1x4 is what it should be. If you want to 2x2, you can use `yabai -m window --warp ...` to "organize" the layout. Or you can toggle the window to be float by `yabai -m window --toggle float` ant move each one to the four corners of the screen using `yabai -m window --grid ...`. Please refer to the Wiki page for details.

**Comment by koekeishiya** [comment]
By default, yabai will split the window that is currently focused. You can change your focus before opening a new application/window, to change the outcome of the layout.
You can also preselect a region in which the new window should appear, by using the `window --insert ..` command.
