### ISSUE TITLE
Resizing windows is no longer instant

### ISSUE THREAD

**Issue by haze** [koekeishiya/yabai#499]
Sorry I don't have a before video, but I'm not sure what happened;
https://imgur.com/mf7OCsP

In this video, I'm using my `alt-e` and `alt-t` key binds to resize, center and float windows. Before, this would be instant and the window would snap to the center, but now there is an animation that plays and the centering works only when I press the key bind twice.

You can view my skhd config [here](https://github.com/haze/conf/blob/master/.skhdrc)

I've also found that running with `skhv -V` I'm getting these errors when trying the same key binds:
```
cannot apply grid layout to a managed window.
cannot apply grid layout to a managed window.
cannot apply grid layout to a managed window.
```

**Comment by koekeishiya** [comment]
I don't think I can be of much help here. Is that some macOS config or something? I don't remember my windows ever animating like that.

The errors you see from the commands run through skhd is simply saying that the window you are trying to perform a grid operation on is currently being managed by the bsp-algorithm of yabai, and you need to make it floating first.

**Comment by haze** [comment]
I updated and now I no longer have this issue, it was very weird though.
