### ISSUE TITLE
Default behaviour

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#50]
I want to discuss the default behaviour (empty config) of yabai. 

### Proposal 

Options that are not set should reflect what's closest in behaviour to not running yabai at all. 

For example, if I do not have window_border set in my configuration file, yabai should not render window borders at all. 

I am still not sure whether the default layout should be float with no config file set or bsp, although I feel like float makes more sense here.

### Suggested defaults

```sh
yabai -m config status_bar off
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_shadow on
yabai -m config window_border off
yabai -m config split_ratio 0.5
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config layout float
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0
```

**Comment by koekeishiya** [comment]
I don’t think there is much to discuss here. I agree with your proposed defaults.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by koekeishiya** [comment]
Fixed.
