### ISSUE TITLE
Status bar gone after upgrade to v3.0.0

### ISSUE THREAD

**Issue by chenjunweii** [koekeishiya/yabai#500]
I just upgrade to v3.0.0, and status bar gone

Command => `yabai -m config status_bar
`
Output => `unknown command 'status_bar' for domain 'config'`

any idea ? thanks .

**Comment by sunzoje** [comment]
It's discussed over [here](https://github.com/koekeishiya/yabai/issues/486)

**Comment by yanzhang0219** [comment]
Also, in case you care about the window border, it's removed as well (see discussion here #487 )

**Comment by cmacrae** [comment]
Just a heads up for future releases, you can read the changelog here:  
https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md  

It's always linked on the release page

**Comment by koekeishiya** [comment]
Major version increments mean breaking changes. I would recommend always checking the changelog, at least the version number, before upgrading. Minor and patch version increments are both backwards compatible.
