### ISSUE TITLE
Send window to display and follow focus

### ISSUE THREAD

**Issue by vloth** [koekeishiya/yabai#505]
To send window to display and follow focus I have this little shortcut:
```
cmd + ctrl - l  : yabai -m window --display prev; yabai -m display --focus prev
cmd + ctrl - h  : yabai -m window --display next; yabai -m display --focus next
```
Oddly when the window I'm sending to the next display is the latest in the current display the focus doesn't go to the next display (same for prev).

But when I change it to the following snippet everything works as expected:
```
cmd + ctrl - l  : yabai -m window --display prev; yabai -m display --focus 1
cmd + ctrl - h  : yabai -m window --display next; yabai -m display --focus 2
```

Am I correct to assume the first snippet is wrong and I should always query prev/next display indices?

**Comment by koekeishiya** [comment]
The intention is for the first set of commands to work as you initially wanted, but this is a bit tricky because of how macOS window focusing reports across multiple monitors. I would say that this is a bug, but I don't actually know how to solve it at this time.

**Comment by koekeishiya** [comment]
Fixed on master.

**Comment by anildigital** [comment]
@koekeishiya I use following. The issue I have is when window from display 2 is moved to display 1 which has multiple windows, it's not focusing on just moved window. I have to hit cmd + tab to focus to the window. Any solution for this behaviour? Thanks


```
shift + cmd - space : yabai -m window --display prev; yabai -m display --focus prev  || yabai -m window --display next;  yabai -m display --focus next
```

**Comment by yanzhang0219** [comment]
This is not an issue. Try the script below:
```
shift + cmd - space : cur_window=$(yabai -m query --windows --window | jq '.id') && \
                                    yabai -m window --display prev  || yabai -m window --display next && \
                                    yabai -m window --focus ${cur_window}
```

That is, before sending the window, we can firstly get the the id of the current window, and then after the window is sent, we can focus the window with that id.
