### ISSUE TITLE
Everytime upgrading yabai requires updating privacy settings.

### ISSUE THREAD

**Issue by aca** [koekeishiya/yabai#508]
![image](https://user-images.githubusercontent.com/50316549/81073588-cf6e6500-8f22-11ea-9637-895f52249229.png)

Installed with brew. 
I'm suprised that there is no issue about it (or It may be only me experiencing this issue). 
Is there any workaround for this problem?

// I wish I can just turn off all the security things in mac.

**Comment by dominiklohmann** [comment]
From the README:

> **Code Signing**
> When building from source (or installing from HEAD), it is recommended to codesign the binary so it retains its accessibility and automation privileges when updated or rebuilt.

**Comment by aca** [comment]
Sorry missed it. Thanks @dominiklohmann 
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)
