### ISSUE TITLE
Configurable delay for autoraise and autofocus

### ISSUE THREAD

**Issue by Dimentium** [koekeishiya/yabai#509]
It would be nice to have `focus_follows_mouse_delay` in milliseconds for excluding unexpected windows switching.

Expected behaviour:
- Not activating window under pointer while mouse pointer moving;
- After mouse pointer stopped activate window after `focus_follows_mouse_delay`;
- If `focus_follows_mouse_delay` = 0 do it instantly (like current behaviour).

Is it possible?

**Comment by JonathanHuot** [comment]
what is the rationale behind it? can you give a concrete example ? what this is trying to solve?

could it be related to https://github.com/koekeishiya/yabai/issues/483 ?

**Comment by koekeishiya** [comment]
This would require some structural changes for it to work, but yes, it is possible to do this.
I agree with the above comment; can you describe the problem you are trying to solve?

I appreciate that people suggest solutions, but I would like to be able to assess the problem at hand myself, and only then can I properly evaluate the tradeoffs off said solution, and whether or not I think it is appropriate.

**Comment by Dimentium** [comment]
> I agree with the above comment; can you describe the problem you are trying to solve?

There is no problem )
It just my personal preference - to have a little delay before 'focus follow mouse' would be executed.

Right now I use [AutoRaise](https://github.com/sbmpost/AutoRaise) app for this behaviour.

Anyway, thanks a lot for great app!🍺

**Comment by koekeishiya** [comment]
I don't think that I am interested in adding this, sorry.

**Comment by tariqc80** [comment]
Hmmm, this is a pretty important feature for those that use focus follows mouse.  I wonder if there's another work around that other use?    The issues is this, occasionally it's necessary to drag the pointer across a field without losing focus.  For example, navigating to a hover popup window, or navigating to the menu bar when another window is in the way; if we lose focus, the popup will close, or the menu bar context will switch.  Sometimes this can break functionality in apps.  I provided an example of how setting `focus_follows_mouse` to `autofocus` will break functionality in the UI for Zoom

I also demonstrate how it's not possible to access the menu bar when you stack windows.  I have my terminal app and Firefox arranged in tiles; I can't get to the menu for kitty.

I really love that yabai has focus follows mouse, it's something that I've been missing on macOS for years.  AutoRaise app does work well, but it's much cooler to have it built into yabai.




https://user-images.githubusercontent.com/7843563/137838632-913e49da-7c3e-4a38-863f-28da079a596f.mov


https://user-images.githubusercontent.com/7843563/137838648-1bdb88c5-717b-4be3-8436-e6cb0a949abb.mov

**Comment by caduellery** [comment]
The problem here is that I have one screen above the other, then when I simply move the cursor from my top screen to the bottom screen, it activates the menu bar items of the bottom screen.

https://user-images.githubusercontent.com/10601241/148644895-f1ffdfab-a4a6-4ff6-b357-70bdca83d340.mov
