### ISSUE TITLE
Show space type in bar

### ISSUE THREAD

**Issue by xiamaz** [koekeishiya/yabai#51]
Currently spaces in yabai can either be floating or tiling. Sometimes it would be nice to know in which state the current space is, without having to toggle the state or to try to move windows around.

It would be useful to show the current space type in the bar.

**Comment by koekeishiya** [comment]
I don't think I will be making the bar more configurable through settings. It was just meant to be something very simple to provide an alternative to the Übersicht bar I personally used previously. A lot of people sent me emails asking about it, so I figured I'd provide something similar a long with the window manager.

That said, the entire code for creating, configuring and drawing the bar is isolated in bar.c, so it should be very trivial to maintain your own fork where you can do whatever you want to with regards to the status bar, without risking any merge conflicts when you want to pull from upstream.

If you have questions regarding the statusbar code, feel free to create an issue regarding that, and I'll try to help out.

**Comment by xiamaz** [comment]
I have already implemented something like that. The issue is that it requires adding an event triggered on settings change, eg change of space type.

It would be great if you could consider adding an event triggered on changes to view settings. I can also provide a PR for my solution

**Comment by koekeishiya** [comment]
Hmm yeah I see the issue you're having. I don't at this time think it is appropriate to use the current event system for that purpose. I have not given this particular problem any thought, so it is hard for me to suggest a good way of doing what you require.

While adding an event that is triggered when a view changes settings is a way to achieve this, it doesn't feel like the proper route to go.

I'll keep this in mind as iteration are made, but I can't make any promises at this time.

**Comment by kiryph** [comment]
I would also be interested in showing the current layout 'bsp' or 'float' in the status bar.

I do not like Übersicht and would appreciate if the status bar would not be abandoned and actually would improve over time.
