### ISSUE TITLE
Querying active rules

### ISSUE THREAD

**Issue by ajbw** [koekeishiya/yabai#511]
How does one query or list active rules?  I'm seeing some weird behaviour which I _think_ is being caused by a rule, but I can't figure out how to get a listing of active rules.  I've tried a variety of different candidates, such as:

```
❯ yabai -m rule --show
unknown command '--show' for domain 'rule'
❯ yabai -m rule --list
unknown command '--list' for domain 'rule'
❯ yabai -m rule --query
unknown command '--query' for domain 'rule'
❯ yabai -m query --rules
unknown command '--rules' for domain 'query'
```

Any clues?  I'm really enjoying using yabai, but the behaviour I'm trying to diagnose is irritating, and not being able to just view active rules to figure out where to look next is frustrating.

**Comment by koekeishiya** [comment]
It's not possible to list registered rules. Yabai does not currently store enough information to correctly echo back out the information that it received, as we init regex structures for matching patterns during init and we don't store the original text.

**Comment by koekeishiya** [comment]
Implemented on master.

**Comment by koekeishiya** [comment]
Sample output:
```
~ yabai -m rule --list | jq                                                                       0:52
[
  {
    "index": 0,
    "label": "",
    "app": "^Mail$",
    "title": "",
    "display_id": 0,
    "space_id": 7,
    "follow_space": 0,
    "opacity": 0,
    "manage": -1,
    "sticky": -1,
    "layer": "",
    "native-fullscreen": -1,
    "grid": "0:0:0:0:0:0"
  },
  # .. removed for brevity
  {
    "index": 8,
    "label": "",
    "app": "^Xcode$",
    "title": "",
    "display_id": 0,
    "space_id": 0,
    "follow_space": 0,
    "opacity": 0,
    "manage": 0,
    "sticky": -1,
    "layer": "",
    "native-fullscreen": -1,
    "grid": "0:0:0:0:0:0"
  }
]
```

Remove by using the index from the output: `yabai -m rule --remove 1`
Note that the index is based on its location in the list and is not a fixed identifier, e.g if you remove rule with index 4, the rule that previously had index 5 will now become index 4.

**Comment by ajbw** [comment]
I just got the chance to try this out; it works great.  Thanks for adding the feature!
