### ISSUE TITLE
Querying for windows does not return visible: 0 for hidden apps

### ISSUE THREAD

**Issue by aaraney** [koekeishiya/yabai#515]
`yabai -m query --windows` does not provide information on the hidden status of an app. Is this the intended functionality? It seems that no matter if an app/window is minimized, open, or hidden the `visible` attribute is never altered. 

See the below output. In this example terminal is open and visible and Firefox is open but hidden. 

``` bash
$ yabai -m query --windows --display 
[{
	"id":90,
	"pid":302,
	"app":"Terminal",
	"title":"austinraney — yabai -m query --windows --display — yabai — -zsh — 99×44",
	"frame":{
		"x":561.0000,
		"y":36.0000,
		"w":1015.0000,
		"h":864.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":1,
	"focused":1,
	"split":"none",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"shadow":1,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":895,
	"pid":2463,
	"app":"Firefox",
	"title":"Mozilla Firefox",
	"frame":{
		"x":0.0000,
		"y":378.0000,
		"w":1600.0000,
		"h":522.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXDialog",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":1,
	"visible":1,
	"focused":0,
	"split":"none",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"shadow":1,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}]
```

System info:
macOS 10.14.4
yabai-v3.0.0 installed from HEAD using brew

**Comment by koekeishiya** [comment]
So the `visible` attribute indicates that the window belongs to a space that is currently visible. See #116 for reference. Maybe that is an ambiguous name and the query attributes should probably be a part of the provided documentation. There is no attribute to check whether the application itself is hidden, but there is an attribute `minimized`.

**Comment by aaraney** [comment]
@koekeishiya thanks for the clarification. Adding it to the querying documentation would definitely be helpful, I can address that in a future PR. I added functionality in `window` to supply if an application is hidden or not and plan to open a PR for review, I hope you will accept the feature. 

Background on the feature request: I would like to continue to use yabai on an ultra wide display but add rules to govern window sizes based on the number of active windows. Personally, I hide apps a good bit over minimizing them, so having the ability to keep a count of active visible (not minimized or hidden) windows will be sufficient to make such a rule.
