### ISSUE TITLE
Allow adding padding on a display

### ISSUE THREAD

**Issue by entropitor** [koekeishiya/yabai#517]
In my setup, I want to add padding to all spaces on one display and when I move a space onto that display, also have the padding applied. Currently however, padding is set on a space, not on a display.

Would it be possible to add this?

**Comment by koekeishiya** [comment]
Unlikely to add this as it can already be achieved by writing some small scripts at the user-level.

**Comment by entropitor** [comment]
@koekeishiya It would be possible but it would have to store the required padding size somewhere and reset it on every desktop / space change event from yabai (so when a desktop is added / removed, things get updated and same if space moves across desktop)

**Comment by koekeishiya** [comment]
You could just query the padding from an existing space that belongs to the target display: yabai -m config --space 3 top_padding and set the padding automatically in your bind that moves the space to the target display.

**Comment by koekeishiya** [comment]
Closing this as a subset of #598
