### ISSUE TITLE
Chrome DevTools

### ISSUE THREAD

**Issue by xseman** [koekeishiya/yabai#518]
I can't get DevTools to be `manage=off`

My rule
`yabai -m rule --add app="Chrome" title="^DevTools$" manage=off`

Any tips? Thanks!

**Comment by haukeadler** [comment]
The title changes shortly after the window has been created. If you look closely, the title starts with "devtools://..." so the following rule does the trick:

`yabai -m rule --add app="^Google Chrome$" title="^devtools" manage=off`
