### ISSUE TITLE
Application-level queries

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#520]
This is an idea I've had while reading #515, and the exact scope I am yet unsure about: The introduction of a fourth level of queries named `apps`, for all application-level stuff for applications that have at least one window handled by yabai.

I've sometimes also found myself wanting to restrict queries to applications. E.g., for getting all windows of the current application, this could then be used: `yabai -m query --windows --app`.

Let's gather some thoughts on this.

**Comment by aaraney** [comment]
@dominiklohmann Personally I don't see the need for that level of abstraction in yabai. Given that every query is handled using some `json` parser, you should be able to use a filter or selection to obtain what you want. This is what I thought before I wrote some `jq` to do what you were thinking of... it was a pain to say the least.

``` bash
yabai -m query --windows | \
jq '.[] | {app: .app, focused: .focused, id: .id}' | \
jq -s 'group_by(.app) | map({app: .[0].app, ids: map(.id), focused: (map(.focused) | add)}) | map(select(.focused==1))'
```

I agree with you @dominiklohmann it would make it much easier to implement some interesting rules and signals.

**Comment by koekeishiya** [comment]
I'm not sure if this is worth the complexity. I feel like this breaks the intended interface of the query system (3x3 + optional) system that is in place. There is also no backing for applications in yabai as of now. Something like this would therefor be pretty much just as expensive as if you where to simply write 2 queries in the current system.

**Comment by dominiklohmann** [comment]
I tend to agree with you the more I think about the implications. The added complexity is just too much.
