### ISSUE TITLE
[Question] How to go from a vertical split to a horizontal split?

### ISSUE THREAD

**Issue by denisidoro** [koekeishiya/yabai#522]
Sorry if it's a noob question but I've been using chunkwm/yabai for ~2 years and I haven't figured this out yet.

Let's say I have two windows like this:
```
==========================
          window 1
--------------------------
          window 2
==========================
```

How can I change it to this?
```
==========================
            |
  window 1  |  window 2
            |
==========================
```

**Comment by dominiklohmann** [comment]
Three ways:

- `yabai -m window --toggle split`
- Drag window 1 to the left quarter of window 2
- Drag window 2 to the right quarter of window 1

**Comment by johnallen3d** [comment]
One more (hacky) options?

```
yabai -m space --rotate 90
```

**Comment by denisidoro** [comment]
@johnallen3d thanks! this is what I used to do, but the behavior wasn't what I expected when a display has 3+ windows

**Comment by johnallen3d** [comment]
Makes sense @denisidoro! I just tried out `yabai -m window --toggle split` with 3 windows. 😍
