### ISSUE TITLE
Some Windows Are Out of Management

### ISSUE THREAD

**Issue by y1rah** [koekeishiya/yabai#523]
![image](https://user-images.githubusercontent.com/30183249/81825785-a1fc6980-9569-11ea-8d19-02fc84f3c70e.png)

For example, the **matlab** loses window manage, it seems `.app` of this software falls into a deep root of the directory.

How to manage this and the sub of matlab windows.

**Comment by y1rah** [comment]
Though it is solved by:

```
yabai -m rule --add label="MATLAB" app="^MATLAB$" manage=true
```

in `.yabairc`, but why the default is `off`?

Is this due to being non-direct child of the root of applications directory?

**Comment by y1rah** [comment]
Again, matlab seems follows rule only when:

`MatLab Open -> Yabai Restart` when the config file is set as above.

It fails when yabai is already started then open the software.

![Screen Shot 2020-05-13 at 11 11 19 PM](https://user-images.githubusercontent.com/30183249/81830787-1be32180-956f-11ea-8323-381e7e54a7a4.png)

May this related to **yabai reckon it as a folder**?

**Comment by koekeishiya** [comment]
Try to run yabai from the master branch. I think these issues should be resolved.

**Comment by koekeishiya** [comment]
Should be fixed in the latest release.
