### ISSUE TITLE
Can yabai move a window to the display that is on the left?

### ISSUE THREAD

**Issue by danijar** [koekeishiya/yabai#526]
On Linux, I used i3 which has a nice way to support multiple displays. The key combination <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>H</kbd> moves a window to the left in the tree. Usually, this would just swap the window with one that is further left on the same display. But if the window is already left most on the display, it moves the window over to the next display on the left.

I would like to replicate this behavior with yabai because I've found myself not use my displays on the side as much when I manually have to think about which workspace to send a window to.

**Comment by koekeishiya** [comment]
If the provided *display selectors* are not enough you can use the script mentioned in this issue: https://github.com/koekeishiya/yabai/issues/225

**Comment by koekeishiya** [comment]
#225 is implemented on master and allows the usage of cardinal directions to target a display. In your case `yabai -m display --focus west` should do what you want based on the original question.

**Comment by danijar** [comment]
Thank you! I assume the correct way to do what I was trying is this?

```
alt - h : yabai -m window --focus west || yabai -m display --focus west
alt - j : yabai -m window --focus south || yabai -m display --focus south
alt - k : yabai -m window --focus north || yabai -m display --focus north
alt - l : yabai -m window --focus east || yabai -m display --focus east
```

**Comment by koekeishiya** [comment]
As far as focusing goes, yeah, that does seem correct to me.
I noticed that you also mentioned swapping windows in your original question, and that would be something like `yabai -m window --swap west || yabai -m window --display west`.

They'll be in the next release, yeah. If you don't mind running from the master branch, it is usually very stable, except for when I decide to make breaking changes, but you can just look at the changelog before updating to see what changes have been made.

I don't have a set schedule for when a new release is made. It mostly depends on what changes have been made and if I think some of them are important enough to get out before any additional major changes. I suppose it also depends on how much I think I will be working on the project in the upcoming days/weeks.

If there has been a reasonable amount of changes and I don't think I'll be doing too much in the near future, I usually do a release.

**Comment by danijar** [comment]
Got it, thanks!

**Comment by danijar** [comment]
@koekeishiya Can you think of a solution to this?

**Comment by koekeishiya** [comment]
You can focus the new display first and then set the the insertion point by using `yabai -m window last --insert east` or query the active space of the target display, retrieve the window_id from last-window and use that to set the insertion point on that space.

Alternatively if you don't mind some jumping around, the absolute simplest way is to simply move the window, follow focus, and then just `yabai -m window --warp last`.

**Comment by danijar** [comment]
Thanks! Would last work here? When moving a window to the west screen, it should take the east edge of that screen. When moving to the east screen, it should take the west edge of that screen.

**Comment by koekeishiya** [comment]
For _east_ you can use _first_ instead of _last_, but same strategy as mentioned previously.

Sent from my iPhone

On 24 Jun 2020, at 16:51, Danijar Hafner <notifications@github.com> wrote:

﻿

Thanks! Would last work here? When moving a window to the west screen, it should take the east edge of that screen. When moving to the east screen, it should take the west edge of that screen.

**Comment by vizcay** [comment]
I came here trying to find a way to rotate the focused window between displays AND keeping the focus. End up doing:

```bash
WIN_ID=$(yabai -m query --windows --window | jq '.id') && yabai -m window --display recent && yabai -m window --focus $WIN_ID
```

Maybe someone finds it useful.

**Comment by restfuladi** [comment]
> You can focus the new display first and then set the the insertion point by using `yabai -m window last --insert east` or query the active space of the target display, retrieve the window_id from last-window and use that to set the insertion point on that space.
> 
> Alternatively if you don't mind some jumping around, the absolute simplest way is to simply move the window, follow focus, and then just `yabai -m window --warp last`.

First, Yabai is amazing, thank you so much for creating it. I'm not upgrading OSX again until I'm sure Yabai works.

This thread has improved my workflow almost to the point of perfection. One thing is missing, I'm not able to get the "swap across displays" function to work right. For example, `ctrl + shift - left  : yabai -m window --swap west || $(yabai -m window --display west; yabai -m display --focus west; yabai -m window last --insert east)`, the window still moves to the west side of the destination display (instead of inserting on the east side) and I get a strange red box in the east-most window. 

If someone can help me figure this out I'll be in nirvana. Thanks.

**Comment by kerryj89** [comment]
Here is how I got it working, it could probably be simplified but I couldn't fuss with it any longer.

```
shift + ctrl - left : WIN_ID=$(yabai -m query --windows --window | jq '.id'); yabai -m window --swap west; [[ ! $? == 0 ]] && (yabai -m display --focus west; yabai -m window last --insert east; yabai -m window --focus $WIN_ID; yabai -m window --display prev; yabai -m window --focus $WIN_ID);
shift + ctrl - right : WIN_ID=$(yabai -m query --windows --window | jq '.id'); yabai -m window --swap east; [[ ! $? == 0 ]] && (yabai -m display --focus east; yabai -m window first --insert west; yabai -m window --focus $WIN_ID; yabai -m window --display next; yabai -m window --focus $WIN_ID);
```

**Comment by SnackForever** [comment]
> Here is how I got it working, it could probably be simplified but I couldn't fuss with it any longer, using some of koekeishiya and vizcay's ideas.
> 
> ```
> shift + ctrl - left : WIN_ID=$(yabai -m query --windows --window | jq '.id'); yabai -m window --swap west; [[ ! $? == 0 ]] && (yabai -m display --focus west; yabai -m window last --insert east; yabai -m window --focus $WIN_ID; yabai -m window --display prev; yabai -m window --focus $WIN_ID);
> shift + ctrl - right : WIN_ID=$(yabai -m query --windows --window | jq '.id'); yabai -m window --swap east; [[ ! $? == 0 ]] && (yabai -m display --focus east; yabai -m window first --insert west; yabai -m window --focus $WIN_ID; yabai -m window --display next; yabai -m window --focus $WIN_ID);
> ```
My version, i have just my mac and an other monitor
```
#!/bin/bash

# Get the ID of the focused space's current display
FOCUSED_SPACE=$(yabai -m query --spaces | jq -r '.[] | select(.["has-focus"] == true) | .index')
# Get the display on which the focused space is located
CURRENT_DISPLAY=$(yabai -m query --spaces | jq -r ".[] | select(.index == $FOCUSED_SPACE ) | .display")
echo $FOCUSED_SPACE
echo $CURRENT_DISPLAY
# If the space is on display 1, move it to display 2, and vice versa
if [ "$CURRENT_DISPLAY" -eq 1 ]; then
    TARGET_DISPLAY=2
else
    TARGET_DISPLAY=1
fi

# Move the focused space to the target display
yabai -m space $FOCUSED_SPACE --display $TARGET_DISPLAY

sketchybar --trigger space_change --trigger windows_on_spaces
```
