### ISSUE TITLE
Set app to be topmost window and float?

### ISSUE THREAD

**Issue by Jarvvski** [koekeishiya/yabai#527]
I'm checking the docs for anything about setting the window layer for a given app via rules.

I see `layer` but that doesn't seem to achieve what I waned.

Essentially;

If $app is open, I'd want it to float and always be on top of my windows - similar to a _picture in picture_ stream

Here's what I've currently got:

```sh
yabai -m rule --add app="^zoom.*$" sticky=on layer=above manage=off
```

As far as I read from the docs:

- sticky would mean it's on every space/monitor I look at
- layer _should_ be keeping it on top of other windows
- manage disables the bsp tiling, so it floats

What should I be doing instead?

**Comment by koekeishiya** [comment]
That looks correct to me; try to simply make it target `^Safari$` to verify that.

**Comment by Jarvvski** [comment]
So it's the native zoom app - not safari

Notice how I switch focus to the editor in Img 2 - it hides the zoom window

![image](https://user-images.githubusercontent.com/6012840/82223662-fde13c80-9933-11ea-8904-5f9b8569c9db.png)
Img 1

![image](https://user-images.githubusercontent.com/6012840/82223810-37b24300-9934-11ea-9c1f-8b0dd965ef05.png)
Img 2

**Comment by koekeishiya** [comment]
Does the window hide itself when the application is deactivated (https://developer.apple.com/documentation/appkit/nswindow/1419777-hidesondeactivate)?

This just simply looks like Zoom decides to override the window property we set.
Move the zoom window further up on your screen so that it remains visible to you when you change focus to the editor application. If the window remain visible, but occluded, we can maybe try to investigate further. If the window is simply hidden, then I don't think there is much to be done.

topmost & sticky work just fine for the applications that I use it for, so I don't think this is a bug in yabai.

**Comment by Jarvvski** [comment]
Thanks for the speedy reply @koekeishiya 

So, here's the window in the background - behind the editor

(you can see the title bar in the top right of the screen)

![image](https://user-images.githubusercontent.com/6012840/82231890-e3609080-993e-11ea-9aec-6fb554cf36bc.png)

**Comment by koekeishiya** [comment]
Can you try to see if the following works for you on *Finder* windows: `yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off`

**Comment by Jarvvski** [comment]
@koekeishiya 

![image](https://user-images.githubusercontent.com/6012840/82240729-f62d9200-994b-11ea-93b1-7e1232adbb91.png)


Doesn't seem to want to work for me

I don't have SIP disabled though, so is this one of those SIP only features?

**Comment by koekeishiya** [comment]
This feature requires SIP to be disabled, yes.

**Comment by Jarvvski** [comment]
Damn. Ok, that solves it then.

Thanks

**Comment by bedeio** [comment]
Hey, I have SIP disabled and this is not working for me.

I am on an M1 Mac Mini with BigSur 11.2.3.

Tried what was suggested above and messing with the global `window_topmost` config and toggling `topmost` on focused window via hotkey.

Any ideas?

**Comment by Jarvvski** [comment]
> on an M1 Mac

@bedeio disabling SIP is used to inject code into the Dock.app. But, the arch is different for M1 macs so you need to do more than just disable SIP

There's a big issue open [here](https://github.com/koekeishiya/yabai/issues/725) that discusses this. There's an unofficial fork that works, but @koekeishiya is rightly waiting until M1 is better supported on whatever m2/2nd gen products come out in the future.

**Comment by basbebe** [comment]
I noticed a similar behavior using vlc.

I have 
`yabairc`
```sh
yabai -m rule --add app=VLC manage=off border=off
```

`skhdrc`
```bash
# toggle float
ctrl + alt - space : yabai -m window --toggle float

# toggle sticky
ctrl + alt - s : yabai -m window --toggle sticky ; \
                 yabai -m window --toggle topmost ;
```


It seems like from time to time when minimize vlc after making it sticky, the 'topmost' property is lost.
When I then toggle <kbd>ctrl</kbd> + <kbd> alt </kbd> + <kbd>s </kbd> again, the window is topmost but not sticky (I would have to quit and restart vlc to reset state).

Is this considered a bug or did I do a mistake in my config?

Or just a curious behavior of vlc?

**Comment by yar00001** [comment]
Just wanted to mention I also have this issue. Floating works but the window doesn't stay on top. This is my settings for Slack:

```
yabai -m rule --add app="^Slack$" sticky=on layer=above manage=off
```

![image](https://user-images.githubusercontent.com/2102983/133342012-5f150ef2-2d5b-4205-a3ec-603f070a24c3.png)

**Comment by CameronBurley** [comment]
Hello @Jarvvski what theme is this? It's so nice.

**Comment by lukebarton** [comment]
> Hello @Jarvvski what theme is this? It's so nice.

It's Tokyo Midnight, I believe
