### ISSUE TITLE
Ease process type restrictions and rework observation requirements

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#529]
Experimenting with changes to more accurately target processes that we should attempt to observe and how we decide when to give up.

The *current* method is fairly strict and filters out quite a few processes that we should not.
A native macOS application example of this is the application *System Information*, or the fairly popular application Hammerspoon (#502). Other examples can be found by searching the issue board. 

This new process filter ignores the process if it is an XPC service, or if it is marked as LSBackgroundOnly. If a process passes this filter, we don't try to observe through the AX Observer API right away (and retry every 10ms if it fails), like we used to. Instead, we query the NSApplications "is finished running" state. If an application is not yet finished running, we check again in 1ms, repeatedly. When an application reports as finished launching, we check the NSApplications [activation policy](https://developer.apple.com/documentation/appkit/nsapplicationactivationpolicy?language=objc) and make sure that it is NOT *prohibited*. Applications that are marked as *prohibited* is ignored.

We then try to subscribe through the AX Observer API *once*. If this fails there is something faulty with the application or system and we give up.

There is a potential problem with this new strategy: 

> The value of this property corresponds to the running application having received an NSApplicationDidFinishLaunchingNotification notification internally. Some applications do not post this notification (applications that do not rely on NSApplication) and so are never reported as finished launching.`

This can be solved by using key-value observation rather than doing a dumb infinite retry.

Edit (Summary):

Yabai will now initially accept ALL process types except for XPC processes.

We then check whether it is a background process or not. If it IS a background process,
we subscribe to changes to the *activation policy* property. This allows us to pick up processes that for some reason reports as a background process upon startup, but changes type rapdily after being launched (or slowly for that matter). If it is not a background process, we continue.

We then check whether the process has finished launching or not. If the process has not finished launching, we subscribe to changes to the *finishedLaunching* property. This allows us to get rid of polling, effectively reducing system load and helps the application be more responsive while other software is launching. If the process has finished launching, we continue.

Finally, if the above steps complete properly, we try to subscribe to AX notifications. If this fails we ignore the application.

**Comment by koekeishiya** [comment]
The new method has been implemented as described above. Key-value observation is NOT yet implemented, but probably should be, before this is considered finished.

This appears to work better for me with the applications that I use. I don't use a lot of the applications that people have reported in the issue board, and so it would be nice if other people could run this version (preferably with debug output enabled) and report back after some time.

**Comment by koekeishiya** [comment]
Implemented key-value observing and whatever. Edited the original post to reflect the change that have been made.

**Comment by lwouis** [comment]
Hi @koekeishiya! First, thanks a lot for sharing this new development, as we face the same demons (pun intended) for AltTab. Some remarks:

* You're replacing polling with KV observers. I'm wondering how efficient these are. I assume way more efficient, but I'm actually curious as to how macOS implements them. Overall, we are doing KV observing in AltTab also, for the `NSApplication.isFinishedLaunching` property to check when an app is finished launching. I have whitelisted some specific app that have the wrong `NSApplication.activationPolicy` after they have `.isFinishedLaunching == true`. It may be useful to listen to changes of `.activationPolicy` in the future to be more forgiving to incorrect apps.

* I believe your current approach misses on some use-cases. I suggest you see how it works with big apps that have a splash-screen or loading bar at launch. The example I use for this is Gimp. When started, it will quickly report `.isFinishedLaunching == true` and `.activationPolicy == .regular`. However attempt to call the AX observer API will fail. At this point in time, the app is showing a loading window to the user.

  After a while, it finishes loading, and calls to the AX observer API will succeed. It still has `.isFinishedLaunching == true` and `.activationPolicy == .regular` at this point. This is where polling is the only option I found. This is the big blocker for me: a process that gives all the signals to be showing windows, and finished launching, but is actually still loading. There is nothing to observe that's going to change when the app is actually ready to be sub'ed to, that's why today we still poll for 2min before giving up.

  The worst part is that these must be fairly common, especially with pro-software like Photoshop, Adobe AfterEffects, AutoCAD, AutoDesk, Maya, Blender, etc.

**Comment by koekeishiya** [comment]
Hmm interesting. I’ll give gimp a shot. I tested with photoshop and that works as expected.

Sent from my iPhone

On 19 May 2020, at 08:33, lwouis <notifications@github.com> wrote:

﻿

Hi @koekeishiya<https://github.com/koekeishiya>! First, thanks a lot for sharing this new development, as we face the same demons (pun intended) for AltTab. Some remarks:

  *   You're replacing polling with KV observers. I'm wondering how efficient these are. I assume way more efficient, but I'm actually curious as to how macOS implements them. Overall, we are doing KV observing in AltTab also, for the NSApplication.isFinishedLaunching property to check when an app is finished launching. I have whitelisted some specific app that have the wrong NSApplication.activationPolicy after they have .isFinishedLaunching == true. It may be useful to listen to changes of .activationPolicy in the future to be more forgiving to incorrect apps.

  *   I believe your current approach misses on some use-cases. I suggest you see how it works with big apps that have a splash-screen or loading bar at launch. The example I use for this is Gimp. When started, it will quickly report .isFinishedLaunching == true and .activationPolicy == .regular. However attempt to call the AX observer API will fail. At this point in time, the app is showing a loading window to the user.

After a while, it finishes loading, and calls to the AX observer API will succeed. It still has .isFinishedLaunching == true and .activationPolicy == .regular at this point. This is where polling is the only option I found. This is the big blocker for me: a process that gives all the signals to be showing windows, and finished launching, but is actually still loading. There is nothing to observe that's going to change when the app is actually ready to be sub'ed to, that's why today we still poll for 2min before giving up.

The worst part is that these must be fairly common, especially with pro-software like Photoshop, Adobe AfterEffects, AutoCAD, AutoDesk, Maya, Blender, etc.

**Comment by koekeishiya** [comment]
@lwouis CopyQ works just fine for me. I notice that it does go through a change in activation policy, so I definitely think you will benefit from implementing that as well. I'm not sure how alt-tab is structured with regards to this, but so far I've observed that the activation policy could change either before or after *isFinishedLaunching* has been set to true, so you need to support out-of-order initialization here. This was trivial to do in yabai due to how the event system is implemented here.

**Comment by lwouis** [comment]
>  I noticed that it failed with the message kAXErrorCannotComplete

Yes this is what I observed with other apps as well. Also interesting to note is that the OS will block the subscription call up to around 6s, so using polling and counting the attempts is not correct as the time blocked on the call is variable. In AltTab, I added a clock check and stop polling after 2 wall-clock minutes.

> @lwouis CopyQ works just fine for me. I notice that it does go through a change in activation policy, so I definitely think you will benefit from implementing that as well.

Thanks for this info! I'll open a ticket and definitely implement this, as it's more flexible, and apps that change their policy seem to be relatively common.

**Comment by lwouis** [comment]
Hey @koekeishiya! I implemented observing `.activationPolicy` in AltTab. It's indeed the right way to go. I could remove the hardcoded exception for CopyQ, Octave.app, and Parsec, and I've seen just today that it also fixed Wine. It's clearly an improvement.

I noticed in 5186e25 that you have struggled a bit with the KVO API. I also had some issue with `removeObserver`, and moved to the `.observe` API. I think it may be Swift only. I'm not sure if there is any way for you to use it from C. It's block-based, and there is no need to manually call `removeObserver` as freeing references to the pointer you can from calling to subscribe removes the observer automatically. There is also an `.invalidate` method to manually stop observing. Just sharing in case that helps you

**Comment by koekeishiya** [comment]
> It's clearly an improvement.

Glad to hear that observing the activation policy was a success. I checked briefly and it appears that the `.observe` in which you can pass a block is Swift-only. I'm not completely sure how the NSRunningApplication memory is managed either; if you call *get NSRunningApplicationForPID* multiple times, does it allocate a new instance or does it return the same one, because that changes how I need to think of managing the KO-observation.

You are correct that I use an older Carbon API to monitor processes. I have tried various methods during the last couple of years, and the Carbon event API was the most reliable one.
