### ISSUE TITLE
Is it possible to disable yabai in specific space?

### ISSUE THREAD

**Issue by cxa** [koekeishiya/yabai#53]
Hi,

I was a chunkwm user, and recently transferred to yabai.

What feature I miss in chunkwm is, when you set some space to float(`chunkc set 1_desktop_mode float`), it will not touch the window settings. But I can't find a way to follow this behavior in yabai. So my question is, will future version consider to add this feature?

**Comment by dominiklohmann** [comment]
```sh
yabai -m config --space 1 layout float
```

**Comment by cxa** [comment]
Thanks.

Sorry I didn't describe cleanly. I mean when space layout is float, don't follow the global window settings, I've tried

```
yabai -m config --space 1 window_border  off
```

but not work.

As I checked documentation, currently only `layout` works on different space but not `window_*` settings.

**Comment by dominiklohmann** [comment]
What you're trying to achieve is just not possible right now. 

I've tried coming up with some automation for disabling borders on floating spaces that you could use as a workaround, but sadly the window queries do not return whether borders are currently enabled for a window or not, which, combined with the fact that there's only a toggle action, makes them unusable for scripting.

**Comment by cxa** [comment]
Thanks, I got it.

**Comment by JonathanHuot** [comment]
In case you want to toggle current space between `bsp` and `float`:

`yabai -m config --space $(yabai -m query --spaces --space|\jq -r .index) layout $(yabai -m query --spaces --space |jq -r 'if .type|contains("float") then "bsp" else "float" end')`
