### ISSUE TITLE
Is it possible to disable yabai in some specific desktops?

### ISSUE THREAD

**Issue by weikang-q** [koekeishiya/yabai#532]
MacOS can have multiple desktops and you can swiped between them use your fingers. But for some desktops, I don't want to arrange my windows strictly. So I want to disable yabai in those desktops. Is it possible?

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/yabai/wiki/Configuration#layout

**Comment by weikang-q** [comment]
I am so sorry for my carelessness. Actually I did not know what 'space' means before.
