### ISSUE TITLE
Yabai update message showing every 5 seconds

### ISSUE THREAD

**Issue by rodrigopsasaki** [koekeishiya/yabai#534]
For some reason now I get a popup saying that a new version of yabai was installed and it will restart shortly

> A new version of yabai was just installed and yabai will restart shortly.

Just keeps popping up non-stop every 3~5 seconds. Does anyone know what this is?

**Comment by rodrigopsasaki** [comment]
Tried restarts and different configs to get it to stop. In the end I did a full reinstall

**Comment by koekeishiya** [comment]
There is no built-in update checks or anything in yabai. This is something you must have added  yourself somehow, from somewhere.

**Comment by rodrigopsasaki** [comment]
@koekeishiya do you have any idea of what this could be or how I could start looking?

**Comment by koekeishiya** [comment]
Maybe see if you have added something to your yabairc file that is not present in the sample config. I see that there is some auto-update thing mentioned in the wiki: https://github.com/koekeishiya/yabai/wiki/Tips-and-tricks#auto-updating-from-head-via-brew
