### ISSUE TITLE
Cannot add yabai to Accessibility Settings

### ISSUE THREAD

**Issue by RauschUndNot** [koekeishiya/yabai#536]
When I try to add Yabai to the accessibility whitelist via System Preferences > Security and Privacy > Privacy > Accessibility > +, the binary is greyed-out. Does anyone know of another way to do this? Screenshot below. Thank you.

![yabai](https://user-images.githubusercontent.com/53289272/82746374-f5866880-9d5c-11ea-8c12-82d3a9222426.png)

I'm running MacOS High Sierra v10.13.6
Yabai v. 3.0.2
SIP partially disabled?

```
$ csrutil status
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
    Apple Internal: disabled
    Kext Signing: enabled
    Filesystem Protections: enabled
    Debugging Restrictions: disabled
    DTrace Restrictions: enabled
    NVRAM Protections: enabled
    BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

**Comment by RauschUndNot** [comment]
Workaround...

1) I wrapped the binary using an AppleScript Application Bundle in Script Editor... see [Wrapping an executable inside a Mac OS X application.](http://brizzled.clapper.org/blog/2008/10/22/wrapping-an-executable-inside-a-mac-os-x-application/)

```
to run
	do shell script "~/bin/yabai"
end run
```

2) I ran the app. It will tell you that the program would like access to accessibility features.

3) Go to the Security and Privacy > Privacy > Accessibility and select yabai.

**Comment by koekeishiya** [comment]
For me I get prompted the first time I run it using brew services. So `brew services start yabai`, open prompt and check the automatically added entry for yabai. Then `brew services stop yabai` followed by `brew services start yabai`.

**Comment by RauschUndNot** [comment]
I started this issue before I ultimately decided to install Homebrew and install yabai that way. I originally cloned the repository and tried to compile using `make`. I received a lot of warnings about text-based stub files.

But no longer an issue. I gave in and installed Homebrew. Thank you.
