### ISSUE TITLE
Screen saver doesn't appear and displays black screen

### ISSUE THREAD

**Issue by tom-auger** [koekeishiya/yabai#537]
On Catalina 10.15.4. 
When the screen saver starts it's visible for a fraction of a second before stopping and showing a black screen.
After stopping yabai the screen saver works normally again.

**Comment by koekeishiya** [comment]
So this is caused by enabling `window_topmost on`, because yabai detects the screen save window and changes its window level.

**Comment by tom-auger** [comment]
Thanks! Setting `window_topmost off` fixed the screensaver.

I also encountered a similar issue where the login screen didn't appear after waking from sleep. This also seems to be working again with the same fix.

**Comment by koekeishiya** [comment]
Fixed on master.
