### ISSUE TITLE
does yabai still do border colours?

### ISSUE THREAD

**Issue by maishams** [koekeishiya/yabai#539]
hi!

i just reinstalled yabai and my colour configurations don't seem to work, nor is a way to handle them described in the documents as far as i can tell. has this feature been removed? if so, at what version so i can use that version.

thank you in advance and sorry if this was already stated somewhere

**Comment by maishams** [comment]
just saw that they were nuked

**Comment by maishams** [comment]
just saw they were nuked

**Comment by koekeishiya** [comment]
Go https://github.com/koekeishiya/limelight for a port of the border system that used to be in yabai.
