### ISSUE TITLE
Add ability to move between spaces while in Mission Control with "fast focus desktop" command.

### ISSUE THREAD

**Issue by SxC97** [koekeishiya/yabai#542]
I have `ctrl + left|right` set to the `fast focus desktop` command, unfortunately this doesn't work while in Mission Control.

Is it possible to add this feature? Perhaps just allow `fast focus desktop` to function as regular `move to left|right space` command while in Mission Control?

**Comment by koekeishiya** [comment]
Unlikely to happen, but if/when I get to fixing #181 this could be solved with a fallback definition in your skhd config or w/e hotkey mechansim you use.

**Comment by SxC97** [comment]
Would it be possible to use `mission_control_enter` and `mission_control_exit` to temporarily enable an skhd mode in which `ctrl + left|right` are remapped?

**Comment by koekeishiya** [comment]
So apparently I'm just stupid. The particular case you are looking for has already been solved. If you try to focus a space using `space --focus` while inside mission-control, the command will fail with a non-zero exit code. You can set the space switching shortcuts in System Preferences > Keyboard > Mission Control > left/right to some combination you don't use; eg: `cmd+alt+left|right`

Then in your skhd config:
```
ctrl - left : yabai -m space --focus prev || skhd -k "cmd + alt - left"
ctrl - right : yabai -m space --focus next || skhd -k "cmd + alt - right"
```

**Comment by SxC97** [comment]
This worked perfectly, thank you!
