### ISSUE TITLE
System Preferences ignoring rules when opened from another app

### ISSUE THREAD

**Issue by ThinkChaos** [koekeishiya/yabai#547]
When an app triggers system preferences, say by asking for a permission, yabai doesn't apply its rules to System Preferences.

If you think this is fixable and you're willing to give me some pointers I'd happily invest some time into fixing this as a thanks for your awesome work.
I didn't see an issue for this so I apologies if there's one I missed.

**Comment by koekeishiya** [comment]
Are you talking about e.g this kind of prompt?
<img width="465" alt="Screenshot 2020-05-30 at 14 23 13" src="https://user-images.githubusercontent.com/6175959/83328140-2694fa80-a281-11ea-9c20-eb886ab01a33.png">

If so here is the information of said window:
```
yabai -m query --windows --space                                                               14:22
[{
        "id":69625,
        "pid":7406,
        "app":"universalAccessAuthWarn",
        "title":"Accessibility Access",
        "frame":{
                "x":489.0000,
                "y":183.0000,
                "w":461.0000,
                "h":171.0000
        },
        "level":3,
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "movable":1,
        "resizable":0,
        "display":1,
        "space":1,
        "visible":1,
        "focused":0,
        "split":"none",
        "floating":1,
        "sticky":0,
        "minimized":0,
        "topmost":1,
        "shadow":0,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
}]
```

**Comment by ThinkChaos** [comment]
Yes I meant that kind of prompt. But I meant the actual System Preferences app that opens when you click "Open System Preferences" on that prompt.

Double checking to answer you I noticed that my rule to float System Preferences was wrong but usually worked because I have a rule that matches `title=Preferences`, which matches Sys. Prefs. on its "homepage". 🤦 
Sorry about that!
