### ISSUE TITLE
Unable to focus space or display with SIP enabled

### ISSUE THREAD

**Issue by windowsrefund** [koekeishiya/yabai#548]
Running 10.15 (Catalina) and I can't disable SIP as I don't have the password and never will. Please forgive me and trust I hate this more than you :)

However, I'm still hoping I should be able to benefit from this tiler regardless. I can focus windows in all directions but am seeing something odd when I attempt to change focus between my 2 displays

From a shell on display 1, I can run ``yabai -m display --focus next`` and focus is changed to display 2. Nice!

However, the following skdrc mappings produce no similar result:

```
alt - 1 : yabai -m display --focus prev
alt - 2 : yabai -m display --focus next

```
I am also unable to change focus between spaces (I have 2 which I'll show below) either from running yaibai directly in a shell or via skhd.

I did read about the SIP-related limitations but the FAQ says "focus/create/destroy space without animation". What exactly is meant by "without animation"? I just want to change focus and am not even sure what animation I would or would not expect to be involved. Should I be able to change focus of spaces with SIP enabled?

Here's the output of the query which shows I have 2 displays and 2 spaces:

```
yabai -m query --spaces
[{
	"id":1,
	"label":"",
	"index":1,
	"display":1,
	"windows":[3398, 3084],
	"type":"bsp",
	"visible":1,
	"focused":1,
	"native-fullscreen":0,
	"first-window":3398,
	"last-window":3084
},{
	"id":6,
	"label":"",
	"index":2,
	"display":2,
	"windows":[3341],
	"type":"bsp",
	"visible":1,
	"focused":0,
	"native-fullscreen":0,
	"first-window":3341,
	"last-window":3341
}]
yabai -m query --displays
[{
	"id":418843528,
	"uuid":"0009F357-004A-6C76-98A7-AD39161D08FD",
	"index":1,
	"spaces":[1],
	"frame":{
		"x":0.0000,
		"y":0.0000,
		"w":1920.0000,
		"h":1080.0000
	}
},{
	"id":418843527,
	"uuid":"2F87FBC0-5196-2031-56EF-B5FF21C11881",
	"index":2,
	"spaces":[2],
	"frame":{
		"x":1920.0000,
		"y":0.0000,
		"w":1920.0000,
		"h":1080.0000
	}
}]
```

Thanks for any feedback

**Comment by koekeishiya** [comment]
Focusing spaces require SIP to be disabled. If you cannot do that the only way is to use the built-int shortcuts that can be set in System Preferences -> Keyboard -> Shortcuts -> Mission Control.

Focusing display should work just fine (and does so for me).
Try to open to terminal windows; one for each display.

On the first display type: `yabai -m display --focus next`
On the second display, type: `yabai -m display --focus prev`

Assuming that is the problem; you issue is related to your skhd setup, maybe the bind is not invoked correctly for whatever reason.

**Comment by windowsrefund** [comment]
OK, thank you so much. I'm new to (having to use) OSX and didn't even know about Mission Control. I'll explore...

**Comment by windowsrefund** [comment]
Thanks again for the clarification. I'm very close to having a usable setup now and am only struggling with creating a clear visual way to know which window is active on a given monitor. 

It seems as if there is no way to manage borders? I've seen references to active_window_border_color and normal_window_border_color but am assuming support has been dropped. Is there another approach that's possible with SIP enabled?

**Comment by koekeishiya** [comment]
See #487 for discussion regarding active window indicator.

**Comment by Nebuchadrezzar** [comment]
Any chance the documentation can be updated with repeats to this topic?  Just as the OP, I too read the FAQ line "focus/create/destroy space without animation" to mean yabai can focus/create/destroy a space WITH animation if SIP is turned on.  Removing the clause "with animation" would clarity this point.

**Comment by koekeishiya** [comment]
The documentatio is already updated: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#space
