### ISSUE TITLE
App whitelist for rules?

### ISSUE THREAD

**Issue by ebai101** [koekeishiya/yabai#552]
I'm trying to create a whitelist of apps to be managed by yabai. On the wiki there are examples for creating rules specific to apps that match a regex, but is there a way to invert the match so that the rule applies to everything _except_ the matched app?

I tried at first to use a negative lookahead in a rule, something like this:
```(shell)
yabai -m config layout bsp
yabai -m rule --add app="^(?!(Google Chrome|iTerm2))(.*)$" manage=off
```
POSIX ERE doesn't support lookahead operators, so that didn't work. Why is yabai using this engine specifically? Is it faster than something like PCRE?

Maybe I'm missing something obvious - I couldn't find any previous posts on this topic, so I figured I'd ask.

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/yabai/issues/173 <https://github.com/koekeishiya/yabai/issues/173>

The reason for not using a separate library is that I simply don’t think it is worth to depend on an external dependency for something that is used as rarely as this. As you mentioned the main case that POSIX ERE does not support is the use case where you want to do a whitelist, which is supported by other means.

**Comment by ebai101** [comment]
Got it, thank you. I figured there was a native way to do this.

I think the [docs](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#66-rule) could be improved w.r.t this feature, the syntax was a little unclear. Possibly something like:

```
app[!]=<REGEX>
Name of application. If ! is present, rule applies to applications that do not match the regex.

title[!]=<REGEX>
Title of window.  If ! is present, rule applies to window titles that do not match the regex.
```

**Comment by koekeishiya** [comment]
Added note in the docs.
