### ISSUE TITLE
Crashes on macOS 10.15.5

### ISSUE THREAD

**Issue by autrilla** [koekeishiya/yabai#553]
Hi! First of all thanks for making yabai :).

I upgraded to 10.15.5 yesterday, and I've been experiencing some crashes where my laptop's screen goes white for about half a second and I get taken back to the login screen, with TouchID disabled and a full password entry required. This only happens when yabai is enabled.

The simplest way I've found to reproduce is to start yabai and then open System Preferences. It might be because I have

```
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
```

I'll test without that in a second, but submitting this issue first in case it crashes again and I lose this draft :).

Edit: it does happen without that line in my config as well.

My system:
yabai-v3.0.2 (from homebrew), with --install-sa.
macos 10.15.5
SIP disabled

Is there any further information I can provide to help debug this?

**Comment by autrilla** [comment]
Video of this in action: https://photos.app.goo.gl/r7eNmZC6RfAfSfhdA

Note that this is not the only way to get it to crash in this fashion. I also see crashes when switching workspaces or moving windows around in workspaces, but it's harder to reproduce. When opening system preferences it happens reliably.

**Comment by koekeishiya** [comment]
Probably https://github.com/koekeishiya/yabai/issues/277

**Comment by autrilla** [comment]
That seems very likely, thanks!
