### ISSUE TITLE
Focusing spaces with animation with SIP disabled

### ISSUE THREAD

**Issue by therladbsgh** [koekeishiya/yabai#556]
Issue #548 shows that disabling SIP is required not only for "focusing spaces with no animation", but also just the "focusing spaces" functionality itself. Upon testing it I can confirm this to be true (enabling SIP disables focusing spaces, and disabling SIP makes focusing spaces with no animation.

I would like to focus spaces _with_ animations, but currently in the Wiki page for Configuration I could not find any animation settings for spaces. If I am mistaken, could you let me know the steps necessary to enable animations for space switching? Or am I misunderstanding and there is no such functionality?

**Comment by koekeishiya** [comment]
External applications cannot do this even with the animation, because there is no API for this. Changing a space requires the Dock application to update its internal state, which we can only do through code injection when SIP is disabled.

The best you can do with SIP disabled is what I mentioned in #548 as you reference:
> If you cannot do that the only way is to use the built-in shortcuts that can be set in System Preferences -> Keyboard -> Shortcuts -> Mission Control.

**Comment by windowsrefund** [comment]
With SIP enabled, I'm up and running without using spaces at all. Granted, I know I'm not able to fully benefit from this awesome software but I'm able to be productive through switching displays and making use of limelight. Very nice.

**Comment by therladbsgh** [comment]
Sorry, for clarification: I do have SIP disabled at the moment, which allows switching spaces. I was wondering if it was possible to focus spaces with animation with SIP disabled.

**Comment by koekeishiya** [comment]
So the answer is no. Space switching in yabai does not have an animation and there is not going to be one, as it is supposed to be fast. If you want animation you can just use the default mission control shortcuts I mentioned above.

**Comment by therladbsgh** [comment]
Ah, got it. Using the default mission control shortcuts is a non-option for me since I need to be able to switch to full-screen applications. Guess I'll get used to instant space switching!

**Comment by therladbsgh** [comment]
#205 demonstrates a way to switch between spaces with animation (and SIP enabled). As a caveat, it is a little slower than native switching (since it focuses the window first).
