### ISSUE TITLE
Potentially high CPU use from Yabai/WindowServer from latest HEAD

### ISSUE THREAD

**Issue by jonathanwilner** [koekeishiya/yabai#557]
Hi,

I'm wondering if there's anything I can do to investigate or improve the CPU load from WindowServer that might be coming from Yabai recently. I'm running the latest from HEAD on 10.15.5. It's a 15" mid-2018 MacBook Pro w/32 GB RAM.

My .yabairc is as follows:

```

#!/usr/bin/env sh

# auto update from HEAD
#YABAI_CERT=yabai-cert sh -c "umask 0022 ; $(curl -fsSL "https://git.io/update-yabai")" &

# global settings
yabai -m config debug_output                 offn
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.05
yabai -m config window_opacity_duration      0.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# window rules
yabai -m rule --add app=Emacs$ manage=on
yabai -m rule --add app="^Messages$"    manage=off sticky=on grid=4:4:1:1:2:2
yabai -m rule --add app="^FaceTime$"             manage=off

# signals
yabai -m signal --add event=window_destroyed \
    action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated \
    action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo `date -n "+%Y-%m-%d %H:%M:%S.%s"`  "[YABAI] Configuration loaded..." ```

**Comment by jonathanwilner** [comment]
Forgot the figure - WindowServer is about 30 %.
![Screen Shot 2020-06-03 at 10 55 32 AM](https://user-images.githubusercontent.com/4776967/83671053-ed160500-a588-11ea-8fb5-3dac10e3b495.png)
![Screen Shot 2020-06-03 at 10 55 24 AM](https://user-images.githubusercontent.com/4776967/83671057-eedfc880-a588-11ea-93cb-d592bcb6e270.png)

**Comment by koekeishiya** [comment]
Are you certain that comes from yabai running? The WindowServer spikes in cpu usage quite a lot for me, even when yabai is not running, depending on the other applications that I am running.

**Comment by jonathanwilner** [comment]
That's a totally fair question. I see Skylight in the Spindump & window switching/tiling has become much more slow than in previous builds. Would it be helpful to post any other process information to help with a diagnosis one way or the other?

**Comment by koekeishiya** [comment]
Well one quick test I'd do is to simply have yabai running, open acitivty monitor or some other monitoring tool, and just watch the cpu usage while doing nothing. When you are not actively opening/moving windows, moving the cursor etc, yabai is doing nothing and all threads are sleeping. So in this state, if the WindowServer still has a high cpu usage, that would be caused by something other than yabai.

**Comment by jonathanwilner** [comment]
Hi - I disabled Yabai and had the same CPU usage from WindowServer. It's not Yabai. :-(

**Comment by yigitkonur** [comment]
This one is most probably related with Übersicht.
