### ISSUE TITLE
How to create an empty space?

### ISSUE THREAD

**Issue by edwardreed81** [koekeishiya/yabai#558]
What would be the best way to create and empty space and switch to it? Doing `yabai -c space --create` seems to move all the windows in the active space to the newly created one which seems counter intuitive to me.

Ideally I'd like my shortcut for switching spaces (alt - #) to create a space if it doesn't exist and switch to it without moving any windows.

**Comment by koekeishiya** [comment]
`yabai -m space --create` does create a new empty space.

**Comment by edwardreed81** [comment]
Seems you're right - I don't know what I was doing before. I'm just learning.

Is there a way to immediately switch to that new space? Can I somehow figure out the index of the created space and do something like

`yabai -m space --create || yabai -m space --focus #`

**Comment by koekeishiya** [comment]
You can do it like this (sample bind using skhd):
```
# create desktop and follow focus - uses jq for parsing json (brew install jq)
cmd + alt - n : yabai -m space --create && \
                index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')" && \
                yabai -m space --focus "${index}"
```

In a single display setup you can also just do: `yabai -m space --create && yabai -m space --focus last`

**Comment by edwardreed81** [comment]
Great, thank you!

**Comment by MikeDrewitt** [comment]
Unfortunately `yabai -m space --create && yabai -m space --focus last` doesn't seem to work with a multi-monitor setup. `last` seems to always refer to the last space on the last monitor.

**Comment by koekeishiya** [comment]
The code block in my comment above does exactly that.

Sent from my iPhone

On 28 Dec 2020, at 21:21, Michael Drewitt <notifications@github.com> wrote:

﻿

Unfortunately yabai -m space --create && yabai -m space --focus last doesn't seem to work with a multi-monitor setup. last seems to always refer to the last space on the last monitor.

**Comment by MikeDrewitt** [comment]
I'm sorry, my brain must have stopped working when I wrote that out. I think in my head I was thinking without the extra dependency, but if there's not a way around it it's not a huge deal.

**Comment by koekeishiya** [comment]
There is no other way as of right now. I'll think about what it might look like to have such operations return useful information in the future, rather than only error messages/setting the exit code.

Sent from my iPhone

On 29 Dec 2020, at 14:21, Michael Drewitt <notifications@github.com> wrote:

﻿

I'm sorry, my brain must have stopped working when I wrote that out. I think in my head I was thinking without the extra dependency, but if there's not a way around it it's not a huge deal.

**Comment by timofurrer** [comment]
In recent versions of yabai it seems that the `jq` command is wrong. Instead it should be:

```sh
jq 'map(select(."is-native-fullscreen" == false))[-1].index'
```

which results in the following binding:

```diff
shift + alt - n : yabai -m space --create && \
                   index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
                   yabai -m window --space "${index}" && \
                   yabai -m space --focus "${index}"
```

**Comment by qns7** [comment]
> In recent versions of yabai it seems that the `jq` command is wrong. Instead it should be:
> 
> ```shell
> jq 'map(select(."is-native-fullscreen" == false))[-1].index'
> ```
> 
> which results in the following binding:
> 
> ```diff
> shift + alt - n : yabai -m space --create && \
>                    index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
>                    yabai -m window --space "${index}" && \
>                    yabai -m space --focus "${index}"
> ```

This doesn't work on my machine, it switches to the new space, but then switches back almost immediately. Perhaps some one has an idea why this happens?

Best regards Q
