### ISSUE TITLE
some simple questions of a newbie

### ISSUE THREAD

**Issue by emninger** [koekeishiya/yabai#559]
I'm totally new to MacOS (used to use Arch and i3 or bspwm) so it's very likely, i'm missing something very simple. Sorry for that in advance ;)

1) How do i start the yabai panel / status bar?

I have this statement in my config file, but it does not come up:

```
# bar settings
yabai -m config status_bar                   on

yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"

yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"

yabai -m config status_bar_background_color  0xff202020

yabai -m config status_bar_foreground_color  0xffa8a8a8

yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X

yabai -m config status_bar_power_icon_strip  Ôàû ÔÉß

yabai -m config status_bar_space_icon        ÔÑâ

yabai -m config status_bar_clock_icon        time
```

2) Does yabai create defaultwise a given number of workspaces? Or should that be configured in the config file? And if so, how?

I have this statement in the config:

`yabai -m space --create`

But nothing happens. Is this may be hurted by the MacOS MissionControl?

(I'm running yabai on a MacBook Air with Catalina)

Thanks in advance for your patience!

**Comment by rross101** [comment]
Hey - equally new here and just installing and configuring it - but on your first issue, I see that the status bar has been removed (see GitHub issue [here](https://github.com/koekeishiya/yabai/issues/486) ) but there are other options - I'm trying [this](https://github.com/somdoron/spacebar)

**Comment by dominiklohmann** [comment]
> I have this statement in the config:
> 
> `yabai -m space --create`

This requires the scripting addition to be installed. See https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection#what-is-system-integrity-protection-and-why-does-it-need-to-be-disabled for more information.

**Comment by atidyshirt** [comment]
Another super simple question :), how do we actually use signalling for Übersicht? Here is my attempt, however it doesn't seem to update at all.
```
yabai -m signal --add event=space_changed \
  action="osascript` -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=display_changed \
  action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=space_changed \
  action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
yabai -m signal --add event=window_focused \
  action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
yabai -m signal --add event=window_destroyed \
  action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
yabai -m signal --add event=application_front_switched \
  action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
```

**Comment by yanzhang0219** [comment]
Try to remove the backtick sign in the first action...

**Comment by atidyshirt** [comment]
Hmm I have tried removing it, but I don't know how to check errors etc.

**Comment by atidyshirt** [comment]
The backtick was actually a typo I believe, however it has not solved the problem.

**Comment by yanzhang0219** [comment]
These signal commands look correct. I think you should check simple-bar-spaces-jsx and simple-bar-process-jsx. Also check whether the system integrity protection is disabled. 
BTW, to check whether yabai signal works well, you could use a simple signal like `yabai -m signal --add event=space_changed action="say abc"`. Then turn up the volume. When you change the space, if you could hear "abc" from the speaker of your laptop, it means yabai's signal feature works well in your system. Also it means your action parts are wrong. To check the action part, try to run the action part directly in your terminal to see whether that jsx code works well or not.

**Comment by atidyshirt** [comment]
When I get home, will check the signals, SIP should definitely be disabled as I can create and destroy windows. Thanks for help, will look into it.

**Comment by atidyshirt** [comment]
Signals appear to be working fine, I believe it is either a problem in syntax of how I am calling the refresh, or it is somehow not communicating with Übersicht.

**Comment by atidyshirt** [comment]
Update: this syntax appears to work, as noted on the Übersicht github page.
```
yabai -m signal --add event=space_changed \
  action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
```
