### ISSUE TITLE
“brew services …” doesn’t start yabai and doesn’t correctly reflect service status, while direct invocation works

### ISSUE THREAD

**Issue by strogonoff** [koekeishiya/yabai#560]
`brew services start|stop` commands behave as if the service can be started, stopped and is running successfully, but `yabai -m` commands complain about failure to connect to socket.

<s>However, socket file does exist under `/tmp`.</s>

Socket file does not get created while the service is shown as “started” by `brew services`.

While service is supposedly running, there appears to be no yabai process.

```console
me@machine:~$ ps aux | fgrep yabai
me            11778   0.0  0.0  4399356    796 s005  S+   11:01PM   0:00.00 fgrep yabai
```

When running `yabai` directly, `yabai -m` commands succeed, and socket file gets created.

Ideally, at least services could somehow accurately reflect if yabai fails to start…

## Background

I install brew packages while su’ing as another user with admin privileges, but without root/sudo. I run binaries as my regular user. Never had a problem with that before.

I tried starting yabai service from (1) my regular user, from (2) that admin user, and from (3) admin user + sudo. (2) fails loudly, (3) declares that it takes root ownership over some files but otherwise succeeds (since it screwed up permissions, I assume, I wiped and reinstalled yabai after that just in case). (1) succeeds as described in the beginning of the issue. In all cases, `yabai -m` failed.

## SIP

I did not disable SIP or install the scripting addon, so there’s that. I want to get started with yabai in restricted functionality.

**Comment by strogonoff** [comment]
`brew services run` uncovers something:

```
/usr/local/opt/yabai/homebrew.mxcl.yabai.plist: Path had bad ownership/permissions
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /usr/local/opt/yabai/homebrew.mxcl.yabai.plist` exited with 122.
```

**Comment by strogonoff** [comment]
Chowning the above .plist to my user removes the error message in `brew services run yabai`, but the service does not get started with same behavior as `brew services start yabai`.

**Comment by strogonoff** [comment]
Side note: this does not happen with skhd, which works perfectly with `brew services`.

**Comment by koekeishiya** [comment]
I have no idea how brew services works. I think you might have better luck if you open an issue or request help from the brew community. Personally, I use launchd directly.

**Comment by dominiklohmann** [comment]
`brew services` just uses `launchctl` under the hood. It's a very thin wrapper. Almost all of its code is in here: https://github.com/Homebrew/homebrew-services/blob/master/lib/services_cli.rb

This issue is most likely a user error.

**Comment by alextes** [comment]
I had this issue. "failure to connect to socket"
`brew run yabai` solved it for me.

**Comment by mathias-nyman** [comment]
I had the same issue, and it stems from installing brew packages from a separate 'admin' user, while starting the yabai brew service as a 'regular' user.

The yabai installation creates this folder for logs, but the 'regular' user does not have privileges to write files to it:
```
$ ls -la /usr/local/var/log/yabai 
total 8
drwxr-xr-x  4 admin   admin            128 Sep  5 22:15 ./
```

The plist file that comes with yabai specifies two log files in this directory, to which the yabai service will try to write at startup but will fail to do so causing yabai to terminate:
```
  <key>StandardOutPath</key>
  <string>/usr/local/var/log/yabai/yabai.out.log</string>
  <key>StandardErrorPath</key>
  <string>/usr/local/var/log/yabai/yabai.err.log</string>
```

A quick fix for this issue is to pre-create the log files and change their ownership to the 'regular' user:
```
touch /usr/local/var/log/yabai/yabai.out.log
touch /usr/local/var/log/yabai/yabai.err.log
chown regular:regular /usr/local/var/log/yabai/yabai.*.log
```

@koekeishiya would you consider not terminating yabai even if stdout and stderr are not writeable?

**Comment by koekeishiya** [comment]
> @koekeishiya would you consider not terminating yabai even if stdout and stderr are not writeable?

The termination is controlled by launchd as far as I know; I don't know how I would even solve that.

**Comment by strogonoff** [comment]
> I had the same issue, and it stems from installing brew packages from a separate 'admin' user, while starting the yabai brew service as a 'regular' user.

Thanks for corroborating, looks like you use the same setup as what I described when filing this issue.

**Comment by strogonoff** [comment]
Not sure this issue can be considered closed but I am neutral on this (no longer looking to use yabai due to SIP), project looks super cool though, thanks and keep up the good work!

**Comment by boris-sbizzera** [comment]
impossible to run brew services run yabai or start yabai. no prompt for permission appears. On Big Sur 11.2.3. Is ther a solution

**Comment by returnzer0** [comment]
I faced this exact issue with Catalina. Tried the workaround above but it didn't help. So, I decided to create a group named `brew` and then give it permissions to the folders used by brew services.

1. Go to Users & Groups in settings and create a new Group. Add users to this group that are running yabai. I named my group `brew` for obvious reasons.
2. Run the following commands.
```
$ sudo chgrp -R brew $(brew --prefix)/*
$ ls -la $(brew --prefix)
$ sudo chmod -R g+w $(brew --prefix)/*
$ brew doctor
```

This should allow this new group permissions to run brew without any issues, thereby solving the permissions issue that causes yabai not to activate upon startup.

**Comment by ltOgt** [comment]
For me the issue was caused by `/opt/homebrew` having the wrong ownership
`sudo chown -R $(whoami) /opt/homebrew` fixed it

**Comment by ADGEfficiency** [comment]
I had a similar issue to this - `yabai` would start but wasn't finding my `yabairc`. 

I have a custom `XDG_CONFIG_HOME` - I fixed this using [this solution](https://stackoverflow.com/questions/71517976/brew-services-start-tomcat-is-ignoring-zshrc-environmental-variables):

```
#  .zshrc
launchctl setenv XDG_CONFIG_HOME $XDG_CONFIG_HOME
```

**Comment by kingluddite** [comment]
I use

 yabai --start-service
 yabai --restart-service
 
 skhd --start-service
 skhd --restart-service 
 
 And is works
