### ISSUE TITLE
Cardinal movement arguments for swap/warp consider unmanaged windows

### ISSUE THREAD

**Issue by eramdam** [koekeishiya/yabai#561]
Ever since 3.0.0 I've noticed a weird behaviour. It seems as if unmanaged windows are being considered for swap/wrap actions, thus blocking said action.

I've recorded the behavior in the video below https://www.dropbox.com/s/ztzeufpc7ko5urv/yabai-wrap.mp4?dl=0

After running a `git bisect` on the repo, I've ended up on a763f983c2322f31488a63de97913f41d5faa270 which implemented the euclidian distance logic to find a target window, so I don't know if the issue is really that unmanaged windows are being wrongfully considered or if the distance logic needs to be tweaked 😅 

My gut feeling says that unmanaged windows should be ignored by warp/swap actions because those actions aren't really useful outside of the bsp layout but I may be missing some other perspective.

**Comment by eramdam** [comment]
I've noticed that this might be related to https://github.com/koekeishiya/yabai/issues/531#issuecomment-632324779

I also noticed that the `next`, `prev`, `last` and `first` arguments aren't affected by this since they consider only the managed windows. So I guess the fix would be to harmonize the cardinal direction arguments for warp/swap so they would only consider managed windows?

**Comment by koekeishiya** [comment]
Swap/Warp does already only look at managed windows: https://github.com/koekeishiya/yabai/blob/master/src/window_manager.c#L633 <https://github.com/koekeishiya/yabai/blob/master/src/window_manager.c#L633>

Probably some issue with the distance/direction calculation.

**Comment by eramdam** [comment]
Huh, I guess I assumed that because I get an error saying 
`the selected window is not managed.`

When running the command directly. So I guess it tries to find a target window and then bails out if it's unmanaged rather than continue trying until it finds a managed window?

**Comment by koekeishiya** [comment]
You’re probably right. I probably messed up a long time ago when I changed how i wrote the parser and it probably calls the other function all the time, even for warp/swap operations.

**Comment by koekeishiya** [comment]
This is a bug indeed, closing this in favour of https://github.com/koekeishiya/yabai/issues/562
