### ISSUE TITLE
Rework cardinal directions for window selector to ignore floating windows

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#562]
Due to a lot of weird quirks when trying to support floating windows in the cardinal directions for the window selector, I've decided that it is simply better to be able to provide a good experience with the navigation for managed windows. I barely, if ever, use cardinal directions to focus floating windows and trying to support that creates a lot of issues. 

It is obviously not a problem that is impossible to solve, but I don't think the time and effort required is worth it, considering how little this specific edge case is being used. I also think there are superior methods to focusing floating windows that could be utilized instead.

See some of the referenced issues for some of the problems that I'm talking about.

**Comment by koekeishiya** [comment]
Solved all issues at once by simply ignoring floating windows, and using the region allocated for the node of the managed window itself rather than the actual window size, to get around issues with window size constraints, window zoom integration, etc.

**Comment by harsilspatel** [comment]
I was wondering if this can be re-enabled for floating windows, perhaps as an experimental feature that would only turn on if say a flag is set to `true`? The reason being, I only use yabai for focusing on floating windows, i.e. my workflow consists of a single line yabai config `yabai -m config layout float` and the following skhd config:
```
ctrl + alt - h : yabai -m window --focus west
ctrl + alt - j : yabai -m window --focus south
ctrl + alt - k : yabai -m window --focus north
ctrl + alt - l : yabai -m window --focus east
ctrl + alt - m : yabai -m window --focus mouse
ctrl + alt - r : yabai -m window --focus recent
```

**Comment by wwilsman** [comment]
Ditto for re-enabling this, even experimentally, for floating windows. I also only use yabai in floating window mode and have since lost the ability to focus any of my windows. :(

**Comment by harsilspatel** [comment]
Currently I'm using the last supported version for `float` layout which is v3.1.0 - not an ideal solution since I won't be able to use cool features from the newer releases but getting by for now
