### ISSUE TITLE
FFM refocuses windows constantly, closing popups

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#563]
To reproduce: Open Safari, press <kbd>cmd</kbd> + <kbd>L</kbd> to open address bar. Now move the cursor, which closes the address bar because the main window gets re-focused. This should not be happening.

Until very recently, this used to work just fine, so I presume it has to do with the recent FFM changes, which made the feature a bit overeager.

**Comment by koekeishiya** [comment]
I can’t reproduce this; works just fine for me. Address bar and the pane remain open.

**Comment by dominiklohmann** [comment]
Restarting Safari fixed it for me; restarting yabai, however, did not.

I'm closing this issue until I can reproduce this again, might've just been a hiccup on Safari's end.
