### ISSUE TITLE
Config that allows to blacklist some applications

### ISSUE THREAD

**Issue by AlaaSaadAbdo** [koekeishiya/yabai#568]
Hi,

First of all, thank you very much for the amazing tool!

I wanted to ask if there's any way to blacklist some applications that don't have windows. 
E.g. lightshot for screenshots?

I'm also aware of the `manage=off` setting but that has not really worked for this situation.

```
yabai -m rule --add app="^Steam$" manage=off
```

Cheers!

**Comment by koekeishiya** [comment]
There is currently no way to do this, no. The process observation happen before the config message system kicks in.

**Comment by AlaaSaadAbdo** [comment]
Thanks for the info :)

**Comment by koekeishiya** [comment]
If this is related to stuff that had similar issues to Übersicht, I just pushed a more general fix that should work for other applications that do similar tricks to achieve their functionality.

**Comment by AlaaSaadAbdo** [comment]
Indeed it was. Thanks. I will let you know once it's released
