### ISSUE TITLE
Minimized windows are falsely reported as visible

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#569]
The `visible` attribute of a window query used to be `0` for minimized windows. This changed recently.

I consider this a bug, since the `visible` attribute used to be a good way to implement custom focus commands. While it can be worked around using a conjunction with the `minimized` attribute, I suppose the change was of accidental nature.

**Comment by koekeishiya** [comment]
I don’t remember making changes here. Do you happen to know when this broke?

**Comment by dominiklohmann** [comment]
Sometime over the last week, I haven't been able to stay up to date with master lately.

I can run a git-bisect if you want me to.

**Comment by koekeishiya** [comment]
That would be great, if you don’t mind.

**Comment by dominiklohmann** [comment]
Here's the culprit:

> [e6781b53d5e908b7668475a08f48fa858e399883] #379 ability to (de)minimize windows, and report current state through window queries

```
❯ git bisect log
git bisect start
# bad: [f6c683edf36b29f0adef40a4665f3ceda5bc4fb6] #535 don't modify properties of AXUnknown and AXPopover windows
git bisect bad f6c683edf36b29f0adef40a4665f3ceda5bc4fb6
# bad: [f6c683edf36b29f0adef40a4665f3ceda5bc4fb6] #535 don't modify properties of AXUnknown and AXPopover windows
git bisect bad f6c683edf36b29f0adef40a4665f3ceda5bc4fb6
# bad: [f6c683edf36b29f0adef40a4665f3ceda5bc4fb6] #535 don't modify properties of AXUnknown and AXPopover windows
git bisect bad f6c683edf36b29f0adef40a4665f3ceda5bc4fb6
# good: [0926a034276e2a15fc210919f41f3663cd52d687] Merge branch 'master' of https://github.com/koekeishiya/yabai
git bisect good 0926a034276e2a15fc210919f41f3663cd52d687
# good: [5633746ec0d017c2aa7e7d5dd5d04a104a377fdd] simple stats for eventloop
git bisect good 5633746ec0d017c2aa7e7d5dd5d04a104a377fdd
# bad: [adf6aa8714cacf30463869e1ec7413cdf9638038] #528 reset ffm cache upon space change
git bisect bad adf6aa8714cacf30463869e1ec7413cdf9638038
# good: [666fa40c4f05af87c0bdba523c31597b9b4cc641] v2.4.2
git bisect good 666fa40c4f05af87c0bdba523c31597b9b4cc641
# bad: [19b691ee405f1cfe336ae7fd3c590a3bcf2abb47] #492 cache insertion point if we do a manual override
git bisect bad 19b691ee405f1cfe336ae7fd3c590a3bcf2abb47
# bad: [9d2a0e3bb78aa53fb2d6b9e5dc1288a45931e226] #379 update documentation for window deminimize
git bisect bad 9d2a0e3bb78aa53fb2d6b9e5dc1288a45931e226
# good: [ee209d057aa5648045039f042540ef4aad5fa5c6] v2.4.3
git bisect good ee209d057aa5648045039f042540ef4aad5fa5c6
# good: [6d8f13f3a6b42c7694493d2d4053dc2d14db70ec] wid, sid, and psn are already unique; remove transformation
git bisect good 6d8f13f3a6b42c7694493d2d4053dc2d14db70ec
```

**Comment by koekeishiya** [comment]
Ok so assuming I'm not stupid, the real issue is actually that minimized windows wasn't reported in the window queries at all prior to that commit.

**Comment by dominiklohmann** [comment]
Yeah from looking at the code change, that looks to be about it. I'm not using minimized windows all too much, which may be why this has gone unnoticed so far.

Anyways, those windows are certainly not visible, so I think I'd still consider this a bug.
