### ISSUE TITLE
Improve visual feedback of insertion selection

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#572]
Because the visual feedback is no longer related to the actual frame of the window that occupies a node, the current feedback can often look weird or out of place, as it is simply an outline around empty space (depending on whether the window fits the size of its node or not, for various reasons).

A more pleasing visual feedback would be to actually mark the entire selected area of the node itself, rather than just outlining it.

**Comment by dominiklohmann** [comment]
This looks really odd when using it with window borders disabled. Can you remove the border from the insertion area in that case?

**Comment by koekeishiya** [comment]
I still do think an outline gives it a nice effect due to difference in the alpha, but the width is definitely overkill.

Something like:

<img width="1440" alt="Screenshot 2020-06-13 at 12 53 08" src="https://user-images.githubusercontent.com/6175959/84566879-fa937200-ad74-11ea-814b-38d2a79728c1.png">

vs

<img width="1440" alt="Screenshot 2020-06-13 at 12 55 08" src="https://user-images.githubusercontent.com/6175959/84566911-46461b80-ad75-11ea-828b-4b3cc7ea2a1c.png">

**Comment by dominiklohmann** [comment]
That's much better, yes. Thanks!
