### ISSUE TITLE
about yabai rule

### ISSUE THREAD

**Issue by rmGFW** [koekeishiya/yabai#573]
i put this rule in my config file 
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
but it not work
the finder app is still managed by yabai . i want finder to be float

i have made SIP disabled and also restart yabai after modify the config file

**Comment by koekeishiya** [comment]
If you *only* add it to your config, you need to restart yabai for the config (and the newly added rule) to be applied. You can also just run that one command manually from a shell and it will work just fine as well. I tested the rule and it works fine. you just didn't run it in the active session.
