### ISSUE TITLE
yabai not working (block of kAXErrorCannotComplete)

### ISSUE THREAD

**Issue by technoplato** [koekeishiya/yabai#575]
These are some errors I get upon starting yabai from a fresh pull from Github. 

```
thread: 125664704 | application_observe_notification: kAXCreatedNotification failed with error kAXErrorCannotComplete
thread: 125664704 | application_observe_notification: kAXFocusedWindowChangedNotification failed with error kAXErrorCannotComplete
thread: 125664704 | application_observe_notification: kAXWindowMovedNotification failed with error kAXErrorCannotComplete
thread: 125664704 | application_observe_notification: kAXWindowResizedNotification failed with error kAXErrorCannotComplete
thread: 125664704 | application_observe_notification: kAXTitleChangedNotification failed with error kAXErrorCannotComplete
thread: 125664704 | application_observe_notification: kAXMenuOpenedNotification failed with error kAXErrorCannotComplete
```

I've tried running from `brew` as well as from the Terminal. I've got yabai working on my laptop just fine and am using the same .yabairc. 

I've also made sure SIP is disabled, yabai is added to my accessibility list, and can't think of what else to try.

Can I get you more information to help me debug this?

MacOS 10.15.4

**Comment by koekeishiya** [comment]
These are just warnings that certain applications running on your system does not support the macOS accessibility operations that yabai require to be able to interact with said application. There is nothing that yabai can due to resolve that.

**Comment by technoplato** [comment]
Thanks for the response. All is working now.

**Comment by thewisenerd** [comment]
>  certain applications ... does not support the macOS accessibility operations

should the application names be logged too?

**Comment by Rougemoot** [comment]
> These are just warnings that certain applications running on your system does not support the macOS accessibility operations that yabai require to be able to interact with said application. There is nothing that yabai can due to resolve that.

How would you make sure the application in question does everything needed to comply with yabai? I'm working with the developer of a gtk app (Elkowar's Wacky Widgets), and the fact yabai can't interact with the windows makes it unusable.

What are those accessibility operations?

**Comment by elkowar** [comment]
If you roughly know what needs to be done for yabai to be able to manage a window, as in, if you have some hints as to what to search for, that'd be immensely helpful, @koekeishiya 
Currently, I see that it doesn't work, but as an application developer, I have no idea what to look for as to how to fix it. Any hints would be appreciated :D

**Comment by koekeishiya** [comment]
@elkowar 

I don't know the specifics, but a Zathura (pdf viewer) user resolved this in that application by using the `gtk-mac-integration` library (I know nothing of this).

Some issues that might be helpful in some way:
https://github.com/zegervdv/homebrew-zathura/issues/38
https://github.com/koekeishiya/yabai/issues/408
