### ISSUE TITLE
how to controll the second monitor?

### ISSUE THREAD

**Issue by Insua** [koekeishiya/yabai#576]
The main monitor create three desktop and I can focus them,
Then I create three desktop on the second monitor But I don't kown the index of second monitor
so,I can't focus them by shortcuts
need help

**Comment by koekeishiya** [comment]
The location of the space in mission-control is the index you specify to focus a space.
You can also retrieve information using the query command:
```
~ yabai -m query --spaces                                                                        13:18
[{
        "id":6,
        "label":"",
        "index":1,
        "display":1,
        "windows":[516, 171],
        "type":"bsp",
        "visible":1,
        "focused":1,
        "native-fullscreen":0,
        "first-window":171,
        "last-window":516
},{
        "id":7,
        "label":"",
        "index":2,
        "display":1,
        "windows":[328],
        "type":"bsp",
        "visible":0,
        "focused":0,
        "native-fullscreen":0,
        "first-window":328,
        "last-window":328
},{
        ...
},{
        "id":20,
        "label":"",
        "index":11,
        "display":1,
        "windows":[505],
        "type":"float",
        "visible":0,
        "focused":0,
        "native-fullscreen":1,
        "first-window":0,
        "last-window":0
}]

# use the "index" value to focus the space
~ yabai -m space --focus 11   
```

**Comment by Insua** [comment]
thanks,can I put only index 2 and 6 to monitor 2,and other spaces to monitor 2

**Comment by koekeishiya** [comment]
The index is controlled by macOS and cannot be changed. 
You can give names to spaces by using their original index, and then refer to the name afterwards:

```
# set name s2 for space with mission-control index 2
yabai -m space 2 --label my_space

# focus space with mission-control index 2
yabai -m space --focus my_space
```

**Comment by Insua** [comment]
> The index is controlled by macOS and cannot be changed.
> You can give names to spaces by using their original index, and then refer to the name afterwards:
> 
> ```
> # set name my_space for space with mission-control index 2
> yabai -m space 2 --label my_space
> 
> # focus space with mission-control index 2
> yabai -m space --focus my_space
> ```

谢谢！
