### ISSUE TITLE
Add a combined signal for window_created / application_launched

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#581]
This has come up a few times before, and I think it's time to revisit the stance on artificial signals, i.e., signals that do not directly reflect a system event.

Currently, the `window_created` and `application_launched` signal must both be used when all window creations/restorations are of interest, and the `application_launched` signal requires a fair bit of boilerplate code to go from a process identifier to a set of window identifiers.

For a better user experience, an artificial signal could be added that is triggered on `window_created`, and additionally once per window that is restored on `application_launched`.
The signal should carry the window identifier, much like `window_created` does, such that it can be used as a simple replacement.

I suggest naming the signal `window_registered` or `window_added`, as it must fire whenever yabai registers a new window.

**Comment by koekeishiya** [comment]
I will revisit this at some point, but no ETA. I agree that there are certainly improvements that can be made to the signal system in terms of usability.
