### ISSUE TITLE
[Feature Request] Toggle border for a space

### ISSUE THREAD

**Issue by rockyzhang24** [koekeishiya/yabai#584]
The syntax could be like this: `yabai -m space --toggle border`

It has an impact on three types of windows:
1. All the existing windows in this space
2. All the newly-created windows in this space
3. All the windows sent to this space

Scenario to use this feature:
1. Assuming the border is on now. This feature could turn off the border in a space so that all windows in this space have no border. Then for some applications whose border performs weird (like some IDEs or device emulators), we could switch to this space and open such an application, or send such an application to that space. 
2. Combined with `yabai -m space --toggle float`, we could make a space perform as the native macOS, i.e., floating window and no window border. So sometimes if we want to use the native macOS, we don't need to turn off yabai globally, and instead, we just need to create a new space and toggle it with `--toggle float` and `--toggle border`. This is very convenient.

Thank you very much.

**Comment by koekeishiya** [comment]
Unlikely to be implemented due to complexity of knowing when a window enters such a space, as we are not able to have macOS tell us that a window has been moved to a different space.

**Comment by koekeishiya** [comment]
Closing as out of scope.
