### ISSUE TITLE
Toggling Opacity requires application restart

### ISSUE THREAD

**Issue by timlkelly** [koekeishiya/yabai#585]
When toggling the `window_opacity` from on to off and restarting Yabai, the opacity of the windows does not change. Windows continue to be transparent. 

Quitting and reopening a specific Application will fix this for said application, however, other applications will continue to be transparent until they been restarted.

This isn't a critical issue and I am unsure if this is in Yabai's realm or just part of how macOS behaves, but I wanted to bring this to your attention.

macOS 10.15.5
yabai 3.2.0

**Comment by dominiklohmann** [comment]
In the meantime, you can use this:

```sh
yabai -m query --windows |
  jq '.[].id' |
  xargs -I{} yabai -m window {} --opacity 1.0
```

Read as: Query information about all windows, and modify their the query result to show only the `id` field, then for every window id set the corresponding windows opacity to 1.0.
