### ISSUE TITLE
Emacs Window Strange Behaviour

### ISSUE THREAD

**Issue by nuynait** [koekeishiya/yabai#587]
Yabai version: v3.2.0

skhd version: 0.3.5

Macos version: 10.15.5

I have been using Emacs under Yabai for a while. Sometimes, it has this strange behaviour:
-----
![Captured 2020-06-21 at 09 25 42](https://user-images.githubusercontent.com/2152195/85225954-ae62b600-b3a2-11ea-8df8-970ed5845bed.gif)

Please allow me to explain what's happening. this is a 2k ultra monitor positioned vertically. On top its a terminal window. On the bottom, its the Emacs. I was using Magit in Emacs. 

1. When I press s to stage a file, (Sometimes doing other actions can trigger this as well.), the Emacs shrinks into half of its original height.
2. Then right after that, I float the emacs window and then un-float and put that window back. The emacs gets shrink again. 
3. Then I throw Emacs to another workspace, it layouts fine with no issue. And when I throw Emacs back, it first put back Emacs in its shrink size and then automatically resize back to its correct size.

----
PS: I have `yabai -m rule --add app=Emacs manage=on`  this line in my config file, otherwise, yabai won't do any actions to my Emacs.

**Comment by dominiklohmann** [comment]
> I have `yabai -m rule --add app=Emacs manage=on` this line in my config file, otherwise, yabai won't do any actions to my Emacs.

That forces yabai to tile _all_ Emacs windows with no exception, which includes transparent standard windows that Emacs creates (and mislabels, because those should not be standard windows).

Try adding a `title!='^$`to your rule to make the rule only apply to windows that have a title.

**Comment by nuynait** [comment]
@dominiklohmann Thanks for the advice. I have added the suggested title property to my rule. I have restarted `yabai` and it seem to be fine right now. The problem I have only happens occasionally, I hope that it solved this issue.
