### ISSUE TITLE
Make specific app float rule dosen't work

### ISSUE THREAD

**Issue by Insua** [koekeishiya/yabai#588]
```
# float apps
yabai -m rule --add app="Wechat.app" sticky=on layer=above manage=off
yabai -m rule --add app="Eudic.app" sticky=on layer=above manage=off
yabai -m rule --add app="NeteaseMusic.app" sticky=on layer=above manage=off
yabai -m rule --add app="IINA.app" sticky=on layer=above manage=off
yabai -m rule --add app="QQ.app" sticky=on layer=above manage=off
yabai -m rule --add app="Nutstore.app" sticky=on layer=above manage=off
```
this is my yabairc config , after resart, this about apps still not float

**Comment by yanzhang0219** [comment]
Try to remove the extension, i.e., ".app" in each command, and they will work. The application name is the name without ".app". You can check the application name from the macOS menu bar next to the apple symbol ().

**Comment by koekeishiya** [comment]
The simples way is to use the yabai query system:

```
yabai -m query --windows
```

Write a regex that matches the value of the `app` attribute.

**Comment by Insua** [comment]
thinks,my system is Chinese I should use the chines word instend of english 
yabai -m rule --add app="微信" sticky=on layer=above manage=off
works fine
