### ISSUE TITLE
Window z-order interaction with autofocus

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#59]
### Steps to reproduce issue

```sh
# required configuration
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
```

- Tile two windows
- Raise one window by clicking on it
- Move mouse over other window to focus it, but do not raise it
- Hold down <kbd>fn</kbd> and try to move the window over raised (but unfocused window) to swap their positions

This currently does not work because the focused window gets moved under the raised window. 

### Proposed fix

The mouse action `move` should raise the window that gets moved.

**Comment by koekeishiya** [comment]
No need to raise the window. Fixed on master.

**Comment by dominiklohmann** [comment]
Changed the title accordingly. Thanks for the quick fix.
