### ISSUE TITLE
Keep previous layout after exiting full screen mode

### ISSUE THREAD

**Issue by daphen** [koekeishiya/yabai#590]
I usually have chrome, on a space along with other apps and if I enter full screen mode on something like a YouTube video and then exit out of it, Yabai doesn't remember which space on my layout that the different apps where occupying, so all of a sudden my terminal takes up the "main" slot and Chrome is super tiny etc. Is there a way around this?

**Comment by koekeishiya** [comment]
It does not remember the position because macOS actually creates and destroys windows during this process. I am not interested in trying to tackle all the headache that comes with this.

**Comment by daphen** [comment]
Alright, thanks for the heads up, makes sense.
