### ISSUE TITLE
Cannot enable Safari extensions while Yabai is running

### ISSUE THREAD

**Issue by haringsrob** [koekeishiya/yabai#591]
Ok, sorry for reporting this. I might just be the only one using a combination of Yabai and Safari.

Anyway, there seems to be a bug on the Safari side that makes the enabling of the checkboxes only work when the window is in a certain state.

In my case I had to stop yabai, enable extensions and then start the yabai service again.

I also tried putting the window on a floating space, but no advance.

For me you can close this issue immediately, but let it be there for those that google!

https://developer.apple.com/forums/thread/128456

**Comment by koekeishiya** [comment]
Sounds like a weird issue. Does this always happen or only sometimes? Could you maybe try and grab the output of `yabai -m query --windows --space` to retrieve information about the Safari window that is having issues. Also do you use `window_topmost` or similar yabai settings?

**Comment by jonathanwilner** [comment]
Definitely also happened to me. Also had to figure out how to stop Yabai. Very weird bug from Apple.

**Comment by alexaldrick** [comment]
I just realised the same thing. I was working on developing a Safari extension, and suddenly Safari started complaining that it 'detected an app or service that interfered with clicking'. I thought it was just a bug on Safari's end after troubleshooting online. I'm so used to Yabai, that I completely forgot I do have something interfering with clicking. 

Can confirm this is happening still. Would be glad to help with troubleshooting if anyone can start me in the right direction.

**Comment by 24unix** [comment]
@alexaldrick I had the same issue when converting Binnen-I be gone to a Safari Webextension.
I cannot tell 100% what was the cause, but now it works, even with yabai running, so yabai doesn’t seem to be the cause of that problem.
Might be a problem with skhd, but I don’t use it.

**Comment by lightbluepoppy** [comment]
For me, I cannot click open `Customize and Control Google Chrome` and `Search Tabs` panes on Google Chrome at the top-right corner.
