### ISSUE TITLE
Xcode reloading scripting addition.

### ISSUE THREAD

**Issue by yangnom** [koekeishiya/yabai#592]
I've gotten back into using Xcode and while I'm using the program, I get a notification that the scripting payload is being reloaded and then (I think) yabai reloads because my windows reset themselves.

It _seems_ like it happens because Xcode is running some debugging whenever I stop typing, but I'm really not sure.

Has anyone else experienced anything like this or does anyone have an idea where to start to figure this out?

**Comment by dominiklohmann** [comment]
Sounds like a duplicate of #580? Are you running the latest release?

Maybe you can show the verbose output of yabai when this crash occurs.

**Comment by yangnom** [comment]
Yes, that it is exactly that problem (upon further messing about it appears to happen during popover completion).
