### ISSUE TITLE
How to make it go?

### ISSUE THREAD

**Issue by willhaslett** [koekeishiya/yabai#593]
Hi. My life is in the terminal and I did a stint with i3 awhile back and loved it, so I think that I'm following the documentation like a reasonably informed person would.

The installation went fine, SIP, accessibility, Mission Control, start brew service...

But now how do I simply make it do its thing? My windows aren't managed. How do I start working with managed windows, have yabai take over? The space commands work, but how do I make the tiling go? I've created `~/.yabairc` and `~/.skhdrc`using the example file content, restarted the brew service, restarted the computer... 

I'm sure I'm missing something very basic, but shouldn't that something slap me in the face when I read "Quick Start"?

**Comment by dominiklohmann** [comment]
Did you enable tiling in your config?

```
yabai -m config layout bsp
```

The defaults are designed to be as close to the macOS default as possible, which is why the default layout is `float` instead of `bsp`.

**Comment by willhaslett** [comment]
I see. Thank you. I do suggest a prominent notice of this default in the Quick Start. People find this excellent repo when looking for a tiling window manager, and when they follow the install instructions, there is no tiling. It seems like the example `.yabairc` should result in the same behavior that one sees in the screenshot in the README.

**Comment by koekeishiya** [comment]
The sample config does actually have tiling enabled, but everything else is off, as you can see here: https://github.com/koekeishiya/yabai/blob/master/examples/yabairc

**Comment by willhaslett** [comment]
Got it. Thank you. My bad. I had accidentally swapped the `rc` file names. That'll do it.
