### ISSUE TITLE
Unexpected behavior with focus_follows_mouse=autofocus

### ISSUE THREAD

**Issue by safris** [koekeishiya/yabai#595]
I have just installed yabai with a minimal setup (to use "focus follow mouse" feature, without auto raise):

```
yabai -m config focus_follows_mouse autofocus
```

It works amazingly well! There are a couple glitches, though, that I cannot figure out how to solve via configuration.

**Glitch 1**

When I am Command+Tab'ing, I have a habit of mousing over the window switcher to pick the exact application I want to switch to. When I mouse over the switcher, the switcher disappears. Or, if the cursor is under the switcher when I press Command+Tab, then the app that's under the cursor is immediately activated and brought frontmost.

**Glitch 2**

I have auto-hiding dock. When I move the cursor to bring up the dock at the bottom, and move the cursor across the application icons, whatever icon is under the cursor, that application is immediately brought frontmost. I attempted to remedy this glitch by adding a `window_focused` signal to `Dock`, but it seems signals for Dock are not coming through.

**Glitch 3**

In order to try to remedy these issues via configuration, I attempted set the `mouse_modifier` to `cmd`. This thus disables autofocus when Command is pressed (which is perfect!), but then it causes another side-effect that is a no-go for me: If `mouse_modifier` is `cmd`, then whenever `cmd` is pressed, the only mouse actions that are registered are `mouse_action1` and `mouse_action2`. I noticed this is an issue when attempting to click on a link in Chrome while holding the Command key. The expected behavior of this action is for the link to be loaded in a new tab, without the focus switching to that new tab. The actual behavior, however, is that the click is not registered, because I assume that `mouse_action1` is consuming the mouse events.

Looking at the configuration spec, `mouse_action1` and `mouse_action2` only accept `move` or `resize`.

_Is it plausible to have `off` as a third option, to basically disable the mouse actions if so desired? This would allow `mouse_modifier` to be set to `cmd` sans the side-effects._

**Glitch 4**

Whenever a menu of some kind is displayed, menu items are immediately clicked when I mouse over them. I can remedy this with the following signal config:

```
yabai -m signal --add event=menu_opened action="yabai -m config focus_follows_mouse off"
```

However, since there is no `menu_closed` signal, I cannot create a signal event to turn `focus_follows_mouse` back to `autofocus`.

I'm surprised that I've not found other issues mentioning these specific glitches. Perhaps this is just something happening on my machine due to some misconfiguration?

Thanks for your help!
seva

**Comment by koekeishiya** [comment]
I doubt that I will spend time looking into this as I am thinking of removing autofocus in the next breaking release. See my comment here: https://github.com/koekeishiya/yabai/issues/578#issuecomment-644127717

**Comment by safris** [comment]
Hi @koekeishiya, thanks for your quick reply. I've just discovered yabai, so I'm pretty new to the terminology. You refer to "autoraise + window_topmost". What does "window_topmost" mean? I know what "autoraise" is, but I don't know what "window_topmost" is.

**Comment by koekeishiya** [comment]
*window_topmost* lets floating window always stay above other windows.

**Comment by safris** [comment]
Alright, I'll check out the behavior of _window_topmost_. FFM was always the #1 thing I missed the most from the X11 days, but I know MacOS is not made for it. I just randomly searched for FFM for MacOS in google, expecting to find the age-old posts saying it can't be done. But when I saw _yabai_, I couldn't believe it! The fact that you've gotten this far is truly amazing! I look forward to your next release!

**Comment by karkraeg** [comment]
I also encountered Glitch 2, but only since yabai v3 - I can’t remember that it was like this in v2. Is this possible?

**Comment by koekeishiya** [comment]
I am no longer able to reproduce issue 1, 2 and 4 on the latest master. Can you verify?

**Comment by trevex** [comment]
I encounted the glitches as well and stumbled upon this issue.

I installed the lastest master amd can confirn 1, 2 and 4 are fixed. 👍

**Comment by hamir-suspect** [comment]
I have yabai-v4.0.0 and I encountered the issue 2, how is this fixed or remedied? For now I just have 
// yabai -m config focus_follows_mouse          autofocus
but this is not behaviour I want.
