### ISSUE TITLE
macOS Big Sur dock crashes when trying to right click icon when scripting addition is loaded

### ISSUE THREAD

**Issue by BeanieBen9990** [koekeishiya/yabai#597]
Loading the scripting addition makes right clicking icons on the dock crash it. Right clicking any icon on the dock with the SA loaded crashes the dock immediately. Sometimes this also causes a notification that instead of the SA being reloaded, that is couldn't load and to make sure SIP is disabled (which it is)

**Comment by koekeishiya** [comment]
Please keep all Big Sur related issues in the stickied issue. I've copied this post into that issue.
