### ISSUE TITLE
Display Specific Settings

### ISSUE THREAD

**Issue by IgnacyWie** [koekeishiya/yabai#598]
I think that display scpecific settings would be so good feature. For example having autobalance on on super ultrawide and off on MacBook screen

**Comment by superfunkminister** [comment]
I want this so much! I was thinking of implementing it from scratch, by using the [display_changed signal](https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#signal) to destroy spaces, recreate them, looping through the open apps and sending them to their specific spaces with display specific settings... but it'd be great if this was baked in.

**Comment by prgres** [comment]
Aby updates in this matter? 
I need a much more padding with 38" external monitor than macbook one

**Comment by AlJohri** [comment]
I'd also be really interested in this so that I can have a constant sidebar on my larger display by setting `yabai -m config left_padding 470` and leaving it at a smaller value on my laptop display.

**Comment by koekeishiya** [comment]
The way this would work internally is basically something you can script as well in your config.

1. Get all spaces belonging to the display you want to configure, using `yabai -m query --displays --display <display_index>`
2. Loop through all spaces and call `yabai -m config --space space_index layout|top_padding|left_padding|.. <value>`

More options to customize display selectors have been added on master at the time of writing this comment (the release after v6.0.15 -- will be v7.0.0 when released).

**Comment by AlJohri** [comment]
Is there a way to persist the config value as you create new spaces on each display?

**Comment by mizlan** [comment]
@AlJohri Use signal
