### ISSUE TITLE
Dock 'space' appearing on wrong monitor

### ISSUE THREAD

**Issue by tomusher** [koekeishiya/yabai#6]
The blank space where the dock should go is showing on the wrong monitor for me.

If I have the dock aligned to the right (on my right monitor), the empty space is on my first (left monitor), on the right side.
If I have the dock aligned to the left (on my left monitor), the space is on my second (right montior), on the left side.

If it's useful:
```
>>> [Quartz.CGDisplayBounds(id) for id in Quartz.CGGetActiveDisplayList(2, None, None)[1]]
[<NSRect origin=<NSPoint x=0.0 y=0.0> size=<NSSize width=2560.0 height=1440.0>>, <NSRect origin=<NSPoint x=-1920.0 y=0.0> size=<NSSize width=1920.0 height=1080.0>>]
```

(2560x1440 monitor is on the right, 1920x1080 monitor is on the left)

**Comment by koekeishiya** [comment]
Thanks for reporting this. Fixed on master.
