### ISSUE TITLE
Allow disabling battery indicator from status bar

### ISSUE THREAD

**Issue by weslly** [koekeishiya/yabai#60]
I have a mac mini and the battery widget always show 0% because I don't have a battery. Would it be possible to disable it from the status bar with a config option?

**Comment by koekeishiya** [comment]
On master we check for the existance of a battery, and hide the indicator if none could be found.

**Comment by weslly** [comment]
@koekeishiya for some reason this only works when I compile and link the binary myself. But when I install from `brew install yabai` (v 1.0.2, and even --HEAD), it still shows the battery indicator.

**Comment by weslly** [comment]
@koekeishiya found the reason, actually it only works when compiled with `make`, not `make install`. Could be something with the make flags.

**Comment by koekeishiya** [comment]
Sounds weird to me. The only difference in build settings are `-g -O0` and `-O2`
