### ISSUE TITLE
a space command to start a program always/defaultwise in a certain space?

### ISSUE THREAD

**Issue by emninger** [koekeishiya/yabai#603]
Is there such thing in yabai (like eg. in i3 or bspwm in linux)? I looked into the space commands but did not see it ... (?)
TIA

**Comment by yanzhang0219** [comment]
You could try yabai rules. For example, `yabai -m rule --add app="Finder" space=2` will open Finder and send it to space 2 automatically.

**Comment by koekeishiya** [comment]
You can use window rule as mentioned above: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule
