### ISSUE TITLE
Any way to get active window process name?

### ISSUE THREAD

**Issue by ryuta69** [koekeishiya/yabai#605]
chunkc could get process name by below

```
echo $(/usr/local/bin/chunkc tiling::query --window owner) - " +
             "$(/usr/local/bin/chunkc tiling::query --window name):::" +
             "$(/usr/local/bin/chunkc tiling::query --desktop mode)
```

Is there any way to get in yabai?

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#query

Sample to get information about the focused window: `yabai -m query --windows --window`. You can use the tool `jq` to process the json output to filter/select properties etc.

**Comment by ryuta69** [comment]
Thank you very much! It's great!
Now I can integrate with yabai and ubersicht!
