### ISSUE TITLE
[help] No window corners

### ISSUE THREAD

**Issue by NiTHIN-K** [koekeishiya/yabai#607]
https://i.imgur.com/nyEvDfB.png
As you can see the window borders don't conform to the windows. This is a normal install with yabai and skhd threw through brew

**Comment by yanzhang0219** [comment]
See https://github.com/koekeishiya/yabai/issues/565#issuecomment-642230037

> The border system does not support border radius and placement like the old system did, and it probably never will; guess we'll see.

**Comment by koekeishiya** [comment]
Borders have square corners, because there is no way (that I know of) to retrieve the corner mask of a window so that we can match the window.

**Comment by tsujp** [comment]
I'm at least semi-confident I could get something working to that end, how did you want to model this though? It would require analysing `.car` files so a naive solution right now could be:

1. Include that logic within Yabai itself.
2. Another project which talks to Yabai over some protocol.

Which would be most appropriate _at a glance_ for you @koekeishiya ?
