### ISSUE TITLE
Colour picker apps (i.e. Sip, ColorSnapper) don't "see" window contents

### ISSUE THREAD

**Issue by namkeen** [koekeishiya/yabai#608]
When using a colour picker like Sip, which is basically a system wide eyedropper tool to pick a colour, the app ignores yabai windows and instead just "sees" colours from the desktop background image. Is there any way to alter this behaviour in yabai?

**Comment by dominiklohmann** [comment]
Can you elaborate a bit? What are "yabai windows"?

**Comment by namkeen** [comment]
After further review, it looks like this is completely unrelated to yabai. Closing.
