### ISSUE TITLE
Disable manage LICEcap app

### ISSUE THREAD

**Issue by glepnir** [koekeishiya/yabai#609]
Hi, i set this `yabai -m rule --add app="^LICEcap$"             manage=off` to disable manage it. then restart services of yabai.
But failed.How can i do it?

**Comment by koekeishiya** [comment]
Are you sure the name you specify is correct? Use `yabai -m query --windows` to verify. 
Also you need to add the rule to your config file (although I assume you did this), for it to persist through restart.

You can list the currently active rules using the following command: `yabai -m rule --list`

**Comment by glepnir** [comment]
@koekeishiya  I ensure the name is correct.  the app is here https://www.cockos.com/licecap/
![image](https://user-images.githubusercontent.com/41671631/87811166-cbe74a80-c890-11ea-948e-62ae96a61a92.png)

**Comment by koekeishiya** [comment]
You should verify using the yabai command because that is the name it sees. The rule works fine for all applications that I use, and so that is why I assume the specified name is wrong. The name of the application bundle is not necessarily equal to the name that we retrieve from the macOS process manager API.

**Comment by glepnir** [comment]
Ok I got this.
```
},{
        "index":3,
        "label":"",
        "app":"^LICEcap$",
        "title":"",
        "display_id":0,
        "space_id":0,
        "follow_space":0,
        "opacity":0.0000,
        "manage":0,
        "sticky":-1,
        "layer":"",
        "border":-1,
        "native-fullscreen":-1,
        "grid":"0:0:0:0:0:0"
},{
```

**Comment by glepnir** [comment]
Aha. i got it in activity. its `licecap`. it works.
