### ISSUE TITLE
Official banner / logo

### ISSUE THREAD

**Issue by koekeishiya** [koekeishiya/yabai#61]
It would be nice to have a good looking banner for the README/Wiki, and a square logo/icon for the executable, that could also be repurposed as a badge for system notifications.

Ideas for what would be suitable graphics for these purposes are welcome.
If anyone has experience with this kind of work and want to contribute, that would be great!

To stick with the spirit of the rest of this project, I would like any contributed graphics / design to be made available under a permissive license (CC0?).

Thanks for taking an interest in this software.

**Comment by richardbmx** [comment]
@koekeishiya  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project.

[My Portfolio](https://www.behance.net/richardcaseres)

**Comment by koekeishiya** [comment]
@richardbmx 

That would be great, I'd like that a lot. Looking forward to see what ideas you can come up with

**Comment by richardbmx** [comment]
@koekeishiya  Perfect I will work on it

**Comment by richardbmx** [comment]
@koekeishiya Happy first day I want to apologize for the delay I had some problems with the internet connection.

Here I want to present these two ideas that I developed for your project in both I express the management of windows for IOs, in the second idea I created a figure that works a window with the letter Y to give a more unique personality for your project, I hope you please if you want some change you just have to request it and I will gladly do it

![logo140](https://user-images.githubusercontent.com/35604837/60778238-24bfc700-a104-11e9-9e97-f60ab2146aaf.png)

**Comment by koekeishiya** [comment]
@richardbmx 

No need to apologize for the delay. Thanks again for doing this!

I think both are pretty great. I think the first one would fit best as a banner used in the README/wiki, where as the Y in the second one would be a great fit as the executable logo.

What do other people think?

**Comment by dominiklohmann** [comment]
I particularly like the idea of the top right icon, so I tried to re-create it using the 10px border radius of macOS windows and the traffic light buttons original size, position and colours and gave the front window a 2px shadow. I think this fits a bit better.

I'm not sure about using a Y on the icon. I think logo + "yabai" to the right (bottom left) is the best layout for the banner. I like the the font you used very much.

I experimented with using fontawesome icons that signal automation or power user tools instead of the Y on the icon, but I'm not too sure I like it. 

<div align=center>
<figure>
  <img alt="logo yabai" src=https://user-images.githubusercontent.com/4488655/60814064-4026e280-a195-11e9-8304-d3192e3857bb.png width=30%>
  <figcaption><br>Logo</figcaption>
</figure>
</div>

<div align=center>
<figure>
  <img alt="banner yabai" src=https://user-images.githubusercontent.com/4488655/60814791-9a747300-a196-11e9-9945-6a5ef22baba8.png width=75%>
  <figcaption><br>Banner (ignore the font)</figcaption>
</figure>
</div>

**Comment by hello-party** [comment]
I really like the multiple windows, but shouldn't the windows be somewhat tiled? The second design could be visually confusing since it can resemble the Kodi icon.

**Comment by r3volution11** [comment]
My idea:

![Screen-Shot-2019-07-14-22-01-53 07](https://user-images.githubusercontent.com/698508/61192550-1ed96100-a683-11e9-9559-5c20b9603117.png)

The icon represents tiling while rotated to present a "Y." And of course, the colors in the lettering signify window controls. Simple.

**Comment by capaldo** [comment]
> My idea:
> 
> ![Screen-Shot-2019-07-14-22-01-53 07](https://user-images.githubusercontent.com/698508/61192550-1ed96100-a683-11e9-9559-5c20b9603117.png)
> 
> The icon represents tiling while rotated to present a "Y." And of course, the colors in the lettering signify window controls. Simple.

Maybe a different font? Either way I'm loving it as is.

**Comment by ayaz-qureshi** [comment]
Hi i just created a logo/iocn for Yabai, tell me where you need improvement. When the logo will be finalized then i will move to the banner. feel free to criticize.
 
![yabai logo](https://user-images.githubusercontent.com/53651323/62411628-cbd03b00-b5aa-11e9-8cf1-178c89422356.png)

**Comment by hello-party** [comment]
The stacked windows don't really reflect a tiling window manager. 

I think @r3volution11 has the right idea. Either the logo should be literal (representing tiling) or absolutely not literal (text with another illustration.)

Like r3v's, I think it should be more along lines of something like this -- but not this because it's not good. 

![logo](https://user-images.githubusercontent.com/1559567/62417229-812cde00-b5ff-11e9-9e0b-64c92b9a852e.png)

**Comment by fools-mate** [comment]
The idea of @r3volution11  is very clever and I want to contribute my version to it. So I tried to make the logo a bit more playful.

I hope you like it.

![yabai-logo-foolsmate-01](https://user-images.githubusercontent.com/34334994/64011246-9a03b300-cb1b-11e9-808d-64c264a17409.png)

**Comment by koekeishiya** [comment]
@fools-mate I like this one a lot actually. 

There are a lot of great ideas present here, and I'm not sure how to go about deciding on which one to go with.

**Comment by r3volution11** [comment]
@fools-mate Thanks for the comment. I like what you've done as well. I'm not so sure about overlaying the font when showing the full name but I see how it makes sense in keeping it together. I wonder if removing the window control colors would be it look less cluttered (just a white fill).

**Comment by fools-mate** [comment]
@koekeishiya & @r3volution11 - Thank you for the feedback!

@r3volution11 - I fully understand your arguments and I think the new variant could be a good approach to make the logo cleaner. 

I also fixed the optical illusion that the Y looked thinner than the rest.

![yabai-logo-fools-mate-03](https://user-images.githubusercontent.com/34334994/64337035-bce00c80-cfde-11e9-9b7a-206d7fdfefb1.png)

**Comment by pcr910303** [comment]
@fools-mate I mostly like the last variant, it's great!
Can you tilt the 'y' a little more? I feel that the slope of the right line of 'y' is too steep.

**Comment by dominiklohmann** [comment]
I really, really like that last one by @fools-mate. That‘s the one for me, I think.

**Comment by koekeishiya** [comment]
@fools-mate I like that last variant one as well. Could you upload in this issue or send me a 512x512 version of the icon and I'll add it to the repository. As @dominiklohmann is responsible for the wiki he would need the banner image. I suppose that could also be stored in the repo if necessary, but it is probably sufficient to simply upload it in an issue and refer to it by url like I do with screenshots.

**Comment by dominiklohmann** [comment]
I‘d prefer Sketch/PSD if possible, then we can always adjust the size later. Also icons are 1024x1024 per Apple Human Interface Guidelines for the 2x version.

**Comment by koekeishiya** [comment]
> Also icons are 1024x1024 per Apple Human Interface Guidelines for the 2x version.

Hmm weird, the following docs say 512: https://developer.apple.com/documentation/appkit/nsworkspace/1529882-seticon?language=objc

**Comment by dominiklohmann** [comment]
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

**Comment by fools-mate** [comment]
@koekeishiya  & @dominiklohmann - I'm really glad you like it!

In the archive you will find everything you need. 
(banner & icons as svg and png (16px up to 1024px))

This is a version without drop shadows. If you want one, just tell me.

[yabai-logo.zip](https://github.com/koekeishiya/yabai/files/3579795/yabai-logo.zip)

**Comment by dominiklohmann** [comment]
Thank you so much! 👍

**Comment by dominiklohmann** [comment]
@fools-mate in the banner, there is a white circle around the red dot in the a, while there's no white circle in the yellow and green dots. Can you make it transparent for the a as well so the banner doesn't look off on backgrounds other than white? That'd be very much appreciated!

**Comment by fools-mate** [comment]
@dominiklohmann - Oh, I missed that. Here you get the corrected version.

[yabai-banner-fix.zip](https://github.com/koekeishiya/yabai/files/3580671/yabai-banner-fix.zip)

**Comment by koekeishiya** [comment]
Thanks to everyone who participated with ideas, and designs. I've decided to go with the version made by @fools-mate. Closing this issue.

**Comment by x-ji** [comment]
Out of curiosity, I've always been wondering what the name "yabai" actually means. All I know is that in Japanese it means "very bad"/"dangerous" 😅. Did you have that in mind when you chose that name @koekeishiya (also your handle sounds Japanese but I don't think it's an actual Japanese word, or is it?)
