### ISSUE TITLE
Add focus_follows_mouse autofocus only until a key pressed

### ISSUE THREAD

**Issue by anbm-admin** [koekeishiya/yabai#611]
It would be great if we could have autofocus but only until a key is pressed on the keyboard, that would be very useful because a lot of times you only want the focus to write or use a keyboard shortcut in the hovered app and this way you don't lose the ability to use the menu bar when you cross any other application.

**Comment by dominiklohmann** [comment]
You can hold the `mouse_modifier` key (defaults to <kbd>fn</kbd>) to temporarily disable `focus_follows_mouse`.

**Comment by anbm-admin** [comment]
Thanks for the tip but anyways I suggest that it'll be easier to do the autofocus only until a key is pressed, that would cover almost any case of use for the autofocus and avoid any side effects

**Comment by dominiklohmann** [comment]
What's stopping you from setting up a keybind that changes your `focus_follows_mouse` setting to `off`?

**Comment by koekeishiya** [comment]
I'm not really interested in making changes to the focus-follows-mouse functionality at this point in time. It works more or less the way I originally envisioned it. I understand that it might not be the cup of tea for everyone, but such is life.
