### ISSUE TITLE
Borders end up behind windows

### ISSUE THREAD

**Issue by brorbw** [koekeishiya/yabai#614]
I've pulled the latest version and the borders end up behind the windows when they get focused and then they stay there.

**Comment by koekeishiya** [comment]
As mentioned in #565 , you need to reinstall the scripting-addition.

**Comment by brorbw** [comment]
I see. I thought I did, but I forgot `sudo` but yabai no longer warns if you are trying to install `sa` without `sudo`

**Comment by brorbw** [comment]
Issue resolved by running `sudo yabai --install-sa`

**Comment by BovineEnthusiast** [comment]
@koekeishiya Does this mean that for those of us who don't disable SIP, we will always have this issue even if 

```
yabai -m config active_window_border_topmost on
```

is set?

Thanks!
