### ISSUE TITLE
external_bar only works in config when set before padding

### ISSUE THREAD

**Issue by dsanson** [koekeishiya/yabai#615]
Took me a few minutes to figure out that the `external_bar` setting needs to be set *before* `top_padding`, `bottom_padding`, etc. in `yabairc`. So something like this works as expected:

```
yabai -m config external_bar                 all:0:26
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
```

But something like this won't respect the `external_bar` setting until after toggling the padding on and off (e.g., with `yabai -m space --toggle padding`):

```
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config external_bar                 all:0:26
```

**Comment by koekeishiya** [comment]
That is not intentional and I don't immediately remember why this would be the case. Sounds more like a bug rather than an anomaly that has to be documented.

**Comment by koekeishiya** [comment]
Fixed on master.
