### ISSUE TITLE
"visible" is set to 1 for hidden apps

### ISSUE THREAD

**Issue by d-miketa** [koekeishiya/yabai#616]
On Mac OS one can either minimise a window (Cmd+M by default) or hide the application altogether (Cmd+H). Whereas `yabai -m query --windows --space [n]` shows if a window is minimised, it seems to be agnostic about whether the app is hidden or not (which, in this case, it is):

```
{
        "id":11256,
        "pid":8062,
        "app":"WhatsApp",
        "title":"WhatsApp",
        "frame":{
                "x":15.0000,
                "y":576.0000,
                "w":856.0000,
                "h":529.0000
        },
        "level":0,
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "movable":1,
        "resizable":1,
        "display":1,
        "space":1,
        "visible":1,
        "focused":0,
        "split":"none",
        "floating":0,
        "sticky":0,
        "minimized":0,
        "topmost":0,
        "opacity":0.9000,
        "shadow":1,
        "border":1,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
}
```

Here `visible=1` simply indicates that the space (2) is visible on its associated display (1). I think it'd make more sense if `visible=0` if the app is hidden; failing that, there should be a `hidden` key.

The following Applescript snippet works as I'd expect:
```
target_app="WhatsApp"
osascript -e "tell application \"System Events\" to get visible of first process whose name is \"${target_app}\" "
false
```

**Comment by koekeishiya** [comment]
I am aware of this inconsistency, but waiting to fix it until I revise the output of the query system.
