### ISSUE TITLE
Borders don't follow window movement

### ISSUE THREAD

**Issue by peppy** [koekeishiya/yabai#617]
Reproduction:
- Set window border to >0px
- Swap windows using (in the example `yabai -m window --swap west`)
- Border's "shadow"(?) portion doesn't follow the movement and sticks to the wrong window.

![2020-07-20 10 59 57](https://user-images.githubusercontent.com/191335/87893316-84241700-ca7a-11ea-81bb-921b1f92a4c3.gif)

In the example I've made the width very thick to better show the issue. I do two swaps west then one swap east.

**Comment by koekeishiya** [comment]
What the heck, borders are not supposed to have shadows. Guess I never noticed because I run with `window_shadow off` and that also removed the shadow of the border window created by yabai.

**Comment by peppy** [comment]
The weird part is, it still happens with `window_shadow` turned off (the active border doesn't have a shadow, but the "ghost" one does:

![IMG_0657](https://user-images.githubusercontent.com/191335/88241247-8083d080-ccc4-11ea-98a3-6921dee9c6c1.jpeg)

**Comment by koekeishiya** [comment]
I misspoke earlier. Borders created by yabai are not affected by the `window_shadow` setting. Made a change to master that explicitly disables the shadow when the border window is created, and that seemed to fix the issue for me.

**Comment by peppy** [comment]
Tested head, works perfectly. Thanks!
