### ISSUE TITLE
application_launched action for Google Chrome

### ISSUE THREAD

**Issue by jorgebef** [koekeishiya/yabai#618]
I've been managing yabai so that some applications that use small windows start as floating and upon launch they would automatically become tiled, so that the subsequent windows that said app creates are still floating, while the main one is tiled.
This is the case of Mail for me, which works like a charm, but I cannot make Google Chrome follow said pattern.

Here is the code I use which works for Mail but has no effect on Google Chrome, am I missing something or is this a known issue?

`yabai -m signal --add event=application_launched app='^Mail$' action='yabai -m window --toggle float'`
`yabai -m signal --add event=application_launched app='^Google Chrome$' action='yabai -m window --toggle float'`

If any extra info is neeeded I am more than happy to look for what is causing the issue!

**Comment by Chandru-B** [comment]
I had a similar issue with Google Chrome. I had to quit google chrome with ⌘Q and relaunch sometimes.

**Comment by dominiklohmann** [comment]
The `application_launched` signal may trigger before the windows are restored. This looks like a timing issue in your signal to me, since you simply look for the active window (default selector).

**Comment by jorgebef** [comment]
> The `application_launched` signal may trigger before the windows are restored. This looks like a timing issue in your signal to me, since you simply look for the active window (default selector).

You were absolutely right, it apparently triggers before there is a window to even be selected!

For future reference if anyone encounters this problem, I just solved it with a simple sleep command as such:
`yabai -m signal --add event=application_launched app='^Google Chrome$' action='sleep 0.7 && yabai -m window --toggle float'`

Issue closed!
