### ISSUE TITLE
Disable focus follows mouse while mouse modifier key is held down

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#62]
### Issue

- Focus follows mouse makes it hard to access the menu bar for some windows

### Proposed fix

- Temporarily disable focus follows mouse while the `mouse_modifier` key is held down
- When the `mouse_modifier` key is released and focus follows mouse is active, focus/raise the window below the cursor (do not require cursor movement)

**Comment by koekeishiya** [comment]
> Temporarily disable focus follows mouse while the mouse_modifier key is held down

This would be a trivial change to support, and makes sense.

> When the mouse_modifier key is released and focus follows mouse is active, focus/raise the window below the cursor (do not require cursor movement)

I'm a bit reluctant to adding this, as we would need to hook into basically *all* key-down events, similar to how *skhd* works. Is there maybe a different approach that could give similar affect?

**Comment by dominiklohmann** [comment]
I cannot come up with a different approach. The second proposal is probably best left unimplemented for now with all the requirements it has and I may post it again at a later time iff yabai starts listening to key events for some other reason.
