### ISSUE TITLE
Yabai keeps restarting using Xcode 11.5

### ISSUE THREAD

**Issue by returnzer0** [koekeishiya/yabai#621]
Yabai keeps restarting whenever I am writing code in Xcode. Doesn't happen in any other application.

I have not setup auto-updates which might cause it to restart.

The only keys I have mapped to restart yabai are `shift + alt + ctrl + r` which are not pressed when I am writing code.

**Comment by dominiklohmann** [comment]
Duplicate of #580 

Update to yabai v3.2.1 and the issue should be gone.

**Comment by returnzer0** [comment]
Thank you, it was indeed this issue.
