### ISSUE TITLE
Parallels Coherence Windows Applications Aren't Tiled

### ISSUE THREAD

**Issue by Ninja73737** [koekeishiya/yabai#622]
When Parallels desktop windows coherence mode applications are opened they aren't tiled, but I'd like them to be. Here are the results of the `yabai -m query --windows` command for the "Messenger (Beta)" windows application.
Before running `yabai -m window --toggle float`:
```
{
	"id":5697,
	"pid":8659,
	"app":"Messenger (Beta)",
	"title":"Messenger",
	"frame":{
		"x":407.0000,
		"y":501.0000,
		"w":800.0000,
		"h":435.0000
	},
	"level":3,
	"role":"AXWindow",
	"subrole":"AXDialog",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":3,
	"visible":1,
	"focused":0,
	"split":"none",
	"floating":1,
	"sticky":0,
	"minimized":0,
	"topmost":1,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}
```
And after running `yabai -m window --toggle float` on the window in question:
```
{
	"id":5697,
	"pid":8659,
	"app":"Messenger (Beta)",
	"title":"Messenger",
	"frame":{
		"x":709.0000,
		"y":323.0000,
		"w":882.0000,
		"h":474.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXDialog",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":3,
	"visible":1,
	"focused":0,
	"split":"none",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}
```
The window was also moved a bit between those two tests.
Let me know if you'd like me to do any more testing to help figure out why yabai isn't finding these windows, I suspect there's something non-standard about the way Parallels passes application windows through to MacOS, but I'm not sure how to go about doing more testing.
Edit: here's a link to an explanation of what coherence mode is: https://kb.parallels.com/en/4670

**Comment by koekeishiya** [comment]
The window is not tiled because it has subrole `AXDialog` and not `AXStandardWindow`.
You can make this specific window automatically tile by using window rules: https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule

Add something like this to your config file: `yabai -m rule --add app="^Messenger (Beta)$" title="^Messenger$" manage=on`

**Comment by Ninja73737** [comment]
Ok thanks!

**Comment by Ninja73737** [comment]
Quick update, for those that also run into this, I've added this line to my yabai config: `find ~/Library/Parallels/Applications\ Menus/ -maxdepth 3 -type f | awk -F'/' '{ print $NF; }' | awk '{$1=$1};1' | tr "\n" "\0" | xargs -0 -I{} yabai -m rule --add app="^{}\$" title=".*" manage=on`
Basically, it recursively lists all the files inside your parallels coherence app shortcuts folder, then creates a rules that enable management for any windows that have the same app name as one of those shortcuts. It's definitely not perfect, I've just started using it, but let me know if you have any suggested improvements let me know.
