### ISSUE TITLE
Is it possible to draw/move a window off screen?

### ISSUE THREAD

**Issue by cmacrae** [koekeishiya/yabai#623]
Hey @koekeishiya 👋 

Wondering if it's possible to intentionally draw/move an application window off the screen?  
I'd like to have an application running which I can Cmd+Tab to to gain focus, but I don't want it displayed (minimization isn't an option).

If not, I'm sure I could cook up my own little patch to use personally, I just wanted to see if it was possible natively.

**Comment by dominiklohmann** [comment]
You can move a window to the bottom right side of the screen such that it is barely visible.

```sh
yabai -m window --move abs:10000:10000
```

Did you consider minimizing the window using yabai, or moving it to a temporary space that you create ad-hoc?

**Comment by cmacrae** [comment]
Thanks @dominiklohmann 🙌   
I'd prefer to avoid minimize, as I effectively want to frequently give the window focus using Cmd+Tab, but not display it, and have that all happen without interrupting my current workspace/window setup (so, don't want to minimize/unminimize or switch spaces).

Thanks! This is good enough for me 😁

**Comment by dominiklohmann** [comment]
Note: If you hold <kbd>option</kbd> before releasing <kbd>command</kbd> when using <kbd>command</kbd> + <kbd>tab</kbd>, you force the target application's windows to be deminimized.
