### ISSUE TITLE
Yabai Constantly Crashing / Unstable

### ISSUE THREAD

**Issue by lossdev** [koekeishiya/yabai#624]
I used to be able to use yabai months ago without issue, however, at one point in time, yabai started consistently crashing into a white screen, force logging me out, then (of course) losing my windows when I have to log back in, and has been ever since. I'm not sure if it's an issue of something else I have installed conflicting somehow or any other possibility.

The crashing seems to be exacerbated by 

* Moving window spaces quickly (or at all sometimes)
* Modifying `.yabairc` and restarting yabai; yabai becomes extremely unstable after the restart and has been crashing in a minute or less afterwards
* System under heavy load

Here's what `yabai.err.log` said (note: the first failure was after I updated to 3.2.1 and before I enabled accessibility settings):

```
thread: 338234816 | yabai: could not access accessibility features! abort..
thread: 269201408 | yabai: scripting-addition either failed to load or could not inject payload into Dock.app! Error: -600
unknown command 'window_border_radius' for domain 'config'
could not locate the window to act on!
unknown key 'active_window_opacity'
unknown key 'active_window_opacity'
unknown key 'active_window_opacity'
could not locate the window to act on!
unknown key 'active_window_opacity'
could not locate the window to act on!
unknown key 'active_window_opacity'
unknown key 'active_window_opacity'
could not locate the window to act on!
unknown key 'active_window_opacity'
could not locate the window to act on!
unknown key 'active_window_opacity'
```

I've already removed `window_border_radius` and `active_window_opacity` from my `.yabairc`, and that didn't seem to have an effect on the issue. I'm not sure where else to look at to see why my whole desktop would be crashing.

yabai version: 3.2.1
akhd version: 0.0.6
macOS version: 10.15.5

**Comment by koekeishiya** [comment]
Probably https://github.com/koekeishiya/yabai/issues/277

**Comment by lossdev** [comment]
That seems to have been it, thanks!
