### ISSUE TITLE
For integration with Kitty, how can another process get its yabai-compatible window numbers?

### ISSUE THREAD

**Issue by eraserhd** [koekeishiya/yabai#625]
Background, I'm running yabai with kitty, and kitty has several windows in the same process. I want to be able to have my editor (running in several Kitty windows), figure out where it is on the screen, relative to other editor windows.

Kitty has window numbers, but they start at 1 and increase monotonically.  I looked at the yabai code and found the use of the private API `_AXUIElementGetWindow(ref, &wid)`.

I'm not sure how, in Kitty, to get a AXUIElementRef from a window (the ref isn't the window itself, is it?), or whether I can use this private API without requiring the user to agree to accessibility permissions.  I see that NSWindow has windowNumber, but the documentation says this is not the same as the global window server number.

Thoughts?

kovidgoyal/kitty#2552

**Comment by koekeishiya** [comment]
NSWindow windowNumber is the same thing, whatever documentation says otherwise is wrong. AXUIElementRefs are only necessary for external software that wants to interact with windows of some other application.

**Comment by eraserhd** [comment]
Thank you!  This got merged to kitty and is working nicely.
