### ISSUE TITLE
Recent update to Chrome results in strange size/placement issues with multiple displays

### ISSUE THREAD

**Issue by chandlerc** [koekeishiya/yabai#627]
I track yabai following head (using `brew upgrade --fetch-HEAD`). Within the last week (maybe two) I have a new bug.

I'm not sure exactly how best to get information to help debug this, please let me know if I can do something to help describe this more precisely or debug it.

When switching between displays (consistently when attaching or removing an external display, and at times simple when changing focus between displays) the shape and/or size of windows changes to not match the obvious tiling. The most obvious case is on my larger external display. I have two windows there, and one or both of them change to a different shape. It roughly looks like the full-size single window on my laptop, with both windows over top of each other.

If I do anything that re-layouts the display (for example `yabai -m space --rotate 90`), everything returns to normal.

This resumes periodically when I change display focus between different display devices (screens? I forget the macOS for this).

So far, I don't recall this happening when I change between displays on a the same device.

Anyways, I know this is somewhat vague. Hopefully someone can suggest what diagnostic steps would help debug this.

**Comment by chandlerc** [comment]
Hmm, went back to the last release (v3.2.1) and it's still happening, so not likely a *regression* as just some strange new behavior uncovered when connecting and disconnecting physical monitors...

It feels almost like a race condition somewhere. Will keep experimenting to understand exactly what's going wrong here.

**Comment by koekeishiya** [comment]
So by display devices I assume you mean physical monitors? and by changing between displays on the same device, I assume you mean different workspaces (spaces) that all belong to the same monitor?

Hmm regarding display connection/disconnection. Are you using a 4k display when this is happening? It reminds me somewhat of https://github.com/koekeishiya/yabai/issues/259, but issues arising when simply focusing a different display is not something that I have experienced before.

I would be surprised if there is a race condition, as everything in yabai runs off a single thread. There are probably 3 threads in total for observing various notifications from macOS that queues an internal event on to our event-loop using a lock-free queue.

Did you verify that `yabai --version` actually outputs *yabai-v3.2.1* after you downgraded? 
I know there has been issues with brew when switching between head and release versions in the past.

I suppose you could run as `yabai --verbose` or add `yabai -m config debug_output on` to your config file. Messages are written to stderr and stdout, so you'd have to configure that if you haven't done so already. I believe this wiki section should be up-to-date: https://github.com/koekeishiya/yabai/wiki/Configuration#debug-output-and-error-reporting
There is not much logging happening throughout, so this will probably only give you an indication of which type of events were processed at the time the issue occurred.

**Comment by chandlerc** [comment]
(thanks for correcting my terminology, I think you understood me correctly)

I am using a 4k external monitor, and so there are GPU switches that take place.

I definitely have seen something like #259 when coming back from sleep. Windows end up collected on just my laptop some of the time, but not always. This doesn't bother me too much, it only happens coming back from sleep. I opened #238 to request something to try to mitigate it, but it didn't seem like the APIs were really present to make it work. 


This is definitely different. Notably, the windows don't tile correctly at all. They don't even fit correctly on the display, they seem weirdly mis-located and sized hanging partially off a corner.

I can try to get it to happen with blank windows to take a screen shot or something if that would help, but so far it has only happened while I've been working...

**Comment by koekeishiya** [comment]
This might not be something you can do, but figured I'd ask anyway.. is it possible for you to try and use regular 1080p displays for some time and see if this issue is exclusive to 4k displays? My assumption is that it will be, and if so I am unable to really do much about that, as I do not have a 4k display to observe, test and reproduce the issue.

**Comment by chandlerc** [comment]
Some progress here. It is ... I think weirder than at least I imagined.

Perhaps most significantly, I can now reliably trigger this, every single time. That makes it much easier to run any experiments to help, and the necessary requirements also are ... surprising.

- It only seems to happen when I have Chrome windows in the current workspace on both physical monitors. And I mean this *only* applies to Chrome windows that I've found. Neither my kitty terminals nor TextEdit windows replicate this behavior, so something about *Chrome* is at least somewhat unusual here.

- The mis-layout is triggered by: `yabai -m display --focus $id`, and is the *target* of this focus change that becomes mis-layouted.

- It may matter whether Chrome or some other application gets the focus as well. But getting somewhat inconsistent results here.

- It doesn't seem to happen when I just move the mouse from one display to another (with autofocus off).

- Several different layout updating events seem capable of restoring the layout, not just rotating.

---

I don't have a 1080p display readily available. But now that this is really easily reproducible for me, I can try to force my current monitor to use a different resolution and test that out.

I'll also wire up logging and enable debugging to collect logs for you.

Will update later today hopefully, just need to get some work stuff cleared out first....

**Comment by chandlerc** [comment]
(Oh, and I suspect that it was a *Chrome* update that caused this to start happening, not anything else. So I suspect Chrome somehow started changing how it manages its windows and that is what is triggering the misinteraction with Yabai. Of course, the 4k thing still seems plausibly also a necessary component triggering this... 🤦🏻‍♂️)

**Comment by Berteun** [comment]
I'm using yabai from brew, v3.2.1 and have Chrome  84.0.4147.105. I also noticed that quite recently Chrome stopped working. Now I don't use a lot of automatic tiling, I have some short cuts defined through skhd to put windows in the layout I'd like to.

For whatever reason this doesn't work with with Chrome anymore. Then I saw this issue which looks relevant. I hope this can help you into the right direction.

Here some test commands form the terminal, that, when Chrome is the active window, result in an error from Yabai:
```
# I move my terminal to occupy the left half of the screen. Works great.
$ yabai -m window --grid 1:2:0:0:1:1

# I sleep so I can switch to Chrome, and and then Yabai issues this error.
$ sleep 2; yabai -m window --grid 1:2:0:0:1:1
could not locate the window to act on!

# I sleep and switch to Firefox, and that works.
$ sleep 2; yabai -m window --grid 1:2:0:0:1:1

$ yabai -v
yabai-v3.2.1
```

I have SIP enabled. If you need any more information, then please let me know.

**Comment by koekeishiya** [comment]
Well that sounds to me like the chrome team did something that broke basic support for the accessibility API that yabai relies on.

Sent from my iPhone

On 6 Aug 2020, at 09:16, Berteun <notifications@github.com> wrote:

﻿

I'm using yabai from brew, v3.2.1 and have Chrome 84.0.4147.105. I also noticed that quite recently Chrome stopped working. Now I don't use a lot of automatic tiling, I have some short cuts defined through skhd to put windows in the layout I'd like to.

For whatever reason this doesn't work with with Chrome anymore. Then I saw this issue which looks relevant. I hope this can help you into the right direction.

Here some test commands form the terminal, that, when Chrome is the active window, result in an error from Yabai:

# I move my terminal to occupy the left half of the screen. Works great.
$ yabai -m window --grid 1:2:0:0:1:1

# I sleep so I can switch to Chrome, and and then Yabai issues this error.
$ sleep 2; yabai -m window --grid 1:2:0:0:1:1
could not locate the window to act on!

# I sleep and switch to Firefox, and that works.
$ sleep 2; yabai -m window --grid 1:2:0:0:1:1

$ yabai -v
yabai-v3.2.1


I have SIP enabled. If you need any more information, then please let me know.

**Comment by chandlerc** [comment]
Agreed. And in fact, it has fixed itself with another Chrome update. Closing the issue, sorry for the noise.
