### ISSUE TITLE
Issues with Hyper.js terminal

### ISSUE THREAD

**Issue by Liquidmantis** [koekeishiya/yabai#630]
I'm having consistent issues with the Hyper.js terminal app.  It seems to constantly become sticky and floating.  I have hotkeys to toggle both states, and all my other tested apps work fine, but Hyper constantly launches as both sticky and floating, confirmed with querying windows.  If I use my hotkeys to turn off the sticky and floating, nothing changes, but if I maximize Hyper to native-fullscreen then restore it, it will snap to the layout, but still remains sticky on all spaces.

It's only Hyper that this is happening with.  I've tried VS Code and Slack and they both behave, so I don't think it's an Electron issue.

**Comment by babygau** [comment]
i experienced same issue with `PDF Expert` app

**Comment by yanzhang0219** [comment]
Both Hyper.js and PDF Expert work very well on my end. I installed yabai from HEAD and my macOS version is 10.15.6. You could try to install yabai from HEAD (refer to https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) and see whether it could be solved.

**Comment by Liquidmantis** [comment]
Looks like this was a case of user error for me.  Hyper was assigned to "All Desktops".  Once I set that back to None it started behaving with Yabai and respecting the sticky and floating states.

![image](https://user-images.githubusercontent.com/399056/89141668-78b4ff00-d502-11ea-9c9b-213bf02394dc.png)
