### ISSUE TITLE
Switching Spaces

### ISSUE THREAD

**Issue by 24unix** [koekeishiya/yabai#631]
Hi, I'm new to Yabai.

As Big Sur killed Deskovery III I miss my transparent windows :(

Found Yabai, guessed it could be a good replacement, tiling can be disabled on a per space basis, thats very cool for me.
On the main monitor I don't want any software to interfere with my preferred windows Layout, but on the addional monitors it's quite nice …
But: I have to break spaces, otherwise Yabai won't work :(

So I thought I could recreate the right behaviour (switching spaces changes them on all monitors) with some hotkeys in skhd.
But switching doesn't work at all. E.g.  yabai -m space --focus 3 should change the space on the current monitor, shouldn't it?
That monitor is assigned space 9 to 16.

I just want the behaviour back I had from the beginning of using macOS. ctrl-x switches all monitors to the respective space, before it were space 1 to 8, now it are 1 to 24, too much for the system hotkeys (can only handle up to 16 spaces).

Maybe someone can point me in the right direction.

Kind regards,
  Micha
Edit: I'm getting used to Yabai.
The broken up spaces are not that bad, as fullscreen mode comes usable again (with the former default the secondary monitors just turn black, rendering them useless). I get used to bsp Mode, even on the main display.
Only issue is the switching of the spaces, then I'd have a Mac setup better than any KDE Desktop.

**Comment by dominiklohmann** [comment]
Big Sur is in developer beta. If you want to run yabai with all of its features, use the stable version of macOS.

On the same note, please keep all Big Sur-related things in the pinned thread: #589.

Closing this as duplicate.
