### ISSUE TITLE
please support osx 10.12.x

### ISSUE THREAD

**Issue by clankill3r** [koekeishiya/yabai#633]
Please add support to OSX 10.12.x.
If this is not possible then I would like to know why.
I really don't want to update my OS.

**Comment by dominiklohmann** [comment]
macOS 10.12 Sierra is almost 4 years old now, and lacks some APIs that yabai uses. I seriously doubt this is going to happen, but since this is an open-source repository, you can always fork and open a PR with your adaptations for macOS 10.12x.

Out of curiosity: What's stopping you from updating?

**Comment by koekeishiya** [comment]
There is no technical limitation that I am aware of, but supporting macOS 10.12.x requires more effort and time than I think it is worth, due to internal differences between the OS versions.
