### ISSUE TITLE
Ability to mark windows and focus previous marks

### ISSUE THREAD

**Issue by NickvanDyke** [koekeishiya/yabai#634]
What would your thoughts be on marking functionality, similar to in VIM? i.e. `yabai -m window --mark d`, then do whatever, then later `yabai -m window --focus-mark d` will focus the window that was focused during the first command.

**Comment by dominiklohmann** [comment]
Labels are only supported for spaces currently, but not for windows. 

If labels were supported for windows as well, you'd be able to use this:

```bash
# fictive syntax
yabai -m window --label test
yabai -m window --focus test
```

With yabai as is, you could use the window identifier, which happens to be a valid window selector.

```bash
# get the id of the focused window
id="$(yabai -m query --windows --window | jq '.id')"

# later: focus the window by its id
yabai -m window --focus "$id"
```

**Comment by NickvanDyke** [comment]
Ah, good point, I hadn't thought of that! Thanks!
