### ISSUE TITLE
Feature Request: Command to find name of a focused window and persist/apply default float setting

### ISSUE THREAD

**Issue by grant-park** [koekeishiya/yabai#638]
I find it a hassle to lookup the name of an application and write a rule in my config to ensure that it floats the next time I open it. It is a common solution to a problem like https://github.com/koekeishiya/yabai/issues/345 

I would like to have a skhd hotkey to press and run a yabai command to give me the name of an application that I currently focused on (this may include things like system preferences, skype, etc.) interpolated in a name I can copy/paste to my yabai config e.g. `"title='Preferences"` or `"app='Google Chrome'"` The name could be output in a file somewhere or in a live cli that is listening for updates. 

Even better would be the ability to float a window "permanently" so that whenever I float a window, I could add the option to float it the next time I ever open it. This setting could be persisted in a file somewhere that I can edit. 

EDIT: my temporary solution is from this https://github.com/koekeishiya/yabai/issues/605 I do a `sleep 3s && yabai -m query --windows --window` in my terminal and then quickly focus the window I want the name of -- I then check back in the terminal to see the value

**Comment by yanzhang0219** [comment]
You could run `yabai -m query --windows --space` in a terminal to print out the information of each window in the current space. Then you can find the window name which you care about. 

Or you can bind a key to `yabai -m query --winodws --window | jq .app > focusname`. Then you could press this key to get the name of your current focused window and output it into a file named focusname.

**Comment by grant-park** [comment]
Awsome stuff! Thanks for the creative solution.

**Comment by koekeishiya** [comment]
You can also bind the following to get the app and/or title of the currently focused window on the clipboard:
```
# read the app attribute of the currently focused window
yabai -m query --windows --window | jq -r '.app' | pbcopy

# read the title attribute of the currently focused window
yabai -m query --windows --window | jq -r 'title' | pbcopy
```

You can also select multiple fields, something like: 
```
yabai -m query --windows --window | jq -r '"\(.app) - \(.title)"'
```
