### ISSUE TITLE
Make -m window --focus iterative

### ISSUE THREAD

**Issue by oleksii-haponiuk** [koekeishiya/yabai#639]
I can't afford having 4 (or even 2 with `next` and `prev`) keys just to focus windows. I'd like it to be iterative so that when it reaches last window, it starts again. This way I'll be able to use just `--focus next` to focus all the windows in current space. Actually it's a built-in feature in OS X (Keyboard -> Shortcuts -> Keyboard -> Move focus to active or next window), but it's clunky, I suppose because of "active" part, which means that sometimes if I move to some space and use this shortcut it returns me to the previous space.

**Comment by dominiklohmann** [comment]
yabai returns a non-zero exit code if a command failed, which you can use to implement wraparound:

```bash
# cycle forwards
yabai -m window next || yabai -m window first

# cycle backwards
yabai -m window prev || yabai -m window last
```

**Comment by kiryph** [comment]
In the code snippet of @dominiklohmann `--focus` is missing
```
# cycle forwards
yabai -m window --focus next || yabai -m window --focus first

# cycle backwards
yabai -m window --focus prev || yabai -m window --focus last
```
