### ISSUE TITLE
Question about setting rules

### ISSUE THREAD

**Issue by qhuyduong** [koekeishiya/yabai#64]
Hi.

I’m trying to set dedicated desktop for some apps as below:
```
yabai -m rule --add app=Emacs space=1
yabai -m rule --add app=iTerm space=2
yabai -m rule --add app=Slack space=3
yabai -m rule --add app=Google\ Chrome space=4
yabai -m rule --add app=Messages space=5
```
They seem to work fine at first. However after moving around for a while, some apps are in wrong order. Am i doing something wrong?

Thanks

**Comment by koekeishiya** [comment]
You have likely enabled the following macOS mission-control setting: http://osxdaily.com/2011/11/12/stop-spaces-rearranging-mac-os-x/

**Comment by qhuyduong** [comment]
@koekeishiya it's indeed! After disabling that option everything seems working fine. Thank you.
