### ISSUE TITLE
Switching to a different window when current one is in zoom-fullscreen mode

### ISSUE THREAD

**Issue by pshomov** [koekeishiya/yabai#642]
I am not quite certain what should be the correct behaviour since I do not have experience with other tiling window manager. However the current behaviour from yabai leaves the windows in a pretty weird way. Here is the scenario I am referring to in more detail:

I have a space configured for "bsp" layout. I have a couple of windows and I set the current one to "zoom-fullscreen". All is good but as soon as I tried to focus a window let's say 'west', the newly focused window shows up over the zoomed fullscreen one but stays in its original allocated size.

I think I would prefer if the newly focused window becomes zoom-fullscreen and all other windows that I navigate in this space until I toggle the zoom-fullscreen mode.
I am looking to "fix" this with signals and actions but I think it would make sense to make this a native feature.

**Comment by koekeishiya** [comment]
The current behaviour is working as intended, but certainly people might have a different preference for how it should work.
I think you might want to look into the *stack* layout introduced in the latest release instead of using *zoom-fullscreen* the way which you describe above.
