### ISSUE TITLE
[feature request] per-display space isolation

### ISSUE THREAD

**Issue by MIJOTHY** [koekeishiya/yabai#645]
Enjoying the WM. One thing I miss from my xmonad setup is having spaces logically isolated according to the display they are on: each display has its own set of spaces and doesn't know about the spaces on other displays. For example, spaces 7-12 on display 2 are treated as 1-6 on that display, and while that display is focused, no other spaces are considered.

Happy to give a PR a shot if you think this sort of thing would be worthwhile. It's possible with some jq wrangling, but not very nice or performant. My initial thought is to have a config setting that defines this behaviour by default globally. Thoughts?

**Comment by 24unix** [comment]
I really like that idea.

I have three monitors (displays), and ended up having 24 spaces when I had to enable "Displays have separate spaces" for Yabai.

But I really handle it as 8 desktops, each desktop includes all three displays.

**Comment by koekeishiya** [comment]
I am not really interested in doing this, primarily because it would not work well with the current API design.
Every command can be issued at runtime and so *all* commands that act on spaces will no longer be able to target spaces outside of the focused monitor, which will break configuration options.

It would be possible to separate that, but it complicates the system in both code and mental capacity required to use it effectively.

**Comment by hb0nes** [comment]
> Enjoying the WM. One thing I miss from my xmonad setup is having spaces logically isolated according to the display they are on: each display has its own set of spaces and doesn't know about the spaces on other displays. For example, spaces 7-12 on display 2 are treated as 1-6 on that display, and while that display is focused, no other spaces are considered.
> 
> Happy to give a PR a shot if you think this sort of thing would be worthwhile. It's possible with some jq wrangling, but not very nice or performant. My initial thought is to have a config setting that defines this behaviour by default globally. Thoughts?

Did you find a workaround for this?
Who the f can manage 24 spaces, I have the same problem.

Coming from dwm, this is a pain to deal with on Mac.

**Comment by koekeishiya** [comment]
@hb0nes 

You can use the query system to to target the x'th space of a display of your choosing (e.g the focused display, the display that the cursor is on or whatever). See my comment here: https://github.com/koekeishiya/yabai/issues/670#issuecomment-698871253
