### ISSUE TITLE
[Question] Help with un-managing Firefox Nightly update window with no title

### ISSUE THREAD

**Issue by muhammad-saleh** [koekeishiya/yabai#647]
Hi,
Thank you for creating Yabai and thank you for your great efforts.

I need your help please with un-managing the Firefox Nightly update window, it has no title.

I have this rule in my `yabairc` file but it doesn't work, Could someone please tell me what do I need to change to get the update window to float?

This window is what's shown when you check for updates in Firefox Nightly.

Thank you 🙏 

```
yabai -m rule --add app="^Firefox*" title="" manage=off
```

<img width="662" alt="image" src="https://user-images.githubusercontent.com/1510608/91291719-bfaab300-e795-11ea-80a8-15a9726a3d94.png">

**Comment by yanzhang0219** [comment]
Open this update window and a terminal in the same workspace. Then try to run `yabai -m query --windows --space` in the terminal. You can get the information about both windows in the current workspace. Then you could find the actual name and title of this firefox update window.

**Comment by muhammad-saleh** [comment]
@yanzhang0219 That's what I got for this window:

```json
{
	"id":665,
	"pid":3296,
	"app":"Firefox Nightly",
	"title":"",
	"frame":{
		"x":753.0000,
		"y":28.0000,
		"w":654.0000,
		"h":365.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":0,
	"display":1,
	"space":1,
	"visible":1,
	"focused":0,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},
```

**Comment by yanzhang0219** [comment]
Try this yabai rule `yabai -m rule --add app="Firefox Nightly" title="" manage=off` to see whether it works?

**Comment by muhammad-saleh** [comment]
@yanzhang0219 It didn't work unfortunately! Is there a way to validate that this rule is loaded?

**Comment by yanzhang0219** [comment]
`yabai -m rule --list` will list all registered rules.

**Comment by muhammad-saleh** [comment]
@yanzhang0219 interesting... if the rule has `title=""` it's not loaded and if I removed the title from the rule, the rule will be loaded but this will make the whole app float

**Comment by muhammad-saleh** [comment]
Maybe there should be a unique value/identifier for either managing/un-managing all app windows or a unique identifier for empty titles, something like `title="[EMPTY]"`

**Comment by dominiklohmann** [comment]
You gotta use `title='^$'` for the empty title. The empty string matches _every_ title, but `^$` matches only entirely empty titles (`^` refers to the start of the line, `$` refers to the end of the line).

**Comment by muhammad-saleh** [comment]
@dominiklohmann Works! Thank you both a lot!

**Comment by yanzhang0219** [comment]
Wow. Interesting! I don't know this before. Thank you @dominiklohmann
