### ISSUE TITLE
Allow windows to opened in reverse

### ISSUE THREAD

**Issue by uri** [koekeishiya/yabai#65]
It would be nice if there was an option to reverse the tree. For example when opening a new window it would appear on the left instead of right. Or if the screen is more tall than it is narrow to open the new window above instead of bellow.

**Comment by koekeishiya** [comment]
Implemented on master.

New config *window_placement*, e.g:

```
# spawns to the left if vertical split, or top if horizontal split
yabai -m config window_placement first_child

# spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
```

**Comment by uri** [comment]
Works great!
