### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by 24unix** [koekeishiya/yabai#650]
I really like Yabai more and more. Thanks for the great programm.

But I've got one problem: My windows are semi transparent, when I take a screenshot, only the background image ist captured, not the window.

There a was around that?

Kind regards,
  Micha

**Comment by koekeishiya** [comment]
How exactly do you capture the screenshot? Works fine for me on Catalina 10.15.6.

**Comment by 24unix** [comment]
Oh, sorry, didn't get a notification about the reply.

Usually I take screenshot with a little menubar app I wrote, it's basically a frontend for the screencapture command.
But I've got the same effect when using shift-apple-4.

I'm currently also on 10.15.6.

**Comment by 24unix** [comment]
Just found it out by fortune, the problem was not related to Yabai, it was a permission problem.

I bought a new iMac 2020, set it up from Timemachine, and, well, somehow there was a missing entry.

For other people with the same problem, here's how to fix:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/36622631/94713507-2ac64700-034b-11eb-9de7-1593f5d0fe03.png">
