### ISSUE TITLE
Focus space while grabbing window with mouse

### ISSUE THREAD

**Issue by TheNoim** [koekeishiya/yabai#653]
Hi,

Recently I noticed a thing which bothers me with yabai. Often I grab a window with my mouse and then press a shortcut to focus the next space. The current behaviour is that yabai will change the space and move the window. This is fine. However, if some other window is on the next space then the current window grabbed by the mouse isn't in focus anymore. 

I made a quick screen record to demonstrate the issue: 

![yabai issue](https://user-images.githubusercontent.com/5133056/92147988-2c6c2000-ee1c-11ea-8da2-cbedb3601eaa.gif)

Is there any way to change this?

Thank you in advance :)

**Comment by koekeishiya** [comment]
I don't think this is something that can be fixed, at least I currently have no idea how to do so. This behaviour is not something that is implemented in yabai. If I switch spaces using mission-control shortcuts while grabbing a window with the mouse it will be moved to the target display as you show with yabai, but in this case it actually keeps focus. I'm not sure why it would lose focus when using yabai, as we fall back to macOS' behaviour for deciding which application/window becomes the focused window after a space change.

**Comment by TheNoim** [comment]
The thing is, I could implement a workaround if I would be able to check whether a window is currently grabbed with the mouse. Then when I focus the new space I could focus the window again. 

Somehow TotalSpaces2 implements it. Sadly it is not open source. I am not sure if there is any way to re this.

**Comment by koekeishiya** [comment]
Yabai already tracks when the user grabs/drags a window, so the workaround you describe would be fairly trivial to implement (internally in the codebase), but I would rather try to investigate the core issue and see if it can be resolved, instead of re-focusing the grabbed window after the space change occur.

**Comment by TheNoim** [comment]
> Yabai already tracks when the user grabs/drags a window, so the workaround you describe would be fairly trivial to implement (internally in the codebase)

Could you at least expose this or point me where in the code you already tracking it? Tried to find it by myself without luck. 

Btw, I tried to find out how TS2 works and I think they move the window by themself and keep the frontmost state. But I am not experienced enough to reverse there system.

**Comment by TheNoim** [comment]
I understand that it is better to find the underlying core issue. However, if there is no fix in the near future, I would suggest implementing a workaround first.

**Comment by koekeishiya** [comment]
If you want to add a workaround locally, simply add the following below this line: https://github.com/koekeishiya/yabai/blob/master/src/space_manager.c#L641

```
if (g_mouse_state.window) window_manager_focus_window_with_raise(&g_mouse_state.window->application->psn, g_mouse_state.window->id, g_mouse_state.window->ref);
```

Probably also need to forward declare the variable at the top of the file: https://github.com/koekeishiya/yabai/blob/master/src/space_manager.c#L3
```
extern struct mouse_state g_mouse_state;
```

**Comment by TheNoim** [comment]
This works really well. Thanks.

**Comment by koekeishiya** [comment]
Right.. undo those changes and try to add the following here https://github.com/koekeishiya/yabai/blob/master/src/event.c#L553
```
if (g_mouse_state.window) window_manager_focus_window_with_raise(&g_mouse_state.window->application->psn, g_mouse_state.window->id, g_mouse_state.window->ref);
```

This might have some unintended sideeffects if you use the mouse-actions functionality provided through yabai.
Personally I don't rely on this weird click & hold window to move it to a different space. There are yabai commands for that, that can be used in combination with the focus space commands. You could also just make a shell script that returns the window currently below the cursor and then moves it to a space and also focuses the space.

**Comment by TheNoim** [comment]
This has a higher success rate. But wouldn't it be easier if I just could query the current state?

For example: 

```patch
$ yabai -m query --windows --window mouse
{
	"id":1489,
	"pid":1456,
	"app":"iTerm2",
	"title":"fzf",
	"frame":{
		"x":164.0000,
		"y":69.0000,
		"w":1180.0000,
		"h":654.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":3,
	"visible":1,
	"focused":1,
	"split":"none",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
-	"native-fullscreen":0
+       "native-fullscreen":0,
+       "grabbed": true
}
```

Then I would move the window first with a script and then switch space. Maybe this would even be useful for others and not just me.

**Comment by TheNoim** [comment]
I really would like to see a solution for this. Especially because TotalSpaces is deprecated :)

**Comment by TheNoim** [comment]
Ok, it wasn't that hard:

```patch
Index: src/window.c
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/window.c b/src/window.c
--- a/src/window.c	(revision 8777db43b8551e0bc4e5c55d1e15bcbed52501a1)
+++ b/src/window.c	(date 1623664333715)
@@ -143,6 +143,14 @@
     bool zoom_fullscreen = node && node->zoom && node->zoom == view->root;
     int stack_index = node && node->window_count > 1 ? window_node_index_of_window(node, window->id)+1 : 0;
 
+    bool grabbed = false;
+
+    if (g_mouse_state.window) {
+        if (g_mouse_state.window->id == window->id) {
+            grabbed = true;
+        }
+    }
+
     fprintf(rsp,
             "{\n"
             "\t\"id\":%d,\n"
@@ -170,6 +178,7 @@
             "\t\"stack-index\":%d,\n"
             "\t\"zoom-parent\":%d,\n"
             "\t\"zoom-fullscreen\":%d,\n"
+            "\t\"grabbed\":%d,\n"
             "\t\"native-fullscreen\":%d\n"
             "}",
             window->id,
@@ -198,6 +207,7 @@
             stack_index,
             zoom_parent,
             zoom_fullscreen,
+            grabbed,
             window_is_fullscreen(window));
 }
 
Index: src/window.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/window.h b/src/window.h
--- a/src/window.h	(revision 8777db43b8551e0bc4e5c55d1e15bcbed52501a1)
+++ b/src/window.h	(date 1623664296379)
@@ -1,6 +1,8 @@
 #ifndef WINDOW_H
 #define WINDOW_H
 
+extern struct mouse_state g_mouse_state;
+
 const CFStringRef kAXFullscreenAttribute = CFSTR("AXFullScreen");
 
 #define AX_WINDOW_MINIMIZED_INDEX      0

```

Can I do a pr for this, or is something wrong with this code?
