### ISSUE TITLE
Borders not replaced for minimised windows

### ISSUE THREAD

**Issue by d-miketa** [koekeishiya/yabai#654]
Say I have two Safari windows open, one shown and the other hidden, and restart Yabai with border replacement turned on. The visible window will have a border while the hidden one will keep its original MacOS decorations. The problem is resolved for an individual window if Yabai is restarted while the window in question is visible.

**Comment by koekeishiya** [comment]
I can reproduce the issue. After I have deminimized the window (that did not get a border), and move it around by dragging its titlebar, the border will appear.

**Comment by koekeishiya** [comment]
This was fixed in v4.0.0.
