### ISSUE TITLE
PIP windows: possible to turn off borders?

### ISSUE THREAD

**Issue by malkomalko** [koekeishiya/yabai#655]
My config has window borders set and I find it quite distracting when I put a window into `pip` mode to have the border shown around the window.  It also draws the border incorrectly so I a large rectangle border around the pip window.

Thoughts?

**Comment by atidyshirt** [comment]
could you do something like this? (I don't use the PIP thing in yabai but this is how I do picture in picture)

```
 alt - p : yabai -m window --toggle sticky;\
           yabai -m window --toggle border; \
           yabai -m window --grid 4:1:4:4:0:0
```

**Comment by malkomalko** [comment]
This is perfect!
