### ISSUE TITLE
too many space in bottom

### ISSUE THREAD

**Issue by windwp** [koekeishiya/yabai#656]
1. the space of the bottom in my window is too big? I don't use any bar and dock but it still too big compare to space in the top.

![image](https://i.imgur.com/lgFzYwj.png)

2. i use that command `yabai -m window --close` to close but it can't focus the next window after close and if you open dock they still have icon on that app.

**Comment by yanzhang0219** [comment]
If you're using iTerm2, refer to this https://github.com/koekeishiya/yabai/issues/651#issuecomment-683421896
