### ISSUE TITLE
skhd functionality missing for some time?

### ISSUE THREAD

**Issue by rhpittman314** [koekeishiya/yabai#659]
Will skhd functionality return for yabai? I found it very easy to config in the same way as setting rules in yabai. It was handy to have, but for the past several versions of yabai, it seems to have stopped working.
Was something affected in an upgrade that I should be changing to have this kind of functionality restored? Or are there plans to enable this in the future? Thanks in advance.

**Comment by koekeishiya** [comment]
Nothing has changed; the architecture is the same as it has been since the very beginning. skhd is probably just not running correctly on your system for some reason. You should take a look here: https://github.com/koekeishiya/skhd/issues/48

**Comment by rhpittman314** [comment]
The issue was an outdated payload addition.
My mistake, I tend to leave my monitor on my laptop turned off to avoid further "burning" of the monitor, and since the notification telling me the payload was outdated was on the screen that was turned off, I kept missing it. Will keep this in mind for future updates. Thanks!
