### ISSUE TITLE
Add mouse option to WINDOW_SEL

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#66]
### Proposal

Add a ~`cursor`~ `mouse` option to `WINDOW_SEL`, so that the focus, swap and warp window commands can interact with the window under the ~cursor~ mouse. 

This is mostly useful with ffm disabled, but focusing the window under the ~cursor~ mouse may also be useful on some signals, e.g. `window_destroyed`.

**Comment by koekeishiya** [comment]
Does *mouse*, *cursor* or *pointer* make the most sense? I personally find *cursor* / *pointer* to be better than *mouse*, but considering the other options use *mouse*, would it be better to use that here as well, for consistency?

**Comment by dominiklohmann** [comment]
Mouse is probably better for consistency, while cursor would be technically more correct. 

So mouse it is, because consistency in the command line interface is important.

**Comment by koekeishiya** [comment]
New value added to the definition of *WINDOW_SEL*: *mouse*.

`yabai -m window --focus mouse`

**Comment by dominiklohmann** [comment]
Awesome. Added it to the wiki already. 

I've now been using the below snippet for 5 minutes and love it already. Fixes issues with closing floating windows quite smoothly in my opinion.

```sh
yabai -m signal --add event=window_destroyed \
        action="yabai -m window --focus mouse"
```

**Comment by koekeishiya** [comment]
This *signal* system actually has way more potential than I originally realized during its development, especially considering how easy it was to implement. Overall I am much more satisfied with how *yabai* is structured / organized than I ever was with chunkwm. Guess third time's the charm.

**Comment by dominiklohmann** [comment]
Yeah, I've recently realised that I can just split my config into multiple files and reload selected files on certain signals. This has made my setup so much better, it's almost unreal. Gotta publish my dotfiles sometime to show off all these scripts I made already.

**Comment by pcr910303** [comment]
@dominiklohmann Wow the lazy-load of config is a great idea! What about making a ‘Tips & Tricks’ in a wiki and adding some config ideas... (especially ones that use signals)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
