### ISSUE TITLE
Not managed applications not returning focus anywhere after being closed

### ISSUE THREAD

**Issue by ArtemM** [koekeishiya/yabai#662]
I've installed toggl and added rule to not manage it by adding to configuration:
`yabai -m rule --add label="Toggl Track" app="^Toggl Track$" title="^Toggl Track$" manage=off`
That seems to work (toggl window is not arranged automatically) but when I activate toggle and then deactivate it either by shortcut or by clicking "x" focus does not return to the previous window. Navigating north/south/west/east does not bring window focus back (nothing happens visually). Logs saying that Yabai tries to do a switch (likely because there is no "current" window commands fail:
```
EVENT_HANDLER_DAEMON_MESSAGE: window --focus west
EVENT_HANDLER_DAEMON_MESSAGE: window --focus east
EVENT_HANDLER_DAEMON_MESSAGE: window --focus north
EVENT_HANDLER_DAEMON_MESSAGE: window --focus south
```
 Switching to another space or clicking on window with mouse reactivates focus.  

Relevant log part (toggl activated and deactivated, nothing happens afterward):
```
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: Toggl Track (93083)
EVENT_HANDLER_APPLICATION_DEACTIVATED: iTerm2
EVENT_HANDLER_APPLICATION_ACTIVATED: Toggl Track
window_manager_create_and_add_window: Toggl Track 66273
EVENT_HANDLER_WINDOW_FOCUSED: Toggl Track 66273
EVENT_HANDLER_DISPLAY_CHANGED: 459140280 7
window_manager_create_and_add_window: ignoring AXUnknown window Steam 2735
window_manager_create_and_add_window: ignoring AXUnknown window Finder 58458
window_manager_create_and_add_window: ignoring AXUnknown window Finder 58460
EVENT_HANDLER_WINDOW_FOCUSED: Toggl Track 66273
EVENT_HANDLER_WINDOW_DESTROYED: Toggl Track 66273
```
Checked with Activity Monitor and it shows the same behavior.
ENV:
MacOS Catalina 10.15.6

**Comment by koekeishiya** [comment]
This is a macOS issue. yabai does not override focus in any way unless a focus command is initiated by the user.
I don't think there is much that can be done here from our pov.
