### ISSUE TITLE
focus next/focus first doesn't work when in Fullscreen mode

### ISSUE THREAD

**Issue by stylerw** [koekeishiya/yabai#665]
So, I appreciate very much the addition of stacked mode for smaller screens and to allow temporary fullscreening of apps.  One minor frustration though is that stacked mode appears to not respect the existing 'Next/Previous/First window' commands.  That is... `/usr/local/bin/yabai window --focus next` doesn't move me to the next stacked window, and `/usr/local/bin/yabai -m window --focus first` doesn't move to the first on the tree.  I see that there is a list of `focus stack.XXX` commands in https://github.com/koekeishiya/yabai/issues/337, but it confused me that the generic commands don't work in Fullscreen mode.

This is a little detail, but having a unified command would make it easier to bind a single key which would mean 'Next window' no matter your mode (e.g. I have Hyper+Space bound to `/usr/local/bin/yabai window --focus next || /usr/local/bin/yabai -m window --focus first`).

**Comment by koekeishiya** [comment]
This is done deliberately as the stack layout uses the bsp-stacking  mechanism as its backing implementation. No plans to try and unify these yet at least.

**Comment by stylerw** [comment]
I understand that, but perhaps there could be a command that checks the method of window arrangement, and gives you 'Focus on next' regardless?  This is useful for folks who use both small and large screens.

**Comment by koekeishiya** [comment]
If I understand you correctly, the following should work fine:
```hype - space : (yabai -m window --focus stack.next || yabai -m window --focus next) || (yabai -m window --focus stack.first || yabai -m window --focus first)```

**Comment by stylerw** [comment]
Hm, although that works as expected for stacked windows and can cycle continuously through windows in stacked mode, that doesn't seem to continuously cycle through in non-stacked layouts, it cycles through most of the windows and then stops, never returning.
