### ISSUE TITLE
Layout Issue with balloon/hover text

### ISSUE THREAD

**Issue by 10zero11** [koekeishiya/yabai#666]
I'm not sure how to correctly refer to this, however;

I've noticed this most aggressively in Skype for Business but other apps also.
 
If my mouse pointer hovers over some ui element like 'Chats' in the side bar menu, a small blue box pops up next to the mouse pointer with some 'help text'.

As soon as this occurs, the active application is divided by the layout manager 'bsp' style and tries to move the hover text to that allocated region.

The hover text disappears and then attempts to render the new window.
The new window then disappears and then the parent resizes to recover the region.
Then the hover text re-appears.

This creates a loop of flickering between the various steps.

Anyone know how I might get yabai's layout manager to ignore this?

I can't capture a screen shot as the behaviour stops as soon as the screenshot tool is executed.
thanks,
d

**Comment by dominiklohmann** [comment]
> I can't capture a screen shot as the behaviour stops as soon as the screenshot tool is executed.

You can run something like `sleep 3 && yabai -m query --windows` to get information about the window that yabai is falsely recognizing. That leaves you 3 seconds (adjust as you like) to reproduce the state after running the command.

You can then use the rule system to ignore the desired window.

**Comment by 10zero11** [comment]
I was unable to capture with 'sleep 3 && yabai -m query --windows' or similar. The yabai -m query seems to disturb the rendering loop.

what I did capture is in the below attached images by running yabai in --verbose mode in a console.

The point of significance is;
'window_manager_create_and_add_window' followed immediately by
'EVENT_HANDLER_WINDOW_DESTROYED'

<img width="702" alt="out2" src="https://user-images.githubusercontent.com/4876476/94223702-fbbb6a00-ff33-11ea-98b5-267d8acd0a9f.png">

<img width="681" alt="sk1" src="https://user-images.githubusercontent.com/4876476/94223678-f2320200-ff33-11ea-83ac-9632210c10f0.png">

Unfortunately, the window number is unique each time the application is executed.

Anyone have any cool ideas?

thanks,
d

**Comment by int3rrupt** [comment]
I have the same issue with Outlook and Teams. So it looks like it's only caused by Microsoft products. They must be implementing tool tips in a non-standard way.

**Comment by int3rrupt** [comment]
I was able to sleep the query for 1s multiple times until I got a hit:
```json
[{
	"id":159174,
	"pid":51965,
	"app":"Microsoft Outlook",
	"title":"",
	"frame":{
		"x":532.0000,
		"y":140.0000,
		"w":279.0000,
		"h":19.0000
	},
	"level":103,
	"role":"AXHelpTag",
	"subrole":"",
	"movable":1,
	"resizable":0,
	"display":1,
	"space":5,
	"visible":1,
	"focused":0,
	"split":"none",
	"floating":1,
	"sticky":1,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
},{
	"id":159163,
	"pid":51965,
	"app":"Microsoft Outlook",
	"title":"Inbox • me@mydomain",
	"frame":{
		"x":20.0000,
		"y":42.0000,
		"w":2520.0000,
		"h":1378.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":6,
	"visible":1,
	"focused":1,
	"split":"none",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":1,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}]
```

I already have a rule the following rules for Outlook but they don't seem to resolve this particular issue:
```bash
yabai -m rule --add app="Microsoft Outlook" \
    manage=off
yabai -m rule --add app="Microsoft Outlook" \
    title="" \
    manage=off
yabai -m rule --add app="Microsoft Outlook" \
    title="^Inbox.*" \
    manage=on \
    space=2
yabai -m rule --add app="Microsoft Outlook" \
    title=".* Reminders" \
    sticky=on \
    opacity=1 \
    manage=off \
    border=off
```

Since I don't see anything for `role` in the Rules Docs, maybe the code has to change in order to ignore events relating to `"role":"AXHelpTag"`

**Comment by int3rrupt** [comment]
@10zero11, you should be able to use
```bash
yabai -m rule --add app="^Microsoft Outlook$" \
    title!="^(Calendar|Inbox)" \
    manage=off
```

This fixed the issue for me. For more info: #396 
You should be able to set something similar for Skype.
