### ISSUE TITLE
iTerm2 window ignored on first launch on application

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#67]
### Bug

This video shows me pressing my hotkey for opening a new iTerm2 window twice. Notice how the first window is not recognised by yabai. `EVENT_HANDLER_APPLICATION_LAUNCHED` fires very often very quickly here.

Screen recording: https://streamable.com/75mst

The apple script in question:

```osascript
try  
	tell application id "com.googlecode.iTerm2"
		set status to create window with default profile command ""
	end tell
on error
	tell application id "com.googlecode.iTerm2"
		activate
	end tell
end try
```

I compile the script using `osacompile` to improve the execution speed and then run it using `osascript /path/to/compiled/script.scpt`.

**Comment by koekeishiya** [comment]
So the *spam* for application launched is that we periodically retry *observing* the application given that the returned error code basically tells us to *try again later*. That is normal behaviour.

What I find interesting is that the weird *application_hidden* event that follows, which is almost immediately followed by an *application_visible* event. Weird. Does this happen if you simply launch a new instance of iTerm through e.g Spotlight/Alfred ?

**Comment by dominiklohmann** [comment]
Simply launching iTerm does not open any windows for me because of this setting. 

![image](https://user-images.githubusercontent.com/4488655/60052294-28e7ef80-96d5-11e9-8d0d-03210d88bad4.png)

When I change the setting to the default value, iTerm2 spawns both a normally tiled and an ignored window when opened through my script. Opening iTerm2 normally with the setting changed to default works as expected.

I cannot leave this setting at the default value because I want my script to only ever spawn one window of iTerm2, even if the application was not previously opened. Relying on the exit code of the script and using `/usr/bin/open`  as a fallback instead of the `on error` block is visibly slower.

**Comment by koekeishiya** [comment]
This is so weird, your script seemingly works just fine for me with the same settings: https://streamable.com/fjqda

I also attempted this multiple times with *window_border off*, and had the same result.

**Comment by dominiklohmann** [comment]
I really have no clue what causes this behaviour. Weirdly enough running the script in Script Editor works for me, it's just when I execute it using `osascript` that it bugs out. Will leave this open for now and investigate this more later on.

**Comment by dominiklohmann** [comment]
So the underlying issue here is that spawning the first iTerm2 window like this does not cause a window_created notification somehow. 

The following AppleScript does, however, so I consider this issue fixed. I still do not know why this happens and I can reproduce it 100% with the above script, but this is no issue with yabai I think.

```applescript
tell application id "com.apple.SystemEvents"
  set IS_RUNNING to count (processes whose name is "iTerm2")
end tell

tell application id "com.googlecode.iTerm2"
  if IS_RUNNING > 0 then
    try  
      create window with default profile command ""
    on error
      activate
      create window with default profile command ""
    end try
  else
    activate
    create window with default profile command ""
  end if
end tell
```

Closing this.

**Comment by koekeishiya** [comment]
Removing the bug label as per your conclusion.
