### ISSUE TITLE
Switch space on currently focused monitor

### ISSUE THREAD

**Issue by patrick91** [koekeishiya/yabai#670]
Hi, this is more of a question. I was wondering if it is possible to tell yabai to switch space based on where the mouse is?

I have two monitors and I want to be able to use a shortcut to switch spaces based on where the mouse, like this:

```
yabai -m space --focus 2 --display mouse
```

Unfortunately `--display mouse` seems to move the mouse in the second space

Is something like this possible?

**Comment by koekeishiya** [comment]
The following will focus the 2nd space on the display that has the mouse cursor.
```
yabai -m space --focus $(yabai -m query --displays --display mouse | jq -r '.spaces[1]') 
```

The above will query information of the display that currently holds the mouse cursor, select the spaces list and return the value in the specified index of the array. The unfiltered output looks like this:
```
~ yabai -m query --displays --display mouse                                                                                                                                                     
{
        "id":69731904,
        "uuid":"F466F621-B5FA-04A0-0800-CFA6C258DECD",
        "index":1,
        "spaces":[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "frame":{
                "x":0.0000,
                "y":0.0000,
                "w":1440.0000,
                "h":900.0000
}
```

**Comment by patrick91** [comment]
That's awesome, thank you! Works pretty well!
