### ISSUE TITLE
Question: How can I change the display index order?

### ISSUE THREAD

**Issue by aca** [koekeishiya/yabai#673]
This is probably question not for yabai but for mac.
If I set a monitor like this Display order (this order) is set like this 1, 3, 2.
![image](https://user-images.githubusercontent.com/50316549/94374518-c5eecf00-0147-11eb-9827-52d34fa4d342.png)

Is it possible to change the display order to 1, 2, 3 just as display is aligned?

**Comment by yanzhang0219** [comment]
I think it is managed by macOS itself and nothing can be done on yabai side.

**Comment by koekeishiya** [comment]
There is no support in Yabai to do this. I am not familiar with tools to change.
