### ISSUE TITLE
Question: is it possible to auto-stack new windows?

### ISSUE THREAD

**Issue by alextremblay** [koekeishiya/yabai#674]
Hello,

Fisrt off, that you for making yabai and being so incredibly helpful to those who use it. it's appreciated :)

Is it possible to configure (on a per-space basis or globally) a rule like `yabai -m window --insert stack`, so that new windows created in that space automatically stack onto the most recent window?

My use case is that I really like stacks, but i also really like bsp layout and the ability to have more than one stack in a given space.
If i set the layout of a space to `bsp`, i can have multiple stacks but all new windows cause splits
If i set the layout of a space to `stack`, all new windows stack, but it's no longer possible to split a stack and have multiple stacks

I'm stuck on this one. Any advice or direction would be greatly appreciated

**Comment by dominiklohmann** [comment]
You can cause the next insertion to happen in `stack` mode on the focused window whenever the focused window changes:

```
yabai -m signal --add event=window_focused action='yabai -m window $WINDOW_WINDOW_ID --insert stack'
```

You can hide the insertion overlay by setting the config option `insert_feedback_color`.

**Comment by alextremblay** [comment]
awesome, thank you!

That's almost perfect

The only time it fails is if you close a window and create a new one. I added 
```
yabai -m signal --add event=application_terminated action='yabai -m window --insert stack'
yabai -m signal --add event=window_destroyed action='yabai -m window --insert stack'
```
and now it's working great.

Thank you so much!

**Comment by pyinto** [comment]
@dominiklohmann is this still working for you? I experience some strange lags, sometimes window is added in stack, sometimes it doesn't

**Comment by pyinto** [comment]
> @alextremblay and @dominiklohmann thank you for this. It largely address what I was looking for. Would it be possible to modify this so that new windows are stacked only if there are currently 3 windows on the screen? I have a wide-screen and by default I prefer not to have more than three windows

Does this still work for you? Did you add anything else? I still see that windows sometimes open not in the stack.

**Comment by pyinto** [comment]
> awesome, thank you!
> 
> That's almost perfect
> 
> The only time it fails is if you close a window and create a new one. I added
> 
> ```
> yabai -m signal --add event=application_terminated action='yabai -m window --insert stack'
> yabai -m signal --add event=window_destroyed action='yabai -m window --insert stack'
> ```
> 
> and now it's working great.
> 
> Thank you so much!

Does this still work for you? Did you add anything else? I still see that windows sometimes open not in the stack.

**Comment by gennaro-tedesco** [comment]
I too see no effect in `bsp` layouts with the above configurations, namely new windows still open in a new tile (horizontal or vertical) rather than stack on the existing ones.

**Comment by KaKi87** [comment]
Hi,

Is it possible to do this only on a specific monitor, and keep the normal behavior on the other ones ?

Thanks
