### ISSUE TITLE
Menu bar application ignoring manage rule

### ISSUE THREAD

**Issue by piersolenski** [koekeishiya/yabai#676]
The [Fantastical](https://flexibits.com/fantastical) menu bar window exhibits the following behaviour when toggled, forcing other windows to recalculate:

![Kapture 2020-10-01 at 19 38 43](https://user-images.githubusercontent.com/1285419/94850770-587cc000-041f-11eb-8d56-f19d4819efdb.gif)

I've tried disabling it's management in the config file:

`yabai -m rule --add app="^Fantastical Helper$" manage=off topmost=on`

All my other menu bar applications work without any additional rules in the config file.

**Comment by yanzhang0219** [comment]
You're correct. You should use this yabai rule to make Fantastical behave properly.

**Comment by koekeishiya** [comment]
Are you sure the name you are matching against is correct? Use `yabai -m query --windows --space` to list all windows on the active space.

**Comment by superfunkminister** [comment]
It should be... This is the debug output for that window.

```json
{
  "id": 14770,
  "pid": 36874,
  "app": "Fantastical Helper",
  "title": "Fantastical",
  "frame": {
    "x": 1199,
    "y": 32,
    "w": 472,
    "h": 1012
  },
  "level": 26,
  "role": "AXWindow",
  "subrole": "AXStandardWindow",
  "movable": 1,
  "resizable": 1,
  "display": 1,
  "space": 2,
  "visible": 1,
  "focused": 1,
  "split": "none",
  "floating": 1,
  "sticky": 0,
  "minimized": 0,
  "topmost": 0,
  "opacity": 1,
  "shadow": 1,
  "border": 0,
  "stack-index": 0,
  "zoom-parent": 0,
  "zoom-fullscreen": 0,
  "native-fullscreen": 0
}
```

**Comment by yanzhang0219** [comment]
I put this `yabai -m rule --add app="Fantastical Helper" border=off manage=off` in my yabairc and it works well.

**Comment by superfunkminister** [comment]
Removing `topmost=on` seemed to fix the window resizing, however I have problems trying to right click anything in the Fantastical dropdown.
