### ISSUE TITLE
Can't create new space or focus to existing one.

### ISSUE THREAD

**Issue by ftpd** [koekeishiya/yabai#678]
Hi. I'm new to yabai, so let me start with thank you for such a great project.
I have almost everything I need, expect the two issues mentioned in title. I'm trying:
yabai -m space --create
which is not working. When I create a new space manually by clicking + in macOS menu, I can't do:
yabai -m space --focus 2.

I don't have any error message in /usr/local/var/log/yabai/yabai.error.log, just no reaction at all.

What am I doing wrong? I have yabai v3.3.0 from brew, SIP is disabled (completely).
Maybe it's because I'm running beta of Big Sur? Should I put this into #589 maybe?

**Comment by yanzhang0219** [comment]
Refer to and try https://github.com/koekeishiya/yabai/pull/677

**Comment by ftpd** [comment]
That's why I was asking about #589 - decided to create all those issues anyway, but I will continue there, thanks.
