### ISSUE TITLE
I can't install SA.

### ISSUE THREAD

**Issue by ftpd** [koekeishiya/yabai#679]
After:
sudo yabai --install-sa
my error.log is full of lines:
yabai: scripting-addition either failed to load or could not inject payload into Dock.app! Error: -609
(sometimes error number is -1712).

Often everything goes 'flashy' - my menubar (standard one) flashes, and background image changes into just solid dark for a second, it gets back to normal, flash, normal, flash... until I force brew services restart yabai.

What am I doing wrong? I have yabai v3.3.0 from brew, SIP is disabled (completely).
Maybe it's because I'm running beta of Big Sur? Should I put this into #589 maybe?

**Comment by yanzhang0219** [comment]
yabai for Big Sur is still under testing and developing, so it is very normal to have many issues and bugs. Don't pollute issues here. Please post all the issues related to Big Sur into #589. Then read #677 to get the progress of Big Sur adaption, and put all the concerns regarding this adaption into #677.

**Comment by ftpd** [comment]
That's why I was asking about #589 - decided to create all those issues anyway, but I will continue there, thanks.
