### ISSUE TITLE
How is moving windows with mod+lmouse supposed to work?

### ISSUE THREAD

**Issue by ftpd** [koekeishiya/yabai#680]
Im sorry, but I'm not getting this and there is no irc channel/usenet group/subreddit (or I haven't found it).
I have settings in my config file (it's the default one for now) that say I can move windows holding mod (fn) and l-mouse. Nothing happens when I do this, and resizing is working just fine. What I'm doing wrong here?

**Comment by ftpd** [comment]
Bonus question - I didn't want to create new issue for that: if I have two windows: A left, B right, what command should I use to move window B _below_ A (making A going wide)?

**Comment by yanzhang0219** [comment]
If you're running yabai under Big Sur, some issues maybe caused by Big Sur, not yabai itself. Please bear all issues regarding Big Sur until yabai's adaption is finished.

**Comment by ftpd** [comment]
I will close it as I did with all the others of mine - but 'bonus question' is not related to a version, so maybe I could get answer for it before closing?

**Comment by koekeishiya** [comment]
You can toggle the split mode using `yabai -m window --toggle split` or you can do something like `yabai -m window next --insert south && yabai -m window --toggle float && yabai -m window --toggle float`
