### ISSUE TITLE
Float window to its previous position (in tiling mode)

### ISSUE THREAD

**Issue by Sulfyderz** [koekeishiya/yabai#681]
Hello,

I have solved all my problems with old discussions but only one persists.

When I have a tiled window at a specific position (for instance at x: 20, y: 20 with w: 300 and h: 200), sometimes I do this (by using **skhd**):
```python
# float / unfloat window and center on screen
fn - t : yabai -m window --toggle float;\
          yabai -m window --grid 5:5:1:1:3:3
```

Well, when I use that shorcut again, my window is tiled again (that's OK !). But, unfortunately, it doesn't go back to its previous position with its previous size. I know a previous discussion talked about this but in the opposite direction (i.e. the old position of the floating window). Could someone help me ?

Best regards,

**Comment by koekeishiya** [comment]
Add the following script somewhere in your home folder, e.g: `~/Scripts/yabai_restore.sh` and make it executable: `chmod +x ~/Script/yabai_restore.sh`:

```
#!/usr/bin/env zsh

function store_window () {
    restore="$(yabai -m query --windows --window "${YABAI_WINDOW_ID}" |
    jq -re --arg YABAI_WINDOW_ID "${YABAI_WINDOW_ID}" '
        if .floating == 1 then
           .frame | "yabai -m window \($YABAI_WINDOW_ID) --move abs:\(.x):\(.y)\n"
               + "yabai -m window \($YABAI_WINDOW_ID) --resize abs:\(.w):\(.h)"
        else
            empty
        end')"
    if [[ ! -z "${restore}" ]]; then
        echo "${restore}" >"/tmp/yabai-restore/${YABAI_WINDOW_ID}.restore"
        chmod +x "/tmp/yabai-restore/${YABAI_WINDOW_ID}.restore"
    fi
}

() {
    rm -rf /tmp/yabai-restore
    mkdir /tmp/yabai-restore
    # The labels below are generated using `uuidgen` to ensure these signals never run more than once.
    yabai -m signal --add label='AA1BE1CD-6665-47B5-B5C4-111FBFFF0E1D' event=window_moved action="${functions[store_window]}"
    yabai -m signal --add label='91CC175D-9D33-4D48-9767-0FAF33E63209' event=window_resized action="${functions[store_window]}"
}
```

Then add the following to your yabairc:
```
# restore position of floating windows when they are manually unfloated
~/Scripts/yabai_restore.sh
```

Simply toggle float for a window as usual, using: `yabai -m window --toggle float`

Credits to @dominiklohmann for writing this solution and sharing it.

**Comment by Sulfyderz** [comment]
Hello,

Thank you, but it doesn't work. Don't worry, I'm used to use yabai without it.

Best regards,

**Comment by yanzhang0219** [comment]
Hi, 
You can refer to my script I am using: https://github.com/yanzhang0219/dotfiles/blob/master/.config/yabai/scripts/toggle-window-floating-tiling.sh. It works perfectly. It not only restores to the previous position but also the previous size. 

**To make it work**
**Step-1:**
First add the snippet below in your `yabairc` to make sure that each time yabai starts, the temporary folder will be recreated. 
```
tempDir=/tmp/yabai-tiling-floating-toggle
[ -d $tempDir ] && rm -rf $tempDir
mkdir $tempDir
```
**Step-2:**
Bind a key to this script like `alt - t : ~/.config/yabai/scripts/toggle-window-floating-tiling.sh`. 

DONE!

Demo below:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11582667/96374892-725e1880-112a-11eb-9728-7cb5ec67ebb9.gif)

P.S.:
Actually, I put the snippet in step-1 into another file [yabai/scripts/initialization](https://github.com/yanzhang0219/dotfiles/blob/master/.config/yabai/scripts/initialization.sh) and `source` this file in my [yabairc](https://github.com/yanzhang0219/dotfiles/blob/master/.config/yabai/yabairc). So the same effect will be achieved. 
You may observe that when I first switch a window to float, it doesn't retain its size and instead becomes floating with an appropriate size. This size varies according to the different sizes of the display (monitor). I calculate the size for each monitor in the initialization file. So the first time when you switch a window from bsp to float, it will have an appropriate size based on the monitor this window is in. 
(Very welcome to refer to my yabai config in my repo)

Thanks and hope this is helpful.

**Comment by ajayk-02** [comment]
> config

this works great for just one window 
is there a way to extend it to all windows at once when toggling between bsp and float @koekeishiya ? 😃
