### ISSUE TITLE
How to change the appearance of a stack window set

### ISSUE THREAD

**Issue by frek818** [koekeishiya/yabai#682]
Thanks you for the work you've put into this awesome piece of software. I've incorporated the stacking feature into my workflow. I also use active and inactive border colors. Are there any features that can make it obvious that a stack of windows is a stack? I started looking into targeting border color using a rule but it seems border color can only be changed based on the where a window is active or inactive.

**Comment by AdamWagner** [comment]
Hi @frek818 

There's a lot of good conversation on this in https://github.com/koekeishiya/yabai/issues/203.

Personally, I was inspired by the design proposed in this comment  https://github.com/koekeishiya/yabai/issues/203#issuecomment-652948362 and built a prototype to implement it: https://github.com/AdamWagner/stackline

This is the only option that I'm currently aware of… but I admit that I haven't really been looking for alternatives. If you end up trying it out, please let me know if you run into any trouble ;-)

**Comment by koekeishiya** [comment]
Currently no ETA for anything built-in here. See the above post for some potential solution.
