### ISSUE TITLE
How to fullscreen or no padding automatically when there's only one window?

### ISSUE THREAD

**Issue by Boltzmachine** [koekeishiya/yabai#688]
Maybe the answer is obvious, but I cannot find it in Wiki or other places.

**Comment by yanzhang0219** [comment]
Use `yabai -m window --toggle native-fullscreen`. Make sure the window has a title bar with the macOS native maximum button on it.

**Comment by Boltzmachine** [comment]
Oh, maybe I had some mistakes in the title. I mean I want automatically no gap or padding when there's only one window.

**Comment by yanzhang0219** [comment]
You should use yabai signal to implement it.

Adding this in your yabairc
```bash
yabai -m signal --add event=application_launched action="~/padding.sh"
yabai -m signal --add event=application_terminated action="~/padding.sh"

yabai -m signal --add event=window_created action="~/padding.sh"
yabai -m signal --add event=window_destroyed action="~/padding.sh"
```

Then under your home directory, create a `sh` script file name `~/padding.sh` by running `touch ~/padding.sh`. Next, make it executable by running `chmod +x ~/padding.sh`. Then, copy the code below into it.

```bash
#!/usr/bin/env bash

space_index=$(yabai -m query --spaces --space | jq .index)

check_padding=~/check_padding_$space_index

[[ ! -f $check_padding ]] && echo 1 > $check_padding

read padding <<< $(cat $check_padding)

[[ $(yabai -m query --windows --space | jq '.|length') -eq 1 ]] && [[ $padding -eq 1 ]] && yabai -m space --toggle padding && echo 0 > $check_padding

[[ $(yabai -m query --windows --space | jq '.|length') -gt 1 ]] && [[ $padding -eq 0 ]] && yabai -m space --toggle padding && echo 1 > $check_padding
```

Finally, restart your yabai service by running `launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"`

DONE!

Demo below:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11582667/95885163-cd120180-0d31-11eb-8888-b026860befaf.gif)

**Comment by Boltzmachine** [comment]
Wow, that's cool! thanks a lot. By the way, what's the terminal emulator you're using?

**Comment by Boltzmachine** [comment]
Wow, that's cool! thanks a lot!

**Comment by windowsrefund** [comment]
It seems this no longer works on Yabai v4.0.0
