### ISSUE TITLE
[BUG] Apps freeze when entering full screen

### ISSUE THREAD

**Issue by Luberry** [koekeishiya/yabai#690]
OS: MacOs 10.14.5
Yabai: yabai-v3.3.0

When I launch apps and expand to full screen with yabai running the apps end up freezing.
<img width="1680" alt="Screen Shot 2020-10-16 at 5 34 09 PM" src="https://user-images.githubusercontent.com/438520/96310853-2c903b80-0fd6-11eb-8a7a-2f2ae2b4653a.png">

**Comment by koekeishiya** [comment]
This used to be a bug on Catalina, that when fixed, apparently resurfaced on Mojave. There appears to be an API inconsistency between these two versions of macOS.

**Comment by Luberry** [comment]
@koekeishiya which version was this change made on so that I can revert to it for now. Really miss the tiling on my mac, and don't really want to upgrade to catalina rn.

**Comment by koekeishiya** [comment]
This commit: https://github.com/koekeishiya/yabai/commit/aae3b32ac20bf3501054233c6f032c39fed9bf18

**Comment by koekeishiya** [comment]
I don't have a machine running macOS Mojave so I cannot verify the latest changes. Can you try to run from the master branch and see if that solves your issue?

If you use brew:

```
brew uninstall yabai
brew install yabai --HEAD
```

**Comment by Luberry** [comment]
I actually just upgraded to catalina since some of my other apps were bugging out on mojave. if i have time ill downgrade the catalina vm i have chilling on one of my servers and test there.
