### ISSUE TITLE
Feature Request: DWM-like Tagging

### ISSUE THREAD

**Issue by RauschUndNot** [koekeishiya/yabai#691]
Would it be possible for `yabai` to support DWM-like tagging? (or does it already support something like this and I'm unaware?)

Every now and then I have a window or two that I would like to appear in more than one workspace. It'd be nice to say "I'd like to use this window in these spaces, and that one in those spaces" and to be able to do that. Thank you.

**Comment by koekeishiya** [comment]
This is technically possible to do, but it would require a fair bit of changes to the codebase.

**Comment by chaoxu** [comment]
If one can add any information to a window(say a label just like spaces) is helpful enough that scripts outside can do the management.

**Comment by koekeishiya** [comment]
You should be able to use the window id retrieved through the query system then, as it uniquely identifies the window.

**Comment by koekeishiya** [comment]
Closing as out of scope for this project.
