### ISSUE TITLE
Closing focused window should give focus to remaining window

### ISSUE THREAD

**Issue by danijar** [koekeishiya/yabai#692]
Steps to reproduce:
1. Enable the option that automatically focuses windows underneath the mouse cursor
2. Open two windows in tiling mode next to each other
3. Focus one of the windows and close it using a keyboard command

Actual result:
1. The focused window closes
2. The remaining window expands to fill the newly available space
3. No window is focused, even though the remaining window is underneath the cursor
4. To focus the remaining window, the mouse has to be moved by at least one pixel

Expected result:
1. The focused window closes
2. The remaining window expands to fill the newly available space
3. The remaining window gains focus automatically

It would be great if this reach for the mouse could be avoided.

Having the window underneath the cursor change without the mouse moving can happen not just when closing a window, but also when moving/resizing a window. I think the following behavior would be natural to the user and is also what i3 does:
- When closing a focused window, the remaining window that takes the space underneath the mouse cursor gains focus. This is the case that currently does not work.
- When resizing/moving a focused window, the window remains focused and the mouse cursor is set to the center location of the resized/moved window. This also applies when the focused window is resized/moved as the result of another window in the grid being resized/moved. I think this case already works correctly.

It could make sense to activate this behavior only when the option for the focus following the mouse cursor is enabled.

**Comment by koekeishiya** [comment]
You can use the following signals to automatically focus the window below the cursor after a window/application is closed.
```
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

```

**Comment by braham-snyder** [comment]
> You can use the following signals to automatically focus the window below the cursor after a window/application is closed.
> 
> ```
> yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
> yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
> ```

+1 on defaulting it. I liked the same thing on `chunkwm` for a few years, and I think this is common: https://github.com/koekeishiya/yabai/issues/485#issuecomment-617953545

search keywords: last application window refocus mouse_follows_focus mouse follows focus

**Comment by kaprests** [comment]
> You can use the following signals to automatically focus the window below the cursor after a window/application is closed.
> 
> ```
> yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
> yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
> ```

So glad I found this! I also really think it should be default behaviour, I mean when would you want to have no window in focus? I have only been on macos for about a week, but the lack of automatic focus on remaining window(s) was already driving me crazy.

**Comment by Chumion** [comment]
> You can use the following signals to automatically focus the window below the cursor after a window/application is closed.
> 
> ```
> yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
> yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
> ```

Not sure if this is still not the default in 7.1.5. I installed it yesterday and it auto-focused remaining windows for one day, but suddenly stopped working. I was about to give up using yabai before stumbling upon this. Thank you!

For anyone facing the same issue:

You have other options besides `mouse`, including but not limited to 'first', 'last', 'prev', 'next', and 'recent'. On my machine, all the relative ones ('next', 'prev', 'recent') failed, while the absolute ones worked perfectly.

**Comment by Bellavene** [comment]
A bit better solution for hammerspoon

```
wf = hs.window.filter
allwindows = wf.new(nil)
allwindows:subscribe({wf.windowDestroyed, wf.windowMinimized, wf.windowHidden}, function(window, appName, reason)
    local app = hs.application.frontmostApplication()
    local bundle = app:bundleID()
    local count = 0

    for k, v in pairs(app:visibleWindows()) do
            count = count + 1
    end

    if app:bundleID() == "com.apple.finder" then
        if count < 2 then
            app:activate(true)
            app:hide()
            return
        end
    elseif app:bundleID() == bundle then
        if count < 1 then
            app:activate(true)
            app:hide()
            return
        end
    end
end)

```
