### ISSUE TITLE
Dual keys for mouse_modifier 

### ISSUE THREAD

**Issue by rdewolff** [koekeishiya/yabai#693]
Is there a way to configure dual keys for `mouse_modifier` option in config?

Something like:

```
yabai -m config mouse_modifier               cmd+alt
```

**Comment by koekeishiya** [comment]
This is currently not possible; you can merge this PR locally if you want: https://github.com/koekeishiya/yabai/pull/596
I have other plans for how I want to solve this when I get started.

**Comment by rdewolff** [comment]
Am curious, what are ur plans? 

Thanks for the PR link.

**Comment by koekeishiya** [comment]
Uh, see #601
