### ISSUE TITLE
Dropdown menu bug (Things 3)

### ISSUE THREAD

**Issue by d-miketa** [koekeishiya/yabai#694]
In Things 3 (free trial available at [their website](https://culturedcode.com/things/)) a particular dropdown menu doesn't work with Yabai (SIP enabled) and the problem may appear elsewhere.

To reproduce this error, go to File > New Repeating To Do. An overlaid window appears:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/320321/96378485-2cce3980-1184-11eb-91c3-7046449f12b3.png">
The two dropdown menus (currently 'after completion' and 'week') hide a fraction of a second after I click on them and I can't interact with them using the keyboard either.

**Comment by montchr** [comment]
I've run into similar issues in other applications, including the Hot Corners popup within macOS System Preferences > Desktop & Screen Saver > Hot Corners:

![](https://p198.p4.n0.cdn.getcloudapp.com/items/5zuwQ90L/Screen%20Recording%202020-11-13%20at%2020.49.42.gif?v=8e42df0e7933b3a8ee29b19f751ce30c)

**Comment by koekeishiya** [comment]
Seems like this is an issue when `window_topmost` setting is enabled, yeah?

**Comment by kvndrsslr** [comment]
For me this bug was omnipresent in Big Sur. After reading this and disabling `window_topmost` dropdowns are behaving normally again.

**Comment by dominiklohmann** [comment]
This can be resolved with rules already, it's just a matter of configuration. Yabai should not hardcode exceptions for individual applications, that's what rules and signals are for after all. Closing this.

**Comment by d-miketa** [comment]
I don't understand this decision. It was demonstrated above that one particular setting of `window_topmost` breaks _a part of the Mac OS System Preferences app_ – hardly a generic individual application. (Incidentally the issue also affects Things 3, and if it were contained to that app, I'd agree with your assessment.) 

I understand rules as expressions of personal taste, not hacks necessary to restore basic system functionality. Clearly no one likes the behaviour in question, so it ought to qualify as an edge case which is currently improperly handled by `window_topmost on`.

**Comment by tami5** [comment]
Similar issue, with Xcode internal dialog are pushed back window_topmost on/off same issue

**Comment by brosasaki** [comment]
How does one properly "resolve this with rules"? Also, this definitely isn't an individual application thing. I get the same issue with the options search functions in Preferences and in iTerm2's settings menu, alongside scroll-lists; I suspect Yabai is currently breaking intended MacOS UI functionality (scroll-lists and options search pop-up elements should be on top). d-miketa is right, this is an unhandled edge case.
