### ISSUE TITLE
Find if a window is recently focused through yabai

### ISSUE THREAD

**Issue by chaoxu** [koekeishiya/yabai#695]
This information is stored somewhere, but unclear how to access it.
I don't think one can find it through query. 

Also some things lacking in the query is checking if a window is picture-in-picture.

**Comment by koekeishiya** [comment]
You can do `yabai -m query --windows --window recent`. yabai does not track full focus history.

**Comment by chaoxu** [comment]
Thank you.

Is that a new feature? The response when I run it is `could not locate the selected window.`

I'm running 10.15.7, and yabai 3.3.0.

**Comment by koekeishiya** [comment]
Not a new feature. That is the output when yabai determines that there was no recent window, or that the recent window is invalid (no longer exists).

**Comment by koekeishiya** [comment]
The query output will be refined in a future version, including things like pip if it doesn't get scrapped by then.
