### ISSUE TITLE
Kitty windows do not tile

### ISSUE THREAD

**Issue by poupas** [koekeishiya/yabai#696]
Hi,

I'm having an issue where all Kitty windows stay floated, regardless of any performed action (creating more windows, restarting Kitty, etc.).

Setup:
  * Using the default Kitty configuration.
  * Tiling is enabled by default, and this issue only happens with Kitty.

Output from `yabai -m query --windows --space`

```json
{
	"id":602,
	"pid":2833,
	"app":"kitty",
	"title":"bash",
	"frame":{
		"x":1272.0000,
		"y":368.0000,
		"w":717.0000,
		"h":443.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":4,
	"visible":1,
	"focused":0,
	"split":"none",
	"floating":1,
	"sticky":1,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":1,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}
```

Any help is appreciated!

Thanks

**Comment by jeroenbourgois** [comment]
@poupas what did you do to solve this? I am having the same issue.

**Comment by poupas** [comment]
@jeroenbourgois I switched to [Amethyst](https://github.com/ianyh/Amethyst). Probably not the answer you were expecting, sorry :)

**Comment by yanzhang0219** [comment]
Kitty performs perfectly on my end.

**Comment by jeroenbourgois** [comment]
> @jeroenbourgois I switched to [Amethyst](https://github.com/ianyh/Amethyst). Probably not the answer you were expecting, sorry :)

Reinstalled both, guess it will be Amethyst for me to then, sadly. Thanks for the input!

**Comment by jeroenbourgois** [comment]
@koekeishiya @poupas @yanzhang0219 solved it on my side, completely by accident. Decided to give it another try after a couple of weeks using iTerm. Apparently at some point I must have selected 'All Desktops' from the Dock app context menu for Kitty... wierd why I did this, spot this by accident just today after seeing Kitty was staying on top on every Space. I never used that context menu, ever, in all those years using MacOS. But after setting it to 'None' all was back to normal.

![image](https://user-images.githubusercontent.com/202312/108169026-7ad65800-70f8-11eb-91b9-6e63cd07db3c.png)
