### ISSUE TITLE
yabai -m space --focus - Stopped working

### ISSUE THREAD

**Issue by FinnFrotscher** [koekeishiya/yabai#697]
```
yabai -m space --focus [NUMBER]
```
this used to work until yesterday. Anything else works. Any ideas?

**Comment by yanzhang0219** [comment]
Restart yabai service or reboot your laptop.

**Comment by FinnFrotscher** [comment]
done and done. no change. updated and reinstalled aswell

**Comment by FinnFrotscher** [comment]
```
$ yabai -V                                              
> yabai: could not acquire lock-file! abort..
```
is there a way i can observe the logs, eventstream or something?
this is terribly annoying.

**Comment by koekeishiya** [comment]
What changed on your system? It doesnt just stop working for no reason. macOS update? Apple Service?

Try reinstalling the scripting addition. Also, see https://github.com/koekeishiya/yabai/wiki/Configuration#debug-output-and-error-reporting

**Comment by FinnFrotscher** [comment]
```
sudo yabai --uninstall-sa
sudo yabai --install-sa
```
Fixed it <3

**Comment by Sayrus** [comment]
Thanks a lot for documenting this ❤️ . Just had the issue and fixed it.

**Comment by emninger** [comment]
I have the same issue since i did the big sur upgrade. 

'sudo yabai --load-sa' solves it. But i have to do it any time i reboot the mac. Is there a way to add this command to the yabai start command?

Thanks a lot in advance

**Comment by koekeishiya** [comment]
I added some instructions in the wiki here: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

Just scroll down a bit, or ctrl+f Big Sur

**Comment by emninger** [comment]
Thanks!

**Comment by emninger** [comment]
I did like explained there, but i do not see any effect. If it is done correctly i should also be able to do, in a terminal 'sudo yabai --load-sa' without being asked for a password, correct?

Moreover, i'm wondering why the line in the yabai file in sudoers.d is
'<user> ALL = (root) NOPASSWD: /opt/local/bin/yabai --load-sa'
(when there is no /opt/local/... directory)

**Comment by koekeishiya** [comment]
```
# open/create a new file for writing using the vim editor (use nano or something if you are not familiar with vim)
sudo vim /private/etc/sudoers.d/yabai

# input the line below into the file you are editing.
# replace <user> with your username (output of whoami). 
# change the path to the yabai binary if necessary 
<user> ALL = (root) NOPASSWD: /opt/local/bin/yabai --load-sa
```
