### ISSUE TITLE
Ability to have padding when the layout is float mode

### ISSUE THREAD

**Issue by jaideeprana** [koekeishiya/yabai#699]
I'm using a status bar along with Yabai.
For most of my needs I have to use the float layout, however the problem with that is I don't get the paddings on the left, right, top and bottom.

The padding works perfectly as per the config in the yabairc file in bsp layout or tiling mode but not in float.

Is there a way to get it working in float mode as well?

**Comment by koekeishiya** [comment]
Not really sure what you are asking for here; using `yabai -m window --grid ..` to set the frame of floating windows will correctly obey the specified padding.

**Comment by jaideeprana** [comment]
This is what I expect in a float window layout:
<img width="1680" alt="Screenshot 2020-11-15 at 4 15 00 PM" src="https://user-images.githubusercontent.com/3875065/99182858-c2e28900-275d-11eb-8fd2-ee15a43fd6ac.png">

However, this what I'm getting currently:
<img width="1680" alt="Screenshot 2020-11-15 at 4 14 57 PM" src="https://user-images.githubusercontent.com/3875065/99182874-de4d9400-275d-11eb-954f-1d750c8f047b.png">

As you can see I want padding to be added in float window layout however I'm not able to find out a way to add it.

**Comment by koekeishiya** [comment]
This is not something that I want to add. The point of the float layout is to leave the space completely unmanaged. 
You can use the grid command as I mentioned earlier to position and resize floating windows, or windows that reside in a floating space. This command will obey the padding specified in the config, and should do what you want.

**Comment by zilahir** [comment]
@koekeishiya this is also what I was looking for. Still new to this, but is there I way to hook up a yobai command like in your examples, for example to `mouse_action2`. So when i am (full)resizing a window with double click, it would respect the padding so it wouldnt go over it? 

thank in advance!

**Comment by cagdassalur** [comment]
@zilahir I'm having the same issue right now, can you share your config please?
