### ISSUE TITLE
Implement next / prev / last and per-space wraparound for window focus / swap / warp operations

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#7]
Nit: this is really missing from my old chunkwm workflow. Used to toggle between two windows all the time with focus next + per-space wraparound. (It's kinda making me regret switching just before going to a conference right now because I keep trying to take notes without switching back to Vim.)

I can also create a PR implementing this feature, would probably get around to doing so sometime next week. I just figured a quick issue showing interest in this feature might not be a bad thing. Any thoughts?

**Comment by koekeishiya** [comment]
next / prev / last are definitely something I think should be available for the window focus, swap and warp commands, and I can probably do these today or tomorrow. I'm not sure if I am fully sold on wrapping yet, however, if they are to be done I'd like it to always wrap, or have it all be a single setting - so either wrap everything, or nothing.

**Comment by dominiklohmann** [comment]
> so either wrap everything, or nothing.

That's fine with me. Seems like an easier mental model than per-space wraparound anyways and the `last` selector already solves my swap back and forth problem for note-taking. 👍

**Comment by koekeishiya** [comment]
Closing this for now. Might revisit wrapping at a later point.
