### ISSUE TITLE
Notifications stop displaying as soon as the scripting addition is loaded

### ISSUE THREAD

**Issue by cmacrae** [koekeishiya/yabai#700]
**Description**
As the title states: it seems that notifications stop displaying as soon as the scripting addition loads.  
For instance, if I boot up fresh, and I have notifications lingering from the calendar/reminders/etc., they will show briefly. Then, as the scripting addition loads, all of them abruptly disappear and will not display as they arrive.  

I can still hear notification sounds, and they still show up in the 'Notifications' tab in the sidebar if I bring it up.  
If I kill the `NotificationCenter` process, it's automatically restarted by the daemon and the notifications re-appear for a short period of time... however, they soon dissapear again.

I get this issue on two separate systems (using the same version of yabai & the same config).  
I think it started with v3.3.0 - I run a Nix overlay for the `master` builds.

Please let me know if there's any further information I can provide for debugging.

**Config**
Here's the config I'm using
```
yabai -m config active_window_border_color 0xff00afaf
yabai -m config active_window_border_topmost off
yabai -m config active_window_opacity 1.0
yabai -m config auto_balance on
yabai -m config bottom_padding 10
yabai -m config external_bar all:0:26
yabai -m config focus_follows_mouse autoraise
yabai -m config layout bsp
yabai -m config left_padding 10
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_follows_focus off
yabai -m config mouse_modifier fn
yabai -m config normal_window_border_color 0xff505050
yabai -m config normal_window_opacity 1.0
yabai -m config right_padding 10
yabai -m config split_ratio 0.50
yabai -m config top_padding 10
yabai -m config window_border on
yabai -m config window_border_width 4
yabai -m config window_gap 10
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config window_placement second_child
yabai -m config window_shadow float
yabai -m config window_topmost on
# rules
yabai -m rule --add app='System Preferences' manage=off
yabai -m rule --add app='Live' manage=off
```

**Comment by koekeishiya** [comment]
Sounds weird; I'm not a heavy notifications user so it will probably be fixed sooner if someone would help get to the bottom of this. As far as I know, yabai is not doing anything out of the ordinary when triggering a notification: https://github.com/koekeishiya/yabai/blob/master/src/misc/notify.h#L30

**Comment by cmacrae** [comment]
I'm going to close this issue, as since upgrading to Big Sur, the problem seems to have disappeared
