### ISSUE TITLE
Toggle of native fullscreen not working with Alacritty+ window decorations:none

### ISSUE THREAD

**Issue by danielfalbo** [koekeishiya/yabai#701]
If I set in my [Alacritty](https://github.com/alacritty/alacritty) configuration file
```yml
window:
    decorations: none
```
and then I try to
```sh
yabai -m window --toggle native-fullscreen
```
on the Alacritty window, that does not work. Other Alacritty window decorations settings seem to work as they should

**Comment by yanzhang0219** [comment]
This is not an issue. 
Yabai cannot toggle a window native-fullscreen if the window does not have a title bar which has a maximum button on the top-left.

**Comment by danielfalbo** [comment]
Ok, thank you!
