### ISSUE TITLE
Suggestion: Better onboarding for accessibility permissions

### ISSUE THREAD

**Issue by issmirnov** [koekeishiya/yabai#703]
Hey @koekeishiya,

Whenever I install or upgrade yabai on a new machine, it's always an annoying dance with the accessibility settings + the endless popups requesting permissions.

I noticed that in https://github.com/dexterleng/vimac, there's a simple popup that shows up, and then auto-disappears when the permissions are granted. Perhaps it's worth looking at the code and potentially borrowing it? 

Hope this is useful.

**Comment by koekeishiya** [comment]
Agree that this is not the best experience during a first install. However, sequential upgrades should not require you to enable accessibility permission, as the released binaries are codesigned (unless mentioned in the changelog that it will require a permissions reset). If you build from source you need to manually codesign the binary.

**Comment by duckpuppy** [comment]
I have to redo the accessibility permissions every time yabai updates (skhd as well). It shows up as a new entry in the accessibility list. I delete the old one and check the new one.
