### ISSUE TITLE
Refer to space settings by name?

### ISSUE THREAD

**Issue by rintcius** [koekeishiya/yabai#705]
Is there an underlying reason that space settings can only be referred to by `mission-control index` in here `yabai -m config [--space <mission-control index>] <space setting>` ?

Asking because I Initially tried to refer to them by label and was surprised that that didn't work.

**Comment by koekeishiya** [comment]
I believe this is just something that has been overlooked; there should not be any technical limitation here.

**Comment by rintcius** [comment]
Great, thank you!

**Comment by 24unix** [comment]
The Labels are different from the Names, aren't they?

I gave my spaces/desktops descriptive Names. I looks like labels double that …

<img width="370" alt="image" src="https://user-images.githubusercontent.com/36622631/99182575-f8737c00-2735-11eb-84b8-4a762c64b3c4.png">

**Comment by koekeishiya** [comment]
@24unix Labels are a yabai specific thing. The space internals in macOS does not have an associated name, but it uses a guid and a 64bit integer. The "Desktop 1" etc. are just visuals rendered by mission-control and there is no way for yabai to retrieve or override these visuals.

**Comment by 24unix** [comment]
@koekeishiya OK, thx.
Too bad that TotalSpaces is closed source, might be interesting to see how they managed to access the names. 
However, I just noticed, under Big Sur the names aren't shown in Mission Control, in earlier versions that was the case. Now it's just only like you described.
