### ISSUE TITLE
Recompile / run local changes?

### ISSUE THREAD

**Issue by Bloumbs** [koekeishiya/yabai#706]
Super noob question, but is there a quick guide on how to sort of run yabai "locally" if I'm wanting to make some changes? Like how to recompile and run Yabai not from the normal "brew services start yabai" release version command, but like "in and out" of a different local build of it? Also, while doing this, it'd probably be wise to not have the normal release yabai from homebrew installed at the same time, wouldn't it?

Like I said, "super noob question". Still REALLY new to this.

**Comment by 24unix** [comment]
Just clone the git repo, change into it and type "make".

Copy it to /usr/local/bin and then you can start it like every other normal program.

It would be advisable to remove the brew formula, yes.
