### ISSUE TITLE
Rule that specifies "title" seems to affect non-matching windows

### ISSUE THREAD

**Issue by AdamWagner** [koekeishiya/yabai#707]
**Rule**
```sh
yabai -m rule --add app="Google Chrome" title="Picture in Picture" manage=on grid=10:10:1:1:8:8 border=on sticky=on layer=above
```

**Without rule**: Tooltips in Google Chrome float/are unmanaged
**With rule**: Tooltips in Google Chrome are tiled… despite not matching the the `title="Picture in Picture"` specified in the rule.

I ran a query command in a loop to capture some of the details of the tooltip window in a temp file. This proves that the tooltip's window title is empty (and should not match "Picture in Picture"). 

Note that I tried many variations of the title regex (e.g., `title="^Picture in Picture$"`, `title="fake"`) with the same result.

```jsonc
  {
    "title": "",
    "height": 19,
    "role": "AXHelpTag",
    "subrole": "",
    "app": "Google Chrome"
  },
```

![Screenshot 2020-11-07 at 14 37 39](https://user-images.githubusercontent.com/1683979/98452756-fb071d80-2106-11eb-9b9e-6ee6ba85d8fb.gif)

**Comment by koekeishiya** [comment]
So the issue is not really that the title filter doesn't apply, however, when a window has no title at all the check basically says "this window doesn't to have a title so we cannot perform a title check". I've changed the code so that if a window reports no title at all, we treat at as having the empty string as its title.

**Comment by AdamWagner** [comment]
Excellent! Thank you @koekeishiya. I'll try it out today.

**Comment by AdamWagner** [comment]
Can confirm that #707 fixes the issue I was having: Chrome windows with empty titles are no longer matched by rules that specify a title regex. 👍
