### ISSUE TITLE
Stacking lost if video goes full screen

### ISSUE THREAD

**Issue by pablosproject** [koekeishiya/yabai#709]
Hi, first of all, thanks for the awesome work with yabai. It's an amazing boost to my productivity. I have the following issue, I usually stack browser+IDE on the left and maintain a terminal to the right.
If, in the browser, I play a video and make it full screen, coming back from full screen delete the stack and I need to re-stack window.
It's not a big issue, but it's annoying, any idea how to solve it?

**Comment by koekeishiya** [comment]
I don't know of any straight forward way to handle this. The issue is that when a video is full screened, it "destroys" the original window behind the scenes and creates a new one. From Yabai's pov. the window is gone and a new one is detected.

**Comment by pablosproject** [comment]
Is there any possibility of detecting when window is going full screen, save the state, and then restore it once the full screen is over? 
I may try to take a look at it if you can point where I should start investigating.

**Comment by koekeishiya** [comment]
Detection if window fullscreen changes: https://github.com/koekeishiya/yabai/blob/master/src/event.c#L415

Last time I looked at this macOS literally destroyed the existing window and created a new one, giving it a new id.
I have kinda given up trying to make workarounds for all the stupid things they do.
