### ISSUE TITLE
How to open GIMP's dialog windows in floating mode?

### ISSUE THREAD

**Issue by danijar** [koekeishiya/yabai#710]
I would like to have the main window inside the tiled layout and all remaining dialog windows in floating mode. The app name us `GIMP-<version>` and the main window's title is `<filename> (<options>) <dimensions> – GIMP`.

I first tried to use a negative lookahead. However, I found that yabai [does not support](https://github.com/koekeishiya/yabai/issues/173) negative lookaheads.

```
yabai -m rule --add app='^GIMP' title='(?!GIMP)$' manage=off
```

I then to use the negative syntax explained in [this issue](https://github.com/koekeishiya/yabai/issues/552). However, this gives an `unknown key 'title[!]'` error in yabai v3.3.0.

```
yabai -m rule --add app='^GIMP' 'title[!]="GIMP$"' manage=off
```

How can I write a rule that disables the tiling window management for GIMP windows except for the main window?

**Comment by yanzhang0219** [comment]
`[]` means `optional`, so you should use `title=xxx` or `title!=xxx`.

**Comment by koekeishiya** [comment]
As yanzhang mentioned, `yabai -m rule --add app='^GIMP' 'title!="GIMP$"' manage=off` should do it.

**Comment by danijar** [comment]
Perfect, thanks! I had to catch one more special case where the main window title would be different when no image is loaded. The complete rule is:

```
yabai -m rule --add app='^GIMP' title!='(^GNU|GIMP$)' manage=off
```

**Comment by jordan-da** [comment]
thank you, this was very helpful

**Comment by tomelliot** [comment]
I needed a $ at the end of the app name:
`yabai -m rule --add app='^GIMP$' title!='(^GNU|GIMP$)' manage=off`
