### ISSUE TITLE
Focusing desktop not working on Big Sur

### ISSUE THREAD

**Issue by capaldo** [koekeishiya/yabai#712]
Attempting to focus a desktop via `yabai -m window --space 2` does not work. I tried running `sudo yabai --load-sa` but the issue persists.

Edit: To add, window shadows and opacity are also not working.

**Comment by marcusmyers** [comment]
When running the `sudo yabai --load-sa` I get the following error:

```
could not retrieve task port for pid: 3849
yabai: scripting-addition failed to inject payload into Dock.app!
```

@capaldo Is that what you receive as well?

**Comment by SxC97** [comment]
I get the following error when running `sudo yabai --load-sa`

```
could not load bootstrap object file
yabai: scripting-addition failed to inject payload into Dock.app!
```

**Comment by chilledsaint0716** [comment]
Attempting to focus a desktop via `yabai -m space --focus 3` does not work too.
I got the following error:
`cannot focus space due to an error with the scripting-addition.`

**Comment by koekeishiya** [comment]
Make sure sip is (partially) disabled, and reinstall the scripting-addition. check the wiki for installation instructions.

**Comment by chilledsaint0716** [comment]
sudo yabai --uninstall-sa
sudo yabai --install-sa
sudo yabai --load-sa

fixed, thx bro.

**Comment by zakroma** [comment]
Reinstalling and reloading SA doesn't work for me. It does work until the reboot/logout. Then it doesnt work. 

Reinstalling yabai and skhd does nothing too.

**Comment by capaldo** [comment]
> Reinstalling and reloading SA doesn't work for me. It does work until the reboot/logout. Then it doesnt work, trying the `sudo yabai --load-sa` results in "Payload doesn't support this macOS version!"
> 
> Reinstalling yabai and skhd does nothing too.
> 
> **Update:**
> For some reason `tail -f /usr/local/var/log/yabai/yabai.err.log` showed that there was an error in my .yabairc:
> `/Users/zakroma/.yabairc: line 1: !/usr/bin/env: No such file or directory`
> 
> changing `!/usr/bin/env sh` --> `!/usr/bin/env zsh`
> has completely fixed all the problems!

This worked. Thank you @koekeishiya and @zakroma.

**Comment by 24unix** [comment]
@capaldo That seems strange.

This ist a fresh Big Sur upgrade:
`╰─➤  file /bin/sh
/bin/sh: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/bin/sh (for architecture x86_64):	Mach-O 64-bit executable x86_64
/bin/sh (for architecture arm64e):	Mach-O 64-bit executable arm64e
╰─➤  /usr/bin/env sh
sh-3.2$
`
However, your shebang (#!) is missing the hash sign.

**Comment by capaldo** [comment]
> @capaldo That seems strange.
> 
> 
> 
> This ist a fresh Big Sur upgrade:
> 
> `╰─➤  file /bin/sh
> 
> 
> 
> /bin/sh: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
> 
> 
> 
> /bin/sh (for architecture x86_64):	Mach-O 64-bit executable x86_64
> 
> /bin/sh (for architecture arm64e):	Mach-O 64-bit executable arm64e
> 
> 
> 
> ╰─➤  /usr/bin/env sh
> 
> 
> 
> sh-3.2$
> 
> `
> 
> However, your shebang (#!) is missing the hash sign.

I added it with a hash sign.

**Comment by 24unix** [comment]
What gives "file /bin/sh" and "/usr/bin/env sh"?

**Comment by zakroma** [comment]
> What gives "file /bin/sh" and "/usr/bin/env sh"?

Not sure I got what you're asking, but I've changed mine to `#!/bin/zsh` as that should

**Comment by 24unix** [comment]
Try to execute whats inside the quotes, as mine is working with #!/usr/bin/env sh

**Comment by zakroma** [comment]
> Try to execute whats inside the quotes, as mine is working with #!/usr/bin/env sh

Results in the same output that you mentioned above.

Adding a proper shebang actually does fix the problem.

**Comment by 24unix** [comment]
👍
