### ISSUE TITLE
Cant install via Homebrew on 11.0.1

### ISSUE THREAD

**Issue by MoSchaub** [koekeishiya/yabai#717]
I tried to install yabai on big sur but it fails with the following error:
Error: An exception occurred within a child process:
Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/local/var/log

**Comment by koekeishiya** [comment]
Sounds like some permissions are messed up with your homebrew installation.

**Comment by MoSchaub** [comment]
Homebrew Doctor says it works fine

**Comment by 24unix** [comment]
Try
ls -las /usr/local
ls -las /usr/local/var
ls -las /usr/local/var/log

and tell us the output.

If the last one fails, just do "mkdir -p /usr/local/var/log"

**Comment by MoSchaub** [comment]
Ok i fixed it by creating the /usr/local/var/log directory and then changing the ownership of the directory and retried: worked perfectly
