### ISSUE TITLE
Focusing a display with an empty space moves the cursor to the center of that display

### ISSUE THREAD

**Issue by Rougemoot** [koekeishiya/yabai#718]
Hi!
When using `yabai -m display --focus 2` to switch focus to my second monitor, if that monitor is on a space with no windows my cursor moves to the center of that monitor.

My use of that is assigning a mouse button to
```
mouse_display=$(yabai -m query --displays --display mouse | jq .index) && \
yabai -m display --focus $mouse_display && \
yabai -m space --focus "$(yabai -m query --spaces --display \
| jq 'reverse | nth(index(map(select(.focused == 1))) - 1).index')"
```
to switch spaces on the display below the cursor. Doing so my mouse jumps to the center which I don't want.

Is there a workaround to that? Is it a deliberate behaviour? Thanks.

**Comment by koekeishiya** [comment]
This is intended, as there is no other way to actually switch focus to a monitor that has no open windows on its active space. No workaround as far as I know.

**Comment by dominiklohmann** [comment]
Closing this as there doesn't seem to be a good way to resolve this.
