### ISSUE TITLE
How to focus most recent window in a space after switching spaces

### ISSUE THREAD

**Issue by noib3** [koekeishiya/yabai#719]
After switching spaces I often have to manually focus a window in that space, which gets really annoying really quickly. Instead I'd like yabai to always focus the most recent window in the space I'm in. I tried the following commands in my skhdrc (here shown for spaces 1 and 2):

```
alt - 1 : yabai -m space --focus 1 && yabai -m window --focus "$(yabai -m query --windows --space | jq .[0].id)"
alt - 2 : yabai -m space --focus 2 && yabai -m window --focus "$(yabai -m query --windows --space | jq .[0].id)"
```

but those didn't seem to solve anything.

Btw, I have `When switching to an application, switch to a Space with open windows for the application` unchecked in System Preferences -> Mission Control.

**Comment by koekeishiya** [comment]
You can use the following signal:

```
# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
```

**Comment by noib3** [comment]
Thanks, that solved it!

**Comment by badloop** [comment]
For anyone still running into this issue, I found that Microsoft Teams was usurping the 0 spot in the window array on space that it had been seen on (Great job, Microsoft.... :-( ) I tend to have a single space for most of my windows that is labeled with the name of the application that will be open on it, so I wrote a little helper function using the above so that whenever I switch to a space, it will focus the window that has the same name as the space.  Hope this helps!

```bash
focus_window () {
    SPACE_NAME=$(yabai -m query --spaces --space | jq ".label")
    WINDOW_ID=$(yabai -m query --windows --space | jq ".[] | select (.app=${SPACE_NAME}).id")
    yabai -m window --focus "${WINDOW_ID}"
}

# focus window after active space changes
yabai -m signal --add event=space_changed action="focus_window"

# focus window after active display changes
yabai -m signal --add event=display_changed action="focus_window"
```

**Comment by Arelav** [comment]
@koekeishiya Thanks a lot. 
> No need to modify your focus binds.
I'll leave it here just in case it won't work for somebody as in my case. I had a floating MS Teams window and to make it work I changed it to `jq .[-1].id` to use a last window.

**Comment by webavant** [comment]
Using a third-party tool, `synergy-core`, I had the same problem @badloop mentioned above. A working solution included selecting the first visible window using `jq`:

```shell
yabai -m signal --add event=space_changed action='yabai -m window --focus $(yabai -m query --windows --space | jq -r '\''[.[]|select(."is-visible")][0].id'\'')'
```
