### ISSUE TITLE
Make windows float if it is non-resizable

### ISSUE THREAD

**Issue by Menchen** [koekeishiya/yabai#720]
It would help a lot if there's an option that automatically makes windows float if it's non-resizable or a new signal...

I tried using signal but it seems that some apps change to non-resizable after its creation (Intellij IDEA, the welcome screen) and one way I think I can do it is polling all windows with `yabai -m query`, but it's so slow and adds overheat to the system, maybe a signal for windows property change?

Another example is Finder copy progression windows... it would mess up my current space and allocate a big chunk of space just for a tiny window.

**Comment by koekeishiya** [comment]
This used to be the default, but had to change for reasons that I no longer remember.
You can identify patterns for these windows and create rules that automatically make them float.

e.g: `yabai -m rule --add app="^Steam$" space=games manage=off`
See https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule

**Comment by anujc4** [comment]
You could use a similar configuration
```
# Do not manage windows with certain titles eg. Copying files or moving to bin
yabai -m rule --add title="(Copy|Bin|About This Mac|Info)" manage=off

# Do not manage some apps which are not resizable
yabai -m rule --add app="^(Calculator|VLC|System Preferences)$" manage=off
```
