### ISSUE TITLE
Focus on next/prev space goes through monitor boundary, but "one-way" only

### ISSUE THREAD

**Issue by ericliou** [koekeishiya/yabai#721]
I'm trying to understand the behaviour when changing focus between spaces.
It seems that sometimes the next/prev goes out of the monitor boundary, but sometimes it doesn't.

This is how I reproduce on my machine:
**Labels:**
```
(this is a space)
((this is the space that's being shown on the monitor))
* focus
```
```
Macbook monitor            External monitor
(1) ((2)) (3)               (4) ((*5)) (6)

yabai -m space --focus prev

Macbook monitor            External monitor
(1) ((2)) (3)               ((*4)) (5) (6)

yabai -m space --focus prev
(goes out of boundary)

Macbook monitor            External monitor
(1) ((*2)) (3)               ((4)) (5) (6)

yabai -m space --focus next

Macbook monitor            External monitor
(1) (2) ((*3))               (4) (5) (6)

yabai -m space --focus next
(hits monitor boundary, nothing happens)

Macbook monitor            External monitor
(1) (2) ((*3))               (4) (5) (6)
```

Should the prev/next cross monitor boundary? Any idea why the behaviour is inconsistent between one monitor and another?
I don't have any any fancy event listening command to have this behaviour.

macOS Catalina 10.15.7
yabai-v3.3.4

**Comment by koekeishiya** [comment]
If you are on mission-control space "Desktop 1" (or if it is a fullscreen app space) *prev* will fail. If you are on mission-control space "Desktop N" (or a fullscreen app space), *next* will fail. Basically, there is no wraparound from the last space til the first space. If you want that you can do (*skhd* syntax): 
```
# focus next space, or the first space if we are at the end
cmd + alt - z : yabai -m space --focus next || yabai -m space --focus first

# focus prev space, or the last space if we are at the beginning
cmd + alt - c : yabai -m space --focus prev || yabai -m space --focus last
```

**Comment by koekeishiya** [comment]
Not sure if this applies, but note:

_In the Mission Control preferences pane in System Preferences, the setting "Automatically rearrange Spaces based on most recent use" should be disabled for commands that rely on the ordering of spaces to work reliably._

**Comment by ericliou** [comment]
Thank you for the comment.
I don't think that's the issue I'm having, since the boundary is not in the first and last spaces.
It's the middle ones where two monitors are transitioning.

I updated the issue with clearer mission-control indexes.

Btw I have the Automatically rearrange turned off.

**Comment by koekeishiya** [comment]
Do you get an error message when running: `yabai -m space --focus next` manually in a terminal, when space 3 is focused?
What happens if you run `yabai -m space --focus 4` instead?

**Comment by ericliou** [comment]
Hm interesting

> Do you get an error message when running: yabai -m space --focus next manually in a terminal, when space 3 is focused?


No, nothing happens. I stay in the same space and window.
```
$ yabai -m space --focus next && echo $?
0
```

> What happens if you run yabai -m space --focus 4 instead?

Interesting results.
While in space 3 `--focus 3` shows `cannot focus an already focused space.` (expected)
While in space 3 `--focus 4` does nothing, stays in space 3, returns successfully. (unexpected)
While in space 5 `--focus 4` goes to **space 3**. (unexpected)
While in space 5 `--focus 3` goes to **space 3**. (expected)

It seems to me it's pointing two indexes (3 and 4) to the same place. I've restarted yabai fwiw.

> What happens if you are on space 6 (your ordering from above) and run yabai -m space --focus next ?
`could not locate the next space` (expected)

**Comment by koekeishiya** [comment]
Can you post the output of: 
yabai -m query --displays
and
yabai -m query --spaces

**Comment by ericliou** [comment]
```
 $ yabai -m query --displays
[{
	"id":69734406,
	"uuid":"130D4D5B-F3A2-DF89-A5D1-327E1F081CAE",
	"index":1,
	"spaces":[1, 2, 3, 4],
	"frame":{
		"x":0.0000,
		"y":0.0000,
		"w":1680.0000,
		"h":1050.0000
	}
},{
	"id":722497181,
	"uuid":"A84E2D07-5454-345F-D24B-4055F164C3E9",
	"index":2,
	"spaces":[5, 6, 7],
	"frame":{
		"x":1680.0000,
		"y":-390.0000,
		"w":2560.0000,
		"h":1440.0000
	}
}]
```
```
 $ yabai -m query --spaces
[{
	"id":14,
	"label":"",
	"index":1,
	"display":1,
	"windows":[814],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":814,
	"last-window":814
},{
	"id":50,
	"label":"",
	"index":2,
	"display":1,
	"windows":[31614],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":31614,
	"last-window":31614
},{
	"id":128,
	"label":"",
	"index":3,
	"display":1,
	"windows":[53480, 44000],
	"type":"bsp",
	"visible":1,
	"focused":1,
	"native-fullscreen":0,
	"first-window":53480,
	"last-window":44000
},{
	"id":9,
	"label":"",
	"index":4,
	"display":1,
	"windows":[],
	"type":"float",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":0,
	"last-window":0
},{
	"id":111,
	"label":"",
	"index":5,
	"display":2,
	"windows":[29020],
	"type":"bsp",
	"visible":1,
	"focused":0,
	"native-fullscreen":0,
	"first-window":29020,
	"last-window":29020
},{
	"id":10,
	"label":"",
	"index":6,
	"display":2,
	"windows":[132],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":132,
	"last-window":132
},{
	"id":125,
	"label":"",
	"index":7,
	"display":2,
	"windows":[47437, 45337, 38443, 44400],
	"type":"bsp",
	"visible":0,
	"focused":0,
	"native-fullscreen":0,
	"first-window":47437,
	"last-window":44400
}]
```

This is from the macbook monitor's Mission Control:
![image](https://user-images.githubusercontent.com/46451142/99379163-3ac8c480-28c0-11eb-997b-81bb8adc6956.png)

**Comment by ericliou** [comment]
And this is from the external monitor's Mission Control;
![image](https://user-images.githubusercontent.com/46451142/99379818-0f92a500-28c1-11eb-888f-9d659b082aef.png)

**Comment by koekeishiya** [comment]
So based on the query output you can see that macOS claim that there are in fact 4 spaces on your primary monitor, and not just 3 as shown in mission-control. This output is fetched live through the macOS API.

What's the output of: `defaults read com.apple.spaces`?

I have not experienced this issue personally. What happens if you run:
```
yabai -m space 10 --destroy
echo $?
```

This issue is likely some cached macOS file that for some reason is out of sync.

**Comment by ericliou** [comment]
I guess you are right, it does show 4 spaces too:
```
                    "Display Identifier" = Main;
                    Spaces =                     (
                                                {
                            ManagedSpaceID = 14;
                            id64 = 14;
                            type = 0;
                            uuid = "FA0352C3-72B1-4478-AE08-4DCA9C964E39";
                        },
                                                {
                            ManagedSpaceID = 50;
                            id64 = 50;
                            type = 0;
                            uuid = "BF6CCD0A-7C13-49A8-B9A9-1409DD7E5F07";
                        },
                                                {
                            ManagedSpaceID = 258;
                            id64 = 258;
                            type = 0;
                            uuid = "5661CDBB-AAA3-4628-A136-7A85EEFC3AEE";
                        },
                                                {
                            ManagedSpaceID = 9;
                            id64 = 9;
                            pid =                             (
                                1216,
                                522
                            );
                            type = 2;
                            uuid = dashboard;
                        }
                    );
```
```
 $ yabai -m space 4 --destroy
cannot destroy a macOS fullscreen space.
```
I'll just restart the laptop then. Thank you for the help and debugging 👍

**Comment by ericliou** [comment]
Just an update, space configurations persist through restarts. Just so I don't waste more of your time, I'll probably just write the command to ignore that specific space.
If you have more ideas, I'll be curious to know.

**Comment by koekeishiya** [comment]
The `com.apple.spaces` plist file is just a cache and you should be able to simply remote it, relog/reboot and things should be fine I think. Full path should be: `~/Library/Preferences/com.apple.spaces.plist`

Looking at the output you posted above, the "extra" space appears to reference the dashboard functionality that was removed from macOS in Catalina. You could maybe use that to guide your search if deleting the above file + reboot was not enough to resolve the issue.
