### ISSUE TITLE
[Issue] focusing window stop working

### ISSUE THREAD

**Issue by drselump14** [koekeishiya/yabai#722]
OS: Catalina 10.15.7
Yabai: stable 3.3.4, HEAD

After updating to the latest yabai, invoking

`yabai -m window --focus prev` causes `could not locate the prev managed window`

Done the reinstalling  yabai and install --load-sa, accessibility permission also fine. 

Any help would be appreciated?

**Comment by koekeishiya** [comment]
Can you elaborate? Works fine for me:

![yabai_722](https://user-images.githubusercontent.com/6175959/99397807-d4ee3400-28e3-11eb-9879-b7ac0da4cc80.gif)

Note: focusing windows do not require the scripting-addition to be installed.

**Comment by drselump14** [comment]
@koekeishiya Thanks for the response! Well, that's strange is there anything that I missed?

**Comment by koekeishiya** [comment]
Are you using the *stack* space layout? If so you need to use `yabai -m window --focus stack.prev` instead of `yabai -m window --focus prev`

**Comment by drselump14** [comment]
Well, I'm currently in normal mode (floating window?) and not only `prev` that's not working `west,east,north,south` are not working too

**Comment by drselump14** [comment]
In the previous version, all the commands worked perfectly even in floating mode, is the API has changed?

**Comment by koekeishiya** [comment]
focus commands do not work on floating windows. this changed with the release of version 3.0.0, https://github.com/koekeishiya/yabai/issues/562

**Comment by axelson** [comment]
Could the error message be improved to note that changing the focused window is not supported in floating mode? I had the same error and didn't realize that was the cause.
