### ISSUE TITLE
How do I only tile certain apps?

### ISSUE THREAD

**Issue by Hum4n01d** [koekeishiya/yabai#727]
My current configuration is has the layout set to `bsp` to tile windows and I'm using a list of apps that are specifically disabled with `yabai -m rule --add manage=off app="$app"`.

I want to invert my configuration so that all apps float by default and I have a specific list of apps that are managed. How would I accomplish this? I tried setting the global mode to `float` and manually setting `manage=on` on those apps but it didn't work.

**Comment by koekeishiya** [comment]
First set the space layout to bsp.

Then `yabai -m rule --add app!="^(Safari|Finder|Notes)$" manage=off `

This will float every app except Safari, Finder, and Notes.

**Comment by yanzhang0219** [comment]
Just for curiosity, why is that inverted way not correct? That is: setting the layout to float by `yabai -m config layout float` followed by setting a rule to make some windows be managed by `yabai -m rule --add app="^(Safari|Finder|Notes)$" manage=on`. 
Thank you!

**Comment by koekeishiya** [comment]
Floating spaces are not set up the same way; they are not initialized in a way that allowws for any tiling to happen, if that makes sense. They are simply "left alone". The space layout setting will override any potential modifier that is put on the window in this case.

**Comment by Hum4n01d** [comment]
Thank you!

**Comment by b3nnythemartian** [comment]
this saved my life, you da goat no cap

**Comment by zerone0x** [comment]
reaally good, I need to close yabai everytime when I use zoom
