### ISSUE TITLE
skhd not running on Big Sur

### ISSUE THREAD

**Issue by emninger** [koekeishiya/yabai#729]
After upgrading to MacOS 11 skhd is not working anymore. I tried all, what you suggested, but to no extent.

I have /private/etc/sudoers.d/yabai with this line
`myusername ALL = (root) NOPASSWD: /opt/local/bin/yabai --load-sa`

and ~/.yabairc with
`sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
`

I also installed and re-installed several times yabai and skhd. But the shortcuts do not work at all - although, if i put in into a terminal the single commands they work. What might be the error?

Thanks in advance for any help!

**Comment by yanzhang0219** [comment]
skhd is independent of yabai so yabai config won't influence skhd's behavior.
Try to check whether you have given the accessibility authorization to skhd, i.e, in System Preferences -> Security & Privacy -> Accessibility, make sure you have checked skhd.

**Comment by davay** [comment]
@emninger stop the skhd service and then check what skhd -V gives you, maybe a syntax error in the config?

**Comment by emninger** [comment]
@davay: Thanks for the tip!

**Comment by tomas-ramos21** [comment]
I'm having the same issue. But only some Skhd commands are not working. I also noticed Skhd does not start when I log in.

Not sure if we should move this into Skhd's repository?

Using the suggested command above I get the following message when trying to change spaces:

```
[~] skhd -V
skhd: successfully created pid-file..
skhd: using config '/Users/USERNAME/.config/skhd/skhdrc'
cannot focus space due to an error with the scripting-addition.
```

I have followed the instructions to guarantee SIP is disabled:
```
[~] csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled
```

Both Skhd and Alacritty (i.e. Where the commands are run) were given the ability to control the computer:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/26782592/99966476-51e04880-2dd1-11eb-8b3d-aa7636ef0bf0.png">

**Comment by emninger** [comment]
But, one problem remains: The automatical load of 'sudo yabai --load-sa' does not work for me - although i did all what was suggested, i.e. a line containing 'sudo yabai --load-sa' in $HOME/.yabairc and the file in /etc/sudoers.d yabai with the line '<username> ALL = (root) NOPASSWD: /opt/local/bin/yabai --load-sa' ... 

Would there be, eventually, a way to configure skhd itself to do all the shortcuts i'd like to have in yabai WITHOUT the load command of yabai?

Thanks in advance for any help.

**Comment by 24unix** [comment]
I guess if you issue sudo 'yabai --load-sa' you are prompted for your password, you are missing your actual username before ALL.

**Comment by davay** [comment]
24unix is correct, that line in sudoers.d/yabai should be 
`<USERNAME> ALL = (root) NOPASSWD: /usr/local/bin/yabai --load-sa`

**Comment by dominiklohmann** [comment]
If you read the wiki page closely, it says to replace the path to the binary with whatever that path is on your system. You can find that path by running `which yabai`, which for most configurations will print `/usr/local/bin/yabai`.

**Comment by yanzhang0219** [comment]
@emninger run `whoami` to get your `<USERNAME>`.

**Comment by emninger** [comment]
Thanks to all .... ;) Unfortunately i made a mistake in cut&paste. But my username is there in the yabai file in '/etc/sudoers.d/'
Special thanks to @dominiklohmann. For some reason, don't remember or know why, i had /opt/local/bin/yabai instead of /usr/local/bin/yabai ...

**Comment by int3rrupt** [comment]
@emninger you and I must have got it from the same place. I had the same issue. Came to help but looks like you found it.
