### ISSUE TITLE
Unable to switch spaces on Big Sur 11.1 Beta

### ISSUE THREAD

**Issue by lbibass** [koekeishiya/yabai#730]
Hi, I appear to be unable to change or edit spaces on the Big Sur 11.1 beta. 

I am unsure why this is. Any ideas? Could the scripting addition be incompatible with this version of MacOS?

**Comment by yanzhang0219** [comment]
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

**Comment by pegak** [comment]
I have exactly same problem. Everything else works (switching displays, moving windows, switching windows position etc.) but only this thing is broken. I am not able to change spaces. It changes displays for me. :)

I have Mac OS X 11.1 Beta and Yabai -v3.3.4.

**Comment by lbibass** [comment]
> https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
> 
> https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

I've already done that, with the correct steps for Big Sur.

**Comment by koekeishiya** [comment]
First of all, why are you still running the Beta version?

Verify that the scripting-addition installed correctly; this path should exist:  `/Library/ScriptingAdditions/yabai.osax`
What is the output of running: `sudo yabai --load-sa`

I upgraded from the release candidate to the official release and everything works fine.

**Comment by yanzhang0219** [comment]
Oops, I just notice what you are saying is version 11.1. Probably yabai has not been adapted to 11.1 yet.

**Comment by koekeishiya** [comment]
Right.. I read 11.0.1 as well. Features that require the scripting-addition are heavily version-specific and I do not run Beta versionf of macOS on my mac. If you want to use these features you either need to patch it yourself or refrain from updating until the public release.

**Comment by lbibass** [comment]
> Right.. I read 11.0.1 as well. Features that require the scripting-addition are heavily version-specific and I do not run Beta versions of macOS on my mac. If you want to use these features you either need to patch it yourself or refrain from updating until the public release.

patching it requires changing the version check, correct? Do you mind explaining what/where I need to change?

**Comment by koekeishiya** [comment]
Well, not exactly just a version check..

The byte patterns (and sometimes also offsets) here need to be changed to support 11.1:

https://github.com/koekeishiya/yabai/blob/master/src/osax/x86_64/payload.m

**Comment by lbibass** [comment]
> Well, not exactly just a version check..
> 
> The byte patterns (and sometimes also offsets) here need to be changed to support 11.1:
> 
> https://github.com/koekeishiya/yabai/blob/master/src/osax/x86_64/payload.m

Oh wow, I had no idea it was that complex! Thankfully, my workflow doesn't require me to have the scripting addition. I'll unenroll from the beta and wait for the actual release.

**Comment by pegak** [comment]
Thank you very much, I also didn't know about this complexity. :) Gonna wait for 11.1 as already updated.

**Comment by avindra** [comment]
For anyone else on 11.1beta, you can define shortcuts for switching spaces in the native MacOS settings.  I would recommend :one:  and :two: 

:one:  Under `System Preferences > Keyboard > Shortcuts`, you can check the boxes to enable the hotkeys.

By default it's `CTRL+1` -> `CTRL+10`.

:two:  Check the "Reduce motion" box in the Display section of Accessibility. So there isn't jitter when switching workspaces like how yabai does it when its working.

**Comment by yanzhang0219** [comment]
macOS 11.1 is officially released. Does anyone check whether yabai work well on it? Thanks.

**Comment by avindra** [comment]
Using 11.1, still unable to switch spaces. My guess is offsets probably need updating.

**Comment by yanzhang0219** [comment]
Okay, thank you. Let's stay tune. ❤️
