### ISSUE TITLE
Wrapping around for a single stack? (As opposed to wrapping around for an entire space)

### ISSUE THREAD

**Issue by jsphnecclia** [koekeishiya/yabai#734]
I saw @dominiklohmann 's commands [here](https://github.com/koekeishiya/yabai/issues/203#issuecomment-700527407) for cycling through every window in a space, including stacks, with wraparound. I'm wondering if it's possible to simply add wraparound to the default behavior of stacks. That is, cycling through a stack as you can do by default except that when you reach the end (or the beginning) it cycles to the first (or last)? (I'm not familiar with queries/jq/xargs)

**Comment by dominiklohmann** [comment]
Just use `yabai -m window --focus stack.next || yabai -m window --focus stack.first` instead for cycling stacks to do the wraparound manually.

The `||` is a logical or, i.e., if the first command fails the latter is executed.

**Comment by jsphnecclia** [comment]
That works perfectly! Thank you
