### ISSUE TITLE
All windows tile temporarily on reload

### ISSUE THREAD

**Issue by Hum4n01d** [koekeishiya/yabai#735]
When I reload my yabai configuration with `launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"`, all of my windows tile, then the ones that are set to `manage=off` float again. This is annoying though because it destroys the existing window layout and leaves me with a bunch of irregularly shaped windows that look tiled (the sizing and position) but are actually floating. Is this intended behavior?

**Comment by dominiklohmann** [comment]
The configuration file is loaded asynchronously. Move the line that sets the default space layout to `bsp` after the lines configuring the window rules, that should solve your issue.

**Comment by Hum4n01d** [comment]
Thank you! That fixed it 😁
