### ISSUE TITLE
Question: Possible to have an even-thirds layout?

### ISSUE THREAD

**Issue by ianjsikes** [koekeishiya/yabai#736]
I know yabai is based on BSP layout. I'm wondering if it is possible in any way to have a layout with three windows side-by-side. I haven't been able to figure out a way.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/5607226/99979378-e1e3ab00-2d5b-11eb-96ef-91dd5b43fc58.png">

**Comment by koekeishiya** [comment]
You can change the split-type/orientation before opening a window using e.g `yabai -m window —insert east` or afterwards using `yabai -m window —toggle split`, followed by `yabai -m space —balance` to make them all equal in size.
