### ISSUE TITLE
[Config] 'window_border_placement' unknown 

### ISSUE THREAD

**Issue by christo-ph** [koekeishiya/yabai#738]
If I am trying to set window_border_placement, Yabai says it doesn't know this setting. Any changes here?

```
❯ yabai -m config window_border_placement exterior
unknown command 'window_border_placement' for domain 'config'
```

Big Sur, SIP disabled, recent yabai

**Comment by 24unix** [comment]
There is no option window_border_placement.

All options are in src/messages.c

These are related to border:

#define COMMAND_CONFIG_BORDER                "window_border"
#define COMMAND_CONFIG_BORDER_WIDTH          "window_border_width"
#define COMMAND_CONFIG_BORDER_ACTIVE_COLOR   "active_window_border_color"
#define COMMAND_CONFIG_BORDER_NORMAL_COLOR   "normal_window_border_color"

**Comment by christo-ph** [comment]
When was this removed? I cannot read anything in the changelog:

https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#210---2019-11-09

**Comment by koekeishiya** [comment]
It was a part of the old window border system, removed in v3.0.0: https://github.com/koekeishiya/yabai/blob/master/CHANGELOG.md#300---2020-05-01

**Comment by 24unix** [comment]
Are you sure it ever existed?

In yabai? Not chunkwm?

**Comment by christo-ph** [comment]
Ok. I will close this for now as it is not supported anymore.
