### ISSUE TITLE
Line at the bottom of status bar on the right

### ISSUE THREAD

**Issue by jbharat** [koekeishiya/yabai#74]
I am noticing a line on the default mac status bar. This does not occur at the start but shows after sometime.

<img width="507" alt="Screen Shot 2019-06-27 at 3 20 05 pm" src="https://user-images.githubusercontent.com/6837979/60238911-527c6300-98ef-11e9-8f2d-10202323e9f9.png">

yabai-v1.0.2 with scripting addon
I have the following config. Status bar is disabled. 
```
#!/bin/zsh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff9dccff
yabai -m config normal_window_border_color   0x00000000
yabai -m config insert_window_border_color   0xff9dccff
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

yabai -m config window_placement first_child

echo "yabai configuration loaded.."
```

**Comment by jbharat** [comment]
Sorry. Its Microsoft Teams app. It keeps a hidden notification popup there.

**Comment by mattsawyer77** [comment]
@jbharat did you find a mitigation for this? I also have to use Teams for work and that little hidden window seems to receive the focus anytime I switch spaces.

**Comment by jbharat** [comment]
@mattsawyer77 I have no solution to this. It still shows that popup even on disabling all notifications in teams app.

**Comment by dominiklohmann** [comment]
Am I correct in assuming that this is a border that yabai draws on an invisible window? 

Ifyes, try creating a rule that matches just that one window and disable its border, or create a rule for the event window_created and filter from that if a rule is not sufficient.

**Comment by jbharat** [comment]
@dominiklohmann I will give it a try.

**Comment by jbharat** [comment]
@dominiklohmann thanks. 

`yabai -m rule --add  label=ignoreTeamsNotification app="Microsoft Teams" title="Microsoft Teams Notification" manage=off`

@mattsawyer77 This seems to be working for me. Notification window does not get focused unless I move the mouse over it. The rule is based on info returned from window query
```
{
        "id":35637,
        "pid":46332,
        "app":"Microsoft Teams",
        "title":"Microsoft Teams Notification",
        "frame":{
                "x":1612.0000,
                "y":23.0000,
                "w":0.0000,
                "h":0.0000
        },
        "level":3,
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "movable":1,
        "resizable":0,
        "display":1,
        "space":1,
        "visible":1,
        "focused":0,
        "split":"none",
        "floating":1,
        "sticky":1,
        "border":1,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
}
```

**Comment by jbharat** [comment]
@dominiklohmann I noticed that when switching from a different display, the focus still goes on Teams notification even with the rule. 

Ex 
Rule applied `yabai -m rule --add label=ignoreTeamsNotification app="Microsoft Teams" title="Microsoft Teams Notification" manage=off`
space 1, 2 are on display 1
space 3, 4 are on display 2
Teams is on space 1. 
mouse_follows_focus = on
focus_follows_mouse = autofocus

So when focusing from space 2 to space 1,  cursor is not on the small teams notification line which is right as per the rule.
When focusing from space 3(or 4) to space 1, cursor is on teams notification line, which should not happen.

**Comment by dominiklohmann** [comment]
```sh
# disable the border on the MS teams window
yabai -m rule --add \
    app='^Microsoft Teams$' \
    title='^Microsoft Teams Notification$' \
    border=off

# The below signal only works on current master, not in 1.1.2
# Tries to focus the window under the cursor whenever the MS teams notification gains focus
# Probably conflicts with mouse follows focus in some ways
yabai -m signal --add \
    event=window_focused \
    app='^Microsoft Teams$' \
    title='^Microsoft Teams Notification$' \
    action='yabai -m window --focus mouse > /dev/null 2>&1'
```

**Comment by jbharat** [comment]
Slightly modified the signal. 

```
yabai -m signal --add \
    event=window_focused \
    app='^Microsoft Teams$' \
    title='^Microsoft Teams Notification$' \
    action='yabai -m window --focus south > /dev/null 2>&1'
```

This pushes the focus to whichever window that is below the notification. Usually I keeps Teams main window there. This seems to be the best workaround for me. Thanks

**Comment by dominiklohmann** [comment]
I wouldn't use `south`. If you actually want to focus the notification you'll end up in an infinite loop, which is why I specifically used `mouse`. Additionally, `south` does not work properly when focusing a floating window—instead it uses `last` as a fallback (`north` and `west` to `first`, `south` and `east` to `last`).

**Comment by jbharat** [comment]
Yes I understand that. But I dont click Teams notifications anyway so it is ok.

**Comment by dominiklohmann** [comment]
See also [this uservoice forum post](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/37054621-notifications) asking Microsoft to switch to the default macOS notification system. 

I just don't understand why they're doing this... other Electron apps handle notifications just fine and don't need to build their own notification system. The amount of work committed to this system when Electron supports native notification centers out of the box just reeks of big company culture issues. And stealing focus when a notification spawns is just evil.

**Comment by runar-indico** [comment]
I would also like to add, that sometimes, cmd-tabbing or clicking the Teams-icon in the Dock, Teams misbehaves, even without Yabai, and focuses on the Notification instead. I find this incredible frustrating from Microsoft.

In any case, I found a workaround with yabai, which seems to fix the issue.

```shell-script
 yabai -m signal --add \
    event=window_focused \
    app='^Microsoft Teams$' \
    title='^Microsoft Teams Notification$' action=" yabai -m window --focus $(yabai -m query --windows | jq 'map(select(.title | endswith("Microsoft Teams")))[-1].id')"

```

Note that you may need to change the app-title here to match the notification-window if you use a different language than english.

This will add a rule for every time the Teams-notification gains focus, and then switch to the main Teams-window instead.

**Comment by colossatr0n** [comment]
Here's a script that works with multiple monitors (and I would suppose a single monitor as well). 

It redirects the focus to the last used window of the display's space when a Teams notification window tries to steal it. It also allows you to interact with a Teams notification if you choose to do so (replying to a message), so it can differentiate between the invisible notification window that is alway there and a visible one.

Add this file to `~/.config/yabai/scripts/` (or wherever your yabai folder is) and name it `defeat-teams`.

```bash
#!/usr/bin/env sh                                                                                                                                                           

echo "Running $(basename "$0")"
focused_app=$(yabai -m query --windows --window)
is_invis_teams_noti=$(echo "$focused_app" | jq '.title == "Microsoft Teams Notification" and .frame.w == 0 and .frame.h == 0')

if $is_invis_teams_noti; then
        focused_display_id=$(echo "$focused_app" | jq '.display')
        visible_space_id=$(yabai -m query --spaces --display $focused_display_id | jq 'map(select(.visible == 1))[0].index')
        available_windows=$(yabai -m query --windows --display $focused_display_id | jq --argjson space $visible_space_id 'map(select(.space == $space))')
        recent_window_id=$(echo "$available_windows" | jq 'map(select(.title | contains("Microsoft Teams Notification") | not))[0].id')
        yabai -m window --focus $recent_window_id
fi
```

Open up your `yabairc` and add the following:

```bash
yabai -m signal --add \
      event=application_activated \
      app="^Microsoft Teams$" \
      action='${HOME}/.config/yabai/scripts/defeat-teams'

yabai -m signal --add \
      event=window_focused \
      app="^Microsoft Teams$" \
      title="^Microsoft Teams Notification$" \
      action='${HOME}/.config/yabai/scripts/defeat-teams'
```

You may need to update modify the path to `defeat-teams` depending on where you put it.

**Comment by ramonbakker** [comment]
Workaround:
Enabling native notifications in Microsoft Teams fixed the (focus) problem for me. Instructions for how to enable the native notifications can be found at https://superuser.com/questions/1580328/force-microsoft-teams-to-use-os-native-notifications/1638418#1638418.

**Comment by mattpus** [comment]
> Here's a script that works with multiple monitors (and I would suppose a single monitor as well).
> 
> It redirects the focus to the last used window of the display's space when a Teams notification window tries to steal it. It also allows you to interact with a Teams notification if you choose to do so (replying to a message), so **it can differentiate between the invisible notification window that is alway there and an actual chat notification**.
> 
> Add this file to `~/.config/yabai/scripts/` (or wherever your yabai folder is) and name it `defeat-teams`. The following works for yabai >= 4.0.
> 
> ```shell
> #!/usr/bin/env sh
> # Works for yabai >= 4.0
> 
> echo "Running $(basename "$0")"
> focused_app=$(yabai -m query --windows --window)
> is_invis_teams_noti=$(echo "$focused_app" | jq '.title == "Microsoft Teams Notification" and .frame.h == 0')
> echo "Invisible teams window selected: $is_invis_teams_noti"
> 
> if $is_invis_teams_noti; then
>         focused_display_id=$(echo "$focused_app" | jq '.display')
>         visible_space_id=$(yabai -m query --spaces --display $focused_display_id | jq 'map(select(."is-visible" == true))[0].index')
> 	available_windows=$(yabai -m query --windows --display $focused_display_id | jq --argjson space $visible_space_id 'map(select(.space == $space))')
> 	recent_window_id=$(echo "$available_windows" | jq 'map(select(.title | contains("Microsoft Teams Notification") | not))[0].id')
> 	yabai -m window --focus $recent_window_id
> fi
> ```
> 
> For yabai versions < 4.0, use this script instead.
> 
> ```shell
> #!/usr/bin/env sh
> # Works for yabai < 4.0
> 
> echo "Running $(basename "$0")"
> focused_app=$(yabai -m query --windows --window)
> is_invis_teams_noti=$(echo "$focused_app" | jq '.title == "Microsoft Teams Notification" and .frame.h == 0')
> echo "Invisible teams window selected: $is_invis_teams_noti"
> 
> if $is_invis_teams_noti; then
>         focused_display_id=$(echo "$focused_app" | jq '.display')
>         visible_space_id=$(yabai -m query --spaces --display $focused_display_id | jq 'map(select(.visible == 1))[0].index')
>         available_windows=$(yabai -m query --windows --display $focused_display_id | jq --argjson space $visible_space_id 'map(select(.space == $space))')
> 	recent_window_id=$(echo "$available_windows" | jq 'map(select(.title | contains("Microsoft Teams Notification") | not))[0].id')
> 	yabai -m window --focus $recent_window_id
> fi
> ```
> 
> Open up your `yabairc` and add the following:
> 
> ```shell
> yabai -m signal --add \
>       event=application_activated \
>       app="^Microsoft Teams$" \
>       action='${HOME}/.config/yabai/scripts/defeat-teams'
> 
> yabai -m signal --add \
>       event=window_focused \
>       app="^Microsoft Teams$" \
>       title="^Microsoft Teams Notification$" \
>       action='${HOME}/.config/yabai/scripts/defeat-teams'
> ```
> 
> You may need to update modify the path to `defeat-teams` depending on where you put it.
> 
> EDIT: Updated the script for yabai >= 4.0. Some of the attribute names are different than in previous versions.

this is not working for me

**Comment by toastedonion** [comment]
@mattpus maybe the following signal helps, to deal with this pesky window:

```
yabai -m signal --add event=space_changed action='cur_msteams_wid=$(yabai -m query --windows --window | jq -r "if .app == \"Microsoft Teams\" and .title == \"Microsoft Teams Notification\" then .id else empty end"); if [ -n $cur_msteams_wid ]; then next_window_id=$(yabai -m query --windows --space | jq -r "map(select(.id != $cur_msteams_wid)) | first | .id // empty"); if [ -n $next_window_id ]; then yabai -m window $next_window_id --focus; fi ; fi'
```

In principle, when changing the space and the `Microsoft Teams Notification` gets focused it will check if there are any other windows on this space and if it finds one, focus the first window found instead. In theory this should be the most recently focused window of that space. At least during my quick manual test the response of `yabai -m query --windows --space` seems to order the list by the most recently selected windows (apart from sticky windows, which always seem to come first).

I only started using this signal today, so it might still need some adjustments. For example it might still focus this notification window, when trying to switch via clicking on the icon in the dock and only following clicks will cycle through the remaining Microsoft Teams windows (funnily enough the notifications window will then no longer be focused anymore). But I can live with that, since I usually don't use the dock.

Another case might be in the presence of multiple sticky windows, which you might not want to be selected, in which case you would have to adjust the `jq` query and exclude them as well.

Even though it hasn't been long yet, it seems to be working great for my workflow and it feels awesome to finally have the proper windows focused automatically again, when changing spaces.

I also have the following signal, to automatically float this small control window when you are in a call, since that one was also always misbehaving for me:

```
yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -e ".\"can-resize\"" || yabai -m window $YABAI_WINDOW_ID --toggle float' app="Microsoft Teams"
```

I couldn't get it to work properly with rules, since it seems like the window gets created with a different title, which gets changed at some later point so my rule never got applied. That is also the reason why I only filter by `app="Microsoft Teams"` for the signal. I then check whether the window is resizable and if not I toggle the window to floating.

I have been using this signal for some time now and so far I haven't yet encountered an issue with it.

**Comment by epichub** [comment]
For me the window title just recently changed to "Microsoft Teams classic" so had to adapt the signal rules accordingly - but then started to work. Before that I also had some strange jq syntax errors in my yabai log.

**Comment by oddnugget** [comment]
I'm having a similar issue, but with a different app: [tuple](https://tuple.app/). Unfortunately, according to #162 yabai ignores windows with the role `AXPopover` which the tuple window has. 

I am getting `window_manager_create_and_add_window: ignoring AXPopover window Tuple 1532` whenever i switch spaces (and tuple steals the focus). Running `yabai -m query --windows --window` returns `could not query window information`.
