### ISSUE TITLE
API possible?

### ISSUE THREAD

**Issue by 24unix** [koekeishiya/yabai#744]
@koekeishiya You once posted an example where you echoed something directly into the yabai sock.

If doing so, one won't need the scripting additions, or am I wrong?

Currently I build the command and then execute them via Swift Process(), I guess talking directly to the socket would be much more elegant.

If yes, is there any kind of documentation for talking to yabai via socks?

Kind regards,
  Micha

**Comment by 24unix** [comment]
I glimpsed more through the code of yabai.

```
static void do_window_alpha(const char *message)
{
    Token wid_token = get_token(&message);
    uint32_t wid = token_to_uint32t(wid_token);
    if (!wid) return;

    Token alpha_token = get_token(&message);
    float alpha = token_to_float(alpha_token);
    CGSSetWindowAlpha(_connection, wid, alpha);
}

```

This seems to be what I need.

Now it gets OT for yabai, sorry that I ask anyways but I can't reproduce the behaviour :-( 

Has anybody a hint for me?

https://stackoverflow.com/questions/65183582/swift-cgssetwindowalpha-not-working-as-expected

**Comment by dominiklohmann** [comment]
You need a private set of permissions to change the opacity of other applications windows. Yabai does this by injecting code into Dock.app, which happens to have these permissions.

**Comment by 24unix** [comment]
Hmm.
At first, thanks for you fast reply.

So I could either find out how to inject this code in Dock.App or @koekeishiya would jump over his shadow to make the check for separate spaces optional so that I can continue to use yabai in the upstream release.

That is what I currently have, I'd like to make it useable as easy as possible:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/36622631/101398001-bb7e4d80-38cd-11eb-8fc2-5eb9cd4a9a66.png">

Currently I build the sequences for yabai -m … and execute them via Process(). Before tinkering with Dock.App it might be easier to use socks and talk to yabai-socket. 

But after each upgrade I've to patch yabais code to ignore the separate spaces, else it would be perfect for me.

**Comment by 24unix** [comment]
OK, I got it working by using this code:

https://github.com/rxhanson/Rectangle/blob/master/Rectangle/AccessibilityAuthorization/AccessibilityWindowController.swift
