### ISSUE TITLE
Yabai window management in Big Sur (Preview, Firefox)

### ISSUE THREAD

**Issue by jasonpott** [koekeishiya/yabai#746]
Hi Thank you for your time in developing Yabai. I am really enjoying the application and the added functionality.

I have noticed that certain apps are not being managed correctly by Yabai.

Preview: When a single file is opened in preview yabai performs correctly and tiles correctly. However if a second tab is opened with a duplicate file or a different file alltogether yaba resizes the window as if accommodating an additional panel  yet no additional window has been created.

Firefox: Firefox appears to not be well managed by Yabai. When ever I swap window locations with another window the firefox pane does not move across and typically is just nudged slightly either being overlaid by the intended replacement window orobscuring it. Mannually position firefox is possible  and does not disturb other windows.

I have some screen recordings of the behaviour I can share if that would help but they were too large to upload here.

**Comment by jasonpott** [comment]
I have also noted that this happens with the default TextEdit.app with new portions of the screen being allocated to each new tab that is opened after the app is initialiaised.

**Comment by koekeishiya** [comment]
The firefox issue is probably #109 and has been fixed on master. The preview issue is likely #68 and will not be fixed until Apple improve their APIs.
