### ISSUE TITLE
Slow yabai in big sur

### ISSUE THREAD

**Issue by chaoxu** [koekeishiya/yabai#748]
Recently I made the switch to big sur, also I've updated yabai version to 3.3.5

Now it takes a very long time to do anything.

Running `yabai -m space --focus 1` could take seconds, and is is unclear why at all.

```
time yabai -m space --focus 1
> yabai -m space --focus 1  0.01s user 0.00s system 0% cpu 2.919 total
```

**Comment by chaoxu** [comment]
I found that some other process was using 99% of the CPU, and that made yabai unusable. Once turning off that process, things are ok again.

Is there a way to make yabai so it should take priority over everything else?

**Comment by pegak** [comment]
I think you can you `nice` or `renicer`. :)

**Comment by dominiklohmann** [comment]
This seems to be answered. Closing this.
