### ISSUE TITLE
Loading the scripting addition doesn't seem to be idempotant and can send Dock.app into a crash loop

### ISSUE THREAD

**Issue by cmacrae** [koekeishiya/yabai#749]
### Issue
Running `yabai --load-sa` (as `root`) when the SA has already been injected sends Dock.app into an indefinite crash loop

### System Info
- system: `"x86_64-darwin"`
- host os: `Darwin 20.1.0, macOS 10.16`
- yabai vers: v3.3.5
- SIP: disabled

### Questions/Thoughts
- What is a successful return from `yabai --check-sa` supposed to convey? That it is just installed? Or also that it has been loaded?
- Running `yabai --load-sa` should be idempotent
- Let me know if I can provide any further information for debugging (I'm not sure how to get the logs for Dock.app). I've provided more context below

### Additional Context
I just upgraded to Big Sur the other day and in doing so saw the [relevant documentation](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup) about the necessity of loading the scripting addition with `sudo yabai --load-sa`

I maintain the Nix package and nix-darwin service module. Part of the service module implements installation of the SA using a system daemon (so, run as `root`). I decided this was a nice place to load the SA, so as not to mess around with `sudo`.  
The resulting script is simply:
```bash
#! /nix/store/8r6qgv5ihwkwwa4r4ydjjb0h3hk4viwi-bash-4.4-p23/bin/bash

if [ ! $(/nix/store/sli7prdi4ap4lx7idqfy2wawq86zdpwi-yabai-3.3.5/bin/yabai --check-sa) ]; then
  /nix/store/sli7prdi4ap4lx7idqfy2wawq86zdpwi-yabai-3.3.5/bin/yabai --install-sa
fi

/nix/store/sli7prdi4ap4lx7idqfy2wawq86zdpwi-yabai-3.3.5/bin/yabai --load-sa

```

As you can see, any time this daemon is loaded, it will run `yabai --load-sa` (as `root`).  
When rebuilding the system configuration, all defined agents/daemons are reloaded, including this script.  
Being that this is a frequent operation, when making configuration changes, I've found that when the SA is loaded over the top of an already running injection, it sends Dock.app into an indefinite crash loop.

**Comment by koekeishiya** [comment]
I am unable to reproduce this when issuing the command twice from either the terminal, the yabairc file, or a combination of both.
It doesn’t really make sense to me, as the call to dlopen would be a noop the second time anyway.

That said it should be possible to check the images of the Dock process to see if the scripting addition has been loaded or not (when we have root privileges).

Sent from my iPhone

On 7 Dec 2020, at 12:14, Calum MacRae <notifications@github.com> wrote:

﻿

Issue

Running yabai --load-sa (as root) when the SA has already been injected sends Dock.app into an indefinite crash loop

System Info

  *   system: "x86_64-darwin"
  *   host os: Darwin 20.1.0, macOS 10.16
  *   yabai vers: v3.3.5
  *   SIP: disabled

Questions/Thoughts

  *   What is a successful return from yabai --check-sa supposed to convey? That it is just installed? Or also that it has been loaded?
  *   Running yabai --load-sa should be idempotent
  *   Let me know if I can provide any further information for debugging (I'm not sure how to get the logs for Dock.app). I've provided more context below

Additional Context

I just upgraded to Big Sur the other day and in doing so saw the relevant documentation<https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup> about the necessity of loading the scripting addition with sudo yabai --load-sa

I maintain the Nix package and nix-darwin service module. Part of the service module implements installation of the SA using a system daemon (so, run as root). I decided this was a nice place to load the SA, so as not to mess around with sudo.
The resulting script is simply:

#! /nix/store/8r6qgv5ihwkwwa4r4ydjjb0h3hk4viwi-bash-4.4-p23/bin/bash

if [ ! $(/nix/store/sli7prdi4ap4lx7idqfy2wawq86zdpwi-yabai-3.3.5/bin/yabai --check-sa) ]; then
  /nix/store/sli7prdi4ap4lx7idqfy2wawq86zdpwi-yabai-3.3.5/bin/yabai --install-sa
fi

/nix/store/sli7prdi4ap4lx7idqfy2wawq86zdpwi-yabai-3.3.5/bin/yabai --load-sa


As you can see, any time this daemon is loaded, it will run yabai --load-sa (as root).
When rebuilding the system configuration, all defined agents/daemons are reloaded, including this script.
Being that this is a frequent operation, when making configuration changes, I've found that when the SA is loaded over the top of an already running injection, it sends Dock.app into an indefinite crash loop.

**Comment by dominiklohmann** [comment]
The launch daemon is running before login, right @cmacrae?

**Comment by cmacrae** [comment]
Thanks for the quick response here @koekeishiya - I think @dominiklohmann may be onto something here (thanks!).  
I'll have a play around with agents/daemons and see what the behaviour is. My initial testing hadn't caught this circumstance.  

I imagine I'll likely be closing this issue soon after finding something that works 😅

**Comment by dominiklohmann** [comment]
Alternatively, `yabai --load-sa` could jus wait for the Dock to be ready for injection.

**Comment by koekeishiya** [comment]
Do you have some tips for how that would work? We already retrieve the Docks PID using https://developer.apple.com/documentation/appkit/nsrunningapplication/1530798-runningapplicationswithbundleide?language=objc and so I am not sure how we would know how long to wait for.

**Comment by dominiklohmann** [comment]
I wonder whether you can wait for the Dock window's presence.

**Comment by koekeishiya** [comment]
Added a check to the `isFinishedLaunching` property when attempting to get the pid for injection.
