### ISSUE TITLE
High RAM usage by Yabai

### ISSUE THREAD

**Issue by MCotocel** [koekeishiya/yabai#751]
I'm using a 2017 iMac with 16 GB RAM. When looking through activity monitor, I've noticed Yabai using over 1 GB of RAM.

Screenshot:

<img width="393" alt="Screenshot 2020-12-10 at 1 21 15 PM" src="https://user-images.githubusercontent.com/74227209/101752192-a6cad100-3aea-11eb-9241-354a3a4ff3b3.png">

**Comment by koekeishiya** [comment]
yabai version?
macOS version?
uptime?

do you have window borders enabled?
single or multi monitor (or mixed?) setup?

**Comment by MCotocel** [comment]
>yabai version?

Yabai-v3.3.5

>macOS version?

11.0.1

>uptime?

1 week

>do you have window borders enabled?

No window borders (SIP is enabled)

> single or multi monitor (or mixed?) setup?

Single monitor

**Comment by koekeishiya** [comment]
I suspect this is a rather small leak, or in some special use-case, as I have rarely ever seen my own usage above ~30mb.
Can you try to check maybe once or twice daily, for a week, to get an indication of how rapidly the usage grows?

The latest version of yabai really only performs new allocations upon application launch and window creation, so there are not exactly a lot of things that should be able to cause a major leak in any way.

**Comment by MCotocel** [comment]
It's slowly growing. Yesterday it was at around 5 MB usage after I restarted Yabai, now it's at 220 MB usage.

**Comment by dominiklohmann** [comment]
Can you share your yabai configuration? I cannot reproduce this either.

**Comment by MCotocel** [comment]
```
# Mouse modifier and actions

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 resize

# Gaps and layout type

yabai -m config layout bsp
yabai -m config top_padding 40
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# Floating windows

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^Emacs$" manage=off
yabai -m rule --add app="^Stickies$" manage=off
```

**Comment by dominiklohmann** [comment]
Yeah that definitely isn't the issue. Are you setting up any signals repeatedly that hang?

**Comment by MCotocel** [comment]
What do you mean by "signals repeatedly that hang?"

**Comment by TonyWu20** [comment]
I have this issue too. The RAM usage grows by the time. At the beginning it is just around 30-40 MB, and then gradually stack up to hundreds of MB or even up to 4 GB (after an uptime of seven days).
My `yabai.rc`:
```
#!/usr/bin/env bash
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# ====== Variables =============================

gaps_top="0"
gaps_bottom="0"
gaps_left="0"
gaps_right="0"
gaps_inner="0"

normal_border_color="010101"
focused_border_color="808080"
preselect_border_color="2d74da"

# ====== Tiling settings =======================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         on
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# ====== Border settings =======================

yabai -m config window_border               on
yabai -m config window_border_width         2
yabai -m config active_window_border_color  "0xE0${focused_border_color}"
yabai -m config insert_window_border_color  "0xE0${preselect_border_color}"
yabai -m config normal_window_border_color  "0x00${normal_border_color}"

# ====== List of rules =========================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="VirtualBox" app="^VirtualBox$" manage=off
#yabai -m rule --add label="Python" app="^Python$" manage=off
 
yabai -m config external_bar all:26:0
```

**Comment by koekeishiya** [comment]
The config doesn't really matter. What does your usage during the week look like. Do you launch and quit  a lot of applications? Do you create and close a lot of windows. Do you leave applications in a launched but no available windows state (e.g application is still "running" in the Dock). What is approximately the max amount of windows opened at the same time (across all spaces and displays) etc.

As I mentioned above there are only 3 places in the code where we actually allocate memory on the heap, and it is useful to try and identify whether the bug is regarding the lifetime of these allocations, or if I've just messed up all the stupid reference counting stuff that Apple API is forcing us to deal with.

**Comment by MCotocel** [comment]
I usually switch spaces quite a lot. Usually I have Firefox open, which I minimize a lot, a terminal, and a note-taking application. I also have Microsoft Teams open most of the time.

**Comment by TonyWu20** [comment]
Just after 23 hours my yabai RAM usage reached 780 MB. In the past day I just kept a window of Alacritty (with tmux running) and a window of chrome with several tabs, and sometimes opened and closed windows of Finder. There were three to four applications in a launched but no available windows state. I kept six spaces across three monitors.

**Comment by scottkurihara** [comment]
I am experiencing this as well since upgrading to Big Sur. It reached 4GB this morning.

Mac OS 11.0.1

Yabai-v3.3.5

Uptime - 2 days

I use my computer w/ one external display. Always running Ubersicht. Use Slack, Safari, Chrome, Jupyter Notebook, and Music.

**Comment by doublevcodes** [comment]
After seeing a usage of over 5GB of RAM, is it possible to know when we'll be able to use stuff which is currently in `the-future`
