### ISSUE TITLE
I want to delete these from automation

### ISSUE THREAD

**Issue by sxwxyfp** [koekeishiya/yabai#752]
I want to delete these from automation

![image](https://user-images.githubusercontent.com/21303306/101800379-2dfa6200-3b48-11eb-8cae-4ffdf0089fa7.png)

**Comment by sxwxyfp** [comment]
tccutil reset AppleEvents

**Comment by dominiklohmann** [comment]
This seems resolved. The above answer is correct here.

If you want to avoid duplicate entries, start codesigning the binary.
