### ISSUE TITLE
Border size seems to be off by 1 pixel

### ISSUE THREAD

**Issue by sluukkonen** [koekeishiya/yabai#753]
![image](https://user-images.githubusercontent.com/39655/101808929-9da82700-3b1f-11eb-8ada-ac9eeec85051.png)

Perhaps this is by design, but to my eye, the border rectangle should be one pixel larger. 

macOS 11.0.1
yabai 3.3.5

Relevant configuration:

```
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xffff0000
yabai -m config normal_window_border_color   0x01000000
```

**Comment by noib3** [comment]
I agree, the border seems off in my setup too
![2020-Dec-17@20:44:23](https://user-images.githubusercontent.com/59321248/102535644-c6449980-40a8-11eb-8cdd-dca917cb863f.png)

**Comment by koekeishiya** [comment]
This is not a mistake and the border matches the actual window. What you are seeing is the window shadow.

Shadows on:
<img width="242" alt="Screenshot 2020-12-17 at 22 43 41" src="https://user-images.githubusercontent.com/6175959/102547427-84701f00-40b9-11eb-9938-55d99bbb4edf.png">


Shadows off (`yabai -m config window_shadow off`):
<img width="211" alt="Screenshot 2020-12-17 at 22 44 10" src="https://user-images.githubusercontent.com/6175959/102547439-8a660000-40b9-11eb-9683-9fa2a4fa80b7.png">

**Comment by sluukkonen** [comment]
I suppose this makes sense. Thanks!

**Comment by sluukkonen** [comment]
Hmm. Turning off window shadows seems to remove shadows from everywhere in the UI (e.g. menus, spotlight window and so on). 

Would it make sense if the window border was drawn over the shadow when shadows are enabled?

**Comment by koekeishiya** [comment]
Different windows can have different shadow parameters (at least they used to before Big Sur), so I think that might be tricky to get right.
