### ISSUE TITLE
[Suggestion] Use Github Discussions for community.. discussions

### ISSUE THREAD

**Issue by ericliou** [koekeishiya/yabai#754]
So this new feature for Github, it could be a good place for people to share tips, dotfiles, setups and ask questions.

**Comment by 24unix** [comment]
I had the same in mind this morning, second the wish.

Perhaps with a "Showoff" region, where one can posts screenshots and the stuff you mentioned.

**Comment by yanzhang0219** [comment]
Exactly. Second this. We could create some regions like "showoff", "tips" and "questions". If so, this issues page can be only used for bug reporting. More elegant and tidier.

**Comment by 24unix** [comment]
Yea, I always felt a bit „bad“ opening issues while it were just questions due to my limited knowledge of yabai.

**Comment by dominiklohmann** [comment]
I second this. Lots of questions are better suited for discussions.

@koekeishiya if you're unsure about this, I can help out moderating it as usual.

**Comment by koekeishiya** [comment]
I've enabled github discussions, but only with the preqrequisite that I personally am not forced into spending a huge amount of time moderating and what not. @dominiklohmann If you want to moderate that section that would be great.

**Comment by dominiklohmann** [comment]
Sounds great to me. I'll start moving some existing issues that are discussions over.
