### ISSUE TITLE
Relationship between floating and sticky

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#760]
This would need to be implemented within yabai. Setting `sticky` should not set `floating`, but `floating` should be implied if `sticky` is set. That way you do not lose information on the way bug.

I would actually consider this a bug in the current implementation.

_Originally posted by @dominiklohmann in https://github.com/koekeishiya/yabai/discussions/745#discussioncomment-193808_

**Comment by koekeishiya** [comment]
Fixed in the latest release.
