### ISSUE TITLE
11.1 issues

### ISSUE THREAD

**Issue by capaldo** [koekeishiya/yabai#762]
Yabai refuses to load the scripting addition stating it does not support the version of macOS. Is there any way to override this?

**Comment by yanzhang0219** [comment]
Stay tuned. 11.1 was released just this morning. I think the author will adapt it soon. 
Refer to https://github.com/koekeishiya/yabai/issues/730

**Comment by capaldo** [comment]
> Stay tuned. 11.1 was released just this morning. I think the author will adapt it soon.
> Refer to #730

I know. I just wanted to make sure he was aware of it thats all.

**Comment by eramdam** [comment]
I have the same issue but somehow the window opacity feature works, fwiw

**Comment by 2m** [comment]
Yup, opacity works. So far I only noticed that workspace switching does not work.

**Comment by koekeishiya** [comment]
Fixed on master.

**Comment by danielfalbo** [comment]
Even if some things were not working, other things were super smooth! For example, swapping windows: 
![out](https://user-images.githubusercontent.com/39460524/102315783-09055500-3f75-11eb-9b86-804c3b5697b6.gif). I really liked that! Don't know if it would be possible to make everything work without losing those cute smooth transitions, for sure it would be great.

**Comment by lATAl** [comment]
`brew install koekeishiya/formulae/yabai --HEAD` return an error

```
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 1e1df15 goto sleep;
==> make install
Last 15 lines from /Users/tuan/Library/Logs/Homebrew/yabai/01.make:
xxd -i -a ./src/osax/loader ./src/osax/sa_loader.c
xxd -i -a ./src/osax/payload ./src/osax/sa_payload.c
xxd -i -a ./src/osax/payload ./src/osax/sa_payload.c
xxd -i -a ./src/osax/mach_bootstrap ./src/osax/sa_mach_bootstrap.c
rm -f ./src/osax/loader
xxd -i -a ./src/osax/mach_bootstrap ./src/osax/sa_mach_bootstrap.c
rm -f ./src/osax/payload
rm -f ./src/osax/mach_bootstrap
xxd -i -a ./src/osax/mach_bootstrap ./src/osax/sa_mach_bootstrap.c
rm -f ./src/osax/loader
xxd: ./src/osax/mach_bootstrap: No such file or directory
make: *** [src/osax/sa_loader.c] Error 2
make: *** Waiting for unfinished jobs....
rm -f ./src/osax/payload
rm -f ./src/osax/mach_bootstrap

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/koekeishiya/homebrew-formulae/issues

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

```

**Comment by BeMacized** [comment]
@lATAl I ran into the same issue, but for some reason it worked when I ran it a second time.
