### ISSUE TITLE
yabai -m space --create doesn't work in the new big sur update

### ISSUE THREAD

**Issue by tidues** [koekeishiya/yabai#763]
After the new update of the Big Sur (new version 11.1), the yabai -m space --create/destroy cannot create or destroy a workspace anymore. Also, there is no error message from running the command. BTW, I checked that SIP is disabled.

It seems that the issue is due to yabai cannot change to a different workspace in the same display. The command 
yabai -m space --focus k 
is not working if workspace k is on the same display, but it still works if k is on another display.

New Update:
When loading the scripting-addition, the notification says "payload doesn't support this macOS version". My current OS version is: Big Sur version 11.1.

**Comment by yanzhang0219** [comment]
After updating yabai, I have some issue about space forcus in the same display as well (I have workspace 1 and 2 on my second display, but `yabai -m space focus 2` switch the focus to workspace 3 which is on my third display). Then I tried to destroy all the workspaces in the same display and recreate them again (i.e., destroy workspace 2 and recreate it again). Afterward, the focus works well again. 

I think you can try what I did. If this doesn't help, try to execute the commands below again or reboot your machine.
```
sudo yabai --uninstall-sa
sudo yabai --install-sa
sudo yabai --load-sa
```

**Comment by tidues** [comment]
Thank you for the suggestion.  I tried all the steps, including reinstall and reload the sa and restart the computer, but it didn't solve the problem.

But I found something that should be the issue: when I execute the command "sudo yabai --load-sa", it says "payload doesn't support this macos version".

**Comment by yanzhang0219** [comment]
Okay. Try the latest master instead of the latest released version. Refer to https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

**Comment by lrangell** [comment]
Same here, but `sudo yabai --load-sa` doesn't print any output. `SIP` is also disabled.

**Comment by tidues** [comment]
> Okay. Try the latest master instead of the latest released version. The author made yabai adapt to Big Sur 11.1 yesterday and it has not been released yet.
> Refer to https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)

Thanks! This solved the problem.

**Comment by kirkegaard** [comment]
I think this might be broken in big sur beta 11.2. Ive tried all of the above and have SIP completely turned off. When i try to trigger any space commands like `--create` it'll just return an empty response and no new space is created. I also dont see anything in my logs so im a bit lost. Is there anything i can check to make sure SA is loaded correctly?

**Comment by yanzhang0219** [comment]
@kirkegaard To adapt to the new macOS version, I think a new payload code should be used. Just stay tuned and the author will make it as soon as its official version is released.
