### ISSUE TITLE
Use active-window-border-color only when there are multiple windows in a space?

### ISSUE THREAD

**Issue by Vermoot** [koekeishiya/yabai#767]
Hi!

I'd like to know if there is any way I can change the active window border color depending on the number of windows in the active space/in visible spaces.

Say I have Firefox in space 1 and four iTerm windows in space 2, I'd like to be able to differentiate active/normal iTerm windows with a yellow border on the active one, but when on space 1 I'd like Firefox to have a normal border, since it's alone in that space.

Does that make sense?

Thanks.

**Comment by Glup3** [comment]
Hey!

Here is my solution to your problem. I execute a custom script on every window change via `Signals`. The script checks if there are multiple applications (aka windows) in the space and toggles the `window_border` property.

#### **`yabairc`**
```bash
# your other configs

yabai -m signal --add event=application_front_switched action="/path/to/the/custom/script"
```

#### **`customScript.sh`**
```bash
#!/usr/bin/env bash

windows="$(yabai -m query --spaces --space | jq '.windows')"

if [[ $windows == *","* ]]
then
  yabai -m config window_border on
  yabai -m config active_window_border_color "0xFFFFFF00"
else
  yabai -m config window_border off
fi

```

Don't forget to make your custom script executable `chmod +x ./customScript.sh`
