### ISSUE TITLE
Directional focus does not work on Mojave 10.14.5

### ISSUE THREAD

**Issue by paigevpark** [koekeishiya/yabai#77]
I'm unable to focus in any direction on Mojave 10.14.5.

I'm currently checked out at HEAD 429fdd7 using homebrew and have scripting addition installed by doing the following:
```
brew services stop yabai
brew uninstall yabai
brew install yabai --HEAD
sudo yabai --uninstall-sa
sudo yabai --install-sa
pkill Dock
brew services start yabai
```

`yabai -m window --focus east` gives me no output, indicating that a window is being found. However, the focus does not change.

**Comment by binamkayastha** [comment]
Same, I installed via make though. Not 100% sure if I got the permissions correct

**Comment by koekeishiya** [comment]
You need to disable SIP.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chetannaik** [comment]
Same problem. I did disable SIP. It is still not working for me.

**Comment by paigevpark** [comment]
@koekeishiya SIP is disabled. 
`$ csrutil status
System Integrity Protection status: disabled.`
