### ISSUE TITLE
SIP filesystem protection

### ISSUE THREAD

**Issue by ThinkChaos** [koekeishiya/yabai#772]
Hello,

After installing the scripting addon I partially re-enabled SIP with `csrutil enable --without debug --without dtrace --no-internal`. I'm pretty sure this used to work as I had noted this incantation, but yabai requests that I disable FS.
Is this a recent change? Is there a reason the SA need FS access after being installed?

Thanks for all your work on this (and past) amazing projects!

**Comment by koekeishiya** [comment]
The error message you get was added in v3.3.5: https://github.com/koekeishiya/yabai/issues/716

I have personally never been able to load code with *filesystem protections* enabled, and I tested just now to make sure, and it terminates the Dock process with the following exception type:

```
Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x0000000104a31e00
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2
```

Maybe it works with *filesystem protections* enabled, if *AMFI* (Apple Mobile File Integrity) is disabled (not sure if you may have done that for other software to work properly).

**Comment by ThinkChaos** [comment]
Thanks for the quick reply.

I definitely have never disabled AMFI, so it's not that.
I think I'm just remembering this wrong. I'll go ahead and close this and use the command from the wiki.

Out of curiosity how do you obtain that exception info?
Attaching Dock via lldb and running `yabai --load-sa` didn't get me anything.

**Comment by koekeishiya** [comment]
You can find crash logs containing this information in Console.app > Crash Reports

Sent from my iPhone

On 23 Dec 2020, at 22:22, ThinkChaos <notifications@github.com> wrote:

﻿

Thanks for the quick reply.

I definitely have never disabled AMFI, so it's not that.
I think I'm just remembering this wrong. I'll go ahead and close this and use the command from the wiki.

Out of curiosity how do you obtain that exception info?
Attaching Dock via lldb and running yabai --load-sa didn't get me anything.
