### ISSUE TITLE
Allow status_bar_space_icon_strip to be edited during runtime

### ISSUE THREAD

**Issue by knowler** [koekeishiya/yabai#78]
Though I do have some default labels for my spaces, it would be great if I didn’t have to restart yabai and lose the tiling layout in order to change these labels. Do you think this could be a possible addition to yabai?

Thank you for all your work on this project. It’s been a huge productivity help for me. :)

**Comment by koekeishiya** [comment]
I currently have no intentions of changing anything related to the *status bar* settings. I may change my opinion on this in the future, but if that happens, all bar settings should be editable at runtime for consistency.

**Comment by koekeishiya** [comment]
@knowler In v1.1.0 you can edit all config settings during runtime, including the status_bar settings.
