### ISSUE TITLE
Padding question

### ISSUE THREAD

**Issue by yevhenshymotiuk** [koekeishiya/yabai#784]
Can I enable following settings only if a desktop contains >=2 windows?
```
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
```

**Comment by yanzhang0219** [comment]
You can use `yabai -m query --windows --space | jq 'length'` to get the number of windows in the current space.
Then you can build a command to enable some setting if and only if the number of windows in the current space is larger than 1 (i.e., `>=2`):

```
[[ $(yabai -m query --windows --space | jq 'length') -gt 1 ]] && yabai -m config top_padding 10
```

When the number of windows is less than 2, remove the padding:
```
[[ $(yabai -m query --windows --space | jq 'length') -lt 2 ]] && yabai -m config top_padding 0
```

Next, you should use yabai signal to make it run automatically
```
yabai -m signal --add event=window_created action="[[ $(yabai -m query --windows --space | jq 'length') -gt 1 ]] && yabai -m config top_padding 10"
yabai -m signal --add event=window_destroyed action="[[ $(yabai -m query --windows --space | jq 'length') -lt 2 ]] && yabai -m config top_padding 0"
```

Probably you need more events to make it robust because `window_created` and `window_destroyed may not cover all the situations. I just give you some hints. Hope it is helpful.

**Comment by yevhenshymotiuk** [comment]
Yes, it was very helpful. Thank you. I am trying to achieve something similar to [`smart_gaps` in i3-gaps](https://github.com/Airblader/i3#smart-gaps)

**Comment by yevhenshymotiuk** [comment]
Don't understand, why none of the following padding settings work (neither initial setup nor signals). Also initial padding setup works if manually executed in terminal but signals don't

``` shell
# tile apps
yabai -m rule --add app="^Emacs$" sticky=off manage=on

# float apps
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off

# layout
yabai -m config layout bsp
yabai -m config window_gap 7

# padding for one window
[[ $(yabai -m query --windows --space | jq "length") -lt 2 ]] \
   && yabai -m config top_padding 0 \
   && yabai -m config bottom_padding 0 \
   && yabai -m config left_padding 0 \
   && yabai -m config right_padding 0

# padding for two or more windows
[[ $(yabai -m query --windows --space | jq "length") -gt 1 ]] \
   && yabai -m config top_padding 10 \
   && yabai -m config bottom_padding 10 \
   && yabai -m config left_padding 10 \
   && yabai -m config right_padding 10

# signals
yabai -m signal --add \
    event=window_created \
    action="[[ $(yabai -m query --windows --space | jq 'length') -gt 1 ]] \
        && yabai -m config top_padding 10 \
        && yabai -m config bottom_padding 10 \
        && yabai -m config left_padding 10 \
        && yabai -m config right_padding 10"
yabai -m signal --add \
    event=window_destroyed \
    action="[[ $(yabai -m query --windows --space | jq 'length') -lt 2 ]] \
        && yabai -m config top_padding 0 \
        && yabai -m config bottom_padding 0 \
        && yabai -m config left_padding 0 \
        && yabai -m config right_padding 0"

yabai -m config window_placement second_child

yabai -m config split_ratio 0.50
yabai -m config auto_balance off

```

**Comment by yevhenshymotiuk** [comment]
I think, currently it is not possible to apply conditional initial padding setup for some reason (we can't query number of windows for every desktop while initializing yabai or something like this). Also i have no idea, why this signals setup is not working

**Comment by yevhenshymotiuk** [comment]
The problem is we should apply different padding settings on different desktops depending on window number

**Comment by yanzhang0219** [comment]
In the `action` of yabai signal, you should escape `$`, so change it to `action="[[ \$(yabai -m query --windows --space | jq 'length') -gt 1 ]] ....`.

> The problem is we should apply different padding settings on different desktops depending on number of windows

You can iterate over all the spaces, and for each space, get the number of windows there and then set the padding.
For example:
```
yabai -m query --spaces | jq '.[].index' | xargs -I{} yabai -m query --windows --space {} | jq 'length'
```
will output the number of windows in each space. Next, you just need to set the paddings based on the number. 

If you are not familiar with `jq`, you can read its manual first (https://stedolan.github.io/jq/manual/). But it is better to read  yabai asciidoc first to understand what yabai could do (https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#signal).

**Comment by yevhenshymotiuk** [comment]
1) I've separated padding setup and general config. Initial padding setup is working now if it is called directly but if add `sh $HOME/.config/yabai/padding.sh` to yabairc and restart yabai, nothing happens. I think, it depends on how yabai executes yabairc actually. 

2) I had escaped `$` symbol and added `--space mouse` option to config lines in signal actions, but it didn't make signals work

Here is the code of my zsh script for padding:
```
# initial setup
window_numbers=$(yabai -m query --spaces \
    | jq '.[].index'  \
    | xargs -I{} yabai -m query --windows --space {} \
    | jq "length")

di=1
for wn in $window_numbers; do
    p=$(($wn == 1 ? 0 : 10))

    yabai -m config --space $di top_padding $p
    yabai -m config --space $di bottom_padding $p
    yabai -m config --space $di left_padding $p
    yabai -m config --space $di right_padding $p

    di=$(($di+1))
done

# signals
yabai -m signal --add \
    event=window_created \
    action="[[ \$(yabai -m query --windows --space | jq 'length') -gt 1 ]] \
        && yabai -m config --space mouse top_padding 10 \
        && yabai -m config --space mouse bottom_padding 10 \
        && yabai -m config --space mouse left_padding 10 \
        && yabai -m config --space mouse right_padding 10"
yabai -m signal --add \
    event=window_destroyed \
    action="[[ \$(yabai -m query --windows --space | jq 'length') == 1 ]] \
        && yabai -m config --space mouse top_padding 0 \
        && yabai -m config --space mouse bottom_padding 0 \
        && yabai -m config --space mouse left_padding 0 \
        && yabai -m config --space mouse right_padding 0"
```

**Comment by yevhenshymotiuk** [comment]
I'd like to to something like the following code, but it still doesn't work

`padding.sh`:
``` shell
# initial setup
window_numbers=$(yabai -m query --spaces \
    | jq '.[].index'  \
    | xargs -I{} yabai -m query --windows --space {} \
    | jq "length")

di=1
for wn in $window_numbers; do
    p=$(($wn == 1 ? 0 : 10))

    yabai -m config --space $di top_padding $p
    yabai -m config --space $di bottom_padding $p
    yabai -m config --space $di left_padding $p
    yabai -m config --space $di right_padding $p

    di=$(($di+1))
done

# signals
yabai -m signal --add \
    event=window_created \
    action="$HOME/.config/yabai/check_padding.sh"
yabai -m signal --add \
    event=window_destroyed \
    action="$HOME/.config/yabai/check_padding.sh"
```

`check_padding.sh`:
``` shell
p=$(($(yabai -m query --windows --space | jq 'length') == 1 ? 0 : 10))

yabai -m config --space mouse top_padding $p
yabai -m config --space mouse bottom_padding $p
yabai -m config --space mouse left_padding $p
yabai -m config --space mouse right_padding $p
```

**Comment by yevhenshymotiuk** [comment]
For now have no idea, why the following code doesn't work. `padding_refresh_command` works if executed using `/ust/bin/env sh -c` but doesn't work if triggered by a signal
``` shell
padding_refresh_command="p=\$((\$(yabai -m query --windows --space | jq 'length') == 1 ? 0 : 10)) && \
    yabai -m config --space mouse top_padding \$p && \
    yabai -m config --space mouse bottom_padding \$p && \
    yabai -m config --space mouse left_padding \$p && \
    yabai -m config --space mouse right_padding \$p"

yabai -m signal --add event=window_created action="$padding_refresh_command"
yabai -m signal --add event=window_destroyed action="$padding_refresh_command"
yabai -m signal --add event=application_launched action="$padding_refresh_command"
yabai -m signal --add event=application_terminated action="$padding_refresh_command"
```

**Comment by yanzhang0219** [comment]
Put all your code into my `yabairc` and it works well on my end.

**Comment by yevhenshymotiuk** [comment]
Does it work after you run this code in your terminal? Cause for me it doesn't

**Comment by yanzhang0219** [comment]
I pasted all your code above to the end of my `yabairc`. Then I restarted the yabai service by `launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"`. It worked well.

**Comment by yevhenshymotiuk** [comment]
Ok, here is my `yabairc`, but padding code should work separately, isn't it?. These are just shell commands

``` shell
# load scripting-additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# gloval settings
# yabai -m config mouse_follows_focus on
# yabai -m config focus_follows_mouse autoraise
yabai -m config window_placement second_child
yabai -m config window_shadow off
yabai -m config window_border on
yabai -m config window_border_width 5
yabai -m config active_window_border_color 0xffa35763
yabai -m config normal_window_border_color 0xff353c54
yabai -m config insert_feedback_color 0xaa7c5c9c
yabai -m config split_ratio 0.50
yabai -m config auto_balance on
yabai -m config window_gap 7

# mission-control desktop labels
yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label social
yabai -m space 4 --label mail
yabai -m space 5 --label media

# window rules
yabai -m rule --add app="^Firefox$" space=web
yabai -m rule --add app="^Emacs$" space=code manage=on
yabai -m rule --add app="^Telegram$" space=social
yabai -m rule --add app="^Slack$" space=social
yabai -m rule --add app="^Discord$" space=social
yabai -m rule --add app="^Spark$" space=mail manage=on
yabai -m rule --add app="^Transmission$" space=media
yabai -m rule --add app="^Spotify$" space=media manage=on
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^Spotlight$" layer=above manage=off
yabai -m rule --add app="^Stickies$" manage=off
yabai -m rule --add app="^System Preferences$" layer=above manage=off

# general space layput
yabai -m config layout bsp

# padding
window_numbers=$(yabai -m query --spaces \
    | jq '.[].index'  \
    | xargs -I{} yabai -m query --windows --space {} \
    | jq "length")

di=1
for wn in $window_numbers; do
    p=$((wn == 1 ? 0 : 10))

    yabai -m config --space $di top_padding $p
    yabai -m config --space $di bottom_padding $p
    yabai -m config --space $di left_padding $p
    yabai -m config --space $di right_padding $p

    di=$((di+1))
done

# padding signals
padding_refresh_command="p=\$((\$(yabai -m query --windows --space | jq 'length') == 1 ? 0 : 10)) && \
    yabai -m config --space mouse top_padding \$p && \
    yabai -m config --space mouse bottom_padding \$p && \
    yabai -m config --space mouse left_padding \$p && \
    yabai -m config --space mouse right_padding \$p"

yabai -m signal --add event=window_created action="$padding_refresh_command"
yabai -m signal --add event=window_destroyed action="$padding_refresh_command"
yabai -m signal --add event=application_launched action="$padding_refresh_command"
yabai -m signal --add event=application_terminated action="$padding_refresh_command"

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
```

**Comment by yanzhang0219** [comment]
> but padding code should work separately, isn't it? These are just shell commands

Yep. But in `yabaric`, the padding code is a setting, not an execution, i.e., it tells yabai to execute a piece of shell scripts when an event is triggered. If the code before it has an error, this setting won't be evaluated, i.e., the signal won't be created. 

When debugging, try to simplify the code by just leaving the piece of code you want to debug on and delete (or comment out) other codes temporarily.  You could remove all the rules and other personal settings, just keep the `yabairc` build-in settings and your padding setting you want to test. Then see whether it works on your end.

**Comment by yevhenshymotiuk** [comment]
Doesn't work in either cases, whatever i comment

**Comment by yevhenshymotiuk** [comment]
If i try to set some simple signals from the terminal manually after evaluating yabairc, they work, so i thought the issue is in padding signals code, but currently don't understand, how it can work for you

**Comment by yevhenshymotiuk** [comment]
You should be able to run this code in terminal (after your `yabairc` was evaluated) and both initial padding setup and signals should work

``` shell
# initial setup
window_numbers=$(yabai -m query --spaces \
    | jq '.[].index'  \
    | xargs -I{} yabai -m query --windows --space {} \
    | jq "length")

di=1
for wn in $window_numbers; do
    p=$((wn == 1 ? 0 : 10))

    yabai -m config --space $di top_padding $p
    yabai -m config --space $di bottom_padding $p
    yabai -m config --space $di left_padding $p
    yabai -m config --space $di right_padding $p

    di=$((di+1))
done

# signals
padding_refresh_command="p=\$((\$(yabai -m query --windows --space | jq 'length') == 1 ? 0 : 10)) && \
    yabai -m config --space mouse top_padding \$p && \
    yabai -m config --space mouse bottom_padding \$p && \
    yabai -m config --space mouse left_padding \$p && \
    yabai -m config --space mouse right_padding \$p"

yabai -m signal --add event=window_created action="$padding_refresh_command"
yabai -m signal --add event=window_destroyed action="$padding_refresh_command"
yabai -m signal --add event=application_launched action="$padding_refresh_command"
yabai -m signal --add event=application_terminated action="$padding_refresh_command"
```

**Comment by yevhenshymotiuk** [comment]
For some reason one of my signals is looped. I found out this using following code
``` shell
refresh_padding_command="padding=10
[ \$(yabai -m query --windows --space | jq 'length') -eq 1 ] && padding=0
osascript -e \"display notification \$padding\"

yabai -m config --space mouse top_padding \$padding
yabai -m config --space mouse bottom_padding \$padding
yabai -m config --space mouse left_padding \$padding
yabai -m config --space mouse right_padding \$padding"


yabai -m signal --add event=window_created action="$refresh_padding_command"
yabai -m signal --add event=window_destroyed action="$refresh_padding_command"
```

**Comment by yevhenshymotiuk** [comment]
@yanzhang0219 `yabai -m query --windows --space | jq` returns nothing if called as a signal action

**Comment by yanzhang0219** [comment]
`jq` outputs the results matching the filters to stdout. You should give some filters to `jq`.

**Comment by yevhenshymotiuk** [comment]
No, without arguments it just pretty-prints the JSON

**Comment by yanzhang0219** [comment]
Oh.. Right. My bad. My brain stopped working. Sorry. 
`yabai -m query --windows --space | jq` outputs the pretty JSON to the stdout.

**Comment by yevhenshymotiuk** [comment]
If we can't query space info in action, my trick can not be implemented using yabai commands and jq, as far as i understand

**Comment by yanzhang0219** [comment]
> If we can't query space info in action, my trick can not be implemented using yabai commands and jq, as far as i understand 

We CAN query sapce in action, but we should do something using the results, not just output it into stdout. Understand?

**Comment by yevhenshymotiuk** [comment]
I don't need to use stdout at all. Check this code. Space info output is piped into jq and then the value in stored in the variable. But this code is not going to work, because `space_info` and `number_of_windows` have no values. You talk about querying yabai manually in my terminal, but the thing is about code in signal action
``` shell
space_info="$(yabai -m query --windows --space | jq)"
number_of_windows="$(yabai -m query --windows --space | jq 'length')"
padding=10

[ "$number_of_windows" -eq 1 ] && padding=0

osascript -e "display notification \"number_of_windows: $number_of_windows, padding: $padding\""
osascript -e "display notification \"$space_info\""

yabai -m config --space mouse top_padding "$padding"
yabai -m config --space mouse bottom_padding "$padding"
yabai -m config --space mouse left_padding "$padding"
yabai -m config --space mouse right_padding "$padding"
```

**Comment by yanzhang0219** [comment]
In your terminal, run:
```
space_info="$(yabai -m query --windows --space | jq)"
echo $sapce_info
```
you will see the contents in `space_info`.

**Comment by yevhenshymotiuk** [comment]
Ok, that's what i am talking about. Now try to create a script `refresh.sh` and use it in a signal action `sh <path-to-script>`

**Comment by yanzhang0219** [comment]
`space_info` is not global but local. It only available in the script file. 
Please paste your `refresh.sh` and the signal code in your `yabairc` here.

**Comment by yevhenshymotiuk** [comment]
Hasn't changed anything. Following code in `yabairc`
``` shell
padding_refresh_command="space_info=\$(yabai -m query --windows --space | jq)
number_of_windows=\$(yabai -m query --windows --space | jq 'length')
padding=10

echo \"space_info: \$space_info, padding: \$padding, number_of_windows: \$number_of_windows\" >> \"\$HOME/yabailogs.txt\"

[ \$number_of_windows -eq 1 ] && padding=0

yabai -m config --space mouse top_padding \$padding
yabai -m config --space mouse bottom_padding \$padding
yabai -m config --space mouse left_padding \$padding
yabai -m config --space mouse right_padding \$padding"

yabai -m signal --add event=application_launched action="$padding_refresh_command"
yabai -m signal --add event=application_terminated action="$padding_refresh_command"
```
and `yabailogs.txt`:
``` txt
space_info: , padding: 10, number_of_windows: 
space_info: , padding: 10, number_of_windows: 
space_info: , padding: 10, number_of_windows: 
space_info: , padding: 10, number_of_windows: 
```

**Comment by yanzhang0219** [comment]
1. Create a separate script file,` ~/refresh.sh` with the code below:
```bash
#!/usr/bin/env bash

space_info=$(yabai -m query --windows --space | jq)
number_of_windows=$(yabai -m query --windows --space | jq 'length')

padding=10

echo "space_info: $space_info, padding: $padding, number_of_windows: $number_of_windows" >> "/Users/yanzhang/yabailogs.txt"

[ $number_of_windows -eq 1 ] && padding=0

yabai -m config --space mouse top_padding $padding
yabai -m config --space mouse bottom_padding $padding
yabai -m config --space mouse left_padding $padding
yabai -m config --space mouse right_padding $padding
```

2. Change it execution mode. Run below code in the terminal directly
``` bash
chmod +x ~/refresh.sh
```

3. In your yabai, add signals like below:
```bash
yabai -m signal --add event=window_created action="~/refresh.sh"
yabai -m signal --add event=indow_destroyed action="~/refresh.sh"
```

(I change the event from `application_launched`, `application_terminated` to `window_created`, `window_destroyed` because `application` related events are not that convenient for testing.)

Tested and verified that it worked well. Attached a short video below for demo. 

https://user-images.githubusercontent.com/11582667/104107034-6c319100-526e-11eb-8b66-ed1785d28cf8.mov

**Comment by yevhenshymotiuk** [comment]
Funny, it isn't still working for me.

**Comment by yevhenshymotiuk** [comment]
> So, when the program is running the code (2), space_info variable has nothing.

But the program is running this code only on action, so there shouldn't be any case, when `space_info` variable has nothing

Implementation directly in `yabairc` using command string and implementation using separate script should have almost anything different

**Comment by yanzhang0219** [comment]
oh....So sorry. I missed that double quotes. 1, 2, and 3 are together in one pair of quote. Sorry.

**Comment by yevhenshymotiuk** [comment]
`(3)` was signals part. `(1)` and `(2)` only were xD

**Comment by yanzhang0219** [comment]
Okay. I see. But that's not important.
It works on my end...

**Comment by yevhenshymotiuk** [comment]
Quite strange. I still have no value for `space_info` variable

**Comment by yanzhang0219** [comment]
Just now, I put all your code directly into my `yabairc`

![image](https://user-images.githubusercontent.com/11582667/104108637-32b35280-527b-11eb-8fe4-b7fb405d8d8f.png)

And it still works. 

https://user-images.githubusercontent.com/11582667/104108653-51194e00-527b-11eb-9820-d3b9bc7ca95c.mov

**Comment by yevhenshymotiuk** [comment]
It is strange, that if i just check space info
``` shell
padding_refresh_command="space_info=\$(yabai -m query --windows --space | jq)
echo \"space_info: \$space_info\" >> \"\$HOME/yabailogs.txt\""

yabai -m signal --add event=window_created action="$padding_refresh_command"
yabai -m signal --add event=window_destroyed action="$padding_refresh_command"
```
i see nothing
``` txt
space_info: 
space_info: 
space_info: 
space_info: 
```

**Comment by yanzhang0219** [comment]
Interesting!
Do you try to reboot your computer? Or re-install yabai of the dev version (https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)). Do you fully disable the SIP?

**Comment by yevhenshymotiuk** [comment]
Yea, i rebooted my computer. SIP is disabled. yabai is from brew. I'll try to install the dev version

**Comment by yanzhang0219** [comment]
Sigh 😞 
I have no idea.

**Comment by yevhenshymotiuk** [comment]
It seems like i skipped `/private/etc/sudoers.d/yabai` part while installing for the first time. But i installed the dev version added sudoers file and rebooted. Still nothing

**Comment by yevhenshymotiuk** [comment]
Found out, that i disabled SIP using `csrutil disable` instead of `csrutil disable --with kext --with dtrace --with nvram --with basesystem` (for Big Sur). Now i have
```
~
❯ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```
It didn't help though. Interesting...

**Comment by yevhenshymotiuk** [comment]
It might be an OS version issue. Installation requirement is 11.0.1. I use 11.2

**Comment by yanzhang0219** [comment]
Okay... 11.1 is supported as well, but not sure about 11.2. Normally for a new macOS version, yabai needs to update a byte patterns in the payload.c file. We have to wait for the adaption.

**Comment by kpritam** [comment]
> I separated your refresh related code into a single script file. I tested it and verified that it worked well. Details are described below for your reference.
> 
> 1. Create a separate script file,` ~/refresh.sh` with the code below:
> 
> ```shell
> #!/usr/bin/env bash
> 
> space_info=$(yabai -m query --windows --space | jq)
> number_of_windows=$(yabai -m query --windows --space | jq 'length')
> 
> padding=10
> 
> echo "space_info: $space_info, padding: $padding, number_of_windows: $number_of_windows" >> "/Users/yanzhang/yabailogs.txt"
> 
> [ $number_of_windows -eq 1 ] && padding=0
> 
> yabai -m config --space mouse top_padding $padding
> yabai -m config --space mouse bottom_padding $padding
> yabai -m config --space mouse left_padding $padding
> yabai -m config --space mouse right_padding $padding
> ```
> 
> 1. Change it execution mode. Run below code in the terminal directly
> 
> ```shell
> chmod +x ~/refresh.sh
> ```
> 
> 1. In your yabai, add signals like below:
> 
> ```shell
> yabai -m signal --add event=window_created action="~/refresh.sh"
> yabai -m signal --add event=indow_destroyed action="~/refresh.sh"
> ```
> 
> (I change the event from `application_launched`, `application_terminated` to `window_created`, `window_destroyed` because `application` related events are not that convenient for testing.)
> 
> Attached a short video below for demo.
> 
>  Screen.Recording.2021-01-09.at.11.32.21.AM.mov

This worked for me as well. I am on BigSur.

**Comment by yevhenshymotiuk** [comment]
> This worked for me as well. I am on BigSur.

It may work on 11.1 and previous ones, but may not work on 11.2, I suppose

**Comment by koekeishiya** [comment]
The signal and query system are not affected by SIP and/or macOS version.
