### ISSUE TITLE
[Suggestion] Mention in the installation docs the option 'Displays have separate Spaces'

### ISSUE THREAD

**Issue by gaultier** [koekeishiya/yabai#785]
I followed closely the installation instructions and `yabai` would fail with the message: `yabai: 'display has separate spaces' is disabled! abort.`

I figured after some investigation that the option 'Displays have separate Spaces'
in Mission Control should be enabled:
<img width="678" alt="Screenshot 2021-01-05 at 08 52 14" src="https://user-images.githubusercontent.com/3737145/103620165-513fe380-4f33-11eb-950d-0f082ca16d96.png">

Not sure if this is possible to automatically enable this option with some installation script, or to document it in the installation procedure.

Cheers

**Comment by koekeishiya** [comment]
This is already mentioned in the *requirements and caveats* section in the readme, as well as the *installation requirements* in the wiki. There are private APIs that appear to be able to modify this setting, but I don't think it is a good idea to automatically change system settings without the users consent. I also am fairly certain that the system has to be restarted, or at least requries a logout/login when this value changs.


![image](https://user-images.githubusercontent.com/6175959/103642900-1b5f2700-4f54-11eb-85da-3a662b1608f0.png)



![image](https://user-images.githubusercontent.com/6175959/103642862-0edace80-4f54-11eb-8f28-1d03816927c0.png)

**Comment by 24unix** [comment]
Yes, a logout/login is required.

I found no way to avoid it.

**Comment by gaultier** [comment]
Oh, you are right, I missed it. Indeed, changing this setting pops up a dialog telling the user this change will only have effects after a logout.
Alright, feel free to close.
Thanks for the nice project!

**Comment by IonelLupu** [comment]
I get the same error in the logs "yabai: 'display has separate spaces' is disabled! abort..". Logging out doesn't fix the issue
