### ISSUE TITLE
Emacs window border

### ISSUE THREAD

**Issue by yshym** [koekeishiya/yabai#788]
I have `yabai -m rule --add app="^Emacs$" space=code manage=on` line in my `yabairc` and Emacs is successfully managed by yabai, but if i enable window borders, Emacs doesn't have one. Is it possible without macport?

**Comment by bashu** [comment]
I second that

**Comment by templateK** [comment]
FYI, [emacs-mac](https://bitbucket.org/mituharu/emacs-mac) displays the border when the option is enabled.

**Comment by koekeishiya** [comment]
Note to self: "malformed" windows that are made manageable through rules should be whitelisted for borders (and other similar properties).

**Comment by vespakoen** [comment]
I added this to src/window.c:

```diff
diff --git a/src/window.c b/src/window.c
index 8ef484e..cbf7785 100644
--- a/src/window.c
+++ b/src/window.c
@@ -384,6 +384,8 @@ bool window_level_is_standard(struct window *window)

 bool window_is_standard(struct window *window)
 {
+    if (window->rule_manage) return true;
+
     bool standard_win = false;
     CFStringRef role  = NULL;
     CFStringRef srole = NULL;
```

Probably not the ideal fix, but works for me, I use it for Adobe After Effects like this:

```
yabai -m rule --add app="^Adobe After Effects*" manage=on border=on
```
