### ISSUE TITLE
space domain not working

### ISSUE THREAD

**Issue by scbizu** [koekeishiya/yabai#79]
Hi, there. Thanks for giving us such an awesome project ! But when I try to config my yabai, I find that the space domain level command are not working . And, when I use -V to start yabai, there is no weird logs, here is my logs ,yabairc, and MacOS version , do I use it in right way XD? Thanks in advance.

## logs

![image](https://user-images.githubusercontent.com/8732481/60384782-bc923500-9ab4-11e9-8cb4-b60521beaef1.png)

![image](https://user-images.githubusercontent.com/8732481/60384790-ccaa1480-9ab4-11e9-8e91-d4d7af2b96af.png)

![image](https://user-images.githubusercontent.com/8732481/60384806-00853a00-9ab5-11e9-89de-bbbea87bc3e1.png)

## yabairc

```
#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣
yabai -m config status_bar_power_icon_strip  ❤️ 💔
yabai -m config status_bar_space_icon        📦
yabai -m config status_bar_clock_icon        🐸

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   20

echo "yabai configuration loaded.."
```

### MacOS Version 

![image](https://user-images.githubusercontent.com/8732481/60384846-49d58980-9ab5-11e9-9abc-958689a45977.png)

**Comment by koekeishiya** [comment]
You need to disabe SIP. https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection

**Comment by scbizu** [comment]
Thanks for your rapid reply , I'll give it a try

**Comment by scbizu** [comment]
It seems not working as before , do I need to re-install yabai and re-install yabairc ?

**Comment by koekeishiya** [comment]
You need to also install the scripting-addition: `sudo yabai --install-sa`.
See https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release) for full install instructions.

**Comment by scbizu** [comment]
Thanks ! It works (I forget to use sudo to run yabai --install-sa)
