### ISSUE TITLE
How can I start macOS and have fullscreen spaces already named?

### ISSUE THREAD

**Issue by yangnom** [koekeishiya/yabai#790]
I always want emacs, safari, and terminal running in full screen and to have the ability to change to those screens with the following commands.

```
hyper - e : yabai -m space --focus emacs  
hyper - 9 : yabai -m space --focus safari  
hyper - 0 : yabai -m space --focus terminal  
```

Unfortunately to do so, I have to full screen emacs, safari and terminal and then move them into spaces 1, 2 and 3, and then run the following commands.

```
yabai -m space 1 --label emacs
yabai -m space 2 --label safari
yabai -m space 3 --label terminal
```

I feel like there is a better way to do this, but I'm not sure what it is.

**Comment by mideuger** [comment]
You can setup your workspace in `yabairc` . Its basically a shell script, so you should be able create/label your spaces and launch/move your applications directly from there.

**Comment by yangnom** [comment]
It's easy enough to start an application in full screen (this way seems a bit hacky, so if there is a better way, please tell me)
```bash
/usr/bin/osascript -e "tell application \"Safari\"" -e "activate" -e "tell application \"System Events\"" -e "keystroke \"f\" using {control down, command down}" -e "end tell" -e "end tell"
```

I suppose my problem now is, how can I reference a fullscreen application space?

According to [this](https://github.com/koekeishiya/yabai/wiki/Commands#message-passing-interface)

> The mission-control indices for spaces can be seen when mission control is active.

I was hoping it would be as easy as `yabai -m space --focus Safari` but that returns `value 'Safari' is not a valid option for SPACE_SEL`

So I need to figure out how to either move directly to a fullscreen space, or label a fullscreen space a la `yabai -m space 2 --label safari`, neither of which I can do.

**Comment by mideuger** [comment]
I actually have no better idea to generically launch an application in fullscreen. Some apps may have dedicated parameter for this. Maybe you could also try `yabai -m window --toggle native-fullscreen` but I think you may run into some timing issues.

To reference the space with your fullscreen app you can use this (assuming `jq` is installed) :
`yabai -m query --windows | jq -er 'map(select(.app == "Safari" and ."native-fullscreen" == 1))[0].space'`

This will return the space index of the first fullscreen Safari window.

**Comment by yangnom** [comment]
You are correct that opening and full screening applications then labeling them does have some timing problems, so just having a script that does the line you gave  me 3 times with 3 different applications (safari, emacs, terminal) I believe will work.  During some testing, certain parts of yabai have broken (desktop switching) so I can't fully test and figure everything out, but I'll close this thread.

**Comment by yangnom** [comment]
> I actually have no better idea to generically launch an application in fullscreen. Some apps may have dedicated parameter for this. Maybe you could also try `yabai -m window --toggle native-fullscreen` but I think you may run into some timing issues.
> 
> To reference the space with your fullscreen app you can use this (assuming `jq` is installed) :
> `yabai -m query --windows | jq -er 'map(select(.app == "Safari" and ."native-fullscreen" == 1))[0].space'`
> 
> This will return the space index of the first fullscreen Safari window.

I'm wondering how I can use 
`yabai -m query --windows | jq -er 'map(select(.app == "Safari" and ."native-fullscreen" == 1))[0].space'` as the argument for another command
`

**Comment by yanzhang0219** [comment]
You can store its result into a variable and use that variable in another command like
`SPACE=$(yabai -m query --windows | jq -er 'map(select(.app == "Safari" and ."native-fullscreen" == 1))[0].space') && echo $SPACE`

Or you can take advantage of `xargs`. For example,
`( yabai -m query --windows | jq -er 'map(select(.app == "Safari" and ."native-fullscreen" == 1))[0].space' ) | xargs -I{} yabai -m space --focus {}` will focus the space where the native-fullscreen Safari resides.

**Comment by yangnom** [comment]
@yanzhang0219 thank you very much, the `xargs` example does *exactly* what I've wanted to do for quite some time!
