### ISSUE TITLE
Auto-Resizing Not Working With SIP Enabled

### ISSUE THREAD

**Issue by firexcy** [koekeishiya/yabai#792]
I’m trying setting up yabai on an M1 MacBook Pro with macOS 11.1 installed. According to the pinned issue, yabai currently works with reduced capacities on M1 models, notably without the ability to modify Dock.app. Therefore, I decide it preferable to keep SIP enabled since most advanced features aren’t available at this time anyway, and M1 Macs are disallowed from running iOS apps with SIP disabled (there will be an alert that iOS apps can’t be opened because Security Policy is set to Permissive Security). 

However, I find that if I leave SIP enabled, yabai would also lose the ability to automatically adjust window sizes, compromising the main purpose of a tiling WM. I understand that ultimately it’s Apple that is to blame, but given that other WM such as Amethyst does work even with SIP enabled, is it possible for yabai to support auto-resizing without scripting additions? Thanks.

**Comment by koekeishiya** [comment]
Build the master branch from source or using brew (`brew install yabai --HEAD`) and set up your config file as usual, and it will run just fine.

**Comment by firexcy** [comment]
Confirm it works; thanks for your fast response. An additional question: does the new version so changes that it is now necessary to declare the height of the menu bar, even the native one? Before upgrading, yabai accommodates the system menu bar automatically; but after upgrading, it seems I have to manually set `yabai -m config external_bar all:24:0` or the `top-padding` is calculated from the actual edge of the screen instead of the bottom edge of the menu bar.

**Comment by koekeishiya** [comment]
That appears to be a M1 specific bug. The API that is used works correctly on Big Sur running on intel architecture.  I haven't bought an M1 machine myself yet, so am unable to debug said issue. (Waiting for the 14" version that is hopefully released in a couple of months).

**Comment by firexcy** [comment]
Thank you. I have no further questions.

**Comment by koekeishiya** [comment]
I created an issue to track the menubar bug with some information on where M1 users can debug this if they want to:
https://github.com/koekeishiya/yabai/issues/793
