### ISSUE TITLE
Move window to space without disabling SIP

### ISSUE THREAD

**Issue by typoon** [koekeishiya/yabai#795]
Hi,

I noticed that with SIP enabled it seems like it is not possible to move a window to another space. Amethyst seems to be able to do that, so I did some digging and looks like they use `CGSpacesInfo` for that as seen here: https://github.com/ianyh/Amethyst/blob/7cd205a1f8460d19f407acfde6aa2a33b7b0cfe7/Amethyst/Managers/WindowManager.swift#L642

Would it be possible to implement the feature to move windows to a different space in yabai using this API so that SIP can remain enabled?

Thanks!

**Comment by yanzhang0219** [comment]
I think "moving windows to another space or display" does not require SIP disabled. It is not listed on the wiki page https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection and https://github.com/koekeishiya/yabai/issues/13#issuecomment-497950485. 

I uninstalled scriping-addition just now by `sudo yabai --uninstall-sa, killall Dock`. Then I tested "moving a window in space 1 to space 2` via `yabai -m window space 2`, and it works well.

**Comment by typoon** [comment]
You are completely correct. I got confused between the move window to space
and the focus space commands. It is focusing a space that does not work
without SIP disabled.

Sorry for the confusion. I guess it is safe to ignore me here then.

Any idea how Mission Control might be doing that? I would assume there
might be some private API for it that could be used?

**Comment by yanzhang0219** [comment]
I don't know the underlying techniques that Mission Control uses to do that. But I have another way to switch workspace with SIP disabled by means of the macOS Keyboard shortcuts. 

I set the shortcuts in "System Preferences -> Keyboard -> shortcuts -> Mission Control" for workspace switching. For example `^1`, `^2`, ..., `^N` for switching to workspace 1, 2, ..., N. 

Then I create a shell script. I can pass in an argument as the target workspace id, and this script will help us switch to that workspace. The shell script is here (https://github.com/yanzhang0219/dotfiles/blob/master/.config/yabai/scripts/focus-space-SIP.sh)

Next, in `skhdrc`, we just need to create some keybindings for switching workspaces using this script. For example, `alt - 3 : ~/.config/yabai/scripts/focus-space-SIP.sh 3 ` for switch to workspace 3.

**Comment by typoon** [comment]
Yeah, that is what I have been doing. Only problem I have with that is that
there doesnt seem to be a reliable way of exporting those keyboard
shortcuts from MacOS, so whenever I setup a new machine I have to recreate
those shortcuts manually.

I will google around some more and see if I can find any pointers.

**Comment by yanzhang0219** [comment]
Exactly. 
I have no idea where they are stored (probably in some plist file). What I am doing is enabling the automatic Time Machine backup so that I can set up a new machine using the latest backup in the future.

**Comment by hpl002** [comment]
Not to jump on the thread here, but creating a completely separate repository that describes how one can successfully mimic the same behavior as yabai without disabling SIP would be extremely useful.

Im sure many others would not only find this useful but also happily try and resolve some issues if you were to collect all of this in one place.

**Comment by yanzhang0219** [comment]
@hpl002 Thank you for your advice. I am a heavy user of yabai, and that's what I am thinking. In the Discussions, we have a section called "Ideas" and I think that's a great place to gather tips/skills. 

I learned a lot during my using and configuring yabai. I am really desired to share them. I will create a brand new thread there later to share what I've learned and come up with.

**Comment by hpl002** [comment]
> @hpl002 Thank you for your advice. I am a heavy user of yabai, and that's what I am thinking. In the Discussions, we have a section called "Ideas" and I think that's a great place to gather tips/skills.
> 
> I learned a lot during my using and configuring yabai. I am really desired to share them. I will create a brand new thread there later to share what I've learned and come up with.

Awesome! Thank you for your willingness. Looking forward to having a look 🎉
