### ISSUE TITLE
Comparnig limelight and yabai's built-in border 

### ISSUE THREAD

**Issue by bookercodes** [koekeishiya/yabai#797]
Thank for all the work you've done, koekeishiya!

I am using yabai and  [limelight](https://github.com/koekeishiya/limelight) - they're really nice. I especially like that an `internal` border effectively squares windows on Big Sur.  

Only downside is flickering (when switching windows and, more notably, dragging windows).

Would using yabai's built-in border functionality feel smoother?

Am curious to try, but still considering if I should partially disable SIP. [This discussion](https://github.com/koekeishiya/yabai/issues/13) has given me plenty to chew on.

**Comment by koekeishiya** [comment]
In short, yes, the yabai border system works differently and is smoother. For detailed information see #565

**Comment by bookercodes** [comment]
This addressed my question and some! Thank you.
