### ISSUE TITLE
Fixed-size windows

### ISSUE THREAD

**Issue by jwoglom** [koekeishiya/yabai#800]
Apologies if this functionality is already supported and I am just not aware of how to use it.

I would like to change the window layout of a given space to have all windows in a fixed size -- e.g., if I have 15 terminal windows open, a 5x3 grid of some sort. Running `yabai -m space --layout bsp` causes a fractal pattern on the screen, I'd like to just make all of the open windows approximately evenly sized so I can see what is happening on all of them.

Is this possible as-is or would this require an improvement to yabai? Thanks!

**Comment by koekeishiya** [comment]
Is `yabai -m space --balance` not sufficient?

**Comment by braham-snyder** [comment]
`yabai -m space --balance` helps a ton, but with a lot of windows gives a window pattern vaguely like this:

```
 ________________
|   |____________|
|   |   |________|
|   |   |   |____|
|___|___|___|____|
```

That's the "fractal pattern" he means, I think.

&nbsp;

A regular grid where each window is roughly the same size and shape would improve readability a bunch.

**Comment by dominiklohmann** [comment]
Are you aware of `yabai -m config auto_balance on`? You can use it in combination with a signal that sets the insertion point to the largest window whenever you focus a window to get the desired behavior.

**Comment by jwoglom** [comment]
Would you mind sharing how you've configured that signal?
