### ISSUE TITLE
Could not close terminal emulators with yabai -m window --close

### ISSUE THREAD

**Issue by DragonL40** [koekeishiya/yabai#806]
when running `$(yabai -m window $(yabai -m query --windows --window | jq -re ".id") --close)` in the terminal, this message is displayed `could not close window with id '6151'.`

The same result as when using `yabai -m window --close`.

I used to use a keymap in skhd to evoke the first command and close the terminal, but it doesn't work anymore (tested on Alacritty and Kitty). It still works on all the other applications, just not working for the terminal emulators.

**Comment by carlosflorencio** [comment]
Experiencing this issue as well, not sure if it helps but some info about the window:

```json
{
	"id":38352,
	"pid":44591,
	"app":"Alacritty",
	"title":"cfl12: yabai -m query --windows",
	"frame":{
		"x":965.0000,
		"y":24.0000,
		"w":953.0000,
		"h":1011.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"display":1,
	"space":2,
	"visible":1,
	"focused":1,
	"split":"vertical",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":0,
	"border":1,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}
```

```bash
❯ yabai -m window --close
could not close window with id '38352'.
```

**Comment by dominiklohmann** [comment]
`yabai -m window --close` simply simulates a press on the window's `AXCloseButton`. If the window doesn't have one, the command cannot work.

**Comment by carlosflorencio** [comment]
@dominiklohmann yep you're right, adding the title bar to the terminal solves it. Thanks :)

**Comment by weirane** [comment]
In case anyone encountered this issue from search engine and don't want the title bar in the terminal, if you use skhd to close the window, you can pass the key binding to the terminal using the "application specific hotkey" feature and let the terminal handle the key binding that closes the window, so you can keep the same key binding and you don't need the title bar in the terminal.

I use option-q to close a window and alacritty as my terminal. Example config:

In `skhdrc`:
```
lalt - q [
    # pass the key binding to alacritty
    "alacritty" ~
    * : yabai -m window --close
]
```

In `alacritty.toml`:
```toml
[keyboard]
bindings = [
  { mods = "Option", key = "q", action = "Quit" },
]
```
