### ISSUE TITLE
yabai -m space --focus 2 just does nothing after upgrade to 11.1

### ISSUE THREAD

**Issue by FinnFrotscher** [koekeishiya/yabai#807]
Hello,
i just upgraded macos to 11.1.
After going through all the `--uninstall-sa --install --load-sa`, `brew install --HEAD` and `brew restart yabai` motions, the command`$ yabai -m space --focus 2` does nothing and prints nothing to the console.
`yabai -m space --focus 1` prints `cannot focus an already focused space.`

pls help.

**Comment by mirophan** [comment]
Hi @FinnFrotscher, I am having the same issue. Have you been able to resolve it? Thanks.

**Comment by FinnFrotscher** [comment]
I thought i did but its reappearing after each restart.
what i did was follow the install instrcutions from https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD) including the big sur sudo startup file manipulation. it worked until restart.

**Comment by FinnFrotscher** [comment]
@koekeishiya do you have an idea what might cause this issue?

**Comment by koekeishiya** [comment]
Upgrade to the lastest version: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#updating-to-the-latest-release

Verify that you have followed this: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup by manually running `sudo yabai --load-sa` in a terminal (It should complete without asking for your password).

**Comment by FinnFrotscher** [comment]
turns out i broke my sudoers file the first time i tried that.
