### ISSUE TITLE
After swap-ing a window, mouse doesn't follow with mouse_follows_focus on

### ISSUE THREAD

**Issue by evanmoses-okta** [koekeishiya/yabai#808]
I have `mouse_follows_focus on`, and when I execute `yabai -m window --swap [any direction]`, the current window moves as expected, but the mouse doesn't follow it, remaining in place. If it matters, I did *not* disable SIP, but it didn't look like anything that requires SIP disabled should affect this.

Compounding the problem, I have my keys bound like this:

```
shift + alt - h : yabai -m window --swap west || yabai -m window --display west
```

When I move the window to the next display, the mouse stays in place *and another window on the "current" display* retains focus, regardless of the `focus_follows_mouse` setting.  The upshot is that if I press `A-S-h` twice, intending to move window A to the west twice, and it crosses a display border, I end up moving multiple different windows on the originating display.  To illustrate (x is mouse, * is focused window):

```
|------|   |------|
|      |   |    x |
|   A  |   | B  C*|  
|------|   |------|
A-S-h
|------|   |------|
|      |   |    x |   C moved west, still focused, but mouse is in B
|   A  |   | C* B |  
|------|   |------|
A-S-h
|------|   |------|
|      |   |    x |   C moved display west, but now B is focused
| A  C |   |  B*  |  
|------|   |------|
A-S-h
|------|   |------|
| A  C |   |    x |   B moved display west, now nothing (Finder) is focused
| B    |   |      |  
|------|   |------|

**Comment by koekeishiya** [comment]
Swap does not trigger mouse-follows-focus. This is intentional, but I am open to discussion based on feedback.

**Comment by danymat** [comment]
I did find how to do it:

Note: when I try to focus to the window swapped, it doesn't work because I'm already in that window, even after swap. So what I did was to focus the previous window and focus again to the swapped window:

This is my contribution, fixed:
```
hyper - right : window=$(yabai -m query --windows --window | jq -r '.id') \
    && (yabai -m window --swap largest || yabai -m window --swap next || yabai -m window --swap prev ) \
    && yabai -m window --focus $window \
    && yabai -m window --focus prev \
    && yabai -m window --focus $window
```
