### ISSUE TITLE
Float child windows in center.

### ISSUE THREAD

**Issue by rpoovey** [koekeishiya/yabai#810]
Is it possible to float and center all child windows of a specific application? Like a mail client for instance, it would be nice if the compose window is floating and in the center but the main window stays managed.

**Comment by joshtwo** [comment]
I suppose the question here is what defines "child window". I would try querying the window IDs of the application and assume the window with the lowest ID is the "main window" any window with a higher ID is a "child window", but you might start to run into trouble if things open in an unexpected order.
