### ISSUE TITLE
moving space between displays with different `shape`

### ISSUE THREAD

**Issue by weiwee** [koekeishiya/yabai#811]
My daily work flow is that 
- there is a monitor on the front to i used to handle the main tasks
- and a secondary monitor on the right shows some docs/wiki/notes.

and sometimes, i need to move space from secondary monitor to my main monitor, use
```sh
yabai -m space  --display 1 
```

it works fine except `black background`
![image](https://user-images.githubusercontent.com/18696809/106248132-85b17180-624b-11eb-8322-c5079f523233.png)

![image](https://user-images.githubusercontent.com/18696809/106249311-2eac9c00-624d-11eb-9e11-fa145b8b9c09.png)

This may related to the different `shape` of monitor because i rotate secondary monitor 90 degree, and it works fine if i rotate it back to normal. Seems yabai `copy` the space directly to other display without reshape background image...  

any suggestion here?

**Comment by MuhammedZakir** [comment]
Related: #781, #498

**Comment by weiwee** [comment]
> Related: #781, #498

Thanks. This is a duplicate.  feel free to close this.

I simply move all windows to target space right now:
```sh
yabai -m query --spaces --space 1 | jq '.windows | .[]' | xargs -t -I{} yabai -m window {} --space 2
```

hope it helps.
