### ISSUE TITLE
Warning: Calling ENV.O2 is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by lebombastic** [koekeishiya/yabai#817]
Am getting that error and Yabai, SKHD is completely broken.

any help?
also below issue 
`==> Reinstalling koekeishiya/formulae/yabai
Warning: Calling ENV.O2 is deprecated! There is no replacement.
Please report this issue to the koekeishiya/formulae tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/yabai.rb:15

==> make install
Last 15 lines from /Users/abdo/Library/Logs/Homebrew/yabai/01.make:
xxd -i -a ./src/osax/loader ./src/osax/sa_loader.c
xxd -i -a ./src/osax/payload ./src/osax/sa_payload.c
xxd -i -a ./src/osax/loader ./src/osax/sa_loader.c
xxd -i -a ./src/osax/mach_bootstrap ./src/osax/sa_mach_bootstrap.c
xxd -i -a ./src/osax/payload ./src/osax/sa_payload.c
rm -f ./src/osax/loader
rm -f ./src/osax/payload
rm -f ./src/osax/mach_bootstrap
xxd -i -a ./src/osax/mach_bootstrap ./src/osax/sa_mach_bootstrap.c
xxd: ./src/osax/mach_bootstrap: No such file or directory
make: *** [src/osax/sa_loader.c] Error 2
make: *** Waiting for unfinished jobs....
xxd -i -a ./src/osax/loader ./src/osax/sa_loader.c
xxd: ./src/osax/loader: No such file or directory
make: *** [src/osax/sa_mach_bootstrap.c] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/koekeishiya/homebrew-formulae/issues
`

**Comment by koekeishiya** [comment]
Merged PR referenced by @dominiklohmann. Closing as resolved.
