### ISSUE TITLE
Topmost still can't show pop up ?

### ISSUE THREAD

**Issue by Sulfyderz** [koekeishiya/yabai#819]
Hello,

I've already read this [issue](https://github.com/koekeishiya/yabai/issues/395) about topmost hiding pop-ups. Currently I use this command to "topmost" a window:
`fn - f : yabai -m window --toggle topmost;
yabai -m window --toggle zoom-fullscreen`

Behold what's going on when I use this command on a Chrome window. In the following screenshots, I wrote "goo" in the address bar.

Here, it's when I do **not** use the "topmost" command.
<img width="500" alt="Screen Shot 2021-02-01 at 14 00 14" src="https://user-images.githubusercontent.com/72023070/106463952-4f1c6680-6498-11eb-8146-a2d8cef1d825.png">

Here, it's the "topmost" case. As you can see, no suggestions at all.
<img width="500" alt="Screen Shot 2021-02-01 at 14 06 13" src="https://user-images.githubusercontent.com/72023070/106462771-d10b9000-6496-11eb-891e-93118bf9ea38.png">

I would like to know whether there is a possible improvement to force a window to show its own pop-ups. Is there any ?

EDIT: I have found something weird when I captured the screens for this post with the shortcut `cmd - shift - 5`. Indeed, when I selected the "capture selected window" option, the suggestions are back on the png. So strange.

Best regards.

**Comment by Sulfyderz** [comment]
Hello again,

I have found a solution ! Even though it is dirty, it works.
Here is the new command line:
`fn - f : yabai -m window --toggle topmost; yabai -m window --toggle zoom-fullscreen; yabai -m window --toggle topmost`

The difference ? I call again `yabai -m window --toggle topmost` at the end.

Hope it will help anybody else.

Have a good day,
Sulfyderz.

**Comment by koekeishiya** [comment]
Fixed in v6.0.0 #1887

**Comment by Sulfyderz** [comment]
Thank you for your great work !
