### ISSUE TITLE
Don't suggest editing sudoers with vim

### ISSUE THREAD

**Issue by srizzling** [koekeishiya/yabai#824]
Was reading the docs on enabling the script aditions for big sur and noticed the following instructions in the wiki:

```
sudo vim /private/etc/sudoers.d/yabai
```

A more safer approach to edit this file would be to use visudo.. or else sudo will be stuffed up..

```
sudo visudo /private/etc/sudoers.d/yabai
```

**Comment by koekeishiya** [comment]
Did you test this? Fairly certain that the correct command would be: `sudo visudo -f /private/etc/sudoers.d/yabai`

**Comment by koekeishiya** [comment]
Edited wiki.
