### ISSUE TITLE
Finder tabs break tiling

### ISSUE THREAD

**Issue by SpiCy0** [koekeishiya/yabai#825]
When finder is set to always use tabs, yabai will tile the window like there is another window next to it, instead of letting the tabbed window fill the screen. This happens with applications that use the same tab interface that finder does, such as MultiMC

**Comment by SpiCy0** [comment]
Switching to Amethyst for now, hope this gets fixed

**Comment by yanzhang0219** [comment]
Duplicate: https://github.com/koekeishiya/yabai/issues/68
