### ISSUE TITLE
MacOS 11.2 requires explicit --load-sa at each new login

### ISSUE THREAD

**Issue by BigTheta** [koekeishiya/yabai#827]
Self explanatory, every time I restart my Macbook I have to run `sudo yabai --load-sa` before I'm able to switch workspaces using the `yabai -m window --space #` command since upgrading to Big Sur 11.2.

**Comment by BigTheta** [comment]
Running `yabai-v3.3.7` installed from homebrew.

**Comment by alin23** [comment]
Upgrading the system also reverts the sudoers file to default. You might need to re edit that.

**Comment by alin23** [comment]
https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup

**Comment by BigTheta** [comment]
Ah. Never needed that before. It fixed it. Thank you.
