### ISSUE TITLE
Monocle space layout

### ISSUE THREAD

**Issue by Wes974** [koekeishiya/yabai#83]
Will the monocle space layout be a part of yabai ? It is currently the only thing keeping me on chunckwm
Thanks !

**Comment by koekeishiya** [comment]
I haven't decided yet if this is something I want to support.

**Comment by Sweenu** [comment]
@Wes974 It is not the exact same use case but you can use `yabai -m window --toggle zoom-fullscreen` if you just want to quickly have a window take the whole screen.

I used to use monocle for that but I think `zoom-fullscreen` will be sufficient for my use.

**Comment by koekeishiya** [comment]
I don't think this is something that I want to support. I don't find it particularly useful, at least not the way it was implemented prior in chunkwm.

**Comment by Wes974** [comment]
Damn that's too bad because I actually used it a lot. But well guess I'll either stay on chunkwm for now or I will look a bit more into yabai and see what I can do to configure it close to what I'm used to
Thanks !

**Comment by dominiklohmann** [comment]
I’m pretty sure that you can completely emulate the old behaviour using signals and a lot of shell scripts with queries. I wrote a note down trying to get something like this to work over the next few days when I have time.

**Comment by dominiklohmann** [comment]
Actually this is impossible currently. There's no .zoom-fullscreen attribute in `yabai -m query --windows --window` and caching this is unreliable because signals fire asynchronously. 

I'll open a separate issue for this.

**Comment by dominiklohmann** [comment]
@Wes974 Here are two pieces of code you can use to enter and leave monocle mode for a space:

```sh
# Set all windows on active space to zoom-fullscreen
yabai -m query --windows --space \
    | jq -re '.[] | select(."zoom-fullscreen" == 0) | .id' \
    | xargs -I{} yabai -m window {} --toggle zoom-fullscreen

# Set all windows on active space back to normal
yabai -m query --windows --space \
    | jq -re '.[] | select(."zoom-fullscreen" == 1) | .id' \
    | xargs -I{} yabai -m window {} --toggle zoom-fullscreen
```

You can either plug these into signals that trigger depending on the space you're on or just bind these oneliners to hotkeys in skhd to use them manually.

For example, you could write a script that only triggers if `yabai -m query --spaces --space | jq -re '.index == 2'` is true if you want to run this on space 2 only.

**Comment by dominiklohmann** [comment]
I came up with a well-working solution just like I mentioned above. I split it into two scripts, each taking an optional space arrangement-index as their argument (default: current space). The only downside currently is that it creates some temporary files and does not delete them, but these get deleted once you restart your computer.

cc/ @pcr910303 @Sweenu @Wes974 @koekeishiya as you seemed interested in this. Will also put this in the wiki with the next batch of edits.

### enable_monocle_mode

```sh
#! /usr/bin/env sh

current_space="$(yabai -m query --spaces --space | jq -re '.index')"
target_space="${1:-${current_space}}"
target_space_id="$(yabai -m query --spaces | jq -re ".[] | select(.index == ${target_space}) | .id")"

script=$(mktemp)
chmod +x $script
cat > $script <<- EOM
	yabai -m query --spaces --space | jq -re ".id == ${target_space_id}" \
		&& yabai -m query --windows --space \
			| jq -re '.[] | select(."zoom-fullscreen" == 0) | .id' \
			| xargs -I{} yabai -m window {} --toggle zoom-fullscreen
EOM

if [ "${current_space}" = "${target_space}" ]; then
	yabai -m query --windows --space \
		| jq -re '.[] | select(."zoom-fullscreen" == 0) | .id' \
		| xargs -I{} yabai -m window {} --toggle zoom-fullscreen
fi

yabai -m signal --add label="monocle_mode_${target_space_id}_space_changed" \
	event=space_changed action="${script}"

yabai -m signal --add label="monocle_mode_${target_space_id}_window_moved" \
	event=window_moved action="${script}"

yabai -m signal --add label="monocle_mode_${target_space_id}_window_created" \
	event=window_created action="${script}"

yabai -m signal --add label="monocle_mode_${target_space_id}_application_launched" \
	event=application_launched action="${script}"
```

### disable_monocle_mode

```sh
#! /usr/bin/env sh

current_space="$(yabai -m query --spaces --space | jq -re '.index')"
target_space="${1:-${current_space}}"
target_space_id="$(yabai -m query --spaces | jq -re ".[] | select(.index == ${target_space}) | .id")"

yabai -m signal --remove "monocle_mode_${target_space_id}_space_changed" 
yabai -m signal --remove "monocle_mode_${target_space_id}_window_moved"
yabai -m signal --remove "monocle_mode_${target_space_id}_window_created"
yabai -m signal --remove "monocle_mode_${target_space_id}_application_launched"

if [ "${current_space}" = "${target_space}" ]; then
	yabai -m query --windows --space \
		| jq -re '.[] | select(."zoom-fullscreen" == 1) | .id' \
		| xargs -I{} yabai -m window {} --toggle zoom-fullscreen
else
	script=$(mktemp)
	chmod +x $script
	cat > $script <<- EOM
		if yabai -m query --spaces --space | jq -re ".id == ${target_space_id}"; then
			yabai -m query --windows --space \
				| jq -re '.[] | select(."zoom-fullscreen" == 1) | .id' \
				| xargs -I{} yabai -m window {} --toggle zoom-fullscreen
			yabai -m signal --remove "monocle_mode_${target_space_id}_delay_disable"
		fi
	EOM

	yabai -m signal --add label="monocle_mode_${target_space_id}_delay_disable" \
		event=space_changed action="${script}"
fi
```

### Example usage

Remember that both scripts need executable permissions (`chmod +x /path/to/script`).

```
# enable monocle mode for space 2
enable_monocle_mode 2

# (try to) disable monocle mode for current space
disable_monocle_mode
```

**Comment by lucaorio** [comment]
Wow, I use the _monocle_ layout *a lot*. I will install yabai and give it a try tonight, but I'm sad to see it gone! :(

**Comment by dominiklohmann** [comment]
> How do we use yabai on a small laptop screen if monocle is not supported? Interested to know the alternative

You could either adapt my snippet from above or just use a separate space for everything.

**Comment by koekeishiya** [comment]
Your script above could simply use a floating space combined with the *--grid* command as well, instead of dealing with zoom-fullscreen all the time.

**Comment by dominiklohmann** [comment]
Floating spaces don't work well with `yabai -m window --focus next`, which means you'd have to use a different focussing command (or adapt it based on the layout of the currently focused space).

**Comment by mwz** [comment]
Lack of monocle layout is a major bummer for me as it is my primary layout in chunckwm 😢 With chunkwm no longer being maintained and monocle not supported in yabai I'm not sure now what the best thing to do is. Does chunkwm work on Catalina? @dominiklohmann does your script work without SIP being disabled? Have you worked out what is causing this window flickering that you mentioned earlier?

**Comment by pcr910303** [comment]
@dominiklohmann Looks like the monocle mode code isn't in the wiki... Just wanted to inform you 👍

**Comment by dominiklohmann** [comment]
The script would need to be adapted for recent versions of yabai @mwz, it can probably also be simplified a lot. I put this on my personal backlog, but that list is only getting longer currently (likewise, the wiki/docs website, which is pretty close to the top of that list @pcr910303).

A proper, more general solution to the monocle mode issue would be to add stacking support #203.

**Comment by dominiklohmann** [comment]
> That's enabling monocle-mode and shaking any window.

Yeah, the script is not very robust. It breaks with mouse actions, you're likely swapping window positions by dropping them onto each other here.

**Comment by x-ji** [comment]
I also used monocle a lot in `chunkwm`, similar to how I used a lot of `Tabbed` layout in XMonad. But now I realized it's actually not that bad to do without it. It forces me to think clearly about which app to put on which workspace. In most cases I end up with only one app per workspace, and it's always clear to which one I'm switching. If there's some app I temporarily don't need, I can just send it to workspace 9, for example.

**Comment by tekacs** [comment]
The place that I find myself using monocle is for browser windows - I keep all of them on space 2, stacked upon one another.

Thanks @dominiklohmann for the script that you wrote - it's made it practical for me to switch to yabai and continue with my current workflow.

I'm open to better suggestions for managing those windows though, if I'm missing a trick (BSP isn't practical with a dozen browser windows open, nor can I really spread them across spaces).

The best answer might be to have topic-specific windows and to put them in specific places (or whatnot), but keeping my browsers that organized might be difficult for me for now.

**Comment by x-ji** [comment]
FWIW I use plugins such as Vimium and Treetabs for my browser, so that I can switch to the tab I want immediately, without having to switch between multiple windows. Of course everybody might have different use cases though.

**Comment by x-ji** [comment]
@dominiklohmann Thanks for the script. It is a helpful workaround for now. I had to also add 

```
yabai -m window --focus prev
yabai -m window --focus next
```

as shortcuts into my `skhdrc` so that I can cycle between all windows properly. The default north/south/west/east cycling doesn't work for windows in such a desktop.

**Comment by danbee** [comment]
Going to throw in another upvote for monocle layout. I used this a bunch with chunkwm (especially when using just my laptop screen) and miss it a great deal since switching to Yabai.

**Comment by koekeishiya** [comment]
This is called "stack" in yabai and was added like 5months ago

**Comment by danbee** [comment]
@koekeishiya Oh, huh! I'll look that up, thanks!

**Comment by rjhilgefort** [comment]
For anyone that's reading this issue and trying to use the "stack" layout, I couldn't find docs on it, but found the commands to focus stacks in the code [here](https://github.com/koekeishiya/yabai/blob/8777db43b8551e0bc4e5c55d1e15bcbed52501a1/doc/yabai.1#L106). TL;DR, you can do it like this:

```
yabai -m window --focus stack.prev
yabai -m window --focus stack.next
yabai -m window --focus stack.first
yabai -m window --focus stack.last
yabai -m window --focus stack.recent
```

From there I modified my focus commands so they didn't care what layout I was in (bsp or stack)- they would focus/cycle regardless with the same key binds. That looks like this in my config:

```
alt - h : [[ $(yabai -m query --spaces --space | jq -re '.type') = "bsp" ]]\
          && yabai -m window --focus west\
          || yabai -m window --focus stack.prev
alt - j : [[ $(yabai -m query --spaces --space | jq -re '.type') = "bsp" ]]\
          && yabai -m window --focus south\
          || yabai -m window --focus stack.prev
alt - k : [[ $(yabai -m query --spaces --space | jq -re '.type') = "bsp" ]]\
          && yabai -m window --focus north\
          || yabai -m window --focus stack.next
alt - l : [[ $(yabai -m query --spaces --space | jq -re '.type') = "bsp" ]]\
          && yabai -m window --focus east\
          || yabai -m window --focus stack.next
```

Hope this helps someone trying to reproduce what Monocle was for Chunkwm like I am!

**Comment by Bellavene** [comment]
Stacking all windows of an application in a space if there are no less than two windows.

```
#!/bin/zsh
# Get all the windows on current space
######################################
local CURRENT_DISPLAY=$(/opt/homebrew/bin/yabai -m query --windows --window | /opt/homebrew/bin/jq '.display')
local WINDOWS_ARRAY=$(/opt/homebrew/bin/yabai -m query --windows --space $(/opt/homebrew/bin/yabai -m query --spaces --space | /opt/homebrew/bin/jq '.index') --display $CURRENT_DISPLAY | /opt/homebrew/bin/jq -r 'map(select(.["is-minimized"]==false and .["is-floating"]==false))')

# Get the number of windows on the current space
################################################
local NUMBER_OF_WINDOWS=$(echo $WINDOWS_ARRAY | /opt/homebrew/bin/jq -r 'length')
local WINDOW=$(/opt/homebrew/bin/yabai -m query --windows --window | /opt/homebrew/bin/jq -r '.id')

# If we are Less than or equal to 2 windows on current space exit script
########################################################################
if (( $NUMBER_OF_WINDOWS > 2 )); then
	# Stack first instance of application when more than 2 windows
	##############################################################
	local APP_ID=$(echo $WINDOWS_ARRAY | jq -r '(.[] | select(."has-focus")) as {$id, $app} | map( select( .app==$app and ((."is-hidden" or ."is-minimized") | not) ) )' | /opt/homebrew/bin/jq -r 'map(select(.app)) | .[] | .id' | awk 'END{print}')
	/opt/homebrew/bin/yabai -m window $APP_ID --stack $WINDOW
else
    exit 1
fi

```

yabai -m signal --add event=window_created action="~/bin/yabai-stack-app"

**Comment by koekeishiya** [comment]
You can just use the `stack` layout

**Comment by Bellavene** [comment]
Sure, just sharing workarounds I've tried. Those signal scripts are mostly crutches, for sure.

**Comment by Bellavene** [comment]
And stack layout doesn't match my needs, because sometimes, as an example, I want to preview something externally and don't change focus from my app, in that case the preview window will be stacked above.

Here I got stacked terminal windows while pressed TAB to open file preview window.
<img width="1680" alt="Screenshot 2023-01-30 at 23 15 40" src="https://user-images.githubusercontent.com/77557804/215585948-0f1c2858-4f55-408e-a420-27073abb5f9f.png">
