### ISSUE TITLE
insert feedback doesn't disappear after toggle float windows

### ISSUE THREAD

**Issue by tshu-w** [koekeishiya/yabai#832]
I want to stack and unstack windows #708 . Inspired by @danielfalbo in https://github.com/koekeishiya/yabai/issues/203#issuecomment-706675848 I made following shortcuts:
```
# stack or moved managed window
shift + cmd - h : yabai -m window --stack west \
    || (yabai -m window --insert west; yabai -m window --toggle float; yabai -m window --toggle float)
shift + cmd - j : yabai -m window --stack south \
    || (yabai -m window --insert south; yabai -m window --toggle float; yabai -m window --toggle float)
shift + cmd - k : yabai -m window --stack north \
    || (yabai -m window --insert north; yabai -m window --toggle float; yabai -m window --toggle float)
shift + cmd - l : yabai -m window --stack east \
    || (yabai -m window --insert east; yabai -m window --toggle float; yabai -m window --toggle float)
```
Although the window can be unstacked where I want it to be, the insertion feedback does not disappear after two toggle window floats, which is annoying. BTW, I also meet issue #791.

yabai-v3.3.7
macOS 11.2.1

**Comment by koekeishiya** [comment]
I'm unable to reproduce this bug on `the-future` branch using the provided binds.

**Comment by tshu-w** [comment]
To be clear, maybe I didn't describe it well, I found that this problem only occurs in the current window stack on top of other windows. yabai 3.3.10
