### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by TheCultLeader666** [koekeishiya/yabai#835]
Whenever I run the command to install yabai I get this error: `Error: The following formula cannot be installed from bottle and must be built from source.`

**Comment by TheCultLeader666** [comment]
I'm able to install the dev version, but not the release version

**Comment by TheCultLeader666** [comment]
Would I be able to build in from source by just cloning the repo and running make? Would I have to symlink it to /usr/path/bin/?

**Comment by koekeishiya** [comment]
Simply building from source is as simple as cloning the repo and running make, yes. If you want to build the manpage, supply the icon, codesign etc. you need to do some additional steps.

The makefile only builds the program. You probably want to either copy or symlink the built files into somewhere in your path. This you do manually yourself.

**Comment by TheCultLeader666** [comment]
I'm probably going to stick with the dev version, since it's neatly controlled through brew services

**Comment by koekeishiya** [comment]
I am unable to reproduce the issue with brew. Both `brew install yabai` and `brew install yabai --HEAD` works fine for me.

**Comment by TheCultLeader666** [comment]
I uninstalled and tried again, seemed to work
