### ISSUE TITLE
Dock overlaps floating windows in Big Sur

### ISSUE THREAD

**Issue by iam-cult** [koekeishiya/yabai#836]
When yabai is running in macOS Big Sur, the dock overlaps topmost windows, as well as context menus and dropdowns, as shown in the following screenshots:

**With yabai running**
![Screen Shot 2021-02-14 at 10 49 33](https://user-images.githubusercontent.com/65368815/107881482-6fa6e080-6edc-11eb-8511-98388402dfa7.png)
![Screen Shot 2021-02-14 at 10 52 40](https://user-images.githubusercontent.com/65368815/107881560-c4e2f200-6edc-11eb-919e-f5b1e0898089.png)

**Without yabai running**
![Screen Shot 2021-02-14 at 10 55 07](https://user-images.githubusercontent.com/65368815/107881654-3753d200-6edd-11eb-9636-545273a7c3e0.png)
![Screen Shot 2021-02-14 at 10 55 40](https://user-images.githubusercontent.com/65368815/107881665-42a6fd80-6edd-11eb-87ec-83a4462a49f7.png)

**Comment by TheCultLeader666** [comment]
The menubar has the same behavior

**Comment by koekeishiya** [comment]
Sounds like an issue with `yabai -m config window_topmost on`.

**Comment by Midren** [comment]
Having similar issues with configuration color in iTerm2

<img width="319" alt="зображення" src="https://user-images.githubusercontent.com/32875119/112678517-affe6480-8e73-11eb-9b42-d4bfbabee803.png">

**Comment by koekeishiya** [comment]
Fixed in v6.0.0 #1887
