### ISSUE TITLE
Closing window

### ISSUE THREAD

**Issue by Sweenu** [koekeishiya/yabai#84]
I see no way of closing a window like there used to be on chunkwm: `chunkc tiling::window --close`.
Am I missing some other way to do it?

**Comment by dominiklohmann** [comment]
Currently not possible. Workaround: `skhd --key "cmd - w"`.

**Comment by dominiklohmann** [comment]
Here's a better workaround that does essentially the same that `chunkwm` did. Will work a little more consistent than emulating the keypress.

```sh
osascript -e 'tell application "System Events" to perform action "AXPress" of (first button whose subrole is "AXCloseButton") of (first window whose subrole is "AXStandardWindow") of (first process whose frontmost is true)'
```

**Comment by Sweenu** [comment]
Thank you! Works well indeed :)

Out of curiosity, is there a technical problem making this impossible to implement as it was on chunkwm?

**Comment by koekeishiya** [comment]
No technical issue. Just didn't get around to it yet.

**Comment by koekeishiya** [comment]
I don't think this is necessary to add considering how easy it is to do with applescript.

**Comment by dominiklohmann** [comment]
So the downside of the AppleScript implementation above is that it is not possible to trigger this on windows other than the frontmost window. Should this be reconsidered, considering `yabai -m window [<window_sel>] --destroy` could be probably work on all windows instead of just the focused one?

**Comment by koekeishiya** [comment]
Implemented on master.

**Comment by pm0u** [comment]
I realize this issue is closed but I could not find documented in the wiki the proper syntax to close a window --

```
yabai -m window --close
```

**Comment by typkrft** [comment]
> I realize this issue is closed but I could not find documented in the wiki the proper syntax to close a window --
> 
> ```
> yabai -m window --close
> ```
> 
> for those who land here looking

This is a really good documentation. 
https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#642-command

**Comment by pm0u** [comment]
@typkrft thanks! that is really helpful. don't want continue to derail this already closed issue, but I am confused why this is out of sync with the wiki. I'll look into that and see if it's somewhere I could help

**Comment by typkrft** [comment]
> @typkrft thanks! that is really helpful. don't want continue to derail this already closed issue, but I am confused why this is out of sync with the wiki. I'll look into that and see if it's somewhere I could help

No worries, it's probably just easier to maintain and probably somethings are out of whack while M1 stuff gets sorted out. It's mentioned here and there in issues, but haven't looked at the wiki in a while. IDK if PRs for documentation are welcome or wise at this moment, but if anyone reads this I'm happy to volunteer some time.
