### ISSUE TITLE
Yabai starts without scripting additions, but nothing indicates that it's running (Big Sur 11.2.1)

### ISSUE THREAD

**Issue by BlkPingu** [koekeishiya/yabai#841]
From [the previous thread](https://github.com/koekeishiya/yabai/issues/838#issuecomment-780281037):

> That is, if you don't want to use the advanced features, you don't need to install the scripting addition and you can keep SIP being fully enabled.

@yanzhang0219 How do I start yabai without advanced features? Homebrew does start yabai with `brew services start yabai` but nothing indicates it. Meaning, my windows don't actually move into tiles or anything. Like Yabai isn't working.

**Comment by yanzhang0219** [comment]
Try to follow this (https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)) but skip the "install the scripting addition" part. Then using brew to start yabai service. Of course "Automatically load scripting addition on startup" is not necessary. I think it should work.

**Comment by koekeishiya** [comment]
You don't need to do anything special; just start yabai without installing the scripting-addition, done.

> Meaning, my windows don't actually move into tiles or anything.

Did you actually make a yabai configuration file?

**Comment by BlkPingu** [comment]
@koekeishiya  Yes I have. Also, according to brew, I have yabai 3.3.7 installed. I have not yet messed with SIP.

```
▶ cat ~/.yabairc
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
```

**Comment by yanzhang0219** [comment]
Use this (https://github.com/koekeishiya/yabai/blob/master/examples/yabairc) as your yabairc first and try whether yabai works. Because you keep the SIP enabled, so `-sa` line is not necessary and you can remove it.

**Comment by BlkPingu** [comment]
Works like a charm now, thank you
