### ISSUE TITLE
hyper + <mod> doesn't seem to work

### ISSUE THREAD

**Issue by ThSGM** [koekeishiya/yabai#843]
The following does work: 

```
# focus window
hyper - h : yabai -m window --focus west
hyper - j : yabai -m window --focus south
hyper - k : yabai -m window --focus north
hyper - l : yabai -m window --focus east

# move window
cmd + shift - h : yabai -m window --warp west
cmd + shift - j : yabai -m window --warp south
cmd + shift - k : yabai -m window --warp north
cmd + shift - l : yabai -m window --warp east
```

but if I replace "cmd" with "hyper" in the second set of commands, it does not work. It seems that hyper + <mod> doesn't work. Here, I've set up the hyper key via Karabiner.

**Comment by tshu-w** [comment]
`hyper`(cmd + shift + alt + ctrl) in skhd is different in Karabiner? A list of all built-in modifier and literal keywords of skhd can be found https://github.com/koekeishiya/skhd/issues/1#issue-248494406

**Comment by ThSGM** [comment]
@tshu-w  You're right. I'm an idiot and the shift key is already part of hyper!

**Comment by gerardbosch** [comment]
I don't know much about the details, but with http://capslock.vonng.com modifications (via Karabiner-elements), a new <kbd>Hyper</kbd> key is created (replacing the <kbd>Caps Lock</kbd>) that acts as <kbd>R Ctrl</kbd> + <kbd>R Opt</kbd> + <kbd>R Cmd</kbd> + <kbd>R Shift</kbd>.

And, using this setup, hyper is treated somehow as a new key, and as such it can be mixed with other left modifiers to allow extra functionality like: <kbd>Hyper</kbd> + <kbd>Left Cmd</kbd>.

Can this be achieved in skhd? or is it possible to redefine skhd built-in Hyper definition to use right modifiers and leave left modifiers to further combine with hyper? Thx!

**Comment by gerardbosch** [comment]
This is what I get when I hold down the <kbd>Hyper</kbd> key (the Caps Lock).

![image](https://user-images.githubusercontent.com/30733556/115003038-b0ec4a00-9ea5-11eb-85f8-c5c173489c8d.png)

And something similar (just different flags) shows when I hold <kbd>R Shift</kbd>

![image](https://user-images.githubusercontent.com/30733556/115003872-8222a380-9ea6-11eb-97e6-a879521a7f81.png)

that does not match the expected `38` for Shift according to https://github.com/koekeishiya/skhd/issues/1

**Comment by justdanyul** [comment]
> I don't know much about the details, but with http://capslock.vonng.com modifications (via Karabiner-elements), a new Hyper key is created (replacing the Caps Lock) that acts as R Ctrl + R Opt + R Cmd + R Shift.
> 
> And, using this setup, Hyper can be mixed with other left modifiers to allow extra functionality like: Hyper + Left Cmd.
> 
>     * Can this be achieved in skhd? or is it possible to redefine skhd built-in Hyper definition to use right modifiers and leave left modifiers to further combine with hyper? Thx!
> 
> 
> P.S. I can think on things like "Move window to next space": Hyper + L Shift + L

I'd love to be able to do this as well. Comparing with my i3wm setup, having a hyper + shit style modifier (that doesn't clash with other things) one of the few things that i find myself missing
