### ISSUE TITLE
Question about moving window off top of screen while holding mouse_modifier

### ISSUE THREAD

**Issue by mbigras** [koekeishiya/yabai#844]
Hello!

Is it possible to move a window off the top of the screen while holding the mouse modifier?

It's possible to drag off-screen to the left, right, and bottom. I guess macOS doesn't want someone to do it off the top because then they would lose view of the top bar of a window which is used for moving a window natively. I use yabai's mouse modifier to move my windows so I don't put my mouse on the top bar to move a window. I think it would be very cool to have the laptop screen be like a viewport into a much larger desktop that extends beyond to the left, right, bottom, *and* top. I know it's possible for a window to be shown moving off the top of the screen because using the ["Show desktop" gesture](https://support.apple.com/en-us/HT204895) windows will move off the top of the screen but I don't know if a single window can be moved off the top.

As a tangent, moving windows with yabai by holding the default `mouse_modifier` is great! I also have macOS 3 finger drag Accessibility setting enabled  which makes moving windows very easy because I don't click, I just hold `fn` then touch the trackpad with 3 fingers and drag the window wherever I want.

**Comment by dominiklohmann** [comment]
I don't think this can be done.

Show Desktop is just a visual transformation, it doesn't actually move the windows.

**Comment by koekeishiya** [comment]
This is actually not supported by macOS itself, which is why I had to implement a bounds check here: https://github.com/koekeishiya/yabai/blob/master/src/event.c#L728

**Comment by mbigras** [comment]
Thank you for answering my question!
