### ISSUE TITLE
Functions and Variables Not Available to Yabai in .yabairc

### ISSUE THREAD

**Issue by typkrft** [koekeishiya/yabai#847]
I am trying to understand why variables and functions that I have written in my .yabairc aren't working. 
I'm running --head and starting it with `brew services start yabai`.

For instance, I created a hacky function to move between spaces

```SHELL
move_spaces()
{
    CURRENT_SPACE=$(yabai -m query --spaces| jq '[.[]|select(.focused==1)][0].index')
    TOTAL_SPACES=$(yabai -m query --spaces| jq '. | length')
    DESIRED_SPACE=$1

    if [ $DESIRED_SPACE -lt $CURRENT_SPACE  ]; then 
        n=0
         while [ "$n" -lt  $(($CURRENT_SPACE-$DESIRED_SPACE)) ]; do
             osascript -e "tell application \"System Events\" to key code 123 using control down"
              n=$(( n + 1 ))
          done
    fi

     if [ $DESIRED_SPACE -gt $CURRENT_SPACE  ]; then 
         n=0
         while [ "$n" -lt $(($DESIRED_SPACE - $CURRENT_SPACE)) ]; do
             osascript -e "tell application \"System Events\" to key code 124 using control down"
                        n=$(( n + 1 ))
          done
     fi
}
```

Then I reference it in this signal.

```SHELL
yabai -m signal --add event=application_activated app='^App Store$' action="move_spaces 5"
```

If I start yabai from my terminal it functions as expected. If I start it from brew the logs state `sh: move_spaces: command not found`

I know there's an issue with this information not being part of the env that Yabai is running in, but I'm an idiot and I don't really understand what the proposed solution or work around would be.

Any guidance or help would be greatly appreciated. Thanks!

**Comment by koekeishiya** [comment]
You can use: yabai -m signal --list to see the actual command that is resolved and passed to yabai in both cases and use that to guide your debugging.

Sent from my iPhone

On 24 Feb 2021, at 10:37, Brandon Shockley <notifications@github.com> wrote:

﻿

I am trying to understand why variables and functions that I have written in my .yabairc aren't working.
I'm running --head and starting it with brew services start yabai.

For instance, I created a hacky function to move between spaces

        move_spaces()
        {
            CURRENT_SPACE=$(yabai -m query --spaces| jq '[.[]|select(.focused==1)][0].index')
            TOTAL_SPACES=$(yabai -m query --spaces| jq '. | length')
            DESIRED_SPACE=$1
            echo $(($CURRENT_SPACE-$DESIRED_SPACE))
            echo Curent Space $CURRENT_SPACE Desired Space $DESIRED_SPACE Total Spaces $TOTAL_SPACES

            if [ $DESIRED_SPACE -lt $CURRENT_SPACE  ]; then
                echo 1
                n=0
                while [ "$n" -lt  $(($CURRENT_SPACE-$DESIRED_SPACE)) ]; do
                    osascript -e "tell application \"System Events\" to key code 123 using control down"
                    n=$(( n + 1 ))
                done

                # repeat $(($CURRENT_SPACE-$DESIRED_SPACE)) {
                #     osascript -e "tell application \"System Events\" to key code 123 using control down"
                # }
            fi

                if [ $DESIRED_SPACE -gt $CURRENT_SPACE  ]; then
                    n=0

                    while [ "$n" -lt $(($DESIRED_SPACE - $CURRENT_SPACE)) ]; do
                        osascript -e "tell application \"System Events\" to key code 124 using control down"
                        n=$(( n + 1 ))
                    done

                # repeat  {
                #     osascript -e "tell application \"System Events\" to key code 124 using control down"
                # }
            fi
        }

Then I reference it in this signal.

yabai -m signal --add event=application_activated app='^App Store$' action="move_spaces 5"

If I start yabai from my terminal it functions as expected. If I start it from brew the logs state sh: move_spaces: command not found

I know there's an issue with this information not being part of the env that Yabai is running in, but I'm an idiot and I don't really understand what the proposed solution or work around would be.

Any guidance or help would be greatly appreciated. Thanks!

**Comment by typkrft** [comment]
Thanks for the tip. The list does show the command as expected. It just seems to not know where the function is despite being declared in the config file itself. 

```JSON
,{
	"index":4,
	"label":"",
	"app":"^App Store$",
	"title":"",
	"event":"application_activated",
	"action":"move_spaces 5"
},
```

**Comment by typkrft** [comment]
I ended up just creating executables for each function and referencing them explicitly.
