### ISSUE TITLE
Config script failure should trigger a notification

### ISSUE THREAD

**Issue by DavidDTA** [koekeishiya/yabai#848]
If the config script exits with a nonzero status, yabai should show a notification about that error, like it does if there is no config file.

I just spent a while wondering why one of the yabai messages in my config script wasn't working.  It turns out that it's because I had a typo.

**Comment by DavidDTA** [comment]
It looks like the problem is that fork_exec returns true [as soon as the fork succeeds](https://github.com/koekeishiya/yabai/blob/master/src/misc/helpers.h#L236), without waiting to determine whether the command executed successfully.

**Comment by koekeishiya** [comment]
not realistic with how Yabai is designed.

**Comment by DavidDTA** [comment]
Could you give some more detail about why this is unrealistic? The parent process is able to monitor its children, and can await their exit status.

**Comment by koekeishiya** [comment]
The Yabai config file is a shell script consisting of multiple commands that are sending messages on the yabai socket. yabai's main thread needs to run to receive events from the system and the event loop thread needs to run for the commands in the config to properly communicate with yabai.

I suppose the config could be executed on a background thread which simply waits and reads the exit code and signals the user through a system notification scheduled on the main thread or something, but I don't particularly see a value in that. 

The config is usually very basic in which the exit code does not matter. Other configs are advanced and contain a huge amount of scripting and setup, in which case it is not really helpful to know that "something in the config failed".

Commands return exit codes and errors in the config file should be handled gracefully by the user. It is also possible to notify yourself of errors using notifications by spawning them directly from inside the script itself.

**Comment by DavidDTA** [comment]
Another way to accomplish this could be to have the forked config execute a wrapper that executes the config and spawns a message if an error occurs.

This feature would be most useful during development of config files, in which case the "something" that went wrong would generally be the thing part that was changed.  I agree that for stable config files, they should handle their own errors.
