### ISSUE TITLE
`yabai -m space --focus next` but constrain to current display?

### ISSUE THREAD

**Issue by braham-snyder** [koekeishiya/yabai#849]
Currently, if you're on the last space of a display, `yabai -m space --focus next` focuses the next space by number even if that next space is on a different display. Similarly for `prev`. 

Is there a built-in way to make it a no-op instead? Or should I use `query`?

**Comment by yanzhang0219** [comment]
Yep. You could take advantage of `query`. Try this binding in `skhdrc`: 

```
alt - n : [[ $(yabai -m query --spaces --space | jq '.index' ) != $(yabai -m query --displays --display | jq '.spaces | length') ]] && yabai -m space --focus next
```

It will focus on the next space only if it doesn't reach the last space of the current display. 

Hope it is helpful. Thanks.
