### ISSUE TITLE
cannot disable SIP Debugging Restrictions on BigSur - unable to load SA

### ISSUE THREAD

**Issue by kodydeda4** [koekeishiya/yabai#850]
Hello everyone!
I'm trying to load the SA.  I'm running:
- Yabai 3.3.7  
- Big Sur 11.2.1  
- MacBook Pro (15-inch, 2018) i7, 16GB Ram , 512GB, Radeon 560X  

I booted into recovery mode & ran the command:  
`csrutil enable --without debug --without fs`

But running `sudo yabai --load-sa` outputs:  
`yabai: System Integrity Protection: Debugging Restrictions must be disabled!`

The output of `csrutil status` indicates Debugging Restrictions are still enabled:  
`Configuration:
Apple Internal: disabled  
    Kext Signing: enabled  
    Filesystem Protections: disabled  
    Debugging Restrictions: enabled  
    DTrace Restrictions: enabled  
    NVRAM Protections: enabled  
    BaseSystem Verification: enabled`

I could not find a solution so I posted here as a last resort.  
Thank you!

**Comment by yanzhang0219** [comment]
Please refer to this wiki page carefully (https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection)

> I booted into recovery mode & ran the command:
csrutil enable --without debug --without fs

On Big Sur, you should use
```
csrutil disable --with kext --with dtrace --with nvram --with basesystem
```

**Comment by kodydeda4** [comment]
Thank you so much!
