### ISSUE TITLE
Multi tabs in Preview and Finder

### ISSUE THREAD

**Issue by junwei-wang** [koekeishiya/yabai#852]
If several tabs are opened in Preview or Finder, yabai would regards them as multiple windows.

Here is an example:
<img width="1664" alt="Screenshot 2021-03-04 at 11 59 35" src="https://user-images.githubusercontent.com/866329/109954801-0dbee700-7ce2-11eb-8693-ecc3e6c63668.png">

I opened two tabs in Finder. Yabai leave some empty space for one of the tab.

**Comment by dominiklohmann** [comment]
Duplicate of #68

**Comment by junwei-wang** [comment]
OK. Thank you. I close this issue.
