### ISSUE TITLE
Yabai doesn't launch on startup.

### ISSUE THREAD

**Issue by mohabariza** [koekeishiya/yabai#853]
I'm using a 13" MacBook Air 2019, and I've recently installed yabai. When I restart my Mac, it makes Yabai stop working, but when I go back into the terminal to start it, it says that it's already on. I have to go back to my Yabairc file to run it again. On a possibly related note, I couldn't create a /.config folder so I made a /config folder. Could this be the root of my problem?

**Comment by 24unix** [comment]
I yabai isn't terminated correctly, there might be leftover lockfiles.
In Terminal:
rm /tmp/yabai*

yabai doesn't look into a folder named ~/config. It looks for $XDG_CONFIG_HOME/yabai/yabairc, ~/.config/yabai/yabairc or .yabairc and takes the first it finds.

To create the folder run "mkdir -p ~/.config/yabai"

**Comment by mohabariza** [comment]
Thanks!
