### ISSUE TITLE
[Feature Request] Focusing next clockwise or counterclockwise window

### ISSUE THREAD

**Issue by jsn-li** [koekeishiya/yabai#856]
I'm currently using a keymap where I use two keys to cycle window focus, which I prefer over using four directional keys. However, the `window --focus next` and `prev` commands do not consistently go in any specific direction, which is not great for muscle memory. I think it would be nice to have a command specifically to select the next clockwise/counterclockwise window, similar to [Amethyst](https://ianyh.com/amethyst/). Any thoughts?

**Comment by rcorre** [comment]
This roughly works for cycling through windows in the same space (though isn't always perfectly clockwise/counterclockwise), and gets closer to the [dwm](https://dwm.suckless.org/)-style behavior I've been looking for:

```
cmd - j : yabai -m window --focus $(yabai -m query --windows --space | jq 'sort_by(.id) | .[(to_entries | .[] | select(.value.focused == 1) | .key + 1) % length] | .id')
cmd - k : yabai -m window --focus $(yabai -m query --windows --space | jq 'sort_by(.id) | .[(to_entries | .[] | select(.value.focused == 1) | .key - 1) % length] | .id')
```

It works in both `stack` and `bsp`.

Credit to https://github.com/koekeishiya/yabai/issues/83#issuecomment-875748192 for inspiration.
