### ISSUE TITLE
FR: Rename spaces in Mission Control to match Labels

### ISSUE THREAD

**Issue by Liquidmantis** [koekeishiya/yabai#857]
It'd be great if the Spaces labels showed up in the UI as well.  I found https://github.com/dado3212/spaces-renamer, which lets you rename spaces (surprise!) but it would be nice to not require a separate app just for that functionality.

**Comment by kvndrsslr** [comment]
Just fyi, some Uebersicht widgets for yabai like [simple-bar](https://github.com/Jean-Tinland/simple-bar) do include that functionality and make the lot of mission control obsolete imho.

**Comment by Liquidmantis** [comment]
Thanks!  Übersicht is on my "get around to checking out" list but I'm not running it yet.  Right now I run my desktop in "zen mode" without a menubar or dock, but I'm sure there's a way to dynamically allocate space and toggle visibility of Übersicht widgets.

**Comment by koekeishiya** [comment]
Out of scope for this project.
