### ISSUE TITLE
Yabai placing windows on incorrect display and desktop

### ISSUE THREAD

**Issue by ChrisOlsonFilms** [koekeishiya/yabai#859]
For a bit now I've used Yabai to manage which spaces apps were placed in. For the last handful of months it has been really inconsistent. I have 3 displays and frequently an app that is supposed to open on display 3 will open there, and then immediately move to my middle monitor. Sometimes it goes to the correct one, other times it does not. Most of the time it sends it to the wrong display.

I tried disabling my Yabai rules to control windows and instead used the native way MacOS has for managing which apps are in which space. This also has inconsistent results. As soon as I disable Yabai though, all applications are managed correctly and the issue goes away.

Any ideas? Running MacOS Mojave 10.14.6 Yabai 3.3.7.

**Comment by heywoodlh** [comment]
I seem to have the same issue but with one monitor. My apps will open on the wrong virtual desktop for me. Not sure why.

**Comment by Smingvin** [comment]
Same experience.

For example, I have three displays indexed like this, the left one is #2, the central one is #1, and the right one is #3

I have this rule in my yabairc:

```
yabai -m rule --add app="^Chromium$" display=^3
```

But when I launch Chromium, Yabai alternates between display #3 and #1 between consecutive launches (as in, launch chromium > window goes to display #3 > close Chromium > relaunch Chromium > window goes to display #1 > close > relaunch > goes to display #3 etc)

(same behavior as described by @ChrisOlsonFilms, each time the window is launched on one display then jumps to the other)

The same happening with, for example, mac vim, which alternates between screens #2 and #1.

Extra info for what it's worth:
* Yabai to version 3.3.7
* MacOS Catalina 10.15.7
* Freshly reinstalled Scripting Addition, or removing then reinstalling yabai... neither of those doesn't solve the problem

**Comment by caltuntas** [comment]
I'm a new Yabai user, and I like it. However I have been experiencing the same issue with a single display. It's really frustrating almost randomly  placing the windows sometimes.
