### ISSUE TITLE
Request: Don't un-zoom windows when a new window is added

### ISSUE THREAD

**Issue by Peeja** [koekeishiya/yabai#864]
When a new window appears, any windows that are currently zoomed (fullscreen or parent) become un-zoomed as the new layout is set up. I sometimes run with several windows zoomed, and when I open a new window (or unminimize a window, or native-fullscreen/un-fullscreen a windows), have to set all that up again.

It appears that zoomed windows still take up their normal "slot" in the layout, but are then sized to their zoomed size. When a new window is added, I'd like to have yabai recompute the layout as it currently does, but also keep zoomed windows zoomed. For `zoom-fullscreen`ed windows, that means they'll keep their size and position (the whole screen), but the place they'll return to if they're unzoomed will change. For `zoom-parent`ed windows, that may mean that they move (if their parent ends up moving), but they'll still be `zoom-parent`ed. (I don't really have an opinion on whether I want this for `zoom-parent`ed windows, but that sounds like the simplest, most logical thing to do if this behavior is changed, and I'd be happy with it.)

My gut feeling is that this would be a better default behavior than resetting the zooms as it does today, but obviously I'm biased because I'm asking for the feature. 😃 I'd be grateful just to have it as an available option.

**Comment by macintacos** [comment]
I was pretty surprised that this wasn't the default behavior if I'm honest. Would love to see this implemented.

**Comment by koekeishiya** [comment]
Fixed on master.

**Comment by nikita-orca** [comment]
@koekeishiya could you please take a look https://github.com/koekeishiya/yabai/issues/1481?
This featured caused regression
