### ISSUE TITLE
Yabai asks for accessibility access every few seconds

### ISSUE THREAD

**Issue by danijar** [koekeishiya/yabai#867]
When installing yabai following the instructions in the wiki, the normal popup appears to ask for accessibility access. However, with the current release and dev versions, closing the popup just opens another one. Even after granting permissions, I had a backlog of 10 popups to close. The popups stop appearing after granting permissions, so after that yabai is usable as normal.

I already had skhd with yabai command in its config running, so it's possible that that's causing it. Unfortunately, I don't have time to dig into this much more, but I thought I'd post it anyway in case others are running into a similar problem.

**Comment by cwqt** [comment]
I find I get this when running `brew services start yabai` but not from running `yabai &` direct in cli, using `yabai-v4.0.0` m1 monterey

**Comment by rosenpin** [comment]
> I find I get this when running `brew services start yabai` but not from running `yabai &; disown` direct in cli, using `yabai-v4.0.0` m1 monterey

I am facing the exact same issue

**Comment by Devric** [comment]
> > I find I get this when running `brew services start yabai` but not from running `yabai &; disown` direct in cli, using `yabai-v4.0.0` m1 monterey
> 
> I am facing the exact same issue. Started happening after the 12.1 Monterey update

I had this issue with my M1 at first and found that my termibal emulator (Im using alacrity) was not arm64. Rebuild alacrity and than remove and reinstall yabai with arm64 again. This issue went away.

**Comment by Liquidmantis** [comment]
@Devric thanks for sharing that!  I recently switched from Alacritty to Kitty so I tried uninstalling and reinstalling Yabai and now I'm back in business.  Plus I have an actual icon for Yabai in the Accessibility settings.

**Comment by Liquidmantis** [comment]
Actually, looks like things are in a weird state for me.  Yabai keeps crashing due to a segmentation fault and restarting.  So, I uninstalled Yabai and used brew to install from HEAD, but now I'm back to the infinite prompt for accessibility features.

**Comment by koekeishiya** [comment]
You need to codesign the binary. See the building from source instructions in the wiki.

**Comment by Liquidmantis** [comment]
There we go!  Now I'm back in business.  I was set up to do that but it's been a while and I forgot about it.  🤦 
Thanks!

**Comment by rcorre** [comment]
I installed HEAD with `brew`, and I get this when I run `brew services start yabai` even after codesigning
<img width="657" alt="Screen Shot 2022-03-16 at 10 44 06 AM" src="https://user-images.githubusercontent.com/2496231/158616495-eaaa1680-1fb4-4549-b056-c36bf8241963.png">


```[rrc@RRCs-MacBook-Pro ~]$ codesign -dv --verbose=4 $(which yabai)
Executable=/opt/homebrew/Cellar/yabai/HEAD-34d31e8/bin/yabai
Identifier=yabai
Format=Mach-O universal (x86_64 arm64)
CodeDirectory v=20400 size=6686 flags=0x0(none) hashes=204+2 location=embedded
VersionPlatform=1
VersionMin=720896
VersionSDK=787200
Hash type=sha256 size=32
CandidateCDHash sha256=3fab5bccf1dce38f27170a432f61d81b92612b61
CandidateCDHashFull sha256=3fab5bccf1dce38f27170a432f61d81b92612b613608a5d2249909a5a74ec4df
Hash choices=sha256
CMSDigest=3fab5bccf1dce38f27170a432f61d81b92612b613608a5d2249909a5a74ec4df
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=229376
Executable Segment flags=0x1
Page size=4096
CDHash=3fab5bccf1dce38f27170a432f61d81b92612b61
Signature size=1662
Authority=yabai-cert
Signed Time=Mar 16, 2022 at 10:39:46 AM
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=84```

**Comment by ryderdain** [comment]
@rcorre had this issue today after upgrading HEAD via `brew upgrade` ; the standard code-signing only worked after explicitly codesigning the binary and re-adding *it*, not the symlink, to the list in System Preferences >> Security & Privacy >> Privacy >> Accessibility.

That is, running `codesign -fs 'yabai-cert' $(which yabai)` and approving that to the System Prefs didn't work, _presumably_ because that's a symlink to the file rather than the code itself:
```
$ ls -l $(which yabai)
lrwxr-xr-x  1 xxxx  admin  38 Mar 17 10:23 /opt/homebrew/bin/yabai -> ../Cellar/yabai/HEAD-a4030e7/bin/yabai
$ codesign -fs 'yabai-cert' /opt/homebrew/Cellar/yabai/HEAD-a4030e7/bin/yabai
/opt/homebrew/Cellar/yabai/HEAD-a4030e7/bin/yabai: replacing existing signature
```

**Comment by rcorre** [comment]
That worked, thanks @ryderdain! I did not expect that codesign would just sign a symlink itself rather than the target.

**Comment by larrybotha** [comment]
Since v4.0.0 the following resolved the repeated accessibility prompt:

```shell
$ brew services stop yabai && \
	brew uninstall yabai && \
	brew install yabai && \
	brew services start yabai
```

thanks to https://github.com/koekeishiya/yabai/issues/1201#issuecomment-1072484117

**Comment by rayjanoka** [comment]
I just update the app so I need to run the code signing again `codesign -fs 'yabai-cert' $(which yabai)`

**Comment by pprotas** [comment]
For anyone needing help with this: you might have multiple yabai versions installed. To remove all of them, run a modified version of @larrybotha's script:
```zsh
$ brew services stop yabai && \
	brew uninstall --force yabai && \
	brew install yabai && \
	brew services start yabai
```
The `--force` flag removes all of the yabai installations.

**Comment by joelove** [comment]
> @Devric thanks for sharing that! I recently switched from Alacritty to Kitty so I tried uninstalling and reinstalling Yabai and now I'm back in business. Plus I have an actual icon for Yabai in the Accessibility settings.

Uninstalling and reinstalling worked for me!

```
brew uninstall --force yabai
brew install yabai
```

**Comment by blinkybool** [comment]
None of these fixes worked for me. Finally I figured out that if you run yabai from the terminal (not via `brew services`) it requires the Terminal to have accessibility access, not just yabai. I thought it was accessibility access making `brew services yabai start` not work, but it was actually an unrelated issue (yabairc file path was broken).

**Comment by roni-estein** [comment]
@ryderdain, thanks! I tried a hard-link which also seemed to work, perhaps I'll work that into a local yabai:update script. 🍻

**Comment by koekeishiya** [comment]
Brew services integration has been removed in the latest release (v5.0.4). Use the new service commands to integrate with launchd. There is a also a 30sec timer before the launchd service will attempt to restart yabai, so that should give some time to get through the accessibility access prompt if you fail to do so manually before starting yabai for the first time.

**Comment by trqminh** [comment]
> @rcorre had this issue today after upgrading HEAD via `brew upgrade` ; the standard code-signing only worked after explicitly codesigning the binary and re-adding _it_, not the symlink, to the list in System Preferences >> Security & Privacy >> Privacy >> Accessibility.
> 
> That is, running `codesign -fs 'yabai-cert' $(which yabai)` and approving that to the System Prefs didn't work, _presumably_ because that's a symlink to the file rather than the code itself:
> 
> ```
> $ ls -l $(which yabai)
> lrwxr-xr-x  1 xxxx  admin  38 Mar 17 10:23 /opt/homebrew/bin/yabai -> ../Cellar/yabai/HEAD-a4030e7/bin/yabai
> $ codesign -fs 'yabai-cert' /opt/homebrew/Cellar/yabai/HEAD-a4030e7/bin/yabai
> /opt/homebrew/Cellar/yabai/HEAD-a4030e7/bin/yabai: replacing existing signature
> ```

@ryderdain I try to run this but it showed: error: The specified item could not be found in the keychain. Do you have any suggestion. Thank you for your consideration.
