### ISSUE TITLE
Adobe Premiere Pro not managed by default

### ISSUE THREAD

**Issue by bookercodes** [koekeishiya/yabai#872]
For some reason, Adobe Premiere was evading Yabai's management 🥵 

I thought maybe because I was using Premiere (Beta), the window was being rendered in an experimental way. 

Adding the line below to `.yabairc` puts Adobe Premiere under Yabai's managment, and I am much happier for it!

```
yabai -m rule --add app="^Adobe Premiere Pro" manage=on
```

Creating this issue in case someone else searches the same problem.

Being curious,  I am also hoping to learn why every window is managed by default except Adobe windows?

**Comment by TuralAsgar** [comment]
Thank you!
