### ISSUE TITLE
Adobe Acrobat Reader often does not respond to window commands

### ISSUE THREAD

**Issue by 7vq** [koekeishiya/yabai#875]
<br/>
<br/>

EDIT: I'm using Firefox's pdf reader now, so personally I don't care about this issue anymore.

<br/>

Adobe Acrobat Reader windows usually work fine, but at least once every day some Acrobat window breaks and does nothing in response to, for example, `--resize` and `--swap` commands.

One reliable way of creating a broken window is to open a pdf, then press "Window" > "New Window" in the top menu bar. But windows also frequently break just when I open a new pdf.

`--query` shows `"resizable":0` for a broken window, even though the window is resizable using the mouse.

Restarting yabai gives `"resizable":1` and fixes the window.

These are the full `--query` results for a broken window, followed by that for a working window.

```
{
        "id":34972,
        "pid":78391,
        "app":"Acrobat Reader",
        "title":"",
        "frame":{
                "x":38.0000,
                "y":732.0000,
                "w":1268.0000,
                "h":708.0000
        },
        "level":0,
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "movable":1,
        "resizable":0,
        "display":1,
        "space":16,
        "visible":1,
        "focused":0,
        "split":"vertical",
        "floating":0,
        "sticky":0,
        "minimized":0,
        "topmost":0,
        "opacity":1.0000,
        "shadow":1,
        "border":1,
        "stack-index":0,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
},{
        "id":34322,
        "pid":78391,
        "app":"Acrobat Reader",
        "title":"book4325.pdf",
        "frame":{
                "x":8.0000,
                "y":724.0000,
                "w":842.0000,
                "h":708.0000
        },
        "level":0,
        "role":"AXWindow",
        "subrole":"AXStandardWindow",
        "movable":1,
        "resizable":1,
        "display":1,
        "space":16,
        "visible":1,
        "focused":0,
        "split":"vertical",
        "floating":0,
        "sticky":0,
        "minimized":0,
        "topmost":0,
        "opacity":1.0000,
        "shadow":1,
        "border":1,
        "stack-index":0,
        "zoom-parent":0,
        "zoom-fullscreen":0,
        "native-fullscreen":0
}
```

**Comment by buckmonster-fuller** [comment]
Issue still present on yabai-v4.0.0. Logs just say "could not retrieve window details." when broken windows are created.

To clarify the broken behavior: yabai sees the broken window, and yabai's container for where the window ought to go resizes, swaps, etc as normal, but the macOS window itself never moves anywhere or resizes.

yabai commit I'm using is https://github.com/koekeishiya/yabai/commit/b884717b2d5731f5b4ac164e7c0260076698b08c

I updated yabai through:
```
brew reinstall yabai # already installed with --HEAD
brew services stop koekeishiya/formulae/yabai
sudo yabai --uninstall-sa
sudo yabai --install-sa
sudo yabai --load-sa
brew services start koekeishiya/formulae/yabai
```

**Comment by HamzaMasood1** [comment]
Having the same issue!
