### ISSUE TITLE
[Question] Does yabai auto focus to previously focused window after killing a window?

### ISSUE THREAD

**Issue by marcushwz** [koekeishiya/yabai#878]
## Issue
- I have 2 windows open in display 1, and 1 window open in display 2.
- Current focused window is in display 1 while the previously focused window is in display 2
- After killing the currently focused window, the focus got switched to the previously focused window in display 2.

## Desired behavior
- After killing the currently focused window, the focus should be switched to the **previously focused window in the same space**, if there is none, the focus should still stay at the same space.

## What I have tried
- I have found related issues and many of the suggestions were to include lines below so that yabai will switch the focus under the cursor.

```bash
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
```

- This works fine if I have the config `mouse_follow_focus` set to `off` but doing this introduces other unwanted behavior such as when I have 3 windows opened in the same space, the cursor will always stay on the first opened window
- Hence, the focus always gets switched to that particular window after killing any of the other windows.  In this case, I still want the focus to be switched to the **previously focused window in the same space (if any)**.

## Question
- So I am wondering is this the default behavior where yabai always switch the focus to the previously focused window after the current window is killed
- Any suggestions on how I can configure it so that I can achieve my desired behavior (if this is possible)?

Also, a big thank you to everyone contributing to yabai 🙏, I have enjoyed it very much on my first Macbook. I have been using i3 on a Linux machine before this, and I was managed to configure yabai to mimic 90% of my workflow.

**Comment by marcushwz** [comment]
## Update

- I have found this related [issue](https://github.com/koekeishiya/yabai/issues/485)
- Using a similar approach as the user with some tweaking that I want to focus on the display that the current window is killed at.
- The display id is saved to a tmp file on events like `window_focused` and `application_front_switched`
- Then on events like `window_destroyed` and `application_terminated` I will read from the tmp file to get back the display id where the killed window is on.

```bash
function record_display_id {
  display_id=$(yabai -m query --windows --window | jq '.display')
  ruby $HOME/display_focus.rb write $display_id
}

function focus_current_display {
  yabai -m display --focus $(ruby $HOME/display_focus.rb read)
}

yabai -m signal --add event=window_focused action="${functions[record_display_id]}"
yabai -m signal --add event=application_front_switched action="${functions[record_display_id]}"
yabai -m signal --add event=window_destroyed action="${functions[focus_current_display]}"
yabai -m signal --add event=application_terminated action="${functions[focus_current_display]}"
```

- Then everything works as my expected behavior.
- Anyone has a better approach to handle this flow? I don't think this is a very efficient approach as I am writing to a file every time I switch the focus.
- I think this is a really hacky implementation, will appreciate if anyone have any better approach, if not I will be closing this issue soon as I have got what I wanted with the implemetation above.

**Comment by dominiklohmann** [comment]
> * Anyone has a better approach to handle this flow? I don't think this is a very efficient approach as I am writing to a file every time I switch the focus.

How often do you switch focus? It's usually so rare that it's not time-critical at all, so writing to a file is not an issue.

The way you tackled this works fine I think—I can't come up with a better way to implement this unless you want to touch the code itself.

**Comment by marcushwz** [comment]
Thanks for the reply @dominiklohmann. 

- With my current setup, I have 2 displays with 5 desktops on each display, so I will say I switch focus quite often. But I have been using the yabai config above for almost a day now, and I have not noticed any performance problem. So I think that is good enough for now.
- I will definitely love to dive into the code and understand the implementation, hopefully, one day I could contribute to yabai as well.
- Actually, I have been digging into the codebase yesterday trying to see what I can tweak to achieve what I wanted. But yeah, I am not very familiar with C and how yabai works. I will appreciate it if you could give me some heads up like which file I should be looking at or even any suggestions.
- I will close this issue for now and thanks for the reply again!
