### ISSUE TITLE
Directional focus isn't working in latest build

### ISSUE THREAD

**Issue by bobbybroadcast** [koekeishiya/yabai#88]
Whether using skhd keyboard shortcuts (`alt - h`) or typing the command myself (`yabai -m window --focus west`) does not change focus.

```
▲ ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132

 ▲ ~ yabai --version
yabai-v1.0.3

 ▲ ~ skhd --version
skhd version 0.3.4
```
verbose output of yabai shows it's getting the message, but fails to produce action
```
EVENT_HANDLER_DAEMON_MESSAGE: msg 'window --focus east'
EVENT_HANDLER_DAEMON_MESSAGE: msg 'window --focus west'
EVENT_HANDLER_DAEMON_MESSAGE: msg 'window --focus south'
EVENT_HANDLER_DAEMON_MESSAGE: msg 'window --focus north'
```
other commands, i.e. toggling `zoom-parent` works as expected:
```
EVENT_HANDLER_DAEMON_MESSAGE: msg 'window --toggle zoom-parent'
EVENT_HANDLER_WINDOW_RESIZED: Alacritty 1636
EVENT_HANDLER_DAEMON_MESSAGE: msg 'window --toggle zoom-parent'
EVENT_HANDLER_WINDOW_RESIZED: Alacritty 1636
```

**Comment by koekeishiya** [comment]
There has not been any changes to focusing since one of the very first commits.

Make sure you have SIP disabled and that the scripting addition is propery installed. Check the wiki for instructions.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
