### ISSUE TITLE
Weird state of the Emacs window after waking up from sleep

### ISSUE THREAD

**Issue by x-ji** [koekeishiya/yabai#884]
My Emacs (using [emacs-mac](https://github.com/railwaycat/homebrew-emacsmacport) via homebrew) is managed by default by yabai without me having to add any config. However, every time my Macbook wakes up from sleep, the Emacs window ends up being in a weird state, as shown in the screenshot below:

<img width="1911" alt="Screen Shot 2021-04-17 at 15 04 43" src="https://user-images.githubusercontent.com/2999209/115114290-ca1cf580-9f8e-11eb-957f-a10f2156ccbe.png">

i.e. the actual buffers are only taking up about half of the available vertical space.

No matter how I change the layout and move around the window, it doesn't seem to be resolved. The only thing I can do is to restart Emacs every time after waking up from sleep.

This doesn't seem to happen with any other app yet.

I'm on MacOS 11.2.3 and using 3 external monitors, one 4K monitor with 2x scaling and two 1920x1080 ones.

During the sleep the external monitors are usually disconneted.

Not sure if this is something that can be solved on the yabai side or if it's an issue I should open in the emacs-mac repo. Thought I'd post here in case somebody has seen something similar already.

**Comment by koekeishiya** [comment]
Doesn't seem like something that yabai can impact.
