### ISSUE TITLE
Yabai commands don't work for Spark email client 

### ISSUE THREAD

**Issue by benwoodward** [koekeishiya/yabai#886]
```
# move floating window
shift + alt - h : yabai -m window --move rel:-20:0
shift + alt - l : yabai -m window --move rel:20:0
shift + alt - k : yabai -m window --move rel:0:-20
shift + alt - j : yabai -m window --move rel:0:20

# increase window size
shift + alt + cmd - h : yabai -m window --resize left:-20:0
shift + alt + cmd - l : yabai -m window --resize right:20:20
shift + alt + cmd - k : yabai -m window --resize top:0:-20
shift + alt + cmd - j : yabai -m window --resize bottom:0:20

# decrease window size
alt + cmd - h : yabai -m window --resize right:-20:0
alt + cmd - l : yabai -m window --resize left:20:20
alt + cmd - k : yabai -m window --resize bottom:0:-20
alt + cmd - j : yabai -m window --resize top:0:20
```

These shortcuts work with all the apps I've tried them with except for [Spark.app](https://sparkmailapp.com/)

**Comment by danymat** [comment]
Maybe check if you didn't disable it in the config file

**Comment by andrew8088** [comment]
Spark doesn't play nice with Yabai for me as  well, but I've also seen it with [Amythest](https://github.com/ianyh/Amethyst) ... not sure what's Spark's doing differently ...

**Comment by nicklayb** [comment]
I also have hiccups with spark, especially with auto tiling. I like to have spark alongside Slack and most of the time, Spark overflows out side of the screen, either that or they overlaps. I tried with Firefox and Sparks do the same, I'm sometime able to have it fit by playing with the size of the window and at some point it snaps for good

**Comment by koekeishiya** [comment]
If it still misbehaves in the latest yabai version then there is not much else I can do.
