### ISSUE TITLE
Why does yabai --load-sa require SIP to be turned off after --install-sa

### ISSUE THREAD

**Issue by mTvare6** [koekeishiya/yabai#889]
I had once turned off SIP and ran `sudo yabai --install-sa` and then `sudo yabai --load-sa` and booted into recovery mode and enabled SIP why do I still need to have SIP disabled on every boot to have extra features

**Comment by koekeishiya** [comment]
See https://github.com/koekeishiya/yabai/issues/798#issuecomment-767084471
