### ISSUE TITLE
Payload doesn't support this macOS version on Big Sur 11.3

### ISSUE THREAD

**Issue by iinete** [koekeishiya/yabai#890]
Payload doesn't support this macOS version on Big Sur 11.3. Space focusing stops working as well.

**Comment by yanzhang0219** [comment]
11.3 was released officially today. Please be patient and @koekeishiya will adapt to it soon.

**Comment by 2m** [comment]
Ahh, did not notice how my Macbook got upgraded to 11.3 today. Sneaky Apple. :)

Transparency and window size management seems to work. But switching to different workspaces does not.

**Comment by scbizu** [comment]
> Ahh, did not notice how my Macbook got upgraded to 11.3 today. Sneaky Apple. :)
> 
> Transparency and window size management seems to work. But switching to different workspaces does not.

The same , when I kick the Restart  Now button , I found I forget to check the yabai issue list for the new version compatibility .Unfortunately , after restart , everything seems to be OK except yabai and it really slow down my work efficiency :(

**Comment by jneen** [comment]
Weirdly, the scripting addition seems to be just... gone. And I don't seem to be able to install it. Every command here returned exit status 0.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/225017/116320219-d4f13a80-a785-11eb-88d9-8b01044290f3.png">

**Comment by 2m** [comment]
Realised that native MacOs shortcuts for switching between workspaces is a viable workaround:

<img width="590" alt="paveikslas" src="https://user-images.githubusercontent.com/422086/116352486-ed04a080-a7fd-11eb-9d9f-9dd5e0ed369c.png">

**Comment by scbizu** [comment]
@2m thanks you .

**Comment by 24unix** [comment]
I've got 27 spaces (3 displays, 3x3 spaces on each), that's too much for Mission Control/the shortcuts (limited to IMHO 18), TotalSpaces2 is a liable solution, but you need the latest preview (2.9.8) when using Big Sur 11.3.
And it is not currently supporting AS, but I read they've got a beta wich will do …

**Comment by scbizu** [comment]
Why this issue closed ?

**Comment by 2m** [comment]
A new version of Yabai was released that supports 11.3.

**Comment by guillaumewuip** [comment]
I've disabled SIP, updated yabai to 11.3 and focusing on desktop still don't work on my side.

For 2 desktops, when I'm on the first one and I call `yabai -m space --focus 2`, it does nothing. 
No new outputs in `/usr/local/var/log/yabai/yabai.err.log` or `/usr/local/var/log/yabai/yabai.out.log`.

How can I help debug this issue in more details? Thanks!

**Comment by jaideeprana** [comment]
@guillaumewuip  Even I was getting the same issue but after running `sudo yabai --uninstall-sa` and then `sudo yabai --install-sa` respectively I was able to resolve the issue.

Basically in my case the scripting edition was outdated. Maybe you can try that and see if that works?

**Comment by guillaumewuip** [comment]
Strange, I've just tried what you proposed `sudo yabai --uninstall-sa && sudo yabai --install-sa` and I have the same behaviour with `yabai -m space`.
