### ISSUE TITLE
Major performance issues on Big Sur

### ISSUE THREAD

**Issue by issmirnov** [koekeishiya/yabai#892]
I'm running a 2019 16" MBP (2.4Ghz i9, 32gb RAM) with https://tracesof.net/uebersicht/ and https://www.simple-bar.com/en/.

I have noticed major regressions after upgrading to Big Sur. The entire system slows to a crawl, to the point that even opening a new Google Chrome tab is unbearable slow and takes 5-8 seconds.

I'm running dual 2k 27" monitors, connected via a RX 570 through a Razer Core X Chroma GPU. Issue appears to be worse when the monitors are connected.

I turned off Ubersicht and the issue got marginally better, but the system is still very slow. Turning off yabai didn't help until I completed a reboot.

I have verified that turning on **just** yabai will cause the system to slow down. This doesn't seem to happen when I'm only using the MBP screen. I have 16 virtual desktops across the two physical monitors.

**How can I help debug this?**

**Comment by mlubej** [comment]
I have the same setup, but no experience with previous versions of the OS. I don't have any issues of the scale reported above, but I'm willing to help with testing/reporting.

**Comment by issmirnov** [comment]
I triaged it a bit, and I think the problem is mostly with simple-bar. I opened an issue here: https://github.com/Jean-Tinland/simple-bar/issues/141
