### ISSUE TITLE
Yabai partially stopped working after update to Big Sur 11.3

### ISSUE THREAD

**Issue by jaideeprana** [koekeishiya/yabai#893]
The following functionalities that were previously working have now stopped working after the upgrade. Even though I have SIP disabled.

1. instant space switch
2. create new space
3. destroy space

**Comment by brandon-lile** [comment]
Just upgraded and I'm having similar issues.

I've done `sudo yabai --uninstall-sa` and then `sudo yabai --install-sa` and this prompts a notification stating: `payload doesn't support this MacOS version`

Checking `/usr/local/var/log/yabai/yabai.err.log` doesn't show anything in regards to the previously mentioned notification.

I also completely uninstalled `yabai`, and `skhd` and reinstalled and that did not work either.

Happy to provide any other information that is required.

**Comment by yevhenshymotiuk** [comment]
https://github.com/koekeishiya/yabai/issues/869

**Comment by kgrandly** [comment]
I think we need to wait for the new version

**Comment by brandon-lile** [comment]
Apologies, my google search returned this issue. I just saw #869 and #890

**Comment by jaideeprana** [comment]
@brandon-lile Even I was getting the same issue but after running `sudo yabai --uninstall-sa` and then `sudo yabai --install-sa` respectively I was able to resolve the issue.

Basically in my case the scripting edition was outdated. Maybe you can try that and see if that works?

**Comment by jaideeprana** [comment]
I can confirm it's resolved now.
