### ISSUE TITLE
Focus space in Big Sur not working

### ISSUE THREAD

**Issue by felixnorden** [koekeishiya/yabai#894]
When calling `yabai -m space --focus x` either using skhd or from the command line itself, nothing happens on Big Sur.
I have tried both reinstalling the SA and restarting both skhd and yabai services. Everything else from my configuration seems to work, only focusing spaces does not.

I have installed yabai for Big Sur according to the instructions found [in the wiki](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup).

Feel free to ask for more specific information, not too sure what I should provide! :)

**Comment by simonsmith** [comment]
Also seeing this issue since updating to `11.3.1`.

Running the command shows no output or entry in the error log:

e.g
```
yabai -m space --focus 3
```

However it does register that I'm already focused on the space if I put in an id to match the current space:

```
cannot focus an already focused space.
```

**Comment by christo-ph** [comment]
I suppose it's somehow related to: (?)

```console
$ sudo yabai --load-sa 
Password:
could not spawn remote thread: (os/kern) invalid argument
yabai: scripting-addition failed to inject payload into Dock.app!
```

**Comment by tami5** [comment]
@christo-ph I think so, I had the same issue and now I'm using Amethyst but dying for a solution for this problem. Hopefully it will be solved soon

**Comment by harrygallagher4** [comment]
I just installed 11.3.1 and yabai is working fine for me after upgrading to 3.3.8. 

Here's what I run after every macOS/yabai update, some of it might be unnecessary but I just included everything for good measure. You also have to re-approve yabai's accessibility access. 

```sh
# vim: filetype=zsh

brew services stop yabai
brew services stop skhd

sudo yabai --uninstall-sa
sudo yabai --install-sa

brew services start yabai
brew services start skhd

sudo yabai --load-sa
```

**Comment by tami5** [comment]
Interesting this worked for you on m1 macs? 
> I just installed 11.3.1 and yabai is working fine for me after upgrading to 3.3.8. 
> 
> 
> 
> Here's what I run after every macOS/yabai update, some of it might be unnecessary but I just included everything for good measure. You also have to re-approve yabai's accessibility access. 
> 
> 
> 
> ```sh
> 
> # vim: filetype=zsh
> 
> 
> 
> brew services stop yabai
> 
> brew services stop skhd
> 
> 
> 
> sudo yabai --uninstall-sa
> 
> sudo yabai --install-sa
> 
> 
> 
> brew services start yabai
> 
> brew services start skhd
> 
> 
> 
> sudo yabai --load-sa
> 
> ```

**Comment by Glup3** [comment]
> I just installed 11.3.1 and yabai is working fine for me after upgrading to 3.3.8.
> 
> Here's what I run after every macOS/yabai update, some of it might be unnecessary but I just included everything for good measure. You also have to re-approve yabai's accessibility access.
> 
> ```shell
> # vim: filetype=zsh
> 
> brew services stop yabai
> brew services stop skhd
> 
> sudo yabai --uninstall-sa
> sudo yabai --install-sa
> 
> brew services start yabai
> brew services start skhd
> 
> sudo yabai --load-sa
> ```

It works for me after updating yabai to version 3.3.8!
Tested on a Macbook 13-inch 2020, Intel i7

**Comment by christo-ph** [comment]
Hi @koekeishiya 

this does not seem to work properly. With macOS 11.3.1 and 3.3.8 I still get the error and can't get space switching to work:

```console
$ brew services stop yabai
$ brew services stop skid
$ brew upgrade yabai
[...]
Warning: koekeishiya/formulae/yabai 3.3.8 already installed
$ sudo yabai --uninstall-sa
$ sudo yabai --install-sa
$ brew services start yabai
==> Successfully started `yabai` (label: homebrew.mxcl.yabai)
$ brew services start skhd 
==> Successfully started `skhd` (label: homebrew.mxcl.skhd)
 $ sudo yabai --load-sa
could not spawn remote thread: (os/kern) invalid argument
yabai: scripting-addition failed to inject payload into Dock.app!
$ yabai -m space --focus 2
cannot focus space due to an error with the scripting-addition.
$ yabai -m space --focus 3
cannot focus space due to an error with the scripting-addition.
$ yabai -m space --focus 1
cannot focus an already focused space.
```

**Comment by catherinetcai** [comment]
Was running into this issue. Not really sure why, but stopping yabai, skhd, and then following the tips of logging out/logging back in, starting up yabai, and then starting up skhd seemed to have done the trick in fixing it on Big Sur for me.
