### ISSUE TITLE
Zip download file split window

### ISSUE THREAD

**Issue by Sylenss** [koekeishiya/yabai#898]
How can I stop this from happening? 

Is this zip window called something in particular that I can put in my yabairc file 

![Screen Shot 2021-05-10 at 7 45 43 AM](https://user-images.githubusercontent.com/45975952/117654593-f548ce00-b163-11eb-955e-d98a51655290.png)

**Comment by vadimvolk** [comment]
Please provide an output of:
`yabai -m query --windows
You may try to create a rule based of "app" and "title" started from "Opening" in your windows state file.

**Comment by Sylenss** [comment]
ill try that and get back to you also thank you for commenting

**Comment by Sylenss** [comment]
The crazy thing is its the firefox show all downloads popup window but when i make a rule for it nothing seems to happen and the window is created in another pane

**Comment by koekeishiya** [comment]
Can you post the output of `yabai -m query --windows` when the window is visible like in your screenshot? Ideally these windows would be ignored by default, but macOS is garbage and so here we are.

**Comment by vadimvolk** [comment]
`yabai -m rule --add app="Firefox" title="Opening.+" manage=off`

Here is your rule to append to yabai.rc file. The trick here is using .+ to match with any filename you are going to download.

**Comment by Sylenss** [comment]
> `yabai -m rule --add app="Firefox" title="Opening.+" manage=off`
> 
> Here is your rule to append to yabai.rc file. The trick here is using .+ to match with any filename you are going to download.

It really did the trick, thank you so much
