### ISSUE TITLE
Some apps aren't detected by yabai

### ISSUE THREAD

**Issue by pcr910303** [koekeishiya/yabai#9]
This is a gif that shows that yabai can't detect 1) emacs windows and 2) Quicktime video windows.
It will be (hopefully) reproducible by `brew cask install emacs`, and `emacs -Q`.
While I incidentally thought this is an Emacs problem, a similar problem occurs on Quicktime video windows.
Also, while not shown in the gifs, when I call emacs with my config file, while Emacs is loading (about ~5sec) yabai becomes irresponsive. (e.g. automatic focus following doesn't work, active window opacity doesn't update....)

Emacs: 
![yabai-with-emacs](https://user-images.githubusercontent.com/37990858/58371662-2ebfa900-7f4e-11e9-8494-24fad9527861.gif)

Quicktime: 
![yabai-with-quicktime](https://user-images.githubusercontent.com/37990858/58371718-b4dbef80-7f4e-11e9-92ef-1b241a5db10e.gif)

**Comment by dominiklohmann** [comment]
Take some time, head over to the chunkwm issue tracker and search for emacs. It's a long read.

**Comment by pcr910303** [comment]
Nah, this was due to not restarting the yabai process after updating :-(
