### ISSUE TITLE
Add toggleable attributes to window queries

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#90]
`zoom-fullscreen`, `zoom-parent`, `border`, `sticky`, `split` should all be in `yabai -m query --windows`.

Related: #83

**Comment by koekeishiya** [comment]
Fixed on master.

**Comment by pbrogan12** [comment]
The value for the split key is not a quoted string causing jq to have a parse error

`
{
	"id":2268,
	"pid":6156,
	"app":"Hyper",
	"title":"Hyper",
	"frame":{
		"x":24.0000,
		"y":24.0000,
		"w":1632.0000,
		"h":1002.0000
	},
	"level":"0",
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":1,
	"split":horizontal,
	"floating":0,
	"sticky":0,
	"border":1,
	"zoom-parent":1,
	"zoom-fullscreen":1,
	"native-fullscreen":0
}
`

`
yabai -m query --windows --window | jq .  
parse error: Invalid numeric literal at line 17, column 20
`

**Comment by koekeishiya** [comment]
Well that was a brilliant mistake - fixed and did a new release.
