### ISSUE TITLE
Changing desktop on focus change

### ISSUE THREAD

**Issue by robowraith** [koekeishiya/yabai#903]
I would like to definde a shortcut "cmd + right" that will switch focus to the next window on the right/east **and** switch to the next desktop on the right (next) if there are no more windows to the right of the currently active one.

Basically the ability to have "cmd + right" do a  
`yabai -m window --focus east`
if there is a window to the east of the current window and  
`yabai -m space next`  
if not.

If I query a space's windows, I cannot find out, how yabai knows whether there is a window east of the current one though.
I guess, what I would need is the position of the current window in the tree.

**Comment by koekeishiya** [comment]
`cmd - right : yabai -m window --focus east || yabai -m space --focus next`

Sent from my iPhone

On 19 May 2021, at 17:51, robowraith ***@***.***> wrote:

﻿

I would like to definde a shortcut "cmd + right" that will switch focus to the next window on the right/east and switch to the next desktop on the right (next) if there are no more windows to the right of the currently active one.

Basically the ability to have "cmd + right" do a
yabai -m window --focus east
if there is a window to the east of the current window and
yabai -m space next
if not.

If I query a space's windows, I cannot find out, how yabai knows wheter there is a window east of the current one though.

**Comment by robowraith** [comment]
Oh man, this is embarrassing! 😂
