### ISSUE TITLE
Zoom window behaviour like tmux pane zoom

### ISSUE THREAD

**Issue by HenriAW** [koekeishiya/yabai#904]
Hi,

I'm currently setting up my yabai config and am struggling to get the behaviour I want. Briefly, the functionality I'm looking for is:
1. zoom-window - like tmux zoom-pane - you can briefly make a window fullscreen and then change back afterwards
```bash
# Zoom in
yabai -m query --windows --space | jq '.[].id' | xargs -I {} zsh -c 'if [[ "$(yabai -m query --windows --window {} | jq ".\"zoom-fullscreen\"")" == 0 ]]; then yabai -m window {} --toggle zoom-fullscreen; fi'
# Zoom out
yabai -m query --windows --space | jq '.[].id' | xargs -I {} zsh -c 'if [[ "$(yabai -m query --windows --window {} | jq ".\"zoom-fullscreen\"")" == 1 ]]; then yabai -m window {} --toggle zoom-fullscreen; fi'
```
2. Previous window in current space
```bash
if [[ "$(yabai -m query --spaces --window recent | jq '.[].index')" == "$(yabai -m query --spaces --window | jq '.[0].index')" ]]; then \
  yabai -m window --focus recent; \
else \
  yabai -m window --focus stack.next || yabai -m window --focus stack.first; yabai -m window --focus next || yabai -m window --focus first; \
fi
```
3. Next window in current space
```bash
yabai -m window --focus $(yabai -m query --windows --space | jq '.[-1].id')
```

This works pretty well for the most part, however I feel like I'm over-complicating some of these things quite a bit. Also, when I open a new window, if I'm in zoomed in mode then yabai will re-evaluate the other windows for that application when I'd really like them to all stay in full screen mode.

Does anyone have any advice for how I can achieve this (or if I should be using some other functionality of yabai instead).

Thanks!

**Comment by AlgusDark** [comment]
Did you found any solution @HenriAW ?

**Comment by HenriAW** [comment]
Unfortunately not - I went back to using Amethyst after this since I couldn't install yabai on my work laptop

**Comment by koekeishiya** [comment]
Zoomed window will persist their state upon modification to the layout: #864
