### ISSUE TITLE
How to toggle between 2 padding presets?

### ISSUE THREAD

**Issue by trankien386** [koekeishiya/yabai#905]
Ideally, i want to switch between 2 padding options. The first one is
```
yabai -m config top_padding    5
yabai -m config bottom_padding 5
yabai -m config left_padding   5
yabai -m config right_padding  5
yabai -m config window_gap     5
```
The second one is
```
yabai -m config top_padding    20
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     20
```
Normally, i leave all values at 20 for better looking. But when i need maximum amount of spaces, i leave them at 5. Right now i assign the second preset for space 1 only. I'd like a way to toggle between these two, rather than switch between spaces to experience different padding options.

i also could use these commands
```
yabai -m space --toggle padding
yabai -m space --toggle gap
```
but i would rather want to have 5px padding between windows than 0px.

**Comment by koekeishiya** [comment]
Write a script that queries the current padding and just reassigns the values you want, then bind that script to execute when you press a key. 

`yabai -m config --space 1 top_padding` will return the current top padding of space 1.
then something like the following logic to make a toggle..
if 20 then <x>_padding 5 else <x>_padding 20 where <x> in [ top, bottom, left, right ]

**Comment by trankien386** [comment]
@koekeishiya Thanks for the idea! I haven't figured out the code yet but I really appreciate your answer. Might work this out soon.
