### ISSUE TITLE
Toggle layout for bsp node between stacked, horizontal split and vertical split

### ISSUE THREAD

**Issue by entropitor** [koekeishiya/yabai#908]
It would be nice to have a command / way to toggle the layout for a bsp node: stacked, horizontal split, vertical split.

Right now, we cannot go from split to stacked because we don't know which is the "sibling" 
And we can go from stacked to split (`yabai -m window --toggle float && yabai -m window --toggle float` seems to work in a bsp space layout) but is not super ideal, so it would be nice if this could be tackled as one thing

**Comment by koekeishiya** [comment]
more selectors have been added, #192 .
