### ISSUE TITLE
Get around the automatic creation of a space when adding a display

### ISSUE THREAD

**Issue by Sweenu** [koekeishiya/yabai#91]
I need help with a problem I've had for a long time with chunkwm but I wonder if signals brings a solution to this.

When adding a display, a space is inserted as the first space of the second display. This shifts all my windows up a space so I cannot access the same windows with the same keys when having 1 display and 2 displays.

I tried: 
```bash
yabai -m signal --add event=display_added action="yabai -m space --focus 5 && yabai -m space --destroy"
```
But it just destroys all spaces one by one until there is only one space per display.

Another solution would be to change the key shortcuts to focus spaces dynamically.
For example my current config is the following:
```
lalt - a : yabai -m space --focus 1
lalt - s : yabai -m space --focus 2
lalt - d : yabai -m space --focus 3
lalt - f : yabai -m space --focus 4
lalt - u : yabai -m space --focus 5
lalt - i : yabai -m space --focus 6
lalt - o : yabai -m space --focus 7
lalt - p : yabai -m space --focus 8
```
If I could change that to become:
```
lalt - a : yabai -m space --focus 1
lalt - s : yabai -m space --focus 2
lalt - d : yabai -m space --focus 3
lalt - f : yabai -m space --focus 4
lalt - u : yabai -m space --focus 6
lalt - i : yabai -m space --focus 7
lalt - o : yabai -m space --focus 8
lalt - p : yabai -m space --focus 9
```
when I add a display, then the desktop 5 would be a useless desktop but at least, it solves my problem.

What do you think is the best way to get around this problem?

**Comment by dominiklohmann** [comment]
This is an amazing idea. Here's some thoughts on how I would go about implementing this.

So the display_added signal carries the newly added displays id, which can be used to distinguish whether its space indices are lower or higher than the previously connected displays. You could then move a space from your previously connected displays to your new display, focus the space that was created for the newly connected display and destroy it. 

Just some thoughts, not sure if this works. Added this to the list of things to try sometime soon.

**Comment by Sweenu** [comment]
I might miss something about how spaces work because I'm not able to get something consistent by destroying a space on a `display_added` signal 🤔

**Comment by koekeishiya** [comment]
I don't think you can solve this properly before #119 is added.
