### ISSUE TITLE
[Sublime Text] bug when open new folder in native tab

### ISSUE THREAD

**Issue by sy6sy2** [koekeishiya/yabai#912]
If you use native tabs feature of Sublime Text with Yabai, and if you open a new folder on Sublime Text, Yabai thinks that a real new window is open an resize Sublime Text in the half of screen.

Steps to reproduce:

* Enable Yabai
* Open Sublime Text on a free space (Yabai will put Sublime Text window in full screen, this is the expected behavior)
* Enable native tabs in Sublime Text Window (`"native_tabs": "preferred",`)
* Open a random folder with `File --> Open...`
* Open a second random folder with `File --> Open...`
* Sublime Text will open this new folder in a new "native tab" but Yabai thinks it's a real new window and will resize the only Sublime Text window in half of screen.

**Comment by koekeishiya** [comment]
#68
