### ISSUE TITLE
Unable to go to space 11 via control + - key

### ISSUE THREAD

**Issue by jaideeprana** [koekeishiya/yabai#915]
After using the following config with `ctrl - -` switching to space to space 8, 9, 10 stops working. This is also replicable when using `ctrl - =`.

```
# Focus : focus space
ctrl - 0 : yabai -m space --focus 10
# Focus : focus space
ctrl - - : yabai -m space --focus 11
```

**Comment by danymat** [comment]
Maybe it's not an issue with yabai, but maybe that your key (`-` is not recognized).
To test it, change the key to something else easier, like 
```
ctrl - a : yabai -m space --focus 11
```
And try to see if it works.

**Comment by koekeishiya** [comment]
`ctrl - -` is not valid syntax; `-` is a reserved keyword and cannot be used as a literal (because I was lazy when writing the parser). Use the keycode instead as mentioned in the comment above.

**Comment by jaideeprana** [comment]
Thanks @danymat and @koekeishiya . That resolved the issue for me :)
