### ISSUE TITLE
Chrome Position

### ISSUE THREAD

**Issue by thomasdevos69** [koekeishiya/yabai#922]
All,

I have been using for a while Yabai successfully and Chrome was positioned automatically. About ten days back Chrome is only floating now on top of the other windows and is no longer positioned. 

Any idea what I could be checking in my settings? See attached. 

Thanks
[yabairc.txt](https://github.com/koekeishiya/yabai/files/6615212/yabairc.txt)

Thomas

**Comment by thomasdevos69** [comment]
All,

This has been resolved. 

Yabai seems to position Chrome on top of the other Windows if you have set in Mac for Chrome to be placed on all desktops. 

Thomas

**Comment by ShawnMcCool** [comment]
@thomasdevos69 I am not much of an OSX user. I have run into Chrome not wanting to be spaced automatically. could you describe your fix?

**Comment by thomasdevos69** [comment]
![image](https://user-images.githubusercontent.com/69845116/128148750-71383b93-e1e4-44b2-955d-f9f53fe056c2.png)

If you would select here "All Desktops" then Yabai does no longer position the windows correctly - I had to set it to none and all works now

**Comment by ShawnMcCool** [comment]
Thanks for the response, I'm not having the same effect. When I query with `yabai -m query --windows` I don't even see chrome.

**Comment by sarahhodne** [comment]
I had a similar issue where `yabai -m query --windows` didn't show Chrome. Reinstalling the scripting additions solved it, following the [upgrade instructions](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#updating-to-the-latest-release) in the wiki.
