### ISSUE TITLE
Request: Center windows when they won't stretch

### ISSUE THREAD

**Issue by Peeja** [koekeishiya/yabai#924]
Sometimes windows refuse to stretch to the dimensions yabai wants them to take. For instance, I just tried installing and running the [Beaker Browser](https://beakerbrowser.com/) for the first time, and like many apps on first launch, it has a size-constrained welcome window, here showing me the license information:

![screenshot](https://user-images.githubusercontent.com/2407/121544773-f6c21c00-c9d7-11eb-9c31-f42330eaa4ff.jpg)

Because it's the sole window, it notionally has the full screen by yabai's reckoning. But it refuses to be that big, so it's left up in the corner there, which is fine, but not very nice looking.

Instead, if it *centered* within the space yabai carved out for it, it would look much more natural, and probably even be positioned right where the app developer intended. It would also look great with other windows around: imagine it being in the center of its given space when the screen is split in half like this:

![screenshot-2](https://user-images.githubusercontent.com/2407/121545530-9bdcf480-c9d8-11eb-82dd-20d27c8c5dce.jpg)

I'm guessing this would be a bit of work to implement—it might mean having to do a second pass over the windows or something?—but I think it could be a big improvement.

**Comment by soundneedle** [comment]
Found this that would make it float. Maybe there’s a way to also force it to center.

yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".resizable == 0 and .floating == 0" && yabai -m window $YABAI_WINDOW_ID --toggle float'

**Comment by koekeishiya** [comment]
Closing in favour of #235. Not really any breakthrough yet though.
