### ISSUE TITLE
macos monterey: sip cannot disabled 

### ISSUE THREAD

**Issue by sindhus-in** [koekeishiya/yabai#925]
hi, 

i recently upgraded to macos monterey developer beta and could not disable the sip(?). so yabai keeps giving me notifications about payload not being installed. I looked up how to disable sip. am unable to get into "Recovery Mode" as my mac mini doesn't seem to honour the keys pressed at boot (cmd + r or for that matter any other variations given here: https://support.apple.com/en-us/HT201255).

so i've currently removed yabai on macos 15. please let me know how i can fix this.

thank you.

**Comment by kvndrsslr** [comment]
Monterey support is not finished. Please keep Monterey discussion to #923 and close this issue.

**Comment by sindhus-in** [comment]
thank you.

**Comment by sauhaardac** [comment]
You have to hold down the power button on m1 mac minis top get to recovery. It's not cmd+r anymore.
