### ISSUE TITLE
Unable to switch focus to another screen

### ISSUE THREAD

**Issue by Stianhn** [koekeishiya/yabai#927]
I'm having some issues with switching focus to a different space.  

Trying to focus on my current screen gives me an expected result:
`yabai -m space --focus one
cannot focus an already focused space.`

The same goes for when I try non existing space:
`yabai -m space --focus two1234
value 'two1234' is not a valid option for SPACE_SEL`

But when I try a valid value I get this error:
`yabai -m space --focus two
cannot focus space due to an error with the scripting-addition.`

yabai.err.log looks like this:
`could not retrieve window details.
could not retrieve window details.
value '' is not a valid option for WINDOW_SEL
could not retrieve window details.
could not locate the space to act on!
'window_opacity_duration' cannot be changed on macOS Catalina/Big Sur because of an Apple bug in the WindowServer
could not locate the space to act on!
'window_opacity_duration' cannot be changed on macOS Catalina/Big Sur because of an Apple bug in the WindowServer
could not locate the space to act on!
'window_opacity_duration' cannot be changed on macOS Catalina/Big Sur because of an Apple bug in the WindowServer`

`sudo yabai --load-sa` runs without any errors. Any suggestion on how to move forward with this issue?

**Comment by jinh0** [comment]
I had this same issue, but I realized I was running `v3.3.7` so I updated to the latest `3.3.10` version and did:
```
sudo yabai --uninstall-sa
sudo yabai --install-sa
sudo yabai --load-sa
```

And it works fine now. 

I think this whole issue was because of the new Big Sur update (see [this issue](https://www.gitmemory.com/issue/koekeishiya/yabai/894/832583396)) but I might be wrong.

**Comment by koekeishiya** [comment]
Should be fine; update to the latest released version and install/load the scripting-addition. Wiki instructions should be fine.
