### ISSUE TITLE
focus_follows_mouse best practices?

### ISSUE THREAD

**Issue by hypergig** [koekeishiya/yabai#928]
I love `focus_follows_mouse`. It saves me loads of superfluous mouse clicks per day. But I have noticed that some applications render context menus as separate windows, which means as soon as you attempt move the mouse into the menu it immediately closes as the focus shifts to the main application when when your mouse moves, thus deactivating the menu window which automatically closes.

Zoom and IntelliJ do this. In zoom, if you click the audio menu and attempt to move the mouse into the menu, it closes the menu. In IntelliJ the same happens for many of the smaller "click-to" windows, like those reference windows. For IntelliJ I created this rule to help:

https://github.com/hypergig/workstation/blob/master/config/yabairc#L33

But it isn't perfect. In practice, the mouse moving takes me by surprise and I lose my mental mapping of where it should be on the screen, and nearly always accidently move the mouse out of the subwindow causing it to vanish.

So my question is, what are other people doing that also use `focus_follows_mouse`? Are there any rules or signals that would help the user experience? Is there a way to tell yabia some particular windows should be considered a menu window and thus, don't behave like a normal window and close when the focus changes?

**Comment by Menchen** [comment]
Holding down mouse mod key disable focus follow temporary 
```
yabai -m config mouse_modifier               ctrl
```

**Comment by jordan-da** [comment]
> Holding down mouse mod key disable focus follow temporary
> 
> ```
> yabai -m config mouse_modifier               ctrl
> ```

yeah yeah, and i have tried this with a few modifiers.. the issue is in some IDEs (like intellij) those modifier clicks mean something too and they interfere

**Comment by koekeishiya** [comment]
In v4.0.0, focus follows mouse should be automatically disabled when a context-menu is opened.
