### ISSUE TITLE
Add "main" attribute to display queries

### ISSUE THREAD

**Issue by dominiklohmann** [koekeishiya/yabai#93]
While trying to implement #91 I was thinking that it'd be nice to pull spaces from the main display, but there's no way to identify them currently. 

Currently using `yabai -m query --displays | jq 'min_by(.id)'`, but I'm not sure whether this works by chance or is reliable.

**Comment by koekeishiya** [comment]
The main display is always the display at origin 0,0 according to Apple. Unless your definition of main display differ from theirs.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dominiklohmann** [comment]
That's good to know, the following snippet does work:

```sh
yabai -m query --displays | jq '.[] | select(.frame.x == 0 and .frame.y == 0)'
```
