### ISSUE TITLE
Debug delay after moving cursor to second display

### ISSUE THREAD

**Issue by fiedl** [koekeishiya/yabai#933]
Hi, I'm experiencing a noticeable delay in yabai after moving my mouse from one display to another display. I was wondering if someone could give me some pointers on how I could debug this.

Thanks for the great work!

## How to reproduce

https://user-images.githubusercontent.com/1679688/122811605-ffb4c680-d2d0-11eb-99f7-9c404d7ec565.mov

1. Start `yabai` and wait until ready
2. Move cursor around on one display to make sure the auto-focus feature (`focus_follows_mouse          autofocus`) is working as expected
3. Move mouse cursor from one display to the neighbouring display onto another window
4. Observe the several-second delay until the new window becomes focused

The other display is left of the shown area in the video.

Note the delay: The Safari window becomes active (0:04) quite a while after the cursor has moved into the window (0:01).

## Some observations

- This delay concerns several yabai features including window arrangement and focus. Here, I've used `layout float` to reduce the amount of work to only handling the window focus.
- The debug output shows mouse down/up events. I did not click the mouse in this demonstration, but suspect that those are events emulated by yabai in order to focus the second display.
- I've tried to give the `yabai` process a higher priority with `nice -n 3`. But this did not resolve the issue. 
- I don't experience this issue when only connecting one display.

## Versions

- yabai-v3.3.10
- macOS Big Sur 11.4 (20F71)

**Comment by koekeishiya** [comment]
Closing this as I don't experience such delay in latest version of yabai and macOS.
