### ISSUE TITLE
--load-sa not working on yabai-v3.3.10 on M1

### ISSUE THREAD

**Issue by cmstoddard** [koekeishiya/yabai#935]
I have followed all the steps, but no matter what I do, the file won't load. I can manually input commands like "yabai -m config right_padding  5" which work, and yabai itself doesn't have any issues loading. I wish I could post an error log, but there is no feedback on what exactly is keeping the file from loading/changing the interface.

**Comment by alin23** [comment]
The scripting addition loader needs a full rewrite for the Apple Silicon architecture. 

You can check the progress here: https://github.com/koekeishiya/yabai/issues/725

At the bottom of the thread you can also see xorpse has forked the repo and already done this rewrite so you can try using that until the author of yabai buys an M1 Mac.
