### ISSUE TITLE
Command to focus floating window

### ISSUE THREAD

**Issue by Scrumplex** [koekeishiya/yabai#940]
On Sway (and therefore i3), I can use Meta+Space to toggle focus of the floating window(s).

Is it possible with yabai? A quick trial and error with the man page didn't give me the desired result.

Maybe we need a 
```
yabai -m window --focus lastfloating
```

or something like that.

**Comment by koekeishiya** [comment]
There is no way to toggle into focusing floating windows. Use the query system to retrieve information about windows and pass the id to `yabai -m window --focus`. See #944 for a sample, or search the closed issues.
