### ISSUE TITLE
Cannot focus space even with animation (m1 w/o scripting-addition)

### ISSUE THREAD

**Issue by Marcusory** [koekeishiya/yabai#941]
I am trying to run Yabai _without_ the scripting-addition on my m1, and I believe my interpretation of the documentation is that without the s-a, you're supposed to be able to change space focus just with the default animation. However, when I try to run the command in terminal 

`yabai -m space --focus #`
the error message does still print 
`cannot focus space due to an error with the scripting-addition.`

The section of the documentation I am referring to is here: 

> The following features of yabai require System Integrity Protection to be (partially) disabled:
> 
>     **focus/create/destroy space without animation**
>     move space (and its windows) left, right or to another display
>     remove window shadows
>     enable window transparency
>     control window layers (make windows appear topmost)
>     sticky windows (make windows appear on all spaces)
>     move window by clicking anywhere in its frame
>     toggle picture-in-picture for any given window
>     border for focused and inactive windows

The first line would seem to indicate that this should still be possible without the scripting addition (again, I did not install the s-a, as I am running this on an m1 and understand that s-a is not supported on those chips). 

I've noticed others who have referenced similar issues, but it isn't clear to me if they were running into the same issue or if they were incorrectly trying to run s-a on an incompatible system. Starting a new issue here as the documentation does seem to indicate that this should not be an issue (not sure if this 1) used to be possible without s-a, but now the base code makes it impossible due to integration with s-a, or if 2) this simply was never possible. Either way, might just need to revise the docs).

Edit1: spelling

Edit2: also for anyone  else running this on an m1, obviously the workaround is to manually set these hotkeys under System Preferences > Keyboard > Mission Control > Switch to Desktop #

This more or less works as I am able to still move windows to a different "space"/Desktop via Yabai on skhd (e.g. `yabai -m window space #`), but due to the issue posted, I  can't move+follow focus via skhd in a single key combo since the `yabai -m space --focus #` command won't work, so it's an extra key combo to then manually switch to the new Desktop I moved the window to.

**Comment by koekeishiya** [comment]
There are no APIs to focus a different space without the scripting addition. You can either use the keybindings in mission control, or run a yabai query for your target space and focus the first window in the list, to trigger a space switch. This will only work for spaces that have open windows on them. You can search the issue board for this; there is a script in some closed issue somewhere that  does this.

**Comment by Marcusory** [comment]
Ah, I see. I appreciate the clarification! Thoroughly enjoying the project so far!
