### ISSUE TITLE
Fullscreen without moving to a new space

### ISSUE THREAD

**Issue by PaddiM8** [koekeishiya/yabai#942]
I have been looking through issues and wiki pages, but haven't found a way to prevent applications from being moved to a new space at the end of the list, when fullscreening them. I understand that this is normal macOS behaviour, but it doesn't really fit in with a window manager like this? I want to be able to eg. fullscreen Firefox in space 2 (to get rid of the title bar buttons I don't need), without having to open mission control and manually re-arrange the spaces to make sure I can still use the same keyboard shortcut to access it. Is this possible?

**Comment by koekeishiya** [comment]
It is not possible to fullscreen without moving to a new space; this is a macOS thing.

You might be able to make some sort of script that uses `yabai -m space --move ..` to re-order the space automatically the first time the window enter fullscreen.

**Comment by edte** [comment]
same trouble
