### ISSUE TITLE
external_bar and native-fullscreen

### ISSUE THREAD

**Issue by blink-twice** [koekeishiya/yabai#943]
Is the external_bar option supposed work on spaces that have windows in native-fullscreen? The wiki does not have any indication that external_bar **applies only to spaces in which windows are either not fullscreen** or are **in zoom-fullscreen mode**.

This is what I'm trying to achieve - for my most frequently used apps, I use one space per app with each window in native-fullscreen mode. I want simple-bar to be visible at the bottom of each space, but currently it looks like this is not possible unless I use the windows in zoom-fullscreen. Is this correct? I am using v.3.3.8

**Comment by koekeishiya** [comment]
This is a restriction in macOS. When an application is in native-fullscreen space, the size is controlled by macOS and we have no way to say that we want to leave empty space as padding. 

In general, it is not possible to show other applications/windows on a native-fullscreen space. Technically, there is a way to do this and the bar that used to be built into yabai (v2.x.x) did this, but I doubt simple-bar supports it as it utilizes Übersicht.

Regardless, a native-fullscreen space is not something that we have control over.

**Comment by blink-twice** [comment]
Thank you for the confirmation! It would be great to have it clarified in the Wiki as well.
