### ISSUE TITLE
Add explicit `window --set` alternative to `window --toggle`?

### ISSUE THREAD

**Issue by jesseleite** [koekeishiya/yabai#945]
I have a use case where I want yabai to manage my Slack chat window, but not my Slack call windows. I tried adding this rule:

```
yabai -m rule --add title="Slack call" manage=off
```

Which should work, but doesn't because it's an Electron app that changes the window title to 'Slack call' a second or so after it's been created. Thus, the rule doesn't work, since I think it resolves on window creation?

That said, I almost found a workaround using this signal:

```
yabai -m signal --add title="Slack call" event=window_title_changed action="yabai -m window $YABAI_WINDOW_ID --toggle float"
```

By hooking onto the `window_title_changed` event, the signal is successfully fired, and my window is toggled into a float. However, every time someone joins the call, Slack changes the title again, toggling my window back to bsp.

If yabai had a `window --set float` option (or similar), I could use a signal to explicitly ensure the window stays floated, rather than **_toggling_** between float and bsp. What are your thoughts on this?

**Comment by koekeishiya** [comment]
You can do this by doing a query first and checking the existing value, something like the following:

```
if [ $(yabai -m query --windows --window | jq '.floating') != 1 ]; then yabai -m window --toggle float; fi 
```

**Comment by jesseleite** [comment]
@koekeishiya Will give it a try thanks ❤️

That said, what do you think of the idea to add an explicit `window --set` option to compliment your `window --toggle` option?

**Comment by koekeishiya** [comment]
Unlikely to happen in the near future, although I will keep it in mind as I revise the CLI for v4.0.0 (`the-future` branch).

**Comment by koekeishiya** [comment]
I don't think this is something I want to do. There would just be way to many combinations of commands that would have to be added across all domains to unify a "set this value" syntax, allow cycling of options for commands that have a set of legal arguments etc.
