### ISSUE TITLE
yabai: could not initialize event_loop! abort.. 

### ISSUE THREAD

**Issue by mahomahomaho** [koekeishiya/yabai#95]
Hi, I have installed yabai + skhd on my mac, and it works perfectly on one user (lukasz.mach). 

However, when I switched to another user (maho) - I cannot start yabai because it says:

```
yabai: could not initialize event_loop! abort..
```

I tried to remove sockets from /tmp/*, removed logs from /usr/local/var/log/yabai/* , I think it's not permissions to socket/logs problem. 

I'm so far running yabai from terminal, but running from service (brew services start yabai) brings no difference. 

'lukasz.mach' is the user I used to brew install yabai, if it matters

**Comment by koekeishiya** [comment]
Fixed on master.
