### ISSUE TITLE
Scripting addition failed after upgrading to MacOS Monterray

### ISSUE THREAD

**Issue by qwinters** [koekeishiya/yabai#952]
Haven't confirmed any functionality or performance differences, but do get consistent notifications about scripting payload failing (see below)

<img width="360" alt="Screen Shot 2021-07-04 at 09 56 30" src="https://user-images.githubusercontent.com/3493504/124393192-43430380-dcc7-11eb-9a65-76aa693d422e.png">

Will update this ticket if functionality stops working. At least for now would be good for a way to silence these notifications natively (maybe there already is and I just missed it?)

**Comment by alin23** [comment]
You should remove `sudo yabai --load-sa` from your yabai configuration. 

Yabai SA isn't regularly updated for beta builds of macOS.

**Comment by Devvz** [comment]
I am getting this popup constantly. Seems to be pretty random.

> You should remove `sudo yabai --load-sa` from your yabai configuration.
I do not have this line in my yabai config. i just tried disabling SIP and then running `sudo yabai --uninstall-sa` and it didn't resolve the issue. 

Running the public beta of Monterey, on an M1 MacBook Air with the `xorpse/formulae/yabai` fork.

**Comment by alin23** [comment]
Yabai isn't yet updated for Monterey. It keeps crashing and restarting which is why you keep seeing the notification.

You'll have to disable yabai for the moment until Monterey is officially launched and @koekeishiya can update it.

**Comment by qwinters** [comment]
> You should remove `sudo yabai --load-sa` from your yabai configuration.
> 
> Yabai SA isn't regularly updated for beta builds of macOS.

I don't have that in my load config either. 

(Also to be clear, I'm not expecting direct support anytime soon -- I'm more raising this as an issue just so it's on the radar to be fixed eventually -- I've actually disabled `yabai` for now, but more than happy to run tests/be a guinea pig when Monterrey support eventually becomes a priority)

**Comment by 24unix** [comment]
> I've actually disabled `yabai` for now, 
To be curious: What’s so important about Montery? Can’t it be done in a VM?
I’d miss window opacity too much …

**Comment by Devvz** [comment]
> > To be curious: What’s so important about Montery? Can’t it be done in a VM?
> > I’d miss window opacity too much …

It probably could, and would be best practice for messing around with the new OS, but some people (myself included) like to live dangerously and install beta updates on their main rig (LOL)

**Comment by alin23** [comment]
For me, being on Monterey is important as I develop [a macOS app](https://lunar.fyi) that works with low level APIs and hardware directly so a VM would not work for testing and developing this app.

Also I love testing the new stuff directly! I really wanted to use the Universal Control feature but nobody knew that it won't be included in the first betas..

**Comment by 24unix** [comment]
> but some people (myself included) like to live dangerously and install beta updates on their main rig (LOL)
Ok, Rex Kramer :-)

**Comment by 24unix** [comment]
>  I really wanted to use the Universal Control feature but nobody knew that it won't be included in the first betas..

Oh, is it not? I've got a spare iMac 2017, wanted to test ist some day with my 2020 iMac.

**Comment by alin23** [comment]
No, Universal Control is not available as of Developer Beta 2. We'll have to wait a bit.

**Comment by evprkr** [comment]
Just want to chime in that I'm having this same issue on the Monterey public beta on my M1 MacBook Air. I previously had `sudo yabai --load-sa` in my .yabairc (though I have SIP enabled because the SA isn't supported still for M1 as far as I know) and removing it did not fix the issue. I'm getting the constant pop-ups AND impaired functionality. The notifications appear every time a new window is opened and it seems like the windows won't automatically move themselves around to fill empty space when windows are closed.

So for anyone considering updating to the Monterey beta, you WILL lose Yabai functionality, at least on M1 machines.

**Comment by koekeishiya** [comment]
Neither M1 nor Monterey is currently supported. If these notifications annoy you, you can disable them in `System Preferences > Notifications > Yabai (scroll the list) > Allow notifications`
