### ISSUE TITLE
[Feature] Move focus to next monitor if at the edge of screen

### ISSUE THREAD

**Issue by albert-ying** [koekeishiya/yabai#953]
Say I have two monitors with 4 applications on, with the focus at `a`:

[ **a** | b ] [ c | d ]

I can press `alt`+`right`, which is binded to `yabai -m window --focus east`, to focus on `b` :

[ a | **b** ] [ c | d ]

But if I keep pressing `alt`+`right`, nothing will happen.

It would more intuitive if I can directly move to `c` with the same key bindings.

[ a | b ] [ **c** | d ]

I'm wondering if it is something possible to do.

Thank you!

**Comment by yanzhang0219** [comment]
Suppose your monitor with [c|d] is on the east of the other monitor. You can try this

```
lalt - right : yabai -m window --focus east || \
               yabai -m window --focus $(yabai -m query --windows --display east | \
                                        jq 'map(select(.visible == 1)) | sort_by(.frame.x, .frame.y) | first | .id') || \
```

Explanation: focus the window on the east, if the window is already the east-most (like b in your example), move the focus to the monitor on the east. Then in this monitor, focus on the window on the west-most (i.e., window c in your example).

I use this snippet a lot each day. It's fabulous! 
I have more tricks and convenient bindings like this, if you are interested, feel free to grab it from my [skhdrc](https://github.com/yanzhang0219/dotfiles/blob/master/.config/skhd/skhdrc).

**Comment by albert-ying** [comment]
> Suppose your monitor with [c|d] is on the east of the other monitor. You can try this
> 
> ```
> alt - right : yabai -m window --focus east || \
>                yabai -m window --focus $(yabai -m query --windows --display east | \
>                                         jq 'map(select(.visible == 1)) | sort_by(.frame.x, .frame.y) | first | .id') || \
> ```
> 
> Explanation: focus the window on the east, if the window is already the east-most (like b in your example), move the focus to the monitor on the east. Then in this monitor, focus on the window on the west-most (i.e., window c in your example).
> 
> I use this snippet a lot each day. It's fabulous!
> I have more tricks and convenient bindings like this, if you are interested, feel free to grab it from my [skhdrc](https://github.com/yanzhang0219/dotfiles/blob/master/.config/skhd/skhdrc).

It works perfectly for me! Thank you so much for sharing!
