### ISSUE TITLE
Known issues with Telegram?

### ISSUE THREAD

**Issue by 24unix** [koekeishiya/yabai#957]
I just switched my main Display from float to bsp, all works as expected, but Telegram is just ignored.

It pops up floating over my e.g. Safari.

**Comment by kvndrsslr** [comment]
Works fine for me. On another note I have the problem that sometimes (very seldom) apps are just not picked up by yabai on launch. Quitting and relaunching the app usually fixes the problem immediately.

**Comment by Clansty** [comment]
I have the same problem. In my case, all the applications started ealier than yabai cannot be managed. So the solution for me is to start these applications after yabai. I added this to `.yabairc`

```bash
ps -e | grep Telegram | grep -v grep || (open /Applications/Telegram.app && sleep 3 && osascript -e 'tell application "Finder" to set visible of process "Telegram" to false')
```

But I think "applications started before yabai cannot be managed" is a bug and should be fixed

**Comment by koekeishiya** [comment]
Upgrade to v4.0.0. If you still have the problem, stop the brew service and run manually using `yabai --verbose` and you will see the reason why it is ignored in the startup logs.

**Comment by kvndrsslr** [comment]
The current version of telegram is now actually not playing nicely with yabai for me - wonder if anyone else experiences this?

```
EVENT_HANDLER_APPLICATION_LAUNCHED: Telegram (81218) is not finished launching, subscribing to finishedLaunching changes
-[workspace_context observeValueForKeyPath:ofObject:change:context:]: Telegram (81218) finished launching
application_observe: error 'kAXErrorCannotComplete' for application 'Telegram' and notification 'kAXCreatedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Telegram' and notification 'kAXFocusedWindowChangedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Telegram' and notification 'kAXWindowMovedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Telegram' and notification 'kAXWindowResizedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Telegram' and notification 'kAXTitleChangedNotification'
application_observe: error 'kAXErrorCannotComplete' for application 'Telegram' and notification 'kAXMenuOpenedNotification'
EVENT_HANDLER_APPLICATION_LAUNCHED: could not observe notifications for Telegram (81218) (1)
```

**Comment by carlos-gtz** [comment]
@kvndrsslr Yes, the same is happening with me. Telegram can't be recognized as a window.

```
$ yabai -m query --windows --window
could not retrieve window details.
```

**Comment by zakroma** [comment]
Same thing here, telegram is being ignored by yabai and doesnt appear in a window list after `yabai -m query --windows`:(

**Comment by kalamov** [comment]
Temporarily installed manually the old version 9.1 (238837), link - https://install.appcenter.ms/users/keepcoder/apps/telegram-swift/distribution_groups/public

**Comment by zakroma** [comment]
Great news everyone!

Telegram 9.1.239550 fixes the problem and is getting recognized by yabai!

**Comment by zakroma** [comment]
> > Great news everyone!
> > Telegram 9.1.239550 fixes the problem and is recognized by yabai!
> 
> @zakroma how did you get the last version? I don't see it in brew...

[here](https://install.appcenter.ms/users/keepcoder/apps/telegram-swift/distribution_groups/public)

**Comment by armand1m** [comment]
I really just pressed the `update telegram` button in their UI
