### ISSUE TITLE
Is it possible to have conditional statements or loops?

### ISSUE THREAD

**Issue by CatalinVoineag** [koekeishiya/yabai#962]
Hi.

I've been using yabai for a good while now, just configured some small keybindings like swap and focus windows/spaces.

I want to run a set of commands based on a condition. So I want to change the layout of the space to float and arrange all the windows on the screen within a grid. **Only** if there are 4 windows open in a space.

Apologies for the ugly code, I'm just starting to figure out how yabai works:

```
ctrl + cmd - p : yabai -m space --layout float;\
                 yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .frame.x, .frame.y, .id) | map(select(.visible == 1 and .subrole != \"AXUnknown\")) | reverse | nth(index(map(select(.focused == 1))) - 1).id")";\
                 yabai -m window --grid 2:6:0:0:2:1;\
                 yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .frame.x, .frame.y, .id) | map(select(.visible == 1 and .subrole != \"AXUnknown\")) | reverse | nth(index(map(select(.focused == 1))) - 1).id")";\
                 yabai -m window --grid 2:6:0:1:2:1;\
                 yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .frame.x, .frame.y, .id) | map(select(.visible == 1 and .subrole != \"AXUnknown\")) | reverse | nth(index(map(select(.focused == 1))) - 1).id")";\
                 yabai -m window --grid 1:6:2:1:2:1;\
                 yabai -m window --focus "$(yabai -m query --windows | jq -re "sort_by(.display, .frame.x, .frame.y, .id) | map(select(.visible == 1 and .subrole != \"AXUnknown\")) | reverse | nth(index(map(select(.focused == 1))) - 1).id")";\
                 yabai -m window --grid 1:6:4:1:2:1

```

Logic: 
1. set layout space to float.
2. focus next float window
3. set it into a grid position
4. focus next window and set position within a grid.

This doesn't work perfectly but it breaks when there are no 4 windows in a space. Is it possible to have an if statement in here? And maybe a loop so I can loop through all the windows?

Sorry if this is a stupid question.

**Comment by SxC97** [comment]
I have this working in my [config files](https://github.com/SxC97/dotfiles) but it isn’t very elegant. I have the keycode execute a separate shell script, stored in my `~/.scripts` directory. 

The shell script then runs a `yabai -m query` command and stores the result. Then, an if statement executes the appropriate command.

It’s probably slower than executing it directly in the `.skhdrc`, but it’s the only way I could get it working.

**Comment by CatalinVoineag** [comment]
Thank you. That does sound like a good idea. I'll give it a go 👍🏻
