### ISSUE TITLE
[Feature Request] Yabai without "Displays have separate Spaces" enabled

### ISSUE THREAD

**Issue by refracts** [koekeishiya/yabai#963]
If this isnt possible could there at least be a way to have window borders without tiling and without "Displays have separate Spaces" on

**Comment by koekeishiya** [comment]
Unlikely to happen in the near future. If/when I decide to stop supporting all the older versions of macOS, this can be looked into again.

**Comment by 24unix** [comment]
@refracts I had my issues with separate spaces as well. With Total Spaces 2 you can group spaces on displays and achieve the same behavior as before. With a bonus: Other displays stay usable while one is on full screen. It plays quite nicely with yabai.

**Comment by andreicorpo** [comment]
I would also like to see this implemented. 😄

**Comment by koekeishiya** [comment]
This is just not going to happen, sorry.
