### ISSUE TITLE
Dropdown menu hidden behind parent window when with rule layer=above

### ISSUE THREAD

**Issue by leandwo** [koekeishiya/yabai#966]
On MacOS Big Sur 10.14. Repro with the setting:

```sh
yabai -m rule --add app="^System Preferences$" layer=above manage=off
```
The dropdown menu window shows up in fron when layer is not above. Otherwise is looks like this:

![image](https://user-images.githubusercontent.com/13348080/126750645-41509ac7-2fdf-490c-80d2-55581face4f7.png)

**Comment by koekeishiya** [comment]
Resvoled in latest version.
