### ISSUE TITLE
yabai-v3.3.10's 'yabai -m space --destroy' doesn't work with macOS 11.5 (2G71)

### ISSUE THREAD

**Issue by kevinclark** [koekeishiya/yabai#968]
Yabai is able to create new spaces, move between them, and appears to be managing windows correctly. But it can't destroy a space. No messages are written to out or error logs when the command is run. I'm doing it through skhd, but I see the same behavior running the command manually.

**Comment by koekeishiya** [comment]
Works on 10.5 for me. Reinstall the scripting addition.

Sent from my iPhone

On 24 Jul 2021, at 18:18, Kevin Clark ***@***.***> wrote:

﻿

Yabai is able to create new spaces, move between them, and appears to be managing windows correctly. But it can't destroy a space. No messages are written to out or error logs when the command is run. I'm doing it through skhd, but I see the same behavior running the command manually.

**Comment by kevinclark** [comment]
That fixed it, thanks!
