### ISSUE TITLE
How to best achieve window cycling and symmetric flipping ?

### ISSUE THREAD

**Issue by chogovadze** [koekeishiya/yabai#970]
Hello, thank you very much for Yabai, it is truly an amazing tool! I recently started trying to implement the following two behaviours: 
Cycling window layout within one space 
![Cycle](https://user-images.githubusercontent.com/50154112/126961042-e0e79072-7891-4247-8f1b-b6252d24b9c6.png)

and flipping the window layout symmetrically
![swap](https://user-images.githubusercontent.com/50154112/126961195-4566c964-6756-48b1-9a42-821ef38dcabe.png)

I am uncertain if there is a straightforward method to achieve these 2 behaviours.

**Comment by eramdam** [comment]
You'll want to send the following commands
```
yabai -m space --rotate 90
yabai -m space --mirror y-axis
yabai -m space --mirror x-axis
```

I have these in my [skhd](https://github.com/koekeishiya/skhd) configuration
```
# rotate tree
ctrl + alt + cmd - r : yabai -m space --rotate 90

# mirror tree y-axis
ctrl + alt + cmd - y : yabai -m space --mirror y-axis

# mirror tree x-axis
ctrl + alt + cmd - x : yabai -m space --mirror x-axis
```

**Comment by chogovadze** [comment]
Thanks for the pointers @eramdam! I seemed to have overlooked the "spaces" section while trying to solve this only with "window" commands. For the symmetric flipping `yabai -m space --mirror y-axis` is exactly what I was looking for. However, the cycling behaviour is not the same as "rotate". As the former keeps the same layout and cycles the applications whereas the latter cycles the layout itself. I hope this figure illustrates my point: 
![Untitled Diagram](https://user-images.githubusercontent.com/50154112/127124543-2189bbb4-5d77-46ef-a468-f6ee22d33c92.png)

**Comment by koekeishiya** [comment]
In your specific case of 3 windows, you can use the following command to perform a cycling as you descibe, regardless of which window is currently focused. Note that this does not scale to layouts with more/less windows without modifications.

```
# cycle clockwise
yabai -m window first --swap next && yabai -m window first --swap last

# cycle counter-clockwise
yabai -m window first --swap last && yabai -m window first --swap next
```

**Comment by chogovadze** [comment]
Thank you very much @koekeishiya! The command works perfectly for my use case.

**Comment by koekeishiya** [comment]
The following bash scripts should cycle windows in the given direction regardless of how many windows are in the layout.

cycle_clockwise.sh:
```
#!/bin/bash

win=$(yabai -m query --windows --window last | jq '.id')

while : ; do
    yabai -m window $win --swap prev &> /dev/null
    if [[ $? -eq 1 ]]; then
        break
    fi
done
```

cycle_counterclockwise.sh
```
#!/bin/bash

win=$(yabai -m query --windows --window first | jq '.id')

while : ; do
    yabai -m window $win --swap next &> /dev/null
    if [[ $? -eq 1 ]]; then
        break
    fi
done
```

**Comment by kvndrsslr** [comment]
If you would like to define the sort order different from the natural sort order of the bsp, you could use this script.

swaprotate_space_windows.sh

#!/bin/bash
[[ "$1" == "--reverse" ]] || reverse="| reverse "
yabai -m query --windows --space  | \
jq -re '
  map(select(.minimized != 1))
  | sort_by(.display, .frame.x, .frame.y, ."stack-index", .id)
  '"$reverse"'
  | first as $first
  | map( $first.id, .id )
  | .[]' | \
tail -n +3 | \
xargs -n2 sh -c 'yabai -m window $1 --swap $2' sh
You can run this with --reverse to reverse your sort order and of course you can fiddle with the jq filters to get your desired order.

**Comment by HosAkh** [comment]
Hi, 
I tried these two in my `skhdrc` and restarted yabai but it didn't work. Am I doing something incorrectly? No other shortcuts assigned to these keys

```
# cycle_clockwise cycle through windows
fn - c : /Users/username/.config/skhd/CustomScripts/cycle_clockwise.sh

# cycle clockwise
fn - s : yabai -m window first --swap next && yabai -m window first --swap last
```


thank you
