### ISSUE TITLE
Swap windows across displays

### ISSUE THREAD

**Issue by jack836** [koekeishiya/yabai#972]
Is it possible to move `window-1` from `display-1` to `display-2` so that it occupies the position of any window on `display-2` (say `window-2`)  thereby pushing `window-2` back to `display-1` (to occupy the original position of `window-1`).  In simple terms, it is to swap a window with any other window on a different display. I searched the issues but didn't find any match, and sorry if I missed one.

**Comment by koekeishiya** [comment]
The `swap` command supports this, yes: `yabai -m window --swap <target window>`

If you have `yabai -m config mouse_drop_action swap` set, you can also do this operation using the mouse by dragging a window and dropping it in the center region of the target window.
