### ISSUE TITLE
Center app in space if there is only one running

### ISSUE THREAD

**Issue by nadeemkhedr** [koekeishiya/yabai#975]
Have a question

Have no idea if this is possible or not. I have an ultrawide screen, I almost never want an app to take the full screen. 
Is there a way to center the app and set width if there is only one app running in that space? 

I end up running a dummy terminal just for the resize

**Comment by donaldguy** [comment]
I also have an ultrawide (49"), and am cheating to the middle 3rd like this in my `.yabairc`

```bash
# 32:9 resolution should constrain managed area to middle third (or so)
if yabai -m query --displays --display 1 | jq -e '.frame | (.w)/(.h) | round == 4' > /dev/null; then
        yabai -m config left_padding                400
        yabai -m config right_padding              400

        # other stuff for 32:9 specific setup
        # yabai -m rule --add title=MiniPlayer manage=off
else
        yabai -m config left_padding               12
        yabai -m config right_padding              12
fi
```

leaving the wings for stuff outside yabai's control

I feel like this is about right for 2+ windows
<img width="100%" alt="image" src="https://user-images.githubusercontent.com/43136/128096217-d8c567c8-02ee-4aa6-b340-77eb6de42e60.png">

and is at least ~better for 1 window:
<img width="100%" alt="image" src="https://user-images.githubusercontent.com/43136/128096281-bc974887-8e08-4d6c-8d0b-fb5a95b6f611.png">

---

its conditionalized cause its on a laptop, and I want to go back to (nearly) fullscreen when using internal monitor.

As such it probs should (also) be under a  `yabai -m signal --add event=system_woke action=` dealio (and/or display_resized), but I need to figure out splitting my yabairc into functions/scripts/multiple entrypoints/whatever still

--

if you wanted to go further in when there is only one window in a space I think that would be possible to hang off `window_focused` (or a more targeted set of window tiling, untiling events)  with a callout to ~ `if yabai -m query --windows --display 1 | jq -ec ' map(select(.visible == 1 and .floating == 0)) | length == 1' > /dev/null; then : tighter constraints ;fi` or so

**Comment by nadeemkhedr** [comment]
@donaldguy thanks so much man, i ended up finding a solution very similarly to what you wrote, just needed to add events for when application is created and terminated

`yabairc`
```
yabai -m signal --add event=application_launched action="~/.config/yabai/centerOneApp.sh"
yabai -m signal --add event=application_terminated action="~/.config/yabai/centerOneApp.sh"
```

`centerOneApp.sh`
```
#!/usr/bin/env bash

if yabai -m query --windows --display 1 | jq -ec ' map(select(.visible == 1 and .floating == 0)) | length == 1' > /dev/null; then 
  yabai -m config left_padding 600
  yabai -m config right_padding 600
else
  yabai -m config left_padding 12
  yabai -m config right_padding 12
fi

```

In the end it felt very laggy when having these scripts, so ended up removing them, just shared if anyone wanted to find something similar

**Comment by donaldguy** [comment]
Hey @nadeemkhedr 

I just noticed the existence in the man page* (and verified function of):


>  Space
>    General Syntax
>        yabai -m space `[<SPACE_SEL>]` `<COMMAND>`
> ...
> --padding `abs|rel:<top>:<bottom>:<left>:<right>`
>            Padding added at the sides of the selected space.
> --toggle **padding**|gap|mission-control|show-desktop
>            Toggle space setting on or off for the selected space.

This is possibly interesting for two to three reasons:

1. The ability to do `yabai -m space --padding` to operate on only the current space, without having to do a separate query for what that is
2. The option for relative spacing so, e.g. you might bind `yabai -m space --padding rel:0:0:300:300` and `yabai -m space --padding rel:0:0:-300:-300`  to hotkeys 

I bolded that last toggle but I'm not sure its actually all that useful, since it toggles all padding (both `-m config` derived and otherwise, though seems to still respect `-m config external_bar` on top and bottom) ; but idk might still be worth knowing about if/when there are the rare occasions you _do_ want stuff full screen 

*Technically I noticed in in tab completions from https://github.com/Amar1729/yabai-zsh-completions, but then looked at man page

**Comment by Liquidmantis** [comment]
I’m out of the house and can’t post much right now, but I have a “zen mode” setting that centers a window or stack on a per space basis. 
See from here down for the simple logic

https://github.com/Liquidmantis/dotfiles/blob/1e94792fe78bfaf429a9812a9bdabc13650fb6eb/hammerspoon/functions.lua#L164

**Comment by donaldguy** [comment]
> but I need to figure out splitting my yabairc into functions/scripts/multiple entrypoints/whatever still

I finally found the time & energy to do this (making my config kinda ~python module style), ironically about 4 days before I go on a roadtrip away from my monitor for 2 months, but oh well.

See:
https://github.com/donaldguy/dotfiles/blob/749c564f6b5f8f1d22ecc7f593cad5c8d80f8bd0/executable_dot_yabairc

---

In particular, here is the portion (almost the whole file so far) producing (not instant transitions but oh well) behavior of:
 - hard center 1 window, 
 - semi-center 2 to 4 windows
 - don't center >4

while ignoring windows for hidden applications<sup>1</sup> (which `COMMAND_QUERY_WINDOWS` report as `"visible": 1` at present for me)

```zsh
 #!/usr/bin/env zsh

declare -r YABAIRC=$0

function get_display_aspect_ratio {
  case $(yabai -m query --displays --display mouse | jq '.frame | (.w)/(.h) | round') in
    (2) echo "16:9" ;;
    (4) echo "32:9" ;;
    (*) echo "something:whacky" ;;
  esac
}

function get_space_num_visible_windows {
 yabai -m query --windows --space mouse | \
   jq 'map(select(.visible == 1 and .floating == 0)) |
    # deal with how hidden applications apparently still
    # have "visible" windows
    if all(.split == "none") then
      1
    else
      map(select(.split != "none")) | length
    end'
}

function maybe_center_space {
  if [[ $(get_display_aspect_ratio) == "32:9" ]]; then
    case $(get_space_num_visible_windows) in
      (<0-1>) yabai -m space --padding abs:6:4:800:800 ;;
      (<2-4>) yabai -m space --padding abs:6:4:400:400 ;;
      (*)     yabai -m space --padding abs:6:4:6:6     ;;
    esac
  else
    yabai -m space --padding abs:6:4:4:4
  fi
}

# ...

function config_signals {
  for signal (
    application_launched application_terminated
    application_hidden application_visible
    window_created window_destroyed window_minimized window_deminimized
    space_changed
    display_resized system_woke
  ); do
    yabai -m signal --add event=$signal \
      action="$YABAIRC maybe_center_space" \
      label="maybe_center_space-on-$signal"
  done
}

function config_main {
  # ...
  yabai -m config layout                       bsp
  yabai -m config window_gap                   06
  
  maybe_center_space
  config_signals
}

if [[ $# == 0 ]]; then
  config_main
else
  $1
fi
```

<sup>1</sup> I have been preferring hiding to minimizing of late: cause its faster, but mostly cause [Jean-Tinland/simple-bar](https://github.com/Jean-Tinland/simple-bar) keeps them as icon-only presence that way—likely exactly because they remain `"visible": 1`

**Comment by nadeemkhedr** [comment]
I ended up writing a script in js to toggle zen mode, that is basically toggle between padding 700 left/right and padding 15

the script looks like this, it was written using [script kit](https://www.scriptkit.com/)

```javascript
const selectedSpace = exec(
  `yabai -m query --spaces | jq '.[] | select(.visible==1) | .label'`,
  { silent: true }
).trim()
const rightPadding = exec(
  `yabai -m config --space ${selectedSpace} right_padding`,
  { silent: true }
).trim()

if (rightPadding === '15') {
  exec(`yabai -m space --padding abs:15:15:700:700`, {
    silent: true,
  })
} else {
  exec(`yabai -m space --padding abs:15:15:15:15`, {
    silent: true,
  })
}

```

and then in karabiner bound a key to execute that script

**Comment by Holer90** [comment]
Very similar to the above post by @nadeemkhedr I make a "toggle zen mode" script (in `bash` instead of `js`), which can be used directly with `skhd`, and updated the query-syntax for `yabai-v4.0.0`

```
ctrl + shift - z : current_space=$(yabai -m query --spaces | jq '.[] | select(."is-visible" == true) | .index'); \
	if [[ $(yabai -m config --space $current_space right_padding) -eq 10 ]]; then; \
		yabai -m space --padding abs:10:10:450:450; \
	elif [[ $(yabai -m config --space $current_space right_padding) -eq 450 ]]; then; \
		yabai -m space --padding abs:10:10:900:900; \
	else; \
		yabai -m space --padding abs:10:10:10:10; \
	fi
```

**Comment by beatslikeahelix** [comment]
For anyone who comes across this later, here's a python 3.9 script to calculate what horizontal pad will yield a specified resolution. Then you can put the pad values in @Holer90 's bash script above & profit.
```python
from dataclasses import dataclass, asdict


@dataclass
class ResSpecs:
    monitor_x: int
    monitor_y: int
    tb_pad: int
    desired_ratio: tuple
    menubar: int


def get_LR_pad(
    monitor_x: int, monitor_y: int, tb_pad: int, desired_ratio: tuple, menubar: int = 24
) -> int:
    height = monitor_y - menubar - 2*tb_pad
    x_component, y_component = desired_ratio
    width = round((height / y_component) * x_component)
    lr_pad = round((monitor_x - width) / 2)
    print(f"{desired_ratio} : {lr_pad}")


if __name__ == "__main__":
    resolutions = [(16,9), (3,2), (4,3), (5,4), (1,1)]
    # change according to your display resolution, top & bottom pad & whether menubar is present
    res_specs = [ResSpecs(3440, 1440, 12, res, 24) for res in resolutions]
    for spec in res_specs:
        get_LR_pad(**asdict(spec))
```
Output:
```bash
(16, 9) : 482
(3, 2) : 676
(4, 3) : 792
(5, 4) : 850
(1, 1) : 1024
```

**Comment by maxpetretta** [comment]
Sharing my solution, as the above answers did not work immediately for me:

```
# ~/.config/yabai/yabairc

...
yabai -m signal --add event=window_created action="~/.config/yabai/three-columns.sh"
yabai -m signal --add event=window_destroyed action="~/.config/yabai/three-columns.sh"
...
```

```
# ~/.config/yabai/three-columns.sh  (Remember to chmod +x the file)

windows=$(yabai -m query --windows --display 1 | jq '[.[] | select(."is-visible"==true and ."is-floating"==false)] | length')

if [[ $windows == 1 ]]; then
  yabai -m config left_padding 1713
  yabai -m config right_padding 1713
  yabai -m space --balance
elif [[ $windows == 2 ]]; then
  yabai -m config left_padding 849
  yabai -m config right_padding 849
  yabai -m space --balance
elif [[ $windows == 3 ]]; then
  yabai -m config left_padding 15
  yabai -m config right_padding 15
  yabai -m space --balance
fi
```

This script overrides the default behavior for the first two windows opened on my ultrawide monitor (5140x1440), and returns to the bsp layout afterwards.  It's slower than I would like, but making that trade-off for now.

**Comment by fabiankohlhaas** [comment]
Hier is another version of the script, that works as a toggle: 

```bash
#!/bin/bash
# requiers jq: $ brew install jq

# Path to temp flag file
flag_file="/tmp/yabai_center_window_flag"

# Query for the ammount of windows on space
window_count=$(yabai -m query --windows --space | jq 'length')

# Check if flag exists
if [ -f "$flag_file" ]; then
    # If flag exists restore default
    yabai -m space --padding abs:12:12:12:12
    rm "$flag_file"
else
    # Center window
    if [ "$window_count" -eq 1 ]; then
        yabai -m space --padding abs:12:12:450:450
        touch "$flag_file"
    else
        yabai -m space --padding abs:12:12:12:12
    fi
fi
```
