### ISSUE TITLE
Unable to tile Android emulator provided by Android studio

### ISSUE THREAD

**Issue by jaideeprana** [koekeishiya/yabai#977]
The name of the emulated app is `qemu-system-x86_64`.

PFA screenshots for reference:
<img width="2048" alt="Screenshot 2021-08-02 at 7 34 14 PM" src="https://user-images.githubusercontent.com/3875065/127874223-59860ff3-bc94-49a8-872b-1facbbbcb903.png">

<img width="1589" alt="Screenshot 2021-08-02 at 7 36 03 PM" src="https://user-images.githubusercontent.com/3875065/127874433-4d7a8ed6-ec17-44f9-a9b0-45c71aac3ab5.png">

**Comment by koekeishiya** [comment]
Does it not tile even if you add a rule to match that name and add the `manage=on` property?

**Comment by jaideeprana** [comment]
Sorry for the late reply, tried that but didn't work :(
