### ISSUE TITLE
Having two side-by-side stacks of windows.

### ISSUE THREAD

**Issue by karrot42** [koekeishiya/yabai#98]
Once upon a time I used a tiling window manager called *ratpoison* that only had one desktop (space?) and so you could have all of your windows be full-size and then cycle through them, or you could split up the screen with windows, and there would be some windows that were effectively behind other ones that.  There were windows within the space that you couldn't see.

Basically I could split the screen in two halves (side-by-side) and cycle through windows on either side as I saw fit, and I'd like to accomplish this with yabai.

There was a mode I was using in ChunkWM `chunkc tiling::desktop --layout monocle` which would kind of accomplish this, but I'd like to have basically this with two sets of windows side-by-side.

Thank you much for any help, and if anything is unclear I can write more, I was just trying to spare anyone a long post.

**Comment by dominiklohmann** [comment]
Best you can do is probably enable autobalance for the space you wish to do this on and keep the first split vertical and then all other splits horizontal (can be achieved with some signals, queries and commands). Here's a screenshot of the layout I'm thinking off:

![image](https://user-images.githubusercontent.com/4488655/60772752-191bd280-a0fb-11e9-9a43-9490c3e53725.png)

If you want to overlap the windows to the right, you will have to use floating mode and use the window grid to achieve this. There currently is only zoom-parent and zoom-fullscreen, but no zoom-to-overlap-this-specific-parent-window or whatever you'd need there.

**Comment by karrot42** [comment]
Ah, thank you for confirming it isn't possible to do.  Saved me a lot of trial-and-error.

**Comment by koekeishiya** [comment]
This reminds me of the monocle node concept I tested in kwm in the early days.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by karrot42** [comment]
> This reminds me of the monocle node concept I tested in kwm in the early days.
> 
> Sent with [GitHawk](http://githawk.com)

Am I correct in seeing that monocle mode is not in Yabai (though it is ChunkWM)?

**Comment by koekeishiya** [comment]
Correct. There is no monocle in yabai, yet. I personally didn’t like the version implemented in chunkwm and so I try to iterate on solutions rather than blindly copying an existing one. I like to think that I can do better now that I am more experienced.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by karrot42** [comment]
Totally understand.

To me, monocle mode is a better version of zoom fullscreen and zoom parent-mode (actually I can't tell the difference between those two things) because it has the same effect while allowing you to cycle through all the windows in fullscreen very quickly.

Just giving you an example of my use-case in case it helps to give you an idea of to implement it.

**Comment by koekeishiya** [comment]
I might look into something like this in the future, but no promises. For regular monocle style setup look into the comment made by @dominiklohmann in #83
