### ISSUE TITLE
Managing rule not working properly

### ISSUE THREAD

**Issue by florian-str** [koekeishiya/yabai#981]
I was trying to add an exception for the system preferences. 
The rule I used is ```yabai -m rule --add app="Systemeinstellungen" title=".+" manage=off``` (Systemeinstellungen = System Preferences). If I remove the title attribute, it gives me an error, so I have to search for all titles using regex. The preferences window stays tiled. Running it in verbose mode gives me the following output:
```
EVENT_HANDLER_APPLICATION_LAUNCHED: Systemeinstellungen (44555) is not finished launching, subscribing to finishedLaunching changes
process_is_observable: AccountProfileRemoteViewService (44556) was marked as xpc service! ignoring..
-[workspace_context observeValueForKeyPath:ofObject:change:context:]: Systemeinstellungen (44555) finished launching
EVENT_HANDLER_APPLICATION_LAUNCHED: Systemeinstellungen (44555)
window_manager_create_and_add_window: Systemeinstellungen 6208
EVENT_HANDLER_APPLICATION_FRONT_SWITCHED: Systemeinstellungen (44555)
EVENT_HANDLER_WINDOW_TITLE_CHANGED: iTerm2 6190
EVENT_HANDLER_WINDOW_RESIZED: iTerm2 6190
EVENT_HANDLER_WINDOW_MOVED: Systemeinstellungen 6208
EVENT_HANDLER_APPLICATION_DEACTIVATED: iTerm2
EVENT_HANDLER_APPLICATION_ACTIVATED: Systemeinstellungen
```

If I query the windows, it returns:

```json
{
	"id":6208,
	"pid":44555,
	"app":"Systemeinstellungen",
	"title":"Systemeinstellungen",
	"frame":{
		"x":0.0000,
		"y":552.0000,
		"w":763.0000,
		"h":679.0000
	},
	"level":0,
	"role":"AXWindow",
	"subrole":"AXStandardWindow",
	"movable":1,
	"resizable":0,
	"display":1,
	"space":1,
	"visible":1,
	"focused":0,
	"split":"horizontal",
	"floating":0,
	"sticky":0,
	"minimized":0,
	"topmost":0,
	"opacity":1.0000,
	"shadow":1,
	"border":0,
	"stack-index":0,
	"zoom-parent":0,
	"zoom-fullscreen":0,
	"native-fullscreen":0
}
```

I'd appreciate your help solving the issue.

**Comment by Akhilkrishnauk** [comment]
not an expert here or anything but using
yabai -m rule  --add app="^AppName$" manage=off will not tile the app
idk what ^$ does but if its there, it generally works

**Comment by florian-str** [comment]
Thanks for trying to help, but it didn't work. The ```^``` means, that the app name starts with that phrase and the ```$``` means the name ends with that. It is supposed to make the rules more precise, but has no effect on the issue I'm currently facing.

**Comment by Akhilkrishnauk** [comment]
> Thanks for trying to help, but it didn't work. The ```^``` means, that the app name starts with that phrase and the ```$``` means the name ends with that. It is supposed to make the rules more precise, but has no effect on the issue I'm currently facing. 

Ooh!! Ok . I was having other issues with my yabai as well. For somereason it stopped padding my ubersicht bar and  stopped showing limelight's border. I dont know if its something wrong in my config or itsa bug after updating macos.. so im kinda confused about posting it here as an issue

**Comment by DennisFeldbusch** [comment]
I'm having the same issue! My Systemeinstellungen rule isn't working, too.

**Comment by dubf** [comment]
I'm having the same issue. System Preferences refuses to cooperate with yabai. 

Coincidentally, I also have my Mac in German locale. Might that perhaps be part of the problem? I tried calling the app both in German and in English, but it didn't make a difference.

**Comment by koekeishiya** [comment]
See #1125
