### ISSUE TITLE
Balance space over one axis only

### ISSUE THREAD

**Issue by koschtschei** [koekeishiya/yabai#985]
Hey there,

thanks for this awesome tool!

I'm wondering if there is any way to balance a space over one axis only? Something equivalent to
```
yabai -m space --balance (x-axis | y-axis)
```

Same question for default split ratios. Something equivalent to
```
yabai -m config split_ratio (x-axis | y-axis) <FLOAT_SEL>
```

#### Background

While working with linux I make heavy use of dwm. At the moment im trying to simulate a subset of dwm behaviour by implementing dwm style commands with simple bash scripts bound to some hot keys via skhd. Even if yabai is aiming on bsp only I'm impressed by the flexible and robust nature of the yabai messaging interface.

Cheers

**Comment by koekeishiya** [comment]
This is not possible right now, but would be fairly trivial to implement.

Sent from my iPhone

On 16 Aug 2021, at 19:34, robert-michael ***@***.***> wrote:

﻿

Hey there,

thanks for this awesome tool!

I'm wondering if there is any way to balance a space over one axis only. Something like

yabai -m space --balance <x-axis | y-axis>

Background

While working with linux I make heavy use of dwm. At the moment im trying to simulate a subset of dwm behaviour by implenting dwm style commands with simple bash scripts bound to some hot keys via skhd. Even if yabai is aiming on bsp only I'm impressed by the flexible and robust nature of the yabai messaging interface.

Cheers

**Comment by robert-michael** [comment]
Thanks for the quick response. I would still be interested in such a feature :)

Cheers
