### ISSUE TITLE
Can't interact with pop ups when window is set to layer=above

### ISSUE THREAD

**Issue by rosenpin** [koekeishiya/yabai#987]
### Description
When trying to open a dialog in a floating window using the following rule for example 
`yabai -m rule --add app="System Preferences" sticky=on manage=off grid=12:15:8:2:5:5 layer=above`  
You can't interact with the dialog. This seems to be because when a window is set to `layer=above` it is set to be above even its own pop ups/dialogs.   
I believe this is unwanted behavior, as it basically breaks some important functionality of `layer=above` windows 

### Expected behavior
When opening a "layer=above" window, it will appear above all other windows.
But when opening a popup inside said window, the popup will be shown above the aforementioned window 

### Actual behavior
The popup of the same applications ends up "hiding" behind the original window, making the popup impossible to interact with.

### Example
https://user-images.githubusercontent.com/5289630/130357209-67286e7d-c059-48a9-b7d3-4c196179f5bf.mp4

In the video you can first see a floating window with `layer=above` set, I can't interact with its application selection pop up as it opens behind the floating window.

Then I toggle the window's `sticky`, `topmost` and `float` fields, in which point I can normally interact with the popup

**Comment by TheFoolishPupil** [comment]
I see this same behaviour when using `yabai -m config window_topmost on`. It's a shame because the feature is quite useful but breaks usability of some software that I need to use.

**Comment by koekeishiya** [comment]
Fixed in v6.0.0 #1887
