### ISSUE TITLE
How to focus on a specific space within a display?

### ISSUE THREAD

**Issue by mduboule** [koekeishiya/yabai#988]
Hi and thank you so much for this great software, it's been improving my workflow tremendously.

I wasn't able to spot a solution in the (very detailed) wiki or in the various config files I looked through for the way I'd like to set it up.

I'm trying to assign a shortcut to focus on a specific space on my central monitor (display 2) no matter how many spaces there are on my laptop monitor (display 1).

And sorry if I'm missing on a simple solution. Or does it need a script to calculate the number of spaces in display 1 and create a new index for assigning shortcuts related to display 2? I wouldn't know how to go about writing something like that.

If you could point me to the right direction that'd be really awesome. Many thanks in advance!

I'm on High Sierra with Yabai 3.3.10 and skhd 0.3.5.

**Comment by koekeishiya** [comment]
See my comment here: https://github.com/koekeishiya/yabai/issues/670#issuecomment-698871253

**Comment by mduboule** [comment]
Ah missed that previous post – your solution works like a charm! Thank you so much.
