### ISSUE TITLE
Feature Request: active_window_opacity for terminals with commands or processes running

### ISSUE THREAD

**Issue by yorhodes** [koekeishiya/yabai#989]
I love using yabai to manage terminal windows across a bunch of different codebases and services. It would be cool if multiple terminals could have the active window opacity simultaneously.
![Screen Shot 2021-08-24 at 4 39 25 PM](https://user-images.githubusercontent.com/3020995/130703688-34bc3acd-2f01-42fa-820e-07f4536a6237.png)

**Comment by luardemin** [comment]
Have you tried using rules in your config file? Setting something like `yabai -m rule app="^iTerm$" opacity=1.0` might work.

**Comment by yorhodes** [comment]
good idea
I was thinking specifically an active_window_opacity which somehow detects "active windows" separately from "focused windows"
this is probably out of scope
