### ISSUE TITLE
Fullscreen zoom problem

### ISSUE THREAD

**Issue by xseman** [koekeishiya/yabai#99]
Making window full-screen while it's focused by mouse `focus_follows_mouse autofocus`, it moves it under the last window that was focused by `yabai -m window --focus`.

![output](https://user-images.githubusercontent.com/9111485/60773100-91d15d80-a100-11e9-91b7-ad5f39077cad.gif)

**Comment by dominiklohmann** [comment]
Isn't this the expected behaviour? After all, you only focused the window, but did not raise it.

**Comment by xseman** [comment]
Oh my bad, with `autoraise` it works 👍
