### ISSUE TITLE
macOS 10.14.6 - Firefox 91 is not managed 

### ISSUE THREAD

**Issue by srustamo** [koekeishiya/yabai#990]
Installed the latest with `brew install koekeishiya/formulae/yabai`

Firefox is not being managed. Tried: `yabai -m rule --add app="^Firefox" manage=on` without effect.

Firefox version 91.0.2 (64-bit).

`yabairc` contains this:
```
#!/bin/zsh

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m config window_shadow  float
yabai -m config window_topmost on

yabai -m config layout         bsp
yabai -m config top_padding    5
yabai -m config bottom_padding 5
yabai -m config left_padding   5
yabai -m config right_padding  5
yabai -m config window_gap     5

yabai -m config --space 2 layout float
```

Edit: scripting addition are not installed (SIP not disabled).

**Comment by Inc0n** [comment]
Is firefox the only app in concern here? Are other apps being managed fine?
Please ensure that you have run `brew services start yabai`, and that `yabai` is running.

**Comment by srustamo** [comment]
No, Chrome and Emacs are also in concern. I understand that Emacs is a complicated issue, and Chrome was managed upon yabai install but stopped after a while. I moved to Brave browser, which is managed by yabai OK.

**Comment by Inc0n** [comment]
For Emacs, see if [wiki#tiling-emacs](https://github.com/koekeishiya/yabai/wiki/Tips-and-tricks#tiling-emacs) helps, I uses `d12frosted/emacs-plus/emacs-plus@28`, which has an option `--with-no-titlebar` (see [Emacs-plus#no-titlebar](https://github.com/d12frosted/homebrew-emacs-plus#no-titlebar)), and it is being managed fine.

**Comment by srustamo** [comment]
It looks like I needed to turn off desktop assignment (set it to None as in the attached screenshot) to make Firefox managed.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/749813/132699259-e007757b-091c-47cb-b986-417668b4b405.png">
