### ISSUE TITLE
Information about Stacks

### ISSUE THREAD

**Issue by typkrft** [koekeishiya/yabai#993]
I read through several issues about stacking, but it's possible I missed something. Is there an easy way to discern how many windows are in a specific stack? If not is there a way to get the node? Just thought I would ask in case I'm missing something before I wrote a script to check? Hoping to write a visual stack indicator plugin for sketchybar.

**Comment by typkrft** [comment]
I just realized I can query stack.last and stack.first of a window in a stack.

**Comment by shrik450** [comment]
If you're like me and didn't know how to do this, it's:

```bash
yabai -m query --windows --window stack.first # or stack.last
```
