### ISSUE TITLE
The drop-down menu is not working properly

### ISSUE THREAD

**Issue by QuarterHeaven** [koekeishiya/yabai#995]
![image](https://user-images.githubusercontent.com/41909950/131763547-308c720c-b0d0-4624-b614-c9d44d02313f.png)
like this kind of menu, when I click it, it will hidden behind the father menu.
![111](https://user-images.githubusercontent.com/41909950/131763745-a4dbaad5-1a8c-458f-b238-cd5440c4dc70.gif)

**Comment by johnmain** [comment]
This happens in Firefox as well. 
![Screen Shot 2021-11-19 at 12 09 23 AM](https://user-images.githubusercontent.com/2589334/142568462-80e05ada-05f8-4baa-85df-d43b5c1057a9.png)
Steps:
With Bookmark menu bar enabled
Add a folder with a few Book marks
Open the folder and rightclick on a book mark.

**Comment by joshtwo** [comment]
I've had similar issues for a while, especially in Firefox. I've had to set several apps to `manage=off` to work around it, such as Finder.

**Comment by koekeishiya** [comment]
Should be fixed in latest version.
