### ISSUE TITLE
bug: `env USER is not set!...`

### ISSUE THREAD

**Issue by babygau** [koekeishiya/yabai#996]
Hi, 
`yabai` somehow is broken after I upgrade macOS to 11.5.2. FYI, I'm using Karabiner to manage yabai workspace and got a weird error as you can see in the following

<img width="1663" alt="Screen Shot 2021-09-05 at 3 52 53 pm" src="https://user-images.githubusercontent.com/1514823/132117028-de623205-4ef7-457d-968b-3f7f5f2936a4.png">

Run `env -v` give me `USER=babygau`
<img width="1663" alt="Screen Shot 2021-09-05 at 4 09 53 pm" src="https://user-images.githubusercontent.com/1514823/132117380-f7e502e5-26da-4511-8757-684a0f485acb.png">

I tried to reinstall `yabai` but it didn't help

Please let me know if you need any further information that could help.

**Comment by johnnypea** [comment]
I have the same issue. Thanks.

**Comment by babygau** [comment]
@johnnypea are you using 13.6.0? please try 13.5.0 to see if the issue is fixed. After investigation, I think this is more than Karabiner bug. I already filed an issue here.

https://github.com/pqrs-org/Karabiner-Elements/issues/2812
