### ISSUE TITLE
Window shadow comes back after setting wallpaper with pywal

### ISSUE THREAD

**Issue by albert-ying** [koekeishiya/yabai#997]
Hi, I turned off the window shadows in my `.yabairc`. 

```
yabai -m config window_shadow                off
```

However, each time I run `pywal` to set wallpaper (like `wal -i "$WALLPAPER"`), the shadows come back. I had to do `brew services restart yabai` each time to remove the shadow again, which is slow.

Is there any way to fix it? Or is there any easy way to remove the shadow again? (I noticed that the shadow can also be removed by toggling window floating and back)

**Comment by koekeishiya** [comment]
There is nothing stopping you from just running `yabai -m config window_shadow                off` again. No need to restart yabai.

**Comment by albert-ying** [comment]
Ohh thanks! I didn't know that I can use this command outside of the config file.
